import type { ToolGuidanceDetails } from "./tool-guidance";
const l = (tr: string, en: string, de: string, zh: string) => ({ tr, en, de, zh });

export const encodingToolGuidance: Record<string, ToolGuidanceDetails> = {
  "base64-kodlayici": {
    input: l("Kodlama için Unicode metin; çözme için UTF-8 metnini temsil eden Base64 girin.", "Enter Unicode text to encode, or Base64 representing UTF-8 text to decode.", "Unicode-Text zum Kodieren oder Base64 mit UTF-8-Text zum Dekodieren eingeben.", "编码时输入 Unicode 文本；解码时输入表示 UTF-8 文本的 Base64。"),
    method: l("TextEncoder metni UTF-8 baytlarına çevirir. Çözmede Base64 baytları sıkı UTF-8 denetimli TextDecoder ile okunur.", "TextEncoder produces UTF-8 bytes before Base64 encoding. Decoding uses TextDecoder with strict UTF-8 validation.", "TextEncoder erzeugt UTF-8-Bytes für Base64. Beim Dekodieren prüft TextDecoder die UTF-8-Gültigkeit strikt.", "TextEncoder 先生成 UTF-8 字节再进行 Base64 编码。解码时 TextDecoder 严格验证 UTF-8。"),
    output: l("Seçilen yöne göre Base64 metni veya çözülmüş Unicode metni; kaynak ve çıktı bayt ölçümleri gösterilir.", "Depending on direction, the output is Base64 or decoded Unicode text, with source and output byte measurements.", "Je nach Richtung entsteht Base64 oder dekodierter Unicode-Text, ergänzt um Bytekennzahlen für Quelle und Ausgabe.", "按所选方向输出 Base64 或解码后的 Unicode 文本，并显示输入和输出的字节计量。"),
    verification: l("Çay ☕ metnini kodlayıp geri çözün; Ç ve ☕ aynen korunmalıdır. /w== çözülürken UTF-8 hatası beklenir.", "Encode and decode Çay ☕; both Ç and ☕ must survive unchanged. Decoding /w== must fail UTF-8 validation.", "Çay ☕ kodieren und zurückdekodieren; Ç und ☕ müssen erhalten bleiben. /w== muss die UTF-8-Prüfung verletzen.", "将 Çay ☕ 编码后再解码，Ç 与 ☕ 均应保持不变。解码 /w== 时应触发 UTF-8 错误。"),
    boundary: l("Base64 şifreleme değildir. Bu araç UTF-8 metni içindir; rastgele dosya baytlarını metne dönüştürme garantisi vermez.", "Base64 is not encryption. This tool handles UTF-8 text, not arbitrary binary files or image reconstruction.", "Base64 ist keine Verschlüsselung. Das Werkzeug verarbeitet UTF-8-Text, keine beliebigen Binärdateien oder Bildrekonstruktionen.", "Base64 不是加密。本工具处理 UTF-8 文本，不用于任意二进制文件或图片重建。"),
  },
  "url-kodlayici": {
    input: l("Kodlamak için tek bir URI bileşeni veya parametre değeri; çözmek için yüzde kodlu metin girin.", "Enter one URI component or parameter value to encode, or percent-encoded text to decode.", "Eine URI-Komponente oder einen Parameterwert zum Kodieren bzw. Prozentkodierung zum Dekodieren eingeben.", "编码时输入单个 URI 组件或参数值；解码时输入百分号编码文本。"),
    method: l("Kodlama encodeURIComponent, çözme decodeURIComponent ile yapılır; araç adresi ziyaret etmez.", "Encoding uses encodeURIComponent and decoding uses decodeURIComponent; the tool does not visit the address.", "Kodierung erfolgt mit encodeURIComponent, Dekodierung mit decodeURIComponent; die Adresse wird nicht aufgerufen.", "使用 encodeURIComponent 编码、decodeURIComponent 解码；工具不会访问该地址。"),
    output: l("Ayrılmış karakterleri yüzde dizilerine dönüştüren bileşen metni veya bir kez çözülmüş metin üretilir.", "The result is a component with reserved characters escaped as percent sequences, or text decoded once.", "Das Ergebnis enthält als Prozentfolgen maskierte reservierte Zeichen oder einmal dekodierten Text.", "结果是保留字符被转义为百分号序列的组件，或仅解码一次的文本。"),
    verification: l("a+b & page=1 değeri a%2Bb%20%26%20page%3D1 olmalıdır. Geri çözmede + işareti korunmalıdır.", "a+b & page=1 must become a%2Bb%20%26%20page%3D1. Decoding must preserve the original plus sign.", "a+b & page=1 muss a%2Bb%20%26%20page%3D1 ergeben. Beim Zurückdekodieren muss das Plus erhalten bleiben.", "a+b & page=1 应变为 a%2Bb%20%26%20page%3D1。解码后必须保留原加号。"),
    boundary: l("Tam adresi kodlamak : ve / ayraçlarını da değiştirir. Form kodlamasındaki + → boşluk kuralı burada uygulanmaz.", "Encoding a whole address also escapes its colon and slashes. The form-decoding rule plus → space does not apply here.", "Eine vollständige Adresse kodiert auch Doppelpunkt und Schrägstriche. Die Formularregel Plus → Leerzeichen gilt hier nicht.", "编码完整地址也会转义冒号和斜杠。表单解码中加号转空格的规则在此不适用。"),
  },
  "json-csv-donusturucu": {
    input: l("CSV yönünde başlık ve eşit alan sayılı satırlar; JSON yönünde en az bir düz nesne içeren dizi gerekir.", "CSV input needs a header and equal-width records; JSON input must be a nonempty array of flat objects.", "CSV benötigt eine Kopfzeile und gleich breite Datensätze; JSON ein nicht leeres Array flacher Objekte.", "CSV 输入需包含表头及字段数一致的记录；JSON 输入必须是非空的扁平对象数组。"),
    method: l("CSV ayrıştırıcısı tırnakları, kaçışları ve ayırıcıyı dikkate alır. JSON → CSV sütunları alan adlarından oluşturur.", "CSV parsing respects quotes, escapes, and the detected delimiter. JSON → CSV builds columns from object keys.", "CSV-Parsing berücksichtigt Anführungszeichen, Escaping und erkannte Trenner. JSON → CSV erzeugt Spalten aus Objektschlüsseln.", "CSV 解析考虑引号、转义及检测到的分隔符。JSON → CSV 按对象键建立列。"),
    output: l("CSV → JSON hücreleri metin olarak korur. JSON → CSV düz bir tablo üretir; kayıt ve sütun sayıları gösterilir.", "CSV → JSON preserves cells as strings. JSON → CSV produces a flat table; record and column counts are displayed.", "CSV → JSON erhält Zellen als Zeichenfolgen. JSON → CSV erzeugt eine flache Tabelle; Zeilen- und Spaltenzahlen werden angezeigt.", "CSV → JSON 将单元格保留为字符串。JSON → CSV 输出扁平表格，并显示记录和列数。"),
    verification: l("007 kimliği ve tırnak içindeki A,B hücresi korunmalıdır. Başlığı saymadan kayıt sayısını ve sütun eşleşmesini kontrol edin.", "The identifier 007 and the quoted A,B cell must be preserved. Compare record counts excluding the header and check column mapping.", "Die Kennung 007 und die zitierte Zelle A,B müssen erhalten bleiben. Datensätze ohne Header zählen und Spaltenzuordnung prüfen.", "编号 007 和带引号的 A,B 单元格必须保留。记录计数应排除表头，并核对列映射。"),
    boundary: l("İç içe nesneleri önce düzleştirin. İşlem sınırı 10.000 kayıttır; JSON → CSV için 1–500 sütun gerekir. Formül benzeri hücreler korunur.", "Flatten nested objects first. The limit is 10,000 records; JSON → CSV requires 1–500 columns. Formula-like cells receive protection.", "Verschachtelte Objekte zuerst abflachen. Maximal 10.000 Datensätze; JSON → CSV benötigt 1–500 Spalten. Formelartige Zellen werden geschützt.", "请先将嵌套对象扁平化。最多处理 10,000 条记录；JSON → CSV 需有 1–500 列。类似公式的单元格会受到保护。"),
  },
};

export const encodingWorkflows = {
  "base64-kodlayici": l("UTF-8 gidiş-dönüş kontrolü", "a UTF-8 round-trip check", "einer UTF-8-Rückprüfung", "UTF-8 往返核验"),
  "url-kodlayici": l("parametre değerini hedef uygulamaya iletme", "sending the parameter value to its destination", "der Übergabe des Parameterwerts", "向目标应用传递参数值"),
  "json-csv-donusturucu": l("tabloyu hedef sisteme aktarma", "importing the table into its destination", "dem Import der Tabelle ins Zielsystem", "将表格导入目标系统"),
};
