import type { BaseTool } from "./tool-locales";
import type { ToolCategory } from "./tools";

type Four = { tr: string; en: string; de: string; zh: string };

function tool(slug: string, category: ToolCategory, mark: string, title: Four, short: Four): BaseTool {
  return {
    slug, category, mark, title, short,
    description: {
      tr: `${title.tr}, ${short.tr.toLocaleLowerCase("tr-TR")} Hesaplamayı ve dönüşümü açıklanabilir kurallarla cihazınızda yapar; sonuçları kullanmadan önce varsayımları görebilir ve düzenleyebilirsiniz.`,
      en: `${title.en} lets you ${short.en.charAt(0).toLowerCase()}${short.en.slice(1)} It runs with explainable rules on your device and keeps assumptions visible before you use the result.`,
      de: `${title.de}: ${short.de} Die Verarbeitung erfolgt mit nachvollziehbaren Regeln direkt auf Ihrem Gerät; Annahmen bleiben vor der Nutzung sichtbar.`,
      zh: `${title.zh}：${short.zh} 所有处理均使用可解释规则在您的设备上完成，并在使用结果前清楚显示相关假设。`,
    },
    useCases: {
      tr: ["Hızlı ve denetlenebilir sonuç", "Tekrarlanan işleri standartlaştırma", "Sonucu kopyalama veya indirme"],
      en: ["A quick, auditable result", "Standardizing repeat tasks", "Copying or downloading the result"],
      de: ["Schnelles, prüfbares Ergebnis", "Wiederkehrende Aufgaben standardisieren", "Ergebnis kopieren oder herunterladen"],
      zh: ["快速且可审查的结果", "标准化重复任务", "复制或下载结果"],
    },
    steps: {
      tr: ["Alanları gerçek senaryonuza göre doldurun.", "Cihazımda çalıştır düğmesiyle sonucu üretin.", "Varsayımları kontrol edip sonucu aktarın veya indirin."],
      en: ["Fill the fields for your real scenario.", "Use Run on my device to produce the result.", "Review assumptions, then transfer or download the result."],
      de: ["Felder für Ihr Szenario ausfüllen.", "Mit Auf meinem Gerät ausführen das Ergebnis erzeugen.", "Annahmen prüfen und Ergebnis übertragen oder herunterladen."],
      zh: ["根据实际场景填写字段。", "点击在我的设备上运行生成结果。", "检查假设后传递或下载结果。"],
    },
  };
}

export const essentialTools: BaseTool[] = [
  tool("yuzde-degisim-hizli-hesaplayici", "calculation", "E01", { tr: "Yüzde Değişim Hızlı Hesaplayıcı", en: "Quick Percentage Change Calculator", de: "Schneller Prozentänderungsrechner", zh: "快速百分比变化计算器" }, { tr: "İki değer arasındaki artış, azalış ve mutlak farkı doğrudan form alanlarıyla hesaplayın.", en: "Calculate increase, decrease, and absolute difference with direct form fields.", de: "Anstieg, Rückgang und absolute Differenz direkt über Formularfelder berechnen.", zh: "通过直观表单计算两个数值之间的增减幅度和绝对差值。" }),
  tool("indirim-kdv-hesaplayici", "calculation", "E02", { tr: "İndirim ve KDV Hesaplayıcı", en: "Discount & VAT Calculator", de: "Rabatt- & MwSt.-Rechner", zh: "折扣与增值税计算器" }, { tr: "İndirim, vergi matrahı ve ödenecek toplamı ayrı ayrı görün.", en: "See discount, tax base, and payable total separately.", de: "Rabatt, Steuerbasis und Endsumme getrennt anzeigen.", zh: "分别查看折扣、计税基础和应付总额。" }),
  tool("kredi-taksit-hesaplayici", "calculation", "E03", { tr: "Kredi Taksit Hesaplayıcı", en: "Loan Payment Calculator", de: "Kreditratenrechner", zh: "贷款还款计算器" }, { tr: "Aylık taksiti, toplam geri ödemeyi ve faiz yükünü simüle edin.", en: "Simulate monthly payments, total repayment, and interest cost.", de: "Monatsrate, Gesamtrückzahlung und Zinskosten simulieren.", zh: "模拟月供、总还款额和利息成本。" }),
  tool("kira-paylasim-hesaplayici", "calculation", "E04", { tr: "Kira ve Gider Paylaşım Hesaplayıcı", en: "Rent & Expense Splitter", de: "Miet- & Kostenaufteilung", zh: "房租与费用分摊器" }, { tr: "Kira ve ortak giderleri kişi veya ağırlık bazında adil paylaşın.", en: "Split rent and shared expenses fairly by person or weight.", de: "Miete und Nebenkosten fair nach Person oder Gewicht verteilen.", zh: "按人数或权重公平分摊房租和公共费用。" }),
  tool("tarih-sure-hesaplayici", "calculation", "E05", { tr: "Tarih Aralığı Hesaplayıcı", en: "Date Duration Calculator", de: "Datumsdifferenz-Rechner", zh: "日期间隔计算器" }, { tr: "İki tarih arasındaki gün, hafta ve yaklaşık ay süresini bulun.", en: "Find days, weeks, and approximate months between two dates.", de: "Tage, Wochen und ungefähre Monate zwischen zwei Daten ermitteln.", zh: "计算两个日期之间的天数、周数和约数月。" }),
  tool("yas-hesaplayici", "calculation", "E06", { tr: "Yaş Hesaplayıcı", en: "Age Calculator", de: "Altersrechner", zh: "年龄计算器" }, { tr: "Tam yaşı yıl, ay ve gün olarak hesaplayın.", en: "Calculate exact age in years, months, and days.", de: "Genaues Alter in Jahren, Monaten und Tagen berechnen.", zh: "根据出生日期和指定日期，以年、月、日计算准确年龄。" }),
  tool("tarif-olceklendirici", "general", "E07", { tr: "Tarif Ölçeklendirici", en: "Recipe Scaler", de: "Rezept-Umrechner", zh: "食谱份量换算器" }, { tr: "Malzeme miktarlarını porsiyon sayısına göre yeniden ölçekleyin.", en: "Rescale ingredient amounts for a different serving count.", de: "Zutatenmengen für eine andere Portionszahl umrechnen.", zh: "根据新的份数重新换算配料用量。" }),
  tool("maas-saatlik-ucret-donusturucu", "calculation", "E08", { tr: "Maaş ve Saatlik Ücret Dönüştürücü", en: "Salary & Hourly Pay Converter", de: "Gehalts- & Stundenlohnrechner", zh: "薪资与时薪换算器" }, { tr: "Yıllık, aylık ve saatlik brüt ücretleri ortak varsayımlarla karşılaştırın.", en: "Compare annual, monthly, and hourly gross pay with explicit assumptions.", de: "Jahres-, Monats- und Stundenbrutto mit klaren Annahmen vergleichen.", zh: "在明确假设下比较年薪、月薪和时薪。" }),
  tool("birim-fiyat-karsilastirici", "calculation", "E09", { tr: "Birim Fiyat Karşılaştırıcı", en: "Unit Price Comparator", de: "Grundpreisvergleich", zh: "单价比较器" }, { tr: "Farklı paket boyutlarında gerçekten ucuz olan seçeneği bulun.", en: "Find the genuinely cheaper option across different pack sizes.", de: "Die tatsächlich günstigere Option bei verschiedenen Packungsgrößen finden.", zh: "比较不同包装规格，找出真正更便宜的选择。" }),
  tool("rastgele-takim-olusturucu", "general", "E10", { tr: "Rastgele Takım Oluşturucu", en: "Random Team Generator", de: "Zufalls-Teamgenerator", zh: "随机分组器" }, { tr: "İsim listesini dengeli ve tekrarlanabilir takımlara ayırın.", en: "Split a name list into balanced, reproducible teams.", de: "Namenslisten in ausgewogene, reproduzierbare Teams aufteilen.", zh: "将名单随机分成均衡且可复现的小组。" }),
  tool("liste-siralama-temizleme", "text", "E11", { tr: "Liste Sıralama ve Temizleme", en: "List Sort & Cleanup", de: "Listensortierung & Bereinigung", zh: "列表排序与清理" }, { tr: "Satırları doğal sıraya koyun, boşları ve tekrarları temizleyin.", en: "Sort lines naturally while removing blanks and duplicates.", de: "Zeilen natürlich sortieren und leere oder doppelte Einträge entfernen.", zh: "自然排序文本行，并移除空行和重复项。" }),
  tool("kelime-sikligi-analizoru", "text", "E12", { tr: "Kelime Sıklığı Analizörü", en: "Word Frequency Analyzer", de: "Worthäufigkeitsanalyse", zh: "词频分析器" }, { tr: "En sık kullanılan sözcükleri ve metindeki paylarını ölçün.", en: "Measure the most frequent words and their share of the text.", de: "Häufigste Wörter und deren Anteil am Text messen.", zh: "统计高频词及其在文本中的占比。" }),
  tool("okunabilirlik-on-analizi", "text", "E13", { tr: "Hızlı Okunabilirlik Ön Analizi", en: "Quick Readability Preflight", de: "Lesbarkeits-Schnellcheck", zh: "可读性快速预检" }, { tr: "Uzun cümleleri, yoğun paragrafları ve teknik sözcükleri işaretleyin.", en: "Flag long sentences, dense paragraphs, and technical wording.", de: "Lange Sätze, dichte Absätze und Fachsprache markieren.", zh: "标记长句、密集段落和技术术语。" }),
  tool("e-posta-listesi-temizleyici", "text", "E14", { tr: "E-posta Listesi Temizleyici", en: "Email List Cleaner", de: "E-Mail-Listenbereinigung", zh: "电子邮件列表清理器" }, { tr: "Adresleri ayıklayın, doğrulama ön kontrolü yapın ve tekrarları kaldırın.", en: "Extract addresses, run a syntax pre-check, and remove duplicates.", de: "Adressen extrahieren, Syntax prüfen und Duplikate entfernen.", zh: "提取地址、进行语法预检并移除重复项。" }),
  tool("dosya-adi-guvenli-donusturucu", "text", "E15", { tr: "Güvenli Dosya Adı Dönüştürücü", en: "Safe Filename Converter", de: "Sicherer Dateinamen-Konverter", zh: "安全文件名转换器" }, { tr: "Başlıkları işletim sistemleriyle uyumlu, temiz dosya adlarına çevirin.", en: "Turn titles into clean filenames that work across operating systems.", de: "Titel in saubere, systemübergreifende Dateinamen umwandeln.", zh: "将标题转换为跨操作系统兼容的安全文件名。" }),
  tool("query-string-olusturucu", "data", "E16", { tr: "Query String Oluşturucu", en: "Query String Builder", de: "Query-String-Generator", zh: "查询字符串生成器" }, { tr: "Anahtar-değer satırlarından güvenli URL sorgu parametreleri üretin.", en: "Build safely encoded URL parameters from key-value rows.", de: "Sicher codierte URL-Parameter aus Schlüssel-Wert-Zeilen erstellen.", zh: "从键值行生成安全编码的 URL 查询参数。" }),
  tool("http-durum-kodu-rehberi", "data", "E17", { tr: "HTTP Durum Kodu Açıklayıcı", en: "HTTP Status Code Explainer", de: "HTTP-Statuscode-Erklärung", zh: "HTTP 状态码解释器" }, { tr: "Bir durum kodunun anlamını ve uygulanabilir sonraki kontrolü görün.", en: "See what a status code means and the next practical check.", de: "Bedeutung eines Statuscodes und nächsten Prüfschritt anzeigen.", zh: "查看状态码含义和可执行的下一步检查。" }),
  tool("uuid-toplu-dogrulayici", "data", "E18", { tr: "Toplu UUID Doğrulayıcı", en: "Bulk UUID Validator", de: "UUID-Stapelprüfung", zh: "批量 UUID 验证器" }, { tr: "UUID listesini sürüm, biçim ve tekrar açısından denetleyin.", en: "Check a UUID list for version, format, and duplicates.", de: "UUID-Liste auf Version, Format und Duplikate prüfen.", zh: "检查 UUID 列表的版本、格式和重复项。" }),
  tool("csv-sutun-secici", "data", "E19", { tr: "CSV Sütun Seçici", en: "CSV Column Selector", de: "CSV-Spaltenauswahl", zh: "CSV 列选择器" }, { tr: "Bir CSV tablosundan istediğiniz sütunları sırayla çıkarın.", en: "Extract selected columns from a CSV table in your preferred order.", de: "Gewählte CSV-Spalten in gewünschter Reihenfolge extrahieren.", zh: "按指定顺序从 CSV 表格中提取所需列。" }),
  tool("json-ornek-veri-olusturucu", "data", "E20", { tr: "JSON Örnek Veri Oluşturucu", en: "JSON Sample Data Builder", de: "JSON-Beispieldaten-Generator", zh: "JSON 示例数据生成器" }, { tr: "Alan tanımlarından güvenli, sentetik JSON kayıtları üretin.", en: "Generate safe synthetic JSON records from field definitions.", de: "Sichere synthetische JSON-Datensätze aus Felddefinitionen erzeugen.", zh: "根据字段定义生成安全的合成 JSON 记录。" }),
  tool("json-yol-listeleyici", "data", "E21", { tr: "JSON Yol Listeleyici", en: "JSON Path Lister", de: "JSON-Pfadliste", zh: "JSON 路径列举器" }, { tr: "İç içe JSON içindeki tüm yaprak yolları ve değer türlerini listeleyin.", en: "List every leaf path and value type in nested JSON.", de: "Alle Blattpfade und Werttypen in verschachteltem JSON auflisten.", zh: "列出嵌套 JSON 中的所有叶路径和值类型。" }),
  tool("checksum-karsilastirici", "codeSecurity", "E22", { tr: "Checksum Karşılaştırıcı", en: "Checksum Comparator", de: "Prüfsummenvergleich", zh: "校验和比较器" }, { tr: "Metin verisinin SHA-256 özetini beklenen değerle sabit zamanda karşılaştırın.", en: "Compare a text SHA-256 digest with an expected value in constant time.", de: "SHA-256-Prüfsumme eines Textes konstant mit einem Sollwert vergleichen.", zh: "以恒定时间比较文本的 SHA-256 摘要与预期值。" }),
  tool("sri-hash-olusturucu", "codeSecurity", "E23", { tr: "SRI Hash Oluşturucu", en: "SRI Hash Generator", de: "SRI-Hash-Generator", zh: "SRI 哈希生成器" }, { tr: "Yerel metin veya kod için Subresource Integrity değeri üretin.", en: "Generate a Subresource Integrity value for local text or code.", de: "Subresource-Integrity-Wert für lokalen Text oder Code erzeugen.", zh: "为本地文本或代码生成子资源完整性值。" }),
  tool("csp-direktif-birlestirici", "codeSecurity", "E24", { tr: "CSP Direktif Birleştirici", en: "CSP Directive Merger", de: "CSP-Direktiven-Merger", zh: "CSP 指令合并器" }, { tr: "İki Content Security Policy metnini tekrarları ayıklayarak birleştirin.", en: "Merge two Content Security Policy strings while removing duplicates.", de: "Zwei Content-Security-Policy-Texte ohne Duplikate zusammenführen.", zh: "合并两份内容安全策略并移除重复项。" }),
  tool("ajan-girdi-cikti-sozlesmesi", "ai", "E25", { tr: "Ajan Girdi/Çıktı Sözleşmesi", en: "Agent Input/Output Contract", de: "Agenten-Ein-/Ausgabevertrag", zh: "智能体输入/输出契约" }, { tr: "Bir ajan görevi için doğrulanabilir giriş, çıktı ve hata sözleşmesi hazırlayın.", en: "Build a verifiable input, output, and error contract for an agent task.", de: "Prüfbaren Ein-, Ausgabe- und Fehlervertrag für Agentenaufgaben erstellen.", zh: "为智能体任务创建可验证的输入、输出和错误契约。" }),
];
