import type { Locale } from "./site";
import type { ArticleSection, Post } from "./posts";
import type { LocalizedGuide } from "./localized-guides";
import { getTool } from "./tools";

type L = Record<Locale, string>;
type Guide = { slug: string; relatedTools: string[]; title: L; excerpt: L; category: L; scenario: L; checks: Record<Locale, string[]> };
const l = (tr: string, en: string, de: string, zh: string): L => ({ tr, en, de, zh });

const guides: Guide[] = [
  { slug: "pwa-kurulum-cevrimdisi-gizlilik-kontrolu", relatedTools: ["dosya-adi-guvenli-donusturucu", "checksum-karsilastirici", "json-bicimlendirici"], title: l("PWA Kurulum ve Çevrimdışı Gizlilik Kontrolü", "PWA Install and Offline Privacy Checklist", "PWA-Installation und Offline-Datenschutz prüfen", "PWA 安装与离线隐私检查"), excerpt: l("Bir web uygulamasını güvenle kurun; APK, önbellek ve çevrimdışı erişim sınırlarını gerçekten test edin.", "Install a web app safely and genuinely test APK, cache, and offline-access boundaries.", "Web-App sicher installieren und APK-, Cache- sowie Offline-Grenzen wirklich testen.", "安全安装 Web 应用，并实际测试 APK、缓存与离线访问边界。"), category: l("PWA ve gizlilik", "PWA & privacy", "PWA & Datenschutz", "PWA 与隐私"), scenario: l("ByteQuant’ı telefona eklemek, önemli araçları uçak modunda denemek ve hiçbir araç girdisinin önbelleğe girmediğini doğrulamak.", "Add ByteQuant to a phone, test key tools in airplane mode, and verify that tool inputs never enter the cache.", "ByteQuant zum Smartphone hinzufügen, wichtige Werkzeuge im Flugmodus prüfen und sicherstellen, dass Eingaben nie im Cache landen.", "将 ByteQuant 添加到手机，在飞行模式下测试关键工具，并确认工具输入不会进入缓存。"), checks: { tr: ["Kurulum tarayıcı menüsünden veya yerleşik istemden başlıyor.", "Manifest ve servis çalışanı aynı HTTPS kaynağında.", "Çevrimdışı sayfa hassas girdi göstermiyor."], en: ["Install begins from the browser menu or native prompt.", "Manifest and service worker share the HTTPS origin.", "The offline page exposes no sensitive input."], de: ["Installation startet im Browsermenü oder nativen Dialog.", "Manifest und Service Worker haben denselben HTTPS-Ursprung.", "Offline-Seite zeigt keine sensiblen Eingaben."], zh: ["安装来自浏览器菜单或原生提示。", "清单和服务工作线程使用同一 HTTPS 来源。", "离线页面不显示敏感输入。"] } },
  { slug: "yerel-ajan-is-istasyonu-uygulamali-akis", relatedTools: ["ajan-girdi-cikti-sozlesmesi", "kvkk-veri-maskeleyici", "json-bicimlendirici"], title: l("Yerel Ajandan İş İstasyonuna: Uygulanabilir Akış", "From Local Agent to Workstation: An Executable Flow", "Vom lokalen Agenten zur Workstation: ausführbarer Ablauf", "从本地助手到工作站：可执行流程"), excerpt: l("Bir hedefi araç planına çevirin, çıktıları kontrollü aktarın ve hatalı adımda güvenle geri dönün.", "Turn an outcome into a tool plan, pass outputs deliberately, and roll back safely after a failed step.", "Ziel in Werkzeugplan umwandeln, Ausgaben kontrolliert übergeben und sicher zurückrollen.", "将目标转换为工具计划，受控传递输出，并在失败后安全回退。"), category: l("Yerel otomasyon", "Local automation", "Lokale Automatisierung", "本地自动化"), scenario: l("Bir CSV’deki kişisel veriyi maskeleyip JSON’a dönüştürmek; her adımın girdisini, beklenen çıktısını ve durdurma koşulunu önceden yazmak.", "Mask personal data in a CSV and convert it to JSON while writing each step's input, expected output, and stop condition first.", "Personendaten in CSV maskieren und in JSON umwandeln; Eingabe, Sollausgabe und Stoppbedingung je Schritt vorab festhalten.", "先定义每一步的输入、预期输出和停止条件，再对 CSV 中的个人数据脱敏并转换为 JSON。"), checks: { tr: ["Ajanın seçtiği her araç için gerekçe görünür.", "Aktarım kullanıcı onayı olmadan çalışmıyor.", "İş İstasyonu geri alma geçmişi tutuyor."], en: ["Every Agent tool choice has a visible reason.", "No transfer runs without user approval.", "Workstation keeps an undo trail."], de: ["Jede Werkzeugwahl ist begründet.", "Keine Übergabe ohne Nutzerfreigabe.", "Workstation führt einen Undo-Verlauf."], zh: ["每个工具选择都有可见理由。", "未经用户确认不会传递数据。", "工作站保留撤销历史。"] } },
  { slug: "sunucusuz-topluluk-guvenli-paylasim", relatedTools: ["checksum-karsilastirici", "e-posta-listesi-temizleyici", "url-risk-on-taramasi"], title: l("Sunucusuz Toplulukta Güvenli Paylaşım", "Safe Sharing in a Serverless Community", "Sicher teilen in einer serverlosen Community", "无服务器社区中的安全分享"), excerpt: l("Yerel profil, içerik bağlantısı, taşınabilir paket ve P2P oturumu arasındaki farkı uygulamalı öğrenin.", "Practically distinguish a local profile, content link, portable pack, and direct P2P session.", "Lokales Profil, Inhaltslink, portables Paket und direkte P2P-Sitzung unterscheiden.", "通过实践区分本地资料、内容链接、便携包和直接 P2P 会话。"), category: l("Topluluk güvenliği", "Community safety", "Community-Sicherheit", "社区安全"), scenario: l("Üyelik hesabı olmadan bir iş akışını paylaşmak; kişisel veriyi kaldırmak, paketi doğrulamak ve kalıcı global yayın sınırını açıklamak.", "Share a workflow without an account by removing personal data, validating the pack, and explaining the boundary of durable global publishing.", "Ablauf ohne Konto teilen, Personendaten entfernen, Paket prüfen und Grenze dauerhafter globaler Veröffentlichung erklären.", "无需账户分享工作流：移除个人数据、验证内容包，并说明永久全球发布的边界。"), checks: { tr: ["Gizli profil dışa aktarımda anonimleşiyor.", "İçe aktarılan içerik filtre ve boyut sınırından geçiyor.", "Sunucusuzken sahte global sayaç gösterilmiyor."], en: ["Private profiles are anonymized on export.", "Imported content passes safety and size limits.", "No fake global counts appear without a server."], de: ["Private Profile werden beim Export anonymisiert.", "Importe bestehen Sicherheits- und Größenlimits.", "Keine erfundenen globalen Zahlen ohne Server."], zh: ["私密资料在导出时匿名化。", "导入内容通过安全和大小限制。", "无服务器时不显示虚假全球计数。"] } },
  { slug: "resmi-gundem-kaynaklarini-dogrulama", relatedTools: ["kaynak-guvenilirlik-puanlayici", "iddia-kaynak-eslestirici", "tarih-sure-hesaplayici"], title: l("Resmî Teknoloji Gündemini Doğrulama Rehberi", "How to Verify Official Technology Updates", "Offizielle Technologie-Updates verifizieren", "如何核验官方科技动态"), excerpt: l("Kaynak özetini, yayın tarihini, özgün bağlantıyı ve editoryal bağlamı birbirine karıştırmadan okuyun.", "Read source summaries, publication dates, original links, and editorial context without conflating them.", "Quellenzusammenfassung, Datum, Originallink und redaktionellen Kontext getrennt lesen.", "区分阅读来源摘要、发布日期、原始链接和编辑语境。"), category: l("Kaynak doğrulama", "Source verification", "Quellenprüfung", "来源核验"), scenario: l("Yeni bir siber güvenlik duyurusunu önce tarihe göre bulmak, resmî kısa özeti okumak, özgün sayfayı açmak ve önemli iddiaları ikinci bir birincil kaynakla kontrol etmek.", "Find a new cybersecurity notice by date, read its official brief, open the original page, and check consequential claims against another primary source.", "Neue Sicherheitsmeldung nach Datum finden, offiziellen Kurztext lesen, Original öffnen und wichtige Aussagen mit weiterer Primärquelle prüfen.", "按日期查找网络安全公告，阅读官方摘要，打开原始页面，并用另一一手来源核查重要主张。"), checks: { tr: ["Kartlar yayın tarihine göre sıralı.", "Kaynak özeti ile ByteQuant bağlamı etiketle ayrılıyor.", "Özgün bağlantı üçüncü tarafa geçişi belirtiyor."], en: ["Cards are ordered by publication date.", "Source brief and ByteQuant context are separately labeled.", "The original link discloses third-party navigation."], de: ["Karten sind nach Datum sortiert.", "Quellenkurztext und ByteQuant-Kontext sind getrennt.", "Originallink kennzeichnet Drittseite."], zh: ["卡片按发布日期排序。", "来源摘要与 ByteQuant 语境分别标注。", "原始链接说明将前往第三方网站。"] } },
  { slug: "gunluk-hesaplamalari-e-tablo-olmadan", relatedTools: ["bahsis-hesap-bolusturucu", "indirim-kdv-hesaplayici", "birim-fiyat-karsilastirici"], title: l("E-Tablo Açmadan Günlük Hesaplamalar", "Everyday Calculations Without a Spreadsheet", "Alltagsrechnungen ohne Tabellenkalkulation", "无需电子表格的日常计算"), excerpt: l("Bahşiş, indirim, KDV, birim fiyat ve paylaşım hesaplarında formülü görünür tutup giriş hatasını azaltın.", "Reduce input errors while keeping formulas visible for tips, discounts, VAT, unit prices, and splits.", "Eingabefehler reduzieren und Formeln bei Trinkgeld, Rabatt, Steuer und Aufteilung sichtbar halten.", "在小费、折扣、税费、单价和分摊计算中显示公式并减少输入错误。"), category: l("Günlük üretkenlik", "Everyday productivity", "Alltagsproduktivität", "日常效率"), scenario: l("Restoran hesabını dört kişi arasında bölmek, bahşişin vergi öncesi mi sonrası mı olduğunu açıkça seçmek ve kişi başı sonucu denetlemek.", "Split a restaurant bill among four people, explicitly choose whether the tip is pre- or post-tax, and audit the per-person result.", "Restaurantrechnung auf vier Personen teilen, Trinkgeldbasis ausdrücklich wählen und Pro-Kopf-Wert prüfen.", "四人分摊餐厅账单，明确选择小费按税前或税后计算，并核查每人金额。"), checks: { tr: ["Genel kullanıcıdan JSON istenmiyor.", "Yüzde ile parasal tutar ayrı gösteriliyor.", "Yuvarlama ve kapsam notu görünür."], en: ["General users are never asked for JSON.", "Percentages and money values are separate.", "Rounding and scope notes are visible."], de: ["Kein JSON für allgemeine Nutzer.", "Prozent und Geldbetrag getrennt.", "Rundung und Umfang sichtbar."], zh: ["普通用户无需输入 JSON。", "百分比与金额分开显示。", "舍入和范围说明清晰可见。"] } },
  { slug: "liste-csv-json-cihazda-temizleme", relatedTools: ["e-posta-listesi-temizleyici", "csv-sutun-secici", "json-yol-listeleyici"], title: l("Liste, CSV ve JSON Verisini Cihazda Temizleme", "Clean Lists, CSV, and JSON on Your Device", "Listen, CSV und JSON direkt auf dem Gerät bereinigen", "在设备上清理列表、CSV 与 JSON"), excerpt: l("Tekrarları, gereksiz sütunları ve iç içe alanları ham veriyi yüklemeden güvenli bir zincirle yönetin.", "Handle duplicates, unnecessary columns, and nested fields in a safe chain without uploading raw data.", "Duplikate, unnötige Spalten und verschachtelte Felder ohne Upload sicher bearbeiten.", "无需上传原始数据，安全处理重复项、不必要列和嵌套字段。"), category: l("Veri temizliği", "Data cleaning", "Datenbereinigung", "数据清理"), scenario: l("Bir e-posta dışa aktarımından adresleri çıkarmak, tekrarları ayıklamak, CSV’de yalnızca gerekli sütunları bırakmak ve JSON yol listesini teslim kaydına eklemek.", "Extract addresses from an email export, remove duplicates, retain required CSV columns, and attach a JSON path list to the delivery record.", "Adressen extrahieren, Duplikate entfernen, nötige CSV-Spalten behalten und JSON-Pfade dokumentieren.", "从邮件导出中提取地址、去重、保留必要 CSV 列，并记录 JSON 路径。"), checks: { tr: ["Ham kopya değiştirilmeden saklanıyor.", "Başlık ve satır sayısı çıktıdan önce doğrulanıyor.", "Hatalı veri sessizce atılmıyor."], en: ["The raw copy remains unchanged.", "Header and row counts are verified before handoff.", "Malformed data is never silently discarded."], de: ["Rohkopie bleibt unverändert.", "Kopf- und Zeilenzahl werden geprüft.", "Fehlerhafte Daten werden nicht still verworfen."], zh: ["原始副本保持不变。", "交付前核对表头和行数。", "错误数据不会被静默丢弃。"] } },
  { slug: "web-projesi-guvenlik-on-kontrolu", relatedTools: ["csp-direktif-birlestirici", "sri-hash-olusturucu", "http-durum-kodu-rehberi"], title: l("Web Projesi İçin Güvenlik Ön Kontrolü", "A Security Preflight for Web Projects", "Sicherheits-Vorprüfung für Webprojekte", "Web 项目安全预检"), excerpt: l("CSP, SRI, checksum, HTTP davranışı ve gizli bilgi riskini yayın öncesi açıklanabilir kontrollerle tarayın.", "Review CSP, SRI, checksums, HTTP behavior, and secret exposure with explainable pre-release checks.", "CSP, SRI, Prüfsummen, HTTP-Verhalten und Geheimnisse vor Release nachvollziehbar prüfen.", "在发布前以可解释方式检查 CSP、SRI、校验和、HTTP 行为和机密泄露。"), category: l("Kod güvenliği", "Code security", "Codesicherheit", "代码安全"), scenario: l("Bir statik sitenin üçüncü taraf kaynağı için SRI üretmek, iki CSP taslağını karşılaştırmak ve 404/429/500 hata yollarını kullanıcıya güvenli mesajlarla göstermek.", "Generate SRI for a static site's third-party resource, compare two CSP drafts, and present safe user messages for 404/429/500 paths.", "SRI für Drittressource erzeugen, CSP-Entwürfe vergleichen und sichere Meldungen für 404/429/500 zeigen.", "为静态站点第三方资源生成 SRI，比较两份 CSP 草案，并为 404/429/500 路径提供安全提示。"), checks: { tr: ["Gizli anahtar istemci paketinde bulunmuyor.", "CSP rapor modunda gerçek kaynaklarla deneniyor.", "Algoritma kontrolü güvenlik onayı olarak sunulmuyor."], en: ["No secret is present in the client bundle.", "CSP is tested in report-only mode with real resources.", "An algorithmic check is not presented as security approval."], de: ["Keine Geheimnisse im Client-Bundle.", "CSP im Report-Only-Modus mit echten Quellen testen.", "Algorithmusprüfung ist keine Sicherheitsfreigabe."], zh: ["客户端包中不含机密。", "使用真实资源在仅报告模式下测试 CSP。", "算法检查不等同于安全批准。"] } },
];

function sections(locale: Locale, guide: Guide): ArticleSection[] {
  const t = {
    tr: { prepare: "Önce hedefi ve sınırı yazın", run: "Uygulamalı iş akışı", verify: "Sonucu doğrulama", fail: "Hata yolu ve geri dönüş", next: "Tekrarlanabilir kontrol listesi" },
    en: { prepare: "Write the outcome and boundary first", run: "Applied workflow", verify: "Verify the result", fail: "Failure path and recovery", next: "Repeatable checklist" },
    de: { prepare: "Ziel und Grenze zuerst festhalten", run: "Praktischer Ablauf", verify: "Ergebnis verifizieren", fail: "Fehlerpfad und Wiederherstellung", next: "Wiederholbare Checkliste" },
    zh: { prepare: "先写明目标与边界", run: "实践工作流", verify: "核验结果", fail: "失败路径与恢复", next: "可重复检查清单" },
  }[locale];
  const paragraphs: Record<Locale, string[]> = {
    tr: ["Başlamadan önce kabul ölçütünü, izin verilen veri türünü ve asla otomatikleştirilmeyecek kararı yazın. Örnek veriyi sentetik tutun; gerçek kişisel veri, sır, erişim anahtarı veya lisanslı tam metni rehber akışına kopyalamayın.", "Her araç çıktısı bir gözlem veya kural tabanlı dönüşümdür; kimlik doğrulaması, hukuki uygunluk, güvenlik sertifikası ya da uzman kararı değildir. Yüksek etkili sonucu güncel birincil kaynak veya yetkili kişiyle ayrıca doğrulayın."],
    en: ["Before starting, record acceptance criteria, allowed data types, and the decision that must never be automated. Keep examples synthetic; do not copy real personal data, secrets, access keys, or licensed full text into the guide workflow.", "Every tool output is an observation or rule-based transformation—not identity verification, legal compliance, a security certificate, or expert judgment. Independently verify high-impact outcomes with a current primary source or qualified person."],
    de: ["Vor Beginn Abnahmekriterien, zulässige Datentypen und niemals zu automatisierende Entscheidungen festhalten. Beispiele synthetisch halten; keine echten Personendaten, Geheimnisse, Schlüssel oder lizenzierten Volltexte kopieren.", "Jede Ausgabe ist Beobachtung oder regelbasierte Transformation – keine Identitätsprüfung, Rechtskonformität, Sicherheitszertifizierung oder Expertenentscheidung. Folgenreiche Ergebnisse unabhängig prüfen."],
    zh: ["开始前记录验收标准、允许的数据类型以及绝不能自动化的决定。示例应使用合成数据；不要把真实个人数据、机密、访问密钥或受许可限制的全文复制到流程中。", "每个工具输出都只是观察或基于规则的转换，并非身份验证、法律合规、安全认证或专家判断。高影响结果应通过当前一手来源或合格人员独立核验。"],
  };
  const scenario = guide.scenario[locale];
  const toolSteps = guide.relatedTools.map((slug, index) => {
    const tool = getTool(slug);
    const title = tool?.title[locale] ?? slug.replaceAll("-", " ");
    return locale === "de" ? `Schritt ${index + 1}: ${title}` : locale === "zh" ? `第 ${index + 1} 步：${title}` : locale === "tr" ? `${index + 1}. adım: ${title}` : `Step ${index + 1}: ${title}`;
  });
  const checksFor = (index: number) => [guide.checks[locale][index % guide.checks[locale].length]];
  return [
    { heading: t.prepare, paragraphs: [paragraphs[locale][0], guide.excerpt[locale]], bullets: checksFor(0) },
    { heading: t.run, paragraphs: [scenario, paragraphs[locale][1]], bullets: toolSteps },
    { heading: t.verify, paragraphs: [locale === "tr" ? "Girdi ile çıktıyı yan yana tutun; değişen alanı, dönüşüm kuralını ve insan onayı gereken noktayı işaretleyin. İyi örneğin yanında boş, bozuk, aşırı büyük ve beklenmeyen Unicode içeren girdileri de deneyin." : locale === "de" ? "Eingabe und Ausgabe nebeneinander halten; geänderte Felder, Regel und menschliche Freigabe markieren. Neben gültigen Beispielen auch leere, fehlerhafte, übergroße und unerwartete Unicode-Eingaben testen." : locale === "zh" ? "并排保留输入与输出；标记变化字段、转换规则和需要人工批准的环节。除正常示例外，还应测试空值、格式错误、超大内容和异常 Unicode。" : "Keep input and output side by side; mark changed fields, the applied rule, and where human approval remains. Test empty, malformed, oversized, and unexpected Unicode inputs as well as the happy path."], bullets: checksFor(1) },
    { heading: t.fail, paragraphs: [locale === "tr" ? "Bir adım hata verirse çıktıyı zorla sonraki araca aktarmayın. Son doğrulanmış kopyaya dönün, girdiyi küçültün, hata mesajını kişisel veri ve sırlardan arındırın; yeniden denemeden önce durdurma koşulunu kaydedin." : locale === "de" ? "Bei Fehlern die Ausgabe nicht erzwingen. Zur letzten geprüften Kopie zurückkehren, Eingabe verkleinern, Fehlermeldung von Personendaten/Geheimnissen bereinigen und Stoppbedingung dokumentieren." : locale === "zh" ? "某一步失败时不要强行传递输出。回到最近一次已验证副本，缩小输入，移除错误信息中的个人数据和机密，并记录停止条件。" : "If a step fails, do not force its output forward. Return to the last verified copy, reduce the input, remove personal data and secrets from the error, and record the stop condition before retrying."], bullets: checksFor(2) },
    { heading: t.next, paragraphs: [locale === "tr" ? "Aynı akışı başka biri yalnızca bu kayıtla tekrar edebiliyorsa yöntem yeterince açıktır. Kaynak, tarih, araç sürümü, girdi şeması, beklenen sonuç, bilinen sınırlar ve geri dönüş kopyasını birlikte saklayın." : locale === "de" ? "Die Methode ist klar, wenn eine andere Person sie allein mit diesem Protokoll wiederholen kann. Quelle, Datum, Werkzeugversion, Eingabeschema, Sollausgabe, Grenzen und Rücknahmekopie gemeinsam speichern." : locale === "zh" ? "如果他人仅凭该记录即可重复流程，方法才足够清晰。请一起保存来源、日期、工具版本、输入模式、预期结果、已知边界和回退副本。" : "The method is clear enough when another person can repeat it from the record alone. Keep source, date, tool version, input schema, expected result, known limits, and rollback copy together."], bullets: checksFor(0) },
  ];
}

export const essentialPosts: Post[] = guides.map((guide) => ({ slug: guide.slug, relatedTools: guide.relatedTools, date: "2026-07-28", updated: "2026-07-28", readTime: { tr: "13 dk", en: "12 min" }, title: { tr: guide.title.tr, en: guide.title.en }, excerpt: { tr: guide.excerpt.tr, en: guide.excerpt.en }, description: { tr: `${guide.excerpt.tr} Gerçek senaryo, hata yolu, doğrulama ve güvenlik sınırlarıyla kapsamlı rehber.`, en: `${guide.excerpt.en} A detailed guide with a real scenario, failure path, verification, and safety boundaries.` }, category: { tr: guide.category.tr, en: guide.category.en }, visualSuggestion: { tr: "Girdi, cihaz içi işlem, doğrulama ve kontrollü teslimi gösteren sade akış.", en: "A clear flow from input through on-device processing, verification, and controlled handoff." }, sections: { tr: sections("tr", guide), en: sections("en", guide) } }));

export const essentialLocalizedGuides: LocalizedGuide[] = guides.map((guide) => ({ slug: guide.slug, relatedTools: guide.relatedTools, date: "2026-07-28", updated: "2026-07-28", copy: { de: { title: guide.title.de, excerpt: guide.excerpt.de, description: `${guide.excerpt.de} Ausführlicher Leitfaden mit Szenario, Fehlerpfad, Prüfung und Sicherheitsgrenzen.`, category: guide.category.de, readTime: "12 Min.", sections: sections("de", guide) }, zh: { title: guide.title.zh, excerpt: guide.excerpt.zh, description: `${guide.excerpt.zh} 包含真实场景、失败路径、核验与安全边界的详细指南。`, category: guide.category.zh, readTime: "约 12 分钟", sections: sections("zh", guide) } } }));
