import type { Locale } from "./site";
import type { ToolCategory } from "./tools";
import type { BaseTool } from "./tool-locales";

type L = Record<Locale, string>;
type Spec = { slug: string; category: ToolCategory; mark: string; title: L; short: L };

const common: Record<ToolCategory, { detail: L; useCases: Record<Locale, string[]>; steps: Record<Locale, string[]> }> = {
  prompt: {
    detail: { tr: "Şeffaf kurallarla cihazınızda çalışır; üretilen taslağı hedef model ve gerçek örneklerle doğrulamanız gerekir.", en: "It runs on-device with transparent rules; validate the draft against the target model and real examples.", de: "Die Verarbeitung erfolgt lokal mit transparenten Regeln; prüfen Sie den Entwurf am Zielmodell und an echten Beispielen.", zh: "工具以透明规则在设备端运行；请结合目标模型和真实示例核验草稿。" },
    useCases: { tr: ["Prompt tasarım incelemesi", "Ekip standardı oluşturma", "Yayın öncesi kalite kontrolü"], en: ["Prompt design review", "Team standardization", "Pre-release quality checks"], de: ["Prompt-Entwurfsprüfung", "Teamstandards", "Qualitätsprüfung vor Freigabe"], zh: ["提示词设计审查", "团队标准化", "发布前质量检查"] },
    steps: { tr: ["Hedefi ve mevcut talimatı girin.", "Yerel analizi çalıştırıp gerekçeleri inceleyin.", "Taslağı gerçek test vakalarıyla doğrulayın."], en: ["Enter the goal and current instruction.", "Run the local analysis and review its reasons.", "Validate the draft with real test cases."], de: ["Ziel und Anweisung eingeben.", "Lokale Analyse und Begründungen prüfen.", "Entwurf mit realen Testfällen validieren."], zh: ["输入目标和当前指令。", "运行本地分析并查看理由。", "使用真实测试用例验证草稿。"] },
  },
  text: {
    detail: { tr: "Metni uzak bir servise göndermeden açıklanabilir dil kuralları uygular; bağlam ve anlam için son insan kontrolü gerekir.", en: "It applies explainable language rules without sending text to a remote service; final human review remains necessary for context and meaning.", de: "Erklärbare Sprachregeln werden ohne Upload angewandt; Kontext und Bedeutung erfordern eine abschließende menschliche Prüfung.", zh: "无需上传即可应用可解释的语言规则；语境与含义仍需人工最终审核。" },
    useCases: { tr: ["Yayın öncesi metin kontrolü", "Toplu içerik düzenleme", "Ekip dili tutarlılığı"], en: ["Pre-publication review", "Batch content editing", "Consistent team language"], de: ["Prüfung vor Veröffentlichung", "Stapelbearbeitung", "Einheitliche Teamsprache"], zh: ["发布前审核", "批量内容编辑", "团队语言一致性"] },
    steps: { tr: ["Metni girin veya örneği yükleyin.", "Analizi çalıştırıp işaretlenen yerleri inceleyin.", "Önerileri bağlama göre düzenleyip çıktıyı alın."], en: ["Enter text or load the example.", "Run the analysis and inspect highlighted items.", "Adapt suggestions to context and export the result."], de: ["Text eingeben oder Beispiel laden.", "Analyse starten und Markierungen prüfen.", "Vorschläge kontextbezogen anpassen und exportieren."], zh: ["输入文本或加载示例。", "运行分析并检查标记项。", "结合语境调整建议并导出结果。"] },
  },
  data: {
    detail: { tr: "Girdiyi yerel olarak doğrular ve dönüşüm varsayımlarını görünür kılar; üretim şemaları gerçek veri çeşitleriyle sınanmalıdır.", en: "It validates input locally and exposes transformation assumptions; production schemas should be tested against real data variants.", de: "Eingaben werden lokal validiert und Annahmen offengelegt; Produktionsschemata müssen mit realen Varianten getestet werden.", zh: "在本地验证输入并公开转换假设；生产 Schema 应使用真实数据变体测试。" },
    useCases: { tr: ["API ve veri hazırlığı", "Şema incelemesi", "Hata ayıklama"], en: ["API and data preparation", "Schema review", "Debugging"], de: ["API- und Datenvorbereitung", "Schemaprüfung", "Fehlersuche"], zh: ["API 与数据准备", "Schema 审查", "调试"] },
    steps: { tr: ["Veriyi yapıştırın veya güvenli örneği yükleyin.", "Dönüşümü çalıştırıp uyarıları inceleyin.", "Sonucu hedef sisteminizde doğrulayın."], en: ["Paste data or load the safe example.", "Run the transformation and inspect warnings.", "Validate the result in the target system."], de: ["Daten einfügen oder Beispiel laden.", "Verarbeitung starten und Warnungen prüfen.", "Ergebnis im Zielsystem validieren."], zh: ["粘贴数据或加载安全示例。", "运行处理并检查警告。", "在目标系统中验证结果。"] },
  },
  converter: {
    detail: { tr: "Dönüşümü etkin sekmede yapar, orijinali değiştirmez ve çıktı biçiminin sınırlarını açıkça gösterir.", en: "Conversion happens in the active tab, never overwrites the original, and exposes output-format limits.", de: "Die Konvertierung erfolgt im aktiven Tab, überschreibt nie das Original und nennt Formatgrenzen.", zh: "转换在当前标签页完成，不覆盖原文件，并明确说明输出格式限制。" },
    useCases: { tr: ["Yerel format dönüşümü", "Dokümantasyon çıktısı", "Paylaşım öncesi hazırlık"], en: ["Local format conversion", "Documentation output", "Pre-sharing preparation"], de: ["Lokale Formatkonvertierung", "Dokumentationsausgabe", "Vorbereitung zum Teilen"], zh: ["本地格式转换", "文档输出", "分享前准备"] },
    steps: { tr: ["Kaynak içeriği girin.", "Hedef biçimi seçip dönüşümü çalıştırın.", "Önizlemeyi doğrulayıp çıktıyı indirin."], en: ["Enter the source content.", "Choose the target format and run conversion.", "Verify the preview and download the output."], de: ["Quellinhalt eingeben.", "Zielformat wählen und konvertieren.", "Vorschau prüfen und Ausgabe laden."], zh: ["输入源内容。", "选择目标格式并运行转换。", "核对预览并下载输出。"] },
  },
  security: {
    detail: { tr: "Sonuç açıklanabilir bir ön kontroldür; kimlik, mevzuat uyumu, güvenlik veya kötü amaçsızlık garantisi değildir.", en: "The result is an explainable pre-check, not a guarantee of identity, compliance, security, or harmlessness.", de: "Das Ergebnis ist eine nachvollziehbare Vorprüfung, keine Garantie für Identität, Compliance, Sicherheit oder Unschädlichkeit.", zh: "结果仅为可解释的预检查，不保证身份、合规、安全或无害。" },
    useCases: { tr: ["Gizlilik ön kontrolü", "Paylaşım öncesi temizlik", "Risk kayıt hazırlığı"], en: ["Privacy pre-check", "Pre-sharing cleanup", "Risk-register preparation"], de: ["Datenschutz-Vorprüfung", "Bereinigung vor Freigabe", "Risikoregister"], zh: ["隐私预检查", "分享前清理", "风险登记准备"] },
    steps: { tr: ["Yalnızca inceleme yetkiniz olan içeriği girin.", "Sınırlı yerel taramayı çalıştırın.", "Kritik bulguları bağımsız olarak doğrulayın."], en: ["Enter only content you are authorized to inspect.", "Run the bounded local scan.", "Independently verify critical findings."], de: ["Nur autorisierte Inhalte eingeben.", "Begrenzte lokale Prüfung starten.", "Kritische Befunde unabhängig verifizieren."], zh: ["仅输入有权检查的内容。", "运行受限的本地扫描。", "独立核验关键发现。"] },
  },
  calculation: {
    detail: { tr: "Formülü, birimi ve varsayımları gösteren bir senaryo hesabıdır; profesyonel finans, hukuk veya bilim tavsiyesi değildir.", en: "This is a scenario calculation with visible formula, units, and assumptions; it is not professional financial, legal, or scientific advice.", de: "Dies ist eine Szenariorechnung mit sichtbarer Formel, Einheiten und Annahmen; keine professionelle Finanz-, Rechts- oder Wissenschaftsberatung.", zh: "这是展示公式、单位与假设的情景计算，不构成专业财务、法律或科学建议。" },
    useCases: { tr: ["Senaryo karşılaştırma", "Hızlı ön hesap", "Varsayım belgeleme"], en: ["Scenario comparison", "Quick estimation", "Assumption documentation"], de: ["Szenariovergleich", "Schnelle Schätzung", "Annahmen dokumentieren"], zh: ["情景比较", "快速估算", "记录假设"] },
    steps: { tr: ["Değerleri ve birimleri girin.", "Formülle birlikte sonucu hesaplayın.", "Önemli kararlar için resmî yöntemi doğrulayın."], en: ["Enter values and units.", "Calculate and inspect the formula.", "Verify the official method for important decisions."], de: ["Werte und Einheiten eingeben.", "Ergebnis samt Formel berechnen.", "Für wichtige Entscheidungen die offizielle Methode prüfen."], zh: ["输入数值和单位。", "计算并检查公式。", "重要决策请核验官方方法。"] },
  },
  general: {
    detail: { tr: "Düzenlenebilir bir başlangıç çıktısı üretir ve bilgileri cihazınızda tutar; resmî belge veya uzman onayı yerine geçmez.", en: "It creates an editable starting output and keeps data on-device; it does not replace an official document or expert approval.", de: "Erstellt einen bearbeitbaren Ausgangsentwurf und hält Daten lokal; ersetzt kein offizielles Dokument oder eine fachliche Freigabe.", zh: "生成可编辑的起始结果并将数据保留在设备端；不能替代正式文件或专家批准。" },
    useCases: { tr: ["Günlük planlama", "Yeniden kullanılabilir taslak", "Ekip hazırlığı"], en: ["Everyday planning", "Reusable drafts", "Team preparation"], de: ["Alltagsplanung", "Wiederverwendbare Entwürfe", "Teamvorbereitung"], zh: ["日常规划", "可复用草稿", "团队准备"] },
    steps: { tr: ["İhtiyaç duyulan bilgileri girin.", "Yerel taslağı oluşturun.", "Düzenleyip doğruladıktan sonra dışa aktarın."], en: ["Enter the required information.", "Generate the local draft.", "Edit, verify, and export it."], de: ["Benötigte Angaben eingeben.", "Lokalen Entwurf erzeugen.", "Bearbeiten, prüfen und exportieren."], zh: ["输入所需信息。", "生成本地草稿。", "编辑、核验后导出。"] },
  },
  ai: {
    detail: { tr: "Uzak modele bağlanmadan açıklanabilir bir hazırlık ve değerlendirme sunar; model çıktısını üretmez veya doğrulamaz.", en: "It provides explainable preparation and evaluation without calling a remote model; it neither generates nor verifies model output.", de: "Bietet nachvollziehbare Vorbereitung ohne Remote-Modell; Modellantworten werden weder erzeugt noch verifiziert.", zh: "无需调用远程模型即可进行可解释的准备和评估；不会生成或验证模型输出。" },
    useCases: { tr: ["AI iş akışı hazırlığı", "Bağlam ve risk planlama", "Çıktı değerlendirme"], en: ["AI workflow preparation", "Context and risk planning", "Output evaluation"], de: ["KI-Ablaufvorbereitung", "Kontext- und Risikoplanung", "Ausgabebewertung"], zh: ["AI 工作流准备", "上下文与风险规划", "输出评估"] },
    steps: { tr: ["Hedefi ve kısıtları girin.", "Yerel değerlendirmeyi çalıştırın.", "Sonucu gerçek model ve kaynaklarla sınayın."], en: ["Enter the goal and constraints.", "Run the local evaluation.", "Test the result against the real model and sources."], de: ["Ziel und Grenzen eingeben.", "Lokale Bewertung starten.", "Ergebnis am echten Modell und Quellen testen."], zh: ["输入目标与约束。", "运行本地评估。", "结合真实模型与来源测试结果。"] },
  },
  codeSecurity: {
    detail: { tr: "Kod çalıştırmadan açıklanabilir desenleri tarar; tam SAST, antivirüs, paket itibarı veya sömürülebilirlik kanıtı değildir.", en: "It scans explainable patterns without executing code; it is not complete SAST, antivirus, package reputation, or proof of exploitability.", de: "Prüft erklärbare Muster ohne Codeausführung; kein vollständiges SAST, Antivirus, Paket-Reputation oder Exploit-Nachweis.", zh: "不执行代码，仅扫描可解释模式；不等同于完整 SAST、杀毒、包信誉或可利用性证明。" },
    useCases: { tr: ["Kod inceleme öncesi tarama", "Yapılandırma sıkılaştırma", "Risk önceliklendirme"], en: ["Pre-review scanning", "Configuration hardening", "Risk prioritization"], de: ["Prüfung vor Code-Review", "Konfigurationshärtung", "Risikopriorisierung"], zh: ["代码审查前扫描", "配置加固", "风险排序"] },
    steps: { tr: ["Yetkili kod veya yapılandırmayı girin.", "Sınırlı yerel ön taramayı çalıştırın.", "Bulguları bağlam ve resmî dokümantasyonla doğrulayın."], en: ["Enter authorized code or configuration.", "Run the bounded local pre-scan.", "Verify findings against context and official documentation."], de: ["Autorisierten Code eingeben.", "Begrenzte lokale Vorprüfung starten.", "Befunde mit Kontext und offizieller Doku prüfen."], zh: ["输入获授权的代码或配置。", "运行受限的本地预扫描。", "结合语境和官方文档核验发现。"] },
  },
  research: {
    detail: { tr: "İddia, kaynak ve belirsizliği ayrı tutan bir çalışma tablosu üretir; doğruluğu veya kaynak güvenilirliğini otomatik olarak garanti etmez.", en: "It builds a worksheet that separates claims, sources, and uncertainty; it cannot automatically guarantee accuracy or source reliability.", de: "Erstellt eine Arbeitsmatrix für Aussagen, Quellen und Unsicherheit; Richtigkeit oder Quellenverlässlichkeit werden nicht garantiert.", zh: "生成区分主张、来源与不确定性的工作表；无法自动保证准确性或来源可靠性。" },
    useCases: { tr: ["Masa başı araştırma", "Kaynak karşılaştırma", "Kanıt sentezi"], en: ["Desk research", "Source comparison", "Evidence synthesis"], de: ["Desk Research", "Quellenvergleich", "Evidenzsynthese"], zh: ["案头研究", "来源比较", "证据综合"] },
    steps: { tr: ["Soruyu, iddiaları veya kaynak notlarını girin.", "Yerel matrisi oluşturun.", "Birincil kaynakları ve karşı kanıtları elle doğrulayın."], en: ["Enter the question, claims, or source notes.", "Generate the local matrix.", "Manually verify primary sources and counterevidence."], de: ["Frage, Aussagen oder Quellenhinweise eingeben.", "Lokale Matrix erzeugen.", "Primärquellen und Gegenbelege manuell prüfen."], zh: ["输入问题、主张或来源笔记。", "生成本地矩阵。", "人工核验一手来源与反证。"] },
  },
};

function define(spec: Spec): BaseTool {
  const copy = common[spec.category];
  return {
    slug: spec.slug, category: spec.category, mark: spec.mark, title: spec.title, short: spec.short,
    description: { tr: `${spec.short.tr} ${copy.detail.tr}`, en: `${spec.short.en} ${copy.detail.en}`, de: `${spec.short.de} ${copy.detail.de}`, zh: `${spec.short.zh}${copy.detail.zh}` },
    useCases: copy.useCases, steps: copy.steps,
  };
}

const specs: Spec[] = [
  { slug: "prompt-varsayim-haritasi", category: "prompt", mark: "132", title: { tr: "Prompt Varsayım Haritası", en: "Prompt Assumption Mapper", de: "Prompt-Annahmenkarte", zh: "提示词假设映射器" }, short: { tr: "Bir talimattaki örtük varsayımları, eksik bağlamı ve doğrulama sorularını çıkarın.", en: "Extract hidden assumptions, missing context, and validation questions from an instruction.", de: "Verdeckte Annahmen, fehlenden Kontext und Prüffragen aus Anweisungen ableiten.", zh: "从指令中提取隐含假设、缺失语境与验证问题。" } },
  { slug: "prompt-risk-kaydi", category: "prompt", mark: "133", title: { tr: "Prompt Risk Kaydı", en: "Prompt Risk Register", de: "Prompt-Risikoregister", zh: "提示词风险登记器" }, short: { tr: "Belirsizlik, veri sızıntısı, yetki ve başarısızlık risklerini puanlanabilir bir kayda dönüştürün.", en: "Turn ambiguity, data leakage, authority, and failure risks into a scorable register.", de: "Mehrdeutigkeit, Datenabfluss, Befugnisse und Fehler in ein bewertbares Register überführen.", zh: "将歧义、数据泄露、权限与失败风险整理为可评分登记表。" } },
  { slug: "prompt-cikti-sozlesmesi-testi", category: "prompt", mark: "134", title: { tr: "Prompt Çıktı Sözleşmesi Testi", en: "Prompt Output Contract Tester", de: "Prompt-Ausgabevertragstest", zh: "提示词输出契约测试器" }, short: { tr: "Beklenen alanları, biçimi ve başarısızlık davranışını test edilebilir bir sözleşmeye çevirin.", en: "Turn expected fields, formatting, and failure behavior into a testable contract.", de: "Erwartete Felder, Format und Fehlerverhalten in einen testbaren Vertrag übertragen.", zh: "把预期字段、格式与失败行为转换为可测试契约。" } },
  { slug: "prompt-varyasyon-laboratuvari", category: "prompt", mark: "135", title: { tr: "Prompt Varyasyon Laboratuvarı", en: "Prompt Variation Lab", de: "Prompt-Variationslabor", zh: "提示词变体实验室" }, short: { tr: "Aynı hedef için kısa, yapılandırılmış ve sınırları güçlü prompt varyasyonları üretin.", en: "Create concise, structured, and boundary-strong prompt variants for one goal.", de: "Knappe, strukturierte und klar begrenzte Prompt-Varianten für ein Ziel erstellen.", zh: "为同一目标生成简洁、结构化且边界清晰的提示词变体。" } },
  { slug: "prompt-sikistirma-yardimcisi", category: "prompt", mark: "136", title: { tr: "Prompt Sıkıştırma Yardımcısı", en: "Prompt Compression Assistant", de: "Prompt-Komprimierungsassistent", zh: "提示词压缩助手" }, short: { tr: "Tekrarları ve düşük değerli ifadeleri belirleyerek anlamı koruyan daha kısa bir taslak hazırlayın.", en: "Identify repetition and low-value phrasing to draft a shorter prompt that preserves intent.", de: "Wiederholungen und schwache Formulierungen erkennen und die Absicht kompakt erhalten.", zh: "识别重复和低价值措辞，生成保留意图的精简草稿。" } },
  { slug: "cumle-sadelestirici", category: "text", mark: "137", title: { tr: "Cümle Sadeleştirici", en: "Sentence Simplifier", de: "Satzvereinfacher", zh: "句子简化器" }, short: { tr: "Uzun cümleleri, edilgen yapıları ve gereksiz dolgu sözlerini açıklanabilir biçimde işaretleyin.", en: "Flag long sentences, passive constructions, and unnecessary filler with explainable rules.", de: "Lange Sätze, Passivformen und Füllwörter nachvollziehbar markieren.", zh: "以可解释规则标记长句、被动结构和冗余词。" } },
  { slug: "kapsayici-dil-inceleyici", category: "text", mark: "138", title: { tr: "Kapsayıcı Dil İnceleyici", en: "Inclusive Language Reviewer", de: "Inklusive-Sprachprüfung", zh: "包容性语言检查器" }, short: { tr: "Dışlayıcı veya gereksiz genelleyici ifadeleri bulup bağlama duyarlı gözden geçirme notları oluşturun.", en: "Find exclusionary or overgeneralized language and create context-aware review notes.", de: "Ausgrenzende oder pauschale Sprache finden und kontextsensible Hinweise erstellen.", zh: "发现排斥性或过度概括用语，并生成结合语境的审查提示。" } },
  { slug: "ton-tutarliligi-inceleyici", category: "text", mark: "139", title: { tr: "Ton Tutarlılığı İnceleyici", en: "Tone Consistency Reviewer", de: "Ton-Konsistenzprüfung", zh: "语气一致性检查器" }, short: { tr: "Metin bölümlerindeki resmiyet, kesinlik ve duygu değişimlerini karşılaştırın.", en: "Compare shifts in formality, certainty, and sentiment across text sections.", de: "Wechsel bei Formalität, Gewissheit und Stimmung zwischen Textabschnitten vergleichen.", zh: "比较不同文本段落的正式度、确定性与情绪变化。" } },
  { slug: "toplanti-notu-yapilandirici", category: "text", mark: "140", title: { tr: "Toplantı Notu Yapılandırıcı", en: "Meeting Notes Structurer", de: "Besprechungsnotizen-Strukturierer", zh: "会议笔记结构化工具" }, short: { tr: "Dağınık notları gündem, karar, açık soru, sorumlu ve tarih başlıklarına ayırın.", en: "Organize raw notes into agenda, decisions, open questions, owners, and dates.", de: "Rohnotizen in Agenda, Entscheidungen, offene Fragen, Zuständige und Termine gliedern.", zh: "将零散笔记整理为议程、决策、待决问题、负责人和日期。" } },
  { slug: "aksiyon-maddesi-cikarici", category: "text", mark: "141", title: { tr: "Aksiyon Maddesi Çıkarıcı", en: "Action Item Extractor", de: "Aufgabenextraktor", zh: "行动项提取器" }, short: { tr: "Metindeki görev fiillerini, olası sorumluları ve tarihleri düzenlenebilir bir görev listesine çıkarın.", en: "Extract task verbs, likely owners, and dates into an editable action list.", de: "Aufgabenverben, mögliche Zuständige und Termine als bearbeitbare Liste extrahieren.", zh: "提取任务动词、可能负责人和日期，形成可编辑行动清单。" } },
  { slug: "baslik-varyasyon-laboratuvari", category: "text", mark: "142", title: { tr: "Başlık Varyasyon Laboratuvarı", en: "Headline Variation Lab", de: "Überschriften-Variationslabor", zh: "标题变体实验室" }, short: { tr: "Açıklık, özgüllük ve uzunluk hedeflerine göre başlık kalıpları ve değerlendirme tablosu üretin.", en: "Create headline patterns and a review matrix for clarity, specificity, and length.", de: "Überschriftenmuster und eine Prüftabelle für Klarheit, Spezifität und Länge erzeugen.", zh: "按清晰度、具体性和长度目标生成标题模式与评审表。" } },
  { slug: "atif-yer-tutucu-denetleyici", category: "text", mark: "143", title: { tr: "Atıf Yer Tutucu Denetleyici", en: "Citation Placeholder Auditor", de: "Zitationsplatzhalter-Prüfer", zh: "引用占位符审计器" }, short: { tr: "[kaynak gerekli], TODO ve eksik bağlantı işaretlerini satır bağlamıyla bulun.", en: "Find citation-needed markers, TODOs, and missing-link placeholders with line context.", de: "Zitationshinweise, TODOs und fehlende Links mit Zeilenkontext finden.", zh: "按行定位“需要来源”、TODO 与缺失链接占位符。" } },
  { slug: "json-schema-ornek-uretici", category: "data", mark: "144", title: { tr: "JSON Schema Örnek Üretici", en: "JSON Schema Example Generator", de: "JSON-Schema-Beispielgenerator", zh: "JSON Schema 示例生成器" }, short: { tr: "Bir JSON Schema'dan geçerli başlangıç örneği ve alan kontrol listesi türetin.", en: "Derive a valid starter example and field checklist from a JSON Schema.", de: "Aus einem JSON-Schema ein gültiges Startbeispiel und eine Feldliste ableiten.", zh: "从 JSON Schema 推导有效起始示例和字段检查表。" } },
  { slug: "csv-sutun-profilleyici", category: "data", mark: "145", title: { tr: "CSV Sütun Profilleyici", en: "CSV Column Profiler", de: "CSV-Spaltenprofiler", zh: "CSV 列分析器" }, short: { tr: "Sütun türü, boş değer, benzersizlik, aralık ve örnek dağılımlarını yerel olarak özetleyin.", en: "Summarize column types, missing values, uniqueness, ranges, and sample distributions locally.", de: "Spaltentypen, Fehlwerte, Eindeutigkeit, Bereiche und Stichproben lokal zusammenfassen.", zh: "在本地汇总列类型、缺失值、唯一性、范围与样本分布。" } },
  { slug: "csv-birlestirme-simulatoru", category: "data", mark: "146", title: { tr: "CSV Birleştirme Simülatörü", en: "CSV Join Simulator", de: "CSV-Join-Simulator", zh: "CSV 连接模拟器" }, short: { tr: "İki küçük tabloyu anahtar üzerinden inner, left veya full join ile önizleyin.", en: "Preview inner, left, or full joins between two small tables using a chosen key.", de: "Inner-, Left- oder Full-Joins zweier kleiner Tabellen per Schlüssel voranzeigen.", zh: "使用指定键预览两个小表的 inner、left 或 full join。" } },
  { slug: "json-patch-olusturucu", category: "data", mark: "147", title: { tr: "JSON Patch Oluşturucu", en: "JSON Patch Generator", de: "JSON-Patch-Generator", zh: "JSON Patch 生成器" }, short: { tr: "İki JSON belge arasındaki add, remove ve replace işlemlerini RFC 6902 taslağına dönüştürün.", en: "Turn differences between two JSON documents into an RFC 6902 add, remove, and replace draft.", de: "Unterschiede zweier JSON-Dokumente als RFC-6902-Entwurf mit add, remove und replace ausgeben.", zh: "将两个 JSON 文档的差异生成 RFC 6902 add、remove、replace 草稿。" } },
  { slug: "json-merge-patch-laboratuvari", category: "data", mark: "148", title: { tr: "JSON Merge Patch Laboratuvarı", en: "JSON Merge Patch Lab", de: "JSON-Merge-Patch-Labor", zh: "JSON Merge Patch 实验室" }, short: { tr: "RFC 7396 birleştirme yamasını güvenli örnek üzerinde üretin ve uygulama sonucunu önizleyin.", en: "Create an RFC 7396 merge patch and preview its application on a safe example.", de: "Einen RFC-7396-Merge-Patch erzeugen und seine Anwendung voranzeigen.", zh: "创建 RFC 7396 合并补丁并预览应用结果。" } },
  { slug: "api-sayfalama-planlayici", category: "data", mark: "149", title: { tr: "API Sayfalama Planlayıcı", en: "API Pagination Planner", de: "API-Paginierungsplaner", zh: "API 分页规划器" }, short: { tr: "Offset, cursor ve sayfa tabanlı akışlar için istek sınırı, tekrar deneme ve sonlanma kontrol listesi oluşturun.", en: "Build request limits, retry behavior, and termination checks for offset, cursor, or page pagination.", de: "Limits, Wiederholungen und Abbruchregeln für Offset-, Cursor- oder Seitenpaginierung planen.", zh: "为 offset、cursor 或 page 分页制定请求限制、重试与终止检查。" } },
  { slug: "http-durum-kodu-gezgini", category: "data", mark: "150", title: { tr: "HTTP Durum Kodu Gezgini", en: "HTTP Status Explorer", de: "HTTP-Status-Explorer", zh: "HTTP 状态码浏览器" }, short: { tr: "Durum kodunun anlamını, önbellek davranışını ve istemci eylemini hızlı bir referans olarak görün.", en: "Review status meaning, cache implications, and recommended client action as a quick reference.", de: "Bedeutung, Cache-Auswirkung und empfohlene Client-Aktion schnell nachschlagen.", zh: "快速查看状态码含义、缓存影响与建议客户端操作。" } },
  { slug: "mime-tipi-inceleyici", category: "data", mark: "151", title: { tr: "MIME Tipi İnceleyici", en: "MIME Type Inspector", de: "MIME-Typ-Prüfer", zh: "MIME 类型检查器" }, short: { tr: "Dosya uzantısı, beyan edilen Content-Type ve örnek magic byte sinyallerini karşılaştırın.", en: "Compare file extension, declared Content-Type, and sample magic-byte signals.", de: "Dateiendung, deklarierten Content-Type und Magic-Byte-Signale vergleichen.", zh: "比较文件扩展名、声明的 Content-Type 与 Magic Byte 信号。" } },
  { slug: "csv-markdown-donusturucu", category: "converter", mark: "152", title: { tr: "CSV → Markdown Dönüştürücü", en: "CSV to Markdown Converter", de: "CSV-zu-Markdown-Konverter", zh: "CSV 转 Markdown" }, short: { tr: "CSV satırlarını kaçışları doğru ve hizalama seçilebilir Markdown tabloya dönüştürün.", en: "Convert CSV rows into an escaped Markdown table with selectable alignment.", de: "CSV-Zeilen in eine korrekt escapte Markdown-Tabelle mit Ausrichtung umwandeln.", zh: "将 CSV 行转换为正确转义、可选择对齐方式的 Markdown 表格。" } },
  { slug: "tsv-csv-donusturucu", category: "converter", mark: "153", title: { tr: "TSV ↔ CSV Dönüştürücü", en: "TSV ↔ CSV Converter", de: "TSV-↔-CSV-Konverter", zh: "TSV ↔ CSV 转换器" }, short: { tr: "Sekme ve virgül ayrımlı tabloları tırnaklama kurallarını koruyarak dönüştürün.", en: "Convert tab- and comma-delimited tables while preserving quoting rules.", de: "Tabulator- und kommagetrennte Tabellen unter Beachtung von Anführungsregeln konvertieren.", zh: "在保留引号规则的前提下转换制表符和逗号分隔表格。" } },
  { slug: "sorgu-dizesi-json-donusturucu", category: "converter", mark: "154", title: { tr: "Sorgu Dizisi ↔ JSON", en: "Query String ↔ JSON", de: "Query-String ↔ JSON", zh: "查询字符串 ↔ JSON" }, short: { tr: "Tekrarlanan URL parametrelerini kaybetmeden query string ve JSON arasında dönüşüm yapın.", en: "Convert between query strings and JSON without losing repeated parameters.", de: "Query-Strings und JSON ohne Verlust wiederholter Parameter konvertieren.", zh: "在查询字符串与 JSON 之间转换，并保留重复参数。" } },
  { slug: "metin-ascii-tablo-donusturucu", category: "converter", mark: "155", title: { tr: "Metin → ASCII Tablo", en: "Text to ASCII Table", de: "Text-zu-ASCII-Tabelle", zh: "文本转 ASCII 表格" }, short: { tr: "Basit CSV, TSV veya JSON dizilerini terminal dostu sabit genişlikli tabloya dönüştürün.", en: "Convert simple CSV, TSV, or JSON arrays into terminal-friendly fixed-width tables.", de: "Einfaches CSV, TSV oder JSON in terminalfreundliche Tabellen mit fester Breite umwandeln.", zh: "将简单 CSV、TSV 或 JSON 数组转换为终端友好的等宽表格。" } },
  { slug: "renk-paleti-donusturucu", category: "converter", mark: "156", title: { tr: "Renk Paleti Dönüştürücü", en: "Color Palette Converter", de: "Farbpaletten-Konverter", zh: "调色板转换器" }, short: { tr: "HEX renk listesini CSS değişkenleri, JSON tokenları ve Tailwind taslağına dönüştürün.", en: "Convert HEX color lists into CSS variables, JSON tokens, and a Tailwind-style draft.", de: "HEX-Farblisten in CSS-Variablen, JSON-Tokens und Tailwind-Entwürfe umwandeln.", zh: "将 HEX 颜色列表转换为 CSS 变量、JSON Token 与 Tailwind 风格草稿。" } },
  { slug: "gizli-deger-redaksiyon-planlayici", category: "security", mark: "157", title: { tr: "Gizli Değer Redaksiyon Planlayıcı", en: "Secret Redaction Planner", de: "Secret-Redaktionsplaner", zh: "密钥脱敏规划器" }, short: { tr: "Anahtar, token ve bağlantı dizisi adaylarını türüne göre maskeleme planına dönüştürün.", en: "Turn key, token, and connection-string candidates into a type-aware redaction plan.", de: "Schlüssel-, Token- und Verbindungsstring-Kandidaten in einen typbezogenen Redaktionsplan überführen.", zh: "将密钥、令牌和连接字符串候选整理为按类型脱敏计划。" } },
  { slug: "takma-adlandirma-haritasi", category: "security", mark: "158", title: { tr: "Takma Adlandırma Haritası", en: "Pseudonymization Mapper", de: "Pseudonymisierungskarte", zh: "假名化映射器" }, short: { tr: "Kimlik alanlarını tutarlı yerel takma adlara çevirip geri dönüş ve anahtar yönetimi risklerini belgeleyin.", en: "Map identifier fields to consistent local pseudonyms and document reversibility and key-management risks.", de: "Identifikatoren konsistent pseudonymisieren und Umkehr- sowie Schlüsselrisiken dokumentieren.", zh: "将标识字段映射为一致的本地假名，并记录可逆性与密钥管理风险。" } },
  { slug: "guvenlik-kontrol-listesi-olusturucu", category: "security", mark: "159", title: { tr: "Güvenlik Kontrol Listesi Oluşturucu", en: "Security Checklist Builder", de: "Sicherheitschecklisten-Generator", zh: "安全检查清单生成器" }, short: { tr: "Varlık, tehdit ve değişiklik türüne göre sahipli ve kanıt alanlı güvenlik kontrol listesi hazırlayın.", en: "Build an owned, evidence-ready security checklist from asset, threat, and change type.", de: "Aus Asset, Bedrohung und Änderung eine Sicherheitscheckliste mit Zuständigkeit und Nachweis erstellen.", zh: "根据资产、威胁与变更类型创建包含负责人和证据栏的安全清单。" } },
  { slug: "jwt-sure-zaman-cizelgesi", category: "security", mark: "160", title: { tr: "JWT Süre Zaman Çizelgesi", en: "JWT Expiry Timeline", de: "JWT-Ablaufzeitachse", zh: "JWT 到期时间线" }, short: { tr: "iat, nbf ve exp claim'lerini saat farkı ve tolerans senaryolarıyla zaman çizelgesinde karşılaştırın.", en: "Compare iat, nbf, and exp claims on a timeline with clock-skew and tolerance scenarios.", de: "iat, nbf und exp mit Uhrabweichung und Toleranz als Zeitachse vergleichen.", zh: "结合时钟偏差与容差情景比较 iat、nbf、exp 时间线。" } },
  { slug: "parola-ihlal-hijyeni-kontrolu", category: "security", mark: "161", title: { tr: "Parola İhlal Hijyeni Kontrolü", en: "Password Breach Hygiene Check", de: "Passwort-Leak-Hygieneprüfung", zh: "密码泄露卫生检查" }, short: { tr: "Parolayı ağa göndermeden yeniden kullanım, uzunluk, desen ve olay sonrası adımları değerlendirin.", en: "Review reuse, length, patterns, and post-incident actions without sending the password anywhere.", de: "Wiederverwendung, Länge, Muster und Maßnahmen nach Vorfällen ohne Upload prüfen.", zh: "无需联网即可检查密码复用、长度、模式与泄露后措施。" } },
  { slug: "gizlilik-bildirimi-bosluk-tarayicisi", category: "security", mark: "162", title: { tr: "Gizlilik Bildirimi Boşluk Tarayıcısı", en: "Privacy Notice Gap Scanner", de: "Datenschutzhinweis-Lückenprüfung", zh: "隐私声明缺口扫描器" }, short: { tr: "Amaç, veri türü, saklama, haklar, alıcılar ve iletişim başlıklarındaki olası eksikleri işaretleyin.", en: "Flag potential gaps in purpose, data types, retention, rights, recipients, and contact sections.", de: "Mögliche Lücken bei Zweck, Datenarten, Aufbewahrung, Rechten, Empfängern und Kontakt markieren.", zh: "标记目的、数据类型、保留期、权利、接收方和联系方式的潜在缺口。" } },
  { slug: "kredi-amortisman-tahminleyici", category: "calculation", mark: "163", title: { tr: "Kredi Amortisman Tahminleyici", en: "Loan Amortization Estimator", de: "Kredit-Tilgungsrechner", zh: "贷款摊还估算器" }, short: { tr: "Ana para, oran, vade ve ek ödeme için aylık ödeme ve örnek amortisman tablosu hesaplayın.", en: "Estimate monthly payments and an amortization schedule from principal, rate, term, and extra payments.", de: "Monatsrate und Tilgungsplan aus Kapital, Zins, Laufzeit und Sonderzahlung schätzen.", zh: "根据本金、利率、期限与额外还款估算月供和摊还表。" } },
  { slug: "enflasyon-satin-alma-gucu", category: "calculation", mark: "164", title: { tr: "Enflasyon Satın Alma Gücü", en: "Inflation Purchasing Power", de: "Inflations-Kaufkraftrechner", zh: "通胀购买力计算器" }, short: { tr: "Tutarın sabit enflasyon varsayımı altında gelecekteki veya geçmişteki reel karşılığını karşılaştırın.", en: "Compare future or past real value under an explicit constant-inflation assumption.", de: "Künftige oder frühere Kaufkraft unter expliziter konstanter Inflationsannahme vergleichen.", zh: "在明确的恒定通胀假设下比较未来或过去实际价值。" } },
  { slug: "basabas-noktasi-hesaplayici", category: "calculation", mark: "165", title: { tr: "Başabaş Noktası Hesaplayıcı", en: "Break-even Calculator", de: "Break-even-Rechner", zh: "盈亏平衡计算器" }, short: { tr: "Sabit maliyet, birim fiyat ve değişken maliyetten başabaş adedi ile ciroyu hesaplayın.", en: "Calculate break-even units and revenue from fixed cost, unit price, and variable cost.", de: "Break-even-Menge und Umsatz aus Fixkosten, Preis und variablen Kosten berechnen.", zh: "根据固定成本、单价与单位变动成本计算盈亏平衡销量和收入。" } },
  { slug: "marj-kar-orani-hesaplayici", category: "calculation", mark: "166", title: { tr: "Marj ve Kâr Oranı Hesaplayıcı", en: "Margin & Markup Calculator", de: "Marge- & Aufschlagsrechner", zh: "毛利率与加价率计算器" }, short: { tr: "Maliyet, satış fiyatı, brüt marj ve markup arasındaki farkı çift yönlü hesaplayın.", en: "Calculate cost, selling price, gross margin, and markup in both directions.", de: "Kosten, Verkaufspreis, Bruttomarge und Aufschlag in beide Richtungen berechnen.", zh: "双向计算成本、售价、毛利率与加价率。" } },
  { slug: "olasilik-hesaplayici", category: "calculation", mark: "167", title: { tr: "Olasılık Hesaplayıcı", en: "Probability Calculator", de: "Wahrscheinlichkeitsrechner", zh: "概率计算器" }, short: { tr: "Bağımsız olaylar için birleşim, kesişim, en az bir ve koşullu olasılık senaryolarını hesaplayın.", en: "Calculate union, intersection, at-least-one, and conditional scenarios for independent events.", de: "Vereinigung, Schnitt, mindestens ein Ereignis und bedingte Szenarien berechnen.", zh: "计算独立事件的并集、交集、至少一个与条件概率情景。" } },
  { slug: "orneklem-buyuklugu-tahminleyici", category: "calculation", mark: "168", title: { tr: "Örneklem Büyüklüğü Tahminleyici", en: "Sample Size Estimator", de: "Stichprobengrößen-Schätzer", zh: "样本量估算器" }, short: { tr: "Güven düzeyi, hata payı, oran ve evren için yaklaşık anket örneklemi hesaplayın.", en: "Estimate survey sample size from confidence, margin of error, proportion, and population.", de: "Stichprobengröße aus Konfidenz, Fehlerspanne, Anteil und Grundgesamtheit schätzen.", zh: "根据置信度、误差范围、比例和总体估算调查样本量。" } },
  { slug: "karar-matrisi", category: "general", mark: "169", title: { tr: "Karar Matrisi", en: "Decision Matrix", de: "Entscheidungsmatrix", zh: "决策矩阵" }, short: { tr: "Seçenekleri ağırlıklı ölçütlerle puanlayıp duyarlılık notlarıyla karşılaştırın.", en: "Compare options using weighted criteria and sensitivity notes.", de: "Optionen anhand gewichteter Kriterien und Sensitivitätshinweisen vergleichen.", zh: "使用加权标准和敏感性说明比较选项。" } },
  { slug: "smart-hedef-olusturucu", category: "general", mark: "170", title: { tr: "SMART Hedef Oluşturucu", en: "SMART Goal Builder", de: "SMART-Zielgenerator", zh: "SMART 目标生成器" }, short: { tr: "Bir niyeti özgül, ölçülebilir, ulaşılabilir, ilgili ve zaman sınırlı hedef taslağına dönüştürün.", en: "Turn an intention into a specific, measurable, achievable, relevant, time-bound goal draft.", de: "Eine Absicht in ein spezifisches, messbares, erreichbares, relevantes und terminiertes Ziel überführen.", zh: "将意图转换为具体、可衡量、可实现、相关且有时限的目标草稿。" } },
  { slug: "gundem-olusturucu", category: "general", mark: "171", title: { tr: "Gündem Oluşturucu", en: "Agenda Builder", de: "Agenda-Generator", zh: "议程生成器" }, short: { tr: "Toplantı hedefi, katılımcılar ve sürelerden zaman kutulu gündem ile karar noktaları üretin.", en: "Build a time-boxed agenda and decision points from meeting goal, participants, and durations.", de: "Aus Ziel, Teilnehmenden und Dauer eine zeitlich gegliederte Agenda mit Entscheidungen erstellen.", zh: "根据会议目标、参与者和时长生成分时议程与决策点。" } },
  { slug: "vardiya-plani-formatlayici", category: "general", mark: "172", title: { tr: "Vardiya Planı Formatlayıcı", en: "Shift Schedule Formatter", de: "Schichtplan-Formatierer", zh: "排班表格式化器" }, short: { tr: "Kişi, başlangıç ve bitiş satırlarını çakışma ve dinlenme uyarılı tabloya dönüştürün.", en: "Turn person, start, and end rows into a table with overlap and rest warnings.", de: "Person-, Start- und Endzeilen als Tabelle mit Überlappungs- und Ruhehinweisen formatieren.", zh: "将人员、开始和结束记录转换为含重叠与休息提示的排班表。" } },
  { slug: "kontrol-listesi-duzenleyici", category: "general", mark: "173", title: { tr: "Kontrol Listesi Düzenleyici", en: "Checklist Composer", de: "Checklisten-Editor", zh: "检查清单编排器" }, short: { tr: "Dağınık görevleri sahip, öncelik, kanıt ve tamamlanma ölçütlü bir kontrol listesine dönüştürün.", en: "Turn loose tasks into a checklist with owner, priority, evidence, and completion criteria.", de: "Lose Aufgaben in eine Checkliste mit Zuständigkeit, Priorität, Nachweis und Abschlusskriterium überführen.", zh: "将零散任务整理为包含负责人、优先级、证据与完成标准的清单。" } },
  { slug: "ajan-gorev-ayristirici", category: "ai", mark: "174", title: { tr: "Ajan Görev Ayrıştırıcı", en: "Agent Task Decomposer", de: "Agenten-Aufgabenzerlegung", zh: "智能体任务拆解器" }, short: { tr: "Karmaşık hedefi bağımlılık, kontrol noktası, giriş ve beklenen çıktı içeren yürütülebilir adımlara ayırın.", en: "Break a complex goal into executable steps with dependencies, checkpoints, inputs, and expected outputs.", de: "Komplexe Ziele in ausführbare Schritte mit Abhängigkeiten, Kontrollen, Eingaben und Ausgaben zerlegen.", zh: "将复杂目标拆解为含依赖、检查点、输入和预期输出的可执行步骤。" } },
  { slug: "baglam-oncelik-planlayici", category: "ai", mark: "175", title: { tr: "Bağlam Öncelik Planlayıcı", en: "Context Priority Planner", de: "Kontext-Prioritätsplaner", zh: "上下文优先级规划器" }, short: { tr: "Bağlam parçalarını gereklilik, güncellik, kaynak kalitesi ve token maliyetine göre sıralayın.", en: "Rank context chunks by necessity, recency, source quality, and token cost.", de: "Kontextblöcke nach Notwendigkeit, Aktualität, Quellenqualität und Tokenkosten priorisieren.", zh: "按必要性、时效性、来源质量和 Token 成本排列上下文块。" } },
  { slug: "halusinasyon-risk-kontrol-listesi", category: "ai", mark: "176", title: { tr: "Halüsinasyon Risk Kontrol Listesi", en: "Hallucination Risk Checklist", de: "Halluzinationsrisiko-Checkliste", zh: "幻觉风险检查清单" }, short: { tr: "Doğrulanabilir iddia, kaynak, güncellik ve belirsizlik kontrollerini göreve özel listeye dönüştürün.", en: "Turn claim verification, sourcing, freshness, and uncertainty checks into a task-specific list.", de: "Prüfbare Aussagen, Quellen, Aktualität und Unsicherheit als aufgabenspezifische Liste strukturieren.", zh: "将可验证主张、来源、时效性与不确定性检查整理为任务专用清单。" } },
  { slug: "rag-kaynak-kalite-puanlayici", category: "ai", mark: "177", title: { tr: "RAG Kaynak Kalite Puanlayıcı", en: "RAG Source Quality Scorer", de: "RAG-Quellenqualitätsbewertung", zh: "RAG 来源质量评分器" }, short: { tr: "Kaynakları birincillik, güncellik, kapsam, alıntılanabilirlik ve çelişki bakımından puanlayın.", en: "Score sources for primariness, freshness, coverage, citability, and contradiction risk.", de: "Quellen nach Primärnähe, Aktualität, Abdeckung, Zitierbarkeit und Widerspruchsrisiko bewerten.", zh: "按一手性、时效性、覆盖度、可引用性与矛盾风险评估来源。" } },
  { slug: "model-karsilastirma-rubrigi", category: "ai", mark: "178", title: { tr: "Model Karşılaştırma Rubriği", en: "Model Comparison Rubric", de: "Modellvergleichs-Rubrik", zh: "模型比较量表" }, short: { tr: "Modelleri aynı test setinde doğruluk, gecikme, maliyet, gizlilik ve hata türleriyle karşılaştıracak rubrik oluşturun.", en: "Build a rubric to compare models on accuracy, latency, cost, privacy, and error types using one test set.", de: "Modelle mit einem Testset nach Genauigkeit, Latenz, Kosten, Datenschutz und Fehlertypen vergleichen.", zh: "使用同一测试集按准确性、延迟、成本、隐私和错误类型比较模型。" } },
  { slug: "paket-manifestosu-denetleyici", category: "codeSecurity", mark: "179", title: { tr: "Paket Manifestosu Denetleyici", en: "Package Manifest Auditor", de: "Paketmanifest-Prüfer", zh: "包清单审计器" }, short: { tr: "package.json bağımlılık aralıkları, script'ler, motorlar ve yayın alanları için açıklanabilir risk notları üretin.", en: "Produce explainable risk notes for package.json ranges, scripts, engines, and publishing fields.", de: "Nachvollziehbare Risikohinweise zu package.json-Bereichen, Skripten, Engines und Publishing-Feldern erzeugen.", zh: "针对 package.json 版本范围、脚本、引擎和发布字段生成可解释风险提示。" } },
  { slug: "npm-script-risk-tarayicisi", category: "codeSecurity", mark: "180", title: { tr: "npm Script Risk Tarayıcısı", en: "npm Script Risk Scanner", de: "npm-Skript-Risikoscanner", zh: "npm 脚本风险扫描器" }, short: { tr: "install yaşam döngüsü, ağ indirme, shell zinciri ve silme komutu sinyallerini çalıştırmadan bulun.", en: "Find install lifecycle, network download, shell chaining, and deletion signals without execution.", de: "Install-Lifecycle, Netzwerkdownloads, Shell-Ketten und Löschsignale ohne Ausführung finden.", zh: "不执行脚本即可发现安装生命周期、网络下载、Shell 链接与删除命令信号。" } },
  { slug: "regex-karmasiklik-on-kontrolu", category: "codeSecurity", mark: "181", title: { tr: "Regex Karmaşıklık Ön Kontrolü", en: "Regex Complexity Pre-check", de: "Regex-Komplexitäts-Vorprüfung", zh: "正则复杂度预检查" }, short: { tr: "İç içe niceleyici, belirsiz tekrar ve geniş wildcard desenlerini ReDoS ön incelemesi için işaretleyin.", en: "Flag nested quantifiers, ambiguous repetition, and broad wildcards for ReDoS pre-review.", de: "Verschachtelte Quantifizierer, mehrdeutige Wiederholung und breite Wildcards für ReDoS markieren.", zh: "标记嵌套量词、歧义重复和宽泛通配模式，辅助 ReDoS 预审。" } },
  { slug: "dockerfile-guvenlik-on-kontrolu", category: "codeSecurity", mark: "182", title: { tr: "Dockerfile Güvenlik Ön Kontrolü", en: "Dockerfile Security Pre-check", de: "Dockerfile-Sicherheitsprüfung", zh: "Dockerfile 安全预检查" }, short: { tr: "Root kullanıcı, kayan etiket, sır kopyalama, geniş izin ve önbellek kalıntılarını satır bazında işaretleyin.", en: "Flag root user, floating tags, copied secrets, broad permissions, and cache residue by line.", de: "Root-Nutzer, schwimmende Tags, kopierte Secrets, breite Rechte und Cache-Reste zeilenweise markieren.", zh: "按行标记 root 用户、浮动标签、复制密钥、宽泛权限与缓存残留。" } },
  { slug: "github-actions-izin-denetleyici", category: "codeSecurity", mark: "183", title: { tr: "GitHub Actions İzin Denetleyici", en: "GitHub Actions Permissions Auditor", de: "GitHub-Actions-Berechtigungsprüfung", zh: "GitHub Actions 权限审计器" }, short: { tr: "Workflow izinleri, sabitlenmemiş action referansları ve tehlikeli pull_request_target kullanımını ön tarayın.", en: "Pre-scan workflow permissions, unpinned action references, and risky pull_request_target usage.", de: "Workflow-Rechte, nicht gepinnte Actions und riskantes pull_request_target vorprüfen.", zh: "预扫描工作流权限、未固定 Action 引用与高风险 pull_request_target 用法。" } },
  { slug: "kaynak-guvenilirlik-matrisi", category: "research", mark: "184", title: { tr: "Kaynak Güvenilirlik Matrisi", en: "Source Reliability Matrix", de: "Quellenverlässlichkeitsmatrix", zh: "来源可靠性矩阵" }, short: { tr: "Kaynakları yazarlık, birincillik, yöntem, güncellik, çıkar çatışması ve doğrulanabilirlikle karşılaştırın.", en: "Compare sources by authorship, primariness, method, freshness, conflicts, and verifiability.", de: "Quellen nach Urheberschaft, Primärnähe, Methode, Aktualität, Konflikten und Prüfbarkeit vergleichen.", zh: "按作者、一手性、方法、时效性、利益冲突与可验证性比较来源。" } },
  { slug: "arastirma-sorusu-ayristirici", category: "research", mark: "185", title: { tr: "Araştırma Sorusu Ayrıştırıcı", en: "Research Question Decomposer", de: "Forschungsfragen-Zerlegung", zh: "研究问题拆解器" }, short: { tr: "Geniş soruyu kavramlar, alt sorular, kapsam, kanıt türü ve dışlama ölçütlerine ayırın.", en: "Break a broad question into concepts, subquestions, scope, evidence types, and exclusion criteria.", de: "Breite Fragen in Konzepte, Teilfragen, Umfang, Evidenztypen und Ausschlusskriterien zerlegen.", zh: "将宽泛问题拆解为概念、子问题、范围、证据类型与排除标准。" } },
  { slug: "kanit-sentez-tablosu", category: "research", mark: "186", title: { tr: "Kanıt Sentez Tablosu", en: "Evidence Synthesis Table", de: "Evidenzsynthese-Tabelle", zh: "证据综合表" }, short: { tr: "Kaynak notlarını iddia, yöntem, bulgu, sınırlama, çelişki ve güven düzeyi sütunlarında birleştirin.", en: "Combine source notes into claim, method, finding, limitation, contradiction, and confidence columns.", de: "Quellennotizen nach Aussage, Methode, Befund, Grenze, Widerspruch und Vertrauen zusammenführen.", zh: "按主张、方法、发现、局限、矛盾和置信度汇总来源笔记。" } },
];

export const expansionTools: BaseTool[] = specs.map(define);
export const expansionToolSlugs = new Set(specs.map((spec) => spec.slug));
