import type { Locale } from "./site";
import type { ArticleSection, Post } from "./posts";
import type { LocalizedGuide } from "./localized-guides";

type L = Record<Locale, string>;
type Point = { heading: L; body: L };
type Spec = { slug: string; relatedTools: string[]; title: L; excerpt: L; category: L; points: [Point, Point, Point] };

const method: Record<Locale, string[]> = {
  tr: ["Yöntemi tekrar edilebilir kılmak için girdi biçimini, varsayımları ve kabul ölçütlerini işlemden önce yazın. ByteQuant örnek verisi başlangıç içindir; gerçek iş akışında temsil edici iyi, bozuk ve sınır durumlarını ayrı ayrı deneyin.", "Sonuçta doğrudan gözlem, araç çıkarımı ve kullanıcı kararını birbirinden ayırın. Bir puan veya yeşil rozet; kimlik, güvenlik, hukuki uyum ya da kaynak doğruluğu garantisi değildir.", "Akışı Yerel Ajanda planlayıp İş İstasyonunda sürümlendirin. Her düğümün çıktısını sonraki girdiye aktarmadan önce inceleyin; hassas veriyi çıkarın ve yüksek etkili kararı bağımsız bir kaynak veya uzmanla doğrulayın."],
  en: ["Make the method repeatable by recording input format, assumptions, and acceptance criteria before processing. ByteQuant demos are starting points; test representative good, malformed, and boundary cases in the real workflow.", "Separate direct observation, tool inference, and human decision in the result. A score or green badge is not proof of identity, security, legal compliance, or source accuracy.", "Plan the flow in Local Agent and version it in Workstation. Review every node output before handoff, remove sensitive data, and verify high-impact decisions with an independent source or qualified reviewer."],
  de: ["Eingabeformat, Annahmen und Abnahmekriterien vor der Verarbeitung dokumentieren. ByteQuant-Beispiele sind ein Einstieg; im echten Ablauf repräsentative gültige, fehlerhafte und Grenzfälle testen.", "Direkte Beobachtung, Werkzeugschluss und menschliche Entscheidung im Ergebnis trennen. Eine Punktzahl oder ein grünes Symbol beweist weder Identität, Sicherheit, Rechtskonformität noch Quellenrichtigkeit.", "Ablauf im lokalen Agenten planen und in der Workstation versionieren. Jede Knotenausgabe vor der Übergabe prüfen, sensible Daten entfernen und folgenreiche Entscheidungen unabhängig verifizieren."],
  zh: ["处理前记录输入格式、假设和验收标准，使方法可重复。ByteQuant 示例只是起点；真实流程应分别测试代表性的正确、错误与边界案例。", "在结果中区分直接观察、工具推断与人工决策。分数或绿色标记并不能证明身份、安全、法律合规或来源准确。", "先在本地助手中规划，再在工作站中进行版本管理。每个节点输出传递前都要检查，移除敏感数据，并通过独立来源或合格人员核验高影响决策。"],
};
const bullets: Record<Locale, string[]> = {
  tr: ["Sentetik örnekle küçük başlayın.", "Hata ve durdurma koşullarını yazın.", "Kaynak, tarih ve yöntem notunu çıktıyla saklayın."],
  en: ["Start small with synthetic data.", "Write failure and stop conditions.", "Keep source, date, and method notes with the output."],
  de: ["Klein mit synthetischen Daten beginnen.", "Fehler- und Abbruchbedingungen notieren.", "Quelle, Datum und Methode mit der Ausgabe speichern."],
  zh: ["先用少量合成数据测试。", "记录失败与停止条件。", "将来源、日期和方法说明与输出一起保存。"],
};
const depthCopy: Record<Locale, {
  evidence: string;
  walkthrough: string;
  walkthroughBody: string;
  walkthroughBullets: string[];
  quality: string;
  qualityBody: string;
  qualityBullets: string[];
}> = {
  tr: {
    evidence: "Bu adımı gerçek veriye uygulamadan önce küçük bir sentetik örnekle beklenen sonucu yazın. Normal durumun yanında eksik alan, hatalı biçim, çok uzun girdi ve çelişkili bilgi örneklerini de deneyin. Çıktıda hangi bölümün doğrudan girdiden geldiğini, hangisinin kural tabanlı çıkarım olduğunu ve hangi kararın insan onayı gerektirdiğini görünür biçimde ayırın.",
    walkthrough: "Uygulamalı örnek: girdiden doğrulanmış teslimata",
    walkthroughBody: "Önce güvenli bir örnek girdi hazırlayın ve kişisel veri, sır ya da lisanslı içeriği kaldırın. Ardından aşağıdaki üç kontrolü sırayla uygulayın; her aşamada çıktıyı önceki sürümle karşılaştırın ve yalnızca açık kabul ölçütü karşılandığında ilerleyin. Bir araç uyarı verirse sonucu zorla kullanmak yerine girdiyi küçültün, belirsizliği yazın ve son doğrulanmış aşamaya geri dönün.",
    walkthroughBullets: ["Başlangıç girdisini ve beklenen sonucu birlikte kaydedin.", "Her aşamadan sonra değişen alanları ve gerekçesini not edin.", "Son çıktıyı farklı bir örnek ve bağımsız bir gözden geçirenle yeniden sınayın.", "Paylaşılacak dosyada kaynak, tarih, sürüm ve bilinen sınırları koruyun."],
    quality: "Kalite kapısı, hata senaryosu ve güvenli teslim",
    qualityBody: "Teslimden önce sözdizimi doğruluğu tek başına yeterli değildir. İçerik bütünlüğünü, erişilebilirliği, dil tutarlılığını, gizlilik riskini ve geri alınabilirliği ayrı ayrı kontrol edin. Yüksek etkili finans, hukuk, güvenlik veya kimlik kararlarında ByteQuant çıktısını ön kontrol olarak kabul edin; güncel birincil kaynak ya da yetkili uzman doğrulaması olmadan kesin sonuç gibi sunmayın.",
    qualityBullets: ["Başarı ölçütü gözlenebilir ve tekrar edilebilir mi?", "Boş, bozuk, aşırı büyük ve kötü niyetli girdi güvenli biçimde duruyor mu?", "Sonuç ile araç çıkarımı ve insan kararı birbirinden ayrılıyor mu?", "Hassas veri, dış bağlantı ve lisans koşulları son kez kontrol edildi mi?", "Değişiklik günlüğü ve geri dönüş kopyası hazır mı?"],
  },
  en: {
    evidence: "Before using this step on real data, write the expected result for a small synthetic example. Test missing fields, malformed input, oversized content, and conflicting information as well as the happy path. In the output, clearly separate what came directly from the input, what was inferred by a rule, and what still requires human approval.",
    walkthrough: "Applied walkthrough: from input to verified handoff",
    walkthroughBody: "Begin with a safe sample and remove personal data, secrets, or licensed material. Apply the three checks below in order, compare every stage with the previous version, and continue only when an explicit acceptance criterion passes. If a tool raises a warning, reduce the input, record the uncertainty, and return to the last verified stage instead of forcing the result forward.",
    walkthroughBullets: ["Record the starting input and expected result together.", "After each stage, note changed fields and the reason for the change.", "Retest the final output with a different example and an independent reviewer.", "Keep source, date, version, and known limitations with the shared artifact."],
    quality: "Quality gate, failure path, and safe delivery",
    qualityBody: "Syntax validity alone is not enough for delivery. Review content integrity, accessibility, language consistency, privacy risk, and rollback separately. For high-impact financial, legal, security, or identity decisions, treat ByteQuant output as a pre-check and do not present it as a final determination without a current primary source or qualified reviewer.",
    qualityBullets: ["Is the success criterion observable and repeatable?", "Do empty, malformed, oversized, and adversarial inputs stop safely?", "Are result, tool inference, and human decision clearly separated?", "Were sensitive data, external links, and license conditions checked once more?", "Is a change log and rollback copy available?"],
  },
  de: {
    evidence: "Vor der Anwendung auf echte Daten das erwartete Ergebnis an einem kleinen synthetischen Beispiel festhalten. Neben dem Normalfall auch fehlende Felder, fehlerhafte Formate, übergroße Inhalte und widersprüchliche Angaben testen. In der Ausgabe klar trennen, was direkt aus der Eingabe stammt, was eine Regel ableitet und was menschliche Freigabe benötigt.",
    walkthrough: "Praxisablauf: von der Eingabe zur geprüften Übergabe",
    walkthroughBody: "Mit einem sicheren Beispiel beginnen und Personendaten, Geheimnisse sowie lizenzierte Inhalte entfernen. Die drei Prüfungen in Reihenfolge anwenden, jede Stufe mit der Vorversion vergleichen und nur bei erfülltem Abnahmekriterium fortfahren. Bei einer Warnung Eingabe verkleinern, Unsicherheit dokumentieren und zur letzten geprüften Stufe zurückkehren.",
    walkthroughBullets: ["Ausgangseingabe und erwartetes Ergebnis gemeinsam speichern.", "Nach jeder Stufe geänderte Felder und Begründung notieren.", "Endausgabe mit anderem Beispiel und unabhängiger Prüfung erneut testen.", "Quelle, Datum, Version und bekannte Grenzen am geteilten Artefakt belassen."],
    quality: "Qualitätsgrenze, Fehlerpfad und sichere Übergabe",
    qualityBody: "Gültige Syntax reicht für eine Übergabe nicht aus. Inhaltsintegrität, Barrierefreiheit, Sprachkonsistenz, Datenschutzrisiko und Rücknahmefähigkeit getrennt prüfen. Bei folgenreichen Finanz-, Rechts-, Sicherheits- oder Identitätsentscheidungen ist die ByteQuant-Ausgabe eine Vorprüfung und kein Endurteil ohne aktuelle Primärquelle oder qualifizierte Prüfung.",
    qualityBullets: ["Ist das Erfolgskriterium beobachtbar und wiederholbar?", "Stoppen leere, fehlerhafte, übergroße und missbräuchliche Eingaben sicher?", "Sind Ergebnis, Werkzeugschluss und menschliche Entscheidung getrennt?", "Wurden sensible Daten, externe Links und Lizenzbedingungen erneut geprüft?", "Sind Änderungsprotokoll und Rücknahmekopie vorhanden?"],
  },
  zh: {
    evidence: "在用于真实数据之前，先用小型合成示例写明预期结果。除正常情况外，还要测试缺失字段、错误格式、超大内容与矛盾信息。输出中应明确区分直接来自输入的内容、规则推断的内容，以及仍需人工批准的决定。",
    walkthrough: "实操流程：从输入到经核验的交付",
    walkthroughBody: "先准备安全样例，移除个人数据、密钥与受许可限制的内容。按顺序执行下列三项检查，每一步都与上一版本比较，只有明确验收条件通过后才继续。工具发出警告时，应缩小输入、记录不确定性并返回最近一次已核验阶段，而不是强行推进结果。",
    walkthroughBullets: ["同时保存初始输入与预期结果。", "每一步记录变更字段及变更理由。", "使用不同样例和独立审核者重新测试最终输出。", "分享内容应保留来源、日期、版本与已知限制。"],
    quality: "质量门槛、失败路径与安全交付",
    qualityBody: "语法有效并不足以完成交付。还应分别检查内容完整性、可访问性、语言一致性、隐私风险与可回滚性。对于高影响的金融、法律、安全或身份决定，ByteQuant 输出只能作为预检查；没有当前一手来源或合格审核者时，不应作为最终结论。",
    qualityBullets: ["成功标准是否可观察、可重复？", "空、错误、超大和恶意输入是否会安全停止？", "结果、工具推断与人工决定是否清楚分开？", "是否再次检查敏感数据、外部链接和许可条件？", "是否保留变更记录与回滚副本？"],
  },
};
const L = (tr: string, en: string, de: string, zh: string): L => ({ tr, en, de, zh });
const P = (heading: L, body: L): Point => ({ heading, body });

const specs: Spec[] = [
  {
    slug: "local-agent-workstation-verifiable-planning", relatedTools: ["ajan-gorev-ayristirici", "baglam-oncelik-planlayici", "halusinasyon-risk-kontrol-listesi"],
    title: L("Yerel Ajan ve İş İstasyonu ile Doğrulanabilir Akış Planlama", "Verifiable Workflow Planning with Local Agent and Workstation", "Prüfbare Ablaufplanung mit lokalem Agenten und Workstation", "使用本地助手与工作站规划可验证流程"),
    excerpt: L("Hedefi araç sırasına, güvenlik sınırına ve geri alınabilir düğümlere dönüştürün.", "Turn an outcome into a tool order, safety boundary, and reversible nodes.", "Ein Ziel in Werkzeugreihenfolge, Sicherheitsgrenze und umkehrbare Knoten überführen.", "将目标转换为工具顺序、安全边界与可撤销节点。"), category: L("Yerel otomasyon", "Local automation", "Lokale Automatisierung", "本地自动化"),
    points: [
      P(L("Ajanın gerçek görevi", "What the Agent actually does", "Was der Agent tatsächlich tut", "助手真正执行什么"), L("Yerel Ajan üretken bir uzak model değildir. Hedefteki biçim, gizlilik, dosya ve teslim sinyallerini sürümlenmiş semantik puanlarla eşleştirir; eksik girdi varsa soru sorar ve seçtiği her aracın gerekçesini gösterir.", "Local Agent is not a remote generative model. It matches format, privacy, file, and delivery signals with versioned semantic scores, asks for missing detail, and exposes why every tool was selected.", "Der lokale Agent ist kein generatives Remote-Modell. Er ordnet Format-, Datenschutz-, Datei- und Ausgabesignale über versionierte semantische Bewertungen zu und begründet jedes Werkzeug.", "本地助手不是远程生成模型。它通过版本化语义评分匹配格式、隐私、文件和交付信号，并说明每个工具的选择理由。")),
      P(L("Planı yürütülebilir yapmak", "Make the plan executable", "Den Plan ausführbar machen", "让计划可执行"), L("Her adım için beklenen girdi, çıktı sözleşmesi, dosya gereksinimi ve durdurma koşulu tanımlayın. Önceki çıktının sonraki girdiye geçmesi otomasyon değildir; kullanıcı kontrolünde bir veri aktarımıdır.", "Define expected input, output contract, file requirement, and stop condition for each step. Passing the previous output forward is a user-controlled data handoff, not unattended automation.", "Für jeden Schritt Eingabe, Ausgabevertrag, Dateibedarf und Abbruchbedingung festlegen. Die Weitergabe ist kontrollierter Datentransfer, keine unbeaufsichtigte Automatisierung.", "为每一步定义预期输入、输出契约、文件要求与停止条件。上一输出传递到下一输入是用户控制的数据交接，并非无人值守自动化。")),
      P(L("Sürüm ve geri alma", "Versioning and rollback", "Versionierung und Rücknahme", "版本与撤销"), L("İş İstasyonu düğüm, bağlantı ve girdileri cihazdaki şifreli projede tutar; undo/redo yalnızca açık sekme geçmişidir. Kritik değişiklikten önce URL tarifi veya ayrı proje kopyası oluşturun, fakat hassas girdileri paylaşım bağlantısına eklemeyin.", "Workstation keeps nodes, edges, and inputs in an encrypted on-device project; undo/redo is only the open-tab revision trail. Create a recipe or project copy before critical changes, but exclude sensitive inputs from shared URLs.", "Die Workstation speichert Knoten, Kanten und Eingaben verschlüsselt lokal; Undo/Redo ist nur der Verlauf des offenen Tabs. Vor kritischen Änderungen Rezept oder Projektkopie erstellen, sensible Eingaben aber aus URLs ausschließen.", "工作站把节点、连接和输入加密保存在设备端；撤销/重做只是当前标签页历史。关键变更前创建配方或项目副本，但不要把敏感输入加入分享 URL。")),
    ],
  },
  {
    slug: "prompt-assumptions-risks-output-contracts", relatedTools: ["prompt-varsayim-haritasi", "prompt-risk-kaydi", "prompt-cikti-sozlesmesi-testi"],
    title: L("Prompt Varsayımları, Riskleri ve Çıktı Sözleşmelerini Test Etme", "Testing Prompt Assumptions, Risks, and Output Contracts", "Prompt-Annahmen, Risiken und Ausgabeverträge testen", "测试提示词假设、风险与输出契约"), excerpt: L("Bir promptu yalnızca daha uzun değil, ölçülebilir ve başarısızlığa dayanıklı hale getirin.", "Make a prompt measurable and failure-aware—not merely longer.", "Prompts messbar und fehlertolerant statt nur länger machen.", "让提示词可衡量、可处理失败，而不只是更长。"), category: L("Prompt mühendisliği", "Prompt engineering", "Prompt Engineering", "提示词工程"),
    points: [
      P(L("Örtük varsayımı açık soruya dönüştürün", "Turn assumptions into questions", "Annahmen in Fragen überführen", "把假设变成问题"), L("‘Kısa’, ‘doğru’ veya ‘profesyonel’ gibi sözcükler hedef kitle, kaynak standardı ve kabul eşiği verilmeden test edilemez. Her belirsiz sıfatı doldurulabilir bir parametreye veya doğrulama sorusuna çevirin.", "Words such as concise, correct, or professional cannot be tested without audience, evidence standard, and acceptance threshold. Convert every ambiguous qualifier into a parameter or validation question.", "Begriffe wie kurz, korrekt oder professionell sind ohne Zielgruppe, Evidenzstandard und Schwelle nicht testbar. Jede unklare Eigenschaft wird zum Parameter oder zur Prüffrage.", "“简短”“正确”“专业”等词在缺少受众、证据标准和验收阈值时无法测试。把每个模糊限定词转换为参数或验证问题。")),
      P(L("Risk kaydını göreve bağlayın", "Tie risk to the task", "Risiken an die Aufgabe binden", "把风险绑定到任务"), L("Riskleri genel ‘AI hata yapabilir’ cümlesiyle bırakmayın. Veri sızıntısı, yanlış yetki, güncel olmayan kaynak, kesinlik dili ve biçim ihlalinin olasılığını, etkisini, tespit yöntemini ve sahibini ayrı kaydedin.", "Do not stop at a generic ‘AI can be wrong.’ Record likelihood, impact, detection, mitigation, and owner for data leakage, authority errors, stale sources, overconfidence, and format violations.", "Nicht bei „KI kann irren“ stehen bleiben. Wahrscheinlichkeit, Wirkung, Erkennung, Maßnahme und Zuständigkeit für konkrete Risiken getrennt erfassen.", "不要止于“AI 可能出错”。分别记录数据泄露、权限错误、过期来源、过度确定和格式违规的概率、影响、检测、缓解与负责人。")),
      P(L("Çıktıyı makine ve insan için sınayın", "Test output for machines and people", "Ausgabe für Maschine und Mensch testen", "同时为机器和人测试输出"), L("JSON alanları veya tablo sütunları kadar, eksik bilgi halinde ne olacağı da sözleşmenin parçasıdır. Normal, boş, çelişkili, çok uzun ve kötü niyetli girdiler için beklenen çıktı ile kabul edilmeyen davranışı yazın.", "Missing-information behavior belongs in the contract alongside JSON fields or table columns. Specify expected and forbidden behavior for normal, empty, contradictory, oversized, and adversarial inputs.", "Neben JSON-Feldern oder Tabellenspalten gehört auch das Verhalten bei fehlenden Angaben in den Vertrag. Erwartetes und verbotenes Verhalten für Normal-, Leer-, Konflikt-, Größen- und Missbrauchsfälle festlegen.", "除 JSON 字段或表格列外，缺失信息时的行为也属于契约。为正常、空、矛盾、超长和恶意输入说明预期与禁止行为。")),
    ],
  },
  {
    slug: "meeting-notes-action-items-owned-checklists", relatedTools: ["toplanti-notu-yapilandirici", "aksiyon-maddesi-cikarici", "kontrol-listesi-duzenleyici"],
    title: L("Toplantı Notundan Sahipli Aksiyon Listesine", "From Meeting Notes to Owned Action Items", "Von Besprechungsnotizen zu verantworteten Aufgaben", "从会议笔记到责任明确的行动项"), excerpt: L("Karar, soru, sorumlu, tarih ve kanıtı kaybetmeden notları iş akışına dönüştürün.", "Convert notes into workflow without losing decisions, owners, dates, questions, or evidence.", "Notizen ohne Verlust von Entscheidungen, Zuständigen, Terminen, Fragen oder Nachweisen in einen Ablauf überführen.", "在不丢失决策、负责人、日期、问题和证据的情况下把笔记转为流程。"), category: L("Ekip üretkenliği", "Team productivity", "Teamproduktivität", "团队效率"),
    points: [
      P(L("Karar ile konuşmayı ayırın", "Separate decisions from discussion", "Entscheidung und Diskussion trennen", "区分决策与讨论"), L("Toplantıda söylenen her cümle karar değildir. ‘Önerildi’, ‘değerlendirilecek’ ve ‘karar verildi’ durumlarını ayrı etiketleyin; karar için tarih, kapsam ve onaylayan rolü ekleyin.", "Not every sentence spoken in a meeting is a decision. Label proposed, pending, and decided states separately, then attach date, scope, and approving role to each decision.", "Nicht jeder Satz ist eine Entscheidung. Vorgeschlagen, offen und entschieden getrennt kennzeichnen und Datum, Umfang sowie Freigaberolle ergänzen.", "会议中的每句话都不是决策。分别标记“建议”“待定”“已决定”，并为决策附上日期、范围和批准角色。")),
      P(L("Aksiyonun tamamlanma kanıtını yazın", "Define completion evidence", "Abschlussnachweis definieren", "定义完成证据"), L("‘Kontrol et’ veya ‘düzelt’ tek başına kapanabilir görev değildir. Sorumlu, son tarih, bağımlılık ve görünür kanıt ekleyin: test raporu, ekran görüntüsü, onaylanmış metin veya belirli bir commit gibi.", "Check or fix is not a closable task by itself. Add owner, due date, dependency, and observable evidence such as a test report, screenshot, approved copy, or named commit.", "Prüfen oder beheben allein ist nicht abschließbar. Zuständigkeit, Termin, Abhängigkeit und beobachtbaren Nachweis wie Testbericht, Screenshot oder Commit ergänzen.", "“检查”或“修复”本身不是可关闭任务。增加负责人、截止日期、依赖与可观察证据，例如测试报告、截图、批准文案或指定提交。")),
      P(L("Notları paylaşmadan önce temizleyin", "Clean notes before sharing", "Notizen vor dem Teilen bereinigen", "分享前清理笔记"), L("Katılımcı isimleri, müşteri bilgileri, erişim anahtarları ve olay ayrıntıları toplantı notuna fark edilmeden girebilir. Maskeleme sonrasında karar bağlamının korunup korunmadığını ikinci kez inceleyin.", "Names, customer data, access keys, and incident details can enter notes unnoticed. After masking, review again to ensure decision context remains intact.", "Namen, Kundendaten, Zugriffsschlüssel und Vorfalldetails gelangen leicht unbemerkt in Notizen. Nach der Maskierung prüfen, ob der Entscheidungskontext erhalten bleibt.", "姓名、客户数据、访问密钥和事件细节可能无意进入笔记。遮蔽后再次检查，确保决策语境仍然完整。")),
    ],
  },
  {
    slug: "source-reliability-evidence-synthesis", relatedTools: ["kaynak-guvenilirlik-matrisi", "arastirma-sorusu-ayristirici", "kanit-sentez-tablosu"],
    title: L("Kaynak Güvenilirliği ve Kanıt Sentezi için Pratik Yöntem", "A Practical Method for Source Reliability and Evidence Synthesis", "Praxisleitfaden zu Quellenverlässlichkeit und Evidenzsynthese", "来源可靠性与证据综合的实用方法"), excerpt: L("Kaynak sayısından çok yöntem, birincillik, çelişki ve belirsizliği değerlendirin.", "Evaluate method, primariness, contradiction, and uncertainty—not merely source count.", "Methode, Primärnähe, Widerspruch und Unsicherheit statt bloßer Quellenzahl bewerten.", "评估方法、一手性、矛盾与不确定性，而不是只数来源数量。"), category: L("Araştırma ve kanıt", "Research and evidence", "Recherche und Evidenz", "研究与证据"),
    points: [
      P(L("Soruyu cevaplanabilir parçalara bölün", "Decompose the question", "Frage zerlegen", "拆解问题"), L("Nüfus veya sistem, karşılaştırma, ölçülebilir sonuç, zaman aralığı ve dışlama ölçütü belirtilmeyen geniş sorular farklı kaynakları aynıymış gibi birleştirir. Kapsamı kaynak toplamadan önce sabitleyin.", "Broad questions without population or system, comparison, measurable outcome, time horizon, and exclusion criteria combine unlike evidence. Fix scope before collecting sources.", "Breite Fragen ohne Population/System, Vergleich, messbares Ergebnis, Zeitraum und Ausschlusskriterium vermischen ungleiche Evidenz. Umfang vor der Suche festlegen.", "没有对象或系统、比较项、可衡量结果、时间范围与排除标准的宽泛问题会混合不相似证据。收集来源前先固定范围。")),
      P(L("Kaynak türünü iddiaya eşleyin", "Match source type to claim", "Quellentyp zur Aussage wählen", "让来源类型匹配主张"), L("Ürün özelliği için resmî dokümantasyon, bilimsel etki için yöntemli birincil çalışma, hukuk için güncel mevzuat veya yetkili kurum gerekir. Blog veya forum deneyimi örnek olabilir; kuralın kendisi değildir.", "Use official documentation for product behavior, a method-rich primary study for scientific effect, and current law or competent authority for legal claims. Blogs and forums may illustrate experience but do not establish the rule.", "Für Produktverhalten offizielle Dokumentation, für Wirkung Primärstudien und für Recht aktuelle Vorschriften oder Behörden nutzen. Blogs und Foren illustrieren, begründen aber keine Regel.", "产品行为使用官方文档，科学效果使用方法充分的一手研究，法律主张使用现行法规或主管机构。博客和论坛可说明经验，但不能确立规则。")),
      P(L("Çelişkiyi ortalamayın", "Do not average contradictions", "Widersprüche nicht mitteln", "不要平均矛盾"), L("Kaynaklar farklı sonuca ulaşıyorsa tarih, örneklem, ölçüm, tanım ve çıkar çatışmasını yan yana koyun. Sentez tablosu uzlaşma üretmek için değil, anlaşmazlığın nedenini görünür kılmak içindir.", "When sources disagree, compare date, sample, measurement, definitions, and conflicts of interest. A synthesis table should expose why evidence differs rather than manufacture consensus.", "Bei widersprüchlichen Quellen Datum, Stichprobe, Messung, Definitionen und Interessenkonflikte vergleichen. Die Synthese macht Gründe sichtbar, statt Konsens zu erfinden.", "来源结论不同时，比较日期、样本、测量、定义与利益冲突。综合表用于显示差异原因，而不是制造共识。")),
    ],
  },
  {
    slug: "json-patch-merge-patch-safe-delivery", relatedTools: ["json-patch-olusturucu", "json-merge-patch-laboratuvari", "json-diff-karsilastirma"],
    title: L("JSON Patch ve Merge Patch ile Güvenli Değişiklik Teslimi", "Safe Change Delivery with JSON Patch and Merge Patch", "Sichere Änderungsübergabe mit JSON Patch und Merge Patch", "使用 JSON Patch 与 Merge Patch 安全交付变更"), excerpt: L("Yapısal farkı, uygulanabilir yamayı ve geri alma planını aynı incelemede birleştirin.", "Combine structural diff, applicable patch, and rollback plan in one review.", "Strukturellen Diff, anwendbaren Patch und Rücknahmeplan gemeinsam prüfen.", "在一次审查中结合结构差异、可应用补丁与回滚计划。"), category: L("Veri sözleşmeleri", "Data contracts", "Datenverträge", "数据契约"),
    points: [
      P(L("Düz metin diff yerine yolu izleyin", "Track paths, not text lines", "Pfade statt Textzeilen verfolgen", "跟踪路径而不是文本行"), L("JSON anahtar sırası veya girinti değişikliği semantik değişiklik değildir. JSON Pointer yollarıyla add, remove ve replace işlemleri oluşturmak hangi alanın gerçekten değiştiğini görünür kılar.", "JSON key order and indentation are not semantic changes. Using JSON Pointer paths for add, remove, and replace makes the actual field changes explicit.", "Schlüsselreihenfolge und Einrückung sind keine semantische Änderung. Add, remove und replace mit JSON-Pointer-Pfaden zeigen echte Feldänderungen.", "JSON 键顺序和缩进不是语义变化。使用 JSON Pointer 路径表示 add、remove、replace 可明确真实字段变更。")),
      P(L("İki yama modelini karıştırmayın", "Do not mix the patch models", "Patch-Modelle nicht vermischen", "不要混用补丁模型"), L("RFC 6902 işlem dizisidir; RFC 7396 ise nesne birleştirir ve null değeri silme olarak yorumlar. Null'ın gerçek iş değeri olduğu sözleşmelerde Merge Patch beklenmedik veri kaybı yaratabilir.", "RFC 6902 is an operation sequence; RFC 7396 merges objects and interprets null as deletion. Merge Patch can lose data when null is a legitimate domain value.", "RFC 6902 ist eine Operationsfolge; RFC 7396 verschmilzt Objekte und deutet null als Löschen. Bei fachlich gültigem null kann Merge Patch Daten verlieren.", "RFC 6902 是操作序列；RFC 7396 合并对象并把 null 解释为删除。当 null 是合法业务值时，Merge Patch 可能造成数据丢失。")),
      P(L("Önkoşul ve rollback ekleyin", "Add preconditions and rollback", "Vorbedingungen und Rücknahme", "添加前置条件与回滚"), L("Yamayı hedef belge sürümü veya ETag ile bağlayın, uygulama sonrasında şema ve iş kuralı doğrulaması çalıştırın. Eski belgeyi veya ters yamayı saklamadan üretim değişikliği yapmayın.", "Bind the patch to a target document version or ETag, then validate schema and business rules after application. Do not change production without retaining the old document or a tested inverse path.", "Patch an Dokumentversion oder ETag binden und danach Schema sowie Fachregeln prüfen. Ohne alte Version oder getesteten Rückweg keine Produktionsänderung.", "把补丁绑定到目标文档版本或 ETag，应用后验证 Schema 与业务规则。未保留旧文档或经过测试的逆向路径时，不要修改生产数据。")),
    ],
  },
  {
    slug: "csv-profiling-joins-quality-gates", relatedTools: ["csv-sutun-profilleyici", "csv-birlestirme-simulatoru", "csv-inceleyici"],
    title: L("CSV Profilleme ve Join İşlemleri için Veri Kalite Kapısı", "A Data Quality Gate for CSV Profiling and Joins", "Datenqualitätsprüfung für CSV-Profile und Joins", "CSV 分析与连接的数据质量门禁"), excerpt: L("Boş değer, tür, benzersizlik ve eşleşmeyen anahtarları dönüşümden önce ölçün.", "Measure missing values, types, uniqueness, and unmatched keys before conversion.", "Fehlwerte, Typen, Eindeutigkeit und nicht passende Schlüssel vor der Konvertierung messen.", "转换前测量缺失值、类型、唯一性与未匹配键。"), category: L("Veri kalitesi", "Data quality", "Datenqualität", "数据质量"),
    points: [
      P(L("Sütunu örnekle değil dağılımla okuyun", "Profile distributions, not one row", "Verteilungen statt Einzelzeilen prüfen", "分析分布而非单行"), L("İlk satır sayısal diye sütunun tamamını sayı kabul etmeyin. Boşluk, yerel ondalık ayracı, ön sıfır, tarih biçimi ve nadir aykırı değerleri profilde görünür kılın.", "Do not infer a whole column from one numeric row. Surface missing values, locale-specific decimals, leading zeros, date formats, and rare outliers.", "Eine numerische Zeile bestimmt nicht den gesamten Spaltentyp. Fehlwerte, Dezimaltrennzeichen, führende Nullen, Datumsformate und Ausreißer sichtbar machen.", "不要因一行是数字就推断整列类型。显示缺失值、本地小数分隔符、前导零、日期格式与罕见异常值。")),
      P(L("Join anahtarını sözleşme olarak doğrulayın", "Validate the join key as a contract", "Join-Schlüssel als Vertrag prüfen", "把连接键当作契约验证"), L("Anahtar her iki tabloda aynı anlam ve normalizasyona sahip olmalıdır. Tekillik bekleniyorsa kopyaları join'den önce durdurun; aksi halde satır sayısı çarpılarak sessiz veri bozulması oluşabilir.", "The key must carry the same meaning and normalization in both tables. If uniqueness is expected, stop on duplicates before the join or row counts can multiply silently.", "Der Schlüssel braucht in beiden Tabellen gleiche Bedeutung und Normalisierung. Bei erwarteter Eindeutigkeit Duplikate vor dem Join stoppen, sonst vervielfachen sich Zeilen unbemerkt.", "连接键在两张表中必须有相同含义与规范化。若预期唯一，应在连接前因重复值停止，否则行数可能静默倍增。")),
      P(L("Eşleşmeyen kayıtları teslim edin", "Deliver unmatched records", "Nicht passende Datensätze mitliefern", "交付未匹配记录"), L("Sadece başarılı join çıktısı yeterli değildir. Sol eşleşmeyen, sağ eşleşmeyen, çoklu eşleşen ve boş anahtarlı kayıt sayılarını ayrı raporlayın; karar sahibinin kaybı görmesini sağlayın.", "A successful join table is not enough. Report left-only, right-only, multi-match, and empty-key counts separately so the decision owner can see loss and duplication.", "Eine Join-Tabelle allein reicht nicht. Links-/rechtsseitig fehlende, Mehrfachtreffer und leere Schlüssel getrennt melden, damit Verlust und Duplikation sichtbar sind.", "仅有成功连接表还不够。分别报告左未匹配、右未匹配、多重匹配与空键数量，让决策者看到丢失和重复。")),
    ],
  },
  {
    slug: "api-pagination-http-status-mime-review", relatedTools: ["api-sayfalama-planlayici", "http-durum-kodu-gezgini", "mime-tipi-inceleyici"],
    title: L("API Sayfalama, HTTP Durumları ve MIME Doğrulama Rehberi", "API Pagination, HTTP Status, and MIME Validation Guide", "Leitfaden zu API-Paginierung, HTTP-Status und MIME-Prüfung", "API 分页、HTTP 状态与 MIME 验证指南"), excerpt: L("Tekrar deneme, sonlanma, önbellek ve dosya türü kararlarını görünür sözleşmelere dönüştürün.", "Turn retry, termination, caching, and file-type decisions into explicit contracts.", "Wiederholung, Abbruch, Caching und Dateityp als sichtbare Verträge definieren.", "把重试、终止、缓存与文件类型决策转换为明确契约。"), category: L("API dayanıklılığı", "API resilience", "API-Resilienz", "API 韧性"),
    points: [
      P(L("Sayfalamaya kesin son koşulu koyun", "Give pagination a hard stop", "Paginierung klar begrenzen", "为分页设置硬停止"), L("Boş sayfa, hasNext=false, tekrar eden cursor ve azami sayfa sayısını birlikte ele alın. Cursor'ı yalnızca sayfa başarıyla işlendiğinde kaydedin; aksi halde yeniden başlatma kayıt atlayabilir.", "Handle empty page, hasNext=false, repeated cursor, and a hard page ceiling together. Persist a cursor only after successful processing or a restart can skip records.", "Leere Seite, hasNext=false, wiederholten Cursor und Maximalzahl gemeinsam behandeln. Cursor erst nach erfolgreicher Verarbeitung speichern.", "同时处理空页、hasNext=false、重复 cursor 与最大页数。仅在成功处理页面后保存 cursor，否则重启可能跳过记录。")),
      P(L("Durum kodunu uygulama eylemine bağlayın", "Map status to client action", "Statuscode mit Client-Aktion verbinden", "把状态码映射到客户端操作"), L("401 kimlik doğrulamayı, 403 yetkiyi, 409 durum çatışmasını, 422 semantik doğrulamayı ve 429 hız sınırını anlatır. Her 4xx için aynı tekrar mekanizmasını kullanmak yükü artırır ve kullanıcı hatasını gizler.", "401 concerns authentication, 403 authorization, 409 state conflict, 422 semantic validation, and 429 rate limiting. Retrying every 4xx identically adds load and hides actionable errors.", "401 betrifft Authentifizierung, 403 Autorisierung, 409 Zustandskonflikt, 422 Semantik und 429 Rate Limit. Gleiches Retry für alle 4xx erhöht Last und verdeckt Fehler.", "401 表示认证、403 表示授权、409 表示状态冲突、422 表示语义验证、429 表示限速。对所有 4xx 使用相同重试会增加负载并隐藏可操作错误。")),
      P(L("Dosya türünü üç sinyalle kontrol edin", "Use three file-type signals", "Drei Dateityp-Signale nutzen", "使用三种文件类型信号"), L("Uzantı, Content-Type ve magic byte birbirini desteklemelidir; hiçbiri tek başına güven kanıtı değildir. Dosyayı çalıştırmadan, ayrıştırıcıya boyut/zaman sınırı koyarak ve güvenli hata vererek işleyin.", "Extension, Content-Type, and magic bytes should support one another; none is proof of safety. Process without execution, bound parser time and size, and fail safely.", "Endung, Content-Type und Magic Bytes sollten zusammenpassen, beweisen aber keine Sicherheit. Ohne Ausführung, mit Größen-/Zeitlimit und sicherem Fehler verarbeiten.", "扩展名、Content-Type 与 Magic Byte 应相互支持，但都不能单独证明安全。不要执行文件，应限制解析器时间和大小，并安全失败。")),
    ],
  },
  {
    slug: "privacy-redaction-pseudonymization-notice", relatedTools: ["gizli-deger-redaksiyon-planlayici", "takma-adlandirma-haritasi", "gizlilik-bildirimi-bosluk-tarayicisi"],
    title: L("Redaksiyon, Takma Adlandırma ve Gizlilik Bildirimi Sınırları", "Boundaries of Redaction, Pseudonymization, and Privacy Notices", "Grenzen von Redaktion, Pseudonymisierung und Datenschutzhinweisen", "脱敏、假名化与隐私声明的边界"), excerpt: L("Üç farklı gizlilik kontrolünü aynı şey sanmadan, amaçlarına uygun uygulayın.", "Apply three distinct privacy controls without treating them as interchangeable.", "Drei unterschiedliche Datenschutzkontrollen zweckgerecht statt austauschbar einsetzen.", "按各自目的应用三种不同隐私控制，不要混为一谈。"), category: L("Gizlilik mühendisliği", "Privacy engineering", "Privacy Engineering", "隐私工程"),
    points: [
      P(L("Redaksiyon görünürlüğü azaltır", "Redaction reduces exposure", "Redaktion reduziert Sichtbarkeit", "脱敏降低暴露"), L("Token veya bağlantı dizisini [REDACTED] ile değiştirmek paylaşım kopyasını temizler; kaynağın sızdırılmış geçmişini, logları veya aktif anahtarı geri almaz. Şüpheli ifşada anahtarı döndürün ve geçmişi ayrıca temizleyin.", "Replacing a token or connection string with [REDACTED] cleans the shared copy; it does not undo exposure in history, logs, or the live credential. Rotate suspected secrets and clean history separately.", "[REDACTED] bereinigt die geteilte Kopie, nicht Verlauf, Logs oder aktive Zugangsdaten. Verdächtige Secrets rotieren und Historie getrennt bereinigen.", "用 [REDACTED] 替换令牌或连接字符串只清理分享副本，不能撤销历史、日志或有效凭据中的暴露。疑似泄露时应轮换密钥并另行清理历史。")),
      P(L("Takma adlandırma hâlâ kişisel veridir", "Pseudonymous data can remain personal", "Pseudonyme Daten können personenbezogen bleiben", "假名数据仍可能是个人数据"), L("Tutarlı etiketler kayıtları bağlanabilir bırakır; eşleme anahtarı veya dış bilgi kimliği geri getirebilir. Geri dönüş anahtarını ayırın, erişimi sınırlandırın ve gerçekten gerekmiyorsa anonimlik iddiasında bulunmayın.", "Consistent labels remain linkable, and a mapping key or outside information can restore identity. Separate key access, restrict it, and do not claim anonymity when re-identification remains plausible.", "Konsistente Kennungen bleiben verknüpfbar; Mapping-Schlüssel oder externe Daten können Identität wiederherstellen. Schlüssel trennen, Zugriff begrenzen und keine Anonymität behaupten.", "一致标签仍可关联，映射密钥或外部信息可能恢复身份。应分离并限制密钥访问，在可重新识别时不要声称匿名。")),
      P(L("Bildirim fiilî davranışı anlatmalı", "A notice must describe actual behavior", "Hinweis muss echtes Verhalten beschreiben", "声明必须描述实际行为"), L("Amaç, veri türü, hukuki dayanak, saklama, alıcılar, aktarım, haklar, iletişim ve reklam/çerez davranışı gerçek ürünü yansıtmalıdır. Başlık tarayıcı eksik sözcüğü bulabilir; hukuki yeterliliği belirleyemez.", "Purpose, data categories, legal basis, retention, recipients, transfers, rights, contact, and advertising or cookie behavior must reflect the real product. A gap scanner can find missing wording, not determine legal adequacy.", "Zweck, Datenarten, Rechtsgrundlage, Aufbewahrung, Empfänger, Übermittlung, Rechte, Kontakt und Werbe-/Cookie-Verhalten müssen das echte Produkt abbilden. Ein Scanner erkennt Textlücken, keine Rechtswirksamkeit.", "目的、数据类别、法律依据、保留期、接收方、传输、权利、联系与广告/Cookie 行为必须反映真实产品。缺口扫描器只能发现缺失措辞，不能判断法律充分性。")),
    ],
  },
  {
    slug: "jwt-expiry-authentication-boundaries", relatedTools: ["jwt-sure-zaman-cizelgesi", "jwt-decoder", "unix-zaman-damgasi-donusturucu"],
    title: L("JWT Zaman Çizelgesi ve Kimlik Doğrulama Sınırları", "JWT Timelines and Authentication Boundaries", "JWT-Zeitachsen und Authentifizierungsgrenzen", "JWT 时间线与身份验证边界"), excerpt: L("iat, nbf ve exp alanlarını okuyun; decode işlemini doğrulama sanmayın.", "Read iat, nbf, and exp without mistaking decoding for verification.", "iat, nbf und exp lesen, ohne Dekodieren mit Verifizieren zu verwechseln.", "读取 iat、nbf、exp，但不要把解码误认为验证。"), category: L("Kimlik güvenliği", "Identity security", "Identitätssicherheit", "身份安全"),
    points: [
      P(L("Zaman claim'lerini birlikte okuyun", "Read time claims together", "Zeit-Claims gemeinsam lesen", "一起读取时间 Claim"), L("iat üretim zamanını, nbf en erken kullanım anını, exp sona ermeyi anlatır. Birim saniyedir; saat kayması toleransı kısa ve belgeli olmalı, exp<=nbf gibi tutarsızlıklar reddedilmelidir.", "iat is issuance, nbf earliest use, and exp expiry. Values are seconds; clock-skew tolerance should be short and documented, and contradictions such as exp<=nbf should fail.", "iat ist Ausgabe, nbf früheste Nutzung und exp Ablauf. Werte sind Sekunden; Uhrtoleranz kurz dokumentieren und Widersprüche wie exp<=nbf ablehnen.", "iat 表示签发，nbf 表示最早可用，exp 表示到期。单位为秒；时钟偏差容差应短且有记录，exp<=nbf 等矛盾应拒绝。")),
      P(L("Header iddiadır, güven kanıtı değil", "The header is a claim, not trust", "Header ist Behauptung, kein Vertrauen", "Header 是声明，不是信任证据"), L("alg ve kid alanları tokenın kendi iddiasıdır. İzin verilen algoritma listesi, güvenilir anahtar seti, issuer, audience, nonce ve imza doğrulanmadan payload'a yetki vermeyin.", "alg and kid are claims made by the token itself. Do not grant authority until allowed algorithms, trusted keys, issuer, audience, nonce, and signature are verified.", "alg und kid sind Behauptungen des Tokens. Erst nach Prüfung von erlaubtem Algorithmus, Schlüssel, Issuer, Audience, Nonce und Signatur autorisieren.", "alg 与 kid 是令牌自身声明。未验证允许算法、可信密钥、issuer、audience、nonce 与签名前，不要授予权限。")),
      P(L("Süre dolumu tek iptal mekanizması değildir", "Expiry is not revocation", "Ablauf ist kein Widerruf", "到期不等于撤销"), L("Çalınmış kısa ömürlü token süre bitene kadar kullanılabilir. Riskli sistemler rotation, oturum bağlama, revocation veya arka kanal kontrolü ve olay sonrası anahtar döndürme planına ihtiyaç duyar.", "A stolen short-lived token may work until expiry. Risky systems need rotation, session binding, revocation or back-channel checks, and a post-incident key rotation plan.", "Ein gestohlenes kurzlebiges Token kann bis Ablauf funktionieren. Nötig sind Rotation, Sitzungsbindung, Widerruf oder Backchannel-Prüfung und Incident-Plan.", "被盗的短期令牌可能在到期前仍可使用。高风险系统需要轮换、会话绑定、撤销或后通道检查，以及事件后密钥轮换计划。")),
    ],
  },
  {
    slug: "software-supply-chain-local-prechecks", relatedTools: ["paket-manifestosu-denetleyici", "npm-script-risk-tarayicisi", "github-actions-izin-denetleyici", "dockerfile-guvenlik-on-kontrolu"],
    title: L("Paket, npm Script, Dockerfile ve CI için Yerel Tedarik Zinciri Ön Kontrolü", "Local Supply-Chain Pre-checks for Packages, npm Scripts, Dockerfiles, and CI", "Lokale Lieferketten-Vorprüfung für Pakete, npm, Dockerfile und CI", "包、npm 脚本、Dockerfile 与 CI 的本地供应链预检查"), excerpt: L("Kod çalıştırmadan yüksek değerli risk sinyallerini bulun ve manuel incelemeyi önceliklendirin.", "Find high-value risk signals without execution and prioritize manual review.", "Wertvolle Risikosignale ohne Ausführung finden und manuelle Prüfung priorisieren.", "不执行代码即可发现高价值风险信号并安排人工审查优先级。"), category: L("Kod güvenliği", "Code security", "Codesicherheit", "代码安全"),
    points: [
      P(L("Kurulum yaşam döngüsünü ayrı inceleyin", "Review install lifecycle separately", "Install-Lifecycle getrennt prüfen", "单独审查安装生命周期"), L("preinstall, install ve postinstall bağımlılık kurulurken otomatik çalışabilir. Ağdan script indirme, shell zinciri, ortam sırlarına erişim ve platforma özel davranış için komutu ve çağırdığı dosyayı kaynak düzeyinde inceleyin.", "preinstall, install, and postinstall can run automatically during dependency installation. Review commands and called files for network downloads, shell chaining, environment secrets, and platform-specific behavior.", "preinstall, install und postinstall laufen bei Installation automatisch. Befehle und Dateien auf Downloads, Shell-Ketten, Umgebungs-Secrets und Plattformverhalten prüfen.", "preinstall、install、postinstall 可在安装依赖时自动运行。应从源码检查网络下载、Shell 链接、环境密钥访问与平台特定行为。")),
      P(L("İzin ve referansları daraltın", "Narrow permissions and references", "Rechte und Referenzen begrenzen", "收紧权限与引用"), L("GitHub Actions için job düzeyinde en az permissions kullanın; üçüncü taraf action referansını tam commit SHA'ya sabitleyin ve Dependabot benzeri kontrollü güncelleme yolu kurun. pull_request_target ile güvenilmeyen kodu asla doğrudan çalıştırmayın.", "Use least-privilege job permissions in GitHub Actions, pin third-party actions to full commit SHAs, and establish a controlled update path. Never run untrusted code directly under pull_request_target.", "In GitHub Actions minimale Job-Rechte nutzen, Dritt-Actions auf vollständige SHA pinnen und kontrolliert aktualisieren. Unter pull_request_target keinen untrusted Code direkt ausführen.", "GitHub Actions 应使用最小 job 权限，把第三方 Action 固定到完整提交 SHA，并建立受控更新流程。不要在 pull_request_target 下直接运行不可信代码。")),
      P(L("Kapsayıcı ve root sınırını doğrulayın", "Validate container and root boundaries", "Container- und Root-Grenzen prüfen", "验证容器与 root 边界"), L("Kayan base image etiketi, geniş COPY, 777 izin ve root kullanıcı tekrarlanabilirlik ile ayrıcalık riskini artırır. İmaj digest'i, .dockerignore, kilitli kurulum, salt okunur dosya sistemi ve non-root kullanıcıyı gerçek çalışma ortamında test edin.", "Floating base tags, broad COPY, 777 permissions, and root users increase reproducibility and privilege risk. Test image digests, .dockerignore, locked installs, read-only filesystems, and non-root operation in the real runtime.", "Schwimmende Tags, breites COPY, 777 und root erhöhen Reproduzierbarkeits- und Privilegienrisiko. Digest, .dockerignore, Locked Install, Read-only und Non-root im echten Runtime testen.", "浮动基础镜像标签、宽泛 COPY、777 权限与 root 用户会增加可重复性和权限风险。应在真实运行环境测试镜像 digest、.dockerignore、锁定安装、只读文件系统与非 root 运行。")),
    ],
  },
  {
    slug: "finance-scenario-planning-break-even-margin-inflation", relatedTools: ["basabas-noktasi-hesaplayici", "marj-kar-orani-hesaplayici", "enflasyon-satin-alma-gucu", "kredi-amortisman-tahminleyici"],
    title: L("Başabaş, Marj, Enflasyon ve Kredi Hesaplarını Senaryo Olarak Kullanma", "Using Break-even, Margin, Inflation, and Loan Calculations as Scenarios", "Break-even, Marge, Inflation und Kredit als Szenarien nutzen", "把盈亏平衡、毛利、通胀与贷款计算作为情景"), excerpt: L("Formülü görünür tutun; tek tahmini garanti veya finansal tavsiye gibi sunmayın.", "Keep formulas visible and never present one estimate as a guarantee or financial advice.", "Formeln sichtbar halten und eine Schätzung nie als Garantie oder Beratung darstellen.", "保持公式可见，不要把单一估算当作保证或财务建议。"), category: L("Finansal okuryazarlık", "Financial literacy", "Finanzkompetenz", "金融素养"),
    points: [
      P(L("Marj ile markup'ı ayırın", "Separate margin from markup", "Marge und Aufschlag trennen", "区分毛利率与加价率"), L("Marj kârı satış fiyatına, markup kârı maliyete böler; aynı değildir. Maliyet kapsamına ödeme komisyonu, iade, lojistik, vergi ve personel dahil değilse yüksek görünen oran yanlış karar doğurur.", "Margin divides profit by selling price; markup divides it by cost. They differ. If cost excludes fees, returns, logistics, tax, or labor, an attractive ratio can drive a poor decision.", "Marge teilt Gewinn durch Verkaufspreis, Aufschlag durch Kosten. Fehlende Gebühren, Retouren, Logistik, Steuer oder Arbeit verzerren die Entscheidung.", "毛利率以售价为分母，加价率以成本为分母，两者不同。若成本未包含手续费、退货、物流、税费或人工，漂亮的比率可能导致错误决策。")),
      P(L("Başabaşı aralıkla test edin", "Stress-test break-even", "Break-even als Bereich testen", "对盈亏平衡进行压力测试"), L("Başabaş formülü sabit maliyet/(fiyat−birim değişken maliyet) kullanır. Fiyat indirimi, talep, kapasite ve maliyet değişimi için olumsuz, temel ve olumlu senaryolar oluşturun; birim katkı sıfır veya negatifse hesap durmalıdır.", "Break-even uses fixed cost divided by price minus unit variable cost. Build adverse, baseline, and favorable cases for discounts, demand, capacity, and cost; stop when unit contribution is zero or negative.", "Break-even nutzt Fixkosten/(Preis−variable Stückkosten). Negative, Basis- und Positivfälle für Rabatt, Nachfrage, Kapazität und Kosten bilden; bei Beitrag <=0 stoppen.", "盈亏平衡使用固定成本/(价格−单位变动成本)。针对折扣、需求、产能和成本建立不利、基准、有利情景；单位贡献为零或负时应停止计算。")),
      P(L("Zaman değerini tüm varsayımlarla verin", "Expose every time-value assumption", "Alle Zeitwertannahmen zeigen", "公开所有时间价值假设"), L("Kredi amortismanı faiz periyodu, ek ödeme zamanı ve ücretlere; satın alma gücü ise sabit enflasyon varsayımına bağlıdır. Gerçek teklif, vergi, değişken oran ve erken ödeme kuralları resmî belgeden eklenmeden karar vermeyin.", "Loan amortization depends on compounding period, extra-payment timing, and fees; purchasing power depends on a constant inflation assumption. Add the actual offer, tax, variable-rate, and prepayment rules before deciding.", "Kredittilgung hängt von Zinsperiode, Sonderzahlungszeit und Gebühren ab; Kaufkraft von konstanter Inflation. Reales Angebot, Steuer, variable Zinsen und Vorzahlung vorher ergänzen.", "贷款摊还取决于复利周期、额外还款时间和费用；购买力取决于恒定通胀假设。决策前应加入真实报价、税费、浮动利率与提前还款规则。")),
    ],
  },
  {
    slug: "decision-matrix-smart-goals-agendas", relatedTools: ["karar-matrisi", "smart-hedef-olusturucu", "gundem-olusturucu"],
    title: L("Karar Matrisi, SMART Hedef ve Gündem ile Kararı Eyleme Çevirme", "Turning Decisions into Action with a Matrix, SMART Goals, and Agendas", "Entscheidungen mit Matrix, SMART-Zielen und Agenda umsetzen", "用决策矩阵、SMART 目标与议程把决策转为行动"), excerpt: L("Ölçütleri görünür kılın, ağırlık duyarlılığını test edin ve kararı zaman kutulu eyleme bağlayın.", "Expose criteria, test weight sensitivity, and connect the decision to time-boxed action.", "Kriterien sichtbar machen, Gewichtssensitivität testen und Entscheidung zeitlich umsetzen.", "公开标准、测试权重敏感性，并把决策连接到分时行动。"), category: L("Karar tasarımı", "Decision design", "Entscheidungsdesign", "决策设计"),
    points: [
      P(L("Ölçütü seçenekten önce yazın", "Define criteria before options", "Kriterien vor Optionen definieren", "先定义标准再看选项"), L("Seçenekleri gördükten sonra ağırlık belirlemek istenen sonucu meşrulaştırabilir. Ölçüt tanımı, ölçüm skalası ve ağırlığı önce yazın; zorunlu eşiği ağırlıklı puandan ayrı ele alın.", "Choosing weights after seeing options can legitimize a preferred result. Define criteria, scale, and weights first, and keep mandatory thresholds separate from weighted scoring.", "Gewichte nach Sicht der Optionen können Wunschresultate legitimieren. Kriterien, Skala und Gewichte vorher definieren und Pflichtschwellen getrennt behandeln.", "看到选项后才确定权重可能只是为偏好结果背书。应先定义标准、量表和权重，并把强制门槛与加权评分分开。")),
      P(L("Duyarlılığı görünür kılın", "Show sensitivity", "Sensitivität zeigen", "展示敏感性"), L("En yüksek iki ağırlığı veya en belirsiz puanı ±%20 değiştirin. Sıralama kolayca değişiyorsa ‘kazanan’ güçlü değildir; daha iyi veri toplamak ya da seçenekleri küçük pilotla sınamak gerekir.", "Vary the two largest weights or most uncertain score by ±20%. If ranking changes easily, the winner is weak; collect better evidence or run a small pilot.", "Die zwei höchsten Gewichte oder unsichersten Werte um ±20 % ändern. Wechselt die Rangfolge leicht, ist der Sieger schwach und braucht bessere Daten oder Pilot.", "将两个最大权重或最不确定评分上下调整 20%。若排名轻易变化，“胜者”并不稳健，应收集更好证据或进行小规模试点。")),
      P(L("Kararı kapanabilir göreve çevirin", "Convert the decision into a closable task", "Entscheidung in abschließbare Aufgabe überführen", "把决策转为可关闭任务"), L("SMART hedefe başlangıç değeri, hedef değer, tarih ve veri kaynağı ekleyin. Gündemde bilgi paylaşımı, tartışma ve karar maddelerini ayırın; her karar için sahip, sonraki adım ve kanıt bırakın.", "Add baseline, target, date, and data source to the SMART goal. Separate information, discussion, and decision agenda items, and leave an owner, next action, and evidence for every decision.", "SMART-Ziel um Ausgangswert, Zielwert, Datum und Datenquelle ergänzen. Information, Diskussion und Entscheidung trennen; je Entscheidung Zuständigkeit, nächste Aktion und Nachweis festhalten.", "为 SMART 目标增加基线、目标值、日期和数据来源。议程中区分信息、讨论与决策；每项决策都要留下负责人、下一步和证据。")),
    ],
  },
  {
    slug: "inclusive-tone-headline-review", relatedTools: ["kapsayici-dil-inceleyici", "ton-tutarliligi-inceleyici", "baslik-varyasyon-laboratuvari"],
    title: L("Kapsayıcı Dil, Ton Tutarlılığı ve Başlık Kalitesi İncelemesi", "Reviewing Inclusive Language, Tone Consistency, and Headline Quality", "Inklusive Sprache, Tonkonsistenz und Überschriftenqualität prüfen", "检查包容性语言、语气一致性与标题质量"), excerpt: L("Kural tabanlı işaretleri bağlam, hedef kitle ve somut vaatlerle insan incelemesine dönüştürün.", "Turn rule-based flags into human review grounded in context, audience, and concrete promises.", "Regelbasierte Hinweise mit Kontext, Zielgruppe und konkreten Versprechen menschlich prüfen.", "把规则标记转化为基于语境、受众与具体承诺的人工审查。"), category: L("İçerik tasarımı", "Content design", "Content Design", "内容设计"),
    points: [
      P(L("İşaretleme karar değildir", "A flag is not a verdict", "Markierung ist kein Urteil", "标记不是裁决"), L("‘Yaşlı’, ‘normal’, ‘herkes’ veya argo sözcükler bazı bağlamlarda açıklayıcı, bazılarında dışlayıcı olabilir. Araç sözcüğü işaretler; niyet, etki, alıntı ve hedef kitleyi insan değerlendirir.", "Terms such as elderly, normal, everyone, or slang may be descriptive in one context and excluding in another. The tool flags language; a person evaluates intent, impact, quotation, and audience.", "Begriffe wie alt, normal, alle oder Slang können je nach Kontext beschreibend oder ausgrenzend sein. Das Werkzeug markiert, der Mensch bewertet Absicht, Wirkung, Zitat und Zielgruppe.", "“老人”“正常”“所有人”或俚语在某些语境中是描述，在另一些语境中可能排斥。工具只标记词语；人需要评估意图、影响、引用与受众。")),
      P(L("Ton değişimini bölüm bazında ölçün", "Measure tone by section", "Ton je Abschnitt messen", "按段落衡量语气"), L("Destek metninde sakin girişten tehditkâr büyük harfe geçmek, güveni kırar. Resmiyet, kesinlik, duygu ve cümle uzunluğunu bölüm bölüm karşılaştırın; hata ve başarı durumlarını da aynı dil sistemine bağlayın.", "A support message that jumps from calm introduction to threatening all-caps breaks trust. Compare formality, certainty, sentiment, and sentence length by section, including success and error states.", "Der Sprung von ruhiger Einleitung zu drohenden Großbuchstaben zerstört Vertrauen. Formalität, Gewissheit, Stimmung und Satzlänge je Abschnitt sowie Erfolgs-/Fehlerzustände vergleichen.", "支持文本从平静开头突然变成威胁性全大写会破坏信任。按段比较正式度、确定性、情绪与句长，并统一成功和错误状态语言。")),
      P(L("Başlıkta vaadi sınırlandırın", "Calibrate the headline promise", "Versprechen der Überschrift kalibrieren", "校准标题承诺"), L("‘En iyi’, ‘garantili’ ve ‘tam güvenli’ gibi kanıtlanamayan vaatlerden kaçının. Hedef görev, yerel çalışma, çıktı ve sınırı somutlaştıran başlık hem kullanıcıya hem arama motoruna daha doğru beklenti verir.", "Avoid unprovable promises such as best, guaranteed, or completely secure. A headline that names the task, local method, output, and boundary creates a more accurate expectation for users and search engines.", "Unbelegbare Versprechen wie beste, garantiert oder vollständig sicher vermeiden. Aufgabe, lokale Methode, Ausgabe und Grenze konkret benennen.", "避免“最好”“保证”“完全安全”等无法证明的承诺。明确任务、本地方法、输出与边界的标题能为用户和搜索引擎建立更准确预期。")),
    ],
  },
  {
    slug: "rag-context-hallucination-source-quality", relatedTools: ["rag-kaynak-kalite-puanlayici", "baglam-oncelik-planlayici", "halusinasyon-risk-kontrol-listesi"],
    title: L("RAG için Kaynak Kalitesi, Bağlam Önceliği ve Halüsinasyon Kontrolü", "Source Quality, Context Priority, and Hallucination Control for RAG", "Quellenqualität, Kontextpriorität und Halluzinationskontrolle für RAG", "RAG 的来源质量、上下文优先级与幻觉控制"), excerpt: L("Daha fazla bağlam yerine daha iyi kanıt, daha açık talimat ve izlenebilir iddia seçin.", "Choose better evidence, clearer instructions, and traceable claims instead of merely more context.", "Bessere Evidenz, klarere Anweisung und nachvollziehbare Aussagen statt bloß mehr Kontext wählen.", "不要只增加上下文，应选择更好证据、更清晰指令与可追溯主张。"), category: L("AI kalite güvence", "AI quality assurance", "KI-Qualitätssicherung", "AI 质量保证"),
    points: [
      P(L("Kaynağı chunk'tan önce değerlendirin", "Score the source before the chunk", "Quelle vor dem Chunk bewerten", "先评估来源再切块"), L("Düşük kaliteli kaynağı iyi parçalara bölmek doğruluğu artırmaz. Birincillik, güncellik, yöntem, kapsam, düzeltme geçmişi ve çıkar çatışmasını kaynak düzeyinde puanlayın.", "Good chunking cannot make a weak source accurate. Score primariness, freshness, method, coverage, correction history, and conflicts at source level first.", "Gutes Chunking macht schwache Quellen nicht richtig. Primärnähe, Aktualität, Methode, Umfang, Korrekturen und Konflikte zuerst auf Quellenebene bewerten.", "好的切块无法让弱来源变准确。应先在来源层评估一手性、时效性、方法、覆盖、勘误历史与利益冲突。")),
      P(L("Bağlam bütçesini kanıta göre ayırın", "Allocate context by evidence value", "Kontext nach Evidenzwert verteilen", "按证据价值分配上下文"), L("Zorunlu politika ve sözleşme metni, uzun konuşma geçmişinden önce gelmelidir. Token maliyetini güncellik ve gereklilikle birlikte puanlayın; düşük değerli tekrarları çıkarırken istisna ve tanımları koruyun.", "Mandatory policy and contract text should outrank long conversation history. Score token cost with recency and necessity, removing low-value repetition while preserving exceptions and definitions.", "Pflichtregeln und Verträge stehen vor langer Gesprächshistorie. Tokenkosten mit Aktualität und Notwendigkeit bewerten; Wiederholung entfernen, Ausnahmen und Definitionen behalten.", "强制政策和契约文本应优先于冗长对话历史。将 Token 成本与时效性、必要性一起评分；删除低价值重复时保留例外与定义。")),
      P(L("İddia–alıntı bağını test edin", "Test claim-to-source linkage", "Aussage-Quelle-Verbindung testen", "测试主张与来源连接"), L("Her önemli cümlenin destekleyen parçası, kaynak tarihi ve kapsamı gösterilmelidir. Kaynak yoksa modelin uydurmasını istemek yerine ‘yetersiz kanıt’ çıktısını sözleşmeye ekleyin.", "Every important sentence should point to a supporting passage, source date, and scope. Put insufficient evidence in the output contract rather than inviting the model to fill gaps.", "Jede wichtige Aussage braucht Passage, Quelldatum und Umfang. Bei fehlender Quelle „unzureichende Evidenz“ vertraglich ausgeben statt Lücken erfinden.", "每个重要句子都应指向支持段落、来源日期与范围。来源不足时，应在输出契约中返回“证据不足”，而不是让模型填补空白。")),
    ],
  },
  {
    slug: "accessible-local-tools-error-feedback", relatedTools: ["cumle-sadelestirici", "renk-kontrast-denetleyici", "metin-farki-diff"],
    title: L("Yerel Araçlarda Erişilebilir Hata ve İşlem Geri Bildirimi", "Accessible Errors and Processing Feedback in Local Tools", "Barrierefreie Fehler- und Verarbeitungsrückmeldung in lokalen Werkzeugen", "本地工具中的无障碍错误与处理反馈"), excerpt: L("İşleniyor, tamamlandı ve hata durumlarını yalnız renge değil eyleme ve açıklamaya bağlayın.", "Connect processing, completion, and error states to action and explanation—not color alone.", "Verarbeitung, Erfolg und Fehler mit Aktion und Erklärung statt nur Farbe verbinden.", "把处理中、完成与错误状态连接到操作和说明，而不只依赖颜色。"), category: L("Erişilebilir UX", "Accessible UX", "Barrierefreie UX", "无障碍体验"),
    points: [
      P(L("Durumu anında ve canlı bölgede gösterin", "Announce state immediately", "Status sofort ankündigen", "立即播报状态"), L("Kullanıcı işlemi başlattığında buton kilitlenmeli ve görünür ‘işleniyor’ mesajı aynı anda çıkmalıdır. Sonuç aria-live bölgesinde duyurulmalı; uzun işlem ana iş parçacığını bölmeli veya Worker kullanmalıdır.", "When processing starts, disable duplicate submission and show a visible status immediately. Announce results in an aria-live region, and split long work or move it to a Worker.", "Beim Start Doppelausführung sperren und sichtbaren Status sofort zeigen. Ergebnisse per aria-live ankündigen und lange Arbeit teilen oder Worker nutzen.", "处理开始时应禁用重复提交并立即显示状态。结果应在 aria-live 区域播报；长任务应分段或移入 Worker。")),
      P(L("Hata kullanıcının düzeltebileceği bilgi olsun", "Make errors actionable", "Fehler handlungsfähig machen", "让错误可操作"), L("‘Geçersiz girdi’ yerine satır, alan, beklenen biçim ve bir sonraki düzeltme eylemini yazın. Konsol ayrıntısını kişisel veri veya stack trace ile ekrana taşımayın; teknik tanı ve kullanıcı mesajını ayırın.", "Replace invalid input with line, field, expected shape, and next corrective action. Do not expose personal data or raw stack traces; separate technical diagnostics from user-facing copy.", "Statt „ungültig“ Zeile, Feld, erwartete Form und nächste Korrektur nennen. Keine Personendaten oder rohe Stacktraces zeigen; Diagnose und Nutzermeldung trennen.", "不要只显示“输入无效”，应给出行号、字段、预期格式与下一步修正。不要暴露个人数据或原始堆栈；技术诊断与用户文案要分开。")),
      P(L("Kontrast ve mobil akışı birlikte test edin", "Test contrast and mobile flow together", "Kontrast und Mobilfluss gemeinsam testen", "一起测试对比度与移动流程"), L("İkincil metin, placeholder ve disabled durumları iki temada okunmalıdır. İki kolon mobilde dikey akmalı; kod ve tablo yatay kaydırmalı, düğmeler en az rahat dokunma alanı sağlamalıdır.", "Secondary text, placeholders, and disabled states must remain readable in both themes. Two columns should stack on mobile; code and tables should scroll, and controls need comfortable touch targets.", "Sekundärtext, Platzhalter und Disabled-Zustände müssen in beiden Themes lesbar bleiben. Spalten mobil stapeln, Code/Tabellen scrollen und Touch-Ziele ausreichend groß halten.", "次要文本、占位符与禁用状态在两种主题下都应可读。双列在移动端应纵向堆叠；代码和表格可横向滚动，控件应有舒适触摸区域。")),
    ],
  },
  {
    slug: "p2p-collaboration-safety-codes", relatedTools: ["arac-zinciri-pipeline", "url-guvenlik-on-kontrolu", "sha256-ozet-uretici"],
    title: L("WebRTC P2P İşbirliğinde Güvenlik Kodu ve Veri Sınırı", "Safety Codes and Data Boundaries in WebRTC P2P Collaboration", "Sicherheitscodes und Datengrenzen bei WebRTC-P2P", "WebRTC P2P 协作中的安全码与数据边界"), excerpt: L("Şifreli aktarımı kimlik doğrulama sanmadan davet, onay ve paylaşım sınırlarını yönetin.", "Manage invitation, consent, and sharing boundaries without mistaking encryption for identity verification.", "Einladung, Zustimmung und Freigabe steuern, ohne Verschlüsselung mit Identitätsprüfung zu verwechseln.", "管理邀请、同意与共享边界，不要把加密误认为身份验证。"), category: L("P2P güvenliği", "P2P security", "P2P-Sicherheit", "P2P 安全"),
    points: [
      P(L("Sinyal kodunu sır gibi ele alın", "Treat signaling codes as sensitive", "Signalcodes sensibel behandeln", "把信令代码当作敏感信息"), L("Offer ve answer SDP kodları ağ adayları ve oturum materyali içerebilir. Yalnızca güvendiğiniz kişiye, ayrı bir kanaldan gönderin; süre dolunca veya oda kapanınca yeniden kullanmayın.", "Offer and answer SDP codes can contain network candidates and session material. Send them only to a trusted person through a separate channel, and never reuse them after expiry or room closure.", "Offer-/Answer-SDP kann Netzwerkkandidaten und Sitzungsmaterial enthalten. Nur über separaten Kanal an Vertrauensperson senden und nach Ablauf nicht wiederverwenden.", "Offer 与 Answer SDP 代码可能包含网络候选和会话材料。只通过独立渠道发送给可信的人，过期或关闭房间后不要复用。")),
      P(L("Güvenlik kodunu sesli karşılaştırın", "Compare the safety code out-of-band", "Sicherheitscode separat vergleichen", "通过独立渠道核对安全码"), L("DTLS aktarımı şifreler, fakat yanlış kişiyle kurulan şifreli bağlantı hâlâ yanlıştır. Her iki ekrandaki fingerprint tabanlı kısa kodu sesli veya ayrı güvenilir kanalda karşılaştırmadan paylaşımı açmayın.", "DTLS encrypts transport, but an encrypted connection to the wrong person is still wrong. Compare the fingerprint-derived short code by voice or another trusted channel before enabling sharing.", "DTLS verschlüsselt, aber eine verschlüsselte Verbindung zur falschen Person bleibt falsch. Fingerprint-Code per Sprache oder anderem Vertrauenskanal vergleichen.", "DTLS 会加密传输，但与错误的人建立加密连接仍然是错误的。启用共享前，通过语音或其他可信渠道核对基于指纹的短码。")),
      P(L("Sunucusuz sınırı doğru anlatın", "State the serverless boundary honestly", "Serverlose Grenze ehrlich benennen", "诚实说明无服务器边界"), L("Manuel kod değişimi ortak sinyalleme, STUN ve TURN kullanmaz; bazı NAT/firewall çiftleri bağlanamaz. Küresel üye dizini, kalıcı mesaj ve herkese açık akış ortak depolama gerektirir; yalnız tarayıcıyla varmış gibi gösterilemez.", "Manual code exchange uses no shared signaling, STUN, or TURN, so some NAT or firewall pairs cannot connect. A global directory, durable chat, and public feed require shared storage and cannot honestly be simulated by browser-only state.", "Manueller Codeaustausch nutzt keine Signalisierung, STUN oder TURN; manche NAT/Firewall-Paare verbinden nicht. Globales Verzeichnis, dauerhafte Nachrichten und öffentlicher Feed brauchen gemeinsame Speicherung.", "手动代码交换不使用共享信令、STUN 或 TURN，因此部分 NAT/防火墙组合无法连接。全球目录、持久聊天与公开 Feed 需要共享存储，不能用浏览器本地状态假装实现。")),
    ],
  },
  {
    slug: "privacy-first-news-rss-source-transparency", relatedTools: ["kaynak-guvenilirlik-matrisi", "atif-yer-tutucu-denetleyici", "url-guvenlik-on-kontrolu"],
    title: L("Gizlilik Odaklı RSS Gündeminde Kaynak ve Telif Şeffaflığı", "Source and Copyright Transparency in a Privacy-First RSS Feed", "Quellen- und Urheberrechtstransparenz in einem datenschutzorientierten RSS-Feed", "隐私优先 RSS 动态中的来源与版权透明度"), excerpt: L("Otomatik güncellemeyi yeniden yayıncılık, sonsuz akış ve takip riskine dönüştürmeden tasarlayın.", "Design automatic updates without turning them into republication, endless feeds, or tracking.", "Automatische Aktualisierung ohne Wiederveröffentlichung, Endlosfeed oder Tracking gestalten.", "设计自动更新，同时避免全文转载、无限信息流与跟踪。"), category: L("Kaynak şeffaflığı", "Source transparency", "Quellentransparenz", "来源透明"),
    points: [
      P(L("RSS izni ile makale hakkını ayırın", "Separate feed syndication from article rights", "Feed-Syndikation und Artikelrechte trennen", "区分 Feed 联合与文章权利"), L("Bir kaynağın RSS sunması başlık ve bağlantının okunmasını amaçlar; her makalenin metin ve görselini serbestçe yeniden yayımlama izni anlamına gelmez. En dar veri setini alın ve özgün kaynağa yönlendirin.", "An RSS endpoint supports reading feed records; it does not automatically license every article body and image for republication. Collect the narrowest data set and send readers to the original source.", "Ein RSS-Feed erlaubt das Lesen der Feed-Daten, nicht automatisch die Wiederveröffentlichung aller Texte und Bilder. Nur minimale Daten übernehmen und zur Originalquelle führen.", "RSS 端点支持读取 Feed 记录，但并不自动许可转载每篇文章正文和图片。只收集最小数据集，并把读者引向原始来源。")),
      P(L("Kaynak listesini kodda sınırlandırın", "Allowlist sources in code", "Quellen im Code erlauben", "在代码中设置来源白名单"), L("Yalnız HTTPS, sabit alan adı ve resmî feed uçları kabul edilmelidir. Yönlendirme sonrası host tekrar doğrulanmalı, yanıt boyutu/zamanı sınırlanmalı ve HTML içerik ekrana ham basılmamalıdır.", "Accept only HTTPS, fixed domains, and official endpoints. Revalidate hosts after redirects, cap response time and size, and never render feed HTML as raw page content.", "Nur HTTPS, feste Domains und offizielle Endpunkte akzeptieren. Host nach Redirect prüfen, Zeit/Größe begrenzen und Feed-HTML nie roh rendern.", "仅接受 HTTPS、固定域名与官方端点。重定向后再次验证主机，限制响应时间和大小，绝不把 Feed HTML 原样渲染。")),
      P(L("Sonsuz akış yerine sonlu keşif", "Use finite discovery, not endless scroll", "Endliche Entdeckung statt Endlosscroll", "使用有限发现而非无限滚动"), L("İlk sayfada sınırlı kart gösterin, kategori ve arama sunun, ‘daha fazla’ eylemini kullanıcı başlatsın. Favori yalnız cihazda kalmalı; kaynağı açmanın üçüncü taraf siteye geçiş olduğu açıkça yazılmalıdır.", "Show a bounded first page with category and search controls, then let the user request more. Keep favorites on-device and disclose that opening a source navigates to a third-party site.", "Begrenzte erste Seite mit Kategorie und Suche zeigen; mehr nur auf Nutzeraktion. Favoriten lokal halten und Wechsel zur Drittseite klar nennen.", "首屏显示有限卡片并提供分类和搜索，由用户主动请求更多。收藏保留在设备端，并明确说明打开来源会前往第三方网站。")),
    ],
  },
  {
    slug: "browser-pwa-offline-app-boundaries", relatedTools: ["dosya-risk-on-taramasi", "gorsel-sikistirici", "json-bicimlendirici"],
    title: L("Tarayıcı PWA'sını Gerçek Bir Uygulama Gibi Tasarlama", "Designing a Browser PWA That Feels Like a Real App", "Eine Browser-PWA wie eine echte App gestalten", "把浏览器 PWA 设计成真正的应用体验"), excerpt: L("Kurulum, çevrimdışı davranış, depolama ve dosya sınırlarını teknik jargon yerine kullanıcı göreviyle açıklayın.", "Explain install, offline behavior, storage, and file limits through user tasks rather than technical jargon.", "Installation, Offline-Verhalten, Speicher und Dateigrenzen anhand von Nutzeraufgaben erklären.", "用用户任务而非技术术语说明安装、离线、存储与文件边界。"), category: L("PWA deneyimi", "PWA experience", "PWA-Erlebnis", "PWA 体验"),
    points: [
      P(L("Kurulum çağrısını platforma göre açıklayın", "Explain install by platform", "Installation plattformspezifisch erklären", "按平台解释安装"), L("Tarayıcı beforeinstallprompt sunuyorsa doğrudan düğme gösterin; sunmuyorsa iOS Paylaş→Ana Ekrana Ekle veya masaüstü menü yolunu anlatın. APK ve Android sürüm terminolojisi, web PWA kurulumu için gereksiz korku yaratmamalıdır.", "Show a direct button when beforeinstallprompt exists; otherwise explain iOS Share→Add to Home Screen or the desktop browser path. APK and Android-version language should not confuse a web PWA install.", "Bei beforeinstallprompt direkt installieren, sonst iOS Teilen→Zum Home-Bildschirm oder Desktop-Menü erklären. APK-/Android-Versionstext gehört nicht zur Web-PWA-Installation.", "存在 beforeinstallprompt 时显示直接安装按钮；否则说明 iOS 分享→添加到主屏幕或桌面浏览器路径。不要用 APK 与 Android 版本术语混淆 Web PWA 安装。")),
      P(L("Çevrimdışı sınırı dosya düzeyinde test edin", "Test offline behavior by task", "Offline-Verhalten je Aufgabe testen", "按任务测试离线行为"), L("Ana kabuk önbellekte olsa bile ilk kez açılmayan rota veya lazy chunk çevrimdışı bulunmayabilir. Kurulum sonrası uçak modunda ana sayfa, Ajan, İş İstasyonu ve birkaç önemli aracı gerçek görevle test edin.", "A cached shell does not guarantee an unopened route or lazy chunk is offline. After install, use airplane mode to test home, Agent, Workstation, and key tools with real tasks.", "Ein gecachter Shell garantiert keine ungeöffnete Route oder Lazy-Chunk. Nach Installation im Flugmodus Start, Agent, Workstation und wichtige Aufgaben testen.", "缓存应用外壳并不保证未打开过的路由或懒加载块可离线。安装后应在飞行模式下用真实任务测试首页、助手、工作站与关键工具。")),
      P(L("Yerel depolamayı kullanıcı kontrolünde tutun", "Keep local storage under user control", "Lokalen Speicher kontrollierbar halten", "让用户控制本地存储"), L("IndexedDB projesi cihazda AES-GCM ile şifrelenebilir, ancak aynı tarayıcı profili ve cihaz güvenliği sınırındadır. Proje silme, kalıcı depolama isteği, dışa aktarma ve hassas girdi uyarısı açık olmalıdır.", "IndexedDB projects can be AES-GCM encrypted, but remain within the browser-profile and device-security boundary. Make deletion, persistence requests, export, and sensitive-input warnings explicit.", "IndexedDB-Projekte können AES-GCM-verschlüsselt sein, bleiben aber an Browserprofil und Gerätesicherheit gebunden. Löschen, Persistenz, Export und sensible Eingaben klar erklären.", "IndexedDB 项目可使用 AES-GCM 加密，但仍受浏览器配置与设备安全边界约束。应明确说明删除、持久存储请求、导出与敏感输入警告。")),
    ],
  },
  {
    slug: "seo-aeo-geo-useful-tool-pages", relatedTools: ["seo-slug-olusturucu", "hreflang-etiket-olusturucu", "faq-json-ld-olusturucu"],
    title: L("Araç Sayfalarında SEO, AEO ve GEO: Fayda Önce Gelir", "SEO, AEO, and GEO for Tool Pages: Utility Comes First", "SEO, AEO und GEO für Werkzeugseiten: Nutzen zuerst", "工具页面的 SEO、AEO 与 GEO：实用性优先"), excerpt: L("Anahtar kelime çoğaltmak yerine çalışan demo, özgün rehber, doğru dil sinyali ve sınır üretin.", "Build working demos, original guidance, correct language signals, and honest limits instead of multiplying keywords.", "Funktionierende Demos, eigene Anleitungen, richtige Sprachsignale und ehrliche Grenzen statt Keyword-Vervielfachung.", "不要堆砌关键词，应提供可运行 Demo、原创指南、正确语言信号与诚实边界。"), category: L("Arama kalitesi", "Search quality", "Suchqualität", "搜索质量"),
    points: [
      P(L("Her URL tek bir arama niyetini karşılasın", "Give each URL one clear intent", "Jede URL erfüllt eine klare Absicht", "每个 URL 对应一个明确意图"), L("Araç sayfası çalışan giriş/çıkış, örnek, hata açıklaması, yöntem, sınır ve ilgili iş akışını birlikte sunmalıdır. Aynı içeriğin yalnız sözcükleri değişmiş yüzlerce sayfası ölçekli içerik kötüye kullanımına dönüşebilir.", "A tool page should combine working input/output, demo, error help, method, boundary, and related workflow. Hundreds of near-duplicate pages with query variations can become scaled content abuse.", "Eine Werkzeugseite braucht funktionierende Ein-/Ausgabe, Beispiel, Fehlerhilfe, Methode, Grenzen und Ablauf. Hunderte nahezu gleiche Query-Seiten können skalierter Missbrauch sein.", "工具页应同时提供可运行输入输出、示例、错误帮助、方法、边界与相关流程。仅替换查询词的大量近重复页面可能构成规模化内容滥用。")),
      P(L("Dil sinyalini URL ve içerikle eşleyin", "Align language signals with content", "Sprachsignale mit Inhalt abstimmen", "让语言信号与内容一致"), L("Canonical kendini göstermeli; hreflang tr-TR, en-US, de-DE, zh-CN ve x-default karşılıklı bağlanmalıdır. Başlık, açıklama, görünür metin ve yapılandırılmış veri gerçekten o dilde olmalıdır.", "Canonical should be self-referential; tr-TR, en-US, de-DE, zh-CN, and x-default hreflang entries should be reciprocal. Title, description, visible copy, and structured data must genuinely use that language.", "Canonical zeigt auf sich; hreflang tr-TR, en-US, de-DE, zh-CN und x-default ist reziprok. Titel, Beschreibung, Inhalt und strukturierte Daten müssen wirklich diese Sprache nutzen.", "Canonical 应自引用；tr-TR、en-US、de-DE、zh-CN 与 x-default 的 hreflang 应相互对应。标题、描述、可见内容与结构化数据必须真正使用该语言。")),
      P(L("Şema görünür içeriği yansıtsın", "Make schema reflect visible content", "Schema spiegelt sichtbaren Inhalt", "让 Schema 反映可见内容"), L("HowTo adımları ve FAQ yanıtları sayfada kullanıcı tarafından okunabilmelidir. Yapılandırılmış veri sıralama garantisi değildir; gizli anahtar kelime, uydurma puan veya gerçekte olmayan özellik eklemeyin.", "HowTo steps and FAQ answers should be visible to users. Structured data is not a ranking guarantee; never add hidden keywords, invented ratings, or nonexistent features.", "HowTo-Schritte und FAQ-Antworten müssen sichtbar sein. Strukturierte Daten garantieren kein Ranking; keine versteckten Keywords, erfundenen Bewertungen oder nicht vorhandenen Funktionen.", "HowTo 步骤和 FAQ 回答应对用户可见。结构化数据不保证排名；不要添加隐藏关键词、虚假评分或不存在的功能。")),
    ],
  },
];

function sections(locale: Locale, points: [Point, Point, Point]): ArticleSection[] {
  const depth = depthCopy[locale];
  return [
    ...points.map((point, index) => ({ heading: point.heading[locale], paragraphs: [point.body[locale], method[locale][index], depth.evidence], bullets: bullets[locale] })),
    { heading: depth.walkthrough, paragraphs: [depth.walkthroughBody, `${points[0].heading[locale]} → ${points[1].heading[locale]} → ${points[2].heading[locale]}`], bullets: depth.walkthroughBullets },
    { heading: depth.quality, paragraphs: [depth.qualityBody], bullets: depth.qualityBullets },
  ];
}

export const expansionPosts: Post[] = specs.map((spec) => ({
  slug: spec.slug, relatedTools: spec.relatedTools, date: "2026-07-25", updated: "2026-07-26",
  readTime: { tr: "16 dk", en: "15 min" },
  title: { tr: spec.title.tr, en: spec.title.en }, excerpt: { tr: spec.excerpt.tr, en: spec.excerpt.en },
  description: { tr: `${spec.excerpt.tr} Yöntem, sınır, örnek iş akışı ve doğrulama adımlarıyla ayrıntılı ByteQuant rehberi.`, en: `${spec.excerpt.en} A detailed ByteQuant guide with method, boundaries, workflow, and verification steps.` },
  category: { tr: spec.category.tr, en: spec.category.en }, visualSuggestion: { tr: "Girdi, yerel işlem, doğrulama ve teslim sınırlarını gösteren sade iş akışı.", en: "A clear workflow showing input, local processing, verification, and delivery boundaries." },
  sections: { tr: sections("tr", spec.points), en: sections("en", spec.points) },
}));

export const expansionLocalizedGuides: LocalizedGuide[] = specs.map((spec) => ({
  slug: spec.slug, relatedTools: spec.relatedTools, date: "2026-07-25", updated: "2026-07-26",
  copy: {
    de: { title: spec.title.de, excerpt: spec.excerpt.de, description: `${spec.excerpt.de} Ausführlicher ByteQuant-Leitfaden mit Methode, Grenzen, Ablauf und Prüfung.`, category: spec.category.de, readTime: "15 Min.", sections: sections("de", spec.points) },
    zh: { title: spec.title.zh, excerpt: spec.excerpt.zh, description: `${spec.excerpt.zh}包含方法、边界、工作流与核验步骤的详细 ByteQuant 指南。`, category: spec.category.zh, readTime: "约 15 分钟", sections: sections("zh", spec.points) },
  },
}));
