import type { Locale } from "./site";
import type { ToolCategory } from "./tools";
import type { BaseTool } from "./tool-locales";

type L = Record<Locale, string>;
type Spec = { slug: string; category: ToolCategory; mark: string; title: L; purpose: L };

const l = (tr: string, en: string, de: string, zh: string): L => ({ tr, en, de, zh });

const categoryBoundary: Record<ToolCategory, L> = {
  prompt: l("Kural tabanlı sonuç, gerçek model davranışının kanıtı değildir; temsilî vakalarla yeniden sınayın.", "The rule-based result is not proof of model behaviour; retest with representative cases.", "Das regelbasierte Ergebnis beweist kein Modellverhalten; testen Sie repräsentative Fälle.", "规则结果不能证明模型行为；请使用代表性案例复测。"),
  text: l("Metin cihazınızdan ayrılmaz; anlam ve bağlam kararları için son insan kontrolü gerekir.", "Text stays on your device; meaning and context still require human review.", "Text bleibt auf Ihrem Gerät; Bedeutung und Kontext benötigen menschliche Prüfung.", "文本不会离开设备；语义与语境仍需人工复核。"),
  data: l("Dönüşüm yereldir; şema, kodlama ve veri kaybı varsayımlarını hedef sistemde doğrulayın.", "Conversion is local; verify schema, encoding, and data-loss assumptions in the target system.", "Die Konvertierung ist lokal; Schema, Kodierung und Datenverlust im Zielsystem prüfen.", "转换在本地完成；请在目标系统核验架构、编码与数据丢失假设。"),
  converter: l("Kaynak değiştirilmez; çıktıyı hedef uygulamada açıp birlikte çalışabilirliği doğrulayın.", "The source is not changed; open the output in the target app to verify interoperability.", "Die Quelle bleibt unverändert; prüfen Sie die Ausgabe in der Zielanwendung.", "源内容不会被修改；请在目标应用中打开输出并验证互操作性。"),
  security: l("Bu açıklanabilir bir ön kontroldür; güvenlik, kimlik veya mevzuat uyumu garantisi değildir.", "This is an explainable pre-check, not a security, identity, or compliance guarantee.", "Dies ist eine nachvollziehbare Vorprüfung, keine Sicherheits- oder Compliance-Garantie.", "这是可解释的预检查，不构成安全、身份或合规保证。"),
  calculation: l("Formül ve varsayımlar görünürdür; sonuç profesyonel finans veya bilim tavsiyesi değildir.", "Formulas and assumptions are visible; the result is not professional financial or scientific advice.", "Formeln und Annahmen sind sichtbar; keine professionelle Finanz- oder Wissenschaftsberatung.", "公式与假设均可见；结果不构成专业财务或科学建议。"),
  general: l("Düzenlenebilir bir taslak üretir; resmî kayıt, davet veya uzman onayı yerine geçmez.", "It produces an editable draft and does not replace an official record, invitation, or expert approval.", "Erzeugt einen bearbeitbaren Entwurf und ersetzt keine offizielle Freigabe.", "工具生成可编辑草稿，不能替代正式记录、邀请或专家批准。"),
  ai: l("Uzak model çağırmaz; AI iş akışını planlar fakat model çıktısı üretmez veya doğrulamaz.", "It calls no remote model; it plans AI work but neither generates nor verifies model output.", "Kein Remote-Modell; plant KI-Arbeit, erzeugt oder prüft aber keine Modellantwort.", "不调用远程模型；仅规划 AI 工作流，不生成或验证模型输出。"),
  codeSecurity: l("Kod çalıştırılmadan desenler incelenir; sonuç tam SAST veya istismar kanıtı değildir.", "Patterns are inspected without executing code; the result is not full SAST or proof of exploitability.", "Muster werden ohne Codeausführung geprüft; kein vollständiges SAST oder Exploit-Nachweis.", "仅在不执行代码的情况下检查模式；不等同于完整 SAST 或可利用性证明。"),
  research: l("Kaynaklara ağ isteği yapılmaz; doğruluk, erişilebilirlik ve kaliteyi birincil kaynaktan doğrulayın.", "No source is fetched; verify accuracy, availability, and quality at the primary source.", "Quellen werden nicht abgerufen; Richtigkeit und Qualität an der Primärquelle prüfen.", "工具不会联网获取来源；请在第一手来源核验准确性、可用性与质量。"),
};

const useCases: Record<Locale, string[]> = {
  tr: ["Yayın öncesi denetlenebilir kalite kontrolü", "Tekrarlanabilir ekip iş akışı", "Hata ve sınır durumlarını erken görünür kılma"],
  en: ["Auditable pre-publication quality control", "Repeatable team workflows", "Exposing errors and edge cases early"],
  de: ["Prüfbare Qualitätskontrolle vor Veröffentlichung", "Wiederholbare Teamabläufe", "Fehler und Grenzfälle früh erkennen"],
  zh: ["发布前可审计质量检查", "可重复的团队工作流", "尽早发现错误与边界情况"],
};

const steps: Record<Locale, string[]> = {
  tr: ["Güvenli örneği yükleyin veya kendi verinizi girin.", "İşlemi cihazınızda çalıştırıp hata, uyarı ve ölçümleri inceleyin.", "Çıktıyı hedef ortam ve sınır vakalarıyla doğrulayın."],
  en: ["Load the safe example or enter your own data.", "Run it on-device and inspect errors, warnings, and metrics.", "Validate the output in the target environment and with edge cases."],
  de: ["Sicheres Beispiel laden oder eigene Daten eingeben.", "Lokal ausführen und Fehler, Warnungen und Kennzahlen prüfen.", "Ausgabe im Zielsystem und mit Grenzfällen validieren."],
  zh: ["加载安全示例或输入自己的数据。", "在设备端运行并检查错误、警告与指标。", "在目标环境和边界案例中验证输出。"],
};

const specs: Spec[] = [
  { slug: "prompt-negatif-kisit-denetleyici", category: "prompt", mark: "247", title: l("Prompt Negatif Kısıt Denetleyici", "Prompt Negative-Constraint Auditor", "Prompt-Negativbedingungsprüfung", "提示词否定约束检查器"), purpose: l("Zorunluluk ve yasakların birbiriyle çeliştiği satırları bulun.", "Find lines where requirements and prohibitions conflict.", "Widersprüche zwischen Pflichten und Verboten finden.", "查找要求与禁止项相互冲突的行。") },
  { slug: "prompt-degisken-tip-denetleyici", category: "prompt", mark: "248", title: l("Prompt Değişken Tip Denetleyici", "Prompt Variable Type Checker", "Prompt-Variablentypprüfung", "提示词变量类型检查器"), purpose: l("Şablon değişkenlerini örnek JSON değerleriyle tür ve zorunluluk açısından sınayın.", "Test template variables against example JSON for type and requiredness.", "Vorlagenvariablen mit Beispiel-JSON auf Typ und Pflicht prüfen.", "用示例 JSON 检查模板变量类型与必填项。") },
  { slug: "prompt-cikti-belirlilik-denetleyici", category: "prompt", mark: "249", title: l("Prompt Çıktı Belirlilik Denetleyici", "Prompt Output Determinism Checker", "Prompt-Ausgabebestimmtheitsprüfung", "提示词输出确定性检查器"), purpose: l("Belirsiz ifadeleri ve eksik çıktı sözleşmelerini görünür kılın.", "Expose ambiguous wording and missing output contracts.", "Mehrdeutige Formulierungen und fehlende Ausgabeverträge erkennen.", "识别模糊措辞与缺失的输出契约。") },
  { slug: "prompt-ornek-denge-analizoru", category: "prompt", mark: "250", title: l("Prompt Örnek Denge Analizörü", "Prompt Example Balance Analyzer", "Prompt-Beispielausgleichsanalyse", "提示词示例平衡分析器"), purpose: l("Few-shot sınıf, uzunluk, tekrar ve sınır vakası dengesini ölçün.", "Measure few-shot class, length, duplication, and edge-case balance.", "Klassen-, Längen-, Duplikat- und Grenzfallbalance messen.", "衡量少样本类别、长度、重复与边界案例平衡。") },
  { slug: "prompt-yerellestirme-kontrol-listesi", category: "prompt", mark: "251", title: l("Prompt Yerelleştirme Kontrol Listesi", "Prompt Localisation Checklist", "Prompt-Lokalisierungscheckliste", "提示词本地化检查清单"), purpose: l("Diller arasında yer tutucu, sayı, URL ve değişmez terim kaybını bulun.", "Find placeholder, number, URL, and invariant-term loss across languages.", "Verluste bei Platzhaltern, Zahlen, URLs und festen Begriffen finden.", "查找跨语言占位符、数字、URL 与固定术语丢失。") },
  { slug: "prompt-bagimlilik-grafi-cikarici", category: "prompt", mark: "252", title: l("Prompt Bağımlılık Grafiği Çıkarıcı", "Prompt Dependency Graph Builder", "Prompt-Abhängigkeitsgraph", "提示词依赖关系图生成器"), purpose: l("Adım bağımlılıklarını sıralayın, eksik düğüm ve döngüleri bulun.", "Order step dependencies and find missing nodes and cycles.", "Schrittabhängigkeiten ordnen und fehlende Knoten oder Zyklen finden.", "排序步骤依赖并查找缺失节点与循环。") },
  { slug: "prompt-rubrik-puanlayici", category: "prompt", mark: "253", title: l("Prompt Rubrik Puanlayıcı", "Prompt Rubric Scorer", "Prompt-Rubrikbewertung", "提示词评分量表计算器"), purpose: l("Ağırlıklı ölçütleri şeffaf formülle puanlayıp toplam ağırlığı doğrulayın.", "Score weighted criteria transparently and validate total weight.", "Gewichtete Kriterien transparent bewerten und Gesamtgewicht prüfen.", "透明计算加权标准并验证总权重。") },
  { slug: "prompt-tutarlilik-senaryo-testi", category: "prompt", mark: "254", title: l("Prompt Tutarlılık Senaryo Testi", "Prompt Consistency Scenario Test", "Prompt-Konsistenz-Szenariotest", "提示词一致性场景测试"), purpose: l("Aynı hedefe verilen senaryo kurallarındaki sayı ve olumsuzluk çelişkilerini bulun.", "Find numeric and negation conflicts across rules for the same goal.", "Zahlen- und Negationskonflikte in Szenarioregeln finden.", "查找同一目标规则中的数字与否定冲突。") },
  { slug: "cumle-uzunluk-dagilimi", category: "text", mark: "255", title: l("Cümle Uzunluk Dağılımı", "Sentence Length Distribution", "Satzlängenverteilung", "句子长度分布"), purpose: l("Cümleleri uzunluk aralıklarına ayırıp uç değerleri gösterin.", "Bucket sentence lengths and expose outliers.", "Satzlängen gruppieren und Ausreißer anzeigen.", "按长度分组句子并显示离群值。") },
  { slug: "tekrar-eden-ifade-bulucu", category: "text", mark: "256", title: l("Tekrar Eden İfade Bulucu", "Repeated Phrase Finder", "Phrasenwiederholungsfinder", "重复短语查找器"), purpose: l("İki ile beş kelimelik tekrarları sıklık ve konumuyla bulun.", "Find repeated two-to-five-word phrases with frequency and position.", "Wiederholte Zwei- bis Fünfwortphrasen mit Häufigkeit finden.", "查找重复的二至五词短语及其频率。") },
  { slug: "liste-tutarlilik-denetleyici", category: "text", mark: "257", title: l("Liste Tutarlılık Denetleyici", "List Consistency Checker", "Listenkonsistenzprüfung", "列表一致性检查器"), purpose: l("Madde işareti, numaralandırma, noktalama ve tekrar tutarlılığını sınayın.", "Check bullet, numbering, punctuation, and duplication consistency.", "Aufzählung, Nummerierung, Zeichensetzung und Duplikate prüfen.", "检查项目符号、编号、标点与重复一致性。") },
  { slug: "noktalama-tirnak-normalizasyonu", category: "text", mark: "258", title: l("Noktalama ve Tırnak Normalizasyonu", "Punctuation & Quote Normalizer", "Zeichensetzungs- und Anführungsnormalisierung", "标点与引号规范化"), purpose: l("Tırnak, tire ve boşlukları seçilen güvenli stile dönüştürün.", "Normalize quotes, dashes, and spacing to a selected safe style.", "Anführungen, Gedankenstriche und Abstände sicher normalisieren.", "将引号、破折号与空格规范为所选安全样式。") },
  { slug: "kisaltma-sozluk-cikarici", category: "text", mark: "259", title: l("Kısaltma Sözlüğü Çıkarıcı", "Acronym Glossary Extractor", "Abkürzungsverzeichnis-Extraktor", "缩略语词汇表提取器"), purpose: l("Büyük harfli kısaltmaları, ilk tanımı ve kullanım sayısıyla çıkarın.", "Extract uppercase acronyms with first definition and use count.", "Großgeschriebene Abkürzungen mit Definition und Häufigkeit extrahieren.", "提取大写缩略语、首次定义与使用次数。") },
  { slug: "sade-dil-kontrolu", category: "text", mark: "260", title: l("Sade Dil Kontrolü", "Plain-Language Checker", "Klarsprache-Prüfung", "简明语言检查器"), purpose: l("Uzun cümle, jargon ve dolaylı anlatım sinyallerini açıklanabilir puanla bulun.", "Find long sentences, jargon, and indirect wording with an explainable score.", "Lange Sätze, Jargon und indirekte Sprache nachvollziehbar erkennen.", "以可解释评分识别长句、术语与间接表达。") },
  { slug: "baslik-hiyerarsisi-denetleyici", category: "text", mark: "261", title: l("Başlık Hiyerarşisi Denetleyici", "Heading Hierarchy Auditor", "Überschriftenhierarchie-Prüfung", "标题层级检查器"), purpose: l("Markdown başlık atlamalarını, tekrarları ve boş başlıkları bulun.", "Find Markdown heading jumps, duplicates, and empty headings.", "Sprünge, Duplikate und leere Markdown-Überschriften finden.", "查找 Markdown 标题跳级、重复与空标题。") },
  { slug: "terim-tutarlilik-denetleyici", category: "text", mark: "262", title: l("Terim Tutarlılık Denetleyici", "Terminology Consistency Checker", "Terminologiekonsistenz-Prüfung", "术语一致性检查器"), purpose: l("Tercih edilen terimlerle yasak varyantların kullanımını karşılaştırın.", "Compare preferred terms with disallowed variants.", "Bevorzugte Begriffe mit unerwünschten Varianten vergleichen.", "比较首选术语与禁用变体的使用情况。") },
  { slug: "paragraf-gecis-analizoru", category: "text", mark: "263", title: l("Paragraf Geçiş Analizörü", "Paragraph Transition Analyzer", "Absatzübergangsanalyse", "段落过渡分析器"), purpose: l("Paragraflar arasındaki bağlayıcı ve konu sürekliliği sinyallerini ölçün.", "Measure connector and topic-continuity signals between paragraphs.", "Konnektoren und Themenkontinuität zwischen Absätzen messen.", "衡量段落间连接词与主题连续性。") },
  { slug: "json-yol-degeri-cikarici", category: "data", mark: "264", title: l("JSON Yol Değeri Çıkarıcı", "JSON Path Value Extractor", "JSON-Pfadwert-Extraktor", "JSON 路径值提取器"), purpose: l("Nokta ve dizi indeksli basit yollardan değerleri güvenle çıkarın.", "Safely extract values with simple dot and array-index paths.", "Werte sicher über Punkt- und Arraypfade extrahieren.", "通过点路径与数组索引安全提取值。") },
  { slug: "json-ornek-veri-uretici", category: "data", mark: "265", title: l("JSON Schema Örnek Veri Üretici", "JSON Schema Sample Builder", "JSON-Schema-Beispielgenerator", "JSON Schema 示例生成器"), purpose: l("JSON Schema tür, required ve example alanlarından deterministik örnek üretin.", "Build deterministic samples from JSON Schema types, required fields, and examples.", "Deterministische Beispiele aus JSON-Schema erzeugen.", "根据 JSON Schema 类型、必填项与示例生成确定性样本。") },
  { slug: "csv-sutun-yeniden-adlandirici", category: "data", mark: "266", title: l("CSV Sütun Yeniden Adlandırıcı", "CSV Column Renamer", "CSV-Spaltenumbenenner", "CSV 列重命名器"), purpose: l("Başlıkları eşleme tablosuyla değiştirip çakışmaları durdurun.", "Rename headers with a mapping table and stop collisions.", "Spalten per Mapping umbenennen und Kollisionen stoppen.", "按映射表重命名表头并阻止冲突。") },
  { slug: "csv-ayirac-tespit-araci", category: "data", mark: "267", title: l("CSV Ayıraç Tespit Aracı", "CSV Delimiter Detector", "CSV-Trennzeichenerkennung", "CSV 分隔符检测器"), purpose: l("Virgül, noktalı virgül, sekme ve dik çizgiyi satır tutarlılığıyla puanlayın.", "Score comma, semicolon, tab, and pipe by row consistency.", "Komma, Semikolon, Tab und Pipe nach Zeilenkonsistenz bewerten.", "按行一致性评估逗号、分号、制表符与竖线。") },
  { slug: "ndjson-toplu-dogrulayici", category: "data", mark: "268", title: l("NDJSON Toplu Doğrulayıcı", "NDJSON Batch Validator", "NDJSON-Stapelvalidierung", "NDJSON 批量验证器"), purpose: l("Her satırı bağımsız JSON kaydı olarak doğrulayıp hatayı konumuyla gösterin.", "Validate every line as an independent JSON record and locate errors.", "Jede Zeile als JSON-Datensatz prüfen und Fehler lokalisieren.", "逐行验证独立 JSON 记录并定位错误。") },
  { slug: "sql-parametre-listesi-olusturucu", category: "data", mark: "269", title: l("SQL Parametre Listesi Oluşturucu", "SQL Parameter Inventory", "SQL-Parameterinventar", "SQL 参数清单生成器"), purpose: l("SQL çalıştırmadan adlandırılmış, numaralı ve soru işaretli parametreleri çıkarın.", "Extract named, numbered, and question-mark parameters without executing SQL.", "Benannte, nummerierte und Fragezeichenparameter ohne SQL-Ausführung extrahieren.", "在不执行 SQL 的情况下提取命名、编号与问号参数。") },
  { slug: "url-yol-segmenti-analizoru", category: "data", mark: "270", title: l("URL Yol Segmenti Analizörü", "URL Path Segment Analyzer", "URL-Pfadsegmentanalyse", "URL 路径段分析器"), purpose: l("Kodlanmış yol parçalarını çözümleyip boş, nokta ve çift kodlama risklerini gösterin.", "Decode path segments and expose empty, dot, and double-encoding risks.", "Pfadsegmente dekodieren und Leer-, Punkt- oder Doppelcodierung erkennen.", "解码路径段并识别空段、点段与双重编码风险。") },
  { slug: "accept-language-ayristirici", category: "data", mark: "271", title: l("Accept-Language Ayrıştırıcı", "Accept-Language Parser", "Accept-Language-Parser", "Accept-Language 解析器"), purpose: l("Dil aralıklarını q değerine ve özgüllüğe göre sıralayın.", "Sort language ranges by q-value and specificity.", "Sprachbereiche nach q-Wert und Spezifität sortieren.", "按 q 值与具体程度排序语言范围。") },
  { slug: "etag-karsilastirici", category: "data", mark: "272", title: l("ETag Karşılaştırıcı", "ETag Comparator", "ETag-Vergleich", "ETag 比较器"), purpose: l("Güçlü ve zayıf ETag karşılaştırma sonuçlarını ayrı gösterin.", "Show strong and weak ETag comparison results separately.", "Starke und schwache ETag-Vergleiche getrennt anzeigen.", "分别显示强与弱 ETag 比较结果。") },
  { slug: "json-nesne-birlestirme-stratejisi", category: "data", mark: "273", title: l("JSON Nesne Birleştirme Stratejisi", "JSON Object Merge Planner", "JSON-Objekt-Mergeplaner", "JSON 对象合并规划器"), purpose: l("Sığ ve derin birleştirmeyi önizleyip tür çakışmalarını raporlayın.", "Preview shallow and deep merge and report type conflicts.", "Flaches und tiefes Merge samt Typkonflikten vergleichen.", "预览浅层与深层合并并报告类型冲突。") },
  { slug: "json-dizi-sayfalama-planlayici", category: "data", mark: "274", title: l("JSON Dizi Sayfalama Planlayıcı", "JSON Array Pagination Planner", "JSON-Array-Seitenplaner", "JSON 数组分页规划器"), purpose: l("Dizi için sayfa sınırlarını, toplam sayfayı ve boş sayfa durumunu hesaplayın.", "Calculate page bounds, total pages, and empty-page state for an array.", "Seitengrenzen, Gesamtseiten und Leerseiten für Arrays berechnen.", "计算数组页边界、总页数与空页状态。") },
  { slug: "graphql-islem-envanteri", category: "data", mark: "275", title: l("GraphQL İşlem Envanteri", "GraphQL Operation Inventory", "GraphQL-Operationsinventar", "GraphQL 操作清单"), purpose: l("Sorgu, mutation ve fragment adlarını statik olarak listeleyin.", "Statically list query, mutation, and fragment names.", "Query-, Mutation- und Fragmentnamen statisch auflisten.", "静态列出查询、变更与片段名称。") },
  { slug: "http-link-basligi-ayristirici", category: "data", mark: "276", title: l("HTTP Link Başlığı Ayrıştırıcı", "HTTP Link Header Parser", "HTTP-Link-Header-Parser", "HTTP Link 标头解析器"), purpose: l("Link hedefi, rel ve parametreleri alıntılı virgülleri koruyarak ayırın.", "Parse targets, rels, and parameters while preserving quoted commas.", "Ziele, rel und Parameter mit geschützten Kommas parsen.", "解析目标、rel 与参数并保留引号内逗号。") },
  { slug: "toml-json-donusturucu", category: "converter", mark: "277", title: l("TOML ↔ JSON Dönüştürücü", "TOML ↔ JSON Converter", "TOML ↔ JSON-Konverter", "TOML ↔ JSON 转换器"), purpose: l("Temel TOML tablolarını JSON'a ve düz JSON'u TOML taslağına dönüştürün.", "Convert basic TOML tables to JSON and flat JSON to a TOML draft.", "Einfache TOML-Tabellen und flaches JSON konvertieren.", "在基础 TOML 表与扁平 JSON 草稿间转换。") },
  { slug: "base32-kodlayici", category: "converter", mark: "278", title: l("Base32 Kodlayıcı / Çözücü", "Base32 Encoder / Decoder", "Base32-Kodierer / Dekodierer", "Base32 编码 / 解码器"), purpose: l("UTF-8 metni RFC 4648 Base32 ile kodlayın veya doğrulayarak çözün.", "Encode UTF-8 with RFC 4648 Base32 or decode with validation.", "UTF-8 mit RFC-4648-Base32 kodieren oder validiert dekodieren.", "使用 RFC 4648 Base32 编码 UTF-8 或经验证后解码。") },
  { slug: "hex-metin-donusturucu", category: "converter", mark: "279", title: l("HEX ↔ Metin Dönüştürücü", "HEX ↔ Text Converter", "HEX ↔ Text-Konverter", "HEX ↔ 文本转换器"), purpose: l("UTF-8 metni onaltılık baytlara ve geçerli baytları metne dönüştürün.", "Convert UTF-8 text to hexadecimal bytes and valid bytes back to text.", "UTF-8-Text und hexadezimale Bytes konvertieren.", "在 UTF-8 文本与有效十六进制字节间转换。") },
  { slug: "roma-rakami-donusturucu", category: "converter", mark: "280", title: l("Roma Rakamı Dönüştürücü", "Roman Numeral Converter", "Römische-Zahlen-Konverter", "罗马数字转换器"), purpose: l("1–3999 tam sayıları kanonik Roma rakamlarıyla çift yönlü dönüştürün.", "Convert integers 1–3999 to and from canonical Roman numerals.", "Ganzzahlen 1–3999 und kanonische römische Zahlen konvertieren.", "在 1–3999 整数与规范罗马数字间转换。") },
  { slug: "buyuk-tamsayi-taban-donusturucu", category: "converter", mark: "281", title: l("Büyük Tamsayı Taban Dönüştürücü", "Large-Integer Base Converter", "Großtzahl-Zahlensystem-Konverter", "大整数进制转换器"), purpose: l("JavaScript sayı sınırını aşan tam sayıları 2 ile 36 arasındaki tabanlarda kayıpsız dönüştürün.", "Convert integers beyond JavaScript's safe-number range losslessly between bases 2 and 36.", "Ganzzahlen jenseits der sicheren JavaScript-Grenze verlustfrei zwischen Basis 2 und 36 konvertieren.", "在 2 至 36 进制间无损转换超出 JavaScript 安全范围的大整数。") },
  { slug: "ical-etkinlik-olusturucu", category: "converter", mark: "282", title: l("iCalendar Etkinlik Oluşturucu", "iCalendar Event Builder", "iCalendar-Termingenerator", "iCalendar 事件生成器"), purpose: l("Başlık, UTC zaman ve konumdan kaçışları doğru VEVENT taslağı üretin.", "Build an escaped VEVENT draft from title, UTC time, and location.", "Escapten VEVENT-Entwurf aus Titel, UTC-Zeit und Ort erzeugen.", "根据标题、UTC 时间与地点生成正确转义的 VEVENT 草稿。") },
  { slug: "vcard-kisi-karti-olusturucu", category: "converter", mark: "283", title: l("vCard Kişi Kartı Oluşturucu", "vCard Contact Builder", "vCard-Kontaktgenerator", "vCard 联系人生成器"), purpose: l("Ad, e-posta, telefon ve kurumdan vCard 4.0 taslağı üretin.", "Build a vCard 4.0 draft from name, email, phone, and organisation.", "vCard-4.0-Entwurf aus Name, E-Mail, Telefon und Organisation erzeugen.", "根据姓名、邮箱、电话与组织生成 vCard 4.0 草稿。") },
  { slug: "cok-degerli-sorgu-json-donusturucu", category: "converter", mark: "284", title: l("Çok Değerli Sorgu ↔ JSON Dönüştürücü", "Multi-value Query ↔ JSON Converter", "Mehrwert-Query ↔ JSON-Konverter", "多值查询 ↔ JSON 转换器"), purpose: l("Tekrarlı parametre sırasını dizi olarak koruyarak sorgu dizesi ve JSON arasında dönüştürün.", "Convert query strings and JSON while preserving repeated parameter order as arrays.", "Query-Strings und JSON unter Erhalt wiederholter Parameterreihenfolgen konvertieren.", "在保留重复参数顺序为数组的情况下转换查询字符串与 JSON。") },
  { slug: "csv-html-tablo-donusturucu", category: "converter", mark: "285", title: l("CSV → Güvenli HTML Tablo", "CSV → Safe HTML Table", "CSV → Sichere HTML-Tabelle", "CSV → 安全 HTML 表格"), purpose: l("CSV hücrelerini HTML kaçışıyla erişilebilir tablo koduna dönüştürün.", "Convert CSV cells to accessible table markup with HTML escaping.", "CSV-Zellen HTML-escaped in zugängliche Tabelle umwandeln.", "将 CSV 单元格经 HTML 转义后转换为无障碍表格标记。") },
  { slug: "gizlilik-risk-kaydi-olusturucu", category: "security", mark: "286", title: l("Gizlilik Risk Kaydı Oluşturucu", "Privacy Risk Register Builder", "Datenschutz-Risikoregister", "隐私风险登记表生成器"), purpose: l("Olasılık ve etkiyi puanlayıp sahip, kontrol ve kalan riski belgeleyin.", "Score likelihood and impact and document owner, control, and residual risk.", "Wahrscheinlichkeit, Auswirkung, Kontrolle und Restrisiko dokumentieren.", "评估可能性与影响并记录责任人、控制措施与剩余风险。") },
  { slug: "veri-minimizasyonu-karar-matrisi", category: "security", mark: "287", title: l("Veri Minimizasyonu Karar Matrisi", "Data Minimisation Decision Matrix", "Datenminimierungs-Entscheidungsmatrix", "数据最小化决策矩阵"), purpose: l("Alanları amaç, zorunluluk, saklama ve alternatif açısından tut/kaldır/incele diye sınıflayın.", "Classify fields as keep, remove, or review by purpose, necessity, retention, and alternatives.", "Felder nach Zweck und Erforderlichkeit behalten, entfernen oder prüfen.", "按目的、必要性、保留期与替代方案分类保留、删除或复核。") },
  { slug: "riza-kaydi-sablonu", category: "security", mark: "288", title: l("Rıza Kaydı Şablonu", "Consent Record Template", "Einwilligungsnachweis-Vorlage", "同意记录模板"), purpose: l("Amaç, sürüm, zaman, geri çekme ve kanıt alanları için denetlenebilir taslak üretin.", "Build an auditable draft for purpose, version, time, withdrawal, and evidence.", "Prüfbaren Entwurf für Zweck, Version, Zeitpunkt und Widerruf erstellen.", "生成包含目的、版本、时间、撤回与证据字段的可审计草稿。") },
  { slug: "dpia-on-eleme-sihirbazi", category: "security", mark: "289", title: l("DPIA Ön Eleme Sihirbazı", "DPIA Screening Wizard", "DSFA-Vorprüfung", "DPIA 初筛向导"), purpose: l("Ölçek, hassasiyet, izleme ve yenilik sinyallerini gerekçeli inceleme listesine dönüştürün.", "Turn scale, sensitivity, monitoring, and novelty signals into a reasoned review list.", "Skalierung, Sensitivität, Überwachung und Innovation begründet prüfen.", "将规模、敏感性、监控与创新信号转为有理由的复核清单。") },
  { slug: "saklama-suresi-son-tarih-hesaplayici", category: "security", mark: "290", title: l("Saklama Süresi Son Tarih Hesaplayıcı", "Retention Expiry Calculator", "Aufbewahrungsfrist-Rechner", "保留期限到期计算器"), purpose: l("Başlangıç tarihi ve sürelerden UTC güvenli silme inceleme tarihleri üretin.", "Create UTC-safe deletion review dates from start dates and periods.", "UTC-sichere Löschprüfdaten aus Startdatum und Frist berechnen.", "根据起始日期与期限生成 UTC 安全的删除复核日期。") },
  { slug: "redaksiyon-tutarlilik-denetleyici", category: "security", mark: "291", title: l("Redaksiyon Tutarlılık Denetleyici", "Redaction Consistency Checker", "Schwärzungskonsistenz-Prüfung", "遮盖一致性检查器"), purpose: l("Önce ve sonra metinde kalan e-posta, telefon, kimlik ve özel belirteçleri bulun.", "Find email, phone, identifier, and custom tokens left in before/after text.", "Verbliebene E-Mail-, Telefon-, Kennungs- und Spezialtoken finden.", "查找遮盖前后仍残留的邮箱、电话、标识符与自定义标记。") },
  { slug: "veri-siniflandirma-etiketleyici", category: "security", mark: "292", title: l("Veri Sınıflandırma Etiketleyici", "Data Classification Labeler", "Datenklassifizierungs-Etikettierer", "数据分类标记器"), purpose: l("Metin desenlerini genel, iç, gizli ve kısıtlı önerileriyle açıklayın.", "Explain text patterns with public, internal, confidential, and restricted suggestions.", "Textmuster als öffentlich, intern, vertraulich oder eingeschränkt erläutern.", "根据文本模式解释公开、内部、机密与受限分类建议。") },
  { slug: "ihlal-bildirim-zaman-cizelgesi", category: "security", mark: "293", title: l("İhlal Bildirim Zaman Çizelgesi", "Breach Notification Timeline", "Verletzungsmelde-Zeitplan", "泄露通知时间线"), purpose: l("Fark edilme anından itibaren geçen süreyi ve belge bekleyen karar noktalarını gösterin.", "Show elapsed time and decision points awaiting documented review.", "Vergangene Zeit und dokumentationspflichtige Entscheidungspunkte anzeigen.", "显示发现后的经过时间与待记录复核的决策节点。") },
  { slug: "cerez-envanteri-risk-siniflandirici", category: "security", mark: "294", title: l("Çerez Envanteri Risk Sınıflandırıcı", "Cookie Inventory Risk Classifier", "Cookie-Inventar-Risikoklassifizierung", "Cookie 清单风险分类器"), purpose: l("Ad, alan adı, süre ve amaçtan inceleme önceliği üretin.", "Prioritise review from cookie name, domain, duration, and purpose.", "Prüfpriorität aus Name, Domain, Dauer und Zweck ableiten.", "根据名称、域名、期限与目的生成复核优先级。") },
  { slug: "csp-kaynak-ifadesi-tester", category: "codeSecurity", mark: "295", title: l("CSP Kaynak İfadesi Test Aracı", "CSP Source Expression Tester", "CSP-Quellausdruck-Test", "CSP 源表达式测试器"), purpose: l("Bir URL'nin basit source-list ifadesiyle eşleşmesini ve riskli jokerleri inceleyin.", "Review whether a URL matches a simple source-list and expose risky wildcards.", "URL-Match gegen Source-List und riskante Wildcards prüfen.", "检查 URL 是否匹配简单 source-list 并识别高风险通配符。") },
  { slug: "sri-degeri-dogrulayici", category: "codeSecurity", mark: "296", title: l("SRI Değeri Doğrulayıcı", "SRI Value Verifier", "SRI-Wertprüfung", "SRI 值验证器"), purpose: l("Metnin SHA-256 özetini verilen integrity değeriyle cihazınızda karşılaştırın.", "Compare text SHA-256 with an integrity value on-device.", "Text-SHA-256 lokal mit Integrity-Wert vergleichen.", "在设备端比较文本 SHA-256 与 integrity 值。") },
  { slug: "paket-adi-benzerlik-tarayicisi", category: "codeSecurity", mark: "297", title: l("Paket Adı Benzerlik Tarayıcısı", "Package Name Similarity Scanner", "Paketnamen-Ähnlichkeitsscan", "包名相似度扫描器"), purpose: l("Aday paket adlarını güvenilen listeyle düzenleme mesafesine göre karşılaştırın.", "Compare candidate package names with a trusted list by edit distance.", "Paketnamen per Editierdistanz mit Vertrauensliste vergleichen.", "按编辑距离比较候选包名与可信列表。") },
  { slug: "punycode-domain-inceleyici", category: "codeSecurity", mark: "298", title: l("Punycode Alan Adı İnceleyici", "Punycode Domain Inspector", "Punycode-Domainprüfung", "Punycode 域名检查器"), purpose: l("xn-- etiketleri, karışık yazı sistemi ve şüpheli ayırıcı sinyallerini bulun.", "Find xn-- labels, mixed-script, and suspicious-separator signals.", "xn--Labels, Schriftmischung und verdächtige Trenner erkennen.", "识别 xn-- 标签、混合文字系统与可疑分隔符信号。") },
  { slug: "jwt-claim-politikasi-denetleyici", category: "codeSecurity", mark: "299", title: l("JWT Claim Politikası Denetleyici", "JWT Claim Policy Checker", "JWT-Claim-Richtlinienprüfung", "JWT 声明策略检查器"), purpose: l("İmza doğrulamadan exp, nbf, aud, iss ve zorunlu claim durumunu inceleyin.", "Inspect exp, nbf, aud, iss, and required claims without verifying the signature.", "exp, nbf, aud, iss und Pflichtclaims ohne Signaturprüfung prüfen.", "在不验证签名的情况下检查 exp、nbf、aud、iss 与必需声明。") },
  { slug: "ssh-yetkili-anahtar-inceleyici", category: "codeSecurity", mark: "300", title: l("SSH Yetkili Anahtar İnceleyici", "SSH Authorized Key Inspector", "SSH-Authorized-Key-Prüfung", "SSH 授权密钥检查器"), purpose: l("Açık anahtar türü, yorum ve SHA-256 parmak izini özel anahtar olmadan gösterin.", "Show public-key type, comment, and SHA-256 fingerprint without private material.", "Typ, Kommentar und SHA-256-Fingerabdruck öffentlicher Schlüssel anzeigen.", "在不涉及私钥的情况下显示公钥类型、注释与 SHA-256 指纹。") },
  { slug: "pem-blok-inceleyici", category: "codeSecurity", mark: "301", title: l("PEM Blok İnceleyici", "PEM Block Inspector", "PEM-Blockprüfung", "PEM 块检查器"), purpose: l("PEM sınırlarını, etiketleri ve Base64 gövde bütünlüğünü anahtar açmadan inceleyin.", "Inspect PEM boundaries, labels, and Base64 body integrity without opening keys.", "PEM-Grenzen, Labels und Base64-Körper ohne Schlüsselzugriff prüfen.", "在不打开密钥的情况下检查 PEM 边界、标签与 Base64 主体完整性。") },
  { slug: "git-diff-sir-tarayicisi", category: "codeSecurity", mark: "302", title: l("Git Diff Sır Tarayıcısı", "Git Diff Secret Scanner", "Git-Diff-Secret-Scanner", "Git Diff 密钥扫描器"), purpose: l("Yalnızca eklenen satırlarda yüksek sinyalli sır desenlerini bulun.", "Find high-signal secret patterns only in added diff lines.", "Signalstarke Secret-Muster nur in hinzugefügten Diffzeilen finden.", "仅在新增 diff 行中查找高置信秘密模式。") },
  { slug: "api-anahtari-format-on-kontrolu", category: "codeSecurity", mark: "303", title: l("API Anahtarı Format Ön Kontrolü", "API Key Format Pre-check", "API-Key-Formatvorprüfung", "API 密钥格式预检查"), purpose: l("Ön ek, uzunluk, karakter kümesi ve entropi sinyallerini anahtarı saklamadan inceleyin.", "Inspect prefix, length, alphabet, and entropy signals without storing the key.", "Präfix, Länge, Zeichensatz und Entropie ohne Speicherung prüfen.", "在不存储密钥的情况下检查前缀、长度、字符集与熵信号。") },
  { slug: "html-guvenli-atribut-denetleyici", category: "codeSecurity", mark: "304", title: l("HTML Güvenli Atribut Denetleyici", "HTML Safe Attribute Checker", "HTML-Attribut-Sicherheitsprüfung", "HTML 安全属性检查器"), purpose: l("inline event, javascript URL ve riskli target kombinasyonlarını statik olarak bulun.", "Statically find inline events, javascript URLs, and risky target combinations.", "Inline-Events, JavaScript-URLs und riskante target-Kombinationen finden.", "静态查找内联事件、javascript URL 与高风险 target 组合。") },
  { slug: "yuzde-dagilim-dengeleyici", category: "calculation", mark: "305", title: l("Yüzde Dağılım Dengeleyici", "Percentage Allocation Balancer", "Prozentverteilungs-Ausgleich", "百分比分配平衡器"), purpose: l("Kalemleri yüzde 100'e ölçekleyip yuvarlama farkını görünür kılın.", "Scale allocations to 100% and expose rounding differences.", "Anteile auf 100 % skalieren und Rundungsdifferenzen zeigen.", "将分配缩放至 100% 并显示舍入差异。") },
  { slug: "paket-birim-maliyet-karsilastirici", category: "calculation", mark: "306", title: l("Paket Birim Maliyet Karşılaştırıcı", "Package Unit-Cost Comparator", "Paket-Grundkostenvergleich", "包装单位成本比较器"), purpose: l("Gram/kilogram ve mililitre/litre paketlerini ortak en küçük birime indirip sıralayın.", "Normalise gram/kilogram and millilitre/litre packages to a common smallest unit and rank them.", "Gramm/Kilogramm- und Milliliter/Liter-Pakete auf gemeinsame Einheit normieren und sortieren.", "将克/千克与毫升/升包装统一到最小单位后排序。") },
  { slug: "calisma-ucreti-esdegerlik-hesaplayici", category: "calculation", mark: "307", title: l("Çalışma Ücreti Eşdeğerlik Hesaplayıcı", "Work-Pay Equivalence Calculator", "Arbeitsentgelt-Äquivalenzrechner", "工作报酬等值计算器"), purpose: l("Yıllık, aylık, haftalık ve saatlik ücretleri ücretli hafta/saat varsayımlarıyla eşdeğerleyin.", "Equate annual, monthly, weekly, and hourly pay using explicit paid-week and paid-hour assumptions.", "Jahres-, Monats-, Wochen- und Stundenentgelt mit bezahlten Wochen/Stunden vergleichen.", "根据明确的带薪周数与工时换算年、月、周与小时报酬。") },
  { slug: "nakit-pisti-hesaplayici", category: "calculation", mark: "308", title: l("Nakit Pisti Hesaplayıcı", "Cash Runway Calculator", "Liquiditätsreichweiten-Rechner", "现金可持续期计算器"), purpose: l("Nakit, aylık gelir, gider ve güvenlik tamponuyla senaryo süresi hesaplayın.", "Calculate runway from cash, monthly income, spend, and safety buffer.", "Reichweite aus Kasse, Einnahmen, Ausgaben und Puffer berechnen.", "根据现金、月收入、支出与安全缓冲计算可持续期。") },
  { slug: "stok-yeniden-siparis-hesaplayici", category: "calculation", mark: "309", title: l("Stok Yeniden Sipariş Hesaplayıcı", "Stock Reorder Point Calculator", "Bestellpunkt-Rechner", "库存再订购点计算器"), purpose: l("Talep, teslim süresi ve güvenlik stoğundan sipariş noktasını hesaplayın.", "Calculate reorder point from demand, lead time, and safety stock.", "Bestellpunkt aus Bedarf, Lieferzeit und Sicherheitsbestand berechnen.", "根据需求、交付周期与安全库存计算再订购点。") },
  { slug: "oran-arastirmasi-orneklem-planlayici", category: "calculation", mark: "310", title: l("Oran Araştırması Örneklem Planlayıcı", "Proportion Study Sample Planner", "Stichprobenplaner für Anteilsstudien", "比例研究样本规划器"), purpose: l("Bir oran araştırması için güven, hata payı, beklenen oran ve sonlu nüfus düzeltmesini açık formülle planlayın.", "Plan a proportion study from confidence, margin, expected proportion, and finite-population correction.", "Anteilsstudie mit Konfidenz, Fehlermarge, erwartetem Anteil und endlicher Population planen.", "按置信度、误差范围、预期比例与有限总体修正规划比例研究样本。") },
  { slug: "guven-araligi-hesaplayici", category: "calculation", mark: "311", title: l("Güven Aralığı Hesaplayıcı", "Confidence Interval Calculator", "Konfidenzintervall-Rechner", "置信区间计算器"), purpose: l("Ortalama, standart sapma ve örneklemden yaklaşık z aralığı üretin.", "Build an approximate z interval from mean, standard deviation, and sample size.", "Näherungsweises z-Intervall aus Mittelwert, Streuung und n berechnen.", "根据均值、标准差与样本量计算近似 z 区间。") },
  { slug: "toplanti-maliyeti-hesaplayici", category: "calculation", mark: "312", title: l("Toplantı Maliyeti Hesaplayıcı", "Meeting Cost Calculator", "Meetingkosten-Rechner", "会议成本计算器"), purpose: l("Katılımcı ücretleri, süre ve hazırlık süresinden toplam maliyeti görünür kılın.", "Expose total cost from participant rates, duration, and preparation time.", "Gesamtkosten aus Teilnehmerlöhnen, Dauer und Vorbereitung zeigen.", "根据参与者费率、时长与准备时间显示总成本。") },
  { slug: "vardiya-kapsama-hesaplayici", category: "calculation", mark: "313", title: l("Vardiya Kapsama Hesaplayıcı", "Shift Coverage Calculator", "Schichtabdeckungs-Rechner", "班次覆盖计算器"), purpose: l("Saatlik ihtiyaç ve mevcut kapasite arasındaki açıkları listeleyin.", "List gaps between hourly staffing demand and available capacity.", "Lücken zwischen Stundenbedarf und Kapazität auflisten.", "列出每小时人员需求与可用容量之间的缺口。") },
  { slug: "zaman-bloklama-plani", category: "general", mark: "314", title: l("Zaman Bloklama Planı", "Time-Blocking Planner", "Zeitblock-Planer", "时间分块规划器"), purpose: l("Görev, süre, öncelik ve molalardan düzenlenebilir günlük plan üretin.", "Build an editable day plan from tasks, durations, priorities, and breaks.", "Tagesplan aus Aufgaben, Dauer, Priorität und Pausen erstellen.", "根据任务、时长、优先级与休息生成可编辑日程。") },
  { slug: "pomodoro-oturum-planlayici", category: "general", mark: "315", title: l("Pomodoro Oturum Planlayıcı", "Pomodoro Session Planner", "Pomodoro-Sitzungsplaner", "番茄工作法会话规划器"), purpose: l("Odak, kısa ve uzun mola sürelerinden saatli oturum çizelgesi üretin.", "Create a timed session schedule from focus, short-break, and long-break periods.", "Zeitplan aus Fokus-, Kurz- und Langpausen erstellen.", "根据专注、短休与长休时长生成定时会话计划。") },
  { slug: "etkinlik-kontrol-listesi-olusturucu", category: "general", mark: "316", title: l("Etkinlik Kontrol Listesi Oluşturucu", "Event Checklist Builder", "Veranstaltungs-Checkliste", "活动检查清单生成器"), purpose: l("Tarih, sahip ve görevlerden aşamalı etkinlik kontrol listesi hazırlayın.", "Build a phased event checklist from dates, owners, and tasks.", "Phasen-Checkliste aus Datum, Verantwortlichen und Aufgaben erstellen.", "根据日期、责任人与任务生成分阶段活动清单。") },
  { slug: "embedding-parca-ortusme-planlayici", category: "ai", mark: "317", title: l("Embedding Parça/Örtüşme Planlayıcı", "Embedding Chunk & Overlap Planner", "Embedding-Chunk- und Überlappungsplaner", "Embedding 分块与重叠规划器"), purpose: l("Belge uzunluğu, parça ve örtüşmeden çağrı sayısı ile bağlam tekrarını hesaplayın.", "Calculate chunk count and repeated context from document length, chunk, and overlap.", "Chunkzahl und Kontextwiederholung aus Länge und Überlappung berechnen.", "根据文档长度、块大小与重叠计算块数及重复上下文。") },
  { slug: "arac-cagrisi-json-dogrulayici", category: "ai", mark: "318", title: l("Araç Çağrısı JSON Doğrulayıcı", "Tool-Call JSON Validator", "Tool-Call-JSON-Validierung", "工具调用 JSON 验证器"), purpose: l("Araç adı, argüman nesnesi ve zorunlu alan sözleşmesini yerel olarak doğrulayın.", "Validate tool name, argument object, and required-field contract locally.", "Werkzeugname, Argumentobjekt und Pflichtfelder lokal validieren.", "在本地验证工具名称、参数对象与必填字段契约。") },
  { slug: "doi-toplu-dogrulayici", category: "research", mark: "319", title: l("DOI Toplu Doğrulayıcı", "DOI Batch Validator", "DOI-Stapelvalidierung", "DOI 批量验证器"), purpose: l("DOI metinlerini normalleştirip sözdizimi, tekrar ve güvenli bağlantıyı raporlayın.", "Normalise DOI strings and report syntax, duplicates, and safe links.", "DOIs normalisieren und Syntax, Duplikate sowie Links berichten.", "规范 DOI 字符串并报告语法、重复项与安全链接。") },
  { slug: "literatur-eleme-karar-gunlugu", category: "research", mark: "320", title: l("Literatür Eleme Karar Günlüğü", "Literature Screening Decision Log", "Literatur-Screening-Entscheidungslog", "文献筛选决策日志"), purpose: l("Kayıt, karar, gerekçe ve inceleyici alanlarında eksik veya çelişkili kararları bulun.", "Find missing or conflicting record, decision, reason, and reviewer fields.", "Fehlende oder widersprüchliche Screening-Entscheidungen finden.", "查找记录、决策、理由与审查者字段的缺失或冲突。") },
  { slug: "kanit-tablosu-tekillestirici", category: "research", mark: "321", title: l("Kanıt Tablosu Tekilleştirici", "Evidence Table Deduplicator", "Evidenztabellen-Deduplizierer", "证据表去重器"), purpose: l("DOI, başlık ve yıl üzerinden olası yinelenen kayıt kümelerini bulun.", "Find likely duplicate record groups by DOI, title, and year.", "Wahrscheinliche Duplikate nach DOI, Titel und Jahr finden.", "按 DOI、标题与年份查找可能重复的记录组。") },
];

function toTool(spec: Spec): BaseTool {
  const boundary = categoryBoundary[spec.category];
  return {
    ...spec,
    short: spec.purpose,
    description: {
      tr: `${spec.purpose.tr} ${boundary.tr}`,
      en: `${spec.purpose.en} ${boundary.en}`,
      de: `${spec.purpose.de} ${boundary.de}`,
      zh: `${spec.purpose.zh}${boundary.zh}结果会同时展示输入假设、处理步骤、错误与边界情况，便于您在导出或继续工作流前完成复核并保留可重复的检查记录。`,
    },
    useCases,
    steps,
  };
}

export const frontierTools: BaseTool[] = specs.map(toTool);
export const frontierToolSlugs = new Set(specs.map((spec) => spec.slug));
export const frontierToolCount = specs.length;
