import type { Locale } from "./site";
import type { ArticleSection, Post } from "./posts";
import type { LocalizedGuide } from "./localized-guides";

type L = Record<Locale, string>;
type Guide = { slug: string; relatedTools: string[]; title: L; excerpt: L; category: L; outcome: L; boundary: L };
const l = (tr: string, en: string, de: string, zh: string): L => ({ tr, en, de, zh });

const guides: Guide[] = [
  { slug: "prompt-kisit-tip-ve-cikti-sozlesmesi-rehberi", relatedTools: ["prompt-negatif-kisit-denetleyici", "prompt-degisken-tip-denetleyici", "prompt-cikti-belirlilik-denetleyici", "prompt-rubrik-puanlayici"], title: l("Üretimde Prompt Kısıtları, Değişken Tipleri ve Çıktı Sözleşmeleri", "Production Prompt Constraints, Variable Types, and Output Contracts", "Prompt-Bedingungen, Variablentypen und Ausgabeverträge", "生产提示词的约束、变量类型与输出契约"), excerpt: l("Çelişen talimatları, tür hatalarını ve belirsiz çıktı beklentilerini model çağrısından önce denetlenebilir bir sözleşmeye dönüştürün.", "Turn conflicting instructions, type errors, and vague output expectations into an auditable contract before a model call.", "Widersprüche, Typfehler und vage Ausgaben vor dem Modellaufruf in einen prüfbaren Vertrag überführen.", "在调用模型前，将冲突指令、类型错误与模糊输出要求转为可审计契约。"), category: l("Prompt mühendisliği", "Prompt engineering", "Prompt Engineering", "提示词工程"), outcome: l("Bir destek ajanı promptunu zorunlu/yasak kurallar, tipli değişkenler, JSON çıktı şeması ve ağırlıklı kabul rubriğiyle sürümlenebilir hale getirmek.", "Make a support-agent prompt versionable with required/prohibited rules, typed variables, a JSON output schema, and a weighted acceptance rubric.", "Einen Support-Agent-Prompt mit Regeln, typisierten Variablen, JSON-Schema und gewichteter Rubrik versionierbar machen.", "用必需/禁止规则、类型化变量、JSON 输出架构与加权验收量表，使客服智能体提示词可版本化。"), boundary: l("Statik analiz gerçek model davranışını veya güvenliğini kanıtlamaz; hedef model, gerçek araç izinleri ve adversarial vakalar ayrıca sınanmalıdır.", "Static analysis proves neither actual model behaviour nor safety; test the target model, real tool permissions, and adversarial cases separately.", "Statische Analyse beweist weder Modellverhalten noch Sicherheit; Zielmodell und echte Berechtigungen separat testen.", "静态分析无法证明真实模型行为或安全性；目标模型、真实工具权限与对抗案例必须另行测试。") },
  { slug: "cok-dilli-prompt-ve-ornek-kalite-rehberi", relatedTools: ["prompt-ornek-denge-analizoru", "prompt-yerellestirme-kontrol-listesi", "prompt-tutarlilik-senaryo-testi", "few-shot-ornek-olusturucu"], title: l("Dört Dilde Prompt ve Few-shot Örnek Kalitesi", "Prompt and Few-shot Example Quality Across Four Languages", "Prompt- und Few-shot-Qualität in vier Sprachen", "四语言提示词与少样本示例质量"), excerpt: l("Yer tutucuları koruyun, örnek sınıflarını dengeleyin ve çeviri sırasında davranış sözleşmesinin sessizce değişmesini önleyin.", "Preserve placeholders, balance example classes, and prevent the behaviour contract changing silently during translation.", "Platzhalter erhalten, Beispiele ausgleichen und stille Verhaltensänderungen bei Übersetzungen verhindern.", "保留占位符、平衡示例类别并避免翻译时行为契约静默改变。"), category: l("Çok dilli AI kalitesi", "Multilingual AI quality", "Mehrsprachige KI-Qualität", "多语言 AI 质量"), outcome: l("Türkçe, İngilizce, Almanca ve Çince prompt sürümlerinde aynı değişkenleri, sınırları, sınıfları ve red-team vakalarını koruyan yayın kontrolü kurmak.", "Build release checks that preserve variables, boundaries, classes, and red-team cases across Turkish, English, German, and Chinese prompts.", "Release-Prüfungen für Variablen, Grenzen, Klassen und Red-Team-Fälle in vier Sprachen aufbauen.", "为土耳其语、英语、德语与中文提示词建立保留变量、边界、类别与红队案例的发布检查。"), boundary: l("Sayı ve yer tutucu eşitliği anlamsal eşdeğerliği kanıtlamaz; ana dili konuşan editör ve gerçek model testi gerekir.", "Matching numbers and placeholders does not prove semantic equivalence; native editorial and model review remain necessary.", "Gleiche Zahlen und Platzhalter beweisen keine semantische Gleichwertigkeit; muttersprachliche Prüfung bleibt nötig.", "数字与占位符一致不能证明语义等价；仍需母语编辑与真实模型测试。") },
  { slug: "okunabilir-teknik-icerik-kalite-rehberi", relatedTools: ["cumle-uzunluk-dagilimi", "sade-dil-kontrolu", "baslik-hiyerarsisi-denetleyici", "terim-tutarlilik-denetleyici", "paragraf-gecis-analizoru"], title: l("Okunabilir Teknik İçerik İçin Ölçülebilir Editoryal Kalite", "Measurable Editorial Quality for Readable Technical Content", "Messbare redaktionelle Qualität für verständliche Techniktexte", "可读技术内容的可衡量编辑质量"), excerpt: l("Cümle uzunluğu, terim, başlık ve geçiş sinyallerini birlikte kullanarak metni sadeleştirirken teknik doğruluğu koruyun.", "Use sentence, terminology, heading, and transition signals together to simplify writing without losing technical accuracy.", "Satz-, Terminologie-, Überschriften- und Übergangssignale kombinieren, ohne technische Genauigkeit zu verlieren.", "结合句长、术语、标题与过渡信号，在简化文本时保持技术准确性。"), category: l("İçerik tasarımı", "Content design", "Content Design", "内容设计"), outcome: l("Bir araç sayfasını H1–H3 yapısı, tutarlı terim sözlüğü, kısa görev cümleleri ve açıklanan teknik kavramlarla mobilde taranabilir hale getirmek.", "Make a tool page scannable on mobile with H1–H3 structure, consistent terminology, short task sentences, and explained concepts.", "Eine Werkzeugseite mit H1–H3, Terminologie und kurzen Sätzen mobil erfassbar machen.", "通过 H1–H3 结构、一致术语、简短任务句与概念解释，使工具页在移动端易于浏览。"), boundary: l("Okunabilirlik puanı doğruluk, erişilebilirlik veya ikna kalitesini tek başına ölçmez; gerçek kullanıcı görevleriyle test edin.", "A readability score alone measures neither accuracy, accessibility, nor persuasion; test real user tasks.", "Ein Lesbarkeitswert misst weder Genauigkeit noch Barrierefreiheit; mit echten Aufgaben testen.", "可读性分数不能单独衡量准确性、无障碍或说服力；应以真实用户任务测试。") },
  { slug: "json-yol-schema-birlestirme-rehberi", relatedTools: ["json-yol-degeri-cikarici", "json-ornek-veri-uretici", "json-nesne-birlestirme-stratejisi", "json-dizi-sayfalama-planlayici"], title: l("JSON Yol, Schema, Birleştirme ve Sayfalama İçin Güvenli Veri Akışı", "A Safe JSON Workflow for Paths, Schemas, Merging, and Pagination", "Sicherer JSON-Ablauf für Pfade, Schemas, Merge und Seiten", "JSON 路径、架构、合并与分页的安全工作流"), excerpt: l("Yapısal veriyi seçin, örnekleyin, birleştirin ve sayfalayın; tür çakışması ile boş sayfa davranışını açıkça belgeleyin.", "Select, sample, merge, and paginate structured data while documenting type conflicts and empty-page behaviour.", "Strukturierte Daten auswählen, erzeugen, mergen und paginieren; Typkonflikte sichtbar halten.", "选择、生成、合并并分页结构化数据，同时明确记录类型冲突与空页行为。"), category: l("JSON veri kalitesi", "JSON data quality", "JSON-Datenqualität", "JSON 数据质量"), outcome: l("Bir API örnek yanıtını Schema’dan üretmek, gerekli alanı yol ile seçmek, kullanıcı tercihlerini derin birleştirmek ve kararlı sayfalara bölmek.", "Generate an API sample from Schema, select required fields by path, deep-merge preferences, and split the result into stable pages.", "API-Beispiel aus Schema erzeugen, Pfade auswählen, Präferenzen mergen und stabil paginieren.", "从 Schema 生成 API 样本、按路径选择字段、深度合并偏好并稳定分页。"), boundary: l("Basit yol ve örnek üretimi tüm JSON Schema anahtarlarını desteklemez; imza, sözleşme ve üretim geçişinde tam standart uygulaması kullanın.", "Simple paths and sample generation do not cover every JSON Schema keyword; use a complete standards implementation for signatures and production contracts.", "Einfache Pfade und Beispiele decken nicht alle JSON-Schema-Schlüssel ab; Produktion braucht vollständige Standards.", "简单路径与样本生成不覆盖所有 JSON Schema 关键字；签名与生产契约应使用完整标准实现。") },
  { slug: "csv-ndjson-teslim-kalite-rehberi", relatedTools: ["csv-ayirac-tespit-araci", "csv-sutun-yeniden-adlandirici", "ndjson-toplu-dogrulayici", "csv-html-tablo-donusturucu"], title: l("CSV ve NDJSON Teslimlerinde Sessiz Veri Kaybını Önleme", "Prevent Silent Data Loss in CSV and NDJSON Delivery", "Stillen Datenverlust bei CSV und NDJSON verhindern", "防止 CSV 与 NDJSON 交付中的静默数据丢失"), excerpt: l("Ayıracı kanıtlayın, başlık çakışmasını durdurun, her kaydı doğrulayın ve HTML çıktısını güvenli biçimde kaçırın.", "Prove the delimiter, stop header collisions, validate every record, and safely escape HTML output.", "Trennzeichen belegen, Header-Kollisionen stoppen, Datensätze prüfen und HTML sicher escapen.", "确认分隔符、阻止表头冲突、逐条验证记录并安全转义 HTML 输出。"), category: l("Tablolu veri aktarımı", "Tabular data delivery", "Tabellarische Datenlieferung", "表格数据交付"), outcome: l("Bilinmeyen bir CSV dosyasını ham kopyayı koruyarak incelemek, hedef kolon sözleşmesine eşlemek, NDJSON’a bölmek ve hatalı satırları konumuyla raporlamak.", "Inspect an unknown CSV while preserving the raw copy, map it to a target column contract, split to NDJSON, and locate bad rows.", "Unbekannte CSV prüfen, Rohkopie bewahren, Spalten mappen und fehlerhafte NDJSON-Zeilen lokalisieren.", "保留原始副本，检查未知 CSV、映射目标列契约、拆分 NDJSON 并定位错误行。"), boundary: l("Ayıraç puanı kodlama, yerel ondalık veya tarih yorumunu doğrulamaz; kaynak sahibiyle veri sözlüğünü teyit edin.", "Delimiter scoring does not validate encoding, locale decimals, or dates; confirm the data dictionary with the source owner.", "Trennzeichenerkennung validiert weder Kodierung noch Dezimal- oder Datumsregeln; Datenwörterbuch bestätigen.", "分隔符评分不能验证编码、本地小数或日期解释；请与数据所有者确认数据字典。") },
  { slug: "http-graphql-metadata-teslim-rehberi", relatedTools: ["accept-language-ayristirici", "etag-karsilastirici", "graphql-islem-envanteri", "http-link-basligi-ayristirici", "sql-parametre-listesi-olusturucu"], title: l("HTTP ve GraphQL Metadata Sözleşmelerini Yayın Öncesi Denetleme", "Pre-release Auditing of HTTP and GraphQL Metadata Contracts", "HTTP- und GraphQL-Metadaten vor dem Release prüfen", "发布前审计 HTTP 与 GraphQL 元数据契约"), excerpt: l("Dil tercihi, cache etiketi, sayfalama bağlantısı, operasyon adı ve SQL parametresini gözlemlenebilir bir sözleşmede birleştirin.", "Combine language preference, cache tags, pagination links, operation names, and SQL parameters in an observable contract.", "Sprache, Cache-Tags, Pagination, Operationsnamen und SQL-Parameter beobachtbar verbinden.", "将语言偏好、缓存标签、分页链接、操作名称与 SQL 参数纳入可观测契约。"), category: l("API teslimi", "API delivery", "API-Auslieferung", "API 交付"), outcome: l("Bir çok dilli liste uç noktasının Accept-Language sırasını, ETag koşullarını, Link pagination ilişkilerini ve GraphQL operasyon envanterini test kaydına bağlamak.", "Tie a multilingual list endpoint's language order, ETag conditions, Link pagination relations, and GraphQL operation inventory to a test record.", "Sprachreihenfolge, ETag, Link-Pagination und GraphQL-Inventar eines Endpunkts testbar dokumentieren.", "将多语言列表端点的语言顺序、ETag 条件、Link 分页关系与 GraphQL 操作清单关联到测试记录。"), boundary: l("Metin ayrıştırma gerçek ağ, cache, TLS, veritabanı veya yetkilendirme davranışını doğrulamaz; entegrasyon testi zorunludur.", "Text parsing validates no real network, cache, TLS, database, or authorization behaviour; integration tests are mandatory.", "Textparser prüfen kein echtes Netzwerk-, Cache-, TLS-, Datenbank- oder Berechtigungsverhalten.", "文本解析无法验证真实网络、缓存、TLS、数据库或授权行为；必须执行集成测试。") },
  { slug: "dayanikli-metin-kodlama-donusturme-rehberi", relatedTools: ["base32-kodlayici", "hex-metin-donusturucu", "sayi-tabani-donusturucu", "roma-rakami-donusturucu", "toml-json-donusturucu"], title: l("Base32, HEX, Sayı Tabanı ve TOML Dönüşümlerinde Doğruluk", "Correct Base32, HEX, Number-Base, and TOML Conversion", "Korrekte Base32-, HEX-, Zahlensystem- und TOML-Konvertierung", "Base32、HEX、进制与 TOML 转换的正确性"), excerpt: l("Kodlama ile şifrelemeyi ayırın, Unicode baytlarını doğru taşıyın ve kısmi biçim desteğinin sınırlarını görünür tutun.", "Separate encoding from encryption, carry Unicode bytes correctly, and expose the limits of partial format support.", "Kodierung von Verschlüsselung trennen, Unicode korrekt übertragen und Formatgrenzen zeigen.", "区分编码与加密、正确传输 Unicode 字节并明确部分格式支持的边界。"), category: l("Veri kodlama", "Data encoding", "Datenkodierung", "数据编码"), outcome: l("UTF-8 metni Base32 ve HEX ile gidiş-dönüş sınamak, büyük tamsayıyı tabanlar arasında kayıpsız taşımak ve basit TOML yapılandırmasını JSON’a aktarmak.", "Round-trip UTF-8 through Base32 and HEX, move large integers losslessly across bases, and transfer basic TOML configuration to JSON.", "UTF-8 per Base32/HEX rückübertragen, Ganzzahlen verlustfrei konvertieren und einfaches TOML nach JSON bringen.", "让 UTF-8 经 Base32 与 HEX 往返、无损转换大整数进制并将基础 TOML 配置转为 JSON。"), boundary: l("Kodlama gizlilik sağlamaz. Basit TOML dönüştürücü diziler, tarih türleri ve karmaşık tablolar için tam parser yerine geçmez.", "Encoding provides no confidentiality. The basic TOML converter is not a full parser for arrays, dates, and complex tables.", "Kodierung bietet keine Vertraulichkeit; der einfache TOML-Konverter ist kein vollständiger Parser.", "编码不提供机密性；基础 TOML 转换器不能替代支持数组、日期与复杂表的完整解析器。") },
  { slug: "takvim-kisi-karti-veri-tasinabilirligi-rehberi", relatedTools: ["ical-etkinlik-olusturucu", "vcard-kisi-karti-olusturucu", "sorgu-dizesi-json-donusturucu", "url-yol-segmenti-analizoru"], title: l("iCalendar ve vCard ile Gizlilik Odaklı Veri Taşınabilirliği", "Privacy-first Data Portability with iCalendar and vCard", "Datenschutzfreundliche Portabilität mit iCalendar und vCard", "使用 iCalendar 与 vCard 的隐私优先数据可移植性"), excerpt: l("Takvim ve kişi kartlarını cihazda üretin; zaman, kaçış, kişisel veri ve hedef uygulama doğrulamasını birlikte yönetin.", "Create calendar and contact cards on-device while managing time, escaping, personal data, and target-app validation together.", "Kalender- und Kontaktdaten lokal erzeugen und Zeit, Escaping sowie Zielanwendung prüfen.", "在设备端创建日历与联系人卡片，并同时管理时间、转义、个人数据与目标应用验证。"), category: l("Veri taşınabilirliği", "Data portability", "Datenportabilität", "数据可移植性"), outcome: l("UTC zamanlı bir etkinliği VEVENT olarak, açıkça seçilmiş kişi alanlarını vCard olarak üretmek ve gerçek veri eklemeden önce sentetik örnekle içe aktarmayı sınamak.", "Create a UTC VEVENT and a vCard with deliberately selected contact fields, then test import with synthetic data before real records.", "UTC-VEVENT und bewusst minimierte vCard erzeugen und Import zuerst synthetisch testen.", "生成 UTC VEVENT 与仅含必要字段的 vCard，并在真实记录前用合成数据测试导入。"), boundary: l("Dosya üretimi davet göndermez, takvim çakışmasını çözmez veya rıza oluşturmaz; gereksiz kişi alanlarını eklemeyin.", "File generation sends no invite, resolves no calendar conflict, and creates no consent; omit unnecessary contact fields.", "Dateierzeugung sendet keine Einladung und schafft keine Einwilligung; unnötige Kontaktdaten weglassen.", "生成文件不会发送邀请、解决日历冲突或产生同意；请省略不必要的联系人字段。") },
  { slug: "gizlilik-risk-minimizasyon-riza-rehberi", relatedTools: ["gizlilik-risk-kaydi-olusturucu", "veri-minimizasyonu-karar-matrisi", "riza-kaydi-sablonu", "veri-siniflandirma-etiketleyici"], title: l("Gizlilik Riskinden Veri Minimizasyonu ve Rıza Kaydına", "From Privacy Risk to Data Minimisation and Consent Records", "Vom Datenschutzrisiko zu Minimierung und Einwilligungsnachweis", "从隐私风险到数据最小化与同意记录"), excerpt: l("Veri alanlarını amaç ve zorunlulukla sorgulayın, kontrolleri sahiplenin ve rıza kanıtını sürümlü bir kayıt olarak tasarlayın.", "Challenge fields by purpose and necessity, assign controls, and design consent evidence as a versioned record.", "Datenfelder nach Zweck prüfen, Kontrollen zuordnen und Einwilligung versioniert dokumentieren.", "按目的与必要性审视字段、分配控制措施并将同意证据设计为版本化记录。"), category: l("Gizlilik yönetişimi", "Privacy governance", "Datenschutz-Governance", "隐私治理"), outcome: l("Bir ürün kayıt akışındaki her alan için amaç, alternatif, süre ve risk sahibi yazmak; gereksiz alanı kaldırmak ve bildirim sürümünü rıza kanıtına bağlamak.", "Document purpose, alternative, retention, and risk owner for every signup field, remove unnecessary data, and bind notice version to consent evidence.", "Zweck, Alternative, Frist und Risikoverantwortung je Registrierungsfeld dokumentieren.", "为每个注册字段记录目的、替代方案、保留期与风险责任人，删除非必要数据并将通知版本绑定到同意证据。"), boundary: l("Şablonlar hukuki dayanak seçmez veya rızanın geçerliliğini garanti etmez; uygulanabilir hukuk ve gerçek arayüz yetkili uzmanla incelenmelidir.", "Templates neither choose a lawful basis nor guarantee valid consent; review applicable law and the real interface with qualified expertise.", "Vorlagen wählen keine Rechtsgrundlage und garantieren keine wirksame Einwilligung.", "模板不会选择合法依据或保证同意有效；应由合格专家审查适用法律与真实界面。") },
  { slug: "dpia-saklama-ihlal-cerez-operasyon-rehberi", relatedTools: ["dpia-on-eleme-sihirbazi", "saklama-suresi-son-tarih-hesaplayici", "ihlal-bildirim-zaman-cizelgesi", "cerez-envanteri-risk-siniflandirici"], title: l("DPIA, Saklama, İhlal ve Çerez Envanteri İçin Operasyon Rehberi", "An Operations Guide to DPIA, Retention, Breaches, and Cookie Inventories", "Praxisleitfaden zu DSFA, Aufbewahrung, Vorfällen und Cookies", "DPIA、保留期、泄露与 Cookie 清单运营指南"), excerpt: l("Yasal karar vermeden önce risk sinyallerini, zaman çizelgesini, sorumluları ve kanıt bekleyen noktaları görünür kılın.", "Expose risk signals, timelines, owners, and evidence gaps before making a legal determination.", "Risikosignale, Zeitlinien, Verantwortung und Beleglücken vor Rechtsentscheidungen sichtbar machen.", "在作出法律判断前，明确风险信号、时间线、责任人与证据缺口。"), category: l("Gizlilik operasyonları", "Privacy operations", "Datenschutzbetrieb", "隐私运营"), outcome: l("Yeni bir analiz özelliğini DPIA ön elemeden geçirmek, kayıt sınıfları için silme inceleme tarihi üretmek, olay zamanlarını UTC kaydetmek ve çerezleri inceleme önceliğine ayırmak.", "Screen a new analytics feature, calculate deletion-review dates, record incident events in UTC, and prioritise cookie review.", "Analytics-Funktion prüfen, Löschdaten berechnen, Vorfälle in UTC protokollieren und Cookies priorisieren.", "初筛新分析功能、计算删除复核日期、以 UTC 记录事件并确定 Cookie 复核优先级。"), boundary: l("Araçlar mevzuatın hangi süre veya bildirimi zorunlu tuttuğunu belirlemez; yargı alanı, rol ve olay etkisi ayrı değerlendirilmelidir.", "The tools do not determine which deadline or notification law requires; assess jurisdiction, role, and incident impact separately.", "Die Werkzeuge bestimmen keine gesetzlichen Fristen; Rechtsraum und Ereigniswirkung separat prüfen.", "工具不会确定法律要求的期限或通知；必须另行评估司法辖区、角色与事件影响。") },
  { slug: "csp-sri-jwt-tarayici-guvenlik-rehberi", relatedTools: ["csp-kaynak-ifadesi-tester", "sri-degeri-dogrulayici", "jwt-claim-politikasi-denetleyici", "html-guvenli-atribut-denetleyici"], title: l("CSP, SRI, JWT ve HTML İçin Tarayıcı Güvenliği Ön Kontrolleri", "Browser Security Pre-checks for CSP, SRI, JWT, and HTML", "Browser-Sicherheitschecks für CSP, SRI, JWT und HTML", "CSP、SRI、JWT 与 HTML 的浏览器安全预检查"), excerpt: l("Kaynak politikasını, içerik bütünlüğünü, claim sözleşmesini ve riskli HTML özelliklerini ayrı güven sınırlarıyla denetleyin.", "Review source policy, resource integrity, claim contracts, and risky HTML attributes with separate trust boundaries.", "Quellenrichtlinie, Integrität, Claims und riskante HTML-Attribute getrennt prüfen.", "以独立信任边界检查源策略、资源完整性、声明契约与高风险 HTML 属性。"), category: l("Web uygulama güvenliği", "Web application security", "Webanwendungssicherheit", "Web 应用安全"), outcome: l("Harici bir script için SRI değerini doğrulamak, CSP source-list taslağını gerçek URL ile ön sınamak ve JWT payload claimlerini imza doğrulamasından açıkça ayırmak.", "Verify SRI for an external script, pre-test a CSP source-list with a real URL, and keep JWT payload checks distinct from signature verification.", "SRI prüfen, CSP-Source-List vorab testen und JWT-Claims klar von Signaturprüfung trennen.", "验证外部脚本 SRI、用真实 URL 预检 CSP source-list，并明确区分 JWT payload 检查与签名验证。"), boundary: l("Bu araçlar tam CSP eşleme motoru, sertifika zinciri, JWT imza doğrulayıcısı veya tarayıcı entegrasyon testi değildir.", "These tools are not a full CSP matcher, certificate-chain validator, JWT signature verifier, or browser integration test.", "Kein vollständiger CSP-Matcher, Zertifikatsprüfer, JWT-Signaturvalidator oder Browsertest.", "这些工具不是完整 CSP 匹配器、证书链验证器、JWT 签名验证器或浏览器集成测试。") },
  { slug: "kaynak-kod-sir-ve-kimlik-on-kontrol-rehberi", relatedTools: ["git-diff-sir-tarayicisi", "api-anahtari-format-on-kontrolu", "paket-adi-benzerlik-tarayicisi", "punycode-domain-inceleyici", "ssh-yetkili-anahtar-inceleyici", "pem-blok-inceleyici"], title: l("Commit Öncesi Sır, Paket, Alan Adı ve Anahtar Hijyeni", "Pre-commit Secret, Package, Domain, and Key Hygiene", "Secret-, Paket-, Domain- und Schlüsselhygiene vor Commits", "提交前的秘密、包、域名与密钥卫生"), excerpt: l("Eklenen satırları yüksek sinyalli desenlerle tarayın, yazım benzeri paketleri sorgulayın ve yalnızca açık anahtar metadatasını inceleyin.", "Scan added lines for high-signal patterns, question lookalike packages, and inspect public-key metadata only.", "Neue Zeilen nach Secrets scannen, ähnliche Pakete prüfen und nur Public-Key-Metadaten untersuchen.", "扫描新增行中的高置信模式、质疑相似包名并仅检查公钥元数据。"), category: l("Güvenli geliştirme", "Secure development", "Sichere Entwicklung", "安全开发"), outcome: l("Pull request öncesinde diff taraması çalıştırmak, şüpheli paketi güvenilen listeyle karşılaştırmak, domain yazı sistemini incelemek ve açık SSH parmak izini ikinci kanalla doğrulamak.", "Scan a diff before review, compare suspicious packages to a trusted list, inspect domain scripts, and verify public SSH fingerprints over a second channel.", "Diff scannen, Pakete vergleichen, Domain-Schriften prüfen und SSH-Fingerabdruck über zweiten Kanal bestätigen.", "在审查前扫描 diff、将可疑包与可信列表比较、检查域名文字系统并通过第二通道验证 SSH 公钥指纹。"), boundary: l("Desen bulunmaması sır olmadığını veya paketin güvenilirliğini kanıtlamaz; gerçek sır sızdıysa döndürün ve geçmişi uygun süreçle temizleyin.", "No pattern match proves neither absence of secrets nor package trust; rotate real exposures and remediate history through an approved process.", "Kein Treffer beweist weder Secret-Freiheit noch Paketvertrauen; echte Secrets rotieren.", "未匹配模式不代表没有秘密或包可信；真实泄露必须轮换并按批准流程修复历史。") },
  { slug: "seffaf-operasyon-hesaplari-rehberi", relatedTools: ["yuzde-dagilim-dengeleyici", "birim-fiyat-karsilastirici", "nakit-pisti-hesaplayici", "stok-yeniden-siparis-hesaplayici", "toplanti-maliyeti-hesaplayici"], title: l("Şeffaf Formüllerle Operasyon ve Maliyet Senaryoları", "Operational and Cost Scenarios with Transparent Formulas", "Betriebs- und Kostenszenarien mit transparenten Formeln", "使用透明公式构建运营与成本场景"), excerpt: l("Yüzde dağılımı, birim fiyat, nakit pisti, stok eşiği ve toplantı maliyetini ortak varsayım tablosunda yönetin.", "Manage allocation, unit price, runway, reorder points, and meeting cost in one assumptions table.", "Verteilung, Grundpreis, Liquidität, Bestellpunkt und Meetingkosten gemeinsam modellieren.", "在统一假设表中管理百分比分配、单位价格、现金周期、再订购点与会议成本。"), category: l("Operasyon planlama", "Operations planning", "Betriebsplanung", "运营规划"), outcome: l("Aynı karar için temel, olumsuz ve iyimser senaryoları üretmek; para birimi, vergi, zamanlama ve belirsizliği çıktı yanında açıkça kaydetmek.", "Build baseline, adverse, and optimistic cases for one decision while recording currency, tax, timing, and uncertainty next to results.", "Basis-, Negativ- und Optimistikszenarien samt Währung, Steuer und Unsicherheit dokumentieren.", "为同一决策构建基准、不利与乐观场景，并在结果旁记录货币、税费、时点与不确定性。"), boundary: l("Sabit oran ve ortalamalar gerçek talep, fiyat, nakit akışı veya davranış dağılımını temsil etmeyebilir; sonuç tavsiye değil senaryodur.", "Fixed rates and averages may not represent real demand, pricing, cash flow, or behaviour; results are scenarios, not advice.", "Feste Werte repräsentieren reale Nachfrage oder Cashflow möglicherweise nicht; Ergebnisse sind Szenarien.", "固定比率与平均值可能不代表真实需求、价格、现金流或行为分布；结果仅为场景而非建议。") },
  { slug: "orneklem-guven-araligi-kapasite-rehberi", relatedTools: ["orneklem-buyuklugu-tahminleyici", "guven-araligi-hesaplayici", "vardiya-kapsama-hesaplayici", "maas-saatlik-ucret-donusturucu"], title: l("Örneklem, Güven Aralığı ve Kapasite Hesaplarını Doğru Yorumlama", "Interpreting Sample, Confidence, and Capacity Calculations Correctly", "Stichproben-, Konfidenz- und Kapazitätsrechnungen richtig deuten", "正确解释样本量、置信区间与容量计算"), excerpt: l("Formülü yeniden üretilebilir tutun; örnekleme tasarımı, yanlılık, dağılım ve iş gücü varsayımlarını sonucun dışında bırakmayın.", "Keep formulas reproducible and do not hide sampling design, bias, distribution, or workforce assumptions.", "Formeln reproduzierbar halten und Stichprobendesign, Bias sowie Kapazitätsannahmen offenlegen.", "保持公式可复现，并明确样本设计、偏差、分布与人员假设。"), category: l("Nicel karar desteği", "Quantitative decision support", "Quantitative Entscheidungshilfe", "定量决策支持"), outcome: l("Bir oran araştırması için örneklem tahmini yapmak, ortalama için yaklaşık güven aralığı üretmek ve vardiya açığını saatlik tabloda göstermek.", "Estimate a sample for a proportion study, build an approximate mean interval, and show hourly staffing gaps.", "Stichprobe schätzen, Mittelwertintervall berechnen und stündliche Personallücken zeigen.", "估算比例研究样本、构建均值近似区间并显示每小时人员缺口。"), boundary: l("Yaklaşık z formülleri karmaşık örnekleme, küçük örnek, bağımlı gözlem veya ağır kuyrukları çözmez; istatistik uzmanı gerekir.", "Approximate z formulas do not solve complex samples, small n, dependence, or heavy tails; obtain statistical review.", "z-Näherungen lösen keine komplexen Stichproben oder Abhängigkeiten; statistische Prüfung nötig.", "近似 z 公式不能解决复杂抽样、小样本、相关观测或重尾问题；需统计专家复核。") },
  { slug: "odak-zaman-ve-ekip-planlama-rehberi", relatedTools: ["zaman-bloklama-plani", "pomodoro-oturum-planlayici", "etkinlik-kontrol-listesi-olusturucu", "toplanti-maliyeti-hesaplayici"], title: l("Odak Süresi, Etkinlik ve Ekip Maliyetini Birlikte Planlama", "Planning Focus Time, Events, and Team Cost Together", "Fokuszeit, Veranstaltungen und Teamkosten gemeinsam planen", "协同规划专注时间、活动与团队成本"), excerpt: l("Görevleri zaman bloklarına çevirin, molayı koruyun, sorumluyu görünür yapın ve toplantı süresinin fırsat maliyetini hesaplayın.", "Turn tasks into time blocks, protect breaks, expose ownership, and calculate the opportunity cost of meetings.", "Aufgaben blocken, Pausen schützen, Verantwortung zeigen und Meetingkosten berechnen.", "将任务转为时间块、保护休息、明确责任人并计算会议机会成本。"), category: l("Kişisel ve ekip üretkenliği", "Personal and team productivity", "Persönliche und Teamproduktivität", "个人与团队生产力"), outcome: l("Bir yayın gününü öncelikli bloklara ayırmak, altı odak oturumu planlamak, kontrol listesini sahip ve tarihle bağlamak ve toplantı maliyetini alternatifle karşılaştırmak.", "Split a release day into priority blocks, schedule six focus sessions, bind checklist items to owners and dates, and compare meeting cost with an alternative.", "Release-Tag blocken, Fokus planen, Checkliste Verantwortlichen zuordnen und Meetingkosten vergleichen.", "将发布日拆为优先时间块、安排六次专注会话、关联清单责任人与日期并比较会议成本与替代方案。"), boundary: l("Planlayıcı takvim rezervasyonu yapmaz, insan enerjisini ölçmez veya çalışma hakkı kurallarını uygulamaz; kullanıcı planı değiştirebilmelidir.", "The planner books no calendar, measures no human energy, and enforces no labour rules; users must be able to change the plan.", "Der Planer bucht keinen Kalender und erzwingt kein Arbeitsrecht; Nutzer müssen den Plan ändern können.", "规划器不会预订日历、衡量人的精力或执行劳动规则；用户必须能修改计划。") },
  { slug: "ai-parcalama-ve-arac-cagrisi-rehberi", relatedTools: ["embedding-parca-ortusme-planlayici", "arac-cagrisi-json-dogrulayici", "prompt-bagimlilik-grafi-cikarici", "prompt-rubrik-puanlayici"], title: l("AI Parçalama, Araç Çağrısı ve İş Akışı Sözleşmesi Tasarımı", "Designing AI Chunking, Tool Calls, and Workflow Contracts", "KI-Chunking, Tool Calls und Workflow-Verträge entwerfen", "设计 AI 分块、工具调用与工作流契约"), excerpt: l("Bağlam tekrar maliyetini hesaplayın, araç argümanını şemaya bağlayın ve bağımlılık grafiğini en az yetkili yürütme planına dönüştürün.", "Calculate repeated context, bind tool arguments to a schema, and turn dependencies into a least-privileged execution plan.", "Kontextwiederholung berechnen, Tool-Argumente binden und Abhängigkeiten minimal berechtigen.", "计算重复上下文、将工具参数绑定架构并把依赖关系转为最小权限执行计划。"), category: l("Yerel AI iş akışları", "Local AI workflows", "Lokale KI-Abläufe", "本地 AI 工作流"), outcome: l("Uzun belgeyi örtüşmeli parçalara ayırmak, beklenen araç çağrısı JSON’unu doğrulamak, döngüsüz plan üretmek ve çıktıyı rubrikle kabul etmek.", "Chunk a long document with overlap, validate expected tool-call JSON, build an acyclic plan, and accept output through a rubric.", "Dokument mit Überlappung teilen, Tool-Call-JSON prüfen, azyklisch planen und per Rubrik abnehmen.", "将长文档重叠分块、验证工具调用 JSON、构建无环计划并用量表验收输出。"), boundary: l("Bu hesaplar embedding kalitesi, model doğruluğu veya aracın gerçekten yetkili çalıştığını kanıtlamaz; çalışma zamanı kontrolleri ayrı zorlanmalıdır.", "These calculations prove neither embedding quality, model accuracy, nor real tool authorization; enforce runtime controls separately.", "Diese Berechnungen beweisen weder Embedding-Qualität noch echte Tool-Berechtigung.", "这些计算不能证明 embedding 质量、模型准确性或真实工具授权；运行时控制必须另行强制。") },
  { slug: "doi-eleme-kanit-tekillestirme-rehberi", relatedTools: ["doi-toplu-dogrulayici", "literatur-eleme-karar-gunlugu", "kanit-tablosu-tekillestirici", "iddia-kanit-boslugu-inceleyici"], title: l("DOI Doğrulamadan Kanıt Tablosu Tekilleştirmeye Araştırma Akışı", "A Research Workflow from DOI Validation to Evidence Deduplication", "Rechercheablauf von DOI-Prüfung bis Evidenz-Deduplizierung", "从 DOI 验证到证据表去重的研究工作流"), excerpt: l("Kaynak kimliğini normalleştirin, eleme kararını gerekçelendirin, çatışmayı görünür yapın ve olası kopyaları insan incelemesine hazırlayın.", "Normalise source identifiers, justify screening decisions, expose conflicts, and prepare likely duplicates for human review.", "Quellenkennungen normalisieren, Screening begründen, Konflikte zeigen und Duplikate prüfen.", "规范来源标识、说明筛选决策、暴露冲突并将可能重复项交由人工复核。"), category: l("Kanıt yönetimi", "Evidence management", "Evidenzmanagement", "证据管理"), outcome: l("Bir tarama dışa aktarımındaki DOI’leri tek biçime getirmek, iki inceleyicinin karar çakışmasını bulmak ve başlık/yıl benzerliğini yalnızca aday eşleşme olarak raporlamak.", "Normalise DOI values in a search export, find reviewer decision conflicts, and report title/year similarity only as candidate matches.", "DOIs normalisieren, Reviewer-Konflikte finden und Titelähnlichkeit nur als Kandidat melden.", "规范检索导出的 DOI、查找审查者决策冲突并仅将标题/年份相似性报告为候选匹配。"), boundary: l("DOI sözdizimi kaynağın varlığını veya kalitesini kanıtlamaz; fuzzy eşleşme kayıtları otomatik silmemelidir.", "DOI syntax proves neither source existence nor quality, and fuzzy matching must never delete records automatically.", "DOI-Syntax beweist weder Existenz noch Qualität; Fuzzy-Matches dürfen nie automatisch löschen.", "DOI 语法不能证明来源存在或质量；模糊匹配绝不能自动删除记录。") },
];

const headings: Record<Locale, string[]> = {
  tr: ["Kararı ve başarı ölçütünü tanımlayın", "Girdi sözleşmesini ve hakları hazırlayın", "Akışı küçük, geri alınabilir adımlarla çalıştırın", "Hata ve sınır vakalarını kasıtlı olarak sınayın", "Çıktıyı kaynakla uzlaştırın", "Kanıtı, sınırı ve sonraki incelemeyi kaydedin"],
  en: ["Define the decision and success criteria", "Prepare the input contract and rights", "Run small, reversible workflow steps", "Deliberately test failures and edge cases", "Reconcile output with the source", "Record evidence, limits, and next review"],
  de: ["Entscheidung und Erfolgskriterien definieren", "Eingabevertrag und Rechte vorbereiten", "Kleine reversible Schritte ausführen", "Fehler und Grenzfälle bewusst testen", "Ausgabe mit Quelle abgleichen", "Belege, Grenzen und nächste Prüfung protokollieren"],
  zh: ["定义决策与成功标准", "准备输入契约与使用权", "以小而可逆的步骤执行工作流", "主动测试失败与边界案例", "将输出与来源核对", "记录证据、边界与下次复核"],
};

const paragraphs: Record<Locale, Array<(g: Guide) => string>> = {
  tr: [
    (g) => `Araç seçmeden önce verilecek kararı, kararın sahibini ve yanlış sonucun etkisini yazın. Bu rehberdeki somut hedef şudur: ${g.outcome.tr} “Çıktı üretildi” bir başarı ölçütü değildir; doğruluk, tamlık, geri alınabilirlik, süre ve insan onayı için ölçülebilir eşikler belirleyin. Kararı etkileyen varsayımları ilk sayfada görünür tutmak, sonradan yapılan gerekçelendirmeyi ve otomasyon yanlılığını azaltır.`,
    (g) => `Yalnızca sentetik veri, kendi veriniz veya açıkça kullanım hakkınız bulunan içerikle başlayın. Ham girdiyi salt okunur bir kopya olarak koruyun; alan adı, tür, birim, dil, tarih biçimi, kodlama, eksik değer ve yinelenen kayıt kurallarını ayrı bir sözlükte yazın. ${g.boundary.tr} Hassas veri gerekiyorsa veri minimizasyonu uygulayın ve paylaşılabilir örneklerde gerçek kişileri temsil eden değer kullanmayın.`,
    (g) => `Akışı tek bir büyük dönüşüm yerine gözlenebilir kapılara ayırın: giriş doğrulaması, dönüşüm, yapısal kontrol, önce/sonra karşılaştırması ve dışa aktarma. ${g.relatedTools.join(", ")} araçlarının her biri için beklenen girdi, beklenen çıktı, hata mesajı ve durdurma koşulu yazılı olsun. İlk denemeyi tek kayıtla yapın; küçük toplu örnek başarıyla uzlaşmadan büyük dosyaya geçmeyin.`,
    () => `Mutlu yol örneğinin yanında boş girdi, bozuk kodlama, beklenmeyen Unicode, aşırı uzun değer, eksik zorunlu alan, yinelenen anahtar, negatif sayı, sıfıra bölme, yanlış zaman dilimi ve kasıtlı çelişki deneyin. Hata kullanıcıya hangi alanın neden geçersiz olduğunu ve düzeltmek için ne yapacağını söylemelidir. Sessiz düzeltme yerine değişen değeri ve uygulanan varsayımı sonuçla birlikte gösterin.`,
    () => `Kaynak ve çıktı için satır, alan, toplam, boş değer, tekil anahtar ve kontrol toplamlarını karşılaştırın. Dönüşüm tersine çevrilebiliyorsa gidiş-dönüş testi yapın; değilse veri kaybı listesini yayınlayın. Rastgele seçilmiş birkaç kaydı elle inceleyin ve önemli iddiaları birincil kaynağa kadar takip edin. Görsel olarak düzgün bir tablo, yapısal olarak doğru veya gerçeğe uygun olduğunun kanıtı değildir.`,
    (g) => `Son çalışma kaydına tarih, araç ve veri sürümü, kabul eşiği, bilinen sınırlar, hata vakaları, çıktı özeti, insan onayı ve yeniden inceleme tarihi ekleyin. ${g.boundary.tr} Hukuki, güvenlik, sağlık veya finans etkisi bulunan kararlarda güncel birincil kaynak ve yetkili uzman incelemesini iş akışının zorunlu kapısı yapın; araç sonucunu kesin doğrulama diye sunmayın.`,
  ],
  en: [
    (g) => `Before selecting a tool, write down the decision, its owner, and the impact of a wrong result. The practical objective here is: ${g.outcome.en} “Output was produced” is not a success criterion; define measurable thresholds for accuracy, completeness, reversibility, time, and human approval. Keeping assumptions visible from the start reduces post-hoc justification and automation bias.`,
    (g) => `Begin only with synthetic data, your own data, or material whose reuse rights are explicit. Preserve the raw input read-only and document field names, types, units, language, dates, encoding, missing values, and duplicate rules in a separate dictionary. ${g.boundary.en} Minimise sensitive data and never use values representing real people in shareable examples.`,
    (g) => `Split the workflow into observable gates: input validation, transformation, structural review, before/after comparison, and export. For ${g.relatedTools.join(", ")}, document expected input, output, failure message, and stop condition. Start with one record and do not scale until a small batch reconciles successfully.`,
    () => `Alongside the happy path, test empty input, malformed encoding, unexpected Unicode, oversized values, missing required fields, duplicate keys, negative numbers, division by zero, wrong time zones, and deliberate contradictions. Errors should name the invalid field, explain why it failed, and state the next corrective action. Prefer visible assumptions to silent correction.`,
    () => `Reconcile source and output row counts, fields, totals, missing values, unique keys, and checksums. Run a round-trip test when conversion is reversible; otherwise publish a data-loss list. Manually inspect a random sample and trace consequential claims to primary evidence. A visually tidy table is not proof of structural or factual correctness.`,
    (g) => `Record date, tool and data version, acceptance threshold, known limits, failure cases, output summary, human approval, and next review. ${g.boundary.en} For legal, security, health, or financial impact, make qualified review against current primary sources a mandatory workflow gate; never present a tool result as conclusive verification.`,
  ],
  de: [
    (g) => `Vor der Werkzeugwahl werden Entscheidung, Verantwortung und Folgen eines Fehlers dokumentiert. Das konkrete Ziel lautet: ${g.outcome.de} Eine erzeugte Ausgabe ist noch kein Erfolg; Genauigkeit, Vollständigkeit, Reversibilität, Zeit und menschliche Freigabe brauchen messbare Schwellen. Sichtbare Annahmen reduzieren nachträgliche Rechtfertigung und Automationsbias.`,
    (g) => `Beginnen Sie nur mit synthetischen, eigenen oder klar lizenzierten Daten. Bewahren Sie die Rohdaten schreibgeschützt auf und dokumentieren Sie Felder, Typen, Einheiten, Sprache, Datum, Kodierung, Leerwerte und Duplikate. ${g.boundary.de} Sensible Daten werden minimiert; teilbare Beispiele enthalten keine realen Personenwerte.`,
    (g) => `Teilen Sie den Ablauf in Eingabeprüfung, Transformation, Strukturkontrolle, Vorher/Nachher-Vergleich und Export. Für ${g.relatedTools.join(", ")} werden Eingabe, Ausgabe, Fehlermeldung und Stoppbedingung festgelegt. Erst einen Datensatz, dann einen kleinen Batch testen und abgleichen.`,
    () => `Testen Sie leere und fehlerhafte Eingaben, unerwartetes Unicode, übergroße Werte, fehlende Pflichtfelder, Duplikate, negative Zahlen, Division durch null, falsche Zeitzonen und bewusste Widersprüche. Fehler müssen Feld, Grund und Korrekturschritt nennen; Annahmen werden sichtbar statt still korrigiert.`,
    () => `Gleichen Sie Zeilen, Felder, Summen, Leerwerte, eindeutige Schlüssel und Prüfsummen zwischen Quelle und Ausgabe ab. Reversible Konvertierungen brauchen Round-Trip-Tests; andernfalls wird möglicher Datenverlust dokumentiert. Eine Stichprobe wird manuell geprüft und wichtige Aussagen bis zur Primärquelle verfolgt.`,
    (g) => `Protokollieren Sie Datum, Werkzeug- und Datenversion, Schwellen, Grenzen, Fehlerfälle, Ausgabe, Freigabe und nächste Prüfung. ${g.boundary.de} Rechtliche, sicherheitskritische, gesundheitliche oder finanzielle Entscheidungen erfordern qualifizierte Prüfung mit aktuellen Primärquellen.`,
  ],
  zh: [
    (g) => `选择工具前先写明要作出的决策、责任人以及错误结果的影响。本指南的实际目标是：${g.outcome.zh}“生成了输出”并非成功标准；应为准确性、完整性、可逆性、时间与人工批准设定可衡量阈值。从一开始就公开假设，可减少事后合理化与自动化偏见。`,
    (g) => `仅使用合成数据、自有数据或重用权明确的材料。以只读方式保留原始输入，并在独立字典中记录字段名、类型、单位、语言、日期、编码、缺失值与重复规则。${g.boundary.zh}尽量减少敏感数据，共享示例不得使用代表真实个人的值。`,
    (g) => `把工作流拆为可观察关卡：输入验证、转换、结构检查、前后比较与导出。为 ${g.relatedTools.join("、")} 明确记录预期输入、输出、失败消息与停止条件。先用单条记录测试，小批量数据核对成功前不要扩展规模。`,
    () => `除正常路径外，还要测试空输入、错误编码、异常 Unicode、超长值、缺失必填字段、重复键、负数、除零、错误时区与故意冲突。错误消息应指出无效字段、失败原因与纠正动作；不要静默修复，应在结果旁显示改变的值与所用假设。`,
    () => `核对来源与输出的行数、字段、总计、缺失值、唯一键与校验值。可逆转换应执行往返测试；不可逆时应发布数据丢失清单。人工抽查随机记录，并把重要主张追溯到第一手来源。视觉整齐的表格不能证明结构或事实正确。`,
    (g) => `最终记录应包含日期、工具与数据版本、验收阈值、已知边界、失败案例、输出摘要、人工批准与下次复核日期。${g.boundary.zh}涉及法律、安全、健康或财务影响时，应把合格专家依据最新一手来源的复核设为强制关卡，绝不能把工具结果表述为最终验证。`,
  ],
};

function sections(locale: Locale, guide: Guide): ArticleSection[] {
  return headings[locale].map((heading, index) => ({ heading, paragraphs: [paragraphs[locale][index](guide), index % 2 ? guide.boundary[locale] : guide.excerpt[locale]], bullets: [guide.outcome[locale], guide.boundary[locale], txt(locale, { tr: "Girdi, çıktı ve karar sahibini kaydedin.", en: "Record input, output, and decision owner.", de: "Eingabe, Ausgabe und Verantwortung protokollieren.", zh: "记录输入、输出与决策责任人。" })] }));
}
function txt(locale: Locale, value: L) { return value[locale]; }

const renamedToolSlugs: Record<string, string> = {
  "sayi-tabani-donusturucu": "buyuk-tamsayi-taban-donusturucu",
  "sorgu-dizesi-json-donusturucu": "cok-degerli-sorgu-json-donusturucu",
  "birim-fiyat-karsilastirici": "paket-birim-maliyet-karsilastirici",
  "maas-saatlik-ucret-donusturucu": "calisma-ucreti-esdegerlik-hesaplayici",
  "orneklem-buyuklugu-tahminleyici": "oran-arastirmasi-orneklem-planlayici",
};

const publishedGuides = guides.slice(0, 15).map((guide) => ({
  ...guide,
  relatedTools: guide.relatedTools.map((slug) => renamedToolSlugs[slug] ?? slug),
}));

export const frontierPosts: Post[] = publishedGuides.map((guide) => ({
  slug: guide.slug, relatedTools: guide.relatedTools, date: "2026-08-02", updated: "2026-08-02", readTime: { tr: "18 dk", en: "17 min" }, title: { tr: guide.title.tr, en: guide.title.en }, excerpt: { tr: guide.excerpt.tr, en: guide.excerpt.en }, description: { tr: `${guide.excerpt.tr} Uygulama adımları, olumsuz testler, doğrulama ölçütleri ve güven sınırlarıyla ayrıntılı rehber.`, en: `${guide.excerpt.en} A detailed guide with implementation steps, negative tests, verification criteria, and trust boundaries.` }, category: { tr: guide.category.tr, en: guide.category.en }, visualSuggestion: { tr: "Yerel işlem adımlarını, hata kapılarını ve insan onayını gösteren erişilebilir akış diyagramı.", en: "An accessible flow diagram showing local processing, failure gates, and human approval." }, sections: { tr: sections("tr", guide), en: sections("en", guide) },
}));

export const frontierLocalizedGuides: LocalizedGuide[] = publishedGuides.map((guide) => ({
  slug: guide.slug, relatedTools: guide.relatedTools, date: "2026-08-02", updated: "2026-08-02", copy: {
    de: { title: guide.title.de, excerpt: guide.excerpt.de, description: `${guide.excerpt.de} Ausführlich mit Negativtests, Prüfkriterien und Vertrauensgrenzen.`, category: guide.category.de, readTime: "17 Min.", sections: sections("de", guide) },
    zh: { title: guide.title.zh, excerpt: guide.excerpt.zh, description: `${guide.excerpt.zh} 包含详细步骤、负面测试、核验标准与信任边界。`, category: guide.category.zh, readTime: "约 17 分钟", sections: sections("zh", guide) },
  },
}));

export const frontierGuideCount = publishedGuides.length;
