export type NewsItem = { id: string; title: string; url: string; date: string; source: "NASA" | "NIST" | "CISA" | "GOV.UK" | "NSF" | "NIH" | "ESA" | "NCSC" | "NOAA"; category: "science" | "technology" | "security" | "standards"; region: "global" | "uk"; sourceLanguage: "en"; sourceSummary: string; summaryOrigin: "feed" | "metadata" };

// Generated at build time from official, allowlisted RSS endpoints. Feed descriptions are attribution-linked and intentionally limited to a short excerpt.
export const newsGeneratedAt = "2026-08-09T00:32:21.607Z";
export const newsItems: NewsItem[] = [
  {
    "id": "nasa-iiqr5e",
    "title": "APOD: 2026 August 8 – A Messier Moment for Tempel 2",
    "url": "https://science.nasa.gov/image-article/apod/apod-2026-august-8-a-messier-moment-for-tempel-2/",
    "date": "2026-08-08",
    "source": "NASA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "NASA published this official science update under the headline “APOD: 2026 August 8 – A Messier Moment for Tempel 2”. Open the source for…",
    "summaryOrigin": "metadata"
  },
  {
    "id": "noaa-michee",
    "title": "NOAA to hold public meetings on California Coastal Management Program",
    "url": "https://oceanservice.noaa.gov/news/aug26/czma-public-meetings.html",
    "date": "2026-08-08",
    "source": "NOAA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Public invited to provide input on the state’s coastal management program and performance evaluation",
    "summaryOrigin": "feed"
  },
  {
    "id": "nasa-6uvvox",
    "title": "2026 IGARSS Hyperwall Schedule",
    "url": "https://science.nasa.gov/earth/2026-igarss-hyperwall-schedule/",
    "date": "2026-08-07",
    "source": "NASA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "IGARSS 2026 Join NASA in the Exhibit Hall (Booth #100) for Hyperwall Storytelling by NASA experts. Full Hyperwall Agenda below. MONDAY, AUGUST 10 3:00…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nasa-1hqizfc",
    "title": "NASA’s IXPE Studies Magnetar",
    "url": "https://www.nasa.gov/image-article/nasas-ixpe-studies-magnetar/",
    "date": "2026-08-07",
    "source": "NASA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Scientists using NASA’s IXPE (Imaging X-ray Polarimetry Explorer) conducted more than 140 hours of observations of the magnetar 1E 1547-5408, shown in this Aug.…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nasa-104eio1",
    "title": "NASA’s Lunar Development and Test Facility Prepares Artemis Hardware for Moon",
    "url": "https://www.nasa.gov/centers-and-facilities/johnson/nasas-lunar-development-and-test-facility-prepares-artemis-hardware-for-moon/",
    "date": "2026-08-07",
    "source": "NASA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Before astronauts return to the Moon’s surface through NASA’s Artemis program, the hardware they depend on must first prove it can survive the unforgiving…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nasa-16nfsi3",
    "title": "APOD: 2026 August 7 – Rubin’s Cosmos Field",
    "url": "https://science.nasa.gov/image-article/apod/apod-2026-august-6-rubins-cosmos-field/",
    "date": "2026-08-07",
    "source": "NASA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "NASA published this official science update under the headline “APOD: 2026 August 7 – Rubin’s Cosmos Field”. Open the source for full context.",
    "summaryOrigin": "metadata"
  },
  {
    "id": "nasa-ly3ewr",
    "title": "Sensing the Poles’ Hidden Heat",
    "url": "https://science.nasa.gov/earth/earth-observatory/sensing-the-poles-hidden-heat/",
    "date": "2026-08-07",
    "source": "NASA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "New animations from NASA’s PREFIRE mission reveal two years of seasonal temperature swings at the Arctic and Antarctic.",
    "summaryOrigin": "feed"
  },
  {
    "id": "nsf-4yx1e4",
    "title": "Podcast: New telescope to transform study of universe",
    "url": "https://www.nsf.gov/news/podcast-new-telescope-transform-study-universe",
    "date": "2026-08-07",
    "source": "NSF",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "As the 10-year Legacy Survey of Space and Time officially starts, Edward Ajhar discusses the NSF-DOE Vera C. Rubin Observatory and how it will…",
    "summaryOrigin": "feed"
  },
  {
    "id": "esa-qrq62u",
    "title": "Join us live and enjoy the total solar eclipse!",
    "url": "https://www.esa.int/ESA_Multimedia/Videos/2026/08/Join_us_live_and_enjoy_the_total_solar_eclipse",
    "date": "2026-08-07",
    "source": "ESA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Video: 00:01:44 [English] On 12 August 2026, Europe will witness one of nature’s most spectacular events: a total solar eclipse starting at 19:30 CEST.…",
    "summaryOrigin": "feed"
  },
  {
    "id": "esa-e329a7",
    "title": "Week in images: 03-07 August 2026",
    "url": "https://www.esa.int/About_Us/Week_in_images/Week_in_images_03-07_August_2026",
    "date": "2026-08-07",
    "source": "ESA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Week in images: 03-07 August 2026 Discover our week through the lens",
    "summaryOrigin": "feed"
  },
  {
    "id": "esa-1usjh4l",
    "title": "Danube’s waters fall to record lows",
    "url": "https://www.esa.int/ESA_Multimedia/Images/2026/08/Danube_s_waters_fall_to_record_lows",
    "date": "2026-08-07",
    "source": "ESA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Image: These Copernicus Sentinel-2 images over the Danube north of Budapest show how the river’s level has fallen to a record low in Hungary…",
    "summaryOrigin": "feed"
  },
  {
    "id": "esa-nz1hx7",
    "title": "IRIS² reinforced and accelerated as implementation advances",
    "url": "https://www.esa.int/Applications/Connectivity_and_Secure_Communications/IRIS2_reinforced_and_accelerated_as_implementation_advances",
    "date": "2026-08-07",
    "source": "ESA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "On 7 August, the European Commission and the SpaceRISE consortium concluded negotiations and signed an implementation agreement to roll out IRIS² , the European…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nist-3bn656",
    "title": "NIST Researchers Correct Common Error Confounding Nanotech Measurements",
    "url": "https://www.nist.gov/news-events/news/2026/08/nist-researchers-correct-common-error-confounding-nanotech-measurements",
    "date": "2026-08-06",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The scientists offer a practical solution that relies on accounting for measurement errors before testing materials or developing products.",
    "summaryOrigin": "feed"
  },
  {
    "id": "nasa-1sf0hxd",
    "title": "Educators & Teens Get Hands-On With TEMPO Data to Help Investigate Local Air Quality",
    "url": "https://science.nasa.gov/learning-resources/science-activation/educators-teens-get-hands-on-with-tempo-data-to-help-investigate-local-air-quality/",
    "date": "2026-08-06",
    "source": "NASA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The NASA Science Activation Program’s Cosmic Storytelling with NASA Data (CosmicDS) project, led by Harvard University in Cambridge, Massachusetts, works to bring authentic NASA…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nasa-1nd06u7",
    "title": "NASA’s SkyFall Helicopters at Work (Artist’s Concept)",
    "url": "https://science.nasa.gov/photojournal/nasas-skyfall-helicopters-at-work-artists-concept/",
    "date": "2026-08-06",
    "source": "NASA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Description This artist’s concept depicts NASA’s three SkyFall Mars helicopters collecting data while flying over the surface of the Red Planet. The green frequency…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nasa-156ywek",
    "title": "Antenna Testing for NASA’s SkyFall Mission",
    "url": "https://science.nasa.gov/photojournal/antenna-testing-for-nasas-skyfall-mission/",
    "date": "2026-08-06",
    "source": "NASA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Description SkyFall ground-penetrating radar engineer Maya Román connects a coaxial cable to a test antenna in the Environmental Test Lab’s electromagnetic interference testing chamber…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nasa-18lu9mi",
    "title": "I Am Artemis: Tom Percy",
    "url": "https://www.nasa.gov/missions/artemis/i-am-artemis/i-am-artemis-tom-percy/",
    "date": "2026-08-06",
    "source": "NASA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "As NASA sets its sights on long-term exploration of the Moon and Mars, the agency is increasing the cadence of its Artemis missions. Helping…",
    "summaryOrigin": "feed"
  },
  {
    "id": "esa-1msaby4",
    "title": "ExoMars stretches out its legs",
    "url": "https://www.esa.int/ESA_Multimedia/Videos/2026/08/ExoMars_stretches_out_its_legs",
    "date": "2026-08-06",
    "source": "ESA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Video: 00:00:06 The footage shows the simultaneous deployment of two landing legs from the ExoMars landing platform, in two sequential pairs. The legs travel…",
    "summaryOrigin": "feed"
  },
  {
    "id": "esa-g2f20p",
    "title": "Webb opens a Treasure Chest filled with stars",
    "url": "https://www.esa.int/ESA_Multimedia/Images/2026/08/Webb_opens_a_Treasure_Chest_filled_with_stars",
    "date": "2026-08-06",
    "source": "ESA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Image: This NASA/ESA/CSA James Webb Space Telescope Picture of the Month takes us to a fantastical realm within our home galaxy , where piercing…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nist-9ai57k",
    "title": "‘Spooky’ Particles Transit DC Suburbs, a Step Toward a Quantum Network",
    "url": "https://www.nist.gov/news-events/news/2026/08/spooky-particles-transit-dc-suburbs-step-toward-quantum-network",
    "date": "2026-08-05",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The achievement shows that fragile quantum entanglement can survive even in tough, real-world conditions.",
    "summaryOrigin": "feed"
  },
  {
    "id": "esa-kta2py",
    "title": "Total solar eclipse: how to watch live from home",
    "url": "https://www.esa.int/Science_Exploration/Space_Science/Total_solar_eclipse_how_to_watch_live_from_home",
    "date": "2026-08-05",
    "source": "ESA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "A total solar eclipse is coming to Europe. The European Space Agency (ESA) will broadcast live from 19:30 CEST on 12 August, allowing you…",
    "summaryOrigin": "feed"
  },
  {
    "id": "esa-r3ae6q",
    "title": "Your chance to run software in deep space on ESA's asteroid mission",
    "url": "https://www.esa.int/Enabling_Support/Space_Engineering_Technology/Your_chance_to_run_software_in_deep_space_on_ESA_s_asteroid_mission",
    "date": "2026-08-05",
    "source": "ESA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The European Space Agency is offering European researchers and companies a rare and exciting opportunity to run their innovative software directly in deep space…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nist-18jr3vy",
    "title": "NIST Joins National Genesis Mission to Accelerate AI Innovation",
    "url": "https://www.nist.gov/news-events/news/2026/08/nist-joins-national-genesis-mission-accelerate-ai-innovation",
    "date": "2026-08-04",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "NIST will execute two of its efforts through its Centers for AI in Manufacturing and Critical Infrastructure.",
    "summaryOrigin": "feed"
  },
  {
    "id": "nsf-1aohd17",
    "title": "New NSF State and Regional AI Infrastructure Hubs will power AI-enabled scientific research across the country",
    "url": "https://www.nsf.gov/news/new-nsf-state-regional-ai-infrastructure-hubs-will-power-ai",
    "date": "2026-08-04",
    "source": "NSF",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "New initiative will accelerate AI-enabled scientific discovery by expanding access to compute for researchers, students and educators through regional partnerships among state and local…",
    "summaryOrigin": "feed"
  },
  {
    "id": "ncsc-vlazfq",
    "title": "NCSC statement in response to recent incidents resulting from frontier AI evaluations",
    "url": "https://www.ncsc.gov.uk/news/ncsc-statement-in-response-to-recent-incidents-resulting-from-frontier-ai-evaluations",
    "date": "2026-08-04",
    "source": "NCSC",
    "category": "security",
    "region": "uk",
    "sourceLanguage": "en",
    "sourceSummary": "A statement from Ollie Whitehouse, Chief Technology Officer at the NCSC, on AI security following recent incidents.",
    "summaryOrigin": "feed"
  },
  {
    "id": "nasa-1eenvhb",
    "title": "NASA Delivers Navigation System for Commercial Lunar Relay",
    "url": "https://www.nasa.gov/technology/space-comms/nasa-delivers-navigation-system-for-commercial-lunar-relay/",
    "date": "2026-08-03",
    "source": "NASA",
    "category": "technology",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "NASA delivered the NavCube3-mini payload on July 13 to Intuitive Machines for integration into Altus-1, the company’s first lunar relay satellite, marking an important…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nsf-be95t0",
    "title": "NSF stands up 2 Materials Innovation Platforms with $50M investment",
    "url": "https://www.nsf.gov/news/nsf-stands-2-materials-innovation-platforms-50m-investment",
    "date": "2026-08-03",
    "source": "NSF",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The U.S. National Science Foundation is investing $50 million in research infrastructure to enable the discovery and development of materials that can withstand extreme…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nsf-1poo2n9",
    "title": "Building the future, atom by atom — NSF deploys $108M for materials science at 6 research centers",
    "url": "https://www.nsf.gov/news/building-future-atom-atom-nsf-deploys-108m-materials-science",
    "date": "2026-07-30",
    "source": "NSF",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The U.S. National Science Foundation is pushing materials science beyond the state-of-the-art with an investment of $108 million in six advanced research centers. The…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nasa-1xseic1",
    "title": "NASA’s Curiosity Mars Rover Discovers Field of Honeycomb Textures",
    "url": "https://www.nasa.gov/missions/mars-science-laboratory/curiosity-rover/nasas-curiosity-mars-rover-discovers-field-of-honeycomb-textures/",
    "date": "2026-07-29",
    "source": "NASA",
    "category": "technology",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "As NASA’s Curiosity rover recently began climbing up a Martian valley nicknamed “Valle Grande,” it sent back images that were a familiar sight to…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nsf-1tzy9r3",
    "title": "NSF partners with universities and industry on pilot initiative for four-year Ph.D. programs with real-world research placements",
    "url": "https://www.nsf.gov/news/nsf-partners-universities-industry-pilot-initiative-four",
    "date": "2026-07-29",
    "source": "NSF",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The U.S. National Science Foundation announced a $47 million investment over ﬁve years, along with additional ﬁnancial commitments from nearly three dozen universities and…",
    "summaryOrigin": "feed"
  },
  {
    "id": "gov-uk-mzuczg",
    "title": "Letter to the Prime Minister on investment in innovative science and technology companies",
    "url": "https://www.gov.uk/government/publications/letter-to-the-prime-minister-on-investment-in-innovative-science-and-technology-companies",
    "date": "2026-07-28",
    "source": "GOV.UK",
    "category": "technology",
    "region": "uk",
    "sourceLanguage": "en",
    "sourceSummary": "The Council for Science and Technology has written to the Prime Minister giving advice on encouraging scale up investment in innovative science and technology…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nsf-gyz6e7",
    "title": "NSF announces first awards to advance AI and cybersecurity education and workforce development through CyberAICorps Scholarship for Service Program",
    "url": "https://www.nsf.gov/news/nsf-announces-first-awards-advance-ai-cybersecurity",
    "date": "2026-07-28",
    "source": "NSF",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The U.S. National Science Foundation's Directorate for STEM Education today announced the inaugural awards under the CyberAICorps Scholarship for Service (CyberAI SFS) program, representing…",
    "summaryOrigin": "feed"
  },
  {
    "id": "gov-uk-140eqmj",
    "title": "Developing drone technology for future warfare",
    "url": "https://www.gov.uk/government/case-studies/developing-drone-technology-for-future-warfare",
    "date": "2026-07-27",
    "source": "GOV.UK",
    "category": "technology",
    "region": "uk",
    "sourceLanguage": "en",
    "sourceSummary": "Dstl worked with the Army, industry and allies to test drone technology and develop AI capabilities for future battlefield operations.",
    "summaryOrigin": "feed"
  },
  {
    "id": "nsf-9wumxj",
    "title": "Podcast: New microchips could supercharge AI",
    "url": "https://www.nsf.gov/news/podcast-new-microchips-could-supercharge-ai",
    "date": "2026-07-27",
    "source": "NSF",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "U.S. National Science Foundation-supported researcher Qing Cao discusses a new monolithic, 3D-integrated silicon microchip and how it might impact artificial intelligence systems...",
    "summaryOrigin": "feed"
  },
  {
    "id": "nasa-1b60hfw",
    "title": "NASA Announces New Spacecraft Technology Demonstration Mission at Moon",
    "url": "https://www.nasa.gov/directorates/rtmd/nasa-announces-new-spacecraft-technology-demonstration-mission-at-moon/",
    "date": "2026-07-24",
    "source": "NASA",
    "category": "technology",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "NASA is working with industry to advance the next phase of cislunar infrastructure for the agency’s Artemis program and Moon Base, including orbital assets…",
    "summaryOrigin": "feed"
  },
  {
    "id": "gov-uk-o6aft2",
    "title": "AI to power change at the heart of government as Lord Vallance appointed chair of new PM AI Taskforce",
    "url": "https://www.gov.uk/government/news/ai-to-power-change-at-the-heart-of-government-as-lord-vallance-appointed-chair-of-new-pm-ai-taskforce",
    "date": "2026-07-24",
    "source": "GOV.UK",
    "category": "technology",
    "region": "uk",
    "sourceLanguage": "en",
    "sourceSummary": "For the first time, AI will be positioned at the very centre of government, thanks to the launch of the PM’s new AI Taskforce…",
    "summaryOrigin": "feed"
  },
  {
    "id": "ncsc-bilfv7",
    "title": "UK and partners expose Russian state-supported actors for new ‘zero-click’ phishing campaign targeting Western organisations",
    "url": "https://www.ncsc.gov.uk/news/uk-and-partners-expose-russian-state-supported-actors-for-new-zero-click-phishing-campaign",
    "date": "2026-07-23",
    "source": "NCSC",
    "category": "security",
    "region": "uk",
    "sourceLanguage": "en",
    "sourceSummary": "GCHQ’s National Cyber Security Centre and international partners issue warning as ‘LAUNDRY BEAR’ cyber threat group exposed for targeted phishing campaign",
    "summaryOrigin": "feed"
  },
  {
    "id": "nist-10or147",
    "title": "NIST Announces Funding Opportunity for 14 MEP Centers to Advance Small and Medium-Sized U.S. Manufacturers",
    "url": "https://www.nist.gov/news-events/news/2026/07/nist-announces-funding-opportunity-14-mep-centers-advance-small-and-medium",
    "date": "2026-07-22",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "NIST MEP will host an informational webinar on Tuesday, July 28, 2026, at 1 p.m. ET to provide general information about this opportunity and…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nasa-r4z16i",
    "title": "Robotic Servicing Mission Launches with NASA Support",
    "url": "https://www.nasa.gov/technology/robotic-servicing-mission-launches-with-nasa-support/",
    "date": "2026-07-22",
    "source": "NASA",
    "category": "technology",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Following its liftoff from Cape Canaveral on July 21 aboard a SpaceX Falcon 9 rocket, the Mission Robotic Vehicle (MRV) hosting the NASA-supported Robotic…",
    "summaryOrigin": "feed"
  },
  {
    "id": "gov-uk-1laxrdx",
    "title": "Generative AI in animals in science: response from Lord Hanson",
    "url": "https://www.gov.uk/government/publications/generative-ai-in-animals-in-science-response-from-lord-hanson",
    "date": "2026-07-22",
    "source": "GOV.UK",
    "category": "technology",
    "region": "uk",
    "sourceLanguage": "en",
    "sourceSummary": "Lord Hanson has responded to the Animals in Science Committee’s letter on the use of artificial intelligence in animals in science.",
    "summaryOrigin": "feed"
  },
  {
    "id": "nsf-147qwfm",
    "title": "New NSF initiative aims to unlock dataset value for AI-enabled scientific discovery",
    "url": "https://www.nsf.gov/news/new-nsf-initiative-aims-unlock-dataset-value-ai-enabled",
    "date": "2026-07-22",
    "source": "NSF",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The U.S. National Science Foundation announced the NSF Unlocking Dataset Value for AI-Enabled Scientific Discovery program, a new investment to advance scientific community datasets…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nsf-1hn1w5s",
    "title": "NSF announces $83M investment in integrated data systems and services to advance AI-driven science and strengthen U.S. research infrastructure",
    "url": "https://www.nsf.gov/news/nsf-announces-83m-investment-integrated-data-systems",
    "date": "2026-07-22",
    "source": "NSF",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The U.S. National Science Foundation today announced $83 million in awards through the Integrated Data Systems and Services (IDSS) program. The awards will expand…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nsf-1ntiq5x",
    "title": "Statement from NSF Chief of Staff Brian Stone, performing the duties of the NSF director, on advancing the Administration's AI priorities through the Genesis Mission",
    "url": "https://www.nsf.gov/news/statement-nsf-chief-staff-brian-stone-performing-duties-nsf-1",
    "date": "2026-07-22",
    "source": "NSF",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The U.S. National Science Foundation is proud to join the White House Office of Science and Technology Policy, the U.S. Department of Energy and…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nsf-11m8cn3",
    "title": "Podcast: New treatment to fight deadliest cancer",
    "url": "https://www.nsf.gov/news/podcast-new-treatment-fight-deadliest-cancer",
    "date": "2026-07-21",
    "source": "NSF",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "U.S. National Science Foundation-supported professor Neil Forbes discusses how the bacteria salmonella can be modified for treatment against some of the deadliest cancers...",
    "summaryOrigin": "feed"
  },
  {
    "id": "nsf-1lcvfu",
    "title": "Podcast: New security and communications materials",
    "url": "https://www.nsf.gov/news/podcast-new-security-communications-materials",
    "date": "2026-07-15",
    "source": "NSF",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Nicholas Kotov discusses complex materials and the development of new fused-silk materials with applications in security and communications...",
    "summaryOrigin": "feed"
  },
  {
    "id": "nist-1dpewg7",
    "title": "NIST Receives New Patent for Microbe-Killing Water Heater",
    "url": "https://www.nist.gov/news-events/news/2026/07/nist-receives-new-patent-microbe-killing-water-heater",
    "date": "2026-07-14",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Warm water in household pipes can be a breeding ground for harmful bacteria.",
    "summaryOrigin": "feed"
  },
  {
    "id": "nsf-1rmt4dr",
    "title": "NSF awards 12 new Regional Innovation Engines to fuel research, jobs and economic growth nationwide",
    "url": "https://www.nsf.gov/news/nsf-awards-12-new-regional-innovation-engines-fuel-research",
    "date": "2026-07-14",
    "source": "NSF",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The U.S. National Science Foundation announced it awarded the newest NSF Regional Innovation Engines (NSF Engines) awards to 12 U.S. teams across 20 states.…",
    "summaryOrigin": "feed"
  },
  {
    "id": "noaa-3rsp3w",
    "title": "How Removing Lost Crab Traps Is Helping Map the Chesapeake Bay",
    "url": "https://oceanservice.noaa.gov/news/july26/bathymetric-data.html",
    "date": "2026-07-14",
    "source": "NOAA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "NOAA published this official science update under the headline “How Removing Lost Crab Traps Is Helping Map the Chesapeake Bay”. Open the source for…",
    "summaryOrigin": "metadata"
  },
  {
    "id": "ncsc-1dfjuxd",
    "title": "UK and Allies urge critical sectors to improve defences against Russian intelligence targeting",
    "url": "https://www.ncsc.gov.uk/news/uk-and-allies-urge-critical-sectors-to-improve-defences-against-russian-intelligence-targeting",
    "date": "2026-07-13",
    "source": "NCSC",
    "category": "security",
    "region": "uk",
    "sourceLanguage": "en",
    "sourceSummary": "New advisory highlights Russian state cyber actors’ global exploitation of poorly configured routers",
    "summaryOrigin": "feed"
  },
  {
    "id": "nist-18qr5wm",
    "title": "New Fabric Test Material Could Help Strengthen Domestic Supply Chain for Textiles and Clothing",
    "url": "https://www.nist.gov/news-events/news/2026/07/new-fabric-test-material-could-help-strengthen-domestic-supply-chain",
    "date": "2026-07-09",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Researchers estimate that 56% of textiles can be recycled or recovered, but most don’t make it back into the domestic supply chain.",
    "summaryOrigin": "feed"
  },
  {
    "id": "nsf-26d7ia",
    "title": "NSF launches Project Triad to advance quantum technology for real-world applications",
    "url": "https://www.nsf.gov/news/nsf-launches-project-triad-advance-quantum-technology-real",
    "date": "2026-07-07",
    "source": "NSF",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The U.S. National Science Foundation today announced Project Triad, a first-of-its-kind initiative to integrate quantum sensing, quantum networking and quantum computing into a single…",
    "summaryOrigin": "feed"
  },
  {
    "id": "noaa-qufz44",
    "title": "Transforming Chesapeake Bay Water Forecasting",
    "url": "https://oceanservice.noaa.gov/news/july26/transforming-chesapeake.html",
    "date": "2026-07-07",
    "source": "NOAA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "A rocky jetty crosses the frame in shallow Bay waters. A wooden walkway follows the jetty halfway, then turns and continues as an L-shaped…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nist-i5q59n",
    "title": "Arvind Raman Confirmed as the 18th NIST Director",
    "url": "https://www.nist.gov/news-events/news/2026/07/arvind-raman-confirmed-18th-nist-director",
    "date": "2026-07-06",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Raman comes to NIST from Purdue University, where he was the dean of engineering.",
    "summaryOrigin": "feed"
  },
  {
    "id": "nist-rgo50e",
    "title": "NIST Launches Center to Drive the Manufacture of Quantum Technologies",
    "url": "https://www.nist.gov/news-events/news/2026/06/nist-launches-center-drive-manufacture-quantum-technologies",
    "date": "2026-06-29",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "NIST has announced an agreement with SRI International to establish the Quantum Manufacturing Engineering Center (QMEC).",
    "summaryOrigin": "feed"
  },
  {
    "id": "nist-t7cfvj",
    "title": "NIST Releases Technical Findings on What Caused the 2021 Partial Collapse of Champlain Towers South",
    "url": "https://www.nist.gov/news-events/news/2026/06/nist-releases-technical-findings-what-caused-2021-partial-collapse",
    "date": "2026-06-22",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "In an investigation that began just days after the tragedy, the team examined two dozen possible scenarios for where and why the collapse started.",
    "summaryOrigin": "feed"
  },
  {
    "id": "ncsc-hxumow",
    "title": "The AI shift in cyber risk: why leaders must act now",
    "url": "https://www.ncsc.gov.uk/news/the-ai-shift-in-cyber-risk-why-leaders-must-act-now",
    "date": "2026-06-22",
    "source": "NCSC",
    "category": "security",
    "region": "uk",
    "sourceLanguage": "en",
    "sourceSummary": "Five Eyes cyber security agencies urge organisations to act on rapidly transforming cyber risk.",
    "summaryOrigin": "feed"
  },
  {
    "id": "ncsc-b2gryq",
    "title": "Alert: NCSC issues advice following global targeting of Fortinet firewalls and VPN gateways",
    "url": "https://www.ncsc.gov.uk/news/advice-following-global-targeting-of-fortinet-firewalls-and-vpn-gateways",
    "date": "2026-06-18",
    "source": "NCSC",
    "category": "security",
    "region": "uk",
    "sourceLanguage": "en",
    "sourceSummary": "Organisations using Fortinet services are being urged to take action following a campaign affecting firewalls and VPN gateways.",
    "summaryOrigin": "feed"
  },
  {
    "id": "ncsc-1aiavvj",
    "title": "NCSC CEO: Hostile states linked to three-quarters of cyber attacks affecting UK's critical systems",
    "url": "https://www.ncsc.gov.uk/news/ncsc-ceo-hostile-states-linked-to-three-quarters-of-cyber-attacks",
    "date": "2026-06-17",
    "source": "NCSC",
    "category": "security",
    "region": "uk",
    "sourceLanguage": "en",
    "sourceSummary": "Dr Richard Horne highlighted the scale of cyber threats against the UK’s critical infrastructure at RUSI’s Annual Security Lecture.",
    "summaryOrigin": "feed"
  },
  {
    "id": "noaa-5y0cc9",
    "title": "NOAA forecasts an above-average summer 'dead zone' in Gulf of America",
    "url": "https://oceanservice.noaa.gov/news/jun26/summer-dead-zone.html",
    "date": "2026-06-16",
    "source": "NOAA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Low-oxygen conditions are expected to be larger than average, impacting a 7,027 square-mile area.",
    "summaryOrigin": "feed"
  },
  {
    "id": "nist-7oz3o8",
    "title": "NIST Expands Its Library of ‘Chemical Fingerprints’ to Identify Unknown Substances",
    "url": "https://www.nist.gov/news-events/news/2026/06/nist-expands-its-library-chemical-fingerprints-identify-unknown-substances",
    "date": "2026-06-09",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Researchers and manufacturers rely on the library to identify unknown compounds in food, drugs, cosmetics, the environment, body fluids, forensic evidence and even space…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nist-vhemnc",
    "title": "NIST Mathematical Proof Supports Transition to a Continuous-Monitor-and-Update Security Model for AI Systems",
    "url": "https://www.nist.gov/news-events/news/2026/06/nist-mathematical-proof-supports-transition-continuous-monitor-and-update",
    "date": "2026-06-09",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The proof extends to AI the logic used by famed mathematician Kurt Gödel, whose incompleteness theorems have had a profound effect on math for…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nist-1jyv2x0",
    "title": "New AI Model Shows How to Evacuate for Fires One Safe Step at a Time",
    "url": "https://www.nist.gov/news-events/news/2026/06/new-ai-model-shows-how-evacuate-fires-one-safe-step-time",
    "date": "2026-06-04",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "A NIST-led team has created a new AI model that can identify safe evacuation routes in a single-story floor plan during a fire, with…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nist-j02ahz",
    "title": "NIST Researchers Discover a New Way to Whisk Alloys Together With Lasers",
    "url": "https://www.nist.gov/news-events/news/2026/06/nist-researchers-discover-new-way-whisk-alloys-together-lasers",
    "date": "2026-06-04",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "NIST also improved how X-rays are used to study the atomic structure of metals in real time during 3D printing, allowing researchers to observe…",
    "summaryOrigin": "feed"
  },
  {
    "id": "noaa-k98w6m",
    "title": "Harmful Algal Bloom Monitoring Expands to New Coastal Northeast and Great Lakes Regions",
    "url": "https://oceanservice.noaa.gov/news/jun26/harmful-algal-bloom-monitoring.html",
    "date": "2026-06-01",
    "source": "NOAA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The new products for the Northeast coast and Great Lakes strengthen NOAA’s ability to deliver timely, science-based tools for state, local, and regional partners.",
    "summaryOrigin": "feed"
  },
  {
    "id": "nist-1ghsuvd",
    "title": "NIST Expands AI Consortium’s Scope, Calls for New Members",
    "url": "https://www.nist.gov/news-events/news/2026/05/nist-expands-ai-consortiums-scope-calls-new-members",
    "date": "2026-05-29",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The consortium will focus on AI innovation and adoption, with six task groups concentrating on different aspects of AI measurement science and evaluation.",
    "summaryOrigin": "feed"
  },
  {
    "id": "noaa-21v7if",
    "title": "El Niño and high tide flooding, a possible double whammy for some coastal communities in 2026",
    "url": "https://oceanservice.noaa.gov/news/may26/el-nino-flooding.html",
    "date": "2026-05-15",
    "source": "NOAA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The predicted El Niño could mean more high tide flooding for many locations.",
    "summaryOrigin": "feed"
  },
  {
    "id": "noaa-1c0l41i",
    "title": "NOAA releases new National Coral Reef Resilience Strategy",
    "url": "https://oceanservice.noaa.gov/news/may26/coral-reef-resilience.html",
    "date": "2026-05-06",
    "source": "NOAA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "NOAA published this official science update under the headline “NOAA releases new National Coral Reef Resilience Strategy”. Open the source for full context.",
    "summaryOrigin": "metadata"
  },
  {
    "id": "noaa-1p55gvv",
    "title": "NOAA Ship Thomas Jefferson returns to the Great Lakes",
    "url": "https://oceanservice.noaa.gov/news/may26/noaaship-greatlakes-survey-2026.html",
    "date": "2026-05-01",
    "source": "NOAA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Marine sectors show increases in jobs and wages",
    "summaryOrigin": "feed"
  },
  {
    "id": "ncsc-mc5szq",
    "title": "Executive Summary: Defending against China-nexus covert networks of compromised devices",
    "url": "https://www.ncsc.gov.uk/news/executive-summary-defending-against-china-nexus-covert-networks-of-compromised-devices",
    "date": "2026-04-23",
    "source": "NCSC",
    "category": "security",
    "region": "uk",
    "sourceLanguage": "en",
    "sourceSummary": "Organisations should map and baseline their edge device traffic, especially VPN and remote access connections, and adopt dynamic threat feed filtering that includes known…",
    "summaryOrigin": "feed"
  },
  {
    "id": "ncsc-ucf6a4",
    "title": "Defending against China-nexus covert networks of compromised devices",
    "url": "https://www.ncsc.gov.uk/news/defending-against-china-nexus-covert-networks-of-compromised-devices",
    "date": "2026-04-23",
    "source": "NCSC",
    "category": "security",
    "region": "uk",
    "sourceLanguage": "en",
    "sourceSummary": "Explaining the widespread shift in tactics, techniques and procedures (TTPs) towards networks of compromised infrastructure, and how to defend against it",
    "summaryOrigin": "feed"
  },
  {
    "id": "ncsc-foh8hf",
    "title": "NCSC: Leave passwords in the past - passkeys are the future",
    "url": "https://www.ncsc.gov.uk/news/ncsc-leave-passwords-in-the-past-passkeys-are-the-future",
    "date": "2026-04-23",
    "source": "NCSC",
    "category": "security",
    "region": "uk",
    "sourceLanguage": "en",
    "sourceSummary": "Passkeys are the more secure and user-friendly login method and should be the default authentication option for consumers.",
    "summaryOrigin": "feed"
  },
  {
    "id": "ncsc-1kupztg",
    "title": "International cyber agencies share fresh advice to defend against China-linked covert networks",
    "url": "https://www.ncsc.gov.uk/news/international-cyber-agencies-fresh-advice-defend-against-china-linked-covert-networks",
    "date": "2026-04-23",
    "source": "NCSC",
    "category": "security",
    "region": "uk",
    "sourceLanguage": "en",
    "sourceSummary": "New advisory highlights how to defend against attacker tactics believed to be used by China-linked actors to hide malicious cyber activity.",
    "summaryOrigin": "feed"
  }
];
