export type NewsItem = { id: string; title: string; url: string; date: string; source: "NASA" | "NIST" | "CISA" | "GOV.UK"; category: "science" | "technology" | "security" | "standards"; region: "global" | "uk"; sourceLanguage: "en"; sourceSummary?: string };

// Generated at build time from official, allowlisted RSS endpoints. Summaries are included only where the source's reuse terms permit it.
export const newsGeneratedAt = "2026-07-26T08:45:37.731Z";
export const newsItems: NewsItem[] = [
  {
    "id": "nasa-1l8pc5u",
    "title": "NASA’s ESCAPADE Snaps Family Portrait of Earth, Moon",
    "url": "https://science.nasa.gov/image-article/centers-and-facilities/goddard/nasas-escapade-snaps-family-portrait-of-earth-moon/",
    "date": "2026-07-24",
    "source": "NASA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "On July 3, one of NASA’s two Mars-destined ESCAPADE (Escape and Plasma Acceleration and Dynamics Explorers) spacecraft captured photos of Earth and the Moon in visible and thermal infrared light. At the time, the spacecraft was 363,250 miles (584,600 kilometers) from Earth and 115,600 miles (186,100 kilometers) from the Moon, making the Moon appear relatively […]"
  },
  {
    "id": "nasa-1nf052z",
    "title": "New Crew Members Welcomed to International Space Station",
    "url": "https://www.nasa.gov/image-article/new-crew-members-welcomed-to-international-space-station/",
    "date": "2026-07-24",
    "source": "NASA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "From left, Expedition 74 flight engineers Anna Kikina and Pyotr Dubrov of Roscosmos, and Anil Menon of NASA pose for a July 18, 2026, photo while holding a cake celebrating their recent arrival aboard the International Space Station. The trio arrived at the space station on July 14, 2026, after launching from the Baikonur Cosmodrome […]"
  },
  {
    "id": "nasa-a2n7qp",
    "title": "NASA Announces New Spacecraft Technology Demonstration Mission at Moon",
    "url": "https://www.nasa.gov/directorates/armd/nasa-announces-new-spacecraft-technology-demonstration-mission-at-moon/",
    "date": "2026-07-24",
    "source": "NASA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "NASA is working with industry to advance the next phase of cislunar infrastructure for the agency’s Artemis program and Moon Base, including orbital assets and demonstrations. Under a contract awarded to Advanced Space, the agency’s CAPSTONE 02 mission will demonstrate rendezvous and proximity operations, autonomous navigation, and cislunar communication capabilities while continuing to characterize the […]"
  },
  {
    "id": "nasa-oq1wb8",
    "title": "NASA to Support Blue Origin New Glenn Rocket Testing, Advance Artemis",
    "url": "https://www.nasa.gov/news-release/nasa-to-support-blue-origin-new-glenn-rocket-testing-advance-artemis/",
    "date": "2026-07-24",
    "source": "NASA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "NASA and Blue Origin announced Friday they recently agreed to conduct second stage hot fire testing for the company’s New Glenn rocket on the B-2 test stand at the agency’s Stennis Space Center near Bay St. Louis, Mississippi. The annex to a reimbursable Space Act Agreement signed earlier this month highlights NASA’s commitment to working […]"
  },
  {
    "id": "nasa-11zri2a",
    "title": "Hubble Spies One-Sided Spiral",
    "url": "https://science.nasa.gov/missions/hubble/hubble-spies-one-sided-spiral/",
    "date": "2026-07-24",
    "source": "NASA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "This Hubble image features spiral galaxy NGC 4654, located 72 million light-years away in the constellation Virgo (the Maiden)."
  },
  {
    "id": "nasa-1yegygr",
    "title": "A Million-Panel Project",
    "url": "https://science.nasa.gov/earth/earth-observatory/a-million-panel-project/",
    "date": "2026-07-24",
    "source": "NASA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Utah’s new solar power and battery storage facility is among the largest in the region."
  },
  {
    "id": "nasa-1hmw3ow",
    "title": "Curiosity Blog, Sols 4954–4960: Celebrating Our Rover Engineers Past and Present",
    "url": "https://science.nasa.gov/blog/curiosity-blog-sols-4954-4960-celebrating-our-rover-engineers-past-and-present/",
    "date": "2026-07-24",
    "source": "NASA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Written by Lucy Thompson, Senior Research Scientist, University of New Brunswick, Canada Earth planning date: Friday, July 27, 2026 As an APXS uplink lead and strategic planner, I have the privilege of working with the rover engineers most days that I am on operations. The APXS instrument measures the chemistry of rocks, unconsolidated materials and […]"
  },
  {
    "id": "gov-uk-o6aft2",
    "title": "AI to power change at the heart of government as Lord Vallance appointed chair of new PM AI Taskforce",
    "url": "https://www.gov.uk/government/news/ai-to-power-change-at-the-heart-of-government-as-lord-vallance-appointed-chair-of-new-pm-ai-taskforce",
    "date": "2026-07-24",
    "source": "GOV.UK",
    "category": "technology",
    "region": "uk",
    "sourceLanguage": "en",
    "sourceSummary": "For the first time, AI will be positioned at the very centre of government, thanks to the launch of the PM’s new AI Taskforce which will be chaired by Lord Vallance."
  },
  {
    "id": "nasa-ze0ads",
    "title": "Look for NASA+ Now Streaming on Amazon Fire TV",
    "url": "https://www.nasa.gov/news-release/look-for-nasa-now-streaming-on-amazon-fire-tv/",
    "date": "2026-07-23",
    "source": "NASA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Continuing agency efforts to bring space closer to home, NASA+ is heading to more streaming platforms. On Thursday, NASA announced its programming is on Fire TV Channels. Fire TV customers can easily access this content by asking Alexa+ on compatible devices. Future programming on Fire TV may include science mission launches, a test flight for […]"
  },
  {
    "id": "nasa-agho3g",
    "title": "Crews Move Artemis IV Liquid Hydrogen Tank",
    "url": "https://www.nasa.gov/image-article/crews-move-artemis-iv-liquid-hydrogen-tank/",
    "date": "2026-07-23",
    "source": "NASA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Crews at NASA’s Michoud Assembly Facility in New Orleans transport the 130-foot-tall Artemis IV liquid hydrogen tank out of a production cell inside the main factory building into a detached test building on a separate portion of the 829-acre site on May 15, 2026. The liquid hydrogen tank will form part of the core stage for […]"
  },
  {
    "id": "nasa-1gdrrzj",
    "title": "NASA’s MAVEN Illuminates New Understanding of Auroras at Mars",
    "url": "https://science.nasa.gov/missions/maven/nasas-maven-illuminates-new-understanding-of-auroras-at-mars/",
    "date": "2026-07-23",
    "source": "NASA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "NASA MAVEN (Mars Atmosphere and Volatile Evolution) mission scientists have uncovered a key puzzle piece in understanding certain types of auroras on Mars, finding that they form in a similar way to Earth-based auroras. Results published Thursday in Nature Communications show the same mechanism that circulates and catapults charged particles into Earth’s atmosphere is happening at […]"
  },
  {
    "id": "nist-10or147",
    "title": "NIST Announces Funding Opportunity for 14 MEP Centers to Advance Small and Medium-Sized U.S. Manufacturers",
    "url": "https://www.nist.gov/news-events/news/2026/07/nist-announces-funding-opportunity-14-mep-centers-advance-small-and-medium",
    "date": "2026-07-22",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "NIST MEP will host an informational webinar on Tuesday, July 28, 2026, at 1 p.m. ET to provide general information about this opportunity and guidance on preparing applications."
  },
  {
    "id": "nasa-r4z16i",
    "title": "Robotic Servicing Mission Launches with NASA Support",
    "url": "https://www.nasa.gov/technology/robotic-servicing-mission-launches-with-nasa-support/",
    "date": "2026-07-22",
    "source": "NASA",
    "category": "technology",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Following its liftoff from Cape Canaveral on July 21 aboard a SpaceX Falcon 9 rocket, the Mission Robotic Vehicle (MRV) hosting the NASA-supported Robotic Servicing of Geosynchronous Satellites (RSGS) payload is now en route to geosynchronous Earth orbit, where it will use its advanced robotics to service spacecraft. RSGS leverages in-space robotics expertise from NASA, […]"
  },
  {
    "id": "gov-uk-1laxrdx",
    "title": "Generative AI in animals in science: response from Lord Hanson",
    "url": "https://www.gov.uk/government/publications/generative-ai-in-animals-in-science-response-from-lord-hanson",
    "date": "2026-07-22",
    "source": "GOV.UK",
    "category": "technology",
    "region": "uk",
    "sourceLanguage": "en",
    "sourceSummary": "Lord Hanson has responded to the Animals in Science Committee’s letter on the use of artificial intelligence in animals in science."
  },
  {
    "id": "gov-uk-1lr9ig5",
    "title": "£708 million to accelerate UK next-generation air combat technology",
    "url": "https://www.gov.uk/government/news/708-million-to-accelerate-uk-next-generation-air-combat-technology",
    "date": "2026-07-22",
    "source": "GOV.UK",
    "category": "technology",
    "region": "uk",
    "sourceLanguage": "en",
    "sourceSummary": "Thousands of British workers will accelerate development of advanced technologies for use by the Royal Air Force, following a £708 million investment announced today."
  },
  {
    "id": "nasa-1834srb",
    "title": "Coilable Stacked Solar Sails for Very High delta-V Missions",
    "url": "https://www.nasa.gov/directorates/stmd/niac/niac-studies/coilable-stacked-solar-sails-for-very-high-delta-v-missions/",
    "date": "2026-07-21",
    "source": "NASA",
    "category": "technology",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Artur Davoyan University of California, Los Angeles The goal of the proposed program is to enable the next generation of solar sails featuring very high characteristic acceleration–potentially up to 2 mm/s²–and large effective areas exceeding 10,000 m², to support future ultra–high delta-V missions. These advanced solar sails would significantly transform space exploration and utilization, making […]"
  },
  {
    "id": "nasa-7a76r5",
    "title": "A New Compact Instrument Enables High-Fidelity Measurements of Energetic Particles on CubeSats",
    "url": "https://science.nasa.gov/science-research/science-enabling-technology/technology-highlights/a-new-compact-instrument-enables-high-fidelity-measurements-of-energetic-particles-on-cubesats/",
    "date": "2026-07-21",
    "source": "NASA",
    "category": "technology",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "A team of NASA-sponsored scientists and engineers has developed a novel approach to observing high-energy particles in the near-Earth space environment, incorporating miniaturized sensors into a compact, multi-view particle detection instrument unlike any before it. Built for NASA’s Relativistic Electron Atmospheric Loss (REAL) CubeSat mission, the innovative instrument (also called REAL) enables more complete measurements […]"
  },
  {
    "id": "nasa-1sh84tu",
    "title": "Ontario Wildfire Smoke Moves East",
    "url": "https://science.nasa.gov/earth/earth-observatory/ontario-wildfire-smoke-moves-east/",
    "date": "2026-07-16",
    "source": "NASA",
    "category": "technology",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Canadian wildfires sent plumes of smoke streaming over Ontario, Quebec, and parts of the U.S. Midwest and Northeast."
  },
  {
    "id": "nist-1dpewg7",
    "title": "NIST Receives New Patent for Microbe-Killing Water Heater",
    "url": "https://www.nist.gov/news-events/news/2026/07/nist-receives-new-patent-microbe-killing-water-heater",
    "date": "2026-07-14",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Warm water in household pipes can be a breeding ground for harmful bacteria."
  },
  {
    "id": "nist-18qr5wm",
    "title": "New Fabric Test Material Could Help Strengthen Domestic Supply Chain for Textiles and Clothing",
    "url": "https://www.nist.gov/news-events/news/2026/07/new-fabric-test-material-could-help-strengthen-domestic-supply-chain",
    "date": "2026-07-09",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Researchers estimate that 56% of textiles can be recycled or recovered, but most don’t make it back into the domestic supply chain."
  },
  {
    "id": "nasa-1lkrs5g",
    "title": "Super Typhoon Bavi",
    "url": "https://science.nasa.gov/earth/earth-observatory/super-typhoon-bavi/",
    "date": "2026-07-09",
    "source": "NASA",
    "category": "technology",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The third category 5 tropical cyclone of 2026 crossed the U.S. Northern Mariana Islands and Guam before continuing toward Asia."
  },
  {
    "id": "nasa-1lb1308",
    "title": "NASA’s New Horizons Spacecraft Wakes from Hibernation in Good Health",
    "url": "https://science.nasa.gov/missions/new-horizons/nasas-new-horizons-spacecraft-wakes-from-hibernation-in-good-health/",
    "date": "2026-07-07",
    "source": "NASA",
    "category": "technology",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Following its longest hibernation period ever of nearly a year, NASA’s New Horizons spacecraft has emerged in good health and is ready to begin transmitting science data gathered in the distant Kuiper Belt far beyond Pluto. On June 23, flight controllers at the Johns Hopkins Applied Physics Laboratory (APL) in Laurel, Maryland, confirmed New Horizons, […]"
  },
  {
    "id": "nist-i5q59n",
    "title": "Arvind Raman Confirmed as the 18th NIST Director",
    "url": "https://www.nist.gov/news-events/news/2026/07/arvind-raman-confirmed-18th-nist-director",
    "date": "2026-07-06",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Raman comes to NIST from Purdue University, where he was the dean of engineering."
  },
  {
    "id": "nasa-18g6yer",
    "title": "NASA’s CAPSTONE Completes Extended Mission Testing Lunar Technologies",
    "url": "https://www.nasa.gov/technology/space-comms/nasas-capstone-completes-extended-mission-testing-lunar-technologies/",
    "date": "2026-07-06",
    "source": "NASA",
    "category": "technology",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "As NASA prepares for a sustained human presence on the Moon, missions will increasingly require spacecraft that can navigate and communicate without a direct connection to Earth. NASA’s Cislunar Autonomous Positioning System Technology Operations and Navigation Experiment, or CAPSTONE, validated and advanced these capabilities. Designed to test and validate technologies in lunar orbit, CAPSTONE launched […]"
  },
  {
    "id": "nist-rgo50e",
    "title": "NIST Launches Center to Drive the Manufacture of Quantum Technologies",
    "url": "https://www.nist.gov/news-events/news/2026/06/nist-launches-center-drive-manufacture-quantum-technologies",
    "date": "2026-06-29",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "NIST has announced an agreement with SRI International to establish the Quantum Manufacturing Engineering Center (QMEC)."
  },
  {
    "id": "nasa-1378clb",
    "title": "NextSTEP-3 A: Lunar Enabling Technology",
    "url": "https://www.nasa.gov/directorates/stmd/nextstep-3-a-lunar-enabling-technology/",
    "date": "2026-06-29",
    "source": "NASA",
    "category": "technology",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Solicitation Number: 80GRC026R0008 May 19, 2026 – Synopsis issued June 29, 2026 – Draft BAA and Appendix A Issued | Web Article NASA issued a draft Broad Agency Announcement under NextSTEP‑3, Appendix A, on June 29, 2026, to advance concepts that accelerate the technological readiness of critical systems for lunar surface and cislunar architecture. This solicitation seeks to close key technology gaps and […]"
  },
  {
    "id": "nasa-2w6ajn",
    "title": "Partners, NASA Ready for June Launch of Swift Boost Mission",
    "url": "https://science.nasa.gov/missions/swift/swift-boost-mission/partners-nasa-ready-for-june-launch-of-swift-boost-mission/",
    "date": "2026-06-26",
    "source": "NASA",
    "category": "technology",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "A mission to raise the orbit of NASA’s Swift observatory is poised for launch June 30."
  },
  {
    "id": "nist-t7cfvj",
    "title": "NIST Releases Technical Findings on What Caused the 2021 Partial Collapse of Champlain Towers South",
    "url": "https://www.nist.gov/news-events/news/2026/06/nist-releases-technical-findings-what-caused-2021-partial-collapse",
    "date": "2026-06-22",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "In an investigation that began just days after the tragedy, the team examined two dozen possible scenarios for where and why the collapse started."
  },
  {
    "id": "nist-7oz3o8",
    "title": "NIST Expands Its Library of ‘Chemical Fingerprints’ to Identify Unknown Substances",
    "url": "https://www.nist.gov/news-events/news/2026/06/nist-expands-its-library-chemical-fingerprints-identify-unknown-substances",
    "date": "2026-06-09",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Researchers and manufacturers rely on the library to identify unknown compounds in food, drugs, cosmetics, the environment, body fluids, forensic evidence and even space rocks."
  },
  {
    "id": "nist-vhemnc",
    "title": "NIST Mathematical Proof Supports Transition to a Continuous-Monitor-and-Update Security Model for AI Systems",
    "url": "https://www.nist.gov/news-events/news/2026/06/nist-mathematical-proof-supports-transition-continuous-monitor-and-update",
    "date": "2026-06-09",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The proof extends to AI the logic used by famed mathematician Kurt Gödel, whose incompleteness theorems have had a profound effect on math for nearly a century."
  },
  {
    "id": "nist-1jyv2x0",
    "title": "New AI Model Shows How to Evacuate for Fires One Safe Step at a Time",
    "url": "https://www.nist.gov/news-events/news/2026/06/new-ai-model-shows-how-evacuate-fires-one-safe-step-time",
    "date": "2026-06-04",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "A NIST-led team has created a new AI model that can identify safe evacuation routes in a single-story floor plan during a fire, with a multilevel version in the works."
  },
  {
    "id": "nist-j02ahz",
    "title": "NIST Researchers Discover a New Way to Whisk Alloys Together With Lasers",
    "url": "https://www.nist.gov/news-events/news/2026/06/nist-researchers-discover-new-way-whisk-alloys-together-lasers",
    "date": "2026-06-04",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "NIST also improved how X-rays are used to study the atomic structure of metals in real time during 3D printing, allowing researchers to observe how materials change under extreme conditions."
  },
  {
    "id": "nist-1ghsuvd",
    "title": "NIST Expands AI Consortium’s Scope, Calls for New Members",
    "url": "https://www.nist.gov/news-events/news/2026/05/nist-expands-ai-consortiums-scope-calls-new-members",
    "date": "2026-05-29",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The consortium will focus on AI innovation and adoption, with six task groups concentrating on different aspects of AI measurement science and evaluation."
  },
  {
    "id": "nist-172v4l1",
    "title": "Shooting for the Moon: Ultrastable Lasers in Dark Craters Could Enable Lunar Navigation, Precision Timekeeping, New Science",
    "url": "https://www.nist.gov/news-events/news/2026/05/shooting-moon-ultrastable-lasers-dark-craters-could-enable-lunar-navigation",
    "date": "2026-05-18",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Lunar craters in permanent shadow could be ideal locations for building the most stable optical lasers ever made."
  },
  {
    "id": "nist-1wwu3sn",
    "title": "Wear and Tear Changes Measurable PFAS Levels in Firefighter Hoods, Gloves and Wildland Gear",
    "url": "https://www.nist.gov/news-events/news/2026/05/wear-and-tear-changes-measurable-pfas-levels-firefighter-hoods-gloves-and",
    "date": "2026-05-13",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "In the fourth of an ongoing series of reports, NIST shows that wear and tear increased the levels of PFAS found in hoods and gloves."
  },
  {
    "id": "nist-1wetxzt",
    "title": "NIST Weighs In on the Mystery of the Gravitational Constant",
    "url": "https://www.nist.gov/news-events/news/2026/04/nist-weighs-mystery-gravitational-constant",
    "date": "2026-04-16",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "A NIST researcher has unveiled the results of a 10-year quest to measure the constant."
  },
  {
    "id": "nist-1qhwjkg",
    "title": "Any Color You Like: NIST Scientists Create ‘Any Wavelength’ Lasers in Tiny Circuits for Light",
    "url": "https://www.nist.gov/news-events/news/2026/04/any-color-you-nist-scientists-create-any-wavelength-lasers-tiny-circuits",
    "date": "2026-04-15",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "NIST scientists and collaborators have pioneered a way to make integrated circuits for light by depositing complex patterns of specialized materials onto silicon wafers."
  },
  {
    "id": "nist-4zkurq",
    "title": "NIST Researchers Develop Photonic Chip Packaging That Can Withstand Extreme Environments",
    "url": "https://www.nist.gov/news-events/news/2026/03/nist-researchers-develop-photonic-chip-packaging-can-withstand-extreme",
    "date": "2026-03-30",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The advance could allow these technologies to operate in deep-space probes, inside nuclear reactors, in ultrahigh vacuum systems, and at temperatures both near absolute zero and in scorchingly hot industrial settings."
  },
  {
    "id": "nist-3x0gxe",
    "title": "NIST Helps Fingerprint Examiners With New Data and Software Release",
    "url": "https://www.nist.gov/news-events/news/2026/03/nist-helps-fingerprint-examiners-new-data-and-software-release",
    "date": "2026-03-23",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The new tools are an annotated collection of 10,000 fingerprints and a software program that can sort fingerprints according to their quality."
  },
  {
    "id": "nist-1sj7nxv",
    "title": "NIST Submits Annual Report to Congress Summarizing FY 2025 Progress on National Construction Safety Team Investigations",
    "url": "https://www.nist.gov/news-events/news/2026/03/nist-submits-annual-report-congress-summarizing-fy-2025-progress-national",
    "date": "2026-03-19",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The report includes an overview of work completed on the Champlain Towers South investigation."
  },
  {
    "id": "nist-130sgyf",
    "title": "2 Health Care Organizations Will Receive 2025 Baldrige National Quality Awards",
    "url": "https://www.nist.gov/news-events/news/2026/02/2-health-care-organizations-will-receive-2025-baldrige-national-quality",
    "date": "2026-02-19",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The award highlights organizations that focus on resilience."
  },
  {
    "id": "nist-xx2ey2",
    "title": "Announcing the &quot;AI Agent Standards Initiative&quot; for Interoperable and Secure Innovation",
    "url": "https://www.nist.gov/news-events/news/2026/02/announcing-ai-agent-standards-initiative-interoperable-and-secure",
    "date": "2026-02-17",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The Initiative will ensure that the next generation of AI is widely adopted with confidence, can function securely on behalf of its users, and can interoperate smoothly across the digital ecosystem."
  }
];
