export type NewsItem = { id: string; title: string; url: string; date: string; source: "NASA" | "NIST" | "CISA" | "GOV.UK" | "NSF" | "NIH" | "ESA" | "NCSC" | "NOAA"; category: "science" | "technology" | "security" | "standards"; region: "global" | "uk"; sourceLanguage: "en"; sourceSummary: string; summaryOrigin: "feed" | "metadata" };

// Generated at build time from official, allowlisted RSS endpoints. Feed descriptions are attribution-linked and intentionally limited to a short excerpt.
export const newsGeneratedAt = "2026-09-04T19:09:11.455Z";
export const newsItems: NewsItem[] = [
  {
    "id": "nasa-gqtpc9",
    "title": "NASA Hosts Virtual Artemis Webinar for Blind, Low-Vision Community",
    "url": "https://www.nasa.gov/general/nasa-hosts-virtual-artemis-webinar-for-blind-low-vision-community/",
    "date": "2026-09-04",
    "source": "NASA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "NASA will host a virtual webinar at 2 p.m. EDT on Friday, Oct. 2, titled “The RS-25 Engine and the Future of Artemis Missions:…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nasa-p3doc1",
    "title": "Lunar Occultation of Venus",
    "url": "https://www.nasa.gov/image-article/lunar-occultation-of-venus/",
    "date": "2026-09-04",
    "source": "NASA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "On Wednesday, June 17, skywatchers across the United States—and parts of Canada—enjoyed a rare event: a daytime lunar occultation of Venus. A lunar occultation…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nasa-1vr1b03",
    "title": "APOD: 2026 September 4 – Na Uhane Mahoe Huki Pu i ke Ola",
    "url": "https://science.nasa.gov/image-article/apod-2026-september-4-na-uhane-mahoe-huki-pu-i-ke-ola/",
    "date": "2026-09-04",
    "source": "NASA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "NASA published this official science update under the headline “APOD: 2026 September 4 – Na Uhane Mahoe Huki Pu i ke Ola”. Open the…",
    "summaryOrigin": "metadata"
  },
  {
    "id": "nasa-1ibj3hw",
    "title": "A Trio of Tropical Cyclones in the Pacific",
    "url": "https://science.nasa.gov/earth/earth-observatory/a-trio-of-tropical-cyclones-in-the-pacific/",
    "date": "2026-09-04",
    "source": "NASA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The Pacific was buzzing with storms while the Atlantic was notably quiet.",
    "summaryOrigin": "feed"
  },
  {
    "id": "esa-1cf7kiu",
    "title": "Week in images: 31 Aug - 04 Sep 2026",
    "url": "https://www.esa.int/About_Us/Week_in_images/Week_in_images_31_Aug_-_04_Sep_2026",
    "date": "2026-09-04",
    "source": "ESA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Week in images: 31 Aug - 04 Sep 2026 Discover our week through the lens",
    "summaryOrigin": "feed"
  },
  {
    "id": "esa-16xbhrr",
    "title": "How Sentinel-3 tracks climate change",
    "url": "https://www.esa.int/Applications/Observing_the_Earth/Copernicus/Sentinel-3/How_Sentinel-3_tracks_climate_change",
    "date": "2026-09-04",
    "source": "ESA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Copernicus Sentinel-3 is one of the most diverse missions for measuring and monitoring Earth’s climate systems. It captures a breadth of data about the…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nasa-17a7qa",
    "title": "NASA to Cover Progress 96 Spacecraft Launch, Docking",
    "url": "https://www.nasa.gov/news-release/nasa-to-cover-progress-96-spacecraft-launch-docking/",
    "date": "2026-09-03",
    "source": "NASA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "NASA will provide live coverage of the launch and docking of a Roscosmos cargo spacecraft carrying about three tons of food, fuel, and supplies…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nasa-1y5s326",
    "title": "Curiosity Blog, Sols 4988-4994: More New Tricks for an Old Dog",
    "url": "https://science.nasa.gov/blog/curiosity-blog-sols-4988-4994-more-new-tricks-for-an-old-dog/",
    "date": "2026-09-03",
    "source": "NASA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Written by Michelle Minitti, MAHLI Deputy Principal Investigator Earth planning date: Friday, Aug. 21, 2026 After Curiosity’s 14 years on the surface, Mars continues…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nasa-rt0fmo",
    "title": "Igniting Roman’s Journey",
    "url": "https://www.nasa.gov/image-article/igniting-romans-journey/",
    "date": "2026-09-03",
    "source": "NASA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Now on a three-month, million-mile journey to its final orbit, NASA’s Nancy Grace Roman Space Telescope will soon reveal the universe’s darkest secrets. The…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nasa-1ucq6sp",
    "title": "NASA’s Hubble Spies Superbubble Scene",
    "url": "https://science.nasa.gov/missions/hubble/nasas-hubble-spies-superbubble-scene/",
    "date": "2026-09-03",
    "source": "NASA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "This Hubble Space Telescope image features a sprawling cosmic vista called N44.",
    "summaryOrigin": "feed"
  },
  {
    "id": "nasa-7pz7fl",
    "title": "APOD: 2026 September 3 – The Eclipse and the Stork",
    "url": "https://science.nasa.gov/image-article/apod-2026-september-3-the-eclipse-and-the-stork/",
    "date": "2026-09-03",
    "source": "NASA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "NASA published this official science update under the headline “APOD: 2026 September 3 – The Eclipse and the Stork”. Open the source for full…",
    "summaryOrigin": "metadata"
  },
  {
    "id": "nasa-vitfsk",
    "title": "Peatland Fires Darken Skies in Indonesia",
    "url": "https://science.nasa.gov/missions/aqua/peatland-fires-darken-skies-in-indonesia/",
    "date": "2026-09-03",
    "source": "NASA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "With Indonesia gripped by drought, fires are smoldering on the surface and underground.",
    "summaryOrigin": "feed"
  },
  {
    "id": "gov-uk-izqyqh",
    "title": "AI sleep data could provide one-week early warning of flu and COVID-19",
    "url": "https://www.gov.uk/government/news/ai-sleep-data-could-provide-one-week-early-warning-of-flu-and-covid-19",
    "date": "2026-09-03",
    "source": "GOV.UK",
    "category": "technology",
    "region": "uk",
    "sourceLanguage": "en",
    "sourceSummary": "UKHSA study finds sleep app cough data can detect respiratory illness and signal outbreaks early.",
    "summaryOrigin": "feed"
  },
  {
    "id": "esa-ltqtuu",
    "title": "BepiColombo’s Mercury arrival begins - full replay",
    "url": "https://www.esa.int/ESA_Multimedia/Videos/2026/09/BepiColombo_s_Mercury_arrival_begins_-_full_replay",
    "date": "2026-09-03",
    "source": "ESA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Video: 02:31:10 Watch the replay of the livestream originally broadcast on 3 September as ESA/JAXA's BepiColombo mission took the first critical step towards arriving…",
    "summaryOrigin": "feed"
  },
  {
    "id": "esa-p3n29f",
    "title": "Latest updates: BepiColombo's arrival at Mercury",
    "url": "https://www.esa.int/Science_Exploration/Space_Science/BepiColombo/Latest_updates_BepiColombo_s_arrival_at_Mercury",
    "date": "2026-09-03",
    "source": "ESA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "After eight years of travelling through the inner Solar System, BepiColombo is arriving at Mercury. This page will show the latest updates throughout the…",
    "summaryOrigin": "feed"
  },
  {
    "id": "esa-12lxm0w",
    "title": "FLEX and Sentinel-3C sealed within Vega-C fairing",
    "url": "https://www.esa.int/Applications/Observing_the_Earth/FLEX_and_Sentinel-3C_sealed_within_Vega-C_fairing",
    "date": "2026-09-02",
    "source": "ESA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "At Europe’s Spaceport in French Guiana, preparations for one of the year’s most anticipated Earth-observation launches are entering their final stages. FLEX and Copernicus…",
    "summaryOrigin": "feed"
  },
  {
    "id": "esa-1h1z0hj",
    "title": "Third spacewalk completed for Sophie Adenot",
    "url": "https://www.esa.int/Science_Exploration/Human_and_Robotic_Exploration/epsilon/Third_spacewalk_completed_for_Sophie_Adenot",
    "date": "2026-09-02",
    "source": "ESA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "ESA astronaut Sophie Adenot and NASA astronaut Jessica Meir successfully completed US EVA-99 at 21:29 CEST on Tuesday 1 September. It was Sophie’s third…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nasa-irz0ej",
    "title": "NASA Selects Blue Origin as Mars Telecommunications Network Provider",
    "url": "https://www.nasa.gov/news-release/nasa-selects-blue-origin-as-mars-telecommunications-network-provider/",
    "date": "2026-09-01",
    "source": "NASA",
    "category": "technology",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "NASA awarded Blue Origin a contract Tuesday to develop the agency’s Mars Telecommunications Network, a next-generation communications system that will enable reliable, high-bandwidth communications…",
    "summaryOrigin": "feed"
  },
  {
    "id": "gov-uk-1n5sylw",
    "title": "£100 million competition to back British AI companies to fix public services",
    "url": "https://www.gov.uk/government/news/100-million-competition-to-back-british-ai-companies-to-fix-public-services",
    "date": "2026-08-31",
    "source": "GOV.UK",
    "category": "technology",
    "region": "uk",
    "sourceLanguage": "en",
    "sourceSummary": "£100 million fund competition will help promising British AI start-ups start in the UK and tackle some of society&#39;s biggest challenges.",
    "summaryOrigin": "feed"
  },
  {
    "id": "nsf-zpe5mb",
    "title": "Podcast: Lasers and materials of the future",
    "url": "https://www.nsf.gov/news/podcast-lasers-materials-future",
    "date": "2026-08-31",
    "source": "NSF",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Chunlei Guo, an NSF-supported researcher, discusses his work using femtosecond lasers to design materials with highly functionalized purposes...",
    "summaryOrigin": "feed"
  },
  {
    "id": "esa-1ibfvtz",
    "title": "What happened this month at the European Space Agency? (August 2026)",
    "url": "https://www.esa.int/ESA_Multimedia/Videos/2026/08/What_happened_this_month_at_the_European_Space_Agency_August_2026",
    "date": "2026-08-31",
    "source": "ESA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Video: 00:03:19 August was a busy month for ESA, between spectacular views, historic milestones and exciting new discoveries. From a total solar eclipse broadcast…",
    "summaryOrigin": "feed"
  },
  {
    "id": "esa-ligpyz",
    "title": "Roman lifts off on a mission to survey the infrared sky",
    "url": "https://www.esa.int/ESA_Multimedia/Images/2026/08/Roman_lifts_off_on_a_mission_to_survey_the_infrared_sky",
    "date": "2026-08-31",
    "source": "ESA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Image: NASA’s Nancy Grace Roman Space Telescope lifted off on a SpaceX Falcon Heavy rocket from NASA’s Kennedy Space Center in Florida, USA, at…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nasa-m3qu56",
    "title": "Ribbon-Cutting Event for NASA Deep Space Network’s Deep Space Station 23",
    "url": "https://science.nasa.gov/photojournal/ribbon-cutting-event-for-nasa-deep-space-networks-deep-space-station-23/",
    "date": "2026-08-30",
    "source": "NASA",
    "category": "technology",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Description Leadership from NASA Headquarters, the Jet Propulsion Laboratory, and the Deep Space Network (DSN) stand in front of the recently completed Deep Space…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nasa-1uad26a",
    "title": "NASA Deep Space Network’s New Goldstone Antenna Goes Online",
    "url": "https://science.nasa.gov/photojournal/nasa-deep-space-networks-new-goldstone-antenna-goes-online/",
    "date": "2026-08-30",
    "source": "NASA",
    "category": "technology",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Description Long shadows are cast by the recently completed Deep Space Station 23 at the Deep Space Network’s Goldstone complex near Barstow, California, in…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nasa-1rxh00a",
    "title": "Panorama Showcasing the 34-Meter Antennas of the DSN’s Goldstone Complex",
    "url": "https://science.nasa.gov/photojournal/panorama-showcasing-the-34-meter-antennas-of-the-dsns-goldstone-complex/",
    "date": "2026-08-30",
    "source": "NASA",
    "category": "technology",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Description Five antennas soak in the summer sun at the Deep Space Network’s Goldstone complex near Barstow, California, in August 2026. The recently completed…",
    "summaryOrigin": "feed"
  },
  {
    "id": "ncsc-1c0x249",
    "title": "Disruptive cyber activity highlights risk from internet-exposed systems and edge devices",
    "url": "https://www.ncsc.gov.uk/news/disruptive-cyber-activity-highlights-risk-from-internet-exposed-systems-and-edge-devices",
    "date": "2026-08-27",
    "source": "NCSC",
    "category": "security",
    "region": "uk",
    "sourceLanguage": "en",
    "sourceSummary": "Owners of operational technology encouraged to address avoidable vulnerabilities, and build long-term cyber resilience.",
    "summaryOrigin": "feed"
  },
  {
    "id": "nsf-dxw9sw",
    "title": "NSF launches three new Science and Technology Centers with $90M investment in transformative research",
    "url": "https://www.nsf.gov/news/nsf-launches-three-new-science-technology-centers-90m",
    "date": "2026-08-26",
    "source": "NSF",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The U.S. National Science Foundation is investing $90 million over five years to support three new NSF Science and Technology Centers (NSF STC). These…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nsf-1pzalrv",
    "title": "Eight NSF research institutes to propel U.S. quantum science with $290M investment",
    "url": "https://www.nsf.gov/news/eight-nsf-research-institutes-propel-us-quantum-science-290m",
    "date": "2026-08-25",
    "source": "NSF",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Understanding and wielding the quantum properties of nature is the ambitious objective of eight research institutes that will collectively receive more than $290 million…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nsf-1k0drwf",
    "title": "Podcast: Educator wins Presidential AI Challenge",
    "url": "https://www.nsf.gov/news/podcast-educator-wins-presidential-ai-challenge",
    "date": "2026-08-25",
    "source": "NSF",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "U.S. National Science Foundation-supported researchers are behind an educational effort to introduce artificial intelligence techniques to elementary school children...",
    "summaryOrigin": "feed"
  },
  {
    "id": "nsf-173oa4b",
    "title": "Podcast: Researchers bring AI to elementary schoolers",
    "url": "https://www.nsf.gov/news/podcast-researchers-bring-ai-elementary-schoolers",
    "date": "2026-08-25",
    "source": "NSF",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Researchers discuss the challenges of introducing artificial intelligence concepts into elementary school curriculum and how the project led to a win in the inaugural…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nist-zxfshv",
    "title": "NIST Researchers Supersize Quantum Technology to Help Detect Faint Photons",
    "url": "https://www.nist.gov/news-events/news/2026/08/nist-researchers-supersize-quantum-technology-help-detect-faint-photons",
    "date": "2026-08-24",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Our everyday life is flooded with photons, the quantum building blocks of light. For cutting-edge technology, from quantum computing to deep-tissue imaging, detecting every…",
    "summaryOrigin": "feed"
  },
  {
    "id": "gov-uk-xtquge",
    "title": "Joint Declaration of Intent between the United Kingdom of Great Britain and Northern Ireland and Ukraine on a UK-Ukraine Artificial Intelligence Partnership",
    "url": "https://www.gov.uk/government/news/joint-declaration-of-intent-between-the-united-kingdom-of-great-britain-and-northern-ireland-and-ukraine-on-a-uk-ukraine-artificial-intelligence-partn",
    "date": "2026-08-24",
    "source": "GOV.UK",
    "category": "technology",
    "region": "uk",
    "sourceLanguage": "en",
    "sourceSummary": "GOV.UK published this official technology update under the headline “Joint Declaration of Intent between the United Kingdom of Great Britain and Northern Ireland and…",
    "summaryOrigin": "metadata"
  },
  {
    "id": "gov-uk-q08126",
    "title": "New partnership set to see the UK and Ukraine develop battle winning technology as Britain secures access to Ukraine's Avengers AI Labs",
    "url": "https://www.gov.uk/government/news/new-partnership-set-to-see-the-uk-and-ukraine-develop-battle-winning-technology-as-britain-secures-access-to-ukraines-avengers-ai-labs",
    "date": "2026-08-24",
    "source": "GOV.UK",
    "category": "technology",
    "region": "uk",
    "sourceLanguage": "en",
    "sourceSummary": "A landmark AI deal between the UK and Ukraine has been signed today as the two countries join forces to develop new military capabilities…",
    "summaryOrigin": "feed"
  },
  {
    "id": "gov-uk-3jvzb0",
    "title": "NAD Group appoints new Chief Digital and Information Officer",
    "url": "https://www.gov.uk/government/news/nad-group-appoints-new-chief-digital-and-information-officer",
    "date": "2026-08-19",
    "source": "GOV.UK",
    "category": "technology",
    "region": "uk",
    "sourceLanguage": "en",
    "sourceSummary": "Dan Rodenhurst will lead all of the MOD’s digital and data teams, succeeding Charles Forte.",
    "summaryOrigin": "feed"
  },
  {
    "id": "gov-uk-166amn",
    "title": "Lanarkshire AI Growth Zone secures £300 million investment as Dell establishes Scottish base",
    "url": "https://www.gov.uk/government/news/lanarkshire-ai-growth-zone-secures-300-million-investment-as-dell-establishes-scottish-base",
    "date": "2026-08-17",
    "source": "GOV.UK",
    "category": "technology",
    "region": "uk",
    "sourceLanguage": "en",
    "sourceSummary": "AI Growth Zone to support more than 3,400 jobs and attract major new investment to Lanarkshire – supporting the drive for good growth in…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nsf-e2pul0",
    "title": "NSF announces $1.5B for foundational research to drive scientific breakthroughs for American technological leadership",
    "url": "https://www.nsf.gov/news/nsf-announces-15b-foundational-research-drive-scientific",
    "date": "2026-08-17",
    "source": "NSF",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The U.S. National Science Foundation today released 12 new notices of funding opportunities (NOFOs) providing over $1.5 billion for foundational research, including basic and…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nist-1m9ypxq",
    "title": "NIST National Construction Safety Team Advisory Committee Meeting Scheduled for Sept. 23 and 24, 2026",
    "url": "https://www.nist.gov/news-events/news/2026/08/nist-national-construction-safety-team-advisory-committee-meeting-scheduled",
    "date": "2026-08-13",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Anyone wishing to attend the virtual meeting must register by 5 p.m. EDT on Wednesday, Sept. 16.",
    "summaryOrigin": "feed"
  },
  {
    "id": "nsf-1b2ujma",
    "title": "Podcast: The Legacy Survey of Space and Time (LSST)",
    "url": "https://www.nsf.gov/news/podcast-legacy-survey-space-time-lsst",
    "date": "2026-08-10",
    "source": "NSF",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "NSF Noirlab&#039;s Robert Blum discusses NSF-DOE Vera C. Rubin Observatory&#039;s signature mission, the Legacy Survey of Space and Time, and how it will transform…",
    "summaryOrigin": "feed"
  },
  {
    "id": "noaa-michee",
    "title": "NOAA to hold public meetings on California Coastal Management Program",
    "url": "https://oceanservice.noaa.gov/news/aug26/czma-public-meetings.html",
    "date": "2026-08-08",
    "source": "NOAA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Public invited to provide input on the state’s coastal management program and performance evaluation",
    "summaryOrigin": "feed"
  },
  {
    "id": "nsf-4yx1e4",
    "title": "Podcast: New telescope to transform study of universe",
    "url": "https://www.nsf.gov/news/podcast-new-telescope-transform-study-universe",
    "date": "2026-08-07",
    "source": "NSF",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "As the 10-year Legacy Survey of Space and Time officially starts, Edward Ajhar discusses the NSF-DOE Vera C. Rubin Observatory and how it will…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nist-3bn656",
    "title": "NIST Researchers Correct Common Error Confounding Nanotech Measurements",
    "url": "https://www.nist.gov/news-events/news/2026/08/nist-researchers-correct-common-error-confounding-nanotech-measurements",
    "date": "2026-08-06",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The scientists offer a practical solution that relies on accounting for measurement errors before testing materials or developing products.",
    "summaryOrigin": "feed"
  },
  {
    "id": "nist-9ai57k",
    "title": "‘Spooky’ Particles Transit DC Suburbs, a Step Toward a Quantum Network",
    "url": "https://www.nist.gov/news-events/news/2026/08/spooky-particles-transit-dc-suburbs-step-toward-quantum-network",
    "date": "2026-08-05",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The achievement shows that fragile quantum entanglement can survive even in tough, real-world conditions.",
    "summaryOrigin": "feed"
  },
  {
    "id": "nist-18jr3vy",
    "title": "NIST Joins National Genesis Mission to Accelerate AI Innovation",
    "url": "https://www.nist.gov/news-events/news/2026/08/nist-joins-national-genesis-mission-accelerate-ai-innovation",
    "date": "2026-08-04",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "NIST will execute two of its efforts through its Centers for AI in Manufacturing and Critical Infrastructure.",
    "summaryOrigin": "feed"
  },
  {
    "id": "nsf-1aohd17",
    "title": "New NSF State and Regional AI Infrastructure Hubs will power AI-enabled scientific research across the country",
    "url": "https://www.nsf.gov/news/new-nsf-state-regional-ai-infrastructure-hubs-will-power-ai",
    "date": "2026-08-04",
    "source": "NSF",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "New initiative will accelerate AI-enabled scientific discovery by expanding access to compute for researchers, students and educators through regional partnerships among state and local…",
    "summaryOrigin": "feed"
  },
  {
    "id": "ncsc-vlazfq",
    "title": "NCSC statement in response to recent incidents resulting from frontier AI evaluations",
    "url": "https://www.ncsc.gov.uk/news/ncsc-statement-in-response-to-recent-incidents-resulting-from-frontier-ai-evaluations",
    "date": "2026-08-04",
    "source": "NCSC",
    "category": "security",
    "region": "uk",
    "sourceLanguage": "en",
    "sourceSummary": "A statement from Ollie Whitehouse, Chief Technology Officer at the NCSC, on AI security following recent incidents.",
    "summaryOrigin": "feed"
  },
  {
    "id": "nsf-be95t0",
    "title": "NSF stands up 2 Materials Innovation Platforms with $50M investment",
    "url": "https://www.nsf.gov/news/nsf-stands-2-materials-innovation-platforms-50m-investment",
    "date": "2026-08-03",
    "source": "NSF",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The U.S. National Science Foundation is investing $50 million in research infrastructure to enable the discovery and development of materials that can withstand extreme…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nsf-1poo2n9",
    "title": "Building the future, atom by atom — NSF deploys $108M for materials science at 6 research centers",
    "url": "https://www.nsf.gov/news/building-future-atom-atom-nsf-deploys-108m-materials-science",
    "date": "2026-07-30",
    "source": "NSF",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The U.S. National Science Foundation is pushing materials science beyond the state-of-the-art with an investment of $108 million in six advanced research centers. The…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nsf-1tzy9r3",
    "title": "NSF partners with universities and industry on pilot initiative for four-year Ph.D. programs with real-world research placements",
    "url": "https://www.nsf.gov/news/nsf-partners-universities-industry-pilot-initiative-four",
    "date": "2026-07-29",
    "source": "NSF",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The U.S. National Science Foundation announced a $47 million investment over ﬁve years, along with additional ﬁnancial commitments from nearly three dozen universities and…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nsf-gyz6e7",
    "title": "NSF announces first awards to advance AI and cybersecurity education and workforce development through CyberAICorps Scholarship for Service Program",
    "url": "https://www.nsf.gov/news/nsf-announces-first-awards-advance-ai-cybersecurity",
    "date": "2026-07-28",
    "source": "NSF",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The U.S. National Science Foundation's Directorate for STEM Education today announced the inaugural awards under the CyberAICorps Scholarship for Service (CyberAI SFS) program, representing…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nsf-9wumxj",
    "title": "Podcast: New microchips could supercharge AI",
    "url": "https://www.nsf.gov/news/podcast-new-microchips-could-supercharge-ai",
    "date": "2026-07-27",
    "source": "NSF",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "U.S. National Science Foundation-supported researcher Qing Cao discusses a new monolithic, 3D-integrated silicon microchip and how it might impact artificial intelligence systems...",
    "summaryOrigin": "feed"
  },
  {
    "id": "ncsc-bilfv7",
    "title": "UK and partners expose Russian state-supported actors for new ‘zero-click’ phishing campaign targeting Western organisations",
    "url": "https://www.ncsc.gov.uk/news/uk-and-partners-expose-russian-state-supported-actors-for-new-zero-click-phishing-campaign",
    "date": "2026-07-23",
    "source": "NCSC",
    "category": "security",
    "region": "uk",
    "sourceLanguage": "en",
    "sourceSummary": "GCHQ’s National Cyber Security Centre and international partners issue warning as ‘LAUNDRY BEAR’ cyber threat group exposed for targeted phishing campaign",
    "summaryOrigin": "feed"
  },
  {
    "id": "nist-10or147",
    "title": "NIST Announces Funding Opportunity for 14 MEP Centers to Advance Small and Medium-Sized U.S. Manufacturers",
    "url": "https://www.nist.gov/news-events/news/2026/07/nist-announces-funding-opportunity-14-mep-centers-advance-small-and-medium",
    "date": "2026-07-22",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "NIST MEP will host an informational webinar on Tuesday, July 28, 2026, at 1 p.m. ET to provide general information about this opportunity and…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nist-1dpewg7",
    "title": "NIST Receives New Patent for Microbe-Killing Water Heater",
    "url": "https://www.nist.gov/news-events/news/2026/07/nist-receives-new-patent-microbe-killing-water-heater",
    "date": "2026-07-14",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Warm water in household pipes can be a breeding ground for harmful bacteria.",
    "summaryOrigin": "feed"
  },
  {
    "id": "noaa-3rsp3w",
    "title": "How Removing Lost Crab Traps Is Helping Map the Chesapeake Bay",
    "url": "https://oceanservice.noaa.gov/news/july26/bathymetric-data.html",
    "date": "2026-07-14",
    "source": "NOAA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "NOAA published this official science update under the headline “How Removing Lost Crab Traps Is Helping Map the Chesapeake Bay”. Open the source for…",
    "summaryOrigin": "metadata"
  },
  {
    "id": "ncsc-1dfjuxd",
    "title": "UK and Allies urge critical sectors to improve defences against Russian intelligence targeting",
    "url": "https://www.ncsc.gov.uk/news/uk-and-allies-urge-critical-sectors-to-improve-defences-against-russian-intelligence-targeting",
    "date": "2026-07-13",
    "source": "NCSC",
    "category": "security",
    "region": "uk",
    "sourceLanguage": "en",
    "sourceSummary": "New advisory highlights Russian state cyber actors’ global exploitation of poorly configured routers",
    "summaryOrigin": "feed"
  },
  {
    "id": "nist-18qr5wm",
    "title": "New Fabric Test Material Could Help Strengthen Domestic Supply Chain for Textiles and Clothing",
    "url": "https://www.nist.gov/news-events/news/2026/07/new-fabric-test-material-could-help-strengthen-domestic-supply-chain",
    "date": "2026-07-09",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Researchers estimate that 56% of textiles can be recycled or recovered, but most don’t make it back into the domestic supply chain.",
    "summaryOrigin": "feed"
  },
  {
    "id": "noaa-qufz44",
    "title": "Transforming Chesapeake Bay Water Forecasting",
    "url": "https://oceanservice.noaa.gov/news/july26/transforming-chesapeake.html",
    "date": "2026-07-07",
    "source": "NOAA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "A rocky jetty crosses the frame in shallow Bay waters. A wooden walkway follows the jetty halfway, then turns and continues as an L-shaped…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nist-i5q59n",
    "title": "Arvind Raman Confirmed as the 18th NIST Director",
    "url": "https://www.nist.gov/news-events/news/2026/07/arvind-raman-confirmed-18th-nist-director",
    "date": "2026-07-06",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Raman comes to NIST from Purdue University, where he was the dean of engineering.",
    "summaryOrigin": "feed"
  },
  {
    "id": "nist-rgo50e",
    "title": "NIST Launches Center to Drive the Manufacture of Quantum Technologies",
    "url": "https://www.nist.gov/news-events/news/2026/06/nist-launches-center-drive-manufacture-quantum-technologies",
    "date": "2026-06-29",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "NIST has announced an agreement with SRI International to establish the Quantum Manufacturing Engineering Center (QMEC).",
    "summaryOrigin": "feed"
  },
  {
    "id": "nist-t7cfvj",
    "title": "NIST Releases Technical Findings on What Caused the 2021 Partial Collapse of Champlain Towers South",
    "url": "https://www.nist.gov/news-events/news/2026/06/nist-releases-technical-findings-what-caused-2021-partial-collapse",
    "date": "2026-06-22",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "In an investigation that began just days after the tragedy, the team examined two dozen possible scenarios for where and why the collapse started.",
    "summaryOrigin": "feed"
  },
  {
    "id": "ncsc-hxumow",
    "title": "The AI shift in cyber risk: why leaders must act now",
    "url": "https://www.ncsc.gov.uk/news/the-ai-shift-in-cyber-risk-why-leaders-must-act-now",
    "date": "2026-06-22",
    "source": "NCSC",
    "category": "security",
    "region": "uk",
    "sourceLanguage": "en",
    "sourceSummary": "Five Eyes cyber security agencies urge organisations to act on rapidly transforming cyber risk.",
    "summaryOrigin": "feed"
  },
  {
    "id": "ncsc-b2gryq",
    "title": "Alert: NCSC issues advice following global targeting of Fortinet firewalls and VPN gateways",
    "url": "https://www.ncsc.gov.uk/news/advice-following-global-targeting-of-fortinet-firewalls-and-vpn-gateways",
    "date": "2026-06-18",
    "source": "NCSC",
    "category": "security",
    "region": "uk",
    "sourceLanguage": "en",
    "sourceSummary": "Organisations using Fortinet services are being urged to take action following a campaign affecting firewalls and VPN gateways.",
    "summaryOrigin": "feed"
  },
  {
    "id": "ncsc-1aiavvj",
    "title": "NCSC CEO: Hostile states linked to three-quarters of cyber attacks affecting UK's critical systems",
    "url": "https://www.ncsc.gov.uk/news/ncsc-ceo-hostile-states-linked-to-three-quarters-of-cyber-attacks",
    "date": "2026-06-17",
    "source": "NCSC",
    "category": "security",
    "region": "uk",
    "sourceLanguage": "en",
    "sourceSummary": "Dr Richard Horne highlighted the scale of cyber threats against the UK’s critical infrastructure at RUSI’s Annual Security Lecture.",
    "summaryOrigin": "feed"
  },
  {
    "id": "noaa-5y0cc9",
    "title": "NOAA forecasts an above-average summer 'dead zone' in Gulf of America",
    "url": "https://oceanservice.noaa.gov/news/jun26/summer-dead-zone.html",
    "date": "2026-06-16",
    "source": "NOAA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Low-oxygen conditions are expected to be larger than average, impacting a 7,027 square-mile area.",
    "summaryOrigin": "feed"
  },
  {
    "id": "nist-7oz3o8",
    "title": "NIST Expands Its Library of ‘Chemical Fingerprints’ to Identify Unknown Substances",
    "url": "https://www.nist.gov/news-events/news/2026/06/nist-expands-its-library-chemical-fingerprints-identify-unknown-substances",
    "date": "2026-06-09",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Researchers and manufacturers rely on the library to identify unknown compounds in food, drugs, cosmetics, the environment, body fluids, forensic evidence and even space…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nist-vhemnc",
    "title": "NIST Mathematical Proof Supports Transition to a Continuous-Monitor-and-Update Security Model for AI Systems",
    "url": "https://www.nist.gov/news-events/news/2026/06/nist-mathematical-proof-supports-transition-continuous-monitor-and-update",
    "date": "2026-06-09",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The proof extends to AI the logic used by famed mathematician Kurt Gödel, whose incompleteness theorems have had a profound effect on math for…",
    "summaryOrigin": "feed"
  },
  {
    "id": "nist-1jyv2x0",
    "title": "New AI Model Shows How to Evacuate for Fires One Safe Step at a Time",
    "url": "https://www.nist.gov/news-events/news/2026/06/new-ai-model-shows-how-evacuate-fires-one-safe-step-time",
    "date": "2026-06-04",
    "source": "NIST",
    "category": "standards",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "A NIST-led team has created a new AI model that can identify safe evacuation routes in a single-story floor plan during a fire, with…",
    "summaryOrigin": "feed"
  },
  {
    "id": "noaa-k98w6m",
    "title": "Harmful Algal Bloom Monitoring Expands to New Coastal Northeast and Great Lakes Regions",
    "url": "https://oceanservice.noaa.gov/news/jun26/harmful-algal-bloom-monitoring.html",
    "date": "2026-06-01",
    "source": "NOAA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The new products for the Northeast coast and Great Lakes strengthen NOAA’s ability to deliver timely, science-based tools for state, local, and regional partners.",
    "summaryOrigin": "feed"
  },
  {
    "id": "noaa-21v7if",
    "title": "El Niño and high tide flooding, a possible double whammy for some coastal communities in 2026",
    "url": "https://oceanservice.noaa.gov/news/may26/el-nino-flooding.html",
    "date": "2026-05-15",
    "source": "NOAA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "The predicted El Niño could mean more high tide flooding for many locations.",
    "summaryOrigin": "feed"
  },
  {
    "id": "noaa-1c0l41i",
    "title": "NOAA releases new National Coral Reef Resilience Strategy",
    "url": "https://oceanservice.noaa.gov/news/may26/coral-reef-resilience.html",
    "date": "2026-05-06",
    "source": "NOAA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "NOAA published this official science update under the headline “NOAA releases new National Coral Reef Resilience Strategy”. Open the source for full context.",
    "summaryOrigin": "metadata"
  },
  {
    "id": "noaa-1p55gvv",
    "title": "NOAA Ship Thomas Jefferson returns to the Great Lakes",
    "url": "https://oceanservice.noaa.gov/news/may26/noaaship-greatlakes-survey-2026.html",
    "date": "2026-05-01",
    "source": "NOAA",
    "category": "science",
    "region": "global",
    "sourceLanguage": "en",
    "sourceSummary": "Marine sectors show increases in jobs and wages",
    "summaryOrigin": "feed"
  },
  {
    "id": "ncsc-foh8hf",
    "title": "NCSC: Leave passwords in the past - passkeys are the future",
    "url": "https://www.ncsc.gov.uk/news/ncsc-leave-passwords-in-the-past-passkeys-are-the-future",
    "date": "2026-04-23",
    "source": "NCSC",
    "category": "security",
    "region": "uk",
    "sourceLanguage": "en",
    "sourceSummary": "Passkeys are the more secure and user-friendly login method and should be the default authentication option for consumers.",
    "summaryOrigin": "feed"
  }
];
