export type InfoKey = "about" | "privacy" | "cookies" | "terms" | "contact" | "faq";
export type InfoLocale = "tr" | "en";
type Localized<T> = Record<InfoLocale, T>;

export type InfoSection = { heading: string; paragraphs: string[]; bullets?: string[]; links?: { label: string; href: string }[] };
export type InfoContent = {
  eyebrow: Localized<string>;
  title: Localized<string>;
  intro: Localized<string>;
  updated?: Localized<string>;
  sections: Localized<InfoSection[]>;
};

export const info: Record<InfoKey, InfoContent> = {
  about: {
    eyebrow: { tr: "BYTEQUANT HAKKINDA", en: "ABOUT BYTEQUANT" },
    title: { tr: "Dijital işleri daha özel, açık ve erişilebilir hale getiriyoruz", en: "Making digital work more private, transparent, and accessible" },
    intro: { tr: "ByteQuant; prompt, metin, veri ve güvenlik görevlerini tarayıcı içinde tamamlamaya odaklanan bağımsız bir web projesidir. Amacımız büyük iddialar değil, günlük işlerde güvenilir küçük araçlar ve yöntemini açıklayan içerikler sunmaktır.", en: "ByteQuant is an independent web project focused on completing prompt, text, data, and security tasks inside the browser. Our goal is not grand claims, but dependable small tools and content that explains the method." },
    sections: {
      tr: [
        { heading: "Neden ByteQuant var?", paragraphs: ["Basit bir metin dönüşümü için bile kullanıcıdan hesap, dosya yükleme veya uzak sunucu erişimi isteyen çok sayıda ürün var. Oysa kelime sayımı, JSON doğrulama, kişisel veri desenlerini maskeleme ve SHA-256 özeti üretme gibi görevler modern bir tarayıcıda güvenli biçimde yapılabilir. ByteQuant bu görevleri gereksiz veri yolculuğu olmadan çözmek için kuruldu.", "Ürün, 'client-side' ifadesini pazarlama etiketi olarak değil tasarım sınırı olarak ele alır. Temel araç girdileri sunucuya gönderilmez; kullanılan yöntem ve yaklaşık sonuçlar araç sayfalarında açıklanır." ] },
        { heading: "Misyonumuz ve ürün ilkelerimiz", paragraphs: ["Misyonumuz, teknik ve teknik olmayan kullanıcıların hassas metinlerle daha bilinçli çalışmasını sağlamak; tekrarlanan küçük işleri hızlı, ücretsiz ve anlaşılır araçlarla kolaylaştırmaktır."], bullets: ["Sunucu gerektirmeyen işi cihazda tutmak", "Her aracın ne yaptığını ve ne yapmadığını açıklamak", "Kayıt veya üyeliği temel kullanıma engel yapmamak", "Erişilebilir, mobil uyumlu ve hızlı bir deneyim sunmak", "Hata ve düzeltme bildirimlerine açık olmak"] },
        { heading: "Uzmanlık ve editoryal yaklaşım", paragraphs: ["ByteQuant içeriği web geliştirme, tarayıcı güvenliği, veri işleme ve prompt tasarımı uygulamalarına dayanır. Hukuki konularda kesin uygunluk iddiası üretmeyiz. KVKK ve GDPR ile ilgili içerikler genel bilgilendirme sağlar; somut yükümlülükler için yetkin hukuk ve veri koruma uzmanı görüşü gerekir.", "Makaleler ürün davranışıyla karşılaştırılır, önemli yöntem sınırları metinde belirtilir ve değişiklik tarihi görünür tutulur. Bir teknik hata, eksik açıklama veya düzeltme talebi için bytequant@yahoo.com adresi kullanılabilir." ] },
        { heading: "İş modeli ve bağımsızlık", paragraphs: ["ByteQuant araçları ücretsizdir. Site gelecekte açıkça işaretlenmiş reklam alanlarıyla desteklenebilir. Reklam, editoryal sıralamayı veya araç sonucunu belirlemez. Ücretli tanıtım yayımlanırsa içerikten ayrı ve anlaşılır biçimde etiketlenir.", "Şu an ekip üyesi veya kurucu hakkında doğrulanabilir kişisel biyografi yayımlamadığımız için hayalî unvan ve deneyim iddiası kullanmıyoruz. Güveni, ürünün gözlemlenebilir davranışı, açık politikaları ve ulaşılabilir iletişim kanalı üzerinden kurmayı tercih ediyoruz." ] },
        { heading: "Açık kaynak, sürümler ve hesap verebilirlik", paragraphs: ["ByteQuant kaynak kodu MIT lisansı altında GitHub'da yayımlanır. Araç mantığı, üçüncü taraf bağımlılıklar, güvenlik politikası ve değişiklik geçmişi denetlenebilir; bu, gizlilik beyanını yalnızca söze dayalı olmaktan çıkarır.", "Düzeltmeleri gözlemlenebilir ürün davranışı, tekrarlanabilir örnek ve ilgili sayfa bağlantısıyla kabul ederiz. Güvenlik açıkları SECURITY.md süreciyle özel olarak, içerik ve yöntem önerileri ise topluluk alanında paylaşılabilir." ], links: [{ label: "GitHub açık kaynak deposu", href: "https://github.com/byte-quant/bytequant" }, { label: "Topluluk paylaşım alanı", href: "/topluluk" }] },
      ],
      en: [
        { heading: "Why ByteQuant exists", paragraphs: ["Many products require an account, upload, or remote server even for simple transformations. Yet tasks such as word counting, JSON validation, pattern masking, and SHA-256 digests can run in a modern browser. ByteQuant was created to solve those jobs without unnecessary data travel.", "We treat client-side operation as a design boundary, not a marketing label. Core tool inputs are not sent to a server, and each tool explains its method and estimates." ] },
        { heading: "Mission and product principles", paragraphs: ["Our mission is to help technical and non-technical users work more deliberately with sensitive text and finish recurring small tasks with free, understandable tools."], bullets: ["Keep server-free work on-device", "Explain what each tool does and does not do", "Do not gate core use behind an account", "Build for accessibility, mobile use, and speed", "Welcome corrections and bug reports"] },
        { heading: "Expertise and editorial approach", paragraphs: ["ByteQuant content draws on web development, browser security, data processing, and prompt design practices. We do not claim automatic legal compliance. KVKK and GDPR articles are general information; specific obligations require qualified legal and data-protection advice.", "Articles are checked against product behavior, limitations are stated, and update dates are visible. Corrections can be sent to bytequant@yahoo.com." ] },
        { heading: "Business model and independence", paragraphs: ["ByteQuant tools are free. The site may later be supported by clearly labeled advertising. Advertising does not determine editorial ranking or tool output; sponsored material would be separated and labeled.", "We do not publish invented titles or biographies when a verified personal profile is unavailable. Trust should come from observable product behavior, clear policies, and reachable contact channels." ] },
        { heading: "Open source, releases, and accountability", paragraphs: ["ByteQuant source is published on GitHub under the MIT License. Tool behavior, third-party dependencies, security policy, and change history can be inspected, making privacy claims testable rather than trust-only.", "Corrections should include observable behavior, a reproducible example, and the affected page. Report vulnerabilities privately through SECURITY.md; share content and workflow suggestions in the community area." ], links: [{ label: "GitHub open-source repository", href: "https://github.com/byte-quant/bytequant" }, { label: "Community sharing area", href: "/en/community" }] },
      ],
    },
  },
  privacy: {
    eyebrow: { tr: "GİZLİLİK POLİTİKASI", en: "PRIVACY POLICY" },
    title: { tr: "Veri akışını açık ve mümkün olduğunca kısa tutuyoruz", en: "We keep data flows clear and as short as possible" },
    intro: { tr: "Bu politika, bytequant.org ziyaret edildiğinde hangi bilgilerin işlendiğini ve tarayıcı içi araçların nasıl çalıştığını açıklar. Mevcut sürümde araç girdileri ByteQuant sunucularına gönderilmez.", en: "This policy explains what information is processed when you visit bytequant.org and how the in-browser tools work. In the current version, tool inputs are not sent to ByteQuant servers." },
    updated: { tr: "Son güncelleme: 22 Temmuz 2026", en: "Last updated: July 22, 2026" },
    sections: {
      tr: [
        { heading: "1. Kapsam, veri sorumlusu ve iletişim", paragraphs: ["Bu politika ByteQuant web sitesi, araç sayfaları, rehberler ve iletişim kanalları için geçerlidir. Bu hizmet bakımından veri sorumlusu ByteQuant'tır. Gizlilik soruları ve veri sahibi başvuruları bytequant@yahoo.com adresine iletilebilir; başvuruyu yanıtlamak için yalnızca gerekli kimlik ve talep bilgileri istenir.", "Araç girdileri ByteQuant'a aktarılmadığından bunlar üzerinde merkezi erişim kurulmaz. E-posta yoluyla bizimle iletişime geçtiğinizde gönderdiğiniz iletişim bilgileri ve mesaj içeriği, talebinizi yanıtlamak ve gerekli kayıtları korumak amacıyla işlenir." ] },
        { heading: "2. Araç girdileri, Yerel Ajan, kurulabilir uygulama ve tarayıcı içi işleme", paragraphs: ["Prompt, metin, JSON, CSV, Regex, parola, görsel ve PDF gibi araç girdileri tarayıcınızda işlenir. Bu girdiler ByteQuant sunucusuna gönderilmez, hesapla ilişkilendirilmez ve varsayılan olarak localStorage içine kaydedilmez. Sayfayı yenilemek veya kapatmak etkin oturumdaki girdiyi kaldırır.", "Yerel Ajan hedefi çok dilli semantik kurallar ile işler; uzak LLM veya AI API'si çağırmaz. Plan ve son sekiz konuşma özeti yalnızca açık sekmenin sessionStorage alanında tutulur. Sesli giriş ancak tarayıcı cihaz içi işlemeyi doğruladığında etkinleşir ve uzak konuşma tanımaya geri düşmez.", "ByteQuant'ı ana ekrana veya masaüstüne eklemek, siteyi ayrı bir pencereden daha hızlı açmanızı sağlayan tarayıcı özelliğidir; indirilen bağımsız bir Android APK değildir. Eski Android uyarısı görülürse kurulumu iptal edin, tarayıcıyı güncelleyin, eski ByteQuant kısayolunu kaldırın ve güncel tarayıcı menüsünden yeniden kurun.", "Kopyalama ve indirme işlemleri sizin cihazınızda yeni bir veri kopyası oluşturur. Görsel/PDF dönüştürme sırasında geçici nesne URL'leri yalnızca sekme belleğinde tutulur ve sonuç temizlendiğinde veya sekme kapatıldığında bırakılır. Paylaşılan cihazlarda pano geçmişi ve indirilen dosyalar kullanıcı sorumluluğundadır." ] },
        { heading: "2A. İş İstasyonu, şifreli projeler, P2P ve tarif bağlantıları", paragraphs: ["İş İstasyonu'nda açıkça kaydettiğiniz projeler bytequant-workspaces adlı IndexedDB veritabanında tutulur. Proje belgeleri AES-GCM-256 ile şifrelenir; çıkarılamayan cihaz anahtarı aynı veritabanında saklanır. ByteQuant anahtara veya projeye uzaktan erişemez. Bu koruma, ele geçirilmiş cihazı, kötü amaçlı tarayıcı eklentisini ya da aynı origin üzerinde çalışan zararlı kodu etkisiz kılan bir güvenlik garantisi değildir.", "Araçlara geçiş sırasında bytequant:workstation-active:v1, bytequant:workstation-handoff:v1 ve açıkça seçilen Ajan hedefi için bytequant:workstation-agent-goal:v1 sessionStorage kayıtları aynı sekmede geçici ve boyut sınırlı aktarım yapabilir; geri dönüşte temizlenir. Dosya seçimi, parola alanı, kod çalıştırma ve indirme otomatikleştirilmez.", "Sunucusuz ortak çalışma, WebRTC DataChannel ve tarayıcıların DTLS şifrelemesini kullanır. ByteQuant sinyal sunucusu, STUN veya TURN çalıştırmaz. Tek kullanımlık davet ve yanıt kodları 10 dakika içinde geçersiz olur ve bağlantı adayları gibi ağ bilgileri içerebilir. Canlı paylaşım varsayılan olarak kapalıdır; iki taraf ayrı bir kanaldan aynı güvenlik kodunu gördüğünü doğrulamadan etkinleştirilemez. Bu kod aradaki kişi saldırısını fark etmeye yardımcı olur ancak gerçek kimlik doğrulaması değildir. NAT, güvenlik duvarı veya tarayıcı politikaları bağlantıyı engelleyebilir.", "Tarif bağlantıları çıktıları her zaman, girdileri ise varsayılan olarak dışarıda bırakır. Girdileri dahil etmeyi seçerseniz bu veri URL'de, tarayıcı geçmişinde, panoda, mesajlaşma hizmetinde ve bağlantıyı alan kişinin cihazında görünür hâle gelir. Hassas, kişisel veya gizli veriyi tarif bağlantısına eklemeyin." ] },
        { heading: "3. Çerezler, yerel depolama ve açık rıza", paragraphs: ["ByteQuant mevcut sürümde HTTP çerezi, analitik tanımlayıcı veya reklam etiketi yerleştirmez. bq-consent-v1 seçiminizi 180 gün hatırlamak için; bq-theme ise açıkça istediğiniz renk temasını sunmak için gerekli yerel depolama olarak kullanılır.", "bq-tool-usage-v1 ve bq-tool-favorites-v1 yalnızca açık rızanızdan sonra etkinleşir. Araç slug'ı, sayaç, son kullanım zamanı veya sabitlenen araç kimliklerini içerir; girdi, dosya, parola veya çıktı içermez. Rızayı geri çektiğinizde iki kayıt da silinir.", "Araçlar arası sonuç aktarımı bytequant:tool-transfer:v1 içinde aynı sekmede en fazla 20 dakika tutulur. Yerel Ajan konuşma özeti ve Workstation plan aktarımı da yalnızca sessionStorage kullanır ve sekme kapanınca sona erer." ], links: [{ label: "Çerez ve yerel depolama politikası", href: "/cerez-politikasi" }] },
        { heading: "3A. Proje etkinliği ve topluluk paylaşımı", paragraphs: ["Ana sayfadaki proje sağlığı kartı statik içeriktir; GitHub API'sine istek göndermez. İş akışı veya değişiklik geçmişi bağlantısını açarsanız GitHub'a gidersiniz ve GitHub kendi politikası kapsamında standart bağlantı verilerini işleyebilir. Araç girdisi, favori veya kullanım sayacı aktarılmaz.", "Topluluk taslak aracı metni bu sekmede ön kontrolden geçirir ve ByteQuant sunucusuna kaydetmez. Hesapsız paylaşım; boyutu sınırlandırılmış bir URL, indirilen Markdown dosyası veya cihazın paylaş menüsü üzerinden yapılabilir. Kalıcı herkese açık yayın için GitHub Discussions isteğe bağlıdır. Otomatik ön filtre nihai moderasyon veya güvenlik garantisi değildir." ] },
        { heading: "4. Teknik erişim kayıtları ve GitHub Pages", paragraphs: ["Site statik olarak GitHub Pages üzerinde barındırılmak üzere hazırlanmıştır. Barındırma ve ağ sağlayıcıları güvenlik, hata ayıklama ve hizmet sunumu için IP adresi, zaman damgası, istek yolu ve kullanıcı aracısı gibi standart bağlantı kayıtlarını kendi politikaları kapsamında işleyebilir. ByteQuant araç girdileri bu isteklerin parçası değildir.", "GitHub veya alan adı/ağ sağlayıcısının bağımsız işleme faaliyetleri için ilgili sağlayıcıların güncel gizlilik metinleri geçerlidir." ] },
        { heading: "5. Reklam, analitik ve üçüncü taraf bağlantıları", paragraphs: ["Sayfa düzeninde içerikten açıkça ayrılmış reklam yer tutucuları vardır; etkin AdSense kimliği, reklam betiği veya analitik SDK'sı yoktur. EEA, Birleşik Krallık veya İsviçre'de Google reklam ürünleri etkinleştirilmeden önce Google sertifikalı, IAB TCF ile entegre bir CMP kurulmalı; sağlayıcılar, amaçlar, saklama süreleri ve kişiselleştirme seçenekleri açıklanmalıdır.", "X ve Instagram bağlantıları yalnızca tıkladığınızda üçüncü taraf siteye gider. Bu sağlayıcılar IP adresi ve tarayıcı bilgisi gibi verileri kendi politikalarına göre işleyebilir. Araç girdileri reklam, analitik veya sosyal ağ hedeflemesi için paylaşılmaz." ], links: [{ label: "Google yayıncı CMP gereksinimleri", href: "https://support.google.com/adsense/answer/13554116" }] },
        { heading: "6. Hukuki dayanaklar, saklama ve haklar", paragraphs: ["Açık rızaya bağlı yerel kişiselleştirmenin dayanağı GDPR madde 6(1)(a)'dır ve rıza her an geri çekilebilir. İletişim talepleri, talebin niteliğine göre sözleşme öncesi adımlar veya güvenli ve erişilebilir bir hizmet yürütme yönündeki meşru menfaat kapsamında işlenir. E-posta kayıtları son anlamlı temastan sonra en fazla 12 ay tutulur; hukuki yükümlülük veya uyuşmazlık hâlinde gerekli süre uzayabilir.", "Uygulanabilir olduğu ölçüde erişim, düzeltme, silme, kısıtlama, itiraz, taşınabilirlik ve rızayı geri çekme haklarınız vardır. bytequant@yahoo.com adresine başvurabilir ve yetkili denetim makamına şikâyette bulunabilirsiniz. Araç girdileri sunucuda tutulmadığından bu metinler üzerinde merkezi erişim veya silme işlemi yapılamaz." ] },
        { heading: "7. Uluslararası aktarım, güvenlik, çocuklar ve değişiklikler", paragraphs: ["Statik site GitHub Pages ve ağ altyapısı üzerinden sunulurken teknik bağlantı verileri sağlayıcının altyapısında EEA dışına aktarılabilir. Uygulanabilir olduğunda sağlayıcının veri koruma şartları, standart sözleşme maddeleri veya diğer geçerli güvenceler değerlendirilmelidir. Araç girdileri bu aktarımın parçası değildir.", "Statik mimari ve veri minimizasyonu riski azaltır ancak mutlak güvenlik garantisi vermez. Hizmet özellikle çocuklara yönelik değildir. Önemli politika veya veri akışı değişiklikleri yürürlüğe girmeden önce bu sayfa ve onay arayüzü güncellenir." ], links: [{ label: "GitHub Gizlilik Bildirimi", href: "https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement" }, { label: "AB GDPR metni", href: "https://eur-lex.europa.eu/eli/reg/2016/679/oj" }] },
      ],
      en: [
        { heading: "1. Scope, controller, and contact", paragraphs: ["This policy covers the ByteQuant site, tools, guides, and contact channels. ByteQuant is the controller for this service. Privacy questions and data-subject requests can be sent to bytequant@yahoo.com; only identity and request information needed to answer a request is collected.", "Tool input is not transferred to ByteQuant and cannot be centrally accessed. If you contact us by email, the contact details and message you provide are processed to answer the request and retain necessary records." ] },
        { heading: "2. Tool input, Local Agent, installable app, and browser processing", paragraphs: ["Prompt, text, JSON, CSV, Regex, password, image, PDF, and similar inputs are processed in your browser. They are not sent to ByteQuant servers, linked to an account, or stored in localStorage by default. Refreshing or closing the page removes active-session input.", "Local Agent applies multilingual semantic rules and calls no remote LLM or AI API. Its plan and the latest eight conversation summaries stay in the open tab's sessionStorage. Voice input activates only after the browser verifies on-device processing and never falls back to remote recognition.", "Adding ByteQuant to a home screen or desktop is a browser feature that opens the site in its own window; it is not a separately downloaded Android APK. If an old-Android warning appears, cancel, update the browser, remove the stale ByteQuant shortcut, and reinstall from the current browser menu.", "Copying or downloading creates a new copy on your device. Temporary object URLs used during image/PDF conversion stay in tab memory and are released when a result is cleared or the tab closes. Clipboard history and downloaded files on shared devices remain under your control." ] },
        { heading: "2A. Workstation, encrypted projects, P2P, and recipe links", paragraphs: ["Projects you explicitly save in Workstation stay in the bytequant-workspaces IndexedDB database. Project documents are encrypted with AES-GCM-256 and a non-extractable device key stored in the same database. ByteQuant cannot remotely access the key or project. This protection does not make a compromised device, malicious extension, or hostile same-origin code safe.", "During tool navigation, bytequant:workstation-active:v1, bytequant:workstation-handoff:v1, and the explicitly selected Agent goal in bytequant:workstation-agent-goal:v1 provide temporary bounded same-tab handoff and are cleared on return. File selection, password fields, code execution, and downloads are never automated.", "Serverless collaboration uses WebRTC DataChannel and browser DTLS, with no ByteQuant signaling server, STUN, or TURN. Single-use invitation and answer codes expire after 10 minutes and can contain connectivity candidates. Live sharing is off by default and cannot start until both people compare the same safety code through a separate channel. The code helps detect an active intermediary but is not real-world identity verification. NAT, firewalls, or browser policy may still prevent a connection.", "Recipe links always exclude output and exclude input by default. If you opt in to include input, that data becomes visible in the URL, browser history, clipboard, messaging service, and recipient's device. Never include sensitive, personal, or confidential data in a recipe URL." ] },
        { heading: "3. Cookies, local storage, and consent", paragraphs: ["The current ByteQuant release sets no HTTP cookie, analytics identifier, or advertising tag. bq-consent-v1 remembers your choice for 180 days, while bq-theme is necessary local storage used to deliver the color theme you explicitly request.", "bq-tool-usage-v1 and bq-tool-favorites-v1 activate only after consent. They contain tool slugs, counts, last-use time, or pinned tool IDs—never input, files, passwords, or output. Withdrawing consent deletes both records.", "Cross-tool output handoff stays in bytequant:tool-transfer:v1 in the same tab for at most 20 minutes. Local Agent conversation context and Workstation plan handoff also use sessionStorage only and end with the tab session." ], links: [{ label: "Cookie and local-storage policy", href: "/en/cookies" }] },
        { heading: "3A. Project activity and community sharing", paragraphs: ["The home-page project-health card is static and makes no GitHub API request. If you open its workflow or commit-history links, you visit GitHub, which may process standard connection data under its policy. No tool input, favorites, or usage counts are transferred.", "The community composer pre-screens text in this tab and stores nothing on a ByteQuant server. Account-free sharing uses a size-bounded URL, downloaded Markdown, or the device share menu. GitHub Discussions is optional for durable public publishing. The automatic pre-filter is not final moderation or security assurance." ] },
        { heading: "4. Technical access logs and GitHub Pages", paragraphs: ["The site is designed for static hosting on GitHub Pages. Hosting and network providers may process standard connection records—IP address, timestamp, request path, and user agent—for security and delivery under their own policies. Tool input is not included in those requests.", "Independent processing by GitHub, domain, or network providers is governed by their current privacy notices." ] },
        { heading: "5. Advertising, analytics, and external links", paragraphs: ["The layout includes clearly separated ad placeholders, but no active AdSense identifier, advertising script, or analytics SDK. Before Google advertising products are enabled for the EEA, UK, or Switzerland, a Google-certified CMP integrated with IAB TCF must be configured and vendors, purposes, retention, and personalization choices disclosed.", "X and Instagram receive a request only if you follow their external links and may then process IP and browser data under their own notices. Tool input is never shared for advertising, analytics, or social targeting." ], links: [{ label: "Google publisher CMP requirements", href: "https://support.google.com/adsense/answer/13554116" }] },
        { heading: "6. Legal bases, retention, and rights", paragraphs: ["Optional local personalization relies on GDPR Article 6(1)(a) consent, which can be withdrawn at any time. Contact requests are handled as pre-contract steps where relevant or under the legitimate interest in operating a secure and accessible service. Email records are kept for no more than 12 months after the last meaningful contact unless a legal duty or dispute requires longer.", "Where applicable, you may request access, correction, deletion, restriction, objection, portability, or withdrawal of consent by emailing bytequant@yahoo.com, and may complain to a competent supervisory authority. Tool input is not retained on a server and therefore cannot be centrally accessed or erased." ] },
        { heading: "7. International transfers, security, children, and changes", paragraphs: ["When the static site is delivered through GitHub Pages and network infrastructure, technical connection data may be processed outside the EEA. Where applicable, the provider's data-protection terms, standard contractual clauses, or other valid safeguards must be assessed. Tool input is not part of that transfer.", "Static architecture and minimization reduce risk but cannot guarantee absolute security. The service is not directed specifically to children. Material policy or data-flow changes will be reflected in this page and consent interface before they take effect." ], links: [{ label: "GitHub Privacy Statement", href: "https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement" }, { label: "EU GDPR text", href: "https://eur-lex.europa.eu/eli/reg/2016/679/oj" }] },
      ],
    },
  },
  cookies: {
    eyebrow: { tr: "ÇEREZ VE YEREL DEPOLAMA", en: "COOKIES AND LOCAL STORAGE" },
    title: { tr: "Cihazınızdaki depolamayı amaç, süre ve kontrolle sınırlarız", en: "We limit device storage by purpose, duration, and user control" },
    intro: { tr: "ByteQuant araçları HTTP çerezi gerektirmez. Bu sayfa kullanılan localStorage anahtarlarını, hukuki gerekçelerini ve bunları nasıl yönetebileceğinizi açıklar.", en: "ByteQuant tools require no HTTP cookies. This page explains the localStorage keys in use, why they exist, and how you can control them." },
    updated: { tr: "Son güncelleme: 22 Temmuz 2026", en: "Last updated: July 22, 2026" },
    sections: {
      tr: [
        { heading: "1. Mevcut depolama envanteri", paragraphs: ["bq-consent-v1: Gizlilik seçiminizi, politika sürümünü ve karar zamanını 180 gün saklar. Bu kayıt, tercihinizi hatırlamak ve tekrar tekrar sormamak için zorunludur.", "bq-theme: Sizin seçtiğiniz açık/koyu temayı cihazda hatırlar. Bir hizmet tercihini yerine getirdiği için zorunlu depolama olarak değerlendirilir.", "bq-tool-usage-v1 ve bq-tool-favorites-v1: Yalnızca açık rızayla etkinleşir. Araç slug'ı, açılma sayısı, son kullanım zamanı veya sabitlenen araç kimliklerini tutar; araç girdisi veya çıktısı içermez.", "bytequant:local-agent:v1 ve bytequant:agent-history:v1: Yerel Ajanı açıkça kullandığınızda hedef, plan ve en fazla sekiz konuşma özetini yalnızca mevcut sekmenin sessionStorage alanında tutar; sekme oturumu bitince silinir.", "bytequant-workspaces (IndexedDB): Yalnızca İş İstasyonu'nda açıkça kaydettiğiniz proje belgelerini AES-GCM-256 şifreli olarak ve çıkarılamayan cihaz anahtarını yerel cihazda tutar. Siz projeyi silene veya site verilerini temizleyene kadar kalır; kota tarayıcı tarafından belirlenir.", "bytequant:workstation-active:v1, bytequant:workstation-handoff:v1, bytequant:workstation-agent-plan:v1 ve bytequant:tool-transfer:v1: Etkin proje, Ajan planı veya araçlar arasında aktarmayı seçtiğiniz sınırlı metni aynı sekmenin sessionStorage alanında geçici tutar. Araç aktarımı en fazla 20 dakika, diğer kayıtlar sekme oturumu sonuna kadar kalır."] },
        { heading: "2. Kullanmadığımız teknolojiler", paragraphs: ["Mevcut sürüm HTTP çerezi, cihazlar arası kimlik, parmak izi, piksel, analitik SDK, reklam kimliği veya üçüncü taraf izleme etiketi kullanmaz.", "Reklam yer tutucuları görsel düzen öğeleridir; AdSense ya da başka bir reklam ağına istek göndermez. Kaynak kodda bir yayıncı kimliği bulunmaz."] },
        { heading: "3. Rıza verme, reddetme ve geri çekme", paragraphs: ["İsteğe bağlı yerel kişiselleştirme varsayılan olarak kapalıdır ve önceden işaretlenmez. 'Yalnızca zorunlu' seçeneği, kabul seçeneğiyle aynı katmanda sunulur; reddetmek aracın işlevini azaltmaz.", "Altbilgideki 'Gizlilik tercihleri' düğmesiyle seçiminizi istediğiniz anda değiştirebilirsiniz. Rıza geri çekildiğinde bq-tool-usage-v1 ve bq-tool-favorites-v1 aynı anda silinir. Tarayıcı site verilerini temizlemek tüm yerel kayıtları da kaldırır."] },
        { heading: "4. ePrivacy ve GDPR yaklaşımı", paragraphs: ["ePrivacy Direktifi madde 5(3), kullanıcının cihazında bilgi saklanması veya okunması için kural olarak açık ve kapsamlı bilgiyle rıza ister; yalnızca açıkça talep edilen hizmet için kesinlikle gerekli depolama istisna olabilir.", "GDPR kapsamında rıza özgür, belirli, bilgilendirilmiş ve açık bir olumlu eylemle verilmelidir. Rızayı geri çekmek, vermek kadar kolay olmalıdır. Ulusal ePrivacy uygulama kuralları ayrıca değerlendirilmelidir." ], links: [{ label: "ePrivacy Direktifi madde 5(3)", href: "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002L0058-20091219" }, { label: "EDPB rıza özeti", href: "https://www.edpb.europa.eu/system/files/2026-04/edpb-summary-consent_en.pdf" }] },
        { heading: "5. Gelecekte analitik veya reklam eklenirse", paragraphs: ["Yeni bir amaç, sağlayıcı veya depolama teknolojisi etkinleştirilmeden önce envanter, gizlilik politikası ve rıza arayüzü güncellenmelidir. Önceden verilmiş yerel kişiselleştirme rızası yeni amaçlara genişletilemez.", "Google AdSense EEA, Birleşik Krallık veya İsviçre'de etkinleştirilecekse Google sertifikalı ve IAB TCF ile entegre bir CMP kurulmadan reklam etiketi yüklenmemelidir. ads.txt kaydı yalnızca doğrulanmış yayıncı kimliği alındıktan sonra eklenmelidir." ], links: [{ label: "Google sertifikalı CMP gereksinimi", href: "https://support.google.com/adsense/answer/13554116" }] },
      ],
      en: [
        { heading: "1. Current storage inventory", paragraphs: ["bq-consent-v1: Keeps your privacy choice, policy version, and decision time for 180 days. This record is essential to remember the choice and avoid asking on every visit.", "bq-theme: Remembers the light or dark theme you request. It is treated as essential storage because it delivers an explicit service preference.", "bq-tool-usage-v1 and bq-tool-favorites-v1: Activated only with consent. They keep tool slugs, open count, last-used time, or pinned tool IDs and contain no tool input or output.", "bytequant:local-agent:v1 and bytequant:agent-history:v1: When you explicitly use Local Agent, these tab-scoped values hold the goal, plan, and up to eight conversation summaries. They end with the tab session.", "bytequant-workspaces (IndexedDB): Stores only Workstation projects you explicitly save, as AES-GCM-256 ciphertext, plus a non-extractable device key. It remains until you delete projects or clear site data; the browser controls quota.", "bytequant:workstation-active:v1, bytequant:workstation-handoff:v1, bytequant:workstation-agent-plan:v1, and bytequant:tool-transfer:v1: Temporarily hold a project, Agent plan, or bounded text you choose to pass in the same tab. Tool handoff expires after 20 minutes; other records end with the tab session."] },
        { heading: "2. Technologies we do not use", paragraphs: ["The current release uses no HTTP cookie, cross-device identifier, fingerprint, pixel, analytics SDK, advertising identifier, or third-party tracking tag.", "Advertising placeholders are visual layout elements only. They make no request to AdSense or another ad network, and the source contains no publisher identifier."] },
        { heading: "3. Giving, refusing, and withdrawing consent", paragraphs: ["Optional local personalization is off by default and never pre-ticked. 'Essential only' appears on the same layer as acceptance, and refusing does not reduce tool functionality.", "Use the footer's 'Privacy choices' control at any time. Withdrawing consent deletes bq-tool-usage-v1 and bq-tool-favorites-v1 immediately. Clearing browser site data removes every local record."] },
        { heading: "4. ePrivacy and GDPR approach", paragraphs: ["Article 5(3) of the ePrivacy Directive generally requires consent, after clear and comprehensive information, before storing or reading information on a device; an exception may apply where storage is strictly necessary for an explicitly requested service.", "Under GDPR, consent must be freely given, specific, informed, and expressed by a clear affirmative action. Withdrawal must be as easy as giving consent. National ePrivacy implementation rules must also be assessed." ], links: [{ label: "ePrivacy Directive Article 5(3)", href: "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002L0058-20091219" }, { label: "EDPB consent summary", href: "https://www.edpb.europa.eu/system/files/2026-04/edpb-summary-consent_en.pdf" }] },
        { heading: "5. If analytics or advertising is added later", paragraphs: ["Before a new purpose, provider, or storage technology is activated, the inventory, privacy notice, and consent interface must be updated. Consent for local personalization cannot be stretched to cover a new purpose.", "If Google AdSense is enabled for the EEA, UK, or Switzerland, no ad tag should load until a Google-certified CMP integrated with IAB TCF is configured. An ads.txt record should be added only after a verified publisher identifier exists." ], links: [{ label: "Google certified CMP requirement", href: "https://support.google.com/adsense/answer/13554116" }] },
      ],
    },
  },
  terms: {
    eyebrow: { tr: "KULLANIM KOŞULLARI", en: "TERMS OF USE" },
    title: { tr: "Araçları güvenli, yasal ve bilinçli kullanın", en: "Use the tools safely, lawfully, and deliberately" },
    intro: { tr: "ByteQuant'ı kullanarak bu koşulları kabul etmiş olursunuz. Araçlar genel amaçlı yardımcı hizmetlerdir; profesyonel danışmanlığın veya zorunlu doğrulamanın yerini almaz.", en: "By using ByteQuant, you agree to these terms. The tools are general-purpose utilities and do not replace professional advice or mandatory verification." },
    updated: { tr: "Yürürlük tarihi: 22 Temmuz 2026", en: "Effective date: July 22, 2026" },
    sections: {
      tr: [
        { heading: "1. Hizmetin kapsamı", paragraphs: ["ByteQuant, tarayıcı içinde çalışan ücretsiz prompt, metin, veri, görsel, PDF ve güvenlik araçları ile bilgilendirici rehberler sunar. Yerel Ajan bu araçlar için açıklanabilir plan önerileri üretir; büyük dil modeli, uzman görüşü, güvenlik onayı veya kimlik doğrulama değildir. Hizmet üyelik gerektirmez.", "Araçların cihazınızda çalışması, tarayıcı sürümü ve JavaScript, Canvas, Web Crypto ve tarayıcı belleği gibi özelliklerin desteğine bağlıdır. Kurulum özelliği bir tarayıcı PWA'sıdır; ByteQuant APK veya mağaza uygulaması dağıtmaz ve tarayıcının Android sarmalayıcı uyumluluğunu garanti edemez." ] },
        { heading: "2. İzin verilen kullanım", paragraphs: ["Hizmeti yasal amaçlarla, üçüncü kişilerin haklarına saygı göstererek kullanmalısınız. İşlediğiniz veri için gerekli yetki ve hukuki dayanağa sahip olmak sizin sorumluluğunuzdadır."], bullets: ["Zararlı yazılım, kimlik avı veya yetkisiz erişim hazırlamak yasaktır.", "Başkasına ait kişisel veya gizli veriyi yetkisiz işlemek yasaktır.", "Hizmeti bozacak otomasyon, aşırı trafik veya güvenlik engeli aşma girişimi yasaktır.", "Çıktıyı yanıltıcı biçimde profesyonel onay veya yasal uygunluk belgesi olarak sunmak yasaktır."] },
        { heading: "3. Sonuçların doğrulanması", paragraphs: ["Araçlar açıklanan kurallar ve tarayıcı API'leriyle sonuç üretir. Hatalı girdi, bağlam eksikliği, tarayıcı farkı veya yöntem sınırı hatalı sonuca yol açabilir. Sonucu kullanmadan önce doğrulamak kullanıcı sorumluluğundadır.", "Özellikle kişisel veri maskeleme, Regex, güvenlik ve dönüştürme sonuçları kritik bir sistemde kullanılmadan önce örnek test ve insan incelemesinden geçirilmelidir. PDF sayfası kopyalama dijital imzayı koruma garantisi vermez; şifre koruması aşılmaz ve görsel dönüşümü OCR ya da gerçek vektörleştirme değildir." ] },
        { heading: "3A. İş İstasyonu ve eşler arası paylaşım", paragraphs: ["Görsel plan, Yerel Ajan önerisi, otomatik veri aktarımı ve P2P senkronizasyonu kullanıcı incelemesinin yerini almaz. Bir düğümü açmak, çalıştırmak, dosya seçmek, parola girmek veya indirmek sizin açık eyleminizi gerektirir.", "Oda ve tarif kodlarını yalnızca yetkili kişilerle paylaşın. Bağlantı kodları ağ bilgisi, dahil etmeyi seçtiğiniz tarif girdileri ise hassas içerik taşıyabilir. Güvenlik kodunu ayrı kanalda karşılaştırın ve yalnızca gerekli süre boyunca canlı paylaşımı açık tutun. Tarayıcı kotası, cihaz arızası veya site verilerini temizleme nedeniyle kayıp yaşanabileceğinden önemli projelerin hassas veriden arındırılmış yedeğini kendiniz yönetin." ] },
        { heading: "4. Profesyonel danışmanlık değildir", paragraphs: ["ByteQuant hukuki, finansal, tıbbi, siber güvenlik denetimi veya mevzuat uygunluk hizmeti sunmaz. KVKK ve GDPR açıklamaları genel bilgidir. Somut olaylar için yetkin uzmana başvurun.", "Parola ve SHA-256 araçları teknik yardımcıdır; kurumunuzun kimlik, anahtar yönetimi veya parola saklama politikasının yerini almaz." ] },
        { heading: "5. Fikrî haklar ve bağlantılar", paragraphs: ["ByteQuant markası, özgün arayüzü ve içerikleri ilgili fikrî haklarla korunur. İçerikten kısa alıntı, kaynak ve bağlantı verilerek yapılabilir; bütün içeriğin kopyalanması veya yanıltıcı biçimde yeniden yayımlanması yasaktır.", "Dış bağlantılar kolaylık amacıyla sunulur. Üçüncü taraf sitelerin içerik, güvenlik ve politikalarından ByteQuant sorumlu değildir." ] },
        { heading: "6. Garanti ve sorumluluk sınırı", paragraphs: ["Hizmet makul özenle 'olduğu gibi' sunulur. Kesintisiz çalışma, belirli amaca uygunluk veya hatasız sonuç garantisi verilmez. Uygulanabilir hukukun izin verdiği ölçüde, araç sonucuna dayanılarak oluşan dolaylı kayıp ve zararlardan ByteQuant sorumlu tutulamaz.", "Bu hüküm kanunen sınırlandırılamayan tüketici veya veri sahibi haklarını ortadan kaldırmaz." ] },
        { heading: "7. Değişiklik ve iletişim", paragraphs: ["Koşullar ürün veya hukuki gereksinimler değiştiğinde güncellenebilir. Önemli değişiklikler yeni yürürlük tarihiyle bu sayfada yayımlanır. Sorular bytequant@yahoo.com adresine gönderilebilir." ] },
      ],
      en: [
        { heading: "1. Service scope", paragraphs: ["ByteQuant provides free in-browser prompt, text, data, image, PDF, and security tools plus educational guides. Local Agent suggests explainable plans across those tools; it is not a large language model, expert opinion, security approval, or identity verification. No account is required.", "On-device operation depends on browser support for JavaScript, Canvas, Web Crypto, available memory, and related capabilities. Installation is a browser PWA feature; ByteQuant distributes no APK or app-store package and cannot guarantee the browser's Android wrapper compatibility." ] },
        { heading: "2. Acceptable use", paragraphs: ["Use the service lawfully and respect third-party rights. You are responsible for authority and legal basis to process any data you enter."], bullets: ["Do not prepare malware, phishing, or unauthorized access.", "Do not process another person's confidential or personal data without authority.", "Do not disrupt the service, generate abusive traffic, or bypass safeguards.", "Do not present output as professional approval or a legal compliance certificate."] },
        { heading: "3. Verify output", paragraphs: ["Tools use disclosed rules and browser APIs. Bad input, missing context, browser differences, and method limitations can produce errors. Verify output before relying on it.", "Masking, Regex, security, and conversion results should be tested on representative samples and reviewed by a person before use in a critical system. Copying PDF pages does not guarantee preservation of digital signatures; encryption is never bypassed, and image conversion is neither OCR nor true vectorization." ] },
        { heading: "3A. Workstation and peer sharing", paragraphs: ["Visual plans, Local Agent suggestions, automatic data passing, and P2P synchronization never replace user review. Opening or running a node, choosing a file, entering a password, or downloading requires your explicit action.", "Share room and recipe codes only with authorized people. Connection codes can expose network information, while recipe input you opt to include can expose sensitive content. Compare the safety code through another channel and keep live sharing enabled only as long as needed. Browser quota, device failure, or clearing site data can cause loss, so you are responsible for privacy-safe backups of important projects." ] },
        { heading: "4. Not professional advice", paragraphs: ["ByteQuant does not provide legal, financial, medical, security-audit, or regulatory-compliance services. KVKK and GDPR content is general information. Consult qualified professionals for specific cases.", "Password and SHA-256 utilities do not replace organizational identity, key-management, or password-storage policies." ] },
        { heading: "5. Intellectual property and links", paragraphs: ["The ByteQuant brand, original interface, and content are protected by applicable rights. Short quotations may be used with attribution and a link; full copying or misleading republication is prohibited.", "External links are provided for convenience. ByteQuant is not responsible for third-party content, security, or policies." ] },
        { heading: "6. Warranty and liability", paragraphs: ["The service is provided with reasonable care on an 'as is' basis. We do not guarantee uninterrupted operation, fitness for a particular purpose, or error-free output. To the extent allowed by law, ByteQuant is not liable for indirect loss caused by reliance on tool output.", "Nothing here removes consumer or data-subject rights that cannot legally be limited." ] },
        { heading: "7. Changes and contact", paragraphs: ["Terms may change with the product or legal requirements. Material changes will appear here with a new effective date. Questions can be sent to bytequant@yahoo.com." ] },
      ],
    },
  },
  contact: {
    eyebrow: { tr: "İLETİŞİM", en: "CONTACT" },
    title: { tr: "Sorun, öneri ve düzeltmeleri doğrudan bize iletin", en: "Send bugs, suggestions, and corrections directly to us" },
    intro: { tr: "Araç hataları, erişilebilirlik sorunları, içerik düzeltmeleri ve iş birliği önerileri için e-posta ve sosyal kanallarımızı kullanabilirsiniz. Hassas metni veya gerçek kişisel veriyi mesaja eklemeyin.", en: "Use email or our social channels for tool bugs, accessibility issues, content corrections, and collaboration ideas. Do not include sensitive text or real personal data in your message." },
    sections: {
      tr: [
        { heading: "E-posta", paragraphs: ["Genel destek, gizlilik talepleri ve içerik düzeltmeleri: bytequant@yahoo.com. Mesajınızda ilgili sayfanın bağlantısını, tarayıcı türünü ve sorunu yeniden oluşturmak için gerekli adımları yazmanız çözümü hızlandırır.", "Parola, API anahtarı, kimlik numarası, müşteri kaydı veya gizli belge göndermeyin. Sorunu anonim örnek veriyle anlatın." ] },
        { heading: "Sosyal medya", paragraphs: ["Kısa duyurular ve yeni araç güncellemeleri için X hesabımız @byte_quant, Instagram hesabımız @byte.quant adresindedir. Hesap veya gizlilik talepleri sosyal medya yerine e-posta üzerinden iletilmelidir." ] },
        { heading: "İyi bir hata bildirimi nasıl yazılır?", paragraphs: ["Sorunun ne olduğunu, ne beklediğinizi ve gerçekte ne olduğunu kısa biçimde açıklayın. Mümkünse hassas olmayan örnek girdi kullanın. Ekran görüntüsü gönderecekseniz kişisel verileri önce maskeleyin."], bullets: ["Sayfa veya araç adı", "Tarayıcı ve cihaz türü", "Yeniden oluşturma adımları", "Beklenen ve gerçekleşen sonuç", "Hassas veri içermeyen örnek"] },
        { heading: "Yanıt yaklaşımı", paragraphs: ["Mesajları makul süre içinde incelemeyi hedefliyoruz; kesin yanıt süresi taahhüt etmiyoruz. Güvenlik açığı bildirimleri önceliklendirilir. Kötüye kullanım, spam veya yasa dışı talep içeren mesajlara yanıt verilmeyebilir." ] },
      ],
      en: [
        { heading: "Email", paragraphs: ["General support, privacy requests, and content corrections: bytequant@yahoo.com. Include the relevant page, browser type, and steps needed to reproduce the issue.", "Do not send passwords, API keys, identity numbers, customer records, or confidential files. Describe the issue with anonymous sample data." ] },
        { heading: "Social media", paragraphs: ["For short announcements and tool updates, follow @byte_quant on X and @byte.quant on Instagram. Account or privacy requests should be sent by email rather than social media." ] },
        { heading: "Writing a useful bug report", paragraphs: ["Briefly explain what happened, what you expected, and what actually occurred. Use a non-sensitive sample when possible and mask personal data in screenshots."], bullets: ["Page or tool name", "Browser and device type", "Reproduction steps", "Expected and actual result", "A non-sensitive example"] },
        { heading: "Response approach", paragraphs: ["We aim to review messages within a reasonable period but do not promise a fixed response time. Security reports are prioritized. Spam, abuse, and unlawful requests may not receive a response." ] },
      ],
    },
  },
  faq: {
    eyebrow: { tr: "SIK SORULAN SORULAR", en: "FREQUENTLY ASKED QUESTIONS" },
    title: { tr: "ByteQuant hakkında açık, kısa cevaplar", en: "Clear, concise answers about ByteQuant" },
    intro: { tr: "Araçların çalışma biçimi, gizlilik, sonuçların sınırı ve site politikaları hakkında en sık sorulan soruları bir araya getirdik.", en: "Answers about how the tools work, privacy, output limitations, and site policies." },
    sections: {
      tr: [
        { heading: "Araç girdileri nereye gider?", paragraphs: ["Girdiler etkin tarayıcı sekmesinde işlenir ve ByteQuant sunucularına gönderilmez. Araçlar girdiyi localStorage içine kaydetmez. Tema ve araç kullanım sayacı kişisel içerik taşımayan ayrı yerel değerlerdir; kullanım sayacı yalnızca ana sayfadaki kişisel kısa yolları sıralar." ] },
        { heading: "Araçlar gerçekten ücretsiz mi?", paragraphs: ["Evet. Temel araçların tamamı ücretsiz ve üyeliksizdir. Site gelecekte açıkça işaretlenmiş reklamlarla desteklenebilir; araç sonucunu ücret veya reklam ilişkisi belirlemez." ] },
        { heading: "Neden bazı skorlar yaklaşık?", paragraphs: ["Token ve okunabilirlik gibi ölçüler model veya dil özelliğine göre değişir. Aracın kullandığı şeffaf tahmin hızlı planlama içindir; kesin model tokenizer sonucu veya uzman dil değerlendirmesi değildir." ] },
        { heading: "KVKK/GDPR Veri Maskeleyici tam uygunluk sağlar mı?", paragraphs: ["Hayır. Araç yaygın desenleri bulur ancak isim, nadir olay ve dolaylı tanımlayıcı gibi bağlamsal kişisel verilerin tamamını yakalayamaz. İnsan kontrolü ve gerektiğinde uzman görüşü zorunludur." ] },
        { heading: "ByteQuant yapay zekâ modeline bağlanıyor mu?", paragraphs: ["Hayır. Araçlar ve Yerel Ajan uzak LLM veya başka bir yapay zekâ API'si çağırmaz. Yerel Ajan büyük dil modeli değildir; sürümlenmiş semantik puanlama ve açıklanabilir plan kuralları kullanır. Plan yalnızca açık sekmenin sessionStorage alanında tutulur." ] },
        { heading: "Büyük dosyaları kullanabilir miyim?", paragraphs: ["Araçlar küçük ve orta büyüklükte metin ve dosyalar için tasarlanmıştır. Tarayıcı belleğini korumak için araç sayfasında açıklanan boyut, piksel, sayfa ve adet sınırları vardır. Çok büyük PDF, görsel veya iç içe veri için denetlenmiş masaüstü/komut satırı aracı daha uygun olabilir." ] },
        { heading: "Tarayıcı desteği nedir?", paragraphs: ["Güncel Chrome, Edge, Firefox ve Safari sürümleri önerilir. Parola, UUID ve SHA-256 için güvenli bağlamda Web Crypto; görsel araçları için Canvas ve ilgili kodlayıcı desteği gerekir. Desteklenen WebP/SVG ayrıntıları ve kullanılabilir bellek tarayıcıya göre değişebilir." ] },
        { heading: "Android neden eski sürüm uyarısı gösterebilir?", paragraphs: ["ByteQuant bir APK değil PWA'dır. Android uygulama sarmalayıcısını Chrome/Edge gibi tarayıcı üretir. Uyarı görürseniz onaylamayın; tarayıcıyı güncelleyin, önceden yüklenmiş ByteQuant kısayolunu kaldırın, sayfayı yenileyin ve güncel tarayıcı menüsünden yeniden kurun." ] },
        { heading: "Yeni özetleyici bir yapay zekâ modeli mi?", paragraphs: ["Hayır. Yerel özetleyici kaynak cümlelerini sözcük sıklığıyla puanlayan açıklanabilir çıkarımsal bir yöntemdir. Yeni cümle üretmez, bağlamı insan gibi anlamaz ve kritik ayrıntıyı kaçırabilir; sonucu kaynakla karşılaştırın." ] },
        { heading: "Dosya hash'i veya CSP denetimi güvenlik onayı verir mi?", paragraphs: ["Hayır. SHA-256 bayt bütünlüğünü karşılaştırır; dosyanın güvenliğini veya kaynağın kimliğini kanıtlamaz. CSP denetimi ise sınırlı yapısal sinyalleri bulur ve gerçek sayfada Report-Only testi gerektirir." ] },
        { heading: "Hata veya düzeltme nasıl bildirilir?", paragraphs: ["bytequant@yahoo.com adresine sayfa bağlantısını ve hassas veri içermeyen örneği gönderin. X: @byte_quant, Instagram: @byte.quant. Gizlilik taleplerini e-posta ile iletin." ] },
      ],
      en: [
        { heading: "Where does tool input go?", paragraphs: ["Input is processed in the active browser tab and is not sent to ByteQuant servers. Tools do not store input in localStorage. Theme and tool-usage counts are separate local values with no personal content; the usage count only ranks personal home-page shortcuts." ] },
        { heading: "Are the tools really free?", paragraphs: ["Yes. All core tools are free and require no account. The site may later be supported by clearly labeled advertising, which will not influence tool output." ] },
        { heading: "Why are some scores estimates?", paragraphs: ["Token and readability measures vary by model or language. Transparent estimates are intended for planning, not as an exact model tokenizer or expert linguistic assessment." ] },
        { heading: "Does the KVKK/GDPR masker guarantee compliance?", paragraphs: ["No. It finds common patterns but cannot catch every name, rare event, or indirect identifier. Human review and, when appropriate, expert advice remain necessary." ] },
        { heading: "Does ByteQuant call an AI model?", paragraphs: ["No. Tools and Local Agent call no remote LLM or AI API. Local Agent is not a large language model; it uses versioned semantic scoring and explainable planning rules. The plan stays only in the open tab's sessionStorage." ] },
        { heading: "Can I use very large files?", paragraphs: ["The tools are designed for small and medium text and files. Tool pages disclose size, pixel, page, and count limits that protect browser memory. Audited desktop or command-line tools may be better for very large PDFs, images, or deeply nested data." ] },
        { heading: "Which browsers are supported?", paragraphs: ["Current Chrome, Edge, Firefox, and Safari are recommended. Password, UUID, and SHA-256 features need Web Crypto in a secure context; image tools require Canvas and the relevant encoder. WebP/SVG details and available memory vary by browser." ] },
        { heading: "Why can Android show an old-version warning?", paragraphs: ["ByteQuant is a PWA, not an APK. The browser creates the Android app wrapper. If you see the warning, do not accept it: update the browser, remove any previously installed ByteQuant shortcut, reload the page, and reinstall from the current browser menu." ] },
        { heading: "Is the new summarizer an AI model?", paragraphs: ["No. The local summarizer is an explainable extractive method that scores source sentences from word frequency. It writes no new sentence, does not understand context like a person, and can miss critical detail; compare output with the source." ] },
        { heading: "Does a file hash or CSP audit provide security approval?", paragraphs: ["No. SHA-256 compares byte integrity but does not prove safety or source identity. The CSP audit finds a bounded set of structural signals and still requires Report-Only testing on the real site." ] },
        { heading: "How do I report a bug or correction?", paragraphs: ["Email bytequant@yahoo.com with the page link and a non-sensitive example. X: @byte_quant; Instagram: @byte.quant. Use email for privacy requests." ] },
      ],
    },
  },
};
