import type { Locale } from "./site";

export type InfoKey = "about" | "privacy" | "terms" | "contact" | "faq";
type Localized<T> = Record<Locale, T>;

export type InfoSection = { heading: string; paragraphs: string[]; bullets?: string[] };
export type InfoContent = {
  eyebrow: Localized<string>;
  title: Localized<string>;
  intro: Localized<string>;
  updated?: Localized<string>;
  sections: Localized<InfoSection[]>;
};

export const info: Record<InfoKey, InfoContent> = {
  about: {
    eyebrow: { tr: "BYTEQUANT HAKKINDA", en: "ABOUT BYTEQUANT" },
    title: { tr: "Dijital işleri daha özel, açık ve erişilebilir hale getiriyoruz", en: "Making digital work more private, transparent, and accessible" },
    intro: { tr: "ByteQuant; prompt, metin, veri ve güvenlik görevlerini tarayıcı içinde tamamlamaya odaklanan bağımsız bir web projesidir. Amacımız büyük iddialar değil, günlük işlerde güvenilir küçük araçlar ve yöntemini açıklayan içerikler sunmaktır.", en: "ByteQuant is an independent web project focused on completing prompt, text, data, and security tasks inside the browser. Our goal is not grand claims, but dependable small tools and content that explains the method." },
    sections: {
      tr: [
        { heading: "Neden ByteQuant var?", paragraphs: ["Basit bir metin dönüşümü için bile kullanıcıdan hesap, dosya yükleme veya uzak sunucu erişimi isteyen çok sayıda ürün var. Oysa kelime sayımı, JSON doğrulama, kişisel veri desenlerini maskeleme ve SHA-256 özeti üretme gibi görevler modern bir tarayıcıda güvenli biçimde yapılabilir. ByteQuant bu görevleri gereksiz veri yolculuğu olmadan çözmek için kuruldu.", "Ürün, 'client-side' ifadesini pazarlama etiketi olarak değil tasarım sınırı olarak ele alır. Temel araç girdileri sunucuya gönderilmez; kullanılan yöntem ve yaklaşık sonuçlar araç sayfalarında açıklanır." ] },
        { heading: "Misyonumuz ve ürün ilkelerimiz", paragraphs: ["Misyonumuz, teknik ve teknik olmayan kullanıcıların hassas metinlerle daha bilinçli çalışmasını sağlamak; tekrarlanan küçük işleri hızlı, ücretsiz ve anlaşılır araçlarla kolaylaştırmaktır."], bullets: ["Sunucu gerektirmeyen işi cihazda tutmak", "Her aracın ne yaptığını ve ne yapmadığını açıklamak", "Kayıt veya üyeliği temel kullanıma engel yapmamak", "Erişilebilir, mobil uyumlu ve hızlı bir deneyim sunmak", "Hata ve düzeltme bildirimlerine açık olmak"] },
        { heading: "Uzmanlık ve editoryal yaklaşım", paragraphs: ["ByteQuant içeriği web geliştirme, tarayıcı güvenliği, veri işleme ve prompt tasarımı uygulamalarına dayanır. Hukuki konularda kesin uygunluk iddiası üretmeyiz. KVKK ve GDPR ile ilgili içerikler genel bilgilendirme sağlar; somut yükümlülükler için yetkin hukuk ve veri koruma uzmanı görüşü gerekir.", "Makaleler ürün davranışıyla karşılaştırılır, önemli yöntem sınırları metinde belirtilir ve değişiklik tarihi görünür tutulur. Bir teknik hata, eksik açıklama veya düzeltme talebi için bytequant@yahoo.com adresi kullanılabilir." ] },
        { heading: "İş modeli ve bağımsızlık", paragraphs: ["ByteQuant araçları ücretsizdir. Site gelecekte açıkça işaretlenmiş reklam alanlarıyla desteklenebilir. Reklam, editoryal sıralamayı veya araç sonucunu belirlemez. Ücretli tanıtım yayımlanırsa içerikten ayrı ve anlaşılır biçimde etiketlenir.", "Şu an ekip üyesi veya kurucu hakkında doğrulanabilir kişisel biyografi yayımlamadığımız için hayalî unvan ve deneyim iddiası kullanmıyoruz. Güveni, ürünün gözlemlenebilir davranışı, açık politikaları ve ulaşılabilir iletişim kanalı üzerinden kurmayı tercih ediyoruz." ] },
      ],
      en: [
        { heading: "Why ByteQuant exists", paragraphs: ["Many products require an account, upload, or remote server even for simple transformations. Yet tasks such as word counting, JSON validation, pattern masking, and SHA-256 digests can run in a modern browser. ByteQuant was created to solve those jobs without unnecessary data travel.", "We treat client-side operation as a design boundary, not a marketing label. Core tool inputs are not sent to a server, and each tool explains its method and estimates." ] },
        { heading: "Mission and product principles", paragraphs: ["Our mission is to help technical and non-technical users work more deliberately with sensitive text and finish recurring small tasks with free, understandable tools."], bullets: ["Keep server-free work on-device", "Explain what each tool does and does not do", "Do not gate core use behind an account", "Build for accessibility, mobile use, and speed", "Welcome corrections and bug reports"] },
        { heading: "Expertise and editorial approach", paragraphs: ["ByteQuant content draws on web development, browser security, data processing, and prompt design practices. We do not claim automatic legal compliance. KVKK and GDPR articles are general information; specific obligations require qualified legal and data-protection advice.", "Articles are checked against product behavior, limitations are stated, and update dates are visible. Corrections can be sent to bytequant@yahoo.com." ] },
        { heading: "Business model and independence", paragraphs: ["ByteQuant tools are free. The site may later be supported by clearly labeled advertising. Advertising does not determine editorial ranking or tool output; sponsored material would be separated and labeled.", "We do not publish invented titles or biographies when a verified personal profile is unavailable. Trust should come from observable product behavior, clear policies, and reachable contact channels." ] },
      ],
    },
  },
  privacy: {
    eyebrow: { tr: "GİZLİLİK POLİTİKASI", en: "PRIVACY POLICY" },
    title: { tr: "Veri akışını açık ve mümkün olduğunca kısa tutuyoruz", en: "We keep data flows clear and as short as possible" },
    intro: { tr: "Bu politika, bytequant.org ziyaret edildiğinde hangi bilgilerin işlendiğini ve tarayıcı içi araçların nasıl çalıştığını açıklar. Mevcut sürümde araç girdileri ByteQuant sunucularına gönderilmez.", en: "This policy explains what information is processed when you visit bytequant.org and how the in-browser tools work. In the current version, tool inputs are not sent to ByteQuant servers." },
    updated: { tr: "Son güncelleme: 14 Temmuz 2026", en: "Last updated: July 14, 2026" },
    sections: {
      tr: [
        { heading: "1. Kapsam ve veri sorumlusu iletişimi", paragraphs: ["Bu politika ByteQuant web sitesi, araç sayfaları, rehberler ve iletişim kanalları için geçerlidir. Gizlilik soruları ve veri sahibi başvuruları bytequant@yahoo.com adresine iletilebilir. Başvuruda kimliğinizi doğrulamak için yalnızca gerekli bilgiler istenebilir.", "ByteQuant bağımsız bir web projesidir. Bu metin genel şeffaflık sağlar; uygulanabilir hukuki yükümlülükler hizmetin fiilî işletme ve yerleşim koşullarına göre ayrıca değerlendirilmelidir." ] },
        { heading: "2. Araç girdileri ve client-side işleme", paragraphs: ["Prompt, metin, JSON, CSV, Regex, parola veya benzeri araç girdileri tarayıcınızda işlenir. Bu girdiler ByteQuant sunucusuna gönderilmez, hesapla ilişkilendirilmez ve varsayılan olarak localStorage içine kaydedilmez. Sayfayı yenilemek veya kapatmak etkin oturumdaki girdiyi kaldırır.", "Kopyalama ve indirme işlemleri sizin cihazınızda yeni bir veri kopyası oluşturur. Paylaşılan cihazlarda pano geçmişi ve indirilen dosyalar kullanıcı sorumluluğundadır." ] },
        { heading: "3. Yerel tercihler ve araç kullanım sayacı", paragraphs: ["Açık/koyu tema tercihi bq-theme anahtarıyla, araç sayfalarının açılma sayısı ise bq-tool-usage-v1 anahtarıyla tarayıcınızın localStorage alanında tutulabilir. Kullanım sayacı yalnızca araç slug'ı, sayaç ve son kullanım zamanını içerir; araç girdisini, dosyayı, parolayı veya üretilen çıktıyı içermez ve sunucuya gönderilmez.", "Bu yerel değerler ana sayfadaki kişisel 'En Çok Kullanılan Araçlar' kısa yollarını ve tema seçimini sağlar. Tarayıcınızın site verilerini temizleyerek ikisini de silebilirsiniz. Mevcut sürüm zorunlu olmayan analitik veya reklam çerezi yerleştirmez; bu durum değişirse politika ve gerekli onay arayüzü önceden güncellenecektir." ] },
        { heading: "4. Teknik erişim kayıtları ve GitHub Pages", paragraphs: ["Site statik olarak GitHub Pages üzerinde barındırılmak üzere hazırlanmıştır. Barındırma ve ağ sağlayıcıları güvenlik, hata ayıklama ve hizmet sunumu için IP adresi, zaman damgası, istek yolu ve kullanıcı aracısı gibi standart bağlantı kayıtlarını kendi politikaları kapsamında işleyebilir. ByteQuant araç girdileri bu isteklerin parçası değildir.", "GitHub veya alan adı/ağ sağlayıcısının bağımsız işleme faaliyetleri için ilgili sağlayıcıların güncel gizlilik metinleri geçerlidir." ] },
        { heading: "5. Reklam ve üçüncü taraf hizmetleri", paragraphs: ["Sayfa düzeninde reklam için ayrılmış, içerikten açıkça ayrılan alanlar bulunur; mevcut kaynak pakette etkin bir reklam kimliği veya reklam betiği yoktur. Google AdSense veya başka bir hizmet etkinleştirilirse çerezler, kişiselleştirme, onay yönetimi, sağlayıcı listesi ve red seçenekleri bu politikaya eklenmeden reklam yayına alınmamalıdır.", "Araç girdileri reklam hedefleme amacıyla paylaşılmamalı ve reklam bileşenleri araç çalışma alanından teknik olarak ayrılmalıdır." ] },
        { heading: "6. KVKK ve GDPR kapsamındaki haklar", paragraphs: ["Uygulanabilir olduğu ölçüde bilgi talep etme, erişim, düzeltme, silme, işlemeyi sınırlama, itiraz ve veri taşınabilirliği haklarınız olabilir. ByteQuant araç girdilerini sunucuda tutmadığı için bu metinler üzerinde merkezi erişim veya silme işlemi yapılamaz; veri yalnızca sizin cihazınızda bulunur.", "Bir talebi e-posta ile iletebilirsiniz. Yetkili denetim makamına şikâyet hakkınız saklıdır. Hakların kapsamı, bulunduğunuz yer ve işlemenin hukuki niteliğine göre değişebilir." ] },
        { heading: "7. Güvenlik, çocuklar ve değişiklikler", paragraphs: ["Statik mimari ve veri minimizasyonu riski azaltır ancak hiçbir internet hizmeti mutlak güvenlik garantisi vermez. Hassas metinleri ortak cihazlarda kullanmamanızı, tarayıcıyı güncel tutmanızı ve çıktıları dikkatle yönetmenizi öneririz.", "Hizmet özellikle çocuklara yönelik değildir. Önemli politika değişiklikleri bu sayfada yeni tarih ve anlaşılır açıklamayla yayımlanır." ] },
      ],
      en: [
        { heading: "1. Scope and contact", paragraphs: ["This policy covers the ByteQuant site, tools, guides, and contact channels. Privacy questions and data-subject requests can be sent to bytequant@yahoo.com. Only information needed to verify and answer a request may be requested.", "ByteQuant is an independent web project. This notice provides transparency; specific legal duties depend on actual operation and establishment." ] },
        { heading: "2. Tool input and client-side processing", paragraphs: ["Prompt, text, JSON, CSV, Regex, password, and similar inputs are processed in your browser. They are not sent to ByteQuant servers, linked to an account, or stored in localStorage by default. Refreshing or closing the page removes active-session input.", "Copying or downloading creates a new copy on your device. Clipboard history and downloaded files on shared devices remain under your control." ] },
        { heading: "3. Local preferences and tool-usage counts", paragraphs: ["The light/dark theme may be stored under bq-theme, while tool-page visit counts may be stored under bq-tool-usage-v1 in localStorage. Usage records contain only a tool slug, count, and last-used time; they contain no tool input, file, password, or generated output and are not sent to a server.", "These local values power the personal 'Most Used Tools' shortcuts and theme choice. You can remove both by clearing site data. The current version does not set non-essential analytics or advertising cookies; if that changes, this policy and any required consent controls will be updated before activation." ] },
        { heading: "4. Technical access logs and GitHub Pages", paragraphs: ["The site is designed for static hosting on GitHub Pages. Hosting and network providers may process standard connection records—IP address, timestamp, request path, and user agent—for security and delivery under their own policies. Tool input is not included in those requests.", "Independent processing by GitHub, domain, or network providers is governed by their current privacy notices." ] },
        { heading: "5. Advertising and third parties", paragraphs: ["The layout includes clearly separated reserved advertising areas; the delivered source package contains no active ad identifier or ad script. Before Google AdSense or another service is activated, cookies, personalization, consent management, vendors, and refusal options must be documented here.", "Tool input should never be shared for advertising, and ad components should remain technically separated from the workbench." ] },
        { heading: "6. GDPR and KVKK rights", paragraphs: ["Where applicable, you may have rights to information, access, correction, deletion, restriction, objection, and portability. Because ByteQuant does not retain tool input on a server, it cannot centrally access or delete that text; it remains on your device.", "Requests can be emailed to us, and you may complain to a competent supervisory authority. Exact rights depend on location and legal context." ] },
        { heading: "7. Security, children, and changes", paragraphs: ["Static architecture and minimization reduce risk but cannot guarantee absolute security. Avoid sensitive work on shared devices, keep your browser updated, and manage copied output carefully.", "The service is not directed specifically to children. Material policy changes will be posted here with a new date and clear explanation." ] },
      ],
    },
  },
  terms: {
    eyebrow: { tr: "KULLANIM KOŞULLARI", en: "TERMS OF USE" },
    title: { tr: "Araçları güvenli, yasal ve bilinçli kullanın", en: "Use the tools safely, lawfully, and deliberately" },
    intro: { tr: "ByteQuant'ı kullanarak bu koşulları kabul etmiş olursunuz. Araçlar genel amaçlı yardımcı hizmetlerdir; profesyonel danışmanlığın veya zorunlu doğrulamanın yerini almaz.", en: "By using ByteQuant, you agree to these terms. The tools are general-purpose utilities and do not replace professional advice or mandatory verification." },
    updated: { tr: "Yürürlük tarihi: 14 Temmuz 2026", en: "Effective date: July 14, 2026" },
    sections: {
      tr: [
        { heading: "1. Hizmetin kapsamı", paragraphs: ["ByteQuant, tarayıcı içinde çalışan ücretsiz prompt, metin, veri ve güvenlik araçları ile bilgilendirici rehberler sunar. Hizmet üyelik gerektirmez. İşlevler, içerik ve kullanılabilirlik zaman içinde geliştirilebilir veya değiştirilebilir.", "Araçların cihazınızda çalışması, tarayıcı sürümü ve JavaScript/Web Crypto gibi özelliklerin desteğine bağlıdır." ] },
        { heading: "2. İzin verilen kullanım", paragraphs: ["Hizmeti yasal amaçlarla, üçüncü kişilerin haklarına saygı göstererek kullanmalısınız. İşlediğiniz veri için gerekli yetki ve hukuki dayanağa sahip olmak sizin sorumluluğunuzdadır."], bullets: ["Zararlı yazılım, kimlik avı veya yetkisiz erişim hazırlamak yasaktır.", "Başkasına ait kişisel veya gizli veriyi yetkisiz işlemek yasaktır.", "Hizmeti bozacak otomasyon, aşırı trafik veya güvenlik engeli aşma girişimi yasaktır.", "Çıktıyı yanıltıcı biçimde profesyonel onay veya yasal uygunluk belgesi olarak sunmak yasaktır."] },
        { heading: "3. Sonuçların doğrulanması", paragraphs: ["Araçlar açıklanan kurallar ve tarayıcı API'leriyle sonuç üretir. Hatalı girdi, bağlam eksikliği, tarayıcı farkı veya yöntem sınırı hatalı sonuca yol açabilir. Sonucu kullanmadan önce doğrulamak kullanıcı sorumluluğundadır.", "Özellikle kişisel veri maskeleme, Regex, güvenlik ve dönüştürme sonuçları kritik bir sistemde kullanılmadan önce örnek test ve insan incelemesinden geçirilmelidir." ] },
        { heading: "4. Profesyonel danışmanlık değildir", paragraphs: ["ByteQuant hukuki, finansal, tıbbi, siber güvenlik denetimi veya mevzuat uygunluk hizmeti sunmaz. KVKK ve GDPR açıklamaları genel bilgidir. Somut olaylar için yetkin uzmana başvurun.", "Parola ve SHA-256 araçları teknik yardımcıdır; kurumunuzun kimlik, anahtar yönetimi veya parola saklama politikasının yerini almaz." ] },
        { heading: "5. Fikrî haklar ve bağlantılar", paragraphs: ["ByteQuant markası, özgün arayüzü ve içerikleri ilgili fikrî haklarla korunur. İçerikten kısa alıntı, kaynak ve bağlantı verilerek yapılabilir; bütün içeriğin kopyalanması veya yanıltıcı biçimde yeniden yayımlanması yasaktır.", "Dış bağlantılar kolaylık amacıyla sunulur. Üçüncü taraf sitelerin içerik, güvenlik ve politikalarından ByteQuant sorumlu değildir." ] },
        { heading: "6. Garanti ve sorumluluk sınırı", paragraphs: ["Hizmet makul özenle 'olduğu gibi' sunulur. Kesintisiz çalışma, belirli amaca uygunluk veya hatasız sonuç garantisi verilmez. Uygulanabilir hukukun izin verdiği ölçüde, araç sonucuna dayanılarak oluşan dolaylı kayıp ve zararlardan ByteQuant sorumlu tutulamaz.", "Bu hüküm kanunen sınırlandırılamayan tüketici veya veri sahibi haklarını ortadan kaldırmaz." ] },
        { heading: "7. Değişiklik ve iletişim", paragraphs: ["Koşullar ürün veya hukuki gereksinimler değiştiğinde güncellenebilir. Önemli değişiklikler yeni yürürlük tarihiyle bu sayfada yayımlanır. Sorular bytequant@yahoo.com adresine gönderilebilir." ] },
      ],
      en: [
        { heading: "1. Service scope", paragraphs: ["ByteQuant provides free in-browser prompt, text, data, and security tools plus educational guides. No account is required. Features, content, and availability may evolve.", "On-device operation depends on browser support for JavaScript, Web Crypto, and related capabilities." ] },
        { heading: "2. Acceptable use", paragraphs: ["Use the service lawfully and respect third-party rights. You are responsible for authority and legal basis to process any data you enter."], bullets: ["Do not prepare malware, phishing, or unauthorized access.", "Do not process another person's confidential or personal data without authority.", "Do not disrupt the service, generate abusive traffic, or bypass safeguards.", "Do not present output as professional approval or a legal compliance certificate."] },
        { heading: "3. Verify output", paragraphs: ["Tools use disclosed rules and browser APIs. Bad input, missing context, browser differences, and method limitations can produce errors. Verify output before relying on it.", "Masking, Regex, security, and conversion results should be tested on representative samples and reviewed by a person before use in a critical system." ] },
        { heading: "4. Not professional advice", paragraphs: ["ByteQuant does not provide legal, financial, medical, security-audit, or regulatory-compliance services. KVKK and GDPR content is general information. Consult qualified professionals for specific cases.", "Password and SHA-256 utilities do not replace organizational identity, key-management, or password-storage policies." ] },
        { heading: "5. Intellectual property and links", paragraphs: ["The ByteQuant brand, original interface, and content are protected by applicable rights. Short quotations may be used with attribution and a link; full copying or misleading republication is prohibited.", "External links are provided for convenience. ByteQuant is not responsible for third-party content, security, or policies." ] },
        { heading: "6. Warranty and liability", paragraphs: ["The service is provided with reasonable care on an 'as is' basis. We do not guarantee uninterrupted operation, fitness for a particular purpose, or error-free output. To the extent allowed by law, ByteQuant is not liable for indirect loss caused by reliance on tool output.", "Nothing here removes consumer or data-subject rights that cannot legally be limited." ] },
        { heading: "7. Changes and contact", paragraphs: ["Terms may change with the product or legal requirements. Material changes will appear here with a new effective date. Questions can be sent to bytequant@yahoo.com." ] },
      ],
    },
  },
  contact: {
    eyebrow: { tr: "İLETİŞİM", en: "CONTACT" },
    title: { tr: "Sorun, öneri ve düzeltmeleri doğrudan bize iletin", en: "Send bugs, suggestions, and corrections directly to us" },
    intro: { tr: "Araç hataları, erişilebilirlik sorunları, içerik düzeltmeleri ve iş birliği önerileri için e-posta ve sosyal kanallarımızı kullanabilirsiniz. Hassas metni veya gerçek kişisel veriyi mesaja eklemeyin.", en: "Use email or our social channels for tool bugs, accessibility issues, content corrections, and collaboration ideas. Do not include sensitive text or real personal data in your message." },
    sections: {
      tr: [
        { heading: "E-posta", paragraphs: ["Genel destek, gizlilik talepleri ve içerik düzeltmeleri: bytequant@yahoo.com. Mesajınızda ilgili sayfanın bağlantısını, tarayıcı türünü ve sorunu yeniden oluşturmak için gerekli adımları yazmanız çözümü hızlandırır.", "Parola, API anahtarı, kimlik numarası, müşteri kaydı veya gizli belge göndermeyin. Sorunu anonim örnek veriyle anlatın." ] },
        { heading: "Sosyal medya", paragraphs: ["Kısa duyurular ve yeni araç güncellemeleri için X hesabımız @byte_quant, Instagram hesabımız @byte.quant adresindedir. Hesap veya gizlilik talepleri sosyal medya yerine e-posta üzerinden iletilmelidir." ] },
        { heading: "İyi bir hata bildirimi nasıl yazılır?", paragraphs: ["Sorunun ne olduğunu, ne beklediğinizi ve gerçekte ne olduğunu kısa biçimde açıklayın. Mümkünse hassas olmayan örnek girdi kullanın. Ekran görüntüsü gönderecekseniz kişisel verileri önce maskeleyin."], bullets: ["Sayfa veya araç adı", "Tarayıcı ve cihaz türü", "Yeniden oluşturma adımları", "Beklenen ve gerçekleşen sonuç", "Hassas veri içermeyen örnek"] },
        { heading: "Yanıt yaklaşımı", paragraphs: ["Mesajları makul süre içinde incelemeyi hedefliyoruz; kesin yanıt süresi taahhüt etmiyoruz. Güvenlik açığı bildirimleri önceliklendirilir. Kötüye kullanım, spam veya yasa dışı talep içeren mesajlara yanıt verilmeyebilir." ] },
      ],
      en: [
        { heading: "Email", paragraphs: ["General support, privacy requests, and content corrections: bytequant@yahoo.com. Include the relevant page, browser type, and steps needed to reproduce the issue.", "Do not send passwords, API keys, identity numbers, customer records, or confidential files. Describe the issue with anonymous sample data." ] },
        { heading: "Social media", paragraphs: ["For short announcements and tool updates, follow @byte_quant on X and @byte.quant on Instagram. Account or privacy requests should be sent by email rather than social media." ] },
        { heading: "Writing a useful bug report", paragraphs: ["Briefly explain what happened, what you expected, and what actually occurred. Use a non-sensitive sample when possible and mask personal data in screenshots."], bullets: ["Page or tool name", "Browser and device type", "Reproduction steps", "Expected and actual result", "A non-sensitive example"] },
        { heading: "Response approach", paragraphs: ["We aim to review messages within a reasonable period but do not promise a fixed response time. Security reports are prioritized. Spam, abuse, and unlawful requests may not receive a response." ] },
      ],
    },
  },
  faq: {
    eyebrow: { tr: "SIK SORULAN SORULAR", en: "FREQUENTLY ASKED QUESTIONS" },
    title: { tr: "ByteQuant hakkında açık, kısa cevaplar", en: "Clear, concise answers about ByteQuant" },
    intro: { tr: "Araçların çalışma biçimi, gizlilik, sonuçların sınırı ve site politikaları hakkında en sık sorulan soruları bir araya getirdik.", en: "Answers about how the tools work, privacy, output limitations, and site policies." },
    sections: {
      tr: [
        { heading: "Araç girdileri nereye gider?", paragraphs: ["Girdiler etkin tarayıcı sekmesinde işlenir ve ByteQuant sunucularına gönderilmez. Araçlar girdiyi localStorage içine kaydetmez. Tema ve araç kullanım sayacı kişisel içerik taşımayan ayrı yerel değerlerdir; kullanım sayacı yalnızca ana sayfadaki kişisel kısa yolları sıralar." ] },
        { heading: "Araçlar gerçekten ücretsiz mi?", paragraphs: ["Evet. Temel araçların tamamı ücretsiz ve üyeliksizdir. Site gelecekte açıkça işaretlenmiş reklamlarla desteklenebilir; araç sonucunu ücret veya reklam ilişkisi belirlemez." ] },
        { heading: "Neden bazı skorlar yaklaşık?", paragraphs: ["Token ve okunabilirlik gibi ölçüler model veya dil özelliğine göre değişir. Aracın kullandığı şeffaf tahmin hızlı planlama içindir; kesin model tokenizer sonucu veya uzman dil değerlendirmesi değildir." ] },
        { heading: "KVKK/GDPR Veri Maskeleyici tam uygunluk sağlar mı?", paragraphs: ["Hayır. Araç yaygın desenleri bulur ancak isim, nadir olay ve dolaylı tanımlayıcı gibi bağlamsal kişisel verilerin tamamını yakalayamaz. İnsan kontrolü ve gerektiğinde uzman görüşü zorunludur." ] },
        { heading: "ByteQuant yapay zekâ modeline bağlanıyor mu?", paragraphs: ["Hayır. Mevcut araçlar uzak LLM veya başka bir yapay zekâ API'si çağırmaz. Prompt araçları kural tabanlı yapı kontrolü yapar; NLP araçları açıklanabilir metin istatistikleri kullanır." ] },
        { heading: "Büyük dosyaları kullanabilir miyim?", paragraphs: ["Araçlar küçük ve orta büyüklükte metinler için tasarlanmıştır. Tarayıcı belleğini korumak için girdi sınırları vardır. Çok büyük veya iç içe veri için masaüstü/komut satırı aracı daha uygun olabilir." ] },
        { heading: "Tarayıcı desteği nedir?", paragraphs: ["Güncel Chrome, Edge, Firefox ve Safari sürümleri önerilir. Parola, UUID ve SHA-256 için güvenli bağlamda Web Crypto desteği gerekir. Eski tarayıcılarda bazı işlevler çalışmayabilir." ] },
        { heading: "Hata veya düzeltme nasıl bildirilir?", paragraphs: ["bytequant@yahoo.com adresine sayfa bağlantısını ve hassas veri içermeyen örneği gönderin. X: @byte_quant, Instagram: @byte.quant. Gizlilik taleplerini e-posta ile iletin." ] },
      ],
      en: [
        { heading: "Where does tool input go?", paragraphs: ["Input is processed in the active browser tab and is not sent to ByteQuant servers. Tools do not store input in localStorage. Theme and tool-usage counts are separate local values with no personal content; the usage count only ranks personal home-page shortcuts." ] },
        { heading: "Are the tools really free?", paragraphs: ["Yes. All core tools are free and require no account. The site may later be supported by clearly labeled advertising, which will not influence tool output." ] },
        { heading: "Why are some scores estimates?", paragraphs: ["Token and readability measures vary by model or language. Transparent estimates are intended for planning, not as an exact model tokenizer or expert linguistic assessment." ] },
        { heading: "Does the KVKK/GDPR masker guarantee compliance?", paragraphs: ["No. It finds common patterns but cannot catch every name, rare event, or indirect identifier. Human review and, when appropriate, expert advice remain necessary." ] },
        { heading: "Does ByteQuant call an AI model?", paragraphs: ["No. Current tools do not call a remote LLM or AI API. Prompt tools use rule-based structure checks, while NLP tools use explainable text statistics." ] },
        { heading: "Can I use very large files?", paragraphs: ["The tools are designed for small and medium text. Input limits protect browser memory. Desktop or command-line tools may be better for very large or deeply nested data." ] },
        { heading: "Which browsers are supported?", paragraphs: ["Current Chrome, Edge, Firefox, and Safari are recommended. Password, UUID, and SHA-256 features need Web Crypto in a secure context. Some features may fail in old browsers." ] },
        { heading: "How do I report a bug or correction?", paragraphs: ["Email bytequant@yahoo.com with the page link and a non-sensitive example. X: @byte_quant; Instagram: @byte.quant. Use email for privacy requests." ] },
      ],
    },
  },
};
