import type { Locale } from "./site";
import type { ArticleSection, Post } from "./posts";
import type { LocalizedGuide } from "./localized-guides";

type L = Record<Locale, string>;
type Guide = { slug: string; relatedTools: string[]; title: L; excerpt: L; category: L; objective: L; method: L; failure: L; evidence: L; boundary: L; source: { title: Record<"tr" | "en", string>; url: string } };
const l = (tr: string, en: string, de: string, zh: string): L => ({ tr, en, de, zh });

const guides: Guide[] = [
  {
    slug: "csv-json-veri-uzlastirma-kabul-rehberi", relatedTools: ["csv-satir-fark-uzlastirici", "json-alan-tip-profilleyici", "csv-inceleyici", "json-schema-olusturucu"],
    title: l("CSV ve JSON Veri Uzlaştırma: Taşımadan Sonra Ne Değiştiğini Kanıtlama", "CSV and JSON Reconciliation: Proving What Changed After a Migration", "CSV- und JSON-Abgleich: Änderungen nach einer Migration nachweisen", "CSV 与 JSON 数据核对：证明迁移后发生了什么变化"),
    excerpt: l("Satır sayısı eşitliğinin ötesine geçin; anahtar, tip, boş değer ve hücre farklarını geri alınabilir bir kabul kaydında birleştirin.", "Go beyond equal row counts by combining keys, types, missing values, and cell differences in a reversible acceptance record.", "Über gleiche Zeilenzahlen hinaus Schlüssel, Typen, Leerwerte und Zellunterschiede in einem nachvollziehbaren Abnahmenachweis verbinden.", "不要止于行数相等；把主键、类型、缺失值和单元格差异整合为可回溯的验收记录。"),
    category: l("Veri kalitesi ve taşıma", "Data quality and migration", "Datenqualität und Migration", "数据质量与迁移"),
    objective: l("Kaynak ve hedef tabloda her iş kaydını tekil anahtarla eşleştirip eklenen, kaybolan, değişen ve tip değiştiren alanları açıklayabilen bir kabul paketi oluşturmak.", "Create an acceptance package that matches every business record by a unique key and explains additions, losses, cell changes, and type drift.", "Ein Abnahmepaket erstellen, das jeden Datensatz per Schlüssel zuordnet und neue, verlorene, geänderte sowie typveränderte Felder erklärt.", "建立验收包：用唯一键匹配每条业务记录，并解释新增、丢失、单元格变化和类型漂移。"),
    method: l("Önce başlıkları ve ayıracı doğrulayın; sonra kaynak anahtarının boş veya yinelenen olmadığını kanıtlayın. CSV farkını kayıt düzeyinde çıkarın, JSON örneğinde alan varlığı ve gözlenen tip dağılımını ayrı raporlayın. Satır sırası, biçim farkı ve gerçek veri değişikliğini aynı kategoriye koymayın.", "Validate headers and delimiters first, then prove that the source key is neither blank nor duplicated. Reconcile CSV at record level and profile field presence and observed JSON types separately. Do not confuse row order or formatting with a business-data change.", "Zuerst Kopfzeilen und Trennzeichen prüfen, dann leere oder doppelte Schlüssel ausschließen. CSV auf Datensatzebene abgleichen und JSON-Feldvorkommen sowie Typen separat profilieren. Reihenfolge und Format nicht mit fachlicher Änderung verwechseln.", "先验证表头与分隔符，再证明源主键既不为空也不重复。按记录核对 CSV，并分别分析 JSON 字段存在性和实际类型；不要把行顺序或格式差异当作业务数据变化。"),
    failure: l("Yinelenen anahtarın son kaydı öncekinin üzerine yazması, boş değerin sıfıra çevrilmesi, tarih metninin yerel saatle kayması ve yeni sütunun hedefte sessizce yok olması başlıca olumsuz testlerdir. Her biri sessiz düzeltme yerine durdurucu ve alanı adlandıran bir hata üretmelidir.", "Key overwrites, blank-to-zero coercion, local-time date shifts, and silently dropped new columns are essential negative tests. Each should produce a stopping error that names the field rather than an invisible repair.", "Schlüsselüberschreibung, Leerwert-zu-Null, lokale Datumsverschiebung und still verworfene Spalten sind zentrale Negativtests. Jeder Fall muss mit benanntem Feld stoppen.", "重复键覆盖、空值转零、本地时区日期偏移和新列被静默丢弃是关键负面测试；每种情况都应停止并明确指出字段，而非悄悄修正。"),
    evidence: l("Kayıtta kaynak/çıktı satır ve sütun sayısı, anahtar tekilliği, null/eksik dağılımı, tip sapmaları, değişen alan örnekleri, kullanılan sürüm, tarih ve onay sahibi bulunmalıdır. Ham verinin tamamını paylaşmak yerine hassasiyeti giderilmiş temsilî örnek ve özet sayımlar saklayın.", "Record source/output row and column counts, key uniqueness, null and missing distributions, type drift, examples of changed fields, version, date, and accountable approver. Retain sanitised representative samples and aggregate counts rather than publishing the complete sensitive dataset.", "Zeilen-/Spaltenzahlen, Schlüsselklarheit, Null-/Fehlverteilung, Typabweichungen, Änderungsbeispiele, Version, Datum und Freigabe dokumentieren. Sensible Vollbestände nicht veröffentlichen.", "记录源/输出行列数、主键唯一性、null 与缺失分布、类型漂移、变更字段样例、版本、日期和负责人；保留脱敏代表样本与汇总计数，不发布完整敏感数据。"),
    boundary: l("Yapısal eşitlik, anlamın korunduğunu veya kaydın güncel gerçeği temsil ettiğini kanıtlamaz. Para, kimlik, izin ve yasal saklama gibi yüksek etkili alanlar veri sahibi ve alan uzmanıyla ayrıca örneklenmelidir.", "Structural agreement proves neither semantic preservation nor current truth. High-impact fields such as money, identity, permissions, and legal retention require separate sampling with the data owner and domain specialist.", "Strukturelle Übereinstimmung beweist weder Bedeutung noch Aktualität. Geld-, Identitäts-, Berechtigungs- und Aufbewahrungsfelder brauchen fachliche Stichproben.", "结构一致不能证明语义被保留或记录仍代表当前事实；金额、身份、权限与法定保留等高影响字段必须由数据负责人和领域专家另行抽样。"),
    source: { title: { tr: "RFC 8259 — JSON veri değişim biçimi", en: "RFC 8259 — The JSON Data Interchange Format" }, url: "https://www.rfc-editor.org/rfc/rfc8259" },
  },
  {
    slug: "web-vitals-kapasite-performans-karar-rehberi", relatedTools: ["web-vitals-ornek-analizoru", "yanit-suresi-yuzdelik-hesaplayici", "kuyruk-kapasite-planlayici", "web-performans-butce-planlayici"],
    title: l("Web Vitals, Yüzdelikler ve Kuyruk Kapasitesiyle Performans Kararı", "Performance Decisions with Web Vitals, Percentiles, and Queue Capacity", "Performanceentscheidungen mit Web Vitals, Perzentilen und Warteschlangen", "用 Web Vitals、百分位和队列容量做性能决策"),
    excerpt: l("Tek bir ortalamayı başarı saymak yerine kullanıcı rotası, p75/p95, patlama yükü ve varlık bütçesini aynı sürüm kapısında değerlendirin.", "Replace a single average with route-level evidence, p75/p95, burst load, and asset budgets in one release gate.", "Statt eines Mittelwerts Routen, p75/p95, Burstlast und Asset-Budget in einem Release-Gate bewerten.", "不要把单一平均值当作成功；在同一发布门槛中评估路径、p75/p95、突发负载与资源预算。"),
    category: l("Web performansı", "Web performance", "Web-Performance", "Web 性能"),
    objective: l("Ana görev rotalarında görsel kararlılık, etkileşim gecikmesi, içerik görünme süresi, sunucu/işçi kapasitesi ve indirilen varlık maliyetini kullanıcı tarafından hissedilen tek bir performans kararıyla bağlamak.", "Connect visual stability, interaction delay, content visibility, worker capacity, and transferred assets on key journeys to one user-centred performance decision.", "Visuelle Stabilität, Interaktionslatenz, Inhaltsanzeige, Worker-Kapazität und Transferkosten auf Kernrouten zu einer nutzerzentrierten Entscheidung verbinden.", "把关键任务路径的视觉稳定、交互延迟、内容呈现、工作线程容量与下载资源成本整合为面向用户的性能决策。"),
    method: l("Ölçümleri rota, cihaz sınıfı, önbellek durumu ve sürümle etiketleyin. LCP/INP/CLS örneklerini kendi eşikleriyle değerlendirin; yanıt süresini ortalamanın yanında p50, p75, p95 ve p99 olarak gösterin. Kuyruk kapasitesinde geliş hızı işlem hızına yaklaşıyorsa yalnız daha çok işçi değil, iş azaltma ve geri basınç seçeneğini de ölçün.", "Tag measurements with route, device class, cache state, and release. Evaluate LCP, INP, and CLS with their own thresholds; report response time as p50, p75, p95, and p99 as well as the mean. When arrival approaches service capacity, evaluate demand reduction and backpressure—not only more workers.", "Messwerte nach Route, Gerät, Cache und Version kennzeichnen. LCP, INP und CLS getrennt bewerten; Antwortzeiten als p50/p75/p95/p99 zeigen. Bei hoher Auslastung Lastreduktion und Backpressure neben mehr Workern prüfen.", "按路径、设备类型、缓存状态和版本标记测量。分别评估 LCP、INP、CLS；响应时间除平均值外还要展示 p50、p75、p95、p99。当到达速率接近处理能力时，除增加线程外还要评估减载和背压。"),
    failure: l("Sıcak önbellekte masaüstü testi, sentetik tek koşu, çok küçük yüzdelik örneği, arka plandaki sekme ve ortalamaya gizlenen uzun kuyruk ayrı hata sınıflarıdır. Performans testi içerik veya reklam yerleşimini değiştiren gerçek sayfa durumlarını da kapsamalıdır.", "A warm-cache desktop run, one synthetic sample, tiny percentile set, background tab, and long tail hidden by an average are distinct failure classes. Test real page states affected by content and ad placement as well.", "Warmer Desktop-Cache, Einzellauf, kleine Perzentilstichprobe, Hintergrundtab und im Mittelwert versteckter Tail sind getrennte Fehlerklassen. Reale Inhalts- und Anzeigenzustände mitprüfen.", "热缓存桌面单次测试、小型百分位样本、后台标签页以及被平均值隐藏的长尾是不同故障类型；还应覆盖内容与广告布局变化后的真实页面状态。"),
    evidence: l("Her karşılaştırma için örnek sayısı, ölçüm penceresi, cihaz/ağ profili, p75 ve p95, en kötü rota, varlık boyutu farkı, kuyruk kullanım oranı ve önce/sonra sürümü kaydedin. Geçici bütçe istisnasına sahibi ve bitiş tarihi ekleyin.", "For each comparison, record sample count, window, device/network profile, p75 and p95, worst route, asset-size delta, queue utilisation, and before/after release. Give temporary budget exceptions an owner and expiry date.", "Pro Vergleich Stichprobengröße, Zeitraum, Geräte-/Netzprofil, p75/p95, schlechteste Route, Asset-Differenz, Queue-Auslastung und Version dokumentieren. Ausnahmen brauchen Verantwortung und Ablaufdatum.", "每次对比都记录样本数、时间窗口、设备/网络配置、p75/p95、最差路径、资源体积差、队列利用率及前后版本；临时预算例外必须有负责人和到期日。"),
    boundary: l("Yerel hesaplayıcı gerçek kullanıcı ölçümü toplamaz ve bir laboratuvar skorunu iş sonucuna dönüştürmez. Nihai kabul; sahadaki dağılım, erişilebilirlik görevi, gelir/başarı sinyali ve kullanıcı şikâyetleriyle birlikte yapılmalıdır.", "A local calculator collects no real-user data and cannot turn a lab score into a business outcome. Final acceptance should combine field distributions, accessibility tasks, completion signals, and user reports.", "Ein lokaler Rechner sammelt keine Felddaten und macht aus Laborscores keine Geschäftsergebnisse. Abnahme braucht Feldverteilung, Barrierefreiheitsaufgaben und Nutzerfeedback.", "本地计算器不采集真实用户数据，也不能把实验室分数转成业务结果；最终验收应结合现场分布、无障碍任务、完成信号与用户反馈。"),
    source: { title: { tr: "W3C Navigation Timing Level 2", en: "W3C Navigation Timing Level 2" }, url: "https://www.w3.org/TR/navigation-timing-2/" },
  },
  {
    slug: "mobil-arayuz-katman-dokunma-hedefi-rehberi", relatedTools: ["css-z-index-katman-haritasi", "dokunma-hedefi-boyut-denetleyici", "aria-erisebilir-ad-envanteri", "renk-kontrast-denetleyici"],
    title: l("Mobil Arayüzde Katman, Dokunma Hedefi ve Erişilebilir Ad Kalitesi", "Mobile UI Quality: Layers, Touch Targets, and Accessible Names", "Mobile UI: Ebenen, Touch-Ziele und zugängliche Namen", "移动界面质量：层级、触控目标与可访问名称"),
    excerpt: l("Header, menü, modal ve araç eylemlerini yalnız güzel görünmeleriyle değil; üst üste binme, dokunma, klavye ve ekran okuyucu görevleriyle kabul edin.", "Accept headers, menus, modals, and tool actions through overlap, touch, keyboard, and screen-reader tasks—not appearance alone.", "Header, Menüs, Modale und Tool-Aktionen über Überlappung, Touch, Tastatur und Screenreader abnehmen – nicht nur optisch.", "验收页头、菜单、弹窗与工具操作时，不只看外观，还要测试遮挡、触控、键盘和屏幕阅读器任务。"),
    category: l("Erişilebilir arayüz tasarımı", "Accessible interface design", "Barrierefreies Interface-Design", "无障碍界面设计"),
    objective: l("320 px genişlikten masaüstüne ve %200 metin büyütmeye kadar bir kullanıcının ana eylemi bulabildiği, dokunabildiği, klavyeyle çalıştırabildiği ve sonucunu okuyabildiği bir kabul matrisi kurmak.", "Build an acceptance matrix in which users can find, touch, keyboard-activate, and read the result of the primary action from a 320 px viewport through desktop and 200% text enlargement.", "Eine Abnahmematrix schaffen, in der Hauptaktionen von 320 px bis Desktop und bei 200 % Text gefunden, berührt, per Tastatur ausgelöst und gelesen werden können.", "建立验收矩阵：从 320px 视口到桌面以及 200% 文本放大，用户都能找到、触摸、键盘触发并读取主要操作结果。"),
    method: l("Önce katman adlarını ve küçük bir z-index bütçesini tanımlayın; yüksek sayı yarışını tasarım tokenlarına dönüştürün. Sonra gerçek buton dikdörtgenlerini ve en yakın komşu aralığını ölçün. Her ikon eyleminde görünür metin veya erişilebilir ad, doğru odak sırası, belirgin odak göstergesi ve sonuç duyurusu bulunmalıdır.", "Define named layers and a small z-index budget first, replacing number escalation with design tokens. Then measure real target rectangles and nearest-neighbour spacing. Every icon action needs visible text or an accessible name, correct focus order, clear focus indication, and announced results.", "Benannte Ebenen und kleines z-index-Budget definieren, Zahlenwettlauf durch Tokens ersetzen. Danach echte Zielrechtecke und Abstände messen. Icon-Aktionen brauchen zugängliche Namen, Fokusreihenfolge, Fokusindikator und Ergebnisansage.", "先定义有名称的层级和小型 z-index 预算，用设计令牌替代数字竞赛；再测量真实目标矩形及最近间距。每个图标操作都应有可见文字或可访问名称、正确焦点顺序、清晰焦点指示和结果播报。"),
    failure: l("Yatay taşan sekme, sabit header altında kalan odak, modal arkasında tıklanabilen içerik, yalnız hover ile görünen açıklama, metin uzayınca küçülen buton ve kapat düğmesine çok yakın eylem kasıtlı olarak sınanmalıdır. Türkçe ve Almanca uzun etiketler kısa İngilizce örnekten daha erken taşabilir.", "Deliberately test overflowing tabs, focus hidden under sticky headers, clickable content behind a modal, hover-only help, controls that shrink under long text, and actions too close to dismiss buttons. Long Turkish and German labels can fail before short English samples.", "Überlaufende Tabs, verdeckter Fokus, klickbarer Modal-Hintergrund, Hover-Hilfe, schrumpfende Buttons und zu enge Schließen-Aktionen absichtlich testen. Lange deutsche und türkische Texte früh prüfen.", "主动测试横向溢出的标签、被固定页头遮住的焦点、弹窗后仍可点击的内容、仅悬停显示的帮助、长文字导致缩小的按钮以及过近的关闭操作。土耳其语和德语长标签可能比英语更早溢出。"),
    evidence: l("Rota ve breakpoint başına hedef ölçüleri, odak sırası, erişilebilir ad kaynağı, %200 metin görüntüsü, açık/koyu tema kontrastı ve bir ana görevin klavye/mobil tamamlanma sonucu kaydedilmelidir. Ekran görüntüsü, etkileşim kaydıyla birlikte anlamlıdır.", "For each route and breakpoint, record target sizes, focus order, accessible-name source, 200% text view, light/dark contrast, and completion of one primary task by keyboard and touch. A screenshot is meaningful only with interaction evidence.", "Pro Route und Breakpoint Zielgrößen, Fokusfolge, Namensquelle, 200-%-Text, Hell-/Dunkelkontrast und eine Tastatur-/Touch-Aufgabe dokumentieren. Screenshot nur mit Interaktionsnachweis.", "按路径和断点记录目标尺寸、焦点顺序、可访问名称来源、200% 文本视图、深浅主题对比度，以及键盘和触控完成一项主要任务的结果；截图需结合交互证据才有意义。"),
    boundary: l("Statik CSS ve ölçüm satırları gerçek stacking context, ekran okuyucu davranışı veya motor koordinasyonunu kanıtlamaz. Son kontrol desteklenen tarayıcı, mobil cihaz ve yardımcı teknolojiyle gerçek görev üzerinden yapılmalıdır.", "Static CSS and measurement rows cannot prove stacking-context behaviour, screen-reader output, or motor usability. Final review requires real tasks in supported browsers, mobile devices, and assistive technology.", "Statisches CSS und Messzeilen beweisen weder Stacking Context noch Screenreader- oder Motoriknutzung. Abschlussprüfung erfolgt mit echten Aufgaben auf unterstützten Geräten.", "静态 CSS 与测量行不能证明真实层叠上下文、屏幕阅读器输出或运动可用性；最终检查必须在支持的浏览器、移动设备和辅助技术上执行真实任务。"),
    source: { title: { tr: "W3C WCAG 2.2", en: "W3C Web Content Accessibility Guidelines (WCAG) 2.2" }, url: "https://www.w3.org/TR/WCAG22/" },
  },
  {
    slug: "tarayici-depolama-dosya-manifestosu-dayaniklilik-rehberi", relatedTools: ["tarayici-depolama-butce-planlayici", "dosya-manifestosu-uzlastirici", "yedekleme-3-2-1-hazirlik-denetleyici", "dosya-hash-karsilastirici"],
    title: l("Tarayıcı Depolaması ve Dosya Manifestosuyla Yerel Uygulama Dayanıklılığı", "Local-App Resilience with Browser Storage and File Manifests", "Lokale App-Resilienz mit Browser-Speicher und Dateimanifesten", "用浏览器存储与文件清单提升本地应用韧性"),
    excerpt: l("Çevrimdışı veriyi sınırsız kabul etmeyin; bütçe, tahliye, bütünlük, geri yükleme ve kullanıcıya ait dışa aktarma yolunu birlikte tasarlayın.", "Do not treat offline data as unlimited: design quota, eviction, integrity, restore, and user-owned export together.", "Offline-Daten nicht als unbegrenzt behandeln: Quote, Eviction, Integrität, Restore und nutzereigenen Export gemeinsam gestalten.", "不要把离线数据视为无限；应共同设计配额、清理、完整性、恢复和用户自主管理的导出路径。"),
    category: l("Yerel veri dayanıklılığı", "Local data resilience", "Lokale Datenresilienz", "本地数据韧性"),
    objective: l("Kullanıcı tercihleri, çalışma taslakları, önbellek ve büyük model dosyalarını ayrı yaşam döngülerine bağlayan; bütçe baskısında bozulmadan küçülen ve dışa aktarımdan geri yüklenebilen bir yerel veri planı kurmak.", "Build a local-data plan that gives preferences, drafts, caches, and large model files separate lifecycles, degrades safely under storage pressure, and can restore from a user-owned export.", "Einen lokalen Datenplan mit getrennten Lebenszyklen für Einstellungen, Entwürfe, Cache und Modelle schaffen, der unter Speicherdruck sicher reduziert und aus Nutzerexporten wiederherstellt.", "建立本地数据计划：为偏好、草稿、缓存和大型模型文件设置独立生命周期，在存储压力下安全降级，并能从用户自有导出恢复。"),
    method: l("Her veri sınıfı için amaç, tahmini boyut, saklama süresi, yeniden üretilebilirlik, şifreleme ihtiyacı ve silme eylemini yazın. Korumalı bütçeyi toplam kotadan ayırın; önbelleği ilk tahliye adayı, kullanıcı taslağını açık onay gerektiren sınıf yapın. Dışa aktarımda yol, bayt ve güvenilir hash içeren manifestoyu kaynak ve geri yüklenen kopya arasında uzlaştırın.", "Document purpose, expected size, retention, reproducibility, encryption need, and deletion action for every data class. Separate protected headroom from nominal quota; make caches the first eviction candidate and require explicit approval before deleting drafts. Reconcile path, byte count, and trusted digest between export and restored copy.", "Für jede Datenklasse Zweck, Größe, Aufbewahrung, Reproduzierbarkeit, Verschlüsselung und Löschung dokumentieren. Reserve von Nominalquote trennen; Cache zuerst entfernen, Entwürfe nur mit Bestätigung. Pfad, Bytes und vertrauenswürdigen Digest beim Restore abgleichen.", "为每类数据记录用途、预计大小、保留期限、可再生成性、加密需求和删除动作。将安全余量与名义配额分开；缓存优先清理，删除用户草稿需明确确认。导出与恢复副本之间核对路径、字节数和可信摘要。"),
    failure: l("Gizli modda düşük kota, tarayıcı temizliği, eksik depolama izni, yarıda kalan model indirmesi, eski şema, yanlış parola, aynı yolda farklı dosya ve eksik geri yükleme anahtarı ayrı testlerdir. Uygulama tekrar indirilebilir varlığı kaybettiğinde çalışmalı; geri getirilemeyen kullanıcı verisini sessizce silmemelidir.", "Low private-mode quota, browser cleanup, denied persistence, interrupted model download, old schema, wrong passphrase, same-path different file, and missing recovery key are separate tests. The app should survive loss of reproducible assets and never silently delete irreplaceable user data.", "Niedrige Privatmodusquote, Browserbereinigung, fehlende Persistenz, abgebrochener Modelldownload, altes Schema, falsches Passwort, Pfadkonflikt und fehlender Schlüssel getrennt testen. Nicht ersetzbare Nutzerdaten nie still löschen.", "隐私模式低配额、浏览器清理、持久化被拒、模型下载中断、旧架构、错误密码、同路径不同文件和缺失恢复密钥应分别测试。应用应能承受可再生成资源丢失，绝不能静默删除不可替代的用户数据。"),
    evidence: l("Bütçe tablosu, veri sınıfı sahipliği, gerçek cihaz kota ölçümü, tahliye sırası, manifest farkı, başarılı geri yükleme tarihi, sürüm geçişi ve kullanıcıya gösterilen silme/dışa aktarma metni aynı bakım kaydında bulunmalıdır.", "Keep the budget table, data-class ownership, real-device quota measurement, eviction order, manifest difference, successful restore date, schema migration, and user-facing delete/export copy in one maintenance record.", "Budget, Datenverantwortung, Gerätequote, Eviction-Reihenfolge, Manifestdifferenz, Restore-Datum, Schemamigration und Nutzertexte gemeinsam dokumentieren.", "在同一维护记录中保存预算表、数据类别责任、实机配额测量、清理顺序、清单差异、成功恢复日期、架构迁移以及面向用户的删除/导出说明。"),
    boundary: l("Manifestodaki hash ancak güvenilir kaynaktan ve doğru algoritmayla üretildiyse bütünlük sinyalidir; gizlilik veya dosyanın güvenli içeriğini kanıtlamaz. Tarayıcı kotası cihaz ve tarayıcı kararına bağlıdır, ürün sözü gibi sabit yazılamaz.", "A manifest digest is an integrity signal only when produced by a trusted source with the intended algorithm; it proves neither confidentiality nor safe content. Browser quota is device- and browser-dependent and cannot be promised as a fixed product limit.", "Manifest-Hashes sind nur bei vertrauenswürdiger Quelle und korrektem Algorithmus ein Integritätssignal; weder Vertraulichkeit noch sicherer Inhalt sind bewiesen. Browserquote ist variabel.", "清单摘要只有在可信来源使用预期算法生成时才是完整性信号，不能证明机密性或文件内容安全；浏览器配额取决于设备和浏览器，不能作为固定产品承诺。"),
    source: { title: { tr: "WHATWG HTML — Web storage", en: "WHATWG HTML — Web storage" }, url: "https://html.spec.whatwg.org/multipage/webstorage.html" },
  },
  {
    slug: "api-hata-kota-yonlendirme-operasyon-rehberi", relatedTools: ["api-hata-zarfi-dogrulayici", "api-oran-siniri-kapasite-planlayici", "url-yonlendirme-zinciri-inceleyici", "retry-after-geri-cekilme-planlayici"],
    title: l("API Hata, Kota ve Yönlendirme Sözleşmelerini Birlikte Tasarlama", "Designing API Error, Quota, and Redirect Contracts Together", "API-Fehler-, Quoten- und Redirect-Verträge gemeinsam gestalten", "统一设计 API 错误、配额与重定向契约"),
    excerpt: l("Başarılı yanıt kadar hata zarfını, geri çekilmeyi, kapasite sınırını ve URL geçişini de sürümlenebilir ürün davranışı olarak ele alın.", "Treat error envelopes, backoff, capacity limits, and URL transitions as versioned product behaviour—not afterthoughts to successful responses.", "Fehlerumschlag, Backoff, Kapazitätsgrenzen und URL-Übergänge ebenso wie Erfolg als versioniertes Produktverhalten behandeln.", "把错误信封、退避、容量限制和 URL 迁移都视作可版本化产品行为，而非成功响应的附属品。"),
    category: l("API güvenilirliği", "API reliability", "API-Zuverlässigkeit", "API 可靠性"),
    objective: l("İstemcinin hata nedenini güvenle gösterebildiği, alan düzeltmesini yönlendirebildiği, yeniden denemeyi idempotent biçimde zamanladığı, kotayı aşmadan yavaşladığı ve eski URL'yi döngüsüz yeni hedefe taşıdığı bütünlüklü sözleşme kurmak.", "Create a coherent contract in which clients can safely explain and recover from errors, retry idempotently, slow before quota exhaustion, and move old URLs to new destinations without loops.", "Einen Vertrag schaffen, der Fehler sicher erklärt, Feldkorrektur ermöglicht, idempotent wiederholt, vor Quotenende drosselt und alte URLs schleifenfrei umleitet.", "建立统一契约：客户端能安全解释错误并指导修正，以幂等方式重试，在配额耗尽前减速，并把旧 URL 无循环地迁移到新目标。"),
    method: l("Hata kodunu kullanıcı metninden ayırın; kod makinece sabit, mesaj güvenli ve eyleme dönük olsun. Yığın izi, SQL ve sırları istemciye taşımayın; izleme kimliğini sunucu kaydıyla eşleştirin. Kota planında sürekli yük ile patlamayı ayırın, Retry-After ve idempotency koşulunu belgeleyin. Yönlendirme zincirini tek kalıcı adıma indirin ve son hedefte canonical davranışını kontrol edin.", "Separate stable machine codes from safe actionable messages. Keep stacks, SQL, and secrets out of client responses and correlate a trace id with server records. Distinguish sustained load from bursts, document Retry-After and idempotency, and reduce redirects to one permanent hop whose final canonical behaviour is verified.", "Stabile Maschinen-Codes von sicheren Handlungsnachrichten trennen. Stack, SQL und Geheimnisse nicht ausliefern; Trace-ID mit Serverdaten verbinden. Dauerlast/Burst, Retry-After und Idempotenz dokumentieren. Redirects auf einen permanenten Schritt reduzieren.", "把稳定机器代码与安全、可操作的用户消息分开；不要向客户端泄露堆栈、SQL 和秘密，用追踪 ID 关联服务器记录。区分持续负载和突发，记录 Retry-After 与幂等条件，并把重定向压缩为一个永久步骤。"),
    failure: l("Aynı POST'un iki kez ödeme oluşturması, 429 yanıtında sıkı döngü, trace id olmadan genel 500, alan adını sızdıran doğrulama hatası, HTTPS'den HTTP'ye düşüş ve A→B→A yönlendirme döngüsü sürüm kapısında otomatik test edilmelidir.", "Release tests should cover duplicate side effects from repeated POSTs, tight loops after 429, generic 500 responses without trace ids, validation messages that leak internals, HTTPS downgrades, and A→B→A redirect loops.", "Doppelte POST-Wirkung, enge 429-Schleife, 500 ohne Trace-ID, interne Validierungslecks, HTTPS-Downgrade und A→B→A-Redirectschleife automatisiert testen.", "发布测试应覆盖 POST 重试产生重复副作用、429 后紧循环、无追踪 ID 的通用 500、泄漏内部字段的验证错误、HTTPS 降级及 A→B→A 重定向循环。"),
    evidence: l("Sözleşme örneği, JSON Schema veya eşdeğer doğrulama, durum kodu matrisi, kota varsayımları, yeniden deneme zaman çizelgesi, idempotency anahtarı davranışı, yönlendirme adımları ve gerçek istemcide kullanıcı mesajı birlikte sürümlenmelidir.", "Version the contract sample, JSON Schema or equivalent validation, status-code matrix, quota assumptions, retry timeline, idempotency-key behaviour, redirect hops, and real-client user message together.", "Vertragsbeispiel, Schema/Validierung, Statusmatrix, Quotenannahmen, Retry-Zeitplan, Idempotency-Verhalten, Redirectschritte und reale Nutzermeldung gemeinsam versionieren.", "对契约样例、JSON Schema 或等效验证、状态码矩阵、配额假设、重试时间线、幂等键行为、重定向步骤和真实客户端消息统一版本管理。"),
    boundary: l("Yerel ön kontrol canlı sunucunun kota sayacını, TLS zincirini, log erişimini veya idempotency depolamasını göremez. Sözleşme testi üretim benzeri ortam, yük denemesi ve yetkili operasyon kaydıyla tamamlanmalıdır.", "A local pre-check cannot see live quota counters, TLS chains, log access, or idempotency storage. Complete contract testing with a production-like environment, load exercise, and accountable operational records.", "Lokale Vorprüfung sieht weder Live-Quote, TLS-Kette, Logzugriff noch Idempotenzspeicher. Produktnahe Tests und verantwortliche Betriebsnachweise sind nötig.", "本地预检查看不到线上配额计数、TLS 链、日志访问或幂等存储；契约测试需在类生产环境中结合负载演练和可追责运营记录完成。"),
    source: { title: { tr: "RFC 9110 — HTTP Semantiği", en: "RFC 9110 — HTTP Semantics" }, url: "https://www.rfc-editor.org/rfc/rfc9110" },
  },
  {
    slug: "feature-flag-adr-geri-alinabilir-yayin-rehberi", relatedTools: ["ozellik-bayragi-yayin-planlayici", "adr-karar-kaydi-olusturucu", "surum-notu-degisiklik-derleyici", "paket-manifestosu-denetleyici"],
    title: l("Feature Flag ve ADR ile Geri Alınabilir Ürün Yayını", "Reversible Product Releases with Feature Flags and ADRs", "Reversible Releases mit Feature Flags und ADRs", "用功能开关与 ADR 实现可回退产品发布"),
    excerpt: l("Yüzdeyi artırmayı yayın stratejisi sanmayın; karar gerekçesi, kohort, gözlem, durdurma, geri alma ve kullanıcı iletişimini tek kayıtta bağlayın.", "A rising percentage is not a release strategy: connect rationale, cohorts, observation, stop, rollback, and user communication in one record.", "Steigende Prozentwerte sind keine Strategie: Begründung, Kohorten, Beobachtung, Stopp, Rollback und Nutzerkommunikation verbinden.", "提高百分比并不等于发布策略；应把决策理由、用户群、观察、停止、回滚和用户沟通统一记录。"),
    category: l("Ürün yayını ve yönetişim", "Product release and governance", "Produktfreigabe und Governance", "产品发布与治理"),
    objective: l("Bir özelliğin neden yayınlandığını, hangi kullanıcıların hangi sırayla göreceğini, hangi ölçünün başarı veya zarar sayılacağını ve kimin tek hareketle geri alacağını önceden yazan denetlenebilir yayın kaydı oluşturmak.", "Create an auditable release record that states why a feature ships, which users see it in what order, what counts as success or harm, and who can roll it back in one action.", "Einen prüfbaren Release-Datensatz erstellen: Warum, welche Nutzer in welcher Reihenfolge, Erfolg/Schaden und wer mit einer Aktion zurückrollt.", "建立可审计发布记录：预先说明为何发布、哪些用户按何顺序看到、何种指标代表成功或伤害，以及谁能一键回滚。"),
    method: l("ADR'de bağlamı, en az iki gerçek seçeneği, seçilen kararı, olumlu/olumsuz sonuçları ve yeniden açma koşulunu kaydedin. Feature flag planında iç kohorttan başlayın; her yüzde artışından önce asgari örnek, gözlem süresi, hata eşiği ve kullanıcı görevi tamamlanma ölçüsü isteyin. Bayrağın sahibiyle geri alma sahibini aynı varsaymayın.", "Use an ADR to record context, at least two real options, the decision, positive and negative consequences, and reopening triggers. Start rollout with an internal cohort; require minimum sample, observation time, error threshold, and task-completion evidence before each increase. Do not assume flag ownership and rollback authority are identical.", "Im ADR Kontext, mindestens zwei echte Optionen, Entscheidung, positive/negative Folgen und Neubewertung erfassen. Intern starten; vor jeder Stufe Stichprobe, Beobachtung, Fehlerschwelle und Aufgabenabschluss fordern. Flag- und Rollback-Verantwortung trennen.", "在 ADR 中记录背景、至少两个真实选项、决策、正负后果及重新开启条件。先从内部用户群开始；每次扩大前都要求最低样本量、观察时长、错误阈值和任务完成证据。不要默认开关负责人就是回滚负责人。"),
    failure: l("Kullanıcı atamasının her istekte değişmesi, %1 kohortta yalnız çalışanların bulunması, bayrak kapanınca yeni veri şemasının geri dönememesi, hata oranının düşük ama ana görevin bozuk olması ve eski istemcinin yeni yanıtı okuyamaması ayrı testlerdir.", "Test unstable assignment, an unrepresentative 1% staff-only cohort, data schemas that cannot revert when the flag closes, low error rates despite broken tasks, and old clients unable to read new responses.", "Wechselnde Zuweisung, unrepräsentative 1-%-Mitarbeiterkohorte, nicht rückrollbares Schema, niedrige Fehlerrate trotz kaputter Aufgabe und alte inkompatible Clients getrennt testen.", "分别测试用户分配不稳定、1% 阶段只有员工、关闭开关后数据架构无法回退、错误率低但主要任务已坏，以及旧客户端无法读取新响应。"),
    evidence: l("ADR kimliği, bayrak adı, hedef kohort, aşama yüzdeleri, başlangıç/bitiş saati, metrik panosu, hata ve kullanıcı görev eşiği, geri alma provası, destek metni ve sürüm notu birbirine bağlanmalıdır. Bayrak kaldırma tarihi unutulmamalıdır.", "Link ADR id, flag name, target cohort, percentages, start/end time, metrics, error and task thresholds, rollback rehearsal, support copy, and release notes. Include a date for deleting the temporary flag.", "ADR-ID, Flagname, Zielkohorte, Prozentstufen, Zeitraum, Metriken, Schwellen, Rollback-Probe, Supporttext und Release Notes verbinden. Datum zum Entfernen des Flags festlegen.", "关联 ADR 标识、开关名称、目标用户群、各阶段百分比、起止时间、指标、错误与任务阈值、回滚演练、支持说明和发布说明，并设定删除临时开关的日期。"),
    boundary: l("Kademeli yayın, hatalı hipotezi doğru yapmaz ve etik/izin sorununu küçültmez. Güvenlik, gizlilik, ayrımcılık veya geri döndürülemez veri etkisi olan değişikliklerde düşük yüzde bile önceden yetkili inceleme gerektirir.", "A staged rollout does not make a bad hypothesis correct or reduce an ethical or permission problem. Changes involving security, privacy, discrimination, or irreversible data impact require qualified review even at a tiny percentage.", "Stufenfreigabe macht eine falsche Hypothese nicht richtig und verkleinert keine Ethik- oder Berechtigungsfrage. Sicherheits-, Datenschutz- oder irreversible Datenwirkung braucht auch bei kleiner Quote qualifizierte Prüfung.", "分阶段发布不能让错误假设变正确，也不能缩小伦理或权限问题；涉及安全、隐私、歧视或不可逆数据影响的变更，即使比例很小也需事先专业审查。"),
    source: { title: { tr: "IETF RFC 2119 — Gereksinim dili", en: "IETF RFC 2119 — Requirement Levels" }, url: "https://www.rfc-editor.org/rfc/rfc2119" },
  },
  {
    slug: "icerik-guncellik-kanit-portfoyu-rehberi", relatedTools: ["icerik-guncellik-portfoyu-planlayici", "kaynak-guncellik-takipcisi", "kanit-sentez-tablosu", "atif-yer-tutucu-denetleyici"],
    title: l("İçerik Güncelliği Portföyü: Tarih Değil Kanıt Yenileme Sistemi", "Content Freshness Portfolio: Renewing Evidence, Not Just Dates", "Content-Aktualitätsportfolio: Nachweise statt Datum erneuern", "内容新鲜度组合：更新证据，而不是只改日期"),
    excerpt: l("Yayın tarihini değiştirmek yerine değişim riski, okuyucu etkisi, kaynak sürümü ve gerçek ürün davranışıyla öncelikli bakım kuyruğu oluşturun.", "Build a maintenance queue from change risk, reader impact, source versions, and real product behaviour instead of merely changing publication dates.", "Wartungspriorität aus Änderungsrisiko, Leserwirkung, Quellenversion und Produktverhalten bilden, statt nur Daten zu ändern.", "不要只修改发布日期；依据变化风险、读者影响、来源版本与真实产品行为建立维护队列。"),
    category: l("Editoryal kalite ve kanıt", "Editorial quality and evidence", "Redaktionelle Qualität und Evidenz", "编辑质量与证据"),
    objective: l("Her rehberin hangi kullanıcı sorusunu çözdüğünü, hangi iddiaların zamana duyarlı olduğunu, hangi birincil kaynak ve ürün davranışıyla doğrulandığını ve sıradaki incelemenin neden o tarihte yapılacağını gösterebilen bakım sistemi kurmak.", "Build a maintenance system that explains each guide's user question, time-sensitive claims, primary evidence and product behaviour used for verification, and why the next review is scheduled when it is.", "Ein Wartungssystem schaffen, das Nutzerfrage, zeitkritische Aussagen, Primärnachweise, Produktprüfung und Grund des nächsten Prüftermins je Leitfaden zeigt.", "建立维护系统：说明每篇指南解决的用户问题、哪些主张对时间敏感、依据哪些第一手来源和产品行为验证，以及为何在该日期复核。"),
    method: l("Envantere başlık ve tarihin yanında değişim riski, yanlış bilginin etkisi, trafik/okuyucu önemi, kaynak sahibi ve son gerçek doğrulama ekleyin. Puan yalnız sırayı önerir; editör yasal değişiklik, güvenlik olayı veya ürün kırılması olduğunda sırayı elle yükseltebilir. İncelemede başlığı değil iddiayı, örneği, ekranı, bağlantıyı ve araç çıktısını yeniden çalıştırın.", "Store change risk, impact of error, audience importance, source owner, and last substantive verification alongside title and date. The score only suggests order; editors can escalate legal change, security events, or product breakage. Re-run claims, examples, screens, links, and tool outputs—not just the headline.", "Neben Titel/Datum Änderungsrisiko, Fehlwirkung, Leserbedeutung, Quellenverantwortung und letzte echte Prüfung erfassen. Score schlägt Reihenfolge vor; Recht, Sicherheit oder Produktbruch dürfen eskalieren. Aussage, Beispiel, Oberfläche, Link und Tool-Ausgabe erneut prüfen.", "除标题和日期外，还要记录变化风险、错误影响、读者重要性、来源负责人和最后一次实质验证。评分只建议顺序；法律变化、安全事件或产品故障可由编辑手动升级。复核时重新验证主张、示例、界面、链接与工具输出，而不是只看标题。"),
    failure: l("Sadece updated alanını değiştirmek, aynı paragrafı yüzlerce sayfada çoğaltmak, kaynak bağlantısını okumadan korumak, ürün ekranı değiştiği halde adımları bırakmak ve AI özetini özgün inceleme gibi yayınlamak kalite açığıdır. Bu durumlar otomatik tekrar taraması ve insan örneklemesiyle aranmalıdır.", "Changing only an updated field, repeating one paragraph across hundreds of pages, retaining unread sources, leaving steps after the interface changes, and publishing AI summaries as original review are quality failures. Search for them with duplication audits and human sampling.", "Nur updated ändern, Absätze massenhaft wiederholen, ungelesene Quellen behalten, Schritte trotz UI-Änderung lassen und KI-Zusammenfassung als eigene Prüfung veröffentlichen sind Qualitätsfehler. Automatisch und menschlich prüfen.", "只改 updated 字段、在数百页重复同一段、未阅读仍保留来源链接、界面变化后步骤不更新、把 AI 摘要当原创审查发布，都是质量缺陷；应通过重复检测和人工抽样发现。"),
    evidence: l("Bakım kaydında eski ve yeni iddia, birincil kaynak sürümü/tarihi, ürün commit veya sürümü, çalıştırılan örnek, bulunan fark, editör adı, sonraki inceleme tetikleyicisi ve kullanıcıya görünür değişiklik notu olmalıdır. Değişiklik yoksa bunun da doğrulama tarihi ve kapsamı yazılmalıdır.", "The maintenance record should contain old and new claims, primary-source version/date, product release, rerun example, observed difference, editor, next trigger, and user-visible change note. If nothing changed, record verification date and scope anyway.", "Wartungsnachweis enthält alte/neue Aussage, Quellenversion/-datum, Produktversion, erneut ausgeführtes Beispiel, Unterschied, Redaktion, nächsten Auslöser und sichtbare Änderungsnotiz. Auch keine Änderung wird mit Umfang datiert.", "维护记录应包含新旧主张、第一手来源版本/日期、产品版本、重跑示例、发现差异、编辑者、下次触发条件和面向用户的变更说明；即使无变化，也要记录验证日期与范围。"),
    boundary: l("Güncellik puanı doğruluk, özgünlük veya arama sıralaması garantisi değildir. Faydalı içerik gerçek kullanıcı sorusunu tamamlamalı, kanıtı doğru aktarmalı, sınırını söylemeli ve üründeki görünür davranışla çelişmemelidir.", "A freshness score guarantees neither accuracy, originality, nor search ranking. Useful content must complete a real user question, represent evidence faithfully, state limits, and remain consistent with visible product behaviour.", "Aktualitätsscore garantiert weder Richtigkeit, Originalität noch Ranking. Nützlicher Inhalt löst eine reale Frage, gibt Nachweise korrekt wieder, nennt Grenzen und entspricht dem sichtbaren Produkt.", "新鲜度评分不保证准确、原创或搜索排名；有用内容必须解决真实用户问题、忠实呈现证据、说明边界，并与可见产品行为一致。"),
    source: { title: { tr: "Google Search Central — Faydalı ve güvenilir içerik", en: "Google Search Central — Helpful, reliable, people-first content" }, url: "https://developers.google.com/search/docs/fundamentals/creating-helpful-content" },
  },
];

const headings = {
  tr: ["Kısa cevap ve hedef", "Girdi ve kapsam sözleşmesi", "Adım adım uygulanabilir yöntem", "Olumsuz ve uç durum testleri", "Sonucu kullanıcı göreviyle doğrulama", "Kanıt ve bakım kaydı", "Sınırlar ve sorumlu sonraki adım"],
  en: ["Short answer and objective", "Input and scope contract", "Step-by-step practical method", "Negative and edge-case tests", "Verify against the user task", "Evidence and maintenance record", "Limits and accountable next step"],
  de: ["Kurzantwort und Ziel", "Eingabe- und Umfangsvertrag", "Praktische Methode Schritt für Schritt", "Negativ- und Grenztests", "Mit der Nutzeraufgabe prüfen", "Nachweis und Wartungsprotokoll", "Grenzen und verantwortlicher nächster Schritt"],
  zh: ["简短答案与目标", "输入与范围契约", "可执行的分步方法", "负面与边界测试", "依据用户任务验证", "证据与维护记录", "边界与负责的下一步"],
} satisfies Record<Locale, string[]>;

function sections(locale: Locale, guide: Guide): ArticleSection[] {
  const shared: Record<Locale, string[]> = {
    tr: [guide.objective.tr, `“${guide.title.tr}” akışında başarı, yalnız aracın çıktı vermesi değil; ${guide.excerpt.tr.charAt(0).toLocaleLowerCase("tr-TR")}${guide.excerpt.tr.slice(1)} Son kararın sahibi ve geri alma yolu baştan görünür olmalıdır.`, guide.method.tr, guide.failure.tr, `${guide.category.tr} kapsamındaki mutlu yolu küçük ve sentetik örnekle kurun; ardından boş, bozuk, aşırı büyük, yinelenen ve sınırda girdileri aynı kabul ölçütleriyle çalıştırın.`, guide.evidence.tr, guide.boundary.tr],
    en: [guide.objective.en, `For “${guide.title.en}”, success is not merely that a tool returned output: ${guide.excerpt.en.charAt(0).toLocaleLowerCase("en-US")}${guide.excerpt.en.slice(1)} Make the decision owner and rollback path visible before execution.`, guide.method.en, guide.failure.en, `Build the ${guide.category.en.toLocaleLowerCase("en-US")} happy path with a small synthetic sample, then run blank, malformed, oversized, duplicated, and boundary inputs against the same acceptance criteria.`, guide.evidence.en, guide.boundary.en],
    de: [guide.objective.de, `Bei „${guide.title.de}“ ist Erfolg nicht nur eine erzeugte Ausgabe: ${guide.excerpt.de} Verantwortung und Rollback werden vor der Ausführung sichtbar festgelegt.`, guide.method.de, guide.failure.de, `Den Erfolgspfad für ${guide.category.de} mit einer kleinen synthetischen Probe aufbauen; danach leere, fehlerhafte, große, doppelte und Grenzwerte mit denselben Kriterien testen.`, guide.evidence.de, guide.boundary.de],
    zh: [guide.objective.zh, `对于“${guide.title.zh}”，成功不只是工具产生输出：${guide.excerpt.zh} 执行前还要明确决策责任人与回退路径。`, guide.method.zh, guide.failure.zh, `先用小型合成样本构建“${guide.category.zh}”正常路径，再以相同验收标准测试空、损坏、超大、重复和边界输入。`, guide.evidence.zh, guide.boundary.zh],
  };
  const second: Record<Locale, string[]> = {
    tr: [`${guide.category.tr} kararında sorumlu kişiyi, yanlış sonucun etkisini, kullanılacak veri sınıfını ve otomatikleştirilmeyecek son onayı başlamadan yazın. “${guide.title.tr}” örneklerine kişisel veya gizli veri taşımayın.`, `Bu akışın her adımında girdiyi, çıktıyı, durdurma koşulunu ve geri alma yolunu görünür tutun. “${guide.slug}” kapsamındaki sessiz düzeltmeleri alanı ve yapılacak eylemi söyleyen hatalara dönüştürün.`, `${guide.title.tr} için rakamları kaynak toplamla, metni gerçek ekranla, güvenlik iddiasını tehdit modeliyle ve içerik iddiasını ${guide.source.title.tr} gibi güncel birincil kanıtla uzlaştırın.`, `${guide.category.tr} görevini masaüstü yanında dar mobil görünüm, klavye, %200 metin, yavaş cihaz ve ağsız durumda tamamlayın; ${guide.failure.tr}`, `Bu kabul kaydında sürüm, tarih, veri örneği, eşik, bilinen risk, onay sahibi ve sonraki inceleme tetikleyicisi bulunmalıdır. Asgari kanıt şudur: ${guide.evidence.tr}`, `Bakım sırasında ${guide.source.title.tr} kaynağını yeniden açın, sürüm veya tarih değişimini kaydedin ve yöntemi aynı sentetik örnekle tekrar çalıştırın. Değişiklik yoksa doğrulanan kapsamı yine yazın.`, `${guide.title.tr} çıktısını nihai gerçek gibi yayınlamayın. ${guide.boundary.tr} Yüksek etkili kararı güncel kaynak ve yetkili insan incelemesine bağlayın.`],
    en: [`For this ${guide.category.en.toLocaleLowerCase("en-US")} decision, name the owner, impact of error, data class, and final approval that will not be automated. Keep personal and confidential data out of “${guide.title.en}” examples.`, `Expose input, output, stop condition, and rollback at every stage of this workflow. Within ${guide.slug}, replace silent repairs with errors that identify the field and recovery action.`, `For ${guide.title.en}, reconcile numbers to source totals, copy to the real interface, security claims to a threat model, and content claims to current primary evidence such as ${guide.source.title.en}.`, `Complete the ${guide.category.en.toLocaleLowerCase("en-US")} task on narrow mobile, keyboard, 200% text, constrained devices, and offline states. Include these specific negative cases: ${guide.failure.en}`, `The acceptance record needs version, date, sample, threshold, known risk, approver, and next review trigger. Its minimum evidence is: ${guide.evidence.en}`, `During maintenance, reopen ${guide.source.title.en}, record its version or date, and rerun the same synthetic sample. If nothing changed, still document the verified scope.`, `Do not publish ${guide.title.en} output as final truth. ${guide.boundary.en} Connect consequential decisions to current sources and qualified human review.`],
    de: [`Für diese Entscheidung in ${guide.category.de} vorab Verantwortung, Fehlwirkung, Datenklasse und nicht automatisierte Endfreigabe festlegen. Keine Personen- oder Geheimdaten in Beispiele zu „${guide.title.de}“ übernehmen.`, `Eingabe, Ausgabe, Stopp und Rollback in jeder Stufe zeigen. Im Ablauf ${guide.slug} stille Korrekturen durch Fehler ersetzen, die Feld und Wiederherstellung nennen.`, `Bei ${guide.title.de} Zahlen mit Quellsummen, Texte mit der realen Oberfläche, Sicherheitsbehauptungen mit dem Bedrohungsmodell und Inhalte mit ${guide.source.title.en} abgleichen.`, `Die Aufgabe ${guide.category.de} auch mobil, per Tastatur, bei 200 % Text, auf schwachen Geräten und offline abschließen. Diese Negativfälle gehören dazu: ${guide.failure.de}`, `Der Abnahmenachweis braucht Version, Datum, Probe, Schwelle, Risiko, Freigabe und Prüfauslöser. Der Mindestnachweis lautet: ${guide.evidence.de}`, `${guide.source.title.en} bei der Wartung erneut öffnen, Version oder Datum erfassen und dieselbe synthetische Probe wiederholen. Auch unveränderte Ergebnisse mit Umfang dokumentieren.`, `Die Ausgabe von ${guide.title.de} ist keine endgültige Wahrheit. ${guide.boundary.de} Folgenreiche Entscheidungen brauchen aktuelle Quellen und qualifizierte Prüfung.`],
    zh: [`针对“${guide.category.zh}”决策，开始前明确责任人、错误影响、数据类别和不得自动化的最终批准；“${guide.title.zh}”示例不得包含个人或机密数据。`, `显示此流程每一步的输入、输出、停止条件和回退方式；在 ${guide.slug} 范围内，错误必须指出字段和修正动作，不得静默修复。`, `对于“${guide.title.zh}”，把数字与来源总数、文案与真实界面、安全主张与威胁模型、内容主张与 ${guide.source.title.en} 等最新第一手证据逐项核对。`, `除桌面外，还要在窄屏移动端、键盘、200% 文本、受限设备和离线状态下完成“${guide.category.zh}”任务，并覆盖这些负面场景：${guide.failure.zh}`, `验收记录必须包含版本、日期、样本、阈值、已知风险、批准者和下次复核触发条件；最低证据要求是：${guide.evidence.zh}`, `维护时重新打开 ${guide.source.title.en}，记录其版本或日期，并用同一合成样本重跑；即使无变化，也要记录已验证范围。`, `不要把“${guide.title.zh}”输出当作最终事实。${guide.boundary.zh} 重大决策必须关联最新来源并由合格人员复核。`],
  };
  return headings[locale].map((heading, index) => ({ heading, paragraphs: [shared[locale][index], second[locale][index]], bullets: index === 0 ? [guide.objective[locale]] : index === 6 ? [guide.boundary[locale]] : undefined }));
}

export const insightPosts: Post[] = guides.map((guide) => ({
  slug: guide.slug, relatedTools: guide.relatedTools, date: "2026-09-07", updated: "2026-09-07", readTime: { tr: "17 dk", en: "16 min" }, title: { tr: guide.title.tr, en: guide.title.en }, excerpt: { tr: guide.excerpt.tr, en: guide.excerpt.en }, description: { tr: `${guide.excerpt.tr} Uygulama, olumsuz test, kabul kanıtı ve bakım adımlarıyla özgün rehber.`, en: `${guide.excerpt.en} An original guide with implementation, negative tests, acceptance evidence, and maintenance steps.` }, category: { tr: guide.category.tr, en: guide.category.en }, visualSuggestion: { tr: "Girdi, doğrulama, hata yolu, kanıt ve insan onayını gösteren erişilebilir karar akışı.", en: "An accessible decision flow showing input, validation, failure paths, evidence, and human approval." }, sources: [guide.source], sections: { tr: sections("tr", guide), en: sections("en", guide) },
}));

export const insightLocalizedGuides: LocalizedGuide[] = guides.map((guide) => ({
  slug: guide.slug, relatedTools: guide.relatedTools, date: "2026-09-07", updated: "2026-09-07", copy: {
    de: { title: guide.title.de, excerpt: guide.excerpt.de, description: `${guide.excerpt.de} Eigenständiger Praxisleitfaden mit Negativtests, Nachweisen und Wartung.`, category: guide.category.de, readTime: "16 Min.", sections: sections("de", guide) },
    zh: { title: guide.title.zh, excerpt: guide.excerpt.zh, description: `${guide.excerpt.zh} 包含负面测试、验收证据与维护步骤的原创实践指南。`, category: guide.category.zh, readTime: "约 16 分钟", sections: sections("zh", guide) },
  },
}));

export const insightGuideCount = guides.length;
