import type { Locale } from "./site";
import { detectCsvDelimiter, parseCsv } from "./csv-conversion";
import type { StudioDefinition, StudioResult, StudioValues } from "../components/StudioWorkbenches";

type L = Record<Locale, string>;
const l = (tr: string, en: string, de: string, zh: string): L => ({ tr, en, de, zh });
const tx = (locale: Locale, value: L) => value[locale];
const lines = (value: unknown) => String(value ?? "").split(/\r?\n/u).map((line) => line.trim()).filter(Boolean);
const table = (rows: Array<Array<string | number>>) => rows.map((row, index) => `| ${row.map((cell) => String(cell).replace(/\|/g, "\\|").replace(/\r?\n/g, " ")).join(" | ")} |${index === 0 ? `\n| ${row.map(() => "---").join(" | ")} |` : ""}`).join("\n");
const boundary = (locale: Locale) => tx(locale, l("Sonucu kaynak kayıtla ve gerçek kullanıcı göreviyle doğrulayın; bu yerel ön kontrol tek başına resmî uygunluk veya canlı sistem kanıtı değildir.", "Verify the result against source records and the real user task; this local pre-check alone is not proof of formal compliance or live-system behaviour.", "Ergebnis mit Quelldaten und realer Nutzeraufgabe prüfen; diese lokale Vorprüfung allein beweist weder formelle Konformität noch Live-Verhalten.", "请根据源记录和真实用户任务验证结果；本地预检查本身不能证明正式合规或线上系统行为。"));
const numberValue = (values: StudioValues, key: string, locale: Locale, min: number, max: number) => {
  const raw = String(values[key] ?? "").trim(); const value = Number(raw);
  if (!raw || !Number.isFinite(value) || value < min || value > max) throw new Error(tx(locale, l(`${key} alanına ${min}–${max} arasında geçerli bir sayı girin.`, `Enter a valid ${key} value between ${min} and ${max}.`, `Für ${key} einen gültigen Wert zwischen ${min} und ${max} eingeben.`, `请为 ${key} 输入 ${min}–${max} 之间的有效数字。`)));
  return value;
};
const percentile = (sorted: number[], percent: number) => sorted[Math.max(0, Math.ceil(percent * sorted.length) - 1)];
const field = (key: string, label: L, type: "text" | "number" | "date" | "textarea" | "checkbox" | "select" = "text", help?: L, min?: number, max?: number, step?: number) => ({ key, label, type, help, min, max, step });

export const insightDefinitions: Record<string, StudioDefinition> = {
  "csv-satir-fark-uzlastirici": { fields: [field("before", l("Önceki CSV", "Before CSV", "Vorher-CSV", "变更前 CSV"), "textarea"), field("after", l("Sonraki CSV", "After CSV", "Nachher-CSV", "变更后 CSV"), "textarea"), field("key", l("Benzersiz anahtar sütunu", "Unique key column", "Eindeutige Schlüsselspalte", "唯一键列"))], demo: { before: "id,name,status\n101,Ada,active\n102,Deniz,pending\n103,Lin,active", after: "id,name,status\n101,Ada,active\n102,Deniz,active\n104,Mira,pending", key: "id" } },
  "json-alan-tip-profilleyici": { fields: [field("json", l("JSON nesne dizisi", "JSON object array", "JSON-Objektliste", "JSON 对象数组"), "textarea")], demo: { json: "[\n  {\"id\":1,\"active\":true,\"score\":9.4},\n  {\"id\":2,\"active\":null,\"score\":\"pending\"},\n  {\"id\":3,\"score\":8.7,\"tags\":[\"new\"]}\n]" } },
  "web-vitals-ornek-analizoru": { fields: [field("samples", l("Ölçümler", "Measurements", "Messwerte", "测量数据"), "textarea", l("rota | LCP/INP/CLS | değer", "route | LCP/INP/CLS | value", "Route | LCP/INP/CLS | Wert", "路径 | LCP/INP/CLS | 数值"))], demo: { samples: "/|LCP|2100\n/|INP|145\n/|CLS|0.06\n/tools|LCP|2780\n/tools|INP|230\n/tools|CLS|0.14\n/agent|LCP|1980\n/agent|INP|175\n/agent|CLS|0.04" } },
  "css-z-index-katman-haritasi": { fields: [field("css", l("İncelenecek CSS", "CSS to inspect", "Zu prüfendes CSS", "待检查 CSS"), "textarea"), field("budget", l("Azami katman bütçesi", "Maximum layer budget", "Maximales Ebenenbudget", "最大层级预算"), "number", undefined, 1, 100000)], demo: { css: ".site-header { position: sticky; z-index: 40; }\n.dropdown { position: absolute; z-index: 60; }\n.modal { position: fixed; z-index: 1000; }\n.toast { z-index: 1000; }\n.legacy-overlay { z-index: 99999; }", budget: "2000" } },
  "tarayici-depolama-butce-planlayici": { fields: [field("items", l("Depolama kalemleri", "Storage items", "Speicherposten", "存储项目"), "textarea", l("ad | localStorage/IndexedDB/Cache | MB", "name | localStorage/IndexedDB/Cache | MB", "Name | localStorage/IndexedDB/Cache | MB", "名称 | localStorage/IndexedDB/Cache | MB")), field("budget", l("Toplam bütçe (MB)", "Total budget (MB)", "Gesamtbudget (MB)", "总预算（MB）"), "number", undefined, 1, 100000), field("margin", l("Koruma payı (%)", "Safety margin (%)", "Sicherheitsreserve (%)", "安全余量（%）"), "number", undefined, 0, 80)], demo: { items: "preferences|localStorage|0.3\nconversation-index|IndexedDB|18\nlocal-model|Cache|920\noffline-tools|Cache|42", budget: "1200", margin: "20" } },
  "api-oran-siniri-kapasite-planlayici": { fields: [field("users", l("Tepe eşzamanlı kullanıcı", "Peak concurrent users", "Gleichzeitige Nutzer (Spitze)", "峰值并发用户"), "number", undefined, 1, 10000000), field("perUser", l("Kullanıcı başına istek/dakika", "Requests per user/minute", "Anfragen pro Nutzer/Minute", "每用户每分钟请求"), "number", undefined, 0.01, 100000), field("quota", l("Pencere kotası", "Window quota", "Fensterquote", "窗口配额"), "number", undefined, 1, 1000000000), field("window", l("Pencere süresi (dakika)", "Window length (minutes)", "Fensterlänge (Minuten)", "窗口时长（分钟）"), "number", undefined, 0.1, 1440), field("headroom", l("Hedef koruma payı (%)", "Target headroom (%)", "Zielreserve (%)", "目标余量（%）"), "number", undefined, 0, 90)], demo: { users: "240", perUser: "1.8", quota: "12000", window: "15", headroom: "20" } },
  "dosya-manifestosu-uzlastirici": { fields: [field("source", l("Kaynak manifestosu", "Source manifest", "Quellmanifest", "源清单"), "textarea", l("yol | bayt | SHA-256", "path | bytes | SHA-256", "Pfad | Bytes | SHA-256", "路径 | 字节 | SHA-256")), field("target", l("Hedef manifestosu", "Target manifest", "Zielmanifest", "目标清单"), "textarea")], demo: { source: "index.html|14280|a1b2c3\nassets/app.js|88420|d4e5f6\nassets/app.css|19320|112233", target: "index.html|14280|a1b2c3\nassets/app.js|90110|ffeedd\nassets/logo.svg|3200|778899" } },
  "url-yonlendirme-zinciri-inceleyici": { fields: [field("hops", l("Yönlendirme adımları", "Redirect hops", "Weiterleitungsschritte", "重定向步骤"), "textarea", l("durum | mutlak URL", "status | absolute URL", "Status | absolute URL", "状态 | 绝对 URL"))], demo: { hops: "301|http://example.com/old\n302|https://example.com/old/\n301|https://www.example.com/new\n200|https://example.com/new/" } },
  "api-hata-zarfi-dogrulayici": { fields: [field("json", l("Hata yanıtı JSON", "Error response JSON", "Fehlerantwort-JSON", "错误响应 JSON"), "textarea"), field("traceRequired", l("İzleme kimliği zorunlu", "Require a trace id", "Trace-ID erforderlich", "必须包含追踪 ID"), "checkbox")], demo: { json: "{\n  \"error\": {\n    \"code\": \"VALIDATION_FAILED\",\n    \"message\": \"Please review the highlighted fields.\",\n    \"traceId\": \"req_01J8K4\",\n    \"fields\": [{\"name\":\"email\",\"reason\":\"invalid_format\"}]\n  }\n}", traceRequired: true } },
  "ozellik-bayragi-yayin-planlayici": { fields: [field("audience", l("Uygun kullanıcı sayısı", "Eligible users", "Berechtigte Nutzer", "符合条件的用户数"), "number", undefined, 1, 1000000000), field("stages", l("Yüzde aşamaları", "Percentage stages", "Prozentstufen", "百分比阶段"), "text", l("Örn. 1,5,20,50,100", "Example: 1,5,20,50,100", "Beispiel: 1,5,20,50,100", "示例：1,5,20,50,100")), field("hours", l("Aşama başına gözlem (saat)", "Observation per stage (hours)", "Beobachtung je Stufe (Stunden)", "每阶段观察时长（小时）"), "number", undefined, 0.5, 720), field("error", l("Geri alma hata eşiği (%)", "Rollback error threshold (%)", "Fehlerschwelle für Rollback (%)", "回滚错误阈值（%）"), "number", undefined, 0, 100)], demo: { audience: "48000", stages: "1,5,20,50,100", hours: "24", error: "1.5" } },
  "yanit-suresi-yuzdelik-hesaplayici": { fields: [field("samples", l("Yanıt süreleri (ms)", "Response times (ms)", "Antwortzeiten (ms)", "响应时间（毫秒）"), "textarea", l("Virgül, boşluk veya satırla ayırın", "Separate with commas, spaces, or lines", "Mit Komma, Leerzeichen oder Zeile trennen", "使用逗号、空格或换行分隔"))], demo: { samples: "82, 91, 94, 97, 103, 110, 118, 126, 149, 175, 220, 410" } },
  "kuyruk-kapasite-planlayici": { fields: [field("arrival", l("Gelen iş/dakika", "Arriving jobs/minute", "Eingehende Jobs/Minute", "每分钟到达任务"), "number", undefined, 0, 100000000), field("duration", l("Ortalama işlem süresi (ms)", "Mean processing time (ms)", "Mittlere Bearbeitungszeit (ms)", "平均处理时间（毫秒）"), "number", undefined, 1, 86400000), field("workers", l("Paralel işçi", "Parallel workers", "Parallele Worker", "并行工作线程"), "number", undefined, 1, 100000), field("backlog", l("Başlangıç kuyruğu", "Starting backlog", "Start-Backlog", "初始积压"), "number", undefined, 0, 1000000000), field("burst", l("Patlama süresi (dakika)", "Burst duration (minutes)", "Burstdauer (Minuten)", "突发时长（分钟）"), "number", undefined, 1, 10080)], demo: { arrival: "180", duration: "450", workers: "2", backlog: "120", burst: "30" } },
  "dokunma-hedefi-boyut-denetleyici": { fields: [field("targets", l("Ölçülen hedefler", "Measured targets", "Gemessene Ziele", "已测量目标"), "textarea", l("seçici | genişlik | yükseklik | en yakın aralık (px)", "selector | width | height | nearest gap (px)", "Selektor | Breite | Höhe | nächster Abstand (px)", "选择器 | 宽度 | 高度 | 最近间距（px）")), field("size", l("Asgari boyut (px)", "Minimum size (px)", "Mindestgröße (px)", "最小尺寸（px）"), "number", undefined, 20, 80), field("gap", l("Asgari aralık (px)", "Minimum gap (px)", "Mindestabstand (px)", "最小间距（px）"), "number", undefined, 0, 32)], demo: { targets: ".menu-toggle|44|44|12\n.tool-card__pin|32|32|6\n.share-action|48|40|10\n.language-option|52|52|14", size: "44", gap: "8" } },
  "icerik-guncellik-portfoyu-planlayici": { fields: [field("records", l("İçerik kayıtları", "Content records", "Inhaltsdatensätze", "内容记录"), "textarea", l("başlık | son doğrulama YYYY-AA-GG | değişim riski 1-5 | önem 1-5", "title | last verified YYYY-MM-DD | change risk 1-5 | importance 1-5", "Titel | zuletzt geprüft YYYY-MM-DD | Änderungsrisiko 1-5 | Bedeutung 1-5", "标题 | 最后验证 YYYY-MM-DD | 变化风险 1-5 | 重要性 1-5")), field("capacity", l("Haftalık inceleme kapasitesi", "Weekly review capacity", "Wöchentliche Prüfkapazität", "每周复核容量"), "number", undefined, 1, 1000)], demo: { records: "PWA kurulum rehberi|2026-07-10|4|5\nJSON biçimlendirme rehberi|2026-08-20|1|4\nGizlilik politikası açıklaması|2026-06-15|5|5\nRenk kontrastı rehberi|2026-08-01|2|3", capacity: "2" } },
  "adr-karar-kaydi-olusturucu": { fields: [field("title", l("Karar başlığı", "Decision title", "Entscheidungstitel", "决策标题")), field("context", l("Bağlam ve sorun", "Context and problem", "Kontext und Problem", "背景与问题"), "textarea"), field("options", l("Değerlendirilen seçenekler", "Options considered", "Geprüfte Optionen", "已评估选项"), "textarea", l("Her satırda bir seçenek", "One option per line", "Eine Option pro Zeile", "每行一个选项")), field("decision", l("Seçilen karar ve gerekçe", "Chosen decision and rationale", "Entscheidung und Begründung", "所选决策与理由"), "textarea"), field("consequences", l("Olumlu ve olumsuz sonuçlar", "Positive and negative consequences", "Positive und negative Folgen", "正面与负面后果"), "textarea"), field("evidence", l("Kanıt ve bağlantı adları", "Evidence and link labels", "Nachweise und Linkbezeichnungen", "证据与链接名称"), "textarea"), field("revisit", l("Yeniden değerlendirme tetikleyicisi", "Reconsideration trigger", "Auslöser zur Neubewertung", "重新评估触发条件"), "textarea")], demo: { title: "Araç işlemlerini varsayılan olarak tarayıcıda tut", context: "Kullanıcı girdileri hassas olabilir; küçük ve deterministik dönüşümler için uzak işlem gerekmiyor.", options: "Tarayıcı içinde işlem\nKendi sunucumuzda işlem\nÜçüncü taraf API", decision: "Deterministik çekirdeği tarayıcıda çalıştır; dış işlem gereken özellikleri açık rıza ve görünür sınırla ayır.", consequences: "+ Girdi aktarımı azalır\n+ Çevrimdışı çalışma mümkün olur\n- Cihaz kapasitesi değişkendir\n- Büyük modeller ilk kullanımda indirme gerektirir", evidence: "Tehdit modeli\nPerformans bütçesi\nTarayıcı uyumluluk matrisi", revisit: "Desteklenen tarayıcı oranı %95'in altına düşerse veya görev 128 MB üzeri sürekli bellek gerektirirse." } },
};

function parsePipe(value: unknown, count: number, locale: Locale) {
  return lines(value).map((row, index) => { const parts = row.split("|").map((item) => item.trim()); if (parts.length !== count || parts.some((part) => !part)) throw new Error(tx(locale, l(`${index + 1}. satır tam olarak ${count} dolu alan içermelidir.`, `Line ${index + 1} must contain exactly ${count} non-empty fields.`, `Zeile ${index + 1} muss genau ${count} ausgefüllte Felder enthalten.`, `第 ${index + 1} 行必须恰好包含 ${count} 个非空字段。`))); return parts; });
}

export function runInsightTool(slug: string, values: StudioValues, locale: Locale): StudioResult {
  if (slug === "csv-satir-fark-uzlastirici") {
    const beforeRows = parseCsv(String(values.before ?? ""), locale, detectCsvDelimiter(String(values.before ?? ""))).filter((row) => row.some(Boolean));
    const afterRows = parseCsv(String(values.after ?? ""), locale, detectCsvDelimiter(String(values.after ?? ""))).filter((row) => row.some(Boolean));
    const beforeHead = beforeRows[0]?.map((item) => item.trim()) ?? [], afterHead = afterRows[0]?.map((item) => item.trim()) ?? [], key = String(values.key ?? "").trim();
    if (!key || !beforeHead.includes(key) || !afterHead.includes(key)) throw new Error(tx(locale, l("Anahtar sütun her iki CSV başlığında da bulunmalıdır.", "The key column must exist in both CSV headers.", "Die Schlüsselspalte muss in beiden CSV-Kopfzeilen vorkommen.", "唯一键列必须同时存在于两个 CSV 表头中。")));
    const makeMap = (rows: string[][], headers: string[]) => { const map = new Map<string, Record<string, string>>(); for (const [index, row] of rows.slice(1).entries()) { if (row.length !== headers.length) throw new Error(tx(locale, l(`${index + 2}. CSV satırının sütun sayısı başlıkla eşleşmiyor.`, `CSV row ${index + 2} does not match the header width.`, `CSV-Zeile ${index + 2} stimmt nicht mit der Kopfbreite überein.`, `CSV 第 ${index + 2} 行列数与表头不一致。`))); const record = Object.fromEntries(headers.map((header, cell) => [header, row[cell]])); const id = record[key]?.trim(); if (!id || map.has(id)) throw new Error(tx(locale, l(`Anahtar boş veya yineleniyor: ${id || "∅"}.`, `The key is blank or duplicated: ${id || "∅"}.`, `Schlüssel leer oder doppelt: ${id || "∅"}.`, `键为空或重复：${id || "∅"}。`))); map.set(id, record); } return map; };
    const before = makeMap(beforeRows, beforeHead), after = makeMap(afterRows, afterHead); const all = [...new Set([...before.keys(), ...after.keys()])];
    const changed = all.flatMap((id) => { const left = before.get(id), right = after.get(id); if (!left) return [[id, tx(locale, l("Eklendi", "Added", "Neu", "新增")), "—"]]; if (!right) return [[id, tx(locale, l("Kaldırıldı", "Removed", "Entfernt", "删除")), "—"]]; const fields = [...new Set([...Object.keys(left), ...Object.keys(right)])].filter((fieldName) => fieldName !== key && (left[fieldName] ?? "") !== (right[fieldName] ?? "")); return fields.length ? [[id, tx(locale, l("Değişti", "Changed", "Geändert", "变更")), fields.join(", ")]] : []; });
    const added = all.filter((id) => !before.has(id)).length, removed = all.filter((id) => !after.has(id)).length, modified = changed.filter((row) => row[1] === tx(locale, l("Değişti", "Changed", "Geändert", "变更"))).length;
    return { output: `${table([[key, tx(locale, l("Durum", "Status", "Status", "状态")), tx(locale, l("Değişen alanlar", "Changed fields", "Geänderte Felder", "变更字段"))], ...changed])}\n\n${boundary(locale)}`, metrics: [[tx(locale, l("Eklendi", "Added", "Neu", "新增")), added], [tx(locale, l("Kaldırıldı", "Removed", "Entfernt", "删除")), removed], [tx(locale, l("Değişti", "Changed", "Geändert", "变更")), modified]] };
  }
  if (slug === "json-alan-tip-profilleyici") {
    let data: unknown; try { data = JSON.parse(String(values.json ?? "")); } catch { throw new Error(tx(locale, l("Geçerli JSON girin.", "Enter valid JSON.", "Gültiges JSON eingeben.", "请输入有效 JSON。"))); }
    if (!Array.isArray(data) || !data.length || data.length > 10000 || !data.every((item) => item && typeof item === "object" && !Array.isArray(item))) throw new Error(tx(locale, l("1–10.000 düz JSON nesnesinden oluşan bir dizi girin.", "Enter an array of 1–10,000 flat JSON objects.", "Eine Liste aus 1–10.000 flachen JSON-Objekten eingeben.", "请输入由 1–10,000 个扁平 JSON 对象组成的数组。")));
    const records = data as Array<Record<string, unknown>>, keys = [...new Set(records.flatMap(Object.keys))]; const kind = (value: unknown) => value === null ? "null" : Array.isArray(value) ? "array" : typeof value;
    const rows = keys.map((key) => { const present = records.filter((record) => Object.hasOwn(record, key)), types = [...new Set(present.map((record) => kind(record[key])))]; const nulls = present.filter((record) => record[key] === null).length; const sample = present.find((record) => record[key] !== null)?.[key]; return [key, types.join(", "), present.length, records.length - present.length, nulls, JSON.stringify(sample)?.slice(0, 64) ?? "—"]; }); const mixed = rows.filter((row) => String(row[1]).split(",").length > 1).length;
    return { output: `${table([[tx(locale, l("Alan", "Field", "Feld", "字段")), tx(locale, l("Tipler", "Types", "Typen", "类型")), tx(locale, l("Var", "Present", "Vorhanden", "存在")), tx(locale, l("Eksik", "Missing", "Fehlt", "缺失")), "null", tx(locale, l("Örnek", "Sample", "Beispiel", "样例"))], ...rows])}\n\n${boundary(locale)}`, metrics: [[tx(locale, l("Kayıt", "Records", "Datensätze", "记录")), records.length], [tx(locale, l("Alan", "Fields", "Felder", "字段")), keys.length], [tx(locale, l("Karma tip", "Mixed-type fields", "Gemischte Felder", "混合类型字段")), mixed]], warning: mixed ? tx(locale, l("Karma tipli alanları şema veya içe aktarma öncesinde inceleyin.", "Review mixed-type fields before schema design or import.", "Gemischte Feldtypen vor Schema oder Import prüfen.", "在架构设计或导入前检查混合类型字段。")) : undefined };
  }
  if (slug === "web-vitals-ornek-analizoru") {
    const rows = parsePipe(values.samples, 3, locale).map(([route, metric, raw], index) => { const normalized = metric.toUpperCase(); const value = Number(raw); if (!["LCP", "INP", "CLS"].includes(normalized) || !Number.isFinite(value) || value < 0) throw new Error(tx(locale, l(`${index + 1}. ölçüm geçersiz.`, `Measurement ${index + 1} is invalid.`, `Messwert ${index + 1} ist ungültig.`, `第 ${index + 1} 条测量无效。`))); return { route, metric: normalized, value }; }); if (!rows.length) throw new Error(tx(locale, l("En az bir ölçüm girin.", "Enter at least one measurement.", "Mindestens einen Messwert eingeben.", "请至少输入一条测量。")));
    const thresholds: Record<string, [number, number]> = { LCP: [2500, 4000], INP: [200, 500], CLS: [0.1, 0.25] }; const groups = [...new Set(rows.map((row) => `${row.route}|${row.metric}`))].map((key) => { const [route, metric] = key.split("|"); const samples = rows.filter((row) => row.route === route && row.metric === metric).map((row) => row.value).sort((a, b) => a - b); const [good, poor] = thresholds[metric]; return [route, metric, samples.length, percentile(samples, .5), percentile(samples, .75), percentile(samples, .95), samples.filter((value) => value <= good).length, samples.filter((value) => value > poor).length]; }); const poor = groups.reduce((sum, row) => sum + Number(row[7]), 0);
    return { output: `${table([[tx(locale, l("Rota", "Route", "Route", "路径")), tx(locale, l("Metrik", "Metric", "Metrik", "指标")), "n", "p50", "p75", "p95", tx(locale, l("İyi", "Good", "Gut", "良好")), tx(locale, l("Zayıf", "Poor", "Schlecht", "较差"))], ...groups])}\n\n${boundary(locale)}`, metrics: [[tx(locale, l("Ölçüm", "Samples", "Messwerte", "样本")), rows.length], [tx(locale, l("Rota/metrik", "Route/metric groups", "Route/Metrik", "路径/指标组合")), groups.length], [tx(locale, l("Zayıf örnek", "Poor samples", "Schlechte Werte", "较差样本")), poor]], warning: rows.length < 30 ? tx(locale, l("Örnek küçük; yüzdelikleri yön gösterici olarak okuyun.", "The sample is small; treat percentiles as directional.", "Kleine Stichprobe; Perzentile nur als Hinweis nutzen.", "样本较小；百分位仅供方向参考。")) : undefined };
  }
  if (slug === "css-z-index-katman-haritasi") {
    const css = String(values.css ?? ""), budget = numberValue(values, "budget", locale, 1, 100000); if (!css.trim()) throw new Error(tx(locale, l("CSS girin.", "Enter CSS.", "CSS eingeben.", "请输入 CSS。"))); const matches = [...css.matchAll(/([^{}]+)\{[^{}]*?z-index\s*:\s*(-?\d+)\s*;?[^{}]*?\}/giu)].map((match) => ({ selector: match[1].trim().replace(/\s+/g, " "), value: Number(match[2]) })).sort((a, b) => b.value - a.value); if (!matches.length) throw new Error(tx(locale, l("Sayısal z-index bildirimi bulunamadı.", "No numeric z-index declaration was found.", "Keine numerische z-index-Angabe gefunden.", "未找到数字 z-index 声明。"))); const counts = new Map<number, number>(); matches.forEach((item) => counts.set(item.value, (counts.get(item.value) ?? 0) + 1)); const over = matches.filter((item) => item.value > budget).length, collisions = [...counts.values()].filter((count) => count > 1).length;
    return { output: `${table([[tx(locale, l("Seçici", "Selector", "Selektor", "选择器")), "z-index", tx(locale, l("Not", "Note", "Hinweis", "说明"))], ...matches.map((item) => [item.selector, item.value, item.value > budget ? tx(locale, l("Bütçe üstü", "Above budget", "Über Budget", "超出预算")) : (counts.get(item.value) ?? 0) > 1 ? tx(locale, l("Paylaşılan katman", "Shared layer", "Gemeinsame Ebene", "共享层级")) : "✓"])])}\n\n${boundary(locale)}`, metrics: [[tx(locale, l("Bildirim", "Declarations", "Angaben", "声明")), matches.length], [tx(locale, l("Çakışan değer", "Shared values", "Geteilte Werte", "共享数值")), collisions], [tx(locale, l("Bütçe üstü", "Above budget", "Über Budget", "超出预算")), over]] };
  }
  if (slug === "tarayici-depolama-butce-planlayici") {
    const items = parsePipe(values.items, 3, locale).map(([name, kind, raw], index) => { const mb = Number(raw); if (!Number.isFinite(mb) || mb < 0) throw new Error(tx(locale, l(`${index + 1}. satırdaki MB değeri geçersiz.`, `The MB value on line ${index + 1} is invalid.`, `Der MB-Wert in Zeile ${index + 1} ist ungültig.`, `第 ${index + 1} 行的 MB 数值无效。`))); return { name, kind, mb }; }); const budget = numberValue(values, "budget", locale, 1, 100000), margin = numberValue(values, "margin", locale, 0, 80), usable = budget * (1 - margin / 100), total = items.reduce((sum, item) => sum + item.mb, 0); const sorted = [...items].sort((a, b) => b.mb - a.mb); const overflow = Math.max(0, total - usable);
    return { output: `${table([[tx(locale, l("Kalem", "Item", "Posten", "项目")), tx(locale, l("Tür", "Type", "Typ", "类型")), "MB", "%"], ...sorted.map((item) => [item.name, item.kind, item.mb.toFixed(2), total ? `${(item.mb / total * 100).toFixed(1)}%` : "0%"])])}\n\n${tx(locale, overflow ? l(`Koruma payını korumak için en az ${overflow.toFixed(2)} MB azaltın.`, `Reduce at least ${overflow.toFixed(2)} MB to preserve the safety margin.`, `Mindestens ${overflow.toFixed(2)} MB reduzieren, um die Reserve zu halten.`, `至少减少 ${overflow.toFixed(2)} MB 以保留安全余量。`) : l(`${(usable - total).toFixed(2)} MB kullanılabilir korumalı alan kaldı.`, `${(usable - total).toFixed(2)} MB of protected headroom remains.`, `${(usable - total).toFixed(2)} MB geschützte Reserve verbleiben.`, `剩余 ${(usable - total).toFixed(2)} MB 受保护余量。`))}\n${boundary(locale)}`, metrics: [[tx(locale, l("Kullanım", "Usage", "Nutzung", "使用量")), `${total.toFixed(2)} MB`], [tx(locale, l("Korumalı sınır", "Protected limit", "Geschützte Grenze", "保护上限")), `${usable.toFixed(2)} MB`], [tx(locale, l("Durum", "Status", "Status", "状态")), overflow ? "REVIEW" : "PASS"]], warning: overflow ? tx(locale, l("Plan korumalı bütçeyi aşıyor.", "The plan exceeds the protected budget.", "Der Plan überschreitet das geschützte Budget.", "计划超过受保护预算。")) : undefined };
  }
  if (slug === "api-oran-siniri-kapasite-planlayici") {
    const users = numberValue(values, "users", locale, 1, 10000000), perUser = numberValue(values, "perUser", locale, .01, 100000), quota = numberValue(values, "quota", locale, 1, 1000000000), window = numberValue(values, "window", locale, .1, 1440), headroom = numberValue(values, "headroom", locale, 0, 90); const expected = users * perUser * window, protectedQuota = quota * (1 - headroom / 100), ratio = expected / protectedQuota, safeUsers = Math.floor(protectedQuota / (perUser * window));
    const scenarios = [[tx(locale, l("Sürekli yük", "Sustained load", "Dauerlast", "持续负载")), expected.toFixed(0), `${(ratio * 100).toFixed(1)}%`], [tx(locale, l("2× patlama", "2× burst", "2× Burst", "2× 突发")), (expected * 2).toFixed(0), `${(ratio * 200).toFixed(1)}%`]];
    return { output: `${table([[tx(locale, l("Senaryo", "Scenario", "Szenario", "场景")), tx(locale, l("Pencere isteği", "Window requests", "Fensteranfragen", "窗口请求数")), tx(locale, l("Korumalı kota kullanımı", "Protected quota use", "Geschützte Quotennutzung", "保护配额使用率"))], ...scenarios])}\n\n${tx(locale, l(`Bu varsayımlarla korumalı sürekli kapasite yaklaşık ${safeUsers} eşzamanlı kullanıcıdır.`, `With these assumptions, protected sustained capacity is about ${safeUsers} concurrent users.`, `Mit diesen Annahmen liegt die geschützte Dauerkapazität bei etwa ${safeUsers} gleichzeitigen Nutzern.`, `按这些假设，受保护的持续容量约为 ${safeUsers} 名并发用户。`))}\n${boundary(locale)}`, metrics: [[tx(locale, l("Beklenen", "Expected", "Erwartet", "预期")), expected.toFixed(0)], [tx(locale, l("Korumalı kota", "Protected quota", "Geschützte Quote", "保护配额")), protectedQuota.toFixed(0)], [tx(locale, l("Kapasite", "Capacity", "Kapazität", "容量")), `${safeUsers}`]], warning: ratio > 1 ? tx(locale, l("Sürekli yük korumalı kotayı aşıyor.", "Sustained load exceeds the protected quota.", "Die Dauerlast überschreitet die geschützte Quote.", "持续负载超过受保护配额。")) : undefined };
  }
  if (slug === "dosya-manifestosu-uzlastirici") {
    const parse = (value: unknown) => { const rows = parsePipe(value, 3, locale); const map = new Map<string, { bytes: number; digest: string }>(); rows.forEach(([path, rawBytes, digest], index) => { const bytes = Number(rawBytes); if (!Number.isSafeInteger(bytes) || bytes < 0 || map.has(path)) throw new Error(tx(locale, l(`${index + 1}. satırda boyut geçersiz veya yol yineleniyor.`, `Line ${index + 1} has an invalid size or duplicate path.`, `Zeile ${index + 1} hat eine ungültige Größe oder einen doppelten Pfad.`, `第 ${index + 1} 行大小无效或路径重复。`))); map.set(path, { bytes, digest: digest.toLowerCase() }); }); return map; }; const source = parse(values.source), target = parse(values.target); const paths = [...new Set([...source.keys(), ...target.keys()])]; const changes = paths.flatMap((path) => { const left = source.get(path), right = target.get(path); if (!left) return [[path, tx(locale, l("Hedefte yeni", "New in target", "Neu im Ziel", "目标新增")), "—"]]; if (!right) return [[path, tx(locale, l("Hedefte eksik", "Missing in target", "Fehlt im Ziel", "目标缺失")), "—"]]; const flags = [left.bytes !== right.bytes ? tx(locale, l("boyut", "size", "Größe", "大小")) : "", left.digest !== right.digest ? tx(locale, l("özet", "digest", "Digest", "摘要")) : ""].filter(Boolean); return flags.length ? [[path, tx(locale, l("Uyuşmuyor", "Mismatch", "Abweichung", "不匹配")), flags.join(", ")]] : []; });
    return { output: `${table([[tx(locale, l("Yol", "Path", "Pfad", "路径")), tx(locale, l("Durum", "Status", "Status", "状态")), tx(locale, l("Fark", "Difference", "Unterschied", "差异"))], ...changes])}\n\n${changes.length ? "" : tx(locale, l("✓ Manifestolar yol, boyut ve özet düzeyinde eşleşiyor.\n", "✓ The manifests match at path, size, and digest level.\n", "✓ Die Manifeste stimmen bei Pfad, Größe und Digest überein.\n", "✓ 两份清单在路径、大小与摘要层面一致。\n"))}${boundary(locale)}`, metrics: [[tx(locale, l("Kaynak dosya", "Source files", "Quelldateien", "源文件")), source.size], [tx(locale, l("Hedef dosya", "Target files", "Zieldateien", "目标文件")), target.size], [tx(locale, l("Fark", "Differences", "Abweichungen", "差异")), changes.length]], warning: changes.length ? tx(locale, l("Hedef manifestoda uzlaştırılması gereken farklar var.", "The target manifest contains differences to reconcile.", "Das Zielmanifest enthält abzugleichende Unterschiede.", "目标清单存在需要核对的差异。")) : undefined };
  }
  if (slug === "url-yonlendirme-zinciri-inceleyici") {
    const hops = parsePipe(values.hops, 2, locale).map(([rawStatus, rawUrl], index) => { const status = Number(rawStatus); if (![200, 301, 302, 303, 307, 308].includes(status)) throw new Error(tx(locale, l(`${index + 1}. durum kodu desteklenen yönlendirme/sonuç kodu değil.`, `Status on line ${index + 1} is not a supported redirect/final code.`, `Status in Zeile ${index + 1} wird nicht unterstützt.`, `第 ${index + 1} 行状态码不是支持的重定向/最终状态码。`))); let url: URL; try { url = new URL(rawUrl); } catch { throw new Error(tx(locale, l(`${index + 1}. URL geçersiz.`, `URL on line ${index + 1} is invalid.`, `URL in Zeile ${index + 1} ist ungültig.`, `第 ${index + 1} 行 URL 无效。`))); } return { status, url }; }); if (!hops.length) throw new Error(tx(locale, l("En az bir adım girin.", "Enter at least one hop.", "Mindestens einen Schritt eingeben.", "请至少输入一个步骤。"))); const seen = new Set<string>(), issues: string[] = []; hops.forEach((hop, index) => { const normalized = hop.url.href.replace(/\/$/u, ""); if (seen.has(normalized)) issues.push(tx(locale, l(`${index + 1}. adım URL döngüsü oluşturuyor.`, `Hop ${index + 1} repeats a URL and forms a loop.`, `Schritt ${index + 1} wiederholt eine URL und bildet eine Schleife.`, `第 ${index + 1} 步重复 URL 并形成循环。`))); seen.add(normalized); if (index > 0 && hops[index - 1].url.protocol === "https:" && hop.url.protocol === "http:") issues.push(tx(locale, l(`${index + 1}. adım HTTPS'den HTTP'ye düşüyor.`, `Hop ${index + 1} downgrades HTTPS to HTTP.`, `Schritt ${index + 1} stuft HTTPS auf HTTP herab.`, `第 ${index + 1} 步从 HTTPS 降级到 HTTP。`))); }); if (hops.length > 3) issues.push(tx(locale, l("Zincir üçten fazla adım içeriyor.", "The chain contains more than three hops.", "Die Kette enthält mehr als drei Schritte.", "重定向链超过三步。"))); const redirectTypes = new Set(hops.filter((hop) => hop.status !== 200).map((hop) => [301, 308].includes(hop.status) ? "permanent" : "temporary")); if (redirectTypes.size > 1) issues.push(tx(locale, l("Geçici ve kalıcı yönlendirmeler aynı zincirde karışıyor.", "Temporary and permanent redirects are mixed in one chain.", "Temporäre und permanente Redirects sind gemischt.", "同一链中混用了临时和永久重定向。")));
    return { output: `${table([["#", tx(locale, l("Durum", "Status", "Status", "状态")), "URL", "Host"], ...hops.map((hop, index) => [index + 1, hop.status, hop.url.href, hop.url.host])])}\n\n${issues.map((issue) => `! ${issue}`).join("\n") || tx(locale, l("✓ Girilen zincirde açık döngü veya protokol düşüşü bulunmadı.", "✓ No obvious loop or protocol downgrade was found in the entered chain.", "✓ Keine offensichtliche Schleife oder Protokollabstufung gefunden.", "✓ 输入链中未发现明显循环或协议降级。"))}\n\n${boundary(locale)}`, metrics: [[tx(locale, l("Adım", "Hops", "Schritte", "步骤")), hops.length], ["Host", new Set(hops.map((hop) => hop.url.host)).size], [tx(locale, l("İnceleme", "Review flags", "Prüfhinweise", "检查项")), issues.length]], warning: issues.length ? issues[0] : undefined };
  }
  if (slug === "api-hata-zarfi-dogrulayici") {
    let parsed: unknown; try { parsed = JSON.parse(String(values.json ?? "")); } catch { throw new Error(tx(locale, l("Geçerli hata JSON'u girin.", "Enter valid error JSON.", "Gültiges Fehler-JSON eingeben.", "请输入有效错误 JSON。"))); } const root = parsed && typeof parsed === "object" && !Array.isArray(parsed) ? parsed as Record<string, unknown> : null; const error = root?.error && typeof root.error === "object" && !Array.isArray(root.error) ? root.error as Record<string, unknown> : root; if (!error) throw new Error(tx(locale, l("Hata zarfı bir JSON nesnesi olmalıdır.", "The error envelope must be a JSON object.", "Der Fehlerumschlag muss ein JSON-Objekt sein.", "错误信封必须是 JSON 对象。"))); const code = typeof error.code === "string" && /^[A-Z][A-Z0-9_]{2,63}$/u.test(error.code), message = typeof error.message === "string" && error.message.trim().length >= 8, trace = typeof error.traceId === "string" || typeof error.requestId === "string", fields = error.fields === undefined || (Array.isArray(error.fields) && error.fields.every((item) => item && typeof item === "object")); const raw = JSON.stringify(parsed); const leaks = [/\bat\s+[\w$.]+\s*\([^)]*:\d+:\d+\)/u, /\bSELECT\s+.+\bFROM\b/iu, /(?:api[_-]?key|password|secret|token)\s*[=:]\s*[^\s"}]+/iu].filter((pattern) => pattern.test(raw)).length; const checks = [[code, "code", "VALIDATION_FAILED"], [message, "message", tx(locale, l("Kullanıcıya düzeltme yolunu söyleyin", "Tell the user how to recover", "Nutzern die Korrektur erklären", "说明用户如何修正"))], [trace || !values.traceRequired, "traceId/requestId", tx(locale, l("İzlenebilir kimlik ekleyin", "Add a traceable identifier", "Nachvollziehbare ID ergänzen", "添加可追踪标识"))], [fields, "fields", tx(locale, l("Alan hatalarını dizi olarak verin", "Represent field issues as an array", "Feldfehler als Liste ausgeben", "将字段问题表示为数组"))], [leaks === 0, tx(locale, l("Sızıntı sinyali", "Leakage signals", "Lecksignale", "泄漏信号")), tx(locale, l("Yığın, SQL ve sır ayrıntılarını kaldırın", "Remove stack, SQL, and secret details", "Stack-, SQL- und Geheimnisdetails entfernen", "移除堆栈、SQL 与秘密详情"))]]; const failures = checks.filter(([ok]) => !ok).length;
    return { output: `${table([[tx(locale, l("Durum", "Status", "Status", "状态")), tx(locale, l("Kontrol", "Check", "Prüfung", "检查")), tx(locale, l("Düzeltme", "Fix", "Korrektur", "修正"))], ...checks.map(([ok, label, fix]) => [ok ? "✓" : "!", String(label), ok ? "OK" : String(fix)])])}\n\n${boundary(locale)}`, metrics: [[tx(locale, l("Kontrol", "Checks", "Prüfungen", "检查")), checks.length], [tx(locale, l("Düzeltme", "Fixes", "Korrekturen", "修正")), failures], [tx(locale, l("Sızıntı", "Leak flags", "Leckhinweise", "泄漏项")), leaks]], warning: leaks ? tx(locale, l("Yanıt olası iç sistem ayrıntısı içeriyor.", "The response may expose internal-system details.", "Die Antwort kann interne Systemdetails offenlegen.", "响应可能暴露内部系统详情。")) : undefined };
  }
  if (slug === "ozellik-bayragi-yayin-planlayici") {
    const audience = Math.floor(numberValue(values, "audience", locale, 1, 1000000000)), hours = numberValue(values, "hours", locale, .5, 720), error = numberValue(values, "error", locale, 0, 100); const stages = String(values.stages ?? "").split(/[\s,;]+/u).filter(Boolean).map(Number); if (!stages.length || stages.some((value) => !Number.isFinite(value) || value <= 0 || value > 100) || new Set(stages).size !== stages.length || stages.some((value, index) => index > 0 && value <= stages[index - 1])) throw new Error(tx(locale, l("Aşamaları artan, benzersiz ve 0–100 arası yüzdeler olarak girin.", "Enter increasing unique percentage stages between 0 and 100.", "Eindeutige steigende Prozentstufen zwischen 0 und 100 eingeben.", "请输入 0–100 之间递增且不重复的百分比阶段。"))); const rows = stages.map((stage, index) => [index + 1, `${stage}%`, Math.max(1, Math.ceil(audience * stage / 100)), `${hours} h`, `${error}%`, index === 0 ? tx(locale, l("İç ekip + geri alma provası", "Internal cohort + rollback rehearsal", "Intern + Rollback-Probe", "内部用户 + 回滚演练")) : tx(locale, l("Önceki aşama kabul edilirse", "Only after prior-stage acceptance", "Nur nach Abnahme der Vorstufe", "仅在上一阶段验收后"))]);
    return { output: `${table([["#", tx(locale, l("Kapsam", "Exposure", "Umfang", "覆盖率")), tx(locale, l("Kullanıcı", "Users", "Nutzer", "用户")), tx(locale, l("Gözlem", "Observe", "Beobachten", "观察")), tx(locale, l("Geri alma", "Rollback", "Rollback", "回滚")), tx(locale, l("Kapı", "Gate", "Gate", "门槛"))], ...rows])}\n\n${boundary(locale)}`, metrics: [[tx(locale, l("Aşama", "Stages", "Stufen", "阶段")), stages.length], [tx(locale, l("Toplam süre", "Minimum duration", "Mindestdauer", "最短时长")), `${stages.length * hours} h`], [tx(locale, l("Son kapsam", "Final exposure", "Endumfang", "最终覆盖")), `${stages.at(-1)}%`]], warning: stages.at(-1) !== 100 ? tx(locale, l("Plan %100 kapsamdan önce bitiyor; kalıcı hedefi açıkça kaydedin.", "The plan ends before 100%; record the intended steady state.", "Der Plan endet vor 100 %; Zielzustand dokumentieren.", "计划在 100% 前结束；请记录最终稳定目标。")) : undefined };
  }
  if (slug === "yanit-suresi-yuzdelik-hesaplayici") {
    const samples = String(values.samples ?? "").split(/[\s,;]+/u).filter(Boolean).map(Number); if (samples.length < 2 || samples.length > 100000 || samples.some((value) => !Number.isFinite(value) || value < 0)) throw new Error(tx(locale, l("2–100.000 arasında sonlu, negatif olmayan milisaniye değeri girin.", "Enter 2–100,000 finite non-negative millisecond values.", "2–100.000 endliche, nicht negative Millisekundenwerte eingeben.", "请输入 2–100,000 个有限且非负的毫秒值。"))); const sorted = [...samples].sort((a, b) => a - b), mean = samples.reduce((sum, value) => sum + value, 0) / samples.length, q1 = percentile(sorted, .25), q3 = percentile(sorted, .75), fence = q3 + 1.5 * (q3 - q1), outliers = sorted.filter((value) => value > fence); const percentiles = [["p50", percentile(sorted, .5)], ["p75", percentile(sorted, .75)], ["p90", percentile(sorted, .9)], ["p95", percentile(sorted, .95)], ["p99", percentile(sorted, .99)]];
    return { output: `${table([[tx(locale, l("Ölçü", "Measure", "Messwert", "指标")), "ms"], ...percentiles, [tx(locale, l("Ortalama", "Mean", "Mittelwert", "平均值")), mean.toFixed(2)], [tx(locale, l("Minimum", "Minimum", "Minimum", "最小值")), sorted[0]], [tx(locale, l("Maksimum", "Maximum", "Maximum", "最大值")), sorted.at(-1) ?? 0]])}\n\n${tx(locale, l("IQR aykırı adayları", "IQR outlier candidates", "IQR-Ausreißerkandidaten", "IQR 异常候选"))}: ${outliers.join(", ") || "—"}\n\n${boundary(locale)}`, metrics: [[tx(locale, l("Örnek", "Samples", "Stichproben", "样本")), samples.length], ["p95", `${percentile(sorted, .95)} ms`], [tx(locale, l("Aykırı aday", "Outlier candidates", "Ausreißer", "异常候选")), outliers.length]], warning: samples.length < 30 ? tx(locale, l("Küçük örneklemde yüksek yüzdelikler kararsız olabilir.", "High percentiles can be unstable in a small sample.", "Hohe Perzentile können bei kleiner Stichprobe instabil sein.", "小样本中的高百分位可能不稳定。")) : undefined };
  }
  if (slug === "kuyruk-kapasite-planlayici") {
    const arrival = numberValue(values, "arrival", locale, 0, 100000000), duration = numberValue(values, "duration", locale, 1, 86400000), workers = Math.floor(numberValue(values, "workers", locale, 1, 100000)), backlog = Math.floor(numberValue(values, "backlog", locale, 0, 1000000000)), burst = numberValue(values, "burst", locale, 1, 10080); const capacity = workers * 60000 / duration, utilisation = capacity ? arrival / capacity : Infinity, net = capacity - arrival, projected = Math.max(0, backlog + Math.max(0, arrival - capacity) * burst), drain = net > 0 ? backlog / net : Infinity;
    const rows = [[tx(locale, l("Geliş", "Arrival", "Ankunft", "到达")), arrival.toFixed(2), tx(locale, l("iş/dk", "jobs/min", "Jobs/Min.", "任务/分钟"))], [tx(locale, l("Kapasite", "Capacity", "Kapazität", "容量")), capacity.toFixed(2), tx(locale, l("iş/dk", "jobs/min", "Jobs/Min.", "任务/分钟"))], [tx(locale, l("Kullanım", "Utilisation", "Auslastung", "利用率")), `${(utilisation * 100).toFixed(1)}%`, ""], [tx(locale, l("Patlama sonu kuyruk", "Backlog after burst", "Backlog nach Burst", "突发后积压")), Math.ceil(projected), tx(locale, l("iş", "jobs", "Jobs", "任务"))], [tx(locale, l("Başlangıç kuyruğunu eritme", "Drain starting backlog", "Start-Backlog abbauen", "清空初始积压")), Number.isFinite(drain) ? `${drain.toFixed(1)} min` : "∞", ""]];
    return { output: `${table([[tx(locale, l("Ölçü", "Measure", "Messwert", "指标")), tx(locale, l("Değer", "Value", "Wert", "数值")), tx(locale, l("Birim", "Unit", "Einheit", "单位"))], ...rows])}\n\n${boundary(locale)}`, metrics: [[tx(locale, l("Kullanım", "Utilisation", "Auslastung", "利用率")), `${(utilisation * 100).toFixed(1)}%`], [tx(locale, l("Kapasite", "Capacity", "Kapazität", "容量")), capacity.toFixed(1)], [tx(locale, l("Kuyruk", "Projected backlog", "Prognose-Backlog", "预计积压")), Math.ceil(projected)]], warning: utilisation >= .8 ? tx(locale, utilisation >= 1 ? l("Geliş hızı kapasiteyi aşıyor; kuyruk büyür.", "Arrival rate exceeds capacity; the queue grows.", "Die Ankunftsrate übersteigt die Kapazität; die Warteschlange wächst.", "到达速率超过容量；队列将增长。") : l("Kullanım %80 üzerinde; uzun kuyruk ve gecikme riskini ölçün.", "Utilisation exceeds 80%; measure tail and queue-delay risk.", "Auslastung über 80 %; Tail- und Wartezeitrisiko messen.", "利用率超过 80%；请测量长尾与排队延迟风险。")) : undefined };
  }
  if (slug === "dokunma-hedefi-boyut-denetleyici") {
    const size = numberValue(values, "size", locale, 20, 80), gap = numberValue(values, "gap", locale, 0, 32); const targets = parsePipe(values.targets, 4, locale).map(([selector, widthRaw, heightRaw, gapRaw], index) => { const width = Number(widthRaw), height = Number(heightRaw), nearest = Number(gapRaw); if (![width, height, nearest].every((value) => Number.isFinite(value) && value >= 0)) throw new Error(tx(locale, l(`${index + 1}. hedef ölçümü geçersiz.`, `Target measurement ${index + 1} is invalid.`, `Zielmessung ${index + 1} ist ungültig.`, `第 ${index + 1} 个目标测量无效。`))); const issues = [width < size || height < size ? tx(locale, l("küçük hedef", "small target", "kleines Ziel", "目标过小")) : "", nearest < gap ? tx(locale, l("dar aralık", "tight spacing", "enger Abstand", "间距过窄")) : ""].filter(Boolean); return [selector, `${width}×${height}`, nearest, issues.join(", ") || "✓"]; }); const flagged = targets.filter((row) => row[3] !== "✓").length;
    return { output: `${table([[tx(locale, l("Seçici", "Selector", "Selektor", "选择器")), tx(locale, l("Boyut", "Size", "Größe", "尺寸")), tx(locale, l("Aralık", "Gap", "Abstand", "间距")), tx(locale, l("Durum", "Status", "Status", "状态"))], ...targets])}\n\n${boundary(locale)}`, metrics: [[tx(locale, l("Hedef", "Targets", "Ziele", "目标")), targets.length], [tx(locale, l("İnceleme", "Review", "Prüfen", "需检查")), flagged], [tx(locale, l("Geçen", "Passing", "Bestanden", "通过")), targets.length - flagged]], warning: flagged ? tx(locale, l("Bazı hedefler boyut veya aralık eşiğinin altında.", "Some targets fall below the size or spacing threshold.", "Einige Ziele unterschreiten Größe oder Abstand.", "部分目标低于尺寸或间距阈值。")) : undefined };
  }
  if (slug === "icerik-guncellik-portfoyu-planlayici") {
    const capacity = Math.floor(numberValue(values, "capacity", locale, 1, 1000)), now = Date.now(); const records = parsePipe(values.records, 4, locale).map(([title, date, riskRaw, importanceRaw], index) => { const stamp = Date.parse(`${date}T00:00:00Z`), risk = Number(riskRaw), importance = Number(importanceRaw); if (!Number.isFinite(stamp) || !Number.isInteger(risk) || risk < 1 || risk > 5 || !Number.isInteger(importance) || importance < 1 || importance > 5) throw new Error(tx(locale, l(`${index + 1}. kaydın tarih veya puanı geçersiz.`, `Record ${index + 1} has an invalid date or score.`, `Datensatz ${index + 1} enthält ungültiges Datum oder Wertung.`, `第 ${index + 1} 条记录的日期或评分无效。`))); const age = Math.max(0, Math.floor((now - stamp) / 86400000)), score = Math.round((Math.min(age, 365) / 365 * 40 + risk / 5 * 35 + importance / 5 * 25) * 10) / 10; return { title, date, risk, importance, age, score }; }).sort((a, b) => b.score - a.score); const rows = records.map((record, index) => [index + 1, record.title, record.date, record.age, record.risk, record.importance, record.score, index < capacity ? tx(locale, l("Bu hafta", "This week", "Diese Woche", "本周")) : tx(locale, l("Kuyruk", "Queue", "Warteliste", "队列"))]);
    return { output: `${table([["#", tx(locale, l("İçerik", "Content", "Inhalt", "内容")), tx(locale, l("Doğrulandı", "Verified", "Geprüft", "已验证")), tx(locale, l("Gün", "Days", "Tage", "天")), tx(locale, l("Risk", "Risk", "Risiko", "风险")), tx(locale, l("Önem", "Importance", "Bedeutung", "重要性")), tx(locale, l("Puan", "Score", "Wert", "得分")), tx(locale, l("Plan", "Plan", "Plan", "计划"))], ...rows])}\n\n${boundary(locale)}`, metrics: [[tx(locale, l("Kayıt", "Records", "Datensätze", "记录")), records.length], [tx(locale, l("Bu hafta", "This week", "Diese Woche", "本周")), Math.min(capacity, records.length)], [tx(locale, l("Kuyruk", "Queued", "Wartend", "队列")), Math.max(0, records.length - capacity)]] };
  }
  if (slug === "adr-karar-kaydi-olusturucu") {
    const title = String(values.title ?? "").trim(), context = String(values.context ?? "").trim(), options = lines(values.options), decision = String(values.decision ?? "").trim(), consequences = lines(values.consequences), evidence = lines(values.evidence), revisit = String(values.revisit ?? "").trim(); if (!title || context.length < 20 || options.length < 2 || decision.length < 20 || !consequences.length || !revisit) throw new Error(tx(locale, l("Başlık, en az iki seçenek, açıklayıcı bağlam/karar, sonuç ve yeniden değerlendirme tetikleyicisini doldurun.", "Complete the title, at least two options, explanatory context/decision, consequences, and reconsideration trigger.", "Titel, mindestens zwei Optionen, erklärenden Kontext/Entscheidung, Folgen und Neubewertungsauslöser ausfüllen.", "请填写标题、至少两个选项、清晰的背景与决策、后果及重新评估触发条件。"))); const date = new Date().toISOString().slice(0, 10); const output = `# ADR: ${title}\n\n- ${tx(locale, l("Tarih", "Date", "Datum", "日期"))}: ${date}\n- ${tx(locale, l("Durum", "Status", "Status", "状态"))}: ${tx(locale, l("Önerildi", "Proposed", "Vorgeschlagen", "提议"))}\n\n## ${tx(locale, l("Bağlam", "Context", "Kontext", "背景"))}\n\n${context}\n\n## ${tx(locale, l("Değerlendirilen seçenekler", "Options considered", "Geprüfte Optionen", "已评估选项"))}\n\n${options.map((option) => `- ${option}`).join("\n")}\n\n## ${tx(locale, l("Karar", "Decision", "Entscheidung", "决策"))}\n\n${decision}\n\n## ${tx(locale, l("Sonuçlar", "Consequences", "Folgen", "后果"))}\n\n${consequences.map((item) => `- ${item}`).join("\n")}\n\n## ${tx(locale, l("Kanıt", "Evidence", "Nachweise", "证据"))}\n\n${evidence.map((item) => `- ${item}`).join("\n") || "- —"}\n\n## ${tx(locale, l("Yeniden değerlendirme", "Reconsideration", "Neubewertung", "重新评估"))}\n\n${revisit}`;
    return { output, metrics: [[tx(locale, l("Seçenek", "Options", "Optionen", "选项")), options.length], [tx(locale, l("Sonuç", "Consequences", "Folgen", "后果")), consequences.length], [tx(locale, l("Kanıt", "Evidence items", "Nachweise", "证据项")), evidence.length]] };
  }
  throw new Error(tx(locale, l("Araç çalışma motoruna bağlanamadı.", "The tool could not connect to its processing engine.", "Das Werkzeug konnte nicht mit seiner Engine verbunden werden.", "工具无法连接处理引擎。")));
}
