import type { Locale } from "./site";

export type ArticleSection = {
  heading: string;
  paragraphs: string[];
  bullets?: string[];
};

export type Post = {
  slug: string;
  date: string;
  readTime: Record<Locale, string>;
  title: Record<Locale, string>;
  excerpt: Record<Locale, string>;
  description: Record<Locale, string>;
  category: Record<Locale, string>;
  visualSuggestion: Record<Locale, string>;
  sections: Record<Locale, ArticleSection[]>;
};

export const posts: Post[] = [
  {
    slug: "client-side-ai-araclari-nedir",
    date: "2026-07-14",
    readTime: { tr: "8 dk", en: "7 min" },
    title: { tr: "Client-Side AI Araçları Nedir ve Neden Önemlidir?", en: "What Are Client-Side AI Tools and Why Do They Matter?" },
    excerpt: { tr: "Tarayıcı içinde çalışan araçların gizlilik, hız ve denetlenebilirlik avantajlarını; gerçek sınırlarıyla birlikte öğrenin.", en: "Understand the privacy, speed, and auditability benefits of in-browser tools, together with their real limitations." },
    description: { tr: "Client-side AI ve üretkenlik araçlarının nasıl çalıştığını, hangi verilerin cihazda kaldığını ve hangi senaryolarda tercih edilmesi gerektiğini açıklayan kapsamlı rehber.", en: "A practical guide to how client-side AI and productivity tools work, what stays on-device, and when they are the right choice." },
    category: { tr: "Gizlilik temelleri", en: "Privacy fundamentals" },
    visualSuggestion: { tr: "Tarayıcı sekmesi, cihaz ve sunucu arasındaki veri sınırını gösteren sade bir akış şeması.", en: "A simple flow diagram showing the data boundary between browser, device, and server." },
    sections: {
      tr: [
        { heading: "Client-side ne anlama gelir?", paragraphs: ["Client-side, işlemin bir uzak sunucuda değil kullanıcının tarayıcısında gerçekleşmesi demektir. Metin ayrıştırma, biçim dönüştürme, düzenli ifade testi veya Web Crypto ile özet üretme gibi görevler JavaScript ve tarayıcı API'leri kullanılarak cihazda tamamlanabilir. Böylece girilen metnin bir hizmet sağlayıcısına gönderilmesi teknik olarak gerekli olmaz.", "Bu yaklaşım her zaman 'yapay zekâ modeli cihazda çalışıyor' anlamına gelmez. Bazı araçlar açıklanabilir kurallar ve istatistiksel ölçüler kullanır; bazı gelişmiş uygulamalar ise küçük modelleri WebAssembly veya WebGPU ile çalıştırabilir. Bir ürünün hangi yöntemi kullandığını açıkça söylemesi güven için önemlidir."], bullets: ["İşlem tarayıcı belleğinde gerçekleşir.", "Ağ isteği gerekmeyen görevler çevrimdışı da çalışabilir.", "Kullanıcı girdisinin yaşam döngüsü daha kolay denetlenir."] },
        { heading: "Gizlilik avantajı nereden gelir?", paragraphs: ["Veri aktarımı azaltıldığında saldırı yüzeyi de küçülür. Sunucu günlüğü, üçüncü taraf API, yanlış yapılandırılmış veri tabanı veya destek ekibinin erişimi gibi ek kopyalar oluşmaz. Bu, özellikle kişisel veri içerebilen destek kayıtları, sözleşme taslakları ve kurum içi notlar için anlamlıdır.", "Yine de tarayıcı içi çalışma tek başına KVKK veya GDPR uyumu sağlamaz. Kullanıcı cihazındaki kötü amaçlı eklentiler, paylaşılan bilgisayarlar, panoya kopyalama ve indirilen dosyalar ayrı risklerdir. Uyum; amaç, hukuki dayanak, saklama, erişim ve güvenlik kontrollerinin birlikte değerlendirilmesini gerektirir."], bullets: ["Hassas girdileri paylaşmadan önce maskeleyin.", "İş bittikten sonra sekmeyi ve indirilen çıktıları kontrol edin.", "Aracın ağ isteklerini ve gizlilik politikasını doğrulayın."] },
        { heading: "Hangi görevler tarayıcı için uygundur?", paragraphs: ["Deterministik ve sınırlı görevler client-side mimariye çok uygundur: JSON doğrulama, CSV dönüşümü, kelime sayımı, metin temizleme, karma özeti, parola üretimi ve desen tabanlı veri maskeleme. Sonuç aynı girdide tekrarlanabilir ve kullanıcı tarafından incelenebilir.", "Büyük dil modelleriyle uzun içerik üretimi, güncel web bilgisi veya kurumsal veri tabanına erişim gereken görevler ise genellikle uzak altyapı ister. Burada doğru seçim, 'her şeyi cihazda yapma' iddiası değil, mümkün olan işi cihazda tutup dış işlem gerektiğinde bunu açıkça belirtmektir." ] },
        { heading: "Bir aracı değerlendirirken kontrol listesi", paragraphs: ["İyi bir gizlilik odaklı araç, pazarlama cümlesinden daha fazlasını sunar. Girdinin nereye gittiğini, localStorage kullanıp kullanmadığını, üçüncü taraf kaynaklarını ve çıktı sınırlarını anlatır. Ayrıca hatalı sonuç ihtimalini saklamaz.", "ByteQuant araçlarında temel metin ve veri işlemleri tarayıcı içinde yapılır. Hukuki veya güvenlik açısından kritik kararlarda sonucu uzman incelemesiyle desteklemek gerekir."], bullets: ["Ağ olmadan temel işlev çalışıyor mu?", "Kaynak ve yöntem açıklanmış mı?", "Silme ve saklama davranışı net mi?", "Hata ve kapsam sınırları görünür mü?"] },
      ],
      en: [
        { heading: "What client-side actually means", paragraphs: ["Client-side means a task is completed in the user's browser rather than on a remote server. Text parsing, format conversion, regular-expression testing, and Web Crypto operations can all run with JavaScript and browser APIs, so the input does not need to leave the device.", "This does not automatically mean a full AI model is running locally. Many useful tools rely on transparent rules and statistical measures; some advanced apps run compact models through WebAssembly or WebGPU. Trust starts with stating which method is used."], bullets: ["Processing happens in browser memory.", "Network-free tasks may work offline.", "The input lifecycle is easier to audit."] },
        { heading: "Where the privacy benefit comes from", paragraphs: ["Reducing data transfer removes extra copies and access paths: server logs, third-party APIs, misconfigured databases, and support access. This is valuable for drafts, support records, and internal notes that may contain personal data.", "On-device processing is not a legal-compliance shortcut. Browser extensions, shared computers, clipboard history, and downloaded files remain relevant risks. GDPR or KVKK compliance still depends on purpose, legal basis, retention, access, and security controls." ] },
        { heading: "Good fits and poor fits", paragraphs: ["Deterministic tasks such as JSON validation, CSV conversion, word counting, text cleanup, hashing, password generation, and pattern-based masking are strong client-side candidates. Their results are repeatable and inspectable.", "Long-form generation with large models, current web research, or company-database access normally needs remote infrastructure. The honest design goal is to keep suitable work local and disclose whenever external processing is required." ] },
        { heading: "A practical evaluation checklist", paragraphs: ["A privacy-first product should explain where input goes, whether browser storage is used, which third parties are loaded, and where its output can fail. Marketing language alone is not evidence.", "ByteQuant performs its core text and data transformations in the browser. For legal or security-critical decisions, combine tool output with qualified human review."], bullets: ["Does the core feature work without a network request?", "Are methods and limitations disclosed?", "Is storage and deletion behavior clear?", "Are errors visible and recoverable?"] },
      ],
    },
  },
  {
    slug: "prompt-muhendisliginde-gizlilik",
    date: "2026-07-14",
    readTime: { tr: "9 dk", en: "8 min" },
    title: { tr: "Prompt Mühendisliğinde Gizlilik Nasıl Sağlanır?", en: "How to Protect Privacy in Prompt Engineering" },
    excerpt: { tr: "Bir promptu modele göndermeden önce veri sınıflandırma, maskeleme ve en az veri ilkelerini uygulayın.", en: "Apply data classification, masking, and minimization before a prompt reaches any model." },
    description: { tr: "Prompt hazırlarken kişisel ve kurumsal verileri korumak için uygulanabilir veri minimizasyonu, maskeleme ve kontrol adımları.", en: "Practical minimization, masking, and review steps for protecting personal and company data in prompts." },
    category: { tr: "Prompt güvenliği", en: "Prompt security" },
    visualSuggestion: { tr: "Ham prompttan sınıflandırma, maskeleme, onay ve modele gönderim adımlarına uzanan kontrol hattı.", en: "A review pipeline from raw prompt through classification, masking, approval, and model submission." },
    sections: {
      tr: [
        { heading: "Önce veriyi sınıflandırın", paragraphs: ["Prompt güvenliği, iyi bir cümle yazmaktan önce hangi verinin kullanıldığını anlamakla başlar. Kamuya açık bilgi, kurum içi bilgi, gizli ticari bilgi ve kişisel veri için aynı işlem kuralı uygulanmamalıdır. Bir müşteri kaydı isim, e-posta, sipariş numarası ve serbest metin notu içeriyorsa serbest metindeki görünmeyen kişisel veriler de hesaba katılmalıdır.", "Basit bir sınıflandırma etiketi bile davranışı değiştirir: 'açık', 'dahili', 'gizli' ve 'kişisel veri'. Ekip, hangi sınıfın hangi model veya hesap türünde kullanılabileceğini önceden belirlemelidir."], bullets: ["Girdi kaynağını kaydedin.", "Veri sahibini ve kullanım amacını belirleyin.", "Hangi alanların gerçekten gerekli olduğunu sorun."] },
        { heading: "En az veri ile aynı sonuca ulaşın", paragraphs: ["Veri minimizasyonu, görevi tamamlamak için gerekli olmayan alanları prompttan çıkarmaktır. Bir destek yanıtının tonunu iyileştirmek için müşterinin tam adı, telefon numarası veya sipariş kimliği çoğu zaman gerekmez. Gerçek değerler yerine tutarlı yer tutucular kullanmak bağlamı korur: [MÜŞTERİ], [ÜRÜN], [TARİH] gibi.", "Maskeleme sonrasında görevin hâlâ çözülüp çözülmediğini test edin. Cevap değişmiyorsa kaldırdığınız veri zaten gereksizdir. Bu yöntem hem gizlilik riskini hem de prompt karmaşıklığını azaltır." ] },
        { heading: "Prompt enjeksiyonu ve gizli talimatlar", paragraphs: ["Bir belgeyi özetletirken belgenin içinde modele yönelik talimatlar bulunabilir. 'Önceki kuralları yok say' gibi metinler, içerik ile komutun ayrılmadığı sistemlerde risk yaratır. Kullanıcı girdisini açık sınırlar veya XML benzeri etiketlerle veri olarak işaretlemek, talimat hiyerarşisini güçlendirir.", "Model çıktısının da güvenilir veri olmadığını unutmayın. Bağlantı, kod veya SQL üretiyorsa insan kontrolü ve gerekiyorsa teknik doğrulama yapılmalıdır."], bullets: ["Sistem talimatı ile belge içeriğini ayırın.", "Girdideki talimatları yürütmemesini açıkça belirtin.", "Çıktıya otomatik işlem yetkisi vermeyin."] },
        { heading: "Uygulanabilir gönderim öncesi kontrol", paragraphs: ["Model sağlayıcısının veri kullanım, saklama ve eğitim tercihlerini güncel sözleşme ve ayarlardan kontrol edin. Kişisel hesap ile kurumsal sözleşme aynı korumaları sunmayabilir. KVKK ve GDPR açısından veri işleyen, aktarım ülkesi ve saklama süresi ayrıca değerlendirilmelidir.", "ByteQuant'ın veri maskeleyici ve prompt kalite araçları bu ön hazırlığı cihazda yapmaya yardımcı olur. Otomatik desen tespiti kusursuz değildir; son kontrolün sahibi kullanıcıdır."], bullets: ["Amaç için gereksiz alanları silin.", "Kalan kişisel verileri maskeleyin.", "Sağlayıcı ve hesap politikasını doğrulayın.", "Göndermeden önce ikinci göz kontrolü uygulayın."] },
      ],
      en: [
        { heading: "Classify before you compose", paragraphs: ["Prompt privacy starts by understanding the data, not by polishing the sentence. Public, internal, confidential, and personal data need different handling. Free-text fields deserve special attention because they can hide names, health details, or identifiers.", "A simple label set—public, internal, confidential, personal—helps teams decide which model, account, and approval path may be used." ] },
        { heading: "Reach the same result with less data", paragraphs: ["Data minimization removes fields that are unnecessary for the task. Improving the tone of a support reply rarely requires a full name, phone number, or order identifier. Consistent placeholders such as [CUSTOMER], [PRODUCT], and [DATE] preserve structure without exposing real values.", "Test the task after masking. If the answer remains useful, the removed data was not needed and the prompt is both safer and simpler." ] },
        { heading: "Separate instructions from content", paragraphs: ["Documents can contain text that looks like instructions to a model. Delimit user content clearly, state that embedded instructions are data, and preserve a strict instruction hierarchy. Model output is also untrusted until reviewed, especially when it contains links, code, or queries."], bullets: ["Separate system rules and source content.", "Tell the model not to execute embedded instructions.", "Do not give unreviewed output automatic authority."] },
        { heading: "A pre-submission checklist", paragraphs: ["Review the provider's current retention, training, and regional-transfer terms. Consumer and enterprise accounts may have different controls. Under GDPR or KVKK, processor roles, transfer locations, and retention still need a documented assessment.", "ByteQuant can help mask common patterns and review prompt structure locally. Pattern detection is never perfect, so the final decision remains with the user."], bullets: ["Remove unnecessary fields.", "Mask remaining personal data.", "Verify provider and account settings.", "Use a second-person review for sensitive prompts."] },
      ],
    },
  },
  {
    slug: "meta-prompt-nedir",
    date: "2026-07-14",
    readTime: { tr: "7 dk", en: "6 min" },
    title: { tr: "Meta Prompt Nedir ve Nasıl Kullanılır?", en: "What Is a Meta Prompt and How Do You Use One?" },
    excerpt: { tr: "Tek seferlik talimatları tekrarlanabilir iş akışlarına dönüştüren meta prompt yapısını örneklerle kurun.", en: "Turn one-off instructions into repeatable workflows with a practical meta-prompt structure." },
    description: { tr: "Rol, hedef, bağlam, süreç, sınırlar ve çıktı sözleşmesi bileşenleriyle etkili meta prompt hazırlama rehberi.", en: "A guide to meta prompts built from role, goal, context, process, constraints, and output contracts." },
    category: { tr: "Prompt tasarımı", en: "Prompt design" },
    visualSuggestion: { tr: "Altı yapı taşının tek prompt şablonunda birleşmesini gösteren modüler kartlar.", en: "Modular cards showing six building blocks combining into one prompt template." },
    sections: {
      tr: [
        { heading: "Meta promptun görevi", paragraphs: ["Meta prompt, modelden yalnızca bir cevap istemek yerine nasıl çalışacağını tarif eden üst düzey bir şablondur. Rolü, hedefi, kullanılacak bağlamı, izlenecek süreci, sınırları ve çıktı biçimini birlikte tanımlar. Böylece aynı görev farklı girdilerle daha tutarlı yürütülebilir.", "Her görev meta prompt gerektirmez. Basit bir tarih biçimi dönüşümü için uzun şablon gereksizdir. Ancak ekip tarafından tekrarlanan analiz, değerlendirme veya içerik üretimi süreçlerinde hata payını ve kişiden kişiye değişimi azaltır." ] },
        { heading: "Altı temel bileşen", paragraphs: ["Güçlü bir şablon önce başarıyı tanımlar. 'İyi bir rapor yaz' yerine raporun kimin için olduğu, hangi kararı desteklediği ve hangi kanıt standardını izleyeceği belirtilir. Süreç bölümü modelin ara kontrol adımlarını; çıktı sözleşmesi ise başlıkları, tablo alanlarını veya JSON şemasını belirler."], bullets: ["Rol: Hangi uzman bakış açısı?", "Hedef: Ölçülebilir sonuç nedir?", "Bağlam: Hangi bilgi kullanılabilir?", "Süreç: Hangi kontroller uygulanmalı?", "Sınırlar: Neler yapılmamalı?", "Çıktı: Sonuç hangi biçimde teslim edilmeli?"] },
        { heading: "Değişkenlerle yeniden kullanım", paragraphs: ["Sabit şablondaki değişen parçaları [HEDEF_KİTLE], [KAYNAK_METİN] veya [TON] gibi açık değişkenlerle ayırın. Her değişken için beklenen veri türünü ve boş kalırsa ne olacağını belirtin. Bu, şablonu bir form veya ekip dokümanıyla kullanmayı kolaylaştırır.", "Şablonu sürümlendirmek de önemlidir. Değişiklik tarihini, amacını ve örnek çıktıyı saklayın. Yalnızca çıktı kalitesini değil, hatalı veya uydurma bilgi oranını da test edin." ] },
        { heading: "Kısa örnek ve doğrulama", paragraphs: ["Bir müşteri geri bildirimi özetleyicisi için rol 'müşteri deneyimi analisti', hedef 'temaları ve etkilerini ayırmak', sınır 'kişisel veri üretmemek', çıktı ise 'tema, kanıt, etki ve öneri sütunlu tablo' olabilir. Bu yapı, 'yorumları özetle' talimatından daha denetlenebilirdir.", "ByteQuant Meta Prompt Oluşturucu ilk iskeleti hazırlayabilir. Üretim öncesinde gerçek örneklerle test edin; modelden bilinmeyen bilgiyi açıkça 'yetersiz veri' olarak işaretlemesini isteyin." ] },
      ],
      en: [
        { heading: "The job of a meta prompt", paragraphs: ["A meta prompt describes how a model should work, not only what answer it should produce. It combines a role, goal, available context, process, constraints, and output format so a recurring task can be run consistently with different inputs.", "Simple transformations do not need a long template. Repeated analysis, review, and content workflows often benefit because the standard reduces ambiguity between users and runs." ] },
        { heading: "Six building blocks", paragraphs: ["Start by defining success. Replace 'write a good report' with its audience, decision, and evidence standard. The process describes checks; the output contract defines headings, table columns, or a JSON schema."], bullets: ["Role: which professional perspective?", "Goal: what measurable outcome?", "Context: what information may be used?", "Process: which checks are required?", "Constraints: what must not happen?", "Output: how will the result be delivered?"] },
        { heading: "Reusable variables", paragraphs: ["Separate changing inputs with clear variables such as [AUDIENCE], [SOURCE_TEXT], and [TONE]. Define expected data and what happens when a field is empty. Version the template, record why it changed, and retain representative tests." ] },
        { heading: "A compact example", paragraphs: ["For customer-feedback analysis, use the role 'customer experience analyst,' the goal 'separate themes and impacts,' the constraint 'do not reproduce personal data,' and an output table with theme, evidence, impact, and recommendation. This is more auditable than 'summarize these comments.'", "ByteQuant's Meta Prompt Builder can prepare the first structure. Test it with real examples and require the model to mark missing evidence instead of inventing it." ] },
      ],
    },
  },
  {
    slug: "tarayici-ici-nlp-kvkk-avantajlari",
    date: "2026-07-14",
    readTime: { tr: "8 dk", en: "7 min" },
    title: { tr: "Tarayıcı İçi NLP Araçlarının KVKK Avantajları", en: "KVKK Benefits of In-Browser NLP Tools" },
    excerpt: { tr: "Metin analizi cihazda yapıldığında veri aktarımı, saklama ve erişim riskleri nasıl değişir?", en: "How on-device text analysis changes transfer, retention, and access risk." },
    description: { tr: "Tarayıcı içi NLP araçlarını KVKK ilkeleri açısından veri minimizasyonu, güvenlik ve aktarım boyutlarıyla değerlendiren rehber.", en: "An evaluation of in-browser NLP under KVKK principles, including minimization, security, and transfer." },
    category: { tr: "KVKK ve teknoloji", en: "KVKK & technology" },
    visualSuggestion: { tr: "Veri sorumlusundan tarayıcı işlemine uzanan ve dış aktarımı kesen mimari şema.", en: "An architecture diagram showing browser processing with no external transfer path." },
    sections: {
      tr: [
        { heading: "Mimari kararın hukuki etkisi", paragraphs: ["KVKK bakımından teknik mimari, işlenen veri miktarını ve veriye kimlerin erişebildiğini doğrudan etkiler. Metin bir sunucuya aktarılmadan tarayıcıda analiz edildiğinde hizmet sağlayıcı tarafında yeni bir veri kopyası oluşmayabilir. Bu, veri işleyen ilişkisi, yurt dışı aktarım ve saklama süresi gibi başlıkların kapsamını daraltabilir.", "Ancak 'sunucuya göndermiyoruz' ifadesi tek başına uyum kanıtı değildir. Site analitik, reklam, hata izleme veya uzaktan yüklenen betikler kullanıyorsa farklı veri akışları oluşabilir. Gerçek değerlendirme, ağ trafiği ve ürün davranışıyla doğrulanmalıdır." ] },
        { heading: "Temel ilkelerle ilişki", paragraphs: ["Belirli, açık ve meşru amaç; amaçla bağlantılı ve sınırlı işleme; doğruluk ve gerekli süre kadar saklama ilkeleri tarayıcı içi tasarımla desteklenebilir. Örneğin kelime sayımı için metni saklamak gerekmez. İşlem bittiğinde tarayıcı belleğindeki değer kaldırılabilir.", "Yerel saklama kullanılıyorsa bu da açıkça belirtilmelidir. localStorage sunucu değildir ama paylaşılan cihazda kalıcı iz bırakabilir. Hassas veri için varsayılan olarak saklamama daha güvenli bir tasarımdır."], bullets: ["Gereksiz ağ aktarımını kaldırın.", "Varsayılan saklamayı kapatın.", "Kullanıcıya temizleme seçeneği verin.", "Yüklenen üçüncü taraf betikleri en aza indirin."] },
        { heading: "NLP çıktısının sınırları", paragraphs: ["Okunabilirlik, sözcük sıklığı ve desen bulma gibi NLP ölçümleri bağlama duyarlı olabilir. Bir e-posta deseninin bulunması, metindeki tüm kişisel verilerin bulunduğu anlamına gelmez. Dolaylı tanımlayıcılar, meslek ve olay birleşimleri bir kişiyi belirlenebilir kılabilir.", "Bu nedenle otomatik maskeleme bir ön kontrol katmanıdır. Yüksek riskli paylaşımda alan uzmanı, veri koruma sorumlusu veya hukuk danışmanı sürece dahil edilmelidir." ] },
        { heading: "Satın alma ve geliştirme kontrolü", paragraphs: ["Bir araç seçerken yalnızca arayüze değil bağımlılıklara, içerik güvenlik politikasına, çerezlere ve hata kayıtlarına bakın. Geliştirici tarafında ağ istekleri için izin listesi, bağımlılık güncellemeleri ve güvenlik testleri tutulmalıdır.", "ByteQuant temel araç işlemlerini tarayıcıda yürütür ve hassas metni otomatik olarak saklamaz. Reklam hizmeti gelecekte etkinleştirilirse bunun araç girdisinden ayrı tutulması, açık rıza ve politika güncellemesiyle yönetilmesi gerekir." ] },
      ],
      en: [
        { heading: "Architecture changes the legal surface", paragraphs: ["Under KVKK, technical architecture affects how much data is processed and who can access it. If text is analyzed without leaving the browser, a service-side copy may never be created, reducing the scope of processor access, international transfer, and retention questions.", "The claim still requires verification. Analytics, advertising, error tracking, and remotely loaded scripts can create separate flows even when the main tool is local." ] },
        { heading: "Connection to data-protection principles", paragraphs: ["Purpose limitation, minimization, accuracy, and limited retention can be supported by browser-first design. A word counter does not need to retain the text after it returns a count. If localStorage is used, remember that it can persist on a shared device."], bullets: ["Remove unnecessary network transfers.", "Do not persist input by default.", "Offer a clear reset action.", "Minimize third-party scripts."] },
        { heading: "Limits of NLP output", paragraphs: ["Readability, frequency, and pattern detection are context-sensitive. Finding an email pattern does not prove every personal identifier has been found. Combinations of occupation, location, and events can still identify a person.", "Automatic masking is therefore a first review layer. High-risk disclosures need domain and legal review." ] },
        { heading: "Procurement and engineering checks", paragraphs: ["Inspect dependencies, content-security policy, cookies, and error logging—not only the interface. Engineering teams should maintain allowlisted network destinations, dependency updates, and security tests.", "ByteQuant runs its core transformations in the browser and does not persist sensitive input by default. If advertising is enabled later, it should remain separated from tool input and be covered by updated consent and policy controls." ] },
      ],
    },
  },
  {
    slug: "gelismis-prompt-kalite-kontrolu",
    date: "2026-07-14",
    readTime: { tr: "10 dk", en: "9 min" },
    title: { tr: "Gelişmiş Prompt Kalite Kontrolü Teknikleri", en: "Advanced Prompt Quality-Control Techniques" },
    excerpt: { tr: "Promptları yalnızca akıcı görünmesine göre değil; test, rubrik, karşı örnek ve sürüm disipliniyle değerlendirin.", en: "Evaluate prompts with tests, rubrics, counterexamples, and version discipline—not surface fluency." },
    description: { tr: "Prompt kalitesini sistematik olarak ölçmek için rubrik, test seti, karşı örnek, çıktı şeması ve sürüm yönetimi teknikleri.", en: "Rubrics, test sets, counterexamples, output schemas, and version control for systematic prompt evaluation." },
    category: { tr: "Kalite güvence", en: "Quality assurance" },
    visualSuggestion: { tr: "Prompt, test seti, değerlendirme rubriği ve sürüm kararını bağlayan kapalı döngü.", en: "A closed loop connecting prompt, test set, evaluation rubric, and version decision." },
    sections: {
      tr: [
        { heading: "Kaliteyi ölçülebilir tanımlayın", paragraphs: ["Bir prompt 'güzel cevap veriyor' diye kaliteli sayılmaz. Doğruluk, kapsam, biçim uyumu, kaynak kullanımı, güvenlik ve gereksiz uzunluk gibi boyutlar ayrı değerlendirilmelidir. Her boyut için 0–2 veya 0–4 arası kısa bir rubrik oluşturmak farklı değerlendiricilerin aynı dile yaklaşmasını sağlar.", "Rubrik görevle uyumlu olmalıdır. Yaratıcı metinde özgünlük öne çıkarken veri çıkarımında alan doğruluğu ve eksik değer davranışı daha önemlidir." ] },
        { heading: "Temsil edici test seti kurun", paragraphs: ["Yalnızca ideal örneklerle test edilen prompt üretimde kırılır. Kısa, uzun, eksik, çelişkili, farklı dilde ve hassas veri içeren girdileri kapsayan küçük ama temsil edici bir test seti hazırlayın. Her sürümde aynı seti çalıştırmak gerilemeyi görmenizi sağlar.", "Kenar durumları özellikle değerlidir: boş girdi, tablo içinde satır sonu, belirsiz tarih ve birbirini tutmayan kaynaklar. Beklenen davranış 'cevap üretmek' değil bazen güvenli biçimde durmaktır."], bullets: ["En az bir normal örnek", "En az iki kenar durum", "Bir karşıt veya yanıltıcı örnek", "Bir eksik veri örneği"] },
        { heading: "Çıktı sözleşmesi ve doğrulama", paragraphs: ["Makine tarafından işlenecek çıktıda serbest metin yerine açık şema kullanın. Zorunlu alanları, veri türlerini, izin verilen değerleri ve bilinmeyen bilginin nasıl gösterileceğini belirtin. Üretilen JSON yine de ayrıştırıcı ve iş kuralı kontrolünden geçmelidir.", "Örnek çıktı yararlıdır ama modelin örnekteki içeriği kopyalama riskini azaltmak için örneğin yalnızca biçimi gösterdiğini söyleyin." ] },
        { heading: "Sürüm, maliyet ve insan kontrolü", paragraphs: ["Promptu kod gibi sürümlendirin: değişiklik, gerekçe, test sonucu ve sorumlu kişi. Daha uzun prompt her zaman daha iyi değildir; bağlamı kalabalıklaştırabilir ve maliyeti artırabilir. Gereksiz tekrarları temizleyin.", "Yüksek etkili kararlarda insan onayı kalite sürecinin parçasıdır. ByteQuant Prompt Kalite Denetimi yapı eksiklerini hızlıca gösterir; gerçek alan doğruluğu için görev özel testler gereklidir." ] },
      ],
      en: [
        { heading: "Define quality measurably", paragraphs: ["A prompt is not high quality simply because its answer sounds fluent. Accuracy, coverage, format compliance, evidence use, safety, and unnecessary length should be scored separately. A compact 0–2 or 0–4 rubric gives reviewers a shared language.", "Weight dimensions for the task: originality may matter in creative work, while field accuracy and missing-value behavior dominate extraction." ] },
        { heading: "Build a representative test set", paragraphs: ["Prompts tested only on ideal examples fail in production. Include short, long, incomplete, conflicting, multilingual, and sensitive-data inputs. Run the same set for each version to detect regressions."], bullets: ["At least one normal case", "At least two edge cases", "One adversarial or misleading case", "One missing-data case"] },
        { heading: "Use an output contract", paragraphs: ["For machine-consumed output, define required fields, types, allowed values, and how unknown information is represented. Generated JSON must still pass parsing and business-rule validation. Examples should demonstrate format without encouraging the model to copy sample facts." ] },
        { heading: "Versioning and human review", paragraphs: ["Version prompts like code: record the change, reason, test result, and owner. Longer is not automatically better; remove repetition that crowds the context. Human approval remains part of quality assurance for high-impact decisions.", "ByteQuant's checker exposes structural gaps quickly, while domain accuracy still requires task-specific tests." ] },
      ],
    },
  },
  {
    slug: "sentetik-veri-ve-gizlilik-riskleri",
    date: "2026-07-14",
    readTime: { tr: "9 dk", en: "8 min" },
    title: { tr: "Sentetik Veri Üretimi ve Gizlilik Riskleri", en: "Synthetic Data Generation and Privacy Risks" },
    excerpt: { tr: "Sentetik etiketinin neden otomatik anonimlik anlamına gelmediğini ve güvenli test verisinin nasıl değerlendirileceğini öğrenin.", en: "Learn why 'synthetic' does not automatically mean anonymous and how to assess safer test data." },
    description: { tr: "Sentetik veri üretiminde ezberleme, yeniden tanımlama, dağılım sızıntısı ve kullanım amacı risklerini açıklayan pratik rehber.", en: "A practical guide to memorization, re-identification, distribution leakage, and purpose risks in synthetic data." },
    category: { tr: "Veri güvenliği", en: "Data security" },
    visualSuggestion: { tr: "Gerçek veri, üretim modeli, sentetik çıktı ve risk testlerinden oluşan dört aşamalı süreç.", en: "A four-stage process from real data to generator, synthetic output, and privacy tests." },
    sections: {
      tr: [
        { heading: "Sentetik veri neyi çözer?", paragraphs: ["Sentetik veri, gerçek kayıtların birebir kopyası olmayan ancak belirli istatistiksel veya yapısal özellikleri taklit eden veridir. Yazılım testi, eğitim ve model geliştirme için gerçek kişisel veriye erişimi azaltabilir. Özellikle şema, hata durumu ve iş kuralı testlerinde el ile tasarlanmış sentetik örnekler çok değerlidir.", "Fakat kaynak veri kişisel veri içeriyorsa üretim süreci de bu veriyi işler. Çıktının sentetik olması, eğitim ve erişim aşamalarındaki yükümlülükleri ortadan kaldırmaz." ] },
        { heading: "Ezberleme ve yeniden tanımlama", paragraphs: ["Bir üretici nadir kayıtları veya benzersiz kombinasyonları ezberleyebilir. Çok seyrek bir hastalık, küçük bir ilçe ve belirli yaş birleşimi isim içermese bile kişiyi belirlenebilir kılabilir. Sentetik çıktının gerçek kayda aşırı yakınlığı en temel uyarı işaretidir.", "Mesafe testleri, en yakın komşu analizi ve üyelik çıkarımı gibi yöntemler riski ölçmeye yardımcı olur. Tek bir skor yerine farklı saldırı senaryoları değerlendirilmelidir." ] },
        { heading: "Fayda ve gizlilik dengesini test edin", paragraphs: ["Fazla gürültü eklemek veriyi güvenli kılabilir ama test faydasını yok edebilir. Önce kullanım amacını tanımlayın: arayüz testi için gerçek dağılıma gerek olmayabilir; analitik model için dağılım daha önemlidir. Amaç değiştiğinde veri seti yeniden değerlendirilmelidir.", "Mümkünse sıfırdan kural tabanlı örnek üretin. Gerçek veriden öğrenilen yöntemlerde veri erişimini sınırlandırın, nadir kategorileri birleştirin ve çıktıları benzerlik testinden geçirin."], bullets: ["Kaynak veriye erişimi kaydedin.", "Nadir kombinasyonları bastırın.", "Gerçek kayda yakınlığı ölçün.", "Kullanım amacını veri setiyle birlikte belgeleyin."] },
        { heading: "Paylaşım öncesi yönetişim", paragraphs: ["Sentetik veri de kurumsal varlıktır. Sürüm, üretim yöntemi, kaynak dönemi, bilinen sapmalar ve izin verilen kullanım açıklanmalıdır. Üçüncü tarafla paylaşımda yeniden dağıtım ve birleştirme riskleri sözleşmeye yansıtılmalıdır.", "ByteQuant'ın yerel dönüştürme ve maskeleme araçları küçük örnek setlerini hazırlamaya yardımcı olabilir; ileri sentetik veri güvenliği için istatistiksel gizlilik testleri ve uzman değerlendirmesi gerekir." ] },
      ],
      en: [
        { heading: "What synthetic data can solve", paragraphs: ["Synthetic data is not a one-to-one copy of real records, but it imitates selected structure or statistics. It can reduce access to personal data for software testing, training, and model development. Hand-designed synthetic cases are especially useful for schemas, errors, and business rules.", "If personal data was used to build the generator, that production stage still processes personal data. A synthetic output label does not erase upstream obligations." ] },
        { heading: "Memorization and re-identification", paragraphs: ["Generators can memorize rare records or unique combinations. A rare condition, small location, and precise age may identify someone without a name. Unusual closeness between synthetic and real rows is a core warning signal.", "Nearest-neighbor, distance, and membership-inference tests help assess the risk. Use multiple plausible attack scenarios rather than a single score." ] },
        { heading: "Test utility and privacy together", paragraphs: ["Noise can improve privacy while destroying usefulness. Define the purpose first: interface testing may need valid structure, while analytical development needs realistic distributions. Prefer rule-built examples where possible; restrict source access and suppress rare categories when learning from real data."], bullets: ["Log source-data access.", "Suppress rare combinations.", "Measure closeness to real records.", "Document the allowed use with the dataset."] },
        { heading: "Governance before sharing", paragraphs: ["Synthetic datasets remain managed assets. Document version, generation method, source period, known bias, and permitted use. Contracts should address redistribution and linkage risk.", "ByteQuant's local conversion and masking tools can help with small samples; advanced synthetic-data assurance requires statistical privacy tests and expert review." ] },
      ],
    },
  },
  {
    slug: "promptlari-daha-guvenli-hale-getirme",
    date: "2026-07-14",
    readTime: { tr: "8 dk", en: "7 min" },
    title: { tr: "Prompt'larınızı Nasıl Daha Güvenli Hale Getirirsiniz?", en: "How to Make Your Prompts Safer" },
    excerpt: { tr: "Kişisel veri, prompt enjeksiyonu, yetki aşımı ve doğrulanmamış çıktı risklerine karşı kısa bir güvenlik modeli kurun.", en: "Build a compact safety model for personal data, prompt injection, excess authority, and unverified output." },
    description: { tr: "Günlük yapay zekâ kullanımında prompt ve çıktı güvenliğini artırmak için uygulanabilir savunma katmanları.", en: "Practical defense layers for safer prompts and outputs in everyday AI use." },
    category: { tr: "Güvenli kullanım", en: "Safe use" },
    visualSuggestion: { tr: "Veri, talimat, model ve çıktı etrafında dört koruma halkası.", en: "Four protective rings around data, instruction, model, and output." },
    sections: {
      tr: [
        { heading: "Tehdit modelini basitleştirin", paragraphs: ["Her prompt için kapsamlı güvenlik analizi yapmak pratik değildir. Bunun yerine dört soruyla başlayın: Girdide ne var, modele ne yetki veriliyor, model ne üretecek ve çıktı nerede kullanılacak? Hassas veri ile otomatik eylem aynı akışta birleşiyorsa risk belirgin biçimde yükselir.", "Düşük riskli beyin fırtınasıyla müşteri hesabını değiştiren bir ajan aynı kontrolleri gerektirmez. Koruma düzeyi sonucun etkisine göre artmalıdır." ] },
        { heading: "Girdiyi sınırlandırın", paragraphs: ["Kullanıcı girdisini ve kaynak belgeleri açık sınırlayıcılar içinde sunun. Modelin bu bölümdeki talimatları veri olarak değerlendirmesini söyleyin. Gereksiz kişisel veriyi kaldırın; sırları, API anahtarlarını ve parolaları hiçbir prompta eklemeyin.", "Uzun belgelerde yalnızca gerekli bölümleri kullanmak hem güvenliği hem cevap kalitesini artırır. Daha az bağlam, daha az saldırı yüzeyi ve daha düşük maliyet demektir." ] },
        { heading: "Yetki ve çıktı kontrolü", paragraphs: ["Modelin araç kullanabildiği sistemlerde en az yetki ilkesi uygulanmalıdır. Okuma ve yazma izinlerini ayırın; para transferi, e-posta gönderimi, kayıt silme veya erişim değişikliği gibi eylemler için açık insan onayı isteyin.", "Çıktıyı tür ve şema açısından doğrulayın. URL'leri izin listesiyle, kodu test ortamında ve sayısal iddiaları kaynaklarla kontrol edin. Modelin kendinden emin dili doğruluk kanıtı değildir."], bullets: ["Hassas eylem öncesi insan onayı", "Kısa süreli ve dar kapsamlı yetki", "Şema ve iş kuralı doğrulaması", "Kayıt ve geri alma planı"] },
        { heading: "Tekrarlanabilir ekip standardı", paragraphs: ["Güvenli kullanım bireysel dikkate bırakılmamalıdır. Yasak veri türleri, onay gerektiren görevler, kabul edilen model hesapları ve olay bildirim kanalı tek sayfalık bir standartta toplanabilir. Gerçek hata örnekleriyle kısa eğitimler düzenleyin.", "ByteQuant Veri Maskeleyici ve Prompt Kalite Denetimi gönderim öncesi kontrolü destekler. Nihai güvenlik, model sağlayıcısı ayarları ve kurum içi erişim kontrolleriyle birlikte sağlanır." ] },
      ],
      en: [
        { heading: "Use a compact threat model", paragraphs: ["Start with four questions: what is in the input, what authority is granted, what will the model produce, and where will the output be used? Risk rises when sensitive data and automatic action share the same flow.", "Brainstorming and an agent that changes customer accounts should not use identical controls. Increase safeguards with impact." ] },
        { heading: "Constrain input", paragraphs: ["Place user input and source documents inside explicit delimiters and state that embedded instructions are data. Remove unnecessary personal data, and never place passwords, API keys, or secrets in a prompt. Use only the relevant document sections; less context can mean less exposure and better focus." ] },
        { heading: "Limit authority and verify output", paragraphs: ["Apply least privilege when models can call tools. Separate read and write permissions, and require human approval for payments, messages, deletion, or access changes. Validate schemas and business rules; check URLs against an allowlist and code in a test environment."], bullets: ["Human approval for high-impact actions", "Short-lived, narrow permissions", "Schema and business-rule validation", "Logging and rollback plans"] },
        { heading: "Create a repeatable team standard", paragraphs: ["Document prohibited data, approval-required tasks, allowed model accounts, and the incident channel in a short standard. Train with real failure examples rather than generic warnings.", "ByteQuant's masker and prompt checker support pre-submission review, but final safety also depends on provider settings and internal access control." ] },
      ],
    },
  },
  {
    slug: "bytequant-araclarini-kullanma-rehberi",
    date: "2026-07-14",
    readTime: { tr: "11 dk", en: "10 min" },
    title: { tr: "ByteQuant Araçlarını Etkili Kullanma Rehberi", en: "A Practical Guide to Using ByteQuant Tools" },
    excerpt: { tr: "29 yerel aracı araştırma, içerik, veri ve güvenlik iş akışlarında doğru sırayla birleştirin.", en: "Combine 29 local tools in practical research, content, data, and security workflows." },
    description: { tr: "ByteQuant'ın prompt, metin, veri ve güvenlik araçlarını verimli ve güvenli iş akışlarında kullanmak için kapsamlı başlangıç rehberi.", en: "A complete starting guide to ByteQuant's prompt, text, data, and security tools." },
    category: { tr: "Ürün rehberi", en: "Product guide" },
    visualSuggestion: { tr: "Dört araç kategorisinden üç örnek iş akışına bağlanan yol haritası.", en: "A roadmap connecting four tool categories to three sample workflows." },
    sections: {
      tr: [
        { heading: "Doğru araçla başlayın", paragraphs: ["ByteQuant dört tür işi hedefler: prompt hazırlama, metin inceleme, veri dönüştürme ve gizlilik/güvenlik. Önce ulaşmak istediğiniz çıktıyı tanımlayın. Bir metni modele göndermeden önce maskelemek istiyorsanız güvenlik kategorisi; model talimatını geliştirmek istiyorsanız prompt kategorisi doğru başlangıçtır.", "Araçlar bir yapay zekâ hizmetine bağlanmaz. Analiz ve dönüşüm tarayıcıda yapılır. Bu nedenle sonuçlar hızlı ve açıklanabilirdir; ancak büyük dil modeli üretimi veya internet araştırması yapmaz." ] },
        { heading: "İçerik iş akışı örneği", paragraphs: ["Bir rehber yazısını düzenlerken önce Kelime Sayacı ile kapsamı, ardından Okunabilirlik Analizi ile cümle yoğunluğunu inceleyin. Metin Temizleyici kopyalama sorunlarını düzeltir; Büyük/Küçük Harf Dönüştürücü başlık standardını uygular. İki sürüm arasındaki değişimi Metin Benzerlik Analizi ile sayısallaştırabilirsiniz.", "Skorları hedef değil sinyal olarak görün. Teknik bir rehberin doğal olarak daha uzun cümleleri olabilir. En iyi karar, ölçüm ile editoryal amacı birlikte değerlendirmektir."], bullets: ["Kelime ve yapı ölçümü", "Okunabilirlik kontrolü", "Biçim temizliği", "Sürüm karşılaştırması"] },
        { heading: "Prompt ve gizlilik iş akışı", paragraphs: ["Ham talimatı Meta Prompt Oluşturucu ile yapılandırın, Prompt Kalite Denetimi ile eksik hedef ve kısıtları bulun. İçeriğe gerçek müşteri verisi eklenecekse önce KVKK/GDPR Veri Maskeleyici kullanın. Token Sayacı, bağlamın yaklaşık büyüklüğünü gösterir.", "Maskeleme çıktısını mutlaka elle okuyun. Araç yaygın desenleri bulur; isim, nadir olay veya dolaylı tanımlayıcı gibi bağlamsal verileri her zaman yakalayamaz." ] },
        { heading: "Veri ve geliştirici iş akışı", paragraphs: ["API örneğini JSON Biçimlendirici ile doğrulayın; düz kayıt dizisini JSON ↔ CSV Dönüştürücü ile tabloya aktarın. CSV Yapı İnceleyici başlık ve sütun sorunlarını gösterir. Regex Test Aracı, tekrar kullanılacak ayrıştırma kalıbını örnek metinde sınamanıza yardım eder.", "Dönüşüm öncesinde orijinal verinin yedeğini tutun. İç içe JSON ve çok büyük dosyalar için masaüstü ya da komut satırı araçları daha uygun olabilir." ] },
        { heading: "Çıktıyı güvenli yönetin", paragraphs: ["Kopyala ve indir işlemleri veriyi tarayıcı dışına çıkarır. Paylaşılan bilgisayarda pano geçmişi ve indirilenler klasörünü kontrol edin. Parolaları düz metin notta değil parola yöneticisinde saklayın; SHA-256 aracını parola depolama yöntemi olarak kullanmayın.", "Her araç sayfasında yöntemi, kullanım adımlarını ve sınırları okuyabilirsiniz. Hata veya geliştirme önerisini bytequant@yahoo.com adresine iletmek ürün kalitesine katkı sağlar." ] },
      ],
      en: [
        { heading: "Start with the outcome", paragraphs: ["ByteQuant supports four kinds of work: prompt preparation, text analysis, data transformation, and privacy/security. Define the intended output first. Use security tools before sharing sensitive text and prompt tools when improving model instructions.", "The tools do not call an AI service. Analysis and transformation happen in the browser, making results fast and explainable, but they do not generate with a large language model or research the web." ] },
        { heading: "Example content workflow", paragraphs: ["Use Word Counter for scope, Readability Analyzer for sentence density, Text Cleaner for copy artifacts, and Case Converter for heading standards. Text Similarity can quantify change between versions. Treat scores as signals rather than goals; editorial purpose still decides what is good."], bullets: ["Measure length and structure", "Review readability", "Clean formatting", "Compare versions"] },
        { heading: "Prompt and privacy workflow", paragraphs: ["Structure a rough instruction with Meta Prompt Builder, find missing goals and constraints with Prompt Quality Checker, then run Data Masker before adding real records. Token Counter estimates context size. Always read masked output manually because contextual identifiers may not match a regular expression." ] },
        { heading: "Data workflow and safe output", paragraphs: ["Validate API samples with JSON Formatter, move flat records with JSON ↔ CSV Converter, inspect column consistency with CSV Inspector, and test parsing patterns in Regex Tester. Keep an original backup; nested JSON and very large files may need desktop tooling.", "Copying or downloading moves data outside the page. Check clipboard history and downloads on shared devices, store generated passwords in a password manager, and never use plain SHA-256 for password storage." ] },
      ],
    },
  },
];

export function getPost(slug: string) {
  return posts.find((post) => post.slug === slug);
}
