import type { Locale } from "./site";
import type { ToolCategory } from "./tools";
import type { BaseTool } from "./tool-locales";

type L = Record<Locale, string>;
type Spec = { slug: string; category: ToolCategory; mark: string; title: L; short: L };

const categoryDetail: Record<ToolCategory, L> = {
  prompt: { tr: "Açıklanabilir kurallarla cihazınızda çalışır; üretilen taslağı gerçek model ve test vakalarıyla doğrulayın.", en: "It runs on-device with explainable rules; validate the draft with the real model and representative tests.", de: "Die Prüfung läuft lokal mit nachvollziehbaren Regeln; validieren Sie den Entwurf am echten Modell und mit repräsentativen Tests.", zh: "工具以可解释规则在设备端运行；请结合真实模型与代表性测试验证草稿。" },
  text: { tr: "Metin uzak bir servise gönderilmez; dil ve bağlam kararları için son insan kontrolü gerekir.", en: "Text is not sent to a remote service; final human review remains necessary for language and context.", de: "Text wird nicht an einen Remote-Dienst gesendet; Sprache und Kontext erfordern eine abschließende menschliche Prüfung.", zh: "文本不会发送到远程服务；语言与语境仍需人工最终审核。" },
  data: { tr: "Girdiyi yerel olarak doğrular, dönüşüm varsayımlarını ve veri kaybı riskini görünür kılar.", en: "It validates input locally and exposes transformation assumptions and data-loss risks.", de: "Eingaben werden lokal validiert; Annahmen und mögliche Datenverluste bleiben sichtbar.", zh: "在本地验证输入，并明确显示转换假设与数据丢失风险。" },
  converter: { tr: "Dönüşüm etkin sekmede yapılır, kaynak içerik değiştirilmez ve sınırlar sonuçla birlikte gösterilir.", en: "Conversion happens in the active tab, never overwrites the source, and reports its limits with the result.", de: "Die Konvertierung erfolgt im aktiven Tab, überschreibt die Quelle nicht und zeigt Grenzen mit dem Ergebnis.", zh: "转换在当前标签页完成，不覆盖源内容，并随结果说明限制。" },
  security: { tr: "Sonuç açıklanabilir bir ön kontroldür; güvenlik, kimlik veya mevzuat uyumu garantisi değildir.", en: "The result is an explainable pre-check, not a guarantee of security, identity, or legal compliance.", de: "Das Ergebnis ist eine nachvollziehbare Vorprüfung, keine Garantie für Sicherheit, Identität oder Rechtskonformität.", zh: "结果仅为可解释的预检查，不保证安全、身份或法律合规。" },
  calculation: { tr: "Formül ve varsayımları gösteren bir senaryo hesabıdır; profesyonel finans veya bilim tavsiyesi değildir.", en: "This is a scenario calculation with visible formulas and assumptions, not professional financial or scientific advice.", de: "Dies ist eine Szenariorechnung mit sichtbaren Formeln und Annahmen, keine professionelle Finanz- oder Wissenschaftsberatung.", zh: "这是展示公式与假设的情景计算，不构成专业财务或科学建议。" },
  general: { tr: "Düzenlenebilir bir başlangıç çıktısı üretir; resmî belge veya uzman onayı yerine geçmez.", en: "It creates an editable starting point and does not replace an official document or expert approval.", de: "Erstellt einen bearbeitbaren Ausgangspunkt und ersetzt kein offizielles Dokument oder fachliche Freigabe.", zh: "生成可编辑的起始结果，不能替代正式文件或专家批准。" },
  ai: { tr: "Uzak model çağırmadan AI iş akışını yapılandırır; model çıktısı üretmez veya doğrulamaz.", en: "It structures an AI workflow without calling a remote model; it neither generates nor verifies model output.", de: "Strukturiert KI-Abläufe ohne Remote-Modell; Modellantworten werden weder erzeugt noch verifiziert.", zh: "无需调用远程模型即可构建 AI 工作流；不会生成或验证模型输出。" },
  codeSecurity: { tr: "Kod çalıştırmadan desenleri tarar; tam SAST, istismar kanıtı veya güvenlik onayı değildir.", en: "It scans patterns without executing code; it is not full SAST, proof of exploitability, or security approval.", de: "Prüft Muster ohne Codeausführung; kein vollständiges SAST, Exploit-Nachweis oder Sicherheitsfreigabe.", zh: "不执行代码，仅扫描模式；不等同于完整 SAST、可利用性证明或安全批准。" },
  research: { tr: "İddia, kaynak ve belirsizliği ayırır; doğruluk ve kaynak güvenilirliği yine elle doğrulanmalıdır.", en: "It separates claims, sources, and uncertainty; accuracy and source reliability still require manual verification.", de: "Trennt Aussagen, Quellen und Unsicherheit; Richtigkeit und Quellenqualität müssen manuell geprüft werden.", zh: "区分主张、来源与不确定性；准确性和来源可靠性仍需人工核验。" },
};

const commonUseCases: Record<Locale, string[]> = {
  tr: ["Yayın öncesi kalite kontrolü", "Tekrarlanabilir ekip iş akışı", "Hata ve sınır durumlarını görünür kılma"],
  en: ["Pre-publication quality checks", "Repeatable team workflows", "Making errors and edge cases visible"],
  de: ["Qualitätsprüfung vor Veröffentlichung", "Wiederholbare Teamabläufe", "Fehler und Grenzfälle sichtbar machen"],
  zh: ["发布前质量检查", "可重复的团队工作流", "明确显示错误与边界情况"],
};
const commonSteps: Record<Locale, string[]> = {
  tr: ["Hazır örneği yükleyin veya kendi verinizi girin.", "Yerel işlemi çalıştırıp uyarı ve ölçümleri inceleyin.", "Sonucu hedef ortamda ve sınır durumlarıyla doğrulayın."],
  en: ["Load the safe demo or enter your own data.", "Run the local operation and inspect warnings and metrics.", "Validate the result in the target environment and with edge cases."],
  de: ["Sicheres Beispiel laden oder eigene Daten eingeben.", "Lokale Verarbeitung starten und Warnungen sowie Kennzahlen prüfen.", "Ergebnis im Zielsystem und mit Grenzfällen validieren."],
  zh: ["加载安全示例或输入自己的数据。", "运行本地处理并检查警告与指标。", "在目标环境和边界案例中验证结果。"],
};

function tool(spec: Spec): BaseTool {
  const detail = categoryDetail[spec.category];
  return { ...spec, description: { tr: `${spec.short.tr} ${detail.tr}`, en: `${spec.short.en} ${detail.en}`, de: `${spec.short.de} ${detail.de}`, zh: `${spec.short.zh}${detail.zh}` }, useCases: commonUseCases, steps: commonSteps };
}

const specs: Spec[] = [
  { slug: "talimat-cakisma-denetleyici", category: "prompt", mark: "212", title: { tr: "Talimat Çakışması Denetleyici", en: "Instruction Conflict Auditor", de: "Anweisungs-Konfliktprüfung", zh: "指令冲突检查器" }, short: { tr: "Bir prompttaki zorunluluk, yasak ve öncelik çakışmalarını satır satır bulun.", en: "Find conflicting requirements, prohibitions, and priorities line by line.", de: "Widersprüche zwischen Pflichten, Verboten und Prioritäten zeilenweise finden.", zh: "逐行查找要求、禁止项与优先级之间的冲突。" } },
  { slug: "few-shot-kapsama-analizoru", category: "prompt", mark: "213", title: { tr: "Few-shot Kapsama Analizörü", en: "Few-shot Coverage Analyzer", de: "Few-shot-Abdeckungsanalyse", zh: "少样本覆盖分析器" }, short: { tr: "Örnek çiftlerinin sınıf, tekrar, uzunluk ve sınır durumu kapsamını ölçün.", en: "Measure class, duplication, length, and edge-case coverage across example pairs.", de: "Klassen-, Duplikat-, Längen- und Grenzfallabdeckung von Beispielpaaren messen.", zh: "衡量示例对的类别、重复、长度与边界案例覆盖情况。" } },
  { slug: "prompt-surum-degisiklik-ozeti", category: "prompt", mark: "214", title: { tr: "Prompt Sürüm Değişiklik Özeti", en: "Prompt Version Change Summary", de: "Prompt-Versionsänderungsübersicht", zh: "提示词版本变更摘要" }, short: { tr: "İki prompt sürümündeki ekleme, silme ve davranış riski taşıyan değişiklikleri özetleyin.", en: "Summarize additions, removals, and behavior-risk changes between two prompt versions.", de: "Ergänzungen, Entfernungen und verhaltensrelevante Änderungen zweier Prompt-Versionen zusammenfassen.", zh: "汇总两个提示词版本中的新增、删除与行为风险变化。" } },
  { slug: "degerlendirme-veri-seti-sablonu", category: "ai", mark: "215", title: { tr: "Değerlendirme Veri Seti Şablonu", en: "Evaluation Dataset Template Builder", de: "Evaluationsdatensatz-Vorlage", zh: "评估数据集模板生成器" }, short: { tr: "Girdi, beklenen sonuç ve etiket satırlarını doğrulanabilir JSONL test kayıtlarına dönüştürün.", en: "Turn input, expected result, and label rows into reviewable JSONL test records.", de: "Eingabe-, Erwartungs- und Label-Zeilen in prüfbare JSONL-Testfälle umwandeln.", zh: "把输入、预期结果与标签行转换为可审核的 JSONL 测试记录。" } },
  { slug: "ajan-arac-yetki-matrisi", category: "ai", mark: "216", title: { tr: "Ajan Araç Yetki Matrisi", en: "Agent Tool Authority Matrix", de: "Agenten-Werkzeugbefugnismatrix", zh: "智能体工具权限矩阵" }, short: { tr: "Araçların okuma, yazma, ağ ve insan onayı sınırlarını açık bir matriste tanımlayın.", en: "Define read, write, network, and human-approval boundaries in an explicit matrix.", de: "Lese-, Schreib-, Netzwerk- und Freigabegrenzen in einer klaren Matrix definieren.", zh: "在明确矩阵中定义读取、写入、网络与人工审批边界。" } },
  { slug: "beyaz-alan-gorunurlestirici", category: "text", mark: "217", title: { tr: "Beyaz Alan Görselleştirici", en: "Whitespace Visualizer", de: "Leerraum-Visualisierung", zh: "空白字符可视化工具" }, short: { tr: "Boşluk, sekme, satır sonu ve görünmez kontrol karakterlerini işaretleyin.", en: "Reveal spaces, tabs, line endings, and invisible control characters.", de: "Leerzeichen, Tabs, Zeilenenden und unsichtbare Steuerzeichen anzeigen.", zh: "显示空格、制表符、换行符与不可见控制字符。" } },
  { slug: "unicode-benzer-karakter-tarayicisi", category: "text", mark: "218", title: { tr: "Unicode Benzer Karakter Tarayıcısı", en: "Unicode Confusable Scanner", de: "Unicode-Homoglyphen-Prüfung", zh: "Unicode 易混淆字符扫描器" }, short: { tr: "Karışık alfabe, sıfır genişlikli ve yön değiştiren karakterleri açıklanabilir biçimde bulun.", en: "Find mixed-script, zero-width, and bidirectional characters with explainable evidence.", de: "Gemischte Schriften, Nullbreiten- und bidirektionale Zeichen nachvollziehbar finden.", zh: "以可解释证据查找混合文字、零宽与双向控制字符。" } },
  { slug: "satir-sonu-donusturucu", category: "text", mark: "219", title: { tr: "Satır Sonu Dönüştürücü", en: "Line Ending Converter", de: "Zeilenende-Konverter", zh: "换行符转换器" }, short: { tr: "LF ve CRLF satır sonlarını sayın, karışık yapıyı bulun ve güvenle standartlaştırın.", en: "Count LF and CRLF endings, detect mixed files, and normalize them safely.", de: "LF- und CRLF-Enden zählen, Mischformen erkennen und sicher vereinheitlichen.", zh: "统计 LF 与 CRLF，检测混合换行并安全统一。" } },
  { slug: "paragraf-ana-hat-cikarici", category: "text", mark: "220", title: { tr: "Paragraf Ana Hat Çıkarıcı", en: "Paragraph Outline Extractor", de: "Absatz-Gliederungsextraktor", zh: "段落提纲提取器" }, short: { tr: "Uzun metindeki paragraf tezlerini ve tekrar eden anahtar kavramları yerel olarak çıkarın.", en: "Extract paragraph theses and recurring key concepts locally from long text.", de: "Absatzthesen und wiederkehrende Schlüsselbegriffe lokal aus langen Texten ableiten.", zh: "在本地从长文本中提取段落主旨与重复关键词。" } },
  { slug: "e-posta-konu-onizleyici", category: "text", mark: "221", title: { tr: "E-posta Konu ve Preheader Önizleyici", en: "Email Subject & Preheader Preview", de: "E-Mail-Betreff- & Preheader-Vorschau", zh: "邮件主题与预览文本检查器" }, short: { tr: "Konu ve preheader uzunluğunu mobil/masaüstü kırpma sınırlarıyla önizleyin.", en: "Preview subject and preheader length against common mobile and desktop truncation ranges.", de: "Betreff und Preheader anhand typischer Mobil- und Desktop-Kürzungen prüfen.", zh: "按常见移动端与桌面端截断范围预览主题和预览文本。" } },
  { slug: "json-anahtar-esleme-donusturucu", category: "data", mark: "222", title: { tr: "JSON Anahtar Eşleme Dönüştürücü", en: "JSON Key Mapper", de: "JSON-Schlüsselzuordnung", zh: "JSON 键映射转换器" }, short: { tr: "İç içe JSON anahtarlarını açık eşleme kurallarıyla yeniden adlandırın ve çakışmaları durdurun.", en: "Rename nested JSON keys with explicit mappings and stop on collisions.", de: "Verschachtelte JSON-Schlüssel mit expliziten Regeln umbenennen und Kollisionen stoppen.", zh: "按明确规则重命名嵌套 JSON 键，并在冲突时停止。" } },
  { slug: "json-dizi-sirala-filtrele", category: "data", mark: "223", title: { tr: "JSON Dizi Sıralama ve Filtreleme", en: "JSON Array Sort & Filter", de: "JSON-Array sortieren & filtern", zh: "JSON 数组排序与筛选" }, short: { tr: "Nesne dizilerini alan, yön ve eşitlik filtresiyle kararlı biçimde düzenleyin.", en: "Stably organize object arrays by field, direction, and equality filter.", de: "Objektarrays stabil nach Feld, Richtung und Gleichheitsfilter ordnen.", zh: "按字段、方向与等值条件稳定整理对象数组。" } },
  { slug: "csv-pivot-ozeti", category: "data", mark: "224", title: { tr: "CSV Pivot Özeti", en: "CSV Pivot Summary", de: "CSV-Pivotübersicht", zh: "CSV 透视汇总" }, short: { tr: "CSV satırlarını bir kategoriye göre gruplayıp sayı, toplam veya ortalama özeti üretin.", en: "Group CSV rows by a category and calculate count, sum, or average summaries.", de: "CSV-Zeilen gruppieren und Anzahl, Summe oder Mittelwert berechnen.", zh: "按类别分组 CSV 行并计算计数、总和或平均值。" } },
  { slug: "csv-uzun-genis-donusturucu", category: "data", mark: "225", title: { tr: "CSV Uzun ↔ Geniş Dönüştürücü", en: "CSV Long ↔ Wide Reshaper", de: "CSV Lang ↔ Breit umformen", zh: "CSV 长表 ↔ 宽表转换器" }, short: { tr: "Tabloları açık kimlik, anahtar ve değer sütunlarıyla uzun veya geniş biçime dönüştürün.", en: "Reshape tables between long and wide form using explicit id, key, and value columns.", de: "Tabellen mit expliziten ID-, Schlüssel- und Wertspalten zwischen Lang- und Breitformat umformen.", zh: "使用明确的标识、键和值列在长表与宽表之间转换。" } },
  { slug: "graphql-degisken-dogrulayici", category: "data", mark: "226", title: { tr: "GraphQL Değişken Doğrulayıcı", en: "GraphQL Variable Validator", de: "GraphQL-Variablenprüfung", zh: "GraphQL 变量验证器" }, short: { tr: "Sorgudaki değişken tanımlarını JSON değerleriyle karşılaştırıp eksik, fazla ve temel tür hatalarını bulun.", en: "Compare query variable definitions with JSON values to find missing, extra, and basic type errors.", de: "Variablendefinitionen mit JSON-Werten vergleichen und fehlende, zusätzliche oder falsch typisierte Werte finden.", zh: "对比查询变量定义与 JSON 值，查找缺失、多余及基本类型错误。" } },
  { slug: "http-cache-control-olusturucu", category: "data", mark: "227", title: { tr: "HTTP Cache-Control Oluşturucu", en: "HTTP Cache-Control Builder", de: "HTTP Cache-Control-Generator", zh: "HTTP Cache-Control 生成器" }, short: { tr: "Önbellek hedefi, süre ve yeniden doğrulama kararlarından tutarlı bir başlık üretin.", en: "Build a consistent header from cache audience, lifetime, and revalidation decisions.", de: "Aus Zielgruppe, Lebensdauer und Revalidierung einen konsistenten Header erzeugen.", zh: "根据缓存受众、时长与重新验证决策生成一致的响应头。" } },
  { slug: "content-disposition-olusturucu", category: "data", mark: "228", title: { tr: "Content-Disposition Oluşturucu", en: "Content-Disposition Builder", de: "Content-Disposition-Generator", zh: "Content-Disposition 生成器" }, short: { tr: "Unicode dosya adları için güvenli ASCII geri dönüşlü inline veya attachment başlığı üretin.", en: "Generate inline or attachment headers with a safe ASCII fallback for Unicode filenames.", de: "Inline- oder Attachment-Header mit sicherem ASCII-Fallback für Unicode-Dateinamen erzeugen.", zh: "为 Unicode 文件名生成带安全 ASCII 回退的 inline 或 attachment 响应头。" } },
  { slug: "iso-8601-tarih-inceleyici", category: "data", mark: "229", title: { tr: "ISO 8601 Tarih İnceleyici", en: "ISO 8601 Date Inspector", de: "ISO-8601-Datumsprüfung", zh: "ISO 8601 日期检查器" }, short: { tr: "Tarih-saat satırlarını UTC, epoch, ofset ve belirsiz saat dilimi açısından inceleyin.", en: "Inspect date-time rows for UTC, epoch, offset, and ambiguous time-zone assumptions.", de: "Datumszeilen auf UTC, Epoch, Offset und mehrdeutige Zeitzonenannahmen prüfen.", zh: "检查日期时间行的 UTC、Epoch、偏移与含糊时区假设。" } },
  { slug: "ini-json-donusturucu", category: "converter", mark: "230", title: { tr: "INI ↔ JSON Dönüştürücü", en: "INI ↔ JSON Converter", de: "INI ↔ JSON Konverter", zh: "INI ↔ JSON 转换器" }, short: { tr: "INI bölümleri ile düz JSON nesneleri arasında açıklanabilir dönüşüm yapın.", en: "Convert between INI sections and flat JSON objects with visible assumptions.", de: "INI-Abschnitte und flache JSON-Objekte mit sichtbaren Annahmen konvertieren.", zh: "在 INI 分区与扁平 JSON 对象之间进行透明转换。" } },
  { slug: "properties-json-donusturucu", category: "converter", mark: "231", title: { tr: "Properties ↔ JSON Dönüştürücü", en: "Properties ↔ JSON Converter", de: "Properties ↔ JSON Konverter", zh: "Properties ↔ JSON 转换器" }, short: { tr: "Java `.properties` anahtar-değer satırları ile JSON arasında güvenli taslak dönüşümü yapın.", en: "Convert Java `.properties` key-value rows and JSON into safe drafts.", de: "Java-`.properties`-Zeilen und JSON sicher ineinander umwandeln.", zh: "在 Java `.properties` 键值行与 JSON 之间进行安全草稿转换。" } },
  { slug: "csv-sabit-genislik-donusturucu", category: "converter", mark: "232", title: { tr: "CSV ↔ Sabit Genişlik Dönüştürücü", en: "CSV ↔ Fixed-width Converter", de: "CSV ↔ Festbreiten-Konverter", zh: "CSV ↔ 定宽文本转换器" }, short: { tr: "CSV tablolarını okunabilir sabit genişlikli metne çevirin veya sütun genişlikleriyle geri ayrıştırın.", en: "Convert CSV tables to readable fixed-width text or parse them back with explicit widths.", de: "CSV in lesbaren Festbreitentext umwandeln oder mit expliziten Breiten zurücklesen.", zh: "把 CSV 转为可读定宽文本，或按明确列宽解析回来。" } },
  { slug: "cookie-ozellik-denetleyici", category: "codeSecurity", mark: "233", title: { tr: "Cookie Özellik Denetleyici", en: "Cookie Attribute Auditor", de: "Cookie-Attributprüfung", zh: "Cookie 属性审计器" }, short: { tr: "Set-Cookie satırlarını Secure, HttpOnly, SameSite, alan ve önek kuralları açısından denetleyin.", en: "Audit Set-Cookie rows for Secure, HttpOnly, SameSite, domain, and prefix rules.", de: "Set-Cookie-Zeilen auf Secure, HttpOnly, SameSite, Domain und Präfixregeln prüfen.", zh: "检查 Set-Cookie 行中的 Secure、HttpOnly、SameSite、域与前缀规则。" } },
  { slug: "cors-politikasi-denetleyici", category: "codeSecurity", mark: "234", title: { tr: "CORS Politikası Denetleyici", en: "CORS Policy Auditor", de: "CORS-Richtlinienprüfung", zh: "CORS 策略审计器" }, short: { tr: "CORS yanıt başlıklarında wildcard, kimlik bilgisi, yöntem ve Vary çakışmalarını bulun.", en: "Find wildcard, credential, method, and Vary conflicts in CORS response headers.", de: "Wildcard-, Credential-, Methoden- und Vary-Konflikte in CORS-Headern finden.", zh: "查找 CORS 响应头中的通配符、凭据、方法与 Vary 冲突。" } },
  { slug: "oauth-yonlendirme-uri-denetleyici", category: "codeSecurity", mark: "235", title: { tr: "OAuth Yönlendirme URI Denetleyici", en: "OAuth Redirect URI Auditor", de: "OAuth-Redirect-URI-Prüfung", zh: "OAuth 重定向 URI 审计器" }, short: { tr: "Yönlendirme URI listesini HTTPS, wildcard, fragment, kullanıcı bilgisi ve localhost sınırlarıyla denetleyin.", en: "Audit redirect URIs for HTTPS, wildcards, fragments, userinfo, and localhost boundaries.", de: "Redirect-URIs auf HTTPS, Wildcards, Fragmente, Userinfo und Localhost-Grenzen prüfen.", zh: "检查重定向 URI 的 HTTPS、通配符、片段、用户信息与 localhost 边界。" } },
  { slug: "veri-saklama-suresi-planlayici", category: "security", mark: "236", title: { tr: "Veri Saklama Süresi Planlayıcı", en: "Data Retention Schedule Builder", de: "Aufbewahrungsplan-Generator", zh: "数据保留计划生成器" }, short: { tr: "Veri türü, amaç, başlangıç olayı, süre ve silme sahibini tek bir denetim tablosunda toplayın.", en: "Combine data type, purpose, trigger, period, and deletion owner in one review table.", de: "Datenart, Zweck, Startauslöser, Dauer und Löschverantwortung in einer Prüftabelle bündeln.", zh: "在一张审核表中整理数据类型、目的、起算事件、期限与删除负责人。" } },
  { slug: "anonimlestirme-risk-on-kontrolu", category: "security", mark: "237", title: { tr: "Anonimleştirme Risk Ön Kontrolü", en: "Anonymization Risk Pre-check", de: "Anonymisierungs-Risiko-Vorprüfung", zh: "匿名化风险预检查" }, short: { tr: "CSV örneğinde doğrudan ve dolaylı tanımlayıcıları, seyrek grupları ve küçük eşdeğerlik sınıflarını bulun.", en: "Find direct and quasi-identifiers, sparse groups, and small equivalence classes in a CSV sample.", de: "Direkte und indirekte Kennungen, seltene Gruppen und kleine Äquivalenzklassen in CSV finden.", zh: "在 CSV 样本中查找直接与准标识符、稀疏组和小等价类。" } },
  { slug: "tanimlayici-istatistik-hesaplayici", category: "calculation", mark: "238", title: { tr: "Tanımlayıcı İstatistik Hesaplayıcı", en: "Descriptive Statistics Calculator", de: "Deskriptive Statistik", zh: "描述性统计计算器" }, short: { tr: "Sayı dizisi için ortalama, medyan, çeyrekler, standart sapma ve aykırı değer sınırlarını hesaplayın.", en: "Calculate mean, median, quartiles, standard deviation, and outlier fences for a number series.", de: "Mittelwert, Median, Quartile, Standardabweichung und Ausreißergrenzen berechnen.", zh: "计算数列的均值、中位数、四分位数、标准差与异常值边界。" } },
  { slug: "cagr-hesaplayici", category: "calculation", mark: "239", title: { tr: "CAGR Yıllık Bileşik Büyüme Hesaplayıcı", en: "CAGR Calculator", de: "CAGR-Rechner", zh: "复合年增长率计算器" }, short: { tr: "Başlangıç, bitiş ve yıl sayısından yıllık bileşik büyüme oranını şeffaf formülle hesaplayın.", en: "Calculate compound annual growth from start, end, and years with a transparent formula.", de: "Jährliches Wachstum aus Start-, Endwert und Jahren transparent berechnen.", zh: "根据起始值、终值与年数，用透明公式计算复合年增长率。" } },
  { slug: "roas-roi-hesaplayici", category: "calculation", mark: "240", title: { tr: "ROAS ve ROI Hesaplayıcı", en: "ROAS & ROI Calculator", de: "ROAS- & ROI-Rechner", zh: "ROAS 与 ROI 计算器" }, short: { tr: "Gelir, reklam harcaması ve toplam maliyetten ROAS, kâr ve ROI değerlerini ayırın.", en: "Separate ROAS, profit, and ROI from revenue, ad spend, and total cost.", de: "ROAS, Gewinn und ROI aus Umsatz, Werbeausgaben und Gesamtkosten getrennt berechnen.", zh: "根据收入、广告支出与总成本分别计算 ROAS、利润和 ROI。" } },
  { slug: "abonelik-maliyeti-planlayici", category: "calculation", mark: "241", title: { tr: "Abonelik Maliyeti Planlayıcı", en: "Subscription Cost Planner", de: "Abo-Kostenplaner", zh: "订阅成本规划器" }, short: { tr: "Aylık ücret, koltuk sayısı ve yıllık indirimi hizmet bazında toplayıp gerçek yıllık maliyeti görün.", en: "Combine monthly price, seats, and annual discounts to see the true yearly service cost.", de: "Monatspreis, Sitze und Jahresrabatte zum tatsächlichen Jahresaufwand zusammenführen.", zh: "结合月费、席位数与年付折扣，计算真实年度成本。" } },
  { slug: "tarih-ekle-cikar-hesaplayici", category: "calculation", mark: "242", title: { tr: "Tarih Ekle/Çıkar Hesaplayıcı", en: "Date Add/Subtract Calculator", de: "Datum addieren/subtrahieren", zh: "日期加减计算器" }, short: { tr: "Bir tarihe yıl, ay, gün veya iş günü ekleyip takvim taşmalarını görünür biçimde yönetin.", en: "Add years, months, days, or weekdays to a date with visible calendar-overflow handling.", de: "Jahre, Monate, Tage oder Werktage mit sichtbarer Kalenderlogik addieren.", zh: "向日期添加年、月、天或工作日，并明确处理日历溢出。" } },
  { slug: "pico-arastirma-sorusu-olusturucu", category: "research", mark: "243", title: { tr: "PICO Araştırma Sorusu Oluşturucu", en: "PICO Research Question Builder", de: "PICO-Forschungsfrage", zh: "PICO 研究问题生成器" }, short: { tr: "Popülasyon, müdahale, karşılaştırma, sonuç ve zaman alanlarını sınanabilir bir soruda birleştirin.", en: "Combine population, intervention, comparison, outcome, and time into a testable question.", de: "Population, Intervention, Vergleich, Ergebnis und Zeit in einer prüfbaren Frage verbinden.", zh: "把人群、干预、对照、结局与时间组合为可检验问题。" } },
  { slug: "boolean-arama-stratejisi-olusturucu", category: "research", mark: "244", title: { tr: "Boolean Arama Stratejisi Oluşturucu", en: "Boolean Search Strategy Builder", de: "Boolesche Suchstrategie", zh: "布尔检索策略生成器" }, short: { tr: "Kavram ve eş anlamlı kümelerinden belgelenebilir AND/OR arama sorguları oluşturun.", en: "Build documentable AND/OR search queries from concepts and synonym groups.", de: "Dokumentierbare AND/OR-Suchabfragen aus Begriffen und Synonymgruppen erstellen.", zh: "根据概念与同义词组生成可记录的 AND/OR 检索式。" } },
  { slug: "iddia-kanit-boslugu-inceleyici", category: "research", mark: "245", title: { tr: "İddia–Kanıt Boşluğu İnceleyici", en: "Claim–Evidence Gap Auditor", de: "Aussage–Evidenz-Lückenprüfung", zh: "主张–证据缺口审计器" }, short: { tr: "İddiaları kaynak, yöntem, tarih, destek yönü ve sınırlamalarla karşılaştırın.", en: "Compare claims with source, method, date, support direction, and limitations.", de: "Aussagen mit Quelle, Methode, Datum, Unterstützungsrichtung und Grenzen vergleichen.", zh: "按来源、方法、日期、支持方向与限制核对主张。" } },
  { slug: "kaynak-guncellik-takipcisi", category: "research", mark: "246", title: { tr: "Kaynak Güncellik Takipçisi", en: "Source Freshness Tracker", de: "Quellen-Aktualitätsprüfung", zh: "来源时效跟踪器" }, short: { tr: "Kaynak tarihini, beklenen yenileme aralığını ve kritikliği karşılaştırıp güncelleme önceliği çıkarın.", en: "Compare source date, expected refresh interval, and criticality to prioritize updates.", de: "Quellendatum, Aktualisierungsintervall und Kritikalität zur Priorisierung vergleichen.", zh: "比较来源日期、预期更新周期与关键性，确定更新优先级。" } },
];

export const precisionTools: BaseTool[] = specs.map(tool);
export const precisionToolSlugs = new Set(specs.map((item) => item.slug));
