import type { BaseTool } from "./tool-locales";

type FourText = { tr: string; en: string; de: string; zh: string };

function defineTool(
  slug: string,
  category: BaseTool["category"],
  mark: string,
  title: FourText,
  short: FourText,
  description: FourText,
  useCases: BaseTool["useCases"],
  steps: BaseTool["steps"],
): BaseTool {
  return { slug, category, mark, title, short, description, useCases, steps };
}

export const productivityTools: BaseTool[] = [
  defineTool(
    "prompt-sinirlandirici-ayirici", "prompt", "105",
    { tr: "Prompt Sınırlandırıcı ve Ayırıcı", en: "Prompt Boundary & Delimiter Builder", de: "Prompt-Grenzen- und Trennzeichen-Generator", zh: "提示词边界与分隔符生成器" },
    { tr: "Güvenilmeyen içeriği talimattan ayıran açık veri sınırları kurun.", en: "Build explicit data boundaries that separate untrusted content from instructions.", de: "Trennen Sie nicht vertrauenswürdige Inhalte klar von Anweisungen.", zh: "用明确的数据边界分隔不可信内容与指令。" },
    { tr: "Kullanıcı veya RAG metnini rastgele üretilen ayraçlar içine alır; modelin içerideki metni veri olarak ele almasını isteyen, izin verilen ve yasak davranışları açıklayan bir şablon üretir. Enjeksiyon saldırılarını tek başına engellemez.", en: "Wraps user or RAG text in generated delimiters and produces a template that tells a model to treat enclosed content as data, with allowed and forbidden behavior. It does not stop prompt injection by itself.", de: "Umschließt Benutzer- oder RAG-Text mit erzeugten Trennzeichen und erstellt klare Datenregeln. Dies verhindert Prompt-Injection nicht allein.", zh: "用生成的分隔符包裹用户或 RAG 文本，并生成明确的数据处理规则；它本身不能阻止提示注入。" },
    { tr: ["RAG içeriğini talimattan ayırma", "Kullanıcı metnini güvenli kanala alma", "Prompt incelemesini standartlaştırma"], en: ["Separating RAG content from instructions", "Isolating user text as data", "Standardizing prompt reviews"] },
    { tr: ["İşlenecek metni yapıştırın.", "Yerel şablonu üretin ve sınırları inceleyin.", "Gerçek modelde rol ayrımı ve izin listesiyle ayrıca test edin."], en: ["Paste the content to process.", "Generate the local template and review its boundaries.", "Test separately with role separation and allowlists on the real model."] },
  ),
  defineTool(
    "yapisal-cikti-semasi-olusturucu", "prompt", "106",
    { tr: "Yapısal Çıktı Şeması Oluşturucu", en: "Structured Output Schema Builder", de: "Generator für strukturierte Ausgabeschemas", zh: "结构化输出模式生成器" },
    { tr: "Alan tariflerinden JSON Schema ve model çıktı sözleşmesi üretin.", en: "Turn field definitions into JSON Schema and a model output contract.", de: "Erzeugen Sie JSON Schema und einen Ausgabevertrag aus Felddefinitionen.", zh: "根据字段定义生成 JSON Schema 和模型输出约定。" },
    { tr: "Satır başına alan adı, tür, zorunluluk ve açıklamayı ayrıştırarak kapalı özellikli bir JSON Schema taslağı ve kısa üretim talimatı oluşturur. Şema örnekten türetilir; iş alanı doğrulamasının yerine geçmez.", en: "Parses one field name, type, required flag, and description per line to create a closed-object JSON Schema draft and a concise generation contract. The draft does not replace domain validation.", de: "Erstellt aus Feld, Typ, Pflichtangabe und Beschreibung ein geschlossenes JSON-Schema samt Ausgabevertrag; fachliche Validierung bleibt erforderlich.", zh: "按行解析字段、类型、必填标记与说明，生成封闭对象的 JSON Schema 草案和输出约定；仍需业务校验。" },
    { tr: ["API yanıt sözleşmesi", "Model çıktısını ayrıştırılabilir kılma", "Form alanı şeması hazırlama"], en: ["API response contracts", "Making model output parseable", "Preparing form field schemas"] },
    { tr: ["Alanları name:type:required:açıklama biçiminde yazın.", "Şemayı üretip tür ve zorunlulukları kontrol edin.", "Gerçek doğrulayıcı ve alan kurallarıyla test edin."], en: ["Enter fields as name:type:required:description.", "Generate the schema and review types and requirements.", "Test with a real validator and domain rules."] },
  ),
  defineTool(
    "ai-red-team-kontrol-listesi", "ai", "107",
    { tr: "AI Red-Team Kontrol Listesi", en: "AI Red-Team Checklist Builder", de: "KI-Red-Team-Checklisten-Generator", zh: "AI 红队检查清单生成器" },
    { tr: "Bir AI kullanım senaryosu için risk temelli, izlenebilir test listesi hazırlayın.", en: "Create a risk-based, traceable test checklist for an AI use case.", de: "Erstellen Sie eine risikobasierte, nachvollziehbare KI-Testliste.", zh: "为 AI 使用场景创建基于风险且可追踪的测试清单。" },
    { tr: "Sistemin amacı ve veri bağlamından enjeksiyon, veri sızıntısı, aşırı yetki, yanlış kesinlik, kötüye kullanım ve insan onayı başlıklarında kontrollü test önerileri üretir. Modeli çalıştırmaz ve güvenlik sertifikası vermez.", en: "Builds bounded test ideas for injection, data leakage, excessive agency, false certainty, abuse, and human approval from a system purpose and data context. It neither runs the model nor certifies security.", de: "Leitet begrenzte Tests zu Injection, Datenabfluss, übermäßiger Autonomie, Scheinsicherheit und Freigaben ab; keine Zertifizierung.", zh: "根据系统目的与数据背景生成注入、数据泄露、越权、虚假确定性和人工审批测试；不提供安全认证。" },
    { tr: ["AI özellik yayını öncesi kontrol", "Tehdit modelleme atölyesi", "İnsan değerlendirme planı"], en: ["Pre-release AI feature review", "Threat-model workshops", "Human evaluation planning"] },
    { tr: ["Sistem amacı ve işlediği veri türlerini yazın.", "Kontrol listesini üretip kapsam dışı maddeleri düzenleyin.", "Yetkili ortamda test kanıtı ve sorumluyu kaydedin."], en: ["Describe the system purpose and data types.", "Generate the checklist and tailor its scope.", "Record evidence and owners from authorized tests."] },
  ),
  defineTool(
    "grapheme-guvenli-metin-ters-cevirici", "text", "108",
    { tr: "Grapheme-Güvenli Metin Ters Çevirici", en: "Grapheme-Safe Text Reverser", de: "Graphem-sicherer Textumkehrer", zh: "字素安全文本反转器" },
    { tr: "Emoji ve birleşik karakterleri bozmadan metni ters çevirin.", en: "Reverse text without breaking emoji or combined characters.", de: "Kehren Sie Text um, ohne Emoji oder kombinierte Zeichen zu zerlegen.", zh: "在不破坏表情符号和组合字符的情况下反转文本。" },
    { tr: "Intl.Segmenter desteklendiğinde kullanıcı tarafından görülen grapheme kümelerini ayırarak tersine çevirir; böylece aile emojileri ve aksan birleşimleri kod birimi tabanlı yöntemlere göre korunur.", en: "Uses Intl.Segmenter when available to reverse user-perceived grapheme clusters, preserving family emoji and combining marks better than code-unit reversal.", de: "Kehrt sichtbare Graphemcluster mit Intl.Segmenter um und erhält Emoji sowie kombinierte Zeichen besser als Codeeinheiten-Methoden.", zh: "在可用时使用 Intl.Segmenter 按可见字素簇反转，比代码单元方式更好地保留表情和组合字符。" },
    { tr: ["Unicode test verisi", "Yaratıcı metin dönüşümü", "Karakter işleme eğitimi"], en: ["Unicode test data", "Creative text transforms", "Character-processing education"] },
    { tr: ["Metni yapıştırın.", "Grapheme tabanlı dönüşümü çalıştırın.", "Hedef uygulamada font ve yön görünümünü kontrol edin."], en: ["Paste the text.", "Run grapheme-based reversal.", "Check font and direction rendering in the target app."] },
  ),
  defineTool(
    "cumle-paragraf-bolucu", "text", "109",
    { tr: "Cümle ve Paragraf Bölücü", en: "Sentence & Paragraph Splitter", de: "Satz- und Absatzteiler", zh: "句子与段落拆分器" },
    { tr: "Metni dil duyarlı cümle ve paragraf bloklarına ayırın.", en: "Split text into locale-aware sentence and paragraph blocks.", de: "Teilen Sie Text sprachsensitiv in Sätze und Absätze.", zh: "按语言感知方式将文本拆分为句子和段落。" },
    { tr: "Boş satırlardan paragrafları, Intl.Segmenter ile cümleleri çıkarır; numaralı, denetlenebilir bir döküm ve toplamlar verir. Kısaltmalar ve alan özelindeki noktalama için son kontrol gerekir.", en: "Extracts paragraphs from blank lines and sentences with Intl.Segmenter, returning an auditable numbered outline and totals. Abbreviations and domain punctuation still need review.", de: "Erkennt Absätze und Sätze mit Intl.Segmenter und liefert eine nummerierte Übersicht; Abkürzungen benötigen Kontrolle.", zh: "依据空行和 Intl.Segmenter 提取段落与句子并生成编号清单；缩写和领域标点仍需复核。" },
    { tr: ["Altyazı ve içerik hazırlama", "Metin veri seti bölme", "Editoryal kalite kontrolü"], en: ["Subtitle and content preparation", "Splitting text datasets", "Editorial quality review"] },
    { tr: ["Metni girin.", "Dil duyarlı bölmeyi çalıştırın.", "Kısaltma ve özel ad sınırlarını elle gözden geçirin."], en: ["Enter the text.", "Run locale-aware segmentation.", "Review abbreviation and proper-name boundaries manually."] },
  ),
  defineTool(
    "srt-altyazi-zaman-kaydirici", "text", "110",
    { tr: "SRT Altyazı Zaman Kaydırıcı", en: "SRT Subtitle Time Shifter", de: "SRT-Untertitel-Zeitverschiebung", zh: "SRT 字幕时间偏移器" },
    { tr: "SRT zaman kodlarını milisaniye doğruluğunda ileri veya geri kaydırın.", en: "Shift SRT timecodes forward or backward with millisecond precision.", de: "Verschieben Sie SRT-Zeitcodes millisekundengenau vor oder zurück.", zh: "以毫秒精度向前或向后移动 SRT 时间码。" },
    { tr: "SRT zaman satırlarını doğrular, belirtilen saniye farkını başlangıç ve bitişe uygular, sıfırın altını sınırlar ve değiştirilmemiş metin satırlarını korur. Video kare hızı senkronizasyonunu otomatik çözmez.", en: "Validates SRT timing lines, applies a signed second offset to starts and ends, clamps below zero, and preserves text lines. It does not automatically solve frame-rate drift.", de: "Prüft SRT-Zeitzeilen, verschiebt Start und Ende und begrenzt negative Werte; Bildraten-Drift wird nicht behoben.", zh: "校验 SRT 时间行，按秒偏移起止时间并将负值限制为零；不会自动修复帧率漂移。" },
    { tr: ["Altyazı senkron düzeltmesi", "Fragman için zaman kaydırma", "SRT kalite kontrolü"], en: ["Subtitle sync correction", "Trailer timing shifts", "SRT quality checks"] },
    { tr: ["JSON örneğinde saniye farkını ve SRT metnini girin.", "Zaman kodlarını dönüştürün.", "Videonun başı, ortası ve sonunda senkronu izleyerek doğrulayın."], en: ["Enter offset seconds and SRT text in the JSON sample.", "Transform the timecodes.", "Verify sync visually at the start, middle, and end of the video."] },
  ),
  defineTool(
    "unicode-kod-noktasi-inceleyici", "text", "111",
    { tr: "Unicode Kod Noktası İnceleyici", en: "Unicode Code Point Inspector", de: "Unicode-Codepoint-Inspektor", zh: "Unicode 码点检查器" },
    { tr: "Karakterleri kod noktası, UTF-8 byte ve görünürlük bilgisiyle inceleyin.", en: "Inspect characters by code point, UTF-8 bytes, and visibility.", de: "Prüfen Sie Zeichen nach Codepoint, UTF-8-Bytes und Sichtbarkeit.", zh: "按码点、UTF-8 字节和可见性检查字符。" },
    { tr: "Her Unicode kod noktasını U+ gösterimi, onaltılık UTF-8 byte dizisi ve boşluk/kontrol/birleşik işaret sinyaliyle listeler. Benzer görünen karakterlerin güvenilirlik veya niyetini kanıtlamaz.", en: "Lists every Unicode code point with U+ notation, UTF-8 bytes, and whitespace, control, or combining-mark signals. It cannot prove the trust or intent of lookalike characters.", de: "Listet Unicode-Codepoints, UTF-8-Bytes sowie Leer-, Steuer- und Kombinationszeichen; ähnlich aussehende Zeichen bleiben prüfpflichtig.", zh: "列出每个 Unicode 码点、UTF-8 字节及空白、控制或组合标记；不能证明相似字符的可信意图。" },
    { tr: ["Gizli karakter hata ayıklama", "Homoglif ön incelemesi", "Kodlama eğitimi"], en: ["Debugging invisible characters", "Homoglyph pre-review", "Encoding education"] },
    { tr: ["Metni yapıştırın.", "Kod noktası tablosunu üretin.", "Şüpheli karakteri bağlam ve güvenilir kaynakla doğrulayın."], en: ["Paste the text.", "Generate the code-point table.", "Verify suspicious characters against context and a trusted source."] },
  ),
  defineTool(
    "mors-kodu-donusturucu", "text", "112",
    { tr: "Mors Kodu Dönüştürücü", en: "Morse Code Converter", de: "Morsecode-Konverter", zh: "摩尔斯电码转换器" },
    { tr: "Metin ile Uluslararası Mors kodu arasında iki yönlü dönüşüm yapın.", en: "Convert both ways between text and International Morse code.", de: "Konvertieren Sie Text und internationalen Morsecode in beide Richtungen.", zh: "在文本与国际摩尔斯电码之间双向转换。" },
    { tr: "Latin harfleri, rakamlar ve yaygın noktalama için otomatik metin/Mors algılaması yapar; harfleri boşluk, kelimeleri eğik çizgiyle ayırır ve desteklenmeyen karakterleri açıkça raporlar.", en: "Auto-detects text or Morse for Latin letters, digits, and common punctuation, separating letters by spaces and words by slashes while reporting unsupported characters.", de: "Erkennt Text oder Morse automatisch, trennt Buchstaben und Wörter eindeutig und meldet nicht unterstützte Zeichen.", zh: "自动识别文本或摩尔斯电码，用空格分隔字母、斜线分隔单词，并报告不支持的字符。" },
    { tr: ["Mors öğrenme", "Eğitim alıştırması", "Basit kodlu mesaj çözme"], en: ["Learning Morse", "Educational exercises", "Decoding simple encoded messages"] },
    { tr: ["Metin veya Mors dizisini girin.", "Otomatik dönüşümü çalıştırın.", "Desteklenmeyen karakterleri ve kelime sınırlarını kontrol edin."], en: ["Enter text or Morse.", "Run auto-conversion.", "Review unsupported characters and word boundaries."] },
  ),
  defineTool(
    "json-kanoniklestirici", "data", "113",
    { tr: "JSON Kanonikleştirici", en: "JSON Canonicalizer", de: "JSON-Kanonisierer", zh: "JSON 规范化器" },
    { tr: "Nesne anahtarlarını özyinelemeli sıralayıp kararlı JSON çıktısı üretin.", en: "Recursively sort object keys to produce stable JSON output.", de: "Sortieren Sie Objektschlüssel rekursiv für stabiles JSON.", zh: "递归排序对象键以生成稳定 JSON。" },
    { tr: "JSON nesnelerindeki anahtarları Unicode kod birimi sırasıyla özyinelemeli düzenler, dizilerin sırasını ve değer türlerini korur. Bu pratik kararlılaştırma, RFC 8785/JCS sayısal kanonikleştirme uyumluluğu iddia etmez.", en: "Recursively orders JSON object keys by Unicode code units while preserving array order and value types. This practical stabilization does not claim RFC 8785/JCS numeric canonicalization.", de: "Sortiert Objektschlüssel rekursiv und erhält Arrays sowie Typen; keine Zusage vollständiger RFC-8785/JCS-Kompatibilität.", zh: "递归按 Unicode 代码单元排序对象键并保留数组顺序和类型；不声称完整符合 RFC 8785/JCS。" },
    { tr: ["Snapshot karşılaştırma", "Kararlı önbellek anahtarı hazırlama", "JSON inceleme"], en: ["Snapshot comparisons", "Preparing stable cache inputs", "Reviewing JSON"] },
    { tr: ["JSON verisini yapıştırın.", "Ayrıştırıp anahtarları sıralayın.", "İmza amacı varsa gerekli kanonik standardı ayrıca uygulayın."], en: ["Paste JSON data.", "Parse and sort object keys.", "Apply the required canonical standard separately for signatures."] },
  ),
  defineTool(
    "json-string-kacis-donusturucu", "data", "114",
    { tr: "JSON String Kaçış Dönüştürücü", en: "JSON String Escape / Unescape", de: "JSON-String-Escape / Unescape", zh: "JSON 字符串转义/反转义" },
    { tr: "UTF-8 metni JSON string literaline dönüştürün veya güvenle geri çözün.", en: "Convert UTF-8 text to a JSON string literal or decode it safely.", de: "Konvertieren Sie UTF-8-Text in ein JSON-Stringliteral und zurück.", zh: "将 UTF-8 文本转换为 JSON 字符串字面量或安全解码。" },
    { tr: "Düz metni JSON.stringify ile tırnak, ters eğik çizgi ve kontrol karakterlerinden kaçırır; geçerli bir JSON string literalini JSON.parse ile geri çözer. Kod çalıştırmaz.", en: "Uses JSON.stringify to escape quotes, backslashes, and control characters, or JSON.parse to decode a valid JSON string literal. It never evaluates code.", de: "Escaped Text mit JSON.stringify oder dekodiert gültige JSON-Stringliterale mit JSON.parse; kein Code wird ausgeführt.", zh: "使用 JSON.stringify 转义引号、反斜杠和控制字符，或用 JSON.parse 解码有效字符串字面量；不会执行代码。" },
    { tr: ["API örneği hazırlama", "Kod içi string hata ayıklama", "Satır sonu görünürleştirme"], en: ["Preparing API examples", "Debugging code strings", "Visualizing line breaks"] },
    { tr: ["Düz metin veya tırnaklı JSON string girin.", "Kaçış veya geri çözme işlemini çalıştırın.", "Hedef programlama dilinin ek kaçış kurallarını kontrol edin."], en: ["Enter plain text or a quoted JSON string.", "Run escape or unescape.", "Check any additional escaping required by the target language."] },
  ),
  defineTool(
    "csv-sql-insert-olusturucu", "data", "115",
    { tr: "CSV → SQL INSERT Oluşturucu", en: "CSV to SQL INSERT Builder", de: "CSV-zu-SQL-INSERT-Generator", zh: "CSV 转 SQL INSERT 生成器" },
    { tr: "CSV satırlarını sınırlı, gözden geçirilebilir SQL INSERT taslağına çevirin.", en: "Convert CSV rows into bounded, reviewable SQL INSERT drafts.", de: "Konvertieren Sie CSV-Zeilen in begrenzte, prüfbare SQL-INSERT-Entwürfe.", zh: "将 CSV 行转换为有界且可审查的 SQL INSERT 草案。" },
    { tr: "Tablo adı ve CSV başlıklarını güvenli tanımlayıcı kurallarıyla doğrular, hücreleri SQL string literaline kaçırır ve en fazla 500 satırlık INSERT taslağı üretir. Tür çıkarımı ve veritabanı şema doğrulaması yapmaz.", en: "Validates table and header identifiers, escapes cells as SQL string literals, and produces up to 500 INSERT drafts. It performs no type inference or database-schema validation.", de: "Prüft Tabellen- und Spaltennamen, escaped Zellen und erzeugt bis zu 500 INSERT-Entwürfe; keine Schema- oder Typprüfung.", zh: "校验表名和列名、转义单元格并生成最多 500 条 INSERT 草案；不进行类型或数据库模式校验。" },
    { tr: ["Test verisi hazırlama", "Küçük veri taşıma taslağı", "SQL inceleme eğitimi"], en: ["Preparing test data", "Drafting small data migrations", "SQL review education"] },
    { tr: ["JSON örneğinde tablo adı ve CSV'yi düzenleyin.", "INSERT taslaklarını üretin.", "Yedekli test ortamında tür, transaction ve kısıtları doğrulayın."], en: ["Edit table name and CSV in the JSON sample.", "Generate INSERT drafts.", "Verify types, transactions, and constraints in a backed-up test environment."] },
  ),
  defineTool(
    "http-istek-basligi-olusturucu", "data", "116",
    { tr: "HTTP İstek Başlığı Oluşturucu", en: "HTTP Request Header Builder", de: "HTTP-Request-Header-Generator", zh: "HTTP 请求头生成器" },
    { tr: "Accept, dil, içerik türü ve koşullu başlıklardan temiz bir taslak üretin.", en: "Build a clean header draft from Accept, language, content type, and conditional options.", de: "Erstellen Sie einen klaren Header-Entwurf aus Accept-, Sprach- und Inhaltsoptionen.", zh: "根据 Accept、语言、内容类型和条件选项生成清晰请求头草案。" },
    { tr: "Seçili HTTP istek başlıklarını normalleştirir, CR/LF enjeksiyonunu engeller ve fetch ile ham başlık görünümü üretir. Ağ isteği göndermez; kimlik bilgisi örneği eklemez.", en: "Normalizes selected HTTP request headers, blocks CR/LF injection, and produces raw-header and fetch views. It sends no request and adds no credential sample.", de: "Normalisiert HTTP-Header, blockiert CR/LF-Injection und erzeugt Roh- sowie fetch-Ansichten; keine Anfrage oder Zugangsdaten.", zh: "规范化所选 HTTP 请求头、阻止 CR/LF 注入，并生成原始头和 fetch 视图；不会发送请求或添加凭据。" },
    { tr: ["API dokümantasyonu", "fetch örneği hazırlama", "İçerik pazarlığı kontrolü"], en: ["API documentation", "Preparing fetch examples", "Reviewing content negotiation"] },
    { tr: ["JSON seçeneklerini düzenleyin.", "Başlık taslağını üretin.", "Sunucu sözleşmesi, CORS ve kimlik doğrulamayı ayrıca doğrulayın."], en: ["Edit the JSON options.", "Generate the header draft.", "Verify server contract, CORS, and authentication separately."] },
  ),
  defineTool(
    "mime-turu-bulucu", "data", "117",
    { tr: "MIME Türü Bulucu", en: "MIME Type Lookup", de: "MIME-Type-Suche", zh: "MIME 类型查询" },
    { tr: "Yaygın dosya uzantılarını MIME türü ve kullanım notlarıyla eşleyin.", en: "Map common file extensions to MIME types and handling notes.", de: "Ordnen Sie gängige Dateiendungen MIME-Typen und Hinweisen zu.", zh: "将常见文件扩展名映射到 MIME 类型及处理说明。" },
    { tr: "Dosya adı veya uzantı listesini yerel ve sabit bir tabloyla MIME türlerine eşler; metin/binary ve aktif içerik uyarılarını gösterir. Uzantı içeriğin gerçek türünü veya güvenliğini kanıtlamaz.", en: "Maps filenames or extensions against a local static MIME table and highlights text, binary, or active-content considerations. An extension does not prove actual type or safety.", de: "Ordnet Endungen über eine lokale Tabelle MIME-Typen zu und nennt aktive Inhalte; die Endung beweist weder Typ noch Sicherheit.", zh: "通过本地静态表映射文件名或扩展名，并提示文本、二进制或活动内容；扩展名不能证明真实类型或安全性。" },
    { tr: ["Content-Type taslağı", "Dosya kabul listesi", "Yükleme arayüzü incelemesi"], en: ["Drafting Content-Type", "File accept lists", "Reviewing upload interfaces"] },
    { tr: ["Her satıra dosya adı veya uzantı yazın.", "Yerel eşleştirmeyi çalıştırın.", "Kritik dosyalarda magic byte ve güvenilir ayrıştırıcıyla doğrulayın."], en: ["Enter one filename or extension per line.", "Run the local lookup.", "Verify critical files with magic bytes and a trusted parser."] },
  ),
  defineTool(
    "uuid-inceleyici", "data", "118",
    { tr: "UUID İnceleyici", en: "UUID Inspector", de: "UUID-Inspektor", zh: "UUID 检查器" },
    { tr: "UUID biçimini, sürümünü, varyantını ve özel değerlerini açıklayın.", en: "Explain UUID format, version, variant, and special values.", de: "Erklären Sie UUID-Format, Version, Variante und Sonderwerte.", zh: "解释 UUID 格式、版本、变体和特殊值。" },
    { tr: "Standart 8-4-4-4-12 UUID yazımını doğrular; sürüm nibble'ını, RFC varyant bitlerini ve nil/max durumunu raporlar. Rastgelelik kalitesini, benzersizliği veya sahipliği kanıtlamaz.", en: "Validates canonical 8-4-4-4-12 UUID text and reports the version nibble, RFC variant bits, and nil or max values. It cannot prove randomness quality, uniqueness, or ownership.", de: "Prüft die kanonische UUID-Schreibweise und meldet Version, Variante sowie Nil/Max; keine Garantie für Zufall oder Eindeutigkeit.", zh: "校验标准 UUID 文本并报告版本、变体及 nil/max；不能证明随机质量、唯一性或归属。" },
    { tr: ["API kimliği hata ayıklama", "UUID sürümü öğrenme", "Log inceleme"], en: ["Debugging API identifiers", "Learning UUID versions", "Reviewing logs"] },
    { tr: ["UUID değerini yapıştırın.", "Biçim ve bit alanlarını inceleyin.", "Kimlik kaynağını ve yaşam döngüsünü sistem kayıtlarıyla doğrulayın."], en: ["Paste the UUID.", "Inspect format and bit fields.", "Verify provenance and lifecycle from system records."] },
  ),
  defineTool(
    "ulid-uretici-inceleyici", "data", "119",
    { tr: "ULID Üretici ve İnceleyici", en: "ULID Generator & Inspector", de: "ULID-Generator und -Inspektor", zh: "ULID 生成与检查器" },
    { tr: "Web Crypto ile ULID üretin veya zaman bileşenini yerelde çözün.", en: "Generate a ULID with Web Crypto or inspect its timestamp locally.", de: "Erzeugen Sie ULIDs mit Web Crypto oder prüfen Sie ihren Zeitanteil lokal.", zh: "使用 Web Crypto 生成 ULID，或在本地检查其时间部分。" },
    { tr: "Boş girişte mevcut milisaniye ve kriptografik rastgele byte'lardan 26 karakterli ULID üretir; girilen ULID'nin Crockford Base32 biçimi ve 48 bit zamanını çözer. Monotonik üretim veya küresel benzersizlik garantisi vermez.", en: "Generates a 26-character ULID from the current millisecond and cryptographic random bytes when blank, or decodes Crockford Base32 format and its 48-bit time. It does not guarantee monotonic generation or global uniqueness.", de: "Erzeugt ULIDs aus Zeit und Web-Crypto-Zufall oder dekodiert deren 48-Bit-Zeit; keine monotone oder globale Eindeutigkeitsgarantie.", zh: "空输入时基于毫秒时间和 Web Crypto 随机字节生成 ULID，或解码其 48 位时间；不保证单调或全局唯一。" },
    { tr: ["Sıralanabilir örnek kimlik", "ULID zaman incelemesi", "Test verisi"], en: ["Sortable sample identifiers", "Inspecting ULID time", "Test data"] },
    { tr: ["Üretmek için alanı boş bırakın veya ULID girin.", "Yerel üretim/çözümlemeyi çalıştırın.", "Dağıtık sistem çakışma ve sıralama politikasını ayrıca belirleyin."], en: ["Leave blank to generate or enter a ULID.", "Run local generation or inspection.", "Define collision and ordering policy separately for distributed systems."] },
  ),
  defineTool(
    "changelog-bicimlendirici", "data", "120",
    { tr: "Changelog Biçimlendirici", en: "Changelog Formatter", de: "Changelog-Formatierer", zh: "变更日志格式化器" },
    { tr: "Dağınık değişiklik notlarını Keep a Changelog başlıklarına ayırın.", en: "Group rough release notes into Keep a Changelog-style sections.", de: "Gruppieren Sie Änderungsnotizen in Keep-a-Changelog-Abschnitte.", zh: "将零散发布说明分组为 Keep a Changelog 风格章节。" },
    { tr: "feat, fix, security, deprecate, remove ve breaking öneklerini açıklanabilir kurallarla Added, Fixed, Security, Deprecated, Removed ve Changed bölümlerine taşır; sürüm ve tarihi başlığa ekler.", en: "Maps feat, fix, security, deprecate, remove, and breaking prefixes into Added, Fixed, Security, Deprecated, Removed, and Changed sections using transparent rules, with version and date headers.", de: "Ordnet gängige Präfixe transparent Changelog-Bereichen zu und ergänzt Version sowie Datum.", zh: "按透明规则将常见前缀映射到变更日志章节，并添加版本和日期。" },
    { tr: ["Sürüm notu hazırlama", "PR özetlerini düzenleme", "Yayın kontrol listesi"], en: ["Preparing release notes", "Organizing PR summaries", "Release checklists"] },
    { tr: ["JSON örneğinde sürüm, tarih ve satırları girin.", "Markdown changelog üretin.", "Kullanıcı etkisi, bağlantı ve migration adımlarını elle ekleyin."], en: ["Enter version, date, and lines in the JSON sample.", "Generate Markdown changelog.", "Add user impact, links, and migration steps manually."] },
  ),
  defineTool(
    "css-gradient-olusturucu", "converter", "121",
    { tr: "CSS Gradient Oluşturucu", en: "CSS Gradient Generator", de: "CSS-Verlauf-Generator", zh: "CSS 渐变生成器" },
    { tr: "Doğrulanmış renk duraklarından linear-gradient CSS üretin.", en: "Generate linear-gradient CSS from validated color stops.", de: "Erzeugen Sie linear-gradient-CSS aus geprüften Farbstopps.", zh: "根据校验后的颜色停靠点生成 linear-gradient CSS。" },
    { tr: "Açı ve iki-sekiz HEX renk durağını doğrular, yüzdeleri otomatik dağıtabilir ve arka plan CSS'i ile erişilebilir düz renk yedeği önerir. Gerçek kontrastı ayrıca ölçmek gerekir.", en: "Validates an angle and two to eight HEX stops, optionally distributes positions, and returns background CSS with a solid fallback suggestion. Actual contrast must be checked separately.", de: "Prüft Winkel und zwei bis acht HEX-Stopps, verteilt Positionen und liefert CSS samt Fallback; Kontrast separat prüfen.", zh: "校验角度和 2–8 个 HEX 色标，可自动分布位置，并生成背景 CSS 与纯色回退建议；需另行检查对比度。" },
    { tr: ["Hero arka planı", "Tasarım tokenı prototipi", "Sunum kartı stili"], en: ["Hero backgrounds", "Design-token prototypes", "Presentation card styles"] },
    { tr: ["Açı ve renk duraklarını JSON'da düzenleyin.", "CSS ifadesini üretin.", "Kontrast, bantlaşma ve eski tarayıcı yedeğini test edin."], en: ["Edit angle and color stops in JSON.", "Generate the CSS expression.", "Test contrast, banding, and fallback behavior."] },
  ),
  defineTool(
    "css-box-shadow-olusturucu", "converter", "122",
    { tr: "CSS Box Shadow Oluşturucu", en: "CSS Box Shadow Generator", de: "CSS-Box-Shadow-Generator", zh: "CSS 盒阴影生成器" },
    { tr: "Ölçü ve renkten tutarlı box-shadow CSS ve token çıktısı hazırlayın.", en: "Create consistent box-shadow CSS and token output from dimensions and color.", de: "Erstellen Sie konsistentes box-shadow-CSS und Token-Ausgabe.", zh: "根据尺寸和颜色创建一致的 box-shadow CSS 与令牌输出。" },
    { tr: "X/Y kayma, bulanıklık, yayılma, renk ve inset değerlerini sınırlı aralıklarda doğrular; CSS özelliği ve özel değişken üretir. Gölgenin gerçek erişilebilirlik etkisi görsel test gerektirir.", en: "Validates x/y offset, blur, spread, color, and inset within bounded ranges and returns a CSS property plus custom property. Accessibility impact still requires visual testing.", de: "Prüft Offset, Unschärfe, Ausbreitung, Farbe und inset und liefert CSS sowie Variable; visuelle Prüfung bleibt nötig.", zh: "在限定范围内校验偏移、模糊、扩散、颜色和 inset，并生成 CSS 属性与变量；仍需视觉测试。" },
    { tr: ["Tasarım sistemi gölgesi", "Kart derinliği prototipi", "CSS tokenı"], en: ["Design-system shadows", "Card-depth prototypes", "CSS tokens"] },
    { tr: ["JSON ölçülerini ve rengi düzenleyin.", "CSS çıktısını üretin.", "Açık/koyu tema ve düşük kaliteli ekranlarda test edin."], en: ["Edit JSON dimensions and color.", "Generate CSS output.", "Test in light/dark themes and lower-quality displays."] },
  ),
  defineTool(
    "sayi-tabani-donusturucu", "converter", "123",
    { tr: "Sayı Tabanı Dönüştürücü", en: "Number Base Converter", de: "Zahlensystem-Konverter", zh: "进制转换器" },
    { tr: "Tam sayıları 2–36 tabanları arasında BigInt ile dönüştürün.", en: "Convert integers between bases 2–36 using BigInt.", de: "Konvertieren Sie Ganzzahlen mit BigInt zwischen Basen 2–36.", zh: "使用 BigInt 在 2–36 进制之间转换整数。" },
    { tr: "İşaretli tam sayıyı verilen kaynak tabanda basamak basamak doğrular, BigInt ile kesin dönüştürür ve ikilik, sekizlik, onluk ile onaltılık özet verir. Ondalık kesirleri desteklemez.", en: "Validates a signed integer digit by digit in the source base, converts exactly with BigInt, and provides binary, octal, decimal, and hexadecimal summaries. Fractions are not supported.", de: "Prüft vorzeichenbehaftete Ganzzahlen stellenweise und konvertiert exakt mit BigInt; Brüche werden nicht unterstützt.", zh: "逐位校验源进制的有符号整数并用 BigInt 精确转换；不支持小数。" },
    { tr: ["Programlama eğitimi", "Protokol değeri dönüştürme", "Hex hata ayıklama"], en: ["Programming education", "Protocol value conversion", "Hex debugging"] },
    { tr: ["Değer, kaynak taban ve hedef tabanı girin.", "Kesin dönüşümü çalıştırın.", "İşaret ve bit genişliği varsayımlarını hedef sistemde doğrulayın."], en: ["Enter value, source base, and target base.", "Run exact conversion.", "Verify sign and bit-width assumptions in the target system."] },
  ),
  defineTool(
    "byte-hex-inceleyici", "converter", "124",
    { tr: "Byte ve HEX İnceleyici", en: "Byte & Hex Inspector", de: "Byte- und HEX-Inspektor", zh: "字节与 HEX 检查器" },
    { tr: "UTF-8 metni byte/HEX tablosuna dönüştürün veya HEX'i geri çözün.", en: "Turn UTF-8 text into a byte/hex table or decode hex back to text.", de: "Konvertieren Sie UTF-8-Text in Byte/HEX oder dekodieren Sie HEX.", zh: "将 UTF-8 文本转换为字节/HEX 表，或将 HEX 解码为文本。" },
    { tr: "TextEncoder/TextDecoder ile metnin UTF-8 byte'larını ofset, onluk, onaltılık ve yazdırılabilir ASCII görünümüyle listeler; `hex:` önekli girdiyi byte dizisine geri çözer ve hatalı çiftleri reddeder.", en: "Uses TextEncoder/TextDecoder to list UTF-8 bytes by offset, decimal, hexadecimal, and printable ASCII, or decodes `hex:` input while rejecting malformed pairs.", de: "Listet UTF-8-Bytes nach Offset, Dezimal, HEX und ASCII oder dekodiert `hex:`-Eingaben mit strenger Prüfung.", zh: "使用 TextEncoder/TextDecoder 按偏移、十进制、十六进制和可打印 ASCII 列出 UTF-8 字节，或严格解码 `hex:` 输入。" },
    { tr: ["Kodlama hata ayıklama", "Protokol örneği inceleme", "UTF-8 eğitimi"], en: ["Encoding debugging", "Inspecting protocol samples", "UTF-8 education"] },
    { tr: ["Metin veya `hex:` önekli byte dizisi girin.", "Yerel incelemeyi çalıştırın.", "İkili protokol alanlarını ilgili teknik şartnameyle doğrulayın."], en: ["Enter text or `hex:` followed by bytes.", "Run local inspection.", "Verify binary protocol fields against its specification."] },
  ),
  defineTool(
    "e-posta-basligi-analizoru", "security", "125",
    { tr: "E-posta Başlığı Analizörü", en: "Email Header Analyzer", de: "E-Mail-Header-Analysator", zh: "电子邮件头分析器" },
    { tr: "Ham e-posta başlıklarını rota, kimlik doğrulama ve tutarsızlık sinyalleriyle inceleyin.", en: "Inspect raw email headers for route, authentication, and inconsistency signals.", de: "Prüfen Sie rohe E-Mail-Header auf Route, Authentifizierung und Abweichungen.", zh: "检查原始邮件头中的路由、身份验证和不一致信号。" },
    { tr: "Katlanmış başlık satırlarını ayrıştırır; Received sırasını, From/Reply-To alanlarını ve Authentication-Results içindeki SPF, DKIM, DMARC ifadelerini özetler. Kriptografik imza doğrulamaz ve göndericinin gerçekliğini garanti etmez.", en: "Parses folded header lines and summarizes Received order, From/Reply-To, and SPF, DKIM, or DMARC claims in Authentication-Results. It does not cryptographically verify signatures or guarantee sender identity.", de: "Analysiert gefaltete Header, Received-Wege und SPF/DKIM/DMARC-Angaben; keine kryptografische oder Identitätsbestätigung.", zh: "解析折叠邮件头，汇总 Received 路径、From/Reply-To 及 SPF/DKIM/DMARC 声明；不做密码学验证，也不保证发件人身份。" },
    { tr: ["Oltalama ön incelemesi", "Teslimat yolu hata ayıklama", "E-posta eğitimi"], en: ["Phishing pre-review", "Delivery-route debugging", "Email education"] },
    { tr: ["Kişisel adresleri gerekirse maskeleyip başlıkları yapıştırın.", "Yerel özeti ve uyarıları inceleyin.", "Şüpheli iletide bağlantı açmadan posta sağlayıcınızla doğrulayın."], en: ["Mask personal addresses if needed and paste headers.", "Review the local summary and warnings.", "Verify suspicious mail with your provider without opening links."] },
  ),
  defineTool(
    "csp-nonce-uretici", "codeSecurity", "126",
    { tr: "CSP Nonce Üretici", en: "CSP Nonce Generator", de: "CSP-Nonce-Generator", zh: "CSP Nonce 生成器" },
    { tr: "Web Crypto ile test ve yapılandırma örnekleri için nonce üretin.", en: "Generate nonces with Web Crypto for tests and configuration examples.", de: "Erzeugen Sie Nonces mit Web Crypto für Tests und Konfigurationsbeispiele.", zh: "使用 Web Crypto 为测试和配置示例生成 nonce。" },
    { tr: "Belirlenen byte uzunluğunda kriptografik rastgele değerler üretip Base64 biçiminde nonce ve örnek CSP/script kullanımını gösterir. Üretim nonce'u her HTTP yanıtta sunucuda yeniden üretilmeli ve aynı yanıttaki etiketlere bağlanmalıdır.", en: "Creates cryptographically random values of a chosen byte length, returning Base64 nonces and example CSP/script usage. Production nonces must be generated per HTTP response on the server and attached to tags in that response.", de: "Erzeugt kryptografische Base64-Nonces für Beispiele; Produktions-Nonces müssen pro HTTP-Antwort serverseitig neu entstehen.", zh: "生成指定字节长度的加密随机 Base64 nonce 及示例；生产 nonce 必须在服务器端为每个 HTTP 响应重新生成。" },
    { tr: ["CSP prototipi", "Test fixture oluşturma", "Nonce entegrasyonu öğrenme"], en: ["CSP prototypes", "Test fixtures", "Learning nonce integration"] },
    { tr: ["Byte uzunluğu ve adet girin.", "Web Crypto ile örnekleri üretin.", "Canlı sistemde sunucu yanıtı başına üretim ve cache davranışını doğrulayın."], en: ["Enter byte length and count.", "Generate samples with Web Crypto.", "Verify per-response server generation and caching in production."] },
  ),
  defineTool(
    "parola-politikasi-olusturucu", "security", "127",
    { tr: "Parola Politikası Oluşturucu", en: "Password Policy Builder", de: "Passwortrichtlinien-Generator", zh: "密码策略生成器" },
    { tr: "Uzunluk, engelleme ve kurtarma ilkelerinden uygulanabilir politika taslağı üretin.", en: "Create an actionable policy draft from length, blocking, and recovery controls.", de: "Erstellen Sie eine umsetzbare Richtlinie für Länge, Sperren und Wiederherstellung.", zh: "根据长度、阻止规则和恢复控制创建可执行密码策略草案。" },
    { tr: "Minimum uzunluk, parola yöneticisi/passphrase desteği, yaygın parola engeli, hız sınırlama, MFA ve güvenli kurtarma seçeneklerinden insan okunur politika ile uygulama kontrol listesi üretir. Uyumluluk sertifikası değildir.", en: "Builds a human-readable policy and implementation checklist from minimum length, manager/passphrase support, breached-password blocking, rate limits, MFA, and recovery options. It is not compliance certification.", de: "Erstellt aus Länge, Passphrase, Sperrlisten, Rate-Limits, MFA und Wiederherstellung eine Richtlinie samt Checkliste; keine Zertifizierung.", zh: "根据最小长度、密码管理器/口令支持、泄露密码阻止、速率限制、MFA 和恢复选项生成政策与清单；不是合规认证。" },
    { tr: ["Ürün güvenlik gereksinimi", "Kayıt akışı kontrolü", "Politika inceleme atölyesi"], en: ["Product security requirements", "Signup flow reviews", "Policy review workshops"] },
    { tr: ["JSON seçeneklerini risk bağlamınıza göre düzenleyin.", "Politika ve kontrol listesini üretin.", "Güncel standart, tehdit modeli ve hukuk danışmanıyla doğrulayın."], en: ["Tailor JSON options to your risk context.", "Generate the policy and checklist.", "Verify against current standards, threat model, and qualified counsel."] },
  ),
  defineTool(
    "bilesik-faiz-hesaplayici", "calculation", "128",
    { tr: "Bileşik Faiz Hesaplayıcı", en: "Compound Interest Calculator", de: "Zinseszinsrechner", zh: "复利计算器" },
    { tr: "Başlangıç tutarı ve düzenli katkılarla şeffaf büyüme senaryosu hesaplayın.", en: "Calculate a transparent growth scenario with principal and recurring contributions.", de: "Berechnen Sie ein transparentes Wachstumsszenario mit Startkapital und Beiträgen.", zh: "根据本金和定期投入计算透明的增长情景。" },
    { tr: "Yıllık nominal oranı aylık döneme çevirip başlangıç tutarı ve ay sonu katkılarını dönem dönem simüle eder; toplam katkı, tahmini getiri ve son bakiyeyi ayrı gösterir. Vergi, ücret, enflasyon ve yatırım riski dahil değildir.", en: "Converts an annual nominal rate to monthly periods and simulates principal plus end-of-month contributions, separating total contributions, estimated growth, and ending balance. Taxes, fees, inflation, and investment risk are excluded.", de: "Simuliert Startkapital und Monatsbeiträge mit nominalem Jahreszins; Steuern, Gebühren, Inflation und Risiko sind nicht enthalten.", zh: "将年名义利率换算为月度并模拟本金与月末投入，分别显示投入、估算收益和余额；不含税费、通胀和投资风险。" },
    { tr: ["Birikim senaryosu", "Katkı karşılaştırması", "Finansal eğitim"], en: ["Savings scenarios", "Contribution comparisons", "Financial education"] },
    { tr: ["Tutar, oran, yıl ve aylık katkıyı girin.", "Aylık simülasyonu çalıştırın.", "Karar öncesi gerçek ürünün ücret, vergi ve risklerini doğrulayın."], en: ["Enter amount, rate, years, and monthly contribution.", "Run the monthly simulation.", "Verify product fees, taxes, and risks before decisions."] },
  ),
  defineTool(
    "birikim-hedefi-planlayici", "calculation", "129",
    { tr: "Birikim Hedefi Planlayıcı", en: "Savings Goal Planner", de: "Sparziel-Planer", zh: "储蓄目标规划器" },
    { tr: "Hedef tutara mevcut bakiye ve aylık katkıyla ne zaman ulaşılacağını tahmin edin.", en: "Estimate when a target can be reached from current balance and monthly savings.", de: "Schätzen Sie, wann ein Sparziel mit Guthaben und Monatsrate erreicht wird.", zh: "根据当前余额和每月储蓄估算达到目标的时间。" },
    { tr: "Mevcut birikim, aylık katkı ve varsayımsal yıllık oranla en fazla 100 yıllık aylık simülasyon çalıştırır; hedef ayını, toplam katkıyı ve tahmini büyümeyi gösterir. Finansal tavsiye değildir.", en: "Runs a monthly simulation for up to 100 years from current savings, contributions, and an assumed annual rate, reporting target month, contributions, and estimated growth. It is not financial advice.", de: "Simuliert bis zu 100 Jahre und meldet Zielmonat, Beiträge und geschätztes Wachstum; keine Finanzberatung.", zh: "基于当前储蓄、月投入和假设年利率进行最长 100 年月度模拟，并报告目标月份、投入和估算增长；不构成财务建议。" },
    { tr: ["Acil durum fonu planı", "Satın alma hedefi", "Katkı senaryosu karşılaştırma"], en: ["Emergency-fund planning", "Purchase goals", "Contribution scenario comparison"] },
    { tr: ["Hedef, mevcut tutar, katkı ve oranı girin.", "Aylık hedef simülasyonunu çalıştırın.", "Enflasyon ve gelir belirsizliği için farklı senaryolar deneyin."], en: ["Enter target, current amount, contribution, and rate.", "Run the monthly target simulation.", "Try multiple scenarios for inflation and income uncertainty."] },
  ),
  defineTool(
    "yakit-maliyeti-hesaplayici", "calculation", "130",
    { tr: "Yakıt Maliyeti Hesaplayıcı", en: "Fuel Cost Calculator", de: "Kraftstoffkostenrechner", zh: "燃油成本计算器" },
    { tr: "Mesafe, tüketim, fiyat ve yolculuk sayısından yakıt maliyetini hesaplayın.", en: "Calculate fuel use and cost from distance, efficiency, price, and trip count.", de: "Berechnen Sie Verbrauch und Kosten aus Strecke, Verbrauch, Preis und Fahrten.", zh: "根据距离、油耗、价格和行程次数计算燃油用量与成本。" },
    { tr: "Kilometre, L/100 km, litre fiyatı ve yolculuk sayısını açık formülle çarpar; toplam litre, maliyet ve kilometre başı maliyeti gösterir. Trafik, yük, sıcaklık ve gerçek araç ölçümü sonucu değiştirebilir.", en: "Applies a transparent formula to distance, L/100 km, price per liter, and trip count, showing liters, total cost, and cost per kilometer. Traffic, load, temperature, and real vehicle data can change results.", de: "Berechnet Liter, Gesamtkosten und Kosten pro Kilometer aus Strecke, L/100 km, Preis und Fahrten; reale Bedingungen können abweichen.", zh: "以透明公式根据公里数、L/100km、每升价格和行程次数计算总升数、成本及每公里成本；实际路况会影响结果。" },
    { tr: ["Seyahat bütçesi", "Araç gideri karşılaştırma", "İş yolculuğu ön hesabı"], en: ["Travel budgets", "Vehicle cost comparisons", "Business-trip estimates"] },
    { tr: ["Mesafe, tüketim, fiyat ve sefer sayısını girin.", "Yakıt ve maliyet hesabını çalıştırın.", "Gerçek tüketim ve yol ücretlerini ayrıca ekleyin."], en: ["Enter distance, consumption, price, and trips.", "Calculate fuel and cost.", "Add actual efficiency and road charges separately."] },
  ),
  defineTool(
    "tempo-hiz-donusturucu", "calculation", "131",
    { tr: "Tempo ve Hız Dönüştürücü", en: "Pace & Speed Converter", de: "Tempo- und Geschwindigkeitsrechner", zh: "配速与速度转换器" },
    { tr: "Mesafe ve süreden km/mil temposu ile ortalama hızı çıkarın.", en: "Derive kilometer/mile pace and average speed from distance and time.", de: "Berechnen Sie Kilometer-/Meilentempo und Durchschnittsgeschwindigkeit.", zh: "根据距离和时间计算公里/英里配速与平均速度。" },
    { tr: "Kilometre ve HH:MM:SS süresinden saniye/km, dakika/km, dakika/mil ve km/saat değerlerini kesin birim dönüşümleriyle hesaplar. GPS hatası, mola ve parkur eğimini yorumlamaz.", en: "Calculates seconds per kilometer, minutes per kilometer, minutes per mile, and km/h from kilometers and HH:MM:SS using explicit conversions. It does not interpret GPS error, pauses, or terrain.", de: "Berechnet aus Distanz und HH:MM:SS Tempo pro Kilometer/Meile sowie km/h; GPS-Fehler, Pausen und Gelände bleiben unberücksichtigt.", zh: "根据公里数和 HH:MM:SS 计算每公里/英里配速及 km/h；不解释 GPS 误差、暂停或地形。" },
    { tr: ["Koşu tempo planı", "Bisiklet ortalama hızı", "Antrenman karşılaştırması"], en: ["Running pace plans", "Cycling average speed", "Workout comparisons"] },
    { tr: ["Mesafe ve toplam süreyi girin.", "Tempo ve hız dönüşümünü çalıştırın.", "Antrenman kararlarında sağlık durumunuzu ve gerçek ölçümü dikkate alın."], en: ["Enter distance and total time.", "Calculate pace and speed.", "Consider health context and real measurements for training decisions."] },
  ),
];
