import type { ToolGuidanceDetails } from "./tool-guidance";
import type { Locale } from "./site";

const l = (tr: string, en: string, de: string, zh: string): Record<Locale, string> => ({ tr, en, de, zh });

/** Operation-specific explanations, checked against the actual workbench.
 * Do not manufacture uniqueness by prefixing a category template with a title. */
export const reviewedToolGuidance: Record<string, ToolGuidanceDetails> = {
  "tarih-ekle-cikar-hesaplayici": {
    input: l("Başlangıç tarihini YYYY-MM-DD biçiminde girin; yıl, ay, gün ve Pazartesi–Cuma günü farklarını ayrı alanlara yazın. Kullanmadığınız farklar sıfırdır.", "Enter a YYYY-MM-DD starting date and separate offsets for years, months, days, and Monday–Friday days. Unused offsets are zero.", "Startdatum als YYYY-MM-DD und getrennte Abstände für Jahre, Monate, Tage und Montag–Freitag-Tage eingeben. Ungenutzte Abstände sind null.", "输入 YYYY-MM-DD 起始日期，并分别设置年、月、日及周一至周五的偏移。未使用的偏移为零。"),
    method: l("Hesap UTC takvim alanlarıyla yapılır. Önce yıl ve ay uygulanır; olmayan ay sonu günü son geçerli güne sınırlandırılır. Sonra takvim günleri, en son hafta sonlarını atlayan günler eklenir.", "Calculation uses UTC calendar fields. Years and months come first, with an unavailable month-end day clamped to the last valid day. Calendar days follow, then offsets that skip weekends.", "Berechnet wird mit UTC-Kalenderfeldern. Zuerst Jahre und Monate anwenden und einen fehlenden Monatstag auf den letzten gültigen Tag begrenzen. Danach Kalendertage, zuletzt Tage ohne Wochenenden addieren.", "使用 UTC 日历字段计算。先应用年和月，将不存在的月末日限制为最后一个有效日；再增加日历天数，最后增加跳过周末的天数。"),
    output: l("Sonuç bir takvim tarihidir. Rapor, uygulanan farkları ve ay taşması kuralını gösterir; saat veya saat dilimi dönüşümü üretmez.", "The result is a calendar date. The report lists applied offsets and the month-end rule; it does not produce a time or time-zone conversion.", "Das Ergebnis ist ein Kalenderdatum. Der Bericht zeigt angewendete Abstände und die Monatsendregel, keine Uhrzeit- oder Zeitzonenumrechnung.", "结果是日历日期。报告列出已应用的偏移和月末规则，不输出时刻或时区转换。"),
    verification: l("2024-01-31 üzerine bir ay ekleyin: 2024-02-29 beklenir. Ardından gün alanını 1 yapın: sonuç 2024-03-01 olmalıdır. 2023-02-29 gibi olmayan bir başlangıç tarihini reddetmelidir.", "Add one month to 2024-01-31: expect 2024-02-29. Then set days to 1: expect 2024-03-01. A nonexistent starting date such as 2023-02-29 must be rejected.", "Ein Monat nach 2024-01-31 muss 2024-02-29 ergeben. Mit Tage=1 folgt 2024-03-01. Ein ungültiges Startdatum wie 2023-02-29 muss abgewiesen werden.", "2024-01-31 加一个月应为 2024-02-29，再把日偏移设为 1，应为 2024-03-01。2023-02-29 等不存在的起始日期必须被拒绝。"),
    boundary: l("İş günü yalnız Pazartesi–Cuma anlamındadır; resmi tatiller ve kuruma özel takvimler dahil değildir. Kesirli farklar tam sayıya kesilir. Resmî süre veya sözleşme son günü için ilgili takvimi ayrıca kontrol edin.", "Business days mean Monday–Friday only, without holidays or organization-specific calendars. Fractional offsets are truncated to integers. Check the applicable calendar separately for official or contractual deadlines.", "Werktage bedeuten nur Montag bis Freitag, ohne Feiertage oder betriebliche Kalender. Bruchteile werden auf Ganzzahlen abgeschnitten. Für amtliche oder vertragliche Fristen den zuständigen Kalender gesondert prüfen.", "工作日仅指周一至周五，不含节假日或机构专用日历。小数偏移会截断为整数。正式或合同期限需另行核对适用日历。"),
  },
  "content-disposition-olusturucu": {
    input: l("İndirme davranışı için attachment veya inline seçin ve uzantısı dahil dosya adını yazın. Ham düzenlemede type ve filename anahtarlarını kullanın.", "Choose attachment or inline and enter a filename including its extension. Raw editing uses the type and filename keys.", "attachment oder inline wählen und einen Dateinamen mit Erweiterung eingeben. Die Roheingabe verwendet type und filename.", "选择 attachment 或 inline，并输入含扩展名的文件名。原始编辑使用 type 和 filename 键。"),
    method: l("Ad, ASCII yedeği için sadeleştirilir; özgün Unicode ad ayrıca UTF-8 yüzde kodlamasıyla filename* alanına yazılır. Satır sonu ve sıfır karakterleri temizlenir.", "The name is simplified for an ASCII fallback; the original Unicode name is also percent-encoded as UTF-8 in filename*. Newline and null characters are removed.", "Für die ASCII-Ausweichform wird der Name vereinfacht; der ursprüngliche Unicode-Name wird zusätzlich als UTF-8-Prozentkodierung in filename* geschrieben. Zeilenenden und Nullzeichen werden entfernt.", "名称简化为 ASCII 回退形式，同时将原始 Unicode 名称用 UTF-8 百分号编码写入 filename*。换行和空字符会被移除。"),
    output: l("İlk satır HTTP yanıt başlığıdır; sonraki satırlar açıklamadır. Sunucu yapılandırmasına açıklama metnini eklemeyin. Araç dosya indirmez ve dosyanın içeriğini değiştirmez.", "The first line is an HTTP response header; later lines explain it. Do not include those notes in server configuration. The tool neither downloads a file nor changes its contents.", "Die erste Zeile ist ein HTTP-Antwort-Header; weitere Zeilen erläutern ihn. Diese Hinweise nicht in die Serverkonfiguration übernehmen. Das Werkzeug lädt keine Datei und verändert keine Dateiinhalte.", "第一行是 HTTP 响应标头，后续行是说明。请勿把说明加入服务器配置。工具不会下载文件或改变文件内容。"),
    verification: l("çay raporu.pdf için ASCII adın cay raporu.pdf, UTF-8 alanının %C3%A7ay%20raporu.pdf olduğunu kontrol edin. Başlığı kullanan gerçek yanıtta tarayıcının önerdiği kayıt adını da sınayın.", "For çay raporu.pdf, check the ASCII name cay raporu.pdf and UTF-8 value %C3%A7ay%20raporu.pdf. Also test the browser's suggested save name with the actual response using this header.", "Bei çay raporu.pdf die ASCII-Form cay raporu.pdf und den UTF-8-Wert %C3%A7ay%20raporu.pdf prüfen. Den vorgeschlagenen Speichernamen auch mit der tatsächlichen HTTP-Antwort testen.", "对于 çay raporu.pdf，检查 ASCII 名称为 cay raporu.pdf、UTF-8 值为 %C3%A7ay%20raporu.pdf，并在实际使用该标头的响应中测试浏览器建议的保存名称。"),
    boundary: l("Üretilen başlık bir dosya güvenliği denetimi değildir. Yol parçaları, izin verilen uzantılar, dosya adı çakışmaları ve istemci davranışı sunucu uygulamasında ayrıca ele alınmalıdır.", "A generated header is not a file-safety audit. The server application must separately handle path components, allowed extensions, filename collisions, and client behavior.", "Ein erzeugter Header ist keine Dateisicherheitsprüfung. Pfadbestandteile, erlaubte Erweiterungen, Namenskonflikte und Clientverhalten sind in der Serveranwendung separat zu behandeln.", "生成标头不等于文件安全审计。服务器应用仍需单独处理路径片段、允许的扩展名、名称冲突和客户端行为。"),
  },
  "json-bicimlendirici": {
    input: l("Bir JSON değeri yapıştırın: nesne, dizi, metin, sayı, boolean veya null. Anahtarlar çift tırnaklı olmalıdır; yorumlar ve son elemandan sonraki virgül JSON değildir.", "Paste one JSON value: an object, array, string, number, boolean, or null. Property names need double quotes; comments and trailing commas are not JSON.", "Fügen Sie einen JSON-Wert ein: Objekt, Array, String, Zahl, Boolean oder null. Eigenschaftsnamen benötigen doppelte Anführungszeichen; Kommentare und nachgestellte Kommas sind kein JSON.", "粘贴一个 JSON 值：对象、数组、字符串、数字、布尔值或 null。属性名必须使用双引号；注释和末尾多余逗号不属于 JSON。"),
    method: l("JSON.parse sözdizimini denetler; JSON.stringify iki boşluklu girintiyle veya küçültülmüş metin olarak yeniden yazar. Araç bozuk JSON'u tahmin ederek onarmaz.", "JSON.parse checks syntax; JSON.stringify writes two-space indentation or compact text. The formatter does not guess repairs for malformed JSON.", "JSON.parse prüft die Syntax; JSON.stringify schreibt mit zwei Leerzeichen Einrückung oder kompakt. Fehlerhaftes JSON wird nicht durch Vermutungen repariert.", "JSON.parse 检查语法，JSON.stringify 输出双空格缩进或紧凑文本。格式化工具不会猜测并修复损坏的 JSON。"),
    output: l("Biçimlendirilmiş JSON yanında kök türü, alan sayısı, en derin seviye ve UTF-8 çıktı baytı gösterilir. Alan sayısı dizi uzunluğuyla aynı ölçü değildir.", "The result includes formatted JSON, root type, key count, maximum depth, and UTF-8 output bytes. Key count is not the same measurement as array length.", "Neben dem formatierten JSON erscheinen Wurzeltyp, Schlüsselzahl, maximale Tiefe und UTF-8-Ausgabebytes. Schlüsselzahl und Arraylänge sind unterschiedliche Maße.", "结果包括格式化 JSON、根类型、字段数、最大深度和 UTF-8 输出字节数。字段数量不同于数组长度。"),
    verification: l('{"id":"007","active":false,"items":[]} örneğinde id metin, active boolean ve items boş dizi kalmalıdır. Küçültüp tekrar biçimlendirdiğinizde bu değerleri karşılaştırın.', 'With {"id":"007","active":false,"items":[]}, id must remain a string, active a boolean, and items an empty array. Compare these values after compacting and formatting again.', 'Bei {"id":"007","active":false,"items":[]} muss id ein String, active ein Boolean und items ein leeres Array bleiben. Vergleichen Sie die Werte nach Komprimierung und erneuter Formatierung.', '使用 {"id":"007","active":false,"items":[]} 时，id 应保留字符串类型，active 为布尔值，items 为空数组。压缩后再次格式化并核对这些值。'),
    boundary: l("JavaScript Number büyük tam sayılarda hassasiyet kaybedebilir; uzun kimlikleri tırnaklı metin olarak tutun. Yinelenen anahtarlar ayrıştırmada kaybolabilir. Bu araç JSON Schema doğrulaması yapmaz.", "JavaScript Number can lose precision for large integers; keep long identifiers as quoted strings. Duplicate keys can be lost during parsing. This tool does not validate a JSON Schema.", "JavaScript Number kann bei großen Ganzzahlen Präzision verlieren; lange Kennungen als Strings speichern. Doppelte Schlüssel können beim Parsen verloren gehen. Keine JSON-Schema-Validierung.", "JavaScript Number 可能丢失大整数精度；长标识符应使用字符串。重复键可能在解析时丢失。本工具不执行 JSON Schema 验证。"),
  },
  "jwt-decoder": {
    input: l("Noktayla ayrılmış header.payload.signature biçiminde bir JWT girin. Deneme için sentetik token kullanın; gerçek oturum tokenı sahibine erişim verebilir.", "Enter a JWT in dot-separated header.payload.signature form. Use a synthetic token for a trial; a real session token may grant access to its holder.", "Geben Sie ein JWT im Format header.payload.signature ein. Verwenden Sie zum Testen ein synthetisches Token; echte Sitzungstoken können Zugriff gewähren.", "输入以点分隔的 header.payload.signature 格式 JWT。测试时使用合成令牌；真实会话令牌可能赋予持有者访问权限。"),
    method: l("Header ve payload bölümleri Base64URL biçiminden çözülüp JSON olarak okunur. İmza için anahtar alınmaz; içerik güvenilir kabul edilmez.", "Header and payload segments are decoded from Base64URL and parsed as JSON. No signature key is supplied, and decoded claims are not treated as trusted.", "Header und Payload werden aus Base64URL dekodiert und als JSON gelesen. Ein Signaturschlüssel wird nicht verwendet; Claims gelten nicht als vertrauenswürdig.", "将 header 和 payload 从 Base64URL 解码并解析为 JSON。不提供签名密钥，也不会将解码后的声明视为可信。"),
    output: l("Header ve payload alanları okunabilir görünür. alg bir algoritma beyanıdır; sub, iss, aud ve exp tokenı üreten tarafın iddialarıdır, doğrulama sonucu değildir.", "Header and payload fields become readable. alg declares an algorithm; sub, iss, aud, and exp are claims made by the issuer, not verification results.", "Header- und Payload-Felder werden lesbar. alg nennt einen Algorithmus; sub, iss, aud und exp sind Angaben des Ausstellers, keine Prüfergebnisse.", "显示可读的 header 和 payload 字段。alg 是算法声明；sub、iss、aud、exp 是签发方声明，并非验证结果。"),
    verification: l("Sentetik payload içindeki kullanıcı kimliğini ve süre alanını beklenen değerle karşılaştırın. exp saniye cinsindendir; milisaniye olarak yorumlamak yanlış tarih üretir.", "Compare a synthetic payload's user identifier and expiry with known values. exp uses seconds; interpreting it as milliseconds produces the wrong date.", "Vergleichen Sie Benutzerkennung und Ablaufzeit eines synthetischen Payloads mit bekannten Werten. exp verwendet Sekunden; eine Interpretation als Millisekunden liefert das falsche Datum.", "将合成 payload 的用户标识和过期时间与已知值比较。exp 使用秒；将其当作毫秒会得到错误日期。"),
    boundary: l("Çözümleme imzayı, issuer/audience koşullarını veya yetkiyi doğrulamaz. Gerçek kimlik doğrulamada sunucu doğru anahtar ve izin verilen algoritmayla imzayı denetlemelidir; gerçek tokenları paylaşmayın.", "Decoding does not validate a signature, issuer, audience, or authorization. Authentication requires server-side verification with the correct key and allowed algorithm; do not share live tokens.", "Dekodieren prüft weder Signatur noch Aussteller, Zielgruppe oder Berechtigung. Authentifizierung erfordert serverseitige Prüfung mit richtigem Schlüssel und erlaubtem Algorithmus; echte Token nicht teilen.", "解码不会验证签名、签发者、受众或权限。身份验证需要服务器使用正确密钥和允许的算法检查签名；不要分享真实令牌。"),
  },
  "guclu-parola-uretici": {
    input: l("Mevcut parolanızı girmeyin; üretilecek parolanın uzunluğunu 12–128 karakter arasında seçin. Hedef hizmetin kabul ettiği uzunluğu önceden kontrol edin.", "Do not enter an existing password; choose a generated length between 12 and 128 characters. Check the destination service's accepted length first.", "Geben Sie kein bestehendes Passwort ein; wählen Sie eine Länge von 12 bis 128 Zeichen. Prüfen Sie vorher die Längenregeln des Zieldienstes.", "无需输入已有密码；选择 12 至 128 个字符的生成长度。请先确认目标服务允许的长度。"),
    method: l("Yeni karakterler Web Crypto rastgelelik kaynağıyla seçilir. Aynı ayarlarla yeniden üretmek yeni bir parola vermelidir; bu işlem deterministik bir metin dönüştürme değildir.", "Characters are selected using Web Crypto randomness. Generating again with the same settings should produce a new password; this is not a deterministic text transformation.", "Zeichen werden mit Web-Crypto-Zufall ausgewählt. Eine erneute Generierung bei gleichen Einstellungen soll ein neues Passwort liefern; dies ist keine deterministische Textumwandlung.", "使用 Web Crypto 随机源选择字符。相同设置再次生成应得到新密码；这不是确定性的文本转换。"),
    output: l("Seçilen uzunlukta kopyalanabilir parola üretilir. Bu değer bir hesap oluşturmaz, parolayı bir hizmete kaydetmez ve kendi başına iki aşamalı doğrulama sağlamaz.", "The output is a copyable password of the chosen length. It does not create an account, save a password to a service, or provide two-factor authentication.", "Die Ausgabe ist ein kopierbares Passwort der gewählten Länge. Sie erstellt kein Konto, speichert kein Passwort bei einem Dienst und bietet keine Zwei-Faktor-Authentifizierung.", "输出为选定长度的可复制密码。它不会创建账户、向服务保存密码，也不能代替双重验证。"),
    verification: l("Uzunluğu kontrol edin, ikinci bir üretimde değerin değiştiğini görün ve hedef hizmetin karakter kurallarını doğrulayın. Gerçek parolayı örnek veya ekran görüntüsünde yayımlamayın.", "Check the length, confirm a second generation changes the value, and verify the destination's character rules. Never publish a real password in a sample or screenshot.", "Prüfen Sie Länge, einen neuen Wert bei erneuter Generierung und die Zeichenregeln des Zieldienstes. Echte Passwörter nicht in Beispielen oder Screenshots veröffentlichen.", "核对长度，确认第二次生成的值不同，并检查目标服务的字符规则。不要在示例或截图中公布真实密码。"),
    boundary: l("Güçlü rastgelelik hesap güvenliğini tek başına garanti etmez. Her hesapta ayrı parola ve parola yöneticisi kullanın; paylaşılan bilgisayarda pano geçmişi veya eklentiler çıktıyı görebilir.", "Strong randomness alone does not guarantee account security. Use a different password per account and a password manager; clipboard history or extensions on shared devices may expose output.", "Gute Zufallswerte allein garantieren keine Kontosicherheit. Nutzen Sie pro Konto ein eigenes Passwort und einen Passwortmanager; Zwischenablageverlauf oder Erweiterungen können die Ausgabe offenlegen.", "强随机性不能单独保证账户安全。每个账户使用不同密码并配合密码管理器；共享设备的剪贴板历史或扩展程序可能暴露输出。"),
  },
  "pdf-birlestirme": {
    input: l("Birleştirilecek yerel PDF dosyalarını seçin ve sıralarını belirleyin. Önce iki küçük örnek dosyayla deneyin; şifre korumalı veya bozuk dosyalar açılamayabilir.", "Select local PDF files and arrange their order. Start with two small sample documents; encrypted or damaged files may not open.", "Wählen Sie lokale PDF-Dateien und legen Sie deren Reihenfolge fest. Beginnen Sie mit zwei kleinen Beispieldateien; verschlüsselte oder beschädigte Dateien lassen sich eventuell nicht öffnen.", "选择本地 PDF 并设置顺序。先用两个小型示例文件测试；加密或损坏的文件可能无法打开。"),
    method: l("pdf-lib seçilen dosyaların sayfalarını sırayla yeni bir PDF belgesine kopyalar. Kaynak dosyaların üzerine yazılmaz; metin tanıma veya içerik özeti yapılmaz.", "pdf-lib copies pages from the selected files into a new PDF in order. Source files are not overwritten; the operation does not perform OCR or summarize content.", "pdf-lib kopiert die Seiten der ausgewählten Dateien der Reihe nach in ein neues PDF. Quelldateien bleiben erhalten; weder OCR noch Inhaltszusammenfassung werden durchgeführt.", "pdf-lib 按顺序将选中文件的页面复制到新 PDF。不会覆盖源文件，也不会执行 OCR 或总结内容。"),
    output: l("İndirilebilir birleştirilmiş PDF elde edilir. Örneğin iki sayfalık A ve üç sayfalık B dosyası A→B sırasıyla beş sayfalık bir belge oluşturmalıdır.", "The result is a downloadable merged PDF. A two-page file A followed by a three-page file B should yield a five-page document in A→B order.", "Das Ergebnis ist ein zusammengeführtes PDF zum Herunterladen. Eine zweiseitige Datei A und danach eine dreiseitige Datei B sollen fünf Seiten in der Reihenfolge A→B ergeben.", "结果为可下载的合并 PDF。两页文件 A 后接三页文件 B，应生成按 A→B 排列的五页文档。"),
    verification: l("İndirilen dosyayı PDF okuyucuda açın; toplam sayfa sayısını, ilk/son sayfayı ve dosyaların birleşme noktasını kontrol edin. İmza veya form içeren belgelerde işlevleri ayrıca deneyin.", "Open the download in a PDF reader; check total pages, first and last pages, and the boundary between files. Test any forms or signatures separately.", "Öffnen Sie den Download in einem PDF-Reader; prüfen Sie Seitenzahl, erste und letzte Seite sowie Übergänge. Formulare oder Signaturen separat testen.", "在 PDF 阅读器中打开下载文件，检查总页数、首页、末页以及文件衔接处。另行测试表单和签名。"),
    boundary: l("Sayfa kopyalama dijital imzaları, yer imlerini veya etkileşimli formları koruma garantisi vermez. Büyük dosyalar tarayıcı belleğini tüketebilir; asılları saklayın.", "Page copying does not guarantee preservation of digital signatures, bookmarks, or interactive forms. Large files may exhaust browser memory; retain originals.", "Seitenkopieren garantiert nicht den Erhalt digitaler Signaturen, Lesezeichen oder interaktiver Formulare. Große Dateien können den Browserspeicher erschöpfen; Originale behalten.", "复制页面不保证保留数字签名、书签或交互表单。大型文件可能耗尽浏览器内存，请保留原件。"),
  },
};
export const reviewedToolSlugs = Object.freeze(Object.keys(reviewedToolGuidance));
