import type { ToolGuidanceDetails } from "./tool-guidance";
import type { Locale } from "./site";

const l = (tr: string, en: string, de: string, zh: string): Record<Locale, string> => ({ tr, en, de, zh });

/** Operation-specific explanations, checked against the actual workbench.
 * Do not manufacture uniqueness by prefixing a category template with a title. */
export const reviewedToolGuidance: Record<string, ToolGuidanceDetails> = {
  "json-bicimlendirici": {
    input: l("Bir JSON değeri yapıştırın: nesne, dizi, metin, sayı, boolean veya null. Anahtarlar çift tırnaklı olmalıdır; yorumlar ve son elemandan sonraki virgül JSON değildir.", "Paste one JSON value: an object, array, string, number, boolean, or null. Property names need double quotes; comments and trailing commas are not JSON.", "Fügen Sie einen JSON-Wert ein: Objekt, Array, String, Zahl, Boolean oder null. Eigenschaftsnamen benötigen doppelte Anführungszeichen; Kommentare und nachgestellte Kommas sind kein JSON.", "粘贴一个 JSON 值：对象、数组、字符串、数字、布尔值或 null。属性名必须使用双引号；注释和末尾多余逗号不属于 JSON。"),
    method: l("JSON.parse sözdizimini denetler; JSON.stringify iki boşluklu girintiyle veya küçültülmüş metin olarak yeniden yazar. Araç bozuk JSON'u tahmin ederek onarmaz.", "JSON.parse checks syntax; JSON.stringify writes two-space indentation or compact text. The formatter does not guess repairs for malformed JSON.", "JSON.parse prüft die Syntax; JSON.stringify schreibt mit zwei Leerzeichen Einrückung oder kompakt. Fehlerhaftes JSON wird nicht durch Vermutungen repariert.", "JSON.parse 检查语法，JSON.stringify 输出双空格缩进或紧凑文本。格式化工具不会猜测并修复损坏的 JSON。"),
    output: l("Biçimlendirilmiş JSON yanında kök türü, alan sayısı, en derin seviye ve UTF-8 çıktı baytı gösterilir. Alan sayısı dizi uzunluğuyla aynı ölçü değildir.", "The result includes formatted JSON, root type, key count, maximum depth, and UTF-8 output bytes. Key count is not the same measurement as array length.", "Neben dem formatierten JSON erscheinen Wurzeltyp, Schlüsselzahl, maximale Tiefe und UTF-8-Ausgabebytes. Schlüsselzahl und Arraylänge sind unterschiedliche Maße.", "结果包括格式化 JSON、根类型、字段数、最大深度和 UTF-8 输出字节数。字段数量不同于数组长度。"),
    verification: l('{"id":"007","active":false,"items":[]} örneğinde id metin, active boolean ve items boş dizi kalmalıdır. Küçültüp tekrar biçimlendirdiğinizde bu değerleri karşılaştırın.', 'With {"id":"007","active":false,"items":[]}, id must remain a string, active a boolean, and items an empty array. Compare these values after compacting and formatting again.', 'Bei {"id":"007","active":false,"items":[]} muss id ein String, active ein Boolean und items ein leeres Array bleiben. Vergleichen Sie die Werte nach Komprimierung und erneuter Formatierung.', '使用 {"id":"007","active":false,"items":[]} 时，id 应保留字符串类型，active 为布尔值，items 为空数组。压缩后再次格式化并核对这些值。'),
    boundary: l("JavaScript Number büyük tam sayılarda hassasiyet kaybedebilir; uzun kimlikleri tırnaklı metin olarak tutun. Yinelenen anahtarlar ayrıştırmada kaybolabilir. Bu araç JSON Schema doğrulaması yapmaz.", "JavaScript Number can lose precision for large integers; keep long identifiers as quoted strings. Duplicate keys can be lost during parsing. This tool does not validate a JSON Schema.", "JavaScript Number kann bei großen Ganzzahlen Präzision verlieren; lange Kennungen als Strings speichern. Doppelte Schlüssel können beim Parsen verloren gehen. Keine JSON-Schema-Validierung.", "JavaScript Number 可能丢失大整数精度；长标识符应使用字符串。重复键可能在解析时丢失。本工具不执行 JSON Schema 验证。"),
  },
  "jwt-decoder": {
    input: l("Noktayla ayrılmış header.payload.signature biçiminde bir JWT girin. Deneme için sentetik token kullanın; gerçek oturum tokenı sahibine erişim verebilir.", "Enter a JWT in dot-separated header.payload.signature form. Use a synthetic token for a trial; a real session token may grant access to its holder.", "Geben Sie ein JWT im Format header.payload.signature ein. Verwenden Sie zum Testen ein synthetisches Token; echte Sitzungstoken können Zugriff gewähren.", "输入以点分隔的 header.payload.signature 格式 JWT。测试时使用合成令牌；真实会话令牌可能赋予持有者访问权限。"),
    method: l("Header ve payload bölümleri Base64URL biçiminden çözülüp JSON olarak okunur. İmza için anahtar alınmaz; içerik güvenilir kabul edilmez.", "Header and payload segments are decoded from Base64URL and parsed as JSON. No signature key is supplied, and decoded claims are not treated as trusted.", "Header und Payload werden aus Base64URL dekodiert und als JSON gelesen. Ein Signaturschlüssel wird nicht verwendet; Claims gelten nicht als vertrauenswürdig.", "将 header 和 payload 从 Base64URL 解码并解析为 JSON。不提供签名密钥，也不会将解码后的声明视为可信。"),
    output: l("Header ve payload alanları okunabilir görünür. alg bir algoritma beyanıdır; sub, iss, aud ve exp tokenı üreten tarafın iddialarıdır, doğrulama sonucu değildir.", "Header and payload fields become readable. alg declares an algorithm; sub, iss, aud, and exp are claims made by the issuer, not verification results.", "Header- und Payload-Felder werden lesbar. alg nennt einen Algorithmus; sub, iss, aud und exp sind Angaben des Ausstellers, keine Prüfergebnisse.", "显示可读的 header 和 payload 字段。alg 是算法声明；sub、iss、aud、exp 是签发方声明，并非验证结果。"),
    verification: l("Sentetik payload içindeki kullanıcı kimliğini ve süre alanını beklenen değerle karşılaştırın. exp saniye cinsindendir; milisaniye olarak yorumlamak yanlış tarih üretir.", "Compare a synthetic payload's user identifier and expiry with known values. exp uses seconds; interpreting it as milliseconds produces the wrong date.", "Vergleichen Sie Benutzerkennung und Ablaufzeit eines synthetischen Payloads mit bekannten Werten. exp verwendet Sekunden; eine Interpretation als Millisekunden liefert das falsche Datum.", "将合成 payload 的用户标识和过期时间与已知值比较。exp 使用秒；将其当作毫秒会得到错误日期。"),
    boundary: l("Çözümleme imzayı, issuer/audience koşullarını veya yetkiyi doğrulamaz. Gerçek kimlik doğrulamada sunucu doğru anahtar ve izin verilen algoritmayla imzayı denetlemelidir; gerçek tokenları paylaşmayın.", "Decoding does not validate a signature, issuer, audience, or authorization. Authentication requires server-side verification with the correct key and allowed algorithm; do not share live tokens.", "Dekodieren prüft weder Signatur noch Aussteller, Zielgruppe oder Berechtigung. Authentifizierung erfordert serverseitige Prüfung mit richtigem Schlüssel und erlaubtem Algorithmus; echte Token nicht teilen.", "解码不会验证签名、签发者、受众或权限。身份验证需要服务器使用正确密钥和允许的算法检查签名；不要分享真实令牌。"),
  },
  "guclu-parola-uretici": {
    input: l("Mevcut parolanızı girmeyin; üretilecek parolanın uzunluğunu 12–128 karakter arasında seçin. Hedef hizmetin kabul ettiği uzunluğu önceden kontrol edin.", "Do not enter an existing password; choose a generated length between 12 and 128 characters. Check the destination service's accepted length first.", "Geben Sie kein bestehendes Passwort ein; wählen Sie eine Länge von 12 bis 128 Zeichen. Prüfen Sie vorher die Längenregeln des Zieldienstes.", "无需输入已有密码；选择 12 至 128 个字符的生成长度。请先确认目标服务允许的长度。"),
    method: l("Yeni karakterler Web Crypto rastgelelik kaynağıyla seçilir. Aynı ayarlarla yeniden üretmek yeni bir parola vermelidir; bu işlem deterministik bir metin dönüştürme değildir.", "Characters are selected using Web Crypto randomness. Generating again with the same settings should produce a new password; this is not a deterministic text transformation.", "Zeichen werden mit Web-Crypto-Zufall ausgewählt. Eine erneute Generierung bei gleichen Einstellungen soll ein neues Passwort liefern; dies ist keine deterministische Textumwandlung.", "使用 Web Crypto 随机源选择字符。相同设置再次生成应得到新密码；这不是确定性的文本转换。"),
    output: l("Seçilen uzunlukta kopyalanabilir parola üretilir. Bu değer bir hesap oluşturmaz, parolayı bir hizmete kaydetmez ve kendi başına iki aşamalı doğrulama sağlamaz.", "The output is a copyable password of the chosen length. It does not create an account, save a password to a service, or provide two-factor authentication.", "Die Ausgabe ist ein kopierbares Passwort der gewählten Länge. Sie erstellt kein Konto, speichert kein Passwort bei einem Dienst und bietet keine Zwei-Faktor-Authentifizierung.", "输出为选定长度的可复制密码。它不会创建账户、向服务保存密码，也不能代替双重验证。"),
    verification: l("Uzunluğu kontrol edin, ikinci bir üretimde değerin değiştiğini görün ve hedef hizmetin karakter kurallarını doğrulayın. Gerçek parolayı örnek veya ekran görüntüsünde yayımlamayın.", "Check the length, confirm a second generation changes the value, and verify the destination's character rules. Never publish a real password in a sample or screenshot.", "Prüfen Sie Länge, einen neuen Wert bei erneuter Generierung und die Zeichenregeln des Zieldienstes. Echte Passwörter nicht in Beispielen oder Screenshots veröffentlichen.", "核对长度，确认第二次生成的值不同，并检查目标服务的字符规则。不要在示例或截图中公布真实密码。"),
    boundary: l("Güçlü rastgelelik hesap güvenliğini tek başına garanti etmez. Her hesapta ayrı parola ve parola yöneticisi kullanın; paylaşılan bilgisayarda pano geçmişi veya eklentiler çıktıyı görebilir.", "Strong randomness alone does not guarantee account security. Use a different password per account and a password manager; clipboard history or extensions on shared devices may expose output.", "Gute Zufallswerte allein garantieren keine Kontosicherheit. Nutzen Sie pro Konto ein eigenes Passwort und einen Passwortmanager; Zwischenablageverlauf oder Erweiterungen können die Ausgabe offenlegen.", "强随机性不能单独保证账户安全。每个账户使用不同密码并配合密码管理器；共享设备的剪贴板历史或扩展程序可能暴露输出。"),
  },
  "pdf-birlestirme": {
    input: l("Birleştirilecek yerel PDF dosyalarını seçin ve sıralarını belirleyin. Önce iki küçük örnek dosyayla deneyin; şifre korumalı veya bozuk dosyalar açılamayabilir.", "Select local PDF files and arrange their order. Start with two small sample documents; encrypted or damaged files may not open.", "Wählen Sie lokale PDF-Dateien und legen Sie deren Reihenfolge fest. Beginnen Sie mit zwei kleinen Beispieldateien; verschlüsselte oder beschädigte Dateien lassen sich eventuell nicht öffnen.", "选择本地 PDF 并设置顺序。先用两个小型示例文件测试；加密或损坏的文件可能无法打开。"),
    method: l("pdf-lib seçilen dosyaların sayfalarını sırayla yeni bir PDF belgesine kopyalar. Kaynak dosyaların üzerine yazılmaz; metin tanıma veya içerik özeti yapılmaz.", "pdf-lib copies pages from the selected files into a new PDF in order. Source files are not overwritten; the operation does not perform OCR or summarize content.", "pdf-lib kopiert die Seiten der ausgewählten Dateien der Reihe nach in ein neues PDF. Quelldateien bleiben erhalten; weder OCR noch Inhaltszusammenfassung werden durchgeführt.", "pdf-lib 按顺序将选中文件的页面复制到新 PDF。不会覆盖源文件，也不会执行 OCR 或总结内容。"),
    output: l("İndirilebilir birleştirilmiş PDF elde edilir. Örneğin iki sayfalık A ve üç sayfalık B dosyası A→B sırasıyla beş sayfalık bir belge oluşturmalıdır.", "The result is a downloadable merged PDF. A two-page file A followed by a three-page file B should yield a five-page document in A→B order.", "Das Ergebnis ist ein zusammengeführtes PDF zum Herunterladen. Eine zweiseitige Datei A und danach eine dreiseitige Datei B sollen fünf Seiten in der Reihenfolge A→B ergeben.", "结果为可下载的合并 PDF。两页文件 A 后接三页文件 B，应生成按 A→B 排列的五页文档。"),
    verification: l("İndirilen dosyayı PDF okuyucuda açın; toplam sayfa sayısını, ilk/son sayfayı ve dosyaların birleşme noktasını kontrol edin. İmza veya form içeren belgelerde işlevleri ayrıca deneyin.", "Open the download in a PDF reader; check total pages, first and last pages, and the boundary between files. Test any forms or signatures separately.", "Öffnen Sie den Download in einem PDF-Reader; prüfen Sie Seitenzahl, erste und letzte Seite sowie Übergänge. Formulare oder Signaturen separat testen.", "在 PDF 阅读器中打开下载文件，检查总页数、首页、末页以及文件衔接处。另行测试表单和签名。"),
    boundary: l("Sayfa kopyalama dijital imzaları, yer imlerini veya etkileşimli formları koruma garantisi vermez. Büyük dosyalar tarayıcı belleğini tüketebilir; asılları saklayın.", "Page copying does not guarantee preservation of digital signatures, bookmarks, or interactive forms. Large files may exhaust browser memory; retain originals.", "Seitenkopieren garantiert nicht den Erhalt digitaler Signaturen, Lesezeichen oder interaktiver Formulare. Große Dateien können den Browserspeicher erschöpfen; Originale behalten.", "复制页面不保证保留数字签名、书签或交互表单。大型文件可能耗尽浏览器内存，请保留原件。"),
  },
};
export const reviewedToolSlugs = Object.freeze(Object.keys(reviewedToolGuidance));
