import type { BaseTool } from "./tool-locales";

type Copy = { tr: string; en: string; de: string; zh: string };
type Spec = { slug: string; category: BaseTool["category"]; mark: string; title: Copy; short: Copy; purpose: Copy; uses: Record<keyof Copy, string[]>; steps: Record<keyof Copy, string[]> };

const specs: Spec[] = [
  {
    slug: "json-schema-geriye-uyumluluk-denetleyici", category: "data", mark: "322",
    title: { tr: "JSON Schema Geriye Uyumluluk Denetleyici", en: "JSON Schema Backward Compatibility Checker", de: "JSON-Schema-Kompatibilitätsprüfung", zh: "JSON Schema 向后兼容检查器" },
    short: { tr: "İki JSON Schema sürümünde tüketicileri bozabilecek değişiklikleri yapısal olarak bulun.", en: "Find structural changes between two JSON Schema versions that may break consumers.", de: "Findet strukturelle Änderungen zwischen zwei JSON-Schema-Versionen, die Verbraucher brechen können.", zh: "查找两个 JSON Schema 版本之间可能破坏消费者的结构变化。" },
    purpose: { tr: "Eski ve yeni şemayı; silinen alan, yeni zorunluluk, tür daraltma ve enum daraltma bakımından karşılaştırır. Sonuç bir sözleşme ön kontrolüdür; gerçek tüketici testinin yerini almaz.", en: "Compares old and new schemas for removed fields, new requirements, type narrowing, and enum narrowing. It is a contract pre-check, not a substitute for consumer tests.", de: "Vergleicht alte und neue Schemas auf entfernte Felder, neue Pflichtfelder sowie Typ- und Enum-Einschränkungen. Die Prüfung ersetzt keine Verbrauchertests.", zh: "比较新旧 Schema 中删除的字段、新增必填项、类型收窄和枚举收窄。它是契约预检，不能替代消费者测试。" },
    uses: { tr: ["API sürüm incelemesi", "Veri sözleşmesi değişiklik kaydı", "CI öncesi yerel kontrol"], en: ["API version review", "Data-contract change log", "Local pre-CI review"], de: ["API-Versionsprüfung", "Änderungsprotokoll für Datenverträge", "Lokale Prüfung vor CI"], zh: ["API 版本审查", "数据契约变更记录", "CI 前本地检查"] },
    steps: { tr: ["Eski şemayı ilk alana, yeni şemayı ikinci alana yapıştırın.", "Yapısal karşılaştırmayı çalıştırın.", "Her bulguyu gerçek örnekler ve tüketici testleriyle doğrulayın."], en: ["Paste the old schema first and the new schema second.", "Run the structural comparison.", "Verify every finding with real fixtures and consumer tests."], de: ["Altes Schema zuerst, neues Schema danach einfügen.", "Strukturvergleich ausführen.", "Jeden Befund mit Fixtures und Verbrauchertests prüfen."], zh: ["先粘贴旧 Schema，再粘贴新 Schema。", "运行结构比较。", "使用真实样例和消费者测试核验每项发现。"] },
  },
  {
    slug: "openapi-kirilma-degisikligi-denetleyici", category: "data", mark: "323",
    title: { tr: "OpenAPI Kırılma Değişikliği Denetleyici", en: "OpenAPI Breaking Change Checker", de: "OpenAPI-Breaking-Change-Prüfung", zh: "OpenAPI 破坏性变更检查器" },
    short: { tr: "İki OpenAPI JSON belgesinde kaldırılan yol, yöntem, parametre ve yanıtları raporlayın.", en: "Report removed paths, methods, parameters, and responses across two OpenAPI JSON documents.", de: "Meldet entfernte Pfade, Methoden, Parameter und Antworten in zwei OpenAPI-JSON-Dokumenten.", zh: "报告两个 OpenAPI JSON 文档中被删除的路径、方法、参数和响应。" },
    purpose: { tr: "Sözleşmenin eski ve yeni JSON sürümünü karşılaştırarak belirgin istemci kırılmalarını sınıflandırır; referans çözümleme ve davranışsal uyumluluk ayrıca sınanmalıdır.", en: "Classifies clear client-breaking changes between old and new JSON contracts; reference resolution and behavioral compatibility still require dedicated tests.", de: "Klassifiziert offensichtliche Client-Brüche zwischen alten und neuen JSON-Verträgen; Referenzen und Verhalten müssen separat getestet werden.", zh: "对新旧 JSON 契约之间明显的客户端破坏性变更进行分类；引用解析和行为兼容性仍需专项测试。" },
    uses: { tr: ["API yayın kapısı", "SDK uyumluluk incelemesi", "Sürüm notu hazırlama"], en: ["API release gate", "SDK compatibility review", "Release-note preparation"], de: ["API-Release-Gate", "SDK-Kompatibilitätsprüfung", "Release-Notes vorbereiten"], zh: ["API 发布门禁", "SDK 兼容性审查", "发布说明准备"] },
    steps: { tr: ["Eski ve yeni OpenAPI JSON belgelerini ekleyin.", "Kırılma adaylarını üretin.", "Sunucu davranışı, örnek istek ve SDK testleriyle kararı doğrulayın."], en: ["Add the old and new OpenAPI JSON documents.", "Generate breaking-change candidates.", "Confirm with server behavior, request fixtures, and SDK tests."], de: ["Altes und neues OpenAPI-JSON einfügen.", "Bruchkandidaten erzeugen.", "Mit Serververhalten, Requests und SDK-Tests bestätigen."], zh: ["添加旧版和新版 OpenAPI JSON。", "生成破坏性变更候选项。", "通过服务器行为、请求样例和 SDK 测试确认。"] },
  },
  {
    slug: "markdown-baglanti-butunluk-denetleyici", category: "text", mark: "324",
    title: { tr: "Markdown Bağlantı Bütünlüğü Denetleyici", en: "Markdown Link Integrity Checker", de: "Markdown-Linkintegritätsprüfung", zh: "Markdown 链接完整性检查器" },
    short: { tr: "Markdown içindeki bozuk referansları, güvensiz şemaları ve yinelenen tanımları ağ isteği olmadan bulun.", en: "Find broken references, unsafe schemes, and duplicate definitions in Markdown without network requests.", de: "Findet defekte Referenzen, unsichere Schemata und doppelte Definitionen ohne Netzwerkanfrage.", zh: "无需网络请求即可查找 Markdown 中的断开引用、不安全协议和重复定义。" },
    purpose: { tr: "Satır içi ve referans bağlantılarını ayrıştırır; tanımsız kimlikleri, javascript/data şemalarını ve yinelenen referansları gösterir. Uzak URL'nin gerçekten açıldığını iddia etmez.", en: "Parses inline and reference links, reporting undefined identifiers, javascript/data schemes, and duplicate definitions. It does not claim that remote URLs are reachable.", de: "Analysiert Inline- und Referenzlinks, meldet undefinierte IDs, javascript/data-Schemata und doppelte Definitionen. Externe Erreichbarkeit wird nicht behauptet.", zh: "解析行内链接和引用链接，报告未定义标识、javascript/data 协议和重复定义；不声称远程 URL 可访问。" },
    uses: { tr: ["README yayın kontrolü", "Belge taşıma incelemesi", "Güvenli bağlantı ön taraması"], en: ["README release review", "Documentation migration review", "Safe-link pre-scan"], de: ["README-Veröffentlichungsprüfung", "Dokumentationsmigration", "Sicherer Link-Vorscan"], zh: ["README 发布检查", "文档迁移审查", "安全链接预扫描"] },
    steps: { tr: ["Markdown kaynağını yapıştırın.", "Yerel bağlantı denetimini çalıştırın.", "Uzak hedefleri yayın ortamında ayrıca doğrulayın."], en: ["Paste the Markdown source.", "Run the local link review.", "Verify remote destinations separately in the publishing environment."], de: ["Markdown-Quelle einfügen.", "Lokale Linkprüfung ausführen.", "Externe Ziele in der Veröffentlichungsumgebung prüfen."], zh: ["粘贴 Markdown 源文。", "运行本地链接检查。", "在发布环境中另行验证远程目标。"] },
  },
  {
    slug: "csv-eksik-veri-deseni-analizoru", category: "data", mark: "325",
    title: { tr: "CSV Eksik Veri Deseni Analizörü", en: "CSV Missing-Data Pattern Analyzer", de: "CSV-Fehlwertmuster-Analyse", zh: "CSV 缺失数据模式分析器" },
    short: { tr: "Boş değerleri yalnızca saymak yerine sütun ve satır örüntülerini birlikte inceleyin.", en: "Inspect column and row missingness patterns instead of only counting empty values.", de: "Analysiert Fehlwertmuster über Spalten und Zeilen statt nur leere Werte zu zählen.", zh: "同时分析列和行的缺失模式，而不只是统计空值。" },
    purpose: { tr: "CSV'yi tırnak ve ayraç kurallarıyla ayrıştırır; sütun boşluk oranı, birlikte eksik alan örüntüsü ve sorunlu satırları raporlar. Eksikliğin nedenini veya uygun doldurma yöntemini otomatik belirlemez.", en: "Parses quoted CSV, reporting column missing rates, co-missing field patterns, and affected rows. It does not infer why data is missing or choose an imputation method.", de: "Liest CSV mit Anführungszeichen und meldet Fehlraten je Spalte, gemeinsame Fehlmuster und betroffene Zeilen. Ursache und Imputation werden nicht automatisch bestimmt.", zh: "解析带引号的 CSV，报告各列缺失率、共同缺失模式和受影响行；不会推断缺失原因或自动选择填补方法。" },
    uses: { tr: ["İçe aktarma kalite kapısı", "Anket veri ön incelemesi", "Dönüşüm öncesi kapsam ölçümü"], en: ["Import quality gate", "Survey-data pre-review", "Pre-transformation coverage check"], de: ["Import-Qualitätsprüfung", "Vorprüfung von Umfragedaten", "Abdeckungsprüfung vor Transformation"], zh: ["导入质量门禁", "问卷数据预审", "转换前覆盖率检查"] },
    steps: { tr: ["Başlık satırı olan CSV verisini ekleyin.", "Eksik değer belirteçlerini ve örüntüleri inceleyin.", "Kaynak sistem, örneklem ve iş kuralıyla birlikte karar verin."], en: ["Add CSV data with a header row.", "Review missing-value tokens and patterns.", "Decide with source-system, sampling, and business-rule context."], de: ["CSV mit Kopfzeile einfügen.", "Fehlwertkennzeichen und Muster prüfen.", "Mit Quellsystem, Stichprobe und Fachregel entscheiden."], zh: ["添加带表头的 CSV 数据。", "检查缺失值标记和模式。", "结合源系统、抽样和业务规则作出决定。"] },
  },
  {
    slug: "http-vary-cache-anahtari-denetleyici", category: "codeSecurity", mark: "326",
    title: { tr: "HTTP Vary ve Cache Anahtarı Denetleyici", en: "HTTP Vary & Cache-Key Checker", de: "HTTP-Vary- und Cache-Key-Prüfung", zh: "HTTP Vary 与缓存键检查器" },
    short: { tr: "Yanıt başlıklarında kişiye özel içeriğin ortak önbelleğe sızma riskini açıklanabilir kurallarla tarayın.", en: "Scan response headers for shared-cache risks around personalized content with explainable rules.", de: "Prüft Antwortheader mit nachvollziehbaren Regeln auf Shared-Cache-Risiken bei personalisierten Inhalten.", zh: "使用可解释规则扫描响应头中个性化内容的共享缓存风险。" },
    purpose: { tr: "Cache-Control, Vary, Set-Cookie, Authorization ve içerik varyantı sinyallerini birlikte inceler. CDN'nin gerçek yapılandırmasını ya da canlı yanıt davranışını doğrulamaz.", en: "Reviews Cache-Control, Vary, Set-Cookie, Authorization, and representation signals together. It cannot verify the deployed CDN configuration or live response behavior.", de: "Bewertet Cache-Control, Vary, Set-Cookie, Authorization und Darstellungsmerkmale gemeinsam. Die reale CDN-Konfiguration wird nicht verifiziert.", zh: "综合检查 Cache-Control、Vary、Set-Cookie、Authorization 和内容变体信号；无法验证实际 CDN 配置或线上响应行为。" },
    uses: { tr: ["CDN yayın ön kontrolü", "Kişiselleştirilmiş sayfa incelemesi", "Önbellek olayı analizi"], en: ["CDN pre-release review", "Personalized-page review", "Cache-incident analysis"], de: ["CDN-Vorabprüfung", "Prüfung personalisierter Seiten", "Cache-Vorfallanalyse"], zh: ["CDN 发布前检查", "个性化页面审查", "缓存事件分析"] },
    steps: { tr: ["Temsili istek ve yanıt başlıklarını ekleyin.", "Önbellek risk sinyallerini çalıştırın.", "Canlı CDN kuralı ve çok kullanıcılı testle doğrulayın."], en: ["Add representative request and response headers.", "Run the cache-risk checks.", "Verify with deployed CDN rules and multi-user tests."], de: ["Repräsentative Request- und Response-Header einfügen.", "Cache-Risikoprüfung starten.", "Mit CDN-Regeln und Mehrbenutzertests verifizieren."], zh: ["添加代表性的请求和响应头。", "运行缓存风险检查。", "使用已部署的 CDN 规则和多用户测试验证。"] },
  },
  {
    slug: "html-tablo-erisilebilirlik-denetleyici", category: "text", mark: "327",
    title: { tr: "HTML Tablo Erişilebilirlik Denetleyici", en: "HTML Table Accessibility Checker", de: "Barrierefreiheitsprüfung für HTML-Tabellen", zh: "HTML 表格无障碍检查器" },
    short: { tr: "Tablo işaretlemesinde caption, başlık hücresi, scope ve karmaşık ilişki eksiklerini bulun.", en: "Find missing captions, header cells, scope, and complex table relationships in HTML markup.", de: "Findet fehlende Beschriftungen, Kopfzellen, scope und komplexe Tabellenbeziehungen im HTML-Markup.", zh: "查找 HTML 表格标记中缺失的标题、表头单元格、scope 和复杂关联。" },
    purpose: { tr: "Yapıştırılan HTML içindeki tabloları statik olarak inceler ve ekran okuyucu ilişkilendirmesini güçlendirecek bulgular üretir. Gerçek erişilebilirlik testi için tarayıcı ve yardımcı teknoloji gerekir.", en: "Statically inspects pasted HTML tables and reports markup that can strengthen screen-reader relationships. Real accessibility testing still requires a browser and assistive technology.", de: "Prüft eingefügte HTML-Tabellen statisch und meldet Markup für bessere Screenreader-Beziehungen. Reale Tests benötigen Browser und Hilfstechnologie.", zh: "静态检查粘贴的 HTML 表格，并报告可增强屏幕阅读器关联的标记；真实无障碍测试仍需浏览器和辅助技术。" },
    uses: { tr: ["İçerik yayın kontrolü", "Tasarım sistemi QA", "Eski tablo iyileştirmesi"], en: ["Content release review", "Design-system QA", "Legacy table remediation"], de: ["Content-Veröffentlichungsprüfung", "Designsystem-QA", "Sanierung älterer Tabellen"], zh: ["内容发布检查", "设计系统 QA", "旧表格修复"] },
    steps: { tr: ["Tablo içeren HTML parçasını ekleyin.", "İşaretleme denetimini çalıştırın.", "Klavye ve ekran okuyucuyla gerçek sayfayı test edin."], en: ["Add the HTML fragment containing tables.", "Run the markup review.", "Test the real page with keyboard and screen reader."], de: ["HTML-Fragment mit Tabellen einfügen.", "Markup-Prüfung ausführen.", "Reale Seite mit Tastatur und Screenreader testen."], zh: ["添加包含表格的 HTML 片段。", "运行标记检查。", "使用键盘和屏幕阅读器测试真实页面。"] },
  },
  {
    slug: "borc-odeme-stratejisi-karsilastirici", category: "calculation", mark: "328",
    title: { tr: "Borç Ödeme Stratejisi Karşılaştırıcı", en: "Debt Payoff Strategy Comparator", de: "Vergleich von Schuldentilgungsstrategien", zh: "债务偿还策略比较器" },
    short: { tr: "Aynı aylık bütçeyle kartopu ve çığ yöntemlerini şeffaf aylık simülasyonla karşılaştırın.", en: "Compare snowball and avalanche methods with a transparent monthly simulation and the same budget.", de: "Vergleicht Schneeball- und Lawinenmethode mit transparenter Monatssimulation bei gleichem Budget.", zh: "使用相同预算和透明的月度模拟比较雪球法与雪崩法。" },
    purpose: { tr: "Bakiye, yıllık oran ve minimum ödemelerle iki stratejinin süre ve tahmini faizini hesaplar. Ücret, değişken oran, vergi ve kredi etkisini kapsamaz; finansal tavsiye değildir.", en: "Uses balances, APRs, and minimums to estimate duration and interest for two strategies. Fees, variable rates, taxes, and credit effects are excluded; this is not financial advice.", de: "Schätzt aus Salden, Jahreszinsen und Mindestzahlungen Laufzeit und Zins beider Strategien. Gebühren, variable Zinsen, Steuern und Bonität fehlen; keine Finanzberatung.", zh: "根据余额、年利率和最低还款额估算两种策略的期限和利息；不含费用、浮动利率、税费和信用影响，不构成财务建议。" },
    uses: { tr: ["Aylık ödeme senaryosu", "Strateji farkını görünür kılma", "Bütçe hassasiyet analizi"], en: ["Monthly payment scenario", "Making strategy tradeoffs visible", "Budget sensitivity analysis"], de: ["Monatliches Zahlungsszenario", "Strategieunterschiede sichtbar machen", "Budget-Sensitivitätsanalyse"], zh: ["月度还款情景", "展示策略取舍", "预算敏感性分析"] },
    steps: { tr: ["Her borcu ad, bakiye, yıllık oran ve minimum ödeme ile girin.", "Toplam aylık bütçeyi ekleyip iki simülasyonu çalıştırın.", "Sonucu gerçek sözleşme, ücret ve değişken oranlarla yeniden değerlendirin."], en: ["Enter each debt with name, balance, APR, and minimum payment.", "Add the total monthly budget and run both simulations.", "Re-evaluate against contracts, fees, and variable rates."], de: ["Jede Schuld mit Name, Saldo, Jahreszins und Mindestzahlung eingeben.", "Gesamtbudget ergänzen und beide Simulationen starten.", "Mit Verträgen, Gebühren und variablen Zinsen neu bewerten."], zh: ["输入每笔债务的名称、余额、年利率和最低还款额。", "添加月度总预算并运行两种模拟。", "结合合同、费用和浮动利率重新评估。"] },
  },
  {
    slug: "veri-alani-sozlugu-olusturucu", category: "data", mark: "329",
    title: { tr: "Veri Alanı Sözlüğü Oluşturucu", en: "Data Field Dictionary Builder", de: "Datenfeld-Wörterbuchgenerator", zh: "数据字段字典生成器" },
    short: { tr: "Alan adı, tür, amaç, hassasiyet, kaynak ve saklama bilgisini denetlenebilir bir sözlükte birleştirin.", en: "Combine field name, type, purpose, sensitivity, source, and retention into an auditable dictionary.", de: "Führt Feldname, Typ, Zweck, Sensibilität, Quelle und Aufbewahrung in einem prüfbaren Wörterbuch zusammen.", zh: "将字段名、类型、用途、敏感性、来源和保留期整合为可审计字典。" },
    purpose: { tr: "Satır tabanlı alan envanterini doğrular; yinelenen adları, eksik amaçları ve belirsiz saklama değerlerini göstererek Markdown veri sözlüğü üretir. Kurumsal veri yönetişimi onayı yerine geçmez.", en: "Validates a row-based field inventory, flags duplicate names, missing purposes, and vague retention, then builds a Markdown dictionary. It does not replace organizational data-governance approval.", de: "Validiert ein zeilenbasiertes Feldinventar, markiert Duplikate, fehlende Zwecke und unklare Aufbewahrung und erzeugt ein Markdown-Wörterbuch. Keine Governance-Freigabe.", zh: "验证逐行字段清单，标记重复名称、缺失用途和模糊保留期，并生成 Markdown 字典；不能替代组织的数据治理审批。" },
    uses: { tr: ["Analitik veri sözleşmesi", "Gizlilik envanteri hazırlığı", "Ekipler arası veri teslimi"], en: ["Analytics data contract", "Privacy inventory preparation", "Cross-team data handoff"], de: ["Analytics-Datenvertrag", "Vorbereitung des Datenschutzinventars", "Teamübergreifende Datenübergabe"], zh: ["分析数据契约", "隐私清单准备", "跨团队数据交付"] },
    steps: { tr: ["Her alanı belirtilen sütun düzeninde ekleyin.", "Sözlük ve kalite bulgularını üretin.", "Alan sahibi, hukuk ve güvenlik sorumlularıyla onaylayın."], en: ["Add each field in the documented column order.", "Generate the dictionary and quality findings.", "Approve with data owners, legal, and security stakeholders."], de: ["Jedes Feld in der dokumentierten Spaltenfolge eintragen.", "Wörterbuch und Qualitätsbefunde erzeugen.", "Mit Datenverantwortlichen, Recht und Sicherheit freigeben."], zh: ["按说明的列顺序添加每个字段。", "生成字典和质量发现。", "由数据负责人、法务和安全相关方审核。"] },
  },
];

export const stageTwoToolSlugs = new Set(specs.map((spec) => spec.slug));
export const stageTwoTools: BaseTool[] = specs.map((spec) => ({
  slug: spec.slug, category: spec.category, mark: spec.mark, title: spec.title, short: spec.short,
  description: spec.purpose,
  useCases: Object.fromEntries((Object.keys(spec.uses) as Array<keyof Copy>).map((locale) => [locale, spec.uses[locale].map((item) => `${item} — ${spec.short[locale]}`)])) as Record<keyof Copy, string[]>,
  steps: spec.steps,
}));
