import type { ArticleSection, Post } from "./posts";
import type { LocalizedGuide } from "./localized-guides";
import { publicTools } from "./tools";

type Locale = "tr" | "en" | "de" | "zh";
type Quad = Record<Locale, string>;
type Seed = { slug: string; relatedTools: string[]; title: Quad; excerpt: Quad; description: Quad; category: Quad; sections: Record<Locale, ArticleSection[]> };

const seeds: Seed[] = [
  {
    slug: "multilingual-redaction-quality-assurance", relatedTools: ["kvkk-veri-maskeleyici", "unicode-normalizasyon-inceleyici", "metin-farki-diff", "unicode-benzer-karakter-tarayicisi"],
    title: { tr: "Çok Dilli Verilerde Maskeleme Kalite Güvencesi", en: "Quality Assurance for Redaction in Multilingual Data", de: "Qualitätssicherung für Schwärzung in mehrsprachigen Daten", zh: "多语言数据脱敏质量保证指南" },
    excerpt: { tr: "Türkçe, Almanca, Çince ve karma Unicode metinlerde hassas alanları gizlerken bağlamı ve veri bütünlüğünü koruyun.", en: "Protect sensitive fields in Turkish, German, Chinese, and mixed-Unicode text without losing context or data integrity.", de: "Schützen Sie sensible Felder in türkischen, deutschen, chinesischen und gemischten Unicode-Texten, ohne Kontext zu verlieren.", zh: "在土耳其语、德语、中文及混合 Unicode 文本中隐藏敏感字段，同时保留上下文与数据完整性。" },
    description: { tr: "Maskeleme kapsamını, Unicode normalizasyonunu, benzer karakter riskini ve önce/sonra doğrulamasını tekrarlanabilir bir kabul planına dönüştüren uygulamalı rehber.", en: "A practical guide to turning redaction scope, Unicode normalization, confusable-character risk, and before/after verification into a repeatable acceptance plan.", de: "Praxisleitfaden für einen wiederholbaren Abnahmeplan aus Schwärzungsumfang, Unicode-Normalisierung, Zeichenverwechslungen und Vorher-Nachher-Prüfung.", zh: "将脱敏范围、Unicode 规范化、易混淆字符风险和前后对比转化为可重复验收计划的实用指南。" },
    category: { tr: "Gizlilik kalite güvencesi", en: "Privacy quality assurance", de: "Datenschutz-Qualitätssicherung", zh: "隐私质量保证" },
    sections: {
      tr: [
        { heading: "Önce veri envanteri ve tehdit modelini yazın", paragraphs: ["Ad, e-posta ve telefon gibi belirgin alanların yanında serbest metin, dosya adı, kullanıcı kodu ve birleşince kişiyi tanımlayabilen dolaylı alanları da listeleyin. Hangi alıcının hangi bilgiyi görmesi gerektiğini belirtmeden doğru maskeleme seviyesi seçilemez.", "Gerçek kayıtla denemek yerine aynı dil, noktalama ve alan uzunluklarını temsil eden sentetik bir fixture oluşturun. Böylece maskeleme hatasını yeniden üretebilir, fakat inceleme kaydında kişisel veri çoğaltmazsınız."], bullets: ["Doğrudan ve dolaylı tanımlayıcıları ayırın.", "Alıcı ve kullanım amacını kaydedin.", "Sentetik kabul örneği hazırlayın."] },
        { heading: "Unicode değişimini bilinçli yönetin", paragraphs: ["Aynı görünen metin farklı kod noktaları veya birleşik karakter dizileri taşıyabilir. Normalizasyon arama ve eşleşmeyi iyileştirebilir; ancak imzalı, kanıt niteliğindeki veya byte düzeyinde karşılaştırılan veriyi sessizce değiştirmemelidir.", "Latin, Kiril ve Yunan alfabelerindeki benzer karakterler kullanıcı adı ya da alan adı incelemesini yanıltabilir. Benzer karakter taraması yalnızca inceleme önceliği üretir; kötü niyet veya gerçek kimlik kanıtı değildir."] },
        { heading: "Maskeleme sonrasında önce/sonra kabul testi yapın", paragraphs: ["Diff görünümünde her hassas değerin kaldırıldığını, yer tutucuların aynı kişiyi tekrar tanımlamayacak şekilde kullanıldığını ve iş için gerekli bağlamın kaldığını kontrol edin. Sadece eşleşme sayısına bakmak, serbest metindeki kaçakları kaçırabilir.", "Yanlış pozitifleri de kaydedin. Ürün kodu telefon sanılıyorsa kural kapsamını daraltın; ancak yalnızca daha temiz bir rapor almak için gerçek riskli eşleşmeyi bastırmayın."] },
        { heading: "Yayın kapısını örneklem ve insan onayıyla kapatın", paragraphs: ["Normal örneğe ek olarak aksanlı ad, sağdan sola metin, CJK karakteri, boş alan, bozuk e-posta ve çok uzun satır çalıştırın. Kritik paylaşımda ikinci kişinin örneklem incelemesi otomatik desen kontrolünün yerini değil, eksiklerini tamamlar.", "Kayıtta gerçek değerleri değil kural sürümünü, fixture kimliğini, beklenen ve gözlenen sonucu, kabul sahibini ve yeniden inceleme koşulunu tutun. Maskeleme anonimleştirme garantisi veya mevzuat onayı değildir."] },
      ],
      en: [
        { heading: "Write the inventory and threat model first", paragraphs: ["List direct identifiers such as names and email addresses beside free text, filenames, user codes, and combinations that can identify a person indirectly. The right redaction level depends on who receives the output and why.", "Build a synthetic fixture that preserves representative languages, punctuation, and field lengths. It makes failures reproducible without copying personal data into the review record."], bullets: ["Separate direct and indirect identifiers.", "Record audience and purpose.", "Prepare a synthetic acceptance fixture."] },
        { heading: "Manage Unicode changes deliberately", paragraphs: ["Visually identical text can use different code points or combining sequences. Normalization may improve matching, but must not silently alter signed, evidential, or byte-compared material.", "Confusable Latin, Cyrillic, and Greek characters can mislead username or domain review. A confusable scan prioritizes inspection; it does not prove malicious intent or identity."] },
        { heading: "Run a before-and-after acceptance test", paragraphs: ["Use a diff to confirm that sensitive values disappeared, placeholders cannot reconnect records, and task-relevant context remains. Match counts alone can miss disclosures hidden in free text.", "Record false positives too. Narrow a rule when a product code is treated as a phone number, but never suppress a genuine risky match merely to obtain a cleaner report."] },
        { heading: "Close the release gate with sampling and human approval", paragraphs: ["Test accented names, right-to-left text, CJK characters, empty fields, malformed email, and long lines beside the normal fixture. A second-person sample review complements rather than replaces pattern checks.", "Store rule version, fixture identifier, expected and observed result, approver, and re-review trigger—not real values. Redaction is not a guarantee of anonymization or legal compliance."] },
      ],
      de: [
        { heading: "Dateninventar und Bedrohungsmodell zuerst festhalten", paragraphs: ["Erfassen Sie Namen und E-Mail-Adressen ebenso wie Freitext, Dateinamen, Nutzerkennungen und indirekt identifizierende Kombinationen. Der passende Schwärzungsgrad hängt von Empfänger und Zweck ab.", "Ein synthetisches Fixture sollte Sprachen, Satzzeichen und Feldlängen abbilden. So bleiben Fehler reproduzierbar, ohne personenbezogene Daten ins Prüfprotokoll zu kopieren."], bullets: ["Direkte und indirekte Kennungen trennen.", "Empfänger und Zweck dokumentieren.", "Synthetisches Abnahmebeispiel anlegen."] },
        { heading: "Unicode-Änderungen bewusst steuern", paragraphs: ["Optisch gleicher Text kann aus anderen Codepoints oder Kombinationsfolgen bestehen. Normalisierung verbessert Vergleiche, darf signierte, beweisrelevante oder byteweise geprüfte Daten aber nicht still verändern.", "Verwechselbare lateinische, kyrillische und griechische Zeichen können Nutzer- oder Domainprüfungen täuschen. Ein Treffer priorisiert die Kontrolle, beweist aber weder Absicht noch Identität."] },
        { heading: "Vorher-Nachher-Abnahme durchführen", paragraphs: ["Prüfen Sie im Diff, ob sensible Werte entfernt, Platzhalter nicht rückverknüpfbar und notwendige Zusammenhänge erhalten sind. Reine Trefferzahlen übersehen mögliche Lecks im Freitext.", "Auch Fehlalarme werden protokolliert. Regeln dürfen bei Produktcodes enger werden; echte Risikotreffer dürfen nicht nur für einen sauberen Bericht unterdrückt werden."] },
        { heading: "Freigabe mit Stichprobe und menschlicher Entscheidung", paragraphs: ["Testen Sie Akzente, rechtsläufige und linksläufige Schrift, CJK, leere Felder, fehlerhafte E-Mails und lange Zeilen. Eine zweite Stichprobe ergänzt die Musterprüfung.", "Speichern Sie Regelversion, Fixture-ID, Soll/Ist, Freigabe und erneuten Prüfauslöser statt Originalwerten. Schwärzung garantiert weder Anonymisierung noch Rechtskonformität."] },
      ],
      zh: [
        { heading: "先建立数据清单与威胁模型", paragraphs: ["除姓名、邮箱和电话等直接标识符外，还要列出自由文本、文件名、用户代码以及组合后可间接识别个人的字段。只有明确接收者和用途，才能选择适当的脱敏强度。", "请构造保留代表性语言、标点和字段长度的合成样例。这样既能复现错误，也不会在检查记录中复制个人数据。"], bullets: ["区分直接与间接标识符。", "记录接收者和处理目的。", "准备合成验收样例。"] },
        { heading: "有意识地管理 Unicode 变化", paragraphs: ["视觉相同的文本可能由不同码点或组合序列构成。规范化有助于匹配，但不应静默修改已签名、具有证据意义或需要按字节比较的数据。", "拉丁、西里尔和希腊字母中的易混淆字符可能误导用户名或域名检查。扫描结果只用于安排复核优先级，不能证明恶意或真实身份。"] },
        { heading: "执行脱敏前后验收", paragraphs: ["使用差异视图确认敏感值已移除、占位符无法重新关联记录，同时任务所需上下文仍然存在。只看匹配数量可能漏掉自由文本中的泄露。", "误报也应记录。如果产品代码被识别为电话号码，可缩小规则范围；但不能为了报告更整洁而压制真实风险。"] },
        { heading: "用抽样与人工批准关闭发布门禁", paragraphs: ["除正常样例外，还应测试重音姓名、从右到左文本、CJK 字符、空字段、错误邮箱和超长行。第二人抽样复核用于补充而非替代模式检查。", "记录规则版本、样例编号、预期与观察结果、批准人和复审触发条件，而不是原始值。脱敏并不保证匿名化或法规合规。"] },
      ],
    },
  },
  {
    slug: "offline-incident-evidence-handover", relatedTools: ["git-diff-sir-tarayicisi", "gizli-deger-redaksiyon-planlayici", "dosya-hash-karsilastirici", "ihlal-bildirim-zaman-cizelgesi"],
    title: { tr: "Olay Kayıtlarını Yüklemeden Güvenli Kanıt Devri", en: "Safe Incident-Evidence Handover Without Uploading Logs", de: "Sichere Übergabe von Vorfallnachweisen ohne Log-Upload", zh: "无需上传日志的安全事件证据交接" },
    excerpt: { tr: "Log, diff ve zaman çizelgesini gizli değerleri çoğaltmadan; bütünlük, kapsam ve sorumluluk sınırlarıyla devredin.", en: "Hand over logs, diffs, and timelines with integrity and scope controls, without multiplying secrets.", de: "Übergeben Sie Logs, Diffs und Zeitlinien mit Integritäts- und Umfangskontrollen, ohne Geheimnisse zu vervielfachen.", zh: "在不扩散密钥的情况下，以完整性、范围和责任控制交接日志、差异与时间线。" },
    description: { tr: "Tarayıcı içi sır ön taraması, redaksiyon planı, hash karşılaştırması ve zaman çizelgesi ile güvenli olay paketi hazırlama rehberi.", en: "A guide to preparing a safer incident package with local secret pre-scans, a redaction plan, hash comparison, and a bounded timeline.", de: "Leitfaden für ein sichereres Vorfallpaket mit lokaler Geheimnisprüfung, Redaktionsplan, Hashvergleich und begrenzter Zeitlinie.", zh: "通过本地密钥预扫描、脱敏计划、哈希比较和有界时间线准备安全事件包的指南。" },
    category: { tr: "Olay müdahalesi", en: "Incident response", de: "Vorfallreaktion", zh: "事件响应" },
    sections: {
      tr: [
        { heading: "Amaç ve saklama sınırını olay paketinden önce belirleyin", paragraphs: ["Kanıt paketi her log satırını toplamak için değil, belirli bir olayı yeniden kurmak için hazırlanır. Zaman aralığı, sistem, olay kimliği, karar sahibi ve paketin kimlerle paylaşılacağını başta yazın.", "Gerçek token, oturum çerezi, özel anahtar, müşteri verisi ve gereksiz gövde içeriği pakete girmemelidir. Orijinal delilin yetkili ve erişim kontrollü kopyası ayrı tutulur; paylaşım kopyası redakte edilir."], bullets: ["Olay sorusunu tek cümlede tanımlayın.", "En kısa gerekli zaman aralığını seçin.", "Orijinal ile paylaşım kopyasını ayırın."] },
        { heading: "Sır taramasını kesin hüküm değil önceliklendirme olarak kullanın", paragraphs: ["Diff ve metin taraması anahtar biçimleri, yüksek entropi dizileri ve bilinen önekleri gösterebilir. Bulgu olmaması sır bulunmadığını kanıtlamaz; özel biçimler, parçalanmış değerler ve ikili dosyalar ayrıca incelenir.", "Her bulgu için kaldır, kısmi göster, sabit yer tutucu kullan veya yetkili kanalda tut kararını yazın. Aynı sırrın her yerde aynı yer tutucuya dönüşmesi korelasyon sağlayabilir; bunun gerekli olup olmadığını değerlendirin."] },
        { heading: "Hash ile bütünlüğü doğrulayın, kaynağı değil", paragraphs: ["Paylaşım paketinin SHA-256 özeti aktarım sırasında dosyanın değişip değişmediğini karşılaştırmaya yardım eder. Hash, dosyayı kimin ürettiğini, içeriğin doğru olduğunu veya cihazın ele geçirilmediğini kanıtlamaz.", "Dosya listesi, byte boyutu, hash, üretim zamanı ve kullanılan redaksiyon kuralı birlikte bir manifestte yer almalıdır. Manifestin kendisi de erişim kontrolüne tabidir."] },
        { heading: "Zaman çizelgesini gözlem, çıkarım ve yükümlülük olarak ayırın", paragraphs: ["Her kayıt için kaynak saat dilimi, gözlenen olay, güven düzeyi ve eksik bilgi ayrı tutulur. 'İhlal başladı' gibi çıkarımlar, logda görülen somut olayla aynı sütunda sunulmamalıdır.", "Bildirim süresi aracı yalnızca tarih aritmetiği ve kontrol listesi sağlar; hukuki başlangıç anını veya yükümlülüğü belirlemez. Yetkili ekip gerçek mevzuat, sözleşme ve olay bağlamıyla son kararı verir."] },
      ],
      en: [
        { heading: "Set purpose and retention boundaries before packaging evidence", paragraphs: ["An evidence package should reconstruct a defined event, not collect every log line. State the time range, system, incident identifier, decision owner, and intended recipients first.", "Real tokens, session cookies, private keys, customer data, and unnecessary bodies do not belong in the shared package. Keep an access-controlled original separately and redact the working copy."], bullets: ["Define the incident question in one sentence.", "Choose the shortest necessary time range.", "Separate original and sharing copy."] },
        { heading: "Use secret scanning for prioritization, not a verdict", paragraphs: ["Diff and text scans can flag key shapes, high-entropy strings, and known prefixes. No finding does not prove that secrets are absent; custom formats, split values, and binaries need separate review.", "For every finding, record whether to remove it, partially display it, replace it consistently, or retain it only in an authorized channel. Consistent placeholders may themselves enable correlation."] },
        { heading: "Use hashes to check integrity, not provenance", paragraphs: ["A SHA-256 digest helps compare whether a shared file changed in transit. It cannot prove who created the file, whether its claims are true, or whether the originating device was compromised.", "A manifest should include filename, byte size, digest, creation time, and redaction-rule version. Protect the manifest because filenames and timing can still reveal context."] },
        { heading: "Separate observation, inference, and obligation in the timeline", paragraphs: ["For each entry, keep source timezone, observed event, confidence, and missing information distinct. Do not present an inference such as 'breach began' as though it were a raw log event.", "A notification-timeline tool provides date arithmetic and prompts only; it does not decide legal awareness or duty. Authorized teams must apply current law, contracts, and incident facts."] },
      ],
      de: [
        { heading: "Zweck und Aufbewahrung vor dem Paket begrenzen", paragraphs: ["Ein Nachweispaket rekonstruiert einen definierten Vorfall, statt sämtliche Logs zu sammeln. Zeitraum, System, Vorfallkennung, Verantwortliche und Empfänger werden zuerst festgelegt.", "Token, Sitzungscookies, private Schlüssel, Kundendaten und unnötige Bodies gehören nicht in die Freigabekopie. Das zugriffsgeschützte Original bleibt getrennt."], bullets: ["Vorfallfrage in einem Satz formulieren.", "Kürzesten nötigen Zeitraum wählen.", "Original und Freigabekopie trennen."] },
        { heading: "Geheimnisscan zur Priorisierung nutzen", paragraphs: ["Scans erkennen Schlüsselstrukturen, entropiereiche Zeichenfolgen und bekannte Präfixe. Kein Fund beweist keine Geheimnisse; eigene Formate, geteilte Werte und Binärdateien brauchen zusätzliche Prüfung.", "Für jeden Treffer wird Entfernen, Teilanzeige, Platzhalter oder Aufbewahrung im berechtigten Kanal entschieden. Einheitliche Platzhalter können Korrelation ermöglichen."] },
        { heading: "Hash prüft Integrität, nicht Herkunft", paragraphs: ["Ein SHA-256-Wert hilft festzustellen, ob sich eine Datei beim Transfer verändert hat. Er beweist weder Urheber, Wahrheitsgehalt noch einen sicheren Ursprungsrechner.", "Manifestdaten umfassen Name, Bytezahl, Hash, Erstellungszeit und Regelversion. Auch das Manifest kann Kontext offenlegen und benötigt Schutz."] },
        { heading: "Beobachtung, Schlussfolgerung und Pflicht trennen", paragraphs: ["Zeitzone, beobachtetes Ereignis, Sicherheit und Informationslücke werden je Eintrag getrennt. Die Schlussfolgerung 'Vorfall begann' darf nicht wie ein rohes Logereignis erscheinen.", "Ein Fristenwerkzeug rechnet Daten und liefert Prüffragen; es entscheidet weder Kenntniszeitpunkt noch Rechtspflicht. Zuständige Teams prüfen geltendes Recht, Verträge und Fakten."] },
      ],
      zh: [
        { heading: "打包证据前先限定目的与保留范围", paragraphs: ["证据包用于重建一个明确事件，而不是收集所有日志。应先写明时间范围、系统、事件编号、决策负责人和预期接收者。", "真实 token、会话 Cookie、私钥、客户数据和不必要的正文不应进入共享包。访问受控的原始副本应与脱敏工作副本分开保存。"], bullets: ["用一句话定义事件问题。", "选择最短必要时间范围。", "分开原始副本与共享副本。"] },
        { heading: "把密钥扫描用于排序，而不是最终判定", paragraphs: ["差异和文本扫描可标记密钥形态、高熵字符串与已知前缀。没有发现不代表没有密钥；自定义格式、拆分值和二进制文件仍需单独检查。", "每项发现都应记录删除、部分显示、固定占位符或仅保留在授权渠道的决定。统一占位符本身也可能产生关联风险。"] },
        { heading: "哈希验证完整性，而非来源", paragraphs: ["SHA-256 摘要有助于比较共享文件在传输中是否变化，但不能证明创建者、内容真实性或来源设备未被攻陷。", "清单应包含文件名、字节大小、哈希、生成时间和脱敏规则版本。文件名与时间仍可能泄露上下文，因此清单也需要访问控制。"] },
        { heading: "在时间线中区分观察、推断与义务", paragraphs: ["每条记录应分别保存来源时区、观察到的事件、置信度和缺失信息。不要把‘泄露开始’之类的推断当作原始日志事件。", "通知时间线工具只提供日期计算和检查问题，不能决定法律上的知悉时间或义务。授权团队必须结合现行法律、合同和事件事实作出结论。"] },
      ],
    },
  },
  {
    slug: "spreadsheet-import-calculation-contract", relatedTools: ["csv-ayirac-tespit-araci", "csv-sutun-profilleyici", "csv-eksik-veri-deseni-analizoru", "birim-donusturucu"],
    title: { tr: "Hesaplamadan Önce CSV İçe Aktarma Sözleşmesi Kurma", en: "Build a CSV Import Contract Before You Calculate", de: "Vor Berechnungen einen CSV-Importvertrag definieren", zh: "计算前建立 CSV 导入契约" },
    excerpt: { tr: "Ayıracı, sütun türünü, eksik değer anlamını ve birimleri hesaplamaya geçmeden önce doğrulayın.", en: "Verify delimiter, column type, missing-value meaning, and units before a calculation begins.", de: "Prüfen Sie Trennzeichen, Spaltentyp, Fehlwertbedeutung und Einheiten vor jeder Berechnung.", zh: "在开始计算前验证分隔符、列类型、缺失值含义和单位。" },
    description: { tr: "Tablo içe aktarımını görünüşe göre değil açık veri sözleşmesi, profil, eksiklik örüntüsü ve birim dönüşümüyle kabul eden rehber.", en: "A guide to accepting table imports through an explicit contract, profile, missingness pattern, and unit conversion rather than appearance.", de: "Leitfaden zur Tabellenabnahme mit explizitem Vertrag, Profil, Fehlwertmuster und Einheitenumrechnung statt bloßer Optik.", zh: "通过明确契约、列画像、缺失模式和单位转换验收表格导入，而不是依赖表面显示。" },
    category: { tr: "Veri içe aktarma", en: "Data import", de: "Datenimport", zh: "数据导入" },
    sections: {
      tr: [
        { heading: "Dosyadan önce veri sözleşmesini yazın", paragraphs: ["Beklenen sütun adı, tür, zorunluluk, birim, tarih biçimi, ondalık işareti ve izin verilen değerleri kısa bir sözlükte tanımlayın. Bir hesaplama doğru formülle çalışsa bile yanlış birim veya yanlış yorumlanan boş değer sonucu anlamsızlaştırır.", "Sözleşme sürümü ve üretici sistem adı dosyayla birlikte gelmelidir. Sessizce eklenen veya yeniden adlandırılan sütunlar otomatik varsayımla değil açık inceleme ile karşılanır."], bullets: ["Başlık ve türleri listeleyin.", "Birim ile saat dilimini belirtin.", "Eksik değer politikasını yazın."] },
        { heading: "Ayıracı ve tırnak yapısını örneklemle doğrulayın", paragraphs: ["Virgül, noktalı virgül ve sekme seçimi bölge ayarına göre değişebilir. Tırnak içinde ayıraç, satır sonu veya çift tırnak bulunan hücreler basit split işlemini bozar.", "İlk satırın düzgün görünmesi yeterli değildir. Baş, orta ve son bölümden örnek alın; kapanmamış tırnak ve değişen sütun sayısı açık hata üretmelidir."] },
        { heading: "Profil ve eksiklik örüntüsünü birlikte okuyun", paragraphs: ["Tür tahmini, benzersiz değer, minimum/maksimum ve boşluk oranı kolonun beklenen rolüyle karşılaştırılır. Kimlik alanındaki tekrar ile kategori alanındaki tekrar aynı problem değildir.", "Eksiklik tek tek hücrelerden çok satır grubu, kaynak sistem veya tarih aralığında kümelenebilir. Eksikliği sıfırla doldurmadan önce mekanizmayı ve karar etkisini inceleyin."] },
        { heading: "Birim dönüşümünü geri hesapla kabul edin", paragraphs: ["Dönüşümde kaynak birim, hedef birim, katsayı, yuvarlama ve gösterim hassasiyeti kayda girer. Sıcaklık gibi ofsetli dönüşümler yalnızca çarpma değildir; para birimi ise güncel oran kaynağı gerektirir ve basit birim aracının kapsamı dışındadır.", "En az bir satırı bağımsız hesaplayın, sınır değerini deneyin ve toplamların korunup korunmadığını karşılaştırın. Kabul edilen çıktı, sözleşme sürümü ve fixture ile birlikte saklanır; gerçek hassas tablo paylaşılmaz."] },
      ],
      en: [
        { heading: "Write the data contract before opening the file", paragraphs: ["Define expected headers, types, required status, units, date format, decimal separator, and allowed values in a small dictionary. A correct formula still produces a meaningless result when units or blanks are misread.", "Carry the contract version and producer system with the file. Added or renamed columns require explicit review instead of silent inference."], bullets: ["List headers and types.", "State units and timezone.", "Write the missing-value policy."] },
        { heading: "Verify delimiter and quoting with a sample", paragraphs: ["Comma, semicolon, and tab conventions vary by locale. Delimiters, line breaks, or escaped quotes inside quoted cells defeat naive splitting.", "A correct first row is not enough. Sample the beginning, middle, and end; unclosed quotes and changing column counts must stop with an explicit error."] },
        { heading: "Read profiling and missingness together", paragraphs: ["Compare inferred type, uniqueness, range, and blank rate with the column's intended role. A repeated identifier and a repeated category do not carry the same risk.", "Missingness may cluster by row group, source system, or date. Investigate the mechanism and decision impact before replacing blanks with zero."] },
        { heading: "Accept unit conversion through an independent calculation", paragraphs: ["Record source unit, target unit, factor, rounding, and display precision. Offset conversions such as temperature are not simple multiplication; currency needs a current rate source and sits outside a static unit tool.", "Recalculate at least one row independently, test a boundary, and compare preserved totals. Store the accepted result with contract version and fixture, not the sensitive source table."] },
      ],
      de: [
        { heading: "Datenvertrag vor der Datei schreiben", paragraphs: ["Definieren Sie Kopfzeilen, Typen, Pflichtstatus, Einheiten, Datumsformat, Dezimalzeichen und erlaubte Werte. Selbst eine korrekte Formel wird bei falscher Einheit oder falsch gedeuteter Leerstelle wertlos.", "Vertragsversion und Quellsystem begleiten die Datei. Neue oder umbenannte Spalten werden ausdrücklich geprüft statt still erraten."], bullets: ["Kopfzeilen und Typen auflisten.", "Einheit und Zeitzone nennen.", "Fehlwertregel festhalten."] },
        { heading: "Trennzeichen und Quotes per Stichprobe prüfen", paragraphs: ["Komma, Semikolon und Tab unterscheiden sich nach Region. Trennzeichen, Zeilenumbrüche oder Quotes in zitierten Zellen brechen naives Aufteilen.", "Eine korrekte erste Zeile reicht nicht. Anfang, Mitte und Ende prüfen; offene Quotes und wechselnde Spaltenzahlen müssen klar stoppen."] },
        { heading: "Profil und Fehlwertmuster gemeinsam lesen", paragraphs: ["Typ, Eindeutigkeit, Bereich und Leerquote werden mit der vorgesehenen Spaltenrolle verglichen. Wiederholte Kennungen und wiederholte Kategorien bedeuten Verschiedenes.", "Fehlwerte können nach Gruppe, Quellsystem oder Datum gehäuft auftreten. Ursache und Entscheidungseinfluss werden vor dem Ersetzen durch null geprüft."] },
        { heading: "Einheitenumrechnung unabhängig nachrechnen", paragraphs: ["Quelle, Ziel, Faktor, Rundung und Genauigkeit werden dokumentiert. Temperatur benötigt Offsets; Währung braucht eine aktuelle Kursquelle und liegt außerhalb statischer Einheitenumrechnung.", "Mindestens eine Zeile wird unabhängig gerechnet, ein Grenzwert getestet und Summenerhalt verglichen. Gespeichert werden Vertrag und Fixture, nicht sensible Originaltabellen."] },
      ],
      zh: [
        { heading: "打开文件前先写数据契约", paragraphs: ["在小型数据字典中定义预期列名、类型、必填状态、单位、日期格式、小数分隔符和允许值。即使公式正确，错误单位或误解空值也会让结果失去意义。", "契约版本和生产系统名称应随文件传递。新增或重命名列必须明确复核，不能静默推断。"], bullets: ["列出表头和类型。", "说明单位与时区。", "写明缺失值策略。"] },
        { heading: "通过抽样验证分隔符与引号", paragraphs: ["逗号、分号和制表符习惯因地区而异。带引号单元格中的分隔符、换行或转义引号会破坏简单拆分。", "第一行看起来正确还不够，应抽查开头、中间和结尾；未闭合引号或列数变化必须产生明确错误。"] },
        { heading: "结合列画像与缺失模式判断", paragraphs: ["把推断类型、唯一值比例、范围和空白率与列的预期角色比较。标识符重复与分类值重复并不是同一种问题。", "缺失值可能按行组、来源系统或日期聚集。在用零填充前，应分析缺失机制及其对决策的影响。"] },
        { heading: "通过独立计算验收单位转换", paragraphs: ["记录源单位、目标单位、转换因子、取整和显示精度。温度等带偏移的转换不只是乘法；货币需要当前汇率来源，超出静态单位工具范围。还应明确小数舍入发生在单行还是汇总阶段，因为两种顺序可能产生不同总计。", "至少独立重算一行，测试零值、负值、极大值和精度边界，并比较转换前后的总量与记录数是否保持。若结果用于财务、医疗或合规决策，应由具备授权的人复核来源单位和机构规则。保存契约版本与合成样例，而不是敏感原始表格。"] },
      ],
    },
  },
  {
    slug: "accessible-release-evidence-checklist", relatedTools: ["html-tablo-erisilebilirlik-denetleyici", "renk-kontrast-denetleyici", "markdown-baglanti-butunluk-denetleyici", "meta-etiket-favicon-uretici"],
    title: { tr: "Erişilebilir İçerik Yayını için Kanıt Odaklı Kontrol Listesi", en: "An Evidence-Led Checklist for Accessible Content Releases", de: "Nachweisorientierte Checkliste für barrierefreie Inhalts-Releases", zh: "无障碍内容发布的证据化检查清单" },
    excerpt: { tr: "Tablo semantiği, renk kontrastı, bağlantı bütünlüğü ve sosyal önizlemeyi tek yayın kapısında doğrulayın.", en: "Verify table semantics, color contrast, link integrity, and social previews in one release gate.", de: "Prüfen Sie Tabellensemantik, Farbkontrast, Linkintegrität und Social Preview in einem Release-Gate.", zh: "在同一发布门禁中验证表格语义、颜色对比度、链接完整性和社交预览。" },
    description: { tr: "Otomatik ön kontrolleri klavye, zoom, ekran okuyucu ve gerçek paylaşım önizlemesiyle tamamlayan erişilebilir yayın iş akışı.", en: "An accessible publishing workflow that completes automated pre-checks with keyboard, zoom, screen-reader, and real sharing-preview tests.", de: "Barrierefreier Veröffentlichungsablauf, der automatische Vorprüfungen mit Tastatur-, Zoom-, Screenreader- und Freigabetests ergänzt.", zh: "以键盘、缩放、屏幕阅读器和真实分享预览补充自动预检的无障碍发布工作流。" },
    category: { tr: "Erişilebilir yayın", en: "Accessible publishing", de: "Barrierefreies Publizieren", zh: "无障碍发布" },
    sections: {
      tr: [
        { heading: "İçerik modelini görsel tasarımdan önce doğrulayın", paragraphs: ["Başlık sırası, liste yapısı, bağlantı metni ve tablonun gerçekten iki boyutlu veri taşıyıp taşımadığı yayın öncesinde belirlenir. Kartları hizalamak için tablo kullanmak, görünüm düzgün olsa bile yardımcı teknoloji deneyimini bozar.", "Tabloda kısa caption, anlamlı th hücreleri ve basit ilişkiler için scope gerekir. Çok seviyeli başlıklar karmaşıklaşıyorsa daha basit bir tablo veya alternatif özet sunmak genellikle daha güvenlidir."], bullets: ["Tek bir H1 ve sıralı başlık yapısı kullanın.", "Bağlantıyı cümleden bağımsız okuyun.", "Layout için tablo kullanmayın."] },
        { heading: "Kontrastı gerçek durumlarda ölçün", paragraphs: ["Normal metin, büyük metin, ikon, odak halkası, hata ve devre dışı durumları ayrı değerlendirin. Degrade veya görsel üzerindeki metinde yalnızca başlangıç rengini ölçmek en zayıf noktayı gizleyebilir.", "Kontrast oranı tek başına kullanılabilirlik kanıtı değildir. 200 ve 400 yüzde zoom, koyu/açık tema, yüksek kontrast tercihi ve renk olmadan anlamın korunması gerçek tarayıcıda denenmelidir."] },
        { heading: "Bağlantı ve meta veriyi vaatle aynı tutun", paragraphs: ["Bağlantı metni hedefi açıklamalı; beklenmeyen indirme, yeni sekme veya dil değişimi belirtilmelidir. Yerel Markdown kontrolü sözdizimini ve riskli protokolü görebilir, fakat 404, TLS veya hedef sahipliğini ağ olmadan kanıtlayamaz.", "Title, description, canonical, Open Graph ve favicon marka ile sayfanın gerçek içeriğini yansıtmalıdır. Sosyal kartta görünen vaat, sayfa açıldığında ilk görünümde bulunmuyorsa kullanıcı güveni zedelenir."] },
        { heading: "Otomasyonu gerçek kullanıcı akışıyla kapatın", paragraphs: ["Klavye ile menüden ana göreve, hata mesajına ve sonuç kontrolüne ulaşın. Yatay kaydırma gerekiyorsa bölge odaklanabilir ve etiketli olmalı; önemli sütunları CSS ile sessizce gizlemeyin.", "Kabul kaydına test edilen URL, viewport, zoom, tema, tarayıcı, yardımcı teknoloji, beklenen davranış ve gözlenen sonucu yazın. Tek tarayıcı veya tek otomatik skor WCAG uyumu kanıtlamaz."] },
      ],
      en: [
        { heading: "Validate the content model before visual styling", paragraphs: ["Decide heading order, list structure, link wording, and whether a table truly contains two-dimensional data before release. Using tables to align cards harms assistive technology even when it looks correct.", "A data table needs a concise caption, meaningful th cells, and scope for simple relationships. When multi-level headers become complex, a simpler table or alternate summary is often safer."], bullets: ["Use one H1 and ordered headings.", "Read links outside their sentence.", "Do not use tables for layout."] },
        { heading: "Measure contrast in real states", paragraphs: ["Review normal and large text, icons, focus rings, errors, and disabled states separately. On gradients or images, measuring only the first color can hide the weakest point.", "A ratio alone does not prove usability. Test 200 and 400 percent zoom, both themes, high-contrast preferences, and meaning without color in a real browser."] },
        { heading: "Keep links and metadata aligned with the promise", paragraphs: ["Link text should explain the destination and disclose unexpected downloads, new tabs, or language changes. A local Markdown check sees syntax and risky protocols, but cannot prove 404, TLS, or ownership without network access.", "Title, description, canonical, Open Graph, and favicon must reflect the real page. Trust suffers when the social card promises something absent from the first viewport."] },
        { heading: "Close automation with a real user flow", paragraphs: ["Use a keyboard to move from navigation to the primary task, error message, and result controls. Horizontal scroll regions must be focusable and labeled; do not silently hide meaningful columns with CSS.", "Record URL, viewport, zoom, theme, browser, assistive technology, expectation, and observation. One browser or automated score cannot prove WCAG conformance."] },
      ],
      de: [
        { heading: "Inhaltsmodell vor dem visuellen Design prüfen", paragraphs: ["Überschriftenfolge, Listen, Linktexte und echte Zweidimensionalität von Tabellen werden vor der Freigabe geklärt. Layout-Tabellen schaden Hilfstechnologien trotz korrekter Optik.", "Datentabellen brauchen kurze caption, sinnvolle th und scope. Bei komplexen Mehrfachköpfen ist eine einfachere Tabelle oder Zusammenfassung oft sicherer."], bullets: ["Ein H1 und geordnete Überschriften.", "Links außerhalb des Satzes lesen.", "Keine Layout-Tabellen."] },
        { heading: "Kontrast in echten Zuständen messen", paragraphs: ["Normaltext, Großtext, Icons, Fokusring, Fehler und deaktivierte Zustände werden getrennt geprüft. Bei Verläufen kann nur die erste Farbe die schwächste Stelle verbergen.", "Eine Verhältniszahl beweist keine Nutzbarkeit. Testen Sie 200/400 Prozent Zoom, beide Themes, hohen Kontrast und Bedeutung ohne Farbe im Browser."] },
        { heading: "Links und Metadaten an das Versprechen binden", paragraphs: ["Linktexte erklären Ziel, Download, neuen Tab oder Sprachwechsel. Lokale Markdown-Prüfung sieht Syntax und riskante Protokolle, aber ohne Netz weder 404 noch TLS oder Eigentum.", "Title, Description, Canonical, Open Graph und Favicon spiegeln den Seiteninhalt. Ein Social-Versprechen muss im ersten Viewport wiederzufinden sein."] },
        { heading: "Automatik mit Nutzerfluss abschließen", paragraphs: ["Per Tastatur werden Navigation, Hauptaufgabe, Fehler und Ergebnis erreicht. Horizontales Scrollen ist fokussierbar und beschriftet; wichtige Spalten werden nicht still versteckt.", "Protokollieren Sie URL, Viewport, Zoom, Theme, Browser, Hilfstechnik, Erwartung und Beobachtung. Einzelne Scores beweisen keine WCAG-Konformität."] },
      ],
      zh: [
        { heading: "先验证内容模型，再进行视觉设计", paragraphs: ["发布前先确定标题顺序、列表结构、链接文本以及表格是否真正表示二维数据。即使视觉整齐，用表格对齐卡片仍会损害辅助技术体验。", "数据表需要简洁 caption、含义明确的 th，以及简单关系中的 scope。多级表头过于复杂时，简化表格或提供替代摘要通常更安全。"], bullets: ["只使用一个 H1 并保持标题顺序。", "脱离句子单独阅读链接。", "不要用表格做布局。"] },
        { heading: "在真实状态下测量对比度", paragraphs: ["普通文本、大文本、图标、焦点环、错误和禁用状态应分别评估。渐变或图片上的文字如果只测第一个颜色，可能隐藏最弱位置。", "单一比率不能证明可用性。应在真实浏览器测试 200% 和 400% 缩放、深浅主题、高对比偏好以及不依赖颜色的含义。"] },
        { heading: "让链接和元数据与页面承诺一致", paragraphs: ["链接文本应说明目标，并提示意外下载、新标签页或语言变化。本地 Markdown 检查可发现语法和危险协议，但离线时不能证明 404、TLS 或目标所有权。", "标题、描述、canonical、Open Graph 和 favicon 必须反映真实页面。如果社交卡片承诺的内容在首屏找不到，会损害用户信任。"] },
        { heading: "用真实用户流程完成自动化检查", paragraphs: ["使用键盘从导航到主要任务、错误消息和结果控件。需要横向滚动时，区域应可聚焦并带标签；不要用 CSS 静默隐藏重要列。", "记录 URL、视口、缩放、主题、浏览器、辅助技术、预期和观察结果。单一浏览器或自动评分不能证明符合 WCAG。"] },
      ],
    },
  },
];

const relatedSection = (seed: Seed, locale: Locale): ArticleSection => ({
  heading: locale === "tr" ? "Bu iş akışındaki araçlar ve görevleri" : locale === "de" ? "Werkzeuge und Aufgaben in diesem Ablauf" : locale === "zh" ? "此工作流中的工具与职责" : "Tools and responsibilities in this workflow",
  paragraphs: [locale === "tr" ? "Her araç farklı bir kanıt üretir; tek bir çıktı tüm iş akışını onaylamaz. Sentetik örnekle başlayın, belirtilen kabul kontrolünü uygulayın ve sonuç sınırı aşıyorsa sonraki adıma geçmeyin." : locale === "de" ? "Jedes Werkzeug liefert einen anderen Nachweis; keine einzelne Ausgabe genehmigt den gesamten Ablauf. Beginnen Sie synthetisch, prüfen Sie die Abnahme und stoppen Sie bei überschrittener Grenze." : locale === "zh" ? "每个工具提供不同证据，任何单一输出都不能批准整个流程。请从合成示例开始，执行验收检查；超过边界时不要进入下一步。" : "Each tool contributes different evidence; no single output approves the whole workflow. Start with synthetic data, apply the acceptance check, and stop when a boundary is exceeded."],
  bullets: seed.relatedTools.map((slug) => { const tool = publicTools.find((item) => item.slug === slug); if (!tool) throw new Error(`Stage 3 guide ${seed.slug} references missing tool ${slug}`); return tool.title[locale]; }),
});

export const stageThreePosts: Post[] = seeds.map((seed) => ({
  slug: seed.slug, date: "2026-08-11", updated: "2026-08-11", relatedTools: seed.relatedTools,
  readTime: { tr: "12 dk", en: "11 min" }, title: { tr: seed.title.tr, en: seed.title.en }, excerpt: { tr: seed.excerpt.tr, en: seed.excerpt.en }, description: { tr: seed.description.tr, en: seed.description.en }, category: { tr: seed.category.tr, en: seed.category.en }, visualSuggestion: { tr: "Girdi, yerel ön kontrol, insan kabulü ve kanıt kaydını ayıran uygulama planı.", en: "An action plan separating input, local pre-check, human acceptance, and evidence record." }, sections: { tr: [...seed.sections.tr, relatedSection(seed, "tr")], en: [...seed.sections.en, relatedSection(seed, "en")] },
}));

export const stageThreeLocalizedGuides: LocalizedGuide[] = seeds.map((seed) => ({
  slug: seed.slug, date: "2026-08-11", updated: "2026-08-11", relatedTools: seed.relatedTools,
  copy: { de: { title: seed.title.de, excerpt: seed.excerpt.de, description: seed.description.de, category: seed.category.de, readTime: "11 Min.", sections: [...seed.sections.de, relatedSection(seed, "de")] }, zh: { title: seed.title.zh, excerpt: seed.excerpt.zh, description: seed.description.zh, category: seed.category.zh, readTime: "约 11 分钟", sections: [...seed.sections.zh, relatedSection(seed, "zh")] } },
}));
