import type { Post, ArticleSection } from "./posts";
import type { LocalizedGuide } from "./localized-guides";
import { publicTools } from "./tools";

type Pair = { tr: string; en: string; de: string; zh: string };
type Seed = {
  slug: string; date: string; relatedTools: string[]; title: Pair; excerpt: Pair; description: Pair; category: Pair;
  sections: Record<keyof Pair, ArticleSection[]>;
};

const seeds: Seed[] = [
  {
    slug: "safe-json-schema-openapi-evolution", date: "2026-08-11", relatedTools: ["json-schema-geriye-uyumluluk-denetleyici", "openapi-kirilma-degisikligi-denetleyici", "json-diff-karsilastirma", "openapi-endpoint-envanteri"],
    title: { tr: "JSON Schema ve OpenAPI Sözleşmelerini Tüketiciyi Bozmadan Geliştirme", en: "Evolving JSON Schema and OpenAPI Contracts Without Breaking Consumers", de: "JSON-Schema- und OpenAPI-Verträge ohne Client-Brüche weiterentwickeln", zh: "在不破坏消费者的前提下演进 JSON Schema 与 OpenAPI 契约" },
    excerpt: { tr: "Kırılma adaylarını yapısal diff, anonim fixture ve tüketici testiyle yayın öncesinde görünür kılın.", en: "Expose breaking candidates before release with structural diffs, anonymized fixtures, and consumer tests.", de: "Machen Sie Bruchkandidaten vor dem Release mit Struktur-Diffs, anonymisierten Fixtures und Verbrauchertests sichtbar.", zh: "通过结构差异、匿名样例和消费者测试，在发布前暴露破坏性变更候选项。" },
    description: { tr: "Gerekli alan, tür, enum, API yolu, parametre ve yanıt değişikliklerini güvenli bir sözleşme yayın akışında inceleyen uygulamalı rehber.", en: "A practical guide to reviewing required fields, types, enums, API paths, parameters, and responses in a safer contract-release workflow.", de: "Praxisleitfaden zur Prüfung von Pflichtfeldern, Typen, Enums, API-Pfaden, Parametern und Antworten in einem sicheren Release-Ablauf.", zh: "实用指南：在更安全的契约发布流程中审查必填字段、类型、枚举、API 路径、参数和响应。" },
    category: { tr: "API ve veri sözleşmeleri", en: "API and data contracts", de: "API- und Datenverträge", zh: "API 与数据契约" },
    sections: {
      tr: [
        { heading: "Uyumluluğu sürüm numarasından değil tüketiciden tanımlayın", paragraphs: ["Bir değişikliğin kırıcı olup olmadığı, yalnızca şemanın geçerli olmasına değil mevcut tüketicilerin hangi alanları gönderip okuduğuna bağlıdır. Önce desteklenen istemcileri, saklanan eski kayıtları ve geri alma süresini yazılı hale getirin.", "Yeni zorunlu alan, tür daraltma veya enum değerinin kaldırılması genellikle eski üreticiyi ya da okuyucuyu etkiler. Yeni isteğe bağlı alan çoğunlukla daha güvenlidir; yine de additionalProperties: false kullanan tüketiciler için sorun yaratabilir."], bullets: ["Tüketici ve üretici listesini çıkarın.", "Geri uyumluluk penceresini tarih ile belirtin.", "Kararı yalnızca sürüm etiketine bırakmayın."] },
        { heading: "İki belgeyi aynı kapsamda karşılaştırın", paragraphs: ["Eski ve yeni JSON Schema dosyalarının aynı kök nesneyi temsil ettiğini doğrulayın. OpenAPI karşılaştırmasında ise sunucudan yayınlanan gerçek belgeyi kullanın; farklı ortamların veya yarım oluşturulmuş dosyaların diff'i yanlış alarm üretir.", "ByteQuant doğrudan properties, required, type, enum ve additionalProperties değişikliklerini; OpenAPI tarafında yol, yöntem, parametre zorunluluğu ve yanıt kaldırılmasını tarar. Dış $ref ve koşullu şemalar için uzman araç ve gerçek çözümleme gerekir."] },
        { heading: "Anonim fixture ile değişikliği yeniden üretin", paragraphs: ["Her bulgu için kişisel veri içermeyen en küçük eski istek, yeni istek, eski yanıt ve yeni yanıt örneğini saklayın. Yalnızca ideal örnek değil, eksik alan, bilinmeyen enum, boş dizi ve büyük payload gibi sınır vakalarını da çalıştırın.", "Bir şema diff'i davranışı kanıtlamaz. Sunucunun varsayılan değer, hata kodu, sıralama ve sayfalama davranışı sözleşme testinde ayrıca gözlenmelidir."] },
        { heading: "Kırılmayı geçiş planına dönüştürün", paragraphs: ["Kırıcı değişiklik gerekiyorsa önce yeni alanı isteğe bağlı kabul eden sürümü yayınlayın, üreticileri taşıyın ve ölçümden sonra zorunluluğu etkinleştirin. Yol veya yanıt kaldırırken paralel sürüm, kullanımdan kaldırma tarihi ve makinece okunabilir uyarı sağlayın.", "Değişiklik notu yalnızca 'schema updated' dememelidir; etkilenen işlem, eski davranış, yeni davranış, geçiş örneği, son tarih ve geri dönüş yolu görünür olmalıdır."] },
        { heading: "Yayın kapısını kanıtla kapatın", paragraphs: ["Yerel ön kontrol, anonim fixture testleri, tüketici testleri ve staging gözlemi aynı kayıt altında birleşmelidir. Onay sahibini ve kabul edilen riskleri yazın; otomatik araç karar sahibi değildir.", "Üretim sonrası hata oranı, 4xx dağılımı ve eski istemci kullanımı izlenmelidir. Hassas payload veya erişim anahtarı rapora, CI çıktısına ya da paylaşılabilir URL'ye konulmamalıdır."], bullets: ["Yayın öncesi ve sonrası ölçümü eşleştirin.", "Geri alma ölçütünü önceden belirleyin.", "Raporları sentetik veride tutun."] },
      ],
      en: [
        { heading: "Define compatibility from the consumer, not the version number", paragraphs: ["Whether a change breaks a contract depends on what current consumers send and read, not merely whether the new schema is valid. Record supported clients, persisted historical records, and the rollback window first.", "A new required field, type narrowing, or removed enum value often affects old producers or readers. An optional property is usually safer, but can still break consumers that reject additional properties."], bullets: ["Inventory producers and consumers.", "Give the compatibility window a date.", "Do not delegate the decision to a version label."] },
        { heading: "Compare documents with matching scope", paragraphs: ["Confirm that the old and new JSON Schemas describe the same root object. For OpenAPI, compare documents produced from equivalent environments; mixing a deployed contract with a partial local file creates noise.", "ByteQuant reviews direct properties, requirements, types, enums, additionalProperties, paths, methods, parameter requirements, and removed responses. External references and conditional schemas require full resolution elsewhere."] },
        { heading: "Reproduce each candidate with anonymized fixtures", paragraphs: ["Keep the smallest non-personal old request, new request, old response, and new response for every finding. Exercise missing fields, unknown enum values, empty arrays, and large payloads beside the happy path.", "A structural diff does not prove behavior. Defaults, error codes, ordering, pagination, and authorization must be observed in contract tests." ] },
        { heading: "Turn a breaking change into a migration", paragraphs: ["When a break is necessary, first deploy a version that accepts the new field optionally, migrate producers, measure adoption, and only then enforce it. For removed paths or responses, publish overlap, a deprecation date, and a machine-readable warning.", "Release notes should name the operation, old and new behavior, migration example, deadline, and rollback route—not merely say that the schema changed."] },
        { heading: "Close the release gate with evidence", paragraphs: ["Join the local pre-check, anonymized fixtures, consumer tests, and staging observations in one record. Name the approver and accepted risks; the automated tool is not the decision owner.", "Monitor post-release error rates, 4xx distribution, and old-client use. Never place sensitive payloads or access credentials in reports, CI logs, or shared URLs."], bullets: ["Match pre- and post-release measures.", "Define rollback criteria in advance.", "Keep reports on synthetic data."] },
      ],
      de: [
        { heading: "Kompatibilität vom Verbraucher her definieren", paragraphs: ["Ob eine Änderung bricht, hängt davon ab, was bestehende Clients senden und lesen, nicht nur von der Schema-Gültigkeit. Unterstützte Clients, historische Datensätze und Rückrollfenster werden zuerst dokumentiert.", "Neue Pflichtfelder, engere Typen oder entfernte Enum-Werte gefährden alte Produzenten. Auch optionale Felder können Clients mit strengem additionalProperties-Verhalten brechen."], bullets: ["Produzenten und Verbraucher erfassen.", "Kompatibilitätsfenster datieren.", "Nicht allein auf Versionsnummern vertrauen."] },
        { heading: "Dokumente mit gleichem Umfang vergleichen", paragraphs: ["Altes und neues JSON Schema müssen dasselbe Wurzelobjekt beschreiben. OpenAPI-Dokumente stammen aus vergleichbaren Umgebungen; sonst entstehen Fehlalarme.", "ByteQuant prüft direkte Felder, Pflichtstatus, Typen, Enums, Pfade, Methoden, Parameter und entfernte Antworten. Externe $ref und Bedingungen brauchen eine vollständige Auflösung."] },
        { heading: "Befunde mit anonymisierten Fixtures reproduzieren", paragraphs: ["Für jeden Befund werden kleinste nicht personenbezogene alte und neue Requests sowie Responses gespeichert. Fehlende Felder, unbekannte Enums, leere Arrays und große Payloads gehören neben den Normalfall.", "Ein Struktur-Diff beweist kein Verhalten. Defaults, Fehlercodes, Sortierung, Pagination und Autorisierung werden in Vertragstests beobachtet."] },
        { heading: "Brüche in Migrationen übersetzen", paragraphs: ["Erforderliche Brüche beginnen mit einer Übergangsphase: neues Feld optional akzeptieren, Produzenten migrieren, Nutzung messen und erst danach erzwingen. Entfernte Pfade benötigen Überschneidung, Frist und Warnung.", "Release Notes nennen Operation, altes und neues Verhalten, Migrationsbeispiel, Termin und Rückrollweg."] },
        { heading: "Release-Gate mit Nachweisen schließen", paragraphs: ["Lokale Vorprüfung, Fixtures, Verbrauchertests und Staging-Beobachtung werden in einem Datensatz verbunden. Freigabe und akzeptierte Risiken bleiben menschlich.", "Nach dem Release werden Fehlerraten und Alt-Clients beobachtet. Sensible Payloads und Zugangsdaten gehören nicht in Berichte oder CI-Logs."], bullets: ["Vorher/Nachher-Metriken verbinden.", "Rückrollkriterien vorab definieren.", "Synthetische Daten verwenden."] },
      ],
      zh: [
        { heading: "从消费者而非版本号定义兼容性", paragraphs: ["变更是否破坏契约取决于现有消费者实际发送和读取的内容，而不仅是新 Schema 是否有效。首先记录受支持客户端、历史持久化记录和回滚窗口。", "新增必填字段、类型收窄或删除枚举值常会影响旧生产者；即使新增可选字段，也可能破坏拒绝额外属性的消费者。"], bullets: ["盘点生产者与消费者。", "为兼容窗口写明日期。", "不要把决定交给版本标签。"] },
        { heading: "比较范围一致的文档", paragraphs: ["确认新旧 JSON Schema 描述同一个根对象。OpenAPI 应比较等价环境生成的文档，避免把线上契约与不完整本地文件混在一起。", "ByteQuant 检查直接属性、必填项、类型、枚举、路径、方法、参数必填和删除的响应；外部 $ref 与条件 Schema 需另行完整解析。"] },
        { heading: "用匿名样例复现每个候选项", paragraphs: ["为每项发现保存最小化且不含个人数据的旧请求、新请求、旧响应和新响应。除正常路径外，还要测试缺失字段、未知枚举、空数组和大 payload。", "结构差异不能证明行为；默认值、错误码、排序、分页和授权必须由契约测试观察。"] },
        { heading: "把破坏性变更转化为迁移计划", paragraphs: ["必须变更时，先发布允许新字段为可选项的过渡版本，迁移生产者并测量采用率，再启用强制要求。删除路径或响应时提供并行期、弃用日期和机器可读警告。", "发布说明应写明操作、旧行为、新行为、迁移示例、截止日期和回滚路径，而不只是‘Schema 已更新’。"] },
        { heading: "用证据关闭发布门禁", paragraphs: ["将本地预检、匿名样例、消费者测试和预发布环境观察合并在同一记录中，并明确批准者与接受的风险；自动工具不是决策者。", "发布后监控错误率、4xx 分布和旧客户端使用情况；不得把敏感 payload 或访问凭据写入报告、CI 日志或共享 URL。"], bullets: ["对应发布前后指标。", "预先定义回滚标准。", "报告只使用合成数据。"] },
      ],
    },
  },
  {
    slug: "csv-missingness-data-dictionary-workflow", date: "2026-08-11", relatedTools: ["csv-eksik-veri-deseni-analizoru", "veri-alani-sozlugu-olusturucu", "csv-sutun-profilleyici", "veri-minimizasyonu-karar-matrisi"],
    title: { tr: "Eksik CSV Verisini Anlamak ve Denetlenebilir Veri Sözlüğü Kurmak", en: "Understanding Missing CSV Data and Building an Auditable Data Dictionary", de: "Fehlende CSV-Daten verstehen und ein prüfbares Datenwörterbuch aufbauen", zh: "理解 CSV 缺失数据并建立可审计的数据字典" },
    excerpt: { tr: "Boş hücre sayımını; kaynak, amaç, örüntü, saklama ve karar kaydıyla gerçek veri kalitesi çalışmasına dönüştürün.", en: "Turn empty-cell counts into a real data-quality workflow with source, purpose, patterns, retention, and decisions.", de: "Machen Sie aus Leerzellen eine echte Datenqualitätsprüfung mit Quelle, Zweck, Mustern, Aufbewahrung und Entscheidungen.", zh: "把空单元格统计转化为包含来源、用途、模式、保留期和决策记录的数据质量流程。" },
    description: { tr: "CSV eksiklik örüntülerini doğru ayrıştırma, veri sözlüğü, minimizasyon ve insan onayıyla değerlendiren derin rehber.", en: "A deep guide to evaluating CSV missingness with correct parsing, a data dictionary, minimization, and human approval.", de: "Vertiefender Leitfaden zu CSV-Fehlwerten mit korrektem Parsing, Datenwörterbuch, Minimierung und menschlicher Freigabe.", zh: "深入指南：通过正确解析、数据字典、数据最小化和人工审批评估 CSV 缺失情况。" }, category: { tr: "Veri kalitesi", en: "Data quality", de: "Datenqualität", zh: "数据质量" },
    sections: {
      tr: [
        { heading: "Önce boş değerin dilini tanımlayın", paragraphs: ["Boş hücre, NA, null, tire ve sıfır aynı anlama gelmez. Kaynak sistemin dışa aktarma kuralını, anketin atlama mantığını ve alanın gerçekten zorunlu olup olmadığını sözlükte ayrı ayrı kaydedin.", "Örneğin NA bir ülkede 'uygulanamaz', başka bir tabloda geçerli eyalet kısaltması olabilir. Değeri bağlamdan koparıp otomatik eksik saymak sessiz veri kaybı üretir."], bullets: ["Eksik belirteçlerini alan bazında tanımlayın.", "Sıfır ile yokluğu ayırın.", "Kaynak sistem sürümünü kaydedin."] },
        { heading: "CSV'yi tablo görünümüne güvenmeden ayrıştırın", paragraphs: ["Virgül içeren tırnaklı hücre, kaçırılmış çift tırnak ve satır sonu içeren değerler basit split(',') işlemini bozar. Ön kontrol doğru tırnak ayrıştırması yapmalı, benzersiz başlık istemeli ve kapanmamış alanı açık hata olarak durdurmalıdır.", "Çok büyük dosyalarda örneklem kullanılıyorsa kapsam, satır seçme yöntemi ve limit belirtilmelidir. Örneklemde bulunmayan nadir eksiklik, tüm veri için 'temiz' sonucu verilmesini engeller."] },
        { heading: "Sütun oranından birlikte eksik örüntüye geçin", paragraphs: ["Tek bir sütunun yüzde 10 boş olması karar için yetersizdir. Şehir ve yaşın aynı satırlarda birlikte kaybolması, belirli kaynak kanalını veya koşullu form adımını gösterebilir.", "Örüntüyü kayıt kimliği, tarih, kaynak ve segment ile araştırın; fakat kişisel veriyi gereksiz yere kopyalamayın. Nedensellik iddiası için veri üretim sürecini ve örneklem yanlılığını ayrıca inceleyin."] },
        { heading: "Veri sözlüğünü yaşayan sözleşme yapın", paragraphs: ["Her alan için ad, tür, birim, amaç, hassasiyet, kaynak, sahip ve saklama kuralı bulunmalıdır. 'Analitik için' gibi geniş amaçlar test edilemez; hangi kararın veya metriğin alanı gerektirdiğini yazın.", "Yinelenen alan adları, belirsiz sonsuz saklama ve sahipsiz türetilmiş alanlar yayın kapısında görünür olmalıdır. Sözlük kod, rapor ve gizlilik envanteriyle aynı sürümde güncellenmelidir."] },
        { heading: "Doldurma yerine kararı ve belirsizliği belgeleyin", paragraphs: ["Ortalama, medyan veya en sık değerle doldurma dağılımı ve ilişkileri değiştirebilir. Eksikliğin tamamen rastgele, gözlenen değişkenlere bağlı veya gözlenmeyen sürece bağlı olması farklı yöntem gerektirir.", "Araç yalnızca nerede ve nasıl eksik olduğunu gösterir. Doldurma, satır dışlama veya yeniden toplama kararını alan uzmanı verir; orijinal değer, dönüşüm yöntemi, tarih ve geri alma yolu korunur."], bullets: ["Ham veriyi değiştirmeyin.", "Belirsizlik etkisini raporlayın.", "Kararı yeniden üretilebilir kaydedin."] },
      ],
      en: [
        { heading: "Define the language of missing values first", paragraphs: ["An empty cell, NA, null, a dash, and zero are not interchangeable. Record the source export rule, survey skip logic, and whether each field is truly required.", "NA may mean not applicable in one dataset and be a valid region code in another. Context-free replacement silently destroys data."], bullets: ["Define missing tokens per field.", "Separate zero from absence.", "Record the source-system version."] },
        { heading: "Parse CSV instead of trusting its visual shape", paragraphs: ["Quoted commas, escaped quotes, and embedded line breaks defeat split(','). A pre-check should parse quotes, require unique headers, and stop clearly on an unclosed field.", "When sampling large files, disclose coverage, row selection, and limits. A rare issue outside the sample prevents a claim that the complete dataset is clean."] },
        { heading: "Move from column rates to co-missing patterns", paragraphs: ["A column that is ten percent empty does not explain the problem. City and age disappearing in the same rows may point to a source channel or conditional form step.", "Investigate patterns with date, source, and segment while avoiding unnecessary personal-data copies. Causality still requires review of collection and sampling bias."] },
        { heading: "Make the data dictionary a living contract", paragraphs: ["Every field needs a name, type, unit, purpose, sensitivity, source, owner, and retention rule. 'For analytics' is too broad; name the decision or metric that requires the field.", "Duplicate names, indefinite retention, and ownerless derived fields belong in the release gate. Keep the dictionary versioned with code, reports, and the privacy inventory."] },
        { heading: "Document uncertainty before imputing", paragraphs: ["Mean, median, or mode imputation can change distributions and relationships. Missing completely at random, missing given observed values, and process-driven missingness call for different methods.", "The tool shows where and how data is absent; a domain owner chooses imputation, exclusion, or recollection. Preserve raw values, method, date, and rollback path."], bullets: ["Never overwrite raw data.", "Report uncertainty impact.", "Record decisions reproducibly."] },
      ],
      de: [
        { heading: "Zuerst die Bedeutung fehlender Werte definieren", paragraphs: ["Leere Zelle, NA, null, Bindestrich und Null sind nicht gleich. Exportregel, Sprunglogik und Pflichtstatus werden je Feld dokumentiert.", "NA kann 'nicht anwendbar' oder ein gültiger Code sein. Kontextloses Ersetzen zerstört Daten."], bullets: ["Fehlwertkennzeichen je Feld definieren.", "Null und Abwesenheit trennen.", "Quellsystemversion festhalten."] },
        { heading: "CSV korrekt parsen", paragraphs: ["Kommas in Anführungszeichen, doppelte Quotes und Zeilenumbrüche brechen split(','). Die Prüfung benötigt eindeutige Header und klare Fehler bei offenen Feldern.", "Bei Stichproben werden Abdeckung, Auswahl und Grenzen offengelegt. Ein sauberer Ausschnitt beweist keine saubere Gesamtdatei."] },
        { heading: "Gemeinsame Fehlmuster untersuchen", paragraphs: ["Eine Fehlrate pro Spalte erklärt die Ursache nicht. Gemeinsam fehlende Stadt- und Alterswerte können auf einen Kanal oder Formularpfad hinweisen.", "Muster werden mit Quelle und Segment untersucht, ohne unnötig personenbezogene Daten zu kopieren. Kausalität erfordert Prozessprüfung."] },
        { heading: "Datenwörterbuch als lebenden Vertrag führen", paragraphs: ["Felder brauchen Name, Typ, Einheit, Zweck, Sensibilität, Quelle, Verantwortung und Aufbewahrung. 'Für Analytics' ist kein prüfbarer Zweck.", "Duplikate, unbestimmte Aufbewahrung und verantwortungslose Ableitungen gehören ins Release-Gate."] },
        { heading: "Unsicherheit vor Imputation dokumentieren", paragraphs: ["Mittelwert oder Median verändern Verteilungen. Verschiedene Fehlmechanismen erfordern unterschiedliche Methoden.", "Das Werkzeug zeigt Muster; Fachverantwortliche entscheiden über Imputation, Ausschluss oder Neuerhebung. Rohdaten und Rückrollweg bleiben erhalten."], bullets: ["Rohdaten nie überschreiben.", "Unsicherheit berichten.", "Entscheidungen reproduzierbar halten."] },
      ],
      zh: [
        { heading: "先定义缺失值的语言", paragraphs: ["空单元格、NA、null、短横线和零不能互换。应逐字段记录源系统导出规则、问卷跳题逻辑以及是否真正必填。", "NA 在一个数据集中可能表示不适用，在另一个数据集中可能是有效代码；脱离语境替换会静默破坏数据。"], bullets: ["逐字段定义缺失标记。", "区分零与不存在。", "记录源系统版本。"] },
        { heading: "正确解析 CSV，而不是相信视觉形状", paragraphs: ["带引号的逗号、转义引号和嵌入换行会破坏 split(',')。预检应处理引号、要求唯一表头，并在字段未闭合时明确停止。", "对大文件抽样时要披露覆盖范围、选行方法和限制；样本干净不能证明全量数据干净。"] },
        { heading: "从列缺失率走向共同缺失模式", paragraphs: ["某列百分之十为空并不能解释原因。城市和年龄在同一批行中同时缺失，可能指向特定来源渠道或条件表单步骤。", "结合日期、来源和分群调查模式，同时避免不必要复制个人数据；因果结论仍需审查采集流程与抽样偏差。"] },
        { heading: "把数据字典当作持续更新的契约", paragraphs: ["每个字段都需要名称、类型、单位、用途、敏感性、来源、负责人和保留规则。‘用于分析’过于宽泛，应写明该字段支持的决策或指标。", "重复名称、无限期保留和无人负责的派生字段应进入发布门禁，并与代码、报告和隐私清单同步版本。"] },
        { heading: "填补之前先记录不确定性", paragraphs: ["均值、中位数或众数填补可能改变分布和关联。完全随机缺失、受已观测变量影响的缺失和流程驱动缺失需要不同方法。", "工具只展示缺失位置和模式；领域负责人决定填补、排除或重新采集，并保留原始值、方法、日期和回滚路径。"], bullets: ["绝不覆盖原始数据。", "报告不确定性影响。", "以可复现方式记录决策。"] },
      ],
    },
  },
  {
    slug: "accessible-markdown-html-table-publishing", date: "2026-08-11", relatedTools: ["markdown-baglanti-butunluk-denetleyici", "html-tablo-erisilebilirlik-denetleyici", "markdown-onizleyici", "baslik-hiyerarsisi-denetleyici"],
    title: { tr: "Erişilebilir Markdown ve HTML Tablo Yayınlama Kontrolü", en: "A Release Review for Accessible Markdown and HTML Tables", de: "Veröffentlichungsprüfung für barrierefreies Markdown und HTML-Tabellen", zh: "无障碍 Markdown 与 HTML 表格发布检查" },
    excerpt: { tr: "Bağlantı sözdizimi, güvenli hedef, tablo başlığı ve ekran okuyucu ilişkilerini tek yayın kapısında sınayın.", en: "Test link syntax, safe targets, table captions, and screen-reader relationships in one release gate.", de: "Prüfen Sie Links, sichere Ziele, Tabellenbeschriftungen und Screenreader-Beziehungen in einem Release-Gate.", zh: "在同一发布门禁中检查链接语法、安全目标、表格标题和屏幕阅读器关联。" },
    description: { tr: "Belge bağlantı bütünlüğü ve tablo erişilebilirliğini otomasyon ile gerçek klavye/ekran okuyucu testine bağlayan ayrıntılı rehber.", en: "A detailed guide connecting document link integrity and table accessibility automation to real keyboard and screen-reader testing.", de: "Detaillierter Leitfaden, der Linkintegrität und Tabellenprüfung mit realen Tastatur- und Screenreader-Tests verbindet.", zh: "详细指南：把文档链接完整性和表格无障碍自动检查连接到真实键盘与屏幕阅读器测试。" }, category: { tr: "Erişilebilir yayıncılık", en: "Accessible publishing", de: "Barrierefreies Publizieren", zh: "无障碍发布" },
    sections: {
      tr: [
        { heading: "Bağlantının metni hedefi açıklamalıdır", paragraphs: ["'Buraya tıklayın' veya çıplak URL, bağlantı listesini kullanan okuyucuya bağlam vermez. Metin, hedefi ve mümkünse dosya türü ya da dış site bilgisini kısa biçimde anlatmalıdır.", "Aynı görünen metni farklı hedefler için tekrar kullanmayın. Yeni sekme, indirme veya dil değişimi beklenmedikse görünür olarak belirtilmelidir."], bullets: ["Bağlantıyı cümleden bağımsız okuyun.", "Hedef türünü gerektiğinde belirtin.", "Klavye odağını görünür tutun."] },
        { heading: "Referans ve URL sözdizimini yerelde doğrulayın", paragraphs: ["Tanımsız referans kimliği veya yinelenen tanım, Markdown motoruna göre sessiz düz metne ya da yanlış hedefe dönüşebilir. javascript:, data: ve benzeri yürütülebilir şemalar kullanıcı içeriğinde reddedilmelidir.", "Yerel araç ağ isteği yapmadığı için 404, yönlendirme, TLS ve hedef sayfa sahipliğini doğrulamaz. Bu kontroller yayın CI'ında sınırlı hız ve izinli alan politikasıyla ayrıca yapılmalıdır."] },
        { heading: "Tabloyu yalnızca gerçekten tablo olan veri için kullanın", paragraphs: ["İki boyutlu ilişkisi olmayan içeriği hizalamak için tablo kullanmak mobil ve ekran okuyucu deneyimini bozar. Basit başlık-değer listesi definition list, kart veya düz metin olarak daha iyi olabilir.", "Gerçek veri tablosu kısa bir caption ile amacını anlatmalı; sütun ve satır başlıkları th olmalı, scope ilişkisi basit tabloda açıkça verilmelidir."] },
        { heading: "Karmaşık tabloda ilişkiyi ve mobil davranışı tasarlayın", paragraphs: ["Çok seviyeli başlık, birleşik hücre ve ara toplam içeren tabloda scope tek başına yeterli olmayabilir; id/headers ilişkisi ve daha basit alternatif görünüm düşünülmelidir. Başlıklar görsel kalınlığa değil semantik işaretlemeye dayanmalıdır.", "Dar ekranda yatay kaydırma bölgesi odaklanabilir ve etiketli olmalı; ilk sütunu sabitlemek içeriği örtmemelidir. Veri kaybına yol açan CSS ile sütun gizleme yerine özet görünüm ve tam tablo bağlantısı sunun."] },
        { heading: "Otomasyonu gerçek kullanım testiyle kapatın", paragraphs: ["Statik denetim caption, th ve scope eksiklerini bulabilir; doğru okuma sırası, anlaşılır bağlantı metni ve büyütmede taşma için gerçek tarayıcı gerekir. Klavye, ekran okuyucu, yüzde 200 yakınlaştırma ve koyu/açık tema ile test edin.", "Bulguya ekran görüntüsü değil tekrar üretim adımı, etkilenen kullanıcı, beklenen davranış ve düzeltme kabul ölçütü ekleyin. WCAG uygunluğu tek bir araç çıktısıyla ilan edilmemelidir."], bullets: ["En az bir gerçek yardımcı teknoloji testi yapın.", "Mobil kaydırmayı klavyeyle deneyin.", "Düzeltmeyi aynı fixture ile yeniden sınayın."] },
      ],
      en: [
        { heading: "Link text should explain its destination", paragraphs: ["'Click here' or a raw URL gives little context to someone navigating a list of links. Text should briefly name the destination and, where useful, its file type or external-site status.", "Do not reuse identical visible text for different destinations. Unexpected new tabs, downloads, or language changes should be disclosed."], bullets: ["Read the link outside its sentence.", "Name destination type when useful.", "Keep keyboard focus visible."] },
        { heading: "Validate references and URL syntax locally", paragraphs: ["Undefined reference identifiers and duplicate definitions may become plain text or the wrong target depending on the Markdown engine. Reject executable schemes such as javascript: and data: in user content.", "A local tool makes no request, so it cannot verify 404 status, redirects, TLS, or destination ownership. Add bounded network checks in publishing CI under an allowlist policy."] },
        { heading: "Use a table only for genuinely tabular data", paragraphs: ["Using tables to align content without a two-dimensional relationship harms mobile and screen-reader use. A definition list, cards, or prose may fit simple label-value content better.", "A data table needs a concise caption, semantic th cells, and explicit scope relationships for straightforward row and column headers."] },
        { heading: "Design relationships and mobile behavior for complex tables", paragraphs: ["Multi-level headers, merged cells, and subtotals may require id/headers relationships or a simpler alternate view. Visual boldness does not replace semantic headers.", "On narrow screens, the horizontal scroll region should be focusable and labeled. Avoid hiding columns with CSS when that removes meaning; offer a summary plus the complete table instead."] },
        { heading: "Close automation with real-use testing", paragraphs: ["Static review finds missing caption, th, and scope, but reading order, understandable links, and zoom overflow require a real browser. Test keyboard, screen reader, 200% zoom, and both color themes.", "Record reproduction, affected user, expected behavior, and acceptance criteria rather than only a screenshot. One tool output cannot establish WCAG conformance."], bullets: ["Run at least one assistive-technology test.", "Try mobile scrolling by keyboard.", "Retest with the same fixture."] },
      ],
      de: [
        { heading: "Linktext erklärt das Ziel", paragraphs: ["'Hier klicken' oder rohe URLs geben in Linklisten keinen Kontext. Der Text nennt Ziel und bei Bedarf Dateityp oder externe Website.", "Gleicher sichtbarer Text sollte nicht zu verschiedenen Zielen führen. Neue Tabs, Downloads oder Sprachwechsel werden angekündigt."], bullets: ["Link außerhalb des Satzes lesen.", "Zieltyp bei Bedarf nennen.", "Tastaturfokus sichtbar halten."] },
        { heading: "Referenzen und URL-Syntax lokal prüfen", paragraphs: ["Undefinierte Referenzen und doppelte Definitionen können zu Text oder falschen Zielen werden. javascript: und data: werden in Nutzerinhalten abgelehnt.", "Ohne Netzwerkanfrage werden 404, Weiterleitungen, TLS und Eigentum nicht geprüft; begrenzte CI-Checks ergänzen dies."] },
        { heading: "Tabellen nur für tabellarische Daten", paragraphs: ["Layout-Tabellen schaden Mobil- und Screenreader-Nutzung. Für einfache Label-Werte eignen sich Definitionslisten oder Karten besser.", "Datentabellen brauchen caption, semantische th-Zellen und scope für einfache Zeilen- und Spaltenköpfe."] },
        { heading: "Komplexe Beziehungen und Mobilverhalten gestalten", paragraphs: ["Mehrstufige Köpfe und verbundene Zellen benötigen möglicherweise id/headers oder eine einfachere Alternativansicht. Fettdruck ersetzt keine Semantik.", "Horizontales Scrollen muss fokussierbar und beschriftet sein. Spalten sollten nicht bedeutungsverlustig per CSS verschwinden."] },
        { heading: "Automatik mit realen Tests abschließen", paragraphs: ["Lesereihenfolge, Linkverständnis und Zoom-Überlauf brauchen Browser, Tastatur und Screenreader. Testen Sie außerdem 200 Prozent Zoom und beide Themes.", "Dokumentieren Sie Reproduktion, betroffene Nutzer und Akzeptanzkriterien. Ein Werkzeug beweist keine WCAG-Konformität."], bullets: ["Hilfstechnologie testen.", "Mobil per Tastatur scrollen.", "Mit gleichem Fixture erneut testen."] },
      ],
      zh: [
        { heading: "链接文本应说明目标", paragraphs: ["‘点击这里’或裸 URL 无法为通过链接列表导航的读者提供上下文。文本应简要说明目标，并在有用时标明文件类型或外部网站。", "不要让相同可见文本指向不同目标；意外的新标签页、下载或语言变化应明确告知。"], bullets: ["脱离句子单独阅读链接。", "需要时标明目标类型。", "保持键盘焦点可见。"] },
        { heading: "在本地验证引用与 URL 语法", paragraphs: ["未定义引用标识和重复定义可能因 Markdown 引擎不同而变成纯文本或错误目标。用户内容中的 javascript:、data: 等可执行协议应被拒绝。", "本地工具不发起网络请求，因此无法验证 404、重定向、TLS 或目标所有权；发布 CI 应在允许列表和限速下补充检查。"] },
        { heading: "只为真正的表格数据使用表格", paragraphs: ["为对齐非二维关系内容而使用表格会损害移动端和屏幕阅读器体验。简单标签-值内容更适合定义列表、卡片或正文。", "数据表需要简洁 caption、语义化 th，并为简单行列标题明确提供 scope。"] },
        { heading: "设计复杂关联和移动行为", paragraphs: ["多级表头、合并单元格和小计可能需要 id/headers 关联或更简单的替代视图。视觉加粗不能替代语义表头。", "窄屏横向滚动区域应可聚焦且有标签；不要用 CSS 隐藏导致信息丢失的列，可提供摘要和完整表格入口。"] },
        { heading: "用真实使用测试完成自动化检查", paragraphs: ["静态检查可发现 caption、th 和 scope 缺失，但阅读顺序、链接可理解性和缩放溢出需要真实浏览器。测试键盘、屏幕阅读器、200% 缩放和深浅主题。", "问题记录应包含复现步骤、受影响用户、预期行为和验收标准，而不仅是截图；单一工具输出不能证明符合 WCAG。"], bullets: ["至少执行一次辅助技术测试。", "用键盘尝试移动端滚动。", "使用同一 fixture 复测。"] },
      ],
    },
  },
  {
    slug: "private-cache-and-debt-scenario-boundaries", date: "2026-08-11", relatedTools: ["http-vary-cache-anahtari-denetleyici", "borc-odeme-stratejisi-karsilastirici", "http-guvenlik-basliklari-denetleyici", "kredi-amortisman-tahminleyici"],
    title: { tr: "Ön Kontrol Sonucunu Garantiye Dönüştürmeden Kullanmak: Cache ve Borç Senaryoları", en: "Using Pre-Checks Without Turning Them Into Guarantees: Cache and Debt Scenarios", de: "Vorprüfungen ohne falsche Garantien nutzen: Cache- und Schuldenszenarien", zh: "在不制造虚假保证的前提下使用预检：缓存与债务情景" },
    excerpt: { tr: "Teknik güvenlik ve finans hesaplarında varsayımı, doğrulama sınırını ve gerçek karar sahibini görünür tutun.", en: "Keep assumptions, verification limits, and the real decision owner visible in technical-security and finance calculations.", de: "Halten Sie Annahmen, Prüfgrenzen und echte Verantwortliche bei Sicherheits- und Finanzrechnungen sichtbar.", zh: "在技术安全与财务计算中明确展示假设、验证边界和真正的决策负责人。" },
    description: { tr: "HTTP önbellek sızıntısı sinyalleri ile sabit oranlı borç simülasyonlarını dürüst sınırlar ve gerçek doğrulama adımlarıyla ele alan rehber.", en: "A guide to HTTP cache-leak signals and fixed-rate debt simulations with honest limits and real verification steps.", de: "Leitfaden zu HTTP-Cache-Leak-Signalen und Festzins-Schuldensimulationen mit ehrlichen Grenzen und realer Verifikation.", zh: "指南：以诚实边界和真实验证步骤处理 HTTP 缓存泄漏信号与固定利率债务模拟。" }, category: { tr: "Sorumlu karar desteği", en: "Responsible decision support", de: "Verantwortliche Entscheidungshilfe", zh: "负责任的决策支持" },
    sections: {
      tr: [
        { heading: "Aynı raporda olsalar da risk türlerini karıştırmayın", paragraphs: ["Cache denetimi bir yapılandırma ve veri sızıntısı ön kontrolüdür; borç simülasyonu ise matematiksel bir senaryo karşılaştırmasıdır. İkisi de açıklanabilir hesap üretir fakat ne güvenlik sertifikası ne de finansal tavsiye verir.", "Her sonuçta kullanılan veri, varsayım, dışarıda bırakılan etken ve kararı verecek kişi ayrı gösterilmelidir. Bu çerçeve, kullanıcıya aracın yeteneğini küçültmeden yanlış kesinlik üretmeyi önler."], bullets: ["Yöntemi bir cümlede yazın.", "Sınırı sonuç yanında gösterin.", "Karar sahibini otomasyondan ayırın."] },
        { heading: "Cache anahtarını kişiselleştirme sinyalleriyle birlikte okuyun", paragraphs: ["Authorization, Cookie, Set-Cookie, Content-Language ve içerik kodlaması aynı yanıtın farklı temsilini yaratabilir. public önbellek ile kişisel oturum sinyalinin birleşmesi yüksek öncelikli inceleme gerektirir.", "Vary yalnızca hangi istek başlıklarının anahtara katılacağını bildirir; CDN'nin gerçekten bunu uyguladığını kanıtlamaz. Cache-Control, surrogate kuralı, CDN varsayılanı ve uygulama kodu birlikte gözlenmelidir."] },
        { heading: "Çok kullanıcılı canlı test tasarlayın", paragraphs: ["Sentetik iki kullanıcı oluşturun ve yanıtları farklı kimlik, dil ve yetki düzeyiyle sırayla isteyin. Age, Cache-Status, Vary ve gövde kimliğini kaydedin; gerçek hesap, token veya kişisel veri kullanmayın.", "İlk kullanıcının temsilinin ikinci kullanıcıya dönmesi kritik bulgudur. Yalnızca tek tarayıcı oturumundaki başarılı test, paylaşımlı cache davranışını kanıtlamaz."] },
        { heading: "Borç stratejisini aynı bütçe ve açık formülle karşılaştırın", paragraphs: ["Kartopu yöntemi en küçük bakiyeye, çığ yöntemi en yüksek yıllık orana ek ödemeyi yönlendirir. Adil karşılaştırma için başlangıç bakiyesi, minimumlar, aylık bütçe, faiz bileşik zamanı ve yuvarlama iki senaryoda aynı olmalıdır.", "Düşük faizli yöntemin psikolojik sürdürülebilirliği, yüksek faizli yöntemin matematiksel maliyeti ve nakit akışı ayrı boyutlardır. Araç ay sayısı ve tahmini faiz farkını gösterir; kullanıcının önceliğini seçmez."] },
        { heading: "Gerçek sözleşme ve üretim davranışıyla kapatın", paragraphs: ["Borç sözleşmesinde değişken oran, gecikme, erken ödeme, sigorta ve vergi; cache ortamında CDN katmanı, tarayıcı önbelleği, servis çalışanı ve origin davranışı sonucu değiştirebilir. Ön kontrolün ardından gerçek belge veya ortam doğrulanmalıdır.", "Karar kaydına tarih, sürüm, sentetik fixture, kabul edilen sınır ve yeniden inceleme koşulu ekleyin. Hassas başlıkları veya finansal hesap dökümlerini paylaşılabilir rapora taşımayın."], bullets: ["Canlı davranışı güvenli sentetik veride sınayın.", "Sözleşme maddelerini yetkili kaynaktan okuyun.", "Değişen koşulda hesabı yeniden çalıştırın."] },
      ],
      en: [
        { heading: "Do not confuse risk types just because they share a report", paragraphs: ["A cache review is a configuration and data-leak pre-check; a debt simulation is a mathematical scenario comparison. Both are explainable, but neither provides a security certificate or financial advice.", "Show input, assumptions, excluded factors, and the human decision owner beside every result. This avoids false certainty without hiding what the tool can do."], bullets: ["State the method in one sentence.", "Place limits beside the result.", "Separate decision owner from automation."] },
        { heading: "Read cache keys together with personalization signals", paragraphs: ["Authorization, Cookie, Set-Cookie, Content-Language, and encoding can create different representations of one URL. A public cache combined with a personal-session signal deserves high-priority review.", "Vary declares request-header dimensions but does not prove that a CDN honors them. Cache-Control, surrogate rules, CDN defaults, and application code need observation together."] },
        { heading: "Design a multi-user live test", paragraphs: ["Create two synthetic users and request responses sequentially with different identity, language, and authorization levels. Record Age, Cache-Status, Vary, and a safe body identifier—never real accounts or tokens.", "Receiving the first user's representation for the second is critical. A successful single-session test cannot prove shared-cache isolation."] },
        { heading: "Compare debt strategies with one budget and explicit formulas", paragraphs: ["Snowball directs extra payment to the smallest balance; avalanche directs it to the highest APR. Keep starting balances, minimums, budget, interest timing, and rounding identical.", "Psychological sustainability, mathematical cost, and cash flow are separate dimensions. The tool exposes months and estimated interest; it does not choose the user's priority."] },
        { heading: "Close with real contracts and deployed behavior", paragraphs: ["Variable rates, late fees, prepayment, insurance, and taxes can change debt outcomes. CDN layers, browser caches, service workers, and origin behavior can change cache results. Verify the real document or environment after the pre-check.", "Record date, version, synthetic fixture, accepted boundary, and re-review trigger. Do not move sensitive headers or account statements into shareable reports."], bullets: ["Test deployed behavior with safe synthetic data.", "Read contract terms from authoritative sources.", "Re-run when assumptions change."] },
      ],
      de: [
        { heading: "Risikotypen nicht vermischen", paragraphs: ["Cache-Prüfung bewertet Konfiguration und mögliche Datenlecks; Schuldensimulation vergleicht mathematische Szenarien. Beides ist erklärbar, aber weder Zertifikat noch Finanzberatung.", "Eingaben, Annahmen, Ausschlüsse und menschliche Verantwortung stehen bei jedem Ergebnis."], bullets: ["Methode kurz nennen.", "Grenzen neben das Ergebnis setzen.", "Entscheidung und Automatik trennen."] },
        { heading: "Cache-Key und Personalisierung gemeinsam lesen", paragraphs: ["Authorization, Cookie, Set-Cookie, Sprache und Kodierung erzeugen Varianten. Öffentlicher Cache plus Sitzungssignal verlangt hohe Priorität.", "Vary erklärt Dimensionen, beweist aber keine CDN-Umsetzung. Cache-Control, Surrogate-Regeln und Anwendung werden gemeinsam beobachtet."] },
        { heading: "Mehrbenutzertest entwerfen", paragraphs: ["Zwei synthetische Nutzer fragen mit unterschiedlichen Identitäten, Sprachen und Rechten ab. Age, Cache-Status, Vary und sichere Inhaltskennung werden protokolliert.", "Daten des ersten Nutzers beim zweiten sind kritisch. Ein Einzeltest beweist keine Isolation."] },
        { heading: "Tilgungsstrategien fair vergleichen", paragraphs: ["Schneeball priorisiert kleinste Salden, Lawine höchste Zinsen. Salden, Mindestzahlungen, Budget, Zinszeitpunkt und Rundung bleiben identisch.", "Motivation, Kosten und Cashflow sind verschiedene Dimensionen. Das Werkzeug wählt keine persönliche Priorität."] },
        { heading: "Mit Vertrag und realem Verhalten abschließen", paragraphs: ["Variable Zinsen und Gebühren verändern Schulden; CDN, Browsercache, Service Worker und Origin verändern Cache-Ergebnisse. Nach der Vorprüfung folgt reale Verifikation.", "Datum, Version, synthetisches Fixture, Grenze und erneuter Prüfauslöser werden dokumentiert. Keine sensiblen Header oder Kontoauszüge teilen."], bullets: ["Synthetisch live testen.", "Verträge autoritativ prüfen.", "Bei Annahmeänderung neu rechnen."] },
      ],
      zh: [
        { heading: "不要因为出现在同一报告就混淆风险类型", paragraphs: ["缓存检查是配置与数据泄漏预检，债务模拟是数学情景比较。两者都可解释，但既不是安全证书，也不是财务建议。", "每个结果旁都应展示输入、假设、排除因素和人工决策负责人，以避免虚假确定性。"], bullets: ["用一句话说明方法。", "在结果旁显示边界。", "把决策者与自动化分开。"] },
        { heading: "结合个性化信号理解缓存键", paragraphs: ["Authorization、Cookie、Set-Cookie、Content-Language 和编码可能为同一 URL 产生不同表示。公开缓存与个人会话信号结合时需高优先级审查。", "Vary 只声明请求头维度，不能证明 CDN 真正遵守；应共同观察 Cache-Control、代理规则、CDN 默认值和应用代码。"] },
        { heading: "设计多用户线上测试", paragraphs: ["创建两个合成用户，以不同身份、语言和授权级别依次请求，并记录 Age、Cache-Status、Vary 和安全的正文标识；绝不使用真实账户或 token。", "若第二个用户收到第一个用户的表示，这是严重问题；单会话成功测试无法证明共享缓存隔离。"] },
        { heading: "用相同预算和明确公式比较债务策略", paragraphs: ["雪球法把额外还款投向最小余额，雪崩法投向最高年利率。起始余额、最低还款、预算、计息时间和取整方式必须一致。", "心理可持续性、数学成本和现金流是不同维度；工具展示月份和估算利息，不替用户选择优先级。"] },
        { heading: "以真实合同和部署行为收尾", paragraphs: ["浮动利率、滞纳金、提前还款、保险和税费会改变债务结果；CDN 层、浏览器缓存、Service Worker 和源站行为会改变缓存结果。预检后必须验证真实文档或环境。", "记录日期、版本、合成样例、接受边界和复审触发条件，不要把敏感请求头或账户账单放入可分享报告。"], bullets: ["使用安全合成数据测试线上行为。", "从权威来源阅读合同条款。", "假设变化时重新计算。"] },
      ],
    },
  },
];

const relatedToolsSection = (seed: Seed, locale: keyof Pair): ArticleSection => ({
  heading: locale === "tr" ? "Bu rehberle birlikte kullanabileceğiniz araçlar" : locale === "de" ? "Werkzeuge für diesen Ablauf" : locale === "zh" ? "本指南配套工具" : "Tools used in this workflow",
  paragraphs: [locale === "tr" ? "Aşağıdaki araçlar aynı kararın farklı kanıtlarını üretir. Her çıktıyı gerçek ortam, sözleşme veya yetkili kaynakla ayrıca doğrulayın." : locale === "de" ? "Diese Werkzeuge liefern unterschiedliche Nachweise für dieselbe Entscheidung. Prüfen Sie jedes Ergebnis zusätzlich in der realen Umgebung, im Vertrag oder anhand einer maßgeblichen Quelle." : locale === "zh" ? "下列工具为同一决策提供不同证据。请结合真实环境、合同或权威来源分别核验每项输出；先用合成数据复现流程，再记录人工验收标准与停止条件。" : "These tools produce different evidence for the same decision. Verify every result against the real environment, contract, or an authoritative source."],
  bullets: seed.relatedTools.map((slug) => {
    const tool = publicTools.find((candidate) => candidate.slug === slug);
    if (!tool) throw new Error(`Stage 2 guide ${seed.slug} references missing tool ${slug}`);
    return tool.title[locale];
  }),
});

export const stageTwoPosts: Post[] = seeds.map((seed) => ({
  slug: seed.slug, date: seed.date, updated: seed.date, relatedTools: seed.relatedTools,
  readTime: { tr: "14 dk", en: "13 min" }, title: { tr: seed.title.tr, en: seed.title.en }, excerpt: { tr: seed.excerpt.tr, en: seed.excerpt.en }, description: { tr: seed.description.tr, en: seed.description.en }, category: { tr: seed.category.tr, en: seed.category.en }, visualSuggestion: { tr: "Girdi, yerel ön kontrol, insan doğrulaması ve yayın kararını ayıran dört aşamalı akış.", en: "A four-stage flow separating input, local pre-check, human verification, and release decision." }, sections: { tr: [...seed.sections.tr, relatedToolsSection(seed, "tr")], en: [...seed.sections.en, relatedToolsSection(seed, "en")] },
}));

export const stageTwoLocalizedGuides: LocalizedGuide[] = seeds.map((seed) => ({
  slug: seed.slug, date: seed.date, updated: seed.date, relatedTools: seed.relatedTools,
  copy: {
    de: { title: seed.title.de, excerpt: seed.excerpt.de, description: seed.description.de, category: seed.category.de, readTime: "13 Min.", sections: [...seed.sections.de, relatedToolsSection(seed, "de")] },
    zh: { title: seed.title.zh, excerpt: seed.excerpt.zh, description: seed.description.zh, category: seed.category.zh, readTime: "约 13 分钟", sections: [...seed.sections.zh, relatedToolsSection(seed, "zh")] },
  },
}));
