import type { Locale } from "./site";
import type { ArticleSection, Post } from "./posts";
import type { LocalizedGuide } from "./localized-guides";

type L = Record<Locale, string>;
type Guide = { slug: string; relatedTools: string[]; title: L; excerpt: L; category: L; outcome: L; practice: L; failure: L; evidence: L; boundary: L };
const l = (tr: string, en: string, de: string, zh: string): L => ({ tr, en, de, zh });

const guides: Guide[] = [
  {
    slug: "dayanikli-api-retry-webhook-teslim-rehberi", relatedTools: ["retry-after-geri-cekilme-planlayici", "webhook-teslim-gunlugu-analizoru", "http-durum-kodu-rehberi", "api-sayfalama-planlayici"],
    title: l("Dayanıklı API Retry ve Webhook Teslimi: 429'dan İdempotency Kanıtına", "Reliable API Retries and Webhook Delivery: From 429 to Idempotency Evidence", "Zuverlässige API-Retries und Webhooks: Von 429 zum Idempotenznachweis", "可靠 API 重试与 Webhook 投递：从 429 到幂等证据"),
    excerpt: l("Retry-After, üstel geri çekilme, jitter, teslim kimliği ve zaman sırasını tek bir sınanabilir hata kurtarma sözleşmesinde birleştirin.", "Combine Retry-After, exponential backoff, jitter, delivery identity, and ordering in one testable recovery contract.", "Retry-After, exponentielles Backoff, Jitter, Zustell-ID und Reihenfolge in einem testbaren Recovery-Vertrag verbinden.", "把 Retry-After、指数退避、抖动、投递标识与顺序整合为可测试的恢复契约。"),
    category: l("API güvenilirliği", "API reliability", "API-Zuverlässigkeit", "API 可靠性"),
    outcome: l("429 ve 503 yanıtlarında güvenli yeniden deneme zamanını hesaplayan, POST tekrarlarını idempotency key olmadan durduran ve aynı webhook olayının son durumunu teslim günlüğünden uzlaştıran bir istemci tasarlamak.", "Design a client that calculates safe retry timing for 429 and 503, blocks automatic POST retries without an idempotency key, and reconciles each webhook event's final state from delivery logs.", "Einen Client entwerfen, der 429/503 sicher wiederholt, POST ohne Idempotency-Key stoppt und Webhook-Endzustände aus Protokollen abgleicht.", "设计客户端：计算 429/503 的安全重试时间、无幂等键时阻止自动重试 POST，并从投递日志核对每个 Webhook 事件的最终状态。"),
    practice: l("Güvenli/idempotent yöntemi, azami deneme sayısını, toplam süre tavanını, Retry-After önceliğini ve jitter aralığını yapılandırma dosyasında açıkça belirtin. Her teslimde kararlı olay kimliği, deneme numarası, UTC zaman, durum ve gecikme kaydedin; gövdeyi veya sırrı loglamayın.", "Declare safe/idempotent methods, maximum attempts, total time ceiling, Retry-After precedence, and jitter range in configuration. Record a stable event id, attempt number, UTC time, status, and latency for each delivery without logging bodies or secrets.", "Sichere Methoden, Versuchsgrenze, Zeitlimit, Retry-After-Vorrang und Jitter konfigurieren. Pro Zustellung stabile ID, Versuch, UTC-Zeit, Status und Latenz ohne Body oder Secrets protokollieren.", "在配置中明确安全/幂等方法、最大次数、总时长上限、Retry-After 优先级与抖动范围。每次投递记录稳定事件 ID、尝试次数、UTC 时间、状态与延迟，但不记录正文或密钥。"),
    failure: l("En yaygın arıza, her 4xx'i tekrar etmek, Retry-After'ı yok saymak, aynı olayı iki kez işlemek ve başarısız teslimi başarı saymaktır. Saat sapması, sıra dışı teslim, kısmi ağ kesintisi, yinelenen 2xx ve gecikmiş 200 yanıtı ayrı negatif testler olmalıdır.", "Common failures include retrying every 4xx, ignoring Retry-After, processing one event twice, and treating an exhausted delivery as success. Clock skew, out-of-order delivery, partial outages, repeated 2xx, and a late 200 need separate negative tests.", "Häufige Fehler sind Retry aller 4xx, ignoriertes Retry-After, doppelte Verarbeitung und falscher Erfolg. Uhrabweichung, Reihenfolgefehler, Teilausfall, doppelte 2xx und verspätete 200 separat testen.", "常见故障包括重试所有 4xx、忽略 Retry-After、重复处理同一事件以及把耗尽重试视为成功。时钟偏差、乱序、部分中断、重复 2xx 与迟到的 200 都应单独做负面测试。"),
    evidence: l("Kabul kaydı; her olay için tek iş etkisi, izin verilen toplam deneme, son durum, ilk başarı gecikmesi, tekrar oranı ve operatör uyarısını içermelidir. Sentetik test olayını üretim kaydından ayırın ve idempotency tablosunu olay kimliğiyle sorgulayarak sonucu uzlaştırın.", "Acceptance evidence should contain one business effect per event, allowed attempts, final state, time to first success, duplicate rate, and operator alert. Separate synthetic events from production records and reconcile the idempotency store by event id.", "Der Abnahmenachweis enthält genau einen Geschäftseffekt je Ereignis, Versuche, Endstatus, Zeit bis Erfolg, Duplikatrate und Alarm. Synthetische Ereignisse trennen und Idempotenzspeicher per ID abgleichen.", "验收证据应包含每个事件仅一次业务影响、允许尝试次数、最终状态、首次成功时间、重复率与运维告警。区分合成事件与生产记录，并按事件 ID 核对幂等存储。"),
    boundary: l("Yerel planlayıcı canlı ağ, kuyruk, imza, TLS veya sunucu saatini doğrulamaz. Güvenilirlik sonucu ancak kontrollü entegrasyon ve hata enjeksiyonu testleriyle kanıtlanabilir.", "The local planner verifies no live network, queue, signature, TLS, or server clock. Reliability requires controlled integration and fault-injection tests.", "Der lokale Planer prüft weder Netzwerk, Queue, Signatur, TLS noch Serverzeit. Zuverlässigkeit braucht Integrations- und Fehlerinjektionstests.", "本地规划器不验证真实网络、队列、签名、TLS 或服务器时钟；可靠性必须通过受控集成与故障注入测试证明。"),
  },
  {
    slug: "erisebilir-html-dil-baslik-form-rehberi", relatedTools: ["aria-erisebilir-ad-envanteri", "html-dil-baslik-yapisi-denetleyici", "renk-kontrast-denetleyici", "baslik-hiyerarsisi-denetleyici"],
    title: l("Erişilebilir HTML Yayın Rehberi: Dil, Başlıklar, Formlar ve Erişilebilir Ad", "Accessible HTML Publishing: Language, Headings, Forms, and Accessible Names", "Barrierefreies HTML: Sprache, Überschriften, Formulare und Namen", "无障碍 HTML 发布：语言、标题、表单与可访问名称"),
    excerpt: l("Bir sayfanın görsel olarak düzgün görünmesinin ötesine geçin; dil, başlık akışı, kontrol adı, klavye ve hata durumlarını görev temelli doğrulayın.", "Go beyond visual polish and validate language, heading flow, control names, keyboard use, and errors through real tasks.", "Über visuelle Qualität hinaus Sprache, Überschriften, Namen, Tastatur und Fehler anhand echter Aufgaben prüfen.", "超越视觉整洁，通过真实任务验证语言、标题流程、控件名称、键盘操作与错误状态。"),
    category: l("Erişilebilir içerik tasarımı", "Accessible content design", "Barrierefreies Content Design", "无障碍内容设计"),
    outcome: l("Dört dilde doğru html lang kullanan, tek açıklayıcı H1'e sahip, başlık seviyesi atlamayan ve her etkileşimli kontrolü görünür/erişilebilir ad ile hata yardımına bağlayan bir sayfa şablonu yayınlamak.", "Publish a four-language template with correct html lang, one descriptive H1, no heading-level jumps, and every interactive control connected to a visible or accessible name and useful error help.", "Ein viersprachiges Template mit korrektem lang, einer H1, lückenloser Hierarchie und benannten Kontrollen samt Fehlerhilfe veröffentlichen.", "发布四语言页面模板：正确 html lang、一个描述性 H1、无标题跳级，并为每个交互控件提供可见或可访问名称及有效错误帮助。"),
    practice: l("Belge dilini sayfa kökünde, dil değişimini bölümde işaretleyin. Başlığı kullanıcının göreviyle başlatın; H2'leri ana adımlara, H3'leri alt kararlara ayırın. Form etiketini placeholder yerine kullanın, ikon düğmeye eylemi anlatan ad verin ve hata metnini aria-describedby ile ilgili alana bağlayın.", "Set document language at the root and mark language changes at the relevant span. Lead the title with the user's task, reserve H2 for major steps and H3 for sub-decisions. Use labels rather than placeholders, name icon buttons by action, and connect error help through aria-describedby.", "Dokumentsprache am Root und Sprachwechsel am Abschnitt markieren. Titel an der Nutzeraufgabe ausrichten, H2 für Hauptschritte, H3 für Unterentscheidungen. Labels statt Placeholder und Fehlerhilfe per aria-describedby verbinden.", "在根元素设置文档语言，并在相应片段标记语言变化。标题从用户任务出发，H2 表示主要步骤，H3 表示子决策。使用 label 而非 placeholder，为图标按钮提供动作名称，并通过 aria-describedby 关联错误帮助。"),
    failure: l("Sık hatalar; yalnız renkle durum anlatmak, odak göstergesini kaldırmak, aynı aria-label'i çok sayıda düğmede kullanmak, gizli başlıkla görsel başlığın farklı olması ve hata sonrası odağı kaybetmektir. %200 yakınlaştırma, uzun Almanca metin, Çince satır kırılması ve ekran klavyesi açıkken taşma ayrıca sınanmalıdır.", "Frequent failures include colour-only status, removed focus indicators, repeated aria-label values, hidden names that disagree with visible labels, and lost focus after errors. Also test 200% zoom, long German copy, Chinese line breaking, and mobile overflow with the on-screen keyboard.", "Häufige Fehler: Status nur per Farbe, fehlender Fokus, wiederholte aria-labels, abweichende sichtbare/versteckte Namen und Fokusverlust nach Fehlern. Zusätzlich 200 % Zoom, lange deutsche Texte, chinesische Umbrüche und Bildschirmtastatur testen.", "常见错误包括仅用颜色表达状态、移除焦点指示、重复 aria-label、隐藏名称与可见标签不一致，以及错误后焦点丢失。还应测试 200% 缩放、较长德语文案、中文换行与移动键盘打开时的溢出。"),
    evidence: l("Kabul kanıtında otomatik envanterin yanında yalnız klavye ile tamamlanan görev, odak sırası, ekran okuyucu kontrol adı/durumu, hata düzeltme süresi ve 320–1440 piksel kırılımları bulunmalıdır. Otomatik tarayıcı uyarısını gerçek kullanıcı görevinden ayrı raporlayın.", "Acceptance evidence should combine the automated inventory with keyboard-only completion, focus order, screen-reader name/state, error recovery, and 320–1440 px breakpoints. Report automated findings separately from real user-task evidence.", "Abnahmenachweise verbinden Inventar mit Tastaturaufgabe, Fokusfolge, Screenreader-Name/-Status, Fehlerbehebung und 320–1440-px-Breakpoints. Automatik und Nutzertest getrennt berichten.", "验收证据应把自动清单与纯键盘任务完成、焦点顺序、屏幕阅读器名称/状态、错误恢复及 320–1440 像素断点结合。自动发现与真实用户任务证据应分开报告。"),
    boundary: l("Statik HTML incelemesi CSS görünürlüğünü, Shadow DOM'u, istemci sonrası değişimi veya yardımcı teknoloji davranışını tam olarak ölçmez; WCAG uygunluğu tek araç sonucuyla ilan edilmemelidir.", "Static HTML inspection does not fully measure CSS visibility, Shadow DOM, post-hydration changes, or assistive-technology behaviour; one tool result cannot establish WCAG conformance.", "Statische HTML-Prüfung misst CSS-Sichtbarkeit, Shadow DOM, Hydration und Assistenztechnik nicht vollständig; ein Werkzeug beweist keine WCAG-Konformität.", "静态 HTML 检查无法完整测量 CSS 可见性、Shadow DOM、水合后变化或辅助技术行为；不能凭单一工具结果宣称符合 WCAG。"),
  },
  {
    slug: "sitemap-robots-meta-indexleme-yayin-rehberi", relatedTools: ["sitemap-url-kume-analizoru", "robots-meta-politikasi-olusturucu", "robots-txt-olusturucu-denetleyici", "hreflang-etiket-olusturucu"],
    title: l("Sitemap, Robots Meta ve Hreflang ile Güvenli İndeksleme Yayını", "Safe Indexing Releases with Sitemaps, Robots Meta, and Hreflang", "Sichere Indexierung mit Sitemap, Robots Meta und Hreflang", "使用站点地图、Robots Meta 与 Hreflang 安全发布索引"),
    excerpt: l("URL keşfi, canonical karar, tarama izni ve dil eşleşmesini birbirine karıştırmadan ölçülebilir bir yayın kapısı kurun.", "Build a measurable release gate without confusing URL discovery, canonical choice, crawl permission, and locale matching.", "URL-Entdeckung, Canonical, Crawl-Erlaubnis und Sprachzuordnung in einem messbaren Release-Gate trennen.", "建立可衡量的发布门槛，避免混淆 URL 发现、canonical 选择、抓取许可与语言匹配。"),
    category: l("Teknik SEO ve bilgi mimarisi", "Technical SEO and information architecture", "Technisches SEO und Informationsarchitektur", "技术 SEO 与信息架构"),
    outcome: l("Yalnız canonical ve 200 durumlu içerik URL'lerini sitemap'e alan; dört dilde karşılıklı hreflang kümesi kuran; noindex, robots.txt ve canonical çelişkisini yayın öncesi durduran bir kontrol süreci oluşturmak.", "Create a release process that includes only canonical 200-content URLs in the sitemap, builds reciprocal four-language hreflang clusters, and blocks conflicts among noindex, robots.txt, and canonical before publication.", "Einen Releaseprozess schaffen, der nur kanonische 200-Inhalts-URLs listet, vier Sprachen reziprok verbindet und Konflikte zwischen noindex, robots.txt und Canonical stoppt.", "建立发布流程：站点地图仅包含 canonical 且返回 200 的内容 URL，四语言 hreflang 相互对应，并在发布前阻止 noindex、robots.txt 与 canonical 冲突。"),
    practice: l("URL envanterini şablon türü, dil, canonical, durum ve son güncelleme alanlarıyla tutun. Sitemap'i navigasyon yerine keşif sinyali olarak görün; her dil URL'si kendisini ve diğer dilleri işaretlesin. Robots meta kararı sayfanın içerik amacıyla, robots.txt kararı tarama maliyetiyle, erişim kontrolü ise güvenlikle ayrı ayrı verilmelidir.", "Maintain the URL inventory with template type, locale, canonical, status, and last meaningful update. Treat the sitemap as a discovery signal, not navigation; each locale URL should reference itself and peers. Decide robots meta by content purpose, robots.txt by crawl cost, and access control by security.", "URL-Inventar mit Template, Sprache, Canonical, Status und echter Aktualisierung führen. Sitemap als Discovery-Signal behandeln; jede Sprache referenziert sich und ihre Partner. Robots Meta, robots.txt und Zugriffsschutz getrennt entscheiden.", "URL 清单应记录模板类型、语言、canonical、状态与最近实质更新。把站点地图视为发现信号而非导航；每个语言 URL 应引用自身与其他语言。robots meta 依据内容目的、robots.txt 依据抓取成本、访问控制依据安全分别决策。"),
    failure: l("Düşük değerli parametre sayfalarını listelemek, aynı içeriği farklı host/protokolle yayınlamak, yönlendirme URL'sini sitemap'e koymak, noindex sayfaya canonical ile otorite aktarmaya çalışmak ve eksik dil kümesi üretmek yaygın hatalardır. Kaldırılan URL için 404/410, birleştirilen kopya için 301 ve gerçek alternatif dil için 200 davranışını ayrı test edin.", "Typical failures are listing low-value parameter pages, publishing duplicates across hosts or protocols, including redirects in the sitemap, trying to consolidate a noindex page through canonical, and emitting incomplete locale clusters. Test 404/410 for removed URLs, 301 for consolidated copies, and 200 for genuine language alternatives.", "Typische Fehler: Parameterseiten, Host-/Protokollduplikate, Redirect-URLs in Sitemaps, Canonical auf noindex und unvollständige Sprachcluster. 404/410, 301 und echte 200-Sprachalternativen getrennt testen.", "常见错误包括收录低价值参数页、跨主机/协议发布重复内容、把重定向 URL 放入站点地图、试图用 canonical 合并 noindex 页面，以及生成不完整语言集合。应分别测试删除 URL 的 404/410、合并副本的 301 与真实语言版本的 200。"),
    evidence: l("Her yayın örnekleminde gerçek HTTP durumu, render edilmiş canonical/robots/hreflang, sitemap üyeliği, iç bağlantı sayısı ve benzersiz ana içerik doğrulanmalıdır. Arama motoru raporları gecikmeli olduğundan dağıtım kanıtını, sonraki tarama gözlemini ve organik sonucu ayrı tarihlerle kaydedin.", "For each release sample, verify live HTTP status, rendered canonical/robots/hreflang, sitemap membership, internal-link count, and unique main content. Search reports lag, so record deployment evidence, later crawl observation, and organic outcome on separate dates.", "Je Release-Stichprobe Live-Status, gerenderte Canonical-/Robots-/Hreflang-Tags, Sitemap, interne Links und einzigartigen Hauptinhalt prüfen. Deployment, späteren Crawl und organisches Ergebnis getrennt datieren.", "每次发布抽样应验证真实 HTTP 状态、渲染后的 canonical/robots/hreflang、站点地图成员关系、内部链接数与独特主内容。搜索报告有延迟，因此应分别记录部署证据、后续抓取观察与自然结果日期。"),
    boundary: l("Doğru etiketler sıralama veya indeks garantisi vermez. Arama motoru; içerik değeri, site itibarı, talep, yinelenen sayfalar ve kalite politikaları dahil çok sayıda sinyali bağımsız değerlendirir.", "Correct tags guarantee neither indexing nor ranking. Search engines independently evaluate content value, reputation, demand, duplication, and quality policies among many signals.", "Korrekte Tags garantieren weder Indexierung noch Ranking; Suchmaschinen bewerten Inhalt, Reputation, Nachfrage, Duplikate und Qualitätsrichtlinien unabhängig.", "正确标签既不保证收录也不保证排名；搜索引擎会独立评估内容价值、站点信誉、需求、重复页面与质量政策等多种信号。"),
  },
  {
    slug: "eposta-konu-preheader-icerik-kalite-rehberi", relatedTools: ["eposta-konu-onizleme-denetleyici", "sade-dil-kontrolu", "unicode-normalizasyon-inceleyici", "utm-kampanya-url-olusturucu"],
    title: l("E-posta Konu ve Preheader Tasarımı: Kesilmeden Önce Anlamı Taşımak", "Email Subject and Preheader Design: Carry Meaning Before Truncation", "E-Mail-Betreff und Preheader: Bedeutung vor der Kürzung", "邮件主题与预标题设计：在截断前传达意义"),
    excerpt: l("Konu ile önizlemeyi birbirini tekrarlayan sloganlar yerine, ilk ekranda değer ve bağlamı birlikte taşıyan erişilebilir bir çift olarak yazın.", "Write subject and preheader as an accessible pair that carries value and context in the first view rather than repeating slogans.", "Betreff und Preheader als zugängliches Paar schreiben, das Wert und Kontext vermittelt statt Slogans zu wiederholen.", "把主题与预标题写成互补的无障碍组合，在首屏传达价值与语境，而不是重复口号。"),
    category: l("İçerik ve iletişim tasarımı", "Content and communication design", "Content- und Kommunikationsdesign", "内容与沟通设计"),
    outcome: l("Dört dilde, ilk 35–45 karakterde temel değeri anlatan, önizlemede yeni bilgi ekleyen, yanıltıcı aciliyet kullanmayan ve bağlantı hedefiyle tutarlı bir e-posta açılışı hazırlamak.", "Create a four-language email opening that communicates core value in the first 35–45 characters, adds new information in the preheader, avoids deceptive urgency, and matches the link destination.", "Einen viersprachigen E-Mail-Einstieg erstellen, der in 35–45 Zeichen Nutzen zeigt, im Preheader ergänzt, keine falsche Dringlichkeit nutzt und zum Linkziel passt.", "制作四语言邮件开头：前 35–45 个字符传达核心价值，预标题补充新信息，不使用误导性紧迫感，并与链接目标一致。"),
    practice: l("Önce e-postanın tek işini ve okuyucunun beklenen sonraki adımını yazın. Konu, gönderici ve zaman bağlamıyla tek başına anlaşılmalı; preheader aynı cümleyi tekrar etmek yerine kapsam, süre veya kanıt eklemelidir. Değişken alanlar boş kaldığında güvenli geri dönüş kullanın ve emoji/özel karakteri anlamın yerine koymayın.", "Write the email's one job and expected next action first. The subject should stand on its own beside sender and date; the preheader should add scope, time, or evidence rather than repeat it. Give variables safe fallbacks and never replace meaning with emoji or decoration.", "Zuerst Aufgabe und nächste Aktion definieren. Der Betreff muss neben Absender und Datum allein verständlich sein; der Preheader ergänzt Umfang, Zeit oder Beleg. Variablen brauchen sichere Fallbacks; Emojis ersetzen keine Bedeutung.", "先明确邮件的唯一任务与预期下一步。主题应在发送者与日期旁独立可懂；预标题应补充范围、时间或证据而非重复。变量为空时要有安全回退，表情与装饰不能替代意义。"),
    failure: l("Yalnız masaüstü genişliğinde yazmak, konu ve preheader'ı aynı başlatmak, tamamı büyük harf veya aşırı ünlem kullanmak, kişisel veriyi konuya taşımak ve bağlantı sayfasında verilmeyen bir faydayı vaat etmek güven ve erişilebilirlik kaybıdır. Boş ad, uzun kurum adı, sağdan sola metin ve kapalı görsel durumunu test edin.", "Writing only for desktop width, repeating the opening, using all caps or excessive punctuation, exposing personal data in the subject, and promising a benefit absent from the destination all reduce trust and accessibility. Test empty names, long organisation names, right-to-left text, and images disabled.", "Nur für Desktop schreiben, Betreff und Preheader wiederholen, Versalien/!!!, Personendaten im Betreff und nicht eingelöste Versprechen mindern Vertrauen. Leere Namen, lange Organisationen, RTL und deaktivierte Bilder testen.", "只按桌面宽度撰写、主题与预标题重复、全大写或过多感叹号、在主题暴露个人数据、承诺落地页没有的收益都会损害信任与无障碍。应测试姓名为空、机构名很长、从右到左文本与图片关闭。"),
    evidence: l("Kabul tablosunda her dil için karakter sayısı, küçük/orta/geniş önizleme, değişkenlerin en uzun ve boş hali, ekran okuyucuda okuma sırası, bağlantı metni ile hedef başlığının eşleşmesi ve gerçek istemci ekran görüntüsü bulunmalıdır. Açılma oranını tek kalite ölçütü olarak kullanmayın; şikâyet, yanlış tıklama ve görev tamamlama sinyallerini birlikte değerlendirin.", "For every locale, record character count, narrow/medium/wide preview, longest and empty variable states, screen-reader order, match between link text and destination heading, and a real-client screenshot. Do not use open rate as the sole quality measure; include complaints, mistaken clicks, and task completion.", "Pro Sprache Zeichen, schmale/mittlere/breite Vorschau, längste/leere Variablen, Screenreader-Reihenfolge, Link-Ziel-Abgleich und echten Client-Screenshot dokumentieren. Öffnungsrate nie allein bewerten.", "每种语言都应记录字符数、窄/中/宽预览、变量最长与空状态、屏幕阅读器顺序、链接文本与目标标题匹配，以及真实客户端截图。不要把打开率作为唯一质量指标；还应结合投诉、误点与任务完成。"),
    boundary: l("Uzunluk ve dil sinyalleri teslim edilebilirliği, spam sınıflandırmasını veya kullanıcı ilgisini tahmin etmez. Güncel gönderici itibarı, izin, kimlik doğrulama ve içerik beklentisi ayrı operasyon alanlarıdır.", "Length and language signals predict neither deliverability, spam classification, nor user interest. Sender reputation, permission, authentication, and content expectations are separate operational concerns.", "Längen- und Sprachsignale sagen weder Zustellung noch Spam noch Interesse voraus. Reputation, Einwilligung, Authentifizierung und Erwartung sind separate Bereiche.", "长度与语言信号不能预测投递率、垃圾邮件分类或用户兴趣。发送者信誉、许可、认证与内容预期是独立的运营领域。"),
  },
  {
    slug: "performans-yedekleme-surum-operasyon-rehberi", relatedTools: ["web-performans-butce-planlayici", "yedekleme-3-2-1-hazirlik-denetleyici", "surum-notu-degisiklik-derleyici", "paket-manifestosu-denetleyici"],
    title: l("Performans Bütçesinden Geri Yükleme Kanıtına Güvenli Sürüm Operasyonu", "Safe Release Operations: From Performance Budgets to Restore Evidence", "Sicherer Releasebetrieb: Vom Performance-Budget zum Restore-Nachweis", "安全发布运营：从性能预算到恢复证据"),
    excerpt: l("Hız, bağımlılık, yedek ve değişiklik bilgisini ayrı kontroller olmaktan çıkarıp geri alınabilir bir yayın kararında birleştirin.", "Turn performance, dependencies, backups, and change information into one reversible release decision instead of isolated checks.", "Performance, Abhängigkeiten, Backups und Änderungen zu einer reversiblen Releaseentscheidung verbinden.", "把性能、依赖、备份与变更信息整合为可回退的发布决策，而非孤立检查。"),
    category: l("Sürüm ve dayanıklılık yönetimi", "Release and resilience management", "Release- und Resilienzmanagement", "发布与韧性管理"),
    outcome: l("Mobil aktarım bütçesini aşan değişikliği yayın öncesi durduran, bağımlılık/lisans farkını kaydeden, son geri yükleme kanıtını doğrulayan ve kullanıcı etkisini açık sürüm notunda anlatan bir yayın kapısı kurmak.", "Build a release gate that blocks changes exceeding the mobile transfer budget, records dependency and licence differences, verifies recent restore evidence, and explains user impact in clear release notes.", "Ein Release-Gate schaffen, das Mobilbudgets schützt, Abhängigkeits-/Lizenzänderungen protokolliert, Restore-Nachweis prüft und Nutzerwirkung klar erklärt.", "建立发布门槛：阻止超过移动传输预算的变更，记录依赖与许可证差异，验证近期恢复证据，并在清晰发布说明中解释用户影响。"),
    practice: l("Bütçeyi toplam KB'nin yanında JS, görsel, font ve üçüncü taraf dilimlerine ayırın; her sapmanın sahibi ve gerekçesi olsun. Yayın paketi için kilit dosyası, lisans envanteri, güvenlik değişikliği, geri alma komutu, 3-2-1 kopya kanıtı ve son başarılı geri yükleme tarihini aynı kontrol kaydına bağlayın.", "Split the budget into JS, images, fonts, and third-party slices as well as total KB; assign an owner and rationale to every variance. Link the lockfile, licence inventory, security changes, rollback command, 3-2-1 evidence, and last successful restore date in the same release record.", "Budget neben Gesamt-KB nach JS, Bildern, Fonts und Drittanbietern teilen; jede Abweichung hat Verantwortung und Begründung. Lockfile, Lizenzinventar, Sicherheitsänderung, Rollback, 3-2-1-Nachweis und Restore-Datum gemeinsam dokumentieren.", "除总 KB 外，把预算拆为 JS、图片、字体与第三方部分；每项偏差都应有责任人与理由。把锁文件、许可证清单、安全变更、回滚命令、3-2-1 证据与最近成功恢复日期关联到同一发布记录。"),
    failure: l("Yalnız sıkıştırılmış toplamı izlemek ana iş parçacığı maliyetini gizler; yalnız yedeğin varlığını görmek geri yüklenebilirliği kanıtlamaz; yalnız commit başlığını sürüm notuna kopyalamak kullanıcı etkisini anlatmaz. Soğuk önbellek, düşük bellek, kesilen indirme, bozuk kopya, eksik anahtar ve geri alma sonrası veri şeması ayrı hata senaryolarıdır.", "Tracking only compressed total hides main-thread cost; seeing a backup does not prove restoration; copying commit subjects does not explain user impact. Cold cache, low memory, interrupted download, corrupt copy, missing key, and post-rollback schema compatibility are separate failure scenarios.", "Nur komprimierte Größe verbirgt Main-Thread-Kosten; Backup-Existenz beweist keinen Restore; Commit-Titel erklären keine Nutzerwirkung. Cold Cache, wenig Speicher, Abbruch, beschädigte Kopie, fehlender Schlüssel und Schema nach Rollback separat testen.", "只追踪压缩总量会隐藏主线程成本；看到备份不代表可恢复；复制提交标题也不能解释用户影响。冷缓存、低内存、下载中断、损坏副本、密钥缺失与回滚后的数据架构兼容性都是独立故障场景。"),
    evidence: l("Yayın kanıtı; önce/sonra varlık boyutları, kritik rota tarayıcı ölçümü, test sonucu, bağımlılık farkı, bilinen risk, geri alma sahibi, geri yükleme örnek kaydı ve kullanıcıya dönük değişiklik notunu içermelidir. Geçici istisnaya son kullanma tarihi verin; tekrarlanan istisnayı yeni normal bütçe saymayın.", "Release evidence should include before/after asset sizes, browser measurements on critical routes, tests, dependency diff, known risk, rollback owner, sample restore record, and user-facing notes. Give temporary exceptions an expiry date rather than silently turning them into the new budget.", "Release-Nachweis enthält Vorher/Nachher-Größen, Browsermessungen kritischer Routen, Tests, Abhängigkeitsdiff, Risiko, Rollback-Verantwortung, Restore-Beleg und Nutzerhinweise. Ausnahmen brauchen Ablaufdatum.", "发布证据应包含前后资源大小、关键路径浏览器测量、测试、依赖差异、已知风险、回滚责任人、恢复样本记录与面向用户的说明。临时例外应有到期日，不能默默变成新预算。"),
    boundary: l("Yerel hesaplayıcı gerçek ağ koşulunu, depolama arızasını, tedarik zinciri güvenini veya geri yükleme başarısını kendi başına kanıtlamaz. Son karar üretim benzeri prova ve sorumlu insan onayı gerektirir.", "A local calculator alone proves no real network condition, storage failure, supply-chain trust, or restoration success. Final release requires production-like rehearsal and accountable human approval.", "Ein lokaler Rechner beweist weder Netzwerk, Speicherausfall, Lieferkette noch Restore-Erfolg. Der Release braucht produktionsnahe Probe und verantwortliche Freigabe.", "本地计算器本身不能证明真实网络条件、存储故障、供应链可信度或恢复成功；最终发布需要类生产演练与可追责人工批准。"),
  },
];

const headings = {
  tr: ["Somut sonucu ve sorumluyu tanımlayın", "Girdi sözleşmesini hazırlayın", "Mutlu yolu küçük adımlarla kurun", "Hata yollarını kasıtlı olarak sınayın", "Kullanıcı ve sistem etkisini doğrulayın", "Yayın kanıtını kaydedin", "Sınırı ve sonraki incelemeyi açıklayın"],
  en: ["Define the outcome and owner", "Prepare the input contract", "Build the happy path in small steps", "Test failure paths deliberately", "Verify user and system impact", "Record release evidence", "State the boundary and next review"],
  de: ["Ergebnis und Verantwortung definieren", "Eingabevertrag vorbereiten", "Erfolgspfad kleinteilig aufbauen", "Fehlerpfade bewusst testen", "Nutzer- und Systemwirkung prüfen", "Release-Nachweis dokumentieren", "Grenze und nächste Prüfung nennen"],
  zh: ["定义结果与责任人", "准备输入契约", "用小步骤构建正常路径", "主动测试失败路径", "验证用户与系统影响", "记录发布证据", "说明边界与下次复核"],
} satisfies Record<Locale, string[]>;

function sections(locale: Locale, guide: Guide): ArticleSection[] {
  const paragraphs: Record<Locale, string[][]> = {
    tr: [
      [`Bu rehberin ölçülebilir hedefi şudur: ${guide.outcome.tr}`, `Kararın sahibini, yanlış sonucun etkisini, durdurma koşulunu ve otomatikleştirilmeyecek son onayı daha veri girmeden yazın. “Çalıştı” yerine kullanıcı görevi, doğruluk, süre, geri alınabilirlik ve açıklanabilirlik eşiği belirleyin.`],
      [guide.practice.tr, `Yalnız sentetik, size ait veya kullanım hakkı açık verilerle başlayın. Alan adı, tür, birim, dil, zaman dilimi, hassasiyet, eksik değer ve tekrar kuralını ayrı ayrı kaydedin; ham girdiyi salt okunur örnek olarak koruyun.`],
      [`${guide.relatedTools.join(", ")} araçlarını tek büyük işlem yerine girdi doğrulama, dönüşüm, sonuç kontrolü ve teslim kapıları olarak sıralayın. Her kapıda beklenen çıktı, hata mesajı, devam koşulu ve sorumlu kişi görünür olsun.`, `İlk denemeyi tek kayıt veya küçük örnekle yapın. Sonucu kaynakla uzlaştırmadan büyük dosyaya, otomatik yayına veya gerçek kişisel veriye geçmeyin; varsayımları sonuç kartında gösterin.`],
      [guide.failure.tr, `Boş, bozuk, aşırı uzun, yinelenen, sırası değişmiş, farklı dilde ve kasıtlı çelişkili girdileri saklanan negatif testlere dönüştürün. Hata mesajı alanı, nedeni ve düzeltme adımını söylemeli; sessiz düzeltme yapmamalıdır.`],
      [`Kullanıcı görevinin baştan sona tamamlanabildiğini klavye, mobil kırılım ve yavaş cihaz koşulunda doğrulayın. Kaynak ile sonuç arasında sayı, toplam, kimlik, eksik değer ve değişen alanları karşılaştırın.`, `Görsel olarak düzgün sonuç doğruluk kanıtı değildir. Kritik iddiayı birincil kaynağa, güvenlik etkisini tehdit modeline, içerik etkisini gerçek okuyucu görevine ve performans etkisini tarayıcı ölçümüne bağlayın.`],
      [guide.evidence.tr, `Kayıtta tarih, araç ve veri sürümü, kabul eşiği, negatif testler, çıktı özeti, bilinen risk, insan onayı ve geri alma adımı bulunmalıdır. Tekrarlanabilir olmayan ekran görüntüsünü tek kanıt saymayın; yapılandırma ve örneği birlikte saklayın.`],
      [guide.boundary.tr, `Sınırı sonuçla aynı görünürlükte yazın ve sonraki inceleme tarihini belirleyin. Hukuki, güvenlik, sağlık veya finans etkisi varsa güncel birincil kaynak ve yetkili uzman kontrolünü zorunlu yayın kapısı yapın.`],
    ],
    en: [
      [`The measurable objective of this guide is: ${guide.outcome.en}`, `Name the decision owner, impact of a wrong result, stop condition, and final approval that will not be automated before entering data. Replace “it ran” with thresholds for user-task completion, accuracy, time, reversibility, and explainability.`],
      [guide.practice.en, `Start only with synthetic, owned, or explicitly reusable data. Record field, type, unit, language, time zone, sensitivity, missing-value, and duplicate rules separately, preserving the raw input as a read-only example.`],
      [`Arrange ${guide.relatedTools.join(", ")} as input validation, transformation, result review, and delivery gates rather than one opaque operation. Each gate needs expected output, failure message, continuation rule, and owner.`, `Begin with one record or a small sample. Do not move to large files, automatic release, or real personal data before reconciling the output with the source and exposing assumptions next to the result.`],
      [guide.failure.en, `Turn empty, malformed, oversized, duplicated, out-of-order, cross-language, and deliberately contradictory input into retained negative tests. Errors must identify the field, reason, and corrective action without silent repair.`],
      [`Verify the whole user task with keyboard use, mobile breakpoints, and a constrained device. Reconcile counts, totals, identities, missing values, and changed fields between source and result.`, `A polished result is not proof of correctness. Tie consequential claims to primary evidence, security effects to a threat model, content effects to real reader tasks, and performance effects to browser measurements.`],
      [guide.evidence.en, `Record date, tool and data versions, acceptance thresholds, negative tests, result summary, known risk, human approval, and rollback step. A screenshot alone is not reproducible evidence; keep configuration and sample together.`],
      [guide.boundary.en, `Give the boundary equal visibility to the result and set the next review date. For legal, security, health, or financial impact, make qualified review against current primary sources a mandatory release gate.`],
    ],
    de: [
      [`Das messbare Ziel dieses Leitfadens lautet: ${guide.outcome.de}`, `Verantwortung, Fehlwirkung, Stoppbedingung und nicht automatisierte Endfreigabe vor der Dateneingabe festlegen. Statt „lief“ Schwellen für Aufgabe, Genauigkeit, Zeit, Reversibilität und Erklärbarkeit definieren.`],
      [guide.practice.de, `Nur synthetische, eigene oder klar nutzbare Daten verwenden. Feld, Typ, Einheit, Sprache, Zeitzone, Sensibilität, Leerwert und Duplikatregel getrennt dokumentieren und Rohdaten schreibgeschützt bewahren.`],
      [`${guide.relatedTools.join(", ")} als Eingabeprüfung, Transformation, Ergebniskontrolle und Übergabe statt als Blackbox ordnen. Pro Gate Ausgabe, Fehler, Fortsetzung und Verantwortung festlegen.`, `Mit einem Datensatz oder kleiner Probe beginnen. Vor Abgleich und sichtbaren Annahmen nicht zu großen Dateien, automatischem Release oder echten Personendaten wechseln.`],
      [guide.failure.de, `Leere, fehlerhafte, übergroße, doppelte, ungeordnete, mehrsprachige und absichtlich widersprüchliche Eingaben als Negativtests speichern. Fehler nennen Feld, Grund und Korrektur ohne stille Reparatur.`],
      [`Nutzeraufgabe per Tastatur, Mobil-Breakpoint und begrenztem Gerät vollständig prüfen. Zahlen, Summen, Identitäten, Leerwerte und Änderungen zwischen Quelle und Ergebnis abgleichen.`, `Gute Optik beweist keine Richtigkeit. Wichtige Aussagen an Primärquelle, Sicherheit an Bedrohungsmodell, Inhalt an Nutzeraufgabe und Performance an Browsermessung binden.`],
      [guide.evidence.de, `Datum, Werkzeug-/Datenversion, Schwellen, Negativtests, Ergebnis, Risiko, Freigabe und Rollback dokumentieren. Screenshot allein ist nicht reproduzierbar; Konfiguration und Probe gemeinsam sichern.`],
      [guide.boundary.de, `Grenzen gleich sichtbar wie Ergebnisse machen und nächste Prüfung datieren. Bei Rechts-, Sicherheits-, Gesundheits- oder Finanzwirkung qualifizierte Prüfung mit aktuellen Primärquellen verpflichtend machen.`],
    ],
    zh: [
      [`本指南的可衡量目标是：${guide.outcome.zh}`, `输入数据前先明确决策责任人、错误结果影响、停止条件与不得自动化的最终批准。不要把“运行成功”当标准，应设定用户任务、准确性、时间、可逆性与可解释性阈值。`],
      [guide.practice.zh, `仅从合成、自有或重用权明确的数据开始。分别记录字段、类型、单位、语言、时区、敏感级别、缺失值与重复规则，并把原始输入保存为只读样本。`],
      [`把 ${guide.relatedTools.join("、")} 排列为输入验证、转换、结果复核与交付门槛，而不是一个不透明大操作。每个门槛都应有预期输出、失败消息、继续规则与责任人。`, `先用一条记录或小样本测试。在把结果与来源核对、并把假设显示在结果旁之前，不要扩展到大文件、自动发布或真实个人数据。`],
      [guide.failure.zh, `把空、损坏、超大、重复、乱序、跨语言与故意矛盾输入保留为负面测试。错误必须指出字段、原因与修正动作，不能静默修复。`],
      [`在键盘操作、移动断点与受限设备上验证完整用户任务。核对来源与结果的数量、总计、标识、缺失值与变化字段。`, `视觉整洁不等于正确。重要主张应关联第一手证据，安全影响关联威胁模型，内容影响关联真实读者任务，性能影响关联浏览器测量。`],
      [guide.evidence.zh, `记录日期、工具与数据版本、验收阈值、负面测试、结果摘要、已知风险、人工批准与回滚步骤。单独截图不具可重复性；应同时保留配置与样本。`],
      [guide.boundary.zh, `让边界与结果同样醒目，并设定下次复核日期。涉及法律、安全、健康或财务影响时，应把合格专家依据最新一手来源的复核设为强制发布门槛。`],
    ],
  };
  return headings[locale].map((heading, index) => ({ heading, paragraphs: paragraphs[locale][index], bullets: index === 0 ? [guide.outcome[locale]] : index === 6 ? [guide.boundary[locale]] : undefined }));
}

export const studioPosts: Post[] = guides.map((guide) => ({
  slug: guide.slug, relatedTools: guide.relatedTools, date: "2026-08-22", updated: "2026-08-22", readTime: { tr: "19 dk", en: "18 min" },
  title: { tr: guide.title.tr, en: guide.title.en }, excerpt: { tr: guide.excerpt.tr, en: guide.excerpt.en },
  description: { tr: `${guide.excerpt.tr} Görev, hata senaryosu, kabul kanıtı ve güven sınırlarıyla uygulamalı yayın rehberi.`, en: `${guide.excerpt.en} A practical publishing guide with tasks, failure scenarios, acceptance evidence, and trust boundaries.` },
  category: { tr: guide.category.tr, en: guide.category.en }, visualSuggestion: { tr: "Girdi, hata kapıları, kanıt ve insan onayını gösteren erişilebilir karar akışı.", en: "An accessible decision flow showing input, failure gates, evidence, and human approval." },
  sections: { tr: sections("tr", guide), en: sections("en", guide) },
}));

export const studioLocalizedGuides: LocalizedGuide[] = guides.map((guide) => ({
  slug: guide.slug, relatedTools: guide.relatedTools, date: "2026-08-22", updated: "2026-08-22", copy: {
    de: { title: guide.title.de, excerpt: guide.excerpt.de, description: `${guide.excerpt.de} Praxisleitfaden mit Aufgaben, Fehlerszenarien, Abnahmenachweisen und Vertrauensgrenzen.`, category: guide.category.de, readTime: "18 Min.", sections: sections("de", guide) },
    zh: { title: guide.title.zh, excerpt: guide.excerpt.zh, description: `${guide.excerpt.zh} 包含任务、失败场景、验收证据与信任边界的实践发布指南。`, category: guide.category.zh, readTime: "约 18 分钟", sections: sections("zh", guide) },
  },
}));

export const studioGuideCount = guides.length;
