import type { Locale } from "./site";

type L = Record<Locale, string>;

export type SpecificToolGuidance = {
  input: L;
  method: L;
  output: L;
  verification: L;
  boundary: L;
  workflow: L;
};

const l = (tr: string, en: string, de: string, zh: string): L => ({ tr, en, de, zh });
const g = (input: L, method: L, output: L, verification: L, boundary: L, workflow: L): SpecificToolGuidance => ({ input, method, output, verification, boundary, workflow });

/**
 * Hand-written content contracts for the studio tools. These deliberately
 * mirror the fields and processors in StudioWorkbenches instead of inheriting
 * broad category copy. This keeps each landing page useful before a visitor
 * opens the interactive workbench.
 */
export const studioToolGuidance: Record<string, SpecificToolGuidance> = {
  "retry-after-geri-cekilme-planlayici": g(
    l("HTTP yöntemi, 429 veya 503 yanıtı, Retry-After değeri, deneme sayısı, taban gecikme, üst sınır ve jitter yüzdesi", "HTTP method, 429 or 503 response, Retry-After value, attempt count, base delay, cap, and jitter percentage", "HTTP-Methode, 429- oder 503-Antwort, Retry-After-Wert, Versuchszahl, Basisverzögerung, Obergrenze und Jitter-Prozent", "HTTP 方法、429 或 503 响应、Retry-After 值、尝试次数、基础延迟、上限与抖动百分比"),
    l("Retry-After saniye ya da HTTP tarihi olarak ayrıştırılır. Her deneme için üstel gecikme üst sınırla kısıtlanır, deterministik jitter eklenir ve sunucunun bildirdiği en erken zamanın önüne geçilmez.", "Retry-After is parsed as seconds or an HTTP date. Exponential delay is capped for every attempt, deterministic jitter is added, and no retry is scheduled before the server's earliest time.", "Retry-After wird als Sekunden oder HTTP-Datum geparst. Exponentielle Verzögerung wird begrenzt, deterministischer Jitter ergänzt und kein Versuch vor dem Serverzeitpunkt geplant.", "Retry-After 会按秒数或 HTTP 日期解析。每次指数延迟受上限约束，加入确定性抖动，且不会早于服务器给出的最早时间。"),
    l("deneme numarası, hesaplanan bekleme süresi, en erken yeniden deneme zamanı ve güvenli olmayan yöntem uyarısı içeren zaman çizelgesi", "a timeline containing attempt number, calculated wait, earliest retry time, and an unsafe-method warning", "einen Zeitplan mit Versuchsnummer, Wartezeit, frühestem Retry-Zeitpunkt und Warnung bei unsicherer Methode", "包含尝试序号、计算等待时间、最早重试时刻与非安全方法警告的时间线"),
    l("ilk beklemenin Retry-After değerinden kısa olmadığını, gecikmelerin üst sınırı aşmadığını ve aynı girdinin aynı jitter çizelgesini verdiğini kontrol etme", "checking that the first wait is not shorter than Retry-After, delays never exceed the cap, and identical input produces the same jitter timeline", "prüfen, dass die erste Wartezeit Retry-After nicht unterschreitet, die Obergrenze hält und dieselbe Eingabe denselben Jitter liefert", "检查首次等待不短于 Retry-After、延迟不超过上限，并且相同输入产生相同抖动时间线"),
    l("Bu plan istek göndermez ve işlemin idempotent olduğunu kanıtlamaz. POST/PATCH gibi yan etkili çağrıları otomatik tekrar etmeden önce idempotency anahtarı, sunucu sözleşmesi ve gerçek saat kaymasını doğrulayın.", "This plan sends no request and does not prove idempotency. Before automatically retrying POST or PATCH, verify an idempotency key, the server contract, and real clock skew.", "Der Plan sendet keine Anfrage und beweist keine Idempotenz. Vor automatischen POST-/PATCH-Retries Idempotenzschlüssel, Serververtrag und reale Uhrabweichung prüfen.", "该计划不会发送请求，也不能证明幂等性。自动重试 POST 或 PATCH 前，应验证幂等键、服务器约定与真实时钟偏差。"),
    l("API istemcisinin hız sınırı ve geçici hata politikasını belgelemek", "documenting an API client's rate-limit and transient-failure policy", "Rate-Limit- und Transientfehler-Richtlinie eines API-Clients dokumentieren", "记录 API 客户端的限流与临时故障策略"),
  ),
  "webhook-teslim-gunlugu-analizoru": g(
    l("Her satırda olay kimliği, ISO zaman damgası, HTTP durumu ve milisaniye gecikme bulunan temizlenmiş teslim kayıtları", "sanitised delivery records with event id, ISO timestamp, HTTP status, and latency in milliseconds on each line", "bereinigte Zustellzeilen mit Ereignis-ID, ISO-Zeitstempel, HTTP-Status und Latenz in Millisekunden", "每行包含事件标识、ISO 时间戳、HTTP 状态与毫秒延迟的已脱敏投递记录"),
    l("Satırlar olay kimliğine göre gruplanır; zaman sırası, tekrar sayısı, son başarı, başarısızlık serisi ve gecikme uçları hesaplanır. İçerik çalıştırılmaz ve uç noktaya bağlanılmaz.", "Rows are grouped by event id; ordering, attempt count, final success, failure streaks, and latency outliers are calculated. No content is executed and no endpoint is contacted.", "Zeilen werden nach Ereignis-ID gruppiert; Reihenfolge, Versuche, Enderfolg, Fehlerserien und Latenzausreißer werden berechnet. Keine Ausführung oder Verbindung.", "记录按事件标识分组，计算顺序、尝试次数、最终成功、连续失败与延迟异常；不会执行内容或连接端点。"),
    l("olay bazında teslim özeti, yinelenen ve sıra dışı denemeler, son durum ve incelenecek gecikme kayıtları", "per-event delivery summaries, duplicate and out-of-order attempts, final state, and latency records to review", "Zustellübersichten pro Ereignis, doppelte oder ungeordnete Versuche, Endstatus und zu prüfende Latenzen", "按事件生成的投递摘要、重复与乱序尝试、最终状态及需复核的延迟记录"),
    l("başarılı bir tekrarın önceki hatayı kapattığını, zamanların artan sırada olduğunu ve aynı olayın beklenen idempotency davranışıyla karşılaştırıldığını kontrol etme", "checking that a successful retry closes the earlier failure, timestamps are ordered, and repeated events match the expected idempotency behaviour", "prüfen, ob ein erfolgreicher Retry den Fehler schließt, Zeitstempel geordnet sind und Wiederholungen dem Idempotenzverhalten entsprechen", "检查成功重试是否关闭先前失败、时间戳是否有序，以及重复事件是否符合预期幂等行为"),
    l("Günlük satırı webhook imzasını, gönderici kimliğini veya alıcının yan etkiyi yalnız bir kez uyguladığını kanıtlamaz. Sırları önce kaldırın; imza ve idempotency durumunu yetkili sistemde doğrulayın.", "A log row proves neither webhook signature, sender identity, nor exactly-once side effects. Remove secrets first and verify signatures and idempotency in the authorised system.", "Eine Logzeile beweist weder Signatur, Absender noch Exactly-once-Wirkung. Geheimnisse entfernen und Signatur sowie Idempotenz im autorisierten System prüfen.", "日志记录不能证明 Webhook 签名、发送方身份或副作用仅执行一次。请先移除秘密，并在授权系统中验证签名与幂等性。"),
    l("webhook teslim SLO'sunu ve tekrar politikasını incelemek", "reviewing webhook delivery SLOs and retry policy", "Webhook-Zustell-SLO und Retry-Richtlinie prüfen", "审查 Webhook 投递 SLO 与重试策略"),
  ),
  "aria-erisebilir-ad-envanteri": g(
    l("Düğme, bağlantı, görsel ve form kontrolleri içeren, betik çalıştırılmasına ihtiyaç duymayan HTML parçası", "an HTML fragment containing buttons, links, images, and form controls that needs no script execution", "ein HTML-Fragment mit Buttons, Links, Bildern und Formularfeldern ohne nötige Skriptausführung", "包含按钮、链接、图片与表单控件且无需执行脚本的 HTML 片段"),
    l("HTML, DOMParser ile etkisiz belge olarak ayrıştırılır. Görünür metin, label ilişkisi, aria-labelledby, aria-label, alt ve title kaynakları erişilebilir ad önceliğine göre incelenir.", "HTML is parsed as an inert document with DOMParser. Visible text, label relations, aria-labelledby, aria-label, alt, and title are reviewed in accessible-name priority order.", "HTML wird mit DOMParser als inertes Dokument geparst. Sichttext, Label-Bezug, aria-labelledby, aria-label, alt und title werden nach Namenspriorität geprüft.", "HTML 由 DOMParser 作为惰性文档解析，并按可访问名称优先级检查可见文本、label 关联、aria-labelledby、aria-label、alt 与 title。"),
    l("öğe türü, seçici ipucu, hesaplanan ad kaynağı ve adsız/şüpheli kontrol durumu içeren envanter", "an inventory with element type, selector hint, computed name source, and unnamed or suspicious-control status", "ein Inventar mit Elementtyp, Selektorhinweis, Namensquelle und Status für unbenannte oder verdächtige Elemente", "包含元素类型、选择器提示、名称来源以及无名称或可疑控件状态的清单"),
    l("her etkileşimli öğeyi klavyeyle odaklayıp ekran okuyucuda ad, rol, durum ve hata mesajını gerçek erişilebilirlik ağacında karşılaştırma", "focusing every interactive element by keyboard and comparing name, role, state, and error message in a real screen reader and accessibility tree", "jedes interaktive Element per Tastatur fokussieren und Name, Rolle, Zustand sowie Fehler im echten Accessibility Tree vergleichen", "使用键盘聚焦每个交互元素，并在真实屏幕阅读器与无障碍树中核对名称、角色、状态和错误信息"),
    l("Statik HTML envanteri CSS ile gizlenen metni, Shadow DOM'u, çalışma zamanı durumlarını veya ekran okuyucu davranışını tam olarak göremez; sonuç WCAG uygunluk belgesi değildir.", "A static HTML inventory cannot fully observe CSS-hidden text, Shadow DOM, runtime states, or screen-reader behaviour; it is not a WCAG conformance report.", "Ein statisches HTML-Inventar sieht CSS-verdeckten Text, Shadow DOM, Laufzeitzustände oder Screenreader-Verhalten nicht vollständig und ist kein WCAG-Nachweis.", "静态 HTML 清单无法完整观察 CSS 隐藏文本、Shadow DOM、运行时状态或屏幕阅读器行为，也不是 WCAG 合规报告。"),
    l("form ve etkileşimli bileşen yayın kontrolü yapmak", "performing pre-release checks for forms and interactive components", "Formulare und interaktive Komponenten vor Veröffentlichung prüfen", "执行表单与交互组件的发布前检查"),
  ),
  "html-dil-baslik-yapisi-denetleyici": g(
    l("html lang, title, meta description ve görünür h1-h6 yapısını içeren tam ya da parçalı HTML", "full or partial HTML containing html lang, title, meta description, and visible h1-h6 structure", "vollständiges oder partielles HTML mit html lang, title, Meta-Description und sichtbarer h1-h6-Struktur", "包含 html lang、title、meta description 与可见 h1-h6 结构的完整或局部 HTML"),
    l("İçerik çalıştırılmadan ayrıştırılır; dil etiketi, başlık ve açıklama varlığı, H1 sayısı, boş başlıklar ve atlanan seviye geçişleri ayrı kurallarla raporlanır.", "Content is parsed without execution; language tag, title and description presence, H1 count, empty headings, and skipped levels are reported with separate rules.", "Inhalt wird ohne Ausführung geparst; Sprachangabe, Titel/Beschreibung, H1-Zahl, leere Überschriften und Ebenensprünge werden getrennt gemeldet.", "内容在不执行的情况下解析，分别报告语言标签、标题和描述是否存在、H1 数量、空标题与层级跳跃。"),
    l("belge sinyalleri özeti, sıralı başlık ağacı ve her sorun için kaynak öğeye yönelik düzeltme notu", "a document-signal summary, ordered heading tree, and source-element correction note for every issue", "eine Übersicht der Dokumentsignale, geordneter Überschriftenbaum und Korrekturhinweise je Quellenelement", "文档信号摘要、有序标题树，以及针对每个问题源元素的修正说明"),
    l("sayfayı gerçek URL'de kaynak ve işlenmiş DOM üzerinden kontrol edip ana görevin tek H1 ile anlatıldığını ve başlıkların içerik sırasını bozmadığını doğrulama", "checking source and rendered DOM on the real URL to confirm one task-focused H1 and a heading order that follows content structure", "Quelltext und gerendertes DOM der echten URL prüfen: ein aufgabenbezogenes H1 und inhaltstreue Überschriftenfolge", "在真实 URL 上检查源代码与渲染 DOM，确认只有一个聚焦任务的 H1，且标题顺序遵循内容结构"),
    l("Başlık uzunluğu veya sıra sinyali sıralama, içerik kalitesi ya da ekran okuyucu uyumu garantisi değildir. Sayfanın gerçek dili, amacı ve kullanıcı görevi insan tarafından değerlendirilmelidir.", "Title length or hierarchy signals guarantee neither ranking, content quality, nor screen-reader compatibility. A human must assess the page's real language, purpose, and user task.", "Titellänge und Hierarchie garantieren weder Ranking, Inhaltsqualität noch Screenreader-Kompatibilität. Reale Sprache, Zweck und Nutzeraufgabe brauchen menschliche Prüfung.", "标题长度或层级信号不能保证排名、内容质量或屏幕阅读器兼容性；页面真实语言、目的与用户任务仍需人工判断。"),
    l("çok dilli içerik şablonunu yayınlamadan önce doğrulamak", "validating a multilingual content template before release", "mehrsprachige Inhaltsvorlagen vor Veröffentlichung validieren", "在发布前验证多语言内容模板"),
  ),
  "sitemap-url-kume-analizoru": g(
    l("Sitemap'ten alınmış, her satırda tek mutlak URL bulunan ve en fazla beklenen hostları içeren URL listesi", "a URL list copied from a sitemap with one absolute URL per line and only expected hosts", "eine aus der Sitemap kopierte Liste mit einer absoluten URL pro Zeile und nur erwarteten Hosts", "从站点地图复制的 URL 列表，每行一个绝对 URL，且仅包含预期主机"),
    l("URL'ler ağ isteği olmadan normalleştirilir; protokol, host, yol, sorgu ve fragman ayrılır. Yinelenen canonical adayları, host sapmaları, izleme parametreleri, derin yollar ve olası dil kümeleri gruplanır.", "URLs are normalised without network requests; protocol, host, path, query, and fragment are separated. Duplicate canonical candidates, host drift, tracking parameters, deep paths, and likely locale sets are grouped.", "URLs werden ohne Netzabruf normalisiert und in Protokoll, Host, Pfad, Query und Fragment getrennt. Canonical-Duplikate, Hostabweichungen, Trackingparameter, tiefe Pfade und Sprachgruppen werden gebildet.", "URL 在不发起网络请求的情况下规范化，并拆分协议、主机、路径、查询与片段；随后分组候选 canonical 重复、主机偏差、跟踪参数、深层路径与可能的语言集合。"),
    l("toplam/tekil URL ölçümleri, sorun kümeleri, dil varyantı boşlukları ve yayın öncesi düzeltme listesi", "total and unique URL metrics, issue clusters, locale-variant gaps, and a pre-release correction list", "Gesamt-/Einzel-URL-Kennzahlen, Problemgruppen, Lücken bei Sprachvarianten und Korrekturliste", "URL 总数与唯一数指标、问题分组、语言变体缺口及发布前修正清单"),
    l("örneklenen URL'lerde 200 yanıtı, self-canonical, indexlenebilirlik ve karşılıklı hreflang bağlantılarını canlı tarama veya Search Console ile doğrulama", "verifying sampled URLs for 200 responses, self-canonicals, indexability, and reciprocal hreflang through a live crawl or Search Console", "Stichproben live oder in Search Console auf 200, Self-Canonical, Indexierbarkeit und wechselseitiges Hreflang prüfen", "通过实时抓取或 Search Console 抽查 URL 的 200 响应、自引用 canonical、可索引性与双向 hreflang"),
    l("Bu araç URL'leri açmaz; dizine eklenme, canonical seçimi veya hreflang kabulünü kanıtlayamaz. Silme ve yönlendirme kararlarından önce sunucu yanıtı ile arama motoru raporunu kontrol edin.", "The tool does not open URLs and cannot prove indexing, canonical selection, or hreflang acceptance. Check server responses and search-engine reports before removals or redirects.", "Das Werkzeug öffnet keine URLs und beweist weder Indexierung, Canonical-Auswahl noch Hreflang-Annahme. Vor Löschung oder Redirect Serverantworten und Suchberichte prüfen.", "该工具不会打开 URL，无法证明索引、canonical 选择或 hreflang 接受情况；删除或重定向前应检查服务器响应与搜索引擎报告。"),
    l("sitemap ve çok dilli URL yayınını denetlemek", "auditing sitemap and multilingual URL releases", "Sitemap- und mehrsprachige URL-Veröffentlichung prüfen", "审计站点地图与多语言 URL 发布"),
  ),
  "robots-meta-politikasi-olusturucu": g(
    l("Sayfanın indeks, bağlantı takibi, snippet uzunluğu, görsel önizleme, video önizleme, önbellek ve çeviri tercihleri", "the page's index, link-following, snippet length, image preview, video preview, cache, and translation preferences", "Index-, Linkfolge-, Snippet-, Bild-/Video-Vorschau-, Cache- und Übersetzungspräferenzen der Seite", "页面的索引、链接跟踪、摘要长度、图片预览、视频预览、缓存与翻译偏好"),
    l("Seçimler desteklenen robots direktiflerine çevrilir; çelişkili veya noindex altında etkisiz kalan önizleme seçenekleri görünür uyarıyla ayrılır. Genel robot ve Googlebot çıktısı ayrı gösterilir.", "Selections are translated into supported robots directives; conflicting or ineffective preview options under noindex are separated with a visible warning. General-robot and Googlebot output are shown separately.", "Auswahl wird in Robots-Direktiven übersetzt; widersprüchliche oder unter noindex wirkungslose Vorschauoptionen werden sichtbar markiert. Allgemeine Robots- und Googlebot-Ausgabe werden getrennt.", "所选项会转换为受支持的 robots 指令；与 noindex 冲突或在其下无效的预览选项会以明确警告分开显示，并分别给出通用机器人与 Googlebot 输出。"),
    l("kopyalanabilir meta etiketi, direktif açıklamaları, çelişki uyarıları ve yayında kontrol edilecek başlık listesi", "a copyable meta tag, directive explanations, conflict warnings, and a list of headers to check after release", "kopierbares Meta-Tag, Direktiverklärungen, Konfliktwarnungen und Prüfliste für die Veröffentlichung", "可复制的 meta 标签、指令解释、冲突警告与发布后需检查的响应头清单"),
    l("yayınlanan HTML ve X-Robots-Tag yanıt başlığında tek ve uyumlu politika bulunduğunu, robots.txt engelinin doğrulamayı önlemediğini ve URL Inspection'ın aynı sonucu gördüğünü kontrol etme", "checking that published HTML and X-Robots-Tag headers expose one compatible policy, robots.txt does not block verification, and URL Inspection sees the same result", "prüfen, dass HTML und X-Robots-Tag eine konsistente Richtlinie liefern, robots.txt die Kontrolle nicht blockiert und URL Inspection dasselbe sieht", "检查已发布 HTML 与 X-Robots-Tag 响应头是否给出一致策略、robots.txt 是否未阻止验证，以及 URL Inspection 是否看到相同结果"),
    l("Robots meta erişim kontrolü değildir ve indeks kaldırmayı anında garanti etmez. Hassas içeriği kimlik doğrulama ile koruyun; arama görünürlüğü kararını canlı URL ve güncel resmî belgeyle doğrulayın.", "Robots meta is not access control and does not guarantee immediate de-indexing. Protect sensitive content with authentication and verify search-visibility decisions on the live URL against current official documentation.", "Robots Meta ist kein Zugriffsschutz und garantiert keine sofortige Entfernung. Sensible Inhalte authentifizieren und Sichtbarkeitsentscheidungen an Live-URL und offizieller Dokumentation prüfen.", "Robots meta 不是访问控制，也不能保证立即移除索引；敏感内容应使用身份验证保护，并依据最新官方文档在实时 URL 上验证搜索可见性决策。"),
    l("arama görünürlüğü politikasını yayın şablonuna dönüştürmek", "turning a search-visibility decision into a publishing template", "eine Suchsichtbarkeitsentscheidung als Publishing-Template umsetzen", "把搜索可见性决策转为发布模板"),
  ),
  "eposta-konu-onizleme-denetleyici": g(
    l("Ayrı konu ve preheader metni; hedef dil, cihaz önceliği ve varsa örnek değişken değerleri", "separate subject and preheader text, target language, device priority, and representative variable values", "getrennter Betreff und Preheader, Zielsprache, Gerätepriorität und repräsentative Variablenwerte", "分开的主题与预标题文本、目标语言、设备优先级及代表性变量值"),
    l("Konu ve preheader karakter ve yaklaşık görünür genişlik açısından ayrı ölçülür; yinelenen açılış, tamamı büyük harf, aşırı noktalama, boş önizleme ve kesilme riski açıklanabilir kurallarla işaretlenir.", "Subject and preheader are measured separately for characters and approximate visible width; repeated openings, all-caps, excessive punctuation, empty previews, and truncation risk are flagged with explainable rules.", "Betreff und Preheader werden nach Zeichen und sichtbarer Breite getrennt gemessen; Wiederholung, Versalien, Satzzeichen, leere Vorschau und Kürzungsrisiko werden nachvollziehbar markiert.", "主题与预标题按字符数和近似可见宽度分别测量，并以可解释规则标记重复开头、全大写、过度标点、空预览与截断风险。"),
    l("mobil ve masaüstü önizlemeleri, ölçümler, sorunların metindeki yeri ve yeniden yazım için öncelikli kontrol listesi", "mobile and desktop previews, measurements, issue locations, and a prioritised rewrite checklist", "Mobil-/Desktop-Vorschau, Messwerte, Fundstellen und priorisierte Überarbeitungsliste", "移动端与桌面端预览、测量值、问题位置及优先改写清单"),
    l("en uzun ve boş değişkenlerle gerçek istemcilerde görüntüyü; bağlantı hedefini, izin durumunu ve ekran okuyucu okuma sırasını test etme", "testing real clients with longest and empty variable values, plus link destination, permission state, and screen-reader order", "echte Clients mit längsten/leeren Variablen sowie Linkziel, Einwilligung und Screenreader-Reihenfolge testen", "在真实客户端中使用最长与空变量测试，并核对链接目标、许可状态与屏幕阅读器顺序"),
    l("Uzunluk sinyalleri teslim edilebilirlik, spam sınıflandırması, açılma veya dönüşüm garantisi vermez. Gönderici itibarı, izin, kimlik doğrulama ve kullanıcı beklentisi ayrı incelenmelidir.", "Length signals guarantee neither deliverability, spam classification, opens, nor conversion. Sender reputation, permission, authentication, and user expectations require separate review.", "Längensignale garantieren weder Zustellung, Spamklassifikation, Öffnung noch Conversion. Reputation, Einwilligung, Authentifizierung und Erwartung separat prüfen.", "长度信号不能保证投递、垃圾邮件分类、打开率或转化；发送者信誉、许可、认证与用户预期需另行审查。"),
    l("çok dilli e-posta yayın kontrolünü hazırlamak", "preparing a multilingual email release review", "mehrsprachige E-Mail-Veröffentlichung prüfen", "准备多语言邮件发布检查"),
  ),
  "web-performans-butce-planlayici": g(
    l("HTML, CSS, JavaScript, görsel ve font için mevcut aktarım KB'si; her türün hedef bütçesi, toplam bütçe ve koruma payı", "current transfer KB for HTML, CSS, JavaScript, images, and fonts, plus per-type budgets, total budget, and safety margin", "aktuelle Transfer-KB für HTML, CSS, JavaScript, Bilder und Fonts sowie Teilbudgets, Gesamtbudget und Reserve", "HTML、CSS、JavaScript、图片与字体的当前传输 KB，以及各类预算、总预算与安全余量"),
    l("Kaynak türleri ayrı toplanır; mevcut değer bütçeyle karşılaştırılır, toplam sapma ve yüzde pay hesaplanır, en büyük kontrollü azaltma fırsatları önceliklendirilir.", "Resource types are totalled separately; current values are compared with budgets, total variance and percentage share are calculated, and the largest controllable reduction opportunities are prioritised.", "Ressourcentypen werden getrennt summiert, Istwerte mit Budgets verglichen, Abweichung und Anteil berechnet und größte kontrollierbare Reduktionen priorisiert.", "各资源类型分别汇总，将当前值与预算比较，计算总偏差与占比，并优先列出可控的最大减重机会。"),
    l("tür bazında bütçe tablosu, toplam geçiş/kalma durumu, azaltılması gereken KB ve ölçüm planı", "a per-type budget table, total pass or fail state, KB reduction required, and a measurement plan", "Budgettabelle je Typ, Gesamtstatus, nötige KB-Reduktion und Messplan", "按类型预算表、总体通过或失败状态、需减少的 KB 及测量计划"),
    l("soğuk önbellekli düşük seviye mobil cihazda kritik rotaların sıkıştırılmış aktarımını, ana iş parçacığı süresini ve gerçek LCP/INP/CLS ölçümlerini karşılaştırma", "comparing compressed transfer, main-thread time, and real LCP, INP, and CLS on critical routes with a cold cache and low-end mobile device", "komprimierten Transfer, Main-Thread-Zeit und reale LCP-/INP-/CLS-Werte kritischer Routen mit Cold Cache und schwachem Mobilgerät vergleichen", "在冷缓存和低端移动设备上比较关键路径的压缩传输、主线程时间与真实 LCP、INP、CLS"),
    l("Aktarım bütçesi çalışma zamanı performansını veya Core Web Vitals başarısını tek başına kanıtlamaz. Laboratuvar ve alan verisini, üçüncü taraf maliyetini ve kullanıcı görevini ayrıca ölçün.", "A transfer budget alone does not prove runtime performance or Core Web Vitals success. Measure lab and field data, third-party cost, and the user task separately.", "Ein Transferbudget beweist weder Laufzeitperformance noch Core Web Vitals. Labor-/Felddaten, Drittanbieterkosten und Nutzeraufgabe separat messen.", "传输预算本身不能证明运行时性能或 Core Web Vitals 达标；还应分别测量实验室与现场数据、第三方成本和用户任务。"),
    l("performans regresyonlarını yayın öncesi durdurmak", "stopping performance regressions before release", "Performance-Regressionen vor Veröffentlichung stoppen", "在发布前阻止性能回退"),
  ),
  "yedekleme-3-2-1-hazirlik-denetleyici": g(
    l("Toplam kopya, farklı ortam sayısı, çevrimdışı veya uzak kopya, şifreleme, son başarılı geri yükleme tarihi, RPO ve RTO hedefleri", "total copies, distinct media count, offline or off-site copy, encryption, last successful restore date, and RPO and RTO targets", "Gesamtkopien, unterschiedliche Medien, Offline-/Außer-Haus-Kopie, Verschlüsselung, letzter erfolgreicher Restore sowie RPO/RTO", "副本总数、不同介质数量、离线或异地副本、加密、最近成功恢复日期，以及 RPO 与 RTO 目标"),
    l("Her 3-2-1 koşulu ayrı değerlendirilir; kopya sayısı ile ortam ve konum çeşitliliği karıştırılmaz. Geri yükleme yaşına ve hedeflere göre kanıt boşlukları önceliklendirilir.", "Each 3-2-1 condition is evaluated separately; copy count is not confused with media and location diversity. Evidence gaps are prioritised against restore age and recovery objectives.", "Jede 3-2-1-Bedingung wird getrennt bewertet; Kopienzahl wird nicht mit Medien- oder Ortsvielfalt verwechselt. Nachweislücken werden nach Restore-Alter und Zielen priorisiert.", "每项 3-2-1 条件单独评估，不把副本数量与介质或位置多样性混为一谈；依据恢复测试时间与恢复目标确定证据缺口优先级。"),
    l("koşul bazında hazırlık kartları, eksik kanıtlar, eskimiş geri yükleme testi uyarısı ve sonraki tatbikat listesi", "condition-level readiness cards, missing evidence, stale-restore warnings, and the next rehearsal checklist", "Bereitschaftskarten je Bedingung, fehlende Nachweise, veraltete Restore-Warnung und nächste Übungsliste", "按条件生成的就绪卡、缺失证据、恢复测试过期警告及下一次演练清单"),
    l("seçilen örnek dosyaları izole ortamda geri yükleyip bütünlük özeti, açılabilirlik, erişim yetkisi ve RPO/RTO süresini ölçme", "restoring selected sample files in isolation and measuring integrity digest, readability, access permissions, and achieved RPO and RTO", "ausgewählte Dateien isoliert wiederherstellen und Integrität, Lesbarkeit, Rechte sowie erreichte RPO/RTO messen", "在隔离环境中恢复选定样本文件，并测量完整性摘要、可打开性、访问权限及实际 RPO/RTO"),
    l("Form yanıtları yedeklerin mevcut, bozulmamış veya geri yüklenebilir olduğunu kanıtlamaz. Kritik sistemlerde imzalı kayıt ve düzenli gerçek geri yükleme tatbikatı gereklidir.", "Form answers do not prove that backups exist, are intact, or are restorable. Critical systems require signed evidence and regular real restore rehearsals.", "Formularangaben beweisen weder Existenz, Integrität noch Wiederherstellbarkeit. Kritische Systeme brauchen signierte Nachweise und regelmäßige echte Restore-Übungen.", "表单答案不能证明备份存在、完整或可恢复；关键系统需要签名证据与定期真实恢复演练。"),
    l("kişisel veya ekip yedekleme hazırlığını kanıtla yönetmek", "managing personal or team backup readiness with evidence", "persönliche oder Team-Backup-Bereitschaft nachweisbar verwalten", "用证据管理个人或团队备份就绪度"),
  ),
  "surum-notu-degisiklik-derleyici": g(
    l("Her satırda tek değişiklik bulunan Conventional Commit benzeri veya açık doğal dil girdisi; varsa kapsam, kırıcı değişiklik işareti ve kullanıcı etkisi", "one change per line in Conventional-Commit-like or clear natural language, with scope, breaking marker, and user impact where available", "eine Änderung pro Zeile in Commit-ähnlicher oder klarer Alltagssprache, möglichst mit Bereich, Breaking-Markierung und Nutzerwirkung", "每行一项变更，使用类似 Conventional Commit 或清晰自然语言，并尽可能包含范围、破坏性标记与用户影响"),
    l("Satırlar tür ve kapsam sinyallerine göre ayrıştırılır; yinelenen maddeler normalleştirilir, teknik önekler kullanıcı dilinden ayrılır ve yeni, iyileştirme, düzeltme, güvenlik ve kırıcı değişiklik bölümleri oluşturulur.", "Lines are parsed by type and scope signals; duplicates are normalised, technical prefixes are separated from user language, and added, improved, fixed, security, and breaking sections are built.", "Zeilen werden nach Typ und Bereich geparst, Duplikate normalisiert, technische Präfixe von Nutzersprache getrennt und Abschnitte für Neu, Verbessert, Behoben, Sicherheit und Breaking erstellt.", "按类型与范围信号解析各行，规范重复项，将技术前缀与用户语言分开，并生成新增、改进、修复、安全与破坏性变更章节。"),
    l("kullanıcıya dönük Markdown sürüm notu, kategori sayıları, yinelenenlerin özeti ve eksik bağlam kontrol listesi", "user-facing Markdown release notes, category counts, a duplicate summary, and a missing-context checklist", "nutzerorientierte Markdown-Release-Notes, Kategorienzahlen, Duplikatübersicht und Liste fehlender Kontexte", "面向用户的 Markdown 发布说明、分类数量、重复项摘要与缺失上下文清单"),
    l("her maddenin gerçek değişiklikle eşleştiğini, güvenlik düzeltmesinin hassas ayrıntı sızdırmadığını, kırıcı değişiklikte geçiş adımı ve geri alma yolunun bulunduğunu doğrulama", "checking every item against the actual change, ensuring security notes reveal no sensitive detail, and requiring migration and rollback steps for breaking changes", "jede Notiz mit der Änderung abgleichen, sensible Sicherheitsdetails vermeiden und bei Breaking Changes Migration sowie Rollback verlangen", "逐项核对真实变更，确保安全说明不泄露敏感细节，并要求破坏性变更包含迁移与回滚步骤"),
    l("Derleyici Git geçmişini, test sonucunu veya dağıtımı görmez. Üretilen notu yayınlamadan önce değişiklik sahibi, destek ve güvenlik sorumlusu doğrulamalıdır.", "The compiler sees no Git history, test result, or deployment. Before release, the change owner, support, and security owner must verify the generated notes.", "Der Compiler sieht weder Git-Historie, Tests noch Deployment. Vor Veröffentlichung müssen Änderungsverantwortung, Support und Sicherheit die Notizen prüfen.", "编译器无法查看 Git 历史、测试结果或部署；发布前应由变更负责人、支持与安全负责人核对生成说明。"),
    l("teknik değişiklikleri anlaşılır ve denetlenebilir sürüm iletişimine çevirmek", "turning technical changes into understandable, auditable release communication", "technische Änderungen in verständliche, prüfbare Release-Kommunikation überführen", "把技术变更转为易懂且可审计的发布沟通"),
  ),
};

export const studioGuidanceSlugs = Object.freeze(Object.keys(studioToolGuidance));
