import type { Locale } from "./site";
import type { ToolCategory } from "./tools";
import type { BaseTool } from "./tool-locales";

type L<T = string> = Record<Locale, T>;
type Spec = { slug: string; category: ToolCategory; mark: string; title: L; short: L; description: L; useCases: L<string[]>; steps: L<string[]> };
const l = <T,>(tr: T, en: T, de: T, zh: T): L<T> => ({ tr, en, de, zh });

const sharedSteps = l(
  ["Örneği yükleyin veya anlaşılır alanları kendi senaryonuzla doldurun.", "Denetimi cihazınızda çalıştırın; ölçümleri, uyarıları ve önerilen düzeltmeleri birlikte inceleyin.", "Sonucu gerçek hedef ortamda doğrulayın ve karar kaydına varsayımları ekleyin."],
  ["Load the example or fill the clearly labelled fields for your scenario.", "Run the check on-device and review metrics, warnings, and recommended corrections together.", "Validate the result in the real target environment and record its assumptions."],
  ["Beispiel laden oder die klar beschrifteten Felder für das eigene Szenario ausfüllen.", "Lokal prüfen und Kennzahlen, Warnungen sowie Korrekturen gemeinsam auswerten.", "Ergebnis in der Zielumgebung bestätigen und Annahmen dokumentieren."],
  ["加载示例，或按清晰标注填写自己的场景。", "在设备端运行检查，并同时查看指标、警告与修正建议。", "在真实目标环境中验证结果，并记录所用假设。"],
);

const specs: Spec[] = [
  {
    slug: "retry-after-geri-cekilme-planlayici", category: "data", mark: "332",
    title: l("Retry-After ve Geri Çekilme Planlayıcı", "Retry-After & Backoff Planner", "Retry-After- und Backoff-Planer", "Retry-After 与退避规划器"),
    short: l("429/503 yanıtları için sunucu bekleme süresi, üstel geri çekilme, jitter ve üst sınırı görünür bir zaman çizelgesine dönüştürün.", "Turn 429/503 retry rules, exponential backoff, jitter, and caps into a visible timeline.", "Retry-Regeln für 429/503, exponentielles Backoff, Jitter und Obergrenzen als Zeitplan darstellen.", "把 429/503 重试规则、指数退避、抖动与上限转为可见时间线。"),
    description: l("HTTP Retry-After değerini saniye veya HTTP tarihi olarak yorumlar; güvenli yöntem, deneme sayısı, taban gecikme, üst sınır ve deterministik jitter ile her yeniden denemenin en erken zamanını hesaplar. Ağ isteği yapmaz ve isteği kendisi tekrar göndermez.", "Parses Retry-After as seconds or an HTTP date, then calculates the earliest safe retry timeline from method safety, attempt count, base delay, cap, and deterministic jitter. It sends no request and performs no retry.", "Interpretiert Retry-After als Sekunden oder HTTP-Datum und berechnet aus Methodensicherheit, Versuchen, Basis, Obergrenze und deterministischem Jitter den frühesten Zeitplan. Es sendet keine Anfrage.", "将 Retry-After 解析为秒数或 HTTP 日期，并依据方法安全性、次数、基础延迟、上限和确定性抖动计算最早重试时间线；不会发送网络请求。"),
    useCases: l(["API istemci davranışı tasarlama", "429 yük testini belgeleme", "503 bakım penceresi planlama"], ["Designing API client behaviour", "Documenting 429 load tests", "Planning 503 maintenance recovery"], ["API-Client-Verhalten planen", "429-Lasttests dokumentieren", "503-Wiederanlauf planen"], ["设计 API 客户端行为", "记录 429 压测", "规划 503 恢复"]), steps: sharedSteps,
  },
  {
    slug: "webhook-teslim-gunlugu-analizoru", category: "data", mark: "333",
    title: l("Webhook Teslim Günlüğü Analizörü", "Webhook Delivery Log Analyzer", "Webhook-Zustellprotokoll-Analyse", "Webhook 投递日志分析器"),
    short: l("Webhook denemelerini kimlik, zaman, durum ve gecikmeyle gruplayıp başarısızlık, tekrar ve sıra dışı teslimleri bulun.", "Group webhook attempts by id, time, status, and latency to find failures, duplicates, and out-of-order delivery.", "Webhook-Versuche nach ID, Zeit, Status und Latenz gruppieren und Fehler, Duplikate sowie Reihenfolgeprobleme finden.", "按标识、时间、状态与延迟整理 Webhook 尝试，找出失败、重复与乱序投递。"),
    description: l("Satır tabanlı sentetik veya temizlenmiş teslim kayıtlarını ayrıştırır; aynı olayın tekrarlarını, son başarı durumunu, gecikme uçlarını ve zaman sırası ihlallerini raporlar. İmza doğrulamaz, uç noktaya bağlanmaz ve günlükteki sırları otomatik olarak güvenli hale getirmez.", "Parses synthetic or sanitised line-based delivery records and reports repeated events, final success state, latency outliers, and ordering violations. It does not verify signatures, contact endpoints, or make secrets in logs safe.", "Analysiert synthetische oder bereinigte Zustellzeilen und meldet Wiederholungen, Endstatus, Latenzausreißer und Reihenfolgefehler. Keine Signatur- oder Endpunktprüfung.", "解析合成或已脱敏的投递记录，报告重复事件、最终成功状态、延迟异常与顺序问题；不验证签名，也不连接端点。"),
    useCases: l(["Tekrarlı teslim araştırma", "Webhook SLO ön incelemesi", "Idempotency testi hazırlama"], ["Investigating repeated delivery", "Webhook SLO pre-review", "Preparing idempotency tests"], ["Doppelte Zustellung untersuchen", "Webhook-SLO vorprüfen", "Idempotenztests vorbereiten"], ["调查重复投递", "预审 Webhook SLO", "准备幂等性测试"]), steps: sharedSteps,
  },
  {
    slug: "aria-erisebilir-ad-envanteri", category: "codeSecurity", mark: "334",
    title: l("ARIA Erişilebilir Ad Envanteri", "ARIA Accessible-Name Inventory", "ARIA-Namensinventar", "ARIA 可访问名称清单"),
    short: l("HTML içindeki düğme, bağlantı ve form alanlarını erişilebilir adlarıyla listeleyip adsız kontrolleri bulun.", "Inventory buttons, links, and form controls with their accessible names and find unnamed controls.", "Buttons, Links und Formularfelder samt zugänglichem Namen inventarisieren und unbenannte Elemente finden.", "盘点 HTML 中按钮、链接与表单控件的可访问名称，并找出无名称控件。"),
    description: l("Yapıştırılan HTML'i çalıştırmadan DOMParser ile inceler; görünür metin, aria-label, aria-labelledby, label[for], alt ve title kaynaklarını öncelik sırasıyla raporlar. Sonuç yardımcı teknoloji testi değildir; dinamik durumlar tarayıcı erişilebilirlik ağacıyla ayrıca doğrulanmalıdır.", "Inspects pasted HTML without executing it and reports visible text, aria-label, aria-labelledby, label[for], alt, and title sources in priority order. The result is not an assistive-technology test; dynamic states still require accessibility-tree review.", "Untersucht eingefügtes HTML ohne Ausführung und meldet sichtbaren Text, aria-label, aria-labelledby, label[for], alt und title. Dynamische Zustände brauchen zusätzliche Prüfung.", "在不执行代码的情况下检查粘贴的 HTML，按优先级报告可见文本、aria-label、aria-labelledby、label[for]、alt 与 title；动态状态仍需无障碍树测试。"),
    useCases: l(["Form yayın öncesi denetimi", "İkon düğmesi kontrolü", "WCAG görev testi hazırlığı"], ["Pre-release form audit", "Icon-button review", "Preparing WCAG task tests"], ["Formularprüfung vor Release", "Icon-Button-Prüfung", "WCAG-Aufgabentests vorbereiten"], ["表单发布前审计", "图标按钮检查", "准备 WCAG 任务测试"]), steps: sharedSteps,
  },
  {
    slug: "html-dil-baslik-yapisi-denetleyici", category: "text", mark: "335",
    title: l("HTML Dil ve Başlık Yapısı Denetleyici", "HTML Language & Heading Structure Auditor", "HTML-Sprach- und Überschriftenprüfung", "HTML 语言与标题结构审计器"),
    short: l("HTML lang, title, meta açıklama, tek H1 ve başlık sırasını birlikte denetleyin.", "Audit HTML lang, title, meta description, a single H1, and heading order together.", "HTML-lang, title, Meta-Beschreibung, einzelnes H1 und Überschriftenfolge gemeinsam prüfen.", "同时审计 HTML lang、title、meta 描述、单一 H1 与标题顺序。"),
    description: l("Tam veya parçalı HTML'i çalıştırmadan ayrıştırır; sayfa dili, başlık uzunluğu, açıklama, H1 sayısı, boş başlık ve atlanan seviye sinyallerini anlaşılır bir yayın kontrolüne dönüştürür. Arama sıralaması veya ekran okuyucu uyumu garantisi vermez.", "Parses full or partial HTML without execution and turns page language, title length, description, H1 count, empty headings, and skipped levels into a readable release check. It guarantees neither ranking nor screen-reader compatibility.", "Parst vollständiges oder partielles HTML ohne Ausführung und prüft Sprache, Titellänge, Beschreibung, H1, leere Überschriften und Ebenensprünge. Keine Ranking-Garantie.", "在不执行代码的情况下解析完整或局部 HTML，将页面语言、标题长度、描述、H1 数量、空标题与层级跳跃转为易懂的发布检查；不保证排名。"),
    useCases: l(["İçerik şablonu QA", "Çok dilli sayfa kontrolü", "Başlık hiyerarşisi düzeltme"], ["Content-template QA", "Multilingual page review", "Fixing heading hierarchy"], ["Content-Template-QA", "Mehrsprachige Seitenprüfung", "Überschriftenhierarchie korrigieren"], ["内容模板质检", "多语言页面检查", "修复标题层级"]), steps: sharedSteps,
  },
  {
    slug: "sitemap-url-kume-analizoru", category: "research", mark: "336",
    title: l("Sitemap URL Küme Analizörü", "Sitemap URL Set Analyzer", "Sitemap-URL-Mengenanalyse", "站点地图 URL 集合分析器"),
    short: l("URL listesindeki tekrar, farklı host, HTTP, sorgu parametresi, derin yol ve olası dil kümesi tutarsızlıklarını bulun.", "Find duplicates, mixed hosts, HTTP URLs, query parameters, deep paths, and likely locale-set inconsistencies in a URL list.", "Duplikate, gemischte Hosts, HTTP, Parameter, tiefe Pfade und mögliche Sprachlücken in URL-Listen finden.", "查找 URL 列表中的重复项、混合主机、HTTP、查询参数、深层路径与可能的语言集不一致。"),
    description: l("Sitemap'ten kopyalanan mutlak URL'leri yerel olarak normalleştirir ve kümeler; yinelenen canonical adayları, protokol/host sapmaları, fragmanlar, izleme parametreleri ve tr/en/de/zh eşleşme boşluklarını raporlar. Canlı URL'leri taramaz veya indeks durumunu doğrulamaz.", "Normalises and clusters absolute URLs copied from a sitemap, reporting duplicate canonical candidates, protocol/host drift, fragments, tracking parameters, and likely tr/en/de/zh gaps. It neither crawls live URLs nor verifies index status.", "Normalisiert und gruppiert absolute Sitemap-URLs; meldet Canonical-Duplikate, Protokoll-/Hostabweichungen, Fragmente, Tracking-Parameter und mögliche Sprachlücken. Keine Live-Abfrage.", "在本地规范并聚类从站点地图复制的绝对 URL，报告候选 canonical 重复、协议/主机偏差、片段、跟踪参数及 tr/en/de/zh 语言缺口；不会抓取线上 URL。"),
    useCases: l(["Sitemap yayın kontrolü", "Hreflang kümesi hazırlığı", "Parametreli URL temizliği"], ["Sitemap release review", "Preparing hreflang clusters", "Cleaning parameterised URLs"], ["Sitemap-Releaseprüfung", "Hreflang-Cluster vorbereiten", "Parameter-URLs bereinigen"], ["站点地图发布检查", "准备 hreflang 集合", "清理参数化 URL"]), steps: sharedSteps,
  },
  {
    slug: "robots-meta-politikasi-olusturucu", category: "research", mark: "337",
    title: l("Robots Meta Politikası Oluşturucu", "Robots Meta Policy Builder", "Robots-Meta-Richtliniengenerator", "Robots Meta 策略生成器"),
    short: l("İndeksleme, bağlantı takibi, snippet, görsel ve arşiv tercihlerini çelişkisiz bir robots meta etiketiyle açıklayın.", "Express indexing, link-following, snippet, image, and archive choices as a conflict-free robots meta tag.", "Indexierung, Linkfolge, Snippet, Bild und Archiv als widerspruchsfreies Robots-Meta-Tag ausdrücken.", "把索引、链接跟踪、摘要、图片与归档选择生成为无冲突的 robots meta 标签。"),
    description: l("Kullanıcının seçtiği yayın politikasından Googlebot ve genel robotlar için okunabilir direktif listesi, HTML etiketi ve doğrulama notları üretir; noindex ile snippet/önizleme seçenekleri arasındaki anlamsız birleşimleri durdurur. Tarama engeli, erişim kontrolü veya indeks garantisi değildir.", "Builds a readable directive list, HTML tag, and validation notes for general crawlers and Googlebot, stopping meaningless combinations such as noindex with preview controls. It is neither crawl blocking, access control, nor an indexing guarantee.", "Erzeugt Direktiven, HTML-Tag und Prüfhinweise und verhindert sinnlose Kombinationen wie noindex mit Vorschauoptionen. Kein Zugriffsschutz oder Indexierungsversprechen.", "根据发布策略生成通用机器人与 Googlebot 的指令清单、HTML 标签和验证说明，并阻止 noindex 与预览控制等无意义组合；不构成访问控制或索引保证。"),
    useCases: l(["Yayın şablonu hazırlama", "Önizleme sınırı belgeleme", "noindex kararını gözden geçirme"], ["Preparing publishing templates", "Documenting preview limits", "Reviewing noindex decisions"], ["Publishing-Templates erstellen", "Vorschaugrenzen dokumentieren", "noindex-Entscheidungen prüfen"], ["准备发布模板", "记录预览限制", "复核 noindex 决策"]), steps: sharedSteps,
  },
  {
    slug: "eposta-konu-onizleme-denetleyici", category: "text", mark: "338",
    title: l("E-posta Konu ve Önizleme Denetleyici", "Email Subject & Preheader Reviewer", "E-Mail-Betreff- und Preheader-Prüfung", "邮件主题与预标题检查器"),
    short: l("Konu ve önizleme metninin uzunluk, tekrar, görünür kesilme ve açıklık sinyallerini cihazınızda inceleyin.", "Review subject and preheader length, duplication, visible truncation, and clarity signals on-device.", "Länge, Wiederholung, sichtbare Kürzung und Klarheit von Betreff und Preheader lokal prüfen.", "在设备端检查主题与预标题的长度、重复、可见截断与清晰度信号。"),
    description: l("E-posta konusu ile önizleme metnini ayrı alanlarda ölçer; mobil/masaüstü için yaklaşık görünür uzunluğu, tekrarlanan açılışı, aşırı noktalama, tamamı büyük harf ve boş önizleme durumlarını gösterir. Teslim edilebilirlik veya spam filtresi sonucu tahmin etmez.", "Measures subject and preheader separately and flags approximate mobile/desktop truncation, repeated openings, excessive punctuation, all-caps text, and empty previews. It does not predict deliverability or spam-filter outcomes.", "Misst Betreff und Preheader getrennt und markiert ungefähre Kürzung, Wiederholungen, übermäßige Satzzeichen, Versalien und leere Vorschauen. Keine Zustellprognose.", "分别测量邮件主题和预标题，标记移动端/桌面端近似截断、重复开头、过度标点、全大写与空预览；不预测投递率或垃圾邮件结果。"),
    useCases: l(["Bülten yayın kontrolü", "İşlemsel e-posta QA", "Çok dilli konu satırı karşılaştırma"], ["Newsletter release review", "Transactional-email QA", "Comparing multilingual subject lines"], ["Newsletter-Releaseprüfung", "Transaktionsmail-QA", "Mehrsprachige Betreffzeilen vergleichen"], ["新闻邮件发布检查", "事务邮件质检", "比较多语言主题行"]), steps: sharedSteps,
  },
  {
    slug: "web-performans-butce-planlayici", category: "calculation", mark: "339",
    title: l("Web Performans Bütçesi Planlayıcı", "Web Performance Budget Planner", "Web-Performance-Budgetplaner", "Web 性能预算规划器"),
    short: l("HTML, CSS, JS, görsel ve font kilobaytlarını mobil aktarım bütçesiyle karşılaştırıp öncelikli azaltma planı üretin.", "Compare HTML, CSS, JS, image, and font kilobytes with a mobile transfer budget and produce a prioritised reduction plan.", "HTML-, CSS-, JS-, Bild- und Font-Kilobytes mit einem Mobilbudget vergleichen und priorisierte Reduktionen planen.", "将 HTML、CSS、JS、图片与字体 KB 和移动传输预算比较，并生成优先减重计划。"),
    description: l("Kaynak türü bütçelerini ve mevcut aktarım boyutlarını ayrı alanlarda toplar; toplam sapmayı, en büyük payı, hedefe inmek için gereken azaltmayı ve koruma payını hesaplar. Laboratuvar veya gerçek kullanıcı LCP/INP/CLS ölçümü yapmaz.", "Collects resource budgets and current transfer sizes by type, calculating total variance, largest share, required reduction, and safety margin. It does not measure laboratory or real-user LCP, INP, or CLS.", "Erfasst Budgets und aktuelle Übertragungsgrößen nach Ressourcentyp und berechnet Abweichung, größten Anteil, nötige Reduktion und Reserve. Keine LCP-/INP-/CLS-Messung.", "按资源类型收集预算与当前传输大小，计算总偏差、最大占比、所需减少量与安全余量；不测量实验室或真实用户的 LCP、INP、CLS。"),
    useCases: l(["PR boyut kapısı", "Mobil açılış bütçesi", "Üçüncü taraf betik değerlendirmesi"], ["PR size gates", "Mobile start-up budgets", "Third-party script review"], ["PR-Größengrenzen", "Mobile Startbudgets", "Drittanbieter-Skriptprüfung"], ["PR 体积门槛", "移动启动预算", "第三方脚本评估"]), steps: sharedSteps,
  },
  {
    slug: "yedekleme-3-2-1-hazirlik-denetleyici", category: "security", mark: "330",
    title: l("3-2-1 Yedekleme Hazırlık Denetleyici", "3-2-1 Backup Readiness Checker", "3-2-1-Backup-Bereitschaftsprüfung", "3-2-1 备份就绪检查器"),
    short: l("Kopya, ortam, konum, şifreleme ve geri yükleme denemesini kanıt odaklı bir hazırlık raporunda birleştirin.", "Combine copies, media, locations, encryption, and restore testing in an evidence-focused readiness report.", "Kopien, Medien, Standorte, Verschlüsselung und Restore-Tests zu einem Nachweisbericht verbinden.", "将副本、介质、位置、加密与恢复测试汇总为证据导向的就绪报告。"),
    description: l("Toplam kopya, farklı ortam, çevrimdışı/uzak kopya, şifreleme, son başarılı geri yükleme tarihi ve kurtarma hedefini ayrı ayrı değerlendirir. Yedeğe erişmez, veri kopyalamaz ve felaket kurtarma garantisi vermez.", "Evaluates total copies, distinct media, offline/off-site copies, encryption, last successful restore date, and recovery objective separately. It accesses no backup, copies no data, and guarantees no disaster recovery.", "Bewertet Kopien, unterschiedliche Medien, Offline-/Außer-Haus-Kopie, Verschlüsselung, letzten Restore-Test und Wiederherstellungsziel. Greift auf keine Sicherung zu.", "分别评估副本数、不同介质、离线/异地副本、加密、最近成功恢复日期与恢复目标；不会访问或复制备份，也不保证灾难恢复。"),
    useCases: l(["Kişisel arşiv kontrolü", "Küçük ekip kurtarma hazırlığı", "Yedek tedarikçisi geçişi"], ["Personal archive review", "Small-team recovery readiness", "Backup-provider migration"], ["Privatarchiv prüfen", "Recovery-Bereitschaft kleiner Teams", "Backup-Anbieterwechsel"], ["个人归档检查", "小团队恢复准备", "备份提供商迁移"]), steps: sharedSteps,
  },
  {
    slug: "surum-notu-degisiklik-derleyici", category: "general", mark: "331",
    title: l("Sürüm Notu Değişiklik Derleyici", "Release Notes Change Compiler", "Release-Notes-Änderungscompiler", "发布说明变更编译器"),
    short: l("Ham değişiklik satırlarını kullanıcı etkisine göre yeni, iyileştirme, düzeltme, güvenlik ve kırıcı değişiklik başlıklarında düzenleyin.", "Organise raw change lines by user impact into added, improved, fixed, security, and breaking sections.", "Rohe Änderungen nach Nutzerwirkung in Neu, Verbessert, Behoben, Sicherheit und Breaking ordnen.", "按用户影响把原始变更行整理为新增、改进、修复、安全与破坏性变更章节。"),
    description: l("Conventional Commit benzeri veya doğal dilli satırlardaki tür, kapsam ve kırıcı değişiklik sinyallerini ayrıştırır; yinelenen maddeleri birleştirir, kullanıcıya dönük Markdown sürüm notu ve yayın öncesi eksik bilgi listesi üretir. Git geçmişini okumaz ve sürümü kendi yayınlamaz.", "Parses type, scope, and breaking-change signals from Conventional-Commit-like or plain-language lines, merges duplicates, and produces user-facing Markdown plus a missing-information checklist. It reads no Git history and publishes nothing.", "Parst Typ, Bereich und Breaking-Signale aus Commit-ähnlichen oder freien Zeilen, führt Duplikate zusammen und erzeugt Markdown samt Lückenliste. Liest keine Git-Historie.", "解析类似 Conventional Commit 或自然语言行中的类型、范围与破坏性变更信号，合并重复项，并生成面向用户的 Markdown 与缺失信息清单；不读取 Git 历史，也不发布版本。"),
    useCases: l(["Uygulama mağazası notu", "GitHub sürüm taslağı", "Müşteri değişiklik özeti"], ["App-store notes", "GitHub release drafts", "Customer change summaries"], ["App-Store-Notizen", "GitHub-Releaseentwurf", "Kundenänderungsübersicht"], ["应用商店说明", "GitHub 发布草稿", "客户变更摘要"]), steps: sharedSteps,
  },
];

export const studioTools: BaseTool[] = specs;
export const studioToolSlugs = new Set(specs.map((tool) => tool.slug));
export const studioToolCount = specs.length;
