import type { Locale } from "./site";
import { localizeTool, type BaseTool } from "./tool-locales";

export type ToolCategory = "prompt" | "text" | "data" | "converter" | "security" | "calculation" | "general" | "ai" | "codeSecurity";

export type Tool = {
  slug: string;
  category: ToolCategory;
  mark: string;
  title: Record<Locale, string>;
  short: Record<Locale, string>;
  description: Record<Locale, string>;
  useCases: Record<Locale, string[]>;
  steps: Record<Locale, string[]>;
};

export const categories: Record<ToolCategory, { label: Record<Locale, string>; description: Record<Locale, string>; mark: string }> = {
  prompt: {
    label: { tr: "Prompt araçları", en: "Prompt tools", de: "Prompt-Werkzeuge", zh: "提示词工具" },
    description: { tr: "Daha açık, sınanabilir ve yeniden kullanılabilir yapay zekâ talimatları hazırlayın.", en: "Build clearer, testable, and reusable AI instructions.", de: "Erstellen Sie klarere, prüfbare und wiederverwendbare KI-Anweisungen.", zh: "构建更清晰、可测试且可复用的 AI 指令。" },
    mark: "P",
  },
  text: {
    label: { tr: "Metin ve NLP", en: "Text & NLP", de: "Text & NLP", zh: "文本与 NLP" },
    description: { tr: "Metnin yapısını, okunabilirliğini ve benzerliğini cihazınızda inceleyin.", en: "Inspect structure, readability, and similarity directly on your device.", de: "Prüfen Sie Struktur, Lesbarkeit und Ähnlichkeit direkt auf Ihrem Gerät.", zh: "直接在设备上检查文本结构、可读性和相似度。" },
    mark: "T",
  },
  data: {
    label: { tr: "Veri ve geliştirici", en: "Data & developer", de: "Daten & Entwicklung", zh: "数据与开发" },
    description: { tr: "JSON, CSV, Regex ve kodlama işlemlerini hızlıca tamamlayın.", en: "Handle JSON, CSV, Regex, and encoding tasks quickly.", de: "Erledigen Sie JSON-, CSV-, Regex- und Kodierungsaufgaben schnell.", zh: "快速处理 JSON、CSV、正则表达式和编码任务。" },
    mark: "D",
  },
  converter: {
    label: { tr: "Dönüştürücüler", en: "Converters", de: "Konverter", zh: "转换工具" },
    description: { tr: "Görsel ve PDF dosyalarını cihazınızdan çıkarmadan dönüştürün, sıkıştırın ve düzenleyin.", en: "Convert, compress, and organize image and PDF files without sending them off-device.", de: "Konvertieren, komprimieren und ordnen Sie Bilder und PDFs, ohne sie hochzuladen.", zh: "无需上传，即可转换、压缩和整理图片与 PDF。" },
    mark: "C",
  },
  security: {
    label: { tr: "Gizlilik ve güvenlik", en: "Privacy & security", de: "Datenschutz & Sicherheit", zh: "隐私与安全" },
    description: { tr: "Hassas verileri maskeleyin ve güvenli tanımlayıcılar üretin.", en: "Mask sensitive data and generate secure identifiers.", de: "Maskieren Sie sensible Daten und erzeugen Sie sichere Kennungen.", zh: "遮蔽敏感数据并生成安全标识符。" },
    mark: "S",
  },
  calculation: {
    label: { tr: "Hesaplama araçları", en: "Calculation tools", de: "Rechenwerkzeuge", zh: "计算工具" },
    description: { tr: "Finans, eğitim ve günlük ölçümleri şeffaf formüllerle hesaplayın.", en: "Calculate finance, education, and everyday measurements with transparent formulas.", de: "Berechnen Sie Finanzen, Bildung und Alltagswerte mit transparenten Formeln.", zh: "使用透明公式计算财务、教育和日常数值。" },
    mark: "N",
  },
  general: {
    label: { tr: "Genel kullanıcı araçları", en: "Everyday tools", de: "Alltagswerkzeuge", zh: "日常工具" },
    description: { tr: "Belge ve günlük üretkenlik işlerini cihazınızda tamamlayın.", en: "Complete document and everyday productivity tasks on-device.", de: "Erledigen Sie Dokument- und Alltagsaufgaben direkt auf dem Gerät.", zh: "在设备上完成文档和日常效率任务。" },
    mark: "G",
  },
  ai: {
    label: { tr: "AI araçları", en: "AI tools", de: "KI-Werkzeuge", zh: "AI 工具" },
    description: { tr: "Model girdilerini, bağlam bütçelerini ve konuşma çıktılarını uzak API olmadan hazırlayın.", en: "Prepare model inputs, context budgets, and conversation exports without a remote API.", de: "Bereiten Sie Modelleingaben, Kontextbudgets und Gesprächsexporte ohne Remote-API vor.", zh: "无需远程 API，即可准备模型输入、上下文预算和对话导出。" },
    mark: "AI",
  },
  codeSecurity: {
    label: { tr: "Kod ve dosya güvenliği", en: "Code & file security", de: "Code- & Dateisicherheit", zh: "代码与文件安全" },
    description: { tr: "Dosya, URL ve kaynak kodunda açıklanabilir yerel risk ön taramaları çalıştırın.", en: "Run explainable local risk pre-scans for files, URLs, and source code.", de: "Führen Sie erklärbare lokale Risiko-Vorprüfungen für Dateien, URLs und Quellcode aus.", zh: "对文件、网址和源代码执行可解释的本地风险预扫描。" },
    mark: "CS",
  },
};

const baseTools: BaseTool[] = [
  {
    slug: "prompt-kalite-denetimi", category: "prompt", mark: "01",
    title: { tr: "Prompt Kalite Denetimi", en: "Prompt Quality Checker" },
    short: { tr: "Hedef, bağlam, kısıt ve çıktı biçimini şeffaf kurallarla puanlayın.", en: "Score goals, context, constraints, and output format with transparent rules." },
    description: { tr: "Bir promptun güçlü ve eksik yönlerini puanlayan bu araç; amaç netliği, bağlam, hedef kitle, kısıtlar, örnek ve çıktı biçimi gibi bileşenleri kontrol eder. Sonuç yalnızca bir skor değil, uygulanabilir bir iyileştirme listesi sunar.", en: "This tool evaluates a prompt for goal clarity, context, audience, constraints, examples, and output format. It returns both a score and a practical improvement checklist." },
    useCases: { tr: ["Üretim promptlarını yayınlamadan önce kontrol", "Ekip içi prompt standardı oluşturma", "Belirsiz talimatları iyileştirme"], en: ["Pre-flight checks for production prompts", "Shared team prompt standards", "Improving ambiguous instructions"] },
    steps: { tr: ["Promptunuzu giriş alanına yapıştırın.", "Analizi çalıştırın ve bileşen skorlarını inceleyin.", "Eksik maddeleri ekleyip yeniden ölçün."], en: ["Paste your prompt into the input area.", "Run the analysis and review component scores.", "Add missing elements and measure again."] },
  },
  {
    slug: "meta-prompt-olusturucu", category: "prompt", mark: "02",
    title: { tr: "Meta Prompt Oluşturucu", en: "Meta Prompt Builder" },
    short: { tr: "Bir hedefi rol, süreç, sınırlar ve çıktı şeması içeren yapıya dönüştürün.", en: "Turn a goal into a structured role, process, constraints, and output schema." },
    description: { tr: "Kısa bir görev tanımını; rol, başarı ölçütü, çalışma adımları, sınırlar ve çıktı sözleşmesi içeren yeniden kullanılabilir bir meta prompta dönüştürür. Üretilen metin cihazınızda hazırlanır.", en: "Transforms a short task description into a reusable meta prompt containing a role, success criteria, workflow, constraints, and output contract. Everything is generated on-device." },
    useCases: { tr: ["Tekrarlanan iş akışları", "Kurumsal prompt şablonları", "Ajans ve içerik ekipleri"], en: ["Repeatable workflows", "Team prompt templates", "Agency and content teams"] },
    steps: { tr: ["Gerçek hedefi tek cümleyle yazın.", "Varsa bağlam ve zorunlu kısıtları ekleyin.", "Şablonu üretin, gözden geçirin ve kopyalayın."], en: ["Describe the real goal in one sentence.", "Add context and non-negotiable constraints.", "Generate, review, and copy the template."] },
  },
  {
    slug: "token-sayaci", category: "prompt", mark: "03",
    title: { tr: "Token ve Bağlam Sayacı", en: "Token & Context Counter" },
    short: { tr: "Metin uzunluğunu ve yaklaşık token ihtiyacını modelden bağımsız görün.", en: "Estimate text length and token demand without sending it to a model." },
    description: { tr: "Karakter, kelime, satır ve yaklaşık token sayısını hesaplar. Token sonucu bir tahmindir; gerçek değer kullanılan modelin tokenizer yapısına göre değişir. Hızlı bağlam planlaması için güvenli bir ön kontrol sağlar.", en: "Calculates characters, words, lines, and an approximate token count. The token result is an estimate because exact counts vary by model tokenizer; it is intended for safe context planning." },
    useCases: { tr: ["Bağlam penceresi planlama", "Prompt uzunluğu karşılaştırma", "Maliyet ön tahmini"], en: ["Context-window planning", "Prompt length comparison", "Rough cost estimation"] },
    steps: { tr: ["Metni yapıştırın.", "Sayımı çalıştırın.", "Model sınırıyla karşılaştırırken güvenlik payı bırakın."], en: ["Paste your text.", "Run the count.", "Leave a safety margin when comparing with model limits."] },
  },
  {
    slug: "okunabilirlik-analizi", category: "text", mark: "04",
    title: { tr: "Okunabilirlik Analizi", en: "Readability Analyzer" },
    short: { tr: "Cümle ve kelime yapısını ölçerek metnin anlaşılabilirliğini inceleyin.", en: "Assess clarity through sentence and word structure." },
    description: { tr: "Cümle uzunluğu, kelime çeşitliliği ve hece yoğunluğu üzerinden açıklanabilir bir okunabilirlik özeti üretir. Türkçe için Ateşman yaklaşımından, İngilizce için Flesch yaklaşımından esinlenen yaklaşık ölçüler kullanır.", en: "Produces an explainable readability summary using sentence length, lexical variety, and syllable density. It uses approximate measures inspired by Ateşman for Turkish and Flesch for English." },
    useCases: { tr: ["Blog yazısı düzenleme", "Müşteri iletişimi", "Teknik metni sadeleştirme"], en: ["Editing guides", "Customer communication", "Simplifying technical copy"] },
    steps: { tr: ["En az birkaç cümle girin.", "Analizi çalıştırın.", "Uzun cümleleri bölüp sonucu yeniden karşılaştırın."], en: ["Enter at least a few sentences.", "Run the analysis.", "Split long sentences and compare the result again."] },
  },
  {
    slug: "metin-benzerlik-analizi", category: "text", mark: "05",
    title: { tr: "Metin Benzerlik Analizi", en: "Text Similarity Analyzer" },
    short: { tr: "İki metni sözcük örtüşmesi ve kosinüs benzerliğiyle karşılaştırın.", en: "Compare two texts with word overlap and cosine similarity." },
    description: { tr: "İki metni yerel sözcük frekanslarıyla karşılaştırır; Jaccard örtüşmesi ve kosinüs benzerliği verir. Sonuç anlamsal bir yapay zekâ modeli değildir, açıklanabilir sözcük tabanlı bir ölçümdür.", en: "Compares two texts using local word frequencies and returns Jaccard overlap plus cosine similarity. It is an explainable lexical measure, not an AI semantic model." },
    useCases: { tr: ["Sürüm karşılaştırma", "Tekrarlı içerik ön kontrolü", "Özet ile kaynak tutarlılığı"], en: ["Version comparison", "Duplicate-content pre-checks", "Summary-to-source consistency"] },
    steps: { tr: ["İlk metni ana alana girin.", "İkinci metni karşılaştırma alanına ekleyin.", "Benzerlik yüzdelerini bağlamla birlikte yorumlayın."], en: ["Enter the first text.", "Add the comparison text.", "Interpret similarity percentages in context."] },
  },
  {
    slug: "metin-temizleyici", category: "text", mark: "06",
    title: { tr: "Metin Temizleyici", en: "Text Cleaner" },
    short: { tr: "Gereksiz boşlukları, yinelenen satırları ve dağınık biçimi düzeltin.", en: "Fix excess whitespace, duplicate lines, and inconsistent formatting." },
    description: { tr: "Kopyalanmış metinlerdeki gereksiz boşlukları, yinelenen boş satırları ve satır sonu sorunlarını temizler. Metnin anlamını değiştirmeden daha düzenli bir çıktı üretmeyi amaçlar.", en: "Cleans excess spaces, repeated blank lines, and line-ending issues in copied text while preserving the original meaning." },
    useCases: { tr: ["PDF'den kopyalanan metin", "E-posta taslakları", "İçerik yönetim sistemine aktarım"], en: ["Text copied from PDFs", "Email drafts", "CMS preparation"] },
    steps: { tr: ["Dağınık metni yapıştırın.", "Temizle düğmesini kullanın.", "Çıktıyı kontrol edip kopyalayın veya indirin."], en: ["Paste messy text.", "Use the clean action.", "Review, then copy or download the output."] },
  },
  {
    slug: "buyuk-kucuk-harf-donusturucu", category: "text", mark: "07",
    title: { tr: "Büyük/Küçük Harf Dönüştürücü", en: "Case Converter" },
    short: { tr: "Metni cümle, başlık, büyük veya küçük harf biçimine dönüştürün.", en: "Convert text to sentence, title, uppercase, or lowercase form." },
    description: { tr: "Türkçe karakterleri dikkate alarak büyük, küçük, cümle ve başlık biçimleri arasında dönüşüm yapar. Dönüşüm biçimini araç içindeki seçenekten belirleyebilirsiniz.", en: "Converts text between uppercase, lowercase, sentence case, and title case. Choose the desired format inside the tool." },
    useCases: { tr: ["Başlık standardizasyonu", "Sosyal medya metni", "Veri temizliği"], en: ["Headline standardization", "Social copy", "Data cleanup"] },
    steps: { tr: ["Metni girin.", "Dönüşüm biçimini seçin.", "Sonucu üretip kontrol edin."], en: ["Enter text.", "Choose a conversion style.", "Generate and review the result."] },
  },
  {
    slug: "kelime-sayaci", category: "text", mark: "08",
    title: { tr: "Kelime, Karakter ve Okuma Süresi", en: "Word, Character & Reading Time" },
    short: { tr: "İçerik uzunluğunu, paragraf sayısını ve tahmini okuma süresini ölçün.", en: "Measure content length, paragraphs, and estimated reading time." },
    description: { tr: "Kelime, karakter, cümle, paragraf ve satır sayılarını birlikte sunar. Dakikada yaklaşık 200 kelime varsayımıyla okuma süresi tahmini verir.", en: "Reports words, characters, sentences, paragraphs, and lines, plus reading time estimated at roughly 200 words per minute." },
    useCases: { tr: ["SEO içerik planlama", "Konuşma metni süresi", "Editoryal sınır kontrolü"], en: ["SEO content planning", "Speech timing", "Editorial length checks"] },
    steps: { tr: ["Metni yapıştırın.", "Sayımı çalıştırın.", "Sonucu içeriğin amacıyla birlikte değerlendirin."], en: ["Paste your text.", "Run the count.", "Evaluate length against the content's purpose."] },
  },
  {
    slug: "json-bicimlendirici", category: "data", mark: "09",
    title: { tr: "JSON Biçimlendirici ve Doğrulayıcı", en: "JSON Formatter & Validator" },
    short: { tr: "JSON verisini doğrulayın, okunabilir biçime getirin veya küçültün.", en: "Validate, pretty-print, or minify JSON data." },
    description: { tr: "JSON sözdizimini tarayıcıda doğrular ve okunabilir girintili çıktı üretir. Hata varsa yaklaşık konumu ve tarayıcının ayrıştırma mesajını gösterir.", en: "Validates JSON syntax in the browser and produces readable, indented output. Parse errors are surfaced without sending the payload anywhere." },
    useCases: { tr: ["API yanıtı inceleme", "Yapılandırma dosyası düzenleme", "Hatalı JSON bulma"], en: ["Inspecting API responses", "Editing config files", "Finding malformed JSON"] },
    steps: { tr: ["JSON verisini yapıştırın.", "Biçimlendir veya küçült seçeneğini belirleyin.", "Doğrulanan çıktıyı kopyalayın."], en: ["Paste JSON data.", "Choose pretty or minified output.", "Copy the validated result."] },
  },
  {
    slug: "json-csv-donusturucu", category: "data", mark: "10",
    title: { tr: "JSON ↔ CSV Dönüştürücü", en: "JSON ↔ CSV Converter" },
    short: { tr: "Düz nesne dizileri ile CSV tabloları arasında yerel dönüşüm yapın.", en: "Convert flat object arrays and CSV tables locally." },
    description: { tr: "Düz JSON nesne dizilerini CSV'ye, CSV tablolarını JSON'a dönüştürür. Tırnak ve virgül kaçışlarını işler; karmaşık iç içe nesnelerde dönüştürmeden önce yapıyı düzleştirmeniz gerekir.", en: "Converts flat JSON object arrays to CSV and CSV tables to JSON, including standard quote and comma escaping. Nested objects should be flattened first." },
    useCases: { tr: ["E-tablo aktarımı", "Hızlı veri paylaşımı", "Basit rapor dönüşümü"], en: ["Spreadsheet transfer", "Quick data exchange", "Simple report conversion"] },
    steps: { tr: ["JSON dizisi veya CSV tablosu girin.", "Kaynak biçimi seçin.", "Dönüştürüp sonucu örnek verilerle kontrol edin."], en: ["Enter a JSON array or CSV table.", "Choose the source format.", "Convert and verify the result with sample rows."] },
  },
  {
    slug: "regex-test-araci", category: "data", mark: "11",
    title: { tr: "Regex Test Aracı", en: "Regex Tester" },
    short: { tr: "Düzenli ifadeyi eşleşmeler ve gruplarla güvenli biçimde sınayın.", en: "Test regular expressions with matches and groups." },
    description: { tr: "Bir düzenli ifadeyi örnek metin üzerinde çalıştırır; eşleşme sayısı, konum ve yakalama gruplarını listeler. Çok uzun metinler sınırlandırılarak tarayıcı donması riski azaltılır.", en: "Runs a regular expression against sample text and lists match count, positions, and capture groups. Input size is limited to reduce accidental browser freezes." },
    useCases: { tr: ["Doğrulama kalıbı geliştirme", "Log ayrıştırma", "Arama ve değiştirme hazırlığı"], en: ["Validation patterns", "Log parsing", "Search-and-replace preparation"] },
    steps: { tr: ["Test metnini ana alana yazın.", "Regex kalıbını ve bayrakları girin.", "Eşleşmeleri inceleyip kalıbı daraltın."], en: ["Enter sample text.", "Provide the regex pattern and flags.", "Review matches and refine the pattern."] },
  },
  {
    slug: "csv-inceleyici", category: "data", mark: "12",
    title: { tr: "CSV Yapı İnceleyici", en: "CSV Structure Inspector" },
    short: { tr: "Başlıkları, satır sayısını ve tutarsız sütunları hızlıca bulun.", en: "Find headers, row counts, and inconsistent columns." },
    description: { tr: "CSV içeriğini tarayıcıda ayrıştırarak başlıkları, veri satırı sayısını, sütun sayısını ve düzensiz satırları özetler. Büyük dosyalar için önce küçük bir örnekle kontrol önerilir.", en: "Parses CSV content in the browser and summarizes headers, data rows, column count, and inconsistent rows. Start with a representative sample for very large files." },
    useCases: { tr: ["İçe aktarma öncesi kontrol", "Bozuk satır bulma", "Veri şeması keşfi"], en: ["Pre-import checks", "Finding malformed rows", "Schema discovery"] },
    steps: { tr: ["CSV metnini yapıştırın.", "İncelemeyi çalıştırın.", "Düzensiz satır numaralarını kaynak dosyada düzeltin."], en: ["Paste CSV text.", "Run the inspection.", "Fix reported row numbers in the source file."] },
  },
  {
    slug: "base64-kodlayici", category: "data", mark: "13",
    title: { tr: "Base64 Kodlayıcı ve Çözücü", en: "Base64 Encoder & Decoder" },
    short: { tr: "Unicode metni Base64'e dönüştürün veya Base64 metnini çözün.", en: "Encode Unicode text to Base64 or decode it back." },
    description: { tr: "UTF-8 metni Base64'e kodlar veya geçerli Base64 verisini metne çevirir. Base64 şifreleme değildir; yalnızca veri gösterim biçimidir.", en: "Encodes UTF-8 text as Base64 or decodes valid Base64 to text. Base64 is an encoding format, not encryption." },
    useCases: { tr: ["Veri URI hazırlığı", "Hızlı örnek veri dönüşümü", "Kodlama hatası teşhisi"], en: ["Preparing data payloads", "Quick sample conversion", "Diagnosing encoding issues"] },
    steps: { tr: ["Metni girin.", "Kodla veya çöz seçeneğini belirleyin.", "Hassas çıktıyı paylaşmadan önce içeriği kontrol edin."], en: ["Enter text.", "Choose encode or decode.", "Review sensitive output before sharing it."] },
  },
  {
    slug: "url-kodlayici", category: "data", mark: "14",
    title: { tr: "URL Kodlayıcı ve Çözücü", en: "URL Encoder & Decoder" },
    short: { tr: "Sorgu değerlerini güvenli URL bileşenlerine dönüştürün.", en: "Convert query values into safe URL components." },
    description: { tr: "Metni encodeURIComponent standardıyla URL bileşeni olarak kodlar veya geri çözer. Tam URL yerine tek bir parametre değeriyle çalışmak daha güvenlidir.", en: "Encodes text as a URL component with encodeURIComponent or decodes it. It is safest to work on a single parameter value rather than a complete URL." },
    useCases: { tr: ["Sorgu parametresi hazırlama", "Bozuk bağlantı inceleme", "Yönlendirme değeri çözme"], en: ["Preparing query parameters", "Inspecting broken links", "Decoding redirect values"] },
    steps: { tr: ["URL bileşenini girin.", "Kodla veya çöz seçeneğini seçin.", "Sonucu gerçek bağlantıda kullanmadan önce doğrulayın."], en: ["Enter a URL component.", "Choose encode or decode.", "Verify the result before using it in a real link."] },
  },
  {
    slug: "kvkk-veri-maskeleyici", category: "security", mark: "15",
    title: { tr: "KVKK / GDPR Veri Maskeleyici", en: "KVKK / GDPR Data Masker" },
    short: { tr: "E-posta, telefon, IBAN, kart ve IP gibi desenleri cihazınızda maskeleyin.", en: "Mask email, phone, IBAN, card, and IP patterns on-device." },
    description: { tr: "Yaygın kişisel veri desenlerini düzenli ifadelerle bularak okunabilir yer tutucularla değiştirir. Bu araç hukuki uygunluk garantisi vermez; belgeyi paylaşmadan önce insan kontrolü zorunludur.", en: "Finds common personal-data patterns with regular expressions and replaces them with readable placeholders. It does not guarantee legal compliance; human review remains essential." },
    useCases: { tr: ["Destek kaydı anonimleştirme", "Örnek veri hazırlama", "Belge paylaşımı ön kontrolü"], en: ["Anonymizing support tickets", "Preparing sample data", "Pre-sharing document checks"] },
    steps: { tr: ["Metni yalnızca bu tarayıcı sekmesine yapıştırın.", "Maskelemeyi çalıştırın ve bulunan türleri inceleyin.", "Kaçan veya yanlış maskelenen alanları elle doğrulayın."], en: ["Paste text into this browser tab.", "Run masking and review detected types.", "Manually verify missed or incorrect replacements."] },
  },
  {
    slug: "guclu-parola-uretici", category: "security", mark: "16",
    title: { tr: "Güçlü Parola Üretici", en: "Strong Password Generator" },
    short: { tr: "Web Crypto ile 12–128 karakter arasında rastgele parola üretin.", en: "Generate a random 12–128 character password with Web Crypto." },
    description: { tr: "Tarayıcının kriptografik rastgele sayı üreticisini kullanarak güçlü parola oluşturur. Üretilen parola saklanmaz; kullanmadan önce güvenilir bir parola yöneticisine kaydedin.", en: "Uses the browser's cryptographic random-number generator to create a strong password. The result is not stored; save it in a trusted password manager." },
    useCases: { tr: ["Yeni hesap parolası", "Geçici erişim anahtarı", "Parola yöneticisi girdisi"], en: ["New account passwords", "Temporary access secrets", "Password-manager entries"] },
    steps: { tr: ["Uzunluğu seçin; 20 veya üzeri önerilir.", "Parola üretin.", "Sonucu güvenilir parola yöneticisine kaydedin."], en: ["Choose a length; 20 or more is recommended.", "Generate a password.", "Store it in a trusted password manager."] },
  },
  {
    slug: "uuid-uretici", category: "security", mark: "17",
    title: { tr: "UUID v4 Üretici", en: "UUID v4 Generator" },
    short: { tr: "Tarayıcınızda standart rastgele UUID tanımlayıcıları üretin.", en: "Generate standard random UUID identifiers in your browser." },
    description: { tr: "crypto.randomUUID desteği bulunan tarayıcılarda RFC 4122 uyumlu UUID v4 değerleri üretir. UUID bir parola veya kimlik doğrulama belirteci değildir.", en: "Generates RFC 4122 UUID v4 values in browsers that support crypto.randomUUID. A UUID is not a password or authentication token." },
    useCases: { tr: ["Test kaydı kimliği", "Yerel prototip", "Dağıtık kayıt anahtarı"], en: ["Test record IDs", "Local prototypes", "Distributed record keys"] },
    steps: { tr: ["Üret düğmesine basın.", "Değeri kopyalayın.", "Güvenlik sırrı olarak kullanmayın."], en: ["Press generate.", "Copy the value.", "Do not use it as a security secret."] },
  },
  {
    slug: "sha256-ozet-uretici", category: "security", mark: "18",
    title: { tr: "SHA-256 Özet Üretici", en: "SHA-256 Digest Generator" },
    short: { tr: "Metnin SHA-256 bütünlük özetini Web Crypto ile hesaplayın.", en: "Calculate a SHA-256 integrity digest with Web Crypto." },
    description: { tr: "Metni UTF-8 olarak kodlayıp Web Crypto API ile 64 karakterlik SHA-256 özeti üretir. Özet tek yönlüdür ancak parola saklamak için tek başına uygun değildir.", en: "Encodes text as UTF-8 and uses Web Crypto to return a 64-character SHA-256 digest. It is one-way, but plain SHA-256 is not suitable for password storage." },
    useCases: { tr: ["Metin bütünlüğü karşılaştırma", "İçerik parmak izi", "Test verisi özeti"], en: ["Text integrity comparison", "Content fingerprints", "Test-data digests"] },
    steps: { tr: ["Metni girin.", "SHA-256 hesaplamasını çalıştırın.", "Aynı girdinin aynı özeti verdiğini doğrulayın."], en: ["Enter text.", "Run the SHA-256 calculation.", "Verify identical input returns the same digest."] },
  },
  {
    slug: "few-shot-ornek-olusturucu", category: "prompt", mark: "19",
    title: { tr: "Few-shot Örnek Oluşturucu", en: "Few-shot Example Builder" },
    short: { tr: "Bir görevi örnek girdi–çıktı çiftleriyle yapılandırılmış bir prompta dönüştürün.", en: "Turn a task and example input-output pairs into a structured prompt." },
    description: { tr: "Görev tanımı ile örnek girdi–çıktı çiftlerini bir araya getirerek modellerin beklenen deseni daha açık görmesini sağlayan yeniden kullanılabilir bir few-shot prompt üretir. Örnekler yalnızca tarayıcı belleğinde işlenir.", en: "Combines a task description with example input-output pairs to produce a reusable few-shot prompt that makes the expected pattern explicit. Examples are processed only in browser memory." },
    useCases: { tr: ["Sınıflandırma ve etiketleme", "Tutarlı içerik biçimi", "Dönüşüm görevleri için örnekleme"], en: ["Classification and labeling", "Consistent content formats", "Demonstrating transformation tasks"] },
    steps: { tr: ["Modelin yapacağı görevi açık bir cümleyle yazın.", "Her satıra `girdi => çıktı` biçiminde kaliteli örnekler ekleyin.", "Promptu üretip örneklerin çeşitliliğini ve doğruluğunu kontrol edin."], en: ["Describe the model's task in one clear sentence.", "Add strong examples as `input => output`, one per line.", "Generate the prompt and review example quality and coverage."] },
  },
  {
    slug: "sistem-promptu-persona-sablonu", category: "prompt", mark: "20",
    title: { tr: "Sistem Promptu / Persona Şablonu", en: "System Prompt / Persona Template" },
    short: { tr: "Rol, ton, çalışma ilkeleri ve sınırları profesyonel bir sistem promptunda birleştirin.", en: "Combine role, tone, operating principles, and boundaries in a professional system prompt." },
    description: { tr: "Bir rol tanımını görev, hedef kitle, ton, stil, güvenlik sınırları ve çıktı sözleşmesiyle yapılandırır. Üretilen şablon iddialı ama belirsiz persona cümleleri yerine denetlenebilir davranış kuralları kullanır.", en: "Structures a role around mission, audience, tone, style, safety boundaries, and an output contract. The template favors testable behavior rules over vague persona claims." },
    useCases: { tr: ["Kurumsal asistan davranışı", "İçerik tonu standardı", "Destek botu sınırları"], en: ["Company assistant behavior", "Editorial tone standards", "Support-bot boundaries"] },
    steps: { tr: ["Rolü ve temel sorumluluğu tanımlayın.", "Ton, hedef kitle ve değişmez sınırları ekleyin.", "Şablonu üretip gerçek örneklerle sınayın ve daraltın."], en: ["Define the role and primary responsibility.", "Add tone, audience, and non-negotiable boundaries.", "Generate the template, test it with real examples, and refine it."] },
  },
  {
    slug: "metin-farki-diff", category: "text", mark: "21",
    title: { tr: "Metin Farkı (Diff) Aracı", en: "Text Diff Tool" },
    short: { tr: "İki sürümde eklenen ve silinen satır ya da kelimeleri renkli olarak görün.", en: "See added and removed lines or words across two versions." },
    description: { tr: "İki metni satır veya kelime düzeyinde karşılaştırır; silinen parçaları kırmızı, eklenen parçaları yeşil olarak işaretler. Karşılaştırma LCS tabanlı ve tamamen istemci tarafındadır.", en: "Compares two texts at line or word level, marking removals in red and additions in green. The LCS-based comparison runs entirely client-side." },
    useCases: { tr: ["Metin sürümü inceleme", "Editoryal düzeltme kontrolü", "Kod dışı yapılandırma karşılaştırma"], en: ["Reviewing text versions", "Checking editorial revisions", "Comparing non-code configuration"] },
    steps: { tr: ["Eski ve yeni metni ayrı alanlara yapıştırın.", "Satır veya kelime karşılaştırmasını seçin.", "Renkli farkı inceleyip ekleme ve silme sayılarını doğrulayın."], en: ["Paste the old and new text into separate fields.", "Choose line-level or word-level comparison.", "Review the colored diff and verify addition and removal counts."] },
  },
  {
    slug: "markdown-onizleyici", category: "text", mark: "22",
    title: { tr: "Markdown Önizleyici", en: "Markdown Previewer" },
    short: { tr: "Markdown metnini güvenli HTML önizlemesi ve kopyalanabilir kodla birlikte görün.", en: "Preview Markdown as safe HTML and inspect the generated code." },
    description: { tr: "Başlık, liste, bağlantı, alıntı, vurgu ve kod bloklarını tarayıcıda anlık HTML'e dönüştürür. Ham HTML yürütülmez; giriş önce güvenli biçimde kaçışlanır.", en: "Converts headings, lists, links, quotes, emphasis, and code blocks to live HTML in the browser. Raw HTML is never executed; input is escaped first." },
    useCases: { tr: ["README ve dokümantasyon", "İçerik taslağı önizleme", "Güvenli HTML çıktısı hazırlama"], en: ["README and documentation", "Previewing content drafts", "Preparing safe HTML output"] },
    steps: { tr: ["Markdown metnini sol alana yazın veya yapıştırın.", "Sağdaki canlı önizlemeyi ve HTML kodunu kontrol edin.", "Üretilen HTML'i kopyalayın veya dosya olarak indirin."], en: ["Write or paste Markdown in the left field.", "Review the live preview and generated HTML on the right.", "Copy the HTML or download it as a file."] },
  },
  {
    slug: "unix-zaman-damgasi-donusturucu", category: "data", mark: "23",
    title: { tr: "Unix Zaman Damgası Dönüştürücü", en: "Unix Timestamp Converter" },
    short: { tr: "Epoch saniyesi, milisaniye ve okunabilir tarih arasında iki yönlü dönüşüm yapın.", en: "Convert between epoch seconds, milliseconds, and human-readable dates." },
    description: { tr: "Unix zaman damgasını yerel saat ve UTC tarihine çevirir; seçilen normal tarihin saniye ve milisaniye karşılığını üretir. Saat dilimi farkını açıkça gösterir.", en: "Converts Unix timestamps to local and UTC dates and returns seconds and milliseconds for a selected calendar date. Time-zone differences are displayed explicitly." },
    useCases: { tr: ["Log kaydı inceleme", "API tarih alanı dönüştürme", "Saat dilimi hata ayıklama"], en: ["Inspecting log records", "Converting API date fields", "Debugging time-zone issues"] },
    steps: { tr: ["Epoch değeri veya normal bir tarih girin.", "Saniye/milisaniye algısını ve saat dilimini kontrol edin.", "UTC, yerel tarih ve Unix sonuçlarını kopyalayın."], en: ["Enter an epoch value or a calendar date.", "Check unit detection and the displayed time zone.", "Copy the UTC, local, or Unix result."] },
  },
  {
    slug: "jwt-decoder", category: "data", mark: "24",
    title: { tr: "JWT Decoder", en: "JWT Decoder" },
    short: { tr: "JWT Header ve Payload bölümlerini imza doğrulamadan yerel JSON olarak okuyun.", en: "Read JWT header and payload as local JSON without verifying the signature." },
    description: { tr: "JSON Web Token'ın Base64URL kodlu Header ve Payload bölümlerini tarayıcıda çözer; exp, iat ve nbf zamanlarını okunabilir tarihle açıklar. İmzayı doğrulamaz ve tokenı hiçbir sunucuya göndermez.", en: "Decodes the Base64URL header and payload of a JSON Web Token in the browser and explains exp, iat, and nbf times. It does not verify the signature or send the token to a server." },
    useCases: { tr: ["Kimlik doğrulama hata ayıklama", "Claim inceleme", "Süre sonu kontrolü"], en: ["Authentication debugging", "Inspecting claims", "Checking token expiry"] },
    steps: { tr: ["Hassas olmayan test JWT'sini alana yapıştırın.", "Header, Payload ve zaman claim'lerini çözün.", "Sonucun yalnızca decode olduğunu; imza doğrulaması olmadığını unutmayın."], en: ["Paste a non-sensitive test JWT.", "Decode its header, payload, and time claims.", "Remember that decoding does not verify the signature."] },
  },
  {
    slug: "renk-donusturucu", category: "data", mark: "25",
    title: { tr: "HEX / RGB / HSL Renk Dönüştürücü", en: "HEX / RGB / HSL Color Converter" },
    short: { tr: "HEX, RGB ve HSL değerlerini renk seçiciyle anlık olarak eşitleyin.", en: "Synchronize HEX, RGB, and HSL values instantly with a color picker." },
    description: { tr: "HEX, RGB veya HSL biçimlerinden birini girerek diğer iki gösterimi hesaplar ve erişilebilir bir renk önizlemesi sunar. Dönüşümler tamamen tarayıcıda yapılır.", en: "Accepts HEX, RGB, or HSL input, calculates the other representations, and shows an accessible color preview. All conversion happens in the browser." },
    useCases: { tr: ["Tasarım tokenı hazırlama", "CSS rengi dönüştürme", "Marka paleti kontrolü"], en: ["Preparing design tokens", "Converting CSS colors", "Reviewing brand palettes"] },
    steps: { tr: ["Renk seçiciyi kullanın veya desteklenen bir değer girin.", "HEX, RGB ve HSL sonuçlarını birlikte inceleyin.", "İhtiyacınız olan biçimi tek tıklamayla kopyalayın."], en: ["Use the color picker or enter a supported value.", "Review the synchronized HEX, RGB, and HSL results.", "Copy the format you need with one click."] },
  },
  {
    slug: "qr-kod-olusturucu", category: "data", mark: "26",
    title: { tr: "QR Kod Oluşturucu", en: "QR Code Generator" },
    short: { tr: "Metin veya URL için tarayıcıda QR kod üretip PNG ya da SVG indirin.", en: "Generate a QR code for text or a URL and download PNG or SVG." },
    description: { tr: "Girilen içeriği üçüncü taraf QR servisine göndermeden tarayıcıda QR koda dönüştürür. Yüksek çözünürlüklü PNG ve ölçeklenebilir SVG indirme seçenekleri sunar.", en: "Turns input into a QR code in the browser without calling a third-party QR service. Download options include high-resolution PNG and scalable SVG." },
    useCases: { tr: ["Bağlantı paylaşımı", "Etkinlik ve Wi-Fi bilgisi", "Basılı materyal hazırlama"], en: ["Sharing links", "Event and Wi-Fi details", "Preparing printed material"] },
    steps: { tr: ["QR koda dönüştürülecek metin veya URL'yi girin.", "Oluşan kodu ikinci bir cihazla test edin.", "Kullanım amacına göre PNG veya SVG indirin."], en: ["Enter the text or URL to encode.", "Test the generated code with a second device.", "Download PNG or SVG for your intended medium."] },
  },
  {
    slug: "cron-ifadesi-aciklayici", category: "data", mark: "27",
    title: { tr: "Cron İfadesi Açıklayıcı", en: "Cron Expression Explainer" },
    short: { tr: "Beş alanlı klasik cron ifadelerini doğrulayıp insan dilinde açıklayın.", en: "Validate classic five-field cron expressions and explain them in plain language." },
    description: { tr: "Dakika, saat, ayın günü, ay ve haftanın günü alanlarını ayrı ayrı doğrular; yaygın ifadeleri kısa bir zamanlama cümlesine dönüştürür. Sunucu saat diliminin ayrıca kontrol edilmesi gerektiğini hatırlatır.", en: "Validates minute, hour, day-of-month, month, and day-of-week fields and turns common expressions into a short schedule. It also reminds you to verify the server time zone." },
    useCases: { tr: ["CI/CD zamanlaması", "Yedekleme görevi kontrolü", "Sunucu işi dokümantasyonu"], en: ["CI/CD schedules", "Checking backup jobs", "Documenting server tasks"] },
    steps: { tr: ["Beş alanlı cron ifadesini yapıştırın.", "Her alanın geçerli aralığını ve açıklamasını inceleyin.", "Canlı ortamda sunucu saat dilimini ayrıca doğrulayın."], en: ["Paste a five-field cron expression.", "Review the validation and explanation for every field.", "Verify the server time zone separately before production use."] },
  },
  {
    slug: "exif-meta-veri-temizleyici", category: "security", mark: "28",
    title: { tr: "EXIF / Meta Veri Temizleyici", en: "EXIF / Metadata Cleaner" },
    short: { tr: "JPEG ve PNG görsellerdeki hassas metadatayı yerel olarak okuyup temiz bir kopya indirin.", en: "Inspect sensitive JPEG and PNG metadata locally and download a clean copy." },
    description: { tr: "Seçtiğiniz JPEG veya PNG dosyasındaki cihaz, tarih, yazılım, GPS ve metin metadata alanlarını tarayıcıda inceler. Görseli canvas üzerinde yeniden kodlayarak metadata içermeyen yeni bir kopya üretir; dosya sunucuya yüklenmez.", en: "Inspects device, date, software, GPS, and text metadata in a selected JPEG or PNG inside the browser. It re-encodes pixels through canvas to create a clean copy; the file is never uploaded to a server." },
    useCases: { tr: ["Fotoğraf paylaşımı öncesi gizlilik", "Destek kaydı ekran görüntüsü", "Yayınlanacak görsel temizliği"], en: ["Privacy before photo sharing", "Support-ticket screenshots", "Cleaning images before publication"] },
    steps: { tr: ["En fazla 25 MB JPEG veya PNG dosyasını cihazınızdan seçin.", "Bulunan metadata alanlarını ve görsel boyutunu inceleyin.", "Temiz kopyayı üretip indirin; gerekirse indirdiğiniz dosyayı yeniden tarayın."], en: ["Select a JPEG or PNG up to 25 MB from your device.", "Review detected metadata and image dimensions.", "Generate and download the clean copy, then re-scan it if needed."] },
  },
  {
    slug: "sifre-gucu-testi", category: "security", mark: "29",
    title: { tr: "Şifre Gücü Test Aracı", en: "Password Strength Tester" },
    short: { tr: "Uzunluk, çeşitlilik, tahmini entropi ve kırılma süresi üzerinden parolanızı değerlendirin.", en: "Assess a password using length, variety, estimated entropy, and crack time." },
    description: { tr: "Parola uzunluğu, karakter havuzu, tekrarlar ve yaygın örüntüler üzerinden açıklanabilir bir güç tahmini üretir. Parola yalnızca tarayıcı belleğinde kalır; araç sızıntı veritabanı sorgusu yapmaz ve kesin güvenlik garantisi vermez.", en: "Produces an explainable estimate from password length, character pool, repetition, and common patterns. The password remains in browser memory; no breach database is queried and no absolute security guarantee is made." },
    useCases: { tr: ["Yeni parola ön kontrolü", "Parola politikası eğitimi", "Uzunluk ve çeşitlilik karşılaştırması"], en: ["Pre-checking a new password", "Password-policy education", "Comparing length and character variety"] },
    steps: { tr: ["Gerçek parolanızı paylaşılan cihazda girmeyin; mümkünse benzer bir örnek kullanın.", "Güç seviyesi, entropi ve uyarıları inceleyin.", "Kısa veya tahmin edilebilir yapıyı daha uzun benzersiz bir parola cümlesiyle değiştirin."], en: ["Avoid entering a real password on a shared device; use a representative sample when possible.", "Review the strength level, entropy estimate, and warnings.", "Replace short or predictable structure with a longer unique passphrase."] },
  },
  {
    slug: "arac-zinciri-pipeline", category: "data", mark: "30",
    title: { tr: "Araç Zinciri: CSV → Maskeleme → JSON", en: "Tool Pipeline: CSV → Masking → JSON" },
    short: { tr: "CSV verisini tek sayfada inceleyin, hassas alan adaylarını maskeleyin ve JSON ya da CSV indirin.", en: "Inspect CSV, mask sensitive-data candidates, and download JSON or CSV in one page." },
    description: { tr: "CSV dosyasını etkin tarayıcı sekmesinde ayrıştırır; e-posta, telefon, IBAN, T.C. kimlik ve kart numarası adaylarını açıklanabilir kurallarla maskeler ve sonucu JSON veya CSV olarak indirir. Algoritmik tespit hukuki uygunluk ya da gerçek kimlik doğrulama değildir; insan kontrolü gerekir.", en: "Parses CSV in the active browser tab, masks email, phone, IBAN, Turkish ID, and payment-card candidates with explainable rules, then exports JSON or CSV. Algorithmic detection is neither legal compliance nor identity verification; human review is required." },
    useCases: { tr: ["KVKK/GDPR için örnek veri hazırlama", "CSV verisini güvenli JSON taslağına dönüştürme", "Destek ve test kayıtlarını ön temizleme"], en: ["Preparing sample data for GDPR/KVKK", "Turning CSV into a safer JSON draft", "Pre-cleaning support and test records"] },
    steps: { tr: ["CSV dosyası seçin veya metni yapıştırıp sütun önizlemesini kontrol edin.", "Maske türlerini seçin; bulunan adayları ve değişen hücreleri insan gözüyle doğrulayın.", "Temizlenmiş sonucu JSON ya da CSV olarak indirin; kaynak veriyi ayrıca koruyun."], en: ["Choose a CSV file or paste text and verify the column preview.", "Select masking types and manually review detected candidates and changed cells.", "Download the cleaned result as JSON or CSV and protect the source separately."] },
  },
  {
    slug: "json-diff-karsilastirma", category: "data", mark: "31",
    title: { tr: "JSON Diff / Yapısal Karşılaştırma", en: "JSON Diff / Structural Compare" },
    short: { tr: "İki JSON değerinde eklenen, silinen, değişen ve türü değişen yolları bulun.", en: "Find added, removed, changed, and type-changed paths in two JSON values." },
    description: { tr: "İki JSON nesnesini düz metin yerine anahtar, dizi indeksi, değer ve veri türü düzeyinde karşılaştırır. Sonuçları JSON Pointer benzeri yollarla listeler ve tamamen tarayıcıda çalışır; şema doğrulaması veya imza/kimlik doğrulaması yapmaz.", en: "Compares two JSON values by key, array index, value, and data type rather than plain text. It lists results with JSON Pointer-like paths and runs entirely in-browser; it does not validate schemas, signatures, or identities." },
    useCases: { tr: ["API yanıtı sürüm karşılaştırması", "Yapılandırma değişikliği inceleme", "Test fixture regresyon kontrolü"], en: ["Comparing API response versions", "Reviewing configuration changes", "Checking fixture regressions"] },
    steps: { tr: ["Eski ve yeni geçerli JSON değerlerini iki alana yapıştırın.", "Yapısal karşılaştırmayı çalıştırıp yol ve değişiklik türü filtrelerini inceleyin.", "Raporu kopyalayın veya JSON olarak indirin; anlamlı değişiklikleri şemayla ayrıca doğrulayın."], en: ["Paste valid old and new JSON values into the two fields.", "Run structural comparison and inspect path and change-type filters.", "Copy or download the report, then validate meaningful changes against the schema separately."] },
  },
  {
    slug: "curl-kod-donusturucu", category: "data", mark: "32",
    title: { tr: "cURL → Kod Dönüştürücü", en: "cURL to Code Converter" },
    short: { tr: "Bir cURL komutundan JavaScript, Python, PHP ve Node.js kod taslağı üretin.", en: "Generate JavaScript, Python, PHP, and Node.js code drafts from a cURL command." },
    description: { tr: "Yapıştırılan cURL komutunu çalıştırmadan yerel olarak ayrıştırır; URL, yöntem, header ve gövdeyi JavaScript fetch, Python requests, PHP cURL veya Node.js fetch taslağına dönüştürür. Üretilen kod kimlik bilgilerini doğrulamaz; gizli anahtarları paylaşmadan önce çıkarın.", en: "Locally parses a pasted cURL command without executing it and converts its URL, method, headers, and body to JavaScript fetch, Python requests, PHP cURL, or Node.js fetch. Generated code does not authenticate credentials; remove secrets before sharing." },
    useCases: { tr: ["API dokümantasyonunu prototipleme", "İstekleri diller arasında taşıma", "cURL komutunu okunabilir kod olarak inceleme"], en: ["Prototyping API documentation", "Moving requests between languages", "Reviewing a cURL request as readable code"] },
    steps: { tr: ["Güvenli örnek değerler içeren bir cURL komutunu yapıştırın.", "Komutu yerel olarak ayrıştırın ve hedef dili seçin; hiçbir ağ isteği gönderilmez.", "Üretilen taslağı kopyalayıp hata yönetimi, zaman aşımı ve gizli anahtar yönetimini projenize göre tamamlayın."], en: ["Paste a cURL command containing safe example values.", "Parse it locally and choose a target language; no network request is sent.", "Copy the draft and add project-specific error handling, timeouts, and secret management."] },
  },
  {
    slug: "meta-etiket-favicon-uretici", category: "data", mark: "33",
    title: { tr: "Meta Etiket / Favicon Üretici", en: "Meta Tag / Favicon Generator" },
    short: { tr: "SEO, Open Graph, Twitter Card ve favicon etiketlerini tek bir güvenli HTML bloğunda üretin.", en: "Generate SEO, Open Graph, Twitter Card, and favicon tags in one safe HTML block." },
    description: { tr: "Başlık, açıklama, canonical URL, sosyal görsel ve favicon yollarından kaçışlı HTML meta etiketleri, Next.js metadata taslağı ve manifest özeti üretir. Bu ön kontrol arama motoru indeksleme garantisi veya gerçek crawler doğrulaması değildir.", en: "Builds escaped HTML meta tags, a Next.js metadata draft, and a manifest summary from title, description, canonical URL, social image, and favicon paths. This preflight is not an indexing guarantee or real crawler verification." },
    useCases: { tr: ["Yeni sayfa SEO başlangıcı", "OG ve Twitter Card kontrol listesi", "Favicon ve manifest kurulum taslağı"], en: ["New-page SEO setup", "OG and Twitter Card checklist", "Favicon and manifest setup draft"] },
    steps: { tr: ["Site başlığı, açıklaması ve mutlak canonical URL'yi girin.", "Sosyal görsel ile favicon adreslerini ekleyip canlı önizleme ve uyarıları inceleyin.", "HTML veya Next.js taslağını kopyalayın; Search Console ve platform doğrulayıcılarında ayrıca test edin."], en: ["Enter a site title, description, and absolute canonical URL.", "Add social-image and favicon URLs, then review the live preview and warnings.", "Copy the HTML or Next.js draft and test it separately in Search Console and platform validators."] },
  },
  {
    slug: "gorsel-format-donusturucu", category: "converter", mark: "34",
    title: { tr: "PNG / JPG / WebP / SVG Dönüştürücü", en: "PNG / JPG / WebP / SVG Converter" },
    short: { tr: "PNG, JPG, WebP veya SVG görsellerini tarayıcıda PNG, JPG ya da WebP'ye dönüştürün.", en: "Convert PNG, JPG, WebP, or SVG images to PNG, JPG, or WebP in your browser." },
    description: { tr: "Görsel piksellerini etkin tarayıcı sekmesindeki Canvas API ile yeniden kodlar; çıktı biçimi ve kaliteyi seçmenizi sağlar. SVG girdisi rasterleştirilir, dosya yüklenmez ve PNG'den SVG'ye gerçek vektörleştirme iddiası sunulmaz.", en: "Re-encodes image pixels with the Canvas API in the active browser tab and lets you choose output format and quality. SVG input is rasterized, no file is uploaded, and the tool does not claim to vectorize PNG into SVG." },
    useCases: { tr: ["Web için WebP hazırlama", "JPG ile dosya boyutunu azaltma", "SVG önizlemesini PNG'ye rasterleştirme"], en: ["Preparing WebP for the web", "Reducing file size with JPG", "Rasterizing an SVG preview to PNG"] },
    steps: { tr: ["En fazla 25 MB ve 40 megapiksel desteklenen bir görsel seçin.", "PNG, JPG veya WebP çıktısını ve destekleniyorsa kaliteyi belirleyin.", "Yerel önizlemeyi kontrol edip yeni dosyayı indirin; renk ve şeffaflığı kaynakla karşılaştırın."], en: ["Choose a supported image up to 25 MB and 40 megapixels.", "Select PNG, JPG, or WebP output and quality where supported.", "Review the local preview and download the new file; compare color and transparency with the source."] },
  },
  {
    slug: "gorsel-sikistirici", category: "converter", mark: "35",
    title: { tr: "Görsel Sıkıştırıcı", en: "Image Compressor" },
    short: { tr: "Görselin kalite ve en uzun kenarını ayarlayıp WebP veya JPG olarak daha küçük bir kopya üretin.", en: "Adjust image quality and longest edge to produce a smaller WebP or JPG copy." },
    description: { tr: "PNG, JPG veya WebP görselini tarayıcıda yeniden boyutlandırır ve seçilen kayıplı kaliteyle yeniden kodlar. Önce/sonra dosya boyutunu gösterir; sonuç her görselde daha küçük olmayabileceği için kullanıcıya gerçek ölçümü sunar.", en: "Resizes PNG, JPG, or WebP in-browser and re-encodes it at the selected lossy quality. It reports actual before-and-after size because some settings can produce a larger file." },
    useCases: { tr: ["Core Web Vitals için görsel optimizasyonu", "E-posta ekini küçültme", "Mobil yükleme öncesi yeniden boyutlandırma"], en: ["Image optimization for Core Web Vitals", "Reducing email attachment size", "Resizing before mobile upload"] },
    steps: { tr: ["Kaynak görseli seçin; hassas metadata için önce EXIF temizleyiciyi değerlendirin.", "WebP/JPG, en uzun kenar ve kalite değerlerini belirleyip sıkıştırmayı çalıştırın.", "Önce/sonra boyutunu ve görüntü kalitesini inceleyerek uygun kopyayı indirin."], en: ["Choose the source image; consider the EXIF cleaner first for sensitive metadata.", "Set WebP/JPG, longest edge, and quality, then run compression.", "Review actual size and visual quality before downloading the suitable copy."] },
  },
  {
    slug: "gorselden-pdf", category: "converter", mark: "36",
    title: { tr: "Görselden PDF'e Dönüştürücü", en: "Images to PDF Converter" },
    short: { tr: "PNG, JPG, WebP ve SVG görsellerini sıralı, indirilebilir bir PDF dosyasında birleştirin.", en: "Combine PNG, JPG, WebP, and SVG images into one ordered downloadable PDF." },
    description: { tr: "En fazla 20 görseli etkin tarayıcı sekmesinde rasterleştirip dosya sırasıyla PDF sayfalarına yerleştirir. A4 otomatik yön veya görsel boyutu seçilebilir; işlem MIT lisanslı pdf-lib ile dinamik olarak çalışır ve dosyalar sunucuya gönderilmez.", en: "Rasterizes up to 20 images in the active browser tab and places them on PDF pages in file order. Choose automatic A4 orientation or image-sized pages; the operation dynamically uses MIT-licensed pdf-lib and uploads nothing." },
    useCases: { tr: ["Taranmış belgeleri tek PDF yapma", "Sunum görsellerini paylaşılabilir dosyada toplama", "Fatura veya makbuz görsellerini sıralama"], en: ["Combining scanned pages into one PDF", "Collecting presentation images in a shareable file", "Ordering invoice or receipt images"] },
    steps: { tr: ["Toplam 50 MB'ı aşmayan en fazla 20 görsel seçin ve listelenen sırayı kontrol edin.", "A4 otomatik yön veya görsel boyutunda sayfa seçeneğini belirleyin.", "PDF'yi oluşturup sayfa sırası ve okunabilirliği kontrol ederek indirin."], en: ["Choose up to 20 images totaling no more than 50 MB and review their order.", "Select automatic A4 orientation or image-sized pages.", "Build the PDF, verify page order and readability, then download it."] },
  },
  {
    slug: "pdf-birlestirme", category: "converter", mark: "37",
    title: { tr: "PDF Birleştirme", en: "PDF Merge" },
    short: { tr: "Birden fazla PDF dosyasını seçtiğiniz sırayla tek bir yerel PDF çıktısında birleştirin.", en: "Merge multiple PDFs in your chosen order into one local PDF output." },
    description: { tr: "En fazla 15 PDF ve toplam 50 MB veriyi tarayıcı belleğinde açar, sayfaları görünür dosya sırasıyla yeni bir belgeye kopyalar. Şifre korumasını aşmaz; mevcut dijital imzalar yeni dosyada geçerliliğini kaybedebilir.", en: "Opens up to 15 PDFs totaling 50 MB in browser memory and copies pages into a new document in visible file order. It never bypasses encryption, and existing digital signatures may no longer remain valid." },
    useCases: { tr: ["Rapor eklerini tek dosyada toplama", "Bölüm PDF'lerini sıralı teslim etme", "Taranmış dosya setini birleştirme"], en: ["Combining report appendices", "Delivering ordered document sections", "Merging a set of scanned files"] },
    steps: { tr: ["En az iki, toplam 50 MB'ı aşmayan PDF seçin.", "Yukarı/aşağı düğmeleriyle birleştirme sırasını doğrulayın.", "Yeni PDF'yi oluşturup sayfa sayısı ve sırasını kontrol ederek indirin."], en: ["Choose at least two PDFs totaling no more than 50 MB.", "Verify merge order with the up and down controls.", "Create the new PDF, verify page count and order, then download it."] },
  },
  {
    slug: "pdf-bolme", category: "converter", mark: "38",
    title: { tr: "PDF Bölme / Sayfa Ayırma", en: "PDF Split / Page Extractor" },
    short: { tr: "Bir PDF'ten “1-3,5” biçiminde seçtiğiniz sayfaları yeni bir PDF dosyasına ayırın.", en: "Extract selected pages such as “1-3,5” from a PDF into a new PDF file." },
    description: { tr: "PDF sayfa sayısını tarayıcıda okur ve seçilen aralıkları yeni bir belgeye kopyalar. Şifreli belge korumasını kaldırmaz; form davranışı ve dijital imzalar kopyalanan belgede değişebilir.", en: "Reads the PDF page count in-browser and copies selected ranges into a new document. It does not remove encryption; form behavior and digital signatures may change in the copied document." },
    useCases: { tr: ["Uzun rapordan ilgili bölümü çıkarma", "Belirli tarama sayfalarını paylaşma", "Ek veya kapak sayfalarını ayrı dosyaya alma"], en: ["Extracting a relevant report section", "Sharing selected scanned pages", "Separating appendices or cover pages"] },
    steps: { tr: ["En fazla 50 MB tek PDF seçip algılanan toplam sayfayı doğrulayın.", "1-3,5 gibi bir aralık girin; yalnızca yetkili olduğunuz sayfaları işleyin.", "Yeni PDF'yi oluşturup seçilen sayfaları ve belge bütünlüğünü kontrol ederek indirin."], en: ["Choose one PDF up to 50 MB and verify the detected page count.", "Enter a range such as 1-3,5 and process only pages you are authorized to use.", "Build the new PDF, verify selected pages and document integrity, then download it."] },
  },
  {
    slug: "yatirim-getiri-simulatoru", category: "calculation", mark: "39",
    title: { tr: "Yatırım Getiri Simülatörü", en: "Investment Return Simulator" },
    short: { tr: "Başlangıç tutarı, düzenli katkı, getiri, ücret ve enflasyonla farklı senaryoları karşılaştırın.", en: "Compare scenarios using an initial amount, recurring contribution, return, fees, and inflation." },
    description: { tr: "Aylık bileşik büyüme varsayımıyla nominal ve enflasyona göre düzeltilmiş portföy değerini, toplam katkıyı ve ücret etkisini hesaplar. Sonuç yalnızca matematiksel senaryodur; yatırım tavsiyesi, vergi hesabı veya getiri garantisi değildir.", en: "Calculates nominal and inflation-adjusted portfolio value, total contributions, and fee impact using monthly compounding. It is a mathematical scenario—not investment advice, tax calculation, or a return guarantee." },
    useCases: { tr: ["Düzenli yatırım senaryosu karşılaştırma", "Ücret ve enflasyon etkisini görme", "Uzun vadeli hedef için kaba planlama"], en: ["Comparing recurring-investment scenarios", "Understanding fee and inflation impact", "Rough long-term goal planning"] },
    steps: { tr: ["Başlangıç tutarı, aylık katkı ve süreyi girin.", "Yıllık tahmini getiri, ücret ve enflasyon varsayımlarını ekleyin.", "Nominal ve reel sonuçları karşılaştırın; finansal karar için bağımsız uzman görüşü alın."], en: ["Enter the starting amount, monthly contribution, and duration.", "Add assumed annual return, fee, and inflation.", "Compare nominal and real results and seek independent advice for financial decisions."] },
  },
  {
    slug: "birim-donusturucu", category: "calculation", mark: "40",
    title: { tr: "Ölçü / Birim Dönüştürücü", en: "Measurement / Unit Converter" },
    short: { tr: "Uzunluk, kütle, sıcaklık, hacim ve veri boyutu birimlerini anlık dönüştürün.", en: "Convert length, mass, temperature, volume, and data-size units instantly." },
    description: { tr: "Yaygın metrik ve emperyal birimleri tarayıcı içinde görünür formüllerle dönüştürür; sıcaklık için doğrusal olmayan ofseti doğru uygular. Sonuçlar günlük kullanım içindir; düzenlemeye tabi ölçümlerde kalibre edilmiş sistem kullanın.", en: "Converts common metric and imperial units in-browser with visible formulas and correct temperature offsets. Results are for everyday use; regulated measurements require calibrated systems." },
    useCases: { tr: ["Tarif ve seyahat ölçülerini çevirme", "Teknik dokümanda birim kontrolü", "Dosya boyutu karşılaştırma"], en: ["Converting recipe and travel measurements", "Checking units in technical documents", "Comparing data sizes"] },
    steps: { tr: ["Ölçü kategorisini ve kaynak birimi seçin.", "Değeri girip hedef birimi belirleyin.", "Sonucu, kullanılan katsayıyı ve yuvarlamayı kontrol edin."], en: ["Choose a measurement category and source unit.", "Enter a value and select the target unit.", "Review the result, factor, and rounding."] },
  },
  {
    slug: "not-ortalamasi-hesaplayici", category: "calculation", mark: "41",
    title: { tr: "Not Ortalaması Hesaplayıcı", en: "Weighted Grade Calculator" },
    short: { tr: "Ders veya değerlendirme notlarını ağırlıklarıyla hesaplayın ve toplam ağırlığı doğrulayın.", en: "Calculate course or assessment grades with weights and validate the weight total." },
    description: { tr: "Satır bazlı not ve ağırlıklardan ağırlıklı ortalama üretir; geçersiz değerleri ve yüzde toplamındaki sapmayı gösterir. Okulun yuvarlama, geçme ve eksik not kuralları farklı olabilir; sonuç resmî transkript değildir.", en: "Produces a weighted average from row-based scores and weights and reports invalid values or weight-total gaps. School rounding, pass, and missing-grade rules may differ; output is not an official transcript." },
    useCases: { tr: ["Dönem içi ağırlıklı ortalama", "Proje ve sınav paylarını kontrol", "Hedef not senaryosu"], en: ["Term weighted average", "Checking project and exam shares", "Target-grade scenarios"] },
    steps: { tr: ["Her notu ve yüzde ağırlığını ayrı satıra girin.", "Toplam ağırlık ile geçersiz satır uyarılarını kontrol edin.", "Sonucu kurumunuzun resmî hesap yöntemiyle doğrulayın."], en: ["Enter each score and percentage weight on its own row.", "Check total weight and any invalid-row warnings.", "Verify the result against your institution's official method."] },
  },
  {
    slug: "gpa-cevirici", category: "calculation", mark: "42",
    title: { tr: "GPA Çevirici", en: "GPA Converter" },
    short: { tr: "4.0, 5.0, 10.0 ve 100'lük not ölçekleri arasında açıklanmış yaklaşık dönüşüm yapın.", en: "Estimate conversions among 4.0, 5.0, 10.0, and 100-point grade scales." },
    description: { tr: "Yaygın not ölçekleri arasında doğrusal bir yaklaşık dönüşüm sunar ve formülü açıkça gösterir. Üniversiteler ülke, ders ve harf notuna göre farklı doğrusal olmayan tablolar kullanabilir; sonuç resmî denklik değildir.", en: "Provides a clearly labeled linear estimate among common grading scales and shows the formula. Institutions may use country-, course-, or letter-grade-specific nonlinear tables; output is not an official equivalency." },
    useCases: { tr: ["Başvuru öncesi kaba ölçek karşılaştırma", "Farklı not sistemlerini açıklama", "Resmî tabloya hazırlık"], en: ["Rough pre-application scale comparison", "Explaining different grade systems", "Preparing to use an official table"] },
    steps: { tr: ["Kaynak not ölçeğini ve değeri seçin.", "Hedef ölçeği belirleyip yaklaşık sonucu görün.", "Başvuru veya denklik için kurumun resmî tablosunu kullanın."], en: ["Choose the source grade scale and value.", "Select the target scale and view the estimate.", "Use the institution's official table for applications or equivalency."] },
  },
  {
    slug: "kaynakca-atif-formatlayici", category: "general", mark: "43",
    title: { tr: "Kaynakça / Atıf Formatlayıcı (APA/MLA)", en: "Citation Formatter (APA/MLA)" },
    short: { tr: "Kitap, makale ve web kaynağı bilgilerini APA 7 veya MLA 9 taslağına dönüştürün.", en: "Turn book, article, and web-source details into an APA 7 or MLA 9 draft." },
    description: { tr: "Yazar, tarih, başlık, yayın, DOI ve URL alanlarından yerel bir kaynakça taslağı üretir. İtalik, büyük/küçük harf, çok yazarlı kaynak ve kurum kuralları farklılaşabileceği için güncel stil kılavuzuyla son kontrol gerekir.", en: "Builds a local bibliography draft from author, date, title, publication, DOI, and URL fields. Italics, capitalization, multiple authors, and institutional rules require a final check against the current style guide." },
    useCases: { tr: ["Ödev kaynakçası taslağı", "Web kaynağını standartlaştırma", "DOI/URL alanlarını düzenleme"], en: ["Drafting an assignment bibliography", "Standardizing a web source", "Organizing DOI and URL fields"] },
    steps: { tr: ["Kaynak türü ve atıf stilini seçin.", "Bibliyografik alanları kaynaktaki bilgilerle doldurun.", "Taslağı güncel APA/MLA kılavuzu ve kurum kurallarıyla doğrulayın."], en: ["Choose source type and citation style.", "Fill the bibliographic fields from the source.", "Verify the draft against the current APA/MLA guide and institutional rules."] },
  },
  {
    slug: "fatura-sablonu-olusturucu", category: "general", mark: "44",
    title: { tr: "Fatura Şablonu Oluşturucu", en: "Invoice Template Generator" },
    short: { tr: "Taraf, kalem, vergi ve toplam bilgileriyle yazdırılabilir yerel bir fatura taslağı hazırlayın.", en: "Create a printable local invoice draft with party, line-item, tax, and total details." },
    description: { tr: "Fatura bilgilerini tarayıcıda işler, kalemleri ve vergiyi hesaplar ve yazdırılabilir bir taslak üretir. E-fatura göndermez; ülkeye özgü vergi, seri numarası, para birimi ve saklama yükümlülüklerini otomatik doğrulamaz.", en: "Processes invoice details in-browser, calculates line items and tax, and creates a printable draft. It does not issue e-invoices or validate country-specific tax, numbering, currency, or retention requirements." },
    useCases: { tr: ["Serbest çalışan fatura taslağı", "Kalem ve vergi toplamı kontrolü", "Müşteri önizlemesi hazırlama"], en: ["Freelancer invoice drafts", "Checking item and tax totals", "Preparing a client preview"] },
    steps: { tr: ["Satıcı, müşteri, numara, tarih ve para birimini girin.", "Kalemleri miktar ve birim fiyatla ekleyip vergi oranını belirleyin.", "Önizlemeyi kontrol edin; yasal zorunlulukları doğrulayıp yazdırın."], en: ["Enter seller, customer, number, date, and currency.", "Add line items with quantity and unit price, then set tax.", "Review the preview, verify legal requirements, and print."] },
  },
  {
    slug: "basit-sozlesme-sablonu", category: "general", mark: "45",
    title: { tr: "Basit Sözleşme Şablonu", en: "Simple Contract Template" },
    short: { tr: "Taraflar, hizmet, bedel, süre, fesih ve imza alanlarından tarafsız bir sözleşme taslağı oluşturun.", en: "Build a neutral contract draft from parties, scope, fee, term, termination, and signature fields." },
    description: { tr: "Girilen olguları düzenli başlıklara yerleştirerek genel bir hizmet sözleşmesi taslağı üretir. Bu araç hukuk hizmeti sunmaz, ülkeye özgü emredici hükümleri bilmez ve elektronik imza geçerliliğini sağlamaz; imzadan önce uzman incelemesi gerekir.", en: "Places entered facts into a structured general service-agreement draft. It is not legal advice, does not know jurisdiction-specific mandatory terms, and does not establish e-signature validity; qualified review is required before signing." },
    useCases: { tr: ["Görüşme için ilk taslak", "Kapsam ve teslimatı netleştirme", "Uzman incelemesine hazırlık"], en: ["First draft for discussion", "Clarifying scope and deliverables", "Preparing for qualified review"] },
    steps: { tr: ["Taraf, kapsam, teslimat, bedel ve süre bilgilerini girin.", "Fesih ve uygulanacak hukuk alanlarını açıkça tanımlayın.", "Taslağı düzenleyin ve imzadan önce yetkin hukuk uzmanına inceletin."], en: ["Enter parties, scope, deliverables, fee, and term.", "Define termination and governing-law fields clearly.", "Edit the draft and obtain qualified legal review before signing."] },
  },
  {
    slug: "asiri-kesinlik-dil-tarayicisi", category: "ai", mark: "46",
    title: { tr: "Aşırı Kesinlik Dil Tarayıcısı", en: "Overconfidence Language Scanner" },
    short: { tr: "Metindeki mutlak, garantici veya kanıtsız kesinlik ifadelerini işaretleyip daha dengeli seçenekler görün.", en: "Flag absolute, guaranteeing, or unsupported certainty language and review calibrated alternatives." },
    description: { tr: "Her zaman, kesinlikle, garanti, imkânsız ve risksiz gibi ifadeleri açıklanabilir kurallarla bulur; bağlamı koruyan daha ölçülü alternatifler önerir. Bu dilbilimsel ön kontroldür; gerçeklik doğrulaması veya model tabanlı niyet analizi değildir.", en: "Finds terms such as always, definitely, guaranteed, impossible, and risk-free with explainable rules and suggests more calibrated alternatives. It is a language pre-check, not fact verification or model-based intent analysis." },
    useCases: { tr: ["Pazarlama iddialarını gözden geçirme", "AI yanıt tonunu kalibre etme", "Risk açıklamasını dengeleme"], en: ["Reviewing marketing claims", "Calibrating AI response tone", "Balancing risk disclosures"] },
    steps: { tr: ["İncelenecek metni girin.", "Kesinlik işaretlerini ve önerilen alternatifleri çalıştırın.", "Her bulguyu gerçek bağlam ve kanıt düzeyiyle insan olarak değerlendirin."], en: ["Enter the text to review.", "Run the certainty markers and suggested alternatives.", "Evaluate every finding against real context and evidence level."] },
  },
  {
    slug: "konusma-disa-aktarma-formatlayici", category: "ai", mark: "47",
    title: { tr: "Konuşma Dışa Aktarma Formatlayıcı", en: "Conversation Export Formatter" },
    short: { tr: "Konuşma dökümlerini Markdown, JSONL veya sade metin olarak düzenleyin ve hassas alanları gözden geçirin.", en: "Normalize conversation transcripts as Markdown, JSONL, or plain text and review sensitive fields." },
    description: { tr: "Rol: içerik satırlarını veya yaygın JSON mesaj dizilerini tarayıcıda ayrıştırıp tutarlı dışa aktarma biçimi üretir. Paylaşmadan önce kişisel veri, gizli anahtar ve üçüncü taraf içerik haklarını kullanıcı kontrol etmelidir.", en: "Parses role-prefixed lines or common JSON message arrays in-browser and produces consistent exports. Before sharing, users must review personal data, secrets, and third-party content rights." },
    useCases: { tr: ["Sohbet arşivini Markdown'a çevirme", "Model değerlendirmesi için JSONL hazırlama", "Kişisel veri ön kontrolü"], en: ["Converting a chat archive to Markdown", "Preparing JSONL for model evaluation", "Personal-data pre-checks"] },
    steps: { tr: ["Konuşmayı rol satırları veya JSON mesaj dizisi olarak yapıştırın.", "Hedef biçimi seçip yerel ayrıştırmayı çalıştırın.", "Hassas içerikleri kaldırın ve yalnızca yetkili olduğunuz konuşmaları dışa aktarın."], en: ["Paste the conversation as role lines or a JSON message array.", "Choose the target format and run local parsing.", "Remove sensitive content and export only conversations you are authorized to use."] },
  },
  {
    slug: "token-baglam-butcesi-planlayici", category: "ai", mark: "48",
    title: { tr: "Token / Bağlam Bütçesi Planlayıcı", en: "Token / Context Budget Planner" },
    short: { tr: "Bağlam penceresini sistem talimatı, geçmiş, kaynak, kullanıcı girdisi, çıktı ve güvenlik payına bölün.", en: "Allocate a context window across system instructions, history, sources, user input, output, and safety margin." },
    description: { tr: "Seçilen bağlam sınırında bölümlere ayrılan yaklaşık token bütçesini hesaplar ve aşım riskini görünür kılar. Model tokenizer'ı, gizli sistem ekleri ve sağlayıcı rezervleri sonucu değiştirebilir; değerler planlama tahminidir.", en: "Calculates an approximate sectioned token budget for a chosen context limit and surfaces overflow risk. Model tokenizers, hidden system additions, and provider reserves can change actual usage; values are planning estimates." },
    useCases: { tr: ["RAG bağlam paylaştırma", "Uzun konuşma bütçesi", "Çıktı payı ve güvenlik rezervi"], en: ["RAG context allocation", "Long-conversation budgeting", "Output share and safety reserve"] },
    steps: { tr: ["Model bağlam sınırını ve beklenen çıktı payını girin.", "Sistem, geçmiş, kaynak ve kullanıcı girdisi tahminlerini ekleyin.", "Kalan rezervi kontrol edip gerçek tokenizer ölçümüyle doğrulayın."], en: ["Enter the model context limit and expected output allocation.", "Add estimates for system, history, sources, and user input.", "Review remaining reserve and verify with the actual tokenizer."] },
  },
  {
    slug: "sistem-promptu-netlik-kontrolu", category: "ai", mark: "49",
    title: { tr: "Sistem Promptu Netlik Kontrolü", en: "System Prompt Clarity Checker" },
    short: { tr: "Amaç, yetki, sınır, çelişki, belirsizlik ve çıktı sözleşmesini şeffaf kurallarla kontrol edin.", en: "Check purpose, authority, boundaries, conflicts, ambiguity, and output contract with transparent rules." },
    description: { tr: "Sistem promptunu tamamen yerel kurallarla inceler; görev kapsamı, talimat önceliği, başarısızlık davranışı, veri sınırları ve çıktı biçimindeki boşlukları listeler. Araç bir model çağırmaz ve güvenli davranış garantisi vermez.", en: "Reviews a system prompt using fully local rules and lists gaps in scope, instruction priority, failure behavior, data boundaries, and output format. It calls no model and does not guarantee safe behavior." },
    useCases: { tr: ["Üretim öncesi prompt inceleme", "Talimat çelişkisi bulma", "Güvenlik sınırlarını netleştirme"], en: ["Pre-production prompt review", "Finding instruction conflicts", "Clarifying safety boundaries"] },
    steps: { tr: ["Sistem promptunu eksiksiz yapıştırın.", "Kural tabanlı netlik kontrolünü çalıştırıp bulguları inceleyin.", "Promptu güncelleyin ve gerçek model davranışını ayrıca test edin."], en: ["Paste the complete system prompt.", "Run the rule-based clarity check and review findings.", "Update the prompt and test actual model behavior separately."] },
  },
  {
    slug: "rol-persona-tutarlilik-kontrolu", category: "ai", mark: "50",
    title: { tr: "Rol / Persona Tutarlılık Kontrolü", en: "Role / Persona Consistency Checker" },
    short: { tr: "Persona tanımı ile örnek yanıtları ton, rol, sınır ve yasaklı davranış açısından karşılaştırın.", en: "Compare a persona definition and sample responses for tone, role, boundaries, and prohibited behavior." },
    description: { tr: "Persona kuralları ve örnek cevaplarda görülen ton, birinci şahıs, yetki, kesinlik ve sınır ifadelerini karşılaştırır. Heuristik sonuçlar semantik model testi, jailbreak değerlendirmesi veya red-team çalışması değildir.", en: "Compares tone, first-person identity, authority, certainty, and boundary signals between persona rules and sample replies. Heuristic results are not semantic model testing, jailbreak evaluation, or red teaming." },
    useCases: { tr: ["Bot persona kalite kontrolü", "Örnek yanıt uyumu", "Rol ve yetki sınırı denetimi"], en: ["Bot persona QA", "Sample-response alignment", "Role and authority boundary checks"] },
    steps: { tr: ["Persona/rol kurallarını ilk alana girin.", "Örnek model yanıtlarını ikinci alana ekleyin.", "Bulguları bağlam içinde inceleyip gerçek model testleriyle doğrulayın."], en: ["Enter persona and role rules in the first field.", "Add sample model responses to the second field.", "Review findings in context and verify with real model tests."] },
  },
  {
    slug: "dosya-risk-on-taramasi", category: "codeSecurity", mark: "51",
    title: { tr: "Yerel Dosya Risk Ön Taraması", en: "Local File Risk Pre-Scan" },
    short: { tr: "Dosyanın uzantı, imza, çift uzantı, makro göstergesi ve sınırlı içerik örneklerini yüklemeden inceleyin.", en: "Inspect extension, signature, double extension, macro indicators, and bounded content samples without uploading." },
    description: { tr: "Dosya adı, boyut, magic byte, MIME uyumu ve riskli metin kalıplarını tarayıcı içinde inceler; dosyayı çalıştırmaz veya sunucuya göndermez. Bu araç antivirüs değildir ve yeni, paketlenmiş ya da karmaşık zararlıyı kesin olarak bulamaz veya güvenli ilan edemez.", en: "Inspects filename, size, magic bytes, MIME consistency, and risky text patterns in-browser without executing or uploading the file. It is not antivirus and cannot conclusively detect or clear new, packed, or complex malware." },
    useCases: { tr: ["İndirilmiş dosyayı ilk triyaj", "Uzantı/imza uyumsuzluğu", "Makro ve betik göstergesi arama"], en: ["Initial triage of a downloaded file", "Extension/signature mismatch checks", "Macro and script indicator search"] },
    steps: { tr: ["Yalnızca incelemeye yetkili olduğunuz dosyayı seçin.", "Boyut sınırlı yerel taramayı çalıştırın; dosya hiçbir zaman açılıp çalıştırılmaz.", "Şüpheli bulguda dosyayı izole edin ve güncel profesyonel güvenlik ürünüyle doğrulayın."], en: ["Choose only a file you are authorized to inspect.", "Run the size-bounded local scan; the file is never opened or executed.", "If findings are suspicious, isolate the file and verify with a current professional security product."] },
  },
  {
    slug: "kod-guvenligi-on-taramasi", category: "codeSecurity", mark: "52",
    title: { tr: "Kod Güvenliği Ön Taraması", en: "Code Security Pre-Scan" },
    short: { tr: "Kaynak kodunda riskli API, tehlikeli sink, zayıf kripto ve gömülü sır kalıplarını yerel olarak bulun.", en: "Find risky APIs, dangerous sinks, weak crypto, and embedded-secret patterns locally in source code." },
    description: { tr: "Kod metnini zaman sınırlı Web Worker içinde açıklanabilir Regex kurallarıyla tarar; eval, innerHTML, shell komutu, SQL birleştirme, zayıf hash ve olası anahtar kalıplarını satır numarasıyla raporlar. Derleme akışını veya veri akışını anlamadığı için tam SAST ve uzman kod incelemesinin yerini tutmaz.", en: "Scans code in a time-bounded Web Worker with explainable regex rules and reports eval, innerHTML, shell commands, SQL concatenation, weak hashes, and possible secrets with line numbers. It cannot understand full builds or data flow and does not replace SAST or expert review." },
    useCases: { tr: ["Pull request ön kontrolü", "Kod örneğinde sır arama", "Güvenlik incelemesine hazırlık"], en: ["Pull-request pre-checks", "Secret discovery in snippets", "Preparing for security review"] },
    steps: { tr: ["Yalnızca inceleme yetkiniz bulunan kaynak kodunu yapıştırın.", "Dil seçip yerel, zaman sınırlı taramayı çalıştırın.", "Her bulguyu veri akışı ve bağlamla doğrulayın; sırları derhal döndürün/iptal edin."], en: ["Paste only source code you are authorized to inspect.", "Choose a language and run the local time-bounded scan.", "Verify each finding against data flow and context; rotate exposed secrets immediately."] },
  },
  {
    slug: "url-guvenlik-on-kontrolu", category: "codeSecurity", mark: "53",
    title: { tr: "URL Güvenlik Ön Kontrolü", en: "URL Security Pre-Check" },
    short: { tr: "URL'yi ziyaret etmeden kimlik bilgisi, IP host, Punycode, yönlendirme parametresi ve gizleme sinyallerini inceleyin.", en: "Inspect credentials, IP hosts, Punycode, redirect parameters, and obfuscation signals without visiting the URL." },
    description: { tr: "URL nesnesini tarayıcıda ayrıştırır ve kullanıcı adı/parola, sayısal IP, xn-- alanı, çok sayıda alt alan, kodlanmış karakter ve yönlendirme parametrelerini işaretler. Ağ isteği yapmadığı için itibar, sertifika, indirme veya sayfa içeriğini doğrulayamaz.", en: "Parses a URL in-browser and flags embedded credentials, numeric IPs, xn-- domains, excessive subdomains, encoded characters, and redirect parameters. Because it makes no request, it cannot verify reputation, certificates, downloads, or page content." },
    useCases: { tr: ["Şüpheli bağlantı ilk kontrolü", "Yönlendirme parametresi inceleme", "Punycode ve IP host farkındalığı"], en: ["Initial suspicious-link checks", "Inspecting redirect parameters", "Punycode and IP-host awareness"] },
    steps: { tr: ["Bağlantıyı tıklamadan metin olarak alana yapıştırın.", "Yerel yapısal analizi çalıştırıp host ve parametre bulgularını inceleyin.", "Şüphede bağlantıyı açmayın; kurumunuzun izole itibar ve güvenlik süreçlerini kullanın."], en: ["Paste the link as text without opening it.", "Run local structural analysis and review host and parameter findings.", "If uncertain, do not open it; use your organization's isolated reputation and security process."] },
  },
  {
    slug: "prompt-sablon-degisken-doldurucu", category: "prompt", mark: "54",
    title: { tr: "Prompt Şablonu ve Değişken Doldurucu", en: "Prompt Template & Variable Filler" },
    short: { tr: "{{değişken}} alanları içeren tekrar kullanılabilir promptları güvenli biçimde doldurun.", en: "Fill reusable prompts containing {{variable}} placeholders safely and consistently." },
    description: { tr: "Bir prompt şablonundaki adlandırılmış değişkenleri bulur, `değişken=değer` satırlarıyla yerel olarak doldurur ve eksik alanları görünür bırakır. Araç modeli çağırmaz; üretilen promptun doğruluğu ve hassas veri içermemesi kullanıcı tarafından kontrol edilmelidir.", en: "Finds named placeholders in a prompt template, fills them locally from `variable=value` rows, and leaves missing values visible. It does not call a model; users must review accuracy and sensitive-data exposure." },
    useCases: { tr: ["Ekip prompt şablonlarını standardize etme", "Tekrarlanan içerik görevlerini hızlandırma", "Eksik prompt değişkenlerini bulma"], en: ["Standardizing team prompt templates", "Speeding up repeatable content tasks", "Finding missing prompt variables"] },
    steps: { tr: ["Şablona `{{değişken}}` yer tutucuları ekleyin.", "Her değeri ayrı bir `değişken=değer` satırıyla girin.", "Doldurulan promptu ve eksik değişken uyarılarını inceleyin."], en: ["Add `{{variable}}` placeholders to the template.", "Enter each value on a separate `variable=value` line.", "Review the filled prompt and any missing-variable warning."] },
  },
  {
    slug: "yerel-metin-ozetleyici", category: "text", mark: "55",
    title: { tr: "Yerel Metin Özetleyici", en: "Local Text Summarizer" },
    short: { tr: "Uzun metinden sözcük sıklığına dayalı, açıklanabilir bir cümle özeti çıkarın.", en: "Create an explainable sentence summary from long text using local word frequency." },
    description: { tr: "Metni sunucuya veya yapay zekâ modeline göndermeden cümlelere ayırır, sözcük sıklığıyla puanlar ve seçilen sayıda özgün cümleyi kaynak sırasıyla döndürür. Bu çıkarımsal yöntem bağlamı insan gibi anlamaz ve kritik ayrıntıları kaçırabilir.", en: "Splits text into sentences, scores them by word frequency, and returns selected original sentences in source order without a server or AI model. This extractive method does not understand context like a person and may miss critical detail." },
    useCases: { tr: ["Uzun notlardan hızlı ön okuma", "Toplantı metni ilk özeti", "Kaynak cümleleri bozmadan kısaltma"], en: ["Quick pre-reading of long notes", "First-pass meeting transcript summaries", "Shortening without rewriting source sentences"] },
    steps: { tr: ["Kaynak metni yapıştırın.", "İstenen özet cümlesi sayısını belirleyin.", "Çıkarılan cümleleri kaynakla karşılaştırıp eksik bağlamı tamamlayın."], en: ["Paste the source text.", "Choose the number of summary sentences.", "Compare extracted sentences with the source and restore missing context."] },
  },
  {
    slug: "json-schema-olusturucu", category: "data", mark: "56",
    title: { tr: "JSON Schema Oluşturucu", en: "JSON Schema Generator" },
    short: { tr: "Örnek JSON'dan Draft 2020-12 uyumlu başlangıç şeması çıkarın.", en: "Infer a Draft 2020-12 starter schema from sample JSON." },
    description: { tr: "Geçerli JSON örneğinin nesne, dizi, alan ve temel türlerini inceleyerek düzenlenebilir bir JSON Schema başlangıcı üretir. Şema yalnızca verilen örneği yansıtır; opsiyonel alanlar, biçimler ve gerçek veri varyasyonları ayrıca modellenmelidir.", en: "Inspects objects, arrays, properties, and primitive types in valid sample JSON to produce an editable JSON Schema starter. It reflects only the supplied example; optional fields, formats, and real data variants require further modeling." },
    useCases: { tr: ["API sözleşmesine hızlı başlangıç", "Yapılandırma verisini belgeleme", "Test fixture türlerini görünür kılma"], en: ["Fast API contract starting point", "Documenting configuration data", "Making fixture types visible"] },
    steps: { tr: ["Temsil gücü yüksek geçerli JSON örneğini girin.", "Şemayı üretip alan türlerini ve required listesini inceleyin.", "Gerçek veri varyasyonlarıyla test edip kısıtları elle iyileştirin."], en: ["Enter representative valid JSON.", "Generate the schema and review property types and required fields.", "Test against real variants and refine constraints manually."] },
  },
  {
    slug: "gorsel-boyutlandirici", category: "converter", mark: "57",
    title: { tr: "Görsel Boyutlandırıcı", en: "Image Resizer" },
    short: { tr: "PNG, JPG veya WebP görseli oranını koruyarak yeniden boyutlandırın ve dönüştürün.", en: "Resize and re-encode PNG, JPG, or WebP while preserving aspect ratio." },
    description: { tr: "Tek bir görseli tarayıcı Canvas API'siyle en fazla 8192 piksele boyutlandırır, kutuya sığdırma ve JPG/WebP kalite kontrolü sunar. Dosya yüklenmez; çıktı cihazda oluşturulur. Profesyonel baskı renk profilleri ve tüm metadata korunmaz.", en: "Resizes one image up to 8192 pixels with browser Canvas, fit-within behavior, and JPG/WebP quality control. Files are not uploaded and output is created on-device. Professional print color profiles and all metadata are not preserved." },
    useCases: { tr: ["Web görseli hazırlama", "E-posta eki küçültme", "Sosyal medya boyutu oluşturma"], en: ["Preparing web images", "Reducing email attachments", "Creating social-media dimensions"] },
    steps: { tr: ["25 MB'a kadar PNG, JPG veya WebP seçin.", "Hedef kutuyu, en-boy oranını, biçimi ve kaliteyi belirleyin.", "Önizleme ve dosya boyutunu kontrol edip yeni görseli indirin."], en: ["Choose a PNG, JPG, or WebP up to 25 MB.", "Set the target box, aspect ratio, format, and quality.", "Review preview and file size, then download the new image."] },
  },
  {
    slug: "dosya-hash-karsilastirici", category: "security", mark: "58",
    title: { tr: "Dosya Hash Hesaplayıcı ve Karşılaştırıcı", en: "File Hash Calculator & Comparator" },
    short: { tr: "Bir veya iki dosyanın SHA-256 özetini hesaplayıp bütünlük eşleşmesini kontrol edin.", en: "Calculate SHA-256 for one or two files and compare integrity locally." },
    description: { tr: "Dosyaları sunucuya göndermeden Web Crypto ile SHA-256 özeti üretir ve iki dosyanın bayt düzeyinde aynı olup olmadığını gösterir. Hash eşleşmesi bütünlüğe yardımcı olur; dosyanın güvenliğini, kaynağını veya imza sahibini doğrulamaz.", en: "Uses Web Crypto to create SHA-256 digests without uploading files and reports whether two files match byte-for-byte. A matching hash supports integrity checks but does not verify safety, provenance, or signer identity." },
    useCases: { tr: ["İndirilen dosyayı yayıncı hash'iyle karşılaştırma", "Dosya kopyalarının aynı olduğunu kontrol", "Arşiv teslimi bütünlük kaydı"], en: ["Comparing a download with a publisher hash", "Checking whether file copies match", "Recording archive-delivery integrity"] },
    steps: { tr: ["100 MB'a kadar bir dosya, karşılaştırma için isteğe bağlı ikinci dosya seçin.", "SHA-256 hesaplamasını cihazınızda çalıştırın.", "Hash'i güvenilir ayrı bir kanaldaki beklenen değerle karşılaştırın."], en: ["Choose one file up to 100 MB and optionally a second for comparison.", "Calculate SHA-256 on your device.", "Compare it with an expected value obtained through a separate trusted channel."] },
  },
  {
    slug: "kredi-odeme-hesaplayici", category: "calculation", mark: "59",
    title: { tr: "Kredi Ödeme ve Taksit Hesaplayıcı", en: "Loan Payment & Installment Calculator" },
    short: { tr: "Aylık faiz, vade ve masrafla eşit taksitli kredi senaryosu hesaplayın.", en: "Model an equal-payment loan using monthly interest, term, and fees." },
    description: { tr: "Standart anüite formülüyle aylık taksit, toplam geri ödeme, toplam faiz/masraf ve ilk 12 dönemlik örnek ödeme dökümü üretir. Kurumların günlük faiz, vergi, sigorta ve yuvarlama uygulamaları dahil değildir; sonuç teklif veya finansal tavsiye değildir.", en: "Uses the standard annuity formula to calculate monthly payment, total repayment, interest plus fees, and a first-12-period sample. Lender-specific daily interest, taxes, insurance, and rounding are excluded; output is not an offer or financial advice." },
    useCases: { tr: ["Kredi senaryolarını karşılaştırma", "Vade etkisini görme", "Toplam maliyet ön tahmini"], en: ["Comparing loan scenarios", "Understanding term impact", "Estimating total cost"] },
    steps: { tr: ["Kredi tutarı, aylık faiz, vade ve tek seferlik masrafı girin.", "Ödeme planını hesaplayın.", "Sonucu bankanın resmi ödeme planı ve mevzuata uygun maliyet oranıyla doğrulayın."], en: ["Enter principal, monthly interest, term, and one-time fees.", "Calculate the repayment scenario.", "Verify it against the lender's official schedule and regulated cost disclosures."] },
  },
  {
    slug: "tarih-farki-hesaplayici", category: "general", mark: "60",
    title: { tr: "Tarih Farkı Hesaplayıcı", en: "Date Difference Calculator" },
    short: { tr: "İki tarih arasındaki gün, hafta, yaklaşık yıl ve hafta içi gün sayısını bulun.", en: "Find calendar days, weeks, approximate years, and weekdays between two dates." },
    description: { tr: "Saat dilimi kaymalarını önlemek için iki tarihi UTC takvim günü olarak karşılaştırır; uç günleri dahil etme seçeneği ve resmi tatiller hariç hafta içi gün sayısı verir. Hukuki süreler ve kurumsal çalışma takvimleri için resmi kurallar ayrıca uygulanmalıdır.", en: "Compares dates as UTC calendar days to avoid time-zone drift, with optional inclusive endpoints and weekday counts excluding public holidays. Legal deadlines and organizational calendars require their official rules." },
    useCases: { tr: ["Proje süresi hesaplama", "Yaş ve yıldönümü aralığı", "Hafta içi iş günü ön tahmini"], en: ["Project-duration calculation", "Age and anniversary intervals", "Weekday planning estimates"] },
    steps: { tr: ["Başlangıç ve bitiş tarihlerini seçin.", "Gerekirse iki uç tarihi dahil edin.", "Takvim sonucunu resmi tatil, saat dilimi ve mevzuat kurallarıyla doğrulayın."], en: ["Choose start and end dates.", "Optionally include both endpoints.", "Verify the result against public holidays, time zones, and applicable deadline rules."] },
  },
  {
    slug: "ai-yanit-degerlendirme-rubrigi", category: "ai", mark: "61",
    title: { tr: "AI Yanıt Değerlendirme Rubriği", en: "AI Response Evaluation Rubric" },
    short: { tr: "Göreve özel ölçüt, ağırlık ve dört seviyeli insan değerlendirme rubriği oluşturun.", en: "Build task-specific criteria, weights, and a four-level human evaluation rubric." },
    description: { tr: "Görev ve `ölçüt|ağırlık|kontrol sorusu` satırlarından yeniden kullanılabilir Markdown rubriği üretir, ağırlık toplamını doğrular ve insan incelemesini yapılandırır. Araç yanıtı otomatik puanlamaz; doğruluk, güvenlik veya model kalitesi garantisi vermez.", en: "Creates a reusable Markdown rubric from a task and `criterion|weight|review question` rows, validates total weight, and structures human review. It does not automatically score responses or guarantee accuracy, safety, or model quality." },
    useCases: { tr: ["Model yanıtı kalite kontrolü", "Ekipler arası tutarlı değerlendirme", "AI regresyon test planı"], en: ["Model-response quality review", "Consistent evaluation across teams", "AI regression test planning"] },
    steps: { tr: ["Değerlendirilecek görevi ve hedef kullanıcıyı açıklayın.", "Her ölçütü ağırlık ve denetlenebilir soruyla yazın.", "Toplamı %100 yapıp gerçek örneklerle değerlendiriciler arası uyumu test edin."], en: ["Describe the task and target user.", "Write every criterion with a weight and auditable review question.", "Make weights total 100% and test reviewer agreement on real examples."] },
  },
  {
    slug: "csp-olusturucu-denetleyici", category: "codeSecurity", mark: "62",
    title: { tr: "CSP Oluşturucu ve Denetleyici", en: "CSP Builder & Auditor" },
    short: { tr: "Content-Security-Policy başlığı için güvenli başlangıç üretin ve riskli kaynakları tarayın.", en: "Generate a secure Content-Security-Policy starter and audit risky sources." },
    description: { tr: "CSP direktiflerini yerel olarak ayrıştırır; eksik temel direktifler, wildcard, HTTP, unsafe-eval ve script unsafe-inline gibi yüksek riskli sinyalleri raporlar. Üretilen başlangıç politikası gerçek site bağımlılıklarına göre Report-Only modunda test edilmeden doğrudan uygulanmamalıdır.", en: "Parses CSP directives locally and reports missing baseline directives, wildcards, HTTP, unsafe-eval, and script unsafe-inline signals. The generated starter must be tested in Report-Only mode against real dependencies before enforcement." },
    useCases: { tr: ["Yeni web uygulaması CSP başlangıcı", "Güvenlik header incelemesi", "Üçüncü taraf kaynak envanteri"], en: ["CSP starting point for web apps", "Security-header reviews", "Third-party source inventory"] },
    steps: { tr: ["Mevcut CSP başlığını yapıştırın veya güvenli başlangıcı yükleyin.", "Yapısal denetimi çalıştırıp yüksek ve orta bulguları inceleyin.", "Politikayı önce Report-Only olarak gerçek sayfada test edin ve ihlal raporlarıyla daraltın."], en: ["Paste the current CSP or load the secure starter.", "Run structural audit and review high/medium findings.", "Test in Report-Only mode on the real site and refine it from violation reports."] },
  },
];

export const tools: Tool[] = baseTools.map(localizeTool);

const relatedBySlug: Record<string, string[]> = {
  "prompt-kalite-denetimi": ["meta-prompt-olusturucu", "few-shot-ornek-olusturucu", "sistem-promptu-persona-sablonu"],
  "meta-prompt-olusturucu": ["sistem-promptu-persona-sablonu", "few-shot-ornek-olusturucu", "prompt-kalite-denetimi"],
  "few-shot-ornek-olusturucu": ["sistem-promptu-persona-sablonu", "meta-prompt-olusturucu", "token-sayaci"],
  "sistem-promptu-persona-sablonu": ["prompt-kalite-denetimi", "few-shot-ornek-olusturucu", "meta-prompt-olusturucu"],
  "metin-benzerlik-analizi": ["metin-farki-diff", "okunabilirlik-analizi", "kelime-sayaci"],
  "metin-farki-diff": ["metin-benzerlik-analizi", "markdown-onizleyici", "metin-temizleyici"],
  "markdown-onizleyici": ["metin-farki-diff", "metin-temizleyici", "kelime-sayaci"],
  "json-bicimlendirici": ["json-csv-donusturucu", "jwt-decoder", "base64-kodlayici"],
  "json-csv-donusturucu": ["json-bicimlendirici", "csv-inceleyici", "base64-kodlayici"],
  "jwt-decoder": ["base64-kodlayici", "unix-zaman-damgasi-donusturucu", "json-bicimlendirici"],
  "unix-zaman-damgasi-donusturucu": ["jwt-decoder", "cron-ifadesi-aciklayici", "json-bicimlendirici"],
  "renk-donusturucu": ["qr-kod-olusturucu", "base64-kodlayici", "url-kodlayici"],
  "qr-kod-olusturucu": ["url-kodlayici", "renk-donusturucu", "base64-kodlayici"],
  "cron-ifadesi-aciklayici": ["unix-zaman-damgasi-donusturucu", "regex-test-araci", "json-bicimlendirici"],
  "exif-meta-veri-temizleyici": ["gorsel-sikistirici", "gorsel-format-donusturucu", "kvkk-veri-maskeleyici"],
  "sifre-gucu-testi": ["guclu-parola-uretici", "sha256-ozet-uretici", "exif-meta-veri-temizleyici"],
  "guclu-parola-uretici": ["sifre-gucu-testi", "sha256-ozet-uretici", "uuid-uretici"],
  "arac-zinciri-pipeline": ["kvkk-veri-maskeleyici", "json-csv-donusturucu", "csv-inceleyici"],
  "json-diff-karsilastirma": ["json-bicimlendirici", "json-csv-donusturucu", "metin-farki-diff"],
  "curl-kod-donusturucu": ["json-bicimlendirici", "url-kodlayici", "jwt-decoder"],
  "meta-etiket-favicon-uretici": ["url-kodlayici", "renk-donusturucu", "qr-kod-olusturucu"],
  "gorsel-format-donusturucu": ["gorsel-sikistirici", "gorselden-pdf", "exif-meta-veri-temizleyici"],
  "gorsel-sikistirici": ["gorsel-format-donusturucu", "exif-meta-veri-temizleyici", "gorselden-pdf"],
  "gorselden-pdf": ["gorsel-sikistirici", "pdf-birlestirme", "pdf-bolme"],
  "pdf-birlestirme": ["pdf-bolme", "gorselden-pdf", "sha256-ozet-uretici"],
  "pdf-bolme": ["pdf-birlestirme", "gorselden-pdf", "sha256-ozet-uretici"],
  "kvkk-veri-maskeleyici": ["arac-zinciri-pipeline", "exif-meta-veri-temizleyici", "json-csv-donusturucu"],
  "csv-inceleyici": ["arac-zinciri-pipeline", "json-csv-donusturucu", "json-bicimlendirici"],
  "yatirim-getiri-simulatoru": ["birim-donusturucu", "not-ortalamasi-hesaplayici", "gpa-cevirici"],
  "birim-donusturucu": ["yatirim-getiri-simulatoru", "gpa-cevirici", "not-ortalamasi-hesaplayici"],
  "not-ortalamasi-hesaplayici": ["gpa-cevirici", "birim-donusturucu", "yatirim-getiri-simulatoru"],
  "gpa-cevirici": ["not-ortalamasi-hesaplayici", "birim-donusturucu", "kaynakca-atif-formatlayici"],
  "kaynakca-atif-formatlayici": ["konusma-disa-aktarma-formatlayici", "markdown-onizleyici", "kelime-sayaci"],
  "fatura-sablonu-olusturucu": ["basit-sozlesme-sablonu", "birim-donusturucu", "sha256-ozet-uretici"],
  "basit-sozlesme-sablonu": ["fatura-sablonu-olusturucu", "metin-farki-diff", "sha256-ozet-uretici"],
  "asiri-kesinlik-dil-tarayicisi": ["sistem-promptu-netlik-kontrolu", "rol-persona-tutarlilik-kontrolu", "prompt-kalite-denetimi"],
  "konusma-disa-aktarma-formatlayici": ["token-baglam-butcesi-planlayici", "kvkk-veri-maskeleyici", "json-bicimlendirici"],
  "token-baglam-butcesi-planlayici": ["token-sayaci", "sistem-promptu-netlik-kontrolu", "konusma-disa-aktarma-formatlayici"],
  "sistem-promptu-netlik-kontrolu": ["rol-persona-tutarlilik-kontrolu", "asiri-kesinlik-dil-tarayicisi", "sistem-promptu-persona-sablonu"],
  "rol-persona-tutarlilik-kontrolu": ["sistem-promptu-netlik-kontrolu", "asiri-kesinlik-dil-tarayicisi", "prompt-kalite-denetimi"],
  "dosya-risk-on-taramasi": ["kod-guvenligi-on-taramasi", "url-guvenlik-on-kontrolu", "sha256-ozet-uretici"],
  "kod-guvenligi-on-taramasi": ["dosya-risk-on-taramasi", "url-guvenlik-on-kontrolu", "regex-test-araci"],
  "url-guvenlik-on-kontrolu": ["kod-guvenligi-on-taramasi", "dosya-risk-on-taramasi", "url-kodlayici"],
  "prompt-sablon-degisken-doldurucu": ["meta-prompt-olusturucu", "sistem-promptu-persona-sablonu", "prompt-kalite-denetimi"],
  "yerel-metin-ozetleyici": ["okunabilirlik-analizi", "kelime-sayaci", "metin-temizleyici"],
  "json-schema-olusturucu": ["json-bicimlendirici", "json-diff-karsilastirma", "json-csv-donusturucu"],
  "gorsel-boyutlandirici": ["gorsel-sikistirici", "gorsel-format-donusturucu", "exif-meta-veri-temizleyici"],
  "dosya-hash-karsilastirici": ["sha256-ozet-uretici", "dosya-risk-on-taramasi", "pdf-birlestirme"],
  "kredi-odeme-hesaplayici": ["yatirim-getiri-simulatoru", "birim-donusturucu", "tarih-farki-hesaplayici"],
  "tarih-farki-hesaplayici": ["kredi-odeme-hesaplayici", "birim-donusturucu", "not-ortalamasi-hesaplayici"],
  "ai-yanit-degerlendirme-rubrigi": ["sistem-promptu-netlik-kontrolu", "rol-persona-tutarlilik-kontrolu", "asiri-kesinlik-dil-tarayicisi"],
  "csp-olusturucu-denetleyici": ["kod-guvenligi-on-taramasi", "url-guvenlik-on-kontrolu", "dosya-risk-on-taramasi"],
};

export function getTool(slug: string) {
  return tools.find((tool) => tool.slug === slug);
}

export function getRelatedTools(tool: Tool, limit = 3) {
  const preferred = (relatedBySlug[tool.slug] ?? [])
    .map((slug) => getTool(slug))
    .filter((item): item is Tool => Boolean(item));
  const fallback = tools.filter((item) => item.category === tool.category && item.slug !== tool.slug && !preferred.some((candidate) => candidate.slug === item.slug));
  return [...preferred, ...fallback].slice(0, limit);
}
