import Link from "next/link";
import { absoluteUrl, languageTag, organizationId, pathFor, siteUrl, websiteId, type Locale } from "../lib/site";
import { AgentConversation } from "./AgentConversation";
import { SchemaScript } from "./SchemaScript";
import { SiteShell } from "./SiteShell";

const content = {
  tr: {
    eyebrow: "TARAYICIDA ÇALIŞAN GERÇEK YEREL AI",
    title: "Sohbet edin; gerektiğinde araçları sizin için işe koysun",
    intro: "Günlük bir soru sorun veya yapmak istediğiniz işi anlatın. Hızlı ajan anında plan kurar; isteğe bağlı gerçek yerel model daha doğal yanıtlar üretir. Her iki mod da araç girdilerinizi cihazınızda tutar.",
    start: "Sohbete başla", workspace: "Görsel akış kur",
    steps: [["1", "Anlat", "Hedefi ve varsa örnek veriyi kendi cümlelerinizle yazın."], ["2", "Planı görün", "Araçları, sırayı ve güvenlik notlarını kontrol edin."], ["3", "Devam edin", "Metin akışı otomatik tamamlansın veya doldurulmuş aracı açın."]],
    howTitle: "Ajan ne yapar, ne yapmaz?", howIntro: "Bu sayfa araçların yerine geçmez; doğru aracı bulmayı ve güvenli bir sıra kurmayı kolaylaştırır.",
    cards: [["01", "İhtiyacı anlar", "Hedef, dosya biçimi ve gizlilik sinyallerini eşleştirir."], ["02", "Kısa plan kurar", "Uygun araçları gerekçesiyle sıralar ve eksik bilgiyi sorar."], ["03", "Kontrolü sizde tutar", "Dosya seçimi, çalıştırma ve indirme yalnızca sizin eyleminizle olur."], ["04", "Sonraki adımı açıklar", "Hata mesajını sadeleştirir ve yakın alternatifleri gösterir."]],
    privacyTitle: "İçeriğiniz cihazınızdan çıkmaz",
    privacy: ["Hızlı ajan ve yerel model çıkarımı, hedef metnini veya araç girdisini ByteQuant sunucusuna göndermez.", "Kısa konuşma belleği yalnızca açık sekmenin sessionStorage alanında tutulur.", "Gerçek yerel AI isteğe bağlıdır; ilk etkinleştirmede açık kaynak model dosyaları indirilir, sohbet içeriği bu isteğe eklenmez.", "Model yanıtları hata yapabilir; hukuki, tıbbi, güvenlik veya kimlik doğrulama kararı değildir."],
    faq: [["Yerel Ajan gerçekten yapay zekâ mı?", "İki modu vardır. Hızlı mod açıklanabilir semantik planlama kullanır. WebGPU destekli cihazlarda isteğe bağlı Qwen3 modeli Web Worker içinde gerçek üretken çıkarım yapar; uzak AI API'si kullanılmaz."], ["Bir sohbeti hatırlar mı?", "Aynı sekmedeki son hedefleri ve yanıtları bağlam olarak kullanır; sekme kapandığında bu geçici bellek sona erer."], ["Araçları otomatik çalıştırır mı?", "Desteklenen ve sınırlandırılmış metin akışlarını cihazda tamamlayabilir, algılanan örnek girdiyi ilk araca aktarabilir ve planı İş İstasyonu'na gönderebilir. Dosya seçimi, parola, kod çalıştırma, indirme ve yüksek etkili kararlar sizin onayınızı gerektirir."], ["Model neden otomatik açılmıyor?", "İlk yükleme yüzlerce megabayt depolama ve WebGPU gerektirir. Site hızını korumak ve ağ kullanımını sizin kontrolünüzde tutmak için yalnızca açıkça etkinleştirdiğinizde indirilir; desteklenmeyen cihazlarda hızlı ajan çalışmaya devam eder."]],
  },
  en: {
    eyebrow: "REAL LOCAL AI IN YOUR BROWSER", title: "Chat naturally, then put the right tools to work", intro: "Ask an everyday question or describe a task. Fast Agent builds a plan instantly; the optional real local model produces more natural answers. Both modes keep tool input on your device.", start: "Start a conversation", workspace: "Build a visual flow",
    steps: [["1", "Describe", "Write the outcome and optional sample in your own words."], ["2", "Review", "Check the tools, order, and safety notes."], ["3", "Continue", "Finish a text flow or open the prepared first tool."]],
    howTitle: "What the Agent does—and does not do", howIntro: "It does not replace the tools. It makes the right tool and a safer order easier to find.",
    cards: [["01", "Understands the need", "Matches the outcome, file format, and privacy signals."], ["02", "Builds a short plan", "Orders suitable tools, explains why, and asks for missing details."], ["03", "Keeps you in control", "File selection, execution, and downloads happen only when you act."], ["04", "Explains the next move", "Turns common errors into plain language and offers nearby alternatives."]],
    privacyTitle: "Your content stays on your device", privacy: ["Fast planning and local-model inference do not send goals or tool inputs to a ByteQuant server.", "Short conversation memory stays in sessionStorage for the open tab only.", "Real local AI is opt-in: open-source model assets are downloaded once, and chat content is not added to that request.", "Model answers can be wrong and are not legal, medical, security, or identity-verification decisions."],
    faq: [["Is Local Agent real AI?", "It has two modes. Fast mode uses explainable semantic planning. On WebGPU devices, an optional Qwen3 model performs genuine generative inference inside a Web Worker, with no remote AI API."], ["Does it remember a conversation?", "It uses recent goals and answers as context in the same tab. Closing the tab ends this temporary memory."], ["Can it run tools automatically?", "It can complete supported bounded text workflows, prepare detected input in the first tool, and send a plan to Workstation. File selection, passwords, code execution, downloads, and high-impact decisions require your approval."], ["Why is the model not enabled automatically?", "The first load needs hundreds of megabytes of storage and WebGPU. To protect page speed and keep network use under your control, it downloads only after you opt in; Fast Agent remains available everywhere."]],
  },
  de: {
    eyebrow: "ECHTE LOKALE KI IM BROWSER", title: "Natürlich chatten und passende Werkzeuge einsetzen", intro: "Stellen Sie eine Alltagsfrage oder beschreiben Sie eine Aufgabe. Der schnelle Agent erstellt sofort einen Plan; das optionale lokale Modell formuliert natürlichere Antworten. Beide Modi halten Werkzeugeingaben auf Ihrem Gerät.", start: "Gespräch starten", workspace: "Visuellen Ablauf bauen",
    steps: [["1", "Beschreiben", "Ergebnis und optionales Beispiel formulieren."], ["2", "Prüfen", "Werkzeuge, Reihenfolge und Sicherheitshinweise ansehen."], ["3", "Fortfahren", "Textablauf abschließen oder vorbereitetes Werkzeug öffnen."]],
    howTitle: "Was der Agent kann – und was nicht", howIntro: "Er ersetzt die Werkzeuge nicht, sondern erleichtert die Auswahl und eine sichere Reihenfolge.",
    cards: [["01", "Versteht den Bedarf", "Ordnet Ziel, Dateiformat und Datenschutzsignale zu."], ["02", "Erstellt einen kurzen Plan", "Sortiert passende Werkzeuge, nennt Gründe und fragt fehlende Angaben ab."], ["03", "Lässt die Kontrolle bei Ihnen", "Dateiauswahl, Ausführung und Download erfolgen nur durch Ihre Aktion."], ["04", "Erklärt den nächsten Schritt", "Vereinfacht typische Fehler und zeigt nahe Alternativen."]],
    privacyTitle: "Ihre Inhalte bleiben auf dem Gerät", privacy: ["Schnelle Planung und lokale Modellinferenz senden Ziele oder Werkzeugeingaben nicht an ByteQuant-Server.", "Kurzes Gesprächsgedächtnis bleibt nur im sessionStorage des geöffneten Tabs.", "Die echte lokale KI ist optional: Modelldateien werden einmal geladen, Gesprächsinhalte nicht mitgesendet.", "Modellantworten können irren und sind keine Rechts-, Medizin-, Sicherheits- oder Identitätsprüfung."],
    faq: [["Ist der lokale Agent echte KI?", "Er bietet zwei Modi: nachvollziehbare semantische Schnellplanung und auf WebGPU-Geräten ein optionales Qwen3-Modell mit echter generativer Inferenz im Web Worker, ohne entfernte KI-API."], ["Merkt er sich ein Gespräch?", "Letzte Ziele und Antworten dienen im selben Tab als Kontext. Beim Schließen endet dieses Kurzzeitgedächtnis."], ["Kann er Werkzeuge automatisch ausführen?", "Begrenzte Textabläufe können lokal abgeschlossen, Eingaben vorbereitet und Pläne an die Workstation übergeben werden. Dateiauswahl, Passwörter, Codeausführung, Downloads und folgenreiche Entscheidungen benötigen Ihre Freigabe."], ["Warum startet das Modell nicht automatisch?", "Der erste Ladevorgang braucht mehrere hundert Megabyte und WebGPU. Für schnelle Seiten und kontrollierte Netznutzung wird es nur nach Ihrer Zustimmung geladen; der schnelle Agent bleibt verfügbar."]],
  },
  zh: {
    eyebrow: "浏览器中的真正本地 AI", title: "自然对话，并让合适的工具开始工作", intro: "您可以提出日常问题或描述任务。快速助手会立即规划；可选的真实本地模型会生成更自然的回答。两种模式都让工具输入留在设备上。", start: "开始对话", workspace: "创建可视化流程",
    steps: [["1", "描述", "用自己的话说明结果并可加入示例。"], ["2", "检查", "确认工具、顺序和安全提示。"], ["3", "继续", "完成文本流程或打开已准备的工具。"]],
    howTitle: "助手能做什么、不能做什么", howIntro: "它不会替代工具，而是帮助您找到合适工具和更安全的顺序。",
    cards: [["01", "理解需求", "匹配目标、文件格式与隐私信号。"], ["02", "生成短计划", "排列合适工具、解释原因并询问缺失信息。"], ["03", "由您控制", "文件选择、执行和下载都需要您的操作。"], ["04", "说明下一步", "用简单语言解释常见错误并提供相近替代方案。"]],
    privacyTitle: "内容留在您的设备上", privacy: ["快速规划与本地模型推理不会把目标或工具输入发送到 ByteQuant 服务器。", "短期对话记忆只保存在当前标签页的 sessionStorage 中。", "真实本地 AI 由您选择启用：首次下载开源模型文件，对话内容不会加入下载请求。", "模型回答可能出错，不能替代法律、医疗、安全或身份验证结论。"],
    faq: [["本地助手是真正的 AI 吗？", "它有两种模式：可解释的快速语义规划，以及在支持 WebGPU 的设备上通过 Web Worker 运行的可选 Qwen3 生成模型；不使用远程 AI API。"], ["它会记住对话吗？", "同一标签页中的近期目标与回答会作为上下文；关闭标签页后临时记忆结束。"], ["它能自动运行工具吗？", "它可以在设备端完成受限文本流程、把识别的输入交给首个工具，并把计划发送到工作站。文件选择、密码、代码执行、下载和高影响决定需要您的确认。"], ["为什么模型不会自动开启？", "首次加载需要数百 MB 存储空间和 WebGPU。为保护页面速度并让您控制网络使用，只有明确启用后才下载；快速助手始终可用。"]],
  },
} as const;

export function AgentPage({ locale }: { locale: Locale }) {
  const c = content[locale];
  const pageUrl = absoluteUrl(pathFor(locale, "agent"));
  const agentName = locale === "tr" ? "Yerel Ajan" : locale === "en" ? "Local Agent" : locale === "de" ? "Lokaler Agent" : "本地助手";
  const schemas = [
    { "@context": "https://schema.org", "@type": "WebApplication", "@id": `${pageUrl}#application`, name: `ByteQuant ${agentName}`, url: pageUrl, description: c.intro, applicationCategory: "ProductivityApplication", operatingSystem: "Any modern browser", browserRequirements: "JavaScript enabled; WebGPU is optional for the local generative model", inLanguage: languageTag(locale), isAccessibleForFree: true, creator: { "@id": organizationId }, isPartOf: { "@id": websiteId }, featureList: [...c.cards.map((item) => item[1]), c.faq[0][0]], offers: { "@type": "Offer", price: "0", priceCurrency: "USD" } },
    { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: locale === "tr" ? "Ana sayfa" : locale === "en" ? "Home" : locale === "de" ? "Startseite" : "首页", item: absoluteUrl(pathFor(locale, "home")) }, { "@type": "ListItem", position: 2, name: c.title, item: pageUrl }] },
    { "@context": "https://schema.org", "@type": "FAQPage", inLanguage: languageTag(locale), mainEntity: c.faq.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) },
  ];
  return <SiteShell locale={locale} alternateHref={pathFor(locale === "tr" ? "en" : "tr", "agent")} languageHrefs={{ tr: pathFor("tr", "agent"), en: pathFor("en", "agent"), de: pathFor("de", "agent"), zh: pathFor("zh", "agent") }}>
    <SchemaScript data={schemas} />
    <section className="agent-product-intro agent-product-intro-compact"><div className="container agent-product-intro-grid"><div><span className="eyebrow"><i />{c.eyebrow}</span><h1>{c.title}</h1><p>{c.intro}</p><div className="agent-intro-actions"><a className="primary-button" href="#local-agent">{c.start} <span aria-hidden="true">↓</span></a><Link className="secondary-button" href={pathFor(locale, "workstation")}>{c.workspace} <span aria-hidden="true">→</span></Link></div></div><aside className="agent-simple-promise"><span>01</span><strong>{c.steps[0][1]}</strong><i>→</i><span>02</span><strong>{c.steps[1][1]}</strong><i>→</i><span>03</span><strong>{c.steps[2][1]}</strong></aside></div></section>
    <section id="local-agent" className="section agent-console-section"><div className="container"><AgentConversation locale={locale} /></div></section>
    <section className="section agent-how"><div className="container"><div className="section-heading split-heading"><div><span className="kicker">LOCAL-FIRST</span><h2>{c.howTitle}</h2></div><p>{c.howIntro}</p></div><div className="agent-how-grid">{c.cards.map(([number, title, text]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="section agent-privacy"><div className="container agent-privacy-grid"><div><span className="kicker">PRIVACY BY DESIGN</span><h2>{c.privacyTitle}</h2><p>{siteUrl.replace("https://", "")} · HTTPS · {agentName}</p></div><ul>{c.privacy.map((item) => <li key={item}><span>✓</span><p>{item}</p></li>)}</ul></div></section>
    <section className="section compact-faq"><div className="container"><div className="section-heading centered"><span className="kicker">FAQ</span><h2>{locale === "tr" ? "Kısa ve açık yanıtlar" : locale === "de" ? "Kurze, klare Antworten" : locale === "zh" ? "简明解答" : "Short, clear answers"}</h2></div><div className="faq-list narrow">{c.faq.map(([question, answer]) => <details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></div></section>
  </SiteShell>;
}
