import Link from "next/link";
import { posts, type EditorialLocale } from "../lib/posts";
import { absoluteUrl, languageTag, organizationId, pathFor, postPath, websiteId } from "../lib/site";
import { AdSlot } from "./AdSlot";
import { SchemaScript } from "./SchemaScript";
import { SiteShell } from "./SiteShell";

export function BlogIndex({ locale }: { locale: EditorialLocale }) {
  const isTr = locale === "tr";
  const currentLanguage = languageTag(locale);
  const alternateHref = locale === "tr" ? "/en/blog" : "/blog";
  const orderedPosts = posts.map((post, index) => ({ post, index })).sort((left, right) => right.post.date.localeCompare(left.post.date) || right.index - left.index).map(({ post }) => post);
  const featured = orderedPosts[0]!;
  const remaining = orderedPosts.slice(1);
  const categories = [...new Set(orderedPosts.map((post) => post.category[locale]))];
  const formatDate = (date: string) => new Intl.DateTimeFormat(currentLanguage, { day: "numeric", month: "short", year: "numeric", timeZone: "UTC" }).format(new Date(`${date}T00:00:00.000Z`));
  const blogUrl = absoluteUrl(pathFor(locale, "blog"));
  const schema = [
    { "@context": "https://schema.org", "@type": "Blog", "@id": `${blogUrl}#blog`, name: isTr ? "ByteQuant Rehberleri" : "ByteQuant Guides", url: blogUrl, inLanguage: currentLanguage, description: isTr ? "Gizlilik, tarayıcı içi araçlar, uluslararası SEO ve veri güvenliği için kaynaklı uygulama rehberleri." : "Sourced, practical guides to privacy, in-browser tools, international SEO, and data security.", publisher: { "@id": organizationId }, isPartOf: { "@id": websiteId }, blogPost: orderedPosts.map((post) => ({ "@id": `${absoluteUrl(postPath(locale, post.slug))}#article` })) },
    { "@context": "https://schema.org", "@type": "ItemList", "@id": `${blogUrl}#guide-list`, name: isTr ? "ByteQuant rehberleri" : "ByteQuant guides", numberOfItems: orderedPosts.length, itemListElement: orderedPosts.map((post, index) => ({ "@type": "ListItem", position: index + 1, url: absoluteUrl(postPath(locale, post.slug)), name: post.title[locale] })) },
    { "@context": "https://schema.org", "@type": "BreadcrumbList", "@id": `${blogUrl}#breadcrumb`, itemListElement: [{ "@type": "ListItem", position: 1, name: isTr ? "Ana sayfa" : "Home", item: absoluteUrl(pathFor(locale, "home")) }, { "@type": "ListItem", position: 2, name: isTr ? "Rehberler" : "Guides", item: blogUrl }] },
  ];
  return (
    <SiteShell locale={locale} alternateHref={alternateHref}>
      <SchemaScript data={schema} />
      <section className="page-hero editorial-hero"><div className="container"><nav className="breadcrumbs"><Link href={pathFor(locale, "home")}>{isTr ? "Ana sayfa" : "Home"}</Link><span>/</span><span>{isTr ? "Rehberler" : "Guides"}</span></nav><span className="eyebrow"><i />{isTr ? "Birincil kaynak · gerçek iş akışı · görünür sınırlar" : "Primary sources · real workflows · visible limitations"}</span><h1>{isTr ? "Arama, gizlilik ve tarayıcı içi işler için kanıta dayalı rehberler" : "Evidence-led guides to search, privacy, and in-browser work"}</h1><p>{isTr ? "Kısa cevapla başlayıp yöntemi, sınırı ve doğrulama adımlarını gösteriyoruz. Teknik SEO’dan PDF iş akışına kadar her rehber gerçek bir kullanıcı görevini tamamlamaya odaklanır." : "We start with the useful answer, then show method, limitation, and verification. Every guide—from technical SEO to PDF workflows—focuses on completing a real task."}</p><div className="blog-proof"><span><strong>{orderedPosts.length}</strong>{isTr ? " ayrıntılı rehber" : " in-depth guides"}</span><span><strong>{categories.length}</strong>{isTr ? " konu alanı" : " topic areas"}</span><span><strong>TR · EN</strong>{isTr ? " tam içerik" : " full content"}</span></div></div></section>
      <section className="blog-topic-strip"><div className="container"><strong>{isTr ? "İçerik kümeleri" : "Topic clusters"}</strong><div>{categories.slice(0, 8).map((category) => <span key={category}>{category}<small>{orderedPosts.filter((post) => post.category[locale] === category).length}</small></span>)}</div><a href={isTr ? "/feed.xml" : "/en/feed.xml"}>RSS ↗</a></div></section>
      <section id="guides" className="section blog-list-section"><div className="container"><article className="featured-post"><div className="featured-copy"><span>{isTr ? "YENİ REHBER" : "LATEST GUIDE"} · {featured.category[locale]} · {featured.readTime[locale]}</span><time dateTime={featured.date}>{formatDate(featured.date)}</time><h2><Link href={postPath(locale, featured.slug)}>{featured.title[locale]}</Link></h2><p>{featured.excerpt[locale]}</p><Link className="primary-button" href={postPath(locale, featured.slug)}>{isTr ? "Rehberi okumaya başlayın" : "Start reading"} →</Link></div><div className="featured-visual" aria-hidden="true"><div className="diagram-device"><span>{isTr ? "Araştır" : "Research"}</span><strong>VERIFY</strong><small>{isTr ? "Uygula · Ölç · Güncelle" : "Apply · Measure · Update"}</small></div><div className="blocked-path"><b>✓</b><span>{isTr ? "Kaynaklı yöntem" : "Sourced method"}</span></div></div></article><div className="post-list-grid">{remaining.map((post, index) => <article className="guide-card" key={post.slug}><div className={`guide-number guide-color-${index % 4}`}>{String(index + 2).padStart(2, "0")}</div><div><span>{post.category[locale]} · {post.readTime[locale]} · <time dateTime={post.date}>{formatDate(post.date)}</time></span><h2><Link href={postPath(locale, post.slug)}>{post.title[locale]}</Link></h2><p>{post.excerpt[locale]}</p><Link className="text-link" href={postPath(locale, post.slug)}>{isTr ? "Rehberi oku" : "Read guide"} →</Link></div></article>)}</div></div></section>
      <div className="container"><AdSlot locale={locale} /></div>
      <section className="section editorial-policy"><div className="container"><div><span className="kicker">{isTr ? "EDİTORYAL YAKLAŞIM" : "EDITORIAL APPROACH"}</span><h2>{isTr ? "İddia değil yöntem gösteriyoruz" : "We show the method, not just the claim"}</h2></div><div className="editorial-points"><p><strong>01</strong>{isTr ? "Teknik kavramları gündelik dille açıklarız; önemli ayrımları gizlemeyiz." : "We explain technical ideas in plain language without hiding important distinctions."}</p><p><strong>02</strong>{isTr ? "Hukuki ve güvenlik konularında otomatik uygunluk garantisi vermeyiz." : "We do not promise automatic legal or security compliance."}</p><p><strong>03</strong>{isTr ? "İçerikleri ürün davranışı değiştiğinde gözden geçirir, düzeltme taleplerini açık tutarız." : "We review content when product behavior changes and welcome correction requests."}</p></div></div></section>
    </SiteShell>
  );
}
