"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { reviewCommunityText } from "../lib/community-safety";
import type { Locale } from "../lib/site";
import { communityPublishEvent } from "./CommunityComposer";

type Kind = "workflow" | "tip" | "idea" | "question";
type Visibility = "public" | "private";
type Audience = Visibility | "group";
type CommunityProfile = { name: string; handle: string; color: string; bio: string; visibility: Visibility };
type CommunityGroup = { id: string; name: string; description: string; visibility: Visibility; createdAt: number };
type FeedPost = { id: string; kind: Kind; title: string; body: string; recipe: string; local: boolean; createdAt: number; author: CommunityProfile; audience: Audience; groupId: string };
type FeedComment = { id: string; body: string; createdAt: number };
type FeedState = { posts: FeedPost[]; liked: string[]; saved: string[]; comments: Record<string, FeedComment[]>; groups: CommunityGroup[] };
type ComposerDraft = { version: 1; kind: Kind; title: string; body: string; recipe: string; audience?: Audience; group?: string };
type SharedPost = { version: 3; kind: Kind; title: string; body: string; recipe: string; author: CommunityProfile };
type CommunityPack = { version: 2; exportedAt: string; profile: CommunityProfile; posts: FeedPost[]; groups: CommunityGroup[] };
type FeedFilter = "all" | "mine" | "groups" | "private" | "saved" | Kind;

const storageKey = "bytequant:community-feed:v4";
const profileKey = "bytequant:community-profile:v2";
const communityChannel = "bytequant:community-device:v1";
const kindOrder: Kind[] = ["workflow", "tip", "idea", "question"];
const defaultProfiles: Record<Locale, CommunityProfile> = {
  tr: { name: "Yerel üretici", handle: "cihazim", color: "#3157ff", bio: "Yerel araçlarla güvenli iş akışları kuruyorum.", visibility: "public" },
  en: { name: "Local maker", handle: "my-device", color: "#3157ff", bio: "Building safer workflows with local tools.", visibility: "public" },
  de: { name: "Lokaler Maker", handle: "mein-geraet", color: "#3157ff", bio: "Sichere Abläufe mit lokalen Werkzeugen.", visibility: "public" },
  zh: { name: "本地创作者", handle: "my-device", color: "#3157ff", bio: "使用本地工具构建更安全的工作流。", visibility: "public" },
};

const copy = {
  tr: { eyebrow: "YEREL-FIRST SOSYAL ALAN", title: "Profilinizi, gruplarınızı ve güvenli paylaşım panonuzu yönetin", intro: "Gönderiler, beğeniler, yorumlar ve gruplar bu cihazdaki gerçek etkinliklerdir. Herkese açık içerikleri bağlantı veya doğrulanmış paketle taşıyabilir; özel içeriği cihazda tutabilirsiniz.", all: "Keşfet", mine: "Paylaşımlarım", groups: "Gruplarım", private: "Özel", savedTab: "Kaydedilenler", search: "Gönderi, kişi veya grupta ara", empty: "Bu görünüm henüz boş. Üstteki güvenli paylaşım editörüyle ilk gönderiyi ekleyin.", likes: "Faydalı", liked: "Faydalı buldunuz", save: "Kaydet", saved: "Kaydedildi", comment: "Yorum", share: "Paylaş", locked: "Özel", comments: "Cihazdaki yorumlar", placeholder: "Yapıcı bir yorum yazın; kişisel veri veya sır eklemeyin.", add: "Yorumu ekle", blocked: "İçerik eklenemedi: kişisel veri, sır, spam, dış bağlantı veya uygunsuz dil olabilir.", short: "Yorum en az 3 karakter olmalı.", shared: "İçeriği taşıyan bağlantı kopyalandı.", imported: "Paylaşılan gönderi bu sekmedeki panoya eklendi.", local: "Bu cihaz", curated: "ByteQuant editoryal başlangıç", received: "Bağlantıyla geldi", kinds: { workflow: "İş akışı", tip: "İpucu", idea: "Fikir", question: "Soru" }, profile: "Yerel profil", profileHelp: "Herkese açık profil adı yalnızca sizin paylaştığınız içerikle taşınır. Gizli profil, dışa aktarılan herkese açık gönderilerde anonimleştirilir.", displayName: "Görünen ad", handle: "Kullanıcı adı", bio: "Kısa tanıtım", profileVisibility: "Profil görünürlüğü", publicProfile: "Herkese açık", privateProfile: "Gizli profil", portable: "Taşınabilir sosyal pano", export: "Açık paketi indir", import: "Paket yükle", packError: "Paket doğrulanamadı veya yerel güvenlik filtresinden geçmedi.", groupStudio: "Özel gruplar", groupHelp: "Grup üyeliği bu cihazdaki panoyu düzenler. Paylaşmak için güvenli paket veya doğrudan P2P oturumu kullanın.", groupName: "Yeni grup adı", groupDescription: "Amaç veya konu", groupVisibility: "Grup görünürlüğü", createGroup: "Grup oluştur", noGroup: "Henüz grup yok", public: "Açık", privateGroup: "Özel", boundary: "Kalıcı küresel keşif, hesap eşitleme ve çevrimdışı mesajlar ortak sunucu veya relay gerektirir. ByteQuant bu özellikleri ve sayaçları taklit etmez; içerik taşıyan bağlantı, doğrulanan paket ve doğrudan P2P sunar.", audience: { public: "Herkese açık", private: "Yalnızca cihaz", group: "Grup" } },
  en: { eyebrow: "LOCAL-FIRST SOCIAL SPACE", title: "Manage your profile, groups, and safe sharing board", intro: "Posts, reactions, comments, and groups are real activity on this device. Move public content with a content link or validated pack while keeping private content on-device.", all: "Explore", mine: "My posts", groups: "My groups", private: "Private", savedTab: "Saved", search: "Search posts, people, or groups", empty: "This view is empty. Use the safe composer above to add the first post.", likes: "Useful", liked: "Marked useful", save: "Save", saved: "Saved", comment: "Comment", share: "Share", locked: "Private", comments: "Comments on this device", placeholder: "Write a constructive comment; do not include personal data or secrets.", add: "Add comment", blocked: "Content was blocked: it may contain personal data, a secret, spam, an external link, or abusive language.", short: "A comment needs at least 3 characters.", shared: "A content-carrying link was copied.", imported: "The shared post was added to this tab's board.", local: "This device", curated: "ByteQuant editorial starter", received: "Received by link", kinds: { workflow: "Workflow", tip: "Tip", idea: "Idea", question: "Question" }, profile: "Local profile", profileHelp: "A public alias travels only with content you share. A private profile is anonymized in exported public posts.", displayName: "Display name", handle: "Handle", bio: "Short bio", profileVisibility: "Profile visibility", publicProfile: "Public profile", privateProfile: "Private profile", portable: "Portable social board", export: "Download public pack", import: "Import pack", packError: "The pack could not be validated or did not pass the local safety filter.", groupStudio: "Private groups", groupHelp: "Group membership organizes this device's board. Use a safe pack or direct P2P session to share it.", groupName: "New group name", groupDescription: "Purpose or topic", groupVisibility: "Group visibility", createGroup: "Create group", noGroup: "No groups yet", public: "Public", privateGroup: "Private", boundary: "Persistent global discovery, account sync, and offline messaging require shared server or relay infrastructure. ByteQuant does not fake those features or counts; it offers content links, validated packs, and direct P2P.", audience: { public: "Public", private: "On-device only", group: "Group" } },
  de: { eyebrow: "LOCAL-FIRST COMMUNITY", title: "Profil, Gruppen und sicheres Teilungsboard verwalten", intro: "Beiträge, Reaktionen, Kommentare und Gruppen sind echte Aktivitäten auf diesem Gerät. Öffentliche Inhalte lassen sich per Inhaltslink oder geprüftem Paket übertragen; private Inhalte bleiben lokal.", all: "Entdecken", mine: "Meine Beiträge", groups: "Meine Gruppen", private: "Privat", savedTab: "Gespeichert", search: "Beiträge, Personen oder Gruppen suchen", empty: "Diese Ansicht ist leer. Mit dem sicheren Editor oben können Sie beginnen.", likes: "Hilfreich", liked: "Als hilfreich markiert", save: "Speichern", saved: "Gespeichert", comment: "Kommentar", share: "Teilen", locked: "Privat", comments: "Kommentare auf diesem Gerät", placeholder: "Konstruktiv kommentieren; keine Personendaten oder Geheimnisse.", add: "Kommentar hinzufügen", blocked: "Inhalt blockiert: mögliche Personendaten, Geheimnisse, Spam, externer Link oder Missbrauch.", short: "Ein Kommentar benötigt mindestens 3 Zeichen.", shared: "Ein Inhaltslink wurde kopiert.", imported: "Der geteilte Beitrag wurde dem Board dieses Tabs hinzugefügt.", local: "Dieses Gerät", curated: "ByteQuant-Redaktionsstart", received: "Per Link erhalten", kinds: { workflow: "Ablauf", tip: "Tipp", idea: "Idee", question: "Frage" }, profile: "Lokales Profil", profileHelp: "Ein öffentliches Kürzel reist nur mit geteilten Inhalten. Private Profile werden in öffentlichen Exporten anonymisiert.", displayName: "Anzeigename", handle: "Kürzel", bio: "Kurzprofil", profileVisibility: "Profilsichtbarkeit", publicProfile: "Öffentlich", privateProfile: "Privates Profil", portable: "Portables Community-Board", export: "Öffentliches Paket laden", import: "Paket importieren", packError: "Paket ungültig oder vom lokalen Filter abgelehnt.", groupStudio: "Private Gruppen", groupHelp: "Gruppen ordnen das Board dieses Geräts. Zum Teilen ein sicheres Paket oder direkte P2P-Sitzung verwenden.", groupName: "Neuer Gruppenname", groupDescription: "Zweck oder Thema", groupVisibility: "Gruppensichtbarkeit", createGroup: "Gruppe erstellen", noGroup: "Noch keine Gruppe", public: "Öffentlich", privateGroup: "Privat", boundary: "Dauerhafte globale Suche, Kontosynchronisierung und Offline-Nachrichten benötigen gemeinsame Server oder Relays. ByteQuant täuscht dies nicht vor, sondern bietet Inhaltslinks, geprüfte Pakete und direktes P2P.", audience: { public: "Öffentlich", private: "Nur Gerät", group: "Gruppe" } },
  zh: { eyebrow: "本地优先社交空间", title: "管理个人资料、群组和安全分享看板", intro: "帖子、互动、评论和群组都是真实的设备内活动。公开内容可通过内容链接或验证包迁移，私密内容则留在设备上。", all: "发现", mine: "我的帖子", groups: "我的群组", private: "私密", savedTab: "已收藏", search: "搜索帖子、用户或群组", empty: "当前视图为空。请使用上方安全编辑器发布第一条内容。", likes: "有用", liked: "已标记有用", save: "收藏", saved: "已收藏", comment: "评论", share: "分享", locked: "私密", comments: "本设备评论", placeholder: "写下建设性评论；不要包含个人数据或密钥。", add: "添加评论", blocked: "内容被阻止：可能包含个人数据、密钥、垃圾信息、外部链接或不当语言。", short: "评论至少需要 3 个字符。", shared: "已复制内容分享链接。", imported: "分享的帖子已加入当前标签页。", local: "本设备", curated: "ByteQuant 编辑起始内容", received: "通过链接收到", kinds: { workflow: "工作流", tip: "技巧", idea: "建议", question: "问题" }, profile: "本地资料", profileHelp: "公开别名只会随您分享的内容传递。私密资料在公开导出中会匿名化。", displayName: "显示名称", handle: "用户名", bio: "个人简介", profileVisibility: "资料可见性", publicProfile: "公开资料", privateProfile: "私密资料", portable: "可迁移社交看板", export: "下载公开社区包", import: "导入社区包", packError: "社区包无效或未通过本地安全过滤。", groupStudio: "私密群组", groupHelp: "群组成员关系仅整理本设备看板。分享时请使用安全社区包或直接 P2P 会话。", groupName: "新群组名称", groupDescription: "目的或主题", groupVisibility: "群组可见性", createGroup: "创建群组", noGroup: "尚无群组", public: "公开", privateGroup: "私密", boundary: "持久的全球发现、账号同步与离线消息需要共享服务器或中继。ByteQuant 不会伪造这些功能或数据，而是提供内容链接、验证包和直接 P2P。", audience: { public: "公开", private: "仅设备", group: "群组" } },
} as const;

const importedToDevice = {
  tr: "Paylaşılan gönderi bu cihazdaki panoya eklendi.",
  en: "The shared post was added to this device's board.",
  de: "Der geteilte Beitrag wurde dem Board dieses Geräts hinzugefügt.",
  zh: "分享的帖子已加入此设备的看板。",
} as const;

const starterContent: Record<Locale, Array<[string, Kind, string, string]>> = {
  tr: [["starter-privacy", "workflow", "Gerçek kayıt kullanmadan KVKK akışını prova edin", "Yapay CSV yükleyin, hassas sütunları maskeleyin ve JSON çıktısını yapısal doğrulayın. İlk denemede gerçek müşteri verisi kullanmayın."], ["starter-json", "tip", "JSON tesliminden önce üç kısa kontrol", "Sözdizimini biçimlendirin, beklenen alanları şemayla doğrulayın ve önceki sürümle yapısal fark alın."], ["starter-agent", "question", "Ajan mı İş İstasyonu mu?", "Sonucu biliyor ancak sıra konusunda emin değilseniz Ajanla başlayın. Tekrarlanabilir görsel akış için planı İş İstasyonuna aktarın."]],
  en: [["starter-privacy", "workflow", "Rehearse a privacy workflow without real records", "Load synthetic CSV, mask sensitive columns, and structurally validate the JSON output. Do not use customer records for the first run."], ["starter-json", "tip", "Three checks before delivering JSON", "Format syntax, validate expected fields against a schema, and run a structural diff against the previous version."], ["starter-agent", "question", "Agent or Workstation?", "Start with Agent when the outcome is clear but the order is not. Send the plan to Workstation for a repeatable visual flow."]],
  de: [["starter-privacy", "workflow", "Datenschutz-Ablauf ohne echte Daten proben", "Synthetische CSV laden, sensible Spalten maskieren und JSON strukturell prüfen. Beim ersten Lauf keine Kundendaten verwenden."], ["starter-json", "tip", "Drei Prüfungen vor der JSON-Übergabe", "Syntax formatieren, erwartete Felder per Schema prüfen und einen strukturellen Diff zur Vorversion ausführen."], ["starter-agent", "question", "Agent oder Workstation?", "Mit dem Agenten starten, wenn das Ziel klar, die Reihenfolge aber offen ist. Für wiederholbare Abläufe an die Workstation senden."]],
  zh: [["starter-privacy", "workflow", "不使用真实记录演练隐私流程", "加载合成 CSV、遮蔽敏感列并验证 JSON 结构。第一次运行不要使用真实客户数据。"], ["starter-json", "tip", "交付 JSON 前的三项检查", "格式化语法、用 Schema 验证字段，并与旧版本做结构差异比较。"], ["starter-agent", "question", "助手还是工作站？", "目标明确但顺序不清时先用助手；需要可复用的可视化流程时发送到工作站。"]],
};

function clean(value: string, max: number) { return value.replace(/[\u0000-\u001F\u007F]/g, "").replace(/<[^>]*>/g, "").trim().slice(0, max); }
function makeId() { return globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random().toString(36).slice(2)}`; }
function safeRecipe(value: string) { return !value || /^https:\/\/(?:www\.)?bytequant\.org\/workspace\/?\?recipe=[A-Za-z0-9_%.-]+$/i.test(value); }
function groupId(name: string) { return `group-${name.toLocaleLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 36) || "local"}`; }
function validProfile(value: unknown): value is CommunityProfile { const item = value as Partial<CommunityProfile>; return Boolean(item && typeof item.name === "string" && item.name.length <= 40 && typeof item.handle === "string" && /^[a-z0-9-]{2,24}$/i.test(item.handle) && typeof item.color === "string" && /^#[0-9a-f]{6}$/i.test(item.color) && typeof item.bio === "string" && item.bio.length <= 160 && ["public", "private"].includes(item.visibility ?? "")); }
function validGroup(value: unknown): value is CommunityGroup { const item = value as Partial<CommunityGroup>; return Boolean(item && typeof item.id === "string" && item.id.length <= 80 && typeof item.name === "string" && item.name.length >= 3 && item.name.length <= 50 && typeof item.description === "string" && item.description.length <= 180 && ["public", "private"].includes(item.visibility ?? "") && Number.isFinite(item.createdAt)); }
function validDraft(value: unknown): value is ComposerDraft { const item = value as Partial<ComposerDraft>; return Boolean(item && item.version === 1 && kindOrder.includes(item.kind as Kind) && typeof item.title === "string" && typeof item.body === "string" && typeof item.recipe === "string" && (!item.audience || ["public", "private", "group"].includes(item.audience))); }
function validPost(value: unknown): value is FeedPost { const item = value as Partial<FeedPost>; return Boolean(item && typeof item.id === "string" && item.id.length <= 120 && kindOrder.includes(item.kind as Kind) && typeof item.title === "string" && item.title.length <= 120 && typeof item.body === "string" && item.body.length <= 5000 && typeof item.recipe === "string" && safeRecipe(item.recipe) && typeof item.local === "boolean" && Number.isFinite(item.createdAt) && validProfile(item.author) && ["public", "private", "group"].includes(item.audience ?? "") && typeof item.groupId === "string"); }
function validComment(value: unknown): value is FeedComment { const item = value as Partial<FeedComment>; return Boolean(item && typeof item.id === "string" && item.id.length <= 120 && typeof item.body === "string" && item.body.length <= 800 && Number.isFinite(item.createdAt)); }
function publicAuthor(profile: CommunityProfile): CommunityProfile { return profile.visibility === "public" ? profile : { name: "Private member", handle: "private", color: "#64748b", bio: "", visibility: "private" }; }
function encodeShared(value: SharedPost) { const bytes = new TextEncoder().encode(JSON.stringify(value)); let binary = ""; bytes.forEach((byte) => { binary += String.fromCharCode(byte); }); return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/g, ""); }
function decodeShared(value: string): SharedPost | null { try { const binary = atob(value.replace(/-/g, "+").replace(/_/g, "/").padEnd(Math.ceil(value.length / 4) * 4, "=")); const parsed = JSON.parse(new TextDecoder().decode(Uint8Array.from(binary, (char) => char.charCodeAt(0)))) as Partial<SharedPost>; if (parsed.version !== 3 || !kindOrder.includes(parsed.kind as Kind) || typeof parsed.title !== "string" || typeof parsed.body !== "string" || typeof parsed.recipe !== "string" || !safeRecipe(parsed.recipe) || !validProfile(parsed.author)) return null; return { version: 3, kind: parsed.kind as Kind, title: clean(parsed.title, 120), body: clean(parsed.body, 1600), recipe: clean(parsed.recipe, 4000), author: parsed.author }; } catch { return null; } }

function curated(locale: Locale): FeedPost[] {
  const author: CommunityProfile = { name: locale === "tr" ? "ByteQuant Rehberleri" : locale === "de" ? "ByteQuant Ratgeber" : locale === "zh" ? "ByteQuant 指南" : "ByteQuant Guides", handle: "bytequant", color: "#008f8a", bio: "ByteQuant editorial", visibility: "public" };
  return starterContent[locale].map(([id, kind, title, body]) => ({ id, kind, title, body, recipe: "", local: false, createdAt: 0, author, audience: "public", groupId: "" }));
}

export function CommunityFeed({ locale }: { locale: Locale }) {
  const t = copy[locale];
  const [state, setState] = useState<FeedState>({ posts: [], liked: [], saved: [], comments: {}, groups: [] });
  const [profile, setProfile] = useState<CommunityProfile>(defaultProfiles[locale]);
  const [filter, setFilter] = useState<FeedFilter>("all");
  const [query, setQuery] = useState(""); const [comment, setComment] = useState(""); const [activeComment, setActiveComment] = useState<string | null>(null); const [status, setStatus] = useState(""); const [hydrated, setHydrated] = useState(false);
  const [newGroup, setNewGroup] = useState({ name: "", description: "", visibility: "private" as Visibility });
  const importRef = useRef<HTMLInputElement | null>(null);
  const channelRef = useRef<BroadcastChannel | null>(null);
  const skipBroadcastRef = useRef(false);

  useEffect(() => {
    const frame = requestAnimationFrame(() => {
      try {
        const storedProfile: unknown = JSON.parse(localStorage.getItem(profileKey) ?? "null"); if (validProfile(storedProfile)) setProfile(storedProfile);
        const parsed = JSON.parse(localStorage.getItem(storageKey) ?? "null") as Partial<FeedState> | null;
        if (parsed && Array.isArray(parsed.posts) && Array.isArray(parsed.liked) && parsed.comments && typeof parsed.comments === "object") {
          const comments = Object.fromEntries(Object.entries(parsed.comments).filter(([key, value]) => key.length <= 120 && Array.isArray(value)).map(([key, value]) => [key, value.filter(validComment).slice(-30)]));
          setState({ posts: parsed.posts.filter(validPost).slice(-80), liked: parsed.liked.filter((item): item is string => typeof item === "string").slice(-160), saved: Array.isArray(parsed.saved) ? parsed.saved.filter((item): item is string => typeof item === "string").slice(-160) : [], comments, groups: Array.isArray(parsed.groups) ? parsed.groups.filter(validGroup).slice(-20) : [] });
        }
        const shared = new URL(window.location.href).searchParams.get("community");
        if (shared && shared.length < 8_000) { const draft = decodeShared(shared); if (draft && reviewCommunityText(`${draft.title}\n${draft.body}`).length === 0) setState((current) => ({ ...current, posts: [...current.posts.filter((post) => post.id !== `shared-${shared.slice(0, 20)}`), { id: `shared-${shared.slice(0, 20)}`, kind: draft.kind, title: draft.title, body: draft.body, recipe: draft.recipe, local: false, createdAt: Date.now(), author: draft.author, audience: "public" as const, groupId: "" }].slice(-80) })); }
      } catch { /* Optional tab state can be unavailable. */ }
      setHydrated(true);
    }); return () => cancelAnimationFrame(frame);
  }, []);

  useEffect(() => {
    if (!hydrated || !("BroadcastChannel" in window)) return;
    const channel = new BroadcastChannel(communityChannel);
    channelRef.current = channel;
    channel.onmessage = (event: MessageEvent<unknown>) => {
      if (!event.data || typeof event.data !== "object") return;
      const message = event.data as { state?: Partial<FeedState>; profile?: unknown };
      if (!message.state || !Array.isArray(message.state.posts) || !Array.isArray(message.state.liked) || !Array.isArray(message.state.saved) || !message.state.comments || !Array.isArray(message.state.groups)) return;
      const next: FeedState = { posts: message.state.posts.filter(validPost).slice(-80), liked: message.state.liked.filter((item): item is string => typeof item === "string").slice(-160), saved: message.state.saved.filter((item): item is string => typeof item === "string").slice(-160), comments: Object.fromEntries(Object.entries(message.state.comments).filter(([, value]) => Array.isArray(value)).map(([key, value]) => [key, value.filter(validComment).slice(-30)])), groups: message.state.groups.filter(validGroup).slice(-20) };
      skipBroadcastRef.current = true;
      setState(next);
      if (validProfile(message.profile)) setProfile(message.profile);
      setStatus(locale === "tr" ? "Bu cihazdaki başka bir ByteQuant sekmesiyle eşitlendi." : locale === "de" ? "Mit einem anderen ByteQuant-Tab auf diesem Gerät synchronisiert." : locale === "zh" ? "已与此设备上的另一个 ByteQuant 标签页同步。" : "Synced with another ByteQuant tab on this device.");
    };
    return () => { channel.close(); channelRef.current = null; };
  }, [hydrated, locale]);

  useEffect(() => {
    const receive = (event: Event) => {
      const draft = (event as CustomEvent<unknown>).detail; if (!validDraft(draft) || reviewCommunityText(`${draft.title}\n${draft.body}`).length) { setStatus(t.blocked); return; }
      const audience = draft.audience ?? "public"; const recipe = clean(draft.recipe, 4000); if (!safeRecipe(recipe)) return;
      const name = clean(draft.group ?? "", 50); const id = audience === "group" ? groupId(name) : "";
      const post: FeedPost = { id: makeId(), kind: draft.kind, title: clean(draft.title, 120), body: clean(draft.body, 5000), recipe, local: true, createdAt: Date.now(), author: profile, audience, groupId: id };
      setState((current) => ({ ...current, posts: [...current.posts, post].slice(-80), groups: audience === "group" && name && !current.groups.some((group) => group.id === id) ? [...current.groups, { id, name, description: "", visibility: "private" as const, createdAt: Date.now() }].slice(-20) : current.groups })); setFilter(audience === "group" ? "groups" : audience === "private" ? "private" : "mine"); setStatus("");
    };
    window.addEventListener(communityPublishEvent, receive); return () => window.removeEventListener(communityPublishEvent, receive);
  }, [profile, t.blocked]);
  useEffect(() => { if (hydrated) try { localStorage.setItem(storageKey, JSON.stringify(state)); localStorage.setItem(profileKey, JSON.stringify(profile)); if (skipBroadcastRef.current) skipBroadcastRef.current = false; else channelRef.current?.postMessage({ state, profile }); } catch { /* Continue without persistence. */ } }, [hydrated, profile, state]);

  const posts = useMemo(() => [...curated(locale), ...state.posts].filter((post) => filter === "all" ? post.audience === "public" : filter === "mine" ? post.local : filter === "groups" ? post.audience === "group" : filter === "private" ? post.audience === "private" : filter === "saved" ? state.saved.includes(post.id) : post.kind === filter).filter((post) => `${post.title} ${post.body} ${post.author.name} ${state.groups.find((group) => group.id === post.groupId)?.name ?? ""}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())), [filter, locale, query, state.posts, state.groups, state.saved]);
  const normalizedProfile = (): CommunityProfile => ({ name: clean(profile.name, 40) || "ByteQuant", handle: /^[a-z0-9-]{2,24}$/i.test(profile.handle) ? profile.handle : "local", color: /^#[0-9a-f]{6}$/i.test(profile.color) ? profile.color : "#3157ff", bio: clean(profile.bio, 160), visibility: profile.visibility });
  function toggleList(field: "liked" | "saved", id: string) { setState((current) => ({ ...current, [field]: current[field].includes(id) ? current[field].filter((value) => value !== id) : [...current[field], id].slice(-160) })); }
  function addComment(id: string) { const body = clean(comment, 800); if (body.length < 3) { setStatus(t.short); return; } if (reviewCommunityText(body).length) { setStatus(t.blocked); return; } setState((current) => ({ ...current, comments: { ...current.comments, [id]: [...(current.comments[id] ?? []), { id: makeId(), body, createdAt: Date.now() }].slice(-30) } })); setComment(""); setStatus(""); }
  function createGroup() { const name = clean(newGroup.name, 50); if (name.length < 3 || reviewCommunityText(`${name}\n${newGroup.description}`).length) { setStatus(t.blocked); return; } const group: CommunityGroup = { id: groupId(name), name, description: clean(newGroup.description, 180), visibility: newGroup.visibility, createdAt: Date.now() }; setState((current) => ({ ...current, groups: [...current.groups.filter((item) => item.id !== group.id), group].slice(-20) })); setNewGroup({ name: "", description: "", visibility: "private" }); setFilter("groups"); setStatus(""); }
  async function share(post: FeedPost) { if (post.audience !== "public") { setStatus(t.locked); return; } const draft: SharedPost = { version: 3, kind: post.kind, title: post.title, body: post.body.slice(0, 1600), recipe: post.recipe, author: publicAuthor(post.author) }; const url = new URL(window.location.href); url.searchParams.set("community", encodeShared(draft)); url.hash = "community-feed-title"; if (navigator.share) { try { await navigator.share({ title: post.title, text: post.body.slice(0, 180), url: url.toString() }); return; } catch { return; } } try { await navigator.clipboard.writeText(url.toString()); setStatus(t.shared); } catch { setStatus(url.toString()); } }
  function exportPack() { const pack: CommunityPack = { version: 2, exportedAt: new Date().toISOString(), profile: publicAuthor(normalizedProfile()), posts: state.posts.filter((post) => post.audience === "public").slice(-80).map((post) => ({ ...post, author: publicAuthor(post.author) })), groups: state.groups.filter((group) => group.visibility === "public").slice(-20) }; const url = URL.createObjectURL(new Blob([JSON.stringify(pack, null, 2)], { type: "application/json" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "bytequant-public-community-pack.json"; anchor.click(); window.setTimeout(() => URL.revokeObjectURL(url), 0); }
  async function importPack(file: File | undefined) { if (!file || file.size > 300_000) { setStatus(t.packError); return; } try { const pack = JSON.parse(await file.text()) as Partial<CommunityPack>; if (pack.version !== 2 || !validProfile(pack.profile) || !Array.isArray(pack.posts) || !Array.isArray(pack.groups)) throw new Error("invalid"); const posts = pack.posts.filter(validPost).filter((post) => post.audience === "public" && reviewCommunityText(`${post.title}\n${post.body}`).length === 0).slice(-80).map((post) => ({ ...post, local: false })); const groups = pack.groups.filter(validGroup).filter((group) => group.visibility === "public").slice(-20); setState((current) => ({ ...current, posts: [...current.posts, ...posts].filter((post, index, list) => list.findIndex((candidate) => candidate.id === post.id) === index).slice(-80), groups: [...current.groups, ...groups].filter((group, index, list) => list.findIndex((candidate) => candidate.id === group.id) === index).slice(-20) })); setFilter("all"); setStatus(importedToDevice[locale]); } catch { setStatus(t.packError); } finally { if (importRef.current) importRef.current.value = ""; } }

  return <section className="community-feed community-social-hub" aria-labelledby="community-feed-title">
    <header className="community-feed-heading"><div><span className="kicker">{t.eyebrow}</span><h2 id="community-feed-title">{t.title}</h2><p>{t.intro}</p></div><label><span className="sr-only">{t.search}</span><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t.search} /></label></header>
    <div className="community-social-dashboard">
      <section className="community-profile-card"><header><div className="community-avatar" style={{ backgroundColor: profile.color }}>{profile.name.slice(0, 2).toLocaleUpperCase()}</div><div><strong>{t.profile}</strong><small>@{profile.handle} · {profile.visibility === "public" ? t.publicProfile : t.privateProfile}</small></div></header><p>{t.profileHelp}</p><div className="community-profile-fields"><label><span>{t.displayName}</span><input value={profile.name} maxLength={40} onChange={(event) => setProfile((current) => ({ ...current, name: clean(event.target.value, 40) }))} onBlur={() => setProfile(normalizedProfile())} /></label><label><span>{t.handle}</span><input value={profile.handle} maxLength={24} onChange={(event) => setProfile((current) => ({ ...current, handle: event.target.value.toLocaleLowerCase().replace(/[^a-z0-9-]/g, "").slice(0, 24) }))} onBlur={() => setProfile(normalizedProfile())} /></label><label className="wide"><span>{t.bio}</span><input value={profile.bio} maxLength={160} onChange={(event) => setProfile((current) => ({ ...current, bio: clean(event.target.value, 160) }))} /></label><label><span>{t.profileVisibility}</span><select value={profile.visibility} onChange={(event) => setProfile((current) => ({ ...current, visibility: event.target.value as Visibility }))}><option value="public">{t.publicProfile}</option><option value="private">{t.privateProfile}</option></select></label></div><dl><div><dt>{t.mine}</dt><dd>{state.posts.length}</dd></div><div><dt>{t.savedTab}</dt><dd>{state.saved.length}</dd></div><div><dt>{t.groups}</dt><dd>{state.groups.length}</dd></div></dl><footer><span>{t.portable}</span><button type="button" onClick={exportPack}>{t.export}</button><button type="button" onClick={() => importRef.current?.click()}>{t.import}</button><input ref={importRef} className="sr-only" type="file" accept="application/json,.json" onChange={(event) => void importPack(event.target.files?.[0])} /></footer></section>
      <section className="community-group-card"><header><span>◎</span><div><strong>{t.groupStudio}</strong><small>{t.groupHelp}</small></div></header><label><span>{t.groupName}</span><input value={newGroup.name} maxLength={50} onChange={(event) => setNewGroup((current) => ({ ...current, name: event.target.value }))} /></label><label><span>{t.groupDescription}</span><textarea value={newGroup.description} maxLength={180} rows={3} onChange={(event) => setNewGroup((current) => ({ ...current, description: event.target.value }))} /></label><label><span>{t.groupVisibility}</span><select value={newGroup.visibility} onChange={(event) => setNewGroup((current) => ({ ...current, visibility: event.target.value as Visibility }))}><option value="private">{t.privateGroup}</option><option value="public">{t.public}</option></select></label><button type="button" className="primary-button" onClick={createGroup}>{t.createGroup}</button><div className="community-group-list">{state.groups.map((group) => <button type="button" key={group.id} onClick={() => { setQuery(group.name); setFilter("groups"); }}><span>{group.visibility === "private" ? "◉" : "◎"}</span><strong>{group.name}</strong><small>{group.description || (group.visibility === "private" ? t.privateGroup : t.public)}</small></button>)}{!state.groups.length && <small>{t.noGroup}</small>}</div></section>
    </div>
    <nav className="community-feed-tabs" aria-label={t.title}>{([ ["all", t.all], ["mine", `${t.mine} · ${state.posts.length}`], ["groups", `${t.groups} · ${state.groups.length}`], ["private", t.private], ["saved", `${t.savedTab} · ${state.saved.length}`] ] as Array<[FeedFilter, string]>).map(([value, label]) => <button type="button" className={filter === value ? "active" : ""} key={value} onClick={() => setFilter(value)}>{label}</button>)}{kindOrder.map((kind) => <button type="button" className={filter === kind ? "active" : ""} key={kind} onClick={() => setFilter(kind)}>{t.kinds[kind]}</button>)}</nav>
    {status && <p className="community-feed-status" role="status">{status}</p>}<p className="community-network-boundary"><span>ⓘ</span>{t.boundary}</p>
    <div className="community-feed-grid">{posts.map((post) => { const liked = state.liked.includes(post.id); const saved = state.saved.includes(post.id); const comments = state.comments[post.id] ?? []; const group = state.groups.find((item) => item.id === post.groupId); return <article className={`community-post audience-${post.audience}`} id={`community-${post.id}`} key={post.id}><header><div className="community-author"><span style={{ backgroundColor: post.author.color }}>{post.author.name.slice(0, 2).toLocaleUpperCase()}</span><div><strong>{post.author.name}</strong><small>@{post.author.handle} · {post.local ? t.local : post.createdAt ? t.received : t.curated}</small></div></div><div className="community-post-badges"><b>{t.kinds[post.kind]}</b><span>{post.audience === "group" ? `${t.audience.group}${group ? ` · ${group.name}` : ""}` : t.audience[post.audience]}</span></div></header><h3>{post.title}</h3><p>{post.body}</p>{post.recipe && <a href={post.recipe} rel="nofollow">ByteQuant recipe →</a>}<footer><button type="button" className={liked ? "active" : ""} aria-pressed={liked} onClick={() => toggleList("liked", post.id)}>♡ {liked ? t.liked : t.likes}</button><button type="button" className={saved ? "active" : ""} aria-pressed={saved} onClick={() => toggleList("saved", post.id)}>☆ {saved ? t.saved : t.save}</button><button type="button" onClick={() => { setActiveComment(activeComment === post.id ? null : post.id); setStatus(""); }}>◌ {t.comment}{comments.length ? ` · ${comments.length}` : ""}</button><button type="button" disabled={post.audience !== "public"} onClick={() => void share(post)}>{post.audience === "public" ? `↗ ${t.share}` : `◉ ${t.locked}`}</button></footer>{activeComment === post.id && <div className="community-comments"><strong>{t.comments}</strong>{comments.map((item) => <p key={item.id}><span>↳</span>{item.body}</p>)}<label><span className="sr-only">{t.placeholder}</span><textarea value={comment} maxLength={800} rows={3} onChange={(event) => setComment(event.target.value)} placeholder={t.placeholder} /></label><button type="button" onClick={() => addComment(post.id)}>{t.add}</button></div>}</article>; })}{!posts.length && <div className="community-feed-empty"><span>◎</span><p>{t.empty}</p></div>}</div>
  </section>;
}
