import Link from "next/link";
import { absoluteUrl, languageTag, organizationId, pathFor, type Locale } from "../lib/site";
import { CommunityComposer } from "./CommunityComposer";
import { SchemaScript } from "./SchemaScript";
import { SiteShell } from "./SiteShell";

const copy = {
  tr: { eyebrow: "AÇIK KAYNAK TOPLULUK", title: "İyi iş akışlarını paylaşın; veriyi değil yöntemi yayınlayın", intro: "ByteQuant hesap veya içerik sunucusu çalıştırmaz. Taslağınızı cihazınızda hazırlayıp sınırlı güvenlik filtresinden geçirin, ardından açık kaynak depomuzdaki GitHub Discussions alanında yayınlayın.", cards: [["01", "Yerelde hazırla", "Başlık ve yöntemi bu sekmede yazın; metin ByteQuant sunucusuna gitmez."], ["02", "Gizliliği kontrol et", "Sır, kişisel veri, açık tehdit ve uygunsuz bağlantılar için ön tarama yapın."], ["03", "Toplulukta yayınla", "Güvenli Markdown'ı kopyalayın ve GitHub'ın hesap, raporlama ve moderasyon özelliklerini kullanın."]], rules: "Paylaşım ilkeleri", ruleItems: ["Gerçek kişisel veri, parola, özel anahtar veya müşteri kaydı paylaşmayın.", "Yalnızca sahip olduğunuz ya da paylaşma yetkiniz bulunan içerikleri kullanın.", "Otomatik filtreyi nihai güvenlik veya moderasyon garantisi saymayın.", "Güvenlik açıklarını kamuya açık tartışma yerine SECURITY.md süreciyle bildirin."], repo: "Açık kaynak depoyu incele" },
  en: { eyebrow: "OPEN-SOURCE COMMUNITY", title: "Share useful workflows—not private data", intro: "ByteQuant runs no account or content server. Prepare and pre-screen a draft on-device, then publish it in the GitHub Discussions area of the open-source repository.", cards: [["01", "Prepare locally", "Write the title and method in this tab; text is not sent to a ByteQuant server."], ["02", "Check privacy", "Pre-screen for secrets, personal data, explicit threats, and unsuitable links."], ["03", "Publish with the community", "Copy safe Markdown and use GitHub's account, reporting, and moderation controls."]], rules: "Sharing principles", ruleItems: ["Never share real personal data, passwords, private keys, or customer records.", "Use only material you own or are authorized to share.", "Do not treat the automatic filter as final security or moderation assurance.", "Report vulnerabilities through SECURITY.md rather than a public discussion."], repo: "Explore the open-source repository" },
  de: { eyebrow: "OPEN-SOURCE-COMMUNITY", title: "Nützliche Abläufe teilen – keine privaten Daten", intro: "ByteQuant betreibt keinen Konto- oder Inhaltsserver. Entwurf lokal vorbereiten und vorprüfen, danach in GitHub Discussions des Open-Source-Repositorys veröffentlichen.", cards: [["01", "Lokal vorbereiten", "Titel und Methode bleiben beim Schreiben in diesem Tab."], ["02", "Datenschutz prüfen", "Vorprüfung auf Geheimnisse, Personendaten, offene Drohungen und ungeeignete Links."], ["03", "In der Community veröffentlichen", "Sicheres Markdown kopieren und GitHub-Meldung sowie Moderation nutzen."]], rules: "Grundsätze", ruleItems: ["Keine echten Personendaten, Passwörter, privaten Schlüssel oder Kundendaten teilen.", "Nur eigene oder autorisierte Inhalte verwenden.", "Automatischen Filter nicht als endgültige Sicherheits- oder Moderationsgarantie verstehen.", "Schwachstellen über SECURITY.md statt öffentlich melden."], repo: "Open-Source-Repository ansehen" },
  zh: { eyebrow: "开源社区", title: "分享有用工作流，而不是私人数据", intro: "ByteQuant 不运行账户或内容服务器。请在设备上准备并预检草稿，再发布到开源仓库的 GitHub Discussions。", cards: [["01", "本地准备", "在当前标签页编写标题与方法，文本不会发送到 ByteQuant 服务器。"], ["02", "检查隐私", "预检秘密、个人数据、明显威胁和不合适链接。"], ["03", "发布到社区", "复制安全 Markdown，并使用 GitHub 的账户、举报与审核能力。"]], rules: "分享原则", ruleItems: ["不要分享真实个人数据、密码、私钥或客户记录。", "只使用您拥有或获授权分享的内容。", "自动过滤器不是最终安全或审核保证。", "安全漏洞应通过 SECURITY.md 流程私下报告。"], repo: "查看开源仓库" },
} as const;

export function CommunityPage({ locale }: { locale: Locale }) {
  const c = copy[locale]; const pageUrl = absoluteUrl(pathFor(locale, "community"));
  const schema = [{ "@context": "https://schema.org", "@type": "CollectionPage", name: c.title, description: c.intro, url: pageUrl, inLanguage: languageTag(locale), isPartOf: { "@id": `${absoluteUrl(pathFor(locale, "home"))}#website` }, author: { "@id": organizationId } }, { "@context": "https://schema.org", "@type": "HowTo", name: c.title, inLanguage: languageTag(locale), step: c.cards.map(([number, name, text], index) => ({ "@type": "HowToStep", position: index + 1, name: `${number} · ${name}`, text })) }];
  return <SiteShell locale={locale} alternateHref={pathFor(locale === "tr" ? "en" : "tr", "community")} languageHrefs={{ tr: pathFor("tr", "community"), en: pathFor("en", "community"), de: pathFor("de", "community"), zh: pathFor("zh", "community") }}><SchemaScript data={schema} /><section className="community-hero"><div className="container"><span className="eyebrow"><i />{c.eyebrow}</span><h1>{c.title}</h1><p>{c.intro}</p><div className="community-how">{c.cards.map(([number, title, text]) => <article key={number}><span>{number}</span><h2>{title}</h2><p>{text}</p></article>)}</div></div></section><section className="section"><div className="container"><CommunityComposer locale={locale} /></div></section><section className="section community-rules"><div className="container"><div><span className="kicker">TRUST & SAFETY</span><h2>{c.rules}</h2><ul>{c.ruleItems.map((item) => <li key={item}>✓ <span>{item}</span></li>)}</ul></div><Link className="primary-button" href="https://github.com/byte-quant/bytequant" target="_blank" rel="noreferrer noopener">{c.repo} ↗</Link></div></section></SiteShell>;
}
