"use client";

import { useEffect, useRef, useState } from "react";
import { reviewCommunityText } from "../lib/community-safety";
import { WorkspacePeerMesh } from "../lib/workspace-p2p";
import type { Locale } from "../lib/site";

type Message = { id: string; body: string; from: "me" | "peer"; at: number };
const copy = {
  tr: { eyebrow: "DOĞRUDAN P2P SOHBET", title: "Bir kişiyle, içerik sunucusu olmadan konuşun", intro: "Davet ve yanıt kodlarını güvendiğiniz kişiye ayrı bir kanaldan gönderin. Mesajlar yalnızca açık tarayıcılar arasında, şifreli WebRTC DataChannel üzerinden gider; ByteQuant mesaj geçmişi veya üye dizini tutmaz.", consent: "Kodların yerel ağ adayları içerebileceğini ve yalnızca güvendiğim kişiyle paylaşacağımı anlıyorum.", invite: "Davet oluştur", accept: "Daveti kabul et", apply: "Yanıtı uygula", code: "Davet veya yanıt kodu", result: "Oluşan tek kullanımlık kod", verify: "Karşı tarafta aynı güvenlik kodunu gördüm", safety: "Güvenlik kodu", start: "Sohbeti aç", close: "Odayı kapat", send: "Gönder", placeholder: "En fazla 800 karakter; kişisel veri veya sır paylaşmayın…", blocked: "Mesaj yerel güvenlik filtresinden geçmedi.", waiting: "Bağlantı bekleniyor", connected: "eş bağlı", boundary: "Bu bir kimlik doğrulaması değildir. Ortak sinyalleme/STUN/TURN olmadığı için bazı uzak ağlarda bağlantı kurulamaz; sayfa kapanınca sohbet geçmişi kaybolur. Küresel, kalıcı yayın için ortak bir sunucu zorunludur ve bu sürümde özellikle eklenmemiştir." },
  en: { eyebrow: "DIRECT P2P CHAT", title: "Talk to one person without a content server", intro: "Exchange invite and answer codes through a separate trusted channel. Messages travel only between the open browsers over an encrypted WebRTC DataChannel; ByteQuant stores no message history or member directory.", consent: "I understand that codes can contain local network candidates and will share them only with someone I trust.", invite: "Create invite", accept: "Accept invite", apply: "Apply answer", code: "Invite or answer code", result: "Generated single-use code", verify: "I see the same safety code on the other device", safety: "Safety code", start: "Open chat", close: "Close room", send: "Send", placeholder: "Up to 800 characters; do not share personal data or secrets…", blocked: "The message did not pass the on-device safety filter.", waiting: "Waiting for connection", connected: "peer connected", boundary: "This is not identity verification. Without shared signaling, STUN, or TURN, some remote networks cannot connect; closing the page removes chat history. Global persistent publishing requires shared infrastructure and is intentionally not enabled in this release." },
  de: { eyebrow: "DIREKTER P2P-CHAT", title: "Mit einer Person ohne Inhaltsserver sprechen", intro: "Einladungs- und Antwortcodes über einen separaten vertrauenswürdigen Kanal austauschen. Nachrichten laufen nur zwischen geöffneten Browsern über einen verschlüsselten WebRTC DataChannel; ByteQuant speichert weder Verlauf noch Mitgliederverzeichnis.", consent: "Mir ist bewusst, dass Codes lokale Netzwerkkandidaten enthalten können und nur an eine vertrauenswürdige Person gehören.", invite: "Einladung erstellen", accept: "Einladung annehmen", apply: "Antwort anwenden", code: "Einladungs- oder Antwortcode", result: "Erzeugter Einmalcode", verify: "Auf dem anderen Gerät wird derselbe Sicherheitscode angezeigt", safety: "Sicherheitscode", start: "Chat öffnen", close: "Raum schließen", send: "Senden", placeholder: "Maximal 800 Zeichen; keine Personendaten oder Secrets…", blocked: "Die Nachricht hat die lokale Sicherheitsprüfung nicht bestanden.", waiting: "Warten auf Verbindung", connected: "Gegenstelle verbunden", boundary: "Dies ist keine Identitätsprüfung. Ohne gemeinsame Signalisierung, STUN oder TURN können manche entfernten Netze nicht verbinden; beim Schließen verschwindet der Verlauf. Globale dauerhafte Veröffentlichung erfordert gemeinsame Infrastruktur und ist in dieser Version bewusst nicht aktiviert." },
  zh: { eyebrow: "直接 P2P 聊天", title: "无需内容服务器，与一人直接交流", intro: "通过独立可信渠道交换邀请和应答代码。消息只在已打开的浏览器之间通过加密 WebRTC DataChannel 传输；ByteQuant 不保存消息历史或成员目录。", consent: "我了解代码可能包含本地网络候选信息，并且只会分享给可信的人。", invite: "创建邀请", accept: "接受邀请", apply: "应用应答", code: "邀请或应答代码", result: "生成的一次性代码", verify: "另一台设备显示了相同安全码", safety: "安全码", start: "开启聊天", close: "关闭房间", send: "发送", placeholder: "最多 800 字符；请勿分享个人数据或密钥…", blocked: "消息未通过设备端安全过滤。", waiting: "等待连接", connected: "个对等端已连接", boundary: "这不是身份验证。由于没有共享信令、STUN 或 TURN，部分远程网络可能无法连接；关闭页面后聊天记录会消失。全球持久发布需要共享基础设施，本版本有意不启用。" },
} as const;

export function CommunityP2PChat({ locale }: { locale: Locale }) {
  const t = copy[locale]; const meshRef = useRef<WorkspacePeerMesh | null>(null);
  const [consent, setConsent] = useState(false); const [signal, setSignal] = useState(""); const [generated, setGenerated] = useState(""); const [peers, setPeers] = useState(0); const [codes, setCodes] = useState<string[]>([]); const [verified, setVerified] = useState(false); const [enabled, setEnabled] = useState(false); const [text, setText] = useState(""); const [messages, setMessages] = useState<Message[]>([]); const [status, setStatus] = useState<string>(t.waiting);
  function mesh() { if (meshRef.current) return meshRef.current; const value = new WorkspacePeerMesh(); value.onStatus = (next, count) => { setPeers(count); setStatus(next); }; value.onSecurity = (_peer, code) => setCodes((current) => code ? [...new Set([...current, code])].slice(-4) : current); value.onMessage = (body, _peer, at) => { if (reviewCommunityText(body).length) return; setMessages((current) => [...current, { id: crypto.randomUUID(), body, from: "peer" as const, at }].slice(-100)); }; meshRef.current = value; return value; }
  useEffect(() => () => meshRef.current?.close(), []);
  async function invite() { if (!consent) return; try { setGenerated(await mesh().createInvite()); } catch { setStatus("error"); } }
  async function accept() { if (!consent) return; try { setGenerated(await mesh().acceptInvite(signal)); } catch { setStatus("error"); } }
  async function apply() { if (!consent) return; try { await mesh().acceptAnswer(signal); setGenerated(""); } catch { setStatus("error"); } }
  function toggle() { if (!verified || peers < 1) return; const next = !enabled; mesh().setChatEnabled(next); setEnabled(next); }
  function send() { const body = text.trim(); if (!enabled || !body) return; if (reviewCommunityText(body).length) { setStatus(t.blocked); return; } try { mesh().broadcastMessage(body); setMessages((current) => [...current, { id: crypto.randomUUID(), body, from: "me" as const, at: Date.now() }].slice(-100)); setText(""); } catch { setStatus("error"); } }
  function close() { meshRef.current?.close(); meshRef.current = null; setPeers(0); setCodes([]); setVerified(false); setEnabled(false); setGenerated(""); setSignal(""); setMessages([]); setStatus(t.waiting); }
  return <section className="community-p2p" aria-labelledby="community-p2p-title"><header><span className="kicker">{t.eyebrow}</span><h2 id="community-p2p-title">{t.title}</h2><p>{t.intro}</p></header><div className="community-p2p-grid"><div className="community-p2p-connect"><label className="workspace-checkbox"><input type="checkbox" checked={consent} onChange={(event) => setConsent(event.target.checked)} />{t.consent}</label><div className="community-p2p-actions"><button type="button" disabled={!consent} onClick={() => void invite()}>{t.invite}</button><button type="button" disabled={!consent || !signal.trim()} onClick={() => void accept()}>{t.accept}</button><button type="button" disabled={!consent || !signal.trim()} onClick={() => void apply()}>{t.apply}</button></div><label><span>{t.code}</span><textarea value={signal} maxLength={180000} rows={4} onChange={(event) => setSignal(event.target.value)} /></label>{generated && <label><span>{t.result}</span><textarea readOnly value={generated} rows={4} onFocus={(event) => event.currentTarget.select()} /></label>}<div className="community-p2p-state"><span>{peers} {t.connected}</span><small>{status}</small></div>{codes.map((code) => <label className="community-safety-code" key={code}><span>{t.safety}</span><strong>{code}</strong></label>)}<label className="workspace-checkbox"><input type="checkbox" disabled={!codes.length} checked={verified} onChange={(event) => setVerified(event.target.checked)} />{t.verify}</label><div className="community-p2p-actions"><button className={enabled ? "active" : ""} type="button" disabled={!verified || peers < 1} onClick={toggle}>{t.start}</button><button type="button" onClick={close}>{t.close}</button></div></div><div className="community-chat"><div className="community-chat-log" aria-live="polite">{messages.map((message) => <article className={message.from} key={message.id}><span>{message.from === "me" ? "You" : "Peer"}</span><p>{message.body}</p><small>{new Date(message.at).toLocaleTimeString()}</small></article>)}{!messages.length && <p>{t.waiting}</p>}</div><label><span className="sr-only">Message</span><textarea value={text} maxLength={800} rows={4} placeholder={t.placeholder} onChange={(event) => setText(event.target.value)} /></label><button type="button" className="primary-button" disabled={!enabled || !text.trim()} onClick={send}>{t.send} →</button></div></div><small className="community-p2p-boundary">{t.boundary}</small></section>;
}
