"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { reviewCommunityText } from "../lib/community-safety";
import type { Locale } from "../lib/site";
import { communityPublishEvent } from "./CommunityComposer";

type Kind = "workflow" | "tip" | "idea" | "question";
type CommunityProfile = { name: string; handle: string; color: string };
type FeedPost = { id: string; kind: Kind; title: string; body: string; recipe: string; local: boolean; createdAt: number; author: CommunityProfile };
type FeedComment = { id: string; body: string; createdAt: number };
type FeedState = { posts: FeedPost[]; liked: string[]; saved: string[]; comments: Record<string, FeedComment[]> };
type ComposerDraft = { version: 1; kind: Kind; title: string; body: string; recipe: string };
type SharedPost = { version: 2; kind: Kind; title: string; body: string; recipe: string; author: CommunityProfile };
type CommunityPack = { version: 1; exportedAt: string; profile: CommunityProfile; posts: FeedPost[] };

const storageKey = "bytequant:community-feed:v2";
const profileKey = "bytequant:community-profile:v1";
const kindOrder: Kind[] = ["workflow", "tip", "idea", "question"];
const defaultProfiles: Record<Locale, CommunityProfile> = {
  tr: { name: "Yerel üretici", handle: "cihazim", color: "#3157ff" }, en: { name: "Local maker", handle: "my-device", color: "#3157ff" },
  de: { name: "Lokaler Maker", handle: "mein-geraet", color: "#3157ff" }, zh: { name: "本地创作者", handle: "my-device", color: "#3157ff" },
};

const copy = {
  tr: { eyebrow: "HESAPSIZ TOPLULUK ALANI", title: "Fikirleri keşfedin, kendi panonuzu kurun ve güvenli bağlantıyla paylaşın", intro: "Akış, beğeni ve yorumlar bu cihazın gerçek etkileşimleridir; küresel sayaç gibi gösterilmez. Bir gönderiyi bağlantıya gömdüğünüzde seçtiğiniz kişi içeriği hesabı olmadan açabilir.", all: "Keşfet", mine: "Paylaşımlarım", savedTab: "Kaydettiklerim", search: "Başlık veya yöntemde ara", empty: "Bu görünümde henüz paylaşım yok. Güvenli taslakla ilk katkınızı ekleyebilirsiniz.", likes: "Faydalı", liked: "Faydalı buldunuz", save: "Kaydet", saved: "Kaydedildi", comment: "Yorum", share: "Bağlantı", comments: "Bu cihazdaki yorumlar", placeholder: "Yapıcı bir yorum yazın; kişisel veri veya sır eklemeyin.", add: "Yorumu ekle", blocked: "İçerik eklenemedi: kişisel veri, sır, dış bağlantı veya uygunsuz dil olabilir.", short: "Yorum en az 3 karakter olmalı.", shared: "İçeriği taşıyan paylaşım bağlantısı kopyalandı.", imported: "Paylaşılan gönderi bu sekmedeki panoya eklendi.", local: "Bu cihaz", curated: "ByteQuant başlangıcı", sharedLabel: "Bağlantıyla geldi", kinds: { workflow: "İş akışı", tip: "İpucu", idea: "Fikir", question: "Soru" }, profile: "Yerel profil", profileHelp: "Takma adınız yalnızca bu sekmedeki gönderilere ve dışa aktardığınız pakete eklenir.", displayName: "Görünen ad", handle: "Kullanıcı adı", portable: "Panoyu taşı", export: "Paket indir", import: "Paket yükle", packError: "Paket doğrulanamadı veya güvenlik filtresinden geçmedi.", boundary: "Kalıcı küresel keşif, üye dizini ve çevrimdışı mesajlaşma ortak bir sunucu/relay gerektirir. ByteQuant bunu gizlice taklit etmez; bunun yerine taşınabilir paket, içerikli bağlantı ve doğrudan P2P sunar." },
  en: { eyebrow: "NO-ACCOUNT COMMUNITY SPACE", title: "Discover ideas, build your own board, and share with a safe link", intro: "The feed, reactions, and comments are real interactions on this device, never presented as global counts. A post embedded in a link can be opened by anyone you choose without an account.", all: "Explore", mine: "My posts", savedTab: "Saved", search: "Search titles or methods", empty: "There are no posts in this view yet. Add the first contribution with the safe composer.", likes: "Useful", liked: "Marked useful", save: "Save", saved: "Saved", comment: "Comment", share: "Share link", comments: "Comments on this device", placeholder: "Write a constructive comment; do not include personal data or secrets.", add: "Add comment", blocked: "Content was blocked: it may contain personal data, a secret, an external link, or abusive language.", short: "A comment needs at least 3 characters.", shared: "A link carrying the post was copied.", imported: "The shared post was added to this tab's board.", local: "This device", curated: "ByteQuant starter", sharedLabel: "Received by link", kinds: { workflow: "Workflow", tip: "Tip", idea: "Idea", question: "Question" }, profile: "Local profile", profileHelp: "Your alias is attached only to posts in this tab and packs you export.", displayName: "Display name", handle: "Handle", portable: "Move your board", export: "Download pack", import: "Import pack", packError: "The pack could not be validated or did not pass the safety filter.", boundary: "Persistent global discovery, member directories, and offline messaging require shared server or relay infrastructure. ByteQuant does not fake that boundary; it offers portable packs, content-carrying links, and direct P2P instead." },
  de: { eyebrow: "COMMUNITY OHNE KONTO", title: "Ideen entdecken, eigenes Board aufbauen und per sicherem Link teilen", intro: "Feed, Reaktionen und Kommentare sind echte Interaktionen auf diesem Gerät und werden nie als globale Zahlen ausgegeben. Ein im Link eingebetteter Beitrag lässt sich ohne Konto öffnen.", all: "Entdecken", mine: "Meine Beiträge", savedTab: "Gespeichert", search: "Titel oder Methode suchen", empty: "In dieser Ansicht gibt es noch keinen Beitrag. Über den sicheren Editor können Sie beginnen.", likes: "Hilfreich", liked: "Als hilfreich markiert", save: "Speichern", saved: "Gespeichert", comment: "Kommentar", share: "Link teilen", comments: "Kommentare auf diesem Gerät", placeholder: "Konstruktiv kommentieren; keine Personendaten oder Geheimnisse.", add: "Kommentar hinzufügen", blocked: "Inhalt blockiert: mögliche Personendaten, Geheimnisse, externer Link oder Missbrauch.", short: "Ein Kommentar benötigt mindestens 3 Zeichen.", shared: "Ein Link mit dem Beitragsinhalt wurde kopiert.", imported: "Der geteilte Beitrag wurde dem Board dieses Tabs hinzugefügt.", local: "Dieses Gerät", curated: "ByteQuant-Start", sharedLabel: "Per Link erhalten", kinds: { workflow: "Ablauf", tip: "Tipp", idea: "Idee", question: "Frage" }, profile: "Lokales Profil", profileHelp: "Ihr Alias wird nur Beiträgen dieses Tabs und exportierten Paketen beigefügt.", displayName: "Anzeigename", handle: "Kürzel", portable: "Board übertragen", export: "Paket laden", import: "Paket importieren", packError: "Paket ungültig oder vom lokalen Sicherheitsfilter abgelehnt.", boundary: "Dauerhafte globale Suche, Mitgliederverzeichnis und Offline-Nachrichten benötigen gemeinsame Server- oder Relay-Infrastruktur. ByteQuant täuscht dies nicht vor, sondern bietet portable Pakete, Inhaltslinks und direktes P2P." },
  zh: { eyebrow: "免账号社区空间", title: "发现方法、建立自己的看板，并通过安全链接分享", intro: "动态、互动与评论都是真实的设备内行为，不会伪装成全站数据。嵌入链接的帖子可由您选择的人免账号打开。", all: "发现", mine: "我的分享", savedTab: "已收藏", search: "搜索标题或方法", empty: "当前视图还没有分享，可使用安全编辑器添加第一条。", likes: "有用", liked: "已标记有用", save: "收藏", saved: "已收藏", comment: "评论", share: "分享链接", comments: "本设备上的评论", placeholder: "写下建设性评论；不要包含个人数据或密钥。", add: "添加评论", blocked: "内容被阻止：可能包含个人数据、密钥、外部链接或不当语言。", short: "评论至少需要 3 个字符。", shared: "已复制包含帖子内容的链接。", imported: "分享的帖子已加入当前标签页的看板。", local: "本设备", curated: "ByteQuant 起始内容", sharedLabel: "通过链接收到", kinds: { workflow: "工作流", tip: "技巧", idea: "建议", question: "问题" }, profile: "本地资料", profileHelp: "别名只会附加到当前标签页的帖子和您导出的社区包。", displayName: "显示名称", handle: "用户名", portable: "迁移看板", export: "下载社区包", import: "导入社区包", packError: "社区包无效或未通过本地安全过滤。", boundary: "持久的全球发现、成员目录与离线消息需要共享服务器或中继。ByteQuant 不会伪装具备这些能力，而是提供可移植社区包、内容链接和直接 P2P。" },
} as const;

const starterAuthor: Record<Locale, CommunityProfile> = {
  tr: { name: "ByteQuant Rehberleri", handle: "bytequant", color: "#008f8a" }, en: { name: "ByteQuant Guides", handle: "bytequant", color: "#008f8a" },
  de: { name: "ByteQuant Ratgeber", handle: "bytequant", color: "#008f8a" }, zh: { name: "ByteQuant 指南", handle: "bytequant", color: "#008f8a" },
};
const starterContent: Record<Locale, Array<[string, Kind, string, string]>> = {
  tr: [["starter-privacy", "workflow", "Gerçek kayıt kullanmadan KVKK akışını prova edin", "Yapay CSV yükleyin, hassas sütunları maskeleyin ve JSON çıktısını yapısal doğrulayın. İlk denemede gerçek müşteri verisi kullanmayın."], ["starter-json", "tip", "JSON tesliminden önce üç kısa kontrol", "Sözdizimini biçimlendirin, beklenen alanları şemayla doğrulayın ve önceki sürümle yapısal diff alın."], ["starter-agent", "question", "Ajan mı İş İstasyonu mu?", "Sonucu biliyor ama sıra konusunda emin değilseniz Ajanla başlayın. Tekrarlanabilir görsel akış için planı İş İstasyonuna aktarın."], ["starter-prompt", "idea", "Paylaşılabilir prompt tarifi", "Amaç, bağlam, sınır ve çıktı biçimini ayrı alanlarda tutun; gerçek müşteri verisini sentetik yer tutucularla değiştirin."]],
  en: [["starter-privacy", "workflow", "Rehearse a privacy workflow without real records", "Load synthetic CSV, mask sensitive columns, and structurally validate the JSON output. Do not use customer records for the first run."], ["starter-json", "tip", "Three checks before delivering JSON", "Format syntax, validate expected fields against a schema, and run a structural diff against the previous version."], ["starter-agent", "question", "Agent or Workstation?", "Start with Agent when the outcome is clear but the order is not. Send the plan to Workstation for a repeatable visual flow."], ["starter-prompt", "idea", "A prompt recipe worth sharing", "Keep outcome, context, boundaries, and output shape in separate fields; replace real customer details with synthetic placeholders."]],
  de: [["starter-privacy", "workflow", "Datenschutz-Ablauf ohne echte Daten proben", "Synthetische CSV laden, sensible Spalten maskieren und JSON strukturell prüfen. Beim ersten Lauf keine Kundendaten verwenden."], ["starter-json", "tip", "Drei Prüfungen vor der JSON-Übergabe", "Syntax formatieren, erwartete Felder per Schema prüfen und einen strukturellen Diff zur Vorversion ausführen."], ["starter-agent", "question", "Agent oder Workstation?", "Mit dem Agenten starten, wenn das Ziel klar, die Reihenfolge aber offen ist. Für wiederholbare Abläufe an die Workstation senden."], ["starter-prompt", "idea", "Teilbares Prompt-Rezept", "Ziel, Kontext, Grenzen und Ausgabe getrennt halten; reale Kundendaten durch synthetische Platzhalter ersetzen."]],
  zh: [["starter-privacy", "workflow", "不使用真实记录演练隐私流程", "加载合成 CSV、遮蔽敏感列并验证 JSON 结构。第一次运行不要使用真实客户数据。"], ["starter-json", "tip", "交付 JSON 前的三项检查", "格式化语法、用 Schema 验证字段，并与旧版本做结构差异比较。"], ["starter-agent", "question", "助手还是工作站？", "目标明确但顺序不清时先用助手；需要可复用的可视化流程时发送到工作站。"], ["starter-prompt", "idea", "值得分享的提示词配方", "把目标、上下文、边界与输出结构分开，并用合成占位符替换真实客户信息。"]],
};
const curated = (locale: Locale): FeedPost[] => starterContent[locale].map(([id, kind, title, body]) => ({ id, kind, title, body, recipe: "", local: false, createdAt: 0, author: starterAuthor[locale] }));

function clean(value: string, max: number) { return value.replace(/[\u0000-\u001F\u007F]/g, "").replace(/<[^>]*>/g, "").trim().slice(0, max); }
function makeId() { return globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random().toString(36).slice(2)}`; }
function safeRecipe(value: string) { return !value || /^https:\/\/(?:www\.)?bytequant\.org\/workspace\/?\?recipe=[A-Za-z0-9_%.-]+$/i.test(value); }
function validProfile(value: unknown): value is CommunityProfile { const profile = value as Partial<CommunityProfile>; return Boolean(profile && typeof profile.name === "string" && profile.name.length <= 40 && typeof profile.handle === "string" && /^[a-z0-9-]{2,24}$/i.test(profile.handle) && typeof profile.color === "string" && /^#[0-9a-f]{6}$/i.test(profile.color)); }
function validComposerDraft(value: unknown): value is ComposerDraft { const draft = value as Partial<ComposerDraft>; return Boolean(draft && draft.version === 1 && kindOrder.includes(draft.kind as Kind) && typeof draft.title === "string" && typeof draft.body === "string" && typeof draft.recipe === "string"); }
function validPost(value: unknown): value is FeedPost { const post = value as Partial<FeedPost>; return Boolean(post && typeof post.id === "string" && post.id.length <= 120 && kindOrder.includes(post.kind as Kind) && typeof post.title === "string" && post.title.length <= 120 && typeof post.body === "string" && post.body.length <= 5000 && typeof post.recipe === "string" && safeRecipe(post.recipe) && typeof post.local === "boolean" && Number.isFinite(post.createdAt) && validProfile(post.author)); }
function validComment(value: unknown): value is FeedComment { const item = value as Partial<FeedComment>; return Boolean(item && typeof item.id === "string" && item.id.length <= 120 && typeof item.body === "string" && item.body.length <= 800 && Number.isFinite(item.createdAt)); }
function encodeShared(value: SharedPost) { const bytes = new TextEncoder().encode(JSON.stringify(value)); let binary = ""; bytes.forEach((byte) => { binary += String.fromCharCode(byte); }); return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/g, ""); }
function decodeShared(value: string): SharedPost | null { try { const padded = value.replace(/-/g, "+").replace(/_/g, "/").padEnd(Math.ceil(value.length / 4) * 4, "="); const binary = atob(padded); const bytes = Uint8Array.from(binary, (char) => char.charCodeAt(0)); const draft = JSON.parse(new TextDecoder().decode(bytes)) as Partial<SharedPost>; if (!draft || draft.version !== 2 || !kindOrder.includes(draft.kind as Kind) || typeof draft.title !== "string" || typeof draft.body !== "string" || typeof draft.recipe !== "string" || !safeRecipe(draft.recipe) || !validProfile(draft.author)) return null; return { version: 2, kind: draft.kind as Kind, title: clean(draft.title, 120), body: clean(draft.body, 1600), recipe: clean(draft.recipe, 4000), author: draft.author }; } catch { return null; } }

export function CommunityFeed({ locale }: { locale: Locale }) {
  const t = copy[locale];
  const [state, setState] = useState<FeedState>({ posts: [], liked: [], saved: [], comments: {} });
  const [profile, setProfile] = useState<CommunityProfile>(defaultProfiles[locale]);
  const [hydrated, setHydrated] = useState(false);
  const [filter, setFilter] = useState<"all" | "mine" | "saved" | Kind>("all");
  const [query, setQuery] = useState(""); const [activeComment, setActiveComment] = useState<string | null>(null); const [comment, setComment] = useState(""); const [status, setStatus] = useState("");
  const importRef = useRef<HTMLInputElement | null>(null);

  useEffect(() => {
    const frame = requestAnimationFrame(() => {
      try {
        const storedProfile: unknown = JSON.parse(sessionStorage.getItem(profileKey) ?? "null"); if (validProfile(storedProfile)) setProfile(storedProfile);
        const parsed = JSON.parse(sessionStorage.getItem(storageKey) ?? "null") as Partial<FeedState> | null;
        if (parsed && Array.isArray(parsed.posts) && Array.isArray(parsed.liked) && parsed.comments && typeof parsed.comments === "object") {
          const comments = Object.fromEntries(Object.entries(parsed.comments).filter(([key, value]) => key.length <= 120 && Array.isArray(value)).map(([key, value]) => [key, value.filter(validComment).slice(-30)]));
          setState({ posts: parsed.posts.filter(validPost).slice(-60), liked: parsed.liked.filter((item): item is string => typeof item === "string").slice(-120), saved: Array.isArray(parsed.saved) ? parsed.saved.filter((item): item is string => typeof item === "string").slice(-120) : [], comments });
        }
        const shared = new URL(window.location.href).searchParams.get("community");
        if (shared && shared.length < 8_000) { const draft = decodeShared(shared); if (draft && reviewCommunityText(`${draft.title}\n${draft.body}`).length === 0) { setState((current) => ({ ...current, posts: [...current.posts.filter((post) => post.id !== `shared-${shared.slice(0, 20)}`), { id: `shared-${shared.slice(0, 20)}`, kind: draft.kind, title: draft.title, body: draft.body, recipe: draft.recipe, local: false, createdAt: Date.now(), author: draft.author }].slice(-60) })); setStatus(t.imported); } }
      } catch { /* optional tab state */ }
      setHydrated(true);
    });
    return () => cancelAnimationFrame(frame);
  }, [t.imported]);

  useEffect(() => {
    const receive = (event: Event) => {
      const draft = (event as CustomEvent<unknown>).detail; if (!validComposerDraft(draft) || reviewCommunityText(`${draft.title}\n${draft.body}`).length) return;
      const recipe = clean(draft.recipe, 4000); if (!safeRecipe(recipe)) return;
      const post: FeedPost = { id: makeId(), kind: draft.kind, title: clean(draft.title, 120), body: clean(draft.body, 5000), recipe, local: true, createdAt: Date.now(), author: profile };
      setState((current) => ({ ...current, posts: [...current.posts, post].slice(-60) })); setFilter("mine");
    };
    window.addEventListener(communityPublishEvent, receive); return () => window.removeEventListener(communityPublishEvent, receive);
  }, [profile]);
  useEffect(() => { if (hydrated) try { sessionStorage.setItem(storageKey, JSON.stringify(state)); sessionStorage.setItem(profileKey, JSON.stringify(profile)); } catch { /* continue without persistence */ } }, [hydrated, profile, state]);

  const posts = useMemo(() => [...curated(locale), ...state.posts].filter((post) => filter === "all" ? true : filter === "mine" ? post.local : filter === "saved" ? state.saved.includes(post.id) : post.kind === filter).filter((post) => `${post.title} ${post.body} ${post.author.name}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())), [filter, locale, query, state.posts, state.saved]);
  function toggleList(field: "liked" | "saved", postId: string) { setState((current) => ({ ...current, [field]: current[field].includes(postId) ? current[field].filter((value) => value !== postId) : [...current[field], postId].slice(-120) })); }
  function addComment(postId: string) { const body = clean(comment, 800); if (body.length < 3) { setStatus(t.short); return; } if (reviewCommunityText(body).length) { setStatus(t.blocked); return; } setState((current) => ({ ...current, comments: { ...current.comments, [postId]: [...(current.comments[postId] ?? []), { id: makeId(), body, createdAt: Date.now() }].slice(-30) } })); setComment(""); setStatus(""); }
  async function share(post: FeedPost) { const draft: SharedPost = { version: 2, kind: post.kind, title: post.title, body: post.body.slice(0, 1600), recipe: post.recipe, author: post.author }; const url = new URL(window.location.href); url.searchParams.set("community", encodeShared(draft)); url.hash = "community-feed-title"; if (navigator.share) { try { await navigator.share({ title: post.title, text: post.body.slice(0, 180), url: url.toString() }); return; } catch { return; } } try { await navigator.clipboard.writeText(url.toString()); setStatus(t.shared); } catch { setStatus(url.toString()); } }
  function normalizedProfile(): CommunityProfile { return { name: profile.name.trim() || "ByteQuant", handle: /^[a-z0-9-]{2,24}$/i.test(profile.handle) ? profile.handle : "local", color: /^#[0-9a-f]{6}$/i.test(profile.color) ? profile.color : "#3157ff" }; }
  function exportPack() { const pack: CommunityPack = { version: 1, exportedAt: new Date().toISOString(), profile: normalizedProfile(), posts: state.posts.slice(-60) }; const blob = new Blob([JSON.stringify(pack, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "bytequant-community-pack.json"; anchor.click(); URL.revokeObjectURL(url); }
  async function importPack(file: File | undefined) { if (!file || file.size > 250_000) { setStatus(t.packError); return; } try { const pack = JSON.parse(await file.text()) as Partial<CommunityPack>; if (pack.version !== 1 || !validProfile(pack.profile) || !Array.isArray(pack.posts)) throw new Error("invalid"); const safePosts = pack.posts.filter(validPost).filter((post) => reviewCommunityText(`${post.title}\n${post.body}`).length === 0).slice(-60).map((post) => ({ ...post, local: true })); if (!safePosts.length && pack.posts.length) throw new Error("blocked"); setProfile(pack.profile); setState((current) => ({ ...current, posts: [...current.posts, ...safePosts].filter((post, index, list) => list.findIndex((candidate) => candidate.id === post.id) === index).slice(-60) })); setFilter("mine"); setStatus(t.imported); } catch { setStatus(t.packError); } finally { if (importRef.current) importRef.current.value = ""; } }

  return <section className="community-feed" aria-labelledby="community-feed-title">
    <header><div><span className="kicker">{t.eyebrow}</span><h2 id="community-feed-title">{t.title}</h2><p>{t.intro}</p></div><label><span className="sr-only">{t.search}</span><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t.search} /></label></header>
    <div className="community-profile-strip"><div className="community-avatar" style={{ backgroundColor: profile.color }}>{profile.name.slice(0, 2).toLocaleUpperCase()}</div><div><strong>{t.profile}</strong><small>{t.profileHelp}</small></div><label><span>{t.displayName}</span><input value={profile.name} maxLength={40} onChange={(event) => setProfile((current) => ({ ...current, name: clean(event.target.value, 40) }))} onBlur={() => setProfile(normalizedProfile())} /></label><label><span>{t.handle}</span><input value={profile.handle} maxLength={24} onChange={(event) => setProfile((current) => ({ ...current, handle: event.target.value.toLocaleLowerCase().replace(/[^a-z0-9-]/g, "").slice(0, 24) }))} onBlur={() => setProfile(normalizedProfile())} /></label><div className="community-pack-actions"><small>{t.portable}</small><button type="button" onClick={exportPack}>{t.export}</button><button type="button" onClick={() => importRef.current?.click()}>{t.import}</button><input ref={importRef} className="sr-only" type="file" accept="application/json,.json" onChange={(event) => void importPack(event.target.files?.[0])} /></div></div>
    <nav aria-label={t.title}><button type="button" className={filter === "all" ? "active" : ""} onClick={() => setFilter("all")}>{t.all}</button><button type="button" className={filter === "mine" ? "active" : ""} onClick={() => setFilter("mine")}>{t.mine} · {state.posts.filter((post) => post.local).length}</button><button type="button" className={filter === "saved" ? "active" : ""} onClick={() => setFilter("saved")}>{t.savedTab} · {state.saved.length}</button>{kindOrder.map((kind) => <button type="button" className={filter === kind ? "active" : ""} key={kind} onClick={() => setFilter(kind)}>{t.kinds[kind]}</button>)}</nav>
    {status && <p className="community-feed-status" role="status">{status}</p>}<p className="community-network-boundary"><span>ⓘ</span>{t.boundary}</p>
    <div className="community-feed-grid">{posts.map((post) => { const liked = state.liked.includes(post.id); const saved = state.saved.includes(post.id); const comments = state.comments[post.id] ?? []; const shared = !post.local && post.createdAt > 0; return <article id={`community-${post.id}`} key={post.id}><header><div className="community-author"><span style={{ backgroundColor: post.author.color }}>{post.author.name.slice(0, 2).toLocaleUpperCase()}</span><div><strong>{post.author.name}</strong><small>@{post.author.handle} · {post.local ? t.local : shared ? t.sharedLabel : t.curated}</small></div></div><b>{t.kinds[post.kind]}</b></header><h3>{post.title}</h3><p>{post.body}</p>{post.recipe && <a href={post.recipe} rel="nofollow">ByteQuant recipe →</a>}<footer><button type="button" className={liked ? "active" : ""} aria-pressed={liked} onClick={() => toggleList("liked", post.id)}>♡ {liked ? t.liked : t.likes}</button><button type="button" className={saved ? "active" : ""} aria-pressed={saved} onClick={() => toggleList("saved", post.id)}>☆ {saved ? t.saved : t.save}</button><button type="button" onClick={() => { setActiveComment(activeComment === post.id ? null : post.id); setStatus(""); }}>◌ {t.comment}{comments.length ? ` · ${comments.length}` : ""}</button><button type="button" onClick={() => void share(post)}>↗ {t.share}</button></footer>{activeComment === post.id && <div className="community-comments"><strong>{t.comments}</strong>{comments.map((item) => <p key={item.id}><span>↳</span>{item.body}</p>)}<label><span className="sr-only">{t.placeholder}</span><textarea value={comment} maxLength={800} rows={3} onChange={(event) => setComment(event.target.value)} placeholder={t.placeholder} /></label><button type="button" onClick={() => addComment(post.id)}>{t.add}</button></div>}</article>; })}{posts.length === 0 && <div className="community-feed-empty"><span>◎</span><p>{t.empty}</p></div>}</div>
  </section>;
}
