"use client";

import { useState } from "react";
import type { Locale } from "../lib/site";
import { ToolNotice, type ToolNoticeData } from "./ToolNotice";

type Metric = { label: string; value: string | number };
type ToolResult = { output: string; metrics: Metric[]; notice?: ToolNoticeData };
const pick = <T,>(locale: Locale, value: Record<Locale, T>) => value[locale];
const tag = (locale: Locale) => ({ tr: "tr-TR", en: "en-US", de: "de-DE", zh: "zh-CN" })[locale];

const labels = {
  tr: { local: "Yerel çalışma alanı", privacy: "Girdi bu sekmeden çıkmaz", demo: "Örnek veri yükle", clear: "Temizle", input: "Girdi", secondary: "Ayar / ikinci girdi", run: "Cihazımda çalıştır", running: "İşleniyor…", output: "Doğrulanmış çıktı", copy: "Kopyala", download: "İndir", empty: "Sonuç burada görünecek.", copied: "Çıktı panoya kopyalandı.", downloaded: "Çıktı indirildi.", failed: "İşlem tamamlanamadı" },
  en: { local: "Local workspace", privacy: "Input stays in this tab", demo: "Load example", clear: "Clear", input: "Input", secondary: "Settings / second input", run: "Run on my device", running: "Processing…", output: "Validated output", copy: "Copy", download: "Download", empty: "The result will appear here.", copied: "Output copied.", downloaded: "Output downloaded.", failed: "The operation could not complete" },
  de: { local: "Lokaler Arbeitsbereich", privacy: "Eingaben bleiben in diesem Tab", demo: "Beispiel laden", clear: "Leeren", input: "Eingabe", secondary: "Einstellung / zweite Eingabe", run: "Auf meinem Gerät ausführen", running: "Verarbeitung…", output: "Geprüfte Ausgabe", copy: "Kopieren", download: "Herunterladen", empty: "Das Ergebnis erscheint hier.", copied: "Ausgabe kopiert.", downloaded: "Ausgabe heruntergeladen.", failed: "Der Vorgang konnte nicht abgeschlossen werden" },
  zh: { local: "本地工作区", privacy: "输入保留在当前标签页", demo: "加载示例", clear: "清空", input: "输入", secondary: "设置 / 第二输入", run: "在我的设备上运行", running: "处理中…", output: "已验证输出", copy: "复制", download: "下载", empty: "结果将显示在这里。", copied: "输出已复制。", downloaded: "输出已下载。", failed: "操作未能完成" },
} as const;

const inputNames: Record<string, Record<Locale, string>> = {
  "json-lines-donusturucu": { tr: "JSON dizisi veya NDJSON", en: "JSON array or NDJSON", de: "JSON-Array oder NDJSON", zh: "JSON 数组或 NDJSON" },
  "json-pointer-gezgini": { tr: "JSON belgesi", en: "JSON document", de: "JSON-Dokument", zh: "JSON 文档" },
  "sql-bicimlendirici-analizoru": { tr: "SQL sorgusu", en: "SQL query", de: "SQL-Abfrage", zh: "SQL 查询" },
  "openapi-endpoint-envanteri": { tr: "OpenAPI 3.x JSON", en: "OpenAPI 3.x JSON", de: "OpenAPI-3.x-JSON", zh: "OpenAPI 3.x JSON" },
  "env-dosyasi-denetleyici": { tr: ".env içeriği", en: ".env content", de: ".env-Inhalt", zh: ".env 内容" },
  "unix-izin-hesaplayici": { tr: "İzin (örn. 755 veya rwxr-xr-x)", en: "Permission (e.g. 755 or rwxr-xr-x)", de: "Berechtigung (z. B. 755 oder rwxr-xr-x)", zh: "权限（如 755 或 rwxr-xr-x）" },
  "renk-kontrast-denetleyici": { tr: "Ön plan HEX rengi", en: "Foreground HEX color", de: "Vordergrundfarbe (HEX)", zh: "前景 HEX 颜色" },
  "en-boy-orani-hesaplayici": { tr: "Boyutlar (JSON)", en: "Dimensions (JSON)", de: "Abmessungen (JSON)", zh: "尺寸（JSON）" },
  "css-clamp-olusturucu": { tr: "Akışkan değer ayarları (JSON)", en: "Fluid value settings (JSON)", de: "Fließende Werte (JSON)", zh: "流式值设置（JSON）" },
  "is-gunu-hesaplayici": { tr: "Tarih aralığı (JSON)", en: "Date range (JSON)", de: "Datumsbereich (JSON)", zh: "日期范围（JSON）" },
  "zaman-dilimi-toplanti-planlayici": { tr: "Toplantı ayarları (JSON)", en: "Meeting settings (JSON)", de: "Terminangaben (JSON)", zh: "会议设置（JSON）" },
  "bahsis-hesap-bolusturucu": { tr: "Hesap ayrıntıları (JSON)", en: "Bill details (JSON)", de: "Rechnungsdetails (JSON)", zh: "账单详情（JSON）" },
  "regex-degistirme-laboratuvari": { tr: "Dönüştürülecek metin", en: "Text to transform", de: "Zu ändernder Text", zh: "待转换文本" },
  "markdown-tablo-olusturucu": { tr: "JSON dizisi veya basit CSV", en: "JSON array or simple CSV", de: "JSON-Array oder einfaches CSV", zh: "JSON 数组或简单 CSV" },
  "semver-karsilastirici": { tr: "Sürümler (her satıra bir tane)", en: "Versions (one per line)", de: "Versionen (eine pro Zeile)", zh: "版本（每行一个）" },
};

const secondNames: Partial<Record<string, Record<Locale, string>>> = {
  "json-pointer-gezgini": { tr: "JSON Pointer yolu", en: "JSON Pointer path", de: "JSON-Pointer-Pfad", zh: "JSON Pointer 路径" },
  "renk-kontrast-denetleyici": { tr: "Arka plan HEX rengi", en: "Background HEX color", de: "Hintergrundfarbe (HEX)", zh: "背景 HEX 颜色" },
  "regex-degistirme-laboratuvari": { tr: "1. satır: desen · 2. satır: değiştirme · 3. satır: bayraklar", en: "Line 1: pattern · line 2: replacement · line 3: flags", de: "Zeile 1: Muster · 2: Ersetzung · 3: Flags", zh: "第 1 行：模式 · 第 2 行：替换 · 第 3 行：标志" },
};

function demoFor(slug: string): [string, string] {
  const demos: Record<string, [string, string]> = {
    "json-lines-donusturucu": ['[{"id":1,"state":"ready"},{"id":2,"state":"done"}]', ""],
    "json-pointer-gezgini": ['{"users":[{"name":"Ada","roles":["editor","reviewer"]}]}', "/users/0/roles/1"],
    "sql-bicimlendirici-analizoru": ["select u.id,u.name,count(o.id) as orders from users u left join orders o on o.user_id=u.id where u.active=true group by u.id,u.name order by orders desc;", ""],
    "openapi-endpoint-envanteri": ['{"openapi":"3.1.0","paths":{"/users":{"get":{"operationId":"listUsers","tags":["Users"],"security":[{"bearerAuth":[]}]}},"/users/{id}":{"delete":{"operationId":"deleteUser","deprecated":true}}}}', ""],
    "env-dosyasi-denetleyici": ["APP_ENV=production\nNEXT_PUBLIC_API_BASE=/api\nDATABASE_URL=postgres://demo:demo@localhost/app\nEMPTY_SECRET=\nAPP_ENV=staging", ""],
    "unix-izin-hesaplayici": ["0755", ""],
    "renk-kontrast-denetleyici": ["#172033", "#F7F9FC"],
    "en-boy-orani-hesaplayici": ['{"width":1920,"height":1080,"targetWidth":1280}', ""],
    "css-clamp-olusturucu": ['{"min":16,"max":32,"minViewport":320,"maxViewport":1440,"unit":"px","precision":4}', ""],
    "is-gunu-hesaplayici": ['{"start":"2026-07-01","end":"2026-07-31","holidays":["2026-07-15"],"includeEndpoints":true}', ""],
    "zaman-dilimi-toplanti-planlayici": ['{"date":"2026-07-22T12:00:00Z","zones":["Europe/Istanbul","Europe/Berlin","America/New_York","Asia/Shanghai"]}', ""],
    "bahsis-hesap-bolusturucu": ['{"subtotal":1200,"tax":120,"tipPercent":10,"people":4,"tipOnTax":false,"currency":"TRY"}', ""],
    "regex-degistirme-laboratuvari": ["Ada Lovelace\nGrace Hopper\nAlan Turing", "^(\\w+)\\s+(\\w+)$\n$2, $1\ngm"],
    "markdown-tablo-olusturucu": ['[{"Tool":"JSON Formatter","Local":true},{"Tool":"PDF Merge","Local":true}]', ""],
    "semver-karsilastirici": ["2.0.0\n1.5.0\n2.0.0-beta.2\n2.0.0-beta.11\n1.5.0+build.7", ""],
  };
  return demos[slug] ?? ["", ""];
}

function parseRecord(input: string) { const value: unknown = JSON.parse(input); if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("Expected a JSON object."); return value as Record<string, unknown>; }
function finite(value: unknown, name: string) { const number = Number(value); if (!Number.isFinite(number)) throw new Error(`${name} must be a finite number.`); return number; }
function gcd(a: number, b: number): number { return b ? gcd(b, a % b) : Math.abs(a); }
function hexRgb(value: string) { const raw = value.trim().replace(/^#/u, ""); const full = raw.length === 3 ? raw.split("").map((part) => part + part).join("") : raw; if (!/^[\da-f]{6}$/iu.test(full)) throw new Error("Use a 3- or 6-digit HEX color."); return [0, 2, 4].map((index) => parseInt(full.slice(index, index + 2), 16)); }
function luminance(rgb: number[]) { const linear = rgb.map((channel) => { const value = channel / 255; return value <= .04045 ? value / 12.92 : ((value + .055) / 1.055) ** 2.4; }); return .2126 * linear[0] + .7152 * linear[1] + .0722 * linear[2]; }
type Semver = { raw: string; major: number; minor: number; patch: number; pre: string[] };
function semver(value: string): Semver { const match = /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$/u.exec(value.trim()); if (!match) throw new Error(`Invalid SemVer: ${value}`); return { raw: value.trim(), major: +match[1], minor: +match[2], patch: +match[3], pre: match[4]?.split(".") ?? [] }; }
function compareSemver(a: Semver, b: Semver) { for (const key of ["major", "minor", "patch"] as const) if (a[key] !== b[key]) return a[key] - b[key]; if (!a.pre.length || !b.pre.length) return a.pre.length ? -1 : b.pre.length ? 1 : 0; for (let index = 0; index < Math.max(a.pre.length, b.pre.length); index += 1) { const left = a.pre[index]; const right = b.pre[index]; if (left === undefined) return -1; if (right === undefined) return 1; if (left === right) continue; const ln = /^\d+$/u.test(left); const rn = /^\d+$/u.test(right); if (ln && rn) return Number(left) - Number(right); if (ln !== rn) return ln ? -1 : 1; return left.localeCompare(right); } return 0; }

function processTool(slug: string, input: string, secondary: string, locale: Locale): ToolResult {
  if (!input.trim()) throw new Error(pick(locale, { tr: "Önce girdi sağlayın.", en: "Provide input first.", de: "Geben Sie zuerst Daten ein.", zh: "请先提供输入。" }));
  if (input.length > 500_000) throw new Error("Input exceeds the 500,000 character limit.");
  const metric = (label: Record<Locale, string>, value: string | number): Metric => ({ label: label[locale], value });
  switch (slug) {
    case "json-lines-donusturucu": { const trimmed = input.trim(); if (trimmed.startsWith("[")) { const value: unknown = JSON.parse(trimmed); if (!Array.isArray(value)) throw new Error("JSON input must be an array."); return { output: value.map((item) => JSON.stringify(item)).join("\n"), metrics: [metric({ tr: "Kayıt", en: "Records", de: "Datensätze", zh: "记录" }, value.length), metric({ tr: "Yön", en: "Direction", de: "Richtung", zh: "方向" }, "JSON → NDJSON")] }; } const rows = trimmed.split(/\r?\n/u).filter((line) => line.trim()).map((line, index) => { try { return JSON.parse(line) as unknown; } catch { throw new Error(`Invalid JSON on line ${index + 1}.`); } }); return { output: JSON.stringify(rows, null, 2), metrics: [metric({ tr: "Kayıt", en: "Records", de: "Datensätze", zh: "记录" }, rows.length), metric({ tr: "Yön", en: "Direction", de: "Richtung", zh: "方向" }, "NDJSON → JSON")] }; }
    case "json-pointer-gezgini": { const root: unknown = JSON.parse(input); if (secondary !== "" && !secondary.startsWith("/")) throw new Error("A non-empty JSON Pointer must start with /."); const parts = secondary === "" ? [] : secondary.slice(1).split("/").map((part) => part.replace(/~1/g, "/").replace(/~0/g, "~")); let value: unknown = root; const trace: string[] = ["$ · " + (Array.isArray(value) ? "array" : typeof value)]; parts.forEach((part, index) => { if (value === null || typeof value !== "object" || !(part in value)) throw new Error(`Pointer stops at segment ${index + 1}: ${part}`); value = (value as Record<string, unknown>)[part]; trace.push(`/${parts.slice(0, index + 1).join("/")} · ${Array.isArray(value) ? "array" : value === null ? "null" : typeof value}`); }); return { output: `${trace.join("\n")}\n\nVALUE\n${JSON.stringify(value, null, 2)}`, metrics: [metric({ tr: "Segment", en: "Segments", de: "Segmente", zh: "片段" }, parts.length), metric({ tr: "Sonuç türü", en: "Result type", de: "Ergebnistyp", zh: "结果类型" }, Array.isArray(value) ? "array" : value === null ? "null" : typeof value)] }; }
    case "sql-bicimlendirici-analizoru": { if (/\/\*[\s\S]*$/u.test(input) && !/\*\/[\s\S]*$/u.test(input)) throw new Error("Unclosed SQL block comment."); const keywords = ["select", "from", "left join", "right join", "inner join", "outer join", "join", "where", "group by", "order by", "having", "limit", "offset", "union all", "union", "values", "set", "returning"]; let formatted = input.trim().replace(/\s+/gu, " "); keywords.forEach((word) => { formatted = formatted.replace(new RegExp(`\\s+${word.replace(" ", "\\s+")}\\s+`, "gi"), `\n${word.toUpperCase()} `); }); formatted = formatted.replace(/^\s*(select|update|delete|insert)\b/iu, (word) => word.toUpperCase()); const warnings: string[] = []; if (/\bselect\s+\*/iu.test(input)) warnings.push("REVIEW · SELECT * couples output to schema changes."); if (/\b(?:delete\s+from|update\s+\S+)\b/iu.test(input) && !/\bwhere\b/iu.test(input)) warnings.push("HIGH · UPDATE/DELETE has no WHERE clause."); const statements = input.split(";").filter((part) => part.trim()).length; if (statements > 1) warnings.push("REVIEW · Multiple SQL statements detected."); return { output: `${formatted}${formatted.endsWith(";") ? "" : ";"}\n\nANALYSIS\n${warnings.length ? warnings.join("\n") : "No obvious issue in the selected baseline rules."}\n\nLimit: syntax and query plans are not validated against a database.`, metrics: [metric({ tr: "İfade", en: "Statements", de: "Anweisungen", zh: "语句" }, statements), metric({ tr: "Uyarı", en: "Warnings", de: "Hinweise", zh: "提示" }, warnings.length)] }; }
    case "openapi-endpoint-envanteri": { const spec = parseRecord(input); if (typeof spec.openapi !== "string" || !spec.openapi.startsWith("3.")) throw new Error("Expected an OpenAPI 3.x document."); const paths = spec.paths; if (!paths || typeof paths !== "object" || Array.isArray(paths)) throw new Error("OpenAPI paths object is missing."); const methods = new Set(["get", "post", "put", "patch", "delete", "options", "head", "trace"]); const rows: string[] = ["| Method | Path | operationId | Tags | Security | Deprecated |", "|---|---|---|---|---|---|"]; let secured = 0; let deprecated = 0; Object.entries(paths as Record<string, unknown>).forEach(([path, item]) => { if (!item || typeof item !== "object") return; Object.entries(item as Record<string, unknown>).forEach(([method, operation]) => { if (!methods.has(method) || !operation || typeof operation !== "object") return; const op = operation as Record<string, unknown>; const security = Array.isArray(op.security) ? (op.security.length ? "yes" : "explicit none") : Array.isArray(spec.security) && spec.security.length ? "inherited" : "missing"; if (security === "yes" || security === "inherited") secured += 1; if (op.deprecated === true) deprecated += 1; rows.push(`| ${method.toUpperCase()} | ${path.replace(/\|/g, "\\|")} | ${String(op.operationId ?? "—")} | ${Array.isArray(op.tags) ? op.tags.join(", ") : "—"} | ${security} | ${op.deprecated === true ? "yes" : "no"} |`); }); }); if (rows.length === 2) throw new Error("No HTTP operations were found in paths."); return { output: rows.join("\n"), metrics: [metric({ tr: "Endpoint", en: "Endpoints", de: "Endpunkte", zh: "端点" }, rows.length - 2), metric({ tr: "Güvenlik tanımlı", en: "Secured", de: "Abgesichert", zh: "已声明安全" }, secured), metric({ tr: "Deprecated", en: "Deprecated", de: "Veraltet", zh: "已弃用" }, deprecated)] }; }
    case "env-dosyasi-denetleyici": { const seen = new Set<string>(); const findings: string[] = []; const output: string[] = []; input.split(/\r?\n/u).forEach((line, index) => { const trimmed = line.trim(); if (!trimmed || trimmed.startsWith("#")) return; const match = /^(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)=(.*)$/u.exec(trimmed); if (!match) { findings.push(`LINE ${index + 1} · invalid assignment`); return; } const [, key, raw] = match; if (seen.has(key)) findings.push(`LINE ${index + 1} · duplicate key: ${key}`); seen.add(key); if (/^(?:NEXT_PUBLIC_|VITE_|PUBLIC_)/u.test(key) && /(?:SECRET|TOKEN|PASSWORD|PRIVATE|KEY)/iu.test(key)) findings.push(`HIGH · ${key} may expose a secret to client code`); if (/(?:SECRET|TOKEN|PASSWORD|PRIVATE_KEY|DATABASE_URL)/iu.test(key) && !raw.trim()) findings.push(`REVIEW · ${key} is empty`); if (/^(?:sk-|gh[opusr]_|github_pat_|AKIA)/u.test(raw.replace(/^['"]|['"]$/g, ""))) findings.push(`HIGH · ${key} resembles a live credential`); const visible = /^(?:true|false|\d+(?:\.\d+)?|development|production|test|staging)$/iu.test(raw.trim()); output.push(`${key}=${visible ? raw.trim() : raw.trim() ? "••••••••" : ""}`); }); return { output: `MASKED ENV\n${output.join("\n")}\n\nFINDINGS\n${findings.length ? findings.join("\n") : "No obvious issue in the selected baseline rules."}\n\nLimit: rotate any credential suspected of exposure; this audit cannot prove secrecy.`, metrics: [metric({ tr: "Anahtar", en: "Keys", de: "Schlüssel", zh: "键" }, seen.size), metric({ tr: "Bulgu", en: "Findings", de: "Befunde", zh: "发现" }, findings.length)] }; }
    case "unix-izin-hesaplayici": { const raw = input.trim(); let octal = ""; let symbolic = ""; const bits = [4, 2, 1] as const; if (/^(?:0?[0-7]{3}|[0-7]{4})$/u.test(raw)) { octal = raw.replace(/^0(?=[0-7]{3}$)/u, ""); const access = octal.slice(-3); symbolic = [...access].map((digit) => bits.map((bit, index) => Number(digit) & bit ? "rwx"[index] : "-").join("")).join(""); } else if (/^[r-][w-][x-][r-][w-][x-][r-][w-][x-]$/u.test(raw)) { symbolic = raw; octal = [0, 3, 6].map((start) => bits.reduce((sum, bit, index) => sum + (raw[start + index] !== "-" ? bit : 0), 0)).join(""); } else throw new Error("Use 755, 0755, 4755, or a nine-character rwx value."); const warnings = [octal.endsWith("2") || octal.endsWith("3") || octal.endsWith("6") || octal.endsWith("7") ? "HIGH · writable by others" : "", octal.length === 4 && octal[0] !== "0" ? `REVIEW · special permission digit ${octal[0]}` : ""].filter(Boolean); return { output: `OCTAL\n${octal}\n\nSYMBOLIC\n${symbolic}\n\nOWNER ${symbolic.slice(0, 3)} · GROUP ${symbolic.slice(3, 6)} · OTHER ${symbolic.slice(6)}\n\n${warnings.join("\n") || "No obvious risky bit in the selected baseline rules."}`, metrics: [metric({ tr: "Sayısal", en: "Octal", de: "Oktal", zh: "八进制" }, octal), metric({ tr: "Risk", en: "Risks", de: "Risiken", zh: "风险" }, warnings.length)] }; }
    case "renk-kontrast-denetleyici": { const l1 = luminance(hexRgb(input)); const l2 = luminance(hexRgb(secondary)); const ratio = (Math.max(l1, l2) + .05) / (Math.min(l1, l2) + .05); const verdict = [`Normal text AA: ${ratio >= 4.5 ? "PASS" : "FAIL"}`, `Normal text AAA: ${ratio >= 7 ? "PASS" : "FAIL"}`, `Large text AA: ${ratio >= 3 ? "PASS" : "FAIL"}`, `Large text AAA: ${ratio >= 4.5 ? "PASS" : "FAIL"}`]; return { output: `CONTRAST ${ratio.toFixed(2)}:1\n\n${verdict.join("\n")}\n\nThresholds are mathematical checks; verify the rendered interface and non-text states too.`, metrics: [metric({ tr: "Oran", en: "Ratio", de: "Verhältnis", zh: "比率" }, `${ratio.toFixed(2)}:1`), metric({ tr: "AA normal", en: "AA normal", de: "AA normal", zh: "AA 普通" }, ratio >= 4.5 ? "PASS" : "FAIL")] }; }
    case "en-boy-orani-hesaplayici": { const value = parseRecord(input); const width = finite(value.width, "width"); const height = finite(value.height, "height"); if (width <= 0 || height <= 0 || width > 100_000 || height > 100_000) throw new Error("Dimensions must be between 1 and 100,000."); const divisor = gcd(Math.round(width), Math.round(height)); const lines = [`SOURCE ${width} × ${height}`, `RATIO ${Math.round(width) / divisor}:${Math.round(height) / divisor}`]; if (value.targetWidth !== undefined) { const target = finite(value.targetWidth, "targetWidth"); lines.push(`AT WIDTH ${target} → HEIGHT ${Math.round(target * height / width)}`); } if (value.targetHeight !== undefined) { const target = finite(value.targetHeight, "targetHeight"); lines.push(`AT HEIGHT ${target} → WIDTH ${Math.round(target * width / height)}`); } return { output: lines.join("\n"), metrics: [metric({ tr: "Oran", en: "Ratio", de: "Verhältnis", zh: "比例" }, `${Math.round(width) / divisor}:${Math.round(height) / divisor}`), metric({ tr: "Piksel", en: "Pixels", de: "Pixel", zh: "像素" }, Math.round(width * height).toLocaleString(tag(locale)))] }; }
    case "css-clamp-olusturucu": { const value = parseRecord(input); const min = finite(value.min, "min"); const max = finite(value.max, "max"); const minVw = finite(value.minViewport, "minViewport"); const maxVw = finite(value.maxViewport, "maxViewport"); const unit = typeof value.unit === "string" && /^[a-z%]+$/iu.test(value.unit) ? value.unit : "px"; const precision = Math.max(0, Math.min(6, Math.round(Number(value.precision ?? 4)))); if (max <= min || maxVw <= minVw) throw new Error("Maximum values must be greater than minimum values."); const slope = (max - min) / (maxVw - minVw); const vw = slope * 100; const intercept = min - slope * minVw; const expression = `clamp(${min}${unit}, ${intercept.toFixed(precision)}${unit} + ${vw.toFixed(precision)}vw, ${max}${unit})`; return { output: `${expression}\n\nSLOPE ${slope.toFixed(6)} ${unit}/px\nAT ${minVw}px → ${min}${unit}\nAT ${maxVw}px → ${max}${unit}`, metrics: [metric({ tr: "Minimum", en: "Minimum", de: "Minimum", zh: "最小" }, `${min}${unit}`), metric({ tr: "Maksimum", en: "Maximum", de: "Maximum", zh: "最大" }, `${max}${unit}`)] }; }
    case "is-gunu-hesaplayici": { const value = parseRecord(input); const startText = String(value.start ?? ""); const endText = String(value.end ?? ""); if (!/^\d{4}-\d{2}-\d{2}$/u.test(startText) || !/^\d{4}-\d{2}-\d{2}$/u.test(endText)) throw new Error("Use ISO dates in YYYY-MM-DD form."); const start = new Date(`${startText}T00:00:00Z`); const end = new Date(`${endText}T00:00:00Z`); if (!Number.isFinite(start.valueOf()) || !Number.isFinite(end.valueOf()) || end < start) throw new Error("End date must be on or after start date."); const totalDays = Math.floor((end.valueOf() - start.valueOf()) / 86400000) + 1; if (totalDays > 3660) throw new Error("Date range is limited to 10 years."); const holidays = new Set(Array.isArray(value.holidays) ? value.holidays.map(String) : []); const include = value.includeEndpoints !== false; let business = 0; let weekends = 0; let excludedHolidays = 0; for (let offset = 0; offset < totalDays; offset += 1) { if (!include && (offset === 0 || offset === totalDays - 1)) continue; const date = new Date(start.valueOf() + offset * 86400000); const iso = date.toISOString().slice(0, 10); if (date.getUTCDay() === 0 || date.getUTCDay() === 6) { weekends += 1; continue; } if (holidays.has(iso)) { excludedHolidays += 1; continue; } business += 1; } return { output: `START ${startText}\nEND ${endText}\nBUSINESS DAYS ${business}\nWEEKEND DATES ${weekends}\nEXCLUDED HOLIDAYS ${excludedHolidays}\n\nLimit: verify official holidays and legal deadlines independently.`, metrics: [metric({ tr: "İş günü", en: "Business days", de: "Arbeitstage", zh: "工作日" }, business), metric({ tr: "Takvim günü", en: "Calendar days", de: "Kalendertage", zh: "日历天" }, totalDays)] }; }
    case "zaman-dilimi-toplanti-planlayici": { const value = parseRecord(input); const date = new Date(String(value.date ?? "")); if (!Number.isFinite(date.valueOf())) throw new Error("Use a valid ISO date-time."); const zones = Array.isArray(value.zones) ? value.zones.map(String).slice(0, 12) : []; if (!zones.length) throw new Error("Provide at least one IANA time zone."); const rows = zones.map((zone) => { try { return `${zone.padEnd(28)} ${new Intl.DateTimeFormat(tag(locale), { timeZone: zone, dateStyle: "full", timeStyle: "short", hour12: false }).format(date)}`; } catch { throw new Error(`Unsupported IANA time zone: ${zone}`); } }); return { output: `UTC ${date.toISOString()}\n\n${rows.join("\n")}`, metrics: [metric({ tr: "Bölge", en: "Zones", de: "Zonen", zh: "时区" }, zones.length), metric({ tr: "Kaynak", en: "Source", de: "Quelle", zh: "来源" }, "Intl API")] }; }
    case "bahsis-hesap-bolusturucu": { const value = parseRecord(input); const subtotal = finite(value.subtotal, "subtotal"); const tax = finite(value.tax ?? 0, "tax"); const rate = finite(value.tipPercent ?? 0, "tipPercent"); const people = finite(value.people, "people"); if (subtotal < 0 || tax < 0 || rate < 0 || rate > 100 || !Number.isInteger(people) || people < 1 || people > 1000) throw new Error("Check amounts, tip rate (0–100), and whole-number people count."); const base = value.tipOnTax === true ? subtotal + tax : subtotal; const tip = base * rate / 100; const total = subtotal + tax + tip; const currency = typeof value.currency === "string" ? value.currency.slice(0, 8) : ""; const money = (amount: number) => `${amount.toFixed(2)} ${currency}`.trim(); return { output: `SUBTOTAL ${money(subtotal)}\nTAX ${money(tax)}\nTIP ${money(tip)} (${rate}% on ${value.tipOnTax === true ? "post-tax" : "pre-tax"} base)\nTOTAL ${money(total)}\nPER PERSON ${money(total / people)}\n\nRounding is shown to two decimals; local payment practice may differ.`, metrics: [metric({ tr: "Toplam", en: "Total", de: "Gesamt", zh: "总计" }, money(total)), metric({ tr: "Kişi başı", en: "Per person", de: "Pro Person", zh: "人均" }, money(total / people))] }; }
    case "regex-degistirme-laboratuvari": { if (input.length > 20_000) throw new Error("Regex preview is limited to 20,000 characters."); const [pattern = "", replacement = "", flags = "g"] = secondary.split(/\r?\n/u); if (!pattern || pattern.length > 300) throw new Error("Pattern is required and limited to 300 characters."); if (/\([^)]*[+*][^)]*\)[+*{]/u.test(pattern)) throw new Error("Nested repetition was blocked to reduce catastrophic backtracking risk."); const safeFlags = [...new Set(flags.trim())].join(""); if (!/^[dgimsuvy]*$/u.test(safeFlags)) throw new Error("Unsupported regular-expression flag."); const effectiveFlags = safeFlags.includes("g") ? safeFlags : safeFlags + "g"; const regex = new RegExp(pattern, effectiveFlags); let matches = 0; for (const match of input.matchAll(regex)) { if (match.index === undefined) break; matches += 1; if (matches > 5000) throw new Error("Match limit exceeded (5,000)."); } const output = input.replace(regex, replacement); return { output: `BEFORE\n${input}\n\nAFTER\n${output}`, metrics: [metric({ tr: "Eşleşme", en: "Matches", de: "Treffer", zh: "匹配" }, matches), metric({ tr: "Değişim", en: "Changed", de: "Geändert", zh: "已更改" }, output === input ? "no" : "yes")] }; }
    case "markdown-tablo-olusturucu": { let rows: Record<string, unknown>[]; if (input.trim().startsWith("[")) { const parsed: unknown = JSON.parse(input); if (!Array.isArray(parsed) || parsed.some((item) => !item || typeof item !== "object" || Array.isArray(item))) throw new Error("JSON must be an array of objects."); rows = parsed as Record<string, unknown>[]; } else { const lines = input.trim().split(/\r?\n/u); const headers = lines.shift()?.split(",").map((item) => item.trim()) ?? []; if (!headers.length || lines.some((line) => line.split(",").length !== headers.length)) throw new Error("Simple CSV rows must have the same number of columns."); rows = lines.map((line) => Object.fromEntries(line.split(",").map((item, index) => [headers[index], item.trim()]))); } if (!rows.length || rows.length > 1000) throw new Error("Provide between 1 and 1,000 rows."); const headers = [...new Set(rows.flatMap(Object.keys))].slice(0, 50); const escape = (value: unknown) => String(value ?? "").replace(/\|/g, "\\|").replace(/\r?\n/g, "<br>"); const output = [`| ${headers.map(escape).join(" | ")} |`, `| ${headers.map(() => "---").join(" | ")} |`, ...rows.map((row) => `| ${headers.map((key) => escape(row[key])).join(" | ")} |`)].join("\n"); return { output, metrics: [metric({ tr: "Satır", en: "Rows", de: "Zeilen", zh: "行" }, rows.length), metric({ tr: "Sütun", en: "Columns", de: "Spalten", zh: "列" }, headers.length)] }; }
    case "semver-karsilastirici": { const values = input.split(/\r?\n/u).map((value) => value.trim()).filter(Boolean); if (!values.length || values.length > 500) throw new Error("Provide between 1 and 500 versions."); const parsed = values.map(semver).sort(compareSemver); return { output: `ASCENDING PRECEDENCE\n${parsed.map((value, index) => `${index + 1}. ${value.raw}`).join("\n")}\n\nLOWEST ${parsed[0].raw}\nHIGHEST ${parsed[parsed.length - 1].raw}\n\nBuild metadata does not affect precedence. Compatibility still depends on the package contract.`, metrics: [metric({ tr: "Sürüm", en: "Versions", de: "Versionen", zh: "版本" }, parsed.length), metric({ tr: "Ön sürüm", en: "Prereleases", de: "Vorabversionen", zh: "预发布" }, parsed.filter((value) => value.pre.length).length)] }; }
    default: throw new Error("Unsupported discovery tool.");
  }
}

export function DiscoveryWorkbench({ slug, locale }: { slug: string; locale: Locale }) {
  const l = labels[locale]; const [initialInput, initialSecondary] = demoFor(slug); const [input, setInput] = useState(initialInput); const [secondary, setSecondary] = useState(initialSecondary); const [output, setOutput] = useState(""); const [metrics, setMetrics] = useState<Metric[]>([]); const [notice, setNotice] = useState<ToolNoticeData | null>(null); const [busy, setBusy] = useState(false);
  function reset() { setOutput(""); setMetrics([]); setNotice(null); }
  function loadDemo() { const [nextInput, nextSecondary] = demoFor(slug); setInput(nextInput); setSecondary(nextSecondary); reset(); setNotice({ kind: "info", text: l.demo }); }
  async function run() { setBusy(true); setNotice(null); await new Promise<void>((resolve) => window.setTimeout(resolve, 0)); try { const result = processTool(slug, input, secondary, locale); setOutput(result.output); setMetrics(result.metrics); setNotice(result.notice ?? { kind: "success", text: pick(locale, { tr: "İşlem cihazınızda tamamlandı.", en: "Completed on your device.", de: "Auf Ihrem Gerät abgeschlossen.", zh: "已在您的设备上完成。" }) }); } catch (error) { setOutput(""); setMetrics([]); setNotice({ kind: "error", text: `${l.failed}: ${error instanceof Error ? error.message : String(error)}` }); } finally { setBusy(false); } }
  async function copyOutput() { if (!output) return; try { await navigator.clipboard.writeText(output); setNotice({ kind: "success", text: l.copied }); } catch { setNotice({ kind: "error", text: `${l.failed}: clipboard permission denied` }); } }
  function downloadOutput() { if (!output) return; const url = URL.createObjectURL(new Blob([output], { type: "text/plain;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `bytequant-${slug}.txt`; anchor.click(); window.setTimeout(() => URL.revokeObjectURL(url), 0); setNotice({ kind: "success", text: l.downloaded }); }
  return <section className="workbench" aria-busy={busy}><div className="workbench-toolbar"><div><span className="local-badge">{l.local}</span><strong>{l.privacy}</strong></div><div><button className="demo-button" type="button" onClick={loadDemo}>{l.demo}</button><button className="ghost-button" type="button" onClick={() => { setInput(""); setSecondary(""); reset(); }}>{l.clear}</button></div></div><div className="workbench-grid"><div className="workbench-inputs"><label className="field-label"><span>{inputNames[slug]?.[locale] ?? l.input}</span><textarea value={input} onChange={(event) => { setInput(event.target.value); reset(); }} rows={12} maxLength={500000} spellCheck="false" /><small className="field-counter">{input.length.toLocaleString(tag(locale))} / 500,000</small></label>{secondNames[slug] && <label className="field-label"><span>{secondNames[slug]?.[locale] ?? l.secondary}</span><textarea value={secondary} onChange={(event) => { setSecondary(event.target.value); reset(); }} rows={4} maxLength={20000} spellCheck="false" /></label>}<button type="button" className="primary-button run-button" onClick={() => void run()} disabled={busy}>{busy ? l.running : l.run}<span aria-hidden="true"> →</span></button></div><div className="result-panel" aria-live="polite"><div className="result-header"><span>{l.output}</span><div className="output-actions"><button type="button" onClick={() => void copyOutput()} disabled={!output}>{l.copy}</button><button type="button" onClick={downloadOutput} disabled={!output}>{l.download}</button></div></div>{metrics.length > 0 && <div className="metric-strip">{metrics.map((item) => <div key={item.label}><strong>{item.value}</strong><span>{item.label}</span></div>)}</div>}<pre className={output ? "has-output" : ""} data-agent-output>{output || l.empty}</pre><ToolNotice notice={notice} locale={locale} /></div></div></section>;
}
