"use client";

import { useEffect, useMemo, useState } from "react";
import type { Locale } from "../lib/site";

type Four = { tr: string; en: string; de: string; zh: string };
type Field = { key: string; label: Four; type?: "text" | "number" | "date" | "textarea" | "select"; demo: string; placeholder?: Four; options?: Array<{ value: string; label: Four }> };
type Result = { text: string; metrics?: Array<{ label: string; value: string | number }> };

const L = (locale: Locale, value: Four) => value[locale];
const four = (tr: string, en: string, de: string, zh: string): Four => ({ tr, en, de, zh });
const f = (key: string, label: Four, demo: string, type: Field["type"] = "text", placeholder?: Four, options?: Field["options"]): Field => ({ key, label, demo, type, placeholder, options });

const common = {
  run: four("Cihazımda çalıştır", "Run on my device", "Auf meinem Gerät ausführen", "在我的设备上运行"),
  running: four("İşleniyor…", "Processing…", "Verarbeitung…", "处理中…"),
  demo: four("Örnek veri yükle", "Load example", "Beispiel laden", "加载示例"),
  clear: four("Temizle", "Clear", "Leeren", "清除"),
  copy: four("Kopyala", "Copy", "Kopieren", "复制"),
  download: four("İndir", "Download", "Herunterladen", "下载"),
  output: four("Sonuç", "Result", "Ergebnis", "结果"),
  empty: four("Alanları doldurun; açıklanabilir sonuç burada görünecek.", "Fill the fields; the explainable result will appear here.", "Felder ausfüllen; das nachvollziehbare Ergebnis erscheint hier.", "填写字段；可解释的结果将显示在这里。"),
  error: four("Bu veriler işlenemedi", "These values could not be processed", "Diese Werte konnten nicht verarbeitet werden", "无法处理这些数据"),
  local: four("Tamamlandı · işlem tamamen bu cihazda gerçekleşti", "Complete · processed entirely on this device", "Fertig · vollständig auf diesem Gerät verarbeitet", "完成 · 全部在此设备上处理"),
  needed: four("Lütfen gerekli alanları doldurun.", "Please complete the required fields.", "Bitte füllen Sie die erforderlichen Felder aus.", "请填写必填字段。"),
  copied: four("Sonuç kopyalandı.", "Result copied.", "Ergebnis kopiert.", "结果已复制。"),
};

const label = {
  old: four("İlk değer", "Starting value", "Ausgangswert", "初始值"), next: four("Yeni değer", "New value", "Neuer Wert", "新值"),
  price: four("Liste fiyatı", "List price", "Listenpreis", "标价"), discount: four("İndirim (%)", "Discount (%)", "Rabatt (%)", "折扣 (%)"), vat: four("KDV / vergi (%)", "VAT / tax (%)", "MwSt. / Steuer (%)", "增值税 / 税率 (%)"),
  principal: four("Kredi tutarı", "Loan amount", "Kreditbetrag", "贷款金额"), rate: four("Yıllık faiz (%)", "Annual interest (%)", "Jahreszins (%)", "年利率 (%)"), months: four("Vade (ay)", "Term (months)", "Laufzeit (Monate)", "期限（月）"),
  total: four("Toplam tutar", "Total amount", "Gesamtbetrag", "总金额"), people: four("Kişi sayısı", "Number of people", "Personenzahl", "人数"), weights: four("Pay ağırlıkları (isteğe bağlı)", "Share weights (optional)", "Anteile (optional)", "分摊权重（可选）"),
  start: four("Başlangıç tarihi", "Start date", "Startdatum", "开始日期"), end: four("Bitiş tarihi", "End date", "Enddatum", "结束日期"), birth: four("Doğum tarihi", "Date of birth", "Geburtsdatum", "出生日期"), asof: four("Hesaplama tarihi", "Calculate as of", "Berechnen am", "计算日期"),
  text: four("Metin / liste", "Text / list", "Text / Liste", "文本 / 列表"), count: four("Adet", "Count", "Anzahl", "数量"),
};

function fieldsFor(slug: string): Field[] {
  switch (slug) {
    case "bahsis-hesap-bolusturucu": return [f("subtotal", four("Hesap tutarı", "Bill subtotal", "Rechnungsbetrag", "账单金额"), "1200", "number"), f("tax", four("Vergi / servis tutarı", "Tax / service amount", "Steuer / Servicebetrag", "税费 / 服务费"), "120", "number"), f("tip", four("Bahşiş (%)", "Tip (%)", "Trinkgeld (%)", "小费 (%)"), "10", "number"), f("people", label.people, "4", "number"), f("tipOnTax", four("Bahşiş hesabı", "Tip basis", "Trinkgeldbasis", "小费计算基础"), "no", "select", undefined, [{ value: "no", label: four("Vergi hariç", "Before tax", "Ohne Steuer", "税前") }, { value: "yes", label: four("Vergi dahil", "Including tax", "Mit Steuer", "含税") }])];
    case "en-boy-orani-hesaplayici": return [f("width", four("Genişlik", "Width", "Breite", "宽度"), "1920", "number"), f("height", four("Yükseklik", "Height", "Höhe", "高度"), "1080", "number"), f("target", four("Yeni genişlik", "New width", "Neue Breite", "新宽度"), "1280", "number")];
    case "css-clamp-olusturucu": return [f("min", four("En küçük değer (px)", "Minimum value (px)", "Minimalwert (px)", "最小值 (px)"), "16", "number"), f("max", four("En büyük değer (px)", "Maximum value (px)", "Maximalwert (px)", "最大值 (px)"), "32", "number"), f("minViewport", four("En küçük ekran (px)", "Minimum viewport (px)", "Kleinster Viewport (px)", "最小视口 (px)"), "360", "number"), f("maxViewport", four("En büyük ekran (px)", "Maximum viewport (px)", "Größter Viewport (px)", "最大视口 (px)"), "1440", "number")];
    case "is-gunu-hesaplayici": return [f("start", label.start, "2026-07-01", "date"), f("end", label.end, "2026-07-31", "date"), f("holidays", four("Tatil tarihleri (isteğe bağlı)", "Holiday dates (optional)", "Feiertage (optional)", "节假日日期（可选）"), "2026-07-15", "textarea")];
    case "zaman-dilimi-toplanti-planlayici": return [f("datetime", four("Yerel tarih ve saat", "Local date and time", "Lokales Datum und Uhrzeit", "本地日期和时间"), "2026-07-28T14:00", "text"), f("source", four("Kaynak UTC farkı", "Source UTC offset", "Quell-UTC-Abweichung", "源 UTC 偏移"), "+03:00"), f("targets", four("Hedef UTC farkları", "Target UTC offsets", "Ziel-UTC-Abweichungen", "目标 UTC 偏移"), "+00:00\n+02:00\n+08:00", "textarea")];
    case "yuzde-degisim-hizli-hesaplayici": return [f("old", label.old, "80", "number"), f("next", label.next, "100", "number")];
    case "indirim-kdv-hesaplayici": return [f("price", label.price, "1250", "number"), f("discount", label.discount, "15", "number"), f("vat", label.vat, "20", "number")];
    case "kredi-taksit-hesaplayici": return [f("principal", label.principal, "250000", "number"), f("rate", label.rate, "24", "number"), f("months", label.months, "24", "number")];
    case "kira-paylasim-hesaplayici": return [f("total", label.total, "24000", "number"), f("people", label.people, "3", "number"), f("weights", label.weights, "1,1,1.5", "text", four("Örn. büyük oda için 1.5", "e.g. 1.5 for the larger room", "z. B. 1,5 für das größere Zimmer", "例如大房间填 1.5"))];
    case "tarih-sure-hesaplayici": return [f("start", label.start, "2026-01-01", "date"), f("end", label.end, "2026-07-28", "date")];
    case "yas-hesaplayici": return [f("birth", label.birth, "1995-05-18", "date"), f("asof", label.asof, "2026-07-28", "date")];
    case "tarif-olceklendirici": return [f("ingredients", four("Malzemeler (her satır: miktar birim ad)", "Ingredients (one per line: amount unit name)", "Zutaten (je Zeile: Menge Einheit Name)", "配料（每行：数量 单位 名称）"), "200 g un\n2 adet yumurta\n300 ml süt", "textarea"), f("from", four("Mevcut porsiyon", "Current servings", "Aktuelle Portionen", "当前份数"), "4", "number"), f("to", four("Yeni porsiyon", "New servings", "Neue Portionen", "新份数"), "6", "number")];
    case "maas-saatlik-ucret-donusturucu": return [f("amount", four("Tutar", "Amount", "Betrag", "金额"), "600000", "number"), f("mode", four("Girilen ücret türü", "Input pay period", "Eingabezeitraum", "输入薪资周期"), "annual", "select", undefined, [{ value: "annual", label: four("Yıllık", "Annual", "Jährlich", "年薪") }, { value: "monthly", label: four("Aylık", "Monthly", "Monatlich", "月薪") }, { value: "hourly", label: four("Saatlik", "Hourly", "Stündlich", "时薪") }]), f("hours", four("Haftalık çalışma saati", "Hours per week", "Wochenstunden", "每周工时"), "40", "number"), f("weeks", four("Yıllık çalışma haftası", "Working weeks per year", "Arbeitswochen pro Jahr", "每年工作周数"), "52", "number")];
    case "birim-fiyat-karsilastirici": return [f("priceA", four("A fiyatı", "Option A price", "Preis A", "A 价格"), "89.90", "number"), f("sizeA", four("A miktarı", "Option A quantity", "Menge A", "A 数量"), "750", "number"), f("priceB", four("B fiyatı", "Option B price", "Preis B", "B 价格"), "124.90", "number"), f("sizeB", four("B miktarı", "Option B quantity", "Menge B", "B 数量"), "1200", "number")];
    case "rastgele-takim-olusturucu": return [f("names", four("İsimler (satır başına bir kişi)", "Names (one per line)", "Namen (einer pro Zeile)", "姓名（每行一个）"), "Ada\nCan\nDeniz\nEce\nMert\nSelin", "textarea"), f("teams", four("Takım sayısı", "Number of teams", "Teamanzahl", "小组数量"), "2", "number"), f("seed", four("Tekrar anahtarı", "Reproducible seed", "Wiederholungsschlüssel", "可复现种子"), "bytequant", "text")];
    case "kelime-sikligi-analizoru": return [f("text", label.text, "Güvenli araçlar tarayıcıda çalışır. Tarayıcıda çalışan araçlar veriyi cihazda tutar.", "textarea"), f("count", four("Gösterilecek sözcük", "Words to show", "Anzuzeigende Wörter", "显示词数"), "10", "number")];
    case "okunabilirlik-on-analizi": return [f("text", label.text, "Bu örnek metin kısa cümleler kullanır. Her fikir kendi cümlesinde açıklanır. Teknik terimler gerektiğinde tanımlanır.", "textarea")];
    case "e-posta-listesi-temizleyici": return [f("text", label.text, "Ada <ada@example.com>; TEST@EXAMPLE.COM\nada@example.com\nyanlis@adres", "textarea")];
    case "dosya-adi-guvenli-donusturucu": return [f("text", four("Başlıklar (satır başına bir tane)", "Titles (one per line)", "Titel (einer pro Zeile)", "标题（每行一个）"), "2026 Raporu: Satış / Büyüme?\nMüşteri Notları * Final", "textarea")];
    case "query-string-olusturucu": return [f("base", four("Temel URL (isteğe bağlı)", "Base URL (optional)", "Basis-URL (optional)", "基础 URL（可选）"), "https://example.com/search"), f("pairs", four("Parametreler (anahtar=değer)", "Parameters (key=value)", "Parameter (Schlüssel=Wert)", "参数（键=值）"), "q=gizlilik araçları\nlang=tr\npage=2", "textarea")];
    case "http-durum-kodu-rehberi": return [f("code", four("HTTP durum kodu", "HTTP status code", "HTTP-Statuscode", "HTTP 状态码"), "429", "number")];
    case "uuid-toplu-dogrulayici": return [f("text", four("UUID listesi", "UUID list", "UUID-Liste", "UUID 列表"), "550e8400-e29b-41d4-a716-446655440000\n6ba7b810-9dad-11d1-80b4-00c04fd430c8\ninvalid", "textarea")];
    case "csv-sutun-secici": return [f("csv", four("CSV verisi", "CSV data", "CSV-Daten", "CSV 数据"), "ad,email,sehir\nAda,ada@example.com,Ankara\nCan,can@example.com,İzmir", "textarea"), f("columns", four("Sütunlar (virgülle)", "Columns (comma separated)", "Spalten (kommagetrennt)", "列（逗号分隔）"), "ad,sehir")];
    case "json-ornek-veri-olusturucu": return [f("schema", four("Alanlar (ad:tür)", "Fields (name:type)", "Felder (Name:Typ)", "字段（名称:类型）"), "id:uuid\nname:name\nactive:boolean\nscore:number", "textarea"), f("count", label.count, "3", "number")];
    case "json-yol-listeleyici": return [f("json", four("JSON", "JSON", "JSON", "JSON"), "{\"user\":{\"name\":\"Ada\",\"roles\":[\"editor\"]},\"active\":true}", "textarea")];
    case "checksum-karsilastirici": return [f("text", four("Metin / kod", "Text / code", "Text / Code", "文本 / 代码"), "ByteQuant local integrity", "textarea"), f("expected", four("Beklenen SHA-256 (isteğe bağlı)", "Expected SHA-256 (optional)", "Erwartetes SHA-256 (optional)", "预期 SHA-256（可选）"), "")];
    case "sri-hash-olusturucu": return [f("text", four("Kaynak metni / kod", "Resource text / code", "Ressourcentext / Code", "资源文本 / 代码"), "console.log('ByteQuant');", "textarea"), f("algorithm", four("Algoritma", "Algorithm", "Algorithmus", "算法"), "SHA-384", "select", undefined, ["SHA-256", "SHA-384", "SHA-512"].map((value) => ({ value, label: four(value, value, value, value) })))];
    case "csp-direktif-birlestirici": return [f("first", four("Birinci CSP", "First CSP", "Erste CSP", "第一份 CSP"), "default-src 'self'; img-src 'self' data:; object-src 'none'", "textarea"), f("second", four("İkinci CSP", "Second CSP", "Zweite CSP", "第二份 CSP"), "script-src 'self'; img-src https://images.example; base-uri 'self'", "textarea")];
    case "ajan-girdi-cikti-sozlesmesi": return [f("goal", four("Ajanın hedefi", "Agent goal", "Agentenziel", "智能体目标"), "Müşteri notlarını kişisel verileri çıkardıktan sonra görev listesine dönüştür.", "textarea"), f("input", four("Beklenen girdi", "Expected input", "Erwartete Eingabe", "预期输入"), "UTF-8 düz metin; en fazla 50.000 karakter"), f("output", four("Beklenen çıktı", "Expected output", "Erwartete Ausgabe", "预期输出"), "JSON: tasks[{title, owner?, dueDate?}], warnings[]")];
    default: return [f("text", label.text, "Zeynep\nAhmet\nZeynep\nBerna", "textarea")];
  }
}

function number(values: Record<string, string>, key: string, min = -Infinity) {
  const value = Number(values[key]);
  if (!Number.isFinite(value) || value < min) throw new Error(`${key}: invalid number`);
  return value;
}
function format(locale: Locale, value: number, digits = 2) { return new Intl.NumberFormat({ tr: "tr-TR", en: "en-US", de: "de-DE", zh: "zh-CN" }[locale], { maximumFractionDigits: digits }).format(value); }
function parseDate(value: string) { const date = new Date(`${value}T12:00:00`); if (Number.isNaN(date.getTime())) throw new Error("invalid date"); return date; }
function seeded(value: string) { let hash = 2166136261; for (const char of value) hash = Math.imul(hash ^ char.charCodeAt(0), 16777619); return () => ((hash = Math.imul(hash ^ (hash >>> 15), 2246822519)) >>> 0) / 4294967296; }
function csvLine(line: string) { const cells: string[] = []; let cell = ""; let quoted = false; for (let i = 0; i < line.length; i += 1) { const char = line[i]; if (char === '"') { if (quoted && line[i + 1] === '"') { cell += '"'; i += 1; } else quoted = !quoted; } else if (char === "," && !quoted) { cells.push(cell); cell = ""; } else cell += char; } cells.push(cell); return cells; }
function csvCell(value: string) { return /[",\n]/.test(value) ? `"${value.replace(/"/g, '""')}"` : value; }
function hex(buffer: ArrayBuffer) { return [...new Uint8Array(buffer)].map((value) => value.toString(16).padStart(2, "0")).join(""); }
function base64(buffer: ArrayBuffer) { let binary = ""; new Uint8Array(buffer).forEach((byte) => { binary += String.fromCharCode(byte); }); return btoa(binary); }

async function process(slug: string, values: Record<string, string>, locale: Locale): Promise<Result> {
  const t = (tr: string, en: string, de: string, zh: string) => L(locale, four(tr, en, de, zh));
  if (slug === "bahsis-hesap-bolusturucu") { const subtotal = number(values, "subtotal", 0), tax = number(values, "tax", 0), tipRate = number(values, "tip", 0), people = Math.round(number(values, "people", 1)); const base = values.tipOnTax === "yes" ? subtotal + tax : subtotal; const tip = base * tipRate / 100; const total = subtotal + tax + tip; return { text: `${t("Ara toplam", "Subtotal", "Zwischensumme", "小计")}: ${format(locale, subtotal)}\n${t("Vergi / servis", "Tax / service", "Steuer / Service", "税费 / 服务费")}: ${format(locale, tax)}\n${t("Bahşiş", "Tip", "Trinkgeld", "小费")}: ${format(locale, tip)}\n${t("Genel toplam", "Grand total", "Gesamtsumme", "总计")}: ${format(locale, total)}\n${t("Kişi başı", "Per person", "Pro Person", "每人")}: ${format(locale, total / people)}\n\n${t("Bahşiş tabanı", "Tip basis", "Trinkgeldbasis", "小费计算基础")}: ${values.tipOnTax === "yes" ? t("vergi dahil", "including tax", "mit Steuer", "含税") : t("vergi hariç", "before tax", "ohne Steuer", "税前")}`, metrics: [{ label: t("Kişi başı", "Per person", "Pro Person", "每人"), value: format(locale, total / people) }] }; }
  if (slug === "en-boy-orani-hesaplayici") { const width = number(values, "width", 1), height = number(values, "height", 1), target = number(values, "target", 1); const gcd = (a: number, b: number): number => b ? gcd(b, a % b) : a; const divisor = gcd(Math.round(width), Math.round(height)); return { text: `${t("Oran", "Ratio", "Verhältnis", "比例")}: ${Math.round(width / divisor)}:${Math.round(height / divisor)}\n${t("Yeni boyut", "New size", "Neue Größe", "新尺寸")}: ${format(locale, target, 0)} × ${format(locale, target * height / width, 0)} px` }; }
  if (slug === "css-clamp-olusturucu") { const min = number(values, "min"), max = number(values, "max"), minV = number(values, "minViewport", 1), maxV = number(values, "maxViewport", minV + .001); if (max <= min || maxV <= minV) throw new Error(t("En büyük değerler en küçük değerlerden büyük olmalıdır.", "Maximum values must exceed minimum values.", "Maximalwerte müssen größer als Minimalwerte sein.", "最大值必须大于最小值。")); const slope = (max - min) / (maxV - minV) * 100, intercept = min - slope * minV / 100; return { text: `clamp(${format(locale, min / 16, 4)}rem, ${format(locale, intercept / 16, 4)}rem + ${format(locale, slope, 4)}vw, ${format(locale, max / 16, 4)}rem)\n\n/* ${min}px @ ${minV}px → ${max}px @ ${maxV}px */` }; }
  if (slug === "is-gunu-hesaplayici") { const start = parseDate(values.start), end = parseDate(values.end); if (end < start) throw new Error(t("Bitiş tarihi başlangıçtan önce olamaz.", "End date cannot precede start date.", "Enddatum darf nicht vor dem Startdatum liegen.", "结束日期不能早于开始日期。")); const holidays = new Set(values.holidays.split(/\s+/).filter(Boolean)); let business = 0, weekends = 0, holidayCount = 0; for (const cursor = new Date(start); cursor <= end; cursor.setDate(cursor.getDate() + 1)) { const iso = cursor.toISOString().slice(0, 10); if (cursor.getDay() === 0 || cursor.getDay() === 6) weekends++; else if (holidays.has(iso)) holidayCount++; else business++; } return { text: `${t("İş günü", "Business days", "Arbeitstage", "工作日")}: ${business}\n${t("Hafta sonu", "Weekend days", "Wochenendtage", "周末天数")}: ${weekends}\n${t("Hariç tutulan tatil", "Excluded holidays", "Ausgeschlossene Feiertage", "排除的节假日")}: ${holidayCount}` }; }
  if (slug === "zaman-dilimi-toplanti-planlayici") { const offset = (value: string) => { const match = /^([+-])(\d{2}):(\d{2})$/.exec(value.trim()); if (!match) throw new Error(t("UTC farkını +03:00 biçiminde yazın.", "Write UTC offsets as +03:00.", "UTC-Abweichung als +03:00 schreiben.", "请以 +03:00 格式填写 UTC 偏移。")); return (match[1] === "-" ? -1 : 1) * (Number(match[2]) * 60 + Number(match[3])); }; const local = new Date(values.datetime); if (Number.isNaN(local.getTime())) throw new Error("invalid date"); const utc = local.getTime() - offset(values.source) * 60000; const targets = values.targets.split(/\r?\n|,/).map((v) => v.trim()).filter(Boolean); return { text: targets.map((target) => { const date = new Date(utc + offset(target) * 60000); return `UTC${target}: ${date.toISOString().slice(0, 16).replace("T", " ")}`; }).join("\n") + `\n\n${t("Yaz saati uygulaması sabit UTC farklarında otomatik izlenmez; toplantı gününde doğrulayın.", "Fixed UTC offsets do not track daylight-saving changes; verify on the meeting date.", "Feste UTC-Abweichungen berücksichtigen keine Sommerzeit; am Termin prüfen.", "固定 UTC 偏移不会自动跟踪夏令时；请在会议日期再次确认。")}` }; }
  if (slug === "yuzde-degisim-hizli-hesaplayici") { const a = number(values, "old"); const b = number(values, "next"); if (a === 0) throw new Error(t("İlk değer sıfır olamaz.", "Starting value cannot be zero.", "Der Ausgangswert darf nicht null sein.", "初始值不能为零。")); const diff = b - a; const pct = diff / Math.abs(a) * 100; return { text: `${t("Değişim", "Change", "Änderung", "变化")}: ${format(locale, pct)}%\n${t("Mutlak fark", "Absolute difference", "Absolute Differenz", "绝对差值")}: ${format(locale, diff)}\n${t("Yön", "Direction", "Richtung", "方向")}: ${pct >= 0 ? t("artış", "increase", "Anstieg", "增加") : t("azalış", "decrease", "Rückgang", "减少")}`, metrics: [{ label: "%", value: `${format(locale, pct)}%` }] }; }
  if (slug === "indirim-kdv-hesaplayici") { const price = number(values, "price", 0), discount = number(values, "discount", 0), vat = number(values, "vat", 0); const saved = price * discount / 100, base = price - saved, tax = base * vat / 100, total = base + tax; return { text: `${t("Liste fiyatı", "List price", "Listenpreis", "标价")}: ${format(locale, price)}\n${t("İndirim", "Discount", "Rabatt", "折扣")}: -${format(locale, saved)}\n${t("Vergi matrahı", "Tax base", "Steuerbasis", "计税基础")}: ${format(locale, base)}\n${t("Vergi", "Tax", "Steuer", "税额")}: ${format(locale, tax)}\n${t("Ödenecek toplam", "Total due", "Endsumme", "应付总额")}: ${format(locale, total)}`, metrics: [{ label: t("Toplam", "Total", "Summe", "总额"), value: format(locale, total) }] }; }
  if (slug === "kredi-taksit-hesaplayici") { const p = number(values, "principal", 0), months = Math.round(number(values, "months", 1)), monthly = number(values, "rate", 0) / 1200; const payment = monthly === 0 ? p / months : p * monthly * Math.pow(1 + monthly, months) / (Math.pow(1 + monthly, months) - 1); const total = payment * months; return { text: `${t("Aylık taksit", "Monthly payment", "Monatsrate", "月供")}: ${format(locale, payment)}\n${t("Toplam geri ödeme", "Total repayment", "Gesamtrückzahlung", "总还款额")}: ${format(locale, total)}\n${t("Toplam faiz", "Total interest", "Gesamtzins", "总利息")}: ${format(locale, total - p)}\n\n${t("Not: Bu bir simülasyondur; ücret, sigorta ve değişken oranları içermez.", "Note: This is a simulation; fees, insurance, and variable rates are excluded.", "Hinweis: Simulation ohne Gebühren, Versicherungen und variable Zinsen.", "注意：这是模拟结果，不含手续费、保险和浮动利率。")}` }; }
  if (slug === "kira-paylasim-hesaplayici") { const total = number(values, "total", 0), people = Math.round(number(values, "people", 1)); const weights = values.weights.trim() ? values.weights.split(/[;,\s]+/).map(Number) : Array.from({ length: people }, () => 1); if (weights.length !== people || weights.some((v) => !Number.isFinite(v) || v <= 0)) throw new Error(t("Ağırlık sayısı kişi sayısına eşit ve pozitif olmalıdır.", "Weights must be positive and match the number of people.", "Anteile müssen positiv sein und zur Personenzahl passen.", "权重必须为正数且与人数一致。")); const sum = weights.reduce((a, b) => a + b, 0); return { text: weights.map((w, i) => `${t("Kişi", "Person", "Person", "人员")} ${i + 1}: ${format(locale, total * w / sum)} (${format(locale, w / sum * 100, 1)}%)`).join("\n") }; }
  if (slug === "tarih-sure-hesaplayici") { const a = parseDate(values.start), b = parseDate(values.end); const days = Math.round((b.getTime() - a.getTime()) / 86400000); return { text: `${t("Takvim günü farkı", "Calendar-day difference", "Kalendertage", "日历天差")}: ${days}\n${t("Hafta", "Weeks", "Wochen", "周")}: ${format(locale, days / 7)}\n${t("Yaklaşık ay", "Approximate months", "Ungefähre Monate", "约月数")}: ${format(locale, days / 30.4375)}` }; }
  if (slug === "yas-hesaplayici") { const birth = parseDate(values.birth), at = parseDate(values.asof); if (at < birth) throw new Error(t("Hesaplama tarihi doğum tarihinden önce olamaz.", "Calculation date cannot precede date of birth.", "Berechnungsdatum darf nicht vor dem Geburtsdatum liegen.", "计算日期不能早于出生日期。")); let years = at.getFullYear() - birth.getFullYear(), months = at.getMonth() - birth.getMonth(), days = at.getDate() - birth.getDate(); if (days < 0) { months--; days += new Date(at.getFullYear(), at.getMonth(), 0).getDate(); } if (months < 0) { years--; months += 12; } return { text: `${years} ${t("yıl", "years", "Jahre", "年")}, ${months} ${t("ay", "months", "Monate", "月")}, ${days} ${t("gün", "days", "Tage", "天")}` }; }
  if (slug === "tarif-olceklendirici") { const from = number(values, "from", .01), to = number(values, "to", .01), ratio = to / from; const lines = values.ingredients.split(/\r?\n/).filter(Boolean).map((line) => line.replace(/^([\d.,]+)/, (raw) => format(locale, Number(raw.replace(",", ".")) * ratio))); return { text: `${t("Ölçek", "Scale", "Faktor", "比例")}: ×${format(locale, ratio)}\n\n${lines.join("\n")}` }; }
  if (slug === "maas-saatlik-ucret-donusturucu") { const amount = number(values, "amount", 0), hours = number(values, "hours", .1), weeks = number(values, "weeks", 1); const annual = values.mode === "annual" ? amount : values.mode === "monthly" ? amount * 12 : amount * hours * weeks; return { text: `${t("Yıllık brüt", "Annual gross", "Jahresbrutto", "年薪")}: ${format(locale, annual)}\n${t("Aylık brüt", "Monthly gross", "Monatsbrutto", "月薪")}: ${format(locale, annual / 12)}\n${t("Saatlik brüt", "Hourly gross", "Stundenbrutto", "时薪")}: ${format(locale, annual / hours / weeks)}\n\n${t("Vergi ve yan haklar dahil değildir.", "Taxes and benefits are not included.", "Steuern und Zusatzleistungen sind nicht enthalten.", "不包含税费和福利。")}` }; }
  if (slug === "birim-fiyat-karsilastirici") { const a = number(values, "priceA", 0) / number(values, "sizeA", .0001), b = number(values, "priceB", 0) / number(values, "sizeB", .0001); const winner = a <= b ? "A" : "B"; return { text: `A: ${format(locale, a, 4)} / ${t("birim", "unit", "Einheit", "单位")}\nB: ${format(locale, b, 4)} / ${t("birim", "unit", "Einheit", "单位")}\n${t("Daha avantajlı", "Better value", "Günstiger", "更划算")}: ${winner}\n${t("Birim farkı", "Unit difference", "Einheitsdifferenz", "单价差")}: ${format(locale, Math.abs(a - b), 4)}` }; }
  if (slug === "rastgele-takim-olusturucu") { const names = [...new Set(values.names.split(/\r?\n/).map((v) => v.trim()).filter(Boolean))], teams = Math.round(number(values, "teams", 2)); if (teams > names.length || teams > 20) throw new Error(t("Takım sayısı isim sayısını aşmamalı ve en fazla 20 olmalıdır.", "Team count must not exceed names and is limited to 20.", "Teamzahl darf Namen nicht übersteigen und ist auf 20 begrenzt.", "小组数不能超过人数，最多为 20。")); const random = seeded(values.seed || "bytequant"); for (let i = names.length - 1; i > 0; i--) { const j = Math.floor(random() * (i + 1)); [names[i], names[j]] = [names[j], names[i]]; } return { text: Array.from({ length: teams }, (_, i) => `${t("TAKIM", "TEAM", "TEAM", "小组")} ${i + 1}\n${names.filter((_, n) => n % teams === i).map((v) => `- ${v}`).join("\n")}`).join("\n\n") }; }
  if (slug === "liste-siralama-temizleme") { const lines = values.text.split(/\r?\n/).map((v) => v.trim()).filter(Boolean); const unique = [...new Map(lines.map((v) => [v.toLocaleLowerCase(locale), v])).values()].sort(new Intl.Collator(locale, { numeric: true, sensitivity: "base" }).compare); return { text: unique.join("\n"), metrics: [{ label: t("Silinen tekrar", "Duplicates removed", "Entfernte Duplikate", "移除重复项"), value: lines.length - unique.length }] }; }
  if (slug === "kelime-sikligi-analizoru") { const words = values.text.toLocaleLowerCase(locale).match(/[\p{L}\p{N}][\p{L}\p{N}'’-]*/gu) ?? []; const counts = new Map<string, number>(); words.forEach((w) => counts.set(w, (counts.get(w) ?? 0) + 1)); const top = [...counts].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0], locale)).slice(0, Math.min(100, Math.round(number(values, "count", 1)))); return { text: top.map(([word, count], i) => `${String(i + 1).padStart(2, "0")}. ${word} — ${count} (${format(locale, count / words.length * 100, 1)}%)`).join("\n"), metrics: [{ label: t("Toplam sözcük", "Total words", "Wörter gesamt", "总词数"), value: words.length }, { label: t("Benzersiz", "Unique", "Einzigartig", "唯一词"), value: counts.size }] }; }
  if (slug === "okunabilirlik-on-analizi") { const sentences = values.text.split(/(?<=[.!?。！？])\s+/).filter(Boolean), paragraphs = values.text.split(/\n\s*\n/).filter(Boolean), words = values.text.match(/[\p{L}\p{N}]+/gu) ?? []; const long = sentences.filter((s) => (s.match(/[\p{L}\p{N}]+/gu) ?? []).length > 24); return { text: `${t("Cümle", "Sentences", "Sätze", "句子")}: ${sentences.length}\n${t("Ortalama sözcük/cümle", "Average words/sentence", "Ø Wörter/Satz", "平均每句词数")}: ${format(locale, words.length / Math.max(1, sentences.length), 1)}\n${t("Yoğun paragraf (>120 sözcük)", "Dense paragraphs (>120 words)", "Dichte Absätze (>120 Wörter)", "密集段落（>120词）")}: ${paragraphs.filter((p) => (p.match(/[\p{L}\p{N}]+/gu) ?? []).length > 120).length}\n${t("Uzun cümle", "Long sentences", "Lange Sätze", "长句")}: ${long.length}\n\n${long.length ? long.map((s, i) => `${i + 1}. ${s}`).join("\n") : t("Belirgin uzun cümle bulunmadı.", "No clearly long sentence was found.", "Keine auffällig langen Sätze gefunden.", "未发现明显长句。")}` }; }
  if (slug === "e-posta-listesi-temizleyici") { const matches = values.text.match(/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/g) ?? []; const unique = [...new Set(matches.map((v) => v.toLocaleLowerCase("en-US")))].sort(); return { text: unique.join("\n"), metrics: [{ label: t("Geçerli benzersiz adres", "Valid unique addresses", "Gültige eindeutige Adressen", "有效唯一地址"), value: unique.length }, { label: t("Tekrar", "Duplicates", "Duplikate", "重复项"), value: matches.length - unique.length }] }; }
  if (slug === "dosya-adi-guvenli-donusturucu") { const reserved = /^(con|prn|aux|nul|com[1-9]|lpt[1-9])$/i; const safe = values.text.split(/\r?\n/).filter(Boolean).map((line) => { let value = line.normalize("NFKC").replace(/[<>:"/\\|?*\u0000-\u001F]/g, "-").replace(/[. ]+$/g, "").replace(/\s+/g, " ").trim().slice(0, 120); if (reserved.test(value)) value = `_${value}`; return value || "untitled"; }); return { text: safe.join("\n") }; }
  if (slug === "query-string-olusturucu") { const params = new URLSearchParams(); values.pairs.split(/\r?\n/).filter(Boolean).forEach((line) => { const index = line.indexOf("="); if (index < 1) throw new Error(t("Her parametreyi anahtar=değer biçiminde yazın.", "Write every parameter as key=value.", "Jeden Parameter als Schlüssel=Wert schreiben.", "请将每个参数写成 键=值。")); params.append(line.slice(0, index).trim(), line.slice(index + 1).trim()); }); const query = params.toString(); return { text: values.base.trim() ? `${values.base.trim()}${values.base.includes("?") ? "&" : "?"}${query}` : query }; }
  if (slug === "http-durum-kodu-rehberi") { const code = Math.round(number(values, "code", 100)); const known: Record<number, [string, string]> = { 200: ["OK", "Response succeeded; validate the payload and caching rules."], 201: ["Created", "A resource was created; expose its location or identifier."], 204: ["No Content", "Success without a body; clients must not expect JSON."], 301: ["Moved Permanently", "Update internal links and verify the canonical destination."], 304: ["Not Modified", "The cached representation is still valid."], 400: ["Bad Request", "Validate syntax, required fields, and content type."], 401: ["Unauthorized", "Authentication is missing or invalid; do not confuse it with authorization."], 403: ["Forbidden", "Identity may be known, but access is not allowed."], 404: ["Not Found", "Check the route, identifier, deployment, and intended indexing behavior."], 409: ["Conflict", "The request conflicts with current state; provide a recoverable action."], 422: ["Unprocessable Content", "Syntax is valid but field-level validation failed."], 429: ["Too Many Requests", "Respect Retry-After and use bounded exponential backoff."], 500: ["Internal Server Error", "Log a request ID, protect details, and retry only when safe."], 502: ["Bad Gateway", "An upstream response failed; inspect gateway and dependency health."], 503: ["Service Unavailable", "Service is temporarily unavailable; use Retry-After when known."] }; const entry = known[code]; if (!entry) throw new Error(t("Bu kod için ayrıntılı kayıt yok; 100–599 aralığında bilinen bir kod girin.", "No detailed record exists for this code; enter a known code from 100–599.", "Für diesen Code gibt es keinen Detaildatensatz; bekannten Code zwischen 100 und 599 eingeben.", "没有此代码的详细记录；请输入 100–599 范围内的已知代码。")); return { text: `${code} ${entry[0]}\n\n${entry[1]}\n\n${t("Not: Durum kodu tek başına güvenlik veya içerik doğruluğu kanıtı değildir.", "Note: A status code alone does not prove security or content correctness.", "Hinweis: Ein Statuscode allein beweist weder Sicherheit noch inhaltliche Richtigkeit.", "注意：状态码本身不能证明安全性或内容正确性。")}` }; }
  if (slug === "uuid-toplu-dogrulayici") { const lines = values.text.split(/\r?\n/).map((v) => v.trim()).filter(Boolean); const seen = new Set<string>(); let valid = 0; const output = lines.map((value) => { const match = /^([0-9a-f]{8})-([0-9a-f]{4})-([1-8][0-9a-f]{3})-([89ab][0-9a-f]{3})-([0-9a-f]{12})$/i.exec(value); const duplicate = seen.has(value.toLowerCase()); seen.add(value.toLowerCase()); if (match) valid++; return `${match ? "✓" : "×"} ${value}${match ? ` · v${match[3][0]}${duplicate ? ` · ${t("tekrar", "duplicate", "Duplikat", "重复")}` : ""}` : ` · ${t("geçersiz biçim", "invalid format", "ungültiges Format", "格式无效")}`}`; }); return { text: output.join("\n"), metrics: [{ label: t("Geçerli", "Valid", "Gültig", "有效"), value: valid }, { label: t("Geçersiz", "Invalid", "Ungültig", "无效"), value: lines.length - valid }] }; }
  if (slug === "csv-sutun-secici") { const rows = values.csv.split(/\r?\n/).filter(Boolean).map(csvLine), headers = rows[0] ?? [], wanted = values.columns.split(",").map((v) => v.trim()).filter(Boolean), indexes = wanted.map((name) => headers.indexOf(name)); if (!rows.length || indexes.some((i) => i < 0)) throw new Error(t("İstenen sütunlardan en az biri başlık satırında bulunamadı.", "At least one requested column was not found in the header row.", "Mindestens eine gewünschte Spalte fehlt in der Kopfzeile.", "标题行中未找到至少一个所需列。")); return { text: rows.map((row) => indexes.map((i) => csvCell(row[i] ?? "")).join(",")).join("\n"), metrics: [{ label: t("Veri satırı", "Data rows", "Datenzeilen", "数据行"), value: Math.max(0, rows.length - 1) }, { label: t("Sütun", "Columns", "Spalten", "列"), value: wanted.length }] }; }
  if (slug === "json-ornek-veri-olusturucu") { const specs = values.schema.split(/\r?\n/).filter(Boolean).map((line) => { const [name, type = "string"] = line.split(":").map((v) => v.trim()); if (!name) throw new Error("field name"); return { name, type }; }); const count = Math.min(50, Math.round(number(values, "count", 1))); const data = Array.from({ length: count }, (_, index) => Object.fromEntries(specs.map(({ name, type }) => [name, type === "number" ? index + 1 : type === "boolean" ? index % 2 === 0 : type === "uuid" ? `00000000-0000-4000-8000-${String(index + 1).padStart(12, "0")}` : type === "date" ? new Date(Date.UTC(2026, 0, index + 1)).toISOString().slice(0, 10) : type === "name" ? ["Ada", "Can", "Deniz", "Ece"][index % 4] : `${name}-${index + 1}`]))); return { text: JSON.stringify(data, null, 2), metrics: [{ label: t("Kayıt", "Records", "Datensätze", "记录"), value: count }, { label: t("Alan", "Fields", "Felder", "字段"), value: specs.length }] }; }
  if (slug === "json-yol-listeleyici") { const data: unknown = JSON.parse(values.json); const rows: string[] = []; const walk = (value: unknown, path: string) => { if (Array.isArray(value)) { if (!value.length) rows.push(`${path} · array(empty)`); else value.forEach((item, i) => walk(item, `${path}[${i}]`)); } else if (value && typeof value === "object") { const entries = Object.entries(value); if (!entries.length) rows.push(`${path} · object(empty)`); else entries.forEach(([key, item]) => walk(item, path ? `${path}.${key}` : key)); } else rows.push(`${path || "$"} · ${value === null ? "null" : typeof value} · ${String(value)}`); }; walk(data, ""); return { text: rows.join("\n"), metrics: [{ label: t("Yaprak yol", "Leaf paths", "Blattpfade", "叶路径"), value: rows.length }] }; }
  if (slug === "checksum-karsilastirici") { const digest = hex(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(values.text))); const expected = values.expected.trim().toLowerCase().replace(/^sha256[:-]?/, ""); let same = expected.length === digest.length && expected.length > 0; let mismatch = 0; for (let i = 0; i < digest.length; i++) mismatch |= digest.charCodeAt(i) ^ (expected.charCodeAt(i) || 0); same = same && mismatch === 0; return { text: `SHA-256\n${digest}${expected ? `\n\n${t("Karşılaştırma", "Comparison", "Vergleich", "比较")}: ${same ? "MATCH ✓" : "MISMATCH ×"}` : ""}` }; }
  if (slug === "sri-hash-olusturucu") { const algorithm = ["SHA-256", "SHA-384", "SHA-512"].includes(values.algorithm) ? values.algorithm : "SHA-384"; const digest = await crypto.subtle.digest(algorithm, new TextEncoder().encode(values.text)); return { text: `${algorithm.toLowerCase().replace("-", "")}-${base64(digest)}\n\n${t("Bu değer yalnızca yukarıdaki tam bayt dizisiyle eşleşir.", "This value matches only the exact byte sequence above.", "Dieser Wert passt nur zur exakten obigen Bytefolge.", "此值仅与上方完全相同的字节序列匹配。")}` }; }
  if (slug === "csp-direktif-birlestirici") { const map = new Map<string, Set<string>>(); [values.first, values.second].forEach((policy) => policy.split(";").map((v) => v.trim()).filter(Boolean).forEach((directive) => { const [name, ...tokens] = directive.split(/\s+/); const set = map.get(name) ?? new Set<string>(); tokens.forEach((token) => set.add(token)); map.set(name, set); })); return { text: [...map].map(([name, tokens]) => `${name}${tokens.size ? ` ${[...tokens].join(" ")}` : ""}`).join("; ") + ";\n\n" + t("Uyarı: Birleştirme politikayı gevşetebilir. Tarayıcıda rapor modu ve gerçek kaynaklarla ayrıca doğrulayın.", "Warning: merging may loosen a policy. Verify in report-only mode and with real resources.", "Warnung: Zusammenführen kann die Richtlinie lockern. Im Report-Only-Modus prüfen.", "警告：合并可能放宽策略，请使用仅报告模式和真实资源另行验证。") }; }
  if (slug === "ajan-girdi-cikti-sozlesmesi") { return { text: `${t("AJAN GÖREV SÖZLEŞMESİ", "AGENT TASK CONTRACT", "AGENTEN-AUFTRAGSVERTRAG", "智能体任务契约")}\n\n1. ${t("HEDEF", "GOAL", "ZIEL", "目标")}\n${values.goal.trim()}\n\n2. ${t("GİRDİ SÖZLEŞMESİ", "INPUT CONTRACT", "EINGABEVERTRAG", "输入契约")}\n${values.input.trim()}\n- ${t("Eksik veya hatalı girdide yürütmeyi durdur ve alan bazlı hata döndür.", "Stop on missing or invalid input and return a field-level error.", "Bei fehlender/ungültiger Eingabe stoppen und Feldfehler zurückgeben.", "输入缺失或无效时停止，并返回字段级错误。")}\n\n3. ${t("ÇIKTI SÖZLEŞMESİ", "OUTPUT CONTRACT", "AUSGABEVERTRAG", "输出契约")}\n${values.output.trim()}\n- ${t("Şema dışı alan üretme; belirsiz değeri null ve uyarıyla göster.", "Do not emit undeclared fields; use null plus a warning for uncertainty.", "Keine nicht deklarierten Felder; Unsicherheit als null plus Warnung.", "不要输出未声明字段；不确定值用 null 并附警告。")}\n\n4. ${t("GÜVENLİK VE DURDURMA", "SAFETY & STOP CONDITIONS", "SICHERHEIT & STOPPBEDINGUNGEN", "安全与停止条件")}\n- ${t("Kişisel veri, sır veya yetkisiz içerik algılanırsa otomatik devam etme.", "Do not continue automatically when personal data, secrets, or unauthorized content is detected.", "Bei personenbezogenen Daten, Geheimnissen oder unbefugten Inhalten nicht automatisch fortfahren.", "检测到个人数据、机密或未授权内容时不要自动继续。")}\n- ${t("Her adım, kullanılan araç ve dönüşüm kaydıyla izlenebilir olmalı.", "Every step must be traceable through the tool and transformation record.", "Jeder Schritt muss über Werkzeug und Transformation nachvollziehbar sein.", "每一步都必须通过工具和转换记录可追踪。")}` }; }
  throw new Error(t("Bu araç için işlem tanımı bulunamadı.", "No processor is registered for this tool.", "Für dieses Werkzeug ist kein Prozessor registriert.", "未注册此工具的处理器。"));
}

export function EssentialWorkbench({ slug, locale }: { slug: string; locale: Locale }) {
  const fields = useMemo(() => fieldsFor(slug), [slug]);
  const [values, setValues] = useState<Record<string, string>>(() => Object.fromEntries(fields.map((field) => [field.key, field.type === "select" ? field.demo : ""])));
  const [output, setOutput] = useState("");
  const [metrics, setMetrics] = useState<Result["metrics"]>([]);
  const [status, setStatus] = useState<"idle" | "busy" | "success" | "error">("idle");
  const [message, setMessage] = useState("");

  useEffect(() => {
    const onAgentInput = (event: Event) => {
      const detail = (event as CustomEvent<{ value?: string; fields?: Record<string, string> }>).detail;
      if (detail?.fields) setValues((current) => ({ ...current, ...detail.fields }));
      else if (detail?.value) setValues((current) => ({ ...current, [fields[0].key]: detail.value ?? "" }));
      setStatus("idle"); setOutput(""); setMessage("");
    };
    window.addEventListener("bytequant:agent-input", onAgentInput);
    return () => window.removeEventListener("bytequant:agent-input", onAgentInput);
  }, [fields]);

  async function run() {
    if (status === "busy") return;
    setStatus("busy"); setMessage("");
    try {
      if (fields.some((field) => field.key !== "expected" && field.key !== "weights" && field.key !== "base" && !values[field.key]?.trim())) throw new Error(L(locale, common.needed));
      const result = await process(slug, values, locale);
      setOutput(result.text); setMetrics(result.metrics ?? []); setStatus("success"); setMessage(L(locale, common.local));
    } catch (error) {
      setOutput(""); setMetrics([]); setStatus("error"); setMessage(error instanceof Error ? error.message : L(locale, common.error));
    }
  }
  function loadDemo() { setValues(Object.fromEntries(fields.map((field) => [field.key, field.demo]))); setOutput(""); setMetrics([]); setStatus("idle"); setMessage(""); }
  function clear() { setValues(Object.fromEntries(fields.map((field) => [field.key, field.type === "select" ? field.demo : ""]))); setOutput(""); setMetrics([]); setStatus("idle"); setMessage(""); }
  async function copyOutput() { await navigator.clipboard.writeText(output); setMessage(L(locale, common.copied)); }
  function download() { if (!output) return; const url = URL.createObjectURL(new Blob([output], { type: "text/plain;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = `${slug}-bytequant.txt`; link.click(); window.setTimeout(() => URL.revokeObjectURL(url), 0); }

  return <div className="tool-workbench essential-workbench" onKeyDown={(event) => { if ((event.ctrlKey || event.metaKey) && event.key === "Enter") void run(); }}>
    <div className="essential-form" data-agent-contract="fields-v1" aria-busy={status === "busy"}>{fields.map((field) => <label key={field.key} className={field.type === "textarea" ? "wide" : undefined}><span>{L(locale, field.label)}</span>{field.type === "textarea" ? <textarea data-agent-input data-agent-key={field.key} value={values[field.key] ?? ""} placeholder={field.placeholder ? L(locale, field.placeholder) : undefined} onChange={(event) => setValues((current) => ({ ...current, [field.key]: event.target.value }))} /> : field.type === "select" ? <select data-agent-input data-agent-key={field.key} value={values[field.key] ?? ""} onChange={(event) => setValues((current) => ({ ...current, [field.key]: event.target.value }))}>{field.options?.map((option) => <option key={option.value} value={option.value}>{L(locale, option.label)}</option>)}</select> : <input data-agent-input data-agent-key={field.key} type={field.type ?? "text"} value={values[field.key] ?? ""} placeholder={field.placeholder ? L(locale, field.placeholder) : undefined} onChange={(event) => setValues((current) => ({ ...current, [field.key]: event.target.value }))} />}</label>)}</div>
    <div className="workbench-actions"><button className="primary-button" type="button" onClick={() => void run()} disabled={status === "busy"}>{status === "busy" ? L(locale, common.running) : L(locale, common.run)}</button><button className="secondary-button" type="button" onClick={loadDemo}>{L(locale, common.demo)}</button><button className="text-button" type="button" onClick={clear}>{L(locale, common.clear)}</button><kbd>Ctrl/⌘ + Enter</kbd></div>
    {message && <div className={`tool-status ${status}`} role={status === "error" ? "alert" : "status"}><strong>{status === "error" ? L(locale, common.error) : status === "success" ? "✓" : "ℹ"}</strong><span>{message}</span></div>}
    <section className="workbench-output"><header><div><span>{L(locale, common.output)}</span>{metrics?.map((metric) => <small key={metric.label}>{metric.label}: <b>{metric.value}</b></small>)}</div>{output && <div><button type="button" onClick={() => void copyOutput()}>{L(locale, common.copy)}</button><button type="button" onClick={download}>{L(locale, common.download)}</button></div>}</header><pre data-agent-output data-ready={output ? "true" : "false"}>{output || L(locale, common.empty)}</pre></section>
  </div>;
}
