"use client";

import { useMemo, useState } from "react";
import type { Locale } from "../lib/site";
import { getTool } from "../lib/tools";

type Result = { output: string; metrics?: Array<[string, string | number]>; warning?: string };
type Copy = { local: string; demo: string; clear: string; input: string; second: string; mode: string; run: string; running: string; output: string; copy: string; download: string; empty: string; done: string; copied: string; error: string; privacy: string };

const copy: Record<Locale, Copy> = {
  tr: { local: "Bu sekmede çalışır", demo: "Örnek veri yükle", clear: "Temizle", input: "Girdi", second: "Karşılaştırma / ikinci girdi", mode: "İşlem modu", run: "Yerel işlemi çalıştır", running: "İşleniyor…", output: "Doğrulanabilir çıktı", copy: "Kopyala", download: "İndir", empty: "Çıktı burada görünecek. Örnek veriyi yükleyerek aracı hemen deneyebilirsiniz.", done: "Tamamlandı", copied: "Çıktı panoya kopyalandı.", error: "Girdi işlenemedi", privacy: "İşlem tamamen cihazınızda gerçekleşti. Sonucu paylaşmadan önce hassas veri ve bağlam açısından gözden geçirin." },
  en: { local: "Runs in this tab", demo: "Load example", clear: "Clear", input: "Input", second: "Comparison / second input", mode: "Operation mode", run: "Run locally", running: "Processing…", output: "Verifiable output", copy: "Copy", download: "Download", empty: "Output will appear here. Load the example to try the tool immediately.", done: "Completed", copied: "Output copied to the clipboard.", error: "Input could not be processed", privacy: "Processing happened entirely on your device. Review sensitive data and context before sharing the result." },
  de: { local: "Läuft in diesem Tab", demo: "Beispiel laden", clear: "Leeren", input: "Eingabe", second: "Vergleich / zweite Eingabe", mode: "Verarbeitungsmodus", run: "Lokal ausführen", running: "Verarbeitung…", output: "Prüfbare Ausgabe", copy: "Kopieren", download: "Laden", empty: "Die Ausgabe erscheint hier. Laden Sie das Beispiel, um das Werkzeug sofort zu testen.", done: "Abgeschlossen", copied: "Ausgabe kopiert.", error: "Eingabe konnte nicht verarbeitet werden", privacy: "Die Verarbeitung erfolgte vollständig auf Ihrem Gerät. Prüfen Sie sensible Daten und Kontext vor dem Teilen." },
  zh: { local: "在当前标签页运行", demo: "加载示例", clear: "清空", input: "输入", second: "比较 / 第二输入", mode: "处理模式", run: "在本地运行", running: "处理中…", output: "可核验输出", copy: "复制", download: "下载", empty: "输出将显示在这里。加载示例即可立即试用。", done: "已完成", copied: "输出已复制。", error: "无法处理输入", privacy: "处理完全在您的设备上完成。分享结果前请检查敏感数据与语境。" },
};

const examples: Record<string, [string, string?]> = {
  "prompt-varsayim-haritasi": ["Yeni müşterilere haftalık bir rapor hazırla; kısa ve güvenilir olsun."],
  "prompt-risk-kaydi": ["Müşteri destek kayıtlarını özetle, gerekli olursa kişisel bilgileri de kullan ve kesin sonuç ver."],
  "prompt-cikti-sozlesmesi-testi": ["Görev: ürün geri bildirimini sınıflandır. Çıktı JSON olsun; category, confidence ve evidence alanları zorunlu. Hata durumunda açıklama döndür."],
  "prompt-varyasyon-laboratuvari": ["Teknik olmayan yöneticiler için bu güvenlik raporunu özetle."],
  "prompt-sikistirma-yardimcisi": ["Lütfen mümkünse, eğer yapabilirsen, aşağıdaki uzun metni kısa ve öz bir şekilde, çok uzatmadan kısaca özetle."],
  "cumle-sadelestirici": ["Gerçekleştirilmesi planlanmakta olan değerlendirme sürecinin tamamlanmasının ardından gerekli bilgilendirmenin tarafınıza yapılacağı öngörülmektedir."],
  "kapsayici-dil-inceleyici": ["Her normal kullanıcı bu ayarı kolayca anlar. Yaşlılar teknoloji kullanamaz; geliştirici adam gerekli düzeltmeyi yapar."],
  "ton-tutarliligi-inceleyici": ["Merhaba, size yardımcı olmaktan memnuniyet duyarız.\n\nBU HATAYI HEMEN DÜZELTMEK ZORUNDASINIZ!\n\nSorunuz olursa bize yazabilirsiniz."],
  "toplanti-notu-yapilandirici": ["Amaç: Temmuz sürümü. Karar: beta 29 Temmuz. Ayşe performans testini cuma bitirecek. Açık soru: Almanca içerik kimde? Sonraki toplantı 30 Temmuz."],
  "aksiyon-maddesi-cikarici": ["Mert yarına kadar build raporunu paylaşacak. Tasarım ekibi cuma günü mobil kartları kontrol etmeli. Karar henüz verilmedi."],
  "baslik-varyasyon-laboratuvari": ["Tarayıcıda çalışan gizlilik odaklı JSON biçimlendirici"],
  "atif-yer-tutucu-denetleyici": ["Yerel işleme veri riskini azaltabilir [kaynak gerekli].\nTODO: güncel standardı bağla.\nPerformans %40 arttı (REF?)."],
  "json-schema-ornek-uretici": ["{\n  \"type\": \"object\",\n  \"required\": [\"name\", \"active\"],\n  \"properties\": {\n    \"name\": {\"type\": \"string\", \"example\": \"Ada\"},\n    \"active\": {\"type\": \"boolean\"},\n    \"tags\": {\"type\": \"array\", \"items\": {\"type\": \"string\"}}\n  }\n}"],
  "csv-sutun-profilleyici": ["name,age,city\nAda,31,Ankara\nLin,29,\nMira,31,Berlin"],
  "csv-birlestirme-simulatoru": ["id,name\n1,Ada\n2,Lin", "id,score\n1,92\n3,77"],
  "json-patch-olusturucu": ["{\"name\":\"ByteQuant\",\"tools\":211,\"beta\":true}", "{\"name\":\"ByteQuant\",\"tools\":211,\"locale\":\"de\"}"],
  "json-merge-patch-laboratuvari": ["{\"profile\":{\"name\":\"Ada\",\"city\":\"Ankara\"},\"active\":true}", "{\"profile\":{\"city\":\"Berlin\"},\"active\":null}"],
  "api-sayfalama-planlayici": ["{\"strategy\":\"cursor\",\"pageSize\":50,\"maxPages\":20,\"retryLimit\":3,\"dedupeKey\":\"id\"}"],
  "http-durum-kodu-gezgini": ["200\n201\n304\n401\n404\n409\n422\n429\n503"],
  "mime-tipi-inceleyici": ["{\"filename\":\"report.pdf\",\"contentType\":\"application/octet-stream\",\"magic\":\"25 50 44 46\"}"],
  "csv-markdown-donusturucu": ["tool,privacy,status\nJSON Formatter,local,ready\nPDF Merge,local,ready"],
  "tsv-csv-donusturucu": ["name\tage\tcity\nAda\t31\tAnkara\nLin\t29\tBerlin"],
  "sorgu-dizesi-json-donusturucu": ["tag=privacy&tag=security&page=2&lang=tr"],
  "metin-ascii-tablo-donusturucu": ["name,score,status\nAda,92,ready\nLin,88,review"],
  "renk-paleti-donusturucu": ["brand: #3657ff\nsurface: #111827\ntext: #f8fafc\naccent: #16a34a"],
  "gizli-deger-redaksiyon-planlayici": ["API_KEY=sk_live_example_123456789\nDATABASE_URL=postgres://user:secret@localhost/app\nAuthorization: Bearer eyJhbGciOiJIUzI1NiJ9.demo.signature"],
  "takma-adlandirma-haritasi": ["email,name,customer_id\nada@example.com,Ada,1042\nlin@example.com,Lin,1043"],
  "guvenlik-kontrol-listesi-olusturucu": ["{\"asset\":\"static web app\",\"change\":\"new file upload tool\",\"threats\":[\"XSS\",\"resource exhaustion\",\"metadata leak\"]}"],
  "jwt-sure-zaman-cizelgesi": ["{\"iat\":1784908800,\"nbf\":1784908800,\"exp\":1784912400,\"clockSkewSeconds\":60}"],
  "parola-ihlal-hijyeni-kontrolu": ["correct horse battery staple 2026!"],
  "gizlilik-bildirimi-bosluk-tarayicisi": ["Gizlilik Bildirimi\nVerileri araçların çalışması için işleriz. Çerez tercihleri cihazda tutulur. Sorularınız için privacy@example.org adresine yazın."],
  "kredi-amortisman-tahminleyici": ["{\"principal\":250000,\"annualRate\":3.4,\"years\":10,\"extraMonthly\":250}"],
  "enflasyon-satin-alma-gucu": ["{\"amount\":100000,\"annualInflation\":12,\"years\":5}"],
  "basabas-noktasi-hesaplayici": ["{\"fixedCost\":120000,\"unitPrice\":480,\"unitVariableCost\":210}"],
  "marj-kar-orani-hesaplayici": ["{\"cost\":80,\"price\":125}"],
  "olasilik-hesaplayici": ["{\"a\":0.65,\"b\":0.4,\"independent\":true}"],
  "orneklem-buyuklugu-tahminleyici": ["{\"confidence\":95,\"marginOfError\":5,\"proportion\":50,\"population\":10000}"],
  "karar-matrisi": ["criteria,weight,Option A,Option B\nPrivacy,5,5,3\nEase,4,3,5\nCost,3,4,4"],
  "smart-hedef-olusturucu": ["Hedef: Mobil araç kullanımını artırmak\nÖlçüm: tamamlanan yerel işlemler\nMevcut: haftada 400\nHedef değer: haftada 600\nTarih: 2026-09-30"],
  "gundem-olusturucu": ["Hedef: yeni sürüm kararı\nSüre: 45 dakika\nKatılımcılar: ürün, tasarım, güvenlik\nKonular: test bulguları; erişilebilirlik; yayın kararı"],
  "vardiya-plani-formatlayici": ["Ada,2026-07-27 09:00,2026-07-27 17:00\nLin,2026-07-27 16:00,2026-07-28 00:00\nAda,2026-07-28 08:00,2026-07-28 16:00"],
  "kontrol-listesi-duzenleyici": ["P0 | Ayşe | Build testini çalıştır | CI çıktısı\nP1 | Mert | Mobil görünümü kontrol et | ekran görüntüsü\nP2 | Ekip | Değişiklik günlüğünü yaz | inceleme"],
  "ajan-gorev-ayristirici": ["Müşteri CSV dosyasını doğrula, kişisel verileri maskele, JSON'a dönüştür, kalite raporu üret ve indirilebilir hale getir."],
  "baglam-oncelik-planlayici": ["must | 900 | API sözleşmesi | primary | today\nshould | 2400 | eski konuşma | internal | 90d\nmust | 1200 | güvenlik politikası | primary | 7d\ncould | 4000 | örnek çıktılar | secondary | 30d"],
  "halusinasyon-risk-kontrol-listesi": ["Görev: 2026 güvenlik standardındaki değişiklikleri özetle\nKaynaklar: resmî standart, iki blog\nÇıktı: yöneticiler için karar özeti"],
  "rag-kaynak-kalite-puanlayici": ["Official standard | primary | 2026-06-01 | full text | no conflict\nVendor blog | secondary | 2025-11-02 | excerpt | product interest\nForum comment | anecdotal | unknown | partial | unknown"],
  "model-karsilastirma-rubrigi": ["Task: structured extraction\nCriteria: exactness=5, schema validity=5, latency=3, privacy=5, cost=2\nTest cases: normal, missing field, adversarial text, multilingual"],
  "paket-manifestosu-denetleyici": ["{\"name\":\"demo\",\"version\":\"1.0.0\",\"scripts\":{\"postinstall\":\"node setup.js\",\"test\":\"vitest\"},\"dependencies\":{\"example\":\"*\"},\"engines\":{\"node\":\">=18\"}}"],
  "npm-script-risk-tarayicisi": ["{\"scripts\":{\"preinstall\":\"curl https://example.org/install.sh | sh\",\"clean\":\"rm -rf dist\",\"build\":\"next build\"}}"],
  "regex-karmasiklik-on-kontrolu": ["^(a+)+$\n(.*a){10}\n(?:ab|a)+$\n^[a-z0-9_-]{1,64}$"],
  "dockerfile-guvenlik-on-kontrolu": ["FROM node:latest\nWORKDIR /app\nCOPY . .\nRUN chmod -R 777 /app\nRUN npm install\nCMD [\"npm\",\"start\"]"],
  "github-actions-izin-denetleyici": ["name: CI\non: [pull_request_target]\npermissions: write-all\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: vendor/action@main"],
  "kaynak-guvenilirlik-matrisi": ["NASA release | agency author | primary | documented method | 2026-07-20 | no commercial claim\nVendor benchmark | company | secondary | partial method | 2026-03-11 | sells product\nAnonymous post | unknown | anecdotal | no method | unknown | unknown"],
  "arastirma-sorusu-ayristirici": ["Tarayıcı içinde çalışan gizlilik araçları küçük ekiplerin veri riskini hangi koşullarda azaltır?"],
  "kanit-sentez-tablosu": ["Source A | Local processing avoids upload | browser architecture | supported | no extension analysis\nSource B | Extensions may still access content | threat model | supported | browser dependent\nSource C | Local always means secure | opinion | contradicted | absolute claim"],
};

const dualInput = new Set(["csv-birlestirme-simulatoru", "json-patch-olusturucu", "json-merge-patch-laboratuvari"]);
const modeTools = new Set(["csv-birlestirme-simulatoru", "tsv-csv-donusturucu", "sorgu-dizesi-json-donusturucu", "renk-paleti-donusturucu"]);

function lines(value: string) { return value.split(/\r?\n/).map((line) => line.trim()).filter(Boolean); }
function safeJson(value: string): unknown { try { return JSON.parse(value); } catch { throw new Error("JSON syntax is invalid. Check commas, quotes, and brackets."); } }
function object(value: unknown): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("A JSON object is required."); return value as Record<string, unknown>; }
function num(value: unknown, name: string) { const result = Number(value); if (!Number.isFinite(result)) throw new Error(`${name} must be a finite number.`); return result; }
function fixed(value: number, digits = 2) { return new Intl.NumberFormat("en-US", { maximumFractionDigits: digits }).format(value); }
function localized(locale: Locale, value: Record<Locale, string>) { return value[locale]; }
function escapeCell(value: unknown) { return String(value ?? "").replace(/\|/g, "\\|").replace(/\r?\n/g, "<br>"); }

function parseDelimited(input: string, delimiter?: string) {
  const detected = delimiter ?? (input.includes("\t") ? "\t" : ","); const rows: string[][] = []; let row: string[] = []; let cell = ""; let quoted = false;
  for (let i = 0; i < input.length; i += 1) { const char = input[i]; if (char === '"') { if (quoted && input[i + 1] === '"') { cell += '"'; i += 1; } else quoted = !quoted; } else if (char === detected && !quoted) { row.push(cell); cell = ""; } else if ((char === "\n" || char === "\r") && !quoted) { if (char === "\r" && input[i + 1] === "\n") i += 1; row.push(cell); if (row.some((item) => item.length)) rows.push(row); row = []; cell = ""; } else cell += char; }
  row.push(cell); if (row.some((item) => item.length)) rows.push(row); if (quoted) throw new Error("An unclosed quoted field was found."); return rows;
}
function csvCell(value: unknown, delimiter = ",") { const text = String(value ?? ""); return /["\r\n]/.test(text) || text.includes(delimiter) ? `"${text.replace(/"/g, '""')}"` : text; }
function markdown(rows: string[][]) { if (!rows.length) return ""; const width = Math.max(...rows.map((row) => row.length)); const normalized = rows.map((row) => Array.from({ length: width }, (_, i) => escapeCell(row[i]))); return [`| ${normalized[0].join(" | ")} |`, `| ${Array(width).fill("---").join(" | ")} |`, ...normalized.slice(1).map((row) => `| ${row.join(" | ")} |`)].join("\n"); }
function ascii(rows: string[][]) { if (!rows.length) return ""; const width = Math.max(...rows.map((row) => row.length)); const sizes = Array.from({ length: width }, (_, i) => Math.min(40, Math.max(...rows.map((row) => (row[i] ?? "").length)))); const border = `+-${sizes.map((size) => "-".repeat(size)).join("-+-")}-+`; return [border, ...rows.flatMap((row, index) => [`| ${sizes.map((size, i) => (row[i] ?? "").slice(0, size).padEnd(size)).join(" | ")} |`, ...(index === 0 ? [border] : [])]), border].join("\n"); }
function hash(value: string) { let h = 2166136261; for (const char of value) { h ^= char.charCodeAt(0); h = Math.imul(h, 16777619); } return (h >>> 0).toString(36).padStart(7, "0"); }
function flattenDiff(a: unknown, b: unknown, path = "", depth = 0): Array<Record<string, unknown>> { if (depth > 60) throw new Error("JSON nesting exceeds the 60-level review limit."); if (JSON.stringify(a) === JSON.stringify(b)) return []; if (a && b && typeof a === "object" && typeof b === "object" && !Array.isArray(a) && !Array.isArray(b)) { const left = a as Record<string, unknown>; const right = b as Record<string, unknown>; return [...new Set([...Object.keys(left), ...Object.keys(right)])].flatMap((key) => { const p = `${path}/${key.replace(/~/g, "~0").replace(/\//g, "~1")}`; if (!(key in right)) return [{ op: "remove", path: p }]; if (!(key in left)) return [{ op: "add", path: p, value: right[key] }]; return flattenDiff(left[key], right[key], p, depth + 1); }); } return [{ op: path ? "replace" : "replace-root", path: path || "/", value: b }]; }
function mergePatch(target: unknown, patch: unknown, depth = 0): unknown { if (depth > 60) throw new Error("JSON nesting exceeds the 60-level review limit."); if (!patch || typeof patch !== "object" || Array.isArray(patch)) return patch; const result: Record<string, unknown> = target && typeof target === "object" && !Array.isArray(target) ? { ...(target as Record<string, unknown>) } : {}; for (const [key, value] of Object.entries(patch as Record<string, unknown>)) { if (value === null) delete result[key]; else result[key] = mergePatch(result[key], value, depth + 1); } return result; }
function schemaExample(schema: unknown, depth = 0): unknown { if (depth > 20) throw new Error("Schema nesting exceeds the 20-level example limit."); const s = object(schema); if ("const" in s) return s.const; if (Array.isArray(s.enum) && s.enum.length) return s.enum[0]; if ("example" in s) return s.example; switch (s.type) { case "object": return Object.fromEntries(Object.entries(object(s.properties ?? {})).map(([key, value]) => [key, schemaExample(value, depth + 1)])); case "array": return [schemaExample(s.items ?? { type: "string" }, depth + 1)]; case "boolean": return false; case "integer": return 0; case "number": return 0; case "null": return null; default: return "example"; } }

const statusInfo: Record<number, [string, string]> = { 200: ["OK", "Use the representation; validate Content-Type and cache headers."], 201: ["Created", "Read Location/body and avoid repeating non-idempotent requests."], 204: ["No Content", "Do not attempt to parse a body."], 304: ["Not Modified", "Reuse the validated cached representation."], 400: ["Bad Request", "Fix request syntax or validation errors before retrying."], 401: ["Unauthorized", "Authenticate again; do not loop retries."], 403: ["Forbidden", "Authentication may be valid but authorization is insufficient."], 404: ["Not Found", "Check identity and avoid exposing resource-existence details."], 409: ["Conflict", "Resolve version or state conflict before retry."], 422: ["Unprocessable Content", "Show field-level semantic validation feedback."], 429: ["Too Many Requests", "Honor Retry-After and use bounded backoff."], 500: ["Internal Server Error", "Log a correlation id and retry only when safe."], 503: ["Service Unavailable", "Honor Retry-After; use circuit breaking and a fallback."] };

function processTool(slug: string, input: string, secondary: string, mode: string, locale: Locale): Result {
  const rows = ["csv-markdown-donusturucu", "metin-ascii-tablo-donusturucu", "csv-sutun-profilleyici", "csv-birlestirme-simulatoru", "takma-adlandirma-haritasi", "karar-matrisi"].includes(slug) ? parseDelimited(input) : []; const ls = lines(input); const lower = input.toLocaleLowerCase();
  if (slug === "csv-markdown-donusturucu") return { output: markdown(rows), metrics: [["rows", Math.max(0, rows.length - 1)], ["columns", rows[0]?.length ?? 0]] };
  if (slug === "tsv-csv-donusturucu") { const toTsv = mode === "reverse"; const parsed = parseDelimited(input, toTsv ? "," : "\t"); const delimiter = toTsv ? "\t" : ","; return { output: parsed.map((row) => row.map((cell) => csvCell(cell, delimiter)).join(delimiter)).join("\n"), metrics: [["rows", parsed.length], ["delimiter", toTsv ? "TAB" : "comma"]] }; }
  if (slug === "sorgu-dizesi-json-donusturucu") { if (mode === "reverse") { const source = object(safeJson(input)); const query = new URLSearchParams(); Object.entries(source).forEach(([key, value]) => (Array.isArray(value) ? value : [value]).forEach((item) => query.append(key, String(item)))); return { output: query.toString() }; } const query = new URLSearchParams(input.replace(/^\?/, "")); const result: Record<string, string | string[]> = {}; query.forEach((value, key) => { const existing = result[key]; result[key] = existing === undefined ? value : Array.isArray(existing) ? [...existing, value] : [existing, value]; }); return { output: JSON.stringify(result, null, 2), metrics: [["parameters", [...query.keys()].length], ["unique keys", Object.keys(result).length]] }; }
  if (slug === "metin-ascii-tablo-donusturucu") return { output: ascii(rows), metrics: [["rows", rows.length], ["columns", rows[0]?.length ?? 0]] };
  if (slug === "renk-paleti-donusturucu") { const palette = Object.fromEntries(ls.map((line, i) => { const [rawName, rawColor] = line.includes(":") ? line.split(/:(.+)/) : [`color-${i + 1}`, line]; const color = rawColor.trim(); if (!/^#[0-9a-f]{6}$/i.test(color)) throw new Error(`Invalid HEX color: ${color}`); return [rawName.trim().replace(/[^a-z0-9_-]+/gi, "-"), color.toLowerCase()]; })); if (mode === "reverse") return { output: JSON.stringify(palette, null, 2) }; return { output: `:root {\n${Object.entries(palette).map(([key, value]) => `  --${key}: ${value};`).join("\n")}\n}\n\n${JSON.stringify({ color: palette }, null, 2)}`, metrics: [["colors", Object.keys(palette).length]] }; }
  if (slug === "json-schema-ornek-uretici") { const schema = safeJson(input); const result = schemaExample(schema); return { output: `${JSON.stringify(result, null, 2)}\n\nRequired fields: ${(object(schema).required as string[] | undefined)?.join(", ") || "none declared"}` }; }
  if (slug === "csv-sutun-profilleyici") { if (rows.length < 2) throw new Error("A header and at least one data row are required."); const headers = rows[0]; const profiles = headers.map((header, index) => { const values = rows.slice(1).map((row) => row[index] ?? ""); const present = values.filter(Boolean); const numeric = present.filter((value) => Number.isFinite(Number(value))); return { column: header, rows: values.length, missing: values.length - present.length, unique: new Set(present).size, inferredType: present.length && numeric.length === present.length ? "number" : "string", min: numeric.length ? Math.min(...numeric.map(Number)) : undefined, max: numeric.length ? Math.max(...numeric.map(Number)) : undefined, examples: [...new Set(present)].slice(0, 3) }; }); return { output: JSON.stringify(profiles, null, 2), metrics: [["rows", rows.length - 1], ["columns", headers.length]] }; }
  if (slug === "csv-birlestirme-simulatoru") { const rightRows = parseDelimited(secondary); if (rows.length < 2 || rightRows.length < 2) throw new Error("Both tables need a header and at least one row."); const key = rows[0].find((header) => rightRows[0].includes(header)); if (!key) throw new Error("No shared key column was found."); const li = rows[0].indexOf(key); const ri = rightRows[0].indexOf(key); const header = [...rows[0], ...rightRows[0].filter((_, i) => i !== ri)]; const rightMap = new Map(rightRows.slice(1).map((row) => [row[ri], row])); const used = new Set<string>(); const joined = rows.slice(1).flatMap((left) => { const right = rightMap.get(left[li]); if (right) { used.add(left[li]); return [[...left, ...right.filter((_, i) => i !== ri)]]; } return mode === "inner" ? [] : [[...left, ...Array(rightRows[0].length - 1).fill("")]]; }); if (mode === "full") rightRows.slice(1).filter((right) => !used.has(right[ri])).forEach((right) => joined.push([...Array(rows[0].length).fill(""), ...right.filter((_, i) => i !== ri)].map((cell, i) => i === li ? right[ri] : cell))); return { output: [header, ...joined].map((row) => row.map((cell) => csvCell(cell)).join(",")).join("\n"), metrics: [["key", key], ["matched", used.size], ["output rows", joined.length]] }; }
  if (slug === "json-patch-olusturucu") { const patch = flattenDiff(safeJson(input), safeJson(secondary)); return { output: JSON.stringify(patch, null, 2), metrics: [["operations", patch.length]] }; }
  if (slug === "json-merge-patch-laboratuvari") { const patch = safeJson(secondary); return { output: `MERGE PATCH\n${JSON.stringify(patch, null, 2)}\n\nRESULT\n${JSON.stringify(mergePatch(safeJson(input), patch), null, 2)}` }; }
  if (slug === "api-sayfalama-planlayici") { const c = object(safeJson(input)); const strategy = String(c.strategy ?? "cursor"); const size = Math.max(1, Math.min(1000, num(c.pageSize ?? 50, "pageSize"))); const pages = Math.max(1, Math.min(10000, num(c.maxPages ?? 20, "maxPages"))); return { output: [`Strategy: ${strategy}`, `Hard request ceiling: ${pages} pages / ${size * pages} records`, `Termination: stop on empty page, repeated cursor, explicit hasNext=false, or page ceiling`, `Retry: ${num(c.retryLimit ?? 3, "retryLimit")} attempts with jittered exponential backoff; honor Retry-After`, `Deduplicate by: ${String(c.dedupeKey ?? "stable primary id")}`, "Persist the last accepted cursor only after durable processing; log page/cursor without response payloads."].join("\n"), metrics: [["page size", size], ["max records", size * pages]] }; }
  if (slug === "http-durum-kodu-gezgini") { const codes = ls.flatMap((line) => line.match(/\d{3}/g) ?? []).map(Number); return { output: codes.map((code) => { const info = statusInfo[code] ?? ["Unknown or uncommon", "Check the current HTTP specification and application contract."]; return `${code} ${info[0]}\n  ${info[1]}`; }).join("\n\n"), metrics: [["codes", codes.length]] }; }
  if (slug === "mime-tipi-inceleyici") { const c = object(safeJson(input)); const filename = String(c.filename ?? ""); const ext = filename.split(".").pop()?.toLowerCase() ?? ""; const byExt: Record<string, string> = { pdf: "application/pdf", png: "image/png", jpg: "image/jpeg", jpeg: "image/jpeg", webp: "image/webp", json: "application/json", svg: "image/svg+xml", zip: "application/zip" }; const magic = String(c.magic ?? "").replace(/\s+/g, "").toUpperCase(); const byMagic = magic.startsWith("25504446") ? "application/pdf" : magic.startsWith("89504E47") ? "image/png" : magic.startsWith("FFD8FF") ? "image/jpeg" : magic.startsWith("504B0304") ? "application/zip" : "unknown"; const declared = String(c.contentType ?? "unknown"); return { output: JSON.stringify({ filename, extensionSignal: byExt[ext] ?? "unknown", declared, magicSignal: byMagic, consistent: [byExt[ext], byMagic].filter(Boolean).every((value) => value === declared || declared === "application/octet-stream") }, null, 2), warning: "Type signals are hints; never execute or trust a file solely from its extension or MIME label." }; }
  if (slug === "gizli-deger-redaksiyon-planlayici") { const patterns: Array<[string, RegExp]> = [["bearer-token", /Bearer\s+[A-Za-z0-9._~+/-]{12,}/gi], ["connection-string", /\b(?:postgres|mysql|mongodb(?:\+srv)?):\/\/[^\s]+/gi], ["key-assignment", /\b(?:api[_-]?key|secret|token|password)\s*[:=]\s*[^\s]+/gi]]; let output = input; const counts: Array<[string, number]> = []; patterns.forEach(([name, re]) => { let count = 0; output = output.replace(re, () => { count += 1; return `[REDACTED_${name.toUpperCase()}_${count}]`; }); if (count) counts.push([name, count]); }); return { output: `${output}\n\nREDUCTION PLAN\n${counts.map(([name, count]) => `- ${name}: ${count}; rotate if exposed, then remove from history and logs`).join("\n") || "- No configured pattern matched; manual review is still required."}`, metrics: counts }; }
  if (slug === "takma-adlandirma-haritasi") { if (rows.length < 2) throw new Error("CSV input needs a header and records."); const headers = rows[0]; const mapped = rows.slice(1).map((row) => row.map((cell, index) => /email|name|id/i.test(headers[index] ?? "") ? `BQ-${headers[index].toUpperCase()}-${hash(`${headers[index]}:${cell}`)}` : cell)); return { output: [headers, ...mapped].map((row) => row.map((cell) => csvCell(cell)).join(",")).join("\n"), metrics: [["records", mapped.length], ["mapped fields", headers.filter((h) => /email|name|id/i.test(h)).length]], warning: "These deterministic labels are linkable and are not encryption. Use a secret-keyed construction for real pseudonymization." }; }
  if (slug === "guvenlik-kontrol-listesi-olusturucu") { const c = object(safeJson(input)); const threats = Array.isArray(c.threats) ? c.threats : []; return { output: [`# Security review — ${String(c.change ?? "change")}`, `Asset: ${String(c.asset ?? "unspecified")}`, "", ...threats.flatMap((threat) => [`- [ ] ${threat}: define abuse case and trust boundary`, `  - Owner:`, `  - Evidence:`, `  - Failure/rollback test:`]), "- [ ] Confirm least privilege, size/time limits, safe errors, dependency licenses, and release rollback."].join("\n") }; }
  if (slug === "jwt-sure-zaman-cizelgesi") { const c = object(safeJson(input)); const skew = num(c.clockSkewSeconds ?? 0, "clockSkewSeconds"); const iat = num(c.iat, "iat"), nbf = num(c.nbf ?? c.iat, "nbf"), exp = num(c.exp, "exp"); if (exp <= nbf) throw new Error("exp must be later than nbf."); return { output: [`Issued: ${new Date(iat * 1000).toISOString()}`, `Usable from: ${new Date(nbf * 1000).toISOString()} (earliest with skew ${new Date((nbf - skew) * 1000).toISOString()})`, `Expires: ${new Date(exp * 1000).toISOString()} (latest tolerance ${new Date((exp + skew) * 1000).toISOString()})`, `Nominal lifetime: ${fixed((exp - iat) / 60)} minutes`, "Decode and timeline checks do not verify the signature, issuer, audience, nonce, revocation, or key trust."].join("\n"), metrics: [["lifetime minutes", fixed((exp - iat) / 60)], ["clock skew seconds", skew]] }; }
  if (slug === "parola-ihlal-hijyeni-kontrolu") { const unique = new Set(input).size; const classes = [/[a-z]/.test(input), /[A-Z]/.test(input), /\d/.test(input), /[^\p{L}\p{N}\s]/u.test(input), /\s/.test(input)].filter(Boolean).length; const warnings = [input.length < 15 ? "Use at least 15 characters where the service allows it." : "Length is reasonable for a locally assessed passphrase.", /(password|qwerty|12345|admin|letmein)/i.test(input) ? "A common password fragment was found." : "No configured common fragment was found.", "This tool does not query breach databases. If exposure is suspected: change it, revoke sessions, rotate related secrets, and enable phishing-resistant MFA."]; return { output: warnings.map((item, i) => `${i + 1}. ${item}`).join("\n"), metrics: [["length", input.length], ["character classes", classes], ["unique characters", unique]], warning: "The password is analyzed only in memory and is never included in the output." }; }
  if (slug === "gizlilik-bildirimi-bosluk-tarayicisi") { const checks: Array<[string, RegExp]> = [["controller/contact", /(contact|iletişim|kontakt|联系|@)/i], ["purpose", /(purpose|amaç|zweck|目的)/i], ["data categories", /(personal data|kişisel veri|datenarten|个人信息)/i], ["retention", /(retention|saklama|aufbewahrung|保留)/i], ["rights", /(rights|haklar|rechte|权利)/i], ["recipients/transfers", /(recipient|alıcı|empfänger|接收|transfer|aktarım)/i], ["cookies/ads", /(cookie|çerez|adsense|advertising|werbung|广告)/i]]; const missing = checks.filter(([, re]) => !re.test(input)).map(([name]) => name); return { output: `PRESENT\n${checks.filter(([, re]) => re.test(input)).map(([name]) => `✓ ${name}`).join("\n") || "none detected"}\n\nREVIEW / POSSIBLY MISSING\n${missing.map((name) => `□ ${name}`).join("\n") || "No configured heading is missing."}\n\nThis is a wording pre-check, not a legal compliance determination.`, metrics: [["checks", checks.length], ["review items", missing.length]] }; }
  if (["kredi-amortisman-tahminleyici", "enflasyon-satin-alma-gucu", "basabas-noktasi-hesaplayici", "marj-kar-orani-hesaplayici", "olasilik-hesaplayici", "orneklem-buyuklugu-tahminleyici"].includes(slug)) { const c = object(safeJson(input)); if (slug === "kredi-amortisman-tahminleyici") { const p = num(c.principal, "principal"), years = num(c.years, "years"), annualRate = num(c.annualRate, "annualRate"), extra = num(c.extraMonthly ?? 0, "extraMonthly"); if (p <= 0 || p > 1e15 || years <= 0 || years > 100 || annualRate < 0 || annualRate > 100 || extra < 0 || extra > 1e15) throw new Error("Use a positive principal, 0–100% annual rate, 1–100 years, and a non-negative extra payment."); const months = Math.round(years * 12), rate = annualRate / 1200; const payment = rate === 0 ? p / months : p * rate * (1 + rate) ** months / ((1 + rate) ** months - 1); let balance = p, interest = 0, count = 0; while (balance > .01 && count < months * 2) { const part = balance * rate; const paid = Math.min(balance + part, payment + extra); interest += part; balance -= paid - part; count += 1; } return { output: `Scheduled payment: ${fixed(payment)}\nWith extra payment: ${fixed(payment + extra)}\nEstimated payoff: ${count} months\nEstimated interest: ${fixed(interest)}\nFormula: annuity payment P·r·(1+r)^n / ((1+r)^n−1)`, metrics: [["months", count], ["interest", fixed(interest)]] }; }
    if (slug === "enflasyon-satin-alma-gucu") { const amount = num(c.amount, "amount"), rate = num(c.annualInflation, "annualInflation") / 100, years = num(c.years, "years"), real = amount / (1 + rate) ** years; return { output: `Starting amount: ${fixed(amount)}\nAssumed annual inflation: ${fixed(rate * 100)}%\nYears: ${years}\nFuture purchasing power in today's units: ${fixed(real)}\nPurchasing-power loss: ${fixed((1 - real / amount) * 100)}%`, metrics: [["real value", fixed(real)], ["loss %", fixed((1 - real / amount) * 100)]] }; }
    if (slug === "basabas-noktasi-hesaplayici") { const fixedCost = num(c.fixedCost, "fixedCost"), price = num(c.unitPrice, "unitPrice"), variable = num(c.unitVariableCost, "unitVariableCost"); if (price <= variable) throw new Error("unitPrice must exceed unitVariableCost."); const units = Math.ceil(fixedCost / (price - variable)); return { output: `Contribution per unit: ${fixed(price - variable)}\nBreak-even units: ${units}\nBreak-even revenue: ${fixed(units * price)}\nFormula: fixed cost / (unit price − variable cost)`, metrics: [["units", units], ["revenue", fixed(units * price)]] }; }
    if (slug === "marj-kar-orani-hesaplayici") { const cost = num(c.cost, "cost"), price = num(c.price, "price"); if (cost <= 0 || price <= 0) throw new Error("cost and price must be positive."); return { output: `Gross profit: ${fixed(price - cost)}\nMargin: ${fixed((price - cost) / price * 100)}% (profit ÷ selling price)\nMarkup: ${fixed((price - cost) / cost * 100)}% (profit ÷ cost)`, metrics: [["margin %", fixed((price - cost) / price * 100)], ["markup %", fixed((price - cost) / cost * 100)]] }; }
    if (slug === "olasilik-hesaplayici") { const a = num(c.a, "a"), b = num(c.b, "b"); if ([a, b].some((value) => value < 0 || value > 1)) throw new Error("Probabilities must be between 0 and 1."); const intersection = a * b; return { output: `P(A∩B), assuming independence: ${fixed(intersection, 6)}\nP(A∪B): ${fixed(a + b - intersection, 6)}\nP(at least one): ${fixed(1 - (1 - a) * (1 - b), 6)}\nP(neither): ${fixed((1 - a) * (1 - b), 6)}\nIndependence must be justified; do not use multiplication for dependent events.`, metrics: [["union", fixed(a + b - intersection, 4)], ["intersection", fixed(intersection, 4)]] }; }
    const confidence = num(c.confidence, "confidence"), margin = num(c.marginOfError, "marginOfError") / 100, proportion = num(c.proportion, "proportion") / 100, population = num(c.population ?? 0, "population"); if (confidence < 80 || confidence > 99.9 || margin <= 0 || margin > .5 || proportion <= 0 || proportion >= 1 || population < 0 || population > 1e12) throw new Error("Use confidence 80–99.9, margin 0–50, proportion 0–100 exclusive, and a non-negative bounded population."); const z = confidence >= 99 ? 2.576 : confidence >= 95 ? 1.96 : confidence >= 90 ? 1.645 : 1.282; const n0 = z ** 2 * proportion * (1 - proportion) / margin ** 2; const n = population > 0 ? n0 / (1 + (n0 - 1) / population) : n0; return { output: `Estimated completed responses: ${Math.ceil(n)}\nUncorrected large-population estimate: ${Math.ceil(n0)}\nAssumptions: simple random sample, proportion ${fixed(proportion * 100)}%, confidence ${confidence}%, margin ±${fixed(margin * 100)} percentage points.\nNonresponse, design effects, weighting, subgroup analysis, and measurement error require separate planning.`, metrics: [["sample", Math.ceil(n)], ["z", z]] };
  }
  if (slug === "karar-matrisi") { if (rows.length < 2 || rows[0].length < 4) throw new Error("Use criteria, weight, and at least two option columns."); const options = rows[0].slice(2); const scores = options.map((option, oi) => ({ option, score: rows.slice(1).reduce((sum, row) => sum + num(row[1], "weight") * num(row[oi + 2], option), 0) })); scores.sort((a, b) => b.score - a.score); return { output: `${scores.map((item, i) => `${i + 1}. ${item.option}: ${fixed(item.score)}`).join("\n")}\n\nSensitivity check: vary the two highest weights by ±20% before making a high-impact decision.`, metrics: scores.map((item) => [item.option, fixed(item.score)]) }; }
  if (slug === "smart-hedef-olusturucu") { const fields = Object.fromEntries(ls.map((line) => line.split(/:(.+)/).map((item) => item.trim())).filter((pair) => pair.length >= 2)) as Record<string, string>; const goal = Object.values(fields)[0] ?? input.trim(); const baseline = Object.entries(fields).find(([key]) => /(mevcut|baseline|aktuell|当前)/i.test(key))?.[1] ?? "confirm"; const target = Object.entries(fields).find(([key]) => /(hedef değer|target|zielwert|目标值)/i.test(key))?.[1] ?? "confirm"; const deadline = Object.entries(fields).find(([key]) => /(tarih|date|termin|日期)/i.test(key))?.[1] ?? "confirm"; const measurement = Object.entries(fields).find(([key]) => /(ölç|measure|mess|衡量)/i.test(key))?.[1] ?? "confirm"; const missing = [baseline, target, deadline, measurement].filter((value) => value === "confirm").length; return { output: [`# ${localized(locale, { tr: "SMART hedef sözleşmesi", en: "SMART goal contract", de: "SMART-Zielvertrag", zh: "SMART 目标契约" })}`, ``, `**${localized(locale, { tr: "Sonuç", en: "Outcome", de: "Ergebnis", zh: "结果" })}:** ${goal}`, `**${localized(locale, { tr: "Ölçüm", en: "Measurement", de: "Messung", zh: "衡量方式" })}:** ${measurement}`, `**${localized(locale, { tr: "Başlangıç → hedef", en: "Baseline → target", de: "Ausgang → Ziel", zh: "基线 → 目标" })}:** ${baseline} → ${target}`, `**${localized(locale, { tr: "Son tarih", en: "Deadline", de: "Termin", zh: "截止日期" })}:** ${deadline}`, ``, `## ${localized(locale, { tr: "Kabul ve durdurma koşulları", en: "Acceptance and stop conditions", de: "Abnahme- und Abbruchbedingungen", zh: "验收与停止条件" })}`, `- [ ] ${localized(locale, { tr: "Ölçüm kaynağı ve sahibi açık", en: "Metric source and owner are explicit", de: "Messquelle und Zuständigkeit sind klar", zh: "明确指标来源与负责人" })}`, `- [ ] ${localized(locale, { tr: "Hedef değer son tarihte gözlenebilir", en: "Target is observable by the deadline", de: "Zielwert ist zum Termin beobachtbar", zh: "目标值可在截止日期验证" })}`, `- [ ] ${localized(locale, { tr: "Başarı için kaliteden veya güvenlikten ödün verilmiyor", en: "Success does not trade away quality or safety", de: "Erfolg geht nicht zulasten von Qualität oder Sicherheit", zh: "成功不以牺牲质量或安全为代价" })}`].join("\n"), metrics: [[localized(locale, { tr: "alan", en: "fields", de: "Felder", zh: "字段" }), Object.keys(fields).length], [localized(locale, { tr: "eksik", en: "missing", de: "Fehlend", zh: "缺失" }), missing]], warning: missing ? localized(locale, { tr: "Bazı SMART alanları açık değil; yayımlamadan önce 'confirm' değerlerini doldurun.", en: "Some SMART fields are not explicit; replace every 'confirm' value before publishing.", de: "Einige SMART-Felder fehlen; alle 'confirm'-Werte vor Veröffentlichung ersetzen.", zh: "部分 SMART 字段不明确；发布前请替换所有“confirm”值。" }) : undefined }; }
  if (slug === "gundem-olusturucu") { const fields = Object.fromEntries(ls.map((line) => line.split(/:(.+)/).map((item) => item.trim())).filter((pair) => pair.length >= 2)) as Record<string, string>; const durationText = Object.entries(fields).find(([key]) => /(süre|duration|dauer|时长)/i.test(key))?.[1] ?? "45"; const duration = Math.max(15, Math.min(240, Number(durationText.match(/\d+/)?.[0] ?? 45))); const topicsText = Object.entries(fields).find(([key]) => /(konu|topic|themen|主题)/i.test(key))?.[1] ?? input; const topics = topicsText.split(/[;，]/).map((item) => item.trim()).filter(Boolean).slice(0, 12); const opening = Math.max(3, Math.round(duration * .1)); const closing = Math.max(5, Math.round(duration * .15)); const perTopic = Math.max(3, Math.floor((duration - opening - closing) / Math.max(1, topics.length))); return { output: [`# ${localized(locale, { tr: "Karar odaklı toplantı gündemi", en: "Decision-focused meeting agenda", de: "Entscheidungsorientierte Agenda", zh: "以决策为导向的会议议程" })}`, ``, `00:00–${String(opening).padStart(2, "0")}: ${localized(locale, { tr: "Amaç, roller ve karar eşiği", en: "Outcome, roles, and decision threshold", de: "Ziel, Rollen und Entscheidungsschwelle", zh: "目标、角色与决策门槛" })}`, ...topics.map((topic, index) => `${String(opening + index * perTopic).padStart(2, "0")}:00–${String(Math.min(duration - closing, opening + (index + 1) * perTopic)).padStart(2, "0")}:00 · ${topic}\n  ${localized(locale, { tr: "Çıktı: karar / sahipli aksiyon / açık soru", en: "Output: decision / owned action / open question", de: "Ausgabe: Entscheidung / verantwortete Aufgabe / offene Frage", zh: "输出：决策 / 有负责人的行动 / 待解决问题" })}`), `${String(duration - closing).padStart(2, "0")}:00–${String(duration).padStart(2, "0")}:00 · ${localized(locale, { tr: "Kararları, sahipleri, tarihleri ve kanıtı oku", en: "Read back decisions, owners, dates, and evidence", de: "Entscheidungen, Zuständige, Termine und Nachweise wiederholen", zh: "复述决策、负责人、日期与证据" })}`].join("\n"), metrics: [[localized(locale, { tr: "dakika", en: "minutes", de: "Minuten", zh: "分钟" }), duration], [localized(locale, { tr: "konu", en: "topics", de: "Themen", zh: "主题" }), topics.length]], warning: localized(locale, { tr: "Zaman kutuları öneridir; erişilebilirlik gereksinimleri ve katılımcı sayısına göre uyarlayın.", en: "Time boxes are a planning aid; adapt them for accessibility needs and participant count.", de: "Zeitfenster sind Planungshilfe; an Barrierefreiheit und Teilnehmerzahl anpassen.", zh: "时间盒仅供规划；请根据可访问性需求和参与人数调整。" }) }; }
  if (slug === "kontrol-listesi-duzenleyici") { const rank: Record<string, number> = { P0: 0, P1: 1, P2: 2, P3: 3 }; const items = ls.map((line, index) => { const [priority = "P2", owner = "confirm", task = line, evidence = "confirm"] = line.split("|").map((item) => item.trim()); return { index, priority: priority.toUpperCase() in rank ? priority.toUpperCase() : "P2", owner: owner || "confirm", task: task || line, evidence: evidence || "confirm" }; }).sort((a, b) => rank[a.priority] - rank[b.priority] || a.index - b.index); const missing = items.filter((item) => item.owner === "confirm" || item.evidence === "confirm").length; return { output: `${markdown([[localized(locale, { tr: "Öncelik", en: "Priority", de: "Priorität", zh: "优先级" }), localized(locale, { tr: "Sahip", en: "Owner", de: "Verantwortlich", zh: "负责人" }), localized(locale, { tr: "Tamamlanabilir iş", en: "Closable task", de: "Abschließbare Aufgabe", zh: "可关闭任务" }), localized(locale, { tr: "Tamamlanma kanıtı", en: "Completion evidence", de: "Abschlussnachweis", zh: "完成证据" })], ...items.map((item) => [item.priority, item.owner, item.task, item.evidence])])}\n\n${localized(locale, { tr: "Kapanış kapısı", en: "Closure gate", de: "Abschlussgrenze", zh: "关闭条件" })}\n- [ ] ${localized(locale, { tr: "Sahip kabul etti", en: "Owner accepted", de: "Zuständigkeit bestätigt", zh: "负责人已确认" })}\n- [ ] ${localized(locale, { tr: "Kanıt bağlantısı veya dosyası eklendi", en: "Evidence link or artifact attached", de: "Nachweis verlinkt oder beigefügt", zh: "已附证据链接或文件" })}\n- [ ] ${localized(locale, { tr: "Bağımlılık ve geri alma yolu kaydedildi", en: "Dependency and rollback path recorded", de: "Abhängigkeit und Rücknahmeweg dokumentiert", zh: "已记录依赖与回滚路径" })}`, metrics: [[localized(locale, { tr: "iş", en: "tasks", de: "Aufgaben", zh: "任务" }), items.length], [localized(locale, { tr: "eksik sahip/kanıt", en: "missing owner/evidence", de: "Fehlende Zuständigkeit/Nachweis", zh: "缺少负责人/证据" }), missing]], warning: missing ? localized(locale, { tr: "Bazı işler kapanabilir değil; sahip ve kanıt alanlarını tamamlayın.", en: "Some tasks are not closable; complete owner and evidence fields.", de: "Einige Aufgaben sind nicht abschließbar; Zuständigkeit und Nachweis ergänzen.", zh: "部分任务尚不可关闭；请补充负责人和证据。" }) : undefined }; }
  if (slug === "vardiya-plani-formatlayici") { const shifts = ls.map((line) => { const [person, start, end] = line.split(","); const a = new Date(start), b = new Date(end); if (!person || Number.isNaN(a.valueOf()) || Number.isNaN(b.valueOf()) || b <= a) throw new Error(`Invalid shift: ${line}`); return { person, start: a, end: b, hours: (b.valueOf() - a.valueOf()) / 36e5 }; }); const warnings: string[] = []; shifts.forEach((shift, i) => shifts.slice(i + 1).forEach((other) => { if (shift.person === other.person && shift.start < other.end && other.start < shift.end) warnings.push(`${shift.person}: overlapping shifts`); })); return { output: `${markdown([["Person", "Start", "End", "Hours"], ...shifts.map((s) => [s.person, s.start.toISOString(), s.end.toISOString(), fixed(s.hours)])])}\n\nWarnings\n${warnings.map((w) => `- ${w}`).join("\n") || "- No direct overlap found. Verify local rest and labor rules independently."}`, metrics: [["shifts", shifts.length], ["warnings", warnings.length]] }; }
  if (["ajan-gorev-ayristirici", "baglam-oncelik-planlayici", "halusinasyon-risk-kontrol-listesi", "rag-kaynak-kalite-puanlayici", "model-karsilastirma-rubrigi"].includes(slug)) { if (slug === "baglam-oncelik-planlayici") { const items = ls.map((line) => { const [priority, tokens, title, source, age] = line.split("|").map((v) => v.trim()); return { priority, tokens: Number(tokens) || 0, title, source, age, score: (priority === "must" ? 100 : priority === "should" ? 60 : 25) + (source === "primary" ? 20 : 0) - (Number(tokens) || 0) / 500 }; }).sort((a, b) => b.score - a.score); return { output: items.map((item, i) => `${i + 1}. ${item.title} — ${item.tokens} tokens; ${item.priority}; ${item.source}; ${item.age}\n   Keep reason score: ${fixed(item.score)}`).join("\n"), metrics: [["chunks", items.length], ["tokens", items.reduce((sum, item) => sum + item.tokens, 0)]] }; }
    const goals = input.split(/[.;\n]+/).map((item) => item.trim()).filter((item) => item.length > 4); const title = slug === "ajan-gorev-ayristirici" ? "EXECUTION PLAN" : slug === "rag-kaynak-kalite-puanlayici" ? "SOURCE QUALITY REVIEW" : slug === "model-karsilastirma-rubrigi" ? "CONTROLLED MODEL COMPARISON" : "CLAIM-SAFETY REVIEW"; return { output: `${title}\n${goals.map((goal, i) => `${i + 1}. ${goal}\n   Input/evidence: define before execution\n   Success check: observable, source-linked, and reversible`).join("\n")}\n\nStop conditions\n- Missing authority or sensitive data\n- No primary source for a high-impact factual claim\n- Output contract cannot be validated`, metrics: [["review units", goals.length]] }; }
  if (["paket-manifestosu-denetleyici", "npm-script-risk-tarayicisi", "regex-karmasiklik-on-kontrolu", "dockerfile-guvenlik-on-kontrolu", "github-actions-izin-denetleyici"].includes(slug)) { const findings: Array<[string, string]> = []; const add = (severity: string, message: string) => findings.push([severity, message]); if (slug === "paket-manifestosu-denetleyici" || slug === "npm-script-risk-tarayicisi") { const manifest = object(safeJson(input)); const scripts = object(manifest.scripts ?? {}); Object.entries(scripts).forEach(([name, command]) => { const cmd = String(command); if (/^(pre|post)?install$/i.test(name)) add("high", `${name}: install lifecycle code requires source review`); if (/curl|wget|invoke-webrequest/i.test(cmd)) add("high", `${name}: downloads content during a script`); if (/\brm\s+-rf\b|remove-item.+-recurse/i.test(cmd)) add("medium", `${name}: recursive deletion signal`); if (/[|;&]{1,2}/.test(cmd)) add("medium", `${name}: shell chaining increases review surface`); }); if (slug === "paket-manifestosu-denetleyici") Object.entries(object(manifest.dependencies ?? {})).forEach(([name, version]) => { if (["*", "latest", "next"].includes(String(version))) add("medium", `${name}: floating dependency range ${version}`); }); }
    if (slug === "regex-karmasiklik-on-kontrolu") ls.forEach((pattern, i) => { if (/\([^)]*[+*][^)]*\)[+*{]/.test(pattern)) add("high", `line ${i + 1}: nested quantifier`); if (/\.\*[+*{]|\(\.\*[^)]*\)\{/.test(pattern)) add("medium", `line ${i + 1}: broad wildcard repetition`); if (!findings.some(([, m]) => m.startsWith(`line ${i + 1}:`))) add("info", `line ${i + 1}: no configured high-risk shape found`); });
    if (slug === "dockerfile-guvenlik-on-kontrolu") { ls.forEach((line, i) => { if (/^FROM\s+\S+:(latest|edge)\b/i.test(line)) add("medium", `line ${i + 1}: floating base-image tag`); if (/chmod\s+(?:-R\s+)?777/i.test(line)) add("high", `line ${i + 1}: world-writable permission`); if (/^COPY\s+\.\s+\./i.test(line)) add("medium", `line ${i + 1}: broad build-context copy; verify .dockerignore`); if (/npm install(?!\s+--)/i.test(line)) add("medium", `line ${i + 1}: prefer a locked reproducible install`); }); if (!/^USER\s+/im.test(input)) add("high", "No final non-root USER instruction found"); }
    if (slug === "github-actions-izin-denetleyici") { if (/pull_request_target/.test(input)) add("high", "pull_request_target requires strict checkout and secret boundaries"); if (/permissions:\s*write-all/i.test(input)) add("high", "write-all violates least privilege"); [...input.matchAll(/uses:\s*([^\s]+)@([^\s]+)/g)].forEach((match) => { if (!/^[a-f0-9]{40}$/i.test(match[2])) add("medium", `${match[1]}@${match[2]} is not pinned to a full commit SHA`); }); }
    return { output: findings.map(([severity, message]) => `[${severity.toUpperCase()}] ${message}`).join("\n") || "No configured risk pattern found. Manual review is still required.", metrics: [["findings", findings.length], ["high", findings.filter(([s]) => s === "high").length]], warning: "Pattern matching cannot establish exploitability or package trust." };
  }
  if (["kaynak-guvenilirlik-matrisi", "arastirma-sorusu-ayristirici", "kanit-sentez-tablosu"].includes(slug)) { if (slug === "arastirma-sorusu-ayristirici") { return { output: [`Research question: ${input.trim()}`, "", "Concepts", ...input.split(/\s+/).filter((word) => word.length > 6).slice(0, 8).map((word) => `- ${word.replace(/[^\p{L}\p{N}-]/gu, "")}`), "", "Subquestions", "1. What is the population, system, or context?", "2. Compared with which baseline or alternative?", "3. Which observable outcomes and time horizon matter?", "4. Which harms, counterexamples, and confounders could change the conclusion?", "", "Evidence plan", "- Prefer current primary sources and documented methods.", "- Record inclusion/exclusion criteria before collecting sources.", "- Separate direct evidence, inference, and unanswered questions."].join("\n") }; }
    const matrix = ls.map((line, i) => { const fields = line.split("|").map((v) => v.trim()); return [`S${i + 1}`, ...fields]; }); const headers = slug === "kaynak-guvenilirlik-matrisi" ? ["ID", "Source", "Author", "Type", "Method", "Freshness", "Conflict"] : ["ID", "Source", "Claim", "Method", "Finding", "Limitation"]; return { output: `${markdown([headers, ...matrix])}\n\nReview: verify links, authorship, publication date, methods, corrections, and counterevidence against the primary source.`, metrics: [["sources", matrix.length]] }; }
  if (["prompt-varsayim-haritasi", "prompt-risk-kaydi", "prompt-cikti-sozlesmesi-testi", "prompt-varyasyon-laboratuvari", "prompt-sikistirma-yardimcisi"].includes(slug)) { const assumptions = [!/\b(audience|kitle|zielgruppe|受众)\b/i.test(lower) && "Audience is not explicit", !/\b(format|biçim|schema|json|格式)\b/i.test(lower) && "Output format is not explicit", !/\b(source|kaynak|quelle|来源|evidence|kanıt)\b/i.test(lower) && "Evidence/source rule is not explicit", !/\b(error|hata|failure|fehler|错误)\b/i.test(lower) && "Failure behavior is not explicit"].filter(Boolean); if (slug === "prompt-sikistirma-yardimcisi") { const compact = input.replace(/\b(lütfen mümkünse|eğer yapabilirsen|bir şekilde|kısa ve öz bir şekilde|çok uzatmadan|please if possible|if you can|in order to)\b/gi, "").replace(/\s+/g, " ").trim(); return { output: `${compact}\n\nRemoved or condensed: ${Math.max(0, input.length - compact.length)} characters. Verify that authority, constraints, and exceptions were not lost.`, metrics: [["before", input.length], ["after", compact.length]] }; }
    if (slug === "prompt-varyasyon-laboratuvari") return { output: [`CONCISE\n${input.trim()} Respond with only the essential result and stated uncertainty.`, `STRUCTURED\nGoal: ${input.trim()}\nInputs: [state inputs]\nConstraints: [state limits]\nOutput: [define fields]\nIf blocked: explain the missing information.`, `REVIEW-FIRST\nDraft a result for: ${input.trim()}\nBefore finalizing, check unsupported claims, sensitive data, edge cases, and output-format compliance.`].join("\n\n---\n\n"), metrics: [["variants", 3]] };
    const heading = slug === "prompt-risk-kaydi" ? "RISK REGISTER" : slug === "prompt-cikti-sozlesmesi-testi" ? "OUTPUT CONTRACT REVIEW" : "ASSUMPTION MAP"; return { output: `${heading}\n${assumptions.map((item, i) => `${i + 1}. ${item}\n   Validation question: What value or rule should replace this assumption?`).join("\n") || "No configured structural gap found."}\n\nQuality gate\n- State authority and forbidden actions\n- Define success and failure output\n- Separate facts, inference, and uncertainty\n- Test normal, edge, adversarial, and missing-input cases`, metrics: [["review items", assumptions.length]] };
  }
  if (["cumle-sadelestirici", "kapsayici-dil-inceleyici", "ton-tutarliligi-inceleyici", "toplanti-notu-yapilandirici", "aksiyon-maddesi-cikarici", "baslik-varyasyon-laboratuvari", "atif-yer-tutucu-denetleyici"].includes(slug)) { const sentences = input.split(/(?<=[.!?。！？])\s+|\r?\n+/).map((s) => s.trim()).filter(Boolean); if (slug === "toplanti-notu-yapilandirici") { const groups: Record<string, string[]> = { Decisions: [], Actions: [], Questions: [], Dates: [], Context: [] }; sentences.forEach((sentence) => { const key = /(karar|decision|beschlossen|决定)/i.test(sentence) ? "Decisions" : /(yapacak|meli|must|will|owner|sorumlu|负责)/i.test(sentence) ? "Actions" : /\?|soru|question|frage|问题/i.test(sentence) ? "Questions" : /\b\d{1,2}[./-]\d{1,2}|temmuz|july|juli|月|cuma|friday/i.test(sentence) ? "Dates" : "Context"; groups[key].push(sentence); }); return { output: Object.entries(groups).map(([key, values]) => `## ${key}\n${values.map((v) => `- ${v}`).join("\n") || "- none identified"}`).join("\n\n"), metrics: [["notes", sentences.length], ["actions", groups.Actions.length]] }; }
    if (slug === "aksiyon-maddesi-cikarici") { const actions = sentences.filter((s) => /(yapacak|etmeli|malı|must|should|will|action|bis|soll|需要|应当)/i.test(s)); return { output: actions.map((action, i) => { const owner = action.match(/^\p{L}+(?:\s+\p{L}+)?/u)?.[0] ?? "confirm"; const date = action.match(/\b(?:\d{4}-\d{2}-\d{2}|\d{1,2}[./-]\d{1,2}(?:[./-]\d{2,4})?|tomorrow|friday|yarın|cuma|morgen|freitag|明天|周五)\b/i)?.[0] ?? "confirm"; return `${i + 1}. ${action}\n   ${localized(locale, { tr: "Sahip", en: "Owner", de: "Verantwortlich", zh: "负责人" })}: ${owner}\n   ${localized(locale, { tr: "Tarih", en: "Due", de: "Termin", zh: "截止" })}: ${date}\n   ${localized(locale, { tr: "Kanıt", en: "Evidence", de: "Nachweis", zh: "证据" })}: confirm`; }).join("\n\n") || localized(locale, { tr: "Açık bir aksiyon ifadesi bulunamadı.", en: "No explicit action phrase was found.", de: "Keine eindeutige Aufgabe gefunden.", zh: "未找到明确行动项。" }), metrics: [[localized(locale, { tr: "aksiyon", en: "actions", de: "Aufgaben", zh: "行动项" }), actions.length]], warning: actions.some((action) => !/^\p{L}+/u.test(action)) ? localized(locale, { tr: "Sahip çıkarımı dil kalıbına dayanır; toplantı sahibiyle doğrulayın.", en: "Owner extraction is pattern-based; confirm it with the meeting owner.", de: "Die Zuständigkeit wird per Muster erkannt und muss bestätigt werden.", zh: "负责人提取基于模式，请与会议负责人确认。" }) : undefined }; }
    if (slug === "baslik-varyasyon-laboratuvari") { const base = input.trim().replace(/[.!?]+$/, ""); const suffix = { tr: ["hızlı ve yerel sonuç", "veriniz cihazınızdan çıkmaz", "nasıl güvenli kullanılır?", "adım adım tarayıcı içi çalışma"], en: ["a faster local result", "your data stays on your device", "how do you use it safely?", "a step-by-step browser workflow"], de: ["schnelles lokales Ergebnis", "Ihre Daten bleiben auf dem Gerät", "wie lässt es sich sicher nutzen?", "Schritt für Schritt im Browser"], zh: ["更快的本地结果", "数据留在您的设备上", "如何安全使用？", "分步浏览器工作流"] }[locale]; return { output: [`Direct · ${base}`, `Outcome · ${base}: ${suffix[0]}`, `Trust · ${base} — ${suffix[1]}`, `Question · ${base}：${suffix[2]}`, `Specific · ${base}: ${suffix[3]}`].join("\n"), metrics: [[localized(locale, { tr: "varyasyon", en: "variants", de: "Varianten", zh: "变体" }), 5]], warning: localized(locale, { tr: "Başlıklar vaat değil hipotezdir; yalnızca sayfadaki gerçek özellikleri anlatan varyasyonu kullanın.", en: "Headlines are hypotheses, not promises; use only a variant that reflects the real page.", de: "Überschriften sind Hypothesen, keine Versprechen; nur reale Seiteneigenschaften nennen.", zh: "标题是待验证假设而非承诺；仅使用符合页面真实功能的版本。" }) }; }
    if (slug === "atif-yer-tutucu-denetleyici") { const found = input.split(/\r?\n/).flatMap((line, i) => /\b(TODO|REF\??|citation needed|kaynak gerekli|quelle nötig|需要来源)\b/i.test(line) ? [`line ${i + 1}: ${line.trim()}`] : []); return { output: found.join("\n") || "No configured citation placeholder found.", metrics: [["placeholders", found.length]] }; }
    const flags: string[] = []; sentences.forEach((sentence, i) => { const words = sentence.split(/\s+/).length; if (words > 24) flags.push(`Sentence ${i + 1}: ${words} words; consider splitting after the main claim.`); if (/(her normal kullanıcı|yaşlılar.*yapamaz|adam|guys|crazy|insane|obviously|everyone knows)/i.test(sentence)) flags.push(`Sentence ${i + 1}: review potentially excluding or overgeneralized language.`); if (/[A-ZÇĞİÖŞÜ]{8,}/.test(sentence)) flags.push(`Sentence ${i + 1}: abrupt all-caps emphasis may break tone consistency.`); }); const replacements: Array<[RegExp, string]> = [[/gerçekleştirilmesi planlanmakta olan/gi, "planlanan"], [/yapılacağı öngörülmektedir/gi, "yapılması bekleniyor"], [/tarafınıza/gi, "size"], [/in order to/gi, "to"], [/due to the fact that/gi, "because"], [/obviously|everyone knows/gi, "evidence suggests"]]; const revised = sentences.map((sentence) => replacements.reduce((text, [pattern, replacement]) => text.replace(pattern, replacement), sentence).replace(/\s+/g, " ")).join("\n"); return { output: `${localized(locale, { tr: "ÖNCE", en: "BEFORE", de: "VORHER", zh: "原文" })}\n${input.trim()}\n\n${localized(locale, { tr: "ÖNERİLEN DÜZENLEME", en: "SUGGESTED REVISION", de: "VORSCHLAG", zh: "建议修订" })}\n${revised}\n\n${localized(locale, { tr: "İNCELEME NOTLARI", en: "REVIEW NOTES", de: "PRÜFHINWEISE", zh: "审核说明" })}\n${flags.map((flag) => `- ${flag}`).join("\n") || `- ${localized(locale, { tr: "Yapılandırılmış bir sorun bulunmadı; hedef kitleyle anlam kontrolü yapın.", en: "No configured issue found; verify meaning with the intended audience.", de: "Kein konfiguriertes Problem gefunden; Bedeutung mit Zielgruppe prüfen.", zh: "未发现已配置问题；请与目标受众核对含义。" })}`}`, metrics: [[localized(locale, { tr: "cümle", en: "sentences", de: "Sätze", zh: "句子" }), sentences.length], [localized(locale, { tr: "inceleme", en: "review items", de: "Prüfpunkte", zh: "审核项" }), flags.length]], warning: localized(locale, { tr: "Düzenleme kural tabanlı bir taslaktır; anlam, ton ve kapsayıcılık için insan incelemesi gerekir.", en: "The revision is a rule-based draft; human review is required for meaning, tone, and inclusion.", de: "Der Vorschlag ist regelbasiert; Bedeutung, Ton und Inklusion müssen menschlich geprüft werden.", zh: "修订为规则生成草稿；语义、语气与包容性仍需人工审核。" }) };
  }
  throw new Error("This tool configuration is incomplete.");
}

export function ExpansionWorkbench({ slug, locale }: { slug: string; locale: Locale }) {
  const labels = copy[locale]; const tool = getTool(slug); const sample = examples[slug] ?? [""];
  const [input, setInput] = useState(""); const [secondary, setSecondary] = useState(""); const [mode, setMode] = useState("default"); const [output, setOutput] = useState(""); const [metrics, setMetrics] = useState<Array<[string, string | number]>>([]); const [notice, setNotice] = useState<{ kind: "idle" | "busy" | "success" | "error"; text: string }>({ kind: "idle", text: "" }); const [warning, setWarning] = useState("");
  const modeOptions = useMemo(() => slug === "csv-birlestirme-simulatoru" ? [["default", "left join"], ["inner", "inner join"], ["full", "full join"]] : [["default", locale === "tr" ? "ileri dönüşüm" : "forward"], ["reverse", locale === "tr" ? "ters dönüşüm" : "reverse"]], [slug, locale]);
  function reset() { setOutput(""); setMetrics([]); setNotice({ kind: "idle", text: "" }); setWarning(""); }
  function loadDemo() { setInput(sample[0]); setSecondary(sample[1] ?? ""); setMode("default"); reset(); }
  async function run() { setNotice({ kind: "busy", text: labels.running }); await new Promise<void>((resolve) => requestAnimationFrame(() => resolve())); try { if (!input.trim()) throw new Error(locale === "tr" ? "Önce bir girdi ekleyin veya örnek veriyi yükleyin." : "Enter input or load the example first."); if (dualInput.has(slug) && !secondary.trim()) throw new Error(locale === "tr" ? "Bu araç için ikinci girdi de gereklidir." : "This tool also requires the second input."); const result = processTool(slug, input.slice(0, 150_000), secondary.slice(0, 150_000), mode, locale); setOutput(result.output); setMetrics(result.metrics ?? []); setWarning(result.warning ?? ""); setNotice({ kind: "success", text: labels.done }); } catch (error) { setOutput(""); setMetrics([]); setWarning(""); setNotice({ kind: "error", text: `${labels.error}: ${error instanceof Error ? error.message : String(error)}` }); } }
  async function copyOutput() { if (!output) return; try { await navigator.clipboard.writeText(output); setNotice({ kind: "success", text: labels.copied }); } catch { setNotice({ kind: "error", text: labels.error }); } }
  function download() { if (!output) return; const url = URL.createObjectURL(new Blob([output], { type: "text/plain;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `bytequant-${slug}.txt`; anchor.click(); URL.revokeObjectURL(url); }
  return <section className="workbench expansion-workbench" aria-busy={notice.kind === "busy"}>
    <div className="workbench-bar"><span className="local-status"><i />{labels.local}<small>{tool?.title[locale]}</small></span><div className="workbench-bar-actions"><button type="button" className="demo-button" onClick={loadDemo}>{labels.demo}</button><button type="button" className="ghost-button" onClick={() => { setInput(""); setSecondary(""); reset(); }}>{labels.clear}</button></div></div>
    <div className="workbench-grid"><div className="workbench-inputs"><label className="field-label"><span>{labels.input}</span><textarea value={input} rows={11} maxLength={150000} onChange={(event) => { setInput(event.target.value); reset(); }} spellCheck={false} /><small className="field-counter">{input.length.toLocaleString()} / 150,000</small></label>{dualInput.has(slug) && <label className="field-label"><span>{labels.second}</span><textarea value={secondary} rows={7} maxLength={150000} onChange={(event) => { setSecondary(event.target.value); reset(); }} spellCheck={false} /></label>}{modeTools.has(slug) && <label className="field-label compact-field"><span>{labels.mode}</span><select value={mode} onChange={(event) => { setMode(event.target.value); reset(); }}>{modeOptions.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>}<button type="button" className="primary-button run-button" disabled={notice.kind === "busy"} onClick={() => void run()}>{notice.kind === "busy" ? labels.running : labels.run}<span aria-hidden="true"> →</span></button></div>
      <div className="result-panel" aria-live="polite"><div className="result-header"><span>{labels.output}</span><div className="output-actions"><button type="button" disabled={!output} onClick={() => void copyOutput()}>{labels.copy}</button><button type="button" disabled={!output} onClick={download}>{labels.download}</button></div></div>{metrics.length > 0 && <div className="metric-strip">{metrics.map(([label, value]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div>}<pre className={output ? "has-output" : ""}>{output || labels.empty}</pre>{warning && <div className="tool-notice warning" role="note"><strong>Review boundary</strong><span>{warning}</span></div>}{notice.text && <div className={`tool-notice ${notice.kind}`} role={notice.kind === "error" ? "alert" : "status"}><strong>{notice.kind === "error" ? labels.error : notice.kind === "busy" ? labels.running : labels.done}</strong><span>{notice.text}</span></div>}{notice.kind === "success" && <div className="workbench-trust-card"><span aria-hidden="true">✓</span><p>{labels.privacy}</p></div>}</div></div>
  </section>;
}
