"use client";

import { useMemo, useState } from "react";
import type { Locale } from "../lib/site";
import { getTool } from "../lib/tools";
import { frontierToolSlugs } from "../lib/frontier-tools";
import { StructuredToolOutput } from "./StructuredToolOutput";
import { ToolNotice } from "./ToolNotice";

type Result = { output: string; metrics?: Array<[string, string | number]>; warning?: string };
type Demo = { input: string; secondary?: string; mode?: string };

const lines = (value: string) => value.split(/\r?\n/u).map((line) => line.trim()).filter(Boolean);
const words = (value: string) => value.toLocaleLowerCase().match(/[\p{L}\p{N}]+/gu) ?? [];
const escapeHtml = (value: string) => value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");
const pairs = (value: string) => Object.fromEntries(lines(value).map((line) => { const i = line.indexOf("="); if (i < 1) throw new Error(`Expected key=value: ${line}`); return [line.slice(0, i).trim(), line.slice(i + 1).trim()]; }));
const num = (value: string | undefined, name: string, min = -Infinity) => { const parsed = Number(value); if (!Number.isFinite(parsed) || parsed < min) throw new Error(`${name} must be a number${Number.isFinite(min) ? ` ≥ ${min}` : ""}.`); return parsed; };
const table = (rows: Array<Array<string | number>>) => rows.map((row) => `| ${row.map((cell) => String(cell).replace(/\|/g, "\\|")).join(" | ")} |`).join("\n");
const format = (value: number, digits = 2) => new Intl.NumberFormat("en-US", { maximumFractionDigits: digits }).format(value);

function parseCsv(input: string, delimiter?: string) {
  const first = input.split(/\r?\n/u)[0] ?? "";
  const selected = delimiter ?? [",", ";", "\t", "|"].sort((a, b) => first.split(b).length - first.split(a).length)[0];
  const result: string[][] = []; let row: string[] = []; let cell = ""; let quote = false;
  for (let i = 0; i < input.length; i += 1) { const ch = input[i]; if (ch === '"') { if (quote && input[i + 1] === '"') { cell += '"'; i += 1; } else quote = !quote; } else if (ch === selected && !quote) { row.push(cell); cell = ""; } else if ((ch === "\n" || ch === "\r") && !quote) { if (ch === "\r" && input[i + 1] === "\n") i += 1; row.push(cell); result.push(row); row = []; cell = ""; } else cell += ch; }
  if (quote) throw new Error("Unclosed CSV quote."); if (cell || row.length) { row.push(cell); result.push(row); } return { rows: result, delimiter: selected };
}
function csvCell(value: string) { return /[",\r\n]/.test(value) ? `"${value.replace(/"/g, '""')}"` : value; }
function byteBase32(bytes: Uint8Array) { const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567"; let bits = ""; bytes.forEach((byte) => { bits += byte.toString(2).padStart(8, "0"); }); let out = ""; for (let i = 0; i < bits.length; i += 5) out += alphabet[Number.parseInt(bits.slice(i, i + 5).padEnd(5, "0"), 2)]; return out.padEnd(Math.ceil(out.length / 8) * 8, "="); }
function base32Bytes(value: string) { const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567"; const clean = value.toUpperCase().replace(/=+$/u, "").replace(/\s+/gu, ""); if (!clean || [...clean].some((ch) => !alphabet.includes(ch))) throw new Error("Invalid RFC 4648 Base32 input."); let bits = ""; [...clean].forEach((ch) => { bits += alphabet.indexOf(ch).toString(2).padStart(5, "0"); }); return Uint8Array.from((bits.match(/.{8}/g) ?? []).map((part) => Number.parseInt(part, 2))); }
function levenshtein(a: string, b: string) { const prev = Array.from({ length: b.length + 1 }, (_, i) => i); for (let i = 1; i <= a.length; i += 1) { let diagonal = prev[0]; prev[0] = i; for (let j = 1; j <= b.length; j += 1) { const above = prev[j]; prev[j] = Math.min(prev[j] + 1, prev[j - 1] + 1, diagonal + Number(a[i - 1] !== b[j - 1])); diagonal = above; } } return prev[b.length]; }
function safeJson(value: string) { try { return JSON.parse(value) as unknown; } catch (error) { throw new Error(`Invalid JSON: ${error instanceof Error ? error.message : String(error)}`); } }
function b64url(value: string) { const compact = value.replace(/-/g, "+").replace(/_/g, "/"); const bytes = Uint8Array.from(atob(compact.padEnd(Math.ceil(compact.length / 4) * 4, "=")), (ch) => ch.charCodeAt(0)); return new TextDecoder().decode(bytes); }

export const frontierDemos: Record<string, Demo> = {
  "prompt-negatif-kisit-denetleyici": { input: "Yanıt yalnızca JSON olmalıdır.\nAsla JSON kullanma.\nEn fazla 100 kelime yaz.\nEn az 250 kelime ayrıntı ver." },
  "prompt-degisken-tip-denetleyici": { input: "name|string|required\nage|number|required\ntags|array|optional", secondary: '{"name":"Ada","age":32,"tags":["editor"]}' },
  "prompt-cikti-belirlilik-denetleyici": { input: "Konuyu uygun şekilde anlat ve benzeri ayrıntıları ekle. İyi bir sonuç üret." },
  "prompt-ornek-denge-analizoru": { input: "positive|Ürünü sevdim|olumlu\nneutral|Paket geldi|nötr\nnegative|Uygulama kapanıyor|olumsuz\npositive|Çok kullanışlı|olumlu" },
  "prompt-yerellestirme-kontrol-listesi": { input: "Hello {{name}}, order #42 is ready: https://example.com/42", secondary: "Hallo {{name}}, Bestellung ist fertig: https://example.com/42" },
  "prompt-bagimlilik-grafi-cikarici": { input: "collect:\nclean:collect\nvalidate:clean\nexport:validate" },
  "prompt-rubrik-puanlayici": { input: "accuracy|40|90\nclarity|30|80\nsafety|30|100" },
  "prompt-tutarlilik-senaryo-testi": { input: "Yanıt en fazla 100 kelime olmalı.\nYanıt en az 300 kelime olmalı.\nKaynak uydurma.\nKaynakları tahmin et." },
  "cumle-uzunluk-dagilimi": { input: "Kısa cümle. Bu biraz daha uzun ve açıklayıcı bir cümledir. Okuyucunun aynı anda çok fazla kavramı takip etmesini isteyen, yan tümceler ve açıklamalarla uzayan bu örnek cümle düzenleme sırasında bölünebilir." },
  "tekrar-eden-ifade-bulucu": { input: "Yerel araç hızlıdır. Yerel araç gizlidir. Bu yerel araç tarayıcıda çalışır." },
  "liste-tutarlilik-denetleyici": { input: "- İlk adım.\n- İkinci adım\n* İkinci adım\n4. Son adım." },
  "noktalama-tirnak-normalizasyonu": { input: "  “Merhaba”  --  ByteQuant…  " },
  "kisaltma-sozluk-cikarici": { input: "Content Security Policy (CSP) tarayıcı güvenliğini güçlendirir. CSP düzenli olarak test edilmelidir. SRI de kaynak bütünlüğüne yardım eder." },
  "sade-dil-kontrolu": { input: "İşbu dokümantasyon kapsamında kullanıcıların söz konusu konfigürasyon işlemlerini gerçekleştirmeleri gerekmektedir. Ayarı açın ve sonucu kontrol edin." },
  "baslik-hiyerarsisi-denetleyici": { input: "# Başlık\n### Atlanan seviye\n## Bölüm\n## Bölüm\n#### Alt başlık" },
  "terim-tutarlilik-denetleyici": { input: "Kullanıcı hesabına giriş yapar. Müşteri profili açılır. Üye ayarları değiştirir.", secondary: "kullanıcı=müşteri,üye\ngiriş yap=oturum aç" },
  "paragraf-gecis-analizoru": { input: "Yerel araçlar veriyi cihazda işler. Bu yaklaşım aktarımı azaltır.\n\nBununla birlikte, kullanıcı çıktıyı yine doğrulamalıdır.\n\nPazarlama planı gelecek hafta başlar." },
  "json-yol-degeri-cikarici": { input: '{"user":{"name":"Ada","roles":["editor","reviewer"]}}', secondary: "user.roles[1]" },
  "json-ornek-veri-uretici": { input: '{"type":"object","required":["name"],"properties":{"name":{"type":"string","example":"Ada"},"active":{"type":"boolean"},"score":{"type":"number"}}}' },
  "csv-sutun-yeniden-adlandirici": { input: "ad,rol,aktif\nAda,Editör,true", secondary: "ad=name\nrol=role\naktif=active" },
  "csv-ayirac-tespit-araci": { input: "name;role;active\nAda;Editor;true\nLin;Reviewer;false" },
  "ndjson-toplu-dogrulayici": { input: '{"id":1,"ok":true}\n{"id":2,"ok":false}\n{"id":3,"ok":}' },
  "sql-parametre-listesi-olusturucu": { input: "SELECT * FROM users WHERE tenant_id = :tenant AND id = $1 AND state = ?" },
  "url-yol-segmenti-analizoru": { input: "https://example.com/docs/%E2%9C%93/../report%2520final" },
  "accept-language-ayristirici": { input: "tr-TR,tr;q=0.9,en-US;q=0.8,en;q=0.7,*;q=0.1" },
  "etag-karsilastirici": { input: '"v42"', secondary: 'W/"v42"\n"v41"\n"v42"' },
  "json-nesne-birlestirme-stratejisi": { input: '{"user":{"name":"Ada","roles":["reader"]},"active":true}', secondary: '{"user":{"roles":["editor"],"team":"docs"},"active":false}' },
  "json-dizi-sayfalama-planlayici": { input: '["a","b","c","d","e","f","g"]', secondary: "page=2\nsize=3" },
  "graphql-islem-envanteri": { input: "query GetUser($id: ID!) { user(id:$id){id name} }\nmutation UpdateName { updateName(name:\"Ada\"){id} }\nfragment UserFields on User { id name }" },
  "http-link-basligi-ayristirici": { input: '<https://api.example.com/items?page=2>; rel="next"; title="page, two", <https://api.example.com/items?page=5>; rel="last"' },
  "toml-json-donusturucu": { input: "title = \"ByteQuant\"\nactive = true\n[owner]\nname = \"Ada\"\ncount = 3", mode: "toml-json" },
  "base32-kodlayici": { input: "ByteQuant privacy tools", mode: "encode" },
  "hex-metin-donusturucu": { input: "Merhaba ByteQuant", mode: "encode" },
  "roma-rakami-donusturucu": { input: "2026" },
  "buyuk-tamsayi-taban-donusturucu": { input: "value=900719925474099312345678901234567890\nfrom=10\nto=36" },
  "ical-etkinlik-olusturucu": { input: "title=ByteQuant review\nstart=20260803T090000Z\nend=20260803T100000Z\nlocation=Online\ndescription=Privacy workflow review" },
  "vcard-kisi-karti-olusturucu": { input: "name=Ada Lovelace\nemail=ada@example.com\nphone=+44 20 0000 0000\norganisation=ByteQuant" },
  "cok-degerli-sorgu-json-donusturucu": { input: "tag=privacy&tag=local&lang=tr", mode: "query-json" },
  "csv-html-tablo-donusturucu": { input: "name,role\nAda,Editor\nLin,<script>alert(1)</script>" },
  "gizlilik-risk-kaydi-olusturucu": { input: "Unintended export|3|5|Data owner|Column allow-list|2\nLong retention|4|4|Privacy lead|Expiry job|2" },
  "veri-minimizasyonu-karar-matrisi": { input: "email|account recovery|yes|30 days|none\nbirth_date|marketing|no|forever|age band\nnotes|support|unknown|90 days|structured tags" },
  "riza-kaydi-sablonu": { input: "purpose=Product updates\nnoticeVersion=privacy-v4\ntimestamp=2026-08-02T10:00:00Z\nmethod=unchecked checkbox\nwithdrawal=https://example.com/preferences" },
  "dpia-on-eleme-sihirbazi": { input: "largeScale=yes\nsensitiveData=yes\nsystematicMonitoring=no\nnovelTechnology=yes\nvulnerablePeople=no\nautomatedDecisions=no" },
  "saklama-suresi-son-tarih-hesaplayici": { input: "support logs|2026-01-15|90|Privacy lead\ninvoices|2026-02-01|3650|Finance" },
  "redaksiyon-tutarlilik-denetleyici": { input: "Ada: ada@example.com, phone +90 555 123 45 67, case REF-4821", secondary: "[NAME]: ada@example.com, phone [PHONE], case REF-4821" },
  "veri-siniflandirma-etiketleyici": { input: "Team plan for next week. Contact ada@example.com. API token sk_live_EXAMPLE_NOT_REAL." },
  "ihlal-bildirim-zaman-cizelgesi": { input: "detected=2026-08-01T08:00:00Z\nassessed=2026-08-01T12:30:00Z\ncontained=2026-08-02T07:00:00Z\nreviewAt=2026-08-03T08:00:00Z" },
  "cerez-envanteri-risk-siniflandirici": { input: "session|bytequant.org|session|authentication\nanalytics_id|third.example|365 days|analytics\nconsent|bytequant.org|180 days|preferences" },
  "csp-kaynak-ifadesi-tester": { input: "default-src 'self'; img-src 'self' https://images.example.com; script-src 'self'", secondary: "https://images.example.com/logo.png" },
  "sri-degeri-dogrulayici": { input: "console.log('ByteQuant');", secondary: "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=" },
  "paket-adi-benzerlik-tarayicisi": { input: "lodahs\nreact-domm\ntypescript", secondary: "lodash\nreact-dom\ntypescript\nnext" },
  "punycode-domain-inceleyici": { input: "example.com\nxn--pple-43d.com\npaypaΙ.com" },
  "jwt-claim-politikasi-denetleyici": { input: "eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJzdWIiOiJkZW1vIiwiYXVkIjoiYnl0ZXF1YW50IiwiaXNzIjoibG9jYWwiLCJleHAiOjIwMDAwMDAwMDB9.", secondary: "aud=bytequant\niss=local\nrequired=sub,exp,aud,iss" },
  "ssh-yetkili-anahtar-inceleyici": { input: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE5vdFJlYWxLZXlGb3JEZW1vT25seTEyMzQ1Njc4OTAx demo@example" },
  "pem-blok-inceleyici": { input: "-----BEGIN CERTIFICATE-----\nU2FmZSBkZW1vIGNvbnRlbnQ=\n-----END CERTIFICATE-----" },
  "git-diff-sir-tarayicisi": { input: "diff --git a/app.ts b/app.ts\n+const token = 'ghp_EXAMPLEONLY12345678901234567890';\n-const debug = true;\n+const mode = 'production';" },
  "api-anahtari-format-on-kontrolu": { input: "sk_test_EXAMPLEONLY_7wH2jK9mP4qR8sT1uV6x" },
  "html-guvenli-atribut-denetleyici": { input: '<a href="javascript:alert(1)" target="_blank">Open</a>\n<img src="demo.png" onerror="alert(1)">' },
  "yuzde-dagilim-dengeleyici": { input: "Design=41\nEngineering=37\nResearch=19" },
  "paket-birim-maliyet-karsilastirici": { input: "Plan A|12.50|500|g\nPlan B|19.90|1.2|kg\nPlan C|8.20|250|g" },
  "calisma-ucreti-esdegerlik-hesaplayici": { input: "annual=72000\nweeks=48\nhoursPerWeek=40" },
  "nakit-pisti-hesaplayici": { input: "cash=180000\nmonthlyRevenue=22000\nmonthlySpend=48000\nbuffer=30000" },
  "stok-yeniden-siparis-hesaplayici": { input: "dailyDemand=18\nleadDays=12\nsafetyStock=75\ncurrentStock=240" },
  "oran-arastirmasi-orneklem-planlayici": { input: "confidence=95\nmargin=5\nproportion=50\npopulation=10000" },
  "guven-araligi-hesaplayici": { input: "mean=42.8\nsd=8.4\nn=64\nconfidence=95" },
  "toplanti-maliyeti-hesaplayici": { input: "durationMinutes=60\npreparationMinutes=15\nAda=45\nLin=60\nDeniz=35" },
  "vardiya-kapsama-hesaplayici": { input: "09:00|4|3\n10:00|5|5\n11:00|6|4\n12:00|3|4" },
  "zaman-bloklama-plani": { input: "09:00\nReview report|60|high\nClean dataset|90|high\nWrite summary|45|medium\nEmail follow-up|20|low", secondary: "break=10" },
  "pomodoro-oturum-planlayici": { input: "start=09:00\nfocus=25\nshortBreak=5\nlongBreak=15\nsessions=6\nlongEvery=4" },
  "etkinlik-kontrol-listesi-olusturucu": { input: "Launch|2026-09-01|Ada\nAccessibility review|2026-08-20|Lin\nPublish guide|2026-08-25|Deniz" },
  "embedding-parca-ortusme-planlayici": { input: "documentTokens=12500\nchunkTokens=800\noverlapTokens=120\nmetadataTokens=40" },
  "arac-cagrisi-json-dogrulayici": { input: '{"name":"json_formatter","arguments":{"indent":2,"input":"{\\"ok\\":true}"}}', secondary: "name=json_formatter\nrequired=indent,input" },
  "doi-toplu-dogrulayici": { input: "https://doi.org/10.1000/xyz123\ndoi:10.5555/12345678\n10.1000/xyz123\ninvalid-doi" },
  "literatur-eleme-karar-gunlugu": { input: "R-001|include|Matches population and outcome|Ada\nR-002|exclude||Lin\nR-002|include|New review|Deniz" },
  "kanit-tablosu-tekillestirici": { input: "10.1000/xyz123|Local-first tools for privacy|2025\n10.1000/xyz123|Local first tools for privacy|2025\n|Browser privacy tool review|2024\n|Browser-based privacy tool review|2024" },
};

const dualSlugs = new Set(["prompt-degisken-tip-denetleyici", "prompt-yerellestirme-kontrol-listesi", "terim-tutarlilik-denetleyici", "json-yol-degeri-cikarici", "csv-sutun-yeniden-adlandirici", "etag-karsilastirici", "json-nesne-birlestirme-stratejisi", "json-dizi-sayfalama-planlayici", "csp-kaynak-ifadesi-tester", "sri-degeri-dogrulayici", "jwt-claim-politikasi-denetleyici", "zaman-bloklama-plani", "arac-cagrisi-json-dogrulayici", "redaksiyon-tutarlilik-denetleyici", "paket-adi-benzerlik-tarayicisi"]);
const modeOptions: Record<string, Array<[string, string]>> = {
  "toml-json-donusturucu": [["toml-json", "TOML → JSON"], ["json-toml", "JSON → TOML"]], "base32-kodlayici": [["encode", "Text → Base32"], ["decode", "Base32 → text"]], "hex-metin-donusturucu": [["encode", "Text → HEX"], ["decode", "HEX → text"]], "cok-degerli-sorgu-json-donusturucu": [["query-json", "Query → JSON"], ["json-query", "JSON → query"]], "json-nesne-birlestirme-stratejisi": [["deep", "Deep merge"], ["shallow", "Shallow merge"]],
};

export async function runFrontierTool(slug: string, input: string, secondary = "", mode = "default"): Promise<Result> {
  if (!frontierToolSlugs.has(slug)) throw new Error(`Unsupported frontier tool: ${slug}`);
  const boundary = "Review the result in its real context; this local pre-check does not make an external guarantee.";
  if (slug === "prompt-negatif-kisit-denetleyici" || slug === "prompt-tutarlilik-senaryo-testi") { const rows = lines(input); const conflicts: string[] = []; const max = rows.flatMap((r) => [...r.matchAll(/(?:en fazla|at most|max(?:imum)?)[^0-9]*(\d+)/gi)].map((m) => Number(m[1]))); const min = rows.flatMap((r) => [...r.matchAll(/(?:en az|at least|min(?:imum)?)[^0-9]*(\d+)/gi)].map((m) => Number(m[1]))); if (max.length && min.length && Math.min(...max) < Math.max(...min)) conflicts.push(`Numeric conflict: minimum ${Math.max(...min)} exceeds maximum ${Math.min(...max)}.`); const tokens = rows.map((r) => new Set(words(r))); rows.forEach((row, i) => rows.slice(i + 1).forEach((other, j) => { const overlap = [...tokens[i]].filter((w) => tokens[i + j + 1].has(w) && w.length > 4); if (overlap.length >= 2 && /(?:asla|kullanma|never|must not|do not)/i.test(row + other) !== /(?:asla|kullanma|never|must not|do not)/i.test(row) && /(?:zorunlu|olmalı|must|required|use)/i.test(row + other)) conflicts.push(`Lines ${i + 1}/${i + j + 2}: review ${overlap.slice(0, 3).join(", ")}.`); })); return { output: `${conflicts.join("\n") || "✓ No obvious requirement/prohibition conflict found."}\n\nRules reviewed: ${rows.length}`, metrics: [["rules", rows.length], ["conflicts", conflicts.length]], warning: boundary }; }
  if (slug === "prompt-degisken-tip-denetleyici") { const defs = lines(input).map((r) => { const [name, type, requirement] = r.split("|"); return { name, type, required: requirement === "required" }; }); const value = safeJson(secondary) as Record<string, unknown>; if (!value || Array.isArray(value) || typeof value !== "object") throw new Error("Example must be a JSON object."); const issues: string[] = []; defs.forEach((d) => { const actual = Array.isArray(value[d.name]) ? "array" : typeof value[d.name]; if (d.required && !(d.name in value)) issues.push(`${d.name}: missing required value`); else if (d.name in value && actual !== d.type) issues.push(`${d.name}: expected ${d.type}, received ${actual}`); }); Object.keys(value).filter((key) => !defs.some((d) => d.name === key)).forEach((key) => issues.push(`${key}: undeclared variable`)); return { output: issues.join("\n") || "✓ Example satisfies the declared variable contract.", metrics: [["variables", defs.length], ["issues", issues.length]], warning: boundary }; }
  if (slug === "prompt-cikti-belirlilik-denetleyici") { const vague = ["appropriate", "suitable", "good", "etc", "and so on", "uygun", "iyi", "vesaire", "benzeri"].filter((term) => input.toLocaleLowerCase().includes(term)); const anchors = [/(?:json|csv|table|list|tablo|liste)/i, /(?:schema|şema|required|zorunlu)/i, /(?:maximum|minimum|en fazla|en az)/i].filter((r) => r.test(input)).length; return { output: `Ambiguous terms: ${vague.join(", ") || "none found"}\nOutput-contract anchors: ${anchors}/3\n\nRecommendation: name the format, required fields, limits, and failure behaviour.`, metrics: [["vague terms", vague.length], ["anchors", anchors]], warning: boundary }; }
  if (slug === "prompt-ornek-denge-analizoru") { const rows = lines(input).map((r) => r.split("|")); const counts = new Map<string, number>(); rows.forEach((r) => counts.set(r[0], (counts.get(r[0]) ?? 0) + 1)); const duplicate = rows.length - new Set(rows.map((r) => r.slice(1).join("|").toLowerCase())).size; return { output: `${table([["class", "count"], ...[...counts]])}\n\nLength range: ${Math.min(...rows.map((r) => r.join(" ").length))}–${Math.max(...rows.map((r) => r.join(" ").length))} characters\nDuplicates: ${duplicate}`, metrics: [["examples", rows.length], ["classes", counts.size], ["duplicates", duplicate]], warning: boundary }; }
  if (slug === "prompt-yerellestirme-kontrol-listesi") { const extract = (v: string) => new Set([...(v.match(/\{\{[^}]+\}\}|https?:\/\/\S+|\b\d+(?:[.,]\d+)?\b/g) ?? [])]); const a = extract(input), b = extract(secondary); const missing = [...a].filter((x) => !b.has(x)), added = [...b].filter((x) => !a.has(x)); return { output: `Missing from translation: ${missing.join(", ") || "none"}\nUnexpected in translation: ${added.join(", ") || "none"}\n\nSource tokens: ${a.size}; translation tokens: ${b.size}`, metrics: [["missing", missing.length], ["unexpected", added.length]], warning: boundary }; }
  if (slug === "prompt-bagimlilik-grafi-cikarici") { const graph = new Map(lines(input).map((r) => { const [n, deps = ""] = r.split(":"); return [n.trim(), deps.split(",").map((x) => x.trim()).filter(Boolean)]; })); const missing = [...graph.values()].flat().filter((d) => !graph.has(d)); const out: string[] = []; const state = new Map<string, number>(); const cycles: string[] = []; const visit = (n: string, trail: string[]) => { if (state.get(n) === 1) { cycles.push([...trail, n].join(" → ")); return; } if (state.get(n) === 2) return; state.set(n, 1); (graph.get(n) ?? []).forEach((d) => visit(d, [...trail, n])); state.set(n, 2); out.push(n); }; graph.forEach((_, n) => visit(n, [])); return { output: `Execution order: ${out.join(" → ")}\nMissing dependencies: ${[...new Set(missing)].join(", ") || "none"}\nCycles: ${cycles.join("; ") || "none"}`, metrics: [["steps", graph.size], ["cycles", cycles.length]], warning: boundary }; }
  if (slug === "prompt-rubrik-puanlayici") { const rows = lines(input).map((r) => { const [name, w, s] = r.split("|"); return { name, weight: num(w, name, 0), score: num(s, name, 0) }; }); const weight = rows.reduce((a, b) => a + b.weight, 0), total = rows.reduce((a, b) => a + b.weight * b.score, 0) / (weight || 1); return { output: `${table([["criterion", "weight", "score", "contribution"], ...rows.map((r) => [r.name, r.weight, r.score, format(r.weight * r.score / 100)])])}\n\nWeighted score: ${format(total, 2)}/100\nWeight total: ${format(weight)}%${weight !== 100 ? " ⚠ expected 100%" : " ✓"}`, metrics: [["score", format(total)], ["weight", `${weight}%`]], warning: boundary }; }
  if (["cumle-uzunluk-dagilimi", "sade-dil-kontrolu", "paragraf-gecis-analizoru"].includes(slug)) { const sentences = input.split(/(?<=[.!?。！？])\s+/u).filter(Boolean); const lengths = sentences.map((s) => words(s).length); const long = lengths.filter((n) => n > 24).length; const paragraphs = input.split(/\n\s*\n/u).filter(Boolean); const connectors = paragraphs.slice(1).filter((p) => /^(however|therefore|also|meanwhile|but|so|bununla|bu nedenle|ayrıca|ancak)/i.test(p)).length; const jargon = (input.match(/(?:gerçekleştir|kapsamında|hususunda|utili[sz]e|aforementioned|leverage)/gi) ?? []).length; return { output: `${table([["bucket", "sentences"], ["1–8 words", lengths.filter((n) => n <= 8).length], ["9–16", lengths.filter((n) => n > 8 && n <= 16).length], ["17–24", lengths.filter((n) => n > 16 && n <= 24).length], ["25+", long]])}\n\nParagraphs: ${paragraphs.length}\nExplicit transitions: ${connectors}\nJargon signals: ${jargon}\nLongest sentence: ${Math.max(...lengths, 0)} words`, metrics: [["sentences", sentences.length], ["long", long], ["jargon", jargon]], warning: boundary }; }
  if (slug === "tekrar-eden-ifade-bulucu") { const w = words(input); const found: Array<[string, number]> = []; for (let n = 2; n <= 5; n += 1) { const map = new Map<string, number>(); for (let i = 0; i <= w.length - n; i += 1) { const phrase = w.slice(i, i + n).join(" "); map.set(phrase, (map.get(phrase) ?? 0) + 1); } map.forEach((count, phrase) => { if (count > 1) found.push([phrase, count]); }); } found.sort((a, b) => b[1] - a[1] || b[0].length - a[0].length); return { output: found.length ? table([["phrase", "count"], ...found.slice(0, 30)]) : "✓ No repeated two-to-five-word phrase found.", metrics: [["words", w.length], ["repeats", found.length]], warning: boundary }; }
  if (slug === "liste-tutarlilik-denetleyici") { const rows = lines(input); const styles = new Set(rows.map((r) => /^[-*+] /.test(r) ? r[0] : /^\d+[.)] /.test(r) ? "number" : "plain")); const contents = rows.map((r) => r.replace(/^(?:[-*+] |\d+[.)] )/u, "").trim()); const duplicates = contents.filter((v, i) => contents.indexOf(v) !== i); const punctuation = new Set(contents.map((v) => /[.!?;:]$/u.test(v))); return { output: `Styles: ${[...styles].join(", ")}\nDuplicate items: ${[...new Set(duplicates)].join("; ") || "none"}\nEnd-punctuation styles: ${punctuation.size}\n\n${styles.size > 1 || punctuation.size > 1 ? "⚠ Normalise list style before publication." : "✓ List style is consistent."}`, metrics: [["items", rows.length], ["styles", styles.size], ["duplicates", duplicates.length]], warning: boundary }; }
  if (slug === "noktalama-tirnak-normalizasyonu") { const output = input.replace(/[“”„]/g, '"').replace(/[‘’]/g, "'").replace(/\s*(?:—|–|--+)\s*/g, " — ").replace(/\s+([,.;:!?])/g, "$1").replace(/[ \t]{2,}/g, " ").trim(); return { output, metrics: [["changed characters", [...input].filter((ch, i) => ch !== output[i]).length], ["output length", output.length]], warning: boundary }; }
  if (slug === "kisaltma-sozluk-cikarici") { const matches = input.match(/\b[A-ZÇĞİÖŞÜ][A-ZÇĞİÖŞÜ0-9-]{1,}\b/g) ?? []; const acronyms = [...new Set(matches)]; const rows = acronyms.map((a) => { const definition = new RegExp(`([\\p{L}][\\p{L} -]{2,80}) \\(${a.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\)`, "u").exec(input)?.[1]?.trim() ?? "not found"; return [a, matches.filter((v) => v === a).length, definition]; }); return { output: table([["acronym", "uses", "first definition"], ...rows]), metrics: [["acronyms", acronyms.length], ["undefined", rows.filter((r) => r[2] === "not found").length]], warning: boundary }; }
  if (slug === "baslik-hiyerarsisi-denetleyici") { const headings = lines(input).map((line, i) => ({ line: i + 1, level: line.match(/^(#{1,6})\s+/)?.[1].length ?? 0, text: line.replace(/^#{1,6}\s*/u, "") })).filter((h) => h.level); const issues: string[] = []; headings.forEach((h, i) => { if (!h.text) issues.push(`Line ${h.line}: empty heading`); if (i && h.level > headings[i - 1].level + 1) issues.push(`Line ${h.line}: jumps H${headings[i - 1].level} → H${h.level}`); }); const dup = headings.filter((h, i) => headings.findIndex((x) => x.text.toLowerCase() === h.text.toLowerCase()) !== i); dup.forEach((h) => issues.push(`Line ${h.line}: duplicate “${h.text}”`)); return { output: issues.join("\n") || "✓ Heading hierarchy is sequential and unique.", metrics: [["headings", headings.length], ["issues", issues.length]], warning: boundary }; }
  if (slug === "terim-tutarlilik-denetleyici") { const rules = lines(secondary).map((r) => { const [preferred, alternatives = ""] = r.split("="); return { preferred, alternatives: alternatives.split(",").filter(Boolean) }; }); const findings = rules.flatMap((r) => r.alternatives.map((a) => [r.preferred, a, (input.toLocaleLowerCase().match(new RegExp(a.toLocaleLowerCase().replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "gu")) ?? []).length] as [string, string, number])).filter((r) => r[2]); return { output: findings.length ? table([["preferred", "variant", "uses"], ...findings]) : "✓ No disallowed terminology variant found.", metrics: [["rules", rules.length], ["variant uses", findings.reduce((s, r) => s + r[2], 0)]], warning: boundary }; }
  if (slug === "json-yol-degeri-cikarici") { const root = safeJson(input); const parts = secondary.replace(/\[(\d+)\]/g, ".$1").split(".").filter(Boolean); let current: unknown = root; for (const part of parts) { if (current === null || typeof current !== "object" || !(part in current)) throw new Error(`Path not found at ${part}.`); current = (current as Record<string, unknown>)[part]; } return { output: JSON.stringify(current, null, 2), metrics: [["path segments", parts.length], ["result type", Array.isArray(current) ? "array" : typeof current]], warning: boundary }; }
  if (slug === "json-ornek-veri-uretici") { const schema = safeJson(input) as Record<string, unknown>; const build = (node: Record<string, unknown>, depth = 0): unknown => { if (depth > 8) throw new Error("Schema nesting exceeds 8 levels."); if ("example" in node) return node.example; if (node.type === "object") return Object.fromEntries(Object.entries((node.properties ?? {}) as Record<string, Record<string, unknown>>).map(([k, v]) => [k, build(v, depth + 1)])); if (node.type === "array") return [build((node.items ?? { type: "string" }) as Record<string, unknown>, depth + 1)]; if (node.type === "number" || node.type === "integer") return node.minimum ?? 0; if (node.type === "boolean") return false; if (Array.isArray(node.enum)) return node.enum[0]; return "example"; }; const output = build(schema); return { output: JSON.stringify(output, null, 2), metrics: [["bytes", JSON.stringify(output).length], ["root type", Array.isArray(output) ? "array" : typeof output]], warning: boundary }; }
  if (slug === "csv-sutun-yeniden-adlandirici") { const parsed = parseCsv(input); const mapping = pairs(secondary); const [header, ...body] = parsed.rows; const renamed = header.map((h) => mapping[h] ?? h); if (new Set(renamed).size !== renamed.length) throw new Error("Column mapping creates duplicate headers."); return { output: [renamed, ...body].map((r) => r.map(csvCell).join(parsed.delimiter)).join("\n"), metrics: [["columns", header.length], ["renamed", header.filter((h) => mapping[h]).length], ["rows", body.length]], warning: boundary }; }
  if (slug === "csv-ayirac-tespit-araci") { const candidates = [",", ";", "\t", "|"]; const raw = input.split(/\r?\n/u).filter(Boolean); const scored: Array<Array<string | number>> = candidates.map((d) => { const counts = raw.map((r) => r.split(d).length); return [d === "\t" ? "TAB" : d, counts[0], new Set(counts).size === 1 && counts[0] > 1 ? "strong" : counts[0] > 1 ? "inconsistent" : "absent"]; }); return { output: table([["candidate", "columns", "assessment"], ...scored]), metrics: [["rows", raw.length], ["strong candidates", scored.filter((r) => r[2] === "strong").length]], warning: boundary }; }
  if (slug === "ndjson-toplu-dogrulayici") { const rows = input.split(/\r?\n/u); const findings = rows.map((row, i) => { if (!row.trim()) return [i + 1, "blank", "ignored"]; try { const v = JSON.parse(row); return [i + 1, Array.isArray(v) ? "array" : typeof v, "valid"]; } catch (e) { return [i + 1, "error", e instanceof Error ? e.message : String(e)]; } }); return { output: table([["line", "type", "result"], ...findings]), metrics: [["records", findings.filter((r) => r[1] !== "blank").length], ["errors", findings.filter((r) => r[1] === "error").length]], warning: boundary }; }
  if (slug === "sql-parametre-listesi-olusturucu") { const found = [...input.matchAll(/(?<!:):[A-Za-z_][\w]*|\$\d+|\?/g)].map((m) => m[0]); const unique = [...new Set(found)]; return { output: `${table([["parameter", "uses"], ...unique.map((p) => [p, found.filter((x) => x === p).length])])}\n\nSQL was inspected as text and never executed.`, metrics: [["parameters", unique.length], ["occurrences", found.length]], warning: boundary }; }
  if (slug === "url-yol-segmenti-analizoru") { const url = new URL(input); const segments = url.pathname.split("/").map((raw, i) => { let decoded = ""; try { decoded = decodeURIComponent(raw); } catch { decoded = "INVALID ENCODING"; } const flags = [raw === "" ? "empty" : "", decoded === "." || decoded === ".." ? "dot segment" : "", /%25[0-9a-f]{2}/i.test(raw) ? "possible double encoding" : ""].filter(Boolean).join(", "); return [i, raw, decoded, flags || "—"]; }); return { output: table([["#", "raw", "decoded", "review"], ...segments]), metrics: [["segments", segments.length], ["flagged", segments.filter((r) => r[3] !== "—").length]], warning: boundary }; }
  if (slug === "accept-language-ayristirici") { const ranges = input.split(",").map((x, i) => { const [tag, ...params] = x.trim().split(";"); const qText = params.find((p) => p.trim().startsWith("q="))?.split("=")[1] ?? "1"; const q = num(qText, "q", 0); if (q > 1) throw new Error("q must be between 0 and 1."); return { tag, q, order: i, specificity: tag === "*" ? 0 : tag.split("-").length }; }).sort((a, b) => b.q - a.q || b.specificity - a.specificity || a.order - b.order); return { output: table([["priority", "range", "q", "specificity"], ...ranges.map((r, i) => [i + 1, r.tag, r.q, r.specificity])]), metrics: [["ranges", ranges.length], ["excluded", ranges.filter((r) => r.q === 0).length]], warning: boundary }; }
  if (slug === "etag-karsilastirici") { const norm = (x: string) => ({ weak: /^W\//i.test(x.trim()), value: x.trim().replace(/^W\//i, "") }); const current = norm(input); const rows = lines(secondary).map((x) => { const v = norm(x); return [x, !current.weak && !v.weak && current.value === v.value ? "strong match" : current.value === v.value ? "weak match only" : "no match"]; }); return { output: table([["candidate", "comparison"], ...rows]), metrics: [["candidates", rows.length], ["strong", rows.filter((r) => r[1] === "strong match").length]], warning: boundary }; }
  if (slug === "json-nesne-birlestirme-stratejisi") { const a = safeJson(input) as Record<string, unknown>, b = safeJson(secondary) as Record<string, unknown>; const conflicts: string[] = []; const merge = (x: Record<string, unknown>, y: Record<string, unknown>, path = ""): Record<string, unknown> => Object.fromEntries([...new Set([...Object.keys(x), ...Object.keys(y)])].map((k) => { if (!(k in y)) return [k, x[k]]; if (!(k in x)) return [k, y[k]]; const xv = x[k], yv = y[k]; if (mode === "deep" && xv && yv && typeof xv === "object" && typeof yv === "object" && !Array.isArray(xv) && !Array.isArray(yv)) return [k, merge(xv as Record<string, unknown>, yv as Record<string, unknown>, `${path}.${k}`)]; if ((Array.isArray(xv) ? "array" : typeof xv) !== (Array.isArray(yv) ? "array" : typeof yv)) conflicts.push(`${path}.${k}`); return [k, yv]; })); const result = mode === "shallow" ? { ...a, ...b } : merge(a, b); return { output: `${JSON.stringify(result, null, 2)}\n\nType conflicts: ${conflicts.join(", ") || "none"}`, metrics: [["keys", Object.keys(result).length], ["conflicts", conflicts.length]], warning: boundary }; }
  if (slug === "json-dizi-sayfalama-planlayici") { const arr = safeJson(input); if (!Array.isArray(arr)) throw new Error("Input must be a JSON array."); const c = pairs(secondary), page = Math.floor(num(c.page, "page", 1)), size = Math.floor(num(c.size, "size", 1)), pages = Math.ceil(arr.length / size), start = (page - 1) * size, slice = arr.slice(start, start + size); return { output: `${JSON.stringify(slice, null, 2)}\n\nPage ${page}/${pages || 0}; indexes ${start}–${Math.min(start + size - 1, arr.length - 1)}; empty=${slice.length === 0}`, metrics: [["items", arr.length], ["pages", pages], ["returned", slice.length]], warning: boundary }; }
  if (slug === "graphql-islem-envanteri") { const found = [...input.matchAll(/\b(query|mutation|subscription|fragment)\s+([_A-Za-z][_0-9A-Za-z]*)/g)].map((m) => [m[1], m[2]]); return { output: found.length ? table([["type", "name"], ...found]) : "No named operation found. Anonymous operations are harder to observe and audit.", metrics: [["operations", found.length], ["fragments", found.filter((r) => r[0] === "fragment").length]], warning: boundary }; }
  if (slug === "http-link-basligi-ayristirici") { const parts = input.split(/,(?=\s*<)/u); const parsed = parts.map((part) => { const target = part.match(/<([^>]+)>/)?.[1] ?? ""; const rel = part.match(/;\s*rel=(?:"([^"]+)"|([^;\s]+))/i)?.slice(1).find(Boolean) ?? ""; const params = [...part.matchAll(/;\s*([\w-]+)=(?:"([^"]*)"|([^;,]+))/g)].map((m) => `${m[1]}=${m[2] ?? m[3]}`).join("; "); return [target, rel, params]; }); return { output: table([["target", "rel", "parameters"], ...parsed]), metrics: [["links", parsed.length], ["without rel", parsed.filter((r) => !r[1]).length]], warning: boundary }; }
  if (slug === "toml-json-donusturucu") { if (mode === "json-toml") { const value = safeJson(input) as Record<string, unknown>; if (!value || Array.isArray(value) || typeof value !== "object") throw new Error("Use a JSON object."); const scalar = (v: unknown) => typeof v === "string" ? JSON.stringify(v) : typeof v === "number" || typeof v === "boolean" ? String(v) : JSON.stringify(v); const output: string[] = []; Object.entries(value).filter(([, v]) => !v || typeof v !== "object" || Array.isArray(v)).forEach(([k, v]) => output.push(`${k} = ${scalar(v)}`)); Object.entries(value).filter(([, v]) => v && typeof v === "object" && !Array.isArray(v)).forEach(([k, v]) => { output.push(`\n[${k}]`); Object.entries(v as Record<string, unknown>).forEach(([a, b]) => output.push(`${a} = ${scalar(b)}`)); }); return { output: output.join("\n"), metrics: [["root keys", Object.keys(value).length]], warning: "Supports scalar root keys and one table level; validate advanced TOML separately." }; } const root: Record<string, unknown> = {}; let current = root; lines(input).forEach((line) => { if (line.startsWith("#")) return; const section = line.match(/^\[([^\]]+)\]$/); if (section) { current = {}; root[section[1]] = current; return; } const i = line.indexOf("="); if (i < 1) throw new Error(`Unsupported TOML line: ${line}`); const key = line.slice(0, i).trim(), raw = line.slice(i + 1).trim(); current[key] = /^".*"$/.test(raw) ? JSON.parse(raw) : raw === "true" || raw === "false" ? raw === "true" : Number.isFinite(Number(raw)) ? Number(raw) : raw; }); return { output: JSON.stringify(root, null, 2), metrics: [["root keys", Object.keys(root).length]], warning: "Supports basic scalar keys and one table level; advanced TOML needs a full parser." }; }
  if (slug === "base32-kodlayici") { const output = mode === "decode" ? new TextDecoder("utf-8", { fatal: true }).decode(base32Bytes(input)) : byteBase32(new TextEncoder().encode(input)); return { output, metrics: [["input characters", input.length], ["output characters", output.length]], warning: boundary }; }
  if (slug === "hex-metin-donusturucu") { let output: string; if (mode === "decode") { const clean = input.replace(/\s+/g, ""); if (!/^[0-9a-f]*$/i.test(clean) || clean.length % 2) throw new Error("HEX must contain complete byte pairs."); output = new TextDecoder("utf-8", { fatal: true }).decode(Uint8Array.from(clean.match(/.{2}/g)?.map((v) => Number.parseInt(v, 16)) ?? [])); } else output = [...new TextEncoder().encode(input)].map((b) => b.toString(16).padStart(2, "0")).join(" "); return { output, metrics: [["input characters", input.length], ["output characters", output.length]], warning: boundary }; }
  if (slug === "roma-rakami-donusturucu") { const map: Array<[number, string]> = [[1000,"M"],[900,"CM"],[500,"D"],[400,"CD"],[100,"C"],[90,"XC"],[50,"L"],[40,"XL"],[10,"X"],[9,"IX"],[5,"V"],[4,"IV"],[1,"I"]]; const toRoman = (n: number) => { let out = ""; map.forEach(([v, r]) => { while (n >= v) { out += r; n -= v; } }); return out; }; let output = ""; if (/^\d+$/.test(input.trim())) { const n = Number(input.trim()); if (n < 1 || n > 3999) throw new Error("Use an integer from 1 to 3999."); output = toRoman(n); } else { const roman = input.trim().toUpperCase(); let total = 0, i = 0; while (i < roman.length) { const pair = map.find(([, r]) => roman.startsWith(r, i)); if (!pair) throw new Error("Invalid Roman numeral."); total += pair[0]; i += pair[1].length; } if (toRoman(total) !== roman) throw new Error("Roman numeral is not canonical."); output = String(total); } return { output, metrics: [["characters", input.trim().length]], warning: boundary }; }
  if (slug === "buyuk-tamsayi-taban-donusturucu") { const c = pairs(input), from = Math.floor(num(c.from, "from", 2)), to = Math.floor(num(c.to, "to", 2)); if (from > 36 || to > 36) throw new Error("Bases must be 2–36."); const chars = "0123456789abcdefghijklmnopqrstuvwxyz"; let n = BigInt(0); for (const ch of c.value.toLowerCase()) { const d = chars.indexOf(ch); if (d < 0 || d >= from) throw new Error(`Digit ${ch} is invalid for base ${from}.`); n = n * BigInt(from) + BigInt(d); } return { output: n.toString(to), metrics: [["source base", from], ["target base", to], ["digits", c.value.length]], warning: boundary }; }
  if (slug === "ical-etkinlik-olusturucu" || slug === "vcard-kisi-karti-olusturucu") { const c = pairs(input), esc = (v = "") => v.replace(/\\/g, "\\\\").replace(/\n/g, "\\n").replace(/,/g, "\\,").replace(/;/g, "\\;"); if (slug.startsWith("ical")) { if (!/^\d{8}T\d{6}Z$/.test(c.start) || !/^\d{8}T\d{6}Z$/.test(c.end)) throw new Error("start/end must use YYYYMMDDTHHMMSSZ."); const uid = `${crypto.randomUUID()}@bytequant.local`; return { output: `BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//ByteQuant//Local Event//EN\r\nBEGIN:VEVENT\r\nUID:${uid}\r\nDTSTAMP:${new Date().toISOString().replace(/[-:]/g, "").replace(/\.\d{3}/, "")}\r\nDTSTART:${c.start}\r\nDTEND:${c.end}\r\nSUMMARY:${esc(c.title)}\r\nLOCATION:${esc(c.location)}\r\nDESCRIPTION:${esc(c.description)}\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n`, metrics: [["fields", Object.keys(c).length]], warning: boundary }; } if (!c.name) throw new Error("name is required."); return { output: `BEGIN:VCARD\r\nVERSION:4.0\r\nFN:${esc(c.name)}\r\n${c.email ? `EMAIL:${esc(c.email)}\r\n` : ""}${c.phone ? `TEL:${esc(c.phone)}\r\n` : ""}${c.organisation ? `ORG:${esc(c.organisation)}\r\n` : ""}END:VCARD\r\n`, metrics: [["fields", Object.keys(c).length]], warning: boundary }; }
  if (slug === "cok-degerli-sorgu-json-donusturucu") { if (mode === "json-query") { const v = safeJson(input) as Record<string, unknown>; const p = new URLSearchParams(); Object.entries(v).forEach(([k, val]) => (Array.isArray(val) ? val : [val]).forEach((item) => p.append(k, String(item)))); return { output: p.toString(), metrics: [["parameters", [...p.keys()].length]], warning: boundary }; } const p = new URLSearchParams(input.replace(/^\?/, "")); const out: Record<string, string | string[]> = {}; p.forEach((v, k) => { const old = out[k]; out[k] = old === undefined ? v : Array.isArray(old) ? [...old, v] : [old, v]; }); return { output: JSON.stringify(out, null, 2), metrics: [["keys", Object.keys(out).length], ["values", [...p].length]], warning: boundary }; }
  if (slug === "csv-html-tablo-donusturucu") { const { rows } = parseCsv(input); if (!rows.length) throw new Error("CSV is empty."); const [head, ...body] = rows; const output = `<table>\n  <thead>\n    <tr>${head.map((c) => `<th scope="col">${escapeHtml(c)}</th>`).join("")}</tr>\n  </thead>\n  <tbody>\n${body.map((r) => `    <tr>${head.map((_, i) => `<td>${escapeHtml(r[i] ?? "")}</td>`).join("")}</tr>`).join("\n")}\n  </tbody>\n</table>`; return { output, metrics: [["rows", body.length], ["columns", head.length]], warning: boundary }; }
  if (slug === "gizlilik-risk-kaydi-olusturucu") { const rows = lines(input).map((r) => { const [risk, l, impact, owner, control, residual] = r.split("|"); const score = num(l, risk, 1) * num(impact, risk, 1); return [risk, l, impact, score, score >= 15 ? "high" : score >= 8 ? "medium" : "low", owner, control, residual]; }); return { output: table([["risk", "likelihood", "impact", "score", "band", "owner", "control", "residual"], ...rows]), metrics: [["risks", rows.length], ["high", rows.filter((r) => r[4] === "high").length]], warning: boundary }; }
  if (slug === "veri-minimizasyonu-karar-matrisi") { const rows = lines(input).map((r) => { const [field, purpose, necessary, retention, alternative] = r.split("|"); const decision = necessary === "yes" && retention && retention !== "forever" ? "keep with controls" : necessary === "no" && alternative && alternative !== "none" ? "remove / use alternative" : "review"; return [field, purpose, necessary, retention, alternative, decision]; }); return { output: table([["field", "purpose", "necessary", "retention", "alternative", "decision"], ...rows]), metrics: [["fields", rows.length], ["review", rows.filter((r) => r[5] === "review").length]], warning: boundary }; }
  if (slug === "riza-kaydi-sablonu") { const c = pairs(input); const missing = ["purpose", "noticeVersion", "timestamp", "method", "withdrawal"].filter((k) => !c[k]); return { output: `${JSON.stringify({ recordType: "consent-evidence-draft", ...c, verification: { missing, note: "Confirm freely given, specific, informed, unambiguous choice and applicable law." } }, null, 2)}`, metrics: [["fields", Object.keys(c).length], ["missing", missing.length]], warning: boundary }; }
  if (slug === "dpia-on-eleme-sihirbazi") { const c = pairs(input); const signals = Object.entries(c).filter(([, v]) => /^(yes|true|evet)$/i.test(v)); const priority = signals.length >= 2 ? "DPIA review should be prioritised" : signals.length ? "document a privacy review" : "no listed high-risk signal, continue governance review"; return { output: `${table([["signal", "answer"], ...Object.entries(c)])}\n\nOutcome: ${priority}.\nThis screening cannot decide whether a DPIA is legally required.`, metrics: [["signals", Object.keys(c).length], ["positive", signals.length]], warning: boundary }; }
  if (slug === "saklama-suresi-son-tarih-hesaplayici") { const rows = lines(input).map((r) => { const [record, start, days, owner] = r.split("|"); const date = new Date(`${start}T00:00:00Z`); if (Number.isNaN(date.valueOf())) throw new Error(`Invalid date: ${start}`); date.setUTCDate(date.getUTCDate() + Math.floor(num(days, record, 0))); return [record, start, days, date.toISOString().slice(0, 10), owner]; }); return { output: table([["record", "clock starts", "days", "review/delete date", "owner"], ...rows]), metrics: [["records", rows.length]], warning: boundary }; }
  if (slug === "redaksiyon-tutarlilik-denetleyici") { const patterns = { email: /[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/g, phone: /\+?\d(?:[ .-]*\d){8,}/g, reference: /\b[A-Z]{2,}-\d{3,}\b/g }; const findings = Object.entries(patterns).flatMap(([name, regex]) => [...secondary.matchAll(regex)].map((m) => [name, m[0], input.includes(m[0]) ? "unchanged from source" : "new/unknown"])); return { output: findings.length ? table([["type", "remaining value", "status"], ...findings]) : "✓ No built-in identifier pattern remains in the redacted text.", metrics: [["findings", findings.length]], warning: boundary }; }
  if (slug === "veri-siniflandirma-etiketleyici") { const signals = [["restricted", /(?:api[_ -]?key|token|password|secret|sk_(?:live|test)_)/i], ["confidential", /[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}|\+?\d(?:[ .-]*\d){8,}/], ["internal", /(?:team|plan|roadmap|internal)/i]] as const; const matches = signals.filter(([, r]) => r.test(input)); const level = matches[0]?.[0] ?? "public candidate"; return { output: `Suggested label: ${level}\nSignals: ${matches.map((m) => m[0]).join(", ") || "none"}\n\nClassification must be confirmed against your organisation's policy and context.`, metrics: [["signals", matches.length], ["label", level]], warning: boundary }; }
  if (slug === "ihlal-bildirim-zaman-cizelgesi") { const c = pairs(input), start = Date.parse(c.detected); if (Number.isNaN(start)) throw new Error("detected must be an ISO timestamp."); const rows = Object.entries(c).map(([name, value]) => { const ts = Date.parse(value); if (Number.isNaN(ts)) throw new Error(`${name} is not an ISO timestamp.`); return [name, new Date(ts).toISOString(), format((ts - start) / 3600000, 1)]; }); const latest = Math.max(...Object.values(c).map(Date.parse)); return { output: `${table([["event", "UTC time", "hours since detection"], ...rows])}\n\nElapsed at last recorded event: ${format((latest - start) / 3600000, 1)} hours. Applicable notification clocks require legal review.`, metrics: [["events", rows.length], ["elapsed hours", format((latest - start) / 3600000, 1)]], warning: boundary }; }
  if (slug === "cerez-envanteri-risk-siniflandirici") { const rows = lines(input).map((r) => { const [name, domain, duration, purpose] = r.split("|"); const third = domain && !domain.endsWith("bytequant.org"); const long = /(?:365|year)/i.test(duration); const risk = third && long ? "high review" : third || long ? "medium review" : "baseline review"; return [name, domain, duration, purpose, third ? "third-party" : "first-party", risk]; }); return { output: table([["name", "domain", "duration", "purpose", "party", "priority"], ...rows]), metrics: [["cookies", rows.length], ["high review", rows.filter((r) => r[5] === "high review").length]], warning: boundary }; }
  if (slug === "csp-kaynak-ifadesi-tester") { const directives = Object.fromEntries(input.split(";").map((d) => d.trim()).filter(Boolean).map((d) => { const [name, ...sources] = d.split(/\s+/); return [name, sources]; })); const url = new URL(secondary); const sources = directives["img-src"] ?? directives["default-src"] ?? []; const match = sources.some((s) => s === "*" || (s === "'self'" && url.hostname === "bytequant.org") || s === url.origin || (s.startsWith("*.") && url.hostname.endsWith(s.slice(1)))); return { output: `Selected source list: ${sources.join(" ") || "none"}\nURL: ${url.href}\nApproximate match: ${match}\nRisky wildcard: ${sources.includes("*")}\n\nThis helper does not implement the full CSP matching algorithm. Confirm in a browser and CSP evaluator.`, metrics: [["sources", sources.length], ["match", String(match)]], warning: boundary }; }
  if (slug === "sri-degeri-dogrulayici") { const match = /^sha256-([A-Za-z0-9+/=]+)$/.exec(secondary.trim()); if (!match) throw new Error("Integrity must use sha256-<base64>."); const digest = new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(input))); let binary = ""; digest.forEach((b) => { binary += String.fromCharCode(b); }); const actual = btoa(binary); return { output: `Expected: ${match[1]}\nActual:   ${actual}\nMatch: ${actual === match[1]}\n\nGenerated attribute: sha256-${actual}`, metrics: [["match", String(actual === match[1])], ["bytes", new TextEncoder().encode(input).length]], warning: boundary }; }
  if (slug === "paket-adi-benzerlik-tarayicisi") { const trusted = lines(secondary); const rows = lines(input).map((candidate) => { const best = trusted.map((name) => [name, levenshtein(candidate, name)] as const).sort((a, b) => a[1] - b[1])[0]; return [candidate, best?.[0] ?? "—", best?.[1] ?? "—", best && best[1] > 0 && best[1] <= 2 ? "review possible typo" : best?.[1] === 0 ? "exact trusted name" : "no close trusted name"]; }); return { output: table([["candidate", "nearest trusted", "distance", "assessment"], ...rows]), metrics: [["candidates", rows.length], ["review", rows.filter((r) => r[3] === "review possible typo").length]], warning: boundary }; }
  if (slug === "punycode-domain-inceleyici") { const rows = lines(input).map((domain) => { const scripts = new Set([...domain].filter((c) => /\p{L}/u.test(c)).map((c) => /[A-Za-z]/.test(c) ? "Latin" : /[\u0370-\u03ff]/.test(c) ? "Greek" : /[\u0400-\u04ff]/.test(c) ? "Cyrillic" : "Other")); const flags = [domain.toLowerCase().includes("xn--") ? "punycode label" : "", scripts.size > 1 ? `mixed scripts: ${[...scripts].join("+")}` : "", /[\u2024\u3002\uff0e]/u.test(domain) ? "lookalike dot" : ""].filter(Boolean); return [domain, flags.join("; ") || "no listed signal"]; }); return { output: table([["domain", "review"], ...rows]), metrics: [["domains", rows.length], ["flagged", rows.filter((r) => r[1] !== "no listed signal").length]], warning: boundary }; }
  if (slug === "jwt-claim-politikasi-denetleyici") { const parts = input.trim().split("."); if (parts.length !== 3) throw new Error("JWT must have three segments."); const payload = safeJson(b64url(parts[1])) as Record<string, unknown>; const c = pairs(secondary), required = (c.required ?? "").split(",").filter(Boolean); const issues = required.filter((k) => !(k in payload)).map((k) => `missing required ${k}`); if (typeof payload.exp === "number" && payload.exp <= Date.now() / 1000) issues.push("token is expired"); if (typeof payload.nbf === "number" && payload.nbf > Date.now() / 1000) issues.push("token is not active yet"); ["aud", "iss"].forEach((k) => { if (c[k] && payload[k] !== c[k]) issues.push(`${k} mismatch`); }); return { output: `${JSON.stringify(payload, null, 2)}\n\nPOLICY REVIEW\n${issues.join("\n") || "✓ Listed claim policy passed."}\n\nSignature was NOT verified.`, metrics: [["claims", Object.keys(payload).length], ["issues", issues.length]], warning: boundary }; }
  if (slug === "ssh-yetkili-anahtar-inceleyici") { const [type, body, ...comment] = input.trim().split(/\s+/); if (!/^ssh-(?:ed25519|rsa)|^ecdsa-/.test(type) || !body) throw new Error("Expected an OpenSSH public key line."); const bytes = Uint8Array.from(atob(body), (ch) => ch.charCodeAt(0)); const digest = new Uint8Array(await crypto.subtle.digest("SHA-256", bytes)); let bin = ""; digest.forEach((b) => { bin += String.fromCharCode(b); }); return { output: `Type: ${type}\nComment: ${comment.join(" ") || "none"}\nEncoded bytes: ${bytes.length}\nFingerprint: SHA256:${btoa(bin).replace(/=+$/u, "")}\n\nNo private-key material was requested or parsed.`, metrics: [["bytes", bytes.length], ["type", type]], warning: boundary }; }
  if (slug === "pem-blok-inceleyici") { const blocks = [...input.matchAll(/-----BEGIN ([A-Z0-9 ]+)-----\s*([A-Za-z0-9+/=\s]+?)\s*-----END \1-----/g)].map((m) => { const compact = m[2].replace(/\s+/g, ""); let bytes = 0, status = "valid Base64 body"; try { bytes = atob(compact).length; } catch { status = "invalid Base64 body"; } return [m[1], bytes, status]; }); if (!blocks.length) throw new Error("No matching PEM BEGIN/END block found."); return { output: table([["label", "decoded bytes", "body"], ...blocks]), metrics: [["blocks", blocks.length], ["invalid", blocks.filter((r) => r[2] !== "valid Base64 body").length]], warning: boundary }; }
  if (slug === "git-diff-sir-tarayicisi" || slug === "api-anahtari-format-on-kontrolu") { const candidates = slug.startsWith("git") ? lines(input).filter((r) => r.startsWith("+") && !r.startsWith("+++")) : [input]; const patterns = [/\bgh[pousr]_[A-Za-z0-9]{20,}\b/g, /\bAKIA[A-Z0-9]{16}\b/g, /\bsk_(?:live|test)_[A-Za-z0-9_-]{16,}\b/g, /(?:api[_-]?key|token|secret)\s*[:=]\s*['"][^'"]{12,}/gi]; const findings = candidates.flatMap((line, i) => patterns.flatMap((p) => [...line.matchAll(p)].map((m) => [i + 1, m[0].slice(0, 8) + "…", m[0].length]))); const unique = new Set(input).size, entropy = input.length ? Math.log2(Math.max(unique, 1)) * input.length : 0; return { output: `${findings.length ? table([["line", "redacted match", "length"], ...findings]) : "✓ No high-signal built-in pattern found."}\n\nLength: ${input.length}; character classes: ${unique}; upper-bound entropy signal: ${format(entropy, 1)} bits.\nRotate a real exposed secret; removing it from a later commit is insufficient.`, metrics: [["findings", findings.length], ["length", input.length]], warning: boundary }; }
  if (slug === "html-guvenli-atribut-denetleyici") { const findings = [...input.matchAll(/\son[a-z]+\s*=|(?:href|src)\s*=\s*["']\s*javascript:|target\s*=\s*["']_blank["'](?![^>]*rel\s*=\s*["'][^"']*noopener)/gi)].map((m) => [m.index ?? 0, m[0].trim()]); return { output: findings.length ? table([["character", "finding"], ...findings]) : "✓ No listed high-risk attribute pattern found.", metrics: [["findings", findings.length], ["characters", input.length]], warning: boundary }; }
  if (slug === "yuzde-dagilim-dengeleyici") { const c = pairs(input), total = Object.values(c).reduce((s, v) => s + num(v, "allocation", 0), 0); if (!total) throw new Error("Total allocation must be above zero."); const rows = Object.entries(c).map(([k, v]) => [k, num(v, k), num(v, k) / total * 100]); const rounded = rows.map((r) => [r[0], format(Number(r[2]), 4)]); return { output: `${table([["item", "original", "normalised %"], ...rows.map((r, i) => [r[0], r[1], rounded[i][1]])])}\n\nOriginal total: ${format(total, 4)}; normalized total before display rounding: 100%.`, metrics: [["items", rows.length], ["original total", format(total)]], warning: boundary }; }
  if (slug === "paket-birim-maliyet-karsilastirici") {
    const factors: Record<string, number> = { g: 1, kg: 1000, ml: 1, l: 1000, piece: 1 };
    const rows = lines(input).map((row) => {
      const [name, price, quantity, rawUnit] = row.split("|");
      const unit = rawUnit?.toLowerCase();
      const factor = factors[unit];
      if (!factor) throw new Error(`Unsupported unit ${rawUnit}; use g, kg, ml, l, or piece.`);
      const baseQuantity = num(quantity, `${name} quantity`, Number.EPSILON) * factor;
      const numericPrice = num(price, `${name} price`, 0);
      const unitPrice = numericPrice / baseQuantity;
      const basis = unit === "kg" || unit === "g" ? "per g" : unit === "l" || unit === "ml" ? "per ml" : "per piece";
      return { name, price: numericPrice, quantity: `${quantity} ${rawUnit}`, unitPrice, basis };
    }).sort((a, b) => a.unitPrice - b.unitPrice);
    return {
      output: table([["option", "price", "quantity", "unit price", "basis"], ...rows.map((row) => [row.name, format(row.price, 4), row.quantity, format(row.unitPrice, 6), row.basis])]),
      metrics: [["options", rows.length], ["lowest", rows[0]?.name ?? "—"]],
      warning: boundary,
    };
  }
  if (slug === "calisma-ucreti-esdegerlik-hesaplayici") { const c = pairs(input), weeks = num(c.weeks ?? "52", "weeks", 1), hours = num(c.hoursPerWeek ?? "40", "hoursPerWeek", 1); const annual = c.annual ? num(c.annual, "annual", 0) : c.monthly ? num(c.monthly, "monthly", 0) * 12 : c.hourly ? num(c.hourly, "hourly", 0) * weeks * hours : NaN; if (!Number.isFinite(annual)) throw new Error("Provide annual, monthly, or hourly."); return { output: `Annual: ${format(annual)}\nMonthly: ${format(annual / 12)}\nWeekly: ${format(annual / weeks)}\nHourly: ${format(annual / weeks / hours)}\n\nAssumptions: ${weeks} paid weeks × ${hours} paid hours/week.`, metrics: [["annual", format(annual)], ["hourly", format(annual / weeks / hours)]], warning: boundary }; }
  if (slug === "nakit-pisti-hesaplayici") { const c = pairs(input), usable = num(c.cash, "cash", 0) - num(c.buffer ?? "0", "buffer", 0), burn = num(c.monthlySpend, "monthlySpend", 0) - num(c.monthlyRevenue ?? "0", "monthlyRevenue", 0); const months = burn > 0 ? usable / burn : Infinity; return { output: `Usable cash after buffer: ${format(usable)}\nNet monthly burn: ${format(burn)}\nRunway: ${Number.isFinite(months) ? `${format(months, 2)} months` : "not declining under these assumptions"}\n\nModel excludes taxes, timing, one-off costs, restricted cash, and uncertainty.`, metrics: [["monthly burn", format(burn)], ["runway months", Number.isFinite(months) ? format(months) : "∞"]], warning: boundary }; }
  if (slug === "stok-yeniden-siparis-hesaplayici") { const c = pairs(input), demand = num(c.dailyDemand, "dailyDemand", 0), lead = num(c.leadDays, "leadDays", 0), safety = num(c.safetyStock ?? "0", "safetyStock", 0), stock = num(c.currentStock ?? "0", "currentStock", 0), point = demand * lead + safety; return { output: `Reorder point = daily demand × lead days + safety stock\n${format(demand)} × ${format(lead)} + ${format(safety)} = ${format(point)} units\nCurrent stock: ${format(stock)}\nAction under these assumptions: ${stock <= point ? "reorder threshold reached" : `${format(stock - point)} units above threshold`}`, metrics: [["reorder point", format(point)], ["current", format(stock)]], warning: boundary }; }
  if (slug === "oran-arastirmasi-orneklem-planlayici") { const c = pairs(input), confidence = num(c.confidence ?? "95", "confidence", 80), z = confidence >= 99 ? 2.576 : confidence >= 95 ? 1.96 : confidence >= 90 ? 1.645 : 1.282, e = num(c.margin, "margin", 0.01) / 100, p = num(c.proportion ?? "50", "proportion", 0) / 100; let n = z * z * p * (1 - p) / (e * e); const population = c.population ? num(c.population, "population", 1) : undefined; if (population) n = n / (1 + (n - 1) / population); return { output: `Estimated sample: ${Math.ceil(n)}\nFormula: z² × p(1-p) / e²${population ? " with finite-population correction" : ""}\nz=${z}; p=${p}; margin=${e}; population=${population ?? "not supplied"}`, metrics: [["sample", Math.ceil(n)], ["confidence", `${confidence}%`]], warning: boundary }; }
  if (slug === "guven-araligi-hesaplayici") { const c = pairs(input), mean = num(c.mean, "mean"), sd = num(c.sd, "sd", 0), n = num(c.n, "n", 2), confidence = num(c.confidence ?? "95", "confidence"), z = confidence >= 99 ? 2.576 : confidence >= 95 ? 1.96 : confidence >= 90 ? 1.645 : 1.282, margin = z * sd / Math.sqrt(n); return { output: `Approximate ${confidence}% z interval: [${format(mean - margin, 4)}, ${format(mean + margin, 4)}]\nMargin: ${format(margin, 4)}\nStandard error: ${format(sd / Math.sqrt(n), 4)}\n\nThis does not test distribution, sampling design, independence, or bias.`, metrics: [["lower", format(mean - margin)], ["upper", format(mean + margin)]], warning: boundary }; }
  if (slug === "toplanti-maliyeti-hesaplayici") { const c = pairs(input), duration = num(c.durationMinutes, "durationMinutes", 0), prep = num(c.preparationMinutes ?? "0", "preparationMinutes", 0), rates = Object.entries(c).filter(([k]) => !["durationMinutes", "preparationMinutes"].includes(k)).map(([name, rate]) => [name, num(rate, name, 0)] as const), hours = (duration + prep) / 60, rows = rates.map(([name, rate]) => [name, rate, hours, rate * hours]), total = rows.reduce((s, r) => s + Number(r[3]), 0); return { output: `${table([["participant", "hourly rate", "hours", "estimated cost"], ...rows])}\n\nTotal estimated labour cost: ${format(total)}`, metrics: [["participants", rows.length], ["total", format(total)]], warning: boundary }; }
  if (slug === "vardiya-kapsama-hesaplayici") { const rows = lines(input).map((r) => { const [time, required, available] = r.split("|"); const gap = num(available, time, 0) - num(required, time, 0); return [time, required, available, gap, gap < 0 ? "shortage" : gap > 0 ? "surplus" : "covered"]; }); return { output: table([["time", "required", "available", "net", "status"], ...rows]), metrics: [["periods", rows.length], ["shortages", rows.filter((r) => r[4] === "shortage").length]], warning: boundary }; }
  if (slug === "zaman-bloklama-plani") { const raw = lines(input), start = raw.shift() ?? "09:00", c = pairs(secondary || "break=10"), breakMinutes = num(c.break ?? "10", "break", 0); let cursor = new Date(`2000-01-01T${start}:00Z`).valueOf(); const rows = raw.map((r) => { const [task, duration, priority] = r.split("|"); const begin = new Date(cursor).toISOString().slice(11, 16); cursor += num(duration, task, 1) * 60000; const end = new Date(cursor).toISOString().slice(11, 16); cursor += breakMinutes * 60000; return [begin, end, task, priority, `${breakMinutes}m break after`]; }); return { output: table([["start", "end", "task", "priority", "transition"], ...rows]), metrics: [["blocks", rows.length], ["ends", new Date(cursor - breakMinutes * 60000).toISOString().slice(11, 16)]], warning: boundary }; }
  if (slug === "pomodoro-oturum-planlayici") { const c = pairs(input), focus = num(c.focus, "focus", 1), short = num(c.shortBreak, "shortBreak", 0), long = num(c.longBreak, "longBreak", 0), sessions = Math.floor(num(c.sessions, "sessions", 1)), every = Math.floor(num(c.longEvery ?? "4", "longEvery", 1)); let cursor = new Date(`2000-01-01T${c.start}:00Z`).valueOf(); const rows: Array<Array<string | number>> = []; for (let i = 1; i <= sessions; i += 1) { const start = new Date(cursor).toISOString().slice(11, 16); cursor += focus * 60000; rows.push([i, start, new Date(cursor).toISOString().slice(11, 16), "focus"]); if (i < sessions) { const pause = i % every === 0 ? long : short; cursor += pause * 60000; rows.push(["", rows.at(-1)?.[2] ?? "", new Date(cursor).toISOString().slice(11, 16), `${pause}m break`]); } } return { output: table([["session", "start", "end", "type"], ...rows]), metrics: [["focus sessions", sessions], ["ends", new Date(cursor).toISOString().slice(11, 16)]], warning: boundary }; }
  if (slug === "etkinlik-kontrol-listesi-olusturucu") { const rows = lines(input).map((r) => r.split("|")).sort((a, b) => Date.parse(a[1]) - Date.parse(b[1])); return { output: rows.map((r) => `- [ ] ${r[1]} · ${r[0]} — owner: ${r[2] || "unassigned"}`).join("\n"), metrics: [["tasks", rows.length], ["unassigned", rows.filter((r) => !r[2]).length]], warning: boundary }; }
  if (slug === "embedding-parca-ortusme-planlayici") { const c = pairs(input), doc = num(c.documentTokens, "documentTokens", 1), chunk = num(c.chunkTokens, "chunkTokens", 1), overlap = num(c.overlapTokens, "overlapTokens", 0), metadata = num(c.metadataTokens ?? "0", "metadataTokens", 0); if (overlap >= chunk) throw new Error("overlapTokens must be below chunkTokens."); const count = Math.ceil(Math.max(1, doc - overlap) / (chunk - overlap)), embedded = count * (chunk + metadata), repeated = Math.max(0, (count - 1) * overlap); return { output: `Chunks: ${count}\nEffective step: ${chunk - overlap} tokens\nRepeated overlap: ${repeated} tokens\nEstimated embedded tokens including metadata: ${embedded}\nExpansion vs source: ${format(embedded / doc, 3)}×`, metrics: [["chunks", count], ["repeated", repeated]], warning: boundary }; }
  if (slug === "arac-cagrisi-json-dogrulayici") { const v = safeJson(input) as Record<string, unknown>, c = pairs(secondary), issues: string[] = []; if (v.name !== c.name) issues.push(`name must equal ${c.name}`); if (!v.arguments || Array.isArray(v.arguments) || typeof v.arguments !== "object") issues.push("arguments must be an object"); const required = (c.required ?? "").split(",").filter(Boolean); required.forEach((k) => { if (!v.arguments || !(k in (v.arguments as Record<string, unknown>))) issues.push(`missing argument ${k}`); }); return { output: `${JSON.stringify(v, null, 2)}\n\n${issues.join("\n") || "✓ Tool-call shape satisfies the declared local contract."}`, metrics: [["required", required.length], ["issues", issues.length]], warning: boundary }; }
  if (slug === "doi-toplu-dogrulayici") { const normalized = lines(input).map((v) => v.replace(/^https?:\/\/(?:dx\.)?doi\.org\//i, "").replace(/^doi:\s*/i, "").trim().toLowerCase()); const counts = new Map<string, number>(); normalized.forEach((v) => counts.set(v, (counts.get(v) ?? 0) + 1)); const rows = normalized.map((v) => [v, /^10\.\d{4,9}\/[-._;()/:a-z0-9]+$/i.test(v) ? "valid syntax" : "invalid syntax", counts.get(v)! > 1 ? "duplicate" : "unique", /^10\./.test(v) ? `https://doi.org/${encodeURI(v)}` : "—"]); return { output: table([["normalized DOI", "syntax", "set", "safe link"], ...rows]), metrics: [["records", rows.length], ["invalid", rows.filter((r) => r[1] === "invalid syntax").length], ["duplicates", rows.filter((r) => r[2] === "duplicate").length]], warning: boundary }; }
  if (slug === "literatur-eleme-karar-gunlugu") { const rows = lines(input).map((r) => r.split("|")); const ids = new Map<string, Set<string>>(); rows.forEach((r) => { if (!ids.has(r[0])) ids.set(r[0], new Set()); ids.get(r[0])!.add(r[1]); }); const output = rows.map((r) => [r[0], r[1] || "missing", r[2] || "missing", r[3] || "missing", ids.get(r[0])!.size > 1 ? "conflicting decisions" : !r[1] || !r[2] || !r[3] ? "incomplete" : "complete"]); return { output: table([["record", "decision", "reason", "reviewer", "status"], ...output]), metrics: [["records", rows.length], ["conflicts", output.filter((r) => r[4] === "conflicting decisions").length]], warning: boundary }; }
  if (slug === "kanit-tablosu-tekillestirici") { const rows = lines(input).map((r, i) => { const [doi, title, year] = r.split("|"); return { i: i + 1, doi: doi.toLowerCase(), title, year, key: doi ? `doi:${doi.toLowerCase()}` : `title:${words(title).join(" ")}:${year}` }; }); const groups = new Map<string, number[]>(); rows.forEach((r) => groups.set(r.key, [...(groups.get(r.key) ?? []), r.i])); const exact = [...groups].filter(([, ids]) => ids.length > 1); const fuzzy: string[] = []; rows.forEach((a, i) => rows.slice(i + 1).forEach((b) => { if (!a.doi && !b.doi && a.year === b.year && levenshtein(words(a.title).join(" "), words(b.title).join(" ")) <= 8) fuzzy.push(`${a.i}/${b.i}`); })); return { output: `Exact-key duplicate groups: ${exact.map(([k, ids]) => `${ids.join(", ")} (${k})`).join("; ") || "none"}\nFuzzy title candidates: ${fuzzy.join(", ") || "none"}\n\n${table([["row", "DOI", "title", "year"], ...rows.map((r) => [r.i, r.doi || "—", r.title, r.year])])}`, metrics: [["records", rows.length], ["exact groups", exact.length], ["fuzzy pairs", fuzzy.length]], warning: boundary }; }
  throw new Error(`Implementation missing for ${slug}`);
}

const ui: Record<Locale, Record<string, string>> = {
  tr: { local: "Girdi yalnızca etkin tarayıcı sekmesinde işlenir.", demo: "Örnek veri yükle", clear: "Temizle", input: "Girdi", second: "Karşılaştırma / yapılandırma", mode: "Dönüşüm yönü", run: "Cihazımda çalıştır", running: "İşleniyor…", result: "Sonuç", copy: "Kopyala", download: "İndir", empty: "Sonuç burada görünecek.", done: "Tamamlandı", error: "İşlem tamamlanamadı", privacy: "Bu işlem tamamen cihazınızda gerçekleşti; girdi ByteQuant sunucusuna gönderilmedi." },
  en: { local: "Input is processed only in the active browser tab.", demo: "Load example", clear: "Clear", input: "Input", second: "Comparison / configuration", mode: "Conversion direction", run: "Run on my device", running: "Processing…", result: "Result", copy: "Copy", download: "Download", empty: "The result will appear here.", done: "Completed", error: "Could not complete the operation", privacy: "This operation happened entirely on your device; input was not sent to ByteQuant servers." },
  de: { local: "Eingaben werden nur im aktiven Browser-Tab verarbeitet.", demo: "Beispiel laden", clear: "Leeren", input: "Eingabe", second: "Vergleich / Konfiguration", mode: "Konvertierungsrichtung", run: "Auf meinem Gerät ausführen", running: "Verarbeitung…", result: "Ergebnis", copy: "Kopieren", download: "Herunterladen", empty: "Das Ergebnis erscheint hier.", done: "Abgeschlossen", error: "Vorgang konnte nicht abgeschlossen werden", privacy: "Der Vorgang fand vollständig auf Ihrem Gerät statt; Eingaben wurden nicht an ByteQuant gesendet." },
  zh: { local: "输入仅在当前浏览器标签页中处理。", demo: "加载示例", clear: "清除", input: "输入", second: "比较 / 配置", mode: "转换方向", run: "在设备上运行", running: "处理中…", result: "结果", copy: "复制", download: "下载", empty: "结果将显示在这里。", done: "已完成", error: "无法完成操作", privacy: "此操作完全在您的设备上完成；输入未发送到 ByteQuant 服务器。" },
};

export function FrontierWorkbench({ slug, locale }: { slug: string; locale: Locale }) {
  const t = ui[locale], demo = frontierDemos[slug] ?? { input: "" }, tool = getTool(slug);
  const options = useMemo(() => modeOptions[slug] ?? [], [slug]);
  const [input, setInput] = useState(""); const [secondary, setSecondary] = useState(""); const [mode, setMode] = useState(options[0]?.[0] ?? "default"); const [output, setOutput] = useState(""); const [metrics, setMetrics] = useState<Array<[string, string | number]>>([]); const [warning, setWarning] = useState(""); const [state, setState] = useState<"idle" | "busy" | "success" | "error">("idle"); const [message, setMessage] = useState("");
  const resetResult = () => { setOutput(""); setMetrics([]); setWarning(""); setState("idle"); setMessage(""); };
  const loadDemo = () => { setInput(demo.input); setSecondary(demo.secondary ?? ""); setMode(demo.mode ?? options[0]?.[0] ?? "default"); resetResult(); };
  async function run() { if (state === "busy") return; setState("busy"); setMessage(t.running); await new Promise<void>((resolve) => requestAnimationFrame(() => resolve())); try { if (!input.trim()) throw new Error(locale === "tr" ? "Önce bir girdi yazın veya örneği yükleyin." : "Enter input or load the example first."); if (dualSlugs.has(slug) && !secondary.trim()) throw new Error(locale === "tr" ? "Bu araç için ikinci alan da gereklidir." : "This tool also requires the second field."); const result = await runFrontierTool(slug, input.slice(0, 200_000), secondary.slice(0, 100_000), mode); setOutput(result.output); setMetrics(result.metrics ?? []); setWarning(result.warning ?? ""); setState("success"); setMessage(t.done); } catch (error) { setOutput(""); setMetrics([]); setWarning(""); setState("error"); setMessage(`${t.error}: ${error instanceof Error ? error.message : String(error)}`); } }
  async function copy() { if (!output) return; try { await navigator.clipboard.writeText(output); setMessage(t.done); } catch { setState("error"); setMessage(t.error); } }
  function download() { if (!output) return; const url = URL.createObjectURL(new Blob([output], { type: "text/plain;charset=utf-8" })); const a = document.createElement("a"); a.href = url; a.download = `bytequant-${slug}.txt`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 0); }
  return <section className="workbench precision-workbench frontier-workbench" aria-busy={state === "busy"}>
    <div className="workbench-bar"><span className="local-status"><i />{t.local}<small>{tool?.title[locale]}</small></span><div className="workbench-bar-actions"><button type="button" className="demo-button" onClick={loadDemo}>{t.demo}</button><button type="button" className="ghost-button" onClick={() => { setInput(""); setSecondary(""); resetResult(); }}>{t.clear}</button></div></div>
    <div className="workbench-grid"><div className="workbench-inputs" data-agent-contract={dualSlugs.has(slug) ? "dual-text-v1" : "single-text-v1"}><label className="field-label"><span>{t.input}</span><textarea data-agent-input data-agent-key="input" value={input} rows={12} maxLength={200000} onChange={(e) => { setInput(e.target.value); resetResult(); }} spellCheck={false} /><small className="field-counter">{input.length.toLocaleString()} / 200,000</small></label>{dualSlugs.has(slug) && <label className="field-label"><span>{t.second}</span><textarea data-agent-input data-agent-key="secondary" value={secondary} rows={7} maxLength={100000} onChange={(e) => { setSecondary(e.target.value); resetResult(); }} spellCheck={false} /></label>}{options.length > 0 && <label className="field-label compact-field"><span>{t.mode}</span><select data-agent-mode value={mode} onChange={(e) => { setMode(e.target.value); resetResult(); }}>{options.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>}<button type="button" className="primary-button run-button" data-agent-run disabled={state === "busy"} onClick={() => void run()}>{state === "busy" ? t.running : t.run}<span aria-hidden="true"> →</span></button></div>
      <div className="result-panel" aria-live="polite"><div className="result-header"><span>{t.result}</span><div className="output-actions"><button type="button" disabled={!output} onClick={() => void copy()}>{t.copy}</button><button type="button" disabled={!output} onClick={download}>{t.download}</button></div></div>{metrics.length > 0 && <div className="metric-strip">{metrics.map(([label, value]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div>}<StructuredToolOutput output={output} empty={t.empty} />{warning && <ToolNotice locale={locale} notice={{ kind: "warning", text: warning }} />}{state === "error" && <ToolNotice locale={locale} notice={{ kind: "error", text: message }} />}{state === "success" && <div className="workbench-trust-card"><span aria-hidden="true">✓</span><p>{t.privacy}</p></div>}</div></div>
  </section>;
}
