import Link from "next/link";
import { posts } from "../lib/posts";
import { categories, publicTools as tools, type ToolCategory } from "../lib/tools";
import { absoluteUrl, copy, languageTag, organizationId, pathFor, postPath, toolPath, websiteId, type Locale } from "../lib/site";
import { SchemaScript } from "./SchemaScript";
import { SiteShell } from "./SiteShell";
import { ToolCard } from "./ToolCard";
import { PersonalToolsHub } from "./ToolUsage";
import { PwaInstall } from "./PwaInstall";
import { GitHubActivity } from "./GitHubActivity";
import { localizedGuides } from "../lib/localized-guides";
import { HeroToolSearch } from "./HeroToolSearch";
import { InteractiveDemo } from "./InteractiveDemo";
import { AGENT_VERSION } from "../lib/agent-session";

const faqs = {
  tr: [
    ["ByteQuant'a yazdığım metinler sunucuya gönderiliyor mu?", "Hayır. Araçların temel analiz ve dönüşüm işlemleri tarayıcınızda JavaScript ve Web API'leriyle çalışır. Girdi alanlarındaki içerik ByteQuant sunucularına gönderilmez."],
    ["Araçları kullanmak için üyelik gerekiyor mu?", "Hayır. Araçlar ücretsizdir ve hesap açmadan kullanılabilir. Araç girdileri tarayıcı depolamasına kaydedilmez; tema ve kişisel popüler araç sayacı yalnızca bu cihazda, hassas içerik olmadan tutulabilir."],
    ["Sonuçlar hukuki veya güvenlik garantisi verir mi?", "Hayır. Maskeleme ve analiz araçları ön kontrol sağlar. KVKK, GDPR, güvenlik veya hukuki kararlar için yetkin uzman incelemesi gerekir."],
    ["Token sayacı neden yaklaşık sonuç verir?", "Her model farklı bir tokenizer kullanır. ByteQuant, veriyi dışarı göndermeden hızlı planlama yapabilmeniz için karakter ve dil yapısına dayalı yaklaşık değer üretir."],
    ["Araçlar mobil cihazlarda çalışır mı?", "Evet. Güncel mobil tarayıcılarda temel araçlar çalışır. Web Crypto gibi bazı özellikler tarayıcı desteğine bağlıdır."],
    ["Site reklam içeriyor mu?", "Evet. ByteQuant, içerikten ve araç düğmelerinden ayrılan, açıkça etiketlenmiş Google AdSense reklamlarıyla desteklenebilir. Araç girdileri reklamlara gönderilmez; desteklenen bölgelerde reklam gizlilik seçimi Google sertifikalı CMP ile sunulur."],
    ["Yeni araçların sonuçları nasıl doğrulanmalı?", "JSON Schema yalnızca örneği yansıtır, özetleyici kaynak cümleleri seçer, kredi hesabı matematiksel senaryodur ve güvenlik denetimleri ön kontroldür. Her araç yöntem sınırını gösterir; yüksek etkili sonuçları bağımsız kaynakla doğrulayın."],
    ["Görsel ve dosya araçları verimi saklıyor mu?", "Hayır. Görsel yeniden boyutlandırma ve SHA-256 hesaplama bu sekmede çalışır. Seçtiğiniz dosya sunucuya gönderilmez veya localStorage'a yazılmaz; yalnızca sizin indirdiğiniz çıktı cihazda kalır."],
  ],
  en: [
    ["Is text entered into ByteQuant sent to a server?", "No. Core analysis and transformation run in your browser using JavaScript and Web APIs. Tool input is not sent to ByteQuant servers."],
    ["Do I need an account?", "No. The tools are free and require no account. Tool input is not saved to browser storage; theme and personal popular-tool counts may stay on this device without sensitive content."],
    ["Do results provide legal or security assurance?", "No. Masking and analysis are pre-checks. KVKK, GDPR, security, and legal decisions require qualified human review."],
    ["Why is the token count approximate?", "Each model uses a different tokenizer. ByteQuant estimates from characters and language so you can plan without transmitting the text."],
    ["Do the tools work on mobile?", "Yes. Core tools work in current mobile browsers. Some features, including Web Crypto operations, depend on browser support."],
    ["Does the site contain advertising?", "Yes. ByteQuant may be supported by clearly labelled Google AdSense advertising separated from content and tool controls. Tool input is never sent to ads; where required, ad privacy choices are provided through a Google-certified CMP."],
    ["How should I verify output from the new tools?", "JSON Schema reflects only its sample, summaries select source sentences, loan figures are mathematical scenarios, and security audits are pre-checks. Review each disclosed limitation and independently verify high-impact output."],
    ["Do image and file tools retain my data?", "No. Image resizing and SHA-256 run in this tab. Selected files are neither uploaded nor written to localStorage; only output you explicitly download remains on your device."],
  ],
  de: [
    ["Werden Texte, die ich in ByteQuant eingebe, an einen Server gesendet?", "Nein. Die Kernanalyse und -konvertierung läuft mit JavaScript und Web APIs in Ihrem Browser. Werkzeugeingaben werden nicht an ByteQuant-Server gesendet."],
    ["Brauche ich ein Konto?", "Nein. Die Werkzeuge sind kostenlos und ohne Konto nutzbar. Eingaben werden nicht im Browserspeicher gespeichert; nur Thema und ein optionaler lokaler Werkzeugzähler können auf diesem Gerät bleiben."],
    ["Sind Ergebnisse eine Rechts- oder Sicherheitsgarantie?", "Nein. Maskierung, Berechnung und Scans sind Vorprüfungen. Rechtliche, finanzielle und sicherheitskritische Entscheidungen erfordern qualifizierte menschliche Prüfung."],
    ["Warum sind Tokenwerte nur Schätzungen?", "Modelle verwenden unterschiedliche Tokenizer. ByteQuant schätzt lokal aus Zeichen- und Sprachstruktur, ohne Text zu übertragen."],
    ["Funktionieren die Werkzeuge mobil?", "Ja. Die Kernfunktionen laufen in aktuellen mobilen Browsern. Einige Datei- und Web-Crypto-Funktionen hängen von Browser und Gerätespeicher ab."],
    ["Enthält die Website Werbung?", "Ja. ByteQuant kann durch klar gekennzeichnete Google-AdSense-Werbung unterstützt werden, die von Inhalt und Werkzeugsteuerung getrennt ist. Werkzeugeingaben werden nie an Werbung gesendet; erforderliche Datenschutzoptionen laufen über eine Google-zertifizierte CMP."],
    ["Wie müssen Ergebnisse der neuen Werkzeuge geprüft werden?", "JSON Schema beschreibt nur das Beispiel, Zusammenfassungen wählen Quellsätze, Kreditwerte sind Rechenszenarien und Sicherheitsprüfungen sind Vorchecks. Prüfen Sie wichtige Ausgaben unabhängig."],
    ["Werden Bild- oder Dateidaten gespeichert?", "Nein. Bildskalierung und SHA-256 laufen in diesem Tab. Dateien werden weder hochgeladen noch in localStorage geschrieben; nur ausdrücklich heruntergeladene Ergebnisse bleiben auf Ihrem Gerät."],
  ],
  zh: [
    ["我输入 ByteQuant 的文本会发送到服务器吗？", "不会。核心分析与转换通过 JavaScript 和 Web API 在浏览器中运行，工具输入不会发送到 ByteQuant 服务器。"],
    ["使用工具需要账户吗？", "不需要。工具免费且无需注册。输入不会保存到浏览器存储；仅主题和可选的本地工具计数可能保留在本设备。"],
    ["结果是否构成法律或安全保证？", "不构成。遮蔽、计算和扫描只是预检查。法律、财务和安全关键决策仍需合格专业人员审查。"],
    ["为什么 Token 数只是估算？", "不同模型使用不同分词器。ByteQuant 根据字符与语言结构在本地估算，无需传输文本。"],
    ["工具能在手机上运行吗？", "可以。核心工具支持现代移动浏览器；部分文件与 Web Crypto 功能取决于浏览器能力和设备内存。"],
    ["网站是否包含广告？", "是。ByteQuant 可通过与内容和工具控件分隔、明确标注的 Google AdSense 广告获得支持。工具输入绝不会发送给广告系统；适用地区的广告隐私选择通过 Google 认证的 CMP 提供。"],
    ["如何核验新工具的结果？", "JSON Schema 只反映示例，摘要器选择原句，贷款结果是数学情景，安全审计只是预检查。请阅读每项方法限制，并独立核验高影响输出。"],
    ["图片和文件工具会保存数据吗？", "不会。图片调整和 SHA-256 在当前标签页运行，文件不会上传或写入 localStorage；只有您主动下载的输出会留在设备上。"],
  ],
} as const;

export function HomePage({ locale }: { locale: Locale }) {
  const isTr = locale === "tr";
  const editorialLocale = locale === "tr" ? "tr" : "en";
  const localized = (tr: string, en: string, de: string, zh: string) => ({ tr, en, de, zh })[locale];
  const currentLanguage = languageTag(locale);
  const t = copy[locale];
  const agentWithPrompt = (prompt: string) => `${pathFor(locale, "agent")}?q=${encodeURIComponent(prompt)}`;
  const guideCards = locale === "de" || locale === "zh"
    ? localizedGuides.slice(-3).reverse().map((guide) => ({ slug: guide.slug, category: guide.copy[locale].category, readTime: guide.copy[locale].readTime, title: guide.copy[locale].title, excerpt: guide.copy[locale].excerpt, href: postPath(locale, guide.slug), hrefLang: locale }))
    : posts.slice(-3).reverse().map((post) => ({ slug: post.slug, category: post.category[editorialLocale], readTime: post.readTime[editorialLocale], title: post.title[editorialLocale], excerpt: post.excerpt[editorialLocale], href: postPath(editorialLocale, post.slug), hrefLang: editorialLocale }));
  const alternateHref = locale === "tr" ? "/en" : "/";
  const homeUrl = absoluteUrl(pathFor(locale, "home"));
  const featuredTools = ["json-bicimlendirici", "pdf-birlestirme", "kvkk-veri-maskeleyici", "gorsel-sikistirici", "jwt-decoder", "markdown-onizleyici", "cron-ifadesi-aciklayici", "guclu-parola-uretici", "metin-farki-diff", "qr-kod-olusturucu", "csv-inceleyici", "prompt-kalite-denetimi"]
    .map((slug) => tools.find((tool) => tool.slug === slug))
    .filter((tool): tool is (typeof tools)[number] => Boolean(tool));
  const schema = [
    { "@context": "https://schema.org", "@type": "WebApplication", "@id": `${homeUrl}#application`, name: "ByteQuant", url: homeUrl, applicationCategory: "ProductivityApplication", operatingSystem: "Any modern browser", browserRequirements: "JavaScript enabled", inLanguage: currentLanguage, isAccessibleForFree: true, isPartOf: { "@id": websiteId }, creator: { "@id": organizationId }, offers: { "@type": "Offer", price: "0", priceCurrency: "USD" }, featureList: [localized("ByteQuant AI ile açıklanabilir araç planlama ve otomasyon", "Explainable tool planning and automation with ByteQuant AI", "Nachvollziehbare Werkzeugplanung und Automatisierung mit ByteQuant AI", "使用 ByteQuant AI 进行可解释的工具规划与自动化"), localized("Cihaz içinde görsel düzenleme ve istemden özgün SVG taslak", "On-device image editing and original prompt-based SVG drafts", "Lokale Bildbearbeitung und eigene SVG-Entwürfe aus Prompts", "设备端图片编辑与基于提示词的原创 SVG 草稿"), localized("Görsel İş İstasyonu, şifreli cihaz içi projeler ve sunucusuz P2P", "Visual Workstation, encrypted on-device projects, and serverless P2P", "Visuelle Workstation, verschlüsselte lokale Projekte und serverloses P2P", "可视化工作站、设备端加密项目与无服务器 P2P"), ...Object.values(categories).map((category) => category.label[locale])] },
    { "@context": "https://schema.org", "@type": "CollectionPage", "@id": `${homeUrl}#tool-collection`, name: localized("Öne çıkan ByteQuant tarayıcı araçları", "Featured ByteQuant browser tools", "Ausgewählte ByteQuant Browser-Werkzeuge", "ByteQuant 精选浏览器工具"), url: homeUrl, inLanguage: currentLanguage, isPartOf: { "@id": websiteId }, mainEntity: { "@type": "ItemList", numberOfItems: featuredTools.length, itemListElement: featuredTools.map((tool, index) => ({ "@type": "ListItem", position: index + 1, name: tool.title[locale], url: absoluteUrl(toolPath(locale, tool.slug)) })) }, hasPart: featuredTools.map((tool) => ({ "@type": "WebApplication", name: tool.title[locale], url: absoluteUrl(toolPath(locale, tool.slug)) })) },
    { "@context": "https://schema.org", "@type": "FAQPage", "@id": `${homeUrl}#faq`, url: homeUrl, inLanguage: currentLanguage, isPartOf: { "@id": websiteId }, mainEntity: faqs[locale].map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) },
  ];

  return (
    <SiteShell locale={locale} alternateHref={alternateHref} languageHrefs={{ tr: "/", en: "/en", de: "/de", zh: "/zh" }} includeGlobalSchema>
      <SchemaScript data={schema} />
      <section className="hero-section">
        <div className="container hero-grid">
          <div className="hero-copy">
            <span className="eyebrow"><i />{localized(`${tools.length} araç ve cihaz içi AI, tek yerde`, `${tools.length} tools and on-device AI in one place`, `${tools.length} Werkzeuge und lokale KI an einem Ort`, `${tools.length} 个工具与设备端 AI，一站完成`)}</span>
            <h1>{localized("Ne yapmak istediğinizi anlatın; ByteQuant AI doğru yolu hazırlasın.", "Describe what you need; ByteQuant AI will prepare the right path.", "Beschreiben Sie Ihr Ziel – ByteQuant AI bereitet den passenden Weg vor.", "说出您的目标，让 ByteQuant AI 准备合适的路径。")}</h1>
            <p>{localized(`Günlük bir soruyu konuşun veya veri, belge ve kod işinizi anlatın. ByteQuant AI uygun araçları bulur, desteklenen adımları cihazınızda tamamlar ve sonucu anlaşılır biçimde açıklar. İsterseniz ${tools.length} aracın tamamına doğrudan da ulaşabilirsiniz.`, `Chat about an everyday question or describe a data, document, or code task. ByteQuant AI finds suitable tools, completes supported steps on your device, and explains the result clearly. You can also open any of the ${tools.length} tools directly.`, `Stellen Sie eine Alltagsfrage oder beschreiben Sie eine Daten-, Dokument- oder Codeaufgabe. ByteQuant AI findet passende Werkzeuge, erledigt unterstützte Schritte auf Ihrem Gerät und erklärt das Ergebnis verständlich. Alle ${tools.length} Werkzeuge sind auch direkt erreichbar.`, `您可以提出日常问题，也可以描述数据、文档或代码任务。ByteQuant AI 会寻找合适工具，在设备上完成受支持的步骤，并清晰解释结果；也可直接使用全部 ${tools.length} 个工具。`)}</p>
            <HeroToolSearch locale={locale} />
            <div className="hero-actions"><Link className="primary-button" href={pathFor(locale, "agent")}>✦ {localized("ByteQuant AI ile başlayın", "Start with ByteQuant AI", "Mit ByteQuant AI starten", "开始使用 ByteQuant AI")}<span aria-hidden="true"> →</span></Link><Link className="secondary-button" href={pathFor(locale, "tools")}>{t.allTools}</Link><Link className="hero-workstation-link" href={pathFor(locale, "workstation")}>⌘ {localized("Akış kur", "Build a flow", "Ablauf bauen", "建立流程")}</Link></div>
            <div className="hero-trust"><span>✓ {localized("Üyelik yok", "No account", "Kein Konto", "无需账户")}</span><span>✓ {localized("Sunucuya yükleme yok", "No server upload", "Kein Server-Upload", "无需上传服务器")}</span><span>✓ {localized("Açıklanabilir sonuç", "Explainable output", "Nachvollziehbare Ausgabe", "可解释输出")}</span></div>
            <div className="hero-use-cases" aria-label={localized("ByteQuant AI örnekleri", "ByteQuant AI examples", "ByteQuant-AI-Beispiele", "ByteQuant AI 示例")}><small>{localized("Tek tıkla deneyin", "Try in one click", "Mit einem Klick testen", "一键试用")}</small><div><Link href={agentWithPrompt(localized("Bu JSON hatasını bul ve düzelt: {\"name\": \"Ada\",}", "Find and fix this JSON error: {\"name\": \"Ada\",}", "Finde und behebe diesen JSON-Fehler: {\"name\": \"Ada\",}", "查找并修复此 JSON 错误：{\"name\": \"Ada\",}"))}>{localized("JSON düzelt", "Fix JSON", "JSON reparieren", "修复 JSON")}</Link><Link href={agentWithPrompt(localized("Bir e-posta listesini güvenle temizlemek için yardım et", "Help me safely clean an email list", "Hilf mir, eine E-Mail-Liste sicher zu bereinigen", "帮我安全清理电子邮件列表"))}>{localized("Liste temizle", "Clean a list", "Liste bereinigen", "清理列表")}</Link><Link href={`${pathFor(locale, "agent")}#agent-visual`}>{localized("Görsel düzenle", "Edit an image", "Bild bearbeiten", "编辑图片")}</Link><Link href={agentWithPrompt(localized("Bugün odaklanmam için kısa bir plan yap", "Make a short focus plan for today", "Erstelle einen kurzen Fokusplan für heute", "为我制定今天的简短专注计划"))}>{localized("Günü planla", "Plan my day", "Tag planen", "规划今天")}</Link></div></div>
          </div>
          <div className="hero-product" aria-label={localized("ByteQuant AI konuşma örneği", "ByteQuant AI conversation preview", "ByteQuant-AI-Gesprächsvorschau", "ByteQuant AI 对话预览")}>
            <div className="product-window">
              <div className="window-bar"><span><i /><i /><i /></span><b>bytequant.org{pathFor(locale, "agent")}</b><small>● {localized("Cihazda", "On device", "Auf dem Gerät", "设备端")}</small></div>
              <div className="window-content">
                <div className="preview-heading"><span className="tool-mark category-prompt">BQ</span><div><small>BYTEQUANT AI · {localized("OTOMATİK", "AUTOMATIC", "AUTOMATISCH", "自动")}</small><strong>{localized("Nasıl yardımcı olabilirim?", "How can I help?", "Wie kann ich helfen?", "我能如何帮助您？")}</strong></div><span className="score-ring">✦</span></div>
                <div className="preview-input">{localized("Bu CSV'deki e-postaları temizle, tekrarları kaldır ve JSON hazırla.", "Clean the emails in this CSV, remove duplicates, and prepare JSON.", "E-Mails in dieser CSV bereinigen, Duplikate entfernen und JSON erstellen.", "清理此 CSV 中的电子邮件、去重并生成 JSON。")}</div>
                <div className="preview-checks"><span>✓ {localized("Girdi anlaşıldı", "Input understood", "Eingabe verstanden", "已理解输入")}</span><span>✓ {localized("3 adımlı akış hazır", "3-step flow ready", "3-Schritt-Ablauf bereit", "三步流程已就绪")}</span><span>✓ {localized("Cihazda çalışır", "Runs on device", "Läuft lokal", "在设备上运行")}</span></div>
                <div className="preview-footer"><span><i />{localized("Sonuç ve sonraki adım görünür", "Result and next step are visible", "Ergebnis und nächster Schritt sichtbar", "结果与下一步清晰可见")}</span><b>{localized("Akışı çalıştır", "Run workflow", "Ablauf starten", "运行流程")} →</b></div>
              </div>
            </div>
            <div className="floating-note"><span>◎</span><div><strong>{isTr ? "Ağ isteği yok" : "No network request"}</strong><small>{isTr ? "Girdi tarayıcı belleğinde" : "Input remains in browser memory"}</small></div></div>
          </div>
        </div>
      </section>

      <section className="proof-strip"><div className="container proof-grid"><div><strong>{tools.length}</strong><span>{localized("benzersiz yayımlanmış araç", "distinct published tools", "eigenständige veröffentlichte Werkzeuge", "个独立发布工具")}</span></div><div><strong>{Object.keys(categories).length}</strong><span>{localized("odaklanmış kategori", "focused categories", "fokussierte Kategorien", "个专注分类")}</span></div><div><strong>0</strong><span>{localized("zorunlu hesap", "required accounts", "Pflichtkonten", "个必需账户")}</span></div><div><strong>100%</strong><span>{localized("tarayıcı içi çekirdek işlem", "in-browser core processing", "Kernverarbeitung im Browser", "核心处理在浏览器内")}</span></div></div></section>

      <section className="section home-platform-section" aria-labelledby="home-platform-title">
        <div className="container">
          <div className="section-heading split-heading home-platform-heading">
            <div><span className="kicker">BYTEQUANT · {localized("TEK BAŞLANGIÇ", "ONE STARTING POINT", "EIN EINSTIEG", "统一入口")}</span><h2 id="home-platform-title">{localized("Kararsızsanız ByteQuant AI ile başlayın", "Start with ByteQuant AI when the path is unclear", "Bei unklarem Weg mit ByteQuant AI starten", "不确定从何开始时，先使用 ByteQuant AI")}</h2></div>
            <p>{localized("Hedefinizi günlük dille yazın; ByteQuant AI doğru aracı veya çok adımlı akışı hazırlasın. Ne kullanmanız gerektiğini zaten biliyorsanız araç kütüphanesine ya da görsel çalışma alanına doğrudan geçebilirsiniz.", "Describe the outcome in everyday language and let ByteQuant AI prepare the right tool or multi-step flow. If you already know what you need, open the tool library or visual workspace directly.", "Beschreiben Sie das Ziel in Alltagssprache; ByteQuant AI bereitet das passende Werkzeug oder einen mehrstufigen Ablauf vor. Wenn der Weg klar ist, öffnen Sie direkt die Werkzeugbibliothek oder den visuellen Arbeitsbereich.", "用日常语言描述目标，让 ByteQuant AI 准备合适工具或多步骤流程。若已明确需求，也可直接打开工具库或可视化工作区。")}</p>
          </div>
          <div className="home-platform-grid">
            <article className="home-platform-card home-tools-card">
              <header><span className="home-platform-mark" aria-hidden="true">□</span><div><small>{tools.length} {localized("ÜCRETSİZ ARAÇ", "FREE TOOLS", "KOSTENLOSE WERKZEUGE", "个免费工具")}</small><strong>{localized("Tek bir işi tamamlayın", "Complete one task", "Eine Aufgabe erledigen", "完成一项任务")}</strong></div><b>{localized("HIZLI", "QUICK", "SCHNELL", "快速")}</b></header>
              <h3>{localized("Ne yapacağınızı biliyorsanız en kısa yoldan başlayın", "Start with the shortest path when you know the task", "Wenn die Aufgabe klar ist, nehmen Sie den kürzesten Weg", "任务明确时，直接走最短路径")}</h3>
              <p>{localized("Arama, kategoriler ve Cmd+K ile doğru aracı bulun. Örnek veriyi yükleyin, sonucu cihazınızda üretin ve gerekirse tek tıkla sonraki araca aktarın.", "Use search, categories, or Cmd+K to find the right tool. Load a demo, produce the result on-device, and hand it to the next tool when needed.", "Finden Sie das passende Werkzeug über Suche, Kategorien oder Cmd+K. Beispiel laden, lokal ausführen und das Ergebnis bei Bedarf weitergeben.", "通过搜索、分类或 Cmd+K 找到工具，加载示例，在设备上生成结果，并在需要时传给下一个工具。")}</p>
              <ol className="home-platform-steps"><li><span>01</span>{localized("Aracı bul", "Find", "Finden", "查找")}</li><li><span>02</span>{localized("Yerelde çalıştır", "Run", "Ausführen", "运行")}</li><li><span>03</span>{localized("Sonucu aktar", "Continue", "Weiter", "继续")}</li></ol>
              <footer><Link className="primary-button" href={pathFor(locale, "tools")}>{localized("Araçları keşfet", "Explore tools", "Werkzeuge entdecken", "浏览工具")} →</Link><span>{localized("Hızlı · Odaklı · Ücretsiz", "Fast · Focused · Free", "Schnell · Fokussiert · Kostenlos", "快速 · 专注 · 免费")}</span></footer>
            </article>
            <article className="home-platform-card home-agent-card">
              <header><span className="home-platform-mark" aria-hidden="true">✦</span><div><small>{AGENT_VERSION} · {localized("AKILLI YARDIMCI", "SMART HELPER", "INTELLIGENTER HELFER", "智能助手")}</small><strong>{localized("Ne yapacağınızı anlatın", "Describe what you need", "Beschreiben Sie Ihr Ziel", "描述您的需求")}</strong></div><b>{localized("ÖNERİLEN", "RECOMMENDED", "EMPFOHLEN", "推荐")}</b></header>
                <h3>{localized("Sohbet edin, işi anlatın; sonucu aynı yerde hazırlayın", "Chat, describe the task, and prepare the result in one place", "Sprechen, Aufgabe beschreiben und Ergebnis an einem Ort vorbereiten", "对话、描述任务，并在同一处准备结果")}</h3>
              <p>{localized("ByteQuant AI günlük sorulara yanıt verir, önceki adımları hatırlar, uygun araçları seçer, desteklenen veri işlerini tamamlar ve görselleri cihazınızda düzenler. Daha doğal yanıtlar isterseniz cihazınıza uygun açık kaynak model yalnız onayınızla indirilir.", "ByteQuant AI answers everyday questions, remembers earlier steps, chooses suitable tools, completes supported data tasks, and edits images on your device. For more natural replies, an open-source model suited to your device downloads only with your approval.", "ByteQuant AI beantwortet Alltagsfragen, merkt sich vorige Schritte, wählt passende Werkzeuge, erledigt unterstützte Datenaufgaben und bearbeitet Bilder auf Ihrem Gerät. Ein passendes Open-Source-Modell wird nur mit Ihrer Zustimmung geladen.", "ByteQuant AI 可回答日常问题、记住先前步骤、选择合适工具、完成受支持的数据任务，并在设备上编辑图片。若需要更自然的回答，适合本设备的开源模型只会在您同意后下载。")}</p>
              <ol className="home-platform-steps" aria-label={localized("ByteQuant AI kullanım akışı", "ByteQuant AI usage flow", "Nutzungsablauf von ByteQuant AI", "ByteQuant AI 使用流程")}><li><span>01</span>{localized("Hedefi yaz", "Describe", "Beschreiben", "描述")}</li><li><span>02</span>{localized("Planı denetle", "Review", "Prüfen", "审核")}</li><li><span>03</span>{localized("Adımları çalıştır", "Run", "Ausführen", "执行")}</li></ol>
              <footer><Link className="primary-button platform-agent-button" href={pathFor(locale, "agent")}><b aria-hidden="true">✦</b><span>{localized("ByteQuant AI'ı aç", "Open ByteQuant AI", "ByteQuant AI öffnen", "打开 ByteQuant AI")}</span><i aria-hidden="true">→</i></Link><span>{localized("Hemen başlar · Üyelik gerekmez", "Starts instantly · No account", "Sofort startklar · Kein Konto", "即时开始 · 无需账户")}</span></footer>
            </article>
            <article className="home-platform-card home-workstation-card">
              <header><span className="home-platform-mark" aria-hidden="true">⌘</span><div><small>{localized("GÖRSEL AKIŞ", "VISUAL FLOW", "VISUELLER ABLAUF", "可视化流程")}</small><strong>{localized("Birden fazla aracı sıraya koyun", "Put several tools in order", "Mehrere Werkzeuge verbinden", "按顺序连接多个工具")}</strong></div><b>{localized("ÇOK ADIMLI", "MULTI-STEP", "MEHRSTUFIG", "多步骤")}</b></header>
              <h3>{localized("Araçları bağlayın; projeyi yerel ve düzenlenebilir tutun", "Connect tools and keep the project local and editable", "Werkzeuge verbinden und das Projekt lokal bearbeitbar halten", "连接工具，让项目保持本地且可编辑")}</h3>
              <p>{localized("Hazır bir şablon seçin, adımları görsel olarak takip edin ve kaldığınız yeri bu cihazda saklayın. İsterseniz Ajan planını tek tıkla düzenlenebilir bir akışa dönüştürün.", "Choose a starter, follow each step visually, and keep your place on this device. You can also turn an Agent plan into an editable flow in one click.", "Vorlage wählen, Schritte visuell verfolgen und den Stand auf diesem Gerät sichern. Ein Agentenplan wird mit einem Klick zum bearbeitbaren Ablauf.", "选择模板、可视化跟随步骤，并在本设备保存进度；也可一键把助手计划变成可编辑流程。")}</p>
              <div className="home-workstation-flow" aria-hidden="true"><span>JSON</span><i>→</i><span>{localized("GİZLE", "MASK", "MASKIEREN", "遮蔽")}</span><i>→</i><span>CSV</span><b>{localized("CİHAZDA", "ON DEVICE", "AUF DEM GERÄT", "设备端")}</b></div>
              <footer><Link className="primary-button platform-workstation-button" href={pathFor(locale, "workstation")}><b aria-hidden="true">⌘</b><span>{localized("Görsel akış oluştur", "Build a visual flow", "Visuellen Ablauf erstellen", "创建可视化流程")}</span><i aria-hidden="true">→</i></Link><span>{localized("Hazır örnekler · Geri alma · Kaydetme", "Starters · Undo · Save", "Vorlagen · Rückgängig · Speichern", "模板 · 撤销 · 保存")}</span></footer>
            </article>
          </div>
          <details className="home-platform-boundary"><summary><span aria-hidden="true">ⓘ</span>{localized("ByteQuant AI gizlilik ayrıntıları", "ByteQuant AI privacy details", "Datenschutzdetails zu ByteQuant AI", "ByteQuant AI 隐私详情")}</summary><p>{localized("ByteQuant AI temel planlama ve otomasyonu indirme gerektirmeden başlatır. Daha doğal konuşma için seçilen açık kaynak model yalnız siz onayladığınızda indirilir; uygun ve önceden hazır bir model varsa otomatik kullanılır. Sohbet uzak bir AI servisine gönderilmez; dosya seçme, indirme ve paylaşma her zaman sizin onayınızı gerektirir.", "ByteQuant AI starts core planning and automation without a download. For more natural conversation, the selected open-source model downloads only after your approval; a suitable cached model is reused automatically. Chat is not sent to a remote AI service, and file selection, downloads, and sharing always require your action.", "ByteQuant AI startet Planung und Automatisierung ohne Download. Für natürlichere Gespräche wird das gewählte Open-Source-Modell nur nach Zustimmung geladen; ein bereits vorhandenes passendes Modell wird automatisch wiederverwendet. Gespräche gehen nicht an einen entfernten KI-Dienst; Dateiauswahl, Download und Freigabe bleiben unter Ihrer Kontrolle.", "ByteQuant AI 的基础规划与自动化无需下载即可启动。为了获得更自然的对话，所选开源模型只会在您同意后下载；若设备已有合适缓存则会自动复用。对话不会发送到远程 AI 服务，文件选择、下载与分享始终由您确认。")}</p></details>
        </div>
      </section>

      <PersonalToolsHub locale={locale} />
      <InteractiveDemo locale={locale} />
      <section className="home-social-strip"><div className="container"><div><span aria-hidden="true">◎</span><p><strong>{localized("Topluluktaki yöntemleri keşfedin", "Discover community methods", "Methoden der Community entdecken", "发现社区方法")}</strong>{localized("Global akışı hesap açmadan okuyun. Paylaşmak isterseniz profil anahtarınız yalnızca cihazınızda korunur.", "Read the global feed without an account. If you choose to post, your profile key is protected on your device.", "Lesen Sie den globalen Feed ohne Konto. Wenn Sie posten, bleibt Ihr Profilschlüssel geschützt auf Ihrem Gerät.", "无需账户即可阅读全球动态；如果选择发布，个人资料密钥会保存在您的设备上。")}</p><Link href={pathFor(locale, "community")}>{localized("Topluluğu aç", "Open community", "Community öffnen", "打开社区")} →</Link></div><div><span aria-hidden="true">◉</span><p><strong>{localized("Kaynağıyla gündem", "Updates with sources", "Aktuell mit Quellen", "带来源的动态")}</strong>{localized("Bilim, AI ve güvenlik başlıklarını resmî kaynağa giderek doğrulayın.", "Follow science, AI, and security headlines back to official sources.", "Wissenschaft, KI und Sicherheit direkt an offiziellen Quellen prüfen.", "从官方来源核验科学、AI 与安全动态。")}</p><Link href={pathFor(locale, "news")}>{localized("Gündeme git", "View updates", "Aktuell öffnen", "查看动态")} →</Link></div></div></section>
      <PwaInstall locale={locale} />

      <section className="section open-source-section" aria-labelledby="open-source-title">
        <div className="container open-source-grid">
          <div className="open-source-copy">
            <span className="open-source-badge">MIT · OPEN SOURCE · AUDITABLE</span>
            <h2 id="open-source-title">{localized("Kaynak kodunu görün, güvenlik iddialarını kendiniz doğrulayın", "See the source and verify the privacy claims yourself", "Quellcode einsehen und Datenschutzangaben selbst prüfen", "查看源代码，亲自核验隐私声明")}</h2>
            <p>{localized("ByteQuant'ın araç mantığı, üretim bağımlılıkları, testleri ve yayın geçmişi GitHub'da herkese açıktır. Böylece yalnızca bir güven sözü okumaz; hangi kodun tarayıcınızda çalıştığını ve her değişikliğin hangi kontrollerden geçtiğini inceleyebilirsiniz.", "ByteQuant's tool logic, production dependencies, tests, and release history are public on GitHub. You can inspect what runs in your browser and which checks guard every change instead of relying on a privacy promise alone.", "Werkzeuglogik, Produktionsabhängigkeiten, Tests und Veröffentlichungsverlauf sind auf GitHub öffentlich. So können Sie prüfen, welcher Code im Browser läuft und welche Kontrollen jede Änderung absichern.", "ByteQuant 的工具逻辑、生产依赖、测试与发布记录均在 GitHub 公开。您可以检查浏览器实际运行的代码，以及每项变更经过的质量检查，而不必只依赖隐私承诺。")}</p>
            <ul className="open-source-proof-list"><li>{localized("MIT lisansı ve sürüm sabitlemeli bağımlılıklar", "MIT licence and version-locked dependencies", "MIT-Lizenz und festgeschriebene Abhängigkeiten", "MIT 许可证与锁定版本的依赖")}</li><li>{localized("Her ana dal güncellemesinde test ve üretim derlemesi", "Tests and a production build on every main-branch update", "Tests und Produktions-Build bei jeder Hauptzweig-Aktualisierung", "主分支每次更新均执行测试与生产构建")}</li><li>{localized("Hata bildirimi ve katkı için açık proje geçmişi", "Open project history for issue review and contributions", "Offener Projektverlauf für Fehlerprüfung und Beiträge", "开放的项目历史，便于问题审查与贡献")}</li></ul>
            <div className="open-source-actions"><Link className="primary-button" href="https://github.com/byte-quant/bytequant" target="_blank" rel="noreferrer noopener" aria-label={localized("ByteQuant kaynak kodunu GitHub'da incele; yeni sekmede açılır", "Inspect ByteQuant source on GitHub; opens in a new tab", "ByteQuant-Quellcode auf GitHub prüfen; öffnet in neuem Tab", "在 GitHub 查看 ByteQuant 源代码；将在新标签页打开")}>{localized("Kaynak kodunu GitHub'da incele", "Inspect the source on GitHub", "Quellcode auf GitHub prüfen", "在 GitHub 查看源代码")} ↗</Link><Link className="secondary-button" href={pathFor(locale, "community")}>{localized("Topluluğa katıl", "Join the community", "Community öffnen", "加入社区")} →</Link></div>
          </div>
          <GitHubActivity locale={locale} />
        </div>
      </section>

      <section className="section category-section home-tool-discovery" id={locale === "tr" ? "araclar" : "tools"}>
        <div className="container">
          <div className="section-heading split-heading"><div><span className="kicker">{localized("ARAÇLARI KEŞFEDİN", "DISCOVER TOOLS", "WERKZEUGE ENTDECKEN", "发现工具")}</span><h2>{localized("Önce ihtiyacınızı seçin", "Start with what you need", "Beginnen Sie mit Ihrem Bedarf", "先选择您的需求")}</h2></div><p>{localized("En sık kullanılan araçları burada derledik. Kütüphanede arama yapabilir veya on kategoriden birini seçerek tüm araçlara ulaşabilirsiniz.", "We collected the most-used starting points here. Search the full library or choose one of ten categories to reach every tool.", "Hier finden Sie beliebte Einstiege. Durchsuchen Sie die vollständige Bibliothek oder wählen Sie eine von zehn Kategorien.", "这里汇集了常用入口。您可以搜索完整工具库，也可以从十个类别中进行选择。")}</p></div>
          <div className="home-featured-tools tool-grid">{featuredTools.map((tool) => <ToolCard key={tool.slug} tool={tool} locale={locale} />)}</div>
          <div className="home-category-summary" aria-label={localized("Araç kategorileri", "Tool categories", "Werkzeugkategorien", "工具类别")}>{(Object.keys(categories) as ToolCategory[]).map((key) => <Link key={key} href={`${pathFor(locale, "tools")}#category-${key}`}><span className={`category-dot category-${key}`}>{categories[key].mark}</span><span><strong>{categories[key].label[locale]}</strong><small>{tools.filter((tool) => tool.category === key).length} {localized("araç", "tools", "Werkzeuge", "个工具")}</small></span><b aria-hidden="true">→</b></Link>)}</div>
          <div className="center-action"><Link className="primary-button" href={pathFor(locale, "tools")}>{localized(`Tüm ${tools.length} aracı görüntüle`, `View all ${tools.length} tools`, `Alle ${tools.length} Werkzeuge anzeigen`, `查看全部 ${tools.length} 个工具`)} →</Link></div>
        </div>
      </section>


      <section className="section workflow-section">
        <div className="container workflow-grid"><div className="workflow-copy"><span className="kicker">{localized("NASIL ÇALIŞIR?", "HOW IT WORKS", "SO FUNKTIONIERT ES", "工作原理")}</span><h2>{localized("Üç adımda güvenli bir sonuç", "A safer result in three steps", "In drei Schritten zum sicheren Ergebnis", "三步获得更安全的结果")}</h2><p>{localized("Girdiniz işlenmek için ByteQuant sunucusuna gönderilmez. Böylece günlük işlerinizi gereksiz veri kopyası oluşturmadan tamamlayabilirsiniz.", "Your input is not sent to ByteQuant servers for processing, so you can complete everyday tasks without creating unnecessary data copies.", "Ihre Eingabe wird nicht zur Verarbeitung an ByteQuant-Server gesendet. So erledigen Sie Alltagsaufgaben ohne unnötige Datenkopien.", "您的输入不会发送到 ByteQuant 服务器处理，因此可以在不产生多余数据副本的情况下完成日常任务。")}</p><Link className="text-link" href={postPath(editorialLocale, "client-side-ai-araclari-nedir")} hrefLang={editorialLocale}>{localized("Tarayıcıda çalışma rehberini okuyun", "Read how in-browser tools work", "Mehr über Browser-Werkzeuge erfahren", "了解浏览器内工具如何工作")} →</Link></div><ol className="workflow-steps"><li><span>01</span><div><strong>{localized("Girdinizi ekleyin", "Add your input", "Eingabe hinzufügen", "添加输入")}</strong><p>{localized("Metni yazın veya desteklenen dosyayı seçin.", "Type the text or choose a supported file.", "Text eingeben oder eine unterstützte Datei wählen.", "输入文本或选择受支持的文件。")}</p></div></li><li><span>02</span><div><strong>{localized("İşlemi çalıştırın", "Run the task", "Aufgabe ausführen", "运行任务")}</strong><p>{localized("Tarayıcınız sonucu doğrudan bu sekmede hazırlar.", "Your browser prepares the result directly in this tab.", "Ihr Browser erstellt das Ergebnis direkt in diesem Tab.", "浏览器会直接在当前标签页生成结果。")}</p></div></li><li><span>03</span><div><strong>{localized("Sonucu siz yönetin", "You control the result", "Sie kontrollieren das Ergebnis", "由您控制结果")}</strong><p>{localized("Kontrol edin, kopyalayın, indirin veya sekmeyle birlikte kapatın.", "Review, copy, download, or close it with the tab.", "Prüfen, kopieren, herunterladen oder mit dem Tab schließen.", "检查、复制、下载，或随标签页一起关闭。")}</p></div></li></ol></div>
      </section>

      <section className="section editorial-section">
        <div className="container"><div className="section-heading split-heading"><div><span className="kicker">{localized("REHBERLER", "GUIDES", "RATGEBER", "指南")}</span><h2>{localized("Aracı değil, doğru yöntemi öğrenin", "Learn the method, not only the tool", "Lernen Sie die Methode, nicht nur das Werkzeug", "学习方法，而不只是工具")}</h2></div><p>{localized("Yeni araçların tamamı için dört dilde adım adım kullanım, varsayım, hata sınırı ve bağımsız doğrulama içeriği; ayrıca veri/SEO, metin/hesaplama, kriptografi ve RAG güvenliği için dört derin çalışma rehberi.", "Every new tool includes four-language steps, assumptions, error boundaries, and independent verification, plus four deep workflow guides for data/SEO, text/calculation, cryptography, and RAG safety.", "Alle neuen Werkzeuge enthalten Schritte, Annahmen, Fehlergrenzen und unabhängige Prüfung in vier Sprachen sowie vier vertiefende Ratgeber zu Daten/SEO, Text/Berechnung, Kryptografie und RAG-Sicherheit.", "所有新工具均提供四语言步骤、假设、错误边界与独立核验，并新增数据/SEO、文本/计算、密码学和 RAG 安全四篇深度指南。")}</p></div><div className="post-grid">{guideCards.map((guide, index) => <article className={`post-card post-card-${index + 1}`} key={guide.slug}><span>{guide.category} · {guide.readTime}</span><h3><Link href={guide.href} hrefLang={guide.hrefLang}>{guide.title}</Link></h3><p>{guide.excerpt}</p><Link className="text-link" href={guide.href} hrefLang={guide.hrefLang}>{localized("Rehberi oku", "Read guide", "Ratgeber lesen", "阅读指南")} →</Link></article>)}</div><div className="center-action"><Link className="secondary-button" href={pathFor(locale, "blog")}>{localized("Tüm rehberleri görüntüle", "View all guides", "Alle Ratgeber", "查看全部指南")}</Link></div></div>
      </section>


      <section className="section principles-section"><div className="container"><div className="section-heading centered"><span className="kicker">{localized("NEDEN BYTEQUANT?", "WHY BYTEQUANT?", "WARUM BYTEQUANT?", "为什么选择 BYTEQUANT？")}</span><h2>{localized("Gösterişli iddialar yerine denetlenebilir ilkeler", "Auditable principles instead of flashy claims", "Prüfbare Prinzipien statt großer Versprechen", "用可核验原则取代夸张承诺")}</h2></div><div className="principle-grid"><article><span>↘</span><h3>{localized("Yerel varsayılan", "Local by default", "Standardmäßig lokal", "默认本地处理")}</h3><p>{localized("Sunucu gerektirmeyen görevler cihazınızda kalır. Yeni dış hizmet eklenirse açıkça belirtilir.", "Tasks that do not need a server stay on-device. Any future external service will be disclosed.", "Aufgaben ohne Serverbedarf bleiben auf dem Gerät. Neue externe Dienste werden offengelegt.", "无需服务器的任务保留在设备上。未来新增外部服务会明确说明。")}</p></article><article><span>≋</span><h3>{localized("Açıklanabilir yöntem", "Explainable methods", "Nachvollziehbare Methoden", "可解释方法")}</h3><p>{localized("Skorların ve dönüşümlerin neye dayandığını, yaklaşık sonuçları ve sınırları gösteririz.", "We disclose what scores and transformations use, including estimates and limitations.", "Wir erklären Grundlagen, Näherungen und Grenzen von Bewertungen und Konvertierungen.", "我们说明评分与转换的依据、估算方式和限制。")}</p></article><article><span>□</span><h3>{localized("Tek iş, net çıktı", "One job, clear output", "Eine Aufgabe, klare Ausgabe", "一项任务，清晰输出")}</h3><p>{localized("Araçlar gereksiz panel karmaşası olmadan tek bir sorunu çözmeye odaklanır.", "Tools focus on one problem without unnecessary dashboard complexity.", "Werkzeuge konzentrieren sich ohne unnötige Oberfläche auf ein Problem.", "工具专注解决一个问题，避免不必要的界面复杂度。")}</p></article><article><span>✓</span><h3>{localized("Dürüst sınırlar", "Honest limitations", "Ehrliche Grenzen", "诚实说明限制")}</h3><p>{localized("Otomatik sonuçların uzman görüşü veya hukuki uygunluk garantisi olmadığını açıkça söyleriz.", "Automated output is never presented as expert opinion or legal compliance assurance.", "Automatische Ausgaben werden nicht als Fachmeinung oder Rechtsgarantie dargestellt.", "自动输出不会被描述为专业意见或法律合规保证。")}</p></article></div></div></section>

      <section className="section faq-section"><div className="container faq-layout"><div><span className="kicker">{localized("SIK SORULAN SORULAR", "FREQUENTLY ASKED QUESTIONS", "HÄUFIGE FRAGEN", "常见问题")}</span><h2>{localized("Başlamadan önce bilmeniz gerekenler", "What to know before you start", "Was Sie vor dem Start wissen sollten", "开始前需要了解的事项")}</h2><p>{localized("Başka bir sorunuz varsa bize yazın; ürün davranışı ve gizlilik açıklamalarını açık tutmayı önemsiyoruz.", "If your question is not here, contact us. We value clear explanations of product behavior and privacy.", "Wenn Ihre Frage fehlt, kontaktieren Sie uns. Klare Produkt- und Datenschutzerklärungen sind uns wichtig.", "如果这里没有您的问题，请联系我们。我们重视清晰的产品行为与隐私说明。")}</p><Link className="secondary-button" href={pathFor(locale, "contact")}>{localized("Bize ulaşın", "Contact us", "Kontakt", "联系我们")}</Link></div><div className="faq-list">{faqs[locale].map(([question, answer], index) => <details key={question} open={index === 0}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></div></section>

      <section className="cta-band"><div className="container"><div><span>{localized(`${tools.length} BENZERSİZ ARAÇ · ÜCRETSİZ · ÜYELİKSİZ`, `${tools.length} DISTINCT TOOLS · FREE · NO ACCOUNT`, `${tools.length} EIGENSTÄNDIGE WERKZEUGE · KOSTENLOS · KEIN KONTO`, `${tools.length} 个独立工具 · 免费 · 无需账户`)}</span><h2>{localized("İlk işleminizi cihazınızda tamamlayın.", "Complete your first task on-device.", "Erledigen Sie Ihre erste Aufgabe auf dem Gerät.", "在设备上完成第一项任务。")}</h2></div><Link className="light-button" href={toolPath(locale, "kvkk-veri-maskeleyici")}>{localized("Gizlilik aracını deneyin", "Try the privacy tool", "Datenschutzwerkzeug testen", "试用隐私工具")} →</Link></div></section>
    </SiteShell>
  );
}
