import { newsGeneratedAt, newsItems } from "../lib/generated-news";
import { absoluteUrl, languageTag, organizationId, pathFor, type Locale } from "../lib/site";
import { NewsFeedClient } from "./NewsFeedClient";
import { SchemaScript } from "./SchemaScript";
import { SiteShell } from "./SiteShell";

const copy = {
  tr: { eyebrow: "BYTEQUANT GÜNDEM", title: "Gürültü yerine kaynağı görün: bilim, teknoloji ve güvenlik gündemi", intro: "NASA, NIST, CISA ve açık lisanslı GOV.UK akışlarından doğrulanabilir başlık, tarih ve özgün bağlantı alınır. Yeniden kullanıma açık kaynaklarda kısa akış özeti gösterilir; dört dildeki okuma kartı neyi doğrulamanız gerektiğini anlatır.", update: "Kaynak özeti güncellendi", method: "Kaynak ve yeniden kullanım yöntemi", desk: "Bölgenizdeki resmî kaynaklara gidin", deskIntro: "Bu bağlantılar tarayıcıda canlı çekilmez ve ByteQuant içinde kopyalanmaz. Yerel dildeki gelişmeleri doğrudan kurumun kendi sayfasından izleyebilirsiniz.", notes: ["Yalnızca allowlist içindeki HTTPS NASA, NIST, CISA ve GOV.UK akışları derleme sırasında okunur.", "Başlık, tarih ve özgün bağlantı her kartta kaynağa bağlıdır; kısa özet yalnızca resmî akışın yeniden kullanım koşulları izin verdiğinde gösterilir.", "GOV.UK bilgisi Open Government Licence v3.0 koşulları ve kaynak atfıyla kullanılır; üçüncü taraf görseller yeniden yayımlanmaz.", "Bir başlığın görünmesi ByteQuant onayı değildir; karar vermeden önce özgün kaynağı okuyun."] },
  en: { eyebrow: "BYTEQUANT UPDATES", title: "See the source, not the noise: science, technology, and security updates", intro: "Verifiable titles, dates, and original links come from NASA, NIST, CISA, and openly licensed GOV.UK feeds. A short feed summary appears only where reuse terms allow it, with a four-language lens explaining what to verify.", update: "Source snapshot updated", method: "Source and reuse method", desk: "Open official sources for your region", deskIntro: "These pages are not fetched live or copied into ByteQuant. Use them to follow developments directly in the institution's own language and context.", notes: ["Only allowlisted HTTPS NASA, NIST, CISA, and GOV.UK feeds are read at build time.", "Every card stays tied to its title, date, and original link; a short summary appears only when the official feed's reuse terms allow it.", "GOV.UK information is reused with attribution under the Open Government Licence v3.0; third-party imagery is not republished.", "Inclusion is not a ByteQuant endorsement; read the original before making a decision."] },
  de: { eyebrow: "BYTEQUANT AKTUELL", title: "Quelle statt Rauschen: Wissenschaft, Technik und Sicherheit", intro: "Prüfbare Titel, Datum und Originallink stammen aus NASA-, NIST-, CISA- und offen lizenzierten GOV.UK-Feeds. Kurze Feed-Zusammenfassungen erscheinen nur bei erlaubter Wiederverwendung; der Leserahmen nennt die nötigen Prüfungen.", update: "Quellenstand aktualisiert", method: "Quellen- und Nutzungsmethode", desk: "Offizielle Quellen Ihrer Region öffnen", deskIntro: "Diese Seiten werden nicht live in ByteQuant geladen oder kopiert. Verfolgen Sie Meldungen direkt im sprachlichen und institutionellen Kontext der Quelle.", notes: ["Nur erlaubte HTTPS-Feeds von NASA, NIST, CISA und GOV.UK werden beim Build gelesen.", "Jede Karte bleibt an Titel, Datum und Originallink gebunden; ein Kurztext erscheint nur bei zulässiger Wiederverwendung.", "GOV.UK-Informationen werden mit Quellenangabe unter der Open Government Licence v3.0 genutzt; Drittbilder werden nicht erneut veröffentlicht.", "Aufnahme ist keine Empfehlung durch ByteQuant; vor Entscheidungen die Originalquelle lesen."] },
  zh: { eyebrow: "BYTEQUANT 动态", title: "少一点噪声，多一点来源：科学、技术与安全动态", intro: "可核验标题、日期与原始链接来自 NASA、NIST、CISA 和开放许可的 GOV.UK Feed。仅在复用条款允许时显示简短 Feed 摘要，并用四种语言提供核验提示。", update: "来源快照更新时间", method: "来源与复用方法", desk: "打开您所在地区的官方来源", deskIntro: "这些页面不会被 ByteQuant 实时抓取或复制。您可在机构自身的语言与语境中直接查看动态。", notes: ["仅在构建时读取白名单内的 NASA、NIST、CISA 与 GOV.UK HTTPS Feed。", "每张卡片均保留标题、日期与原始链接；仅在官方 Feed 复用条款允许时显示短摘要。", "GOV.UK 信息依据 Open Government Licence v3.0 并注明来源使用；不转载第三方图片。", "收录不代表 ByteQuant 背书；做出决定前请阅读原始来源。"] },
} as const;

const regionalSources = [
  { code: "TR", name: "TÜBİTAK Haberler", url: "https://tubitak.gov.tr/tr/haberler", descriptions: { tr: "Türkiye'den bilim, araştırma ve teknoloji duyuruları.", en: "Science, research, and technology announcements from Türkiye.", de: "Wissenschafts- und Technikmeldungen aus der Türkei.", zh: "来自土耳其的科学、研究与技术动态。" } },
  { code: "UK", name: "GOV.UK · AI & technology", url: "https://www.gov.uk/search/news-and-communications?keywords=artificial%20intelligence", descriptions: { tr: "Birleşik Krallık kamu kurumlarının AI ve teknoloji duyuruları.", en: "UK public-sector AI and technology announcements.", de: "KI- und Technikmeldungen des britischen öffentlichen Sektors.", zh: "英国公共部门的 AI 与技术公告。" } },
  { code: "DE", name: "BSI Meldungen", url: "https://www.bsi.bund.de/DE/Service-Navi/Presse/Alle-Meldungen-News/alle-meldungen-news_node.html", descriptions: { tr: "Almanya Federal Bilgi Güvenliği Dairesinin güncel duyuruları.", en: "Updates from Germany's Federal Office for Information Security.", de: "Aktuelle Meldungen des Bundesamts für Sicherheit in der Informationstechnik.", zh: "德国联邦信息安全办公室的最新动态。" } },
  { code: "CN", name: "中国科学院 · CAS", url: "https://www.cas.cn/cm/", descriptions: { tr: "Çin Bilimler Akademisinin araştırma ve bilim iletişimi akışı.", en: "Research and science communication from the Chinese Academy of Sciences.", de: "Forschungs- und Wissenschaftsmeldungen der Chinesischen Akademie der Wissenschaften.", zh: "中国科学院的科研与科学传播动态。" } },
] as const;

export function NewsPage({ locale }: { locale: Locale }) {
  const t = copy[locale]; const url = absoluteUrl(pathFor(locale, "news"));
  const schema = { "@context": "https://schema.org", "@type": "CollectionPage", name: t.title, description: t.intro, url, inLanguage: languageTag(locale), isPartOf: { "@id": `${absoluteUrl(pathFor(locale, "home"))}#website` }, publisher: { "@id": organizationId }, mainEntity: { "@type": "ItemList", itemListElement: newsItems.slice(0, 20).map((item, index) => ({ "@type": "ListItem", position: index + 1, url: item.url, name: item.title })) } };
  return <SiteShell locale={locale} alternateHref={pathFor(locale === "tr" ? "en" : "tr", "news")} languageHrefs={{ tr: pathFor("tr", "news"), en: pathFor("en", "news"), de: pathFor("de", "news"), zh: pathFor("zh", "news") }}><SchemaScript data={schema} /><main className="news-page"><section className="news-hero"><div className="container"><span className="eyebrow"><i />{t.eyebrow}</span><h1>{t.title}</h1><p>{t.intro}</p><small>{t.update}: <time dateTime={newsGeneratedAt}>{new Date(newsGeneratedAt).toLocaleDateString(locale, { year: "numeric", month: "long", day: "numeric" })}</time></small></div></section><section className="section"><div className="container"><NewsFeedClient locale={locale} items={newsItems} /></div></section><section className="section news-regional"><div className="container"><div className="section-heading split-heading"><div><span className="kicker">REGIONAL SOURCE DESK</span><h2>{t.desk}</h2></div><p>{t.deskIntro}</p></div><div className="news-regional-grid">{regionalSources.map((source) => <a key={source.code} href={source.url} target="_blank" rel="noreferrer noopener"><span>{source.code}</span><div><strong>{source.name}</strong><p>{source.descriptions[locale]}</p></div><b>↗</b></a>)}</div></div></section><section className="section news-method"><div className="container"><div><span className="kicker">SOURCE TRANSPARENCY</span><h2>{t.method}</h2></div><ul>{t.notes.map((note) => <li key={note}>✓ <span>{note}</span></li>)}</ul></div></section></main></SiteShell>;
}
