import { newsGeneratedAt, newsItems } from "../lib/generated-news";
import { absoluteUrl, languageTag, organizationId, pathFor, type Locale } from "../lib/site";
import { NewsFeedClient } from "./NewsFeedClient";
import { SchemaScript } from "./SchemaScript";
import { SiteShell } from "./SiteShell";

const copy = {
  tr: { eyebrow: "BYTEQUANT GÜNDEM", title: "Bilim, teknoloji ve güvenlikte doğrulanabilir gelişmeler", intro: "Başlıkları otomatik olarak yalnızca resmî NASA ve NIST RSS kaynaklarından alırız. Tam metni kopyalamayız; her kart sizi özgün kaynağa götürür. Beğeni ve kayıt tercihleri cihazınızda kalır.", update: "Kaynak özeti güncellendi", method: "Kaynak ve lisans yöntemi", notes: ["Yalnızca önceden izin verilen HTTPS NASA/NIST alan adları okunur.", "Başlık, tarih ve özgün bağlantı dışında makale metni veya görseli yeniden yayımlanmaz.", "Akış alınamazsa son denetlenmiş yerel liste gösterilir; sayfa sonsuz istek döngüsüne girmez.", "Bir başlığın görünmesi ByteQuant onayı değildir; karar vermeden önce özgün kaynağı okuyun."] },
  en: { eyebrow: "BYTEQUANT UPDATES", title: "Verifiable developments in science, technology, and security", intro: "Headlines are collected automatically only from official NASA and NIST RSS sources. We do not republish full articles; every card leads to the original source. Likes and saved items remain on your device.", update: "Source snapshot updated", method: "Source and reuse method", notes: ["Only pre-approved HTTPS NASA/NIST domains are fetched.", "No article body or image is republished beyond title, date, and original link.", "If a feed is unavailable, the last reviewed local list appears; the page never enters an infinite request loop.", "Inclusion is not a ByteQuant endorsement; read the original before making a decision."] },
  de: { eyebrow: "BYTEQUANT AKTUELL", title: "Prüfbare Entwicklungen aus Wissenschaft, Technik und Sicherheit", intro: "Überschriften werden automatisch nur aus offiziellen NASA- und NIST-RSS-Quellen übernommen. Volltexte werden nicht wiederveröffentlicht; jede Karte führt zur Originalquelle. Favoriten bleiben auf Ihrem Gerät.", update: "Quellenstand aktualisiert", method: "Quellen- und Nutzungsmethode", notes: ["Nur vorab freigegebene HTTPS-Domains von NASA/NIST werden abgerufen.", "Neben Titel, Datum und Originallink werden weder Artikeltext noch Bilder erneut veröffentlicht.", "Ist ein Feed nicht erreichbar, erscheint die letzte geprüfte lokale Liste; keine Endlosschleife.", "Aufnahme ist keine Empfehlung durch ByteQuant; vor Entscheidungen die Originalquelle lesen."] },
  zh: { eyebrow: "BYTEQUANT 动态", title: "可核验的科学、技术与安全进展", intro: "标题仅从 NASA 与 NIST 官方 RSS 来源自动收集。我们不转载全文；每张卡片都会前往原始来源。收藏与偏好只保存在您的设备上。", update: "来源快照更新时间", method: "来源与复用方法", notes: ["仅抓取预先批准的 NASA/NIST HTTPS 域名。", "除标题、日期和原始链接外，不转载文章正文或图片。", "若 Feed 不可用，则显示最近审核的本地列表；页面不会进入无限请求循环。", "收录不代表 ByteQuant 背书；做出决定前请阅读原始来源。"] },
} as const;

export function NewsPage({ locale }: { locale: Locale }) {
  const t = copy[locale]; const url = absoluteUrl(pathFor(locale, "news"));
  const schema = { "@context": "https://schema.org", "@type": "CollectionPage", name: t.title, description: t.intro, url, inLanguage: languageTag(locale), isPartOf: { "@id": `${absoluteUrl(pathFor(locale, "home"))}#website` }, publisher: { "@id": organizationId }, mainEntity: { "@type": "ItemList", itemListElement: newsItems.slice(0, 20).map((item, index) => ({ "@type": "ListItem", position: index + 1, url: item.url, name: item.title })) } };
  return <SiteShell locale={locale} alternateHref={pathFor(locale === "tr" ? "en" : "tr", "news")} languageHrefs={{ tr: pathFor("tr", "news"), en: pathFor("en", "news"), de: pathFor("de", "news"), zh: pathFor("zh", "news") }}><SchemaScript data={schema} /><main className="news-page"><section className="news-hero"><div className="container"><span className="eyebrow"><i />{t.eyebrow}</span><h1>{t.title}</h1><p>{t.intro}</p><small>{t.update}: <time dateTime={newsGeneratedAt}>{new Date(newsGeneratedAt).toLocaleDateString(locale, { year: "numeric", month: "long", day: "numeric" })}</time></small></div></section><section className="section"><div className="container"><NewsFeedClient locale={locale} items={newsItems} /></div></section><section className="section news-method"><div className="container"><div><span className="kicker">SOURCE TRANSPARENCY</span><h2>{t.method}</h2></div><ul>{t.notes.map((note) => <li key={note}>✓ <span>{note}</span></li>)}</ul></div></section></main></SiteShell>;
}
