"use client";

import { useMemo, useState } from "react";
import type { Locale } from "../lib/site";
import type { NewsItem } from "../lib/generated-news";

const copy = {
  tr: { all: "Tümü", savedOnly: "Kaydedilenler", science: "Bilim", technology: "Teknoloji ve AI", security: "Siber güvenlik", standards: "Standartlar", search: "Başlık ve kaynakta ara", save: "Sonra oku", saved: "Kaydedildi", share: "Paylaş", open: "Resmî kaynağı aç", more: "Daha fazla göster", empty: "Bu filtrede içerik bulunamadı.", local: "Kaydedilenler yalnızca bu cihazda tutulur.", source: "Yeni sekmede resmî kaynağa gider", original: "Özgün İngilizce başlık", context: "Bu neden önemli?", sourceFilter: "Kaynak", allSources: "Tüm kaynaklar", showing: "güncelleme gösteriliyor", lenses: { science: "Bilimsel gelişmeyi bağlamıyla değerlendirin; bulgu, duyuru ve görsel içeriği birbirinden ayırın.", technology: "Ürün veya politika duyurusunu gerçek kullanım, güvenlik ve uygulanabilirlik açısından resmî kaynaktan doğrulayın.", security: "Güvenlik haberini doğrudan eylem talimatı saymayın; etkilenen sürüm, kapsam ve düzeltmeyi resmî kaynaktan kontrol edin.", standards: "Standart ve ölçüm güncellemelerinde sürüm, yürürlük tarihi ve kapsamı uygulamadan önce doğrulayın." } },
  en: { all: "All", savedOnly: "Saved", science: "Science", technology: "Technology & AI", security: "Cybersecurity", standards: "Standards", search: "Search titles and sources", save: "Read later", saved: "Saved", share: "Share", open: "Open official source", more: "Show more", empty: "No item matches this filter.", local: "Saved items stay only on this device.", source: "Opens the official source in a new tab", original: "Original English headline", context: "Why this matters", sourceFilter: "Source", allSources: "All sources", showing: "updates shown", lenses: { science: "Read the development in context and distinguish a research finding from an announcement or image feature.", technology: "Verify a product or policy announcement against its practical scope, safety implications, and official source.", security: "Do not treat a security headline as an action plan; confirm affected versions, scope, and remediation at the source.", standards: "Check the version, effective date, and scope of a standards or measurement update before applying it." } },
  de: { all: "Alle", savedOnly: "Gespeichert", science: "Wissenschaft", technology: "Technologie & KI", security: "Cybersicherheit", standards: "Standards", search: "Titel und Quellen durchsuchen", save: "Später lesen", saved: "Gespeichert", share: "Teilen", open: "Offizielle Quelle öffnen", more: "Mehr anzeigen", empty: "Keine Meldung entspricht dem Filter.", local: "Gespeicherte Einträge bleiben nur auf diesem Gerät.", source: "Öffnet die offizielle Quelle in einem neuen Tab", original: "Englischer Originaltitel", context: "Warum ist das wichtig?", sourceFilter: "Quelle", allSources: "Alle Quellen", showing: "Meldungen angezeigt", lenses: { science: "Entwicklung im Kontext lesen und Forschungsergebnis, Ankündigung und Bildbeitrag voneinander unterscheiden.", technology: "Produkt- oder Politikankündigungen anhand von praktischem Umfang, Sicherheit und offizieller Quelle prüfen.", security: "Eine Sicherheitsmeldung ist kein Maßnahmenplan: betroffene Version, Umfang und Abhilfe an der Quelle prüfen.", standards: "Vor der Anwendung Version, Gültigkeitsdatum und Umfang einer Standard- oder Messänderung prüfen." } },
  zh: { all: "全部", savedOnly: "已收藏", science: "科学", technology: "技术与 AI", security: "网络安全", standards: "标准", search: "搜索标题和来源", save: "稍后阅读", saved: "已收藏", share: "分享", open: "打开官方来源", more: "显示更多", empty: "该筛选条件下没有内容。", local: "收藏仅保存在此设备。", source: "在新标签页打开官方来源", original: "英文原始标题", context: "为什么值得关注？", sourceFilter: "来源", allSources: "全部来源", showing: "条动态", lenses: { science: "结合上下文阅读，并区分研究发现、机构公告与图片类内容。", technology: "从实际范围、安全影响与官方来源三个角度核验产品或政策公告。", security: "不要把安全标题直接当作处置方案；请在来源页核对受影响版本、范围与修复措施。", standards: "采用标准或测量更新前，请核对版本、生效日期与适用范围。" } },
} as const;
const key = "bytequant:news-favorites:v1";

export function NewsFeedClient({ locale, items }: { locale: Locale; items: NewsItem[] }) {
  const t = copy[locale];
  const [category, setCategory] = useState<"all" | NewsItem["category"]>("all");
  const [source, setSource] = useState<"all" | NewsItem["source"]>("all");
  const [savedOnly, setSavedOnly] = useState(false); const [query, setQuery] = useState(""); const [limit, setLimit] = useState(12);
  const [favorites, setFavorites] = useState<string[]>(() => { if (typeof window === "undefined") return []; try { const parsed: unknown = JSON.parse(localStorage.getItem(key) ?? "[]"); return Array.isArray(parsed) ? parsed.filter((item): item is string => typeof item === "string").slice(-200) : []; } catch { return []; } });
  const sources = useMemo(() => [...new Set(items.map((item) => item.source))], [items]);
  const filtered = useMemo(() => items.filter((item) => category === "all" || item.category === category).filter((item) => source === "all" || item.source === source).filter((item) => !savedOnly || favorites.includes(item.id)).filter((item) => `${item.title} ${item.source}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())), [category, favorites, items, query, savedOnly, source]);
  const visible = filtered.slice(0, limit);
  function toggle(id: string) { setFavorites((current) => { const next = current.includes(id) ? current.filter((item) => item !== id) : [...current, id].slice(-200); try { localStorage.setItem(key, JSON.stringify(next)); } catch { /* optional preference */ } return next; }); }
  async function share(item: NewsItem) { if (navigator.share) { try { await navigator.share({ title: item.title, url: item.url }); return; } catch { return; } } try { await navigator.clipboard.writeText(`${item.title}\n${item.url}`); } catch { /* source link stays available */ } }
  const filters: Array<[typeof category, string]> = [["all", t.all], ["science", t.science], ["technology", t.technology], ["security", t.security], ["standards", t.standards]];
  return <section className="news-feed">
    <div className="news-controls"><div>{filters.map(([value, label]) => <button type="button" className={category === value && !savedOnly ? "active" : ""} key={value} onClick={() => { setCategory(value); setSavedOnly(false); setLimit(12); }}>{label}</button>)}<button type="button" className={savedOnly ? "active" : ""} onClick={() => { setSavedOnly(true); setLimit(12); }}>☆ {t.savedOnly} · {favorites.length}</button></div><label><span>⌕</span><input type="search" value={query} placeholder={t.search} onChange={(event) => { setQuery(event.target.value); setLimit(12); }} /></label></div>
    <div className="news-source-row"><span>{t.sourceFilter}</span><button type="button" className={source === "all" ? "active" : ""} onClick={() => setSource("all")}>{t.allSources}</button>{sources.map((item) => <button type="button" className={source === item ? "active" : ""} key={item} onClick={() => setSource(item)}>{item}</button>)}<small>{filtered.length} {t.showing}</small></div>
    <small className="news-local-note">◉ {t.local}</small>
    <div className="news-grid">{visible.map((item) => <article key={item.id}><header><span>{t[item.category]}</span><small>{item.source} · {item.region === "uk" ? "UK" : "GLOBAL"}</small></header><small className="news-original-label">{t.original}</small><h2 lang={item.sourceLanguage}>{item.title}</h2><time dateTime={item.date}>{new Date(`${item.date}T12:00:00Z`).toLocaleDateString(locale, { year: "numeric", month: "long", day: "numeric" })}</time><div className="news-context"><strong>{t.context}</strong><p>{t.lenses[item.category]}</p></div><footer><button type="button" className={favorites.includes(item.id) ? "active" : ""} aria-pressed={favorites.includes(item.id)} onClick={() => toggle(item.id)}>☆ {favorites.includes(item.id) ? t.saved : t.save}</button><button type="button" onClick={() => void share(item)}>↗ {t.share}</button><a href={item.url} target="_blank" rel="noreferrer noopener">{t.open} ↗<small>{t.source}</small></a></footer></article>)}{!visible.length && <p className="news-empty">{t.empty}</p>}</div>
    {visible.length < filtered.length && <button className="news-more" type="button" onClick={() => setLimit((value) => value + 12)}>{t.more} ↓</button>}
  </section>;
}
