import { newsGeneratedAt, newsItems } from "../lib/generated-news";
import { absoluteUrl, languageTag, organizationId, pathFor, type Locale } from "../lib/site";
import { NewsFeedClient } from "./NewsFeedClient";
import { SchemaScript } from "./SchemaScript";
import { SiteShell } from "./SiteShell";

const copy = {
  tr: { eyebrow: "BYTEQUANT GÜNDEM", title: "Gürültü yerine kaynağı görün: bilim, teknoloji ve güvenlik gündemi", intro: "NASA, NIST ve açık lisanslı GOV.UK akışlarından başlık, tarih ve özgün bağlantı alınır. Başlık dili açıkça gösterilir; dört dildeki kısa değerlendirme kartı haberin ne olmadığını ve neyi doğrulamanız gerektiğini anlatır.", update: "Kaynak özeti güncellendi", method: "Kaynak ve yeniden kullanım yöntemi", desk: "Bölgenizdeki resmî kaynaklara gidin", deskIntro: "Bu bağlantılar tarayıcıda canlı çekilmez ve ByteQuant içinde kopyalanmaz. Yerel dildeki gelişmeleri doğrudan kurumun kendi sayfasından izleyebilirsiniz.", notes: ["Yalnızca allowlist içindeki HTTPS NASA, NIST ve GOV.UK akışları derleme sırasında okunur.", "Başlık, tarih ve özgün bağlantı dışında makale metni veya görseli yeniden yayımlanmaz.", "GOV.UK bilgisi Open Government Licence v3.0 koşulları ve kaynak atfıyla kullanılır.", "Bir başlığın görünmesi ByteQuant onayı değildir; karar vermeden önce özgün kaynağı okuyun."] },
  en: { eyebrow: "BYTEQUANT UPDATES", title: "See the source, not the noise: science, technology, and security updates", intro: "Titles, dates, and original links come from NASA, NIST, and the openly licensed GOV.UK feed. The source language is explicit, while a four-language reading lens explains what to verify before acting.", update: "Source snapshot updated", method: "Source and reuse method", desk: "Open official sources for your region", deskIntro: "These pages are not fetched live or copied into ByteQuant. Use them to follow developments directly in the institution's own language and context.", notes: ["Only allowlisted HTTPS NASA, NIST, and GOV.UK feeds are read at build time.", "No article body or image is republished beyond title, date, and original link.", "GOV.UK information is reused with attribution under the Open Government Licence v3.0.", "Inclusion is not a ByteQuant endorsement; read the original before making a decision."] },
  de: { eyebrow: "BYTEQUANT AKTUELL", title: "Quelle statt Rauschen: Wissenschaft, Technik und Sicherheit", intro: "Titel, Datum und Originallink stammen aus NASA-, NIST- und offen lizenzierten GOV.UK-Feeds. Die Originalsprache bleibt sichtbar; ein Leserahmen in vier Sprachen nennt die nötigen Prüfungen.", update: "Quellenstand aktualisiert", method: "Quellen- und Nutzungsmethode", desk: "Offizielle Quellen Ihrer Region öffnen", deskIntro: "Diese Seiten werden nicht live in ByteQuant geladen oder kopiert. Verfolgen Sie Meldungen direkt im sprachlichen und institutionellen Kontext der Quelle.", notes: ["Nur erlaubte HTTPS-Feeds von NASA, NIST und GOV.UK werden beim Build gelesen.", "Neben Titel, Datum und Originallink werden weder Artikeltext noch Bilder erneut veröffentlicht.", "GOV.UK-Informationen werden mit Quellenangabe unter der Open Government Licence v3.0 genutzt.", "Aufnahme ist keine Empfehlung durch ByteQuant; vor Entscheidungen die Originalquelle lesen."] },
  zh: { eyebrow: "BYTEQUANT 动态", title: "少一点噪声，多一点来源：科学、技术与安全动态", intro: "标题、日期与原始链接来自 NASA、NIST 和开放许可的 GOV.UK Feed。页面明确标注原始语言，并用四种语言提供核验提示。", update: "来源快照更新时间", method: "来源与复用方法", desk: "打开您所在地区的官方来源", deskIntro: "这些页面不会被 ByteQuant 实时抓取或复制。您可在机构自身的语言与语境中直接查看动态。", notes: ["仅在构建时读取白名单内的 NASA、NIST 与 GOV.UK HTTPS Feed。", "除标题、日期和原始链接外，不转载正文或图片。", "GOV.UK 信息依据 Open Government Licence v3.0 并注明来源使用。", "收录不代表 ByteQuant 背书；做出决定前请阅读原始来源。"] },
} as const;

const regionalSources = [
  { code: "TR", name: "TÜBİTAK Haberler", url: "https://tubitak.gov.tr/tr/haberler", descriptions: { tr: "Türkiye'den bilim, araştırma ve teknoloji duyuruları.", en: "Science, research, and technology announcements from Türkiye.", de: "Wissenschafts- und Technikmeldungen aus der Türkei.", zh: "来自土耳其的科学、研究与技术动态。" } },
  { code: "UK", name: "GOV.UK · AI & technology", url: "https://www.gov.uk/search/news-and-communications?keywords=artificial%20intelligence", descriptions: { tr: "Birleşik Krallık kamu kurumlarının AI ve teknoloji duyuruları.", en: "UK public-sector AI and technology announcements.", de: "KI- und Technikmeldungen des britischen öffentlichen Sektors.", zh: "英国公共部门的 AI 与技术公告。" } },
  { code: "DE", name: "BSI Meldungen", url: "https://www.bsi.bund.de/DE/Service-Navi/Presse/Alle-Meldungen-News/alle-meldungen-news_node.html", descriptions: { tr: "Almanya Federal Bilgi Güvenliği Dairesinin güncel duyuruları.", en: "Updates from Germany's Federal Office for Information Security.", de: "Aktuelle Meldungen des Bundesamts für Sicherheit in der Informationstechnik.", zh: "德国联邦信息安全办公室的最新动态。" } },
  { code: "CN", name: "中国科学院 · CAS", url: "https://www.cas.cn/cm/", descriptions: { tr: "Çin Bilimler Akademisinin araştırma ve bilim iletişimi akışı.", en: "Research and science communication from the Chinese Academy of Sciences.", de: "Forschungs- und Wissenschaftsmeldungen der Chinesischen Akademie der Wissenschaften.", zh: "中国科学院的科研与科学传播动态。" } },
] as const;

export function NewsPage({ locale }: { locale: Locale }) {
  const t = copy[locale]; const url = absoluteUrl(pathFor(locale, "news"));
  const schema = { "@context": "https://schema.org", "@type": "CollectionPage", name: t.title, description: t.intro, url, inLanguage: languageTag(locale), isPartOf: { "@id": `${absoluteUrl(pathFor(locale, "home"))}#website` }, publisher: { "@id": organizationId }, mainEntity: { "@type": "ItemList", itemListElement: newsItems.slice(0, 20).map((item, index) => ({ "@type": "ListItem", position: index + 1, url: item.url, name: item.title })) } };
  return <SiteShell locale={locale} alternateHref={pathFor(locale === "tr" ? "en" : "tr", "news")} languageHrefs={{ tr: pathFor("tr", "news"), en: pathFor("en", "news"), de: pathFor("de", "news"), zh: pathFor("zh", "news") }}><SchemaScript data={schema} /><main className="news-page"><section className="news-hero"><div className="container"><span className="eyebrow"><i />{t.eyebrow}</span><h1>{t.title}</h1><p>{t.intro}</p><small>{t.update}: <time dateTime={newsGeneratedAt}>{new Date(newsGeneratedAt).toLocaleDateString(locale, { year: "numeric", month: "long", day: "numeric" })}</time></small></div></section><section className="section"><div className="container"><NewsFeedClient locale={locale} items={newsItems} /></div></section><section className="section news-regional"><div className="container"><div className="section-heading split-heading"><div><span className="kicker">REGIONAL SOURCE DESK</span><h2>{t.desk}</h2></div><p>{t.deskIntro}</p></div><div className="news-regional-grid">{regionalSources.map((source) => <a key={source.code} href={source.url} target="_blank" rel="noreferrer noopener"><span>{source.code}</span><div><strong>{source.name}</strong><p>{source.descriptions[locale]}</p></div><b>↗</b></a>)}</div></div></section><section className="section news-method"><div className="container"><div><span className="kicker">SOURCE TRANSPARENCY</span><h2>{t.method}</h2></div><ul>{t.notes.map((note) => <li key={note}>✓ <span>{note}</span></li>)}</ul></div></section></main></SiteShell>;
}
