import Link from "next/link";
import type { ReferenceGuide, ReferenceLocale } from "../lib/references";
import { referenceCopy, referencePath } from "../lib/references";
import { absoluteUrl, languageTag, organizationId, pathFor, schemaDate, siteUrl, toolPath, websiteId } from "../lib/site";
import { SchemaScript } from "./SchemaScript";
import { SiteShell } from "./SiteShell";

export function ReferencePage({ guide, locale }: { guide: ReferenceGuide; locale: ReferenceLocale }) {
  const copy = referenceCopy(guide, locale); const url = absoluteUrl(referencePath(locale, guide.slug));
  const t = <T,>(values: Record<ReferenceLocale, T>) => values[locale];
  const schema = [
    { "@context": "https://schema.org", "@type": "TechArticle", "@id": `${url}#article`, headline: copy.title, description: copy.description, url, mainEntityOfPage: { "@type": "WebPage", "@id": url }, isPartOf: { "@id": websiteId }, datePublished: schemaDate("2026-07-15"), dateModified: schemaDate("2026-07-17"), inLanguage: languageTag(locale), author: { "@type": "Organization", "@id": `${siteUrl}/#editorial`, name: "ByteQuant Editorial", parentOrganization: { "@id": organizationId } }, publisher: { "@id": organizationId } },
    { "@context": "https://schema.org", "@type": "FAQPage", "@id": `${url}#faq`, url, inLanguage: languageTag(locale), isPartOf: { "@id": websiteId }, mainEntity: copy.faq.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) },
    { "@context": "https://schema.org", "@type": "BreadcrumbList", "@id": `${url}#breadcrumb`, itemListElement: [{ "@type": "ListItem", position: 1, name: t({ tr: "Ana sayfa", en: "Home", de: "Startseite", zh: "首页" }), item: absoluteUrl(pathFor(locale, "home")) }, { "@type": "ListItem", position: 2, name: copy.title, item: url }] },
  ];
  return <SiteShell locale={locale} alternateHref={referencePath(locale === "tr" ? "en" : "tr", guide.slug)} languageHrefs={{ tr: referencePath("tr", guide.slug), en: referencePath("en", guide.slug), de: referencePath("de", guide.slug), zh: referencePath("zh", guide.slug) }}><SchemaScript data={schema} /><section className="reference-hero"><div className="narrow-container"><nav className="breadcrumbs" aria-label={t({ tr: "Sayfa yolu", en: "Breadcrumb", de: "Brotkrumen", zh: "面包屑导航" })}><Link href={pathFor(locale, "home")}>{t({ tr: "Ana sayfa", en: "Home", de: "Startseite", zh: "首页" })}</Link><span>/</span><span>{copy.title}</span></nav><span className="kicker">{t({ tr: "GELİŞTİRİCİ REFERANSI", en: "DEVELOPER REFERENCE", de: "ENTWICKLERREFERENZ", zh: "开发者参考" })}</span><h1>{copy.title}</h1><p>{copy.intro}</p><Link className="primary-button" href={toolPath(locale, guide.toolSlug)}>{t({ tr: "Canlı araçta test et", en: "Test in the live tool", de: "Im Live-Werkzeug testen", zh: "在实时工具中测试" })} →</Link></div></section><div className="narrow-container reference-content">{copy.sections.map((section, index) => <section key={section.title}><div className="reference-heading"><span>{String(index + 1).padStart(2, "0")}</span><h2>{section.title}</h2></div><div className="reference-table-wrap"><table><thead><tr><th>{t({ tr: "Sözdizimi", en: "Syntax", de: "Syntax", zh: "语法" })}</th><th>{t({ tr: "Anlam", en: "Meaning", de: "Bedeutung", zh: "含义" })}</th><th>{t({ tr: "Örnek", en: "Example", de: "Beispiel", zh: "示例" })}</th></tr></thead><tbody>{section.entries.map((entry) => <tr key={`${entry.expression}-${entry.example ?? ""}`}><td><code>{entry.expression}</code></td><td>{entry.meaning}</td><td>{entry.example ? <code>{entry.example}</code> : "—"}</td></tr>)}</tbody></table></div></section>)}<section className="reference-faq"><span className="kicker">FAQ</span><h2>{t({ tr: "Sık sorulanlar", en: "Common questions", de: "Häufige Fragen", zh: "常见问题" })}</h2>{copy.faq.map((item) => <details key={item.question}><summary>{item.question}<span>+</span></summary><p>{item.answer}</p></details>)}</section></div></SiteShell>;
}
