"use client";

import { useMemo, useState } from "react";
import type { Locale } from "../lib/site";
import { getTool } from "../lib/tools";
import { stageTwoToolSlugs } from "../lib/stage-two-tools";
import { StructuredToolOutput } from "./StructuredToolOutput";
import { ToolNotice } from "./ToolNotice";

type Result = { output: string; metrics: Array<[string, string | number]>; warning: string };
type Demo = { input: string; secondary?: string };
type Dict = Record<Locale, string>;
const l = (locale: Locale, value: Dict) => value[locale];

export const stageTwoDemos: Record<string, Demo> = {
  "json-schema-geriye-uyumluluk-denetleyici": { input: `{"type":"object","properties":{"id":{"type":"string"},"status":{"enum":["draft","live"]}},"required":["id"]}`, secondary: `{"type":"object","properties":{"id":{"type":"integer"},"status":{"enum":["live"]},"owner":{"type":"string"}},"required":["id","owner"],"additionalProperties":false}` },
  "openapi-kirilma-degisikligi-denetleyici": { input: `{"openapi":"3.1.0","paths":{"/users":{"get":{"parameters":[{"name":"limit","in":"query","required":false}],"responses":{"200":{},"400":{}}}},"/health":{"get":{"responses":{"200":{}}}}}}`, secondary: `{"openapi":"3.1.0","paths":{"/users":{"get":{"parameters":[{"name":"limit","in":"query","required":true}],"responses":{"200":{}}}}}}` },
  "markdown-baglanti-butunluk-denetleyici": { input: `# Local workflow\n\nRead the [guide][setup] and [missing][unknown].\nAvoid [unsafe](javascript:alert(1)).\n\n[setup]: /docs/setup\n[setup]: /docs/duplicate` },
  "csv-eksik-veri-deseni-analizoru": { input: `id,city,age,consent\n1,Istanbul,34,yes\n2,,29,yes\n3,Berlin,,\n4,London,NA,no\n5,,,yes` },
  "http-vary-cache-anahtari-denetleyici": { input: `REQUEST\nAuthorization: Bearer synthetic-demo\nAccept-Language: tr\n\nRESPONSE\nCache-Control: public, max-age=3600\nSet-Cookie: session=synthetic\nContent-Language: tr\nVary: Accept-Encoding` },
  "html-tablo-erisilebilirlik-denetleyici": { input: `<table>\n  <tr><td>Quarter</td><td>Revenue</td></tr>\n  <tr><td>Q1</td><td>120</td></tr>\n</table>\n<table>\n  <caption>Delivery status</caption>\n  <thead><tr><th scope="col">Item</th><th scope="col">State</th></tr></thead>\n  <tbody><tr><th scope="row">Report</th><td>Ready</td></tr></tbody>\n</table>` },
  "borc-odeme-stratejisi-karsilastirici": { input: `Card A|4200|22.9|130\nLoan B|7800|9.5|180\nCard C|1600|18.0|70`, secondary: `650` },
  "veri-alani-sozlugu-olusturucu": { input: `customer_id|string|join customer records|confidential|CRM|account lifetime + 30 days\nemail|string|send opted-in notices|personal|CRM|consent + 30 days\norder_total|decimal|reconcile invoices|internal|billing|10 years` },
};

function jsonObject(input: string, label: string) {
  const value = JSON.parse(input) as unknown;
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(`${label} must be a JSON object.`);
  return value as Record<string, unknown>;
}
const obj = (value: unknown) => value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};
const strings = (value: unknown) => Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : [];
const table = (headers: string[], rows: Array<Array<string | number>>) => `| ${headers.join(" | ")} |\n| ${headers.map(() => "---").join(" | ")} |\n${rows.map((row) => `| ${row.map((cell) => String(cell).replaceAll("|", "\\|")).join(" | ")} |`).join("\n")}`;

function schemaDiff(input: string, secondary: string, locale: Locale): Result {
  const oldSchema = jsonObject(input, "Old schema"); const nextSchema = jsonObject(secondary, "New schema");
  const oldProps = obj(oldSchema.properties); const nextProps = obj(nextSchema.properties); const oldReq = new Set(strings(oldSchema.required)); const nextReq = new Set(strings(nextSchema.required));
  const findings: Array<[string, string, string]> = [];
  for (const name of Object.keys(oldProps)) if (!(name in nextProps)) findings.push([name, "removed", "breaking"]);
  for (const name of Object.keys(nextProps)) {
    if (!(name in oldProps)) findings.push([name, nextReq.has(name) ? "added and required" : "added optional", nextReq.has(name) ? "breaking" : "compatible"]);
    else {
      const before = obj(oldProps[name]); const after = obj(nextProps[name]);
      if (JSON.stringify(before.type) !== JSON.stringify(after.type)) findings.push([name, `type: ${JSON.stringify(before.type)} → ${JSON.stringify(after.type)}`, "review/breaking"]);
      const beforeEnum = strings(before.enum); const afterEnum = strings(after.enum);
      if (beforeEnum.length && afterEnum.length && beforeEnum.some((item) => !afterEnum.includes(item))) findings.push([name, `enum removed: ${beforeEnum.filter((item) => !afterEnum.includes(item)).join(", ")}`, "breaking"]);
      if (!oldReq.has(name) && nextReq.has(name)) findings.push([name, "optional → required", "breaking"]);
    }
  }
  if (oldSchema.additionalProperties !== false && nextSchema.additionalProperties === false) findings.push(["$object", "additionalProperties tightened to false", "review/breaking"]);
  return { output: `${findings.length ? table(["path", "change", "impact"], findings) : l(locale, { tr: "İncelenen kurallarda belirgin kırılma adayı bulunmadı.", en: "No clear breaking candidate was found in the reviewed rules.", de: "In den geprüften Regeln wurde kein eindeutiger Bruchkandidat gefunden.", zh: "在已检查规则中未发现明显的破坏性变更候选项。" })}\n\n${l(locale, { tr: "Not: $ref, oneOf/anyOf, format ve koşullu şemalar bu hızlı ön kontrolde tam çözülmez.", en: "Note: $ref, oneOf/anyOf, formats, and conditional schemas are not fully resolved by this pre-check.", de: "Hinweis: $ref, oneOf/anyOf, Formate und bedingte Schemas werden nicht vollständig aufgelöst.", zh: "注意：此预检不会完整解析 $ref、oneOf/anyOf、format 和条件 Schema。" })}`, metrics: [[l(locale, { tr: "alan", en: "fields", de: "Felder", zh: "字段" }), new Set([...Object.keys(oldProps), ...Object.keys(nextProps)]).size], [l(locale, { tr: "bulgu", en: "findings", de: "Befunde", zh: "发现" }), findings.length]], warning: l(locale, { tr: "Uyumluluk kararı için gerçek tüketici örnekleri ve sözleşme testleri gerekir.", en: "A compatibility decision requires real consumer fixtures and contract tests.", de: "Eine Kompatibilitätsentscheidung erfordert reale Fixtures und Vertragstests.", zh: "兼容性结论需要真实消费者样例和契约测试。" }) };
}

function openApiDiff(input: string, secondary: string, locale: Locale): Result {
  const before = jsonObject(input, "Old OpenAPI"); const after = jsonObject(secondary, "New OpenAPI"); const oldPaths = obj(before.paths); const nextPaths = obj(after.paths); const methods = ["get", "post", "put", "patch", "delete", "options", "head"];
  const findings: Array<[string, string, string]> = [];
  for (const path of Object.keys(oldPaths)) {
    if (!(path in nextPaths)) { findings.push([path, "path removed", "breaking"]); continue; }
    const oldPath = obj(oldPaths[path]); const newPath = obj(nextPaths[path]);
    for (const method of methods) if (method in oldPath) {
      if (!(method in newPath)) { findings.push([`${method.toUpperCase()} ${path}`, "operation removed", "breaking"]); continue; }
      const oldOp = obj(oldPath[method]); const newOp = obj(newPath[method]);
      const key = (p: unknown) => { const v = obj(p); return `${String(v.in ?? "")}:${String(v.name ?? "")}`; };
      const oldParams = new Map((Array.isArray(oldOp.parameters) ? oldOp.parameters : []).map((p) => [key(p), obj(p)])); const newParams = new Map((Array.isArray(newOp.parameters) ? newOp.parameters : []).map((p) => [key(p), obj(p)]));
      for (const [name, parameter] of oldParams) if (!newParams.has(name)) findings.push([`${method.toUpperCase()} ${path}`, `parameter removed: ${name}`, "review"]); else if (parameter.required !== true && newParams.get(name)?.required === true) findings.push([`${method.toUpperCase()} ${path}`, `parameter now required: ${name}`, "breaking"]);
      for (const code of Object.keys(obj(oldOp.responses))) if (!(code in obj(newOp.responses))) findings.push([`${method.toUpperCase()} ${path}`, `response removed: ${code}`, "breaking"]);
    }
  }
  return { output: `${findings.length ? table(["operation", "change", "impact"], findings) : l(locale, { tr: "İncelenen yüzeyde belirgin kırılma adayı bulunmadı.", en: "No clear breaking candidate was found on the reviewed surface.", de: "Auf der geprüften Oberfläche wurde kein eindeutiger Bruchkandidat gefunden.", zh: "在已检查范围内未发现明显的破坏性变更候选项。" })}\n\n${l(locale, { tr: "Yalnızca JSON ve doğrudan tanımlar incelenir; dış $ref, medya şeması ve davranış değişiklikleri ayrıca test edilmelidir.", en: "Only JSON and direct definitions are reviewed; external $ref, media schemas, and behavioral changes need separate tests.", de: "Nur JSON und direkte Definitionen werden geprüft; externe $ref, Medienschemas und Verhaltensänderungen brauchen separate Tests.", zh: "仅检查 JSON 和直接定义；外部 $ref、媒体 Schema 和行为变更需另行测试。" })}`, metrics: [[l(locale, { tr: "eski yol", en: "old paths", de: "alte Pfade", zh: "旧路径" }), Object.keys(oldPaths).length], [l(locale, { tr: "bulgu", en: "findings", de: "Befunde", zh: "发现" }), findings.length]], warning: l(locale, { tr: "Bu rapor tam OpenAPI uyumluluk kanıtı değildir.", en: "This report is not proof of complete OpenAPI compatibility.", de: "Dieser Bericht beweist keine vollständige OpenAPI-Kompatibilität.", zh: "本报告不能证明完整的 OpenAPI 兼容性。" }) };
}

function markdownLinks(input: string, locale: Locale): Result {
  const definitions = new Map<string, string>(); const duplicates = new Set<string>(); const definitionPattern = /^\s*\[([^\]]+)\]:\s*(\S+)/gmu; let match: RegExpExecArray | null;
  while ((match = definitionPattern.exec(input))) { const key = match[1].trim().toLocaleLowerCase(); if (definitions.has(key)) duplicates.add(key); definitions.set(key, match[2]); }
  const references = [...input.matchAll(/(?<!!)\[[^\]]+\]\[([^\]]+)\]/gu)].map((item) => item[1].trim().toLocaleLowerCase());
  const inlineTargets = [...input.matchAll(/(?<!!)\[[^\]]+\]\(([^)\s]+)(?:\s+["'][^"']*["'])?\)/gu)].map((item) => item[1]);
  const allTargets = [...inlineTargets, ...definitions.values()]; const unsafe = allTargets.filter((target) => /^(?:javascript|data|vbscript):/iu.test(target)); const undefinedRefs = [...new Set(references.filter((key) => !definitions.has(key)))];
  const rows: Array<[string, string, string]> = [...undefinedRefs.map((key) => ["reference", key, "undefined"] as [string, string, string]), ...[...duplicates].map((key) => ["definition", key, "duplicate"] as [string, string, string]), ...unsafe.map((target) => ["target", target, "unsafe scheme"] as [string, string, string])];
  return { output: `${rows.length ? table(["kind", "value", "issue"], rows) : l(locale, { tr: "Yerel sözdizimi denetiminde sorun bulunmadı.", en: "No issue was found by the local syntax review.", de: "Die lokale Syntaxprüfung fand kein Problem.", zh: "本地语法检查未发现问题。" })}\n\n${l(locale, { tr: "Ağ isteği yapılmadı; HTTP durumu, yönlendirme ve hedef içeriği doğrulanmadı.", en: "No network request was made; HTTP status, redirects, and destination content were not verified.", de: "Es wurde keine Netzwerkanfrage ausgeführt; HTTP-Status, Weiterleitungen und Zielinhalt wurden nicht geprüft.", zh: "未发起网络请求；未验证 HTTP 状态、重定向和目标内容。" })}`, metrics: [[l(locale, { tr: "bağlantı", en: "links", de: "Links", zh: "链接" }), references.length + inlineTargets.length], [l(locale, { tr: "sorun", en: "issues", de: "Probleme", zh: "问题" }), rows.length]], warning: l(locale, { tr: "Uzak bağlantıların erişilebilirliğini yayın ortamında doğrulayın.", en: "Verify remote-link availability in the publishing environment.", de: "Prüfen Sie externe Links in der Veröffentlichungsumgebung.", zh: "请在发布环境中验证远程链接可用性。" }) };
}

function parseCsv(source: string) { const rows: string[][] = []; let row: string[] = []; let cell = ""; let quoted = false; for (let i = 0; i < source.length; i++) { const c = source[i]; if (quoted) { if (c === '"' && source[i + 1] === '"') { cell += '"'; i++; } else if (c === '"') quoted = false; else cell += c; } else if (c === '"') quoted = true; else if (c === ',') { row.push(cell); cell = ""; } else if (c === '\n') { row.push(cell.replace(/\r$/u, "")); rows.push(row); row = []; cell = ""; } else cell += c; } if (quoted) throw new Error("Unclosed quoted CSV field."); if (cell || row.length) { row.push(cell); rows.push(row); } return rows; }
function csvMissing(input: string, locale: Locale): Result { const rows = parseCsv(input); if (rows.length < 2) throw new Error("CSV requires a header and at least one data row."); const headers = rows[0].map((v) => v.trim()); if (headers.some((v) => !v) || new Set(headers).size !== headers.length) throw new Error("CSV headers must be non-empty and unique."); const data = rows.slice(1); const missing = (v: string | undefined) => !v || /^(?:na|n\/a|null|undefined|-)$/iu.test(v.trim()); const counts = headers.map((_, index) => data.filter((row) => missing(row[index])).length); const patterns = new Map<string, number>(); data.forEach((row) => { const absent = headers.filter((_, index) => missing(row[index])); if (absent.length) { const key = absent.join(" + "); patterns.set(key, (patterns.get(key) ?? 0) + 1); } }); return { output: `${table(["column", "missing", "rate"], headers.map((header, index) => [header, counts[index], `${((counts[index] / data.length) * 100).toFixed(1)}%`]))}\n\n${l(locale, { tr: "Birlikte eksik örüntüler", en: "Co-missing patterns", de: "Gemeinsame Fehlmuster", zh: "共同缺失模式" })}\n${patterns.size ? table(["fields", "rows"], [...patterns.entries()].sort((a, b) => b[1] - a[1])) : l(locale, { tr: "Eksik değer belirteci bulunmadı.", en: "No missing-value token was found.", de: "Kein Fehlwertkennzeichen gefunden.", zh: "未发现缺失值标记。" })}`, metrics: [[l(locale, { tr: "satır", en: "rows", de: "Zeilen", zh: "行" }), data.length], [l(locale, { tr: "eksik hücre", en: "missing cells", de: "Fehlzellen", zh: "缺失单元格" }), counts.reduce((a, b) => a + b, 0)]], warning: l(locale, { tr: "NA ve benzeri değerler bağlama göre gerçek veri olabilir; kaynak sözlüğünü kontrol edin.", en: "Tokens such as NA may be valid data in context; check the source dictionary.", de: "Werte wie NA können kontextabhängig gültig sein; prüfen Sie das Quellwörterbuch.", zh: "NA 等标记在特定语境中可能是有效数据；请检查源字典。" }) }; }

function cacheAudit(input: string, locale: Locale): Result { const parts = input.split(/\n\s*RESPONSE\s*\n/iu); if (parts.length !== 2) throw new Error("Use REQUEST and RESPONSE sections."); const headers = (text: string) => new Map(text.split(/\r?\n/u).filter((line) => line.includes(":" )).map((line) => { const at = line.indexOf(":"); return [line.slice(0, at).trim().toLocaleLowerCase(), line.slice(at + 1).trim()]; })); const request = headers(parts[0]); const response = headers(parts[1]); const cache = response.get("cache-control")?.toLocaleLowerCase() ?? ""; const vary = new Set((response.get("vary") ?? "").split(",").map((v) => v.trim().toLocaleLowerCase()).filter(Boolean)); const findings: Array<[string, string]> = []; if ((request.has("authorization") || response.has("set-cookie")) && /(?:^|,)\s*public/u.test(cache)) findings.push(["high", "Personalized signal combined with public caching"]); if (request.has("authorization") && !/(?:^|,)\s*(?:private|no-store)/u.test(cache)) findings.push(["high", "Authorization request without private or no-store"]); if (response.has("content-language") && request.has("accept-language") && !vary.has("accept-language")) findings.push(["medium", "Language variant missing Vary: Accept-Language"]); if (!cache) findings.push(["review", "Cache-Control is absent"]); return { output: `${findings.length ? table(["priority", "finding"], findings) : l(locale, { tr: "Yapılandırılan kurallarda yüksek riskli birleşim bulunmadı.", en: "No high-risk combination was found by the configured rules.", de: "Die konfigurierten Regeln fanden keine Hochrisikokombination.", zh: "配置规则未发现高风险组合。" })}\n\nCache-Control: ${cache || "—"}\nVary: ${[...vary].join(", ") || "—"}`, metrics: [[l(locale, { tr: "istek başlığı", en: "request headers", de: "Request-Header", zh: "请求头" }), request.size], [l(locale, { tr: "bulgu", en: "findings", de: "Befunde", zh: "发现" }), findings.length]], warning: l(locale, { tr: "Canlı CDN davranışını farklı kullanıcı ve varyantlarla sınayın.", en: "Test live CDN behavior with different users and representations.", de: "Testen Sie das reale CDN mit verschiedenen Nutzern und Varianten.", zh: "请使用不同用户和内容变体测试线上 CDN 行为。" }) }; }

function tableAccessibility(input: string, locale: Locale): Result { const tables = [...input.matchAll(/<table\b[^>]*>([\s\S]*?)<\/table>/giu)].map((m) => m[1]); if (!tables.length) throw new Error("No complete <table> element found."); const rows: Array<[number, string, string]> = []; tables.forEach((html, index) => { if (!/<caption\b/iu.test(html)) rows.push([index + 1, "caption", "missing"]); const ths = [...html.matchAll(/<th\b([^>]*)>/giu)]; if (!ths.length) rows.push([index + 1, "header cells", "no <th> found"]); if (ths.some((m) => !/\bscope\s*=|\bid\s*=/iu.test(m[1]))) rows.push([index + 1, "header association", "th without scope or id"]); if (/\brole\s*=\s*["']presentation["']/iu.test(html) && /<th\b/iu.test(html)) rows.push([index + 1, "role", "presentation table contains headers"]); }); return { output: `${rows.length ? table(["table", "area", "finding"], rows) : l(locale, { tr: "Statik işaretleme kontrolünde belirgin sorun bulunmadı.", en: "No clear issue was found by the static markup review.", de: "Die statische Markup-Prüfung fand kein eindeutiges Problem.", zh: "静态标记检查未发现明显问题。" })}\n\n${l(locale, { tr: "Karmaşık çok seviyeli tablolarda headers/id ilişkisini elle doğrulayın.", en: "Manually verify headers/id relationships in complex multi-level tables.", de: "Prüfen Sie headers/id-Beziehungen in komplexen Tabellen manuell.", zh: "请手动核验复杂多级表格中的 headers/id 关系。" })}`, metrics: [[l(locale, { tr: "tablo", en: "tables", de: "Tabellen", zh: "表格" }), tables.length], [l(locale, { tr: "bulgu", en: "findings", de: "Befunde", zh: "发现" }), rows.length]], warning: l(locale, { tr: "Otomatik kontrol WCAG uygunluğu kanıtlamaz; yardımcı teknoloji testi gerekir.", en: "Automated review does not prove WCAG conformance; assistive-technology testing is required.", de: "Automatische Prüfung beweist keine WCAG-Konformität; Hilfstechnologietests sind nötig.", zh: "自动检查不能证明符合 WCAG；仍需辅助技术测试。" }) }; }

type Debt = { name: string; balance: number; apr: number; minimum: number };
function simulate(source: Debt[], budget: number, mode: "snowball" | "avalanche") { const debts = source.map((d) => ({ ...d })); let interest = 0; let month = 0; while (debts.some((d) => d.balance > 0.005) && month < 600) { month++; for (const d of debts) if (d.balance > 0) { const charge = d.balance * d.apr / 1200; d.balance += charge; interest += charge; } let remaining = budget; for (const d of debts) { const pay = Math.min(d.balance, d.minimum, remaining); d.balance -= pay; remaining -= pay; } while (remaining > 0.005) { const active = debts.filter((d) => d.balance > 0.005).sort((a, b) => mode === "snowball" ? a.balance - b.balance || b.apr - a.apr : b.apr - a.apr || a.balance - b.balance); if (!active.length) break; const pay = Math.min(active[0].balance, remaining); active[0].balance -= pay; remaining -= pay; } } return { months: month, interest, complete: debts.every((d) => d.balance <= 0.005) }; }
function debtCompare(input: string, secondary: string, locale: Locale): Result { const debts = input.split(/\r?\n/u).filter(Boolean).map((line, i) => { const [name, balanceText, aprText, minText] = line.split("|").map((v) => v.trim()); const balance = Number(balanceText); const apr = Number(aprText); const minimum = Number(minText); if (!name || !Number.isFinite(balance) || balance <= 0 || !Number.isFinite(apr) || apr < 0 || apr > 100 || !Number.isFinite(minimum) || minimum <= 0) throw new Error(`Line ${i + 1}: use name|balance|APR|minimum.`); return { name, balance, apr, minimum }; }); const budget = Number(secondary); const minTotal = debts.reduce((sum, d) => sum + d.minimum, 0); if (!debts.length || !Number.isFinite(budget) || budget < minTotal) throw new Error(`Monthly budget must be at least ${minTotal.toFixed(2)}.`); const snowball = simulate(debts, budget, "snowball"); const avalanche = simulate(debts, budget, "avalanche"); return { output: `${table(["strategy", "months", "estimated interest", "completed"], [["snowball", snowball.months, snowball.interest.toFixed(2), snowball.complete ? "yes" : "no"], ["avalanche", avalanche.months, avalanche.interest.toFixed(2), avalanche.complete ? "yes" : "no"]])}\n\n${l(locale, { tr: "Aylık bütçe", en: "Monthly budget", de: "Monatsbudget", zh: "月度预算" })}: ${budget.toFixed(2)}\n${l(locale, { tr: "Minimum toplamı", en: "Minimum total", de: "Summe Mindestzahlungen", zh: "最低还款合计" })}: ${minTotal.toFixed(2)}`, metrics: [[l(locale, { tr: "borç", en: "debts", de: "Schulden", zh: "债务" }), debts.length], [l(locale, { tr: "ek ödeme", en: "extra payment", de: "Zusatzbetrag", zh: "额外还款" }), (budget - minTotal).toFixed(2)]], warning: l(locale, { tr: "Sabit oranlı matematiksel senaryodur; finansal tavsiye değildir. Sözleşme ücretlerini ve gerçek ödeme sırasını kontrol edin.", en: "This is a fixed-rate mathematical scenario, not financial advice. Check contract fees and actual payment order.", de: "Dies ist ein Festzins-Szenario, keine Finanzberatung. Vertragsgebühren und Zahlungsreihenfolge prüfen.", zh: "这是固定利率数学情景，不构成财务建议；请核对合同费用和实际还款顺序。" }) }; }

function dictionary(input: string, locale: Locale): Result { const seen = new Set<string>(); const findings: string[] = []; const rows = input.split(/\r?\n/u).filter(Boolean).map((line, i) => { const cells = line.split("|").map((v) => v.trim()); if (cells.length !== 6 || !cells[0] || !cells[1]) throw new Error(`Line ${i + 1}: use field|type|purpose|sensitivity|source|retention.`); const key = cells[0].toLocaleLowerCase(); if (seen.has(key)) findings.push(`duplicate field: ${cells[0]}`); seen.add(key); if (!cells[2] || cells[2].length < 8) findings.push(`purpose needs detail: ${cells[0]}`); if (/^(?:forever|indefinite|unknown|-)$/iu.test(cells[5])) findings.push(`retention needs a decision: ${cells[0]}`); return cells; }); return { output: `${table(["field", "type", "purpose", "sensitivity", "source", "retention"], rows)}\n\n${l(locale, { tr: "Kalite bulguları", en: "Quality findings", de: "Qualitätsbefunde", zh: "质量发现" })}:\n${findings.length ? findings.map((v) => `- ${v}`).join("\n") : "- none"}`, metrics: [[l(locale, { tr: "alan", en: "fields", de: "Felder", zh: "字段" }), rows.length], [l(locale, { tr: "bulgu", en: "findings", de: "Befunde", zh: "发现" }), findings.length]], warning: l(locale, { tr: "Sözlüğü veri sahibi, gizlilik ve güvenlik sorumlularıyla doğrulayın.", en: "Validate the dictionary with data owners, privacy, and security stakeholders.", de: "Validieren Sie das Wörterbuch mit Datenverantwortlichen, Datenschutz und Sicherheit.", zh: "请由数据负责人、隐私和安全相关方验证该字典。" }) }; }

export function runStageTwoTool(slug: string, input: string, secondary = "", locale: Locale = "en"): Result {
  if (!stageTwoToolSlugs.has(slug)) throw new Error(`Unsupported Stage 2 tool: ${slug}`);
  if (!input.trim()) throw new Error(l(locale, { tr: "Önce girdi ekleyin veya örnek veriyi yükleyin.", en: "Add input or load the example first.", de: "Fügen Sie zuerst Daten ein oder laden Sie das Beispiel.", zh: "请先添加输入或加载示例。" }));
  if (slug === "json-schema-geriye-uyumluluk-denetleyici") return schemaDiff(input, secondary, locale);
  if (slug === "openapi-kirilma-degisikligi-denetleyici") return openApiDiff(input, secondary, locale);
  if (slug === "markdown-baglanti-butunluk-denetleyici") return markdownLinks(input, locale);
  if (slug === "csv-eksik-veri-deseni-analizoru") return csvMissing(input, locale);
  if (slug === "http-vary-cache-anahtari-denetleyici") return cacheAudit(input, locale);
  if (slug === "html-tablo-erisilebilirlik-denetleyici") return tableAccessibility(input, locale);
  if (slug === "borc-odeme-stratejisi-karsilastirici") return debtCompare(input, secondary, locale);
  return dictionary(input, locale);
}

const dual = new Set(["json-schema-geriye-uyumluluk-denetleyici", "openapi-kirilma-degisikligi-denetleyici", "borc-odeme-stratejisi-karsilastirici"]);
export function StageTwoWorkbench({ slug, locale }: { slug: string; locale: Locale }) {
  const tool = getTool(slug); const demo = stageTwoDemos[slug]; const [input, setInput] = useState(""); const [secondary, setSecondary] = useState(""); const [result, setResult] = useState<Result | null>(null); const [state, setState] = useState<"idle" | "busy" | "success" | "error">("idle"); const [error, setError] = useState("");
  const t = useMemo(() => ({ input: l(locale, { tr: "İşlenecek veri", en: "Data to process", de: "Zu verarbeitende Daten", zh: "待处理数据" }), second: slug === "borc-odeme-stratejisi-karsilastirici" ? l(locale, { tr: "Toplam aylık bütçe", en: "Total monthly budget", de: "Gesamtes Monatsbudget", zh: "月度总预算" }) : l(locale, { tr: "Yeni sürüm / karşılaştırma", en: "New version / comparison", de: "Neue Version / Vergleich", zh: "新版本 / 对比" }), demo: l(locale, { tr: "Örnek veri yükle", en: "Load example", de: "Beispiel laden", zh: "加载示例" }), clear: l(locale, { tr: "Temizle", en: "Clear", de: "Leeren", zh: "清除" }), run: l(locale, { tr: "Cihazımda çalıştır", en: "Run on my device", de: "Auf meinem Gerät ausführen", zh: "在我的设备上运行" }), running: l(locale, { tr: "İşleniyor…", en: "Processing…", de: "Verarbeitung…", zh: "处理中…" }), output: l(locale, { tr: "Sonuç", en: "Result", de: "Ergebnis", zh: "结果" }), empty: l(locale, { tr: "Sonuç, yöntem sınırı ve doğrulama adımı burada görünecek.", en: "The result, method boundary, and verification step will appear here.", de: "Ergebnis, Methodengrenze und Prüfschritt erscheinen hier.", zh: "结果、方法边界和验证步骤将显示在此处。" }), copy: l(locale, { tr: "Kopyala", en: "Copy", de: "Kopieren", zh: "复制" }), download: l(locale, { tr: "İndir", en: "Download", de: "Download", zh: "下载" }), privacy: l(locale, { tr: "Bu işlem tamamen etkin tarayıcı sekmenizde gerçekleşti; girdi ByteQuant sunucusuna gönderilmedi.", en: "This operation ran entirely in the active browser tab; input was not sent to a ByteQuant server.", de: "Dieser Vorgang lief vollständig im aktiven Browser-Tab; Eingaben wurden nicht an ByteQuant gesendet.", zh: "此操作完全在当前浏览器标签页中运行；输入未发送到 ByteQuant 服务器。" }) }), [locale, slug]);
  const reset = () => { setResult(null); setState("idle"); setError(""); };
  async function run() { setState("busy"); setError(""); await new Promise<void>((resolve) => window.setTimeout(resolve, 0)); try { const value = runStageTwoTool(slug, input.slice(0, 200000), secondary.slice(0, 200000), locale); setResult(value); setState("success"); } catch (cause) { setResult(null); setError(cause instanceof Error ? cause.message : String(cause)); setState("error"); } }
  const output = result?.output ?? "";
  async function copy() { if (output) await navigator.clipboard.writeText(output); }
  function download() { if (!output) return; const url = URL.createObjectURL(new Blob([output], { type: "text/plain;charset=utf-8" })); const a = document.createElement("a"); a.href = url; a.download = `bytequant-${slug}.txt`; a.click(); window.setTimeout(() => URL.revokeObjectURL(url), 0); }
  return <section className="workbench stage-two-workbench" aria-busy={state === "busy"} aria-label={tool?.title[locale]}>
    <div className="workbench-bar"><span className="local-status"><i />{l(locale, { tr: "Yalnızca bu sekmede işlenir", en: "Processed only in this tab", de: "Nur in diesem Tab verarbeitet", zh: "仅在此标签页处理" })}<small>{tool?.title[locale]}</small></span><div className="workbench-bar-actions"><button type="button" className="demo-button" onClick={() => { setInput(demo.input); setSecondary(demo.secondary ?? ""); reset(); }}>{t.demo}</button><button type="button" className="ghost-button" onClick={() => { setInput(""); setSecondary(""); reset(); }}>{t.clear}</button></div></div>
    <div className="workbench-grid"><div className="workbench-inputs" data-agent-contract={dual.has(slug) ? "dual-text-v1" : "single-text-v1"}><div className="frontier-purpose"><strong>{l(locale, { tr: "Bu araç ne yapar?", en: "What does this tool do?", de: "Was macht dieses Werkzeug?", zh: "此工具做什么？" })}</strong><p>{tool?.short[locale]}</p></div><label className="field-label"><span>{t.input}</span><textarea data-agent-input data-agent-key="input" value={input} rows={12} maxLength={200000} aria-invalid={state === "error"} onChange={(e) => { setInput(e.target.value); reset(); }} spellCheck={false}/><small className="field-counter">{input.length.toLocaleString()} / 200,000</small></label>{dual.has(slug) && <label className="field-label"><span>{t.second}</span><textarea data-agent-input data-agent-key="secondary" value={secondary} rows={8} maxLength={200000} aria-invalid={state === "error"} onChange={(e) => { setSecondary(e.target.value); reset(); }} spellCheck={false}/></label>}<button type="button" className="primary-button run-button" data-agent-run disabled={state === "busy"} onClick={() => void run()}>{state === "busy" ? t.running : t.run}<span aria-hidden="true"> →</span></button></div>
      <div className="result-panel" aria-live="polite"><div className="result-header"><span>{t.output}<small className="frontier-state" data-state={state}>{state}</small></span><div className="output-actions"><button type="button" disabled={!output} onClick={() => void copy()}>{t.copy}</button><button type="button" disabled={!output} onClick={download}>{t.download}</button></div></div>{result && <div className="metric-strip">{result.metrics.map(([label, value]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div>}<StructuredToolOutput output={output} empty={t.empty}/>{result?.warning && <ToolNotice locale={locale} notice={{ kind: "warning", text: result.warning }}/>} {state === "error" && <ToolNotice locale={locale} notice={{ kind: "error", text: error }}/>} {state === "success" && <div className="workbench-trust-card"><span aria-hidden="true">✓</span><p>{t.privacy}</p></div>}</div></div>
  </section>;
}
