"use client";

import { useMemo, useState } from "react";
import type { Locale } from "../lib/site";
import { getTool } from "../lib/tools";
import { StructuredToolOutput } from "./StructuredToolOutput";
import { ToolNotice } from "./ToolNotice";

type Values = Record<string, string | boolean>;
type Metric = [string, string | number];
type Result = { output: string; metrics: Metric[]; warning?: string };
type L = Record<Locale, string>;
type Field = { key: string; label: L; type?: "text" | "number" | "date" | "textarea" | "checkbox" | "select"; help?: L; min?: number; max?: number; step?: number; options?: Array<[string, L]> };
type Definition = { fields: Field[]; demo: Values };
const l = (tr: string, en: string, de: string, zh: string): L => ({ tr, en, de, zh });
const text = (locale: Locale, value: L) => value[locale];

const ui = {
  tr: { local: "Yalnızca bu sekmede işlenir", demo: "Örnek veri yükle", clear: "Temizle", run: "Cihazımda incele", running: "İnceleniyor…", result: "Sonuç", idle: "Girdileri doldurup denetimi çalıştırın.", copy: "Kopyala", download: "İndir", done: "Tamamlandı", error: "Girdi düzeltmesi gerekiyor", privacy: "Bu işlem tamamen cihazınızda gerçekleşti; girdi ByteQuant sunucusuna gönderilmedi." },
  en: { local: "Processed only in this tab", demo: "Load example", clear: "Clear", run: "Review on my device", running: "Reviewing…", result: "Result", idle: "Complete the fields and run the review.", copy: "Copy", download: "Download", done: "Complete", error: "Input needs correction", privacy: "This operation happened entirely on your device; the input was not sent to a ByteQuant server." },
  de: { local: "Nur in diesem Tab verarbeitet", demo: "Beispiel laden", clear: "Leeren", run: "Lokal prüfen", running: "Prüfung läuft…", result: "Ergebnis", idle: "Felder ausfüllen und Prüfung starten.", copy: "Kopieren", download: "Herunterladen", done: "Abgeschlossen", error: "Eingabe korrigieren", privacy: "Dieser Vorgang fand vollständig auf Ihrem Gerät statt; die Eingabe wurde nicht an ByteQuant gesendet." },
  zh: { local: "仅在当前标签页处理", demo: "加载示例", clear: "清空", run: "在设备端检查", running: "检查中…", result: "结果", idle: "填写字段并运行检查。", copy: "复制", download: "下载", done: "已完成", error: "需要修正输入", privacy: "此操作完全在您的设备上完成；输入未发送到 ByteQuant 服务器。" },
} as const;

const definitions: Record<string, Definition> = {
  "retry-after-geri-cekilme-planlayici": { fields: [
    { key: "method", label: l("HTTP yöntemi", "HTTP method", "HTTP-Methode", "HTTP 方法"), type: "select", options: [["GET", l("GET · güvenli", "GET · safe", "GET · sicher", "GET · 安全")], ["PUT", l("PUT · idempotent", "PUT · idempotent", "PUT · idempotent", "PUT · 幂等")], ["POST", l("POST · koşullu", "POST · conditional", "POST · bedingt", "POST · 需条件")]] },
    { key: "status", label: l("Yanıt durumu", "Response status", "Antwortstatus", "响应状态"), type: "select", options: [["429", l("429 · Çok fazla istek", "429 · Too many requests", "429 · Zu viele Anfragen", "429 · 请求过多")], ["503", l("503 · Geçici olarak kullanılamıyor", "503 · Temporarily unavailable", "503 · Vorübergehend nicht verfügbar", "503 · 暂时不可用")]] },
    { key: "retryAfter", label: l("Retry-After", "Retry-After", "Retry-After", "Retry-After"), help: l("Saniye veya HTTP tarihi", "Seconds or HTTP date", "Sekunden oder HTTP-Datum", "秒数或 HTTP 日期") },
    { key: "attempts", label: l("Azami deneme", "Maximum attempts", "Maximale Versuche", "最大尝试次数"), type: "number", min: 1, max: 10 },
    { key: "baseMs", label: l("Taban gecikme (ms)", "Base delay (ms)", "Basisverzögerung (ms)", "基础延迟（毫秒）"), type: "number", min: 50, max: 600000 },
    { key: "capMs", label: l("Üst sınır (ms)", "Delay cap (ms)", "Obergrenze (ms)", "延迟上限（毫秒）"), type: "number", min: 50, max: 3600000 },
    { key: "jitter", label: l("Jitter (%)", "Jitter (%)", "Jitter (%)", "抖动（%）"), type: "number", min: 0, max: 50 },
  ], demo: { method: "GET", status: "429", retryAfter: "8", attempts: "5", baseMs: "500", capMs: "30000", jitter: "20" } },
  "webhook-teslim-gunlugu-analizoru": { fields: [{ key: "records", label: l("Teslim kayıtları", "Delivery records", "Zustellprotokoll", "投递记录"), type: "textarea", help: l("zaman | olay kimliği | durum | gecikme ms | deneme", "time | event id | status | latency ms | attempt", "Zeit | Ereignis-ID | Status | Latenz ms | Versuch", "时间 | 事件 ID | 状态 | 延迟毫秒 | 尝试") }], demo: { records: "2026-08-22T09:00:00Z|evt_101|500|420|1\n2026-08-22T09:00:03Z|evt_101|200|180|2\n2026-08-22T09:00:02Z|evt_102|200|950|1\n2026-08-22T09:00:07Z|evt_102|200|210|2" } },
  "aria-erisebilir-ad-envanteri": { fields: [{ key: "html", label: l("İncelenecek HTML", "HTML to inspect", "Zu prüfendes HTML", "待检查 HTML"), type: "textarea" }], demo: { html: "<main>\n  <button aria-label=\"Menüyü aç\"><svg aria-hidden=\"true\"></svg></button>\n  <a href=\"/privacy\">Gizlilik</a>\n  <label for=\"email\">E-posta</label><input id=\"email\" type=\"email\">\n  <button><svg></svg></button>\n</main>" } },
  "html-dil-baslik-yapisi-denetleyici": { fields: [{ key: "html", label: l("Sayfa HTML'i", "Page HTML", "Seiten-HTML", "页面 HTML"), type: "textarea" }], demo: { html: "<!doctype html><html lang=\"tr\"><head><title>Yerel ve Gizlilik Odaklı JSON Araçları | ByteQuant</title><meta name=\"description\" content=\"JSON verisini tarayıcıda doğrulayın, biçimlendirin ve dışa aktarın.\"></head><body><h1>JSON araçları</h1><h2>Nasıl kullanılır?</h2><h3>Örnek veri</h3></body></html>" } },
  "sitemap-url-kume-analizoru": { fields: [{ key: "urls", label: l("Her satırda bir mutlak URL", "One absolute URL per line", "Eine absolute URL pro Zeile", "每行一个绝对 URL"), type: "textarea" }], demo: { urls: "https://bytequant.org/araclar/json-bicimlendirici/\nhttps://bytequant.org/en/tools/json-bicimlendirici/\nhttps://bytequant.org/de/tools/json-bicimlendirici/\nhttps://bytequant.org/zh/tools/json-bicimlendirici/\nhttp://bytequant.org/araclar/json-bicimlendirici/?utm_source=test\nhttps://www.bytequant.org/araclar/json-bicimlendirici/" } },
  "robots-meta-politikasi-olusturucu": { fields: [
    { key: "index", label: l("Sayfa indekslenebilsin", "Allow indexing", "Indexierung erlauben", "允许索引"), type: "checkbox" },
    { key: "follow", label: l("Bağlantılar izlenebilsin", "Allow link following", "Links folgen lassen", "允许跟踪链接"), type: "checkbox" },
    { key: "archive", label: l("Arşivlenmiş kopyaya izin ver", "Allow cached copy", "Archivkopie erlauben", "允许缓存副本"), type: "checkbox" },
    { key: "largeImage", label: l("Büyük görsel önizlemesine izin ver", "Allow large image preview", "Große Bildvorschau erlauben", "允许大图预览"), type: "checkbox" },
    { key: "maxSnippet", label: l("Azami snippet karakteri", "Maximum snippet characters", "Maximale Snippet-Zeichen", "摘要最大字符数"), type: "number", min: -1, max: 1000 },
  ], demo: { index: true, follow: true, archive: true, largeImage: true, maxSnippet: "180" } },
  "eposta-konu-onizleme-denetleyici": { fields: [
    { key: "subject", label: l("Konu satırı", "Subject line", "Betreffzeile", "主题行") },
    { key: "preheader", label: l("Önizleme metni", "Preheader text", "Preheader-Text", "预标题文本"), type: "textarea" },
  ], demo: { subject: "Raporunuz hazır: bu hafta neler değişti?", preheader: "Üç önemli gelişmeyi ve sıradaki güvenli adımı iki dakikada gözden geçirin." } },
  "web-performans-butce-planlayici": { fields: [
    { key: "budget", label: l("Toplam mobil bütçe (KB)", "Total mobile budget (KB)", "Gesamtes Mobilbudget (KB)", "移动总预算（KB）"), type: "number", min: 50, max: 10000 },
    { key: "html", label: l("HTML (KB)", "HTML (KB)", "HTML (KB)", "HTML（KB）"), type: "number", min: 0 },
    { key: "css", label: l("CSS (KB)", "CSS (KB)", "CSS (KB)", "CSS（KB）"), type: "number", min: 0 },
    { key: "js", label: l("JavaScript (KB)", "JavaScript (KB)", "JavaScript (KB)", "JavaScript（KB）"), type: "number", min: 0 },
    { key: "images", label: l("Görseller (KB)", "Images (KB)", "Bilder (KB)", "图片（KB）"), type: "number", min: 0 },
    { key: "fonts", label: l("Fontlar (KB)", "Fonts (KB)", "Fonts (KB)", "字体（KB）"), type: "number", min: 0 },
    { key: "other", label: l("Diğer (KB)", "Other (KB)", "Sonstiges (KB)", "其他（KB）"), type: "number", min: 0 },
  ], demo: { budget: "900", html: "42", css: "68", js: "310", images: "460", fonts: "96", other: "35" } },
  "yedekleme-3-2-1-hazirlik-denetleyici": { fields: [
    { key: "copies", label: l("Toplam güncel kopya", "Current copies", "Aktuelle Kopien", "当前副本数"), type: "number", min: 0, max: 20 },
    { key: "media", label: l("Farklı ortam türü", "Distinct media types", "Unterschiedliche Medientypen", "不同介质类型数"), type: "number", min: 0, max: 10 },
    { key: "offsite", label: l("Uzak/çevrimdışı kopya", "Off-site/offline copy", "Außer-Haus-/Offline-Kopie", "异地/离线副本"), type: "checkbox" },
    { key: "encrypted", label: l("Hassas yedek şifreli", "Sensitive backup encrypted", "Sensible Sicherung verschlüsselt", "敏感备份已加密"), type: "checkbox" },
    { key: "restoreDate", label: l("Son başarılı geri yükleme", "Last successful restore", "Letzter erfolgreicher Restore", "最近成功恢复"), type: "date" },
    { key: "rto", label: l("Hedef kurtarma süresi (saat)", "Recovery-time target (hours)", "Wiederherstellungsziel (Stunden)", "恢复时间目标（小时）"), type: "number", min: 0.1, max: 8760, step: 0.1 },
  ], demo: { copies: "3", media: "2", offsite: true, encrypted: true, restoreDate: "2026-08-01", rto: "4" } },
  "surum-notu-degisiklik-derleyici": { fields: [{ key: "changes", label: l("Her satırda bir değişiklik", "One change per line", "Eine Änderung pro Zeile", "每行一项变更"), type: "textarea", help: l("feat:, fix:, perf:, security:, docs: veya BREAKING CHANGE:", "feat:, fix:, perf:, security:, docs:, or BREAKING CHANGE:", "feat:, fix:, perf:, security:, docs: oder BREAKING CHANGE:", "可使用 feat:、fix:、perf:、security:、docs: 或 BREAKING CHANGE:") }], demo: { changes: "feat(agent): add clearer follow-up suggestions\nfix(mobile): prevent community tabs from clipping\nperf(home): defer non-critical visual effects\nsecurity: reject unsafe external links\ndocs: expand local-processing explanation\nBREAKING CHANGE: recipe format now requires version=2" } },
};

function number(values: Values, key: string, locale: Locale, min = 0, max = Number.MAX_SAFE_INTEGER) {
  const raw = String(values[key] ?? "").trim(); const value = Number(raw);
  if (!raw || !Number.isFinite(value) || value < min || value > max) throw new Error(text(locale, l(`${key} alanına ${min}–${max} arasında geçerli bir sayı yazın.`, `Enter a valid ${key} value between ${min} and ${max}.`, `Für ${key} eine gültige Zahl zwischen ${min} und ${max} eingeben.`, `请为 ${key} 输入 ${min}–${max} 之间的有效数字。`)));
  return value;
}
function markdownTable(rows: Array<Array<string | number>>) { return rows.map((row, index) => `| ${row.map((cell) => String(cell).replace(/\|/g, "\\|")).join(" | ")} |${index === 0 ? `\n| ${row.map(() => "---").join(" | ")} |` : ""}`).join("\n"); }
function lines(value: string) { return value.split(/\r?\n/u).map((item) => item.trim()).filter(Boolean); }
function boundary(locale: Locale) { return text(locale, l("Bu sonuç açıklanabilir bir ön kontroldür; canlı sistem davranışı veya resmî uygunluk kanıtı değildir.", "This is an explainable pre-check, not proof of live-system behaviour or formal compliance.", "Dies ist eine nachvollziehbare Vorprüfung, kein Nachweis für Live-Verhalten oder formelle Konformität.", "这是可解释的预检查，不是线上系统行为或正式合规的证明。")); }
function requirement(ok: boolean, label: string, fix: string) { return [ok ? "✓" : "!", label, ok ? "OK" : fix]; }

export function runStudioTool(slug: string, values: Values, locale: Locale): Result {
  if (slug === "retry-after-geri-cekilme-planlayici") {
    const attempts = Math.floor(number(values, "attempts", locale, 1, 10)), base = number(values, "baseMs", locale, 50, 600000), cap = number(values, "capMs", locale, base, 3600000), jitter = number(values, "jitter", locale, 0, 50) / 100;
    const raw = String(values.retryAfter ?? "").trim(); const seconds = /^\d+(?:\.\d+)?$/u.test(raw) ? Number(raw) : Math.max(0, (Date.parse(raw) - Date.now()) / 1000);
    if (!raw || !Number.isFinite(seconds)) throw new Error(text(locale, l("Retry-After için saniye veya geçerli bir HTTP tarihi girin.", "Enter seconds or a valid HTTP date for Retry-After.", "Für Retry-After Sekunden oder ein gültiges HTTP-Datum eingeben.", "Retry-After 请输入秒数或有效 HTTP 日期。")));
    const method = String(values.method), safe = method === "GET" || method === "PUT";
    const rows: Array<Array<string | number>> = [[text(locale, l("Deneme", "Attempt", "Versuch", "尝试")), text(locale, l("Üstel gecikme", "Exponential delay", "Exponentielle Verzögerung", "指数延迟")), text(locale, l("Jitter aralığı", "Jitter range", "Jitter-Bereich", "抖动范围")), text(locale, l("En erken", "Earliest", "Frühestens", "最早"))]];
    for (let index = 0; index < attempts; index += 1) { const delay = Math.max(seconds * 1000, Math.min(cap, base * 2 ** index)); rows.push([index + 1, `${Math.round(delay)} ms`, `${Math.round(delay * (1 - jitter))}–${Math.round(delay * (1 + jitter))} ms`, `${(delay / 1000).toFixed(2)} s`]); }
    const note = safe ? text(locale, l("Yöntem yeniden deneme için idempotent adaydır.", "The method is an idempotent retry candidate.", "Die Methode ist ein idempotenter Retry-Kandidat.", "该方法可作为幂等重试候选。")) : text(locale, l("POST yalnız idempotency key veya açık sunucu sözleşmesiyle otomatik tekrar edilmelidir.", "Retry POST automatically only with an idempotency key or an explicit server contract.", "POST nur mit Idempotency-Key oder explizitem Serververtrag automatisch wiederholen.", "POST 仅应在有幂等键或明确服务端契约时自动重试。"));
    return { output: `${note}\n\n${markdownTable(rows)}\n\n${boundary(locale)}`, metrics: [["HTTP", String(values.status)], [text(locale, l("Deneme", "Attempts", "Versuche", "尝试")), attempts], ["Retry-After", `${seconds.toFixed(1)} s`]], warning: safe ? undefined : note };
  }
  if (slug === "webhook-teslim-gunlugu-analizoru") {
    const records = lines(String(values.records ?? "")).map((row, index) => { const parts = row.split("|").map((item) => item.trim()); if (parts.length !== 5) throw new Error(text(locale, l(`${index + 1}. satırda beş alan bulunmalı.`, `Line ${index + 1} must contain five fields.`, `Zeile ${index + 1} muss fünf Felder enthalten.`, `第 ${index + 1} 行必须包含五个字段。`))); const [time, id, status, latency, attempt] = parts; const stamp = Date.parse(time); if (!Number.isFinite(stamp) || !id || !/^\d{3}$/u.test(status) || !Number.isFinite(Number(latency)) || !Number.isFinite(Number(attempt))) throw new Error(text(locale, l(`${index + 1}. satırdaki zaman, kimlik veya sayısal alan geçersiz.`, `Line ${index + 1} has an invalid time, id, or number.`, `Zeile ${index + 1} enthält eine ungültige Zeit, ID oder Zahl.`, `第 ${index + 1} 行的时间、标识或数字无效。`))); return { stamp, time, id, status: Number(status), latency: Number(latency), attempt: Number(attempt) }; });
    if (!records.length) throw new Error(text(locale, l("En az bir teslim kaydı girin.", "Enter at least one delivery record.", "Mindestens einen Zustelldatensatz eingeben.", "请至少输入一条投递记录。")));
    const ids = [...new Set(records.map((item) => item.id))]; const duplicates = ids.filter((id) => records.filter((item) => item.id === id && item.status >= 200 && item.status < 300).length > 1); const failures = ids.filter((id) => !records.some((item) => item.id === id && item.status >= 200 && item.status < 300)); const orderIssues = records.filter((item, index) => index > 0 && item.stamp < records[index - 1].stamp).length; const sortedLatency = [...records].sort((a, b) => b.latency - a.latency);
    const rows = [[text(locale, l("Olay", "Event", "Ereignis", "事件")), text(locale, l("Deneme", "Attempts", "Versuche", "尝试")), text(locale, l("Son durum", "Final status", "Endstatus", "最终状态")), text(locale, l("En yüksek gecikme", "Peak latency", "Max. Latenz", "最大延迟"))], ...ids.map((id) => { const group = records.filter((item) => item.id === id).sort((a, b) => a.stamp - b.stamp); return [id, group.length, group.at(-1)?.status ?? "—", `${Math.max(...group.map((item) => item.latency))} ms`]; })];
    return { output: `${markdownTable(rows)}\n\n${text(locale, l("Sıra ihlali", "Ordering issues", "Reihenfolgefehler", "顺序问题"))}: ${orderIssues}\n${text(locale, l("Birden fazla başarılı teslim", "Multiple successful deliveries", "Mehrere erfolgreiche Zustellungen", "多次成功投递"))}: ${duplicates.join(", ") || "—"}\n${text(locale, l("Başarıya ulaşmayan olay", "Events without success", "Ereignisse ohne Erfolg", "未成功事件"))}: ${failures.join(", ") || "—"}\n${text(locale, l("En yavaş kayıt", "Slowest record", "Langsamster Datensatz", "最慢记录"))}: ${sortedLatency[0].id} · ${sortedLatency[0].latency} ms\n\n${boundary(locale)}`, metrics: [[text(locale, l("Olay", "Events", "Ereignisse", "事件")), ids.length], [text(locale, l("Deneme", "Attempts", "Versuche", "尝试")), records.length], [text(locale, l("İnceleme", "Review flags", "Prüfhinweise", "检查项")), duplicates.length + failures.length + orderIssues]] };
  }
  if (slug === "aria-erisebilir-ad-envanteri") {
    const html = String(values.html ?? ""); if (!html.trim()) throw new Error(text(locale, l("İncelenecek HTML'i girin.", "Enter HTML to inspect.", "HTML zur Prüfung eingeben.", "请输入待检查 HTML。")));
    const doc = new DOMParser().parseFromString(html, "text/html"); const controls = [...doc.querySelectorAll<HTMLElement>("button,a[href],input:not([type=hidden]),select,textarea,[role=button],[role=link]")];
    const rows = controls.map((element, index) => { const labelledBy = element.getAttribute("aria-labelledby")?.split(/\s+/u).map((id) => doc.getElementById(id)?.textContent?.trim() ?? "").filter(Boolean).join(" "); const id = element.id; const label = id ? doc.querySelector<HTMLLabelElement>(`label[for="${CSS.escape(id)}"]`)?.textContent?.trim() : ""; const input = element as HTMLInputElement; const name = element.getAttribute("aria-label")?.trim() || labelledBy || label || (element.tagName === "IMG" ? element.getAttribute("alt")?.trim() : "") || element.textContent?.trim() || input.alt || element.getAttribute("title")?.trim() || ""; return [index + 1, element.tagName.toLowerCase(), element.getAttribute("role") ?? "—", name || text(locale, l("ADSIZ", "UNNAMED", "UNBENANNT", "无名称")), name ? "✓" : "!"]; });
    const unnamed = rows.filter((row) => row[4] === "!").length;
    return { output: `${markdownTable([["#", text(locale, l("Öğe", "Element", "Element", "元素")), "role", text(locale, l("Erişilebilir ad", "Accessible name", "Zugänglicher Name", "可访问名称")), text(locale, l("Durum", "Status", "Status", "状态"))], ...rows])}\n\n${boundary(locale)}`, metrics: [[text(locale, l("Kontrol", "Controls", "Steuerelemente", "控件")), controls.length], [text(locale, l("Adsız", "Unnamed", "Unbenannt", "无名称")), unnamed], [text(locale, l("Kapsam", "Coverage", "Abdeckung", "覆盖率")), controls.length ? `${Math.round((1 - unnamed / controls.length) * 100)}%` : "—"]], warning: unnamed ? text(locale, l("Adsız kontroller klavye ve ekran okuyucu görevlerini zorlaştırabilir.", "Unnamed controls can block keyboard and screen-reader tasks.", "Unbenannte Elemente können Tastatur- und Screenreader-Aufgaben blockieren.", "无名称控件可能妨碍键盘与屏幕阅读器任务。")) : undefined };
  }
  if (slug === "html-dil-baslik-yapisi-denetleyici") {
    const html = String(values.html ?? ""); if (!html.trim()) throw new Error(text(locale, l("Sayfa HTML'ini girin.", "Enter page HTML.", "Seiten-HTML eingeben.", "请输入页面 HTML。")));
    const doc = new DOMParser().parseFromString(html, "text/html"); const lang = doc.documentElement.lang.trim(); const titleValue = doc.title.trim(); const description = doc.querySelector<HTMLMetaElement>('meta[name="description"]')?.content.trim() ?? ""; const headings = [...doc.querySelectorAll<HTMLElement>("h1,h2,h3,h4,h5,h6")]; let previous = 0; const jumps: string[] = []; headings.forEach((heading) => { const level = Number(heading.tagName.slice(1)); if (previous && level > previous + 1) jumps.push(`${heading.tagName}: ${heading.textContent?.trim().slice(0, 60) || "∅"}`); previous = level; }); const h1 = headings.filter((heading) => heading.tagName === "H1"); const empty = headings.filter((heading) => !heading.textContent?.trim()); const checks = [requirement(Boolean(lang), "html lang", text(locale, l("Geçerli BCP 47 dili ekleyin", "Add a valid BCP 47 language", "Gültige BCP-47-Sprache ergänzen", "添加有效 BCP 47 语言"))), requirement(titleValue.length >= 20 && titleValue.length <= 65, `title · ${titleValue.length}`, text(locale, l("20–65 karakteri hedefleyin", "Aim for 20–65 characters", "20–65 Zeichen anstreben", "建议 20–65 个字符"))), requirement(description.length >= 70 && description.length <= 170, `description · ${description.length}`, text(locale, l("70–170 karakteri hedefleyin", "Aim for 70–170 characters", "70–170 Zeichen anstreben", "建议 70–170 个字符"))), requirement(h1.length === 1, `H1 · ${h1.length}`, text(locale, l("Tek, açıklayıcı H1 kullanın", "Use one descriptive H1", "Eine beschreibende H1 verwenden", "使用一个描述性 H1"))), requirement(!empty.length, text(locale, l("Boş başlık yok", "No empty headings", "Keine leeren Überschriften", "无空标题")), text(locale, l("Boş başlığı kaldırın veya adlandırın", "Remove or name empty headings", "Leere Überschrift entfernen oder benennen", "删除空标题或补充名称"))), requirement(!jumps.length, text(locale, l("Seviye atlaması yok", "No level jumps", "Keine Ebenensprünge", "无层级跳跃")), jumps.join("; "))]; const failures = checks.filter((row) => row[0] === "!").length;
    return { output: `${markdownTable([[text(locale, l("Durum", "Status", "Status", "状态")), text(locale, l("Kontrol", "Check", "Prüfung", "检查")), text(locale, l("Sonraki adım", "Next action", "Nächster Schritt", "下一步"))], ...checks])}\n\n${text(locale, l("Başlık akışı", "Heading outline", "Überschriftenstruktur", "标题结构"))}:\n${headings.map((heading) => `${"  ".repeat(Number(heading.tagName.slice(1)) - 1)}- ${heading.tagName}: ${heading.textContent?.trim() || "∅"}`).join("\n") || "—"}\n\n${boundary(locale)}`, metrics: [["lang", lang || "—"], [text(locale, l("Başlık", "Headings", "Überschriften", "标题")), headings.length], [text(locale, l("Düzeltme", "Fixes", "Korrekturen", "修正")), failures]] };
  }
  if (slug === "sitemap-url-kume-analizoru") {
    const raw = lines(String(values.urls ?? "")); if (!raw.length) throw new Error(text(locale, l("En az bir mutlak URL girin.", "Enter at least one absolute URL.", "Mindestens eine absolute URL eingeben.", "请至少输入一个绝对 URL。")));
    const parsed = raw.map((value, index) => { try { const url = new URL(value); const normalized = `${url.protocol}//${url.host}${url.pathname.replace(/\/{2,}/g, "/").replace(/\/?$/u, "/")}`; const localeSegment = url.pathname.match(/^\/(en|de|zh)(?:\/|$)/u)?.[1] ?? "tr"; const key = url.pathname.replace(/^\/(?:en|de|zh)(?=\/)/u, "").replace(/\/$/u, ""); return { index: index + 1, value, url, normalized, localeSegment, key, depth: url.pathname.split("/").filter(Boolean).length }; } catch { throw new Error(text(locale, l(`${index + 1}. satır geçerli bir mutlak URL değil.`, `Line ${index + 1} is not a valid absolute URL.`, `Zeile ${index + 1} ist keine gültige absolute URL.`, `第 ${index + 1} 行不是有效绝对 URL。`))); } }); const hosts = [...new Set(parsed.map((item) => item.url.host))]; const duplicates = parsed.filter((item, index) => parsed.findIndex((candidate) => candidate.normalized === item.normalized) !== index); const groups = new Map<string, Set<string>>(); parsed.forEach((item) => groups.set(item.key, (groups.get(item.key) ?? new Set()).add(item.localeSegment))); const incomplete = [...groups].filter(([, locales]) => locales.size > 1 && ["tr", "en", "de", "zh"].some((localeCode) => !locales.has(localeCode))); const flags = parsed.map((item) => [item.index, item.url.protocol === "https:" ? "✓" : "! HTTP", item.url.search ? `! query ${item.url.search}` : "✓", item.url.hash ? `! fragment ${item.url.hash}` : "✓", item.depth, item.url.host]);
    return { output: `${markdownTable([["#", "HTTPS", text(locale, l("Sorgu", "Query", "Query", "查询")), text(locale, l("Parça", "Fragment", "Fragment", "片段")), text(locale, l("Derinlik", "Depth", "Tiefe", "深度")), "Host"], ...flags])}\n\n${text(locale, l("Farklı hostlar", "Distinct hosts", "Unterschiedliche Hosts", "不同主机"))}: ${hosts.join(", ")}\n${text(locale, l("Tekrarlar", "Duplicates", "Duplikate", "重复项"))}: ${duplicates.map((item) => item.value).join("\n") || "—"}\n${text(locale, l("Eksik dil kümeleri", "Incomplete locale clusters", "Unvollständige Sprachcluster", "不完整语言集合"))}: ${incomplete.map(([key, locales]) => `${key || "/"} → ${[...locales].join(",")}`).join("\n") || "—"}\n\n${boundary(locale)}`, metrics: [["URL", parsed.length], ["Host", hosts.length], [text(locale, l("İnceleme", "Review flags", "Prüfhinweise", "检查项")), duplicates.length + incomplete.length + parsed.filter((item) => item.url.protocol !== "https:" || item.url.search || item.url.hash).length]] };
  }
  if (slug === "robots-meta-politikasi-olusturucu") {
    const index = Boolean(values.index), follow = Boolean(values.follow), archive = Boolean(values.archive), large = Boolean(values.largeImage); const maxSnippet = Math.floor(number(values, "maxSnippet", locale, -1, 1000)); const directives = [index ? "index" : "noindex", follow ? "follow" : "nofollow", archive ? "archive" : "noarchive"]; if (index) { directives.push(`max-snippet:${maxSnippet}`, `max-image-preview:${large ? "large" : "standard"}`, "max-video-preview:-1"); }
    const tag = `<meta name="robots" content="${directives.join(", ")}">`; const note = index ? text(locale, l("İndekslenebilir sayfada canonical, hreflang, içerik kalitesi ve HTTP durumunu ayrıca doğrulayın.", "Also verify canonical, hreflang, content quality, and HTTP status on an indexable page.", "Bei indexierbaren Seiten zusätzlich Canonical, hreflang, Inhalt und HTTP-Status prüfen.", "对于可索引页面，还需检查 canonical、hreflang、内容质量与 HTTP 状态。")) : text(locale, l("noindex sayfayı gizli yapmaz; hassas içerik gerçek erişim kontrolü gerektirir.", "noindex does not make a page private; sensitive content needs real access control.", "noindex macht eine Seite nicht privat; sensible Inhalte brauchen Zugriffsschutz.", "noindex 不会让页面变为私密；敏感内容需要真实访问控制。"));
    return { output: `${tag}\n\n${text(locale, l("Direktifler", "Directives", "Direktiven", "指令"))}: ${directives.join(" · ")}\n\n${note}\n${boundary(locale)}`, metrics: [[text(locale, l("Direktif", "Directives", "Direktiven", "指令")), directives.length], [text(locale, l("İndeks", "Indexing", "Indexierung", "索引")), index ? "index" : "noindex"]], warning: !index ? note : undefined };
  }
  if (slug === "eposta-konu-onizleme-denetleyici") {
    const subject = String(values.subject ?? "").trim(), preheader = String(values.preheader ?? "").trim(); if (!subject) throw new Error(text(locale, l("Konu satırını girin.", "Enter a subject line.", "Betreffzeile eingeben.", "请输入主题行。"))); const sameOpening = preheader && subject.toLocaleLowerCase().split(/\s+/u).slice(0, 4).join(" ") === preheader.toLocaleLowerCase().split(/\s+/u).slice(0, 4).join(" "); const flags = [subject.length > 60 ? text(locale, l("Konu küçük ekranlarda kesilebilir.", "The subject may truncate on small screens.", "Der Betreff kann auf kleinen Bildschirmen gekürzt werden.", "主题可能在小屏幕上被截断。")) : "", !preheader ? text(locale, l("Önizleme metni boş; istemci gövde metnini gösterebilir.", "The preheader is empty; clients may expose body text.", "Preheader leer; Clients können Body-Text anzeigen.", "预标题为空；客户端可能显示正文。")) : "", sameOpening ? text(locale, l("Konu ve önizleme aynı ifadeyle başlıyor.", "Subject and preheader repeat the same opening.", "Betreff und Preheader beginnen gleich.", "主题与预标题开头重复。")) : "", /[!?]{3,}/u.test(subject) ? text(locale, l("Art arda noktalama okunabilirliği düşürüyor.", "Repeated punctuation reduces readability.", "Wiederholte Satzzeichen mindern die Lesbarkeit.", "重复标点会降低可读性。")) : "", /[A-ZÇĞİÖŞÜ]{12,}/u.test(subject) ? text(locale, l("Uzun tamamı büyük harf bölümü var.", "A long all-caps segment was found.", "Ein langer Versalienabschnitt wurde gefunden.", "检测到较长全大写片段。")) : ""].filter(Boolean);
    const previews = [[text(locale, l("Mobil yaklaşık", "Approx. mobile", "Mobil ungefähr", "移动端近似")), subject.slice(0, 42) + (subject.length > 42 ? "…" : "")], [text(locale, l("Masaüstü yaklaşık", "Approx. desktop", "Desktop ungefähr", "桌面端近似")), subject.slice(0, 65) + (subject.length > 65 ? "…" : "")], [text(locale, l("Önizleme", "Preheader", "Preheader", "预标题")), preheader.slice(0, 90) + (preheader.length > 90 ? "…" : "")]];
    return { output: `${markdownTable([[text(locale, l("Görünüm", "View", "Ansicht", "视图")), text(locale, l("Yaklaşık metin", "Approximate text", "Ungefährer Text", "近似文本"))], ...previews])}\n\n${flags.length ? flags.map((flag) => `! ${flag}`).join("\n") : text(locale, l("✓ Yerleşik okunabilirlik sinyallerinde açık sorun bulunmadı.", "✓ No clear issue was found by the built-in readability signals.", "✓ Die integrierten Signale fanden kein klares Problem.", "✓ 内置可读性信号未发现明显问题。"))}\n\n${boundary(locale)}`, metrics: [[text(locale, l("Konu karakteri", "Subject characters", "Betreffzeichen", "主题字符")), subject.length], [text(locale, l("Önizleme karakteri", "Preheader characters", "Preheader-Zeichen", "预标题字符")), preheader.length], [text(locale, l("İnceleme", "Review flags", "Prüfhinweise", "检查项")), flags.length]] };
  }
  if (slug === "web-performans-butce-planlayici") {
    const budget = number(values, "budget", locale, 50, 10000); const keys = ["html", "css", "js", "images", "fonts", "other"] as const; const amounts = keys.map((key) => [key, number(values, key, locale, 0, 100000)] as const); const total = amounts.reduce((sum, [, value]) => sum + value, 0); const difference = budget - total; const sorted = [...amounts].sort((a, b) => b[1] - a[1]); const rows = [[text(locale, l("Kaynak", "Resource", "Ressource", "资源")), "KB", "%"], ...sorted.map(([key, value]) => [key, value.toFixed(1), total ? `${(value / total * 100).toFixed(1)}%` : "0%"]), [text(locale, l("TOPLAM", "TOTAL", "GESAMT", "总计")), total.toFixed(1), "100%"]]; const targetCut = Math.max(0, total - budget); const note = targetCut ? text(locale, l(`Bütçeye inmek için en az ${targetCut.toFixed(1)} KB azaltın; önce ${sorted[0][0]} kaynağındaki gereksiz aktarımı inceleyin.`, `Reduce at least ${targetCut.toFixed(1)} KB to meet budget; inspect avoidable ${sorted[0][0]} transfer first.`, `Mindestens ${targetCut.toFixed(1)} KB reduzieren; zuerst vermeidbare ${sorted[0][0]}-Übertragung prüfen.`, `至少减少 ${targetCut.toFixed(1)} KB；先检查 ${sorted[0][0]} 中可避免的传输。`)) : text(locale, l(`${difference.toFixed(1)} KB koruma payı var; yeni bağımlılık ve medya eklemelerinde bu sınırı koruyun.`, `${difference.toFixed(1)} KB of headroom remains; preserve it when adding dependencies and media.`, `${difference.toFixed(1)} KB Reserve verbleiben; bei neuen Abhängigkeiten und Medien schützen.`, `剩余 ${difference.toFixed(1)} KB 余量；新增依赖与媒体时应保留。`));
    return { output: `${markdownTable(rows)}\n\n${note}\n${boundary(locale)}`, metrics: [[text(locale, l("Toplam", "Total", "Gesamt", "总计")), `${total.toFixed(1)} KB`], [text(locale, l("Bütçe", "Budget", "Budget", "预算")), `${budget.toFixed(1)} KB`], [text(locale, l("Durum", "Status", "Status", "状态")), total <= budget ? "PASS" : "REVIEW"]], warning: total > budget ? note : undefined };
  }
  if (slug === "yedekleme-3-2-1-hazirlik-denetleyici") {
    const copies = Math.floor(number(values, "copies", locale, 0, 20)), media = Math.floor(number(values, "media", locale, 0, 10)), offsite = Boolean(values.offsite), encrypted = Boolean(values.encrypted), dateText = String(values.restoreDate ?? ""), restore = Date.parse(`${dateText}T00:00:00Z`), rto = number(values, "rto", locale, .1, 8760); if (!dateText || !Number.isFinite(restore)) throw new Error(text(locale, l("Geçerli son geri yükleme tarihini girin.", "Enter a valid last-restore date.", "Gültiges Datum des letzten Restores eingeben.", "请输入有效的最近恢复日期。"))); const days = Math.max(0, Math.floor((Date.now() - restore) / 86400000)); const checks = [requirement(copies >= 3, text(locale, l("En az üç güncel kopya", "At least three current copies", "Mindestens drei aktuelle Kopien", "至少三个当前副本")), text(locale, l("Ek doğrulanmış kopya oluşturun", "Create another verified copy", "Weitere geprüfte Kopie erstellen", "创建额外已验证副本"))), requirement(media >= 2, text(locale, l("En az iki ortam türü", "At least two media types", "Mindestens zwei Medientypen", "至少两种介质")), text(locale, l("Tek hata alanına bağımlılığı azaltın", "Reduce dependence on one failure domain", "Abhängigkeit von einer Fehlerdomäne reduzieren", "减少对单一故障域的依赖"))), requirement(offsite, text(locale, l("Uzak veya çevrimdışı kopya", "Off-site or offline copy", "Außer-Haus- oder Offline-Kopie", "异地或离线副本")), text(locale, l("Ayrı bir konum ekleyin", "Add a separate location", "Separaten Standort ergänzen", "添加独立位置"))), requirement(encrypted, text(locale, l("Hassas yedek şifreli", "Sensitive backup encrypted", "Sensible Sicherung verschlüsselt", "敏感备份加密")), text(locale, l("Anahtar kurtarma planıyla şifreleyin", "Encrypt with a key-recovery plan", "Mit Schlüssel-Recovery-Plan verschlüsseln", "结合密钥恢复计划进行加密"))), requirement(days <= 90, text(locale, l(`Geri yükleme denemesi · ${days} gün`, `Restore test · ${days} days`, `Restore-Test · ${days} Tage`, `恢复测试 · ${days} 天`)), text(locale, l("Kontrollü geri yükleme denemesi planlayın", "Schedule a controlled restore test", "Kontrollierten Restore-Test planen", "安排受控恢复测试")))]; const gaps = checks.filter((row) => row[0] === "!").length;
    return { output: `${markdownTable([[text(locale, l("Durum", "Status", "Status", "状态")), text(locale, l("Kanıt", "Evidence", "Nachweis", "证据")), text(locale, l("Eylem", "Action", "Aktion", "行动"))], ...checks])}\n\nRTO: ${rto} h\n${boundary(locale)}`, metrics: [[text(locale, l("Kontrol", "Checks", "Prüfungen", "检查")), checks.length], [text(locale, l("Açık", "Gaps", "Lücken", "缺口")), gaps], ["RTO", `${rto} h`]], warning: gaps ? text(locale, l("Hazırlık açığı var; yedeği var saymak yerine geri yükleme kanıtını tamamlayın.", "Readiness gaps remain; complete restore evidence rather than assuming the backup works.", "Es bestehen Lücken; Restore-Nachweise vervollständigen statt Funktion anzunehmen.", "仍有准备缺口；请补全恢复证据，不要假设备份可用。")) : undefined };
  }
  if (slug === "surum-notu-degisiklik-derleyici") {
    const raw = lines(String(values.changes ?? "")); if (!raw.length) throw new Error(text(locale, l("En az bir değişiklik satırı girin.", "Enter at least one change line.", "Mindestens eine Änderungszeile eingeben.", "请至少输入一行变更。"))); const headings: Record<string, L> = { breaking: l("Kırıcı değişiklikler", "Breaking changes", "Inkompatible Änderungen", "破坏性变更"), security: l("Güvenlik", "Security", "Sicherheit", "安全"), feat: l("Yeni", "Added", "Neu", "新增"), perf: l("Performans", "Performance", "Performance", "性能"), fix: l("Düzeltildi", "Fixed", "Behoben", "修复"), docs: l("Belgeler", "Documentation", "Dokumentation", "文档"), other: l("Diğer", "Other", "Sonstiges", "其他") }; const buckets = new Map<string, string[]>(); raw.forEach((line) => { const breaking = /^BREAKING CHANGE:/i.test(line) || /!\s*:/u.test(line); const match = line.match(/^(feat|fix|perf|security|docs)(?:\(([^)]+)\))?!?:\s*(.+)$/iu); const kind = breaking ? "breaking" : match?.[1]?.toLowerCase() ?? "other"; const scope = match?.[2]; const body = (match?.[3] ?? line.replace(/^BREAKING CHANGE:\s*/iu, "")).trim(); const item = scope ? `**${scope}:** ${body}` : body; const current = buckets.get(kind) ?? []; if (!current.some((value) => value.toLocaleLowerCase() === item.toLocaleLowerCase())) current.push(item); buckets.set(kind, current); }); const order = ["breaking", "security", "feat", "perf", "fix", "docs", "other"]; const output = order.filter((kind) => buckets.get(kind)?.length).map((kind) => `## ${text(locale, headings[kind])}\n${buckets.get(kind)?.map((item) => `- ${item}`).join("\n")}`).join("\n\n"); const missing = raw.filter((line) => !/^(feat|fix|perf|security|docs)(?:\([^)]+\))?!?:|^BREAKING CHANGE:/iu.test(line)).length;
    return { output: `# ${text(locale, l("Sürüm notları", "Release notes", "Versionshinweise", "发布说明"))}\n\n${output}\n\n---\n${text(locale, l("Yayın kontrolü: tarih, sürüm numarası, geçiş adımı ve ilgili destek bağlantılarını doğrulayın.", "Release check: confirm date, version number, migration steps, and relevant support links.", "Releaseprüfung: Datum, Version, Migrationsschritte und Supportlinks bestätigen.", "发布检查：确认日期、版本号、迁移步骤与相关支持链接。"))}`, metrics: [[text(locale, l("Benzersiz madde", "Unique items", "Eindeutige Punkte", "唯一条目")), [...buckets.values()].reduce((sum, items) => sum + items.length, 0)], [text(locale, l("Bölüm", "Sections", "Abschnitte", "章节")), buckets.size], [text(locale, l("Türsüz", "Unclassified", "Nicht klassifiziert", "未分类")), missing]] };
  }
  throw new Error(text(locale, l("Bu araç çalışma alanına bağlanamadı.", "This tool could not be connected to its workbench.", "Dieses Werkzeug konnte nicht verbunden werden.", "该工具无法连接到工作区。")));
}

export function StudioWorkbench({ slug, locale }: { slug: string; locale: Locale }) {
  const definition = definitions[slug]; const t = ui[locale]; const tool = getTool(slug); const [values, setValues] = useState<Values>({}); const [result, setResult] = useState<Result | null>(null); const [state, setState] = useState<"idle" | "busy" | "success" | "error">("idle"); const [message, setMessage] = useState(""); const fields = useMemo(() => definition?.fields ?? [], [definition]);
  const resetResult = () => { setResult(null); setState("idle"); setMessage(""); };
  function setValue(key: string, value: string | boolean) { setValues((current) => ({ ...current, [key]: value })); resetResult(); }
  function loadDemo() { setValues({ ...definition.demo }); resetResult(); }
  async function run() { if (state === "busy") return; setState("busy"); setMessage(""); await new Promise<void>((resolve) => requestAnimationFrame(() => resolve())); try { setResult(runStudioTool(slug, values, locale)); setState("success"); } catch (error) { setResult(null); setState("error"); setMessage(error instanceof Error ? error.message : String(error)); } }
  async function copy() { if (!result?.output) return; try { await navigator.clipboard.writeText(result.output); } catch { setState("error"); setMessage(t.error); } }
  function download() { if (!result?.output) return; const url = URL.createObjectURL(new Blob([result.output], { type: "text/plain;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `bytequant-${slug}.txt`; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 0); }
  if (!definition) return null;
  return <section className="workbench studio-workbench" aria-busy={state === "busy"} aria-label={tool?.title[locale]}>
    <div className="workbench-bar"><span className="local-status"><i />{t.local}<small>{tool?.title[locale]}</small></span><div className="workbench-bar-actions"><button type="button" className="demo-button" onClick={loadDemo} disabled={state === "busy"}>{t.demo}</button><button type="button" className="ghost-button" onClick={() => { setValues({}); resetResult(); }} disabled={state === "busy"}>{t.clear}</button></div></div>
    <div className="studio-workbench-grid">
      <div className="studio-form"><div className="frontier-purpose"><strong>{tool?.title[locale]}</strong><p>{tool?.short[locale]}</p></div><div className="studio-fields">{fields.map((field) => <label key={field.key} className={field.type === "textarea" ? "studio-field-wide" : field.type === "checkbox" ? "studio-check" : ""}>{field.type === "checkbox" ? <><input type="checkbox" checked={Boolean(values[field.key])} onChange={(event) => setValue(field.key, event.target.checked)} /><span><strong>{field.label[locale]}</strong>{field.help && <small>{field.help[locale]}</small>}</span></> : <><span>{field.label[locale]}</span>{field.type === "textarea" ? <textarea rows={9} maxLength={200000} value={String(values[field.key] ?? "")} onChange={(event) => setValue(field.key, event.target.value)} spellCheck={false} /> : field.type === "select" ? <select value={String(values[field.key] ?? "")} onChange={(event) => setValue(field.key, event.target.value)}><option value="">—</option>{field.options?.map(([value, label]) => <option value={value} key={value}>{label[locale]}</option>)}</select> : <input type={field.type === "number" || field.type === "date" ? field.type : "text"} min={field.min} max={field.max} step={field.step} value={String(values[field.key] ?? "")} onChange={(event) => setValue(field.key, event.target.value)} />}{field.help && <small>{field.help[locale]}</small>}</>}</label>)}</div><button type="button" className="primary-button run-button" onClick={() => void run()} disabled={state === "busy"}>{state === "busy" ? t.running : t.run}<span aria-hidden="true">→</span></button></div>
      <div className="result-panel" aria-live="polite" aria-busy={state === "busy"}><div className="result-header"><span>{t.result}<small className="frontier-state" data-state={state}>{state === "success" ? t.done : state === "error" ? t.error : state === "busy" ? t.running : ""}</small></span><div className="output-actions"><button type="button" disabled={!result} onClick={() => void copy()}>{t.copy}</button><button type="button" disabled={!result} onClick={download}>{t.download}</button></div></div>{result?.metrics?.length ? <div className="metric-strip">{result.metrics.map(([label, value]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div> : null}<StructuredToolOutput output={result?.output ?? ""} empty={t.idle} />{result?.warning && <ToolNotice locale={locale} notice={{ kind: "warning", text: result.warning }} />}{state === "error" && <ToolNotice locale={locale} notice={{ kind: "error", text: message }} />}{state === "success" && <div className="workbench-trust-card"><span aria-hidden="true">✓</span><p>{t.privacy}</p></div>}</div>
    </div>
  </section>;
}
