import Link from "next/link";
import { categories, getRelatedTools, getTool, publicTools as tools, type Tool } from "../lib/tools";
import { absoluteUrl, languageTag, organizationId, pathFor, postPath, schemaDate, toolPath, websiteId, type Locale } from "../lib/site";
import { SchemaScript } from "./SchemaScript";
import { SiteShell } from "./SiteShell";
import { ToolCard } from "./ToolCard";
import { ToolUsageTracker } from "./ToolUsage";
import { ToolWorkbench } from "./ToolWorkbench";
import { referenceCopy, referencePath, references } from "../lib/references";
import { posts } from "../lib/posts";
import { localizedGuides } from "../lib/localized-guides";
import { AgentToolBridge } from "./AgentToolBridge";
import { WorkspaceToolBridge } from "./WorkspaceToolBridge";
import { ToolExperience } from "./ToolExperience";
import { CONTENT_REVIEW_DATE } from "../lib/content-review";
import { ToolEditorialReview } from "./ToolEditorialReview";
import { getToolGuidanceDetails } from "../lib/tool-guidance";

export function ToolPage({ tool, locale }: { tool: Tool; locale: Locale }) {
  const editorialLocale = locale === "tr" ? "tr" : "en";
  const localized = (tr: string, en: string, de: string, zh: string) => ({ tr, en, de, zh })[locale];
  const currentLanguage = languageTag(locale);
  const guidance = getToolGuidanceDetails(tool);
  const pageUrl = absoluteUrl(toolPath(locale, tool.slug));
  const alternateHref = toolPath(locale === "tr" ? "en" : "tr", tool.slug);
  const related = getRelatedTools(tool);
  const compareOutput = (["text", "data", "converter", "security"] as const).includes(tool.category as "text" | "data" | "converter" | "security");
  const relatedReference = references.find((guide) => guide.toolSlug === tool.slug);
  const relatedReferenceCopy = relatedReference ? referenceCopy(relatedReference, locale) : null;
  const directPosts = posts.filter((post) => post.relatedTools.includes(tool.slug)).slice().reverse();
  const categoryPosts = posts.filter((post) => post.relatedTools.some((slug) => getTool(slug)?.category === tool.category)).slice().reverse();
  const relatedPosts = [...directPosts, ...categoryPosts.filter((post) => !directPosts.some((direct) => direct.slug === post.slug))].slice(0, 2);
  const directLocalizedGuides = localizedGuides.filter((guide) => guide.relatedTools.includes(tool.slug)).slice().reverse();
  const categoryLocalizedGuides = localizedGuides.filter((guide) => guide.relatedTools.some((slug) => getTool(slug)?.category === tool.category)).slice().reverse();
  const recommendedLocalizedGuides = [...directLocalizedGuides, ...categoryLocalizedGuides.filter((guide) => !directLocalizedGuides.some((direct) => direct.slug === guide.slug))].slice(0, 2);
  const guideLinks = locale === "de" || locale === "zh"
    ? [...recommendedLocalizedGuides.map((guide) => ({ slug: guide.slug, category: guide.copy[locale].category, readTime: guide.copy[locale].readTime, title: guide.copy[locale].title, excerpt: guide.copy[locale].excerpt, href: postPath(locale, guide.slug), hrefLang: locale })), ...relatedPosts.filter((post) => !recommendedLocalizedGuides.some((guide) => guide.slug === post.slug)).map((post) => ({ slug: post.slug, category: post.category.en, readTime: post.readTime.en, title: post.title.en, excerpt: post.excerpt.en, href: postPath("en", post.slug), hrefLang: "en" }))].slice(0, 2)
    : relatedPosts.map((post) => ({ slug: post.slug, category: post.category[editorialLocale], readTime: post.readTime[editorialLocale], title: post.title[editorialLocale], excerpt: post.excerpt[editorialLocale], href: postPath(editorialLocale, post.slug), hrefLang: editorialLocale }));
  const answer = `${tool.short[locale]} ${guidance.boundary[locale]}`;
  const inputLabel = localized("Girdi", "Input", "Eingabe", "输入");
  const outputLabel = localized("Çıktı", "Output", "Ausgabe", "输出");
  const verifyLabel = localized("Doğrulama", "Verification", "Prüfung", "核验");
  const methodLabel = localized("Yöntem", "Method", "Methode", "方法");
  const faq = [
    [localized(`${tool.title.tr} hangi girdiyi kabul eder?`, `What input does ${tool.title.en} accept?`, `Welche Eingabe akzeptiert ${tool.title.de}?`, `${tool.title.zh}接受什么输入？`), `${guidance.input[locale]} ${tool.steps[locale][0]}`],
    [localized(`${tool.title.tr} çıktısında ne görürüm?`, `What does ${tool.title.en} return?`, `Was liefert ${tool.title.de}?`, `${tool.title.zh}会输出什么？`), `${guidance.output[locale]} ${guidance.method[locale]}`],
    [localized(`${tool.title.tr} çıktısını nasıl doğrulamalıyım?`, `How should I validate ${tool.title.en} output?`, `Wie prüfe ich die Ausgabe von ${tool.title.de}?`, `如何核验${tool.title.zh}的输出？`), localized(`“${tool.useCases.tr[0]}” senaryosu için önce “${tool.steps.tr[1]}” adımını tamamlayın; ardından “${tool.steps.tr[2]}” kontrolünü uygulayın. Sınır veya bozuk girdiyle ikinci bir deneme yapmadan kritik sonucu kullanmayın.`, `For “${tool.useCases.en[0]}”, first complete “${tool.steps.en[1]}”, then apply this check: “${tool.steps.en[2]}”. Do not use a consequential result before a second test with boundary or malformed input.`, `Für „${tool.useCases.de[0]}“ führen Sie zunächst „${tool.steps.de[1]}“ aus und prüfen danach „${tool.steps.de[2]}“. Folgenreiche Ergebnisse erst nach einem zweiten Test mit Grenz- oder Fehleingabe verwenden.`, `针对“${tool.useCases.zh[0]}”，先完成“${tool.steps.zh[1]}”，再执行“${tool.steps.zh[2]}”。在使用可能产生重要影响的结果前，还应使用边界或错误输入再测试一次。`)],
    [localized("Bu araç verimi bir sunucuya gönderiyor veya kaydediyor mu?", "Does this tool send or store input on a server?", "Sendet oder speichert dieses Werkzeug Eingaben auf einem Server?", "该工具会向服务器发送或保存输入吗？"), localized("Hayır. İşlem bu tarayıcı sekmesinde çalışır ve araç girdisi kalıcı alanda tutulmaz. Kopyalama, indirme veya başka araca aktarım yalnızca sizin eyleminizle gerçekleşir.", "No. Processing runs in this browser tab and tool input is not persisted. Copying, downloading, or transferring happens only when you choose it.", "Nein. Die Verarbeitung läuft in diesem Browser-Tab; Werkzeugeingaben werden nicht dauerhaft gespeichert. Kopieren, Herunterladen oder Übertragen erfolgt nur durch Ihre Aktion.", "不会。处理在当前浏览器标签页中完成，工具输入不会持久保存。复制、下载或传递只会由您的操作触发。")],
  ];
  const schema = [
    { "@context": "https://schema.org", "@type": "WebPage", "@id": `${pageUrl}#page`, name: tool.title[locale], description: tool.short[locale], url: pageUrl, inLanguage: currentLanguage, dateModified: schemaDate(CONTENT_REVIEW_DATE), isPartOf: { "@id": websiteId }, primaryImageOfPage: { "@type": "ImageObject", url: absoluteUrl("/og.png") }, mainEntity: { "@id": `${pageUrl}#application` }, breadcrumb: { "@id": `${pageUrl}#breadcrumb` } },
    { "@context": "https://schema.org", "@type": "WebApplication", "@id": `${pageUrl}#application`, name: tool.title[locale], description: tool.description[locale], url: pageUrl, mainEntityOfPage: { "@id": `${pageUrl}#page` }, applicationCategory: "UtilitiesApplication", operatingSystem: "Any current standards-based browser", browserRequirements: "JavaScript enabled; secure context required for Web Crypto and PWA installation", inLanguage: currentLanguage, isAccessibleForFree: true, dateModified: schemaDate(CONTENT_REVIEW_DATE), featureList: tool.useCases[locale], offers: { "@type": "Offer", price: "0", priceCurrency: "USD" }, creator: { "@id": organizationId }, isPartOf: { "@id": websiteId }, privacyPolicy: absoluteUrl(pathFor(locale, "privacy")) },
    { "@context": "https://schema.org", "@type": "BreadcrumbList", "@id": `${pageUrl}#breadcrumb`, itemListElement: [{ "@type": "ListItem", position: 1, name: localized("Ana sayfa", "Home", "Startseite", "首页"), item: absoluteUrl(pathFor(locale, "home")) }, { "@type": "ListItem", position: 2, name: localized("Araçlar", "Tools", "Werkzeuge", "工具"), item: absoluteUrl(pathFor(locale, "tools")) }, { "@type": "ListItem", position: 3, name: tool.title[locale], item: pageUrl }] },
    { "@context": "https://schema.org", "@type": "HowTo", "@id": `${pageUrl}#how-to`, name: localized(`${tool.title[locale]} nasıl kullanılır?`, `How to use ${tool.title[locale]}`, `${tool.title[locale]} verwenden`, `如何使用${tool.title[locale]}`), description: tool.short[locale], totalTime: "PT3M", inLanguage: currentLanguage, isPartOf: { "@id": `${pageUrl}#application` }, tool: [{ "@type": "HowToTool", name: localized("Güncel bir web tarayıcısı", "A current web browser", "Ein aktueller Webbrowser", "现代网页浏览器") }], step: tool.steps[locale].map((text, index) => ({ "@type": "HowToStep", position: index + 1, name: localized(`${index + 1}. adım`, `Step ${index + 1}`, `Schritt ${index + 1}`, `第 ${index + 1} 步`), text, url: `${pageUrl}#how-to-step-${index + 1}` })) },
    { "@context": "https://schema.org", "@type": "FAQPage", "@id": `${pageUrl}#faq`, inLanguage: currentLanguage, mainEntity: faq.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) },
  ];
  return (
    <SiteShell locale={locale} alternateHref={alternateHref} languageHrefs={{ tr: toolPath("tr", tool.slug), en: toolPath("en", tool.slug), de: toolPath("de", tool.slug), zh: toolPath("zh", tool.slug) }}>
      <SchemaScript data={schema} />
      <ToolUsageTracker slug={tool.slug} />
      <div className="container page-top"><nav className="breadcrumbs" aria-label={localized("Sayfa yolu", "Breadcrumb", "Brotkrumen", "面包屑导航")}><Link href={pathFor(locale, "home")}>{localized("Ana sayfa", "Home", "Startseite", "首页")}</Link><span>/</span><Link href={pathFor(locale, "tools")}>{localized("Araçlar", "Tools", "Werkzeuge", "工具")}</Link><span>/</span><span>{tool.title[locale]}</span></nav></div>
      <section className="tool-hero"><div className="container"><div className="tool-title-row"><span className={`tool-mark tool-mark-xl category-${tool.category}`}>{tool.mark}</span><div><span className="kicker">{categories[tool.category].label[locale]}</span><h1>{tool.title[locale]}</h1><p>{tool.description[locale]}</p></div></div><div className="tool-assurances"><span>✓ {localized("Ücretsiz", "Free", "Kostenlos", "免费")}</span><span>✓ {localized("Üyelik yok", "No account", "Kein Konto", "无需账户")}</span><span>✓ {localized("Tarayıcı içinde", "In-browser", "Im Browser", "浏览器内")}</span></div></div></section>
      <section className="container tool-answer-card" data-tool-intent="specific" aria-labelledby="tool-answer-title">
        <div className="tool-answer-copy"><span className="kicker">{localized("KISA CEVAP", "QUICK ANSWER", "KURZANTWORT", "简短回答")}</span><h2 id="tool-answer-title">{localized("Bu araç ne yapar?", "What does this tool do?", "Was macht dieses Werkzeug?", "这个工具能做什么？")}</h2><p>{answer}</p></div>
        <dl><div><dt>{inputLabel}</dt><dd>{guidance.input[locale]}</dd></div><div><dt>{outputLabel}</dt><dd>{guidance.output[locale]}</dd></div><div><dt>{methodLabel}</dt><dd>{guidance.method[locale]}</dd></div><div><dt>{verifyLabel}</dt><dd>{guidance.verification[locale]}</dd></div></dl>
        <nav aria-label={localized("Araç içi hızlı bağlantılar", "Tool quick links", "Werkzeug-Schnelllinks", "工具快捷链接")}><a className="primary-button" href="#tool-workbench">{localized("Aracı kullan", "Use the tool", "Werkzeug nutzen", "使用工具")} →</a><a href="#how-to">{localized("Kullanım adımları", "Usage steps", "Anleitung", "使用步骤")}</a><a href="#tool-faq">FAQ</a></nav>
      </section>
      <div className="container" id="tool-workbench"><WorkspaceToolBridge slug={tool.slug} locale={locale} /><AgentToolBridge slug={tool.slug} locale={locale} /><ToolWorkbench slug={tool.slug} locale={locale} /><ToolExperience slug={tool.slug} locale={locale} compare={compareOutput} related={related.map((item) => ({ slug: item.slug, title: item.title[locale] }))} /></div>
      <section className="container tool-transparency" aria-label={localized("Araç veri ve yöntem özeti", "Tool data and method summary", "Daten- und Methodenübersicht", "工具数据与方法摘要")}>
        <article><span>01</span><div><strong>{localized("İşleme sınırı", "Processing boundary", "Verarbeitungsgrenze", "处理边界")}</strong><p>{localized("Girdi yalnızca etkin tarayıcı sekmesinin belleğinde işlenir; ByteQuant sunucusuna gönderilmez.", "Input is processed only in the active browser tab's memory and is not sent to a ByteQuant server.", "Eingaben werden nur im Speicher des aktiven Browser-Tabs verarbeitet und nicht an ByteQuant-Server gesendet.", "输入仅在当前浏览器标签页的内存中处理，不会发送到 ByteQuant 服务器。")}</p></div></article>
        <article><span>02</span><div><strong>{localized("Kalıcı depolama", "Persistent storage", "Dauerhafte Speicherung", "持久存储")}</strong><p>{localized("Girdi ve çıktı kaydedilmez. İsteğe bağlı kullanım sayacı içerik değil yalnızca araç kimliği ve sayısını tutar.", "Input and output are not stored. The optional usage counter keeps only tool identity and count, never content.", "Ein- und Ausgabe werden nicht gespeichert. Der optionale Zähler enthält nur Werkzeugkennung und Anzahl, niemals Inhalte.", "输入和输出不会被保存。可选使用计数器只保留工具标识和次数，不保存内容。")}</p></div></article>
        <article><span>03</span><div><strong>{localized("Doğrulama", "Verification", "Prüfung", "核验")}</strong><p>{localized("Sonuç açıklanan kurallar veya tarayıcı API'leriyle üretilir; yüksek etkili kullanım öncesinde bağımsız kontrol gerekir.", "Output comes from disclosed rules or browser APIs and needs independent review before high-impact use.", "Ausgaben stammen aus offengelegten Regeln oder Browser-APIs und müssen vor wichtiger Nutzung unabhängig geprüft werden.", "输出依据公开规则或浏览器 API 生成，在高影响使用前需要独立核验。")}</p></div></article>
      </section>
      <ToolEditorialReview tool={tool} locale={locale} />
      <section className="section tool-guide-section" id="how-to"><div className="container tool-guide-grid"><article><span className="kicker">{localized("NASIL KULLANILIR?", "HOW TO USE IT", "ANWENDUNG", "使用方法")}</span><h2>{localized("Üç adımda sonuç", "A result in three steps", "Ergebnis in drei Schritten", "三步获得结果")}</h2><ol className="numbered-list">{tool.steps[locale].map((step, index) => <li id={`how-to-step-${index + 1}`} key={step}><span>{String(index + 1).padStart(2, "0")}</span><p>{step}</p></li>)}</ol></article><article><span className="kicker">{localized("UYGUN SENARYOLAR", "GOOD USE CASES", "GEEIGNETE ANWENDUNGEN", "适用场景")}</span><h2>{localized("Bu araç ne zaman işe yarar?", "When is this tool useful?", "Wann ist dieses Werkzeug nützlich?", "该工具何时有用？")}</h2><ul className="check-list">{tool.useCases[locale].map((item) => <li key={item}>✓ <span>{item}</span></li>)}</ul><div className="limit-note"><strong>{localized("Önemli sınır", "Important limitation", "Wichtige Grenze", "重要限制")}</strong><p>{localized("Otomatik sonuç bir ön değerlendirmedir. Hukuki, finansal, tıbbi veya güvenlik açısından kritik kararlar için tek başına kullanılmamalıdır.", "Automated output is a preliminary assessment. Do not use it alone for legal, financial, medical, or security-critical decisions.", "Automatische Ausgaben sind Vorprüfungen und dürfen nicht allein für rechtliche, finanzielle, medizinische oder sicherheitskritische Entscheidungen verwendet werden.", "自动输出只是初步评估，不应单独用于法律、财务、医疗或安全关键决策。")}</p></div></article></div></section>
      {guideLinks.length > 0 && <section className="container tool-guide-links" data-guide-links="editorial"><div className="section-heading split-heading"><div><span className="kicker">{localized("DERİNLEŞTİRİN", "LEARN THE WORKFLOW", "ARBEITSABLAUF VERTIEFEN", "深入了解工作流")}</span><h2>{localized("Bu araçla ilgili rehberler", "Guides for this tool", "Ratgeber zu diesem Werkzeug", "该工具的相关指南")}</h2></div></div><div className="tool-guide-link-grid">{guideLinks.map((guide) => <article key={guide.slug}><span>{guide.category} · {guide.readTime}</span><h3><Link href={guide.href} hrefLang={guide.hrefLang}>{guide.title}</Link></h3><p>{guide.excerpt}</p><Link className="text-link" href={guide.href} hrefLang={guide.hrefLang}>{localized("Rehberi oku", "Read guide", guide.hrefLang === "de" ? "Ratgeber lesen" : "Englischen Ratgeber lesen", guide.hrefLang === "zh" ? "阅读指南" : "阅读英文指南")} →</Link></article>)}</div></section>}
      {relatedReference && relatedReferenceCopy && <section className="container tool-reference-link"><div><span className="kicker">{localized("HIZLI BAŞVURU", "QUICK REFERENCE", "SCHNELLREFERENZ", "快速参考")}</span><h2>{relatedReferenceCopy.title}</h2><p>{relatedReferenceCopy.description}</p></div><Link className="secondary-button" href={referencePath(locale, relatedReference.slug)} hrefLang={locale}>{localized("Cheat sheet’i aç", "Open cheat sheet", "Cheat-Sheet öffnen", "打开速查表")} →</Link></section>}
      <section className="section related-section"><div className="container"><div className="section-heading split-heading"><div><span className="kicker">{localized("BU ARAÇLA SIK KULLANILANLAR", "FREQUENTLY USED TOGETHER", "HÄUFIG ZUSAMMEN VERWENDET", "常用搭配工具")}</span><h2>{localized("Bunu şimdi şununla da işleyebilirsiniz", "Process the result with one of these next", "Ergebnis als Nächstes hier weiterverarbeiten", "接下来可用这些工具继续处理")}</h2></div><Link className="text-link" href={pathFor(locale, "tools")}>{localized(`${tools.length} aracın tamamı`, `All ${tools.length} tools`, `Alle ${tools.length} Werkzeuge`, `全部 ${tools.length} 个工具`)} →</Link></div><div className="tool-grid">{related.map((item) => <ToolCard key={item.slug} tool={item} locale={locale} />)}</div></div></section>
      <section className="section compact-faq" id="tool-faq"><div className="container"><div className="section-heading centered"><span className="kicker">{localized("ARAÇ HAKKINDA", "ABOUT THIS TOOL", "ÜBER DIESES WERKZEUG", "关于此工具")}</span><h2>{localized("Sık sorulan sorular", "Frequently asked questions", "Häufig gestellte Fragen", "常见问题")}</h2></div><div className="faq-list narrow">{faq.map(([question, answer]) => <details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></div></section>
    </SiteShell>
  );
}
