import Link from "next/link";
import { categories, getRelatedTools, tools, type Tool } from "../lib/tools";
import { absoluteUrl, languageTag, organizationId, pathFor, postPath, schemaDate, toolPath, websiteId, type Locale } from "../lib/site";
import { AdSlot } from "./AdSlot";
import { SchemaScript } from "./SchemaScript";
import { SiteShell } from "./SiteShell";
import { ToolCard } from "./ToolCard";
import { ToolUsageTracker } from "./ToolUsage";
import { ToolWorkbench } from "./ToolWorkbench";
import { referenceCopy, referencePath, references } from "../lib/references";
import { posts } from "../lib/posts";
import { localizedGuides } from "../lib/localized-guides";
import { AgentToolBridge } from "./AgentToolBridge";
import { WorkspaceToolBridge } from "./WorkspaceToolBridge";
import { ToolExperience } from "./ToolExperience";

export function ToolPage({ tool, locale }: { tool: Tool; locale: Locale }) {
  const editorialLocale = locale === "tr" ? "tr" : "en";
  const localized = (tr: string, en: string, de: string, zh: string) => ({ tr, en, de, zh })[locale];
  const currentLanguage = languageTag(locale);
  const pageUrl = absoluteUrl(toolPath(locale, tool.slug));
  const alternateHref = toolPath(locale === "tr" ? "en" : "tr", tool.slug);
  const related = getRelatedTools(tool);
  const compareOutput = (["text", "data", "converter", "security"] as const).includes(tool.category as "text" | "data" | "converter" | "security");
  const relatedReference = references.find((guide) => guide.toolSlug === tool.slug);
  const relatedReferenceCopy = relatedReference ? referenceCopy(relatedReference, locale) : null;
  const relatedPosts = posts.filter((post) => post.relatedTools.includes(tool.slug)).slice(-2).reverse();
  const guideLinks = locale === "de" || locale === "zh"
    ? [...localizedGuides.filter((guide) => guide.relatedTools.includes(tool.slug)).map((guide) => ({ slug: guide.slug, category: guide.copy[locale].category, readTime: guide.copy[locale].readTime, title: guide.copy[locale].title, excerpt: guide.copy[locale].excerpt, href: postPath(locale, guide.slug), hrefLang: locale })), ...relatedPosts.filter((post) => !localizedGuides.some((guide) => guide.slug === post.slug)).map((post) => ({ slug: post.slug, category: post.category.en, readTime: post.readTime.en, title: post.title.en, excerpt: post.excerpt.en, href: postPath("en", post.slug), hrefLang: "en" }))].slice(0, 2)
    : relatedPosts.map((post) => ({ slug: post.slug, category: post.category[editorialLocale], readTime: post.readTime[editorialLocale], title: post.title[editorialLocale], excerpt: post.excerpt[editorialLocale], href: postPath(editorialLocale, post.slug), hrefLang: editorialLocale }));
  const faq = [
    [localized("Bu araç verimi bir sunucuya gönderiyor mu?", "Does this tool send input to a server?", "Sendet dieses Werkzeug Eingaben an einen Server?", "该工具会把输入发送到服务器吗？"), localized("Hayır. İşlem bu tarayıcı sekmesinde çalışır. Sonucu kopyalamayı veya indirmeyi seçerseniz veri sayfanın dışına sizin işleminizle çıkar.", "No. Processing runs in this browser tab. Data leaves the page only when you choose to copy or download the result.", "Nein. Die Verarbeitung läuft in diesem Browser-Tab. Daten verlassen die Seite nur, wenn Sie ein Ergebnis kopieren oder herunterladen.", "不会。处理在当前浏览器标签页中运行。只有当您复制或下载结果时，数据才会因您的操作离开页面。")],
    [localized("Sonuç kesin midir?", "Is the result definitive?", "Ist das Ergebnis verbindlich?", "结果是确定且权威的吗？"), localized("Araç açıklanan kurallar ve tarayıcı API'leriyle tutarlı sonuç üretir; bağlama, veri kalitesine ve yöntem sınırlarına bağlı hatalar olabilir. Kritik kararları ayrıca doğrulayın.", "The tool produces consistent output from disclosed rules and browser APIs, but context, data quality, and method limitations can affect it. Verify high-impact decisions.", "Das Werkzeug arbeitet nach offengelegten Regeln und Browser-APIs. Kontext, Datenqualität und Methodengrenzen können das Ergebnis beeinflussen; wichtige Entscheidungen müssen separat geprüft werden.", "工具依据公开规则和浏览器 API 生成结果，但语境、数据质量和方法限制都可能影响结果。重要决策请另行核验。")],
    [localized("Girdi kaydediliyor mu?", "Is input saved?", "Werden Eingaben gespeichert?", "输入会被保存吗？"), localized("Hayır. Araç girdisi kalıcı alanda saklanmaz. Açık rıza verirseniz yalnızca araç kimliği ve kullanım sayısı kişisel kısa yollar için bu cihazda tutulabilir.", "No. Tool input is not persisted. With consent, only tool identity and usage count may be kept on this device for personal shortcuts.", "Nein. Werkzeugeingaben werden nicht dauerhaft gespeichert. Mit Einwilligung können nur Werkzeugkennung und Nutzungszahl für lokale Abkürzungen gespeichert werden.", "不会。工具输入不会持久保存。经同意后，仅工具标识和使用次数可为本地快捷方式保存在本设备。")],
  ];
  const schema = [
    { "@context": "https://schema.org", "@type": "WebApplication", "@id": `${pageUrl}#application`, name: tool.title[locale], description: tool.description[locale], url: pageUrl, applicationCategory: "UtilitiesApplication", operatingSystem: "Any current standards-based browser", browserRequirements: "JavaScript enabled; secure context required for Web Crypto and PWA installation", inLanguage: currentLanguage, isAccessibleForFree: true, dateModified: schemaDate("2026-07-21"), featureList: tool.useCases[locale], offers: { "@type": "Offer", price: "0", priceCurrency: "USD" }, creator: { "@id": organizationId }, isPartOf: { "@id": websiteId }, privacyPolicy: absoluteUrl(pathFor(locale, "privacy")) },
    { "@context": "https://schema.org", "@type": "BreadcrumbList", "@id": `${pageUrl}#breadcrumb`, itemListElement: [{ "@type": "ListItem", position: 1, name: localized("Ana sayfa", "Home", "Startseite", "首页"), item: absoluteUrl(pathFor(locale, "home")) }, { "@type": "ListItem", position: 2, name: localized("Araçlar", "Tools", "Werkzeuge", "工具"), item: absoluteUrl(pathFor(locale, "tools")) }, { "@type": "ListItem", position: 3, name: tool.title[locale], item: pageUrl }] },
    { "@context": "https://schema.org", "@type": "HowTo", "@id": `${pageUrl}#how-to`, name: localized(`${tool.title[locale]} nasıl kullanılır?`, `How to use ${tool.title[locale]}`, `${tool.title[locale]} verwenden`, `如何使用${tool.title[locale]}`), description: tool.short[locale], totalTime: "PT3M", inLanguage: currentLanguage, isPartOf: { "@id": `${pageUrl}#application` }, tool: [{ "@type": "HowToTool", name: localized("Güncel bir web tarayıcısı", "A current web browser", "Ein aktueller Webbrowser", "现代网页浏览器") }], step: tool.steps[locale].map((text, index) => ({ "@type": "HowToStep", position: index + 1, name: localized(`${index + 1}. adım`, `Step ${index + 1}`, `Schritt ${index + 1}`, `第 ${index + 1} 步`), text, url: `${pageUrl}#how-to-step-${index + 1}` })) },
    { "@context": "https://schema.org", "@type": "FAQPage", "@id": `${pageUrl}#faq`, inLanguage: currentLanguage, mainEntity: faq.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) },
  ];
  return (
    <SiteShell locale={locale} alternateHref={alternateHref} languageHrefs={{ tr: toolPath("tr", tool.slug), en: toolPath("en", tool.slug), de: toolPath("de", tool.slug), zh: toolPath("zh", tool.slug) }}>
      <SchemaScript data={schema} />
      <ToolUsageTracker slug={tool.slug} />
      <div className="container page-top"><nav className="breadcrumbs" aria-label={localized("Sayfa yolu", "Breadcrumb", "Brotkrumen", "面包屑导航")}><Link href={pathFor(locale, "home")}>{localized("Ana sayfa", "Home", "Startseite", "首页")}</Link><span>/</span><Link href={pathFor(locale, "tools")}>{localized("Araçlar", "Tools", "Werkzeuge", "工具")}</Link><span>/</span><span>{tool.title[locale]}</span></nav></div>
      <section className="tool-hero"><div className="container"><div className="tool-title-row"><span className={`tool-mark tool-mark-xl category-${tool.category}`}>{tool.mark}</span><div><span className="kicker">{categories[tool.category].label[locale]}</span><h1>{tool.title[locale]}</h1><p>{tool.description[locale]}</p></div></div><div className="tool-assurances"><span>✓ {localized("Ücretsiz", "Free", "Kostenlos", "免费")}</span><span>✓ {localized("Üyelik yok", "No account", "Kein Konto", "无需账户")}</span><span>✓ {localized("Tarayıcı içinde", "In-browser", "Im Browser", "浏览器内")}</span></div></div></section>
      <div className="container"><WorkspaceToolBridge slug={tool.slug} locale={locale} /><AgentToolBridge slug={tool.slug} locale={locale} /><ToolWorkbench slug={tool.slug} locale={locale} /><ToolExperience slug={tool.slug} locale={locale} compare={compareOutput} related={related.map((item) => ({ slug: item.slug, title: item.title[locale] }))} /></div>
      <section className="container tool-transparency" aria-label={localized("Araç veri ve yöntem özeti", "Tool data and method summary", "Daten- und Methodenübersicht", "工具数据与方法摘要")}>
        <article><span>01</span><div><strong>{localized("İşleme sınırı", "Processing boundary", "Verarbeitungsgrenze", "处理边界")}</strong><p>{localized("Girdi yalnızca etkin tarayıcı sekmesinin belleğinde işlenir; ByteQuant sunucusuna gönderilmez.", "Input is processed only in the active browser tab's memory and is not sent to a ByteQuant server.", "Eingaben werden nur im Speicher des aktiven Browser-Tabs verarbeitet und nicht an ByteQuant-Server gesendet.", "输入仅在当前浏览器标签页的内存中处理，不会发送到 ByteQuant 服务器。")}</p></div></article>
        <article><span>02</span><div><strong>{localized("Kalıcı depolama", "Persistent storage", "Dauerhafte Speicherung", "持久存储")}</strong><p>{localized("Girdi ve çıktı kaydedilmez. İsteğe bağlı kullanım sayacı içerik değil yalnızca araç kimliği ve sayısını tutar.", "Input and output are not stored. The optional usage counter keeps only tool identity and count, never content.", "Ein- und Ausgabe werden nicht gespeichert. Der optionale Zähler enthält nur Werkzeugkennung und Anzahl, niemals Inhalte.", "输入和输出不会被保存。可选使用计数器只保留工具标识和次数，不保存内容。")}</p></div></article>
        <article><span>03</span><div><strong>{localized("Doğrulama", "Verification", "Prüfung", "核验")}</strong><p>{localized("Sonuç açıklanan kurallar veya tarayıcı API'leriyle üretilir; yüksek etkili kullanım öncesinde bağımsız kontrol gerekir.", "Output comes from disclosed rules or browser APIs and needs independent review before high-impact use.", "Ausgaben stammen aus offengelegten Regeln oder Browser-APIs und müssen vor wichtiger Nutzung unabhängig geprüft werden.", "输出依据公开规则或浏览器 API 生成，在高影响使用前需要独立核验。")}</p></div></article>
      </section>
      <section className="section tool-guide-section"><div className="container tool-guide-grid"><article><span className="kicker">{localized("NASIL KULLANILIR?", "HOW TO USE IT", "ANWENDUNG", "使用方法")}</span><h2>{localized("Üç adımda sonuç", "A result in three steps", "Ergebnis in drei Schritten", "三步获得结果")}</h2><ol className="numbered-list">{tool.steps[locale].map((step, index) => <li id={`how-to-step-${index + 1}`} key={step}><span>{String(index + 1).padStart(2, "0")}</span><p>{step}</p></li>)}</ol></article><article><span className="kicker">{localized("UYGUN SENARYOLAR", "GOOD USE CASES", "GEEIGNETE ANWENDUNGEN", "适用场景")}</span><h2>{localized("Bu araç ne zaman işe yarar?", "When is this tool useful?", "Wann ist dieses Werkzeug nützlich?", "该工具何时有用？")}</h2><ul className="check-list">{tool.useCases[locale].map((item) => <li key={item}>✓ <span>{item}</span></li>)}</ul><div className="limit-note"><strong>{localized("Önemli sınır", "Important limitation", "Wichtige Grenze", "重要限制")}</strong><p>{localized("Otomatik sonuç bir ön değerlendirmedir. Hukuki, finansal, tıbbi veya güvenlik açısından kritik kararlar için tek başına kullanılmamalıdır.", "Automated output is a preliminary assessment. Do not use it alone for legal, financial, medical, or security-critical decisions.", "Automatische Ausgaben sind Vorprüfungen und dürfen nicht allein für rechtliche, finanzielle, medizinische oder sicherheitskritische Entscheidungen verwendet werden.", "自动输出只是初步评估，不应单独用于法律、财务、医疗或安全关键决策。")}</p></div></article></div></section>
      <div className="container"><AdSlot locale={locale} /></div>
      {guideLinks.length > 0 && <section className="container tool-guide-links"><div className="section-heading split-heading"><div><span className="kicker">{localized("DERİNLEŞTİRİN", "LEARN THE WORKFLOW", "ARBEITSABLAUF VERTIEFEN", "深入了解工作流")}</span><h2>{localized("Bu araçla ilgili rehberler", "Guides for this tool", "Ratgeber zu diesem Werkzeug", "该工具的相关指南")}</h2></div></div><div className="tool-guide-link-grid">{guideLinks.map((guide) => <article key={guide.slug}><span>{guide.category} · {guide.readTime}</span><h3><Link href={guide.href} hrefLang={guide.hrefLang}>{guide.title}</Link></h3><p>{guide.excerpt}</p><Link className="text-link" href={guide.href} hrefLang={guide.hrefLang}>{localized("Rehberi oku", "Read guide", guide.hrefLang === "de" ? "Ratgeber lesen" : "Englischen Ratgeber lesen", guide.hrefLang === "zh" ? "阅读指南" : "阅读英文指南")} →</Link></article>)}</div></section>}
      {relatedReference && relatedReferenceCopy && <section className="container tool-reference-link"><div><span className="kicker">{localized("HIZLI BAŞVURU", "QUICK REFERENCE", "SCHNELLREFERENZ", "快速参考")}</span><h2>{relatedReferenceCopy.title}</h2><p>{relatedReferenceCopy.description}</p></div><Link className="secondary-button" href={referencePath(locale, relatedReference.slug)} hrefLang={locale}>{localized("Cheat sheet’i aç", "Open cheat sheet", "Cheat-Sheet öffnen", "打开速查表")} →</Link></section>}
      <section className="section related-section"><div className="container"><div className="section-heading split-heading"><div><span className="kicker">{localized("BU ARAÇLA SIK KULLANILANLAR", "FREQUENTLY USED TOGETHER", "HÄUFIG ZUSAMMEN VERWENDET", "常用搭配工具")}</span><h2>{localized("Bunu şimdi şununla da işleyebilirsiniz", "Process the result with one of these next", "Ergebnis als Nächstes hier weiterverarbeiten", "接下来可用这些工具继续处理")}</h2></div><Link className="text-link" href={pathFor(locale, "tools")}>{localized(`${tools.length} aracın tamamı`, `All ${tools.length} tools`, `Alle ${tools.length} Werkzeuge`, `全部 ${tools.length} 个工具`)} →</Link></div><div className="tool-grid">{related.map((item) => <ToolCard key={item.slug} tool={item} locale={locale} />)}</div></div></section>
      <section className="section compact-faq"><div className="container"><div className="section-heading centered"><span className="kicker">{localized("ARAÇ HAKKINDA", "ABOUT THIS TOOL", "ÜBER DIESES WERKZEUG", "关于此工具")}</span><h2>{localized("Sık sorulan sorular", "Frequently asked questions", "Häufig gestellte Fragen", "常见问题")}</h2></div><div className="faq-list narrow">{faq.map(([question, answer]) => <details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></div></section>
    </SiteShell>
  );
}
