import Link from "next/link";
import { absoluteUrl, languageTag, organizationId, pathFor, siteUrl, websiteId, type Locale } from "../lib/site";
import { SchemaScript } from "./SchemaScript";
import { SiteShell } from "./SiteShell";
import { WorkstationLoader } from "./WorkstationLoader";

const content = {
  tr: {
    eyebrow: "GÖRSEL AKIŞ · ŞİFRELİ PROJELER · SUNUCUSUZ P2P", title: "89 tarayıcı aracını görsel bir geliştirme ortamında birbirine bağlayın",
    intro: "ByteQuant İş İstasyonu; araçları düğüm olarak düzenler, çıktıyı bağlı girdiye taşır, projeleri cihazınızda AES-GCM ile şifreler ve tarifleri veritabanı olmadan paylaşır.",
    cta: "İş istasyonunu aç", badges: ["İlk yükte ağır canvas kodu yok", "IndexedDB + Web Crypto", "WebRTC DataChannel"],
    sectionTitle: "Bir üst katman; mevcut araçlara dokunmadan", sectionIntro: "Araçların çekirdek davranışları aynen korunur. İş istasyonu keşif, düzenleme, veri aktarımı ve yerel kalıcılığı koordine eder; her araç çalıştırma adımı yine kullanıcı eylemi ister.",
    cards: [["01", "Düğümleri kurun", "Araçları arayın veya kategoriyle filtreleyin; mobilde Projeler, Araçlar, Tuval ve Denetçi kısayollarıyla bölümler arasında geçin, sonra portları görsel kabloyla bağlayın."], ["02", "Ajan planını denetleyin", "Yerel Ajanın güven puanını, seçim gerekçelerini ve adımlarını tuvale eklemeden önce inceleyin."], ["03", "Şifreli kaydedin", "Projeler ve girdiler, dış veritabanı olmadan cihazdaki IndexedDB kasasında tutulur."], ["04", "Doğrulayıp paylaşın", "10 dakikalık P2P kodunu, karşılıklı güvenlik kodunu ve ayrı canlı paylaşım onayını kullanın."]],
    boundariesTitle: "Sunucusuz mimarinin dürüst sınırları", boundaries: ["P2P kodları 10 dakika içinde geçersiz olur; bağlantıdan sonra güvenlik kodu ayrı bir kanalda karşılaştırılmadan canlı paylaşım açılamaz.", "Bazı NAT ve firewall kombinasyonları aynı yerel ağ dışında bağlantıyı engeller. ByteQuant bunu aşmak için gizli bir sunucuya geri dönmez.", "URL tarifleri varsayılan olarak girdileri ve her zaman çıktıları çıkarır. Girdiyi bağlantıya eklemek açık kullanıcı seçimi gerektirir.", "IndexedDB kayıtları AES-GCM ile şifrelidir; bu, ele geçirilmiş cihaz veya aynı origin'de çalışan zararlı kod için tam güvenlik garantisi değildir."],
    faq: [["React Flow veya başka bir kütüphane kullanılıyor mu?", "Hayır. Canvas, hafif HTML/SVG ve Pointer Events ile çalışır; yeni üçüncü taraf bağımlılık eklenmez."], ["P2P güvenlik kodu kimlik doğrulaması mı?", "Hayır. Kod iki DTLS parmak izinin aynı oturuma ait olduğunu karşılaştırmaya yardım eder; kişinin gerçek kimliğini kanıtlamaz. Kod ayrı kanalda eşleştirilmeden canlı paylaşım açılamaz."], ["Projeler buluta yazılıyor mu?", "Hayır. Şifreli proje kayıtları yalnızca tarayıcınızın IndexedDB alanındadır ve bu cihazdan otomatik çıkmaz."], ["Yerel Ajan araçları kendi başına çalıştırır mı?", "Hayır. Ajan plan güvenini ve gerekçesini gösterir; dosya seçme, araç çalıştırma, indirme ve sonuç kabulü kullanıcı eylemi gerektirir."]],
  },
  en: {
    eyebrow: "VISUAL FLOWS · ENCRYPTED PROJECTS · SERVERLESS P2P", title: "Connect 89 browser tools inside a visual development environment",
    intro: "ByteQuant Workstation arranges tools as nodes, passes output to connected input, encrypts projects on-device with AES-GCM, and shares recipes without a database.",
    cta: "Open the workstation", badges: ["No heavy canvas code on first load", "IndexedDB + Web Crypto", "WebRTC DataChannel"],
    sectionTitle: "A coordination layer that leaves every tool intact", sectionIntro: "Core tool behavior remains unchanged. Workstation coordinates discovery, layout, handoff, and local persistence; every tool run still requires user action.",
    cards: [["01", "Build nodes", "Search or filter the tool palette; on mobile, jump among Projects, Tools, Canvas, and Inspector before connecting ports with visual wires."], ["02", "Review the agent plan", "Inspect confidence, selection reasons, and steps before adding a local plan to the canvas."], ["03", "Save encrypted", "Projects and inputs stay in an IndexedDB vault with no external database."], ["04", "Verify before sharing", "Use a 10-minute P2P code, compare the mutual safety code, and enable live sharing separately."]],
    boundariesTitle: "Honest boundaries of a serverless architecture", boundaries: ["P2P codes expire after 10 minutes; live sharing stays locked until people compare the safety code through another channel.", "Some NAT and firewall combinations cannot connect outside the same local network. ByteQuant never hides that with a server fallback.", "URL recipes exclude inputs by default and always exclude output. Including input requires an explicit user choice.", "IndexedDB records use AES-GCM at rest; this cannot guarantee safety on a compromised device or against malicious same-origin code."],
    faq: [["Does this use React Flow or another library?", "No. The canvas uses lightweight HTML/SVG and Pointer Events, adding no third-party dependency."], ["Is the P2P safety code identity verification?", "No. It helps compare that both DTLS fingerprints belong to the same session; it does not prove a person's identity. Live sharing stays locked until the code is compared through another channel."], ["Do projects go to the cloud?", "No. Encrypted records stay only in this browser's IndexedDB and never leave automatically."], ["Can Local Agent run tools autonomously?", "No. It shows plan confidence and selection reasons; file selection, execution, downloads, and result acceptance require user action."]],
  },
  de: {
    eyebrow: "VISUELLE ABLÄUFE · VERSCHLÜSSELTE PROJEKTE · SERVERLOSES P2P", title: "89 Browser-Werkzeuge in einer visuellen Entwicklungsumgebung verbinden",
    intro: "ByteQuant Workstation ordnet Werkzeuge als Knoten an, übergibt Ausgaben an verbundene Eingaben, verschlüsselt Projekte lokal mit AES-GCM und teilt Rezepte ohne Datenbank.",
    cta: "Workstation öffnen", badges: ["Kein schwerer Canvas-Code beim Erstaufruf", "IndexedDB + Web Crypto", "WebRTC DataChannel"],
    sectionTitle: "Eine Koordinationsebene, die alle Werkzeuge erhält", sectionIntro: "Die Kernfunktionen bleiben unverändert. Die Workstation koordiniert Suche, Anordnung, Übergabe und lokale Speicherung; jeder Werkzeugstart erfordert weiterhin eine Nutzeraktion.",
    cards: [["01", "Knoten erstellen", "Werkzeuge suchen oder filtern; mobil über Projekte, Werkzeuge, Fläche und Prüfung navigieren und anschließend Ein-/Ausgänge verbinden."], ["02", "Agentenplan prüfen", "Konfidenz, Auswahlgründe und Schritte vor dem Einfügen in die Fläche kontrollieren."], ["03", "Verschlüsselt speichern", "Projekte und Eingaben bleiben in einem IndexedDB-Tresor ohne externe Datenbank."], ["04", "Vor Freigabe verifizieren", "10-Minuten-Code verwenden, Sicherheitscode vergleichen und Live-Freigabe getrennt aktivieren."]],
    boundariesTitle: "Ehrliche Grenzen der serverlosen Architektur", boundaries: ["P2P-Codes verfallen nach 10 Minuten; die Live-Freigabe bleibt gesperrt, bis der Sicherheitscode über einen zweiten Kanal verglichen wurde.", "Manche NAT-/Firewall-Kombinationen verhindern Verbindungen außerhalb desselben LAN. Es gibt keinen versteckten Server-Fallback.", "URL-Rezepte schließen Eingaben standardmäßig und Ausgaben immer aus.", "AES-GCM schützt IndexedDB-Daten im Ruhezustand, garantiert aber keinen Schutz auf kompromittierten Geräten oder vor bösartigem Same-Origin-Code."],
    faq: [["Wird React Flow verwendet?", "Nein. Die Oberfläche nutzt leichtes HTML/SVG und Pointer Events ohne neue Drittanbieterabhängigkeit."], ["Ist der P2P-Sicherheitscode eine Identitätsprüfung?", "Nein. Er hilft beim Vergleich beider DTLS-Fingerprints derselben Sitzung, beweist aber keine reale Person. Ohne Vergleich über einen zweiten Kanal bleibt die Freigabe gesperrt."], ["Werden Projekte in die Cloud geschrieben?", "Nein. Verschlüsselte Einträge bleiben ausschließlich im IndexedDB dieses Browsers."], ["Startet der lokale Agent Werkzeuge selbstständig?", "Nein. Er zeigt Konfidenz und Auswahlgründe; Auswahl, Ausführung und Übernahme bleiben Nutzeraktionen."]],
  },
  zh: {
    eyebrow: "可视化流程 · 加密项目 · 无服务器 P2P", title: "在可视化开发环境中连接 89 个浏览器工具",
    intro: "ByteQuant 工作站把工具排列为节点，将输出传给相连输入，使用 AES-GCM 在设备上加密项目，并在无数据库的情况下分享配方。",
    cta: "打开工作站", badges: ["首屏不加载重型画布代码", "IndexedDB + Web Crypto", "WebRTC DataChannel"],
    sectionTitle: "保留全部工具的协调层", sectionIntro: "工具核心行为保持不变。工作站只协调发现、布局、交接和本地持久化；每次运行仍需用户操作。",
    cards: [["01", "建立节点", "搜索或筛选工具；在移动端通过项目、工具、画布和检查器快捷导航，再连接输入输出端口。"], ["02", "审查助手计划", "在加入画布前查看置信度、选择理由与每个步骤。"], ["03", "加密保存", "项目和输入保存在 IndexedDB 加密库中，不使用外部数据库。"], ["04", "验证后共享", "使用 10 分钟 P2P 代码、核对双方安全码，并单独开启实时共享。"]],
    boundariesTitle: "无服务器架构的真实边界", boundaries: ["P2P 代码 10 分钟后失效；双方通过另一渠道核对安全码之前，实时共享保持锁定。", "部分 NAT/防火墙组合无法在同一局域网之外连接；ByteQuant 不会偷偷回退到服务器。", "URL 配方默认排除输入，并始终排除输出；加入输入必须明确选择。", "IndexedDB 记录使用 AES-GCM 静态加密，但无法保证受感染设备或恶意同源代码下的安全。"],
    faq: [["是否使用 React Flow？", "否。画布使用轻量 HTML/SVG 和 Pointer Events，不增加第三方依赖。"], ["P2P 安全码等于身份验证吗？", "不等于。它帮助核对双方 DTLS 指纹属于同一会话，但不能证明真实身份；通过另一渠道核对之前，实时共享保持锁定。"], ["项目会写入云端吗？", "不会。加密记录只保存在此浏览器的 IndexedDB。"], ["本地助手会自动运行工具吗？", "不会。它显示计划置信度与选择理由；文件选择、运行、下载和结果确认都需要用户操作。"]],
  },
} as const;

export function WorkstationPage({ locale, importer = false }: { locale: Locale; importer?: boolean }) {
  const c = content[locale];
  const pagePath = importer ? "/workspace" : pathFor(locale, "workstation");
  const pageUrl = absoluteUrl(pagePath);
  const schema = importer ? [] : [
    { "@context": "https://schema.org", "@type": "WebApplication", "@id": `${pageUrl}#application`, name: `ByteQuant ${locale === "tr" ? "İş İstasyonu" : "Workstation"}`, url: pageUrl, description: c.intro, applicationCategory: "DeveloperApplication", operatingSystem: "Any modern browser", browserRequirements: "JavaScript, IndexedDB, Web Crypto; WebRTC optional", inLanguage: languageTag(locale), isAccessibleForFree: true, creator: { "@id": organizationId }, isPartOf: { "@id": websiteId }, featureList: c.cards.map((card) => card[1]), offers: { "@type": "Offer", price: "0", priceCurrency: "USD" } },
    { "@context": "https://schema.org", "@type": "HowTo", name: c.title, totalTime: "PT5M", inLanguage: languageTag(locale), step: c.cards.map((card, index) => ({ "@type": "HowToStep", position: index + 1, name: card[1], text: card[2], url: `${pageUrl}#step-${index + 1}` })) },
    { "@context": "https://schema.org", "@type": "FAQPage", inLanguage: languageTag(locale), mainEntity: c.faq.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) },
    { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: locale === "tr" ? "Ana sayfa" : "Home", item: absoluteUrl(pathFor(locale, "home")) }, { "@type": "ListItem", position: 2, name: c.title, item: pageUrl }] },
  ];
  return <SiteShell locale={locale} alternateHref={pathFor(locale === "tr" ? "en" : "tr", "workstation")} languageHrefs={{ tr: pathFor("tr", "workstation"), en: pathFor("en", "workstation"), de: pathFor("de", "workstation"), zh: pathFor("zh", "workstation") }}>
    {schema.length > 0 && <SchemaScript data={schema} />}
    <section className="workstation-hero"><div className="container workstation-hero-grid"><div><span className="eyebrow"><i />{c.eyebrow}</span><h1>{c.title}</h1><p>{c.intro}</p><div className="workstation-badges">{c.badges.map((badge) => <span key={badge}>✓ {badge}</span>)}</div><a className="primary-button" href="#workstation-app">{c.cta} →</a></div><div className="workstation-hero-visual" aria-hidden="true"><span className="hero-node n1">JSON</span><span className="hero-node n2">MASK</span><span className="hero-node n3">CSV</span><i className="hero-wire w1" /><i className="hero-wire w2" /><b>BQ<br /><small>IDE</small></b></div></div></section>
    <section className="section workstation-explain"><div className="container"><div className="section-heading split-heading"><div><span className="kicker">BYTEQUANT WORKSTATION</span><h2>{c.sectionTitle}</h2></div><p>{c.sectionIntro}</p></div><div className="workstation-feature-grid">{c.cards.map((card, index) => <article id={`step-${index + 1}`} key={card[0]}><span>{card[0]}</span><h3>{card[1]}</h3><p>{card[2]}</p></article>)}</div></div></section>
    <section id="workstation-app" className="workstation-app-section"><div className="container workstation-app-container"><WorkstationLoader locale={locale} /></div></section>
    <section className="section workstation-boundaries"><div className="container workstation-boundary-grid"><div><span className="kicker">TRUST BOUNDARY</span><h2>{c.boundariesTitle}</h2><p>{c.intro}</p><Link className="text-link" href={pathFor(locale, "privacy")}>{locale === "tr" ? "Gizlilik politikasını inceleyin" : locale === "de" ? "Datenschutz lesen" : locale === "zh" ? "阅读隐私政策" : "Read the privacy policy"} →</Link></div><ol>{c.boundaries.map((boundary, index) => <li key={boundary}><span>{String(index + 1).padStart(2, "0")}</span><p>{boundary}</p></li>)}</ol></div></section>
    <section className="section faq-section"><div className="container faq-layout"><div><span className="kicker">FAQ</span><h2>{locale === "tr" ? "İş istasyonu hakkında" : locale === "de" ? "Über die Workstation" : locale === "zh" ? "关于工作站" : "About Workstation"}</h2><p>{c.sectionIntro}</p></div><div className="faq-list">{c.faq.map(([question, answer], index) => <details key={question} open={index === 0}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></div></section>
    <section className="cta-band"><div className="container"><div><span>{siteUrl.replace("https://", "").toUpperCase()} · LOCAL-FIRST</span><h2>{c.title}</h2></div><a className="light-button" href="#workstation-app">{c.cta} →</a></div></section>
  </SiteShell>;
}
