"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { createAgentPlan, type AgentPlan } from "../lib/agent-core";
import { AGENT_VERSION, readAgentPlan } from "../lib/agent-session";
import { WORKSPACE_ACTIVE_KEY, WORKSPACE_AGENT_GOAL_KEY, WORKSPACE_AGENT_INPUT_KEY, WORKSPACE_AGENT_PLAN_KEY, WORKSPACE_HANDOFF_KEY, WORKSPACE_TOOL_START_KEY, readActiveWorkspace, readWorkspaceAgentGoal, readWorkspaceAgentInput, readWorkspaceHandoff, readWorkspaceToolStart } from "../lib/workspace-handoff";
import { createWorkspaceRecipe } from "../lib/workspace-recipe";
import { deleteWorkspace, listWorkspaces, loadWorkspace, requestPersistentWorkspaceStorage, saveWorkspace, type WorkspaceSummary } from "../lib/workspace-storage";
import { decodeRecipeInWorker, encodeRecipeInWorker } from "../lib/workspace-worker-client";
import { WORKSPACE_MAX_NODES, createWorkspace, documentFromRecipe, layoutWorkspaceGraph, propagateWorkspaceOutput, updateWorkspace, workspaceGraphSummary, workspaceId, type WorkspaceDocument, type WorkspaceNode } from "../lib/workspace-types";
import { categories, publicTools, tools, type ToolCategory } from "../lib/tools";
import { pathFor, toolPath, type Locale } from "../lib/site";
import { WorkspaceP2PPanel } from "./WorkspaceP2PPanel";

const uiCopy = {
  tr: { title: "ByteQuant İş İstasyonu", saved: "Bu cihazda şifreli", saving: "Şifreli kayıt hazırlanıyor…", saveError: "Çalışma alanı kaydedilemedi. Depolama kotasını veya özel gezinme ayarını kontrol edin.", projects: "Projeler", newProject: "Yeni proje", delete: "Sil", persist: "Kalıcı depolama", persisted: "Tarayıcı kalıcı depolamayı onayladı.", palette: "Araç paleti", search: "{count} araçta ara", category: "Tüm kategoriler", drag: "Sürükleyin veya Ekle düğmesini kullanın.", add: "Ekle", showAll: "Tüm araçları göster", showLess: "Listeyi daralt", canvas: "Görsel akış tuvali", empty: "Bir şablon seçin veya ilk düğümü araç paletinden ekleyin.", connect: "Çıkış portunu, ardından hedef giriş portunu seçin.", max: "Güvenli düğüm sınırına ulaşıldı.", inspector: "Düğüm denetçisi", input: "Girdi", output: "Son çıktı", open: "Araçta çalıştır", remove: "Düğümü kaldır", select: "Düzenlemek için bir düğüm seçin.", ai: "Hızlı akış planlayıcı", aiPlaceholder: "Örn. JSON'u doğrula, hassas alanları maskele ve CSV'ye dönüştür", analyze: "Hızlı planı hazırla", addPlan: "Planı tuvale ekle", replacePlan: "Tuvali planla değiştir", aiBoundary: "Cihazdaki hızlı kural eşleştirmesini kullanır. Açık uçlu sohbet ve daha derin planlama için Yerel Ajanı açın.", decision: "Karar önizlemesi", confidence: "eşleşme", share: "URL tarifi", include: "Girdileri bağlantıya dahil et", createLink: "Paylaşım bağlantısı üret", copy: "Bağlantıyı kopyala", shareSafe: "Çıktılar URL'ye eklenmez; girdiler varsayılan olarak çıkarılır.", imported: "Paylaşılan tarif yeni bir cihaz içi proje olarak kuruldu.", importError: "Tarif okunamadı veya güvenli boyut sınırını aşıyor.", flow: "bağlantı", restored: "Araç çıktısı düğüme ve bağlı sonraki girdiye aktarıldı.", confirmDelete: "Bu cihazdaki şifreli projeyi silmek istiyor musunuz?", confirmClear: "Tuvaldeki tüm düğüm ve bağlantılar silinsin mi?", local: "AES-GCM ile cihazdaki IndexedDB içinde şifreli", unsaved: "Hazırlanıyor…", nodes: "düğüm", ready: "hazır", complete: "tamamlandı", errors: "hata", all: "Tümü", templates: "Başlangıç akışları", undo: "Geri al", redo: "Yinele", layout: "Otomatik düzenle", clear: "Tuvali temizle", duplicate: "Çoğalt", connections: "Bağlantılar", noConnections: "Bu düğümün bağlantısı yok.", disconnect: "Bağlantıyı kaldır", navProjects: "Projeler", navTools: "Araçlar", navCanvas: "Tuval", navInspector: "Denetçi", characters: "karakter", status: { idle: "bekliyor", ready: "hazır", complete: "tamamlandı", error: "hata" } },
  en: { title: "ByteQuant Workstation", saved: "Encrypted on this device", saving: "Preparing encrypted save…", saveError: "Workspace could not be saved. Check storage quota or private-browsing settings.", projects: "Projects", newProject: "New project", delete: "Delete", persist: "Persistent storage", persisted: "The browser approved persistent storage.", palette: "Tool palette", search: "Search {count} tools", category: "All categories", drag: "Drag or use the Add button.", add: "Add", showAll: "Show all tools", showLess: "Collapse list", canvas: "Visual workflow canvas", empty: "Choose a starter flow or add the first node from the palette.", connect: "Select an output port, then a target input port.", max: "The safe node limit was reached.", inspector: "Node inspector", input: "Input", output: "Latest output", open: "Run in tool", remove: "Remove node", select: "Select a node to edit it.", ai: "Quick workflow planner", aiPlaceholder: "Example: validate JSON, mask sensitive fields, then convert to CSV", analyze: "Create quick plan", addPlan: "Add plan to canvas", replacePlan: "Replace canvas with plan", aiBoundary: "Uses fast on-device rule matching. Open Local Agent for open-ended conversation and deeper planning.", decision: "Decision preview", confidence: "match", share: "URL recipe", include: "Include inputs in the link", createLink: "Create share link", copy: "Copy link", shareSafe: "Outputs never enter the URL; inputs are excluded by default.", imported: "The shared recipe was installed as a new on-device project.", importError: "Recipe is invalid or exceeds the safe size limit.", flow: "connections", restored: "Tool output reached the node and its connected next input.", confirmDelete: "Delete this encrypted project from this device?", confirmClear: "Remove every node and connection from the canvas?", local: "AES-GCM encrypted in on-device IndexedDB", unsaved: "Preparing…", nodes: "nodes", ready: "ready", complete: "complete", errors: "errors", all: "All", templates: "Starter flows", undo: "Undo", redo: "Redo", layout: "Auto layout", clear: "Clear canvas", duplicate: "Duplicate", connections: "Connections", noConnections: "This node has no connections.", disconnect: "Remove connection", navProjects: "Projects", navTools: "Tools", navCanvas: "Canvas", navInspector: "Inspector", characters: "characters", status: { idle: "idle", ready: "ready", complete: "complete", error: "error" } },
  de: { title: "ByteQuant Workstation", saved: "Auf diesem Gerät verschlüsselt", saving: "Verschlüsselte Speicherung…", saveError: "Arbeitsbereich konnte nicht gespeichert werden. Speicherquote oder privaten Modus prüfen.", projects: "Projekte", newProject: "Neues Projekt", delete: "Löschen", persist: "Dauerhafter Speicher", persisted: "Der Browser hat dauerhaften Speicher bestätigt.", palette: "Werkzeugpalette", search: "{count} Werkzeuge durchsuchen", category: "Alle Kategorien", drag: "Ziehen oder Hinzufügen verwenden.", add: "Hinzufügen", showAll: "Alle Werkzeuge anzeigen", showLess: "Liste einklappen", canvas: "Visuelle Ablaufoberfläche", empty: "Startablauf wählen oder ersten Knoten aus der Palette hinzufügen.", connect: "Erst Ausgang, dann Zieleingang wählen.", max: "Sichere Knotengrenze erreicht.", inspector: "Knotenprüfung", input: "Eingabe", output: "Letzte Ausgabe", open: "Im Werkzeug ausführen", remove: "Knoten entfernen", select: "Knoten zum Bearbeiten auswählen.", ai: "Schneller Ablaufplaner", aiPlaceholder: "Beispiel: JSON prüfen, sensible Felder maskieren und in CSV umwandeln", analyze: "Schnellplan erstellen", addPlan: "Plan zur Fläche hinzufügen", replacePlan: "Fläche durch Plan ersetzen", aiBoundary: "Nutzt schnelle lokale Regelzuordnung. Für offene Gespräche und tiefere Planung den lokalen Agenten öffnen.", decision: "Entscheidungsvorschau", confidence: "Übereinstimmung", share: "URL-Rezept", include: "Eingaben in Link aufnehmen", createLink: "Freigabelink erstellen", copy: "Link kopieren", shareSafe: "Ausgaben gelangen nie in die URL; Eingaben sind standardmäßig ausgeschlossen.", imported: "Das geteilte Rezept wurde als neues lokales Projekt eingerichtet.", importError: "Rezept ist ungültig oder zu groß.", flow: "Verbindungen", restored: "Werkzeugausgabe wurde an Knoten und Folgeeingang übertragen.", confirmDelete: "Verschlüsseltes Projekt von diesem Gerät löschen?", confirmClear: "Alle Knoten und Verbindungen entfernen?", local: "AES-GCM-verschlüsselt im lokalen IndexedDB", unsaved: "Vorbereitung…", nodes: "Knoten", ready: "bereit", complete: "fertig", errors: "Fehler", all: "Alle", templates: "Startabläufe", undo: "Rückgängig", redo: "Wiederholen", layout: "Automatisch anordnen", clear: "Fläche leeren", duplicate: "Duplizieren", connections: "Verbindungen", noConnections: "Dieser Knoten hat keine Verbindung.", disconnect: "Verbindung entfernen", navProjects: "Projekte", navTools: "Werkzeuge", navCanvas: "Fläche", navInspector: "Prüfung", characters: "Zeichen", status: { idle: "wartet", ready: "bereit", complete: "fertig", error: "Fehler" } },
  zh: { title: "ByteQuant 工作站", saved: "已在此设备上加密", saving: "正在准备加密保存…", saveError: "无法保存工作区。请检查存储配额或隐私浏览设置。", projects: "项目", newProject: "新建项目", delete: "删除", persist: "持久化存储", persisted: "浏览器已批准持久化存储。", palette: "工具面板", search: "搜索 {count} 个工具", category: "全部类别", drag: "拖动或使用添加按钮。", add: "添加", showAll: "显示全部工具", showLess: "收起列表", canvas: "可视化工作流画布", empty: "选择起始流程，或从工具面板添加第一个节点。", connect: "先选择输出端口，再选择目标输入端口。", max: "已达到安全节点上限。", inspector: "节点检查器", input: "输入", output: "最新输出", open: "在工具中运行", remove: "移除节点", select: "选择节点进行编辑。", ai: "快速流程规划器", aiPlaceholder: "例如：验证 JSON、遮蔽敏感字段，再转换为 CSV", analyze: "生成快速计划", addPlan: "把计划添加到画布", replacePlan: "用计划替换画布", aiBoundary: "使用设备端快速规则匹配。开放式对话和深入规划请使用本地助手。", decision: "决策预览", confidence: "匹配度", share: "URL 配方", include: "在链接中包含输入", createLink: "生成分享链接", copy: "复制链接", shareSafe: "输出绝不进入 URL；输入默认排除。", imported: "分享配方已建立为新的设备端项目。", importError: "配方无效或超过安全大小限制。", flow: "条连接", restored: "工具输出已传给该节点及下一个连接输入。", confirmDelete: "从此设备删除这个加密项目？", confirmClear: "移除画布中的全部节点与连接？", local: "使用 AES-GCM 加密保存在设备端 IndexedDB", unsaved: "准备中…", nodes: "个节点", ready: "就绪", complete: "已完成", errors: "错误", all: "全部", templates: "起始流程", undo: "撤销", redo: "重做", layout: "自动布局", clear: "清空画布", duplicate: "复制节点", connections: "连接", noConnections: "此节点没有连接。", disconnect: "移除连接", navProjects: "项目", navTools: "工具", navCanvas: "画布", navInspector: "检查器", characters: "字符", status: { idle: "等待", ready: "就绪", complete: "已完成", error: "错误" } },
} as const;

const workspaceExtraCopy = {
  tr: { onboarding: "Nereden başlamalıyım?", onboardingBody: "Hedefiniz var ama araçları bilmiyorsanız Yerel Ajanla planlayın. Araçları biliyorsanız şablonla doğrudan tuvale başlayın.", withAgent: "Yerel Ajanla planla", withTemplate: "KVKK akışını kur", dismiss: "Tuvali kendim keşfedeceğim", zoomIn: "Yakınlaştır", zoomOut: "Uzaklaştır", fit: "Akışı ekrana sığdır", center: "Seçili düğümü ortala", pan: "Tuvali kaydır", version: "Geçmiş sürümü", connectionBlocked: "Bu bağlantı döngü oluşturacağı için eklenmedi.", emptyTitle: "İlk akışınızı iki yoldan biriyle kurun", emptyAgent: "Hedefi Ajana anlat", emptyTemplate: "Örnek akışı ekle", navigation: "Tuval navigasyonu", importedPlan: "Yerel Ajan planı araç sırası ve gerekçeleriyle aktarıldı." },
  en: { onboarding: "Where should I start?", onboardingBody: "If you know the outcome but not the tools, plan with Local Agent. If you know the tools, begin directly with a starter flow.", withAgent: "Plan with Local Agent", withTemplate: "Build the privacy flow", dismiss: "I’ll explore the canvas", zoomIn: "Zoom in", zoomOut: "Zoom out", fit: "Fit workflow", center: "Center selected node", pan: "Pan canvas", version: "history revision", connectionBlocked: "The connection was blocked because it would create a cycle.", emptyTitle: "Build your first workflow in one of two ways", emptyAgent: "Describe the goal to Agent", emptyTemplate: "Add a starter flow", navigation: "Canvas navigation", importedPlan: "The Local Agent plan was transferred with its tool order and rationale." },
  de: { onboarding: "Wo soll ich beginnen?", onboardingBody: "Wenn das Ziel, aber nicht die Werkzeuge klar sind, planen Sie mit dem lokalen Agenten. Sind die Werkzeuge bekannt, starten Sie mit einer Vorlage.", withAgent: "Mit lokalem Agenten planen", withTemplate: "Datenschutzablauf erstellen", dismiss: "Arbeitsfläche selbst erkunden", zoomIn: "Vergrößern", zoomOut: "Verkleinern", fit: "Ablauf einpassen", center: "Gewählten Knoten zentrieren", pan: "Arbeitsfläche verschieben", version: "Verlaufsversion", connectionBlocked: "Die Verbindung würde einen Zyklus erzeugen und wurde blockiert.", emptyTitle: "Ersten Ablauf auf einem von zwei Wegen erstellen", emptyAgent: "Ziel dem Agenten beschreiben", emptyTemplate: "Startablauf hinzufügen", navigation: "Navigation der Arbeitsfläche", importedPlan: "Der Plan des lokalen Agenten wurde mit Reihenfolge und Begründungen übertragen." },
  zh: { onboarding: "我应该从哪里开始？", onboardingBody: "如果明确目标但不熟悉工具，请先用本地助手规划；如果已知所需工具，可直接从起始流程开始。", withAgent: "使用本地助手规划", withTemplate: "建立隐私流程", dismiss: "自行探索画布", zoomIn: "放大", zoomOut: "缩小", fit: "适应全部流程", center: "居中所选节点", pan: "平移画布", version: "历史版本", connectionBlocked: "该连接会形成循环，因此已阻止。", emptyTitle: "用两种方式之一建立第一个流程", emptyAgent: "向助手描述目标", emptyTemplate: "添加起始流程", navigation: "画布导航", importedPlan: "本地助手计划已连同工具顺序和依据一起传入。" },
} as const;

const workspaceFlowCopy = {
  tr: { navigator: "Akış gezgini", next: "Sıradaki adım", noNext: "Hazır düğüm yok; ilk adıma girdi ekleyin.", isolated: "bağlantısız düğüm", healthy: "Akış bağlantıları düzenli", cancel: "Bağlantı kurmayı iptal et", templates: "Gerçek bir hedefle başlayın", templateSearch: "Akış şablonlarında ara", advanced: "Gelişmiş paylaşım ve eşler arası seçenekler", progress: "Akış ilerlemesi", runNext: "Sıradaki aracı aç", addInput: "Sıradaki girdiyi hazırla", openAgent: "Yerel Ajanla akışı iyileştir", finished: "Akışın bütün adımları tamamlandı", start: "Başlangıç" },
  en: { navigator: "Flow navigator", next: "Next step", noNext: "No node is ready; add input to the first step.", isolated: "disconnected nodes", healthy: "Flow connections look healthy", cancel: "Cancel connection", templates: "Start from a real outcome", templateSearch: "Search workflow starters", advanced: "Advanced sharing and peer options", progress: "Workflow progress", runNext: "Open the next tool", addInput: "Prepare the next input", openAgent: "Improve flow with Local Agent", finished: "Every workflow step is complete", start: "Start" },
  de: { navigator: "Ablaufnavigator", next: "Nächster Schritt", noNext: "Kein Knoten ist bereit; Eingabe im ersten Schritt ergänzen.", isolated: "unverbundene Knoten", healthy: "Ablaufverbindungen sind geordnet", cancel: "Verbindung abbrechen", templates: "Mit einem echten Ziel starten", templateSearch: "Startabläufe durchsuchen", advanced: "Erweiterte Freigabe- und Peer-Optionen", progress: "Ablauffortschritt", runNext: "Nächstes Werkzeug öffnen", addInput: "Nächste Eingabe vorbereiten", openAgent: "Ablauf mit lokalem Agenten verbessern", finished: "Alle Schritte des Ablaufs sind abgeschlossen", start: "Start" },
  zh: { navigator: "流程导航", next: "下一步", noNext: "暂无就绪节点；请为第一步添加输入。", isolated: "个未连接节点", healthy: "流程连接状态良好", cancel: "取消连接", templates: "从真实目标开始", templateSearch: "搜索工作流模板", advanced: "高级分享与点对点选项", progress: "流程进度", runNext: "打开下一个工具", addInput: "准备下一步输入", openAgent: "使用本地助手优化流程", finished: "全部流程步骤已完成", start: "开始" },
} as const;

const workspaceGuidedCopy = {
  tr: {
    overview: "Akış özeti", steps: "Adımlar", nextAction: "Şimdi ne yapmalıyım?", chooseFlow: "Bir sonuç seçin",
    chooseFlowBody: "Hazır akışlardan biriyle başlayın. Araçları bilmeniz gerekmez; her adım gerektiğinde sizi doğru araca götürür.",
    selectedStep: "Seçili adım", inputHelp: "Bu adımda işlenecek metni veya veriyi buraya ekleyin. Sonraki adımlar çıktıyı otomatik devralır.",
    emptyInput: "İlk adım için veri ekleyin", readyInput: "Girdi hazır; aracı açıp sonucu üretin.", completedInput: "Bu adım tamamlandı. Sonraki adıma geçebilirsiniz.",
    showMap: "Görsel haritayı göster", hideMap: "Görsel haritayı gizle", editDetails: "Ayrıntılı düzenleme", help: "Nasıl kullanılır?",
    privateSave: "Değişiklikler bu cihazda otomatik saklanır", allDone: "Akış tamamlandı", stepOf: "adım", statusLabel: "Durum",
    journey: ["Sonucu seç", "İlk veriyi ekle", "Adımları tamamla"], changeFlow: "Başka bir akış seç", pickerTitle: "Hazır akışlardan birini seçin", pickerBody: "Seçtiğiniz akış mevcut tuvalin yerini alır. Sayfadan ayrılmadan önce Geri al ile önceki sürüme dönebilirsiniz.", cancelPicker: "Vazgeç", confirmReplace: "Mevcut tuvali seçtiğiniz hazır akışla değiştirmek istiyor musunuz?", deviceOnly: "Otomatik kayıt · yalnız bu cihaz",
  },
  en: {
    overview: "Flow overview", steps: "Steps", nextAction: "What should I do now?", chooseFlow: "Choose an outcome",
    chooseFlowBody: "Start with a ready-made flow. You do not need to know the tools; each step opens the right tool when needed.",
    selectedStep: "Selected step", inputHelp: "Add the text or data for this step here. Later steps receive the completed output automatically.",
    emptyInput: "Add data for the first step", readyInput: "The input is ready; open the tool to produce the result.", completedInput: "This step is complete. You can continue to the next step.",
    showMap: "Show visual map", hideMap: "Hide visual map", editDetails: "Detailed editing", help: "How does it work?",
    privateSave: "Changes are saved automatically on this device", allDone: "Flow complete", stepOf: "of", statusLabel: "Status",
    journey: ["Choose the outcome", "Add the first data", "Complete the steps"], changeFlow: "Choose another flow", pickerTitle: "Choose a ready-made flow", pickerBody: "The selected flow replaces the current canvas. Before leaving the page, you can use Undo to return to the previous version.", cancelPicker: "Cancel", confirmReplace: "Replace the current canvas with this ready-made flow?", deviceOnly: "Auto-saved · only on this device",
  },
  de: {
    overview: "Ablaufübersicht", steps: "Schritte", nextAction: "Was ist jetzt zu tun?", chooseFlow: "Ergebnis auswählen",
    chooseFlowBody: "Beginnen Sie mit einem fertigen Ablauf. Werkzeugkenntnisse sind nicht nötig; jeder Schritt öffnet bei Bedarf das passende Werkzeug.",
    selectedStep: "Gewählter Schritt", inputHelp: "Fügen Sie hier Text oder Daten für diesen Schritt ein. Folgeschritte übernehmen das fertige Ergebnis automatisch.",
    emptyInput: "Daten für den ersten Schritt ergänzen", readyInput: "Die Eingabe ist bereit; öffnen Sie das Werkzeug und erzeugen Sie das Ergebnis.", completedInput: "Dieser Schritt ist fertig. Sie können mit dem nächsten fortfahren.",
    showMap: "Visuelle Karte zeigen", hideMap: "Visuelle Karte ausblenden", editDetails: "Detaillierte Bearbeitung", help: "Wie funktioniert es?",
    privateSave: "Änderungen werden automatisch auf diesem Gerät gespeichert", allDone: "Ablauf abgeschlossen", stepOf: "von", statusLabel: "Status",
    journey: ["Ergebnis wählen", "Erste Daten eingeben", "Schritte abschließen"], changeFlow: "Anderen Ablauf wählen", pickerTitle: "Fertigen Ablauf auswählen", pickerBody: "Der gewählte Ablauf ersetzt die aktuelle Fläche. Vor dem Verlassen der Seite können Sie mit Rückgängig zur vorherigen Version zurückkehren.", cancelPicker: "Abbrechen", confirmReplace: "Aktuelle Fläche durch diesen fertigen Ablauf ersetzen?", deviceOnly: "Automatisch gespeichert · nur auf diesem Gerät",
  },
  zh: {
    overview: "流程概览", steps: "步骤", nextAction: "现在该做什么？", chooseFlow: "选择目标",
    chooseFlowBody: "从现成流程开始，无需预先了解工具；每一步都会在需要时打开正确工具。",
    selectedStep: "当前步骤", inputHelp: "在此添加本步骤要处理的文本或数据；完成后的输出会自动交给后续步骤。",
    emptyInput: "为第一步添加数据", readyInput: "输入已准备好；请打开工具生成结果。", completedInput: "此步骤已完成，可以继续下一步。",
    showMap: "显示流程图", hideMap: "隐藏流程图", editDetails: "详细编辑", help: "如何使用？",
    privateSave: "更改会自动保存在此设备上", allDone: "流程已完成", stepOf: "共", statusLabel: "状态",
    journey: ["选择目标", "添加第一份数据", "完成各步骤"], changeFlow: "选择其他流程", pickerTitle: "选择现成流程", pickerBody: "所选流程会替换当前画布；离开页面前可使用“撤销”恢复上一版本。", cancelPicker: "取消", confirmReplace: "要用这个现成流程替换当前画布吗？", deviceOnly: "自动保存 · 仅限本设备",
  },
} as const;

const templateDefinitions = [
  { id: "privacy", names: { tr: "CSV gizlilik akışı", en: "CSV privacy flow", de: "CSV-Datenschutzablauf", zh: "CSV 隐私流程" }, summaries: { tr: "Tabloyu incele, hassas alanları maskele, teslim biçimine dönüştür.", en: "Inspect a table, mask sensitive fields, then convert for delivery.", de: "Tabelle prüfen, sensible Felder maskieren und zur Ausgabe konvertieren.", zh: "检查表格、遮蔽敏感字段并转换为交付格式。" }, slugs: ["csv-inceleyici", "kvkk-veri-maskeleyici", "json-csv-donusturucu"] },
  { id: "json", names: { tr: "JSON kalite kapısı", en: "JSON quality gate", de: "JSON-Qualitätsprüfung", zh: "JSON 质量检查" }, summaries: { tr: "Biçimlendir, veri sözleşmesini doğrula ve sürüm farkını bul.", en: "Format, validate the data contract, and find version differences.", de: "Formatieren, Datenvertrag prüfen und Versionsunterschiede finden.", zh: "格式化、验证数据契约并查找版本差异。" }, slugs: ["json-bicimlendirici", "json-schema-olusturucu", "json-diff-karsilastirma"] },
  { id: "seo", names: { tr: "Teknik SEO paketi", en: "Technical SEO pack", de: "Technisches SEO-Paket", zh: "技术 SEO 套件" }, summaries: { tr: "Slug, dil sinyalleri ve SSS şemasını yayın öncesi hazırla.", en: "Prepare slugs, language signals, and FAQ schema before publishing.", de: "Slugs, Sprachsignale und FAQ-Schema vor Veröffentlichung vorbereiten.", zh: "发布前准备 URL、语言信号与 FAQ Schema。" }, slugs: ["seo-slug-olusturucu", "hreflang-etiket-olusturucu", "faq-json-ld-olusturucu"] },
  { id: "prompt", names: { tr: "Prompt güçlendirme", en: "Prompt strengthening", de: "Prompt-Verbesserung", zh: "提示词增强" }, summaries: { tr: "Netliği denetle, sistemi iyileştir ve test vakaları oluştur.", en: "Review clarity, improve the system prompt, and create test cases.", de: "Klarheit prüfen, System-Prompt verbessern und Testfälle erstellen.", zh: "检查清晰度、优化系统提示词并创建测试用例。" }, slugs: ["prompt-kalite-denetimi", "sistem-promptu-netlik-kontrolu", "prompt-test-vaka-matrisi"] },
  { id: "publish", names: { tr: "Güvenli içerik yayını", en: "Safe content publishing", de: "Sichere Inhaltsfreigabe", zh: "安全内容发布" }, summaries: { tr: "Unicode sorunlarını temizle, metni sadeleştir ve güvenli slug üret.", en: "Normalize Unicode, clean the text, and generate a safe slug.", de: "Unicode normalisieren, Text bereinigen und sicheren Slug erzeugen.", zh: "规范 Unicode、清理文本并生成安全 URL。" }, slugs: ["unicode-normalizasyon-inceleyici", "metin-temizleyici", "seo-slug-olusturucu"] },
  { id: "api", names: { tr: "API teslim kontrolü", en: "API delivery review", de: "API-Auslieferungsprüfung", zh: "API 交付检查" }, summaries: { tr: "Uç noktaları envanterle, şemayı doğrula ve güvenlik başlıklarını denetle.", en: "Inventory endpoints, validate schemas, and review security headers.", de: "Endpunkte erfassen, Schemas prüfen und Sicherheitsheader kontrollieren.", zh: "盘点端点、验证 Schema 并检查安全响应头。" }, slugs: ["openapi-endpoint-envanteri", "json-schema-olusturucu", "http-guvenlik-basliklari-denetleyici"] },
  { id: "frontend", names: { tr: "Responsive arayüz kalite kapısı", en: "Responsive UI quality gate", de: "Responsive-UI-Qualitätsprüfung", zh: "响应式界面质量检查" }, summaries: { tr: "Kontrastı, akışkan ölçüyü ve görsel oranını birlikte doğrula.", en: "Check contrast, fluid sizing, and visual ratio together.", de: "Kontrast, flexible Größen und Bildverhältnis zusammen prüfen.", zh: "同时检查对比度、流式尺寸与视觉比例。" }, slugs: ["renk-kontrast-denetleyici", "css-clamp-olusturucu", "en-boy-orani-hesaplayici"] },
  { id: "visual", names: { tr: "Web için görsel hazırlama", en: "Prepare an image for the web", de: "Bild fürs Web vorbereiten", zh: "为网页准备图片" }, summaries: { tr: "Boyutu ayarla, dosyayı sıkıştır ve doğru çıktı biçimine dönüştür.", en: "Resize, compress, and convert an image to the right delivery format.", de: "Bild skalieren, komprimieren und ins passende Ausgabeformat umwandeln.", zh: "调整尺寸、压缩图片并转换为合适的交付格式。" }, slugs: ["gorsel-boyutlandirici", "gorsel-sikistirici", "gorsel-format-donusturucu"] },
  { id: "dataset", names: { tr: "Akış verisi hazırlama", en: "Streaming dataset prep", de: "Streaming-Datensatz vorbereiten", zh: "流式数据集准备" }, summaries: { tr: "NDJSON üret, alan yolunu doğrula ve sürüm uyumluluğunu denetle.", en: "Produce NDJSON, verify field paths, and check version compatibility.", de: "NDJSON erzeugen, Feldpfade prüfen und Versionen vergleichen.", zh: "生成 NDJSON、验证字段路径并检查版本兼容性。" }, slugs: ["json-lines-donusturucu", "json-pointer-gezgini", "semver-karsilastirici"] },
  { id: "schedule", names: { tr: "Ekip ve tarih planlama", en: "Team and date planning", de: "Team- und Terminplanung", zh: "团队与日期规划" }, summaries: { tr: "Saat dilimini uzlaştır, iş gününü hesapla ve paylaşılabilir tablo oluştur.", en: "Align time zones, calculate business days, and create a shareable table.", de: "Zeitzonen abstimmen, Arbeitstage berechnen und Tabelle erstellen.", zh: "协调时区、计算工作日并生成可分享表格。" }, slugs: ["zaman-dilimi-toplanti-planlayici", "is-gunu-hesaplayici", "markdown-tablo-olusturucu"] },
  { id: "evidence", names: { tr: "Kanıta dayalı araştırma", en: "Evidence-led research", de: "Evidenzbasierte Recherche", zh: "证据驱动研究" }, summaries: { tr: "Soruyu ayrıştır, kaynakları puanla ve çelişkileri sentezle.", en: "Decompose the question, score sources, and synthesize contradictions.", de: "Frage zerlegen, Quellen bewerten und Widersprüche synthetisieren.", zh: "拆解问题、评估来源并综合矛盾证据。" }, slugs: ["arastirma-sorusu-ayristirici", "kaynak-guvenilirlik-matrisi", "kanit-sentez-tablosu"] },
  { id: "supply-chain", names: { tr: "Yazılım tedarik zinciri", en: "Software supply-chain review", de: "Software-Lieferkettenprüfung", zh: "软件供应链审查" }, summaries: { tr: "Manifestoyu, npm scriptlerini ve CI izinlerini aynı akışta ön tara.", en: "Pre-scan the manifest, npm scripts, and CI permissions in one flow.", de: "Manifest, npm-Skripte und CI-Rechte in einem Ablauf vorprüfen.", zh: "在同一流程中预扫描清单、npm 脚本与 CI 权限。" }, slugs: ["paket-manifestosu-denetleyici", "npm-script-risk-tarayicisi", "github-actions-izin-denetleyici"] },
  { id: "meeting", names: { tr: "Toplantıdan eyleme", en: "Meeting to action", de: "Vom Meeting zur Aufgabe", zh: "从会议到行动" }, summaries: { tr: "Notları yapılandır, görevleri çıkar ve sahipli kontrol listesi oluştur.", en: "Structure notes, extract actions, and build an owned checklist.", de: "Notizen strukturieren, Aufgaben extrahieren und Checkliste erstellen.", zh: "整理笔记、提取行动项并创建责任清单。" }, slugs: ["toplanti-notu-yapilandirici", "aksiyon-maddesi-cikarici", "kontrol-listesi-duzenleyici"] },
  { id: "rag", names: { tr: "Güvenilir RAG hazırlığı", en: "Trustworthy RAG prep", de: "Verlässliche RAG-Vorbereitung", zh: "可信 RAG 准备" }, summaries: { tr: "Kaynağı puanla, bağlamı önceliklendir ve iddia riskini kontrol et.", en: "Score sources, prioritize context, and review claim risks.", de: "Quellen bewerten, Kontext priorisieren und Aussagenrisiken prüfen.", zh: "评估来源、排列上下文并检查主张风险。" }, slugs: ["rag-kaynak-kalite-puanlayici", "baglam-oncelik-planlayici", "halusinasyon-risk-kontrol-listesi"] },
  { id: "business", names: { tr: "İş kararı senaryosu", en: "Business decision scenario", de: "Geschäftsentscheidungsszenario", zh: "商业决策情景" }, summaries: { tr: "Başabaşı, marjı ve ağırlıklı seçenekleri karşılaştır.", en: "Compare break-even, margin, and weighted options.", de: "Break-even, Marge und gewichtete Optionen vergleichen.", zh: "比较盈亏平衡、毛利与加权选项。" }, slugs: ["basabas-noktasi-hesaplayici", "marj-kar-orani-hesaplayici", "karar-matrisi"] },
  { id: "privacy-notice", names: { tr: "Gizlilik yayını kontrolü", en: "Privacy publication review", de: "Datenschutz-Veröffentlichungsprüfung", zh: "隐私发布检查" }, summaries: { tr: "Bildirim boşluklarını bul, sırları temizle ve kaynak işaretlerini denetle.", en: "Find notice gaps, redact secrets, and audit citation markers.", de: "Hinweislücken finden, Secrets redigieren und Zitate prüfen.", zh: "查找声明缺口、脱敏密钥并审计引用标记。" }, slugs: ["gizlilik-bildirimi-bosluk-tarayicisi", "gizli-deger-redaksiyon-planlayici", "atif-yer-tutucu-denetleyici"] },
  { id: "api-policy", names: { tr: "API politika kapısı", en: "API policy gate", de: "API-Richtlinienprüfung", zh: "API 策略检查" }, summaries: { tr: "CORS, OAuth dönüş adresi ve önbellek davranışını yayın öncesi birlikte incele.", en: "Review CORS, OAuth redirects, and cache behavior together before release.", de: "CORS, OAuth-Redirects und Cache-Verhalten gemeinsam vor Release prüfen.", zh: "发布前共同检查 CORS、OAuth 重定向与缓存行为。" }, slugs: ["cors-politikasi-denetleyici", "oauth-yonlendirme-uri-denetleyici", "http-cache-control-olusturucu"] },
  { id: "reshape", names: { tr: "Veri yeniden şekillendirme", en: "Data reshaping", de: "Daten umformen", zh: "数据重塑" }, summaries: { tr: "CSV yapısını doğrula, pivot özetini üret ve uzun-geniş dönüşümü denetle.", en: "Validate CSV structure, create a pivot summary, and audit long-wide conversion.", de: "CSV-Struktur prüfen, Pivot erstellen und Long-Wide-Umformung kontrollieren.", zh: "验证 CSV 结构、生成透视汇总并检查长宽转换。" }, slugs: ["csv-inceleyici", "csv-pivot-ozeti", "csv-uzun-genis-donusturucu"] },
  { id: "prompt-governance", names: { tr: "Prompt yönetişim akışı", en: "Prompt governance flow", de: "Prompt-Governance-Ablauf", zh: "提示词治理流程" }, summaries: { tr: "Talimat çatışmasını bul, örnek kapsamını ölç ve değerlendirme veri setini hazırla.", en: "Find instruction conflicts, measure example coverage, and prepare an evaluation dataset.", de: "Anweisungskonflikte finden, Beispielabdeckung messen und Evaluationsdatensatz vorbereiten.", zh: "识别指令冲突、衡量示例覆盖并准备评估数据集。" }, slugs: ["talimat-cakisma-denetleyici", "few-shot-kapsama-analizoru", "degerlendirme-veri-seti-sablonu"] },
  { id: "evidence-freshness", names: { tr: "Kanıt ve güncellik takibi", en: "Evidence and freshness review", de: "Evidenz- und Aktualitätsprüfung", zh: "证据与时效复核" }, summaries: { tr: "Araştırma sorusunu kur, kanıt boşluklarını bul ve kaynak inceleme tarihini planla.", en: "Frame the research question, find evidence gaps, and plan source review dates.", de: "Forschungsfrage formulieren, Evidenzlücken finden und Quellenprüfung planen.", zh: "构建研究问题、识别证据缺口并规划来源复核日期。" }, slugs: ["pico-arastirma-sorusu-olusturucu", "iddia-kanit-boslugu-inceleyici", "kaynak-guncellik-takipcisi"] },
] as const;

const nodeWidth = 244;
const nodePortY = 66;

export default function WorkstationClient({ locale }: { locale: Locale }) {
  const t = { ...uiCopy[locale], search: uiCopy[locale].search.replace("{count}", String(publicTools.length)) };
  const extra = workspaceExtraCopy[locale];
  const [document, setDocument] = useState(() => createWorkspace(locale));
  const [projects, setProjects] = useState<WorkspaceSummary[]>([]);
  const [hydrated, setHydrated] = useState(false);
  const [saveState, setSaveState] = useState<"idle" | "saving" | "saved" | "error">("idle");
  const [notice, setNotice] = useState("");
  const [query, setQuery] = useState("");
  const [templateQuery, setTemplateQuery] = useState("");
  const [category, setCategory] = useState<"all" | ToolCategory>("all");
  const [paletteExpanded, setPaletteExpanded] = useState(false);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [connectFrom, setConnectFrom] = useState<string | null>(null);
  const [agentGoal, setAgentGoal] = useState("");
  const [agentPreparedInput, setAgentPreparedInput] = useState("");
  const [agentPlan, setAgentPlan] = useState<AgentPlan | null>(null);
  const [includeInputs, setIncludeInputs] = useState(false);
  const [shareUrl, setShareUrl] = useState("");
  const [past, setPast] = useState<WorkspaceDocument[]>([]);
  const [future, setFuture] = useState<WorkspaceDocument[]>([]);
  const [zoom, setZoom] = useState(1);
  const [panMode, setPanMode] = useState(false);
  const [onboardingOpen, setOnboardingOpen] = useState(false);
  const [guidedMode, setGuidedMode] = useState(true);
  const [showMap, setShowMap] = useState(false);
  const [templatePickerOpen, setTemplatePickerOpen] = useState(false);
  const canvasScrollRef = useRef<HTMLDivElement>(null);
  const returnPath = pathFor(locale, "workstation");
  const selected = document.nodes.find((node) => node.id === selectedId) ?? null;
  const summary = useMemo(() => workspaceGraphSummary(document), [document]);
  const canvasSize = useMemo(() => ({ width: Math.max(1100, ...document.nodes.map((node) => node.x + 330)), height: Math.max(610, ...document.nodes.map((node) => node.y + 230)) }), [document.nodes]);
  const selectedEdges = useMemo(() => selected ? document.edges.filter((edge) => edge.from === selected.id || edge.to === selected.id) : [], [document.edges, selected]);
  const isolatedNodes = useMemo(() => document.nodes.length < 2 ? [] : document.nodes.filter((node) => !document.edges.some((edge) => edge.from === node.id || edge.to === node.id)), [document.edges, document.nodes]);
  const runnableNode = useMemo(() => document.nodes.find((node) => node.status === "ready") ?? document.nodes.find((node) => node.status === "idle" && !document.edges.some((edge) => edge.to === node.id)) ?? null, [document.edges, document.nodes]);
  const runnableIndex = runnableNode ? document.nodes.findIndex((node) => node.id === runnableNode.id) : -1;
  const currentStage = document.nodes.length ? (runnableIndex >= 0 ? runnableIndex + 1 : document.nodes.length) : 0;
  const guided = workspaceGuidedCopy[locale];
  const guidedNode = selected ?? runnableNode ?? document.nodes[0] ?? null;
  const filteredTools = useMemo(() => {
    const terms = query.trim().toLocaleLowerCase().split(/\s+/u).filter(Boolean);
    return publicTools.filter((tool) => {
      if (category !== "all" && tool.category !== category) return false;
      const haystack = `${tool.title[locale]} ${tool.slug} ${tool.short[locale]}`.toLocaleLowerCase();
      return terms.every((term) => haystack.includes(term));
    });
  }, [query, category, locale]);
  const paletteCanCollapse = !query.trim() && category === "all" && filteredTools.length > 24;
  const visibleTools = paletteCanCollapse && !paletteExpanded ? filteredTools.slice(0, 24) : filteredTools;
  const visibleTemplates = useMemo(() => { const term = templateQuery.trim().toLocaleLowerCase(); return templateDefinitions.filter((template) => !term || `${template.names[locale]} ${template.summaries[locale]}`.toLocaleLowerCase().includes(term)); }, [locale, templateQuery]);

  const refreshProjects = useCallback(async () => { try { setProjects(await listWorkspaces()); } catch { setProjects([]); } }, []);
  const replaceDocument = useCallback((next: WorkspaceDocument) => { setDocument(next); setPast([]); setFuture([]); setSelectedId(next.nodes[0]?.id ?? null); }, []);
  const mutateDocument = useCallback((updater: (current: WorkspaceDocument) => WorkspaceDocument, track = true) => setDocument((current) => {
    const next = updater(current);
    if (next === current) return current;
    if (track) { setPast((items) => [...items.slice(-39), current]); setFuture([]); }
    return next;
  }), []);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const active = readActiveWorkspace(sessionStorage.getItem(WORKSPACE_ACTIVE_KEY));
        const handoff = readWorkspaceHandoff(sessionStorage.getItem(WORKSPACE_HANDOFF_KEY));
        const goalHandoff = readWorkspaceAgentGoal(sessionStorage.getItem(WORKSPACE_AGENT_GOAL_KEY));
        const inputHandoff = readWorkspaceAgentInput(sessionStorage.getItem(WORKSPACE_AGENT_INPUT_KEY));
        const planHandoff = readAgentPlan(sessionStorage.getItem(WORKSPACE_AGENT_PLAN_KEY));
        const toolStart = readWorkspaceToolStart(sessionStorage.getItem(WORKSPACE_TOOL_START_KEY));
        const recipeCode = new URLSearchParams(location.search).get("recipe");
        let initial = active;
        if (recipeCode) { initial = documentFromRecipe(await decodeRecipeInWorker(recipeCode)); setNotice(t.imported); history.replaceState(null, "", location.pathname); }
        if (!initial) { const summaries = await listWorkspaces(); if (summaries[0]) initial = await loadWorkspace(summaries[0].id); }
        initial ??= createWorkspace(locale);
        if (toolStart?.locale === locale) {
          const tool = tools.find((item) => item.slug === toolStart.toolSlug);
          if (tool) {
            initial = createWorkspace(locale, tool.title[locale]);
            const node: WorkspaceNode = { id: workspaceId("node"), toolSlug: tool.slug, title: tool.title[locale], x: 48, y: 58, input: toolStart.input, output: "", status: "ready" };
            initial = updateWorkspace(initial, { nodes: [node], edges: [] });
          }
        } else if (planHandoff?.locale === locale && planHandoff.steps.length) {
          initial = createWorkspace(locale, planHandoff.goal.slice(0, 80));
          const nodes = planHandoff.steps.map((step, index): WorkspaceNode => ({ id: workspaceId("node"), toolSlug: step.toolSlug, title: step.title, x: 48 + index * 300, y: 90 + (index % 2) * 34, input: index === 0 ? (inputHandoff ?? planHandoff.goal) : "", output: "", status: index === 0 ? "ready" : "idle" }));
          initial = updateWorkspace(initial, { nodes, edges: nodes.slice(1).map((node, index) => ({ id: workspaceId("edge"), from: nodes[index].id, to: node.id })) });
        } else if (handoff?.completed && handoff.workspaceId === initial.id) { initial = propagateWorkspaceOutput(initial, handoff.nodeId, handoff.output); setNotice(t.restored); }
        sessionStorage.removeItem(WORKSPACE_ACTIVE_KEY); sessionStorage.removeItem(WORKSPACE_HANDOFF_KEY); sessionStorage.removeItem(WORKSPACE_AGENT_GOAL_KEY); sessionStorage.removeItem(WORKSPACE_AGENT_INPUT_KEY); sessionStorage.removeItem(WORKSPACE_AGENT_PLAN_KEY); sessionStorage.removeItem(WORKSPACE_TOOL_START_KEY);
        if (!cancelled) {
          setDocument(initial); setSelectedId(initial.nodes[0]?.id ?? null); setHydrated(true);
          setAgentPreparedInput(inputHandoff ?? "");
          if (planHandoff?.locale === locale) { setAgentGoal(planHandoff.goal); setAgentPlan(planHandoff); setNotice(extra.importedPlan); }
          else if (goalHandoff) { setAgentGoal(goalHandoff); setAgentPlan(createAgentPlan(goalHandoff, publicTools, locale)); }
          const alreadyStarted = Boolean(recipeCode || goalHandoff || toolStart || (planHandoff?.locale === locale && planHandoff.steps.length) || initial.nodes.length);
          try { if (alreadyStarted) sessionStorage.setItem("bytequant:workstation-onboarding:v1", "seen"); } catch { /* optional preference */ }
        }
      } catch { if (!cancelled) { setNotice(t.importError); setHydrated(true); } }
    })();
    return () => { cancelled = true; };
  }, [extra.importedPlan, locale, t.importError, t.imported, t.restored]);

  useEffect(() => {
    if (!hydrated) return;
    const timeout = window.setTimeout(async () => {
      setSaveState("saving");
      try { await saveWorkspace(document); setSaveState("saved"); await refreshProjects(); } catch { setSaveState("error"); }
    }, 700);
    return () => window.clearTimeout(timeout);
  }, [document, hydrated, refreshProjects]);

  useEffect(() => {
    const onKey = (event: KeyboardEvent) => {
      const target = event.target as HTMLElement | null;
      if (target?.matches("input,textarea,select,[contenteditable=true]")) return;
      if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "z") { event.preventDefault(); if (event.shiftKey) redo(); else undo(); }
      if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "y") { event.preventDefault(); redo(); }
      if ((event.ctrlKey || event.metaKey) && (event.key === "+" || event.key === "=")) { event.preventDefault(); setZoom((value) => Math.min(1.5, Number((value + .1).toFixed(2)))); }
      if ((event.ctrlKey || event.metaKey) && event.key === "-") { event.preventDefault(); setZoom((value) => Math.max(.55, Number((value - .1).toFixed(2)))); }
      if ((event.key === "Delete" || event.key === "Backspace") && selectedId) { event.preventDefault(); removeNode(selectedId); }
    };
    window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey);
  });

  function undo() { const previous = past.at(-1); if (!previous) return; setFuture((items) => [document, ...items].slice(0, 40)); setPast((items) => items.slice(0, -1)); setDocument(previous); }
  function redo() { const next = future[0]; if (!next) return; setPast((items) => [...items.slice(-39), document]); setFuture((items) => items.slice(1)); setDocument(next); }
  function dismissOnboarding() { try { sessionStorage.setItem("bytequant:workstation-onboarding:v1", "seen"); } catch { /* session preference is optional */ } setOnboardingOpen(false); }
  function fitView() {
    const viewport = canvasScrollRef.current; if (!viewport) return;
    const next = Math.max(.55, Math.min(1.2, (viewport.clientWidth - 32) / canvasSize.width, (viewport.clientHeight - 32) / canvasSize.height));
    setZoom(Number(next.toFixed(2))); viewport.scrollTo({ left: 0, top: 0, behavior: "smooth" });
  }
  function centerSelected() {
    const viewport = canvasScrollRef.current; if (!viewport || !selected) return;
    viewport.scrollTo({ left: Math.max(0, (selected.x + nodeWidth / 2) * zoom - viewport.clientWidth / 2), top: Math.max(0, (selected.y + 70) * zoom - viewport.clientHeight / 2), behavior: "smooth" });
  }
  function focusNode(node: WorkspaceNode) {
    setSelectedId(node.id); const viewport = canvasScrollRef.current; if (!viewport) return;
    viewport.scrollTo({ left: Math.max(0, (node.x + nodeWidth / 2) * zoom - viewport.clientWidth / 2), top: Math.max(0, (node.y + 70) * zoom - viewport.clientHeight / 2), behavior: "smooth" });
  }
  function prepareNodeInput(node: WorkspaceNode) {
    focusNode(node);
    window.requestAnimationFrame(() => {
      const inspector = globalThis.document.getElementById("workspace-inspector");
      inspector?.scrollIntoView({ behavior: "smooth", block: "center" });
      inspector?.querySelector<HTMLTextAreaElement>("textarea:not([readonly])")?.focus({ preventScroll: true });
    });
  }
  function beginPan(event: React.PointerEvent<HTMLDivElement>) {
    if (!panMode || event.button !== 0) return;
    const viewport = canvasScrollRef.current; if (!viewport) return;
    event.preventDefault(); const start = { x: event.clientX, y: event.clientY, left: viewport.scrollLeft, top: viewport.scrollTop };
    const move = (next: PointerEvent) => viewport.scrollTo({ left: start.left - (next.clientX - start.x), top: start.top - (next.clientY - start.y) });
    const end = () => { window.removeEventListener("pointermove", move); window.removeEventListener("pointerup", end); window.removeEventListener("pointercancel", end); };
    window.addEventListener("pointermove", move); window.addEventListener("pointerup", end, { once: true }); window.addEventListener("pointercancel", end, { once: true });
  }

  function nodeFor(slug: string, index: number, baseX = 48, baseY = 58): WorkspaceNode | null {
    const tool = tools.find((item) => item.slug === slug); if (!tool) return null;
    return { id: workspaceId("node"), toolSlug: slug, title: tool.title[locale], x: baseX + index * 300, y: baseY, input: "", output: "", status: "idle" };
  }

  function addTool(slug: string, position?: { x: number; y: number }) {
    if (document.nodes.length >= WORKSPACE_MAX_NODES) { setNotice(t.max); return; }
    const node = nodeFor(slug, 0, position?.x ?? 48 + (document.nodes.length % 3) * 280, position?.y ?? 48 + Math.floor(document.nodes.length / 3) * 190);
    if (!node) return;
    mutateDocument((current) => updateWorkspace(current, { nodes: [...current.nodes, node] })); setSelectedId(node.id);
  }

  function addTemplate(slugs: readonly string[], name: string) {
    if (document.nodes.length + slugs.length > WORKSPACE_MAX_NODES) { setNotice(t.max); return; }
    const baseY = Math.max(58, ...document.nodes.map((node) => node.y + 190));
    const nodes = slugs.map((slug, index) => nodeFor(slug, index, 48, baseY)).filter((node): node is WorkspaceNode => Boolean(node));
    const edges = nodes.slice(1).map((node, index) => ({ id: workspaceId("edge"), from: nodes[index].id, to: node.id }));
    mutateDocument((current) => updateWorkspace(current, { name: current.nodes.length ? current.name : name, nodes: [...current.nodes, ...nodes], edges: [...current.edges, ...edges] }));
    setSelectedId(nodes[0]?.id ?? null);
  }

  function replaceWithTemplate(slugs: readonly string[], name: string) {
    if (document.nodes.length && !window.confirm(guided.confirmReplace)) return;
    const nodes = slugs.map((slug, index) => nodeFor(slug, index)).filter((node): node is WorkspaceNode => Boolean(node));
    const edges = nodes.slice(1).map((node, index) => ({ id: workspaceId("edge"), from: nodes[index].id, to: node.id }));
    mutateDocument((current) => updateWorkspace(current, { name, nodes, edges }));
    setSelectedId(nodes[0]?.id ?? null);
    setTemplatePickerOpen(false);
    setShowMap(false);
  }

  function dropTool(event: React.DragEvent<HTMLDivElement>) {
    event.preventDefault(); const slug = event.dataTransfer.getData("application/x-bytequant-tool"); const rectangle = event.currentTarget.getBoundingClientRect();
    addTool(slug, { x: Math.max(10, (event.clientX - rectangle.left) / zoom - 100), y: Math.max(10, (event.clientY - rectangle.top) / zoom - 40) });
  }

  function beginMove(event: React.PointerEvent<HTMLButtonElement>, node: WorkspaceNode) {
    if (event.button !== 0) return; event.preventDefault(); setSelectedId(node.id); setPast((items) => [...items.slice(-39), document]); setFuture([]);
    const start = { clientX: event.clientX, clientY: event.clientY, x: node.x, y: node.y };
    const move = (next: PointerEvent) => mutateDocument((current) => updateWorkspace(current, { nodes: current.nodes.map((item) => item.id === node.id ? { ...item, x: Math.max(0, Math.round((start.x + (next.clientX - start.clientX) / zoom) / 8) * 8), y: Math.max(0, Math.round((start.y + (next.clientY - start.clientY) / zoom) / 8) * 8) } : item) }), false);
    const end = () => { window.removeEventListener("pointermove", move); window.removeEventListener("pointerup", end); window.removeEventListener("pointercancel", end); };
    window.addEventListener("pointermove", move); window.addEventListener("pointerup", end, { once: true }); window.addEventListener("pointercancel", end, { once: true });
  }

  function connectTo(nodeId: string) {
    if (!connectFrom || connectFrom === nodeId) { setConnectFrom(null); return; }
    const outgoing = new Map(document.nodes.map((node) => [node.id, [] as string[]])); document.edges.forEach((edge) => outgoing.get(edge.from)?.push(edge.to));
    const stack = [nodeId]; const visited = new Set<string>();
    while (stack.length) { const current = stack.pop()!; if (current === connectFrom) { setNotice(extra.connectionBlocked); setConnectFrom(null); return; } if (visited.has(current)) continue; visited.add(current); stack.push(...(outgoing.get(current) ?? [])); }
    mutateDocument((current) => current.edges.some((edge) => edge.from === connectFrom && edge.to === nodeId) ? current : updateWorkspace(current, { edges: [...current.edges, { id: workspaceId("edge"), from: connectFrom, to: nodeId }] })); setConnectFrom(null);
  }
  function updateNode(id: string, patch: Partial<WorkspaceNode>) { mutateDocument((current) => updateWorkspace(current, { nodes: current.nodes.map((node) => node.id === id ? { ...node, ...patch } : node) }), false); }
  function removeNode(id: string) { mutateDocument((current) => updateWorkspace(current, { nodes: current.nodes.filter((node) => node.id !== id), edges: current.edges.filter((edge) => edge.from !== id && edge.to !== id) })); setSelectedId(null); }
  function duplicateNode(node: WorkspaceNode) { if (document.nodes.length >= WORKSPACE_MAX_NODES) return; const copy = { ...node, id: workspaceId("node"), title: `${node.title} · 2`, x: node.x + 36, y: node.y + 36, output: "", status: node.input ? "ready" as const : "idle" as const }; mutateDocument((current) => updateWorkspace(current, { nodes: [...current.nodes, copy] })); setSelectedId(copy.id); }
  function removeEdge(id: string) { mutateDocument((current) => updateWorkspace(current, { edges: current.edges.filter((edge) => edge.id !== id) })); }
  function openTool(node: WorkspaceNode) { sessionStorage.setItem(WORKSPACE_ACTIVE_KEY, JSON.stringify(document)); sessionStorage.setItem(WORKSPACE_HANDOFF_KEY, JSON.stringify({ version: 1, workspaceId: document.id, nodeId: node.id, toolSlug: node.toolSlug, input: node.input, output: "", returnPath, completed: false })); }

  function analyzeAgentGoal() { if (agentGoal.trim()) setAgentPlan(createAgentPlan(agentGoal, publicTools, locale)); }
  function applyAgentPlan(mode: "append" | "replace") {
    if (!agentPlan?.steps.length) return;
    const existingCount = mode === "append" ? document.nodes.length : 0;
    if (existingCount + agentPlan.steps.length > WORKSPACE_MAX_NODES) { setNotice(t.max); return; }
    const baseY = mode === "append" ? Math.max(70, ...document.nodes.map((node) => node.y + 190)) : 90;
    const nodes = agentPlan.steps.map((step, index): WorkspaceNode => ({ id: workspaceId("node"), toolSlug: step.toolSlug, title: step.title, x: 48 + index * 300, y: baseY + (index % 2) * 34, input: index === 0 ? (agentPreparedInput || agentPlan.goal) : "", output: "", status: index === 0 ? "ready" : "idle" }));
    const edges = nodes.slice(1).map((node, index) => ({ id: workspaceId("edge"), from: nodes[index].id, to: node.id }));
    mutateDocument((current) => updateWorkspace(current, { name: mode === "replace" ? agentPlan.goal.slice(0, 80) : current.name, nodes: mode === "replace" ? nodes : [...current.nodes, ...nodes], edges: mode === "replace" ? edges : [...current.edges, ...edges] })); setSelectedId(nodes[0]?.id ?? null);
  }

  async function createShareLink() { try { const code = await encodeRecipeInWorker(createWorkspaceRecipe(document, includeInputs)); setShareUrl(`${location.origin}${pathFor(locale, "workstation")}?recipe=${encodeURIComponent(code)}`); } catch { setNotice(t.importError); } }
  async function createProject() { replaceDocument(createWorkspace(locale)); setNotice(""); }
  async function openProject(id: string) { try { replaceDocument(await loadWorkspace(id)); } catch { setSaveState("error"); } }
  async function removeProject(id: string) { if (!window.confirm(t.confirmDelete)) return; await deleteWorkspace(id); if (document.id === id) await createProject(); await refreshProjects(); }
  async function persist() { setNotice(await requestPersistentWorkspaceStorage() ? t.persisted : t.local); }

  return <div className="workstation-app" aria-label={t.title}>
    {onboardingOpen && <div className="workspace-onboarding-overlay" role="presentation"><section role="dialog" aria-modal="true" aria-labelledby="workspace-start-title"><button className="workspace-onboarding-close" type="button" aria-label={extra.dismiss} onClick={dismissOnboarding}>×</button><span className="kicker">BYTEQUANT · START</span><h2 id="workspace-start-title">{extra.onboarding}</h2><p>{extra.onboardingBody}</p><div><Link className="primary-button" href={pathFor(locale, "agent")} onClick={dismissOnboarding}>✦ {extra.withAgent}</Link><button type="button" className="secondary-button" onClick={() => { addTemplate(templateDefinitions[0].slugs, templateDefinitions[0].names[locale]); dismissOnboarding(); }}>⌘ {extra.withTemplate}</button></div><button type="button" className="text-link" onClick={dismissOnboarding}>{extra.dismiss}</button></section></div>}
    <header className="workstation-toolbar"><div><span className="workspace-live-dot" /><strong>{document.name}</strong><small>{saveState === "saving" ? t.saving : saveState === "saved" ? guided.privateSave : saveState === "error" ? t.saveError : t.unsaved}</small></div><label><span className="sr-only">{t.title}</span><input value={document.name} maxLength={100} onChange={(event) => mutateDocument((current) => updateWorkspace(current, { name: event.target.value || t.title }), false)} /></label><div><button type="button" onClick={() => setOnboardingOpen(true)}>? {guided.help}</button><button type="button" onClick={persist}>{t.persist}</button></div></header>
    {!guidedMode && <div className="workspace-commandbar" aria-label={t.canvas}><div><button type="button" onClick={undo} disabled={!past.length} title="Ctrl/⌘ Z">↶ {t.undo}</button><button type="button" onClick={redo} disabled={!future.length} title="Ctrl/⌘ Y">↷ {t.redo}</button><span className="workspace-history-count">v{past.length + 1} · {extra.version}</span><button type="button" onClick={() => mutateDocument(layoutWorkspaceGraph)}>{t.layout}</button><button type="button" onClick={() => { if (window.confirm(t.confirmClear)) { mutateDocument((current) => updateWorkspace(current, { nodes: [], edges: [] })); setSelectedId(null); } }}>{t.clear}</button></div><div className="workspace-health"><span><strong>{summary.nodes}</strong>{t.nodes}</span><span><strong>{summary.edges}</strong>{t.flow}</span><span><strong>{summary.ready}</strong>{t.ready}</span><span><strong>{summary.complete}</strong>{t.complete}</span>{summary.errors > 0 && <span className="error"><strong>{summary.errors}</strong>{t.errors}</span>}</div></div>}
    {notice && <div className="workspace-notice" role="status">{notice}</div>}
    {!document.nodes.length && <section className="workspace-quick-start" id="workspace-start" aria-label={guided.chooseFlow}><div><span>{workspaceFlowCopy[locale].start}</span><strong>{guided.chooseFlow}</strong><small>{guided.chooseFlowBody}</small></div><div>{templateDefinitions.slice(0, 6).map((template) => <button type="button" key={template.id} onClick={() => addTemplate(template.slugs, template.names[locale])}><span>+</span><strong>{template.names[locale]}</strong><small>{template.summaries[locale]}</small></button>)}<Link href={pathFor(locale, "agent")}><span>✦</span><strong>{extra.withAgent}</strong><small>{locale === "tr" ? "Hedefi anlatın; Ajan adımları hazırlasın" : locale === "de" ? "Ziel beschreiben; der Agent bereitet die Schritte vor" : locale === "zh" ? "描述目标，由助手准备步骤" : "Describe the goal and let Agent prepare the steps"}</small></Link></div></section>}
    <div className="workspace-mode-switch"><div><strong>{guidedMode ? (locale === "tr" ? "Adım adım çalışma" : locale === "de" ? "Schritt für Schritt" : locale === "zh" ? "分步操作" : "Step-by-step workspace") : (locale === "tr" ? "Akış düzenleyicisi" : locale === "de" ? "Ablaufeditor" : locale === "zh" ? "流程编辑器" : "Flow editor")}</strong><small>{guidedMode ? (locale === "tr" ? "Sadece hedefi, adımları ve sıradaki işlemi gösterir." : locale === "de" ? "Zeigt nur Ziel, Schritte und die nächste Aktion." : locale === "zh" ? "仅显示目标、步骤与下一项操作。" : "Shows only the outcome, steps, and next action.") : (locale === "tr" ? `Projeler, bağlantılar ve ${publicTools.length} araçlık palet burada düzenlenir.` : locale === "de" ? `Hier werden Projekte, Verbindungen und ${publicTools.length} Werkzeuge bearbeitet.` : locale === "zh" ? `在此编辑项目、连接与 ${publicTools.length} 个工具。` : `Edit projects, connections, and the ${publicTools.length}-tool library here.`)}</small></div><button type="button" onClick={() => setGuidedMode((value) => !value)}>{guidedMode ? guided.editDetails : (locale === "tr" ? "Adım adım görünüme dön" : locale === "de" ? "Zur Schrittansicht" : locale === "zh" ? "返回分步视图" : "Return to step-by-step view")}</button></div>
    {guidedMode && document.nodes.length > 0 && <nav className="workspace-journey" aria-label={guided.overview}>{guided.journey.map((label, index) => { const active = index === 0 ? true : index === 1 ? Boolean(document.nodes[0]?.input) : summary.complete > 0; return <span className={active ? "active" : ""} key={label}><i>{active ? "✓" : index + 1}</i><strong>{label}</strong></span>; })}<small>{guided.deviceOnly}</small></nav>}
    {!guidedMode && <nav className="workspace-mobile-nav" aria-label={t.title}><a href="#workspace-projects">{t.navProjects}</a><a href="#workspace-tools">{t.navTools}</a><a href="#workspace-canvas">{t.navCanvas}</a><a href="#workspace-inspector">{t.navInspector}</a></nav>}
    <div className={`workstation-grid ${guidedMode ? "guided-mode" : "advanced-mode"}`}><aside className="workspace-sidebar">
      <section className="workspace-panel" id="workspace-projects"><div className="workspace-panel-heading"><h3>{t.projects}</h3><button type="button" onClick={createProject}>+ {t.newProject}</button></div><div className="workspace-project-list">{projects.map((project) => <div key={project.id} className={project.id === document.id ? "active" : ""}><button type="button" onClick={() => openProject(project.id)}><strong>{project.name}</strong><small>{project.nodes} {t.nodes} · {new Date(project.updatedAt).toLocaleDateString(locale)}</small></button><button type="button" aria-label={`${t.delete}: ${project.name}`} onClick={() => removeProject(project.id)}>×</button></div>)}</div><small>{t.local}</small></section>
      <section className="workspace-panel workspace-templates"><span className="workspace-panel-kicker">{workspaceFlowCopy[locale].templates}</span><div className="workspace-template-heading"><h3>{t.templates}</h3><span>{visibleTemplates.length}/{templateDefinitions.length}</span></div><label className="workspace-template-search"><span>⌕</span><input type="search" value={templateQuery} onChange={(event) => setTemplateQuery(event.target.value)} placeholder={workspaceFlowCopy[locale].templateSearch} /></label><div>{visibleTemplates.map((template) => <button type="button" key={template.id} onClick={() => addTemplate(template.slugs, template.names[locale])}><i aria-hidden="true">{template.id.slice(0, 2).toLocaleUpperCase()}</i><strong>{template.names[locale]}</strong><span>{template.summaries[locale]}</span><small>{template.slugs.length} {t.nodes} →</small></button>)}</div></section>
      <section className="workspace-panel" id="workspace-tools"><div className="workspace-panel-heading"><h3>{t.palette}</h3><span aria-live="polite">{filteredTools.length}/{publicTools.length}</span></div><div className="workspace-filter-grid"><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t.search} /><select aria-label={t.category} value={category} onChange={(event) => setCategory(event.target.value as "all" | ToolCategory)}><option value="all">{t.category}</option>{Object.entries(categories).map(([id, item]) => <option key={id} value={id}>{item.label[locale]}</option>)}</select></div><p>{t.drag}</p><div className="workspace-tool-palette">{visibleTools.map((tool) => <div key={tool.slug} draggable onDragStart={(event) => event.dataTransfer.setData("application/x-bytequant-tool", tool.slug)}><span className={`tool-mark category-${tool.category}`}>{tool.mark}</span><div><strong>{tool.title[locale]}</strong><small>{categories[tool.category].label[locale]}</small></div><button type="button" onClick={() => addTool(tool.slug)}>{t.add}</button></div>)}</div>{paletteCanCollapse && <button className="workspace-palette-more" type="button" aria-expanded={paletteExpanded} onClick={() => setPaletteExpanded((value) => !value)}>{paletteExpanded ? t.showLess : `${t.showAll} · +${filteredTools.length - visibleTools.length}`}</button>}</section>
    </aside><div className="workspace-main">
      {guidedMode && document.nodes.length > 0 && <section className="workspace-guided-dashboard" aria-labelledby="guided-workspace-title">
        <header className="workspace-guided-header"><div><span className="kicker">{guided.overview}</span><h3 id="guided-workspace-title">{document.name}</h3><p>{guided.privateSave}</p></div><div><span>{summary.complete === document.nodes.length ? guided.allDone : locale === "tr" ? `${currentStage}/${document.nodes.length}. ${guided.stepOf}` : `${currentStage} ${guided.stepOf} ${document.nodes.length}`}</span><progress value={summary.complete} max={Math.max(1, document.nodes.length)} aria-label={workspaceFlowCopy[locale].progress} /></div></header>
        <div className="workspace-guided-layout"><nav className="workspace-guided-steps" aria-label={guided.steps}>{document.nodes.map((node, index) => <button type="button" className={`${guidedNode?.id === node.id ? "active" : ""} status-${node.status}`} key={node.id} onClick={() => setSelectedId(node.id)}><span>{node.status === "complete" ? "✓" : index + 1}</span><div><strong>{node.title}</strong><small>{guided.statusLabel}: {t.status[node.status]}</small></div><i aria-hidden="true">→</i></button>)}</nav>
          <aside className="workspace-guided-action"><span>{guided.nextAction}</span>{guidedNode ? <><div className="workspace-guided-selected"><span className={`tool-mark category-${tools.find((item) => item.slug === guidedNode.toolSlug)?.category ?? "developer"}`}>{tools.find((item) => item.slug === guidedNode.toolSlug)?.mark ?? "BQ"}</span><div><small>{guided.selectedStep}</small><h4>{guidedNode.title}</h4><p>{guidedNode.status === "complete" ? guided.completedInput : guidedNode.input ? guided.readyInput : guided.emptyInput}</p></div></div><label>{t.input}<textarea value={guidedNode.input} placeholder={guided.inputHelp} onChange={(event) => updateNode(guidedNode.id, { input: event.target.value.slice(0, 200_000), status: event.target.value ? "ready" : "idle" })} /></label><div className="workspace-guided-actions"><Link className="primary-button" href={toolPath(locale, guidedNode.toolSlug)} onClick={() => openTool(guidedNode)}>{t.open} →</Link><button type="button" onClick={undo} disabled={!past.length}>↶ {t.undo}</button><button type="button" onClick={redo} disabled={!future.length}>↷ {t.redo}</button></div></> : <p>{t.select}</p>}</aside>
        </div><footer className="workspace-guided-footer"><button type="button" onClick={() => setTemplatePickerOpen((value) => !value)} aria-expanded={templatePickerOpen}>＋ {guided.changeFlow}</button><button type="button" onClick={() => setShowMap((value) => !value)} aria-expanded={showMap}>{showMap ? guided.hideMap : guided.showMap}</button><Link href={pathFor(locale, "agent")}>✦ {workspaceFlowCopy[locale].openAgent}</Link><button type="button" onClick={() => setGuidedMode(false)}>{guided.editDetails} →</button></footer>
      </section>}
      {guidedMode && templatePickerOpen && <section className="workspace-guided-picker" aria-labelledby="workspace-picker-title"><header><div><span className="kicker">BYTEQUANT · FLOW</span><h3 id="workspace-picker-title">{guided.pickerTitle}</h3><p>{guided.pickerBody}</p></div><button type="button" onClick={() => setTemplatePickerOpen(false)}>{guided.cancelPicker}</button></header><div>{templateDefinitions.map((template) => <button type="button" key={template.id} onClick={() => replaceWithTemplate(template.slugs, template.names[locale])}><span>{template.slugs.length}</span><div><strong>{template.names[locale]}</strong><small>{template.summaries[locale]}</small></div><i aria-hidden="true">→</i></button>)}</div></section>}
      <section className="workspace-ai-builder"><div><span className="kicker">BQ LOCAL AGENT · {AGENT_VERSION}</span><h3>{t.ai}</h3><p>{t.aiBoundary}</p><Link className="primary-button" href={pathFor(locale, "agent")}>✦ {workspaceFlowCopy[locale].openAgent} →</Link></div><div className="workspace-ai-input"><textarea value={agentGoal} maxLength={20_000} onChange={(event) => { setAgentGoal(event.target.value); setAgentPreparedInput(""); setAgentPlan(null); }} placeholder={t.aiPlaceholder} /><button type="button" className="primary-button" disabled={!agentGoal.trim()} onClick={analyzeAgentGoal}>{t.analyze}</button></div>{agentPlan && <div className="workspace-ai-preview" aria-live="polite"><header><strong>{t.decision}</strong><span>{Math.round(agentPlan.confidence * 100)}% {t.confidence}</span></header><div className="workspace-ai-frame"><span><small>{locale === "tr" ? "Hedef" : locale === "de" ? "Ziel" : locale === "zh" ? "目标" : "Outcome"}</small>{agentPlan.goalFrame.outcome}</span><span><small>{locale === "tr" ? "Güvenlik sınırı" : locale === "de" ? "Sicherheitsgrenze" : locale === "zh" ? "安全边界" : "Safety boundary"}</small>{agentPlan.goalFrame.safety}</span></div><ol>{agentPlan.steps.map((step, index) => <li key={step.id}><span>{index + 1}</span><div><strong>{step.title}</strong><small>{step.reason}</small></div></li>)}</ol><div className="workspace-ai-signals">{agentPlan.signals.map((signal) => <span key={signal}>{signal}</span>)}</div><ul className="workspace-ai-review">{agentPlan.planReview.map((item) => <li key={item}>✓ {item}</li>)}</ul><footer><button type="button" className="primary-button" onClick={() => applyAgentPlan("append")}>{t.addPlan}</button><button type="button" onClick={() => applyAgentPlan("replace")}>{t.replacePlan}</button></footer></div>}</section>
      {!guidedMode && document.nodes.length > 0 && <section className="workspace-flow-navigator" aria-label={workspaceFlowCopy[locale].navigator}><header><div><span>{workspaceFlowCopy[locale].navigator}</span><strong>{runnableNode ? `${workspaceFlowCopy[locale].next}: ${runnableNode.title}` : workspaceFlowCopy[locale].noNext}</strong></div><small className={isolatedNodes.length ? "warning" : "healthy"}>{isolatedNodes.length ? `${isolatedNodes.length} ${workspaceFlowCopy[locale].isolated}` : workspaceFlowCopy[locale].healthy}</small></header><div>{document.nodes.map((node, index) => <button type="button" className={`${selectedId === node.id ? "active" : ""} status-${node.status}`} key={node.id} onClick={() => focusNode(node)}><span>{index + 1}</span><strong>{node.title}</strong><small>{t.status[node.status]}</small></button>)}</div><footer className="workspace-bridge-actions"><span role="status"><strong>{workspaceFlowCopy[locale].progress}</strong> · {currentStage}/{document.nodes.length}</span><progress value={summary.complete} max={Math.max(1, document.nodes.length)} aria-label={workspaceFlowCopy[locale].progress} />{runnableNode ? runnableNode.status === "ready" ? <Link className="primary-button" href={toolPath(locale, runnableNode.toolSlug)} onClick={() => openTool(runnableNode)}>{workspaceFlowCopy[locale].runNext} →</Link> : <button type="button" className="primary-button" onClick={() => prepareNodeInput(runnableNode)}>{workspaceFlowCopy[locale].addInput} ↓</button> : <strong>{summary.complete === document.nodes.length ? workspaceFlowCopy[locale].finished : workspaceFlowCopy[locale].noNext}</strong>}<Link className="secondary-button" href={pathFor(locale, "agent")}>✦ {workspaceFlowCopy[locale].openAgent}</Link></footer></section>}
      {(!guidedMode || showMap) && <section className="workspace-canvas-shell" id="workspace-canvas" aria-labelledby="canvas-title"><header><div><h3 id="canvas-title">{t.canvas}</h3><small>{connectFrom ? t.connect : `${summary.nodes}/${WORKSPACE_MAX_NODES} ${t.nodes} · ${summary.edges} ${t.flow}`}</small></div><div className="workspace-canvas-controls" aria-label={extra.navigation}><button type="button" onClick={() => setZoom((value) => Math.max(.55, Number((value - .1).toFixed(2))))} aria-label={extra.zoomOut}>−</button><output>{Math.round(zoom * 100)}%</output><button type="button" onClick={() => setZoom((value) => Math.min(1.5, Number((value + .1).toFixed(2))))} aria-label={extra.zoomIn}>+</button><button type="button" onClick={fitView}>{extra.fit}</button><button type="button" onClick={centerSelected} disabled={!selected}>{extra.center}</button><button type="button" className={panMode ? "active" : ""} aria-pressed={panMode} onClick={() => setPanMode((value) => !value)}>✥ {extra.pan}</button></div></header>{connectFrom && <div className="workspace-connect-banner" role="status"><span>●</span><p>{t.connect}</p><button type="button" onClick={() => setConnectFrom(null)}>{workspaceFlowCopy[locale].cancel}</button></div>}<div ref={canvasScrollRef} className={`workspace-canvas-scroll ${panMode ? "pan-active" : ""}`} onPointerDown={beginPan}><div className="workspace-canvas-viewport" style={{ width: canvasSize.width * zoom, height: canvasSize.height * zoom }}><div className="workspace-canvas" style={{ width: canvasSize.width, height: canvasSize.height, transform: `scale(${zoom})` }} onDragOver={(event) => event.preventDefault()} onDrop={dropTool} onClick={() => setConnectFrom(null)}>
        <svg className="workspace-wires" aria-hidden="true">{document.edges.map((edge) => { const from = document.nodes.find((node) => node.id === edge.from); const to = document.nodes.find((node) => node.id === edge.to); if (!from || !to) return null; const x1 = from.x + nodeWidth; const y1 = from.y + nodePortY; const x2 = to.x; const y2 = to.y + nodePortY; return <path key={edge.id} d={`M ${x1} ${y1} C ${x1 + 90} ${y1}, ${x2 - 90} ${y2}, ${x2} ${y2}`} />; })}</svg>
        {!document.nodes.length && <div className="workspace-empty"><span>⌘</span><h4>{extra.emptyTitle}</h4><p>{t.empty}</p><div><Link href={pathFor(locale, "agent")}>✦ {extra.emptyAgent}</Link><button type="button" onClick={(event) => { event.stopPropagation(); addTemplate(templateDefinitions[0].slugs, templateDefinitions[0].names[locale]); }}>+ {extra.emptyTemplate}</button></div></div>}
        {document.nodes.map((node, nodeIndex) => <article key={node.id} className={`workspace-node ${selectedId === node.id ? "selected" : ""} ${connectFrom && connectFrom !== node.id ? "connection-target" : ""} status-${node.status}`} style={{ transform: `translate(${node.x}px, ${node.y}px)` }} onClick={(event) => { event.stopPropagation(); setSelectedId(node.id); }}><button className="workspace-node-handle" type="button" aria-label={`${node.title}: ${t.layout}`} onPointerDown={(event) => beginMove(event, node)}><span className="workspace-node-order">{nodeIndex + 1}</span><span className="workspace-grip">⠿</span><strong>{node.title}</strong><small>{node.toolSlug}</small></button><div className="workspace-node-body"><span>{node.input ? `${node.input.length} ${t.characters}` : t.input}</span><i>→</i><span>{node.output ? `${node.output.length} ${t.characters}` : t.output}</span></div><button className="workspace-port input" type="button" aria-label={`${t.input}: ${node.title}`} onClick={(event) => { event.stopPropagation(); connectTo(node.id); }} /><button className={`workspace-port output ${connectFrom === node.id ? "active" : ""}`} type="button" aria-label={`${t.output}: ${node.title}`} onClick={(event) => { event.stopPropagation(); setConnectFrom(node.id); }} /><footer><span className="workspace-node-status">{t.status[node.status]}</span><Link href={toolPath(locale, node.toolSlug)} onClick={() => openTool(node)}>{t.open} →</Link></footer></article>)}
      </div></div></div>{document.nodes.length > 0 && <button type="button" className="workspace-minimap" aria-label={extra.fit} onClick={fitView}><span>{document.nodes.map((node) => <i key={node.id} className={selectedId === node.id ? "active" : ""} style={{ left: `${Math.min(94, node.x / canvasSize.width * 100)}%`, top: `${Math.min(88, node.y / canvasSize.height * 100)}%` }} />)}</span><b>{Math.round(zoom * 100)}%</b></button>}</section>}
      {!guidedMode && <div className="workspace-lower-grid"><section className="workspace-panel workspace-inspector" id="workspace-inspector"><h3>{t.inspector}</h3>{selected ? <><label>{t.input}<textarea value={selected.input} onChange={(event) => updateNode(selected.id, { input: event.target.value.slice(0, 200_000), status: event.target.value ? "ready" : "idle" })} /></label><label>{t.output}<textarea readOnly value={selected.output} /></label><h4>{t.connections}</h4><div className="workspace-edge-list">{selectedEdges.map((edge) => { const otherId = edge.from === selected.id ? edge.to : edge.from; const other = document.nodes.find((node) => node.id === otherId); return <div key={edge.id}><span>{edge.from === selected.id ? "→" : "←"} {other?.title ?? otherId}</span><button type="button" aria-label={t.disconnect} onClick={() => removeEdge(edge.id)}>×</button></div>; })}{!selectedEdges.length && <small>{t.noConnections}</small>}</div><div><Link className="primary-button" href={toolPath(locale, selected.toolSlug)} onClick={() => openTool(selected)}>{t.open}</Link><button type="button" onClick={() => duplicateNode(selected)}>{t.duplicate}</button><button type="button" onClick={() => removeNode(selected.id)}>{t.remove}</button></div></> : <p>{t.select}</p>}</section>
        <details className="workspace-advanced-options"><summary><span>↗</span><strong>{workspaceFlowCopy[locale].advanced}</strong><b>+</b></summary><div><section className="workspace-panel workspace-recipe-panel"><h3>{t.share}</h3><p>{t.shareSafe}</p><label className="workspace-checkbox"><input type="checkbox" checked={includeInputs} onChange={(event) => setIncludeInputs(event.target.checked)} />{t.include}</label><button type="button" className="secondary-button" onClick={createShareLink}>{t.createLink}</button>{shareUrl && <label><span className="sr-only">URL</span><textarea readOnly value={shareUrl} /><button type="button" onClick={() => navigator.clipboard.writeText(shareUrl)}>{t.copy}</button></label>}</section><WorkspaceP2PPanel locale={locale} document={document} onRemoteDocument={(remote) => replaceDocument(remote)} /></div></details></div>}
    </div></div>
  </div>;
}
