import Link from "next/link";
import { absoluteUrl, languageTag, organizationId, pathFor, siteUrl, websiteId, type Locale } from "../lib/site";
import { SchemaScript } from "./SchemaScript";
import { SiteShell } from "./SiteShell";
import { WorkstationLoader } from "./WorkstationLoader";
import { publicTools as tools } from "../lib/tools";

const content = {
  tr: {
    eyebrow: "GÖRSEL AKIŞLAR · CİHAZINIZDA KALIR · ÜCRETSİZ", title: "Tekrarlanan işleri, takip etmesi kolay görsel akışlara dönüştürün",
    intro: "317 araç arasından seçim yapmak zorunda değilsiniz. Hazır bir sonuç seçin veya hedefinizi Yerel Ajana anlatın; ByteQuant adımları sıralar, ilerlemenizi bu cihazda saklar ve sırada ne yapacağınızı gösterir.",
    cta: "İlk akışımı oluştur", badges: ["Hazır akışlarla hızlı başlangıç", "Değişiklikler cihazınızda saklanır", "Her adım sizin kontrolünüzde"],
    sectionTitle: "İlk akışınızı beş anlaşılır adımda kurun", sectionIntro: "Önce sonucu seçin, ardından her adımı sırayla tamamlayın. Ayrıntılı görsel düzenleyici yalnızca bağlantıları özelleştirmek istediğinizde açılır.",
    guideNote: "En kolay yol: bir hazır akış seçin. Hangi araçlara ihtiyacınız olduğunu bilmiyorsanız hedefinizi Yerel Ajana yazın; uygun adımlar İş İstasyonu'na aktarılır.", guideAction: "Adım adım çalışmaya başla",
    exampleTitle: "Tamamlanmış bir akış nasıl görünür?", exampleIntro: "Örnek: bir CSV listesini gerçek kayıt kullanmadan kontrol edin, hassas sütunları maskeleyin ve temiz sonucu JSON olarak indirmeye hazırlayın. Her adım tek bir açık göreve ve görülebilir bir kabul kontrolüne sahiptir.",
    exampleSteps: [["CSV yapısını kontrol et", "Başlıkları, satır sayısını ve bozuk alanları sentetik bir dosyayla inceleyin. Kabul: sütunlar beklenen adlarla ve aynı satır sayısıyla görünür."], ["Hassas alanları maskele", "E-posta ve telefon gibi seçili alanlara kural uygulayın. Kabul: örnek satırların önce/sonra karşılaştırmasında gerekli bilgi korunurken tanımlayıcı parçalar görünmez."], ["JSON çıktısını doğrula", "Temiz sonucu dönüştürün ve ilk, son, boş değer içeren satırları kaynakla karşılaştırın. Kabul: kayıt sayısı ve alan adları korunur; yalnızca seçilen değerler değişir."]],
    cards: [["01", "Akışınıza isim verin", "Yeni bir çalışma başlatın veya bu cihazda daha önce kaydettiğiniz akışlardan birini açın."], ["02", "İstediğiniz sonucu seçin", "Hazır akışlardan birini seçin. Uygun araçlar sizin için doğru sırada eklenir."], ["03", "İlk veriyi ekleyin", "Metni veya veriyi ilk adıma yapıştırın. İş İstasyonu sıradaki işlemi açıkça gösterir."], ["04", "Adımları sırayla tamamlayın", "Aracı açın, sonucu üretin ve akışa dönün. Çıktı sonraki adıma kendiliğinden aktarılır."], ["05", "Kaydedin veya paylaşın", "İlerlemeniz cihazınızda otomatik saklanır. Paylaşacağınız içeriği her zaman siz seçersiniz."]],
    boundariesTitle: "Paylaşmadan önce bilmeniz gerekenler", boundaries: ["Canlı paylaşım kodları 10 dakika geçerlidir. Bağlanmadan önce ekrandaki güvenlik kodunu diğer kişiyle ayrı bir kanaldan karşılaştırın.", "Bazı kurumsal veya sıkı ağlar doğrudan bağlantıyı engelleyebilir. Böyle bir durumda cihazdaki proje ve paylaşım bağlantısı seçenekleri çalışmaya devam eder.", "Paylaşım bağlantıları sonuçları içermez. Girdiler de yalnızca siz özellikle seçerseniz bağlantıya eklenir.", "Projeler bu cihazda şifreli saklanır. Ortak veya güvenliği ihlal edilmiş bir cihaz kullanıyorsanız hassas veri eklemeyin."],
    faq: [["Hangi araçları seçmem gerekiyor?", "Bilmeniz gerekmiyor. Hazır bir akış seçin veya hedefinizi Yerel Ajana anlatın; uygun araçlar sırayla hazırlanır."], ["Canlı paylaşım güvenli mi?", "Bağlantı doğrudan tarayıcılar arasında kurulur. Yine de güvenlik kodunu diğer kişiyle ayrı bir kanaldan karşılaştırmalı ve tanımadığınız kişilere hassas veri göndermemelisiniz."], ["Projeler buluta yazılıyor mu?", "Hayır. Projeler bu tarayıcıda, cihazınıza bağlı yerel alanda saklanır ve kendiliğinden başka yere gönderilmez."], ["Yerel Ajan araçları kendi başına çalıştırır mı?", "Hayır. Ajan adımları hazırlar; dosya seçme, aracı çalıştırma, indirme ve sonucu kabul etme kararları sizde kalır."]],
  },
  en: {
    eyebrow: "VISUAL FLOWS · STAYS ON YOUR DEVICE · FREE", title: "Turn repeated tasks into visual flows that are easy to follow",
    intro: "You do not need to choose from 317 tools yourself. Pick a ready-made outcome or tell Local Agent what you need; ByteQuant orders the steps, saves progress on this device, and shows what to do next.",
    cta: "Create my first flow", badges: ["Start quickly with ready-made flows", "Changes stay on your device", "You approve every step"],
    sectionTitle: "Build your first flow in five clear steps", sectionIntro: "Choose the outcome, then complete one step at a time. The detailed visual editor appears only when you want to customize connections.",
    guideNote: "The easiest route is to choose a ready-made flow. If you do not know which tools you need, describe the goal to Local Agent and transfer the prepared steps here.", guideAction: "Start step by step",
    exampleTitle: "What does a completed flow look like?", exampleIntro: "Example: inspect a CSV list without using real records, mask selected sensitive columns, and prepare the clean result for JSON download. Every step has one clear job and a visible acceptance check.",
    exampleSteps: [["Inspect the CSV structure", "Use a synthetic file to review headings, row count, and malformed fields. Accept when the expected columns and unchanged row count are visible."], ["Mask sensitive fields", "Apply a rule to selected fields such as email and phone. Accept when the before/after comparison hides identifying fragments while preserving the information needed for the task."], ["Validate the JSON result", "Convert the clean data and compare the first, last, and empty-value rows with the source. Accept when record count and field names remain intact and only selected values changed."]],
    cards: [["01", "Name your flow", "Start a new workspace or open a flow you previously saved on this device."], ["02", "Choose the outcome", "Pick a ready-made flow and the right tools are added in a practical order."], ["03", "Add the first data", "Paste the text or data into the first step. Workstation makes the next action clear."], ["04", "Complete one step at a time", "Open the tool, produce the result, and return. The output moves to the next step automatically."], ["05", "Save or share", "Progress is saved automatically on your device. You always choose what, if anything, is shared."]],
    boundariesTitle: "What to know before sharing", boundaries: ["Live-sharing codes work for 10 minutes. Compare the safety code with the other person through a separate channel before connecting.", "Some corporate or restrictive networks may block a direct connection. Your on-device project and share-link options still remain available.", "Share links never contain results. Inputs are included only when you explicitly choose that option.", "Projects are encrypted on this device. Avoid sensitive data on shared or compromised devices."],
    faq: [["Which tools do I need to choose?", "You do not need to know. Pick a ready-made flow or describe the goal to Local Agent and the relevant tools will be arranged in order."], ["Is live sharing safe?", "The connection is direct between browsers. Compare the safety code separately and never send sensitive data to someone you do not trust."], ["Do projects go to the cloud?", "No. Projects stay in local storage tied to this browser and do not leave automatically."], ["Can Local Agent run tools by itself?", "No. Agent prepares the steps; file selection, tool runs, downloads, and accepting results stay under your control."]],
  },
  de: {
    eyebrow: "VISUELLE ABLÄUFE · BLEIBT AUF IHREM GERÄT · KOSTENLOS", title: "Wiederkehrende Aufgaben in leicht verständliche visuelle Abläufe verwandeln",
    intro: "Sie müssen nicht selbst unter 317 Werkzeugen wählen. Nehmen Sie ein fertiges Ergebnis oder beschreiben Sie dem lokalen Agenten Ihr Ziel; ByteQuant ordnet die Schritte, speichert den Stand lokal und zeigt die nächste Aktion.",
    cta: "Ersten Ablauf erstellen", badges: ["Schneller Start mit Vorlagen", "Änderungen bleiben auf Ihrem Gerät", "Jeder Schritt unter Ihrer Kontrolle"],
    sectionTitle: "Den ersten Ablauf in fünf klaren Schritten erstellen", sectionIntro: "Wählen Sie zuerst das Ergebnis und erledigen Sie danach einen Schritt nach dem anderen. Der detaillierte Editor erscheint nur zum Anpassen von Verbindungen.",
    guideNote: "Am einfachsten wählen Sie einen fertigen Ablauf. Wenn die passenden Werkzeuge noch unklar sind, beschreiben Sie dem lokalen Agenten das Ziel und übertragen die vorbereiteten Schritte hierher.", guideAction: "Schrittweise beginnen",
    exampleTitle: "Wie sieht ein abgeschlossener Ablauf aus?", exampleIntro: "Beispiel: Eine CSV-Liste ohne echte Datensätze prüfen, ausgewählte sensible Spalten maskieren und das bereinigte Ergebnis für einen JSON-Download vorbereiten. Jeder Schritt hat genau eine Aufgabe und ein sichtbares Abnahmekriterium.",
    exampleSteps: [["CSV-Struktur prüfen", "Mit einer synthetischen Datei Überschriften, Zeilenzahl und fehlerhafte Felder untersuchen. Abnahme: erwartete Spalten und unveränderte Zeilenzahl sind sichtbar."], ["Sensible Felder maskieren", "Auf ausgewählte Felder wie E-Mail und Telefon eine Regel anwenden. Abnahme: Der Vorher-Nachher-Vergleich verbirgt identifizierende Teile und erhält die benötigte Information."], ["JSON-Ergebnis validieren", "Bereinigte Daten umwandeln und erste, letzte sowie leere Zeilen mit der Quelle vergleichen. Abnahme: Datensatzanzahl und Feldnamen bleiben erhalten; nur ausgewählte Werte ändern sich."]],
    cards: [["01", "Ablauf benennen", "Starten Sie einen neuen Arbeitsbereich oder öffnen Sie einen zuvor auf diesem Gerät gespeicherten Ablauf."], ["02", "Ergebnis auswählen", "Wählen Sie einen fertigen Ablauf; die passenden Werkzeuge werden in sinnvoller Reihenfolge ergänzt."], ["03", "Erste Daten eingeben", "Fügen Sie Text oder Daten in den ersten Schritt ein. Die Workstation zeigt die nächste Aktion klar an."], ["04", "Schrittweise abschließen", "Werkzeug öffnen, Ergebnis erzeugen und zurückkehren. Die Ausgabe wird automatisch an den nächsten Schritt übergeben."], ["05", "Speichern oder teilen", "Der Fortschritt wird auf Ihrem Gerät gespeichert. Sie entscheiden jederzeit, was geteilt wird."]],
    boundariesTitle: "Was Sie vor dem Teilen wissen sollten", boundaries: ["Codes für Live-Freigaben gelten zehn Minuten. Vergleichen Sie vor der Verbindung den Sicherheitscode über einen getrennten Kanal.", "Manche Firmen- oder Schutznetzwerke blockieren direkte Verbindungen. Das lokale Projekt und Freigabelinks bleiben weiterhin nutzbar.", "Freigabelinks enthalten nie Ergebnisse. Eingaben werden nur nach Ihrer ausdrücklichen Auswahl aufgenommen.", "Projekte werden auf diesem Gerät verschlüsselt. Verwenden Sie auf gemeinsam genutzten oder unsicheren Geräten keine sensiblen Daten."],
    faq: [["Welche Werkzeuge muss ich auswählen?", "Sie müssen das nicht wissen. Wählen Sie einen fertigen Ablauf oder beschreiben Sie dem lokalen Agenten das Ziel; passende Werkzeuge werden geordnet."], ["Ist die Live-Freigabe sicher?", "Die Verbindung läuft direkt zwischen Browsern. Vergleichen Sie den Sicherheitscode getrennt und senden Sie Unbekannten keine sensiblen Daten."], ["Werden Projekte in die Cloud geschrieben?", "Nein. Projekte bleiben im lokalen Speicher dieses Browsers und werden nicht automatisch übertragen."], ["Startet der lokale Agent Werkzeuge selbstständig?", "Nein. Er bereitet die Schritte vor; Dateiauswahl, Ausführung, Download und Ergebnisannahme bleiben unter Ihrer Kontrolle."]],
  },
  zh: {
    eyebrow: "可视化流程 · 保存在本设备 · 免费", title: "把重复任务变成清晰易懂的可视化流程",
    intro: "无需自己从 317 个工具中挑选。选择现成目标，或向本地助手描述需求；ByteQuant 会排列步骤、在本设备保存进度，并提示下一步操作。",
    cta: "创建第一个流程", badges: ["使用现成流程快速开始", "更改保存在本设备", "每一步都由您确认"],
    sectionTitle: "通过五个清晰步骤建立首个流程", sectionIntro: "先选择目标，再逐步完成。只有需要自定义连接时，才打开详细的可视化编辑器。",
    guideNote: "最简单的方法是选择现成流程。如果不确定需要哪些工具，请向本地助手描述目标，再把准备好的步骤传到这里。", guideAction: "开始分步操作",
    exampleTitle: "完成后的流程是什么样？", exampleIntro: "示例：不使用真实记录，先检查 CSV 列表，再遮蔽选定的敏感列，最后准备可下载的 JSON 结果。每一步只负责一项明确任务，并提供可见的验收条件。",
    exampleSteps: [["检查 CSV 结构", "使用合成文件检查表头、行数和错误字段。验收条件：预期列名可见，且处理前后行数不变。"], ["遮蔽敏感字段", "对邮箱、电话等选定字段应用规则。验收条件：前后对比中可识别片段被隐藏，同时保留任务所需信息。"], ["核验 JSON 结果", "转换清理后的数据，并把首行、末行和空值行与来源比较。验收条件：记录数量和字段名保持不变，只有选定值发生变化。"]],
    cards: [["01", "为流程命名", "新建工作区，或打开之前保存在此设备上的流程。"], ["02", "选择目标", "选择现成流程，合适的工具会按实用顺序自动加入。"], ["03", "添加第一份数据", "把文本或数据放入第一步；工作站会清楚提示下一项操作。"], ["04", "逐步完成", "打开工具、生成结果并返回；输出会自动交给下一步。"], ["05", "保存或分享", "进度会自动保存在本设备上；是否分享以及分享什么始终由您决定。"]],
    boundariesTitle: "分享前需要了解的事项", boundaries: ["实时分享代码有效期为 10 分钟。连接前，请通过另一渠道与对方核对安全码。", "部分企业或受限网络可能阻止直接连接；设备端项目与分享链接仍可继续使用。", "分享链接绝不会包含结果；只有在您明确选择时才会包含输入。", "项目会在本设备加密保存；请勿在共用或不安全的设备上加入敏感数据。"],
    faq: [["我需要自己选择哪些工具？", "不需要。选择现成流程，或向本地助手描述目标，系统会按顺序准备合适工具。"], ["实时分享安全吗？", "连接在浏览器之间直接建立。请另行核对安全码，不要向不信任的人发送敏感数据。"], ["项目会写入云端吗？", "不会。项目保存在此浏览器的本地空间，不会自动传到其他地方。"], ["本地助手会自行运行工具吗？", "不会。助手负责准备步骤；文件选择、运行、下载与接受结果仍由您决定。"]],
  },
} as const;

export function WorkstationPage({ locale, importer = false }: { locale: Locale; importer?: boolean }) {
  const raw = content[locale];
  const currentToolCount = String(tools.length);
  const updateCount = (value: string) => value.replace(/\b(?:89|211|234|309|317)\b/u, currentToolCount);
  const c = { ...raw, title: updateCount(raw.title), intro: updateCount(raw.intro), cards: raw.cards.map((card) => [card[0], card[1], updateCount(card[2])] as const) };
  const pagePath = importer ? "/workspace" : pathFor(locale, "workstation");
  const pageUrl = absoluteUrl(pagePath);
  const schema = importer ? [] : [
    { "@context": "https://schema.org", "@type": "WebApplication", "@id": `${pageUrl}#application`, name: `ByteQuant ${locale === "tr" ? "İş İstasyonu" : "Workstation"}`, url: pageUrl, description: c.intro, applicationCategory: "DeveloperApplication", operatingSystem: "Any modern browser", browserRequirements: "JavaScript, IndexedDB, Web Crypto; WebRTC optional", inLanguage: languageTag(locale), isAccessibleForFree: true, creator: { "@id": organizationId }, isPartOf: { "@id": websiteId }, featureList: c.cards.map((card) => card[1]), offers: { "@type": "Offer", price: "0", priceCurrency: "USD" } },
    { "@context": "https://schema.org", "@type": "HowTo", name: c.title, totalTime: "PT5M", inLanguage: languageTag(locale), step: c.cards.map((card, index) => ({ "@type": "HowToStep", position: index + 1, name: card[1], text: card[2], url: `${pageUrl}#step-${index + 1}` })) },
    { "@context": "https://schema.org", "@type": "FAQPage", inLanguage: languageTag(locale), mainEntity: c.faq.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) },
    { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: locale === "tr" ? "Ana sayfa" : "Home", item: absoluteUrl(pathFor(locale, "home")) }, { "@type": "ListItem", position: 2, name: c.title, item: pageUrl }] },
  ];
  return <SiteShell locale={locale} alternateHref={pathFor(locale === "tr" ? "en" : "tr", "workstation")} languageHrefs={{ tr: pathFor("tr", "workstation"), en: pathFor("en", "workstation"), de: pathFor("de", "workstation"), zh: pathFor("zh", "workstation") }}>
    {schema.length > 0 && <SchemaScript data={schema} />}
    <section className="workstation-hero"><div className="container workstation-hero-grid"><div><span className="eyebrow"><i />{c.eyebrow}</span><h1>{c.title}</h1><p>{c.intro}</p><div className="workstation-badges">{c.badges.map((badge) => <span key={badge}>✓ {badge}</span>)}</div><div className="product-hero-actions"><a className="primary-button workstation-launch-button" href="#workstation-app"><b aria-hidden="true">1</b><span>{c.cta}</span><i aria-hidden="true">→</i></a><Link className="secondary-button product-cross-link" href={pathFor(locale, "agent")}><span>{locale === "tr" ? "Hedefimi Ajana anlat" : locale === "de" ? "Ziel dem Agenten beschreiben" : locale === "zh" ? "向助手描述目标" : "Describe my goal to Agent"}</span><i aria-hidden="true">✦</i></Link></div></div><div className="workstation-hero-visual" aria-hidden="true"><span className="hero-node n1">1 · {locale === "tr" ? "SEÇ" : locale === "de" ? "WÄHLEN" : locale === "zh" ? "选择" : "CHOOSE"}</span><span className="hero-node n2">2 · {locale === "tr" ? "İŞLE" : locale === "de" ? "START" : locale === "zh" ? "处理" : "RUN"}</span><span className="hero-node n3">3 · {locale === "tr" ? "BİTİR" : locale === "de" ? "FERTIG" : locale === "zh" ? "完成" : "FINISH"}</span><i className="hero-wire w1" /><i className="hero-wire w2" /><b>BQ<br /><small>FLOW</small></b></div></div></section>
    <section id="workstation-app" className="workstation-app-section"><div className="container workstation-app-container"><WorkstationLoader locale={locale} /></div></section>
    <section className="section workstation-example"><div className="container"><div className="section-heading split-heading"><div><span className="kicker">{locale === "tr" ? "UÇTAN UCA ÖRNEK" : locale === "de" ? "DURCHGÄNGIGES BEISPIEL" : locale === "zh" ? "端到端示例" : "END-TO-END EXAMPLE"}</span><h2>{c.exampleTitle}</h2></div><p>{c.exampleIntro}</p></div><ol>{c.exampleSteps.map(([title, body], index) => <li key={title}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{title}</h3><p>{body}</p></div></li>)}</ol></div></section>
    <section className="section workstation-explain"><div className="container"><div className="section-heading split-heading"><div><span className="kicker">{locale === "tr" ? "BYTEQUANT · ADIM ADIM AKIŞLAR" : locale === "de" ? "BYTEQUANT · SCHRITTWEISE ABLÄUFE" : locale === "zh" ? "BYTEQUANT · 分步流程" : "BYTEQUANT · STEP-BY-STEP FLOWS"}</span><h2>{c.sectionTitle}</h2></div><p>{c.sectionIntro}</p></div><div className="workstation-guide-callout"><span aria-hidden="true">→</span><p>{c.guideNote}</p><a href="#workstation-app">{c.guideAction} ↑</a></div><ol className="workstation-feature-grid">{c.cards.map((card, index) => <li id={`step-${index + 1}`} key={card[0]}><span>{card[0]}</span><h3>{card[1]}</h3><p>{card[2]}</p></li>)}</ol></div></section>
    <section className="section workstation-boundaries"><div className="container workstation-boundary-grid"><div><span className="kicker">TRUST BOUNDARY</span><h2>{c.boundariesTitle}</h2><p>{c.intro}</p><Link className="text-link" href={pathFor(locale, "privacy")}>{locale === "tr" ? "Gizlilik politikasını inceleyin" : locale === "de" ? "Datenschutz lesen" : locale === "zh" ? "阅读隐私政策" : "Read the privacy policy"} →</Link></div><ol>{c.boundaries.map((boundary, index) => <li key={boundary}><span>{String(index + 1).padStart(2, "0")}</span><p>{boundary}</p></li>)}</ol></div></section>
    <section className="section faq-section"><div className="container faq-layout"><div><span className="kicker">FAQ</span><h2>{locale === "tr" ? "İş istasyonu hakkında" : locale === "de" ? "Über die Workstation" : locale === "zh" ? "关于工作站" : "About Workstation"}</h2><p>{c.sectionIntro}</p></div><div className="faq-list">{c.faq.map(([question, answer], index) => <details key={question} open={index === 0}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></div></section>
    <section className="cta-band"><div className="container"><div><span>{siteUrl.replace("https://", "").toUpperCase()} · LOCAL-FIRST</span><h2>{c.title}</h2></div><a className="light-button" href="#workstation-app">{c.cta} →</a></div></section>
  </SiteShell>;
}
