import Link from "next/link";
import { absoluteUrl, languageTag, organizationId, pathFor, siteUrl, websiteId, type Locale } from "../lib/site";
import { SchemaScript } from "./SchemaScript";
import { SiteShell } from "./SiteShell";
import { WorkstationLoader } from "./WorkstationLoader";
import { tools } from "../lib/tools";

const content = {
  tr: {
    eyebrow: "GÖRSEL AKIŞ · ŞİFRELİ PROJELER · SUNUCUSUZ P2P", title: "89 tarayıcı aracını görsel bir geliştirme ortamında birbirine bağlayın",
    intro: "ByteQuant İş İstasyonu; araçları düğüm olarak düzenler, çıktıyı bağlı girdiye taşır, projeleri cihazınızda AES-GCM ile şifreler ve tarifleri veritabanı olmadan paylaşır.",
    cta: "İş istasyonunu aç", badges: ["İlk yükte ağır canvas kodu yok", "IndexedDB + Web Crypto", "WebRTC DataChannel"],
    sectionTitle: "İlk akışınızı beş kontrollü adımda kurun", sectionIntro: "Araçların çekirdek davranışları aynen korunur. İş İstasyonu keşif, düzenleme, veri aktarımı ve yerel kalıcılığı koordine eder; her araç çalıştırma adımı yine kullanıcı eylemi ister.",
    guideNote: "Hızlı başlangıç: Hazır bir akış seçebilir veya Yerel Ajana hedefinizi yazabilirsiniz. Plan tuvale eklenmeden önce adımları ve seçim gerekçelerini görürsünüz.", guideAction: "Doğrudan çalışma alanına geç",
    cards: [["01", "Projenizi adlandırın", "Yeni bir proje açın veya bu cihazda şifreli saklanan önceki bir projeyi seçin. Proje adı ve durum üst çubukta görünür."], ["02", "Araçları ekleyin", "Başlangıç akışlarından birini seçin ya da 89 araçlık palette arama ve kategori filtresini kullanarak düğümleri tuvale ekleyin."], ["03", "Planlayın ve bağlayın", "Yerel Ajan planının güvenini ve seçim gerekçelerini inceleyin; ardından bir çıkış portunu hedef giriş portuna bağlayın."], ["04", "Araçta çalıştırıp dönün", "Düğümdeki 'Araçta çalıştır' bağlantısını açın. Girdiyi onaylayın, aracı kendiniz çalıştırın ve sonucu aynı sekmede düğüme geri taşıyın."], ["05", "Kaydedin veya güvenle paylaşın", "Proje cihazınızda otomatik şifrelenir. URL tarifinde girdiler varsayılan olarak kapalıdır; P2P paylaşımında güvenlik kodunu ayrı kanalda doğrulayın."]],
    boundariesTitle: "Sunucusuz mimarinin dürüst sınırları", boundaries: ["P2P kodları 10 dakika içinde geçersiz olur; bağlantıdan sonra güvenlik kodu ayrı bir kanalda karşılaştırılmadan canlı paylaşım açılamaz.", "Bazı NAT ve firewall kombinasyonları aynı yerel ağ dışında bağlantıyı engeller. ByteQuant bunu aşmak için gizli bir sunucuya geri dönmez.", "URL tarifleri varsayılan olarak girdileri ve her zaman çıktıları çıkarır. Girdiyi bağlantıya eklemek açık kullanıcı seçimi gerektirir.", "IndexedDB kayıtları AES-GCM ile şifrelidir; bu, ele geçirilmiş cihaz veya aynı origin'de çalışan zararlı kod için tam güvenlik garantisi değildir."],
    faq: [["React Flow veya başka bir kütüphane kullanılıyor mu?", "Hayır. Canvas, hafif HTML/SVG ve Pointer Events ile çalışır; yeni üçüncü taraf bağımlılık eklenmez."], ["P2P güvenlik kodu kimlik doğrulaması mı?", "Hayır. Kod iki DTLS parmak izinin aynı oturuma ait olduğunu karşılaştırmaya yardım eder; kişinin gerçek kimliğini kanıtlamaz. Kod ayrı kanalda eşleştirilmeden canlı paylaşım açılamaz."], ["Projeler buluta yazılıyor mu?", "Hayır. Şifreli proje kayıtları yalnızca tarayıcınızın IndexedDB alanındadır ve bu cihazdan otomatik çıkmaz."], ["Yerel Ajan araçları kendi başına çalıştırır mı?", "Hayır. Ajan plan güvenini ve gerekçesini gösterir; dosya seçme, araç çalıştırma, indirme ve sonuç kabulü kullanıcı eylemi gerektirir."]],
  },
  en: {
    eyebrow: "VISUAL FLOWS · ENCRYPTED PROJECTS · SERVERLESS P2P", title: "Connect 89 browser tools inside a visual development environment",
    intro: "ByteQuant Workstation arranges tools as nodes, passes output to connected input, encrypts projects on-device with AES-GCM, and shares recipes without a database.",
    cta: "Open the workstation", badges: ["No heavy canvas code on first load", "IndexedDB + Web Crypto", "WebRTC DataChannel"],
    sectionTitle: "Build your first workflow in five controlled steps", sectionIntro: "Core tool behavior remains unchanged. Workstation coordinates discovery, layout, handoff, and local persistence; every tool run still requires user action.",
    guideNote: "Quick start: choose a starter flow or describe the outcome to Local Agent. You see every step and selection reason before a plan reaches the canvas.", guideAction: "Jump to the workspace",
    cards: [["01", "Name your project", "Start a new project or choose one already stored encrypted on this device. Its name and save state stay visible in the top bar."], ["02", "Add tools", "Choose a starter flow or search and filter the 89-tool palette before adding nodes to the canvas."], ["03", "Plan and connect", "Review Local Agent confidence and selection reasons, then connect an output port to the intended input port."], ["04", "Run the tool and return", "Open 'Run in tool' from a node. Approve the input, run the tool yourself, and bring the result back to the node in the same tab."], ["05", "Save or share safely", "The project is encrypted automatically on-device. Recipe inputs are off by default; for P2P, compare the safety code through another channel."]],
    boundariesTitle: "Honest boundaries of a serverless architecture", boundaries: ["P2P codes expire after 10 minutes; live sharing stays locked until people compare the safety code through another channel.", "Some NAT and firewall combinations cannot connect outside the same local network. ByteQuant never hides that with a server fallback.", "URL recipes exclude inputs by default and always exclude output. Including input requires an explicit user choice.", "IndexedDB records use AES-GCM at rest; this cannot guarantee safety on a compromised device or against malicious same-origin code."],
    faq: [["Does this use React Flow or another library?", "No. The canvas uses lightweight HTML/SVG and Pointer Events, adding no third-party dependency."], ["Is the P2P safety code identity verification?", "No. It helps compare that both DTLS fingerprints belong to the same session; it does not prove a person's identity. Live sharing stays locked until the code is compared through another channel."], ["Do projects go to the cloud?", "No. Encrypted records stay only in this browser's IndexedDB and never leave automatically."], ["Can Local Agent run tools autonomously?", "No. It shows plan confidence and selection reasons; file selection, execution, downloads, and result acceptance require user action."]],
  },
  de: {
    eyebrow: "VISUELLE ABLÄUFE · VERSCHLÜSSELTE PROJEKTE · SERVERLOSES P2P", title: "89 Browser-Werkzeuge in einer visuellen Entwicklungsumgebung verbinden",
    intro: "ByteQuant Workstation ordnet Werkzeuge als Knoten an, übergibt Ausgaben an verbundene Eingaben, verschlüsselt Projekte lokal mit AES-GCM und teilt Rezepte ohne Datenbank.",
    cta: "Workstation öffnen", badges: ["Kein schwerer Canvas-Code beim Erstaufruf", "IndexedDB + Web Crypto", "WebRTC DataChannel"],
    sectionTitle: "Den ersten Ablauf in fünf kontrollierten Schritten erstellen", sectionIntro: "Die Kernfunktionen bleiben unverändert. Die Workstation koordiniert Suche, Anordnung, Übergabe und lokale Speicherung; jeder Werkzeugstart erfordert weiterhin eine Nutzeraktion.",
    guideNote: "Schnellstart: Startablauf wählen oder dem lokalen Agenten das Ziel beschreiben. Schritte und Auswahlgründe sind sichtbar, bevor ein Plan auf die Fläche gelangt.", guideAction: "Direkt zum Arbeitsbereich",
    cards: [["01", "Projekt benennen", "Neues Projekt starten oder ein auf diesem Gerät verschlüsselt gespeichertes Projekt wählen. Name und Speicherstatus bleiben oben sichtbar."], ["02", "Werkzeuge hinzufügen", "Startablauf wählen oder die Palette mit 89 Werkzeugen durchsuchen und filtern, bevor Knoten zur Fläche kommen."], ["03", "Planen und verbinden", "Konfidenz und Auswahlgründe des lokalen Agenten prüfen; danach einen Ausgang mit dem vorgesehenen Eingang verbinden."], ["04", "Im Werkzeug ausführen", "Über 'Im Werkzeug ausführen' öffnen, Eingabe prüfen, Werkzeug selbst starten und das Ergebnis im selben Tab zum Knoten zurückführen."], ["05", "Sicher speichern oder teilen", "Das Projekt wird lokal automatisch verschlüsselt. Rezept-Eingaben sind standardmäßig aus; bei P2P den Sicherheitscode separat vergleichen."]],
    boundariesTitle: "Ehrliche Grenzen der serverlosen Architektur", boundaries: ["P2P-Codes verfallen nach 10 Minuten; die Live-Freigabe bleibt gesperrt, bis der Sicherheitscode über einen zweiten Kanal verglichen wurde.", "Manche NAT-/Firewall-Kombinationen verhindern Verbindungen außerhalb desselben LAN. Es gibt keinen versteckten Server-Fallback.", "URL-Rezepte schließen Eingaben standardmäßig und Ausgaben immer aus.", "AES-GCM schützt IndexedDB-Daten im Ruhezustand, garantiert aber keinen Schutz auf kompromittierten Geräten oder vor bösartigem Same-Origin-Code."],
    faq: [["Wird React Flow verwendet?", "Nein. Die Oberfläche nutzt leichtes HTML/SVG und Pointer Events ohne neue Drittanbieterabhängigkeit."], ["Ist der P2P-Sicherheitscode eine Identitätsprüfung?", "Nein. Er hilft beim Vergleich beider DTLS-Fingerprints derselben Sitzung, beweist aber keine reale Person. Ohne Vergleich über einen zweiten Kanal bleibt die Freigabe gesperrt."], ["Werden Projekte in die Cloud geschrieben?", "Nein. Verschlüsselte Einträge bleiben ausschließlich im IndexedDB dieses Browsers."], ["Startet der lokale Agent Werkzeuge selbstständig?", "Nein. Er zeigt Konfidenz und Auswahlgründe; Auswahl, Ausführung und Übernahme bleiben Nutzeraktionen."]],
  },
  zh: {
    eyebrow: "可视化流程 · 加密项目 · 无服务器 P2P", title: "在可视化开发环境中连接 89 个浏览器工具",
    intro: "ByteQuant 工作站把工具排列为节点，将输出传给相连输入，使用 AES-GCM 在设备上加密项目，并在无数据库的情况下分享配方。",
    cta: "打开工作站", badges: ["首屏不加载重型画布代码", "IndexedDB + Web Crypto", "WebRTC DataChannel"],
    sectionTitle: "通过五个可控步骤建立首个流程", sectionIntro: "工具核心行为保持不变。工作站只协调发现、布局、交接和本地持久化；每次运行仍需用户操作。",
    guideNote: "快速开始：选择起始流程，或向本地助手描述目标。计划进入画布之前，您会看到每一步与选择依据。", guideAction: "直接进入工作区",
    cards: [["01", "命名项目", "新建项目，或选择已在此设备加密保存的项目；名称与保存状态会持续显示在顶部。"], ["02", "添加工具", "选择起始流程，或在 89 个工具的面板中搜索和筛选，再把节点加入画布。"], ["03", "规划并连接", "查看本地助手的置信度与选择理由，然后把输出端口连接到目标输入端口。"], ["04", "运行工具并返回", "从节点打开“在工具中运行”，确认输入、亲自执行，并在同一标签页把结果带回节点。"], ["05", "安全保存或分享", "项目会在设备上自动加密。配方默认不包含输入；P2P 分享前请通过另一渠道核对安全码。"]],
    boundariesTitle: "无服务器架构的真实边界", boundaries: ["P2P 代码 10 分钟后失效；双方通过另一渠道核对安全码之前，实时共享保持锁定。", "部分 NAT/防火墙组合无法在同一局域网之外连接；ByteQuant 不会偷偷回退到服务器。", "URL 配方默认排除输入，并始终排除输出；加入输入必须明确选择。", "IndexedDB 记录使用 AES-GCM 静态加密，但无法保证受感染设备或恶意同源代码下的安全。"],
    faq: [["是否使用 React Flow？", "否。画布使用轻量 HTML/SVG 和 Pointer Events，不增加第三方依赖。"], ["P2P 安全码等于身份验证吗？", "不等于。它帮助核对双方 DTLS 指纹属于同一会话，但不能证明真实身份；通过另一渠道核对之前，实时共享保持锁定。"], ["项目会写入云端吗？", "不会。加密记录只保存在此浏览器的 IndexedDB。"], ["本地助手会自动运行工具吗？", "不会。它显示计划置信度与选择理由；文件选择、运行、下载和结果确认都需要用户操作。"]],
  },
} as const;

export function WorkstationPage({ locale, importer = false }: { locale: Locale; importer?: boolean }) {
  const raw = content[locale];
  const c = { ...raw, title: raw.title.replace("89", String(tools.length)), cards: raw.cards.map((card) => [card[0], card[1], card[2].replace("89", String(tools.length))] as const) };
  const pagePath = importer ? "/workspace" : pathFor(locale, "workstation");
  const pageUrl = absoluteUrl(pagePath);
  const schema = importer ? [] : [
    { "@context": "https://schema.org", "@type": "WebApplication", "@id": `${pageUrl}#application`, name: `ByteQuant ${locale === "tr" ? "İş İstasyonu" : "Workstation"}`, url: pageUrl, description: c.intro, applicationCategory: "DeveloperApplication", operatingSystem: "Any modern browser", browserRequirements: "JavaScript, IndexedDB, Web Crypto; WebRTC optional", inLanguage: languageTag(locale), isAccessibleForFree: true, creator: { "@id": organizationId }, isPartOf: { "@id": websiteId }, featureList: c.cards.map((card) => card[1]), offers: { "@type": "Offer", price: "0", priceCurrency: "USD" } },
    { "@context": "https://schema.org", "@type": "HowTo", name: c.title, totalTime: "PT5M", inLanguage: languageTag(locale), step: c.cards.map((card, index) => ({ "@type": "HowToStep", position: index + 1, name: card[1], text: card[2], url: `${pageUrl}#step-${index + 1}` })) },
    { "@context": "https://schema.org", "@type": "FAQPage", inLanguage: languageTag(locale), mainEntity: c.faq.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) },
    { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: locale === "tr" ? "Ana sayfa" : "Home", item: absoluteUrl(pathFor(locale, "home")) }, { "@type": "ListItem", position: 2, name: c.title, item: pageUrl }] },
  ];
  return <SiteShell locale={locale} alternateHref={pathFor(locale === "tr" ? "en" : "tr", "workstation")} languageHrefs={{ tr: pathFor("tr", "workstation"), en: pathFor("en", "workstation"), de: pathFor("de", "workstation"), zh: pathFor("zh", "workstation") }}>
    {schema.length > 0 && <SchemaScript data={schema} />}
    <section className="workstation-hero"><div className="container workstation-hero-grid"><div><span className="eyebrow"><i />{c.eyebrow}</span><h1>{c.title}</h1><p>{c.intro}</p><div className="workstation-badges">{c.badges.map((badge) => <span key={badge}>✓ {badge}</span>)}</div><div className="product-hero-actions"><a className="primary-button workstation-launch-button" href="#workstation-app"><b aria-hidden="true">⌘</b><span>{c.cta}</span><i aria-hidden="true">→</i></a><Link className="secondary-button product-cross-link" href={pathFor(locale, "agent")}><span>{locale === "tr" ? "Önce Ajanla planla" : locale === "de" ? "Zuerst mit Agent planen" : locale === "zh" ? "先用助手规划" : "Plan with Agent first"}</span><i aria-hidden="true">✦</i></Link></div></div><div className="workstation-hero-visual" aria-hidden="true"><span className="hero-node n1">JSON</span><span className="hero-node n2">MASK</span><span className="hero-node n3">CSV</span><i className="hero-wire w1" /><i className="hero-wire w2" /><b>BQ<br /><small>IDE</small></b></div></div></section>
    <section className="section workstation-explain"><div className="container"><div className="section-heading split-heading"><div><span className="kicker">BYTEQUANT WORKSTATION</span><h2>{c.sectionTitle}</h2></div><p>{c.sectionIntro}</p></div><div className="workstation-guide-callout"><span aria-hidden="true">⌘</span><p>{c.guideNote}</p><a href="#workstation-app">{c.guideAction} ↓</a></div><ol className="workstation-feature-grid">{c.cards.map((card, index) => <li id={`step-${index + 1}`} key={card[0]}><span>{card[0]}</span><h3>{card[1]}</h3><p>{card[2]}</p></li>)}</ol></div></section>
    <section id="workstation-app" className="workstation-app-section"><div className="container workstation-app-container"><WorkstationLoader locale={locale} /></div></section>
    <section className="section workstation-boundaries"><div className="container workstation-boundary-grid"><div><span className="kicker">TRUST BOUNDARY</span><h2>{c.boundariesTitle}</h2><p>{c.intro}</p><Link className="text-link" href={pathFor(locale, "privacy")}>{locale === "tr" ? "Gizlilik politikasını inceleyin" : locale === "de" ? "Datenschutz lesen" : locale === "zh" ? "阅读隐私政策" : "Read the privacy policy"} →</Link></div><ol>{c.boundaries.map((boundary, index) => <li key={boundary}><span>{String(index + 1).padStart(2, "0")}</span><p>{boundary}</p></li>)}</ol></div></section>
    <section className="section faq-section"><div className="container faq-layout"><div><span className="kicker">FAQ</span><h2>{locale === "tr" ? "İş istasyonu hakkında" : locale === "de" ? "Über die Workstation" : locale === "zh" ? "关于工作站" : "About Workstation"}</h2><p>{c.sectionIntro}</p></div><div className="faq-list">{c.faq.map(([question, answer], index) => <details key={question} open={index === 0}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></div></section>
    <section className="cta-band"><div className="container"><div><span>{siteUrl.replace("https://", "").toUpperCase()} · LOCAL-FIRST</span><h2>{c.title}</h2></div><a className="light-button" href="#workstation-app">{c.cta} →</a></div></section>
  </SiteShell>;
}
